[Queues] Add local development notes
cloudflare/cloudflare-docs pull request #10039
Opened 2023-07-25 14:32 UTC by kewbish

This PR adds some notes about the required Wrangler / Node versions for developing with Queues locally. It was modeled off the [D1 local dev](https://developers.cloudflare.com/d1/learning/local-development/) guide.

Some Discord users were confused because Wrangler doesn't currently support developing with separate producer / consumer Workers and a local Queue, so I've also added an aside to highlight that.

2023-07-25 14:41 UTC, CharlieBurnett requested changes

2023-07-25 14:41 UTC, CharlieBurnett commented on content/queues/learning/local-development.md
> +If you prefer to develop with separate producer and consumer Workers, pass in the `--remote` flag when calling `wrangler dev`. Note that using `--remote` will access and modify the messages in your p
We have a bug that exists today that prevents remote queue dev work from working properly. We probably shouldnt be suggesting this to users as it will break. We should instead caution them against it as this is a known issue

2023-07-26 10:03 UTC, Maddy-Cloudflare requested changes
Will review this again once Charlie's comment has been addressed.

2023-07-26 10:03 UTC, Maddy-Cloudflare commented on content/queues/learning/local-development.md
> +Queues supports local development workflows using [Wrangler](/workers/wrangler/install-and-update/), the command-line interface for Workers. Wrangler runs the same version of Queues as Cloudflare run
```suggestion
Queues support local development workflows using [Wrangler](/workers/wrangler/install-and-update/), the command-line interface for Workers. Wrangler runs the same version of Queues as Cloudflare runs globally.
```

2023-07-26 10:03 UTC, Maddy-Cloudflare commented on content/queues/learning/local-development.md
> +## Requirements
```suggestion
## Prerequisites 
```

2023-07-26 10:03 UTC, Maddy-Cloudflare commented on content/queues/learning/local-development.md
> +To develop locally with Queues, you must use [Wrangler v3.1.0](https://blog.cloudflare.com/wrangler3/) or later. Refer to [Install/Update Wrangler](https://developers.cloudflare.com/workers/wrangler/
```suggestion
To develop locally with Queues, you will need:
- [Wrangler v3.1.0](https://blog.cloudflare.com/wrangler3/) or later. 
```

2023-07-26 10:03 UTC, Maddy-Cloudflare commented on content/queues/learning/local-development.md
> +Developing locally with Queues also requires a Node.js version of `18.0.0` or later. Consider using a Node version manager like [Volta](https://volta.sh/) or [nvm](https://github.com/nvm-sh/nvm) to a
```suggestion
- Node.js version of `18.0.0` or later. Consider using a Node version manager like [Volta](https://volta.sh/) or [nvm](https://github.com/nvm-sh/nvm) to avoid permission issues and change Node versions.
```

2023-07-26 10:03 UTC, Maddy-Cloudflare commented on content/queues/learning/local-development.md
> +Users new to Queues and/or Cloudflare Workers should visit the [Queues tutorial](/queues/get-started/) to install `wrangler` and deploy their first Queue.
```suggestion
- If you are new to Queues and/or Cloudflare Workers, refer to the [Queues tutorial](/queues/get-started/) to install `wrangler` and deploy their first Queue.
```

2023-07-26 10:03 UTC, Maddy-Cloudflare commented on content/queues/learning/local-development.md
> +
```suggestion
## Start a local development session
```

2023-07-26 10:03 UTC, Maddy-Cloudflare commented on content/queues/learning/local-development.md
> +To start a local development session:
```suggestion
Open your terminal and run the following commands to start a local development session:
```

2023-07-26 10:03 UTC, Maddy-Cloudflare commented on content/queues/learning/local-development.md
> +Local development sessions create a standalone, local-only environment that mirrors the production environment Queues runs in so that you can test your Workers _before_ you deploy to production.
```suggestion
Local development sessions create a standalone, local-only environment that mirrors the production environment Queues runs in so you can test your Workers _before_ you deploy to production.
```

2023-07-26 16:19 UTC, kewbish commented
Removed the note about using remote development - I think the users on Discord were reporting that developing *in production* remotely worked.

Thank you for your edits!

2023-07-26 16:28 UTC, Maddy-Cloudflare approved these changes

2023-07-26 16:34 UTC, kewbish commented
(Please also merge, thank you!)

2023-07-27 07:56 UTC, Maddy-Cloudflare commented
@CharlieBurnett  is this okay to merge?

2023-07-27 16:08 UTC, CharlieBurnett approved these changes

2023-07-27 16:09 UTC, CharlieBurnett commented
@Maddy-Cloudflare @kewbish  lgtm! Lets merge

2023-07-27 16:24 UTC, merged