Revamp metadata information
cloudflare/cloudflare-docs pull request #10101
Opened 2023-07-28 14:59 UTC by markdembo

- Remove not-working metadata.json example
- Rename section from multipart to metadata as multipart uploads are the new default of the Getting started guide
- Add new metadata.json with exhaustive bindings examples
- Link to relevant resources in other parts of the documentation

2023-07-28 15:12 UTC, Maddy-Cloudflare requested changes

2023-07-28 15:12 UTC, Maddy-Cloudflare commented on content/cloudflare-for-platforms/workers-for-platforms/platform/metadata.md
> +title: User Worker Metadata
```suggestion
title: User Worker metadata
```

2023-07-28 15:12 UTC, Maddy-Cloudflare commented on content/cloudflare-for-platforms/workers-for-platforms/platform/metadata.md
> +# User Worker Metadata
```suggestion
# User Worker metadata
```

2023-07-28 15:12 UTC, Maddy-Cloudflare commented on content/cloudflare-for-platforms/workers-for-platforms/platform/metadata.md
> +As part of the [multipart upload of user Workers](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/get-started/configuration/#4-upload-user-workers-to-a-namespace), yo
```suggestion
You define the Worker's metadata as part of the [multipart upload of user Workers](/workers-for-platforms/get-started/configuration/#4-upload-user-workers-to-a-namespace). This metadata defines the Workers'configuration analogue to the [wrangler.toml file](/workers/wrangler/configuration/) for regular Workers.
```

2023-07-28 15:12 UTC, Maddy-Cloudflare commented on content/cloudflare-for-platforms/workers-for-platforms/platform/metadata.md
> +
Would be nice to describe the meaning of a key here, @markdembo

2023-07-28 15:12 UTC, Maddy-Cloudflare commented on content/cloudflare-for-platforms/workers-for-platforms/platform/metadata.md
> +  - The path to the module entrypoint of the user Worker that will be executed. For example: `main.js`.
```suggestion
  - The path to the module entry point of the user Worker that will be executed. For example, `main.js`.
```

2023-07-28 15:33 UTC, markdembo commented on content/cloudflare-for-platforms/workers-for-platforms/platform/metadata.md
> +
@Maddy-Cloudflare I reworked this a bit. Attribute is the standard term for json files.

2023-07-28 15:41 UTC, Maddy-Cloudflare approved these changes

2023-07-28 15:41 UTC, Maddy-Cloudflare commented on content/cloudflare-for-platforms/workers-for-platforms/platform/metadata.md
> +The following attributues are configurable at the top-level.
```suggestion
The following attributes are configurable at the top-level.
```

2023-07-28 15:41 UTC, Maddy-Cloudflare commented on content/cloudflare-for-platforms/workers-for-platforms/platform/metadata.md
> +Analogue to regular Workers, user Workers can also interact with other Cloudflare resources using Bindings. See [metadata.json example](#sample-metadata.json) and the [Wrangler configuration document
```suggestion
Analogue to regular Workers, user Workers can also interact with other Cloudflare resources using Bindings. Refer to [metadata.json example](#sample-metadata.json) and the [Wrangler configuration documentation](/workers/wrangler/configuration/#bindings) for more information.
```

2023-07-28 16:18 UTC, Maddy-Cloudflare approved these changes
Fixing broken link

2023-07-28 16:18 UTC, Maddy-Cloudflare commented on content/cloudflare-for-platforms/workers-for-platforms/platform/metadata.md
> +You define the Worker's metadata as part of the [multipart upload of user Workers](/workers-for-platforms/get-started/configuration/#4-upload-user-workers-to-a-namespace). This metadata defines the W
```suggestion
You define the Worker's metadata as part of the [multipart upload of user Workers](/cloudflare-for-platforms/workers-for-platforms/get-started/configuration/#4-upload-user-workers-to-a-namespace). This metadata defines the Workers'configuration analogue to the [wrangler.toml file](/workers/wrangler/configuration/) for regular Workers.
```

2023-07-31 13:05 UTC, Maddy-Cloudflare approved these changes

2023-07-31 14:43 UTC, merged