Create Blazor how-to
cloudflare/cloudflare-docs pull request #1022
Opened 2021-03-29 01:22 UTC by lerichardson

2021-06-30 18:25 UTC, kristianfreeman requested changes

2021-06-30 18:25 UTC, kristianfreeman commented on products/pages/src/content/how-to/deploy-a-blazor-site.md
> +| Build command        | `curl -sSL https://dot.net/v1/dotnet-install.sh > dotnet-install.sh; chmod +x dotnet-install.sh; ./dotnet-install.sh -c 5.0 -InstallDir ./dotnet5; ./dotnet5/dotnet --version;
Could this be moved into a shell script or command of some kind? This will break our table rendering in the docs

2021-06-30 18:40 UTC, lerichardson commented on products/pages/src/content/how-to/deploy-a-blazor-site.md
> +| Build command        | `curl -sSL https://dot.net/v1/dotnet-install.sh > dotnet-install.sh; chmod +x dotnet-install.sh; ./dotnet-install.sh -c 5.0 -InstallDir ./dotnet5; ./dotnet5/dotnet --version;
Is there some Cloudflare-based place I can upload a shell script? I feel like people wouldn't be too comfortable making the script's location "githubusercontent.com" or something.

2021-06-30 18:59 UTC, signalnerve commented on products/pages/src/content/how-to/deploy-a-blazor-site.md
> +| Build command        | `curl -sSL https://dot.net/v1/dotnet-install.sh > dotnet-install.sh; chmod +x dotnet-install.sh; ./dotnet-install.sh -c 5.0 -InstallDir ./dotnet5; ./dotnet5/dotnet --version;
in this case, I was thinking that the tutorial could suggest some sort of build script that the user should add to their repo, e.g.

```bash
curl -sSL https://dot.net/v1/dotnet-install.sh > dotnet-install.sh
chmod +x dotnet-install.sh
./dotnet-install.sh -c 5.0 -InstallDir ./dotnet5
./dotnet5/dotnet --version
./dotnet5/dotnet publish -c Release -o output
```

then the user could do `chmod +x build.sh`, commit it to their github repo, and the build command in the Pages UI would just be `sh build.sh` - what do you think?

2021-06-30 19:17 UTC, lerichardson commented on products/pages/src/content/how-to/deploy-a-blazor-site.md
> +| Build command        | `curl -sSL https://dot.net/v1/dotnet-install.sh > dotnet-install.sh; chmod +x dotnet-install.sh; ./dotnet-install.sh -c 5.0 -InstallDir ./dotnet5; ./dotnet5/dotnet --version;
Sounds good. I'm making a commit right now.

2021-06-30 19:33 UTC, lerichardson commented
There are now instructions for creating build.sh. I also added some missing `git` commands, like `git init` and `git commit`

2021-06-30 19:52 UTC, signalnerve requested changes
This is so awesome!! Just a few comments and also - can you move this into the new Framework Guides folder that we've added since you opened this PR? Filename should be `products/pages/src/content/framework-guides/deploy-a-blazor-site.md`

2021-06-30 19:52 UTC, signalnerve commented on products/pages/src/content/how-to/deploy-a-blazor-site.md
> +Congrats, you've deployed your Blazor site on Cloudflare Pages! To learn more about what you can do with the platform, [check out our How-To section](/how-to).
```suggestion
Congrats, you've deployed your Blazor site on Cloudflare Pages! To learn more about what you can do with the platform, [check out our Framework Guides section](/framework-guides).
```

2021-06-30 19:52 UTC, signalnerve commented on products/pages/src/content/how-to/deploy-a-blazor-site.md
> +## Install .NET
Can you add newlines between all of these so the raw markdown is easier to read?

2021-06-30 19:52 UTC, signalnerve commented on products/pages/src/content/how-to/deploy-a-blazor-site.md
> +| Build command        | `./build.sh` |
Sorry, it's picky, but can you run this through a markdown table formatter (I like https://marketplace.visualstudio.com/items?itemName=yzhang.markdown-all-in-one) to make sure these table columns line up in Markdown?

2021-07-08 15:21 UTC, deadlypants1973 commented on products/pages/src/content/how-to/deploy-a-blazor-site.md
> +There are two types of Blazor projects, Blazor Server applications, which run on the server, and Blazor WASM (WebAssembly), which run in the browser. Since Blazor Server is not static, we'll be using
```suggestion
There are two types of Blazor projects, Blazor Server applications, which run on the server, and Blazor WASM (WebAssembly), which run in the browser. Since Blazor Server is not static, this guide will use Blazor WASM. Create a new Blazor WASM application by running:
```

2021-07-08 15:21 UTC, deadlypants1973 commented on products/pages/src/content/how-to/deploy-a-blazor-site.md
> +Create a new GitHub repository by visiting [repo.new](https://repo.new). Once you've created a new repository, you can prepare and push your local application to GitHub:
```suggestion
Create a new GitHub repository by visiting [repo.new](https://repo.new). After creating a new repository, prepare and push your local application to GitHub:
```

2021-07-08 15:21 UTC, deadlypants1973 commented on products/pages/src/content/how-to/deploy-a-blazor-site.md
> +Once you've configured your site, you can begin your first deploy. You should see Cloudflare Pages installing `dotnet`, your project dependencies, and building your site, before deploying it.
```suggestion
After configuring your site, you can begin your first deploy. You should see Cloudflare Pages installing `dotnet`, your project dependencies, and building your site, before deploying it.
```

2021-07-08 15:21 UTC, deadlypants1973 commented on products/pages/src/content/how-to/deploy-a-blazor-site.md
> +For the complete guide to deploying your first site to Cloudflare Pages, check out [our Getting Started guide](/getting-started).
```suggestion
For the complete guide to deploying your first site to Cloudflare Pages, refer to the [Getting Started guide](/getting-started).
```

2021-07-08 15:21 UTC, deadlypants1973 commented on products/pages/src/content/how-to/deploy-a-blazor-site.md
> +Once you've deployed your site, you'll receive a unique subdomain for your project on `pages.dev`.
```suggestion
After deploying your site, you will receive a unique subdomain for your project on `pages.dev`. 
```

2021-07-08 15:21 UTC, deadlypants1973 commented on products/pages/src/content/how-to/deploy-a-blazor-site.md
> +Every time you commit new code to your Blazor site, Cloudflare Pages will automatically rebuild your project and deploy it. You'll also get access to [preview deployments](/platform/preview-deploymen
```suggestion
Every time you commit new code to your Blazor site, Cloudflare Pages will automatically rebuild your project and deploy it. You will also get access to [preview deployments](/platform/preview-deployments) on new pull requests, so you can preview how changes look to your site before deploying them to production.
```

2021-07-08 16:57 UTC, deadlypants1973 commented on products/pages/src/content/how-to/deploy-a-blazor-site.md
> +## Install .NET
```suggestion
# Deploy a Blazor Site  
  
[Blazor](https://blazor.net) is an SPA framework that can use C# code, rather then JavaScript in the browser. In this guide, you will build a site using Blazor, and deploy it using Cloudflare Pages.  

## Install .NET
```

2021-07-08 16:57 UTC, deadlypants1973 commented on products/pages/src/content/how-to/deploy-a-blazor-site.md
> +| Build command        | `./build.sh` |
```suggestion

Blazor uses C#, so you will need to [install the .NET SDK](https://dotnet.microsoft.com/download) by grabbing the newest installation from the [.NET downloads page](https://dotnet.microsoft.com/download) and download and running the installer.  

## Creating a new Blazor WASM project  

There are two types of Blazor projects, Blazor Server applications, which run on the server, and Blazor WASM (WebAssembly), which run in the browser. Since Blazor Server is not static, we'll be using Blazor WASM. Create a new Blazor WASM application by running:

```sh
$ dotnet new blazorwasm my-blazor-project
```  
When you have completed your application, make sure to run  
```sh
$ dotnet publish
```
## Creating the build script

To deploy, Cloudflare Pages will need a way to build the Blazor project. In the project's directory root, create a `build.sh` file. Populate it with this:

```sh
#!/bin/sh
curl -sSL https://dot.net/v1/dotnet-install.sh > dotnet-install.sh
chmod +x dotnet-install.sh
./dotnet-install.sh -c 5.0 -InstallDir ./dotnet5
./dotnet5/dotnet --version
./dotnet5/dotnet publish -c Release -o output
```
Then, make the file executable by running:

```sh
chmod +x build.sh
```
## Creating a GitHub repository

Create a new GitHub repository by visiting [repo.new](https://repo.new). Once you've created a new repository, you can prepare and push your local application to GitHub:

```sh
$ dotnet new gitignore
$ git init
$ git add -A
$ git commit -m "Initial commit"
$ git remote add origin https://github.com/yourgithubusername/githubrepo.git
$ git branch -M main
$ git push -u origin main
```
## Deploying with Cloudflare Pages

You can deploy your site to Cloudflare Pages by going to the dashboard, and creating a new site. Select your new GitHub repository that you created above, and in the configuration section, provide the following information:  
<TableLayout>
| Configuration option | Value          |
| -------------------- | -------------- |
| Production branch    | `main`         |
| Build command        | `./build.sh` |
```

2021-07-08 16:57 UTC, deadlypants1973 commented on products/pages/src/content/how-to/deploy-a-blazor-site.md
> +
```suggestion
## Deploying with Cloudflare Pages

You can deploy your site to Cloudflare Pages by going to the dashboard, and creating a new site. Select your new GitHub repository that you created above, and in the configuration section, provide the following information:  
<TableLayout>
| Configuration option | Value                |
| -------------------- | -------------------- |
| Production branch    | `main`               |
| Build command        | `./build.sh`         |
| Build directory      | `output/wwwroot`     |
</TableLayout>
After configuring your site, you can begin your first deploy. You should see Cloudflare Pages installing `dotnet`, your project dependencies, and building your site, before deploying it.

<Aside>

For the complete guide to deploying your first site to Cloudflare Pages, refer to the [Getting Started guide](/getting-started).

</Aside>

After deploying your site, you will receive a unique subdomain for your project on `pages.dev`. 

Every time you commit new code to your Blazor site, Cloudflare Pages will automatically rebuild your project and deploy it. You will also get access to [preview deployments](/platform/preview-deployments) on new pull requests, so you can preview how changes look to your site before deploying them to production.

```

2021-07-08 16:57 UTC, deadlypants1973 commented on products/pages/src/content/how-to/deploy-a-blazor-site.md
> +## Install .NET
```suggestion
# Deploy a Blazor Site  
  
[Blazor](https://blazor.net) is an SPA framework that can use C# code, rather than JavaScript in the browser. In this guide, you will build a site using Blazor, and deploy it using Cloudflare Pages.  

## Install .NET
```

2021-07-08 16:57 UTC, deadlypants1973 commented on products/pages/src/content/how-to/deploy-a-blazor-site.md
> +
```suggestion
## Deploying with Cloudflare Pages

You can deploy your site to Cloudflare Pages by going to the dashboard, and creating a new site. Select your new GitHub repository that you created above, and in the configuration section, provide the following information:  
<TableLayout>
| Configuration option | Value          |
| -------------------- | -------------- |
| Production branch    | `main`         |
| Build command        | `./build.sh` |
| Build directory      | `output/wwwroot`       |
</TableLayout>
After configuring your site, you can begin your first deploy. You should see Cloudflare Pages installing `dotnet`, your project dependencies, and building your site, before deploying it.

<Aside>

For the complete guide to deploying your first site to Cloudflare Pages, refer to the [Getting Started guide](/getting-started).

</Aside>

After deploying your site, you will receive a unique subdomain for your project on `pages.dev`. 
Every time you commit new code to your Blazor site, Cloudflare Pages will automatically rebuild your project and deploy it. You will also get access to [preview deployments](/platform/preview-deployments) on new pull requests, so you can preview how changes look to your site before deploying them to production.

```

2021-07-08 16:57 UTC, deadlypants1973 commented on products/pages/src/content/how-to/deploy-a-blazor-site.md
> +```
```suggestion
## Creating the build script

To deploy, Cloudflare Pages will need a way to build the Blazor project. In the project's directory root, create a `build.sh` file. Populate the file with this:
```sh
#!/bin/sh
curl -sSL https://dot.net/v1/dotnet-install.sh > dotnet-install.sh
chmod +x dotnet-install.sh
./dotnet-install.sh -c 5.0 -InstallDir ./dotnet5
./dotnet5/dotnet --version
./dotnet5/dotnet publish -c Release -o output
```
Then, make the file executable by running:
```sh
chmod +x build.sh
```
```

2021-07-08 16:57 UTC, deadlypants1973 commented on products/pages/src/content/how-to/deploy-a-blazor-site.md
> +```
```suggestion

Blazor uses C#, so you will need to [install the .NET SDK](https://dotnet.microsoft.com/download) by grabbing the newest installation from the [.NET downloads page](https://dotnet.microsoft.com/download) and download and running the installer.  

## Creating a new Blazor WASM project  

There are two types of Blazor projects, Blazor Server applications, which run on the server, and Blazor WASM (WebAssembly), which run in the browser. Since Blazor Server is not static, this guide will use Blazor WASM. Create a new Blazor WASM application by running:
```sh
$ dotnet new blazorwasm my-blazor-project
```  
When you have completed your application, make sure to run:
```sh
$ dotnet publish
```
```

2021-07-08 17:00 UTC, deadlypants1973 commented on products/pages/src/content/how-to/deploy-a-blazor-site.md
> +
```suggestion
## Creating a new Blazor WASM project  

There are two types of Blazor projects, Blazor Server applications, which run on the server, and Blazor WASM (WebAssembly), which run in the browser. Since Blazor Server is not static, this guide will use Blazor WASM. Create a new Blazor WASM application by running:
```sh
$ dotnet new blazorwasm my-blazor-project
```

## Creating the build script

To deploy, Cloudflare Pages will need a way to build the Blazor project. In the project's directory root, create a `build.sh` file. Populate the file with this:
```sh
#!/bin/sh
curl -sSL https://dot.net/v1/dotnet-install.sh > dotnet-install.sh
chmod +x dotnet-install.sh
./dotnet-install.sh -c 5.0 -InstallDir ./dotnet5
./dotnet5/dotnet --version
./dotnet5/dotnet publish -c Release -o output
```

## Creating a GitHub repository

```

2021-07-08 17:02 UTC, deadlypants1973 commented on products/pages/src/content/how-to/deploy-a-blazor-site.md
> +
```suggestion
## Creating a new Blazor WASM project  

There are two types of Blazor projects, Blazor Server applications, which run on the server, and Blazor WASM (WebAssembly), which run in the browser. Since Blazor Server is not static, this guide will use Blazor WASM. Create a new Blazor WASM application by running:
```sh
$ dotnet new blazorwasm my-blazor-project
```

## Creating the build script

To deploy, Cloudflare Pages will need a way to build the Blazor project. In the project's directory root, create a `build.sh` file. Populate the file with this:

```sh
#!/bin/sh
curl -sSL https://dot.net/v1/dotnet-install.sh > dotnet-install.sh
chmod +x dotnet-install.sh
./dotnet-install.sh -c 5.0 -InstallDir ./dotnet5
./dotnet5/dotnet --version
./dotnet5/dotnet publish -c Release -o output
```

## Creating a GitHub repository

```

2021-07-08 17:03 UTC, deadlypants1973 commented on products/pages/src/content/how-to/deploy-a-blazor-site.md
> +
```suggestion
```

```

2021-07-08 17:05 UTC, deadlypants1973 commented on products/pages/src/content/how-to/deploy-a-blazor-site.md
> +After configuring your site, you can begin your first deploy. You should see Cloudflare Pages installing `dotnet`, your project dependencies, and building your site, before deploying it.
```suggestion
## Deploying with Cloudflare Pages

You can deploy your site to Cloudflare Pages by going to the dashboard, and creating a new site. Select your new GitHub repository that you created above, and in the configuration section, provide the following information:  

<TableLayout>
| Configuration option | Value          |
| -------------------- | -------------- |
| Production branch    | `main`         |
| Build command        | `./build.sh` |
| Build directory      | `output/wwwroot`       |
</TableLayout>

After configuring your site, you can begin your first deploy. You should see Cloudflare Pages installing `dotnet`, your project dependencies, and building your site, before deploying it.
```

2021-07-08 17:06 UTC, deadlypants1973 commented on products/pages/src/content/how-to/deploy-a-blazor-site.md
> +You can deploy your site to Cloudflare Pages by going to the dashboard, and creating a new site. Select your new GitHub repository that you created above, and in the configuration section, provide th
```suggestion
Blazor uses C#, so you will need to [install the .NET SDK](https://dotnet.microsoft.com/download) by grabbing the newest installation from the [.NET downloads page](https://dotnet.microsoft.com/download) and download and running the installer.  

## Creating a new Blazor WASM project  

There are two types of Blazor projects, Blazor Server applications, which run on the server, and Blazor WASM (WebAssembly), which run in the browser. Since Blazor Server is not static, this guide will use Blazor WASM. Create a new Blazor WASM application by running:

```sh
$ dotnet new blazorwasm my-blazor-project
```

## Creating the build script

To deploy, Cloudflare Pages will need a way to build the Blazor project. In the project's directory root, create a `build.sh` file. Populate the file with this:

```sh
#!/bin/sh
curl -sSL https://dot.net/v1/dotnet-install.sh > dotnet-install.sh
chmod +x dotnet-install.sh
./dotnet-install.sh -c 5.0 -InstallDir ./dotnet5
./dotnet5/dotnet --version
./dotnet5/dotnet publish -c Release -o output
```

## Creating a GitHub repository

Create a new GitHub repository by visiting [repo.new](https://repo.new). After creating a new repository, prepare and push your local application to GitHub:

```sh
$ dotnet new gitignore
$ git init
$ git add -A
$ git commit -m "Initial commit"
$ git remote add origin https://github.com/yourgithubusername/githubrepo.git
$ git branch -M main
$ git push -u origin main
```

## Deploying with Cloudflare Pages

You can deploy your site to Cloudflare Pages by going to the dashboard, and creating a new site. Select your new GitHub repository that you created above, and in the configuration section, provide the following information:  
```

2021-07-08 17:07 UTC, deadlypants1973 commented on products/pages/src/content/how-to/deploy-a-blazor-site.md
> +You have successfully deployed your Blazor site on Cloudflare Pages. To learn more about what you can do with the platform, [refer to the Framework Guides section](/framework-guides).
```suggestion
# Deploy a Blazor Site  
  
[Blazor](https://blazor.net) is an SPA framework that can use C# code, rather than JavaScript in the browser. In this guide, you will build a site using Blazor, and deploy it using Cloudflare Pages.  

## Install .NET

Blazor uses C#, so you will need to [install the .NET SDK](https://dotnet.microsoft.com/download) by grabbing the newest installation from the [.NET downloads page](https://dotnet.microsoft.com/download) and download and running the installer.  

## Creating a new Blazor WASM project  

There are two types of Blazor projects, Blazor Server applications, which run on the server, and Blazor WASM (WebAssembly), which run in the browser. Since Blazor Server is not static, this guide will use Blazor WASM. Create a new Blazor WASM application by running:

```sh
$ dotnet new blazorwasm my-blazor-project
```

## Creating the build script

To deploy, Cloudflare Pages will need a way to build the Blazor project. In the project's directory root, create a `build.sh` file. Populate the file with this:

```sh
#!/bin/sh
curl -sSL https://dot.net/v1/dotnet-install.sh > dotnet-install.sh
chmod +x dotnet-install.sh
./dotnet-install.sh -c 5.0 -InstallDir ./dotnet5
./dotnet5/dotnet --version
./dotnet5/dotnet publish -c Release -o output
```

## Creating a GitHub repository

Create a new GitHub repository by visiting [repo.new](https://repo.new). After creating a new repository, prepare and push your local application to GitHub:

```sh
$ dotnet new gitignore
$ git init
$ git add -A
$ git commit -m "Initial commit"
$ git remote add origin https://github.com/yourgithubusername/githubrepo.git
$ git branch -M main
$ git push -u origin main
```

## Deploying with Cloudflare Pages

You can deploy your site to Cloudflare Pages by going to the dashboard, and creating a new site. Select your new GitHub repository that you created above, and in the configuration section, provide the following information:  

<TableLayout>
| Configuration option | Value          |
| -------------------- | -------------- |
| Production branch    | `main`         |
| Build command        | `./build.sh` |
| Build directory      | `output/wwwroot`       |
</TableLayout>

After configuring your site, you can begin your first deploy. You should see Cloudflare Pages installing `dotnet`, your project dependencies, and building your site, before deploying it.

<Aside>

For the complete guide to deploying your first site to Cloudflare Pages, refer to the [Getting Started guide](/getting-started).

</Aside>

After deploying your site, you will receive a unique subdomain for your project on `pages.dev`. 
Every time you commit new code to your Blazor site, Cloudflare Pages will automatically rebuild your project and deploy it. You will also get access to [preview deployments](/platform/preview-deployments) on new pull requests, so you can preview how changes look to your site before deploying them to production.

## Learn more

You have successfully deployed your Blazor site on Cloudflare Pages. To learn more about what you can do with the platform, [refer to the Framework Guides section](/framework-guides).
```

2021-07-08 17:08 UTC, deadlypants1973 approved these changes

2021-07-08 17:09 UTC, deadlypants1973 commented on products/pages/src/content/how-to/deploy-a-blazor-site.md
> +## Creating the build script
Can't make suggestions without formatting being messed up but

line 14 needs to be ``` to close the code block, then a line space before "##Creating"

2021-07-08 17:10 UTC, deadlypants1973 commented on products/pages/src/content/how-to/deploy-a-blazor-site.md
> +## Creating a GitHub repository
Line 24 needs to be ``` to close the code block then line 25 needs to be an empty line before "## Creating..."

2021-07-08 17:13 UTC, deadlypants1973 requested changes
Tried to do edits myself in the Github UI but for some reason getting errors. @lerichardson thank you for this! Can you please add the markdown edits and code block backticks in the comments I indicated so we can merge this? :)

2021-07-08 17:14 UTC, lerichardson commented
Yes. I'll get to this as soon as I can!

2021-07-16 19:35 UTC, lerichardson commented
I believe I fixed all of the issues, let me know what I missed

2021-07-19 13:42 UTC, deadlypants1973 approved these changes

2021-07-19 15:44 UTC, signalnerve commented
thanks! @lerichardson do you have a repo i can test with?

2021-07-19 15:48 UTC, lerichardson commented
Yes, just use the repo I forked https://github.com/lerichardson/cloudflare-docs

2021-07-19 16:00 UTC, signalnerve commented
> Yes, just use the repo I forked https://github.com/lerichardson/cloudflare-docs

ah, i mean a blazor example project :)

2021-07-19 16:11 UTC, lerichardson commented
Oh! Here: https://github.com/lerichardson/blazor-test

2021-07-19 16:26 UTC, signalnerve approved these changes

2021-07-19 16:26 UTC, merged