Specify HC retention period
cloudflare/cloudflare-docs pull request #10272
Opened 2023-08-08 14:19 UTC by cicku

2023-08-10 11:17 UTC, victor-perov requested changes
Could we please rename that field and put appropriate title to avoid confusion?

2023-08-10 11:17 UTC, victor-perov commented on data/plans.json
>            "title": "Analytics",
If the idea to show how far back in time each plan can request data, then title is misleading. I would use something like "Maximum time range" or something

2023-08-10 15:35 UTC, cicku commented on data/plans.json
>            "title": "Analytics",
@angelampcosta Need your opinion on how we manage the comparison here. If you are ok with the title then I will do it.

2023-08-11 08:25 UTC, angelampcosta commented on data/plans.json
>            "title": "Analytics",
Sounds good to me. We can go with Viktor's suggestion.

2023-09-04 13:44 UTC, angelampcosta approved these changes

2023-09-29 13:33 UTC, angelampcosta commented
Hi @victor-perov The PR was updated. Could you please review? Thanks!

2023-11-06 17:09 UTC, victor-perov commented
@angelampcosta @cicku 

Thanks for pinging me on this ticket.

What should we do in this case with lines 2626-2633 of the same config? Where we do use "analytics" as availability for LoadBalancing analytics.

In my understanding you're trying to update/alter meaning of the object attributed without updating all use-cases of it.

2023-11-06 17:12 UTC, victor-perov requested changes
I think we should either get a linked PR / issue to get the same applied (see my comment above) for LB Analytics or change it as part of this PR too.

2023-11-06 17:15 UTC, closed without merging