Deansundquist cloudflared ports and ips us region
cloudflare/cloudflare-docs pull request #10308
Opened 2023-08-10 00:08 UTC by deansundquist

The Ports and IP page for Cloudflared doesn't address the hosts that are used if the region is set to US.

2023-08-10 00:11 UTC, abelinkinbio approved these changes

2023-08-10 01:53 UTC, DevinCarr requested changes

2023-08-10 01:53 UTC, DevinCarr commented on content/cloudflare-one/connections/connect-networks/install-and-setup/ports-and-ips.md
> +| `us-region1.v2.argotunnel.com` | 7844 | TCP/UDP (`h2mux`, `http2`, and `quic`) |
Can we remove h2mux from both of these, it is no longer supported.

2023-08-10 14:11 UTC, ranbel commented on content/cloudflare-one/connections/connect-networks/install-and-setup/ports-and-ips.md
> +| `us-region1.v2.argotunnel.com` | 7844 | TCP/UDP (`h2mux`, `http2`, and `quic`) |
Is `h2mux` still supported for `region1.v2.argotunnel.com` and `region2.v2.argotunnel.com`?

2023-08-10 14:33 UTC, abelinkinbio commented on content/cloudflare-one/connections/connect-networks/install-and-setup/ports-and-ips.md
> +| `us-region1.v2.argotunnel.com` | 7844 | TCP/UDP (`h2mux`, `http2`, and `quic`) |
Good call. We should remove there as well.

2023-08-10 15:01 UTC, DevinCarr commented on content/cloudflare-one/connections/connect-networks/install-and-setup/ports-and-ips.md
> +| `us-region1.v2.argotunnel.com` | 7844 | TCP/UDP (`h2mux`, `http2`, and `quic`) |
`h2mux` is no longer supported, we can remove it.

2023-08-10 19:05 UTC, deansundquist commented on content/cloudflare-one/connections/connect-networks/install-and-setup/ports-and-ips.md
> +| `us-region2.v2.argotunnel.com` | 7844 | TCP/UDP (`http2`/`quic`) |
@DevinCarr done.

2023-08-10 20:58 UTC, DevinCarr approved these changes

2023-08-11 17:11 UTC, ranbel approved these changes

2023-08-11 17:23 UTC, merged