Update deploy-a-jekyll-site.md for JEKYLL_ENV environment variable
cloudflare/cloudflare-docs pull request #1033
Opened 2021-03-30 07:36 UTC by dotZak

`JEKYLL_ENV` can be set in two ways: as an environment variable, or as part of the build command. Since the build command is generic to both the _Production_ and _Preview_ environments, an environment variable should be used.

`JEKYLL_ENV` is important to the build process and must be set to `production` for certain features to work properly in Jekyll plugins and themes (the default is `development`, per [Jekyll's documentation on environments](https://jekyllrb.com/docs/configuration/environments/)), so the documentation for Cloudflare Pages should specify how to set it.

I've followed the formatting of the section above it as it is relevant. This should be placed in the documentation as close to the _Build configuration_ section, and should be place before _first deploy_ section so that it's in the order of operations of the setup process.

2021-05-14 22:02 UTC, rita3ko requested changes
Thanks for the PR @dotZak ! Left a minor syntax comment for improvement.  -Rita

2021-05-14 22:02 UTC, rita3ko commented on products/pages/src/content/how-to/deploy-a-jekyll-site.md
> +
`then provide the following information` -> `then add the following environment variable`

2021-05-26 17:01 UTC, dotZak commented
@rita3ko Thanks for the feedback. I've updated the commit with the requested update.

2021-05-26 17:01 UTC, dotZak commented on products/pages/src/content/how-to/deploy-a-jekyll-site.md
> +
This has been addressed.

2021-05-26 17:08 UTC, signalnerve approved these changes

2021-07-13 18:21 UTC, signalnerve commented
@dotZak can you rebase this PR so we can merge it? thanks!

2021-07-14 17:38 UTC, signalnerve commented
@dotZak it looks like the rebase here got a little messed up, do you mind opening a new PR and basing it off of our `production` branch? thanks!

2021-08-04 16:53 UTC, closed without merging