[Turnstile] Update remoteip param information
cloudflare/cloudflare-docs pull request #10614
Opened 2023-09-08 10:07 UTC by AleksandarHr

There was a slight mismatch in the information about the repoteip parameter of Turnstile. This commit clarifies the current usage of the parameter.

2023-09-08 13:58 UTC, punkeel commented on data/changelogs/turnstile.yaml
> +    - Updated remoteip parameter information to clarify it's current usage.
I don't think it's worth a changelog entry (and if so, `its`)

2023-09-08 14:38 UTC, kodster28 commented on data/changelogs/turnstile.yaml
> +    - Updated remoteip parameter information to clarify it's current usage.
I'd agree. Should generally not be adding changelog entries for documentation updates.

2023-09-10 17:29 UTC, migueldemoura commented on content/turnstile/get-started/server-side-validation.md
> +**NOTE:** We currently do not strictly validate against remote IP.
Thoughts on this (replace the previous line too)? 

```suggestion
The `remoteip` parameter helps preventing abuse by ensuring the current visitor is the one who received the token. Note that this is currently not strictly validated.
```

2023-09-11 22:32 UTC, patriciasantaana commented on data/changelogs/turnstile.yaml
> +    - Updated remoteip parameter information to clarify it's current usage.
```suggestion
```

2023-09-11 22:34 UTC, patriciasantaana commented on content/turnstile/get-started/server-side-validation.md
>  {{</Aside>}}
```suggestion
{{<Aside type="note">}}
Remote IP helps prevent abuses by ensuring that the current visitor is the one who received the token. The `remoteip` parameter helps preventing abuse by ensuring the current visitor is the one who received the token. Note that this is currently not strictly validated.
{{</Aside>}}
```

2023-09-11 22:38 UTC, patriciasantaana approved these changes

2023-09-12 15:20 UTC, migueldemoura requested changes

2023-09-12 15:20 UTC, migueldemoura commented on content/turnstile/get-started/server-side-validation.md
> +Remote IP helps prevent abuses by ensuring that the current visitor is the one who received the token. The `remoteip` parameter helps to prevent abuse by ensuring the current visitor is the one who r
```suggestion
The `remoteip` parameter helps to prevent abuse by ensuring the current visitor is the one who received the token. This is currently not strictly validated.
```

2023-09-12 15:39 UTC, migueldemoura approved these changes

2023-09-12 15:45 UTC, migueldemoura approved these changes

2023-09-12 16:09 UTC, merged