Clarify PubSub get started guide to have appropriate information to successfully work
cloudflare/cloudflare-docs pull request #10624
Opened 2023-09-08 20:17 UTC by CharlieBurnett

Added step in token creation to give proper permissions to access membership API

Added step exporting env variables so code snippet below works properly

Removed query param where a second token is generated, given the example only needs one

Changed the sh block for the token generation script to console to resolve text block treating # as a comment

2023-09-08 20:19 UTC, CharlieBurnett commented
@Maddy-Cloudflare @elithrar if either of you know how to properly escape a # character inside a ```sh block, lmk. I tried a \,`,# #, ##, and ` `, none of which had the desired effect. 

My solution was to change the block to a ```console so the full text could be copied. This affects documentation formatting slightly to the trained eye,  but is otherwise completely workable

2023-09-08 21:38 UTC, elithrar requested changes

2023-09-08 21:38 UTC, elithrar commented on content/pub-sub/guide.md
> +7. Select **Add More**  below the newly created permission. Choose **User**, select **Memberships** from the first drop-down, and **Edit** as the permission.
Can you explain why this is necessary / why it didn't work without this?

2023-09-08 21:38 UTC, elithrar commented on content/pub-sub/guide.md
> +#Tip: If you want these to persist across boots, store the below variables in your `.zshrc`, `.bashrc`, or `.profile` files in your home folder
```suggestion
```

We generally want to avoid users from storing secrets persistently in config. Since this is a private beta, it's OK for these to be temporary.

2023-09-08 21:38 UTC, elithrar commented on content/pub-sub/guide.md
> +$ export BROKER_NAME="TheBrokerYouCreated"
It's likely better to have each of these done _before_ the `wrangler ...` command that uses that name, or immediately after, so they are in context.

2023-09-08 21:38 UTC, elithrar commented on content/pub-sub/guide.md
> +  //username: "Your username",
I'd suggest just making this non-optional: don't make users decide during a tutorial.

2023-09-08 21:58 UTC, CharlieBurnett commented on content/pub-sub/guide.md
> +7. Select **Add More**  below the newly created permission. Choose **User**, select **Memberships** from the first drop-down, and **Edit** as the permission.
Attempting to create a namespace with a token lacking these credentials fails with a 10000 authorization error for the API

This is something that I experience when working through the docs as is and has also been experienced by devs in discord doing this same

2023-09-08 22:03 UTC, CharlieBurnett commented on content/pub-sub/guide.md
> +$ export BROKER_NAME="TheBrokerYouCreated"
That's correct. 

The only time these env variables are used is in the command following this commit, with the exception of the CLOUDFLARE_API_TOKEN. Which is first exported above, but also is included below.

 I have repeated the API_TOKEN in this list for clarity, but am happy to remove that line if we feel it improves the reading experience

2023-09-08 22:08 UTC, CharlieBurnett commented on content/pub-sub/guide.md
> +  //username: "Your username",
The reason these lines exist is specifically because of that `mqtt.js` silent auth failure bug we talked about yesterday. 

I added them in as comments to help anyone who might have trouble logging in, but if the bug is fixed then there's no need for them. Thought it would be a nice temporary measure. 

My preference would be removing these lines if we feel like that doesn't make sense.

2023-09-11 14:58 UTC, dcpena reviewed
Left a few suggestions to align with our style guide.

2023-09-11 14:58 UTC, dcpena commented on content/pub-sub/guide.md
> +8. Click **Continue to Summary** at the bottom of the page, where you should see _All accounts - Pub/Sub:Edit_ as the permission
```suggestion
8. Select **Continue to Summary** at the bottom of the page, where you should see _All accounts - Pub/Sub:Edit_ as the permission.
```

2023-09-11 14:58 UTC, dcpena commented on content/pub-sub/guide.md
> +9. Click **Create Token**, and copy the token value.
```suggestion
9. Select **Create Token** and copy the token value.
```

2023-09-11 14:58 UTC, dcpena commented on content/pub-sub/guide.md
> +7. Select **Add More**  below the newly created permission. Choose **User**, select **Memberships** from the first drop-down, and **Edit** as the permission.
```suggestion
7. Select **Add More** below the newly created permission. Choose **User** > **Memberships** from the first dropdown and **Edit** as the permission.
```

2023-09-13 19:00 UTC, CharlieBurnett commented on content/pub-sub/guide.md
> +8. Click **Continue to Summary** at the bottom of the page, where you should see _All accounts - Pub/Sub:Edit_ as the permission
@Maddy-Cloudflare why do we "click" some places and "select" others? What's the standard practice for this?
Note that "click" is the way the docs were previously written. I have no preference, just want to understand which goes where

2023-09-13 19:11 UTC, dcpena commented on content/pub-sub/guide.md
> +8. Click **Continue to Summary** at the bottom of the page, where you should see _All accounts - Pub/Sub:Edit_ as the permission
Hi there, Charlie! Figured I'd respond while it's outside of working hours for Maddy. When the docs were originally written, the PCX team hadn't yet revisited guidance on Select vs Click. Select was the chosen option as it's device agnostic.

To avoid having that one step look completely different from the rest of the procedure, we can keep Click and just make note of revisiting the "Click" options to update them with Select at a later time.

2023-09-13 19:42 UTC, CharlieBurnett commented on content/pub-sub/guide.md
> +8. Click **Continue to Summary** at the bottom of the page, where you should see _All accounts - Pub/Sub:Edit_ as the permission
Thanks @dcpena makes perfect sense. I'll get a commit going changing that language for the next PR

2023-09-13 20:39 UTC, elithrar commented on content/pub-sub/guide.md
> +  //username: "Your username",
I'd strongly recommend simplifying it. Reduce the choices a user has to make when starting out. "If that doesn't work, try again" is neither a) guaranteed to work and b) leads users to ask "why not just make that the default?"

2023-09-13 21:18 UTC, CharlieBurnett commented on content/pub-sub/guide.md
> +  //username: "Your username",
Good call. Will remove

2023-09-14 14:37 UTC, elithrar approved these changes

2023-09-14 15:02 UTC, merged

2023-09-14 15:05 UTC, dcpena approved these changes