durable-objects: use-kv-from-durable-objects.md
cloudflare/cloudflare-docs pull request #10672
Opened 2023-09-13 14:11 UTC by elithrar

This PR shows how to use KV within Durable Objects.

2023-09-13 15:20 UTC, Maddy-Cloudflare requested changes
Will need to review this again.

2023-09-13 15:20 UTC, Maddy-Cloudflare commented on content/durable-objects/examples/use-kv-from-durable-objects.md
> +summary: Read & write to/from KV within a Durable Object
```suggestion
summary: Read and write to/from KV within a Durable Object
```

2023-09-13 15:20 UTC, Maddy-Cloudflare commented on content/durable-objects/examples/use-kv-from-durable-objects.md
> +The following Worker script shows how to configure a [Durable Object](/durable-objects/) to read from and/or write to a [Workers KV namespace](/workers/learning/how-kv-works/). This is useful when us
```suggestion
The following Worker script shows you how to configure a [Durable Object](/durable-objects/) to read from and/or write to a [Workers KV namespace](/workers/learning/how-kv-works/). This is useful when using a Durable Object to coordinate between multiple clients, and allows you to serialize writes to KV and/or broadcast a single read from KV to hundreds or thousands of clients connected to a single Durable Object [using WebSockets](/durable-objects/api/hibernatable-websockets-api/).
```

2023-09-13 15:20 UTC, Maddy-Cloudflare commented on content/durable-objects/examples/use-kv-from-durable-objects.md
> +The example requires:
```suggestion
Prerequisites:
```

2023-09-13 15:20 UTC, Maddy-Cloudflare commented on content/durable-objects/examples/use-kv-from-durable-objects.md
> +* That you have [created a KV namespace](/workers/runtime-apis/kv/) via the Cloudflare dashboard or the [wrangler CLI](/workers/wrangler/install-and-update/)
```suggestion
* A [KV namespace](/workers/runtime-apis/kv/) created via the Cloudflare dashboard or the [wrangler CLI](/workers/wrangler/install-and-update/).
```

2023-09-13 15:20 UTC, Maddy-Cloudflare commented on content/durable-objects/examples/use-kv-from-durable-objects.md
> +* You have [configured a binding](/workers/runtime-apis/kv/#kv-bindings) for the `kv_namespace` in the Cloudflare dashboard or `wrangler.toml`
```suggestion
* A [configured binding](/workers/runtime-apis/kv/#kv-bindings) for the `kv_namespace` in the Cloudflare dashboard or `wrangler.toml` file.
```

2023-09-13 15:20 UTC, Maddy-Cloudflare commented on content/durable-objects/examples/use-kv-from-durable-objects.md
> +* A [Durable Object namespace binding](/workers/wrangler/configuration/#durable-objects) is also configured.
```suggestion
* A configured [Durable Object namespace binding](/workers/wrangler/configuration/#durable-objects).
```

2023-09-13 15:20 UTC, Maddy-Cloudflare commented on content/durable-objects/examples/use-kv-from-durable-objects.md
> +The Worker script creates (or retrieves an existing) Durable Object stub based on a user ID, reads a key from KV, writes a key to KV, and return sa
```suggestion
```

2023-09-13 15:20 UTC, Maddy-Cloudflare commented on content/durable-objects/examples/use-kv-from-durable-objects.md
> +The example Worker script above assumes a `wrangler.toml` as follows:
```suggestion
```

2023-09-13 15:20 UTC, Maddy-Cloudflare commented on content/durable-objects/examples/use-kv-from-durable-objects.md
> +
```suggestion
Configure your `wrangler.toml` file as follows:

```toml
---
filename: wrangler.toml
---
name = "my-worker"

kv_namespaces = [
  { binding = "YOUR_KV_NAMESPACE", id = "<id_of_your_namespace>" }
]

[durable_objects]
bindings = [
  { name = "YOUR_DO_CLASS", class_name = "YourDurableObject" }
```
```

2023-09-13 15:20 UTC, Maddy-Cloudflare commented on content/durable-objects/examples/use-kv-from-durable-objects.md
> +```toml
```suggestion
```

2023-09-13 15:20 UTC, Maddy-Cloudflare commented on content/durable-objects/examples/use-kv-from-durable-objects.md
> +---
```suggestion
```

2023-09-13 15:20 UTC, Maddy-Cloudflare commented on content/durable-objects/examples/use-kv-from-durable-objects.md
> +filename: wrangler.toml
```suggestion
```

2023-09-13 15:20 UTC, Maddy-Cloudflare commented on content/durable-objects/examples/use-kv-from-durable-objects.md
> +---
```suggestion
```

2023-09-13 15:20 UTC, Maddy-Cloudflare commented on content/durable-objects/examples/use-kv-from-durable-objects.md
> +name = "my-worker"
```suggestion
```

2023-09-13 15:20 UTC, Maddy-Cloudflare commented on content/durable-objects/examples/use-kv-from-durable-objects.md
> +
```suggestion
```

2023-09-13 15:20 UTC, Maddy-Cloudflare commented on content/durable-objects/examples/use-kv-from-durable-objects.md
> +kv_namespaces = [
```suggestion
```

2023-09-13 15:20 UTC, Maddy-Cloudflare commented on content/durable-objects/examples/use-kv-from-durable-objects.md
> +  { binding = "YOUR_KV_NAMESPACE", id = "<id_of_your_namespace>" }
```suggestion
```

2023-09-13 15:20 UTC, Maddy-Cloudflare commented on content/durable-objects/examples/use-kv-from-durable-objects.md
> +]
```suggestion
```

2023-09-13 15:20 UTC, Maddy-Cloudflare commented on content/durable-objects/examples/use-kv-from-durable-objects.md
> +
```suggestion
```

2023-09-13 15:20 UTC, Maddy-Cloudflare commented on content/durable-objects/examples/use-kv-from-durable-objects.md
> +[durable_objects]
```suggestion
```

2023-09-13 15:20 UTC, Maddy-Cloudflare commented on content/durable-objects/examples/use-kv-from-durable-objects.md
> +bindings = [
```suggestion
```

2023-09-13 15:20 UTC, Maddy-Cloudflare commented on content/durable-objects/examples/use-kv-from-durable-objects.md
> +  { name = "YOUR_DO_CLASS", class_name = "YourDurableObject" }
```suggestion
```

2023-09-13 15:20 UTC, Maddy-Cloudflare commented on content/durable-objects/examples/use-kv-from-durable-objects.md
> +]
```suggestion
```

2023-09-13 15:20 UTC, Maddy-Cloudflare commented on content/durable-objects/examples/use-kv-from-durable-objects.md
> +```
```suggestion
```

2023-09-13 15:20 UTC, Maddy-Cloudflare commented on content/durable-objects/examples/use-kv-from-durable-objects.md
> +```ts
```suggestion
The following Worker script creates or retrieves an existing Durable Object stub based on a user ID, reads a key from KV, writes a key to KV, and returns sa:

```ts
```

2023-09-13 15:20 UTC, Maddy-Cloudflare commented on content/durable-objects/examples/use-kv-from-durable-objects.md
> +The example Worker script above assumes a `wrangler.toml` as follows:
Moving this `wrangler.toml` file configuration **_before_** the Worker script.

2023-09-13 15:20 UTC, Maddy-Cloudflare commented on content/durable-objects/examples/use-kv-from-durable-objects.md
> +```ts
What is "sa"?

2023-09-13 15:28 UTC, elithrar commented on content/durable-objects/examples/use-kv-from-durable-objects.md
> +The example Worker script above assumes a `wrangler.toml` as follows:
I intentionally put it after so that it doesn't distract from the _code_ itself, which is the most important thing.

2023-09-13 15:36 UTC, Maddy-Cloudflare commented on content/durable-objects/examples/use-kv-from-durable-objects.md
> +The example Worker script above assumes a `wrangler.toml` as follows:
I see what you mean, but the user will have to make sure that the `wrangler.toml` is configured correctly, before they can write the Worker script.

2023-09-14 11:40 UTC, KianNH commented on content/durable-objects/examples/use-kv-from-durable-objects.md
> +  async fetch(req: Request, env: Environment): Promise<Response> {
```suggestion
  async fetch(req: Request, env: Env): Promise<Response> {
```

Or the interface could be changed to `Environment` & the type changed on L72

2023-09-14 12:23 UTC, KianNH commented on content/durable-objects/examples/use-kv-from-durable-objects.md
> +```ts
````suggestion
  { name = "YOUR_DO_CLASS", class_name = "YourDurableObject" }
```

```ts
````

2023-09-14 14:02 UTC, Maddy-Cloudflare approved these changes

2023-09-14 14:02 UTC, Maddy-Cloudflare commented on content/durable-objects/examples/use-kv-from-durable-objects.md
> +* A configured [Durable Object namespace binding](/workers/wrangler/configuration/#durable-objects).
```suggestion
* A [Durable Object namespace binding](/workers/wrangler/configuration/#durable-objects).
```

2023-09-14 16:47 UTC, merged