Added language to pages docs to explain caveat on custom domains
cloudflare/cloudflare-docs pull request #1068
Opened 2021-04-06 10:35 UTC by anthonygrimes

Hi,

I have read [Contributing](https://github.com/cloudflare/.github/blob/master/CONTRIBUTING.md) and don't feel this PR requires an issue as noted in the document.

### Issue:
I recently migrated my Github pages website to Cloudflare Pages and ran into an issue with custom domains failing to resolve on subdomains. I later learned it was because I didn't first associate the subdomain in the Cloudflare Pages dashboard. Reading the docs, I don't feel this is clearly obvious to the end user. Additionally, if a user only configures a CNAME (e.g. www -> xxx.pages.dev) without association in the Cloudflare Pages dashboard, the query will hang for ~15 seconds and either present a 522 error or, Cloudflare domain config depending, will return the naked domain without the www. prefix.

### Summary of change:
I have added language to the pages.dev getting started document which explains that all domains you wish to resolve to your Cloudflare Pages site **must** be added in your Cloudflare Pages dashboard also.

2021-05-14 22:08 UTC, rita3ko requested changes

2021-05-14 22:08 UTC, rita3ko commented on products/pages/src/content/getting-started/index.md
> +Please note that any custom domains (or subdomains) you wish to resolve to your Cloudflare Pages site need to be added via the previous "Set up a domain" process. Manually adding a custom CNAME recor
This comment should go under the `#### Add a custom CNAME record` section. 

Slight nit in wording:
```
Please note that any custom domains (or subdomains) you wish to resolve to your Cloudflare Pages site need to be added via the previous "Set up a domain" process.
``` 
->
```
To ensure a custom domain is added successfully, you must go through the "Set up a custom domain" process described above".
```

2021-05-15 17:49 UTC, anthonygrimes commented on products/pages/src/content/getting-started/index.md
> +Please note that any custom domains (or subdomains) you wish to resolve to your Cloudflare Pages site need to be added via the previous "Set up a domain" process. Manually adding a custom CNAME recor
Thanks for the feedback @rita3ko, I've made the changes!

2021-05-17 16:35 UTC, signalnerve commented on products/pages/src/content/getting-started/index.md
> +To ensure a custom domain is added successfully, you must go through the "Set up a custom domain" process described above". Manually adding a custom CNAME record pointing to your Cloudflare Pages sit
```suggestion
To ensure a custom domain is added successfully, you must go through the "Set up a custom domain" process described above. Manually adding a custom CNAME record pointing to your Cloudflare Pages site - without first associating the domain (or subdomains) in the Cloudflare Pages dashboard - will result in your domain failing to resolve at the CNAME record address, and display a 522 error.
```

2021-07-07 17:44 UTC, signalnerve approved these changes

2021-07-07 17:45 UTC, signalnerve commented
sorry for the delay in reviewing this, it looks great! can you resolve the merge conflict?

2021-07-08 15:27 UTC, deadlypants1973 commented on products/pages/src/content/getting-started/index.md
> +To ensure a custom domain is added successfully, you must go through the "Set up a custom domain" process described above. Manually adding a custom CNAME record pointing to your Cloudflare Pages site
```suggestion
To ensure a custom domain is added successfully, you must go through the [Adding a custom domain](/getting-started#adding-a-custom-domain) process described above. Manually adding a custom CNAME record pointing to your Cloudflare Pages site - without first associating the domain (or subdomains) in the Cloudflare Pages dashboard - will result in your domain failing to resolve at the CNAME record address, and display a 522 error.
```

2021-07-08 16:34 UTC, anthonygrimes commented
> 
> 
> sorry for the delay in reviewing this, it looks great! can you resolve the merge conflict?

No worries at all! Have made the suggested changes and resolved the merge conflicts.

2021-07-09 13:10 UTC, deadlypants1973 approved these changes

2021-07-09 15:21 UTC, rita3ko requested changes

2021-07-09 15:21 UTC, rita3ko commented on products/pages/src/content/getting-started/index.md
> +To ensure a custom domain is added successfully, you must go through the [Adding a custom domain](/getting-started#adding-a-custom-domain) process described above. Manually adding a custom CNAME reco
Hey! Thanks for this PR. Could you wrap this in an <Aside>, and put it below the CNAME record, rather than above it? Then happy to merge.

2021-07-09 15:27 UTC, anthonygrimes commented on products/pages/src/content/getting-started/index.md
> +To ensure a custom domain is added successfully, you must go through the [Adding a custom domain](/getting-started#adding-a-custom-domain) process described above. Manually adding a custom CNAME reco
Hey, I've moved it under the CNAME block, but I'm not sure what you want me to wrap it in - the comment cuts off

2021-07-09 15:34 UTC, rita3ko commented on products/pages/src/content/getting-started/index.md
> +To ensure a custom domain is added successfully, you must go through the [Adding a custom domain](/getting-started#adding-a-custom-domain) process described above. Manually adding a custom CNAME reco
Oh, I didn't realize it had cut off. An `<Aside>` (https://developers.cloudflare.com/docs-engine/reference/markdown#asides)

2021-07-09 15:41 UTC, deadlypants1973 commented on products/pages/src/content/getting-started/index.md
> +To ensure a custom domain is added successfully, you must go through the [Adding a custom domain](/getting-started#adding-a-custom-domain) process described above. Manually adding a custom CNAME reco
```suggestion
<Aside>
To ensure a custom domain is added successfully, you must go through the [Adding a custom domain](/getting-started#adding-a-custom-domain) process described above. Manually adding a custom CNAME record pointing to your Cloudflare Pages site - without first associating the domain (or subdomains) in the Cloudflare Pages dashboard - will result in your domain failing to resolve at the CNAME record address, and display a [522 error](https://support.cloudflare.com/hc/en-us/articles/115003011431-Troubleshooting-Cloudflare-5XX-errors#522error).
</Aside>
```

2021-07-09 15:42 UTC, deadlypants1973 commented on products/pages/src/content/getting-started/index.md
> +To ensure a custom domain is added successfully, you must go through the [Adding a custom domain](/getting-started#adding-a-custom-domain) process described above. Manually adding a custom CNAME reco
Per @rita3ko 's suggestion

2021-07-13 08:16 UTC, anthonygrimes commented on products/pages/src/content/getting-started/index.md
> +To ensure a custom domain is added successfully, you must go through the [Adding a custom domain](/getting-started#adding-a-custom-domain) process described above. Manually adding a custom CNAME reco
Hi @rita3ko I have made these changes now. Thanks for the feedback!

2021-07-13 18:22 UTC, signalnerve commented
@rita3ko do you mind taking another look at this?

2021-07-15 18:50 UTC, rita3ko approved these changes

2021-07-15 18:54 UTC, merged