Add Momento integration
cloudflare/cloudflare-docs pull request #10739
Opened 2023-09-18 13:09 UTC by lauragift21

2023-09-19 13:09 UTC, kristianfreeman commented on content/workers/databases/native-integrations/momento.md
> +    export default {
think this should be reindented to the left

2023-09-19 13:09 UTC, kristianfreeman commented on content/workers/databases/native-integrations/momento.md
> +2. Create a cache called `worker`. You'll need to make sure that you choose the same region when generating a Momento API key in the next step.
does this have to be called `worker`?

2023-09-19 14:09 UTC, lauragift21 commented on content/workers/databases/native-integrations/momento.md
> +2. Create a cache called `worker`. You'll need to make sure that you choose the same region when generating a Momento API key in the next step.
No not really, I will change it

2023-09-25 15:21 UTC, deadlypants1973 requested changes

2023-09-25 15:21 UTC, deadlypants1973 commented on content/workers/databases/native-integrations/momento.md
> +2. Create a cache called `user-profiles`. You'll need to make sure that you choose the same region when generating a Momento API key in the next step.
```suggestion
2. Create a cache called `user-profiles`. You will need to make sure that you choose the same region when generating a Momento API key in the next step.
```

2023-09-25 15:21 UTC, deadlypants1973 commented on content/workers/databases/native-integrations/momento.md
> +2. Create a cache called `user-profiles`. You'll need to make sure that you choose the same region when generating a Momento API key in the next step.
Why are they creating this cache if in step one they already have one?

2023-09-25 16:20 UTC, lauragift21 commented on content/workers/databases/native-integrations/momento.md
> +2. Create a cache called `user-profiles`. You'll need to make sure that you choose the same region when generating a Momento API key in the next step.
Step 2 assumes they don't have a cache and is showing the steps to create one. I'll phrase it better.

2023-09-25 16:24 UTC, lauragift21 commented on content/workers/databases/native-integrations/momento.md
> +2. Create a cache called `user-profiles`. You will need to make sure that you choose the same region when generating a Momento API key in the next step.
```suggestion
2. To create a new cache, select create cache button and assign `user-profiles` as the cache name. You will need to make sure that you choose the same region when generating a Momento API key in the next step.
```

2023-09-25 16:24 UTC, lauragift21 commented on content/workers/databases/native-integrations/momento.md
> +2. Create a cache called `user-profiles`. You will need to make sure that you choose the same region when generating a Momento API key in the next step.
@deadlypants1973 does this work?

2023-09-26 15:33 UTC, deadlypants1973 approved these changes

2023-09-26 15:33 UTC, deadlypants1973 commented on content/workers/databases/native-integrations/momento.md
> +5. The following example code show how to set an item in your cache, get it, and return it as a JSON object. The credentials needed to connect to Momento Cache have been automatically added as secret
```suggestion
5. The following example code show how to set an item in your cache, get it, and return it as a JSON object. The credentials needed to connect to Momento Cache have been automatically added as [secrets](/workers/configuration/secrets/) to your Worker through the integration.
```

2023-09-26 15:34 UTC, deadlypants1973 commented on content/workers/databases/native-integrations/momento.md
> +5. The following example code show how to set an item in your cache, get it, and return it as a JSON object. The credentials needed to connect to Momento Cache have been automatically added as secret
Is the 'credentials needed' the API key in step 3? Because if so, let's say that. We didn't really connect how the API key is relevant to future steps in this doc.

2023-09-26 15:38 UTC, tanushreesharma-cf commented on content/workers/databases/native-integrations/momento.md
> +{{<render file="_database_integrations_definition.md">}}
```suggestion
{{<render file="_database_integrations_definition.md">}}
This integration allows you to connect to Momento from your Worker by getting Momento cache configuration and adding it as [secrets](https://1d791deb.cloudflare-docs-7ou.pages.dev/workers/configuration/environment-variables/) to your Worker.
```

2023-09-26 15:44 UTC, tanushreesharma-cf commented on content/workers/databases/native-integrations/momento.md
> +5. The following example code show how to set an item in your cache, get it, and return it as a JSON object. The credentials needed to connect to Momento Cache have been automatically added as secret
Shouldn't be. Doesn't the integration automatically create and pull in an API key?

2023-09-26 16:12 UTC, lauragift21 commented on content/workers/databases/native-integrations/momento.md
> +5. The following example code show how to set an item in your cache, get it, and return it as a JSON object. The credentials needed to connect to Momento Cache have been automatically added as secret
it does! my bad I wrote this out before I had access to the integration. Now I followed the flow from the dash, and indeed the API key will be created by default so there's no need for the user to create one first. I've now added the steps in step 3.

2023-09-26 16:17 UTC, deadlypants1973 approved these changes

2023-09-27 13:07 UTC, merged