Update CDN reference architecture doc
cloudflare/cloudflare-docs pull request #10746
Opened 2023-09-18 14:49 UTC by haleycode

2023-09-18 15:43 UTC, marciocloudflare commented on content/reference-architecture/cdn-reference-architecture.md
> +**1. DNS unicast routing**
Consider removing the `1.` and the `2.` from this and the `Anycast routing` below. Numbered steps usually refer to steps that have to be taken in sequence, and this isn't it.

2023-09-18 16:00 UTC, marciocloudflare requested changes

2023-09-18 16:00 UTC, marciocloudflare commented on content/reference-architecture/cdn-reference-architecture.md
> +* Cloudflare is a reverse proxy, meaning it receives requests from clients and proxies the requests back to the customer’s origin servers. Thus, every request traverses through Cloudflare’s network b
We don't use edge bc it's meaningless to customers. Edge should be replace with "Cloudflare global network". However, as this doc is filled with Edge, might be a task for another time?

2023-09-18 16:00 UTC, marciocloudflare commented on content/reference-architecture/cdn-reference-architecture.md
> +* The Cloudflare CDN leverages the Cloudflare global Anycast edge network. Thus the incoming request is routed to and answered by the node closest to the user (eyeball).
"eyeball" is another one we don't use and should be replaced with "end user"

2023-09-18 16:00 UTC, marciocloudflare commented on content/reference-architecture/cdn-reference-architecture.md
> +| **Request 1** | **Request 2** |
```suggestion
| Request 1 | Request 2 |
```

2023-09-18 16:00 UTC, marciocloudflare commented on content/reference-architecture/cdn-reference-architecture.md
> +| **Request 1** | **Request 2** |
You don't need bold, bc table titles are already bold

2023-09-18 16:00 UTC, marciocloudflare commented on content/reference-architecture/cdn-reference-architecture.md
> +The main difference between Smart Tiered Cache and Global tiered cache is the number of upper tiers that can talk to the origin servers. With Smart Tiered Cache the closest upper tier to the origin i
```suggestion
The main difference between Smart Tiered Cache and Global Tiered Cache is the number of upper tiers that can talk to the origin servers. With Smart Tiered Cache the closest upper tier to the origin is selected using Argo performance and routing data. This means that all requests that experience a cache miss at a lower tier will funnel through this single upper tier and have a higher percentage chance of a cache hit to avoid sending traffic to an origin server. However, the downside to this architecture is that the lower tier could be located across the globe from the upper tier. Even if the upper tier can fulfill the request from its cache, the distance between the upper tier and lower tier could still add latency to the response depending on the distance traveled. To summarize, Smart Tiered Cache ensures that all requests for cache flow through a single upper tier cache location which increases cache hit percentages, and reduces requests to the origin server, however it can result in higher latencies fulfilling those requests since the upper tier could be located far away from the lower tier that originated the request.
```

2023-09-18 16:00 UTC, marciocloudflare commented on content/reference-architecture/cdn-reference-architecture.md
> +The main difference between Smart Tiered Cache and Global tiered cache is the number of upper tiers that can talk to the origin servers. With Smart Tiered Cache the closest upper tier to the origin i
Changed to `Global Tiered Cache` bc `Smart Tiered Cache` was written in sentence case. Also changed all the `hit`s and `miss`es from all caps. We don't do all caps :)

2023-09-18 16:06 UTC, haleycode commented on content/reference-architecture/cdn-reference-architecture.md
> +The main difference between Smart Tiered Cache and Global tiered cache is the number of upper tiers that can talk to the origin servers. With Smart Tiered Cache the closest upper tier to the origin i
HIT and MISS are accurate, per the author: "They are capitalized because the http headers that return the result capitalize them. So it's how people see them if they look for them."

I'll keep that but fix the rest. Thank you!

2023-09-18 19:25 UTC, haleycode commented on content/reference-architecture/cdn-reference-architecture.md
> +* Cloudflare is a reverse proxy, meaning it receives requests from clients and proxies the requests back to the customer’s origin servers. Thus, every request traverses through Cloudflare’s network b
I'll make the updates where needed, thank you!

2023-09-20 13:04 UTC, marciocloudflare approved these changes

2023-09-20 13:04 UTC, marciocloudflare commented on content/reference-architecture/cdn-reference-architecture.md
> +The main difference between Smart Tiered Cache and Global tiered cache is the number of upper tiers that can talk to the origin servers. With Smart Tiered Cache the closest upper tier to the origin i
```suggestion
The main difference between Smart Tiered Cache and Global tiered cache is the number of upper tiers that can talk to the origin servers. With Smart Tiered Cache the closest upper tier to the origin is selected using Argo performance and routing data. This means that all requests that experience a cache `MISS` at a lower tier will funnel through this single upper tier and have a higher percentage chance of a cache `HIT` to avoid sending traffic to an origin server. However, the downside to this architecture is that the lower tier could be located across the globe from the upper tier. Even if the upper tier can fulfill the request from its cache, the distance between the upper tier and lower tier could still add latency to the response depending on the distance traveled. To summarize, Smart Tiered Cache ensures that all requests for cache flow through a single upper tier cache location which increases cache `HIT` percentages, and reduces requests to the origin server, however it can result in higher latencies fulfilling those requests since the upper tier could be located far away from the lower tier that originated the request.
```

2023-09-20 13:04 UTC, marciocloudflare commented on content/reference-architecture/cdn-reference-architecture.md
> +In Figure 5, Tiered Caching is enabled with Smart Tiered Cache Topology. The diagram depicts the topology of Smart Tiered Cache with Regional Tiered Cache enabled. Lower tier caches, when they experi
```suggestion
In Figure 5, Tiered Caching is enabled with Smart Tiered Cache Topology. The diagram depicts the topology of Smart Tiered Cache with Regional Tiered Cache enabled. Lower tier caches, when they experience a cache `MISS` will first send those requests to a more local, regional hub data center to see if the cache can handle the request. If not, the request will continue on to the upper tier and then origin server, if necessary.
```

2023-09-20 14:16 UTC, merged