Add Turso Integration
cloudflare/cloudflare-docs pull request #10744
Opened 2023-09-18 14:35 UTC by lauragift21

2023-09-25 15:08 UTC, deadlypants1973 requested changes

2023-09-25 15:08 UTC, deadlypants1973 commented on content/workers/databases/native-integrations/turso.md
> +[Turso](https://turso.tech/) is an edge-hosted, distributed database based on [libSQL](https://libsql.org/), an open-source fork of SQLite. It was designed to minimize query latency for applications
```suggestion
[Turso](https://turso.tech/) is an edge-hosted, distributed database based on [libSQL](https://libsql.org/), an open-source fork of SQLite. Turso was designed to minimize query latency for applications where queries comes from anywhere in the world.
```

2023-09-25 15:08 UTC, deadlypants1973 commented on content/workers/databases/native-integrations/turso.md
> +1. You need to install Turso CLI to create and populate a database, Use one of the following two commands in your terminal to install the Turso CLI:
```suggestion
1. You need to install Turso CLI to create and populate a database. Use one of the following two commands in your terminal to install the Turso CLI:
```

2023-09-25 15:08 UTC, deadlypants1973 commented on content/workers/databases/native-integrations/turso.md
> +  Next, Run the following command to make sure the Turso CLI is installed:
```suggestion
  Next, run the following command to make sure the Turso CLI is installed:
```

2023-09-25 15:08 UTC, deadlypants1973 commented on content/workers/databases/native-integrations/turso.md
> +  ✔  Success! Logged in as <your GitHub username>
```suggestion
  ✔  Success! Logged in as <YOUR_GITHUB_USERNAME>
```

2023-09-25 15:08 UTC, deadlypants1973 commented on content/workers/databases/native-integrations/turso.md
> +2. Before you create your first Turso database, you have to authenticate with your GitHub account with the command:
```suggestion
2. Before you create your first Turso database, you have to authenticate with your GitHub account by running:
```
Removing two 'with's

2023-09-25 15:08 UTC, deadlypants1973 commented on content/workers/databases/native-integrations/turso.md
> +  To learn more about Turso, refer to [Turso's official documentation](https://docs.turso.tech).
```suggestion
With your environment configured and your code ready, you can now test your Worker locally before you deploy.

To learn more about Turso, refer to [Turso's official documentation](https://docs.turso.tech).
```

2023-09-25 15:08 UTC, deadlypants1973 commented on content/workers/databases/native-integrations/turso.md
> +  - The libSQL client library import `@libsql/client/web` must be imported exactly as shown when working with Cloudflare workers. The non-web import will not work in the Workers environment.
```suggestion
  - The libSQL client library import `@libsql/client/web` must be imported exactly as shown when working with Cloudflare Workers. The non-web import will not work in the Workers environment.
```

2023-09-25 15:08 UTC, deadlypants1973 commented on content/workers/databases/native-integrations/turso.md
> +  - The `Env` interface contains the environment variable and secret you defined earlier.
This sentence needs a rewrite. The user did not define any environment variables, where were these? Secrets were automatically added, not defined, in step 6.

2023-09-25 16:12 UTC, lauragift21 commented on content/workers/databases/native-integrations/turso.md
> +  - The `Env` interface contains the environment variable and secret you defined earlier.
That's right, I will rephrase the sentence.

2023-09-26 15:41 UTC, deadlypants1973 approved these changes

2023-09-26 15:41 UTC, deadlypants1973 commented on content/workers/databases/native-integrations/turso.md
> +6. The following example shows how to make a query to your Turso database in a Worker. The credentials needed to connect to Turso have been automatically added as secrets to your Worker through the i
```suggestion
6. The following example shows how to make a query to your Turso database in a Worker. The credentials needed to connect to Turso have been automatically added as [secrets](/workers/configuration/secrets/) to your Worker through the integration.
```

2023-09-26 15:41 UTC, deadlypants1973 commented on content/workers/databases/native-integrations/turso.md
> +  - The `Env` interface contains the environment variable and secret defined when you added the Turso integration in step 4.
```suggestion
  - The `Env` interface contains the [environment variable](/workers/configuration/environment-variables/) and [secret](/workers/configuration/secrets/) defined when you added the Turso integration in step 4.
```

2023-09-26 15:42 UTC, deadlypants1973 approved these changes

2023-09-26 15:47 UTC, tanushreesharma-cf approved these changes

2023-09-28 12:35 UTC, merged