[SSL] Provide more guidance for AOP setup
cloudflare/cloudflare-docs pull request #10836
Opened 2023-09-22 16:56 UTC by RebeccaTamachiro

PCX-7901

2023-10-04 12:25 UTC, jason-cf commented
@RebeccaTamachiro I would make step 1 on both pages a partial because the information should be the same, but they are currently different.

2023-10-04 12:42 UTC, jason-cf requested changes
left comment in chat

2023-10-04 13:13 UTC, RebeccaTamachiro commented
> @RebeccaTamachiro I would make step 1 on both pages a partial because the information should be the same, but they are currently different.

Steps are different due to zone-level being possible to use either CF cert or custom, while per-hostname is only custom.

2023-10-10 13:59 UTC, jason-cf approved these changes

2023-10-10 14:30 UTC, merged