[WIP] [Workers] WebSocket docs
cloudflare/cloudflare-docs pull request #1086
Opened 2021-04-07 19:05 UTC by signalnerve

In-progress documentation for the `WebSocketPair` class

2021-04-08 17:11 UTC, Electroid requested changes
This is awesome! Left some comments

2021-04-08 17:11 UTC, Electroid commented on products/workers/src/content/learning/using-websockets.md
> +We're looking for developers to experiment with WebSockets support in Cloudflare Workers, but WebSocket support generally remains in early access. Details such as pricing and limits are not yet avail
I'd flip the sentence: early access and no pricing, then looking for developers. Also, where should we send them? Maybe a`#websockets` Discord channel?

2021-04-08 17:11 UTC, Electroid commented on products/workers/src/content/learning/using-websockets.md
> +WebSockets allow you to communicate in real-time with your Cloudflare Workers serverless functions. In this guide, you'll learn the basics of WebSockets on Cloudflare Workers, both from the perspecti
2-3 sentences to start with what are websockets? I found something [helpful](https://support.cloudflare.com/hc/en-us/articles/200169466-Using-Cloudflare-with-WebSockets#:~:text=Technical%20note-,Overview,without%20having%20to%20reestablish%20sessions.&text=WebSockets%20are%20often%20used%20for,as%20live%20chat%20and%20gaming.) from our own support website.

2021-04-08 17:11 UTC, Electroid commented on products/workers/src/content/learning/using-websockets.md
> +const websocket = new WebSocket("wss://example-websocket.signalnerve.workers.dev)
I would clarify this is code snippet for a web browser, not a Worker. Also, missing an end `"`.

2021-04-08 17:11 UTC, Electroid commented on products/workers/src/content/learning/using-websockets.md
> +  }
```suggestion
  if (upgradeHeader !== "websocket") {
    return new Response("Expected Upgrade: websocket", { status: 426 })
  }
```
Standard to return a `426` status code: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/426

2021-04-08 17:11 UTC, Electroid commented on products/workers/src/content/learning/using-websockets.md
> +  console.log(message.data)
What is the class of `message.data` here?

2021-04-08 17:11 UTC, Electroid commented on products/workers/src/content/learning/using-websockets.md
> +WebSockets are effectively stateless, meaning that they can't practically be used for full applications or anything that requires broader coordination of states between clients.
```suggestion
If your application needs to coordinate among multiple WebSocket connections, such as a chat room or game match, you'll need to create a Durable Object so clients send messages to a single-point-of-coordination. 
```

2021-04-08 17:11 UTC, Electroid commented on products/workers/src/content/runtime-apis/websockets.md
> +// { 0: <Websocket>, 1: <Websocket> }
```suggestion
// { 0: <WebSocket>, 1: <WebSocket> }
```

2021-04-08 17:11 UTC, Electroid commented on products/workers/src/content/runtime-apis/websockets.md
> +- <Code>close()</Code>
```suggestion
- <Code>close(code<ParamType>number</ParamType>, reason<ParamType>string</ParamType>)</Code>
```

2021-04-08 17:11 UTC, Electroid commented on products/workers/src/content/runtime-apis/websockets.md
> +- <Code>close()</Code>
Would also include a link to acceptable `WebSocket` termination codes: https://developer.mozilla.org/en-US/docs/Web/API/CloseEvent

2021-04-10 02:02 UTC, a-robinson reviewed
Thanks for writing this up!

2021-04-10 02:02 UTC, a-robinson commented on products/workers/src/content/learning/using-websockets.md
> +Details such as pricing and limits on Websockets are not yet available. We're looking for developers to experiment with WebSockets support in Cloudflare Workers, but WebSocket support generally remai
Minor inconsistent pluralization: "WebSockets support" vs "WebSocket support"

2021-04-10 02:02 UTC, a-robinson commented on products/workers/src/content/learning/using-websockets.md
> +WebSockets are open connections sustained between the client and the origin server. Inside a WebSockets connection, the client and the origin can pass data back and forth without having to reestablis
s/WebSocket**s** connection/WebSocket connection/ ?

2021-04-10 02:02 UTC, a-robinson commented on products/workers/src/content/learning/using-websockets.md
> +  if (!upgradeHeader || upgradeHeader !== "websocket") {
It's a little odd-looking to have the `!upgradeHeader` check here but not in the smaller version of this snippet above. It isn't needed, but whether you choose to keep it or not I'd expect this snippet and the one above to do the same thing.

2021-04-10 02:02 UTC, a-robinson commented on products/workers/src/content/learning/using-websockets.md
> +With your `client` Websocket returned back to the client, you now need to handle the `server` WebSocket. To begin receiving messages on your Workers function, call `accept` on the `server` WebSocket:
The ordering in which these things should be done isn't as clear as it could be, and it'd be nice if it was all put together at one point. For example, you presumably have to set up the server prior to returning, but this wording doesn't give that impression.

And below, do I have to call `server.accept()` before or after `server.addEventListener(...)`? Or does it not matter?

2021-04-10 02:02 UTC, a-robinson commented on products/workers/src/content/learning/using-websockets.md
> +Writing WebSocket clients that communicate with your Workers function is a two-step process: first, create the WebSocket instance, and then attach events to it, just like we did on the server:
s/attach events/attach event listeners/

2021-04-10 02:02 UTC, a-robinson commented on products/workers/src/content/learning/using-websockets.md
> +For an example of this in practice, see the [`websocket-template`](https://github.com/cloudflare/websocket-template) that we provide to get started with WebSockets.
It's likely intentional, but just in case it isn't that repo is still private.

2021-04-10 02:02 UTC, a-robinson commented on products/workers/src/content/learning/using-websockets.md
> +If your application needs to coordinate among multiple WebSocket connections, such as a chat room or game match, you'll need to create a Durable Object so clients send messages to a single-point-of-c
Can we link to https://developers.cloudflare.com/workers/learning/using-durable-objects from here?

2021-04-10 02:02 UTC, a-robinson commented on products/workers/src/content/learning/using-websockets.md
> +The solution to this is _Durable Objects_, our coordinated state tool for Cloudflare Workers, which is often used in parallel with WebSockets to effectively allow WebSockets to be re-instantiated wit
The first sentence here doesn't flow naturally at all from the previous paragraph -- they say roughly the same thing and the previous paragraph doesn't introduce a problem (as is implied by starting out with "The solution to this is ...")

2021-04-10 02:02 UTC, a-robinson commented on products/workers/src/content/learning/using-websockets.md
> +The solution to this is _Durable Objects_, our coordinated state tool for Cloudflare Workers, which is often used in parallel with WebSockets to effectively allow WebSockets to be re-instantiated wit
> to effectively allow WebSockets to be re-instantiated with persistent state over multiple clients and connections

What does it mean for WebSockets to be re-instantiated?

2021-04-10 02:02 UTC, a-robinson commented on products/workers/src/content/learning/using-websockets.md
> +If your application needs to coordinate among multiple WebSocket connections, such as a chat room or game match, you'll need to create a Durable Object so clients send messages to a single-point-of-c
Ah, I see you linked it in the next paragraph. Maybe you just forgot to remove/change this paragraph?

2021-04-10 02:02 UTC, a-robinson commented on products/workers/src/content/learning/using-websockets.md
> +## Writing a WebSocket Client
FWIW it seems weird to me that there's nothing on this page about how to send a message, only about how to receive them.

2021-04-10 02:02 UTC, a-robinson commented on products/workers/src/content/runtime-apis/websockets.md
> +let websocketPair = Object.values(new WebsocketPair())
I'm a little confused by this -- if you do this, how do you access the client and server objects? Are they at `websocketPair[0]` / `websocketPair[1]` or at `websocketPair.client` and `websocketPair.server`? If the former, then why even bother using `Object.values` here?

This looks like a mistake to me, like an amalgamation of the example above and the example below.

2021-04-10 02:02 UTC, a-robinson commented on products/workers/src/content/runtime-apis/websockets.md
> +## Events
Which of these events provide arguments to their `callbackFunction`? `message` was shown to provide one argument to the callback in the examples on the other page, but what about the others? I'd guess that `error` might, but then again there isn't a type documented for it below, so maybe not?

2021-04-10 02:02 UTC, a-robinson commented on products/workers/src/content/runtime-apis/websockets.md
> +- `type` <Type>string</Type> - Defaults to `message`.
I'm not sure I understand this... Does it mean that if I register:

```
websocket.addEventListener("message", message => {
  ...
}
```

...that `message.data` will contain whatever the other side passed in, and `message.type` will contain a string with the value "message"? In the example on the other page, though, the second log statement was just `console.log(message)`, not `console.log(message.data)`.

2021-04-12 15:34 UTC, signalnerve commented on products/workers/src/content/learning/using-websockets.md
> +  if (!upgradeHeader || upgradeHeader !== "websocket") {
great catch, added in other code snippet

2021-04-13 14:35 UTC, nihaals commented on products/workers/src/content/learning/using-websockets.md
> +const websocket = new WebSocket("wss://websocket-example.signalnerve.workers.dev)
```suggestion
const websocket = new WebSocket("wss://websocket-example.signalnerve.workers.dev")
```

2021-04-13 19:58 UTC, lukeed reviewed
Looking good!

2021-04-13 19:58 UTC, lukeed commented on products/workers/src/content/learning/using-websockets.md
> +The WebsocketPair returned from this constructor is an Object, with two WebSockets at keys `0` and `1`. It's common to grab the two WebSockets from this pair using `Object.values` and ES6 destructuri
```suggestion
An Object is returned from the `WebSocketPair` constructor, with the `0` and `1` keys each holding a WebSocket value. It's common to grab the two WebSockets from this pair using [`Object.values`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_objects/Object/values) and [ES6 destructuring](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment), as seen in the below example.
```

2021-04-13 19:58 UTC, lukeed commented on products/workers/src/content/learning/using-websockets.md
> +With your `client` Websocket returned back to the client, you now need to handle the `server` WebSocket. To begin receiving messages on your Workers function, call `accept` on the `server` WebSocket:
Agree with this. Should `server.accept()` be invoked immediately, or is there a point in time where it becomes safe to do so?

2021-04-13 19:58 UTC, lukeed commented on products/workers/src/content/learning/using-websockets.md
> +})
```suggestion
websocket.addEventListener("message", event => {
  console.log("Message received from server")
  console.log(event.data)
})
```

2021-04-13 19:58 UTC, lukeed commented on products/workers/src/content/runtime-apis/websockets.md
> +- `type` <Type>string</Type> - Defaults to `message`.
The client-side Websocket receives events with `{ type, data }`. I added a code suggestion in the appropriate place.

2021-04-13 22:22 UTC, lukeed commented on products/workers/src/content/learning/using-websockets.md
> +Once you've appropriately checked for the `Upgrade` header, you can create a new instance of WebSocketPair, which contains _server_ and _client_ WebSockets. One of these WebSockets should be handled
```suggestion
Once you've appropriately checked for the `Upgrade` header, you can create a new instance of `WebSocketPair`, which contains _server_ and _client_ WebSockets. One of these WebSockets should be handled by the Workers function (which we'll do shortly), and the other should be returned as part of a `Response` with status 101, indicating the "Switching protocols" response:
```

2021-04-13 22:22 UTC, lukeed commented on products/workers/src/content/learning/using-websockets.md
> +An Object is returned from the `WebSocketPair` constructor, with the `0` and `1` keys each holding a WebSocket value. It's common to grab the two WebSockets from this pair using [`Object.values`](htt
```suggestion
An Object is returned from the `WebSocketPair` constructor, with the `0` and `1` keys each holding a `WebSocket` instance as its value. It's common to grab the two WebSockets from this pair using [`Object.values`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_objects/Object/values) and [ES6 destructuring](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment), as seen in the below example.
```

2021-04-13 22:22 UTC, lukeed commented on products/workers/src/content/learning/using-websockets.md
> +  const client, server = webSocketPair[0], webSocketPair[1]
```suggestion
  const client = webSocketPair[0], server = webSocketPair[1]
```

2021-04-13 22:23 UTC, lukeed approved these changes
:shipit:

2021-04-13 22:25 UTC, merged