[Workers]: Update Jamstack Tutorial
cloudflare/cloudflare-docs pull request #11200
Opened 2023-10-10 11:29 UTC by lauragift21

2023-10-10 14:02 UTC, lauragift21 commented on content/workers/tutorials/build-a-jamstack-app/index.md
> +If you would like to see the finished code for this project, find the [project on GitHub](https://github.com/lauragift21/cloudflare-workers-todos) and refer to the [live demo](https://todos.signalner
```suggestion
If you would like to see the finished code for this project, find the [project on GitHub](https://github.com/lauragift21/cloudflare-workers-todos) and refer to the [live demo](https://todos.examples.workers.dev/) to review what you will be building.
```

2023-12-21 17:46 UTC, deadlypants1973 requested changes
Added some minor suggestions for style guide. This tutorials needs a peer technical review for the entirety of the tutorial from devrel. For things like code description accuracy, there are a few parts in the tutorial where 'fetch' is being addressed rather than the 'fetch' handler. These are two separate concepts and should be made distinct to avoid confusing users.

2023-12-21 17:46 UTC, deadlypants1973 commented on content/workers/tutorials/build-a-jamstack-app/index.md
> +1.  How building with Workers makes it seamless to focus on writing code and ship finished products.
```suggestion
1.  How building with Workers makes allows you to focus on writing code and ship finished products.
```

2023-12-21 17:46 UTC, deadlypants1973 commented on content/workers/tutorials/build-a-jamstack-app/index.md
> +First, use create-cloudflare CLI tool to create a new Cloudflare Workers project. In this tutorial, you will use the default `Hello World` template to create a Workers project.
```suggestion
First, use the [`create-cloudflare`](https://www.npmjs.com/package/create-cloudflare) CLI tool to create a new Cloudflare Workers project named `todos`. In this tutorial, you will use the default `Hello World` template to create a Workers project.
```

2023-12-21 17:46 UTC, deadlypants1973 commented on content/workers/tutorials/build-a-jamstack-app/index.md
> +Inside of your new todos Worker project directory, index.js represents the entry point to your Cloudflare Workers application.
```suggestion
Inside of your new `todos` Worker project directory, `index.js` represents the entry point to your Cloudflare Workers application.
```

2023-12-21 17:46 UTC, deadlypants1973 commented on content/workers/tutorials/build-a-jamstack-app/index.md
> +All Cloudflare Workers applications start by listening for `fetch` events, which are triggered when a client makes a request to a Workers route. After a request is received by the Worker, the respons
```suggestion
All incoming HTTP requests to a Worker are passed to the [`fetch()` handler](/workers/runtime-apis/handlers/fetch/) as a [request](/workers/runtime-apis/request/) object. After a request is received by the Worker, the response your application constructs will be returned to the user. This tutorial will guide you through understanding how the request/response pattern works and how you can use it to build fully featured applications.
```

2023-12-21 17:46 UTC, deadlypants1973 commented on content/workers/tutorials/build-a-jamstack-app/index.md
> +When a Worker receives a `fetch` event, the Worker returns the newly constructed response to the client. Your Worker will serve new responses directly from [Cloudflare's global network](https://www.c
```suggestion
When a Worker receives a `request`, the Worker returns the newly constructed response to the client. Your Worker will serve new responses directly from [Cloudflare's global network](https://www.cloudflare.com/network) instead of continuing to your origin server. A standard server would accept requests and return responses. Cloudflare Workers allows you to respond by constructing responses directly on the Cloudflare global network.
```

2023-12-21 17:46 UTC, deadlypants1973 commented on content/workers/tutorials/build-a-jamstack-app/index.md
> +## 2. What you'll build
```suggestion
## 2. Review project details
```

2023-12-21 17:46 UTC, deadlypants1973 commented on content/workers/tutorials/build-a-jamstack-app/index.md
> +Any project you publish to Cloudflare Workers can make use of modern JavaScript tooling like ES modules, `npm` packages, and [`async`/`await`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/
```suggestion
Any project you deploy to Cloudflare Workers can make use of modern JavaScript tooling like [ES modules](/workers/reference/migrate-to-module-workers/), `npm` packages, and [`async`/`await`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function) functions to build your application. In addition to writing Workers, you can use Workers to [build full applications](/workers/tutorials/build-a-slackbot/) using the same tooling and process as in this tutorial.
```

2023-12-21 17:46 UTC, deadlypants1973 commented on content/workers/tutorials/build-a-jamstack-app/index.md
> +In this tutorial, you will build a todo-list application running on Workers that allows reading data from KV store and using the data to populate an HTML response to send to the client.
```suggestion
In this tutorial, you will build a todo list application running on Workers that allows reading data from a [KV](/kv/) store and using the data to populate an HTML response to send to the client.
```

2023-12-21 17:46 UTC, deadlypants1973 commented on content/workers/tutorials/build-a-jamstack-app/index.md
> +## 3. Writing data to KV
```suggestion
## 3. Write data to KV
```

2023-12-21 17:46 UTC, deadlypants1973 commented on content/workers/tutorials/build-a-jamstack-app/index.md
> +To begin, you need to understand how to populate your todo list with actual data. To do this, use [Cloudflare Workers KV](/kv/) — a key-value store that you can access inside of your Worker script to
```suggestion
To begin, you need to understand how to populate your todo list with actual data. To do this, use [Cloudflare Workers KV](/kv/) — a key-value store that you can access inside of your Worker to read and write data.
```

2023-12-21 17:46 UTC, deadlypants1973 commented on content/workers/tutorials/build-a-jamstack-app/index.md
>  To get started with KV, set up a namespace. All of your cached data will be stored inside that namespace and, with configuration, you can access that namespace inside the script with a predefined var
```suggestion
To get started with KV, set up a namespace. All of your cached data will be stored inside that namespace and, with configuration, you can access that namespace inside the Worker with a predefined variable. Use Wrangler to create a new namespace with the [`kv:namespace create` command](/workers/wrangler/commands/#create-3) and get the associated namespace ID by running the following command in your terminal:
```

2023-12-21 17:46 UTC, deadlypants1973 commented on content/workers/tutorials/build-a-jamstack-app/index.md
> +## Rendering data from KV
```suggestion
## Render data from KV
```

2024-04-23 18:19 UTC, kodster28 commented
Going to close this out for now as there are conflicts in the underlying file + this hasn't seen any action in a few months.

Feel free to re-open on a new PR though, definitely would be good to see this tutorial updated.

2024-05-14 17:52 UTC, kodster28 commented
Howdy @lauragift21, you might want to start a new PR (the `changes requested` will block any approvals / merging).

2024-05-14 17:52 UTC, closed without merging