[Workers AI] Created pricing page for Workers AI
cloudflare/cloudflare-docs pull request #11236
Opened 2023-10-11 16:47 UTC by PedroBarreira

- Added a pricing page for Workers AI

2023-10-11 16:54 UTC, irvinebroque commented on content/workers-ai/platform/pricing.md
> +- **Fast Twitch Neurons (FTN)** - running at nearest user location at $0.125 / 1k neurons
can we explain what these are?

2023-10-11 16:59 UTC, pdwittig requested changes
Do we really want to launch this page until we have task based translations? 100 neurons per 1k tokens, etc.

I guess what is the value of the page without that - it doesn't seem like it gives developers any insights on what their spend would look like.

2023-10-11 17:08 UTC, rita3ko commented
@pdwittig we need to get something up because we keep getting customers asking and not finding in blog post... so important to communicate that we have pricing

2023-10-12 17:42 UTC, pdwittig approved these changes

2023-10-13 15:53 UTC, rita3ko approved these changes

2023-12-06 10:04 UTC, closed without merging