(Do Not Merge) New Cloudflare One reference architecture
cloudflare/cloudflare-docs pull request #11330
Opened 2023-10-17 18:09 UTC by securitypedant

This is v1 of a new reference architecture for the Cloudflare One platform. It is titled "Evolving to a SASE architecture with Cloudflare".

Note that this has one link to currently unpublished documentation for WARP Connector which is expected to ship this week (Oct 17-20th). The specific content is...

/cloudflare-one/connections/connect-networks/private-net/warp-connector/

And is being published by Randbel Sun. As soon as that content goes live, this reference architecture document can also be published.

2023-10-17 18:59 UTC, ranbel commented
WARP connector PR: #11135

2023-10-20 19:57 UTC, haleycode requested changes

2023-10-20 19:57 UTC, haleycode commented on content/reference-architecture/sase-reference-architecture.md
> +Cloudflare One is a Secure Access Service Edge (SASE) platform that protects enterprise applications, users, devices, and networks. By progressively adopting Cloudflare One, organizations can move aw
```suggestion
Cloudflare One is a secure access service edge (SASE) platform that protects enterprise applications, users, devices, and networks. By progressively adopting Cloudflare One, organizations can move away from their patchwork of hardware appliances and other point solutions and instead consolidate security and networking capabilities on one unified control plane. Such network and security transformation helps address key challenges modern businesses face, including:
```

2023-10-20 19:57 UTC, haleycode commented on content/reference-architecture/sase-reference-architecture.md
> +While this document examines Cloudflare One at a technical level, it does not offer fine detail about every product in the platform. Instead, it looks at how all the services in Cloudflare One enable
```suggestion
While this document examines Cloudflare One at a technical level, it does not offer fine detail about every product in the platform. Instead, it looks at how all the services in Cloudflare One enable networking and network security to be consolidated on one architecture. Visit the [developer documentation](https://developers.cloudflare.com/) for further information specific to a product area or use case.
```

2023-10-20 19:57 UTC, haleycode commented on content/reference-architecture/sase-reference-architecture.md
> +3. **Cyber threats evolved**. The above trends expand an organization’s attack surface. For example, attack campaigns have become more sophisticated and persistent in exploiting multiple channels to
```suggestion
3. **Cyber threats evolved**. The above trends expand an organization’s attack surface. For example, attack campaigns have become more sophisticated and persistent in exploiting multiple channels to infiltrate organizations, and cybercriminals face lower barriers to entry with the popularity of the "cybercrime-as-a-service" black market. 
```

2023-10-20 19:57 UTC, haleycode commented on content/reference-architecture/sase-reference-architecture.md
> +Traditional perimeter-based security has struggled to adapt to these changes. In particular, extending the ‘moat’ outwards has introduced operational complexity for administrators, poor experiences f
```suggestion
Traditional perimeter-based security has struggled to adapt to these changes. In particular, extending the "moat" outwards has introduced operational complexity for administrators, poor experiences for users, and inconsistency in how security controls are applied across users and applications. 
```

2023-10-20 19:57 UTC, haleycode commented on content/reference-architecture/sase-reference-architecture.md
> +In recent years, [Secure Access Service Edge](https://www.cloudflare.com/learning/access-management/security-service-edge-sse/), or SASE, has emerged as an aspirational architecture to help achieve t
```suggestion
In recent years, [secure access service edge](https://www.cloudflare.com/learning/access-management/security-service-edge-sse/), or SASE, has emerged as an aspirational architecture to help achieve these goals. In a SASE architecture, network connectivity and security are unified on a single cloud platform and control plane for consistent visibility, control, and experiences from any user to any application. 
```

2023-10-20 19:57 UTC, haleycode commented on content/reference-architecture/sase-reference-architecture.md
> +For both methods, it is important to note that *cloudflared* only proxies inbound traffic to a private application or network. It does not become a gateway or ‘on-ramp’ back to Cloudflare for the net
```suggestion
For both methods, it is important to note that *cloudflared* only proxies inbound traffic to a private application or network. It does not become a gateway or "on-ramp" back to Cloudflare for the network that it proxies inbound connections to. This means that if the web server starts its own connection to another Internet-based API, that connection will not be routed via Cloudflare Tunnel and will instead be routed via the host server's default route and gateway.
```

2023-10-20 19:57 UTC, haleycode commented on content/reference-architecture/sase-reference-architecture.md
> +Organizations may also connect their network locations directly to the Cloudflare network via [Network Interconnect](https://www.cloudflare.com/network-services/products/network-interconnect/) (CNI).
```suggestion
Organizations may also connect their network locations directly to the Cloudflare network via [Cloudflare Network Interconnect](https://www.cloudflare.com/network-services/products/network-interconnect/) (CNI). Currently, Cloudflare supports two types of [network interconnect](/network-interconnect/about/interconnect-types/):
```

2023-10-20 19:57 UTC, haleycode commented on content/reference-architecture/sase-reference-architecture.md
> +RBI renders the received content in an isolated and secure cloud environment. Instead of executing the web content locally, the user device receives commands for how to ‘draw’ the final rendered web
```suggestion
RBI renders the received content in an isolated and secure cloud environment. Instead of executing the web content locally, the user device receives commands for how to "draw" the final rendered web page over a highly optimized protocol supported by all HTML5-compliant browsers on all operating systems. Because the remote browser runs on Cloudflare’s servers, SWG policies are automatically applied to all browser requests.
```

2023-10-20 19:57 UTC, haleycode commented on content/reference-architecture/sase-reference-architecture.md
> +![SASE Cloud Platform](/images/reference-architecture/cloudflare-one-reference-architecture-images/cf1-ref-arch-2.svg)
```suggestion
![Cloudflare's SASE cloud platform offers network, security, and operational services, as well as policy engine features, to provide zero trust connectivity between a variety of user identities, devices and access locations to customer applications, infrastructure and networks.](/images/reference-architecture/cloudflare-one-reference-architecture-images/cf1-ref-arch-2.svg)
```

2023-10-20 19:57 UTC, haleycode commented on content/reference-architecture/sase-reference-architecture.md
> +![Cloudflare Connectivity Cloud](/images/reference-architecture/cloudflare-one-reference-architecture-images/cf1-ref-arch-4.svg)
```suggestion
![Cloudflare's Anycast Network allows provides services on all connected servers to enable secure connections on public and home networks and at corporate offices.] (/images/reference-architecture/cloudflare-one-reference-architecture-images/cf1-ref-arch-4.svg)
```

2023-10-20 19:57 UTC, haleycode commented on content/reference-architecture/sase-reference-architecture.md
> +![Typical enterprise network today](/images/reference-architecture/cloudflare-one-reference-architecture-images/cf1-ref-arch-1.svg)
```suggestion
![Dedicated WAN on-ramps connect to a variety of security solutions. These connections may result in end-user issues and lead to security vulnerabilities for IT teams.](/images/reference-architecture/cloudflare-one-reference-architecture-images/cf1-ref-arch-1.svg)
```

2023-10-20 19:57 UTC, haleycode commented on content/reference-architecture/sase-reference-architecture.md
> +![Using cloudflared for private network connectivity](/images/reference-architecture/cloudflare-one-reference-architecture-images/cf1-ref-arch-10.svg)
```suggestion
![Requests initiated from a client are securely tunneled to Cloudflare via a device agent, while requests from inside the private network follow the default route.](/images/reference-architecture/cloudflare-one-reference-architecture-images/cf1-ref-arch-10.svg)
```

2023-10-20 19:57 UTC, haleycode commented on content/reference-architecture/sase-reference-architecture.md
> +![Summary of options for private network connectivity](/images/reference-architecture/cloudflare-one-reference-architecture-images/cf1-ref-arch-12.svg)
```suggestion
![Cloudflare's Connectivity Cloud securely links a variety of network locations to the Internet through products such as Firewall, ZTNA, CASB and Load Balancer.](/images/reference-architecture/cloudflare-one-reference-architecture-images/cf1-ref-arch-12.svg)
```

2023-10-20 19:57 UTC, haleycode commented on content/reference-architecture/sase-reference-architecture.md
> +![Anycast versus Unicast networking](/images/reference-architecture/cloudflare-one-reference-architecture-images/cf1-ref-arch-5.svg)
```suggestion
![Cloudflare's Anycast network offers the flexibility to route traffic across multiple data centers, whereas Unicast routing often sends all traffic to a single IP address, resulting in slower connections.](/images/reference-architecture/cloudflare-one-reference-architecture-images/cf1-ref-arch-5.svg)
```

2023-10-20 19:57 UTC, haleycode commented on content/reference-architecture/sase-reference-architecture.md
> +![A typical enterprise IT infrastructure](/images/reference-architecture/cloudflare-one-reference-architecture-images/cf1-ref-arch-6.svg)
```suggestion
![Typical enterprise IT infrastructure may consist of different physical locations, devices and data centers that are connected to multiple websites and cloud-hosted applications.](/images/reference-architecture/cloudflare-one-reference-architecture-images/cf1-ref-arch-6.svg)
```

2023-10-20 19:57 UTC, haleycode commented on content/reference-architecture/sase-reference-architecture.md
> +![Cloudflared connecting applications to Cloudflare](/images/reference-architecture/cloudflare-one-reference-architecture-images/cf1-ref-arch-7.svg)
```suggestion
![Using cloudflared, multiple outbound connections can be routed back to Cloudflare across multiple servers to improve overall reliability.](/images/reference-architecture/cloudflare-one-reference-architecture-images/cf1-ref-arch-7.svg)
```

2023-10-20 19:57 UTC, haleycode commented on content/reference-architecture/sase-reference-architecture.md
> +![SSO flow from user, to Cloudflare, to Salesforce, to IdP](/images/reference-architecture/cloudflare-one-reference-architecture-images/cf1-ref-arch-8.svg)
```suggestion
![The flow of SSO requests between a user, applications and IdPs varies depending on the direction and origin of the request, all of which can be proxied through Cloudflare.](/images/reference-architecture/cloudflare-one-reference-architecture-images/cf1-ref-arch-8.svg)
```

2023-10-20 19:57 UTC, haleycode commented on content/reference-architecture/sase-reference-architecture.md
> +![Applications now connected to Cloudflare](/images/reference-architecture/cloudflare-one-reference-architecture-images/cf1-ref-arch-9.svg)
```suggestion
![Connections to applications like Salesforce, Microsoft and ServiceNow are more secure when scanned by CASB.](/images/reference-architecture/cloudflare-one-reference-architecture-images/cf1-ref-arch-9.svg)
```

2023-10-20 19:57 UTC, haleycode commented on content/reference-architecture/sase-reference-architecture.md
> +![Using WARP Connector for private network connectivity](/images/reference-architecture/cloudflare-one-reference-architecture-images/cf1-ref-arch-11.svg)
```suggestion
![In an example scenario, a developer might push code to a git repository, which ends up in a Kubernetes cluster in a staging network. From staging, it is accessed by a QA tester. All of this traffic is protected via WARP Connector.](/images/reference-architecture/cloudflare-one-reference-architecture-images/cf1-ref-arch-11.svg)
```

2023-10-20 19:57 UTC, haleycode commented on content/reference-architecture/sase-reference-architecture.md
> +![Cloudflare Anycast network with tunnels](/images/reference-architecture/cloudflare-one-reference-architecture-images/cf1-ref-arch-13.svg)
```suggestion
![In an example scenario, traffic from an office network's router would be sent to the closest Cloudflare data center via a secure tunnel.](/images/reference-architecture/cloudflare-one-reference-architecture-images/cf1-ref-arch-13.svg)
```

2023-10-20 19:57 UTC, haleycode commented on content/reference-architecture/sase-reference-architecture.md
> +![Methods of connecting and routing traffic to Cloudflare](/images/reference-architecture/cloudflare-one-reference-architecture-images/cf1-ref-arch-14.svg)
```suggestion
![Each method of connecting and routing traffic can be protected through various layers of security such as Cloudflare Network Interconnect, IPSEC tunnels, WARP connector and cloudflared.](/images/reference-architecture/cloudflare-one-reference-architecture-images/cf1-ref-arch-14.svg)
```

2023-10-20 22:08 UTC, haleycode approved these changes

2023-10-20 22:08 UTC, haleycode commented on content/reference-architecture/sase-reference-architecture.md
> +![Users are presented with a list of integrated identity provider's before accessing protected applications.](/images/reference-architecture/cloudflare-one-reference-architecture-images/cf1-ref-arch-
```suggestion
![Users are presented with a list of integrated identity providers before accessing protected applications.](/images/reference-architecture/cloudflare-one-reference-architecture-images/cf1-ref-arch-18.svg)
```

2023-10-20 23:51 UTC, merged