Celso/subdomains
cloudflare/cloudflare-docs pull request #11449
Opened 2023-10-24 16:50 UTC by celso

2023-10-24 17:00 UTC, edevil commented on content/email-routing/email-workers/reply-email-workers.md
> +title: Reply emails from Workers
Reply to emails

2023-10-24 17:01 UTC, edevil commented on content/email-routing/email-workers/reply-email-workers.md
> +    msg.setSubject("Email Routing Auto-reply");
We need to set the In-Reply-To header to the value of the original Message-ID.

2023-10-24 17:02 UTC, edevil commented on content/email-routing/email-workers/reply-email-workers.md
> +To mitigate security risks and abuse, replying to incoming email has a few requirements:
"incoming emails"

2023-10-24 17:02 UTC, edevil commented on content/email-routing/email-workers/reply-email-workers.md
> +* The outgoing sender domain must match the same domain that received the email.
The In-Reply-To requirement should be mentioned here as well.

2023-10-25 16:54 UTC, rita3ko approved these changes

2023-10-25 17:26 UTC, edevil approved these changes

2023-10-26 08:43 UTC, marciocloudflare requested changes

2023-10-26 08:43 UTC, marciocloudflare commented on content/email-routing/_partials/_reply-emails-workers-intro.md
> +You can reply to incoming emails with another new message and implement smart auto-responders programmatically, adding any content and context in the main body of the message. Think of a customer sup
```suggestion
You can reply to incoming emails with another new message and implement smart auto-responders programmatically, adding any content and context in the main body of the message. Think of a customer support email automatically generating a ticket and returning the link to the sender, an out-of-office reply with instructions when you are on vacation, or a detailed explanation of why you rejected an email.
```

2023-10-26 08:43 UTC, marciocloudflare commented on content/email-routing/_partials/_reply-emails-workers-intro.md
> +Reply to emails is a new method of the [EmailMessage object](/email-routing/email-workers/runtime-api/#emailmessage-definition) in the Runtime API. Here's how it works:
```suggestion
Reply to emails is a new method of the [`EmailMessage` object](/email-routing/email-workers/runtime-api/#emailmessage-definition) in the Runtime API. Here is how it works:
```

2023-10-26 08:43 UTC, marciocloudflare commented on content/email-routing/_partials/_reply-emails-workers-intro.md
> +inputParameters: lastSentence
Did you add this variable to the file? I don't see it anywhere. You need to add a `$1`, for example, to the text for the variable to be rendered. If this is intended to be rendered as the last sentence in this file, you need to add a new paragraph with `$1` in it.

2023-10-26 08:43 UTC, marciocloudflare commented on content/email-routing/email-workers/reply-email-workers.md
> +* The email can only be replied to once in the same EmailMessage event.
```suggestion
* The email can only be replied to once in the same `EmailMessage` event.
```

2023-10-26 08:43 UTC, marciocloudflare commented on content/email-routing/email-workers/reply-email-workers.md
> +* The recipient the reply must match the incoming sender.
```suggestion
* The recipient in the reply must match the incoming sender.
```

2023-10-26 08:43 UTC, marciocloudflare commented on content/email-routing/email-workers/reply-email-workers.md
> +* The recipient the reply must match the incoming sender.
Not sure if this was what you originally meant

2023-10-26 08:43 UTC, marciocloudflare commented on content/email-routing/setup/mta-sts.md
> +Suppose that `example.com` is your domain and uses Email Routing. Here’s how you can enable MTA-STS for it.
```suggestion
Suppose that `example.com` is your domain and uses Email Routing. Here is how you can enable MTA-STS for it.
```

2023-10-26 08:43 UTC, marciocloudflare commented on content/email-routing/setup/mta-sts.md
> +3. Confirm that the record was created
```suggestion
3. Confirm that the record was created.
```

2023-10-26 08:43 UTC, marciocloudflare commented on content/email-routing/setup/mta-sts.md
> +3. Confirm that the record was created
If the bash below is the way to confirm that the record was created, I suggest we slightly change the sentence to something like: `Open your terminal and enter the following command to confirm that the record was created:``

Right now, it's not totally clear if the bash command is for step 3 or not

2023-10-26 08:43 UTC, marciocloudflare commented on content/email-routing/setup/mta-sts.md
> +This tells the other end client that is trying to connect to us that we support MTA-STS.
```suggestion
This command tells the end client that is trying to connect to us that we support MTA-STS.
```

2023-10-26 08:43 UTC, marciocloudflare commented on content/email-routing/setup/mta-sts.md
> +To do this you need to deploy a simple Worker that allows Email clients to pull Cloudflare’s Email Routing policy file using the “well-known” URI convention.
```suggestion
To do this you need to deploy a Worker that allows email clients to pull Cloudflare’s Email Routing policy file using the “well-known” URI convention.
```

2023-10-26 08:43 UTC, marciocloudflare commented on content/email-routing/setup/mta-sts.md
> +Next you need an HTTPS endpoint at `mta-sts.example.com` to serve your policy file. This file defines the mail servers in the domain that use MTA-STS. The reason why HTTPS is used here instead of DNS
I think this here should be another sub chapter in what customers need to do to configure MTA. I suggest that above step 1, we create something like `## 1. Create necessary records`" and above this sentence something like `## 2. Serve your policy file` - or whatever you think better explains this next section.

Also, instead of starting below on step 4, please restart on step 1.

2023-10-26 08:43 UTC, marciocloudflare commented on content/email-routing/setup/mta-sts.md
> +4. Go to your **Account** > **Workers & Pages** and press **Create Application**. Pick the "MTA-STS" template from the list.
```suggestion
1. Go to your **Account** > **Workers & Pages** and press **Create Application**. Select the "MTA-STS" template from the list.
```

2023-10-26 08:43 UTC, marciocloudflare commented on content/email-routing/setup/mta-sts.md
> +This Worker simply proxies https://mta-sts.mx.cloudflare.net/.well-known/mta-sts.txt to your own domain. After deploying it, go to the Worker configuration, then **Triggers** > **Custom Domains** and
```suggestion
2. This Worker proxies `https://mta-sts.mx.cloudflare.net/.well-known/mta-sts.txt` to your own domain. After deploying it, go to the Worker configuration, then **Triggers** > **Custom Domains** and **Add Custom Domain**. Type the subdomain `mta-sts.example.com`.
```

2023-10-26 08:43 UTC, marciocloudflare commented on content/email-routing/setup/mta-sts.md
> +You can then confirm that your policy file is working:
```suggestion
You can then confirm that your policy file is working with the following:
```

2023-10-26 08:43 UTC, marciocloudflare commented on content/email-routing/setup/mta-sts.md
> +Email Routing also supports MTA-STS upstream, which greatly improves security when forwarding your Emails to service providers like Gmail or Microsoft, and others.
```suggestion
Email Routing also supports MTA-STS upstream, which greatly improves security when forwarding your Emails to service providers like Gmail, Microsoft, and others.
```

2023-10-26 08:43 UTC, marciocloudflare commented on content/email-routing/setup/subdomains.md
> +Email Routing is a [zone-level](https://developers.cloudflare.com/fundamentals/concepts/accounts-and-zones/#zones) feature. A zone has a top-level domain (the same as the zone name) and it can have s
```suggestion
Email Routing is a [zone-level](/fundamentals/concepts/accounts-and-zones/#zones) feature. A zone has a top-level domain (the same as the zone name) and it can have subdomains (managed under the DNS feature.) As an example, you can have the `example.com` zone, and then the `mail.example.com` and `corp.example.com` sub-domains under it.
```

2023-10-26 08:43 UTC, marciocloudflare commented on content/email-routing/setup/subdomains.md
> +2. Go to **Email** > **Email Routing** > **Settings** and click **Add subdomain**.
```suggestion
2. Go to **Email** > **Email Routing** > **Settings**, and select **Add subdomain**.
```

2023-10-26 09:47 UTC, marciocloudflare approved these changes

2023-10-26 09:57 UTC, merged