[Analytics] httpRequestsByColoGroups to httpRequestsAdaptiveGroups info
cloudflare/cloudflare-docs pull request #1170
Opened 2021-04-19 21:06 UTC by crwaters16

2021-04-19 21:09 UTC, crwaters16 commented on products/analytics/src/content/graphql-api/migration-guides/graph-ql-analytics/index.md
> +query {
Any help cleaning up this query appreciated - not sure the edits I made are 100% correct.

2021-04-19 21:09 UTC, crwaters16 commented on products/analytics/src/content/graphql-api/migration-guides/graph-ql-analytics/index.md
> +- Given ???.
Stole these few lines from one of the other migration guides - if we'd like to keep here, I'd appreciate some input on what goes here (Given a colo code, time range, and zone tag?)

2021-04-20 13:45 UTC, twalwyn requested changes

2021-04-20 13:45 UTC, twalwyn commented on products/analytics/src/content/graphql-api/migration-guides/graph-ql-analytics/index.md
> +This guide shares considerations when migrating from the deprecated `httpRequestsByColoGroups` API to the `httpRequestsAdaptiveGroups` API.
```suggestion
This guide shares considerations when migrating from the deprecated `httpRequests1[m|d]ByColoGroups` GarphQL API nodes to the `httpRequestsAdaptiveGroups` GraphQL API node.
```

2021-04-20 13:45 UTC, twalwyn commented on products/analytics/src/content/graphql-api/migration-guides/graph-ql-analytics/index.md
> +Below is a query from the Cloudflare dashboard that shows how to access number of requests per colocation, bandwidth, and unique visitors with `httpRequestsAdaptiveGroups`.
Should we provide an example of retrieving the same data, but from the `httpRequests1mByColoGroups` GraphQL node? The reason for this suggestion is that I, personally, find it useful to have something to compare to. Put another way, I am proposing the following structure: 
* Outline the deprecated way of retrieving "number of requests per colocation, bandwidth, and unique visitors"
* Outline the replacement
* Highlight the differences

2021-04-20 14:45 UTC, victor-perov requested changes
Thanks for your work on making our docs better! I have just a few suggestions.

2021-04-20 14:45 UTC, victor-perov commented on products/analytics/src/content/graphql-api/migration-guides/graph-ql-analytics/index.md
> +This guide shares considerations when migrating from the deprecated `httpRequestsByColoGroups` API to the `httpRequestsAdaptiveGroups` API.
To be precise, both `httpRequestsByColoGroups` and `httpRequestsAdaptiveGroups` are Nodes of the same API - GraphQL API. I don't think it's correct to say that one is deprecated API and another one - not.

I think would be nice to have wording like:
```
This guide shares considerations when migrating from the deprecated GraphQL
API node `httpRequestsByColoGroups` to the `httpRequestsAdaptiveGroups`.
``` 

P.S. We use a coding standard to keep 80 chars long lines if it comes to a text.

2021-04-20 14:45 UTC, victor-perov commented on products/analytics/src/content/graphql-api/migration-guides/graph-ql-analytics/index.md
> +Below is a query from the Cloudflare dashboard that shows how to access number of requests per colocation, bandwidth, and unique visitors with `httpRequestsAdaptiveGroups`.
I don't think we can benefit from bringing the exact query from the Cloudflare dashboard. We use Apollo client to manage communication with GQL, which adds some extra meta fields we can avoid by providing a clear example.

I would expect to see queries in the docs with a simple, clear purpose, just to make the learning process faster.

2021-04-20 14:45 UTC, victor-perov commented on products/analytics/src/content/graphql-api/migration-guides/graph-ql-analytics/index.md
> +query {
Yeap, the query looks good to me. Though I would suggest some edits, for example (you could use `graphql` as a style for formatting):

```graphql
{
	viewer {
		zones(filter: {zoneTag: $zoneTag}) {
			series: httpRequestsAdaptiveGroups(
				limit: 5,
				orderBy: [ sum_visits_DESC ],
				filter: {
					datetimeFifteenMinutes_geq: $start
					datetimeFifteenMinutes_lt: $end
				}
			) {
				count
				avg {
					sampleInterval
				}
				sum {
					edgeResponseBytes
					visits
				}
				dimensions {
					metric: coloCode
				}
			}
		}
	}
}
```
So it's cleared version of the existing one, but it emphasizes the filter criteria and shows how we can benefit from **orderBy**. This query will get the top 5 colos by visits.

The example of the response could be as follows (json):
```json
{
  "data": {
    "viewer": {
      "zones": [
        {
          "series": [
            {
              "avg": {
                "sampleInterval": 10
              },
              "count": 7700,
              "dimensions": {
                "metric": "AMS"
              },
              "sum": {
                "edgeResponseBytes": 50078910,
                "visits": 5700
              }
            },
            {
              "avg": {
                "sampleInterval": 10
              },
              "count": 7300,
              "dimensions": {
                "metric": "CDG"
              },
              "sum": {
                "edgeResponseBytes": 47685220,
                "visits": 5230
              }
            },
            {
              "avg": {
                "sampleInterval": 10
              },
              "count": 7530,
              "dimensions": {
                "metric": "LHR"
              },
              "sum": {
                "edgeResponseBytes": 46665180,
                "visits": 5220
              }
            },
            {
              "avg": {
                "sampleInterval": 10
              },
              "count": 5200,
              "dimensions": {
                "metric": "EZE"
              },
              "sum": {
                "edgeResponseBytes": 32085270,
                "visits": 3360
              }
            },
            {
              "avg": {
                "sampleInterval": 10
              },
              "count": 5170,
              "dimensions": {
                "metric": "PTY"
              },
              "sum": {
                "edgeResponseBytes": 31573240,
                "visits": 3220
              }
            }
          ]
        }
      ]
    }
  },
  "errors": null
}
```

2021-04-20 14:45 UTC, victor-perov commented on products/analytics/src/content/graphql-api/migration-guides/graph-ql-analytics/index.md
> +- Given ???.
Please find my comment above

2021-04-20 14:45 UTC, victor-perov commented on products/analytics/src/content/graphql-api/migration-guides/index.md
> +If you're currently using the httpRequestsByColoGroups API, the [httpRequestsByColoGroups to httpRequestsAdaptiveGroups](/migration-guides/graph-ql-analytics) guide will help you migrate your queries
A new line is missing after a header

2021-04-20 23:55 UTC, tlozoot reviewed
Few nit-picky comments but thanks, looking great so far!

2021-04-20 23:55 UTC, tlozoot commented on products/analytics/src/content/graphql-api/migration-guides/graph-ql-analytics/index.md
> +- Instead of `requests`, the `httpRequestsAdaptiveGroups` query reports `count`. This means number of requests per colocation.
I think the official Cloudflare term is "data center" and not "colocation" (which is weird too -- why not just say 'colo'?) -- but I think this is a call for @crwaters16 and the tech writing team.

2021-04-20 23:55 UTC, tlozoot commented on products/analytics/src/content/graphql-api/migration-guides/graph-ql-analytics/index.md
> +- Instead of `requests`, the `httpRequestsAdaptiveGroups` query reports `count`. This means number of requests per colocation.
Also @twalwyn this behavior is kind of weird now that we write it out. Should we add `requests` as an explicit field that can be counted?

2021-04-20 23:55 UTC, tlozoot commented on products/analytics/src/content/graphql-api/migration-guides/graph-ql-analytics/index.md
> +- The `httpRequestsAdaptiveGroups` query reports `sum(edgeResponseBytes)` instead of `bandwidth`. This is the same metric that `httpRequestsByColoGroups` reported as `bandwidth`.
I'm not sure about this one, but it might be worth being pedantic and pointing out that `bandwidth` wasn't really correct terminology for this field in the past.

2021-04-20 23:55 UTC, tlozoot commented on products/analytics/src/content/graphql-api/migration-guides/graph-ql-analytics/index.md
> +- `unique visitors per colocation` is not supported in `httpRequestsAdaptiveGroups`, but the `httpRequestsAdaptiveGroups` API does support `visits`.
Again, would just say "data center" or at least 'colo'

2021-04-20 23:55 UTC, tlozoot commented on products/analytics/src/content/graphql-api/migration-guides/graph-ql-analytics/index.md
> +- `unique visitors per colocation` is not supported in `httpRequestsAdaptiveGroups`, but the `httpRequestsAdaptiveGroups` API does support `visits`.
Also, this guide should mention the distinction between a 'unique' and a 'visit'. 

Visits are defined here: https://support.cloudflare.com/hc/en-us/articles/360037684251-Understanding-Cloudflare-Site-Analytics#:~:text=Visits%20-%20A%20visit%20is%20defined%20as%20a%20page%20view%20that%20originated%20from%20a%20different%20website%2C%20or%20direct%20link.%20Cloudflare%20checks%20where%20the%20HTTP%20referer%20does%20not%20match%20the%20hostname.%20One%20visit%20can%20consist%20of%20multiple%20page%20views

2021-04-21 15:08 UTC, crwaters16 commented on products/analytics/src/content/graphql-api/migration-guides/graph-ql-analytics/index.md
> +```graphql
@victor-perov / @twalwyn , would appreciate your eyes on the httpRequestsByColoGroups example I added - stole it from the other migration guide, not sure if we can cut anything in here out so it's more similar to what's in the updated example

2021-04-22 11:26 UTC, victor-perov requested changes

2021-04-22 11:26 UTC, victor-perov commented on products/analytics/src/content/graphql-api/migration-guides/graph-ql-analytics/index.md
> +```graphql
This is not example for **httpRequests1*ByColoGroups** but for **httpRequests1mGroups**. This node doesn't provide aggregations per data center.

2021-04-22 11:26 UTC, victor-perov commented on products/analytics/src/content/graphql-api/migration-guides/graph-ql-analytics/index.md
> +- Fetch `count`, `sum(edgeResponseBytes)`, and `visits` data center analytics by `coloCode`.
```suggestion
- Fetch the total number of requests (as `count`), the total amount of response
  bytes (as `edgeResponseBytes` of `sum` object), and the total number of
  `visits` per data center (as `metric` of `dimensions` object).
```

2021-04-22 11:26 UTC, victor-perov commented on products/analytics/src/content/graphql-api/migration-guides/graph-ql-analytics/index.md
> +- Instead of `requests`, the `httpRequestsAdaptiveGroups` query reports `count`, which indicates the number of requests per data center.
```suggestion
- Instead of `sum(requests)`, the `httpRequestsAdaptiveGroups` node reports
  `count`, which indicates the same number of requests.
```

2021-04-22 11:26 UTC, victor-perov commented on products/analytics/src/content/graphql-api/migration-guides/graph-ql-analytics/index.md
> +- The `httpRequestsAdaptiveGroups` query reports `sum(edgeResponseBytes)` instead of `bandwidth`. Although `httpRequestsByColoGroups` reported this metric as `bandwidth`, calling it `bandwidth` was n
```suggestion
- The `httpRequestsAdaptiveGroups` node reports `sum(edgeResponseBytes)`
  instead of `sum(bytes)`.
```

2021-04-22 11:26 UTC, victor-perov commented on products/analytics/src/content/graphql-api/migration-guides/graph-ql-analytics/index.md
> +- `unique visitors per colocation` is not supported in `httpRequestsAdaptiveGroups`, but the `httpRequestsAdaptiveGroups` API does support `visits`. A visit is defined as a page view that originated
```suggestion
- `unique visitors per data center` is not supported with
  `httpRequestsAdaptiveGroups` node, but the node does support `visits`. A
  visit is defined as a page view that originated from a different website or
  direct link. Cloudflare checks where the HTTP referer does not match the
  hostname. One visit can consist of multiple page views.
```

2021-04-22 11:26 UTC, victor-perov commented on products/analytics/src/content/graphql-api/migration-guides/index.md
> +If you're currently using the httpRequestsByColoGroups API, the [httpRequestsByColoGroups to httpRequestsAdaptiveGroups](/migration-guides/graph-ql-analytics) guide will help you migrate your queries
```suggestion
If you're currently using the deprecated GraphQL API nodes:
`httpRequests1mByColoGroups` or `httpRequests1dByColoGroups`, the
[guide](/migration-guides/graph-ql-analytics) will help you migrate your queries
to use the replacing node - `httpRequestsAdaptiveGroups`.
```

2021-04-22 11:26 UTC, victor-perov commented on products/analytics/src/content/graphql-api/migration-guides/index.md
> +If you're currently using the httpRequestsByColoGroups API, the [httpRequestsByColoGroups to httpRequestsAdaptiveGroups](/migration-guides/graph-ql-analytics) guide will help you migrate your queries
Can we also rename the folder from `graph-ql-analytics` to `graphql-api-analytics`?

2021-04-22 11:26 UTC, victor-perov commented on products/analytics/src/content/graphql-api/migration-guides/graph-ql-analytics/index.md
> +```graphql
I will share a query and the response

2021-04-22 11:26 UTC, victor-perov commented on products/analytics/src/content/graphql-api/migration-guides/graph-ql-analytics/index.md
> +This guide shares considerations when migrating from the deprecated `httpRequestsByColoGroups` GraphQL API node to the `httpRequestsAdaptiveGroups` GraphQL API node.
```suggestion
This guide shares considerations when migrating from the deprecated GraphQL API
nodes `httpRequests1mByColoGroups`, `httpRequests1dByColoGroups` to the
`httpRequestsAdaptiveGroups` node.
```

2021-04-22 11:26 UTC, victor-perov commented on products/analytics/src/content/graphql-api/migration-guides/graph-ql-analytics/index.md
> +# httpRequestsByColoGroups to httpRequestsAdaptiveGroups
```suggestion
# httpRequests1mByColoGroups/httpRequests1dByColoGroups to httpRequestsAdaptiveGroups
```

2021-04-22 11:26 UTC, victor-perov commented on products/analytics/src/content/graphql-api/migration-guides/graph-ql-analytics/index.md
> +title: httpRequestsByColoGroups to httpRequestsAdaptiveGroups
```suggestion
title: httpRequests1mByColoGroups/httpRequests1dByColoGroups to httpRequestsAdaptiveGroups
```

2021-04-22 11:26 UTC, victor-perov commented on products/analytics/src/content/graphql-api/migration-guides/graph-ql-analytics/index.md
> +Previously a query that used the `httpRequestsByColoGroups` GraphQL API node to access the number of requests per data center, bandwidth, and unique visitors looked like the following:
```suggestion
Let's see, how it possible to access the number of requests, unique visitors,
and bandwidth used per data center with the deprecated GraphQL API node
`httpRequests1mByColoGroups`:
```

2021-04-22 11:41 UTC, victor-perov commented on products/analytics/src/content/graphql-api/migration-guides/graph-ql-analytics/index.md
> +With the deprecation of the `httpRequestsByColoGroups` GraphQL API node, the query to access the same data (`count`, `sum(edgeResponseBytes)`, and `visits` in the `httpRequestsAdaptiveGroups` GraphQL
```suggestion
With the deprecation of the
`httpRequests1mByColoGroups`/`httpRequest1dByColoGroups` GraphQL API nodes, the
query to access the same data (`requests`, `bytes`) and `visits`, with the
`httpRequestsAdaptiveGroups` node looks like the following example:
```

2021-04-22 13:31 UTC, victor-perov requested changes

2021-04-22 13:31 UTC, victor-perov commented on products/analytics/src/content/graphql-api/migration-guides/graph-ql-analytics/index.md
> +```graphql
```graphql
{
    viewer {
        zones(filter: {zoneTag: $zoneTag}) {
            series: httpRequests1mByColoGroups(
                limit: 5,
                orderBy: [ sum_requests_DESC ],
                filter: {
                    datetime_geq: $start
                    datetime_lt: $end
                }
            ) {
                sum {
                    requests
                    bytes
                }
                dimensions {
                    coloCode
                }
            }
        }
    }
}
```

An example of the response could be as follows:

```json
{
  "data": {
    "viewer": {
      "zones": [
        {
          "series": [
            {
              "dimensions": {
                "coloCode": "LHR"
              },
              "sum": {
                "bytes": 18260055,
                "requests": 4404
              }
            },
            {
              "dimensions": {
                "coloCode": "AMS"
              },
              "sum": {
                "bytes": 17563009,
                "requests": 4302
              }
            },
            {
              "dimensions": {
                "coloCode": "CDG"
              },
              "sum": {
                "bytes": 17200434,
                "requests": 4032
              }
            },
            {
              "dimensions": {
                "coloCode": "PTY"
              },
              "sum": {
                "bytes": 10400209,
                "requests": 2707
              }
            },
            {
              "dimensions": {
                "coloCode": "JIB"
              },
              "sum": {
                "bytes": 9040105,
                "requests": 2601
              }
            }
          ]
        }
      ]
    }
  },
  "errors": null
}
```

2021-04-22 13:31 UTC, victor-perov commented on products/analytics/src/content/graphql-api/migration-guides/graph-ql-analytics/index.md
> +
I think it makes sense to align this query with the previous one:

```graphql
{
    viewer {
        zones(filter: {zoneTag: $zoneTag}) {
            series: httpRequestsAdaptiveGroups(
                limit: 5,
                orderBy: [ count_DESC ],
                filter: {
                    datetime_geq: $start
                    datetime_lt: $end
                }
            ) {
                count
                avg {
                    sampleInterval
                }
                sum {
                    visits
                    edgeResponseBytes
                }
                dimensions {
                    coloCode
                }
            }
        }
    }
}
```

And the response could be as follows:

```json
{
  "data": {
    "viewer": {
      "zones": [
        {
          "series": [
            {
              "avg": {
                "sampleInterval": 10
              },
              "count": 4350,
              "dimensions": {
                "coloCode": "LHR"
              },
              "sum": {
                "edgeResponseBytes": 17860000,
                "visits": 4120
              }
            },
            {
              "avg": {
                "sampleInterval": 10
              },
              "count": 4210,
              "dimensions": {
                "coloCode": "AMS"
              },
              "sum": {
                "edgeResponseBytes": 17110000,
                "visits": 3910
              }
            },
            {
              "avg": {
                "sampleInterval": 10
              },
              "count": 3890,
              "dimensions": {
                "coloCode": "CDG"
              },
              "sum": {
                "edgeResponseBytes": 17050000,
                "visits": 3700
              }
            },
            {
              "avg": {
                "sampleInterval": 10
              },
              "count": 2550,
              "dimensions": {
                "coloCode": "PTY"
              },
              "sum": {
                "edgeResponseBytes": 10286000,
                "visits": 2130
              }
            },
            {
              "avg": {
                "sampleInterval": 10
              },
              "count": 2410,
              "dimensions": {
                "coloCode": "JIB"
              },
              "sum": {
                "edgeResponseBytes": 9029000,
                "visits": 2080
              }
            }
          ]
        }
      ]
    }
  },
  "errors": null
}
```

2021-04-22 15:57 UTC, crwaters16 commented on products/analytics/src/content/graphql-api/migration-guides/graph-ql-analytics/index.md
> +title: httpRequestsByColoGroups to httpRequestsAdaptiveGroups
Committing this change to the page title but not the text that appears in the table of contents to help with formatting

2021-04-22 17:37 UTC, victor-perov requested changes

2021-04-22 17:37 UTC, victor-perov commented on products/analytics/src/content/graphql-api/migration-guides/graphql-api-analytics/index.md
> +This guide shares considerations when migrating from the deprecated `httpRequests1mByColoGroups` and `httpRequests1dByColoGroups` GraphQL API nodes to the `httpRequestsAdaptiveGroups` GraphQL API nod
Why you don't want to follow the rule of keeping lines 80chars long?

2021-04-22 17:37 UTC, victor-perov commented on products/analytics/src/content/graphql-api/migration-guides/graphql-api-analytics/index.md
> +Previously you accessed data for the five data centers that had the most number of requests with the deprecated `httpRequests1mByColoGroups` GraphQL API node as in the following example:
Sorry, but this sounds a bit weird to me. As a reader, I might not be using this query at all. So I think, it would make more sense if we start our examples with something like: "Let's say you want to get TOP 5 data centers", or "As an example, let's have a look on how to ...".

Lines 80 chars long.

2021-04-22 17:37 UTC, victor-perov commented on products/analytics/src/content/graphql-api/migration-guides/graphql-api-analytics/index.md
> +Previously you accessed data for the five data centers that had the most number of requests with the deprecated `httpRequests1mByColoGroups` GraphQL API node as in the following example:
the query returns not just five data centers, but the top five by requests.

2021-04-22 17:37 UTC, victor-perov commented on products/analytics/src/content/graphql-api/migration-guides/graphql-api-analytics/index.md
> +With the deprecation of the `httpRequests1mByColoGroups` and `httpRequests1dByColoGroups` GraphQL API nodes, the query to access the same data (`count`, `sum(edgeResponseBytes)`, and `visits` in the
80 chars long lines

2021-04-22 17:37 UTC, victor-perov commented on products/analytics/src/content/graphql-api/migration-guides/graphql-api-analytics/index.md
> +  `visits` per data center (as `metric` of `dimensions` object).
```suggestion
  `visits` per data center.
```

I've reworked the query, so it doesn't use `metric` key.

2021-04-22 17:37 UTC, victor-perov commented on products/analytics/src/content/graphql-api/migration-guides/graphql-api-analytics/index.md
> +- Instead of `requests`, the `httpRequestsAdaptiveGroups` node reports `count`, which indicates the number of requests per data center.
80 chars long line

2021-04-22 17:37 UTC, victor-perov commented on products/analytics/src/content/graphql-api/migration-guides/graphql-api-analytics/index.md
> +- The `httpRequestsAdaptiveGroups` node reports `sum(edgeResponseBytes)` instead of `bandwidth`. Although this metric was frequently referred to as `bandwidth`, calling it `bandwidth` was not an accu
**httpRequests1mByColoGroups** and **httpRequests1dByColoGroups** does not report `bandwidth` at all. Also, the second sentence makes no much sense here. I would say we can easily drop this.

```suggestion
```

2021-04-22 17:37 UTC, victor-perov commented on products/analytics/src/content/graphql-api/migration-guides/graphql-api-analytics/index.md
> +- `unique visitors per colocation` is not supported in `httpRequestsAdaptiveGroups`, but the `httpRequestsAdaptiveGroups` API does support `visits`. A visit is defined as a page view that originated
80 chars long lines

2021-04-22 17:37 UTC, victor-perov commented on products/analytics/src/content/graphql-api/migration-guides/index.md
> +If you're currently using the deprecated `httpRequests1mByColoGroups` or `httpRequests1dByColoGroups` GraphQL API nodes, the [HTTP Requests by Colo Groups to HTTP Requests by Adaptive Groups](/migrat
80 chars long line

2021-04-22 17:37 UTC, victor-perov commented on products/analytics/src/content/graphql-api/migration-guides/index.md
> +If you're currently using the deprecated `httpRequests1mByColoGroups` or `httpRequests1dByColoGroups` GraphQL API nodes, the [HTTP Requests by Colo Groups to HTTP Requests by Adaptive Groups](/migrat
I don't think we use `HTTP Requests by Colo Groups` or `HTTP Requests by Adaptive Groups` anywhere else. This will confuse the reader. Would you mind sharing what's wrong with my previous comment on it?

2021-04-22 17:40 UTC, crwaters16 commented on products/analytics/src/content/graphql-api/migration-guides/graphql-api-analytics/index.md
> +This guide shares considerations when migrating from the deprecated `httpRequests1mByColoGroups` and `httpRequests1dByColoGroups` GraphQL API nodes to the `httpRequestsAdaptiveGroups` GraphQL API nod
Not intentionally violating it- I'll take a look at it

2021-04-22 17:44 UTC, crwaters16 commented on products/analytics/src/content/graphql-api/migration-guides/graphql-api-analytics/index.md
> +Previously you accessed data for the five data centers that had the most number of requests with the deprecated `httpRequests1mByColoGroups` GraphQL API node as in the following example:
The part that was catching me up is what "top" meant and why I omitted it from the text - the query returns the five data centers that have the largest number of requests, right? Or is there some other way we're determining which five data centers are returned and what "top" means? 

I'm trying to avoid "let's" to better align with tech writing best practices (I realize we use it in the other migration guides, this is a new thing), so just want to make sure I understand what exact

2021-04-22 17:49 UTC, crwaters16 commented on products/analytics/src/content/graphql-api/migration-guides/graphql-api-analytics/index.md
> +- The `httpRequestsAdaptiveGroups` node reports `sum(edgeResponseBytes)` instead of `bandwidth`. Although this metric was frequently referred to as `bandwidth`, calling it `bandwidth` was not an accu
@victor-perov - @tlozoot can chime in here, but one of the factors that led us to create this migration guide was confusion around "bandwidth" in particular - apparently people are referring to this metric as bandwidth, which is incorrect, and we want to be very clear that although people might refer to it as such, it's not data returned by this node.

2021-04-22 17:54 UTC, crwaters16 commented on products/analytics/src/content/graphql-api/migration-guides/index.md
> +If you're currently using the deprecated `httpRequests1mByColoGroups` or `httpRequests1dByColoGroups` GraphQL API nodes, the [HTTP Requests by Colo Groups to HTTP Requests by Adaptive Groups](/migrat
I wanted to use the same link as what's in the table of contents for human readability - the page itself still uses your original suggestion, so I hope that still centers them in the example we're providing!

2021-04-22 17:57 UTC, crwaters16 commented on products/analytics/src/content/graphql-api/migration-guides/graphql-api-analytics/index.md
> +This guide shares considerations when migrating from the deprecated `httpRequests1mByColoGroups` and `httpRequests1dByColoGroups` GraphQL API nodes to the `httpRequestsAdaptiveGroups` GraphQL API nod
We use soft newlines in our editor, not hard newlines when we reach 80 characters. This helps avoid awkward line breaks and shifts in our paragraphs, so the hard cutoff doesn't apply to dev docs content despite applying elsewhere in our code!

2021-04-22 18:21 UTC, tlozoot commented on products/analytics/src/content/graphql-api/migration-guides/graphql-api-analytics/index.md
> +- The `httpRequestsAdaptiveGroups` node reports `sum(edgeResponseBytes)` instead of `bandwidth`. Although this metric was frequently referred to as `bandwidth`, calling it `bandwidth` was not an accu
Maybe we can say something like:

> To measure data transfer, use `sum(edgeResponseBytes)`. (Note that in the old API, this was called `bandwidth` even though it also measured data transfer)

2021-04-22 18:23 UTC, tlozoot commented on products/analytics/src/content/graphql-api/migration-guides/graphql-api-analytics/index.md
> +- The `httpRequestsAdaptiveGroups` node reports `sum(edgeResponseBytes)` instead of `bandwidth`. Although this metric was frequently referred to as `bandwidth`, calling it `bandwidth` was not an accu
The important points are:
1) You measure data transfer using `sum(edgeResponseBytes)` -- people get confused and ask about this all the time
2) The thing we previously called `bandwidth` is actually `data transfer`. I strongly we don't refer the new thing using the incorrect terminology `bandwidth`. But, we still need to explain "how do you measure the old thing in the new way". Does that make sense?

2021-04-22 18:25 UTC, tlozoot commented on products/analytics/src/content/graphql-api/migration-guides/graphql-api-analytics/index.md
> +                filter: {
We should also add a filter for requestSource: 'eyeball' and explain this below.

2021-04-22 23:04 UTC, tlozoot commented on products/analytics/src/content/graphql-api/migration-guides/graphql-api-analytics/index.md
> +- Adding the `requestSource` filter for `eyeball` returns request, response byte, and visit data about only the end users of your website.
nit, but maybe `data transfer` instead of `response byte` (which just reads slightly awkward to me)

2021-04-22 23:04 UTC, tlozoot approved these changes
This is awesome, thank you!!

2021-04-23 13:55 UTC, kodster28 commented on products/analytics/src/content/graphql-api/migration-guides/graphql-api-analytics/index.md
> +For example, if you wanted to see which five data centers had the most number of requests, the total number of those requests, and the total amount of data transfer, in the past you used the  `httpRe
Maybe shorten from "in the past..." to "you would have used the `httpRequests1mByColoGroups` GraphQL API node."

2021-04-23 13:56 UTC, kodster28 commented on products/analytics/src/content/graphql-api/migration-guides/graphql-api-analytics/index.md
> +For example, if you wanted to see which five data centers had the most number of requests, the total number of those requests, and the total amount of data transfer, in the past you used the  `httpRe
Also maybe add a header of **Request** above the code block

2021-04-23 14:08 UTC, kodster28 approved these changes

2021-04-23 14:08 UTC, kodster28 commented on products/analytics/src/content/graphql-api/migration-guides/graphql-api-analytics/index.md
> +With the deprecation of the `httpRequests1mByColoGroups` and `httpRequests1dByColoGroups` GraphQL API nodes, the query to access the same data (`count`, `sum(edgeResponseBytes)`, and `visits` in the
Would it make sense to add two L2 headers?

Deprecated query and New query?

2021-04-23 14:08 UTC, kodster28 commented on products/analytics/src/content/graphql-api/migration-guides/graphql-api-analytics/index.md
> +With the deprecation of the `httpRequests1mByColoGroups` and `httpRequests1dByColoGroups` GraphQL API nodes, the query to access the same data (`count`, `sum(edgeResponseBytes)`, and `visits` in the
And could you just shorten this to, "The new query would use the `httpRequestsAdaptiveGroups` GraphQL API node."

And then add bolded **Request** and **Response**

2021-04-23 14:08 UTC, kodster28 commented on products/analytics/src/content/graphql-api/migration-guides/graphql-api-analytics/index.md
> +For example, if you wanted to see which five data centers had the most number of requests, the total number of those requests, and the total amount of data transfer, in the past you used the  `httpRe
There's a double space before `httpRequests1mByColoGroups`

2021-04-23 14:08 UTC, kodster28 commented on products/analytics/src/content/graphql-api/migration-guides/graphql-api-analytics/index.md
> +  `visits` per data center.
There's a double space before `visits`

2021-04-23 14:08 UTC, kodster28 commented on products/analytics/src/content/graphql-api/migration-guides/index.md
> +If you're currently using the deprecated `httpRequests1mByColoGroups` or `httpRequests1dByColoGroups` GraphQL API nodes, the [HTTP Requests by Colo Groups to HTTP Requests by Adaptive Groups](/migrat
Broken link

2021-04-23 14:08 UTC, kodster28 commented on products/analytics/src/content/graphql-api/migration-guides/index.md
>  - [Zone Analytics to GraphQL Analytics](/migration-guides/zone-analytics/)
These links to other areas of the docs are also broken

2021-04-23 18:01 UTC, victor-perov approved these changes

2021-04-23 18:05 UTC, merged

2021-04-23 18:06 UTC, crwaters16 commented
Thanks for the input everyone!