Queues: Update commands.md
cloudflare/cloudflare-docs pull request #11750
Opened 2023-11-10 14:55 UTC by elithrar

Add Queues to the wrangler CLI docs.

2023-11-10 15:31 UTC, rts-rob requested changes
Some copy/paste errors and options callouts.

2023-11-10 15:31 UTC, rts-rob commented on content/workers/wrangler/commands.md
> +wrangler queue create <name> [OPTIONS]
Should be `wrangler queues create...` (note the plural)

2023-11-10 15:31 UTC, rts-rob commented on content/workers/wrangler/commands.md
> +wrangler hyperdrive delete <name> [OPTIONS]
Should be `wrangler queues delete...` (note the service name).

2023-11-10 15:31 UTC, rts-rob commented on content/workers/wrangler/commands.md
> +wrangler queues list
Has `[OPTIONS]` for pagination

2023-11-10 15:31 UTC, rts-rob commented on content/workers/wrangler/commands.md
> +wrangler queues consumer add <queue-name> <script-name>
Has `[OPTIONS]` for e.g., batch size.

2023-11-13 15:09 UTC, Maddy-Cloudflare approved these changes

2023-11-13 15:09 UTC, Maddy-Cloudflare commented on content/workers/wrangler/commands.md
> +- [`queues`](#queues) - Configure Workers Queues
```suggestion
- [`queues`](#queues) - Configure Workers Queues.
```

2023-11-13 15:09 UTC, Maddy-Cloudflare commented on content/workers/wrangler/commands.md
> +wrangler queue create <name> [OPTIONS]
```suggestion
wrangler queues create <name> [OPTIONS]
```

2023-11-13 15:09 UTC, Maddy-Cloudflare commented on content/workers/wrangler/commands.md
> +wrangler hyperdrive delete <name> [OPTIONS]
```suggestion
wrangler queues delete <name> [OPTIONS]
```

2023-11-13 15:09 UTC, Maddy-Cloudflare commented on content/workers/wrangler/commands.md
> +wrangler queues list
```suggestion
wrangler queues list [OPTIONS]
```

2023-11-13 15:09 UTC, Maddy-Cloudflare commented on content/workers/wrangler/commands.md
> +wrangler queues consumer add <queue-name> <script-name>
```suggestion
wrangler queues consumer add <queue-name> <script-name> [OPTIONS]
```

2023-11-14 14:12 UTC, rts-rob approved these changes

2023-11-14 14:15 UTC, merged