[Hyperdrive] add Supabase example for Hyperdrive
cloudflare/cloudflare-docs pull request #12033
Opened 2023-11-30 12:54 UTC by inian

2023-11-30 16:06 UTC, Maddy-Cloudflare approved these changes

2023-11-30 16:06 UTC, Maddy-Cloudflare commented on content/hyperdrive/examples/supabase.md
> +-- Here we are granting it the postgres role. In practice, you want to create a role with lesser privileges.
```suggestion
-- Here, you are granting it the postgres role. In practice, you want to create a role with lesser privileges.
```

2023-12-01 15:06 UTC, Maddy-Cloudflare requested changes
To be addressed.

2023-12-05 05:33 UTC, inian commented
@Maddy-Cloudflare I have addressed your comments. can you PTAL?

2024-01-09 15:10 UTC, elithrar approved these changes

2024-01-09 15:19 UTC, Maddy-Cloudflare approved these changes

2024-01-09 15:31 UTC, merged

2024-01-09 16:52 UTC, ant-supabase commented on content/hyperdrive/get-started.md
> -4. **A publicly accessible PostgreSQL (or PostgreSQL compatible) database**. Cloudflare recommends [Neon](https://neon.tech/) or [Supabase](https://supabase.com) if you do not have an existing databa
Shame! Anything we're missing here to get the rec @elithrar?

2024-01-09 16:54 UTC, elithrar commented on content/hyperdrive/get-started.md
> -4. **A publicly accessible PostgreSQL (or PostgreSQL compatible) database**. Cloudflare recommends [Neon](https://neon.tech/) or [Supabase](https://supabase.com) if you do not have an existing databa
We'd prefer to keep the tutorial PR discrete for now, and avoid making users (during our own getting started guide!) have to figure out what to choose from.

2024-01-09 16:54 UTC, awalias commented on content/hyperdrive/get-started.md
> -4. **A publicly accessible PostgreSQL (or PostgreSQL compatible) database**. Cloudflare recommends [Neon](https://neon.tech/) or [Supabase](https://supabase.com) if you do not have an existing databa
oops wrong account...