[Cache] Add warning about JSD and ETags
cloudflare/cloudflare-docs pull request #12086
Opened 2023-12-05 16:47 UTC by cascadingstyletrees

Updating Cache Article based on CUSTESC-33810

Note:
May in the future add warnings about etags in the referenced articles (JSD,E-mail obfs...)

2023-12-05 16:57 UTC, cascadingstyletrees commented
Also PCX-9183

2023-12-06 11:15 UTC, migueldemoura requested changes

2023-12-06 11:15 UTC, migueldemoura commented on content/cache/reference/etag-headers.md
> +When using weak ETag headers, disable [Javascript Detections](/bots/reference/javascript-detections/),[Email Obfuscation](/support/more-dashboard-apps/cloudflare-scrape-shield/what-is-email-address-o
```suggestion
When using weak ETag headers, disable [JavaScript Detections](/bots/reference/javascript-detections/),[Email Obfuscation](/support/more-dashboard-apps/cloudflare-scrape-shield/what-is-email-address-obfuscation/) and [Automatic HTTPS Rewrites](/ssl/edge-certificates/additional-options/automatic-https-rewrites/) to ensure Cloudflare does not remove the ETag headers set by your origin web server.
```

2023-12-06 15:53 UTC, patriciasantaana approved these changes

2023-12-06 19:39 UTC, closed without merging