Add workers ai usage warning in local mode
cloudflare/cloudflare-docs pull request #12190
Opened 2023-12-11 17:12 UTC by G4brym

2023-12-11 17:47 UTC, penalosa requested changes
This should also have a note in the Wrangler configurations docs (https://developers.cloudflare.com/workers/wrangler/configuration/#bindings)

2023-12-11 18:23 UTC, G4brym commented
Hey @penalosa just added a very simple section for workers ai in wrangler configuration.md

2023-12-11 18:56 UTC, penalosa approved these changes

2023-12-11 19:02 UTC, pdwittig approved these changes

2023-12-12 15:44 UTC, kodster28 approved these changes

2023-12-12 15:45 UTC, merged