[LB] Intro tutorial using Pages as origin
cloudflare/cloudflare-docs pull request #12241
Opened 2023-12-14 12:10 UTC by RebeccaTamachiro

PCX-8876

2024-07-01 08:43 UTC, markdembo requested changes
Great addition to our docs! Happy to see. This will be great.
There are a few issues that need to be resolved though and nit-picks/suggestions to be considered.

2024-07-01 08:43 UTC, markdembo commented on content/load-balancing/pools/cloudflare-pages-origin.md
> +    * The origin server IP address. If you do not know it, you can run a dig command against your domain with an [online DNS lookup tool](https://digwebinterface.com) to find out.
issue (blocking): This is highly advised against when using Cloudflare as origin. Use the hostname instead e.g. `mypagesproject.example.com` - due to our anycast network, IPs can change at any time.

2024-07-01 08:43 UTC, markdembo commented on content/load-balancing/pools/cloudflare-pages-origin.md
> +    * (Optional) A [hostname](/load-balancing/additional-options/override-http-host-headers/) by selecting **Add host header**.
issue (blocking) This is not optional.

2024-07-01 08:43 UTC, markdembo commented on content/load-balancing/pools/cloudflare-pages-origin.md
> +        If your production website is hosted on a platform like Cloudflare Pages, where you have a default subdomain (`example.pages.dev`) and then configure a [custom domain](/pages/configuration/cu
issue (blocking) We should word this stronger. It will fail with certainty. suggestion: You need to...

2024-07-01 08:43 UTC, markdembo commented on content/load-balancing/pools/cloudflare-pages-origin.md
> +| Origin address              | `<IP address>`                                |
nitpick (non-blocking): the current UI labels this as endpoint address, instead of origin address

2024-07-01 08:43 UTC, markdembo commented on content/load-balancing/pools/cloudflare-pages-origin.md
> +| Origin name                 | `my-pages-website`                            |
nitpick (non-blocking): the current UI labels this as endpoint name, instead of origin name

2024-07-01 08:43 UTC, markdembo commented on content/load-balancing/pools/cloudflare-pages-origin.md
> +| Origin steering             | `<default>`                                   |
nitpick (non-blocking): the current UI labels this as endpoint steering, instead of origin steering

2024-07-01 08:43 UTC, markdembo commented on content/load-balancing/pools/cloudflare-pages-origin.md
> +{{</Aside>}}
suggestion (non-blocking): Move this warning to the top of this tutorial step and reword a little to say that in the following you'll find a step by step guide for a correct setup. also, again wording can be stronger. It will fail.

2024-07-01 08:43 UTC, markdembo commented on content/load-balancing/pools/cloudflare-pages-origin.md
> +    * The origin server IP address. If you do not know it, you can run a dig command against your domain with an [online DNS lookup tool](https://digwebinterface.com) to find out.
This is super important. This can easily break production.

2024-07-01 08:43 UTC, markdembo commented on content/load-balancing/pools/cloudflare-pages-origin.md
> +| Origin address              | `<IP address>`                                |
issue (blocking): same as above. Move to `<your custom domain or Pages subdomain>`  .

2024-07-02 13:09 UTC, markdembo approved these changes
This looks great! Thanks so much!

2024-07-02 16:37 UTC, angelampcosta approved these changes

2024-07-02 16:37 UTC, angelampcosta commented on content/load-balancing/pools/cloudflare-pages-origin.md
> +To support the [use cases](#use-cases) mentioned above, and assuming only one origin server for your production website and one for the Cloudflare Pages instance, create two pools with one endpoint e
```suggestion
To support the [use cases](#use-cases) mentioned above, and assuming you only have one origin server for your production website and one for the Cloudflare Pages instance, create two pools with one endpoint each:
```

2024-07-02 16:37 UTC, angelampcosta commented on content/load-balancing/pools/cloudflare-pages-origin.md
> +5. Under **Advanced health check settings**, keep the default values and enable the **Follow redirects** option.
```suggestion
5. Under **Advanced health check settings**, keep the default values and enable the **Follow Redirects** option.
```

2024-07-02 16:37 UTC, angelampcosta commented on content/load-balancing/pools/cloudflare-pages-origin.md
> +5. Under **Advanced health check settings**, keep the default values and enable the **Follow redirects** option.
For consistency with dash.

2024-07-02 16:37 UTC, angelampcosta commented on content/load-balancing/pools/cloudflare-pages-origin.md
> +  * A description to provide more detail on the name. Suggestion: `production website`
```suggestion
  * A description to provide more details on the name. Suggestion: `production website`
```

2024-07-02 16:37 UTC, angelampcosta commented on content/load-balancing/pools/cloudflare-pages-origin.md
> +  * Set up **Pool Notifications** and **Health Notifications** as you prefer.
I don't have these two options.

2024-07-02 16:37 UTC, angelampcosta commented on content/load-balancing/pools/cloudflare-pages-origin.md
> +2. Find the pools you created in the list and check if their status is `healthy`. You might have to refresh the page.
```suggestion
2. Find the pools you created in the list and check if their status is `Healthy`. You might have to refresh the page.
```

2024-07-02 16:37 UTC, angelampcosta commented on content/load-balancing/pools/cloudflare-pages-origin.md
> +2. Find the pools you created in the list and check if their status is `healthy`. You might have to refresh the page.
To match dash.

2024-07-02 16:37 UTC, angelampcosta commented on content/load-balancing/pools/cloudflare-pages-origin.md
> +3. Expand each pool entry to confirm that the health status for endpoints within them is also `healthy`.
```suggestion
3. Expand each pool entry to confirm that the health status for endpoints within them is also `Healthy`.
```

2024-07-02 16:37 UTC, angelampcosta commented on content/load-balancing/pools/cloudflare-pages-origin.md
> +3. Expand each pool entry to confirm that the health status for endpoints within them is also `healthy`.
Same.

2024-07-02 16:37 UTC, angelampcosta commented on content/load-balancing/pools/cloudflare-pages-origin.md
> +The basic principle is that, if both your production website and your Cloudflare Pages project are live and directly accessible via browser, the monitors should also be able get a `200` code as HTTP
```suggestion
The basic principle is that, if both your production website and your Cloudflare Pages project are live and directly accessible via browser, the monitors should also be able to get a `200` code as HTTP response.
```

2024-07-02 16:37 UTC, angelampcosta commented on content/load-balancing/pools/cloudflare-pages-origin.md
> +    * Select your preferred option for [proxy mode](/load-balancing/understand-basics/proxy-modes/), [session affinity](/load-balancing/understand-basics/session-affinity/), and [adaptive routing](/l
I don't have the proxy mode option, but I have Data Localization.

2024-07-02 16:37 UTC, angelampcosta commented on content/load-balancing/pools/cloudflare-pages-origin.md
> +2. In the **Manage Load Balancers** list, locate the load balancer you created under a test hostname (such as `lb`) and select to enable it.
```suggestion
2. In the **Manage Load Balancers** list, locate the load balancer you created under a test hostname (such as `lb`) and enable it.
```

2024-07-02 16:37 UTC, angelampcosta commented on content/load-balancing/pools/cloudflare-pages-origin.md
> +After you can confirm everything is working correctly, make sure you re-enable the pools within the load balancer.
```suggestion
After you confirm everything is working correctly, make sure you re-enable the pools within the load balancer.
```

2024-07-03 08:48 UTC, RebeccaTamachiro commented on content/load-balancing/pools/cloudflare-pages-origin.md
> +  * Set up **Pool Notifications** and **Health Notifications** as you prefer.
Well noted! They don't seem to be there anymore.

2024-07-03 09:37 UTC, merged