[D1] Update Wrangler commands
cloudflare/cloudflare-docs pull request #12336
Opened 2023-12-21 04:06 UTC by KianNH

cc @rozenmd

2023-12-21 04:11 UTC, KianNH commented on content/workers/wrangler/commands.md
> +- `--preview` {{<type>}}boolean{{</type>}} {{<prop-meta>}}optional{{</prop-meta>}}
The `--preview` options (elsewhere in this PR too) sound a little weird because `DATABASE_NAME` doesn't imply you can pass the name of a binding too but you can, so all of the `DATABASE_NAME` options likely want changing where those commands accept a binding.

```
wrangler d1 execute <database>

Executed command or SQL file

Positionals:
  database  The name or binding of the DB  [string] [required]
```

2023-12-21 05:06 UTC, rozenmd commented on content/workers/wrangler/commands.md
> +- `--preview` {{<type>}}boolean{{</type>}} {{<prop-meta>}}optional{{</prop-meta>}}
We should really get rid of preview and go all-in on wrangler environments

2023-12-21 15:35 UTC, deadlypants1973 requested changes
Looks amazing :) Remove npx though please, we added instruction on running commands with package managers here: https://developers.cloudflare.com/workers/wrangler/commands/#background

2023-12-21 15:35 UTC, deadlypants1973 commented on content/workers/wrangler/commands.md
> +  - Execute any unapplied migrations on your preview D1 database (as defined by `preview_database_id` in [Wrangler.toml](/workers/wrangler/configuration/#d1-databases)).
```suggestion
  - Execute any unapplied migrations on your preview D1 database (as defined by `preview_database_id` in [`wrangler.toml`](/workers/wrangler/configuration/#d1-databases)).
```

2023-12-21 15:35 UTC, deadlypants1973 commented on content/workers/wrangler/commands.md
> +  - Show the list of unapplied migration files on your preview D1 database (as defined by `preview_database_id` in [Wrangler.toml](/workers/wrangler/configuration/#d1-databases)).
```suggestion
  - Show the list of unapplied migration files on your preview D1 database (as defined by `preview_database_id` in [`wrangler.toml`](/workers/wrangler/configuration/#d1-databases)).
```

2023-12-21 15:35 UTC, deadlypants1973 commented on content/workers/wrangler/commands.md
> +  - The .sqlite3 file to write to (defaults to `'<db-name>.<short-backup-id>.sqlite3'`).
```suggestion
  - The .`sqlite3` file to write to (defaults to `'<DB_NAME>.<SHORT_BACKUP_ID>.sqlite3'`).
```

2023-12-23 09:06 UTC, rozenmd commented on content/workers/wrangler/commands.md
> +  - The .sqlite3 file to write to (defaults to `'<db-name>.<short-backup-id>.sqlite3'`).
`.sqlite3`

2024-01-19 15:10 UTC, KianNH commented on content/workers/wrangler/commands.md
> +  - The .sqlite3 file to write to (defaults to `'<db-name>.<short-backup-id>.sqlite3'`).
```suggestion
  - The `.sqlite3` file to write to (defaults to `'<DB_NAME>.<SHORT_BACKUP_ID>.sqlite3'`).
```

2024-02-29 18:59 UTC, deadlypants1973 commented on content/workers/wrangler/commands.md
> +  - Answer "yes" to any prompts.
```suggestion
  - Answer `yes` to any prompts.
```

2024-02-29 18:59 UTC, deadlypants1973 commented on content/workers/wrangler/commands.md
> +```sh
```suggestion
```tx
```

2024-02-29 18:59 UTC, deadlypants1973 commented on content/workers/wrangler/commands.md
> +$ npx wrangler d1 execute <DATABASE_NAME> [OPTIONS]
```suggestion
wrangler d1 execute <DATABASE_NAME> [OPTIONS]
```

2024-02-29 19:00 UTC, deadlypants1973 approved these changes

2024-02-29 19:05 UTC, merged