workers: make size limits clearer
cloudflare/cloudflare-docs pull request #12432
Opened 2024-01-08 15:30 UTC by elithrar

This PR:

* Makes it clearer that larger Workers bundles can have a negative perf impact
* How to measure the size after compression
* Options for storing config/binary data/etc outside of a Worker bundle

2024-01-08 15:31 UTC, Erisa approved these changes

2024-01-08 15:40 UTC, irvinebroque approved these changes

2024-01-08 15:40 UTC, irvinebroque commented on content/workers/platform/limits.md
> +Note that larger Worker bundles, especially those over 1 MB, can impact the start-up time of the Worker, as the Worker needs to be loaded into memory. You should consider removing unnecessary depende
```suggestion
Note that larger Worker bundles can impact the start-up time of the Worker, as the Worker needs to be loaded into memory. You should consider removing unnecessary dependencies and/or using [Workers KV](/kv/), a [D1 database](/d1/) or [R2](/r2/) to store configuration files, static assets and binary data instead of attempting to bundle them within your Worker code. 
```

2024-01-08 16:07 UTC, Erisa requested changes

2024-01-08 16:07 UTC, Erisa commented on content/workers/platform/limits.md
> +Note that larger Worker bundles, especially those over 1 MB, can impact the start-up time of the Worker, as the Worker needs to be loaded into memory. You should consider removing unnecessary depende
Could we also mention `--minify` in this line as a first step?

2024-01-08 16:07 UTC, Erisa commented on content/workers/platform/limits.md
> +```console
```suggestion
```sh
```

2024-01-08 16:08 UTC, Erisa commented on content/workers/platform/limits.md
> +```console
This makes the interactive elements of the codeblock work, such as highlighting/copying the actual command.

Rather than plain code as `console` is not a supported language: 
![image](https://github.com/cloudflare/cloudflare-docs/assets/14004943/61e9b1b0-11fe-4f11-847b-81d77abdf943)

2024-01-08 16:12 UTC, pedrosousa commented on content/workers/platform/limits.md
> +```console
Reference: [List of languages used in Cloudflare developer documentation](https://developers.cloudflare.com/style-guide/formatting/code-block-guidelines/#list-of-languages-used-in-cloudflare-developer-documentation)

2024-01-08 16:51 UTC, elithrar commented on content/workers/platform/limits.md
> +Note that larger Worker bundles, especially those over 1 MB, can impact the start-up time of the Worker, as the Worker needs to be loaded into memory. You should consider removing unnecessary depende
Do we document `--minify` elsewhere - e.g. the trade-offs, and why it's not the default, how to assess if it's suitable, etc?

(_I_ know why it's not the default in general, but a user doesn't!)

2024-01-13 00:11 UTC, Erisa commented on content/workers/platform/limits.md
> +Note that larger Worker bundles, especially those over 1 MB, can impact the start-up time of the Worker, as the Worker needs to be loaded into memory. You should consider removing unnecessary depende
Couldn't find any other documentation on it, so may not be worth adding after all unless that is also put together

2024-01-17 02:02 UTC, Erisa approved these changes

2024-01-18 13:03 UTC, merged