Clarified that O2O for WPEngine does not need Enterprise
cloudflare/cloudflare-docs pull request #12459
Opened 2024-01-09 19:15 UTC by sergiozygmunt

Clarified that O2O for WPEngine does not need Enterprise

2024-01-10 11:18 UTC, jason-cf commented
Waiting on internal approval for this change.

2024-01-10 11:18 UTC, jason-cf requested changes
sent change requests via chat

2024-01-10 18:19 UTC, jason-cf approved these changes

2024-01-10 18:19 UTC, merged

2024-03-28 00:45 UTC, hulet commented
https://developers.cloudflare.com/cloudflare-for-platforms/cloudflare-for-saas/saas-customers/provider-guides/wpengine/ still says "If you use WP Engine **and also have a Cloudflare Enterprise plan**, you can use your own Cloudflare Zone to proxy web traffic to your Zone first, then WP Engine’s (the SaaS Provider) Zone second."

If O2O for WPEngine does not need Enterprise should this be updated to remove the Cloudflare Enterprise stipulation?

I see that `_provider-guide-intro.md` is also used on the Shopify and SFCC Provider guides which both say "You can only enable O2O on the Cloudflare Enterprise plan." Maybe those providers also no longer require Cloudflare Enterprise though?