Images merge
cloudflare/cloudflare-docs pull request #12492
Opened 2024-01-11 23:09 UTC by dcpena

2024-01-12 17:58 UTC, nasrumikail commented
https://www.facebook.com/profile.php?id=100091631653005 If you want to change your life, you are going to have to do things differently. And sometimes, you can look to inspirational books to create a positive change in your life.

If you desire change, you are going to have to step out of your comfort zone. As Anthony Robbins points out:

“All personal breakthroughs begin with a change in beliefs. So how do we change? The most effective way is to get your brain to associate massive pain to the old belief. You must feel deep in your gut that not only has this belief cost you pain in the past, but it’s costing you in the present and, ultimately, can only bring you pain in the future. Then you must associate tremendous pleasure to the idea of adopting an empowering new belief” — Anthony Robbins

In order to transform your life, you will experience discomfort and pain. Change can be a painful process, but the rewards of going through the change are priceless.

▬▬▬▬▬▬▬▬▬▬▬▬
🇸 🇭 🇦 🇷 🇪 &🇯 🇴 🇮 🇳 👇
@milkaainajireenyaa
@milkaainajireenyaa
▬▬▬▬▬▬▬▬▬▬▬▬
🇸 🇭 🇦 🇷 🇪 &🇯 🇴 🇮 🇳 @dcpena @elithrar @elithrar @dcpena @dcpena @elithrar @hturan @rickyrobinett @outerim

2024-01-16 16:59 UTC, marciocloudflare approved these changes

2024-01-18 09:37 UTC, marciocloudflare commented on content/images/get-started.md
> +Transformations let you optimize images that are stored outside of Cloudflare Images. Cloudflare will automatically cache every transformed image at the edge so that you store only the original image
Consider using `Cloudflare will automatically cache every transformed image in our global network` instead of `edge`

2024-01-18 10:02 UTC, marciocloudflare requested changes

2024-01-18 10:02 UTC, marciocloudflare commented on content/images/get-started.md
> +2. Go to **Images** > T**ransformations**.
```suggestion
2. Go to **Images** > **Transformations**.
```

2024-01-18 10:02 UTC, marciocloudflare commented on content/images/serve-images/adaptive-optimized-format-delivery.md
> +Cloudflare Images automatically transcodes uploaded PNG, JPEG and GIF files to the more efficient AVIF and WebP formats. This happens whenever the customer browser supports them. If the browser does
```suggestion
Cloudflare Images automatically transcodes uploaded PNG, JPEG and GIF files to the more efficient AVIF and WebP formats. This happens whenever the customer browser supports them. If the browser does not support AVIF, Cloudflare Images will fall back to WebP. If there is no support for WebP, then Cloudflare Images will serve compressed files in the original format.
```

2024-01-18 10:02 UTC, marciocloudflare commented on content/images/serve-images/adaptive-optimized-format-delivery.md
> +Cloudflare Images automatically transcodes uploaded PNG, JPEG and GIF files to the more efficient AVIF and WebP formats. This happens whenever the customer browser supports them. If the browser does
Not sure if there was originally a link here

2024-01-18 10:02 UTC, marciocloudflare commented on content/images/serve-images/serve-from-custom-domains.md
> +```
```suggestion
```txt
```

2024-01-18 10:02 UTC, marciocloudflare commented on content/images/serve-images/serve-from-custom-domains.md
> +This feature requires a Business or Enterprise plan to enable regex in Transform Rules. Refer to Cloudflare Transform Rules Availability for more information.
```suggestion
This feature requires a Business or Enterprise plan to enable regex in Transform Rules. Refer to Cloudflare [Transform Rules Availability](/rules/transform/#availability) for more information.
```

2024-01-18 10:02 UTC, marciocloudflare commented on content/images/serve-images/serve-from-custom-domains.md
> +```
```suggestion
```txt
```

2024-01-18 10:02 UTC, marciocloudflare commented on content/images/serve-images/serve-from-custom-domains.md
> +This example lets you rewrite a request from `example.com/images/some-image-id/w100,h300` to `example.com/cdn-cgi/imagedelivery/<ACCOUNT_HASH>/some-image-id/width=100,height=300` and implies Flexible
```suggestion
This example lets you rewrite a request from `example.com/images/some-image-id/w100,h300` to `example.com/cdn-cgi/imagedelivery/<ACCOUNT_HASH>/some-image-id/width=100,height=300` and assumes Flexible variants feature is turned on.
```

2024-01-18 10:02 UTC, marciocloudflare commented on content/images/serve-images/serve-from-custom-domains.md
> +This example lets you rewrite a request from `example.com/images/some-image-id/w100,h300` to `example.com/cdn-cgi/imagedelivery/<ACCOUNT_HASH>/some-image-id/width=100,height=300` and implies Flexible
Not sure, but I think it's `assumes` not `implies`here

2024-01-18 10:02 UTC, marciocloudflare commented on content/images/serve-images/serve-from-custom-domains.md
> +Use a Cloudflare Worker to access your images and a Route using your domain to execute the worker. For an example worker, refer to [Serve private images using signed URL tokens](/images/serve-images/
```suggestion
When using a custom domain, it is not possible to directly set up WAF rules that act on requests hitting the `/cdn-cgi/imagedelivery/` path. If you need to set up WAF rules, you can use a Cloudflare Worker to access your images and a Route using your domain to execute the worker. For an example worker, refer to [Serve private images using signed URL tokens](/images/serve-images/serve-private-images/).
```

2024-01-18 10:02 UTC, marciocloudflare commented on content/images/serve-images/serve-from-custom-domains.md
> +Use a Cloudflare Worker to access your images and a Route using your domain to execute the worker. For an example worker, refer to [Serve private images using signed URL tokens](/images/serve-images/
There's only one example, so it doesn't make sense to have `:` and another paragraph below

2024-01-18 10:02 UTC, marciocloudflare commented on content/images/transform-images/delete-images.md
> +```curl
```suggestion
```bash
```

2024-01-18 10:02 UTC, marciocloudflare commented on content/images/transform-images/delete-variants.md
> +```curl
```suggestion
```bash
```

2024-01-18 10:02 UTC, marciocloudflare commented on content/images/transform-images/edit-images.md
> +- Use a cURL command you can use as an example to access the image.
Not sure what this means

2024-01-18 10:02 UTC, marciocloudflare commented on content/images/transform-images/enable-flexible-variants.md
> +Make a PATCH request to the [Update a variant endpoint](/api/operations/cloudflare-images-variants-update-a-variant).
```suggestion
Make a `PATCH` request to the [Update a variant endpoint](/api/operations/cloudflare-images-variants-update-a-variant).
```

2024-01-18 10:02 UTC, marciocloudflare commented on content/images/transform-images/delete-variants.md
> +Make a DELETE request to the delete variant endpoint.
```suggestion
Make a `DELETE` request to the delete variant endpoint. 
```

2024-01-18 10:02 UTC, marciocloudflare commented on content/images/transform-images/enable-flexible-variants.md
> +```curl
```suggestion
```bash
```

2024-01-18 10:02 UTC, marciocloudflare commented on content/images/transform-images/enable-flexible-variants.md
> +    --data '{"flexible_variants": true}'
```suggestion
curl -X PATCH https://api.cloudflare.com/client/v4/accounts/<ACCOUNT_ID>/images/v1/config \
    --header "Authorization: Bearer <API_TOKEN>" \
    --header "Content-Type: application/json" \
    --data '{"flexible_variants": true}'
```

2024-01-18 10:02 UTC, marciocloudflare commented on content/images/transform-images/resize-images.md
> +Make a POST request to [create a variant](/api/operations/cloudflare-images-variants-create-a-variant).
```suggestion
Make a `POST` request to [create a variant](/api/operations/cloudflare-images-variants-create-a-variant).
```

2024-01-18 10:02 UTC, marciocloudflare commented on content/images/transform-images/resize-images.md
> +```curl
```suggestion
```bash
```

2024-01-18 10:02 UTC, marciocloudflare commented on content/images/transform-images/resize-images.md
> +  -H "Content-Type: application/json" \
```suggestion
  --header "Authorization: Bearer <API_TOKEN>" \
  --header "Content-Type: application/json" \
```

2024-01-18 10:02 UTC, marciocloudflare commented on content/images/upload-images/direct-creator-upload.md
> +Make a POST request to the `direct_upload` endpoint using the example below as reference.
```suggestion
Make a `POST` request to the `direct_upload` endpoint using the example below as reference.
```

2024-01-18 10:02 UTC, marciocloudflare commented on content/images/upload-images/direct-creator-upload.md
> +```curl
```suggestion
```bash
```

2024-01-18 10:02 UTC, marciocloudflare commented on content/images/upload-images/direct-creator-upload.md
> +```curl
```suggestion
```json
```

2024-01-18 10:02 UTC, marciocloudflare commented on content/images/upload-images/direct-creator-upload.md
> +```curl
```suggestion
```bash
```

2024-01-18 10:02 UTC, marciocloudflare commented on content/images/upload-images/direct-creator-upload.md
> +```curl
```suggestion
```json
```

2024-01-18 10:02 UTC, marciocloudflare commented on content/images/upload-images/direct-creator-upload.md
> +```curl
```suggestion
```txt
```

2024-01-18 10:02 UTC, marciocloudflare commented on content/images/upload-images/direct-creator-upload.md
> +```curl
```suggestion
```txt
```

2024-01-18 10:02 UTC, marciocloudflare commented on content/images/upload-images/upload-URL.md
> +```curl
```suggestion
```bash
```

2024-01-18 10:02 UTC, marciocloudflare commented on content/images/upload-images/upload-URL.md
> +```curl
```suggestion
```json
```

2024-01-18 10:02 UTC, marciocloudflare commented on content/images/upload-images/upload-custom-path.md
> +```curl
```suggestion
```bash
```

2024-01-18 10:02 UTC, marciocloudflare commented on content/images/upload-images/upload-custom-path.md
> +```curl
```suggestion
```json
```

2024-01-18 10:02 UTC, marciocloudflare commented on content/images/upload-images/upload-URL.md
> +}
```suggestion
{
    "result": {
        "id": "2cdc28f0-017a-49c4-9ed7-87056c83901",
        "filename": "image.jpeg",
        "metadata": {
            "key": "value":
        },
        "uploaded": "2022-01-31T16:39:28.458Z",
        "requireSignedURLs": false,
        "variants": [
                "https://imagedelivery.net/Vi7wi5KSItxGFsWRG2Us6Q/2cdc28f0-017a-49c4-9ed7-87056c83901/public","https://imagedelivery.net/Vi7wi5KSItxGFsWRG2Us6Q/2cdc28f0-017a-49c4-9ed7-87056c83901/thumbnail"
        ]
        },
        "success": true,
        "errors": [],
        "messages": []
}
```

2024-01-18 10:02 UTC, marciocloudflare commented on content/images/upload-images/upload-dashboard.md
> +3. Drag and drop your image into the **Quick Upload** section or click **Drop images here** or select to browse to select your image locally.
```suggestion
3. Drag and drop your image into the **Quick Upload** section. Alternatively, you can select **Drop images here** or browse to select your image locally.
```

2024-01-18 10:34 UTC, pedrosousa commented on content/images/transform-images/edit-images.md
> +3. Locate the image you want to modify and select **Edit.**
```suggestion
3. Locate the image you want to modify and select **Edit**.
```

2024-01-18 10:38 UTC, pedrosousa commented on content/images/upload-images/direct-creator-upload.md
> + --url https://api.cloudflare.com/client/v4/accounts/<ACCOUNT_ID>/images/v2/direct_upload \
```suggestion
 https://api.cloudflare.com/client/v4/accounts/<ACCOUNT_ID>/images/v2/direct_upload \
```

2024-01-18 10:41 UTC, pedrosousa commented on content/images/upload-images/direct-creator-upload.md
> + --header 'Authorization: Bearer <API_TOKEN>'
```suggestion
curl https://api.cloudflare.com/client/v4/accounts/<ACCOUNT_ID>/images/v1/<IMAGE_ID> \
 --header 'Authorization: Bearer <API_TOKEN>'
```
The `Content-Type` header is not needed in `GET` requests, since we're not sending any `--data`.

2024-01-18 10:45 UTC, pedrosousa commented on content/images/upload-images/direct-creator-upload.md
> +<body>
```suggestion
<!DOCTYPE html>
<html>
<body>
```
We're missing some content at the top (the `</html>` tag is being closed, but it's not included at the start). 
Added a common default for HTML5 files.

2024-01-18 10:47 UTC, pedrosousa commented on content/images/upload-images/upload-URL.md
> +Make a `POST` request using the example below as reference. Keep in mind that the `--form ‘file=’` and `--form ‘url=’` fields are mutually exclusive.
```suggestion
Make a `POST` request using the example below as reference. Keep in mind that the `--form 'file=<FILE>'` and `--form 'url=<URL>'` fields are mutually exclusive.
```
Replace curly quotes and add a placeholder.

2024-01-18 10:47 UTC, pedrosousa commented on content/images/upload-images/upload-custom-path.md
> +- Up to 1024 characters.
```suggestion
- Up to 1,024 characters.
```

2024-01-18 16:01 UTC, marciocloudflare approved these changes

2024-01-19 16:59 UTC, merged