Added useful info when using WARP on a tightly-firewalled corporate network
cloudflare/cloudflare-docs pull request #12509
Opened 2024-01-13 03:45 UTC by jamie-sandbox

Added useful info learned from hours of debugging and reverse-engineering when setting up WARP on a tightly-firewalled corporate network.

2024-01-29 16:31 UTC, ranbel commented
@dh-cf

2024-02-12 01:34 UTC, jamie-sandbox commented
Any progress on this?
________________________________
From: ranbel ***@***.***>
Sent: 29 January 2024 4:31 PM
To: cloudflare/cloudflare-docs ***@***.***>
Cc: jamie-sandbox ***@***.***>; Author ***@***.***>
Subject: Re: [cloudflare/cloudflare-docs] Added useful info when using WARP on a tightly-firewalled corporate network (PR #12509)


@dh-cf<https://github.com/dh-cf>

—
Reply to this email directly, view it on GitHub<https://github.com/cloudflare/cloudflare-docs/pull/12509#issuecomment-1915080069>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/BEHRKDBWUHZ5RAQVI7RJRLDYQ7FGTAVCNFSM6AAAAABBZAM7TSVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSMJVGA4DAMBWHE>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2024-02-12 15:27 UTC, ranbel commented
This PR is awaiting a technical review from the WARP team.

2024-04-04 16:21 UTC, ranbel commented
@aw-cf Could someone on your team help review this PR?

2024-04-04 17:57 UTC, kkrum requested changes
cc @ranbel added some comments based on discussion with engineering team.

2024-04-04 17:57 UTC, kkrum commented on content/cloudflare-one/connections/connect-devices/warp/deployment/firewall.md
> +In order to allow the network connectivity tests within the WARP GUI to function reliably, you will also need to allow the userspace GUI to generate network traffic:
This is a good addition we should keep

2024-04-04 17:57 UTC, kkrum commented on content/cloudflare-one/connections/connect-devices/warp/deployment/firewall.md
> +- `engage.cloudflareclient.com` verifies general Internet connectivity outside of the WARP tunnel. These requests are always sent directly and will not use a proxy server, even if one is configured f
Pending our QA team checking re the proxy comment. We aren't doing anything special here so need to investigate if this is specific to certain configurations or if this is just how Windows decides to handle things.

We should document that the ips engage.cloudflareclient.com use though are whatever WARP Ingress IP we connect to. It isn't always what is in this PR, but could be anything in the WARP Ingress IPv4/24 or IPv6/48 range

2024-04-04 17:57 UTC, kkrum commented on content/cloudflare-one/connections/connect-devices/warp/deployment/firewall.md
> +DoH requests are always sent directly and will not use a proxy server, even if one is configured for the system.
Lets leave this out for now

2024-04-04 17:57 UTC, kkrum commented on content/cloudflare-one/connections/connect-devices/warp/deployment/firewall.md
> +Once the tunnel has been established, communication with the API will take place **inside the tunnel**, unless a proxy configuration (e.g. PAC file) says otherwise.
This is inaccurate. Orchestration API and DoH traffic is *always* outside the tunnel.

2024-04-04 17:57 UTC, kkrum commented on content/cloudflare-one/connections/connect-devices/warp/deployment/firewall.md
> +Prior to connection, the WARP client talks with our edge via a standard HTTPS connection **outside the tunnel** for operations like registration and settings changes.
Lets hold off on this for now

2024-04-04 17:57 UTC, kkrum commented on content/cloudflare-one/connections/connect-devices/warp/deployment/firewall.md
> +Connections to the API will honour the system proxy settings (if configured), however it is recommended that the connections bypass any proxy and are allowed to be made directly. In this case you mus
Lets hold off on this for now

2024-05-22 22:15 UTC, ranbel commented
addressed in #14682

2024-05-22 22:15 UTC, closed without merging