pages: update next.js framework guide
cloudflare/cloudflare-docs pull request #12506
Opened 2024-01-12 21:25 UTC by admah

2024-01-12 22:55 UTC, IgorMinar requested changes
Thanks @admah for putting this together. I gave it a read and I'm suggesting a few changes and removal of a bunch of obsolete content.

2024-01-12 22:55 UTC, IgorMinar commented on content/pages/framework-guides/deploy-a-nextjs-site.md
> +The following steps are only applicable to projects that have not been created and deployd via create-cloudflare.
```suggestion
The following steps are only applicable to projects that have not been created and deployed via create-cloudflare.
```

2024-01-12 22:55 UTC, IgorMinar commented on content/pages/framework-guides/deploy-a-nextjs-site.md
> +## Consider if you need the Edge Runtime
I don't believe we want this section at all. Or rather we should directly say that only edge runtime routes are supported.

2024-01-12 22:55 UTC, IgorMinar commented on content/pages/framework-guides/deploy-a-nextjs-site.md
> +From within the project directory, you'll also need to create a new repo for your project.
you'll also need to add the next-on-pages package and update next.config.js

2024-01-12 22:55 UTC, IgorMinar commented on content/pages/framework-guides/deploy-a-nextjs-site.md
> +From within the project directory, you'll also need to create a new repo for your project.
I suggest you drop this and instead simply point to https://github.com/cloudflare/next-on-pages/tree/main/packages/next-on-pages#cloudflarenext-on-pages which documents the whole process of onboarding existing apps.

2024-01-12 22:55 UTC, IgorMinar commented on content/pages/framework-guides/deploy-a-nextjs-site.md
>  The default template uses traditional Node.js-powered routes that are not supported on Cloudflare Pages. To run your application, you need to opt into the Edge Runtime for any routes that have server
again, this is either done by C3 automatically or is part of next-on-pages instructions, so I'd drop it from here.

2024-01-12 22:55 UTC, IgorMinar commented on content/pages/framework-guides/deploy-a-nextjs-site.md
> +To deploy your application to Cloudflare Pages via the Cloudflare Dashboard, you need to install the `@cloudflare/next-on-pages` package into your project. This library builds your Next.js project in
This repeats what has already been done above. Remove the whole section?

2024-01-12 22:55 UTC, IgorMinar commented on content/pages/framework-guides/deploy-a-nextjs-site.md
> +## Deploy via a static export
This whole section talks about SSG mode of Next which is how Pages originally supported Next, we updated the doc above to support the normal fullstack mode, so I suggest you drop this section completely.

2024-01-12 22:55 UTC, IgorMinar commented on content/pages/framework-guides/deploy-a-nextjs-site.md
>  To deploy your site to Pages:
This section is still focused on SSG deployments. I suggest we simplify it and say that you can either deploy the app by running `wrangler pages:deploy` or by connecting the git repository to our CI/CD via the Cloudflare Dash.

2024-01-12 22:55 UTC, IgorMinar commented on content/pages/framework-guides/deploy-a-nextjs-site.md
> +There are two ways to interact with Cloudflare bindings: locally and remotely.
There is just one way to access the bindings and that's via process.env as documented below. There are two ways to set up bindings, one way for local development and one way for production deployment. Could you please update this section?

2024-01-16 22:35 UTC, admah commented on content/pages/framework-guides/deploy-a-nextjs-site.md
> +## Consider if you need the Edge Runtime
I've removed this section, and left a part at the top of the docs that says this page is for `a full-stack Next.js project which uses the Edge Runtime`

2024-01-16 22:36 UTC, admah commented on content/pages/framework-guides/deploy-a-nextjs-site.md
> +From within the project directory, you'll also need to create a new repo for your project.
I've added the link to that README in a small section.

2024-01-16 22:36 UTC, admah commented on content/pages/framework-guides/deploy-a-nextjs-site.md
>  The default template uses traditional Node.js-powered routes that are not supported on Cloudflare Pages. To run your application, you need to opt into the Edge Runtime for any routes that have server
I've removed this from the doc.

2024-01-16 22:36 UTC, admah commented on content/pages/framework-guides/deploy-a-nextjs-site.md
> +To deploy your application to Cloudflare Pages via the Cloudflare Dashboard, you need to install the `@cloudflare/next-on-pages` package into your project. This library builds your Next.js project in
Removed.

2024-01-16 22:37 UTC, admah commented on content/pages/framework-guides/deploy-a-nextjs-site.md
> +There are two ways to interact with Cloudflare bindings: locally and remotely.
I've rewritten this section with your suggestions. Thanks!

2024-01-16 23:11 UTC, dario-piotrowicz reviewed
I'm adding js examples for accessing bindings for the various frameworks, including Next.js, here: https://github.com/cloudflare/cloudflare-docs/pull/12178

I thought it'd be worth mentioning it here, but my changes there don't necessarily need to be included here or block this PR, I am totally fine if this PR gets merged first and then I solve the merge conflicts in mine 🙂

2024-01-16 23:11 UTC, dario-piotrowicz commented on content/pages/framework-guides/deploy-a-nextjs-site.md
> +The following steps are only applicable to projects that have not been created and deployed via create-cloudflare.
I find the wording quite confusing as there aren't any "steps" here 😕

2024-01-16 23:11 UTC, dario-piotrowicz commented on content/pages/framework-guides/deploy-a-nextjs-site.md
> +If you already have a Next.js project or wish to manually create and deploy one, we recommend that you use `@cloudflare/next-on-pages`. Its [README](https://github.com/cloudflare/next-on-pages/tree/m
```suggestion
If you already have a Next.js project or wish to manually create and deploy one without using c3, we recommend that you use `@cloudflare/next-on-pages` and refer to its [README](https://github.com/cloudflare/next-on-pages/tree/main/packages/next-on-pages#cloudflarenext-on-pages) for instructions and additional information to help you develop and deploy your project. 
```

With these changes we could get read of the note above, couldn't we?

2024-01-16 23:11 UTC, dario-piotrowicz commented on content/pages/framework-guides/deploy-a-nextjs-site.md
> +## Use bindings in your Next.js application
C3 now already does some setup for the user: https://github.com/cloudflare/workers-sdk/pull/4688

So maybe it'd be valuable to mention that here?

2024-01-16 23:11 UTC, dario-piotrowicz commented on content/pages/framework-guides/deploy-a-nextjs-site.md
> +### Access bindings remotely
Access bindings remotely makes me think of running wrangler locally and getting access to the bindings in production 🤔 

wouldn't it be clearer to have something like:
```suggestion
### Access bindings in the deployed application
```
or something along these lines?

2024-01-16 23:14 UTC, dario-piotrowicz commented
@admah do you think we could include the [recommended workflow](https://github.com/cloudflare/next-on-pages/blob/main/internal-packages/next-dev/README.md#recommended-workflow) somewhere here in the guide?

I would really like that as I think that warning developers not to only rely on `dev` is very valuable as that could easily trip them and generate lots of confusion

2024-01-16 23:25 UTC, admah commented on content/pages/framework-guides/deploy-a-nextjs-site.md
> +## Use bindings in your Next.js application
I've added a note about  the default `env.d.ts`.

2024-01-16 23:25 UTC, admah commented on content/pages/framework-guides/deploy-a-nextjs-site.md
> +If you already have a Next.js project or wish to manually create and deploy one, we recommend that you use `@cloudflare/next-on-pages`. Its [README](https://github.com/cloudflare/next-on-pages/tree/m
I removed that note and updated this section.

2024-01-17 12:52 UTC, dario-piotrowicz approved these changes
The changes look good to me 😄 

Thanks @admah 💪

2024-01-17 12:52 UTC, dario-piotrowicz commented on content/pages/framework-guides/deploy-a-nextjs-site.md
> +  `next-dev` submodule.
```suggestion
  In order to have a very fast and polished dev experience the standard dev server provided by Next.js is the best available option. So use it to quickly make changes and iterate over them, while still having access to your Cloudflare bindings thanks to the `next-dev` submodule (as described in the [local bindings section](#set-up-local-bindings) above).
```

2024-01-17 12:52 UTC, dario-piotrowicz commented on content/pages/framework-guides/deploy-a-nextjs-site.md
> +  In order to make sure that your application is being built in a manner that is fully compatible with Cloudflare Pages, before deploying it, or whenever you're comfortable checking the correctness o
```suggestion
  In order to make sure that your application is being built in a manner that is fully compatible with Cloudflare Pages, before deploying it, or whenever you're comfortable checking the correctness of the application during your development process, build your worker by using `@cloudflare/next-on-pages` and preview it locally via `wrangler pages dev .vercel/output/static --compatibility-flag=nodejs_compat`, this is the only way to locally make sure that everything is working as you expect it to.
```

2024-01-17 15:56 UTC, IgorMinar commented on content/pages/framework-guides/deploy-a-nextjs-site.md
> +  In order to make sure that your application is being built in a manner that is fully compatible with Cloudflare Pages, before deploying it, or whenever you're comfortable checking the correctness o
> this is the only way to locally make sure that everything is working as you expect it to.

This sounds a bit unnecessarily scary. Please consider rephrasing with something like "Running your application with `wrangler pages dev` has higher edit & refresh latency, but it more faithfully matches the deployed production environment, allowing you to test and verify your application locally and catch any potential compatibility issues before you deploy."

2024-01-17 15:58 UTC, admah commented on content/pages/framework-guides/deploy-a-nextjs-site.md
> +  In order to make sure that your application is being built in a manner that is fully compatible with Cloudflare Pages, before deploying it, or whenever you're comfortable checking the correctness o
I actually updated that line to be:

`By doing this, you can run your site locally to make sure everything is working as you expect it to.`

2024-01-17 15:59 UTC, IgorMinar commented on content/pages/framework-guides/deploy-a-nextjs-site.md
> +  In order to make sure that your application is being built in a manner that is fully compatible with Cloudflare Pages, before deploying it, or whenever you're comfortable checking the correctness o
oh.. I see. this diff is outdated. please disregard the comment above.

2024-01-17 16:01 UTC, IgorMinar approved these changes
a few small tweaks. the rest looks great now. thanks for all the updates.

2024-01-17 16:01 UTC, IgorMinar commented on content/pages/framework-guides/deploy-a-nextjs-site.md
> +  By doing this, you can run your site locally to make sure everything is working as you expect it to.
```suggestion
  By doing this, you can run your app locally to make sure everything is working as you expect it to.
```

2024-01-17 16:01 UTC, IgorMinar commented on content/pages/framework-guides/deploy-a-nextjs-site.md
> +  In order to make sure that your application is being built in a manner that is fully compatible with Cloudflare Pages, before deploying it, or whenever you're comfortable checking the correctness o
```suggestion
  In order to make sure that your application is being built in a manner that is fully compatible with Cloudflare Pages, before deploying it, or whenever you're comfortable checking the correctness of the application during your development process you'll want to build your worker and preview it locally using Cloudflare's `workerd` JavaScript runtime. 
```

2024-01-19 18:24 UTC, deadlypants1973 requested changes

2024-01-19 18:24 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-nextjs-site.md
> +The fastest way to create a new Next.js site and deploy it to Cloudflare is open up your terminal and run:
```suggestion
To create a new Next.js site, open up your terminal and run:
```

2024-01-19 18:24 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-nextjs-site.md
> +- allow you to deploy your new project
Can we replace this with whether or not we want them to deploy the project at this step?

2024-01-19 18:24 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-nextjs-site.md
> +- allow you to setup a new git repo
Can we replace this with whether or not we want the user to setup a new Git repository at this step?

2024-01-19 18:24 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-nextjs-site.md
> +## Manually configure and deploy your project
```suggestion
## Configure and deploy your project
```

2024-01-19 18:24 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-nextjs-site.md
> +If you already have a Next.js project or wish to manually create and deploy one without using c3, we recommend that you use `@cloudflare/next-on-pages` and refer to its [README](https://github.com/cl
This should move to the top of this guide. Also, this section is titled 'deploy your project' but there are no deployment instructions. This needs to be fixed. Do we want the user to deploy first or preview their site first?

2024-01-19 18:24 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-nextjs-site.md
> +Every time you commit new code to your Next.js site, Cloudflare Pages will automatically rebuild your project and deploy it. You will also get access to [preview deployments](/pages/configuration/pre
```suggestion
After deploying your site, you will receive a unique `*.pages.dev` subdomain for your project.

Every time you commit new code to your Next.js site, Cloudflare Pages will automatically rebuild your project and deploy it. You will also get access to [preview deployments](/pages/configuration/preview-deployments/) on new pull requests, so you can preview how changes look to your site before deploying them to production.
```

2024-01-19 18:24 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-nextjs-site.md
> +Projects created with create-cloudflare have local bindings set up by default.
```suggestion
Projects created with C3 have local bindings set up by default.
```

2024-01-19 18:24 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-nextjs-site.md
> +For example to work with a KV binding locally, you need to open `next.config.js` and add:
```suggestion
For example, to work with a KV binding locally, you need to open `next.config.js` and add:
```
Is `next.config.js` a file automatically generated when you create a Next project with C3?

2024-01-19 18:24 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-nextjs-site.md
> +// (note: this check is recommended but completely optional)
Is utility the correct word here? -> function

2024-01-19 18:24 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-nextjs-site.md
> +To access bindings in your deployed application, you'll first need to [configure](/workers/configuration/bindings/) any necessary bindings and connect them to your project via your project's settings
```suggestion
To access bindings in your deployed application, first [configure](/workers/configuration/bindings/) any necessary bindings and connect them to your project via your project's settings page in the Cloudflare dashboard.
```
Why are we linking to Workers docs here? Cloud be wrong but Pages projects won't use a wrangler.toml set up bindings, will they? I thought they have a different process. Are the docs in Pages Functions more relevant to this?

2024-01-19 18:24 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-nextjs-site.md
> +## Use the create-cloudflare CLI (C3)
```suggestion
## Use the `create-cloudflare` CLI (C3)
```

2024-01-19 18:24 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-nextjs-site.md
> +Cloudflare bindings must be set up for local and remote development.
Can we link a guide or page that we can link here in [local and remote development.]?

2024-01-19 18:24 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-nextjs-site.md
> +Projects created with create-cloudflare have local bindings set up by default.
1) Are they 'local bindings' or are they bindings that are set up for local use? Difference being, if they are the former, then are they bindings you only use locally? 

2) In what file are they set up by default? We should state this.

2024-01-19 18:24 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-nextjs-site.md
> +To set up bindings for use in local development, you will use the `setupDevBindings` function provided by [`@cloudflare/next-on-pages/next-dev`](https://github.com/cloudflare/next-on-pages/tree/main/
The sentence before this makes it sound like the bindings are already set up but this sentence says 'to set up...'. Are the bindings already set up or do you need to set them up? Clarity needed here.

2024-01-19 18:24 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-nextjs-site.md
> +        id: "MY_KV",
```suggestion
        type: "kv",
        id: "MY_KV",
```
We should explain what these two keys are. "MY_KV" doesn't make it clear that this is an ID you need to pull from your KV.

And does 'type' here replace 'binding'? Wrangler config that I am familair with looks different: https://developers.cloudflare.com/workers/wrangler/configuration/#kv-namespaces

2024-01-19 18:24 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-nextjs-site.md
> +You should then be able to access the binding in your code via `process.env` like this:
```suggestion
You should then be able to access the ___ binding in your code via `process.env` like this:
```
Name the example binding for user clarity.

2024-01-19 18:24 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-nextjs-site.md
> +Then, the binding can be accessed directly from `process.env`:
This code block uses the same example KV binding as in the previous section. Let's state explicitly for the user that this is what the following example is doing.

2024-01-19 18:24 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-nextjs-site.md
> +Projects created with create-cloudflare have a default `env.d.ts` file.
```suggestion
Projects created with `create-cloudflare` (C3) have a default `env.d.ts` file.
```
What directory does this file live? Is it auto generated in the first step of this guide?

2024-01-19 18:24 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-nextjs-site.md
> +In order to get proper type support, you'll need to create a new `env.d.ts` file in your project and declare a [binding](/pages/functions/bindings/).
```suggestion
To get proper type support, create a new `env.d.ts` file in your project and declare a [binding](/pages/functions/bindings/).
```

2024-01-19 18:24 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-nextjs-site.md
> +In order to get proper type support, you'll need to create a new `env.d.ts` file in your project and declare a [binding](/pages/functions/bindings/).
Previous sentence said this file was default but now we are asking the user to create one.

2024-01-19 18:24 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-nextjs-site.md
> +The following is an example of adding a `KVNamespace` binding:
Is `KVnamespace` the name of this binding? Or is MY_KV the name of this binding?

2024-01-19 18:24 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-nextjs-site.md
> +When developing a `next-on-pages` application, this is the development workflow that we recommend:
```suggestion
When developing a `next-on-pages` application, this is the development workflow that Cloudflare recommends:
```

2024-01-19 18:24 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-nextjs-site.md
> +- **Develop using the standard Next.js dev server**\
```suggestion
### Develop using the standard Next.js dev server
```

2024-01-19 18:24 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-nextjs-site.md
> +  In order to have a very fast and polished dev experience the standard dev server provided by Next.js is the best available option. So use it to quickly make changes and iterate over them, while sti
```suggestion

The [standard development server provided by Next.js]() is the best available option for a fast and polished development experience. The `next-dev` submodule (as described in the [local bindings section](#set-up-local-bindings) above makes it possible to use Next.js' standard development server while still having access to your Cloudflare bindings.
```
Let's link to what we are talking about here: [standard development server provided by Next.js](). This seems like something Next.js provides that we haven't explained in this doc.

2024-01-19 18:24 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-nextjs-site.md
> +  In order to make sure that your application is being built in a manner that is fully compatible with Cloudflare Pages, before deploying it, or whenever you're comfortable checking the correctness o
```suggestion
### Build and preview your worker locally

To make sure that your application is being built in a manner that is fully compatible with Cloudflare Pages, before deploying it, or whenever you're comfortable checking the correctness of the application during your development process you'll want to build your worker and preview it locally using Cloudflare's `workerd` JavaScript runtime. 
```
As a reader, I'm a bit lost here. How do Workers relate to this guide? This subtitle says "Worker", is that intentional? Also, this is a long run-on sentence, can we revise this part?

2024-01-19 18:24 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-nextjs-site.md
> +  By doing this, you can run your app locally to make sure everything is working as you expect it to.
```suggestion
If you have created your project with C3, you can do this by running `npm run pages:build && npm run pages:dev`. 
  
If you have created your project manually, you will need to run `npx @cloudflare/next-on-pages --watch` and preview it by running `wrangler pages dev .vercel/output/static --compatibility-flag=nodejs_compat`. 
  
By doing this, you can run your application locally to make sure everything is working as you expect it to.
```
1) What is the connection between the previous sentence about Workers and this section about Pages which seems to be about running Pages builds?
2) "By doing this" -> can we change "this" to describing what the proper action the user is taking?

2024-01-19 18:24 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-nextjs-site.md
> +  Once you've previewed your application locally then you can deploy it to Cloudflare Pages (both via direct uploads or git integration) and iterate over the process to make new changes.
```suggestion
### Deploy your application and iterate

After you have previewed your application locally, you can deploy it to Cloudflare Pages (both via Direct Uploads or Git integration) and iterate over the process to make new changes.
```
Link to Direct Upload docs, it is the first time they are being mentioned on this page.

2024-01-22 14:57 UTC, admah commented on content/pages/framework-guides/deploy-a-nextjs-site.md
> +## Manually configure and deploy your project
I wanted this to be different from C3, where you are led through a tool to configure and deploy your project. 

I wonder if just having "Configure and deploy your project" will make users think this is mandatory.

2024-01-22 14:59 UTC, admah commented on content/pages/framework-guides/deploy-a-nextjs-site.md
> +If you already have a Next.js project or wish to manually create and deploy one without using c3, we recommend that you use `@cloudflare/next-on-pages` and refer to its [README](https://github.com/cl
We want C3 to be the first option users are presented with, since it sets everything up for them. 

Users have to deploy before they can preview.

2024-01-23 22:49 UTC, dario-piotrowicz requested changes

2024-01-23 22:49 UTC, dario-piotrowicz commented on content/pages/framework-guides/deploy-a-nextjs-site.md
> +After creating your project, a new `my-next-app` directory will be generated using the official default template, and will be fully compatible with Cloudflare.
I find this sentence a bit ambiguous, I think it would be nice to clarify that there is no "cloudflare official Next.js template" but that we take what we get from the next cli and tweak it for Cloudflare 🤔 
```suggestion
After creating your project, a new `my-next-app` directory will be generated using the the default Next.js template, tweaked to be fully compatible with Cloudflare Pages.
```

2024-01-23 22:49 UTC, dario-piotrowicz commented on content/pages/framework-guides/deploy-a-nextjs-site.md
> +Every time you commit new code to your Next.js site, Cloudflare Pages will automatically rebuild your project and deploy it. You will also get access to [preview deployments](/pages/configuration/pre
```suggestion
Every time you commit new code to your git repository, Cloudflare Pages will automatically rebuild your project and deploy it. You will also get access to [preview deployments](/pages/configuration/preview-deployments/) on new pull requests, so you can preview how changes look to your site before deploying them to production.
```

2024-01-23 22:49 UTC, dario-piotrowicz commented on content/pages/framework-guides/deploy-a-nextjs-site.md
> +## Preview your site
Something is missing in this whole section, it only applies if you use the git Pages integration (which is also kind of incompatible with C3) I do believe we need to mention that this only applies to apps which use the git integration (and maybe also mention the incompatibility with C3?)

2024-01-23 22:51 UTC, dario-piotrowicz commented on content/pages/framework-guides/deploy-a-nextjs-site.md
> +Cloudflare bindings must be set up for local and remote development.
can't "must be set up" give the wrong impression to people here and make them think that they do need to set up bindings even if they don't plan on using them? 🤔

2024-01-23 22:52 UTC, dario-piotrowicz commented on content/pages/framework-guides/deploy-a-nextjs-site.md
> +// we only need to use the utility during development so we can check NODE_ENV
In this code snipper we're missing the file name and highlights 🙂

2024-01-23 22:56 UTC, dario-piotrowicz commented on content/pages/framework-guides/deploy-a-nextjs-site.md
> +In orer to access bindings in a deployed application, you will need to [configure](/pages/functions/bindings/) any necessary bindings and connect them to your project via your project's settings page
what about including a deep link here?
(`https://dash.cloudflare.com/?to=/:account/pages/view/:pages-project/settings/`)

2024-01-23 22:57 UTC, admah commented on content/pages/framework-guides/deploy-a-nextjs-site.md
> +Every time you commit new code to your Next.js site, Cloudflare Pages will automatically rebuild your project and deploy it. You will also get access to [preview deployments](/pages/configuration/pre
Updated

2024-01-23 22:58 UTC, admah commented on content/pages/framework-guides/deploy-a-nextjs-site.md
> +## Preview your site
I added "(git connected)" to the heading. The line "Every time you commit new code to your git repository" is also in the section. Is that enough?

2024-01-23 22:58 UTC, admah commented on content/pages/framework-guides/deploy-a-nextjs-site.md
> +Cloudflare bindings must be set up for local and remote development.
I've reworded this.

2024-01-23 22:58 UTC, admah commented on content/pages/framework-guides/deploy-a-nextjs-site.md
> +// we only need to use the utility during development so we can check NODE_ENV
I added the filename and highlight.

2024-01-23 23:00 UTC, admah commented on content/pages/framework-guides/deploy-a-nextjs-site.md
> +In orer to access bindings in a deployed application, you will need to [configure](/pages/functions/bindings/) any necessary bindings and connect them to your project via your project's settings page
This link only sends me to the overview page. I'm guessing because I don't have a `:pages-project` set. How can we know what that value might be?

2024-01-23 23:12 UTC, dario-piotrowicz commented on content/pages/framework-guides/deploy-a-nextjs-site.md
> +In orer to access bindings in a deployed application, you will need to [configure](/pages/functions/bindings/) any necessary bindings and connect them to your project via your project's settings page
in the overview page, don't you see the `select a project` banner?
![Screenshot 2024-01-23 at 23 10 45](https://github.com/cloudflare/cloudflare-docs/assets/61631103/74d3066a-2d3d-40a7-b0c5-cb4873bb29d7)

If you select one then you get redirected to that project's settings page

But yeah if this is not too clear maybe we should avoid it not to confuse people?

2024-01-23 23:17 UTC, dario-piotrowicz commented on content/pages/framework-guides/deploy-a-nextjs-site.md
> +## Preview your site
I don't think it's really enough and that we should maybe be as clear as possible here 😕 

The problem is that you can have C3 and also have a git repository so the "Every time you commit new code to your git repository" can also apply (wrongly) to that scenario no? (like someone wrongly thinking that C3 installs a git hook or something for auto deployments on push?)

2024-01-25 10:36 UTC, deadlypants1973 reviewed
Removing request changes

2024-01-25 10:37 UTC, deadlypants1973 approved these changes

2024-01-25 10:41 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-nextjs-site.md
> +- allow you to setup a new git repo
C3 doesn't allow you to set up a new Git repo.

2024-01-25 15:48 UTC, merged