chore: clarify context.waitUntil() logic for frequently asked questions
cloudflare/cloudflare-docs pull request #12524
Opened 2024-01-15 19:57 UTC by nora-soderlund

2024-01-16 05:58 UTC, irvinebroque requested changes

2024-01-16 05:58 UTC, irvinebroque commented on content/workers/runtime-apis/handlers/fetch.md
> +Calling `waitUntil()` several times is acceptable and works similarly to `Promise.allSettled` where even if a previous promise is rejected, proceeding promises will continue.
```suggestion
You can call `waitUntil()` multiple times. Similar to `Promise.allSettled`, even if a promise passed to one `waitUntil` call is rejected, promises passed to other `waitUntil()` calls will still continue to execute.
```

2024-02-22 15:41 UTC, jasnell approved these changes

2024-02-22 15:52 UTC, irvinebroque approved these changes

2024-02-22 15:52 UTC, merged