Milan/hibernation tags timeout
cloudflare/cloudflare-docs pull request #12543
Opened 2024-01-16 20:41 UTC by MellowYarker

We introduced the following methods:
- state.getTags()
- state.getHibernatableWebSocketEventTimeout()
- state.setHibernatableWebSocketEventTimeout()

DO NOT MERGE until next release of Workers goes out.

---

Re-opening the PR because it didn't add the rendered docs.

2024-01-17 14:03 UTC, Maddy-Cloudflare requested changes

2024-01-17 14:03 UTC, Maddy-Cloudflare commented on content/durable-objects/api/websockets.md
> +  - Returns an Array of tags associated with the given WebSocket. Throws if you have not called `state.acceptWebSocket()` on the given WebSocket.
```Throws if you have not called `state.acceptWebSocket()` on the given WebSocket.```

"Throws" what? Can you be more specific here?

2024-01-17 14:03 UTC, Maddy-Cloudflare commented on content/durable-objects/api/websockets.md
> +  - Sets the maximum amount of milliseconds a WebSocket event (see handler methods below) can run for.
```suggestion
  - Sets the maximum amount of milliseconds a WebSocket event (refer to the handler methods below) can run for.
```

2024-01-17 14:03 UTC, Maddy-Cloudflare commented on content/durable-objects/api/websockets.md
> +  - The maximum value of `timeout` is 604,800,000 ms -- i.e. 7 days.
```suggestion
  - The maximum value of `timeout` is 604,800,000 ms, meaning 7 days.
```

2024-01-17 14:08 UTC, XoL1507 reviewed
https://github.com/MystenLabs/sui/commit/fba929cc8a5dcb7ceb5663ceee43bba00b4670d1

2024-01-24 10:40 UTC, Maddy-Cloudflare approved these changes

2024-01-24 14:36 UTC, jqmmes approved these changes
LGTM

2024-02-05 16:41 UTC, merged