first draft
cloudflare/cloudflare-docs pull request #12701
Opened 2024-01-26 16:46 UTC by jason-cf

2024-01-30 12:43 UTC, hannes-cf commented on content/fundamentals/setup/manage-domains/connect-your-domain.md
> +# Connect your domain
I think I'd prefer another term instead of "connect".

Technically, you delegate your domain to Cloudflare's authoritative nameservers. The term "connect" isn't really used in DNS land.

I am aware that this is not all about DNS, but also about proxy features. So what about "Onboarding your domain"?

2024-01-30 12:43 UTC, hannes-cf commented on content/fundamentals/setup/manage-domains/connect-your-domain.md
> +This guide reviews the concepts behind connecting your domain using Cloudflare as an Authoritative DNS provider.
Same comment about "connecting" here.

2024-01-30 12:49 UTC, hannes-cf commented on content/fundamentals/setup/manage-domains/connect-your-domain.md
> +To get started with Cloudflare as a [reverse proxy](https://www.cloudflare.com/learning/cdn/glossary/reverse-proxy/), you must first create an account and connect your domain. After creating your acc
```
which informs Cloudflare where to forward requests.
```
This is only true for proxied DNS records and also only for HTTP requests (some folks refer to DNS queries as requests, too, that's why I'm saying this).

On the DNS side, we always only just respond to DNS queries no matter the proxy status. If proxied, we respond with Cloudflare anycast IPs, if grey-clouded, we respond with origin IP/hostname. I feel like this central concept should be more baked into everywhere we talk about proxying.

2024-01-30 12:51 UTC, hannes-cf commented on content/fundamentals/setup/manage-domains/connect-your-domain.md
> +Your configurations only affect live traffic when the domain status is active and your traffic is [proxied](#proxy-eligibility).
```
(...) and your traffic is proxied.
```
Might be useful to add a bit more here. Something like
```
By enabling the proxy status on the DNS records for the hostnames you want to proxy through Cloudflare's network.
```
I don't know, probably phrase it differently, my point is again to ensure what "proxying traffic" means.

2024-01-30 12:52 UTC, hannes-cf commented on content/fundamentals/setup/manage-domains/connect-your-domain.md
> +Proxy eligibility is based on whether the record serves `HTTP` or `HTTPS` traffic. By default, `A`, `AAAA`, and `CNAME` DNS records that serve `HTTP/S` traffic are proxied.
```
(...) that serve `HTTP/S` traffic are proxied.
```
I know the default proxy status is proxied for these record types, but we should maybe phrase this like
```
(...) that serve `HTTP/S` traffic can be proxied.
```

2024-01-30 12:54 UTC, hannes-cf commented on content/fundamentals/setup/manage-domains/connect-your-domain.md
> +The following types of DNS records may be in your DNS configuration, but cannot be proxied:
Nit: I know `DS` and `DNSKEY` are both important for DNSSEC, and `SVCB` and `HTTPS` are connected somehow, too, but I think listing them in a separate line is probably better.

2024-01-30 12:57 UTC, hannes-cf commented on content/fundamentals/setup/manage-domains/connect-your-domain.md
> +Most importantly, if a records proxy is enabled, Cloudflare will respond with an [anycast IP address](/fundamentals/concepts/cloudflare-ip-addresses/), **not** the value defined in your DNS table. Th
```
Most importantly, if the proxy status for a record is enabled,
```

```
This approach informs DNS recursors that the incoming HTTP request should (...)
```
But actually it informs the end device, the recursor has no idea what an anycast IP means and that that lead to HTTP traffic being proxied, they just stupidly resolve records.
```
(...) the DNS record's actual IP address, or CNAME target. 
```
not sure if `CNAME target` is much better, but it should indicate that it's about the value of a CNAME record and not the record itself. Maybe `the DNS record's actual content, e.g. an IP address or a hostname`.

2024-01-30 12:58 UTC, hannes-cf commented on content/fundamentals/setup/manage-domains/connect-your-domain.md
> +Cloudflare is both a DNS server and a [reverse proxy](https://www.cloudflare.com/learning/cdn/glossary/reverse-proxy/) that sits between two distinct networks and depending the proxy status, Cloudfla
Nit: 
```
Cloudflare is both an authoritative DNS server and (...)
```

2024-01-30 13:00 UTC, hannes-cf commented on content/fundamentals/setup/manage-domains/connect-your-domain.md
> +When the browser initiates a `HTTP/S` request to `shop.example.com`, a DNS resolver will convert the hostname into an IP address. Since the records proxy function is `DNS only`, Cloudflare will simpl
Nit:
```
Since the record's proxy status is (...)
```

2024-01-30 13:02 UTC, hannes-cf commented on content/fundamentals/setup/manage-domains/connect-your-domain.md
> +In a full setup, your domain will be pending until you update its nameservers at your domain registrar with the assigned Cloudflare nameservers. This step is essential for two reasons. First, to info
```
First, to inform DNS resolvers where they can get a response for DNS queries for your domain (...)
```

```
to change the domain's nameservers.
```

2024-01-30 13:03 UTC, hannes-cf commented on content/fundamentals/setup/manage-domains/connect-your-domain.md
> +Registrars take up to 24 hours to process nameserver changes (quicker in most cases). You will receive an email when your domain becomes active. While your domain is pending, your `HTTP/S` traffic is
```
While your domain is pending, your `HTTP/S` traffic is not proxied through Cloudflare (...)
```
In fact we will ignore the proxy status and respond with origin IPs/hostnames for all A/AAAA/CNAME records.

2024-01-30 13:04 UTC, hannes-cf commented on content/fundamentals/setup/manage-domains/connect-your-domain.md
> +- [Disable DNSSEC](/dns/dnssec/). DNSSEC is a security extension that ensures all DNS answers can be trusted. If nameservers are changed before disabling DNSSEC, their cryptographic signatures will n
There is a way to onboard without having to disable DNSSEC: https://developers.cloudflare.com/dns/dnssec/dnssec-active-migration/

2024-01-30 15:29 UTC, jason-cf commented on content/fundamentals/setup/manage-domains/connect-your-domain.md
> +- [Disable DNSSEC](/dns/dnssec/). DNSSEC is a security extension that ensures all DNS answers can be trusted. If nameservers are changed before disabling DNSSEC, their cryptographic signatures will n
roger - will update

2024-01-30 18:39 UTC, chrisblanch39 commented
@rik ### **_

https://github.com/cloudflare/cloudflare-docs/assets/108972713/27fe98d4-e099-4228-bb7c-2e974a68364d

_**
![17066399519446193809076118205320](https://github.com/cloudflare/cloudflare-docs/assets/108972713/6dfabb31-dfcc-45e1-aa2b-f95226e2c696)

2024-01-31 19:26 UTC, abstergail commented on content/fundamentals/setup/manage-domains/connect-your-domain.md
> +# Connect your domain
This is to match the new framing of the workflow in the dashboard, and to align with the "connectivity cloud" messaging. In user research on the onboarding flow, I specifically asked about the connect framing and all participants reacted positively ([write-up here](https://wiki.cfdata.org/display/Prod/Zone+Onboarding+Content+Evaluation)).

2024-01-31 19:56 UTC, abstergail commented on content/fundamentals/setup/manage-domains/connect-your-domain.md
> +This guide reviews the concepts behind connecting your domain using Cloudflare as an Authoritative DNS provider.
I think the intro of the doc should be more broadly "Connecting your domain to Cloudflare" and what that entails, with DNS being a foundational piece. Then under a DNS section is where we bring in the "making CF your authoritative DNS provider" language and explain that DNS is foundational to the "connection."

So it would flow like this:
Intro
- value of connecting your domain to CF/that it's necessary to use our app services
- link to what is CF
Get started
- DNS setup
--- explain how DNS is foundational to app services offerings
--- most common setup is full/authoritative, but link to other setups
- Domain configuration
- Domain activation
--- Avoiding downtime 
- What to do next (related resources)
Key concepts (maybe we move these to the Concepts section, and just link to them from a quick summary on this page?)
- How CF handles DNS queries
- How CF proxies your traffic
--- Proxy eligibility
--- Proxied example
--- DNS-only example

2024-01-31 20:34 UTC, abstergail commented on content/fundamentals/setup/manage-domains/connect-your-domain.md
> +To get started with Cloudflare as a [reverse proxy](https://www.cloudflare.com/learning/cdn/glossary/reverse-proxy/), you must first create an account and connect your domain. After creating your acc
```suggestion
To get started with Cloudflare as a [reverse proxy](https://www.cloudflare.com/learning/cdn/glossary/reverse-proxy/), you must first create an account and connect your domain. 

After creating your account, select `Add site` and follow the [step-by-step tutorial](/fundamentals/setup/account-setup/add-site/) to:

1. Select a free or paid plan, which determines which Cloudflare services will apply to your proxied traffic once your domain is active
2. Set up [DNS] (/dns/). This process varies depending on the [DNS setup]((/dns/zone-setups) you choose:

- Full setup (most common): Import all DNS records
- Secondary DNS setup (Enterprise only): Set up incoming zone transfers from your primary DNS provider
- Partial (CNAME) setup (Business and Enterprise only): Import the individual DNS records you want to proxy

3. Activate your domain to start proxying HTTP/S traffic

- Full setup (most common): Change the nameservers of your domain, and wait up to 24 hours for your registrar to process the change
- Secondary DNS setup (Enterprise only): Complete the initial incoming zone transfer from your primary DNS provider
- Partial (CNAME) setup (Business and Enterprise only): Add a verification TXT record at your primary DNS provider

```

2024-01-31 21:41 UTC, abstergail commented on content/fundamentals/setup/manage-domains/connect-your-domain.md
> +Your configurations only affect live traffic when the domain status is active and your traffic is [proxied](#proxy-eligibility).
+1, think this should link either to /dns/proxied-records (with some added context there on the basics of proxying) or it should link to the Proxying traffic anchor on this page (and move the proxy eligibility section under that)

2024-01-31 21:52 UTC, abstergail commented on content/fundamentals/setup/manage-domains/connect-your-domain.md
> +Some services can be set at the account-level, which affect all domains under your account, such as the [Web Application Firewall (WAF)](/waf/).
```suggestion
Some services can be set at the account-level (if available in your domain plan), which affect all domains under your account, such as the [Web Application Firewall (WAF)](/waf/). 
```

2024-02-02 15:50 UTC, jason-cf commented on content/fundamentals/setup/manage-domains/connect-your-domain.md
> +Registrars take up to 24 hours to process nameserver changes (quicker in most cases). You will receive an email when your domain becomes active. While your domain is pending, your `HTTP/S` traffic is
@hannes-cf, only A/AAAA/CNAME records? We will not respond to any other DNS record type?

2024-02-02 15:57 UTC, hannes-cf commented on content/fundamentals/setup/manage-domains/connect-your-domain.md
> +Registrars take up to 24 hours to process nameserver changes (quicker in most cases). You will receive an email when your domain becomes active. While your domain is pending, your `HTTP/S` traffic is
Sorry, should have made myself more clear. We will respond for all DNS records, but just treat all proxied records as DNS only.

2024-02-12 15:02 UTC, abstergail reviewed
Will pick up at the-internet.md this afternoon, thanks!

2024-02-12 15:02 UTC, abstergail commented on content/fundamentals/concepts/how-cloudflare-works.md
> +In a [full setup](/dns/zone-setups/full-setup/), when you connect your domain to Cloudflare, we become your authoritative DNS provider. When Cloudflare receives a DNS query for your domain, our respo
```suggestion
In a [full DNS setup](/dns/zone-setups/full-setup/), when you [connect a domain](/fundamentals/setup/manage-domains/add-site/) to Cloudflare, we become the authoritative DNS provider for that domain. When Cloudflare receives a DNS query for your domain, our response is determined by the configuration [set in your DNS table](/dns/manage-dns-records/how-to/create-dns-records/), including the value of the record, the record's proxy eligibility, and it's [proxy status](https://developers.cloudflare.com/dns/manage-dns-records/reference/proxied-dns-records/). 
```

2024-02-12 15:02 UTC, abstergail commented on content/fundamentals/concepts/how-cloudflare-works.md
> +Most importantly, if a records proxy is enabled, Cloudflare will respond with an [anycast IP address](/fundamentals/concepts/cloudflare-ip-addresses/), **not** the value defined in your DNS table. Th
```suggestion
If a DNS record is proxied, and the [domain status](/dns/zone-setups/reference/domain-status/) is active, Cloudflare responds with an [anycast IP address](/fundamentals/concepts/cloudflare-ip-addresses/), **not** the value defined in your DNS table. This informs the end device that the request should route to Cloudflare's network, instead of directly to the origin server. In contrast, when a DNS record is set to 'DNS only', meaning the proxy is off, Cloudflare responds with the value defined in your DNS table (i.e., an IP address or CNAME record). This means HTTP/S requests go directly to the origin server and are not processed and protected by Cloudflare.
```

2024-02-12 15:02 UTC, abstergail commented on content/fundamentals/concepts/how-cloudflare-works.md
> +Most importantly, if a records proxy is enabled, Cloudflare will respond with an [anycast IP address](/fundamentals/concepts/cloudflare-ip-addresses/), **not** the value defined in your DNS table. Th
I'm not sure if "end device" is clear here, but not sure how to revise

2024-02-12 15:02 UTC, abstergail commented on content/fundamentals/concepts/how-cloudflare-works.md
> +Cloudflare is both an authoritative DNS server and a [reverse proxy](https://www.cloudflare.com/learning/cdn/glossary/reverse-proxy/) that sits between two distinct networks and depending the proxy s
```suggestion
Cloudflare is both an authoritative DNS server and a [reverse proxy](https://www.cloudflare.com/learning/cdn/glossary/reverse-proxy/) that sits between two distinct networks. Depending the [proxy status](/dns/manage-dns-records/reference/proxied-dns-records/) of individual DNS records, Cloudflare responds to DNS queries with different values. This hybrid design allows Cloudflare to respond to both DNS queries and `HTTP/S` traffic, depending on the [proxy status](/dns/manage-dns-records/reference/proxied-dns-records/) of individual hostnames, and the overall [domain status](/dns/zone-setups/reference/domain-status/).
```

2024-02-12 15:02 UTC, abstergail commented on content/fundamentals/concepts/how-cloudflare-works.md
> +You can find the proxy status of your records on the DNS records page under your domain.
```suggestion
In the Cloudflare dashboard, find the proxy status of your records on the DNS records page after selecting the domain.
```

2024-02-12 15:02 UTC, abstergail commented on content/fundamentals/concepts/how-cloudflare-works.md
> +You can find the proxy status of your records on the DNS records page under your domain.
I'm not sure how to link to the dash properly

2024-02-12 15:02 UTC, abstergail commented on content/fundamentals/concepts/how-cloudflare-works.md
> +To proxy `HTTP/S` traffic on non-standard ports or to proxy a `TCP-` or `UDP-` based application, use [Cloudflare Spectrum](/spectrum/).
```suggestion
To proxy `HTTP/S` traffic on [non-standard ports](/fundamentals/reference/network-ports/) or to proxy a `TCP-` or `UDP-` based application, use [Cloudflare Spectrum](/spectrum/). 
```

2024-02-12 15:02 UTC, abstergail commented on content/fundamentals/concepts/how-cloudflare-works.md
> +In the table above, there are two subdomain records, one with the proxy enabled, `blog`, and one without, `shop`.
```suggestion
In the table above, there are two subdomain records, one with the proxy on, `blog`, and one with the proxy off, `shop`.
```

2024-02-12 15:02 UTC, abstergail commented on content/fundamentals/concepts/how-cloudflare-works.md
> +In the table above, there are two subdomain records, one with the proxy enabled, `blog`, and one without, `shop`.
I think we're being inconsistent in using hostname or subdomain - should we pick one or does it depend on the context?

2024-02-12 15:02 UTC, abstergail commented on content/fundamentals/concepts/how-cloudflare-works.md
> +Proxy eligibility is based on whether the record serves `HTTP` or `HTTPS` traffic. By default, `A`, `AAAA`, and `CNAME` DNS records that serve `HTTP/S` traffic can be proxied.
```suggestion
Proxy eligibility is based on whether the record serves `HTTP/s` traffic, or another type of traffic. By default, `A`, `AAAA`, and `CNAME` DNS records that serve `HTTP/S` traffic can be proxied.
```

2024-02-12 15:02 UTC, abstergail commented on content/fundamentals/concepts/how-cloudflare-works.md
> +When the browser initiates a `HTTP/S` request to `blog.example.com`, a DNS resolver will convert the hostname into an IP address. Since the records proxy function is enabled, Cloudflare will return a
```suggestion
When the browser initiates a `HTTP/S` request to `blog.example.com`, a DNS resolver converts the hostname into an IP address. Since the record is proxied, Cloudflare returns an anycast IP address. Then, the browser initiates a `HTTP/S` request to Cloudflare. When Cloudflare receives this HTTP/S request, it processes the request according to the configuration of Cloudflare services for that domain and the account it sits under. Cloudflare then forwards it to the configured origin server, which in this example is `192.0.2.1`.
```

2024-02-12 15:02 UTC, abstergail commented on content/fundamentals/concepts/how-cloudflare-works.md
> +When the browser initiates a `HTTP/S` request to `shop.example.com`, a DNS resolver will convert the hostname into an IP address. Since the record's proxy status is `DNS only`, Cloudflare will simply
```suggestion
When the browser initiates a `HTTP/S` request to `shop.example.com`, a DNS resolver converts the hostname into an IP address. Since the proxy status of the record is set to `DNS only`, Cloudflare will simply return `192.0.2.2`. Then, the browser initiates a `HTTP/S` request to the server hosted at `192.0.2.2`.
```

2024-02-12 15:02 UTC, abstergail commented on content/fundamentals/concepts/how-cloudflare-works.md
> +The following types of DNS records may be in your DNS configuration, but cannot be proxied:
I still like this section and the examples below it, but think they can be moved to /dns/manage-dns-records/reference/proxied-dns-records/

2024-02-15 09:20 UTC, jason-cf commented on content/fundamentals/concepts/how-cloudflare-works.md
> +Most importantly, if a records proxy is enabled, Cloudflare will respond with an [anycast IP address](/fundamentals/concepts/cloudflare-ip-addresses/), **not** the value defined in your DNS table. Th
how about requesting entity or requesting device?

2024-02-15 09:59 UTC, jason-cf commented on content/fundamentals/concepts/how-cloudflare-works.md
> +The following types of DNS records may be in your DNS configuration, but cannot be proxied:
I've moved it

2024-02-28 14:32 UTC, abstergail commented on content/fundamentals/setup/manage-domains/connect-your-domain.md
> +Registrars take up to 24 hours to process nameserver changes (quicker in most cases). You will receive an email when your domain becomes active. While your domain is pending, your `HTTP/S` traffic is
```suggestion
Registrars take up to 24 hours to process nameserver changes (quicker in most cases). You will receive an email when your domain becomes active. While your domain is pending, your `HTTP/S` traffic is not proxying through Cloudflare, but Cloudflare will respond to DNS queries on your assigned nameservers.
```

2024-02-28 14:32 UTC, abstergail commented on content/fundamentals/setup/manage-domains/connect-your-domain.md
> +By activating your domain in full mode, your traffic will immediately start using [Cloudflare's DNS services](/fundamentals/concepts/how-cloudflare-works/#how-cloudflare-handles-dns-queries), so it's
```suggestion
By activating your domain on a full setup, your traffic will immediately start using [Cloudflare's DNS services](/fundamentals/concepts/how-cloudflare-works/#how-cloudflare-handles-dns-queries), so it's important to review how to [avoid downtime](/fundamentals/setup/manage-domains/connect-your-domain/#avoiding-downtime) and what [proxying traffic](/fundamentals/concepts/how-cloudflare-works/#proxying-traffic) means. 
```

2024-02-28 14:32 UTC, abstergail commented on content/fundamentals/setup/manage-domains/connect-your-domain.md
> +2. And second, to verify that you are the domains owner. Only the owner or administrator of a domain can access  its registrar and change its nameservers.
```suggestion
2. And second, to verify that you are the domain's owner. Only the owner or administrator of a domain can access  its registrar and change its nameservers.
```

2024-02-28 14:32 UTC, abstergail commented on content/fundamentals/setup/manage-domains/connect-your-domain.md
> +Some configurations can be set at the account-level (if available in your plan), which are applied to all domains under your account, such as the [Web Application Firewall (WAF)](/waf/).
```suggestion
Some configurations can be set at the account-level (if available in your plan), which can be applied to all domains under your account. 
```

2024-02-28 14:32 UTC, abstergail commented on content/fundamentals/setup/manage-domains/connect-your-domain.md
> +Account-level configurations are processed before domain-level services. Refer to [Traffic sequence](https://blog.cloudflare.com/traffic-sequence-which-product-runs-first) to learn more.
```suggestion
Account-level configurations are applied to incoming traffic before your domain-level configurations. Refer to [traffic sequence](https://blog.cloudflare.com/traffic-sequence-which-product-runs-first) to learn more. 
```

2024-02-28 16:23 UTC, abstergail commented on content/fundamentals/concepts/how-cloudflare-works.md
> +Cloudflare is a large network of servers that can improve the security, performance, and reliability of anything connected to the Internet, such as your website, SaaS applications or your corporate n
```suggestion
The [Cloudflare global network] (https://www.cloudflare.com/network/) can improve the security, performance, reliability, and privacy of anything connected to the Internet, such as your website, SaaS applications, or your corporate network.
```

2024-02-28 16:23 UTC, abstergail commented on content/fundamentals/concepts/how-cloudflare-works.md
> +To optimize your website or web application, Cloudflare acts as a DNS provider for your domain, and a [reverse proxy](https://www.cloudflare.com/learning/cdn/glossary/reverse-proxy/) for your web tra
```suggestion
To optimize your website or web application, Cloudflare acts as a [DNS provider](https://www.cloudflare.com/learning/dns/what-is-dns/) for your domain, and a [reverse proxy](https://www.cloudflare.com/learning/cdn/glossary/reverse-proxy/) for your web traffic. 
```

2024-02-28 16:23 UTC, abstergail commented on content/fundamentals/concepts/how-cloudflare-works.md
> +In a full DNS setup, when you [connect a domain](/fundamentals/setup/manage-domains/connect-your-domain/) to Cloudflare, we become the authoritative DNS provider for that domain. When Cloudflare rece
```suggestion
We support a few different [setups](/dns/zone-setups/) for using Cloudflare as a DNS provider. A [full DNS setup](/dns/zone-setups/full-setup/) is the most common, where Cloudflare becomes the primary authoritative DNS provider for your domain, once you [connect your domain to Cloudflare](/fundamentals/setup/manage-domains/connect-your-domain/). This means we respond to DNS queries for your domain, and you [manage its DNS records](/dns/manage-dns-records/how-to/create-dns-records/) via the Cloudflare dashboard or API.

When Cloudflare receives a DNS query for your domain, our response is determined by the configuration [set in your DNS table](/dns/manage-dns-records/how-to/create-dns-records/), including the value of the record, the record's [proxy eligibility](/dns/manage-dns-records/reference/proxied-dns-records/#proxy-eligibility), and it's [proxy status](/dns/manage-dns-records/reference/proxied-dns-records/). 
```

2024-02-28 16:23 UTC, abstergail commented on content/fundamentals/concepts/how-cloudflare-works.md
> +If the [domain's status](/dns/zone-setups/reference/domain-status/) is active and a DNS record is proxied, Cloudflare responds with an [anycast IP address](/fundamentals/concepts/cloudflare-ip-addres
```suggestion
If the [domain's status](/dns/zone-setups/reference/domain-status/) is active and the queried DNS record is proxied, then Cloudflare responds with an [anycast IP address](/fundamentals/concepts/cloudflare-ip-addresses/), **instead of** the value defined in your DNS table. This effectively re-routes the `HTTP/S` requests to the Cloudflare network, instead of directly reaching the targeted the [origin server](https://www.cloudflare.com/learning/cdn/glossary/origin-server/).

In contrast, if the queried DNS record is set to `DNS only`, meaning the proxy is off, then Cloudflare responds with the value defined in your DNS table (i.e., an IP address or CNAME record). This means `HTTP/S` requests route directly to the origin server and are not processed or protected by Cloudflare.
```

2024-02-28 16:23 UTC, abstergail commented on content/fundamentals/concepts/how-cloudflare-works.md
> +All requests to and from your origin will flow through Cloudflare and — as these requests pass through our network — we can apply various rules and optimizations to improve security, performance, and
```suggestion
All DNS records in your DNS table have a [proxy status](/dns/manage-dns-records/reference/proxied-dns-records/), indicating whether or not HTTP/S traffic for that record will route through Cloudflare on its way between the client and the origin server. If the [domain's status](/dns/zone-setups/reference/domain-status/) is active, all HTTP/S requests for [proxied DNS records](/dns/manage-dns-records/reference/proxied-dns-records/#proxied-records) route through Cloudflare.

As these requests pass through our network, they are processed according to your [configuration](/fundamentals/setup/manage-domains/connect-your-domain/#domain-configurations). Then, if needed, legitimate requests are forwarded to the origin server.

Refer to our [reference architecture](reference-architecture/architectures/cdn/) to learn more about how Cloudflare processes and optimizes your web traffic.
```

2024-02-28 16:23 UTC, abstergail commented on content/fundamentals/concepts/how-cloudflare-works.md
> +In the Cloudflare dashboard, you can the proxy status of your records, within each of your domains, on the DNS records page.
```suggestion
In the Cloudflare dashboard, find out which DNS records are proxied by selecting your domain and navigating to the **DNS records** tab.
```

2024-02-28 16:23 UTC, abstergail commented on content/fundamentals/concepts/how-cloudflare-works.md
> +To proxy `HTTP/S` traffic on [non-standard ports](/fundamentals/reference/network-ports/) or to proxy a `TCP-` or `UDP-` based application, use [Cloudflare Spectrum](/spectrum/).
```suggestion
Proxying is on by default for records that serve HTTP/S traffic (A, AAAA, and CNAME records). To proxy `HTTP/S` traffic on [non-standard ports](/fundamentals/reference/network-ports/) or to proxy a `TCP-` or `UDP-` based application, use [Cloudflare Spectrum](/spectrum/).
```

2024-02-28 16:23 UTC, abstergail commented on content/fundamentals/concepts/how-cloudflare-works.md
> +| `A` | `blog` | `192.0.2.1` | `Proxy on` | `Auto` | `Edit` |
```suggestion
| `A` | `blog` | `192.0.2.1` | `Proxied` | `Auto` | `Edit` | 
```

2024-02-28 16:23 UTC, abstergail commented on content/fundamentals/concepts/how-cloudflare-works.md
> +In the table above, there are two DNS records, one with the proxy on, `blog`, and one with the proxy off, `shop`, (i.e. DNS only).
```suggestion
In the example DNS table above, there are two DNS records, one with the proxy on, `blog`, and one with the proxy off, `shop`, (i.e. DNS only).
```

2024-02-28 16:23 UTC, abstergail commented on content/fundamentals/concepts/how-cloudflare-works.md
> +
can we add a header in between here? "Example DNS table"

2024-02-28 16:23 UTC, abstergail commented on content/fundamentals/concepts/how-cloudflare-works.md
> +#### Proxy enabled example
```suggestion
#### Proxied DNS record example
```

2024-02-28 16:23 UTC, abstergail commented on content/fundamentals/concepts/how-cloudflare-works.md
> +#### DNS-only example
```suggestion
#### DNS-only record example
```

2024-02-28 16:23 UTC, abstergail commented on assets/images/fundamentals/connectivity-cloud.png
are these illustrations supposed to be on the page? I don't see them in the preview

2024-02-28 16:23 UTC, abstergail commented on content/fundamentals/concepts/how-cloudflare-works.md
> +To proxy `HTTP/S` traffic on [non-standard ports](/fundamentals/reference/network-ports/) or to proxy a `TCP-` or `UDP-` based application, use [Cloudflare Spectrum](/spectrum/).
also feel like this aside should be above the "In the cf dash" bit

2024-02-29 14:46 UTC, marciocloudflare requested changes

2024-02-29 14:46 UTC, marciocloudflare commented on content/fundamentals/concepts/how-cloudflare-works.md
> +When Cloudflare receives a DNS query for your domain, our response is determined by the configuration [set in your DNS table](/dns/manage-dns-records/how-to/create-dns-records/), including the value
```suggestion
When Cloudflare receives a DNS query for your domain, our response is determined by the configuration [set in your DNS table](/dns/manage-dns-records/how-to/create-dns-records/), including the value of the record, the record's [proxy eligibility](/dns/manage-dns-records/reference/proxied-dns-records/#proxy-eligibility), and its [proxy status](/dns/manage-dns-records/reference/proxied-dns-records/). 
```

2024-02-29 14:46 UTC, marciocloudflare commented on content/dns/_partials/_limitations.md
> +By default, `A`, `AAAA`, and `CNAME` DNS records that serve `HTTP/S` traffic can be proxied.
```suggestion
By default, `A`, `AAAA`, and `CNAME` DNS records that serve `HTTP/HTTPS` traffic can be proxied.
```

2024-02-29 14:46 UTC, marciocloudflare commented on content/dns/_partials/_limitations.md
> +To proxy `HTTP/S` traffic on [non-standard ports](/fundamentals/reference/network-ports/) or to proxy a `TCP-` or `UDP-` based application, use [Cloudflare Spectrum](/spectrum/).
```suggestion
To proxy `HTTP/HTTPS` traffic on [non-standard ports](/fundamentals/reference/network-ports/) or to proxy a `TCP-` or `UDP-` based application, use [Cloudflare Spectrum](/spectrum/).
```

2024-02-29 14:46 UTC, marciocloudflare commented on content/fundamentals/concepts/how-cloudflare-works.md
> +If the [domain's status](/dns/zone-setups/reference/domain-status/) is active and the queried DNS record is set to `proxied`, then Cloudflare responds with an [anycast IP address](/fundamentals/conce
```suggestion
If the [domain's status](/dns/zone-setups/reference/domain-status/) is active and the queried DNS record is set to `proxied`, then Cloudflare responds with an [anycast IP address](/fundamentals/concepts/cloudflare-ip-addresses/), **instead of** the value defined in your DNS table. This effectively re-routes the `HTTP/HTTPS` requests to the Cloudflare network, instead of directly reaching the targeted the [origin server](https://www.cloudflare.com/learning/cdn/glossary/origin-server/).
```

2024-02-29 14:46 UTC, marciocloudflare commented on content/fundamentals/concepts/how-cloudflare-works.md
> +In contrast, if the queried DNS record is set to `DNS only`, meaning the proxy is off, then Cloudflare responds with the value defined in your DNS table (i.e., an IP address or CNAME record). This me
```suggestion
In contrast, if the queried DNS record is set to `DNS only`, meaning the proxy is off, then Cloudflare responds with the value defined in your DNS table (that is, an IP address or CNAME record). This means `HTTP/HTTPS` requests route directly to the origin server and are not processed or protected by Cloudflare.
```

2024-02-29 14:46 UTC, marciocloudflare commented on content/fundamentals/concepts/how-cloudflare-works.md
> +All DNS records in your DNS table have a [proxy status](/dns/manage-dns-records/reference/proxied-dns-records/), indicating whether or not `HTTP/S` traffic for that record will route through Cloudfla
```suggestion
All DNS records in your DNS table have a [proxy status](/dns/manage-dns-records/reference/proxied-dns-records/), indicating whether or not `HTTP/HTTPS` traffic for that record will route through Cloudflare on its way between the client and the origin server. If the [domain's status](/dns/zone-setups/reference/domain-status/) is active, all `HTTP/HTTPS` requests for [proxied DNS records](/dns/manage-dns-records/reference/proxied-dns-records/#proxied-records) route through Cloudflare.
```

2024-02-29 14:46 UTC, marciocloudflare commented on content/fundamentals/concepts/how-cloudflare-works.md
> +{{<Aside>}}
```suggestion
{{<Aside type="note">}}
```

2024-02-29 14:46 UTC, marciocloudflare commented on content/fundamentals/concepts/how-cloudflare-works.md
> +Proxying is on by default for records that serve HTTP/S traffic (`A`, `AAAA`, and `CNAME` records). To proxy `HTTP/S` traffic on [non-standard ports](/fundamentals/reference/network-ports/) or to pro
```suggestion
Proxying is on by default for records that serve `HTTP/HTTPS` traffic (`A`, `AAAA`, and `CNAME` records). To proxy `HTTP/HTTPS` traffic on [non-standard ports](/fundamentals/reference/network-ports/) or to proxy a `TCP-` or `UDP-` based application, use [Cloudflare Spectrum](/spectrum/).
```

2024-02-29 14:46 UTC, marciocloudflare commented on content/fundamentals/concepts/how-cloudflare-works.md
> +In the example DNS table above, there are two DNS records, one with the proxy on, `blog`, and one with the proxy off, `shop`, (i.e. `DNS only`).
```suggestion
In the example DNS table above, there are two DNS records, one with the proxy on, `blog`, and one with the proxy off, `shop`, (that is, `DNS only`).
```

2024-02-29 14:46 UTC, marciocloudflare commented on content/fundamentals/concepts/how-cloudflare-works.md
> +In the example DNS table above, there are two DNS records, one with the proxy on, `blog`, and one with the proxy off, `shop`, (i.e. `DNS only`).
I think this sentence is a bit difficult to understand, and will be a problem to translate. My suggestion is to break it into something smaller. For example: "In the example DNS table above, there are two DNS records. The `blog` record has the proxy on, while the `shop` record has the proxy off (that is, it is `DNS only`)"

2024-02-29 14:46 UTC, marciocloudflare commented on content/fundamentals/concepts/how-cloudflare-works.md
> +When the browser initiates a `HTTP/S` request to `blog.example.com`, a DNS resolver will convert the hostname into an IP address. Since this domain is using Cloudflare as its Authoritative DNS provid
```suggestion
When the browser initiates a `HTTP/HTTPS` request to `blog.example.com`, a DNS resolver will convert the hostname into an IP address. Since this domain is using Cloudflare as its Authoritative DNS provider, the DNS query will be routed to Cloudflare; and because the proxy is on, Cloudflare will answer with an anycast IP address. Subsequently, the browser initiates a `HTTP/HTTPS` request back to Cloudflare. When Cloudflare receives this request, it performs a lookup to find the matching domain and account configuration and processes the request accordingly. Cloudflare forwards it to the configured origin server, which is `192.0.2.1`.
```

2024-02-29 14:46 UTC, marciocloudflare commented on content/fundamentals/concepts/how-cloudflare-works.md
> +When the browser initiates a `HTTP/S` request to `shop.example.com`, a DNS resolver will convert the hostname into an IP address. Since this domain is using Cloudflare as its Authoritative DNS provid
```suggestion
When the browser initiates a `HTTP/HTTPS` request to `shop.example.com`, a DNS resolver will convert the hostname into an IP address. Since this domain is using Cloudflare as its Authoritative DNS provider, the DNS query will be routed to Cloudflare; but since the proxy is off (that is, `DNS only`), Cloudflare will answer with `192.0.2.2`. Finally, the browser initiates a `HTTP/HTTPS` request to the server hosted at `192.0.2.2`.
```

2024-02-29 14:46 UTC, marciocloudflare commented on content/fundamentals/setup/manage-domains/add-multiple-sites-automation.md
> +    title: Add multiple sites via automation
```suggestion
```

2024-02-29 14:46 UTC, marciocloudflare commented on content/fundamentals/setup/manage-domains/add-multiple-sites-automation.md
> +    title: Add multiple sites via automation
If the title and the meta title are the same, you don't need a meta title

2024-02-29 14:46 UTC, marciocloudflare commented on content/fundamentals/setup/manage-domains/connect-your-domain.md
> +    title: Connect your domain
```suggestion
```

2024-02-29 14:46 UTC, marciocloudflare commented on content/fundamentals/setup/manage-domains/connect-your-domain.md
> +Many of our layer 7 services depend on your domain using Cloudflare as a [reverse proxy](https://www.cloudflare.com/learning/cdn/glossary/reverse-proxy/) for its `HTTP/S` traffic.
```suggestion
Many of our layer 7 services depend on your domain using Cloudflare as a [reverse proxy](https://www.cloudflare.com/learning/cdn/glossary/reverse-proxy/) for its `HTTP/HTTPS` traffic.
```

2024-02-29 14:46 UTC, marciocloudflare commented on content/fundamentals/setup/manage-domains/connect-your-domain.md
> +To get started with Cloudflare as a reverse proxy, you must first create an account and [connect your domain](/fundamentals/setup/manage-domains/connect-your-domain/). After creating your account, se
```suggestion
To get started with Cloudflare as a reverse proxy, you must first create an account and [connect your domain](/fundamentals/setup/manage-domains/connect-your-domain/). After creating your account, select **Add site** and follow the [step-by-step tutorial](/fundamentals/setup/manage-domains/add-site/) to configure your [DNS records](/dns/manage-dns-records/), which informs Cloudflare where to forward requests.
```

2024-02-29 14:46 UTC, marciocloudflare commented on content/fundamentals/setup/manage-domains/connect-your-domain.md
> +Your configurations will only affect live traffic (i.e., when your domain's status is [**active**](/fundamentals/setup/manage-domains/connect-your-domain/#activating-your-domain) and its traffic is [
```suggestion
Your configurations will only affect live traffic (that is, when your domain's status is [**active**](/fundamentals/setup/manage-domains/connect-your-domain/#activating-your-domain) and its traffic is [**proxied**](#proxy-eligibility)). Notably, your configurations can be altered prior to activating or enabling the proxy status on the DNS records for the hostnames you want to proxy.
```

2024-02-29 14:46 UTC, marciocloudflare commented on content/fundamentals/setup/manage-domains/connect-your-domain.md
> +{{<Aside header="Account-level configurations">}}
```suggestion
{{<Aside type="note" header="Account-level configurations">}}
```

2024-02-29 14:46 UTC, marciocloudflare commented on content/fundamentals/setup/manage-domains/connect-your-domain.md
> +2. And second, to verify that you are the domain's owner. Only the owner or administrator of a domain can access  its registrar and change its nameservers.
```suggestion
- First, to inform DNS resolvers that your traffic should route through Cloudflare
- And second, to verify that you are the domain's owner. Only the owner or administrator of a domain can access  its registrar and change its nameservers.
```

2024-02-29 14:46 UTC, marciocloudflare commented on content/fundamentals/setup/manage-domains/connect-your-domain.md
> +2. And second, to verify that you are the domain's owner. Only the owner or administrator of a domain can access  its registrar and change its nameservers.
I think it's better to remove the numbers, since these are not a sequence of steps the customer has to perform

2024-02-29 14:46 UTC, marciocloudflare commented on content/fundamentals/setup/manage-domains/connect-your-domain.md
> +Note: The activation process involves different steps if you are using a [secondary DNS](/dns/zone-setups/zone-transfers/cloudflare-as-secondary/) or [partial (CNAME) setup](/dns/zone-setups/partial-
```suggestion
{{<Aside type="note">}}

The activation process involves different steps if you are using a [secondary DNS](/dns/zone-setups/zone-transfers/cloudflare-as-secondary/) or [partial (CNAME) setup](/dns/zone-setups/partial-setup/).
```

2024-02-29 14:46 UTC, marciocloudflare commented on content/fundamentals/setup/manage-domains/connect-your-domain.md
> +Registrars take up to 24 hours to process nameserver changes (quicker in most cases). You will receive an email when your domain becomes active. While your domain is pending, your `HTTP/S` traffic is
```suggestion
Registrars take up to 24 hours to process nameserver changes (quicker in most cases). You will receive an email when your domain becomes active. While your domain is pending, your `HTTP/HTTPS` traffic is not proxied through Cloudflare, but Cloudflare will respond to DNS queries on your assigned nameservers.
```

2024-02-29 14:46 UTC, marciocloudflare commented on content/fundamentals/setup/manage-domains/connect-your-domain.md
> +By activating your domain on a full setup, your traffic will immediately start using [Cloudflare's DNS services](/fundamentals/concepts/how-cloudflare-works/#how-cloudflare-handles-dns-queries), so i
```suggestion
By activating your domain on a full setup, your traffic will immediately start using [Cloudflare's DNS services](/fundamentals/concepts/how-cloudflare-works/#how-cloudflare-handles-dns-queries), so it is important to review how to [avoid downtime](/fundamentals/setup/manage-domains/connect-your-domain/#avoiding-downtime) and what [proxying traffic](/fundamentals/concepts/how-cloudflare-works/#proxying-traffic) means. 
```

2024-02-29 14:46 UTC, marciocloudflare commented on content/fundamentals/setup/manage-domains/connect-your-domain.md
> +- [Configure SSL/TLS](/ssl/edge-certificates/). The first thing Cloudflare does when it receives a `HTTP/S` request is decryption.
```suggestion
- [Configure SSL/TLS](/ssl/edge-certificates/). The first thing Cloudflare does when it receives a `HTTP/HTTPS` request is decryption.
```

2024-02-29 14:46 UTC, marciocloudflare commented on content/fundamentals/setup/manage-domains/manage-subdomains.md
> +    title: Manage subdomains
```suggestion
```

2024-02-29 14:46 UTC, marciocloudflare commented on content/fundamentals/setup/manage-domains/move-domain.md
> +    title:
You forgot to add the `meta:title`. If it's the same as the title, you can remove this.

2024-02-29 14:46 UTC, marciocloudflare commented on content/fundamentals/setup/manage-domains/pause-cloudflare.md
> +    title:
Same here

2024-02-29 14:46 UTC, marciocloudflare commented on content/fundamentals/setup/manage-domains/redirect-domain.md
> +    title:
Same here

2024-02-29 14:46 UTC, marciocloudflare commented on content/fundamentals/setup/manage-domains/star-zones.md
> +    title: Star websites
```suggestion
```

2024-02-29 15:22 UTC, marciocloudflare approved these changes

2024-02-29 15:28 UTC, merged