Update index.md
cloudflare/cloudflare-docs pull request #12710
Opened 2024-01-28 08:37 UTC by Duncan-Cloudflare

SPM-2206

2024-01-29 10:25 UTC, angelampcosta commented on content/analytics/graphql-api/features/filtering/index.md
> +Filtering times are based on `edgeStartTimestmps` which means requests that end after the filter may be includes in queries (as long as that start within the given time).
```suggestion
Filtering times are based on `edgeStartTimestmps`, which means requests that end after the filter may be included in queries (as long as they start within the given time).
```

2024-01-29 11:20 UTC, jimhawkridge commented on content/analytics/graphql-api/features/filtering/index.md
> +Filtering times are based on `edgeStartTimestmps` which means requests that end after the filter may be includes in queries (as long as that start within the given time).
`edgeStartTimestamp` is an internal field name. And is only applicable to some datasets.
I think if we say "Filtering times are based on event start timestamps which means..." then it will apply more generally to other datasets as well as the one we discussed in the Google Chat.

2024-01-29 11:22 UTC, jimhawkridge requested changes
I suggested a wording change to make this more generally apply to most datasets.

2024-01-29 11:31 UTC, angelampcosta commented on content/analytics/graphql-api/features/filtering/index.md
> +Filtering times are based on `edgeStartTimestmps` which means requests that end after the filter may be includes in queries (as long as that start within the given time).
```suggestion
Filtering times are based on event start timestamps, which means requests that end after the filter may be included in queries (as long as they start within the given time).
```

2024-01-30 16:26 UTC, jimhawkridge approved these changes

2024-01-30 16:26 UTC, merged