[Pages] Fix angular CLI docs
cloudflare/cloudflare-docs pull request #12719
Opened 2024-01-29 11:10 UTC by markdembo

Resolves https://github.com/cloudflare/cloudflare-docs/issues/12183

2024-01-29 11:45 UTC, petebacondarwin commented on content/pages/_partials/_build-configuration.md
> +    build_output_directory: /dist/browser/
This change doesn't look very Angular related?

2024-01-29 11:49 UTC, petebacondarwin commented on content/pages/_partials/_build-configuration.md
> +    build_output_directory: /dist/browser/
Did you mean to chang the Angular build_output_directory?

2024-01-29 11:50 UTC, petebacondarwin requested changes

2024-01-29 11:50 UTC, petebacondarwin commented on content/pages/_partials/_build-configuration.md
>      build_output_directory: dist
I think this should be

```suggestion
    build_output_directory: dist/cloudflare
```

2024-01-29 12:17 UTC, markdembo commented on content/pages/_partials/_build-configuration.md
> +    build_output_directory: /dist/browser/
Wow. Let me fix - sorry

2024-01-29 12:21 UTC, markdembo commented on content/pages/_partials/_build-configuration.md
> +    build_output_directory: /dist/browser/
Done. More coffee next time ;)

2024-01-29 12:21 UTC, markdembo commented on content/pages/_partials/_build-configuration.md
>      build_output_directory: dist
Done

2024-01-29 12:24 UTC, petebacondarwin approved these changes
LGTM - disclaimer: I haven't actually tested this in a Pages git connected project.

2024-02-06 17:05 UTC, deadlypants1973 approved these changes

2024-02-07 10:14 UTC, merged