[D1] Remove How to, rename heading, remove use of gerund
cloudflare/cloudflare-docs pull request #12747
Opened 2024-01-30 14:54 UTC by Maddy-Cloudflare

2024-01-30 18:38 UTC, irvinebroque approved these changes

2024-01-31 09:40 UTC, pedrosousa commented on content/_redirects
> -/d1/client-api/ /d1/how-to/query-databases/ 301
Unless we're sure that no one is using these old URLs (via analytics), we should keep the redirects and update their target URL:

```diff
- /d1/client-api/ /d1/how-to/query-databases/ 301
+ /d1/client-api/ /d1/manage-databases/query-databases/ 301
```

2024-01-31 09:42 UTC, pedrosousa commented on content/_redirects
I believe you're missing a redirect:
```
/d1/how-to/using-d1-from-pages/ /d1/manage-databases/using-d1-from-pages/ 301
```

2024-01-31 09:44 UTC, pedrosousa commented on content/_redirects
> +/d1/how-to/querying-json/ /d1/manage-databases/querying-json/ 301
```suggestion
/d1/how-to/querying-json/ /d1/manage-databases/query-json/ 301
```
Nit: You could use this opportunity to remove some of the gerund forms from page URLs since you're moving the page. Added this suggestion as an example (you would also need to rename the `.md` file).

2024-01-31 09:48 UTC, elithrar approved these changes
Approved if @vy-ton also approves.

2024-01-31 10:39 UTC, Maddy-Cloudflare commented on content/_redirects
> +/d1/how-to/querying-json/ /d1/manage-databases/querying-json/ 301
Thanks @pedrosousa. I would have done this on a separate PR, but I might as well do it here then.

2024-01-31 14:37 UTC, vy-ton requested changes

2024-01-31 14:37 UTC, vy-ton commented on content/d1/manage-databases/_index.md
> +title: Manage databases
Developers will be confused with both `Manage` and `configuration`.

I suggest any of the following `Build`, `Developer 101`, `Basics`

2024-01-31 14:37 UTC, vy-ton commented on content/d1/manage-databases/_index.md
> +title: Manage databases
- [ ] Under this heading, can we drop `Query JSON` and `Generated columns` into Reference.
- [ ] The order here should start with `Import data`, `Query databases`, `Use indexes`
- [ ] Let's move `REST API` from Reference under this heading

2024-02-05 14:21 UTC, vy-ton approved these changes

2024-02-05 19:43 UTC, patriciasantaana approved these changes

2024-02-06 12:29 UTC, merged