update `getBindingsProxy` documentation
cloudflare/cloudflare-docs pull request #12787
Opened 2024-02-01 00:00 UTC by dario-piotrowicz

resolves #12783

2024-02-06 10:37 UTC, dario-piotrowicz commented on content/workers/wrangler/api.md
> +          If `false` is specified no data is persisted on the filesystem.
This looks good to me but I am afraid that `wrangler dev` can be a bit restrictive

I mentioned wrangler generically to:
 - include both `wrangler dev` _and_ `wrangler pages dev`
 - include all wrangler commands that can be used to populate bindings
 
 what do you think?

2024-02-06 10:39 UTC, dario-piotrowicz commented on content/workers/wrangler/api.md
> +    *   Emulation of the [workers `caches` runtime API](https://developers.cloudflare.com/workers/runtime-apis/cache/).
🤦

2024-02-06 14:33 UTC, dario-piotrowicz commented on content/workers/wrangler/api.md
> +          If `false` is specified no data is persisted on the filesystem.
sure, sounds good 🙂👍

2024-02-07 17:57 UTC, deadlypants1973 requested changes

2024-02-07 17:57 UTC, deadlypants1973 commented on content/workers/wrangler/api.md
> +This is useful for emulating bindings in applications targeting Workers, but running outside the Workers runtime (e.g. framework local development servers running in Node.js), or for testing purposes
```suggestion
The `getBindingsProxy` function is useful for emulating bindings in applications targeting Workers, but running outside the Workers runtime (for example, framework local development servers running in Node.js), or for testing purposes (for example, ensuring a Function properly interacts with a binding).
```
Check chat questions

2024-02-07 17:57 UTC, deadlypants1973 commented on content/workers/wrangler/api.md
> +          If `true`, allows the utility to read a JSON config file (e.g. `wrangler.json`).
```suggestion
          If `true`, allows the utility to read a JSON config file (for example, `wrangler.json`).
```

2024-02-07 17:57 UTC, deadlypants1973 commented on content/workers/wrangler/api.md
> +          used by Wrangler, so data can be shared between it and the caller. If `false`, no data is persisted to or read from the filesystem.
```suggestion
          Indicates if and where to persist the bindings data. If not present or `true`, defaults to the same location used by Wrangler, so data can be shared between it and the caller. If `false`, no data is persisted to or read from the filesystem.
```

2024-02-07 17:57 UTC, deadlypants1973 commented on content/workers/wrangler/api.md
> +          The path to the config object to use (default `wrangler.toml`)
```suggestion
          The path to the configuration object to use (default `wrangler.toml`).
```

2024-02-07 17:57 UTC, deadlypants1973 commented on content/workers/wrangler/api.md
> +`getBindingsProxy()` returns a `Promise` resolving to an object containing the following fields:
```suggestion
`getBindingsProxy()` returns a `Promise` resolving to an object containing the following fields.
```

2024-02-07 17:57 UTC, deadlypants1973 commented on content/workers/wrangler/api.md
> +    *   Bindings proxies that can be used in the same way as production bindings. This matches the shape of the `env` object passed as the 2nd argument to modules-format workers. These proxy to bindi
```suggestion
    *   Bindings proxies that can be used in the same way as production bindings. This matches the shape of the `env` object passed as the second argument to modules-format workers. These proxy to binding implementations run inside `workerd`.
```
Is "modules-format workers" = Workers written in ES Modules format?

2024-02-07 17:57 UTC, deadlypants1973 commented on content/workers/wrangler/api.md
> +     Cloudflare [Account ID](/fundamentals/setup/find-account-and-zone-ids/) and a Workers AI enabled API token (refer to [Workers AI documentation](/workers-ai/get-started/rest-api/#1-get-an-api-tok
This needs to be a partial and it should also go in this section as well: https://developers.cloudflare.com/workers/wrangler/configuration/#ai

2024-02-07 17:57 UTC, deadlypants1973 commented on content/workers/wrangler/api.md
> +which would print the following output: `MY_VARIABLE = test`
```suggestion
This will print the following output: `MY_VARIABLE = test`.
```

2024-02-07 18:10 UTC, dario-piotrowicz commented on content/workers/wrangler/api.md
> +This is useful for emulating bindings in applications targeting Workers, but running outside the Workers runtime (e.g. framework local development servers running in Node.js), or for testing purposes
As discussed `This` there was more for the getting of a proxy 🙂

2024-02-07 18:12 UTC, dario-piotrowicz commented on content/workers/wrangler/api.md
> +    *   Bindings proxies that can be used in the same way as production bindings. This matches the shape of the `env` object passed as the 2nd argument to modules-format workers. These proxy to bindi
> Is "modules-format workers" = Workers written in ES Modules format?
yes

2024-02-07 18:12 UTC, deadlypants1973 commented on content/workers/wrangler/api.md
> +This is useful for emulating bindings in applications targeting Workers, but running outside the Workers runtime (e.g. framework local development servers running in Node.js), or for testing purposes
Updated!

2024-02-07 21:24 UTC, dario-piotrowicz commented on content/workers/wrangler/api.md
> +     Cloudflare [Account ID](/fundamentals/setup/find-account-and-zone-ids/) and a Workers AI enabled API token (refer to [Workers AI documentation](/workers-ai/get-started/rest-api/#1-get-an-api-tok
I've converted the first bullet point into a partial and reused in both here and in the wrangler configuration page

The second bullet point is not applicable to the other page (only when using `getBindingsProxy` you need to set those environment variables) so I left that as is

I hope this works for you, please let me know 🙂 🙏

2024-02-08 09:23 UTC, deadlypants1973 approved these changes

2024-02-08 09:23 UTC, deadlypants1973 commented on content/workers/wrangler/api.md
> +    * To use the `AI` binding, you'll need to set the `CLOUDFLARE_ACCOUNT_ID` and `CLOUDFLARE_API_TOKEN` environment variables to your Cloudflare [Account ID](/fundamentals/setup/find-account-and-zon
```suggestion
    * To use the `AI` binding, you need to set the `CLOUDFLARE_ACCOUNT_ID` and `CLOUDFLARE_API_TOKEN` environment variables to your Cloudflare [account ID](/fundamentals/setup/find-account-and-zone-ids/) and a [Workers AI enabled API token](/workers-ai/get-started/rest-api/#1-get-an-api-token) respectively.
```

2024-02-08 09:23 UTC, deadlypants1973 commented on content/workers/_partials/_ai-local-usage-charges.md
> +even in local development.
```suggestion
{{<Aside type="note" header="Workers AI local usage charges">}}

Using Workers AI always accesses your Cloudflare account in order to run AI models, and will incur usage charges even in local development.

{{</Aside>}}
```

2024-02-08 09:23 UTC, deadlypants1973 commented on content/workers/wrangler/api.md
> +    * {{<render file="_ai-local-usage-charges.md" productFolder="workers">}}
```suggestion
{{<render file="_ai-local-usage-charges.md" productFolder="workers">}}
```

2024-02-08 09:24 UTC, deadlypants1973 commented on content/workers/wrangler/configuration.md
> +<br>
```suggestion
```

2024-02-08 09:24 UTC, deadlypants1973 approved these changes

2024-02-08 11:39 UTC, deadlypants1973 commented on content/workers/_partials/_ai-local-usage-charges.md
> +{{<Aside type="note" header="Workers AI local usage charges">}}
```suggestion
{{<Aside type="note" header="Workers AI local development usage charges">}}
```

2024-02-08 11:40 UTC, deadlypants1973 approved these changes

2024-02-08 11:55 UTC, merged