Update interactive challenge
cloudflare/cloudflare-docs pull request #12809
Opened 2024-02-02 05:17 UTC by ucro22

See JIRA Train-1661. Enabling JavaScript and cookies on the browser is required for interactive challenge.

2024-02-02 09:54 UTC, migueldemoura requested changes

2024-02-02 09:54 UTC, migueldemoura commented on content/waf/reference/cloudflare-challenges.md
> +Interactive challenges require a visitor to interact with the challenge page, presenting the visitor with an interactive challenge to solve. Cloudflare does not recommend using Interactive Challenges
This is required for all challenges, not just the interactive one.

2024-02-22 09:23 UTC, migueldemoura approved these changes

2024-02-22 09:23 UTC, pedrosousa commented
I updated the text to mention the JS and cookies requirement for all types of challenges, and also gave more visibility to this information.
Can you please check again, @migueldemoura?

2024-02-22 09:38 UTC, merged