Fix customer reported issues with documentation
cloudflare/cloudflare-docs pull request #1281
Opened 2021-05-05 19:24 UTC by kkrum

2021-05-05 19:45 UTC, abracchi-tw requested changes

2021-05-05 19:45 UTC, abracchi-tw commented on products/cloudflare-one/src/content/connections/connect-devices/warp/deployment/parameters.md
> +  This parameter replaces the old enabled property which can no longer be used in conjunction with the new switch_locked and auto_connect. If you want to use switch_locked and/or auto_connect you mus
```suggestion
  This parameter replaces the old `enabled` property, which can no longer be used in conjunction with the new `switch_locked` and `auto_connect`. If you want to use these parameters, you must remove `enabled`.
```

2021-05-05 19:45 UTC, abracchi-tw commented on products/cloudflare-one/src/content/connections/connect-devices/warp/deployment/parameters.md
> +  This parameter replaces the old enabled property which can no longer be used in conjunction with the new switch_locked and auto_connect. If you want to use switch_locked and/or auto_connect you mus
```suggestion
  This parameter replaces the old `enabled` property, which can no longer be used in conjunction with the new `switch_locked` and `auto_connect`. If you want to use these parameters, you must remove `enabled`.
```

2021-05-05 19:45 UTC, abracchi-tw commented on products/cloudflare-one/src/content/connections/connect-devices/warp/deployment/firewall.md
> +
```suggestion
# WARP with Firewall
```

2021-05-05 19:45 UTC, abracchi-tw commented on products/cloudflare-one/src/content/connections/connect-devices/warp/deployment/firewall.md
> +title: Firewall Considerations
remove `title`, no need to specify it

2021-05-05 19:45 UTC, abracchi-tw commented on products/cloudflare-one/src/content/connections/connect-devices/warp/deployment/firewall.md
> +If your organization utilizes a firewall or other policy to restrict internet traffic, you may need to make changes to allow WARP to connect.
```suggestion
If your organization uses a firewall or other policies to restrict Internet traffic, you may need to make a few changes to allow WARP to connect.
```

2021-05-05 19:45 UTC, abracchi-tw commented on products/cloudflare-one/src/content/connections/connect-devices/warp/deployment/firewall.md
> +The Ingress IPs are the set of IP addresses that WARP Clients will connected to. All traffic from your device to the Cloudflare edge is done via these IP addresses:
```suggestion
These are the IP addresses that the WARP client will connect to. All traffic from your device to the Cloudflare edge will go through these IP addresses.
```

2021-05-05 19:45 UTC, abracchi-tw commented on products/cloudflare-one/src/content/connections/connect-devices/warp/deployment/firewall.md
> +In late May 2021 the ingress change for Cloudflare for Teams WARP Customers will change. The new range will be:
any reason we need to specify this now?

2021-05-05 19:45 UTC, abracchi-tw commented on products/cloudflare-one/src/content/connections/connect-devices/warp/deployment/parameters.md
> +You must also include `auto_connect` with at least a value of 0 on new deployments or cleints will be deployed in the off state without a way for users to manually enable.
```suggestion
<Aside>
On new deployments, you must also include the `auto_connect` parameter with at least a value of 0. This will prevent clients from being deployed in the off state without a way for users to manually enable them.
</Aside>
```

2021-05-05 19:47 UTC, abracchi-tw requested changes

2021-05-05 19:47 UTC, abracchi-tw commented on products/cloudflare-one/src/content/connections/connect-devices/warp/deployment/firewall.md
> +WARP utilizes UDP for all of it's communication. UDP Port required for WARP: UDP 2408.
```suggestion
WARP utilizes UDP for all of its communications. UDP Port required for WARP: UDP 2408. 
```

2021-05-05 21:32 UTC, kkrum commented on products/cloudflare-one/src/content/connections/connect-devices/warp/deployment/firewall.md
> +In late May 2021 the ingress change for Cloudflare for Teams WARP Customers will change. The new range will be:
My thinking is that this is a breaking change for users and they can't just walk away from this document thinking it will work forever. I am planning to work with folks to send a heads up email to all our teams customers in the next week so they have time to plan, but want to make sure I don't miss anyone.

2021-05-06 08:55 UTC, abracchi-tw approved these changes

2021-05-06 08:55 UTC, merged