[Image Resizing] Add Next.js next/image integration instructions
cloudflare/cloudflare-docs pull request #1296
Opened 2021-05-07 19:20 UTC by GregBrimble

Fixes #672.

2021-05-07 19:21 UTC, GregBrimble commented
cc. @kodster28 @signalnerve

2021-05-07 19:24 UTC, kodster28 commented
Thanks for the PR @GregBrimble. I've also emailed the relevant PMs to review the technical details.

2021-05-07 19:45 UTC, signalnerve approved these changes

2021-05-07 22:24 UTC, GregBrimble commented
Sorry, just spotted a tiny mistake on one of the lines where I had left in some TypeScript typings. Taken those out now :)

2021-05-09 04:00 UTC, YoutacRSVARs approved these changes

2021-05-10 13:38 UTC, YoutacRSVARs approved these changes

2021-05-10 13:40 UTC, YoutacRSVARs approved these changes

2021-05-17 13:38 UTC, kodster28 requested changes

2021-05-17 13:38 UTC, kodster28 commented on products/images/src/content/integration-with-frameworks.md
> +Image Resizing can be used automatically with Next.js' [`next/image` component](https://nextjs.org/docs/api-reference/next/image). With a [custom loader](https://nextjs.org/docs/api-reference/next/im
Small wording tweaks: 

- Change to `automatically with the Next.js...` (remove apostrophe, add the)
- Change `which applies` to `applying`

2021-05-17 13:50 UTC, YoutacRSVARs approved these changes

2021-05-17 13:51 UTC, YoutacRSVARs approved these changes

2021-05-24 17:18 UTC, kodster28 approved these changes

2021-05-24 20:43 UTC, merged