c3: update get started guides with info on deploying with git repos.
cloudflare/cloudflare-docs pull request #12966
Opened 2024-02-13 17:33 UTC by admah

Also update quickstart command to replace wrangler generate with valid c3 command.

Addresses documentation for [this issue](https://github.com/cloudflare/workers-sdk/issues/4965) in the workers-sdk repo.

2024-02-13 17:39 UTC, dario-piotrowicz commented
In the whole docs repository there is, as far as I know, only a single place in which we offer switchers for package managers:
![Screenshot 2024-02-13 at 17 36 14](https://github.com/cloudflare/cloudflare-docs/assets/61631103/fb50e24b-06a2-4068-86ff-b00da0f5e94b)

I think Kate told me (but I might be wrong!) that just always only mentioning `npm` was a deliberate choice

I'm not saying that I am against the approach but I guess we should make sure this is ok.... also it feel like a bit of a slippery slope just sprinkling it here and there as I feel that if we added such switchers they should be either everywhere or nowhere 😕 🤔

2024-02-14 16:14 UTC, admah commented
@dario-piotrowicz that's a good point. I'm good with consistency. What do you think @deadlypants1973 ?

2024-02-26 16:13 UTC, deadlypants1973 requested changes

2024-02-26 16:13 UTC, deadlypants1973 commented on content/pages/get-started/c3.md
> +Running this command will prompt you to install the [`create-cloudflare`](https://www.npmjs.com/package/create-cloudflare) package, and lead you through a setup wizard. After you have entered the set
```suggestion
Running `create cloudflare@latest` will prompt you to install the [`create-cloudflare`](https://www.npmjs.com/package/create-cloudflare) package, and lead you through a setup wizard. After you have entered the setup wizard, you will be asked which type of application you would like to create.
```

2024-02-26 16:13 UTC, deadlypants1973 commented on content/pages/get-started/c3.md
> +$ npx create-cloudflare@latest [--] [<DIRECTORY>] [OPTIONS] [-- <NESTED ARGS...>]
1. Could we double check if it is `npm` or `npx` in front of `create cloudflare@latest`? I believe the right command is`npm` because it's prompting an install but we should be consistent here. In Workers get started, it is `npm`.

2. I think there is an unnecessary dash `-` between `create` and `cloudflare` here as well.

2024-02-26 16:13 UTC, deadlypants1973 commented on content/pages/get-started/c3.md
> +    - `hello-world-durable-object`: A basic "Hello World" Cloudflare Worker.
This seems incorrect.

2024-02-26 16:13 UTC, deadlypants1973 commented on content/pages/get-started/c3.md
> +    - `pre-existing`: Fetch a Worker initialized from the dashboard.
```suggestion
    - `pre-existing`: Fetch a Worker initialized from the Cloudflare dashboard.
```

2024-02-26 16:13 UTC, deadlypants1973 commented on content/pages/get-started/c3.md
> +  - A git repository used to create a new project. At a minimum, template folders must contain the following:
```suggestion
  - A Git repository used to create a new project. At a minimum, template folders must contain the following:
```

2024-02-26 16:13 UTC, deadlypants1973 commented on content/pages/get-started/c3.md
> +    - `src/` containing a worker script referenced from `wrangler.toml`
```suggestion
    - `src/` containing a Worker referenced from `wrangler.toml`.
```

2024-02-26 16:13 UTC, deadlypants1973 commented on content/pages/get-started/c3.md
> +{{<tabs labels="npx | yarn | pnpm | bun">}}
This should say `npm`, not `npx`.`npx` is a way to run packages installed with `npm` and so, `npx` is not a standalone package manager like the rest of the options in the tab switcher, it's still under `npm` umbrella.

2024-02-26 16:18 UTC, deadlypants1973 commented on content/pages/get-started/c3.md
> +$ npx create-cloudflare@latest [--] [<DIRECTORY>] [OPTIONS] [-- <NESTED ARGS...>]
@penalosa just told me both are technically work, but can we standardize `npm create cloudflare@ latest` to unify with what is in the Workers docs?

2024-02-26 16:23 UTC, deadlypants1973 reviewed
We need to think of a place for C3 docs that include all the info about options that isn't get started guides, it's getting a bit lengthy for a first touch user guide

2024-02-26 16:23 UTC, deadlypants1973 commented on content/workers/get-started/guide.md
> +In addition to creating new projects from its own templates, C3 also supports creating new projects from git repositories. In order to do that, you can open your terminal window and run:
```suggestion
In addition to creating new projects from C3 templates, C3 also supports creating new projects from Git repositories. To create a new project from a Git repository, open your terminal and run:
```

2024-02-26 16:23 UTC, deadlypants1973 commented on content/workers/get-started/guide.md
> +{{<tabs labels="npx | yarn | pnpm | bun">}}
```suggestion
{{<tabs labels="npm | yarn | pnpm | bun">}}
```

2024-02-26 16:23 UTC, deadlypants1973 commented on content/workers/get-started/guide.md
> +$ npx create-cloudflare@latest --template [<SOURCE>]
Same comment about standardizing `npm` here

2024-02-26 16:23 UTC, deadlypants1973 commented on content/workers/get-started/quickstarts.md
> +{{<tabs labels="npx | yarn | pnpm | bun">}}
```suggestion
{{<tabs labels="npm | yarn | pnpm | bun">}}
```

2024-02-26 16:23 UTC, deadlypants1973 commented on content/workers/get-started/quickstarts.md
> +$ npx create-cloudflare@latest <NEW_PROJECT_NAME> --template [<GITHUB_REPO_URL>]
Same comment about standardizing `npm` here

2024-04-11 21:30 UTC, admah commented on content/pages/get-started/c3.md
> +$ npx create-cloudflare@latest [--] [<DIRECTORY>] [OPTIONS] [-- <NESTED ARGS...>]
I've updated all examples to use `npm`.

2024-05-01 19:11 UTC, closed without merging