Content types for stream and byoip
cloudflare/cloudflare-docs pull request #1303
Opened 2021-05-10 18:23 UTC by kodster28

Leaving out SSL b/c it's such a beast...

2021-05-10 18:37 UTC, bkrebsbach approved these changes

2021-05-10 19:09 UTC, Everlag requested changes

2021-05-10 19:09 UTC, Everlag commented on products/stream/src/content/get-started/index.md
> +pcx-content-type: how to
What does `pcx-content-type` do? ie, does it change the order on the sidebar, effect search, etc?

Its not clear to me what impact this change has to folks looking at the docs.

2021-05-10 19:09 UTC, Everlag commented on products/stream/src/content/index.md
> -# Getting started
@zaidf Do we want to split the index page off from the actual useful part of it?

My perspective on this is that we'd be forcing users to make one more unnecessary click to go from a barebones product description to actually useful documentation.

2021-05-10 19:10 UTC, Everlag commented
Please don't merge the Stream changes until @zaidf takes a look and approves. This is a big change to what people see at the first page of our product docs.

2021-05-10 19:30 UTC, Everlag commented on products/stream/src/content/uploading-videos/index.md
> +# Upload videos to Cloudflare Stream
This change isn't in the scope of the commit message.

2021-05-12 13:10 UTC, kodster28 commented on products/stream/src/content/get-started/index.md
> +pcx-content-type: how to
It doesn't impact any visible part of the docs. The goal of including it is to put our metadata close to individual pages so it's less likely to get out of date.

2021-05-12 13:23 UTC, kodster28 commented on products/stream/src/content/index.md
> -# Getting started
Howdy @Everlag (and @zaidf),

We trying to bring the Stream docs — together with other product docs — in line with the customer journey (and our content strategy).

What that means is structuring the first page of each docs section to be a true [landing page](https://wiki.cfops.it/display/Prod/Landing+Page). These pages — best example in [cf-one](https://developers.cloudflare.com/cloudflare-one/) — help customers decide whether or not they want to use the product in the first place (and then get into the more technical details).

I'll admit that all of that content isn't currently there and it's indeed a `barebones product description` at this point, so open to either holding off on this specific change or working together to provide a more robust landing page.

2021-05-12 13:50 UTC, kodster28 commented on products/stream/src/content/uploading-videos/index.md
> +# Upload videos to Cloudflare Stream
Can remove this if you want. Was trying to add a bit more context to a few headings to help SEO.

2021-05-20 14:00 UTC, kodster28 commented
Howdy @Everlag, since it's taken @zaidf a while to respond and our team is trying to get these `pcx-content-type` values implemented across developer docs (doesn't affect any visible part of the docs), I went ahead and reverted the restructuring around the Stream homepage.

We can go back and discuss/address that in another PR.

2021-05-20 15:17 UTC, Everlag approved these changes

2021-05-20 15:18 UTC, Everlag commented
LGTM, thanks for making the changes. Happy to continue discussing the other changes in a separate PR.

2021-05-20 15:58 UTC, crwaters16 approved these changes
Be sure to comb through and hyphenate the two-word pcx-content-types. A few other nit comments included as well.

2021-05-20 15:58 UTC, crwaters16 commented on products/byoip/src/content/dynamic-advertisement/best-practices.md
> +pcx-content-type: best practices
hyphenate

2021-05-20 15:58 UTC, crwaters16 commented on products/byoip/src/content/dynamic-advertisement/configure-dynamic-advertisement.md
> +pcx-content-type: how to
hyphenate

2021-05-20 15:58 UTC, crwaters16 commented on products/byoip/src/content/get-started/index.md
> +pcx-content-type: how to
hyphenate

2021-05-20 15:58 UTC, crwaters16 commented on products/byoip/src/content/get-started/index.md
> +Optionally, if you use the RPKI protocol to sign your routes, Cloudflare can support you there as well. Just let your account team know if you’re interested in using RPKI!
exclamation point?! ;)

2021-05-20 15:58 UTC, crwaters16 commented on products/byoip/src/content/get-started/index.md
> +Please see the subsequent sections to learn more.
strike "please"

2021-05-20 15:58 UTC, crwaters16 commented on products/byoip/src/content/get-started/index.md
> +Once onboarded, BGP announcements for customer prefixes can be controlled with the [Dynamic Advertisement API](/dynamic-advertisement). This API has other useful features and can also be used via the
have we defined BGP anywhere/do we need to?

2021-05-20 15:58 UTC, crwaters16 commented on products/byoip/src/content/index.md
> +pcx-content-type: landing page
hyphenate

2021-05-20 15:58 UTC, crwaters16 commented on products/stream/src/content/uploading-videos/adding-captions.md
> +pcx-content-type: how to
this definitely should be a how-to, but its current state is messy (though we don't have a how-to strategy to align to yet). Consider interim, or we can just make Márcio aware that some of these pages will need to get some TLC in the future.

2021-05-20 15:58 UTC, crwaters16 commented on products/stream/src/content/uploading-videos/direct-creator-uploads.md
> +pcx-content-type: how to
same thought here - definitely should be a how-to, but not structured into steps at the moment

2021-05-20 15:58 UTC, crwaters16 commented on products/stream/src/content/uploading-videos/upload-video-file.md
> +  - A comma separated strings containing the domains. This will set the [allowed origins setting](../../viewing-videos/securing-your-stream#security-considerations) for the video.
odd article/noun agreement - A comma separated string OR comma separated strings

2021-05-20 16:32 UTC, merged

2021-05-24 18:49 UTC, zaidf commented on products/stream/src/content/index.md
> -# Getting started
@kodster28 as Kyle said, we'd strongly prefer having useful, actionable info on the first page. I think the vision to make the first page be more of a landing page makes sense. Given this is an API product, a lot of the best api products have API howtos on the landing page (ie. see mux.com) so I think a lot of what we have is already congruent with that vision. We can add more content on the page that a typical landing page might have while keeping the later sections.