Update `wrangler types` documentation with new customization options
cloudflare/cloudflare-docs pull request #13040
Opened 2024-02-16 17:54 UTC by dario-piotrowicz

> [!WARNING]
> DO NOT MERGE UNTIL THESE CHANGES ARE RELEASED
> (https://github.com/cloudflare/workers-sdk/pull/5042)

___

update the `wrangler types` documentation to add the new `path` positional parameter and `--env-interface` flag

2024-02-21 14:53 UTC, petebacondarwin requested changes

2024-02-21 14:53 UTC, petebacondarwin commented on content/workers/wrangler/commands.md
> +  - The path to where to write the resulting types n entry point for your Worker.
"n"?

2024-02-21 14:53 UTC, petebacondarwin commented on content/workers/wrangler/commands.md
> +  - The path to where to write the resulting types n entry point for your Worker.
Perhaps:

```suggestion
  - The path to where the declaration file for your Worker will be written.
```

2024-02-21 14:53 UTC, petebacondarwin commented on content/workers/wrangler/commands.md
> +  - _Ignored if the worker uses the Service Worker syntax._
Not valid if the worker uses Service Worker syntax.

2024-02-21 16:29 UTC, dario-piotrowicz commented on content/workers/wrangler/commands.md
> +  - _Ignored if the worker uses the Service Worker syntax._
🤦 yeah I need to update this thanks! 🙇

2024-02-21 16:30 UTC, dario-piotrowicz commented on content/workers/wrangler/commands.md
> +  - The path to where to write the resulting types n entry point for your Worker.
> "n"?

sorry... I have no idea what happened there 😓

2024-02-22 23:39 UTC, dario-piotrowicz commented on content/workers/wrangler/commands.md
> +  - _Ignored if the worker uses the Service Worker syntax._
Updated 🙂👍

2024-02-23 10:24 UTC, petebacondarwin approved these changes
Great!

2024-02-23 14:45 UTC, deadlypants1973 approved these changes

2024-02-23 14:45 UTC, deadlypants1973 commented on content/workers/wrangler/commands.md
> +  - Since it is a declaration file, it needs to have a `d.ts` extension.
```suggestion
  - A declaration file needs to have a `d.ts` extension.
```

2024-02-23 14:45 UTC, deadlypants1973 commented on content/workers/wrangler/commands.md
> +  - _Not valid if the worker uses the Service Worker syntax._
```suggestion
  - Not valid if the Worker uses the Service Worker syntax.
```

2024-02-23 14:52 UTC, petebacondarwin commented on content/workers/wrangler/commands.md
> +  - Since it is a declaration file, it needs to have a `d.ts` extension.
I don't think that suggestion quite captures the validation here. What we are trying to say is that this option is invalid and will error if it does not end in `.d.ts`.

Perhaps:

```suggestion
  - The path to the declaration file must have a `d.ts` extension.
```

2024-02-23 15:41 UTC, dario-piotrowicz commented on content/workers/wrangler/commands.md
> +  - Since it is a declaration file, it needs to have a `d.ts` extension.
Thanks @petebacondarwin that looks good to me 😄👍 

Hopefully @deadlypants1973 agrees 🙂

2024-02-23 17:36 UTC, deadlypants1973 approved these changes

2024-02-23 17:57 UTC, merged