[Workers] Add docs for Vitest testing
cloudflare/cloudflare-docs pull request #13092
Opened 2024-02-21 21:46 UTC by admah

Adds new `Testing` section to the Workers docs that contains:

- setup and install instructions for `@cloudflare/vitest-pool-workers`
- API docs for `@cloudflare/vitest-pool-workers`
- Recipes to help users with a variety of test scenarios
- Migration guides for `unstable_dev` and Miniflare 2's Vitest environment

It also moves the local dev guide from Observability into this section.

2024-02-23 04:02 UTC, admah commented on content/workers/testing/vitest/get-started/migrate-from-unstable-dev.md
> +With the Workers Vitest pool, Workers and their functions can be imported and referenced like any other module. There is no need to stop a Worker via `worker.stop()` either. This is handled automatic
That makes sense. I updated this example to use `SELF.fetch()` 👍

2024-02-23 04:02 UTC, admah commented on content/workers/testing/vitest/get-started/write-your-first-test.md
> +});
I've updated all references to `getWaitUntil` 👍

2024-02-23 04:12 UTC, admah commented on content/workers/testing/vitest/get-started/write-your-first-test.md
> +- Install [Vitest](https://vitest.dev/) `1.3.0`
That's a great idea. I updated the section accordingly.

2024-02-27 19:14 UTC, admah commented
@deadlypants1973 this is ready for review.

2024-03-04 02:46 UTC, irvinebroque requested changes
@admah — see [this comment](https://github.com/cloudflare/cloudflare-docs/pull/13092/files#diff-70995e1ec1f7bc8912b00507e74c57f6923b85508f7432a786cfdd1e012bc173R11) first as it gets at structure and content hierarchy.

2024-03-04 02:46 UTC, irvinebroque commented on content/workers/testing/_index.md
> +Test and debug your Worker projects.
More we can say here?

2024-03-04 02:46 UTC, irvinebroque commented on content/workers/testing/vitest/recipes/_index.md
> +- [Basic integration tests using an auxiliary Worker](https://github.com/cloudflare/workers-sdk/tree/main/fixtures/vitest-pool-workers-examples/basics-integration-auxiliary)
These links 404

2024-03-04 02:46 UTC, irvinebroque commented on content/workers/testing/_index.md
> +{{<directory-listing showDescriptions="true">}}
If I arrive here:

<img width="672" alt="Screenshot 2024-03-03 at 4 20 21 PM" src="https://github.com/cloudflare/cloudflare-docs/assets/1221592/20e4d9a7-fd07-42b2-a794-03317b39ac18">

I'm not quite sure where to go next to understand how to write my first unit test or integration test. "Testing Options" forces me to navigate many options, and the Vitest section doesn't show me either. If I want to learn about how to write a unit test for a Worker — `/workers/testing/vitest/get-started/write-your-first-test/` only shows an integration test, and `/workers/testing/vitest/recipes/` links elsewhere.

A hierarchy like this seems like it'd cover this:

- Local development
- Integration tests
- Unit tests
- Debugging tools
- Vitest integration

The content from `/workers/testing/testing-options/` seems like it can be broken down into:

- Types of tests (belongs on top-level testing page)
- Vitest with Workers (belongs on top-level Vitest page)
- `unstable_dev()` and Miniflare API sections (belong on integration test page as secondary options, with Vitest taking clear priority as happy path, and _much_ more explicitly pointing people towards the `/workers/testing/vitest/get-started/migrate-from-unstable-dev/` page to encourage migration.
- Comparison matrix (belongs on top-level testing page towards the bottom)

2024-03-04 02:46 UTC, irvinebroque commented on content/workers/testing/vitest/configuration.md
> +The Workers Vitest pool provides additional configuration on top of Vitest's usual options.
Link to where someone can learn what a pool is in Vitest?

2024-03-04 02:46 UTC, irvinebroque commented on content/workers/testing/vitest/configuration.md
> +All configuration exists under the `poolOptions.workers` key.
Active voice:

```suggestion
To configure the Workers pool in your Vitest config, do x...
```

2024-03-04 02:46 UTC, irvinebroque commented on content/workers/testing/vitest/configuration.md
> +The `defineWorkersPoolOptions()` function from the `@cloudflare/vitest-pool-workers/config` module can optionally be used for type checking and completions.
Just tell people to use it, don't need to call it out as being optional? Can we be simple and provide happy path?

2024-03-04 02:46 UTC, irvinebroque commented on content/workers/testing/vitest/configuration.md
> +Custom `environment`s or `runner`s are not supported when using the Workers Vitest pool.
Awkward to put `s` outside:
<img width="286" alt="Screenshot 2024-03-03 at 4 59 37 PM" src="https://github.com/cloudflare/cloudflare-docs/assets/1221592/781b25b8-17fa-463e-9f6e-3c557d208e7d">



```suggestion
Custom environments or runners are not supported when using the Workers Vitest pool.
```

2024-03-04 02:46 UTC, irvinebroque commented on content/workers/testing/vitest/configuration.md
> +  - An identity function that returns its input. This function exists to provide type checking and completions for `WorkersPoolOptions`, similar to `defineConfig()` from Vitest.
```suggestion
  - Provides type checking and completions for `WorkersPoolOptions`, similar to [`defineConfig()`](https://vitest.dev/config/) from Vitest.
```

Make this approachable — start with what it does.

2024-03-04 02:46 UTC, irvinebroque commented on content/workers/testing/vitest/configuration.md
> +- {{<code>}}defineWorkersPoolOptions(options:{{<param-type>}}WorkersPoolOptions | ((ctx: WorkersPoolOptionsContext) => WorkersPoolOptions | Promise\<WorkersPoolOptions>){{</param-type>}}): {{<type>}}
The typedef really needs to be this verbose?

2024-03-04 02:46 UTC, irvinebroque commented on content/workers/testing/vitest/configuration.md
> +## `WorkersPoolOptions` definition
```suggestion
## `WorkersPoolOptions`
```

2024-03-04 02:46 UTC, irvinebroque commented on content/workers/testing/vitest/configuration.md
> +  - Entrypoint to Worker run in the same isolate/context as tests. This is required to use `import { SELF } from "cloudflare:test"`, or Durable Objects without an explicit `scriptName`. Note this goe
I don't know what this means. Why would I use it? Why would I need `SELF` from `cloudflare:test` or to not use `scriptName` with DO?

2024-03-04 02:46 UTC, irvinebroque commented on content/workers/testing/vitest/configuration.md
> +- {{<code>}}isolatedStorage: {{<type>}}boolean{{</type>}}{{<prop-meta>}}optional{{</prop-meta>}}{{</code>}}
What's the default value? (I have this question across all of the options)

2024-03-04 02:46 UTC, irvinebroque commented on content/workers/testing/vitest/configuration.md
> +- {{<code>}}isolatedStorage: {{<type>}}boolean{{</type>}}{{<prop-meta>}}optional{{</prop-meta>}}{{</code>}}
(I found it eventaully in the description — could we bubble up the default to the typedef?)

2024-03-04 02:46 UTC, irvinebroque commented on content/workers/testing/vitest/configuration.md
> +  - Enables per-test isolated storage. If enabled, any writes to storage performed in a test will be undone at the end of the test. The test's storage environment is copied from the containing suite,
What is the rationale for why the default is false? What do we recommend? If I am reading this for the first time I'm wondering whether I should enable or disable and not sure.

2024-03-04 02:46 UTC, irvinebroque commented on content/workers/testing/vitest/configuration.md
> +    <summary>Illustrative example</summary>
good example — seems like it should be shown in KV docs? Otherwise buried.

2024-03-04 02:46 UTC, irvinebroque commented on content/workers/testing/vitest/configuration.md
> +  - Miniflare sourceless-[`WorkerOptions`](https://github.com/cloudflare/workers-sdk/tree/main/packages/miniflare#interface-workeroptions) for configuring bindings and compatibility settings. Use the
- What does it mean to be "sourceless"?
- What is the default behavior? By default will Vitest pick up the bindings and compatibility dates in my `wrangler.toml`?

```suggestion
  - Use this to provide configuration information that is typically stored within `wrangler.toml`, such as [bindings](/workers/configuration/bindings/), [compatibility dates](/workers/configuration/compatibility-dates/), and [compatibility flags](/workers/configuration/compatibility-dates/#compatibility-flags).  The `WorkerOptions` interface is defined [here](https://github.com/cloudflare/workers-sdk/tree/main/packages/miniflare#interface-workeroptions). Use the `main` option above to configure the entrypoint.<br><br>
```

2024-03-04 02:46 UTC, irvinebroque commented on content/workers/testing/vitest/configuration.md
> +    Auxiliary Workers can be configured using the `workers` array, containing regular Miniflare [`WorkerOptions`](https://github.com/cloudflare/workers-sdk/tree/main/packages/miniflare#interface-work
What is an "auxiliary" Worker? This isn't a term we've used elsewhere.

2024-03-04 02:46 UTC, irvinebroque commented on content/workers/testing/vitest/configuration.md
> +You must define a compatibility date of `2022-10-31` or higher, and include `nodejs_compat` in your compatibility flags to use the Workers Vitest pool.
Why? Does this mean that in order to use Vitest with Workers, I am required to enable `nodejs_compat` for my Worker?

2024-03-04 02:46 UTC, irvinebroque commented on content/workers/testing/vitest/configuration.md
> +  - The same `inject()` function usually imported from the `vitest` module inside tests. This allows you to define `miniflare` config based on injected values from [`globalSetup`](https://vitest.dev/
I think what you're trying to say here is something like "Use this if you need to provide a value that is dynamically generated and only known at runtime of your tests."?

```suggestion
  - The same `inject()` function usually imported from the `vitest` module inside tests. This allows you to define `miniflare` config based on injected values from [`globalSetup`](https://vitest.dev/config/#globalsetup) scripts. For example, a global setup script might start an upstream server on a random port. This port could be provided and then injected in the configuration for an external service binding or Hyperdrive.
```

2024-03-04 02:46 UTC, irvinebroque commented on content/workers/testing/vitest/configuration.md
> +## `SourcelessWorkerOptions` definition
Can we define "sourceless"?

```suggestion
## `SourcelessWorkerOptions`
```

2024-03-04 02:46 UTC, irvinebroque commented on content/workers/testing/vitest/get-started/migrate-from-miniflare-2.md
> +The `@cloudflare/vitest-pool-workers` package provides similar functionality using modern Miniflare versions and the [`workerd` runtime](https://github.com/cloudflare/workerd).
I think we could do more here to explain benefits. Why migrate? Why will it be worthwhile? What will you get by doing so? Why is it better?

2024-03-04 02:46 UTC, irvinebroque commented on content/workers/testing/vitest/get-started/migrate-from-miniflare-2.md
> +Cloudflare no longer provides a Jest testing environment for Workers. If you previously used Jest, you will need to [migrate to Vitest](https://vitest.dev/guide/migration.html#migrating-from-jest) fi
Re: benefits — we can be louder here too — Vitest is x, y, z — help show that it's worth it.

2024-03-04 02:46 UTC, irvinebroque commented on content/workers/testing/vitest/get-started/migrate-from-miniflare-2.md
> +The Workers Vitest pool does not support testing Workers using the Service Worker format. Please [migrate to the ES modules format](/workers/reference/migrate-to-module-workers/) first.
We keep referring to this as "The Workers Vitest pool" — but even if I've used Vitest before, I might have never heard of or interacted directly with the concept of a "pool".

Would suggest something approachable unless we think it is important to use the "pool" language?

```suggestion
The Workers Vitest integration does not support testing Workers using the Service Worker format. Please [migrate to the ES modules format](/workers/reference/migrate-to-module-workers/) first.
```

2024-03-04 02:46 UTC, irvinebroque commented on content/workers/testing/vitest/get-started/migrate-from-miniflare-2.md
> +## Setting up the pool
More broadly, this step is about configuring Vitest

```suggestion
## Configuring Vitest
```

2024-03-04 02:46 UTC, irvinebroque commented on content/workers/testing/vitest/get-started/migrate-from-miniflare-2.md
> +First, you will need to uninstall the old _environment_ and install the new _pool_. Vitest environments can only customise the global scope, whereas pools can run tests using a completely different _
This seems like a selling point that belongs at the top section, whereas this section should be tactical — what are the steps I need to take. (i.e. — Do <X>)

2024-03-04 02:46 UTC, irvinebroque commented on content/workers/testing/vitest/get-started/migrate-from-miniflare-2.md
> +-     environmentOptions: { ... },
Is there an example configuration that shows the mapping of where the configPath would have been before, in the old way?

2024-03-04 02:46 UTC, irvinebroque commented on content/workers/testing/vitest/get-started/migrate-from-miniflare-2.md
> +## Setting up the pool
It seems like the content within here needs headings to denote steps:

* Install `@cloudflare/vitest-pool-workers`
* Update `vitest.config.js`
* Update `tsconfig.json`

2024-03-04 02:46 UTC, irvinebroque commented on content/workers/testing/vitest/get-started/migrate-from-miniflare-2.md
> +To access bindings in your tests, use the new `env` helper from the `cloudflare:test` module.
```suggestion
To access [bindings](/workers/runtime-apis/bindings/) in your tests, use the `env` helper from the `cloudflare:test` module.
```

2024-03-04 02:46 UTC, irvinebroque commented on content/workers/testing/vitest/get-started/migrate-from-miniflare-2.md
> +If you were previously using isolated storage, enable the `isolatedStorage` option in your Vitest configuration file and remove `setupMiniflareIsolatedStorage()` from your tests:
Seems like its own section?

2024-03-04 02:46 UTC, irvinebroque commented on content/workers/testing/vitest/get-started/migrate-from-miniflare-2.md
> +## Waiting for `waitUntil()`ed `Promise`s
```suggestion
## Working with`waitUntil()`
```

2024-03-04 02:46 UTC, irvinebroque commented on content/workers/testing/vitest/get-started/migrate-from-miniflare-2.md
> +- `fetchMock` is deactivated by default, whereas previously it would start activated. You will need to call `fetchMock.activate()` before calling `fetch()` to enable it.
In the context of a migration guide, I'd expect this to hammer home why this default is better, or why there is a change.

2024-03-04 02:46 UTC, irvinebroque commented on content/workers/testing/vitest/get-started/migrate-from-miniflare-2.md
> +- `fetchMock` is reset at the start of each test run, whereas previously interceptors added in previous runs would apply to the current one.
Similar comment to above — I can guess at why this is easier to reason about — but we should say it.

2024-03-04 02:46 UTC, irvinebroque commented on content/workers/testing/vitest/get-started/migrate-from-miniflare-2.md
> +## Using Durable Object helpers
Content for Durable Objects docs? @vy-ton

2024-03-04 02:46 UTC, irvinebroque commented on content/workers/testing/vitest/get-started/migrate-from-miniflare-2.md
> +The `getMiniflareDurableObjectStorage()`, `getMiniflareDurableObjectState()`, `getMiniflareDurableObjectInstance()`, and `runWithMiniflareDurableObjectGates()` functions have all been replaced with a
Same comment — why is it better? Tell people why we made the change.

2024-03-04 02:46 UTC, irvinebroque commented on content/workers/testing/vitest/get-started/migrate-from-unstable-dev.md
> +The [`unstable_dev`](/workers/wrangler/api/#unstable_dev) API has been a recommended approach for users wanting to run integration tests against their Workers. The `@cloudflare/vitest-pool-workers` p
Passive voice

2024-03-04 02:46 UTC, irvinebroque commented on content/workers/testing/vitest/get-started/migrate-from-unstable-dev.md
> +The [`unstable_dev`](/workers/wrangler/api/#unstable_dev) API has been a recommended approach for users wanting to run integration tests against their Workers. The `@cloudflare/vitest-pool-workers` p
Start with benefits, be clearer than "more ergonomic" and "better developer experience"

Docs don't say "users"

```suggestion
The [`unstable_dev`](/workers/wrangler/api/#unstable_dev) API has been a recommended approach to run integration tests. The `@cloudflare/vitest-pool-workers` package provides a more ergonomic API and better developer experience for users wanting to write a wide variety of tests.
```

2024-03-04 02:46 UTC, irvinebroque commented on content/workers/testing/vitest/get-started/migrate-from-unstable-dev.md
> +With the Workers Vitest pool, now you can do the same thing using the `SELF` fetcher from `cloudflare:test`:
This should explain what `SELF` is and what it references. i.e. — SELF is the Worker you've configured in the `test.poolOptions.workers.main` field in your `vitest.config.js` file. (or something like this)

2024-03-04 02:46 UTC, irvinebroque commented on content/workers/testing/vitest/get-started/migrate-from-unstable-dev.md
> +With the Workers Vitest pool there is no need to stop a Worker via `worker.stop()`. This is handled automatically after tests run.
```suggestion
With the Workers Vitest pool there is no need to stop a Worker via `worker.stop()`. The Vitest Workers pool automatically stops your Worker after tests run.
```

2024-03-04 02:46 UTC, irvinebroque commented on content/workers/testing/vitest/get-started/migrate-from-unstable-dev.md
> +Via the `unstable_dev` API, users can reference a `wrangler.toml` config file by adding it as an option like this:
No users in docs

```suggestion
You can configure `unstable_dev` to use a specific `wrangler.toml` config file:
```

2024-03-04 02:46 UTC, irvinebroque commented on content/workers/testing/vitest/get-started/migrate-from-unstable-dev.md
> +With the Workers Vitest pool, you can now set this in `vitest.config.js` for all of your tests.
Sounds like there is a benefit here that we're maybe underselling — that before you'd have to litter your test code with this config, and now you can configure it in one place?

2024-03-04 02:46 UTC, irvinebroque commented on content/workers/testing/vitest/get-started/write-your-first-test.md
> +      "@cloudflare/workers-types/experimental",
Why experimental?

2024-03-04 02:46 UTC, irvinebroque commented on content/workers/testing/vitest/get-started/write-your-first-test.md
> +- More examples of tests using this package can be found in the `@cloudflare/vitest-pool-workers` [repo](https://github.com/cloudflare/workers-sdk/tree/main/packages/vitest-pool-workers/test)
This content should be bubbled way up to the top of this page to be discoverable.

2024-03-04 02:46 UTC, irvinebroque commented on content/workers/testing/vitest/get-started/write-your-first-test.md
> +- Open your Worker project's root folder or create a new project via our [Get Started guide](/workers/get-started/guide/#1-create-a-new-worker-project)
Think "Worker project" is confusing. Also can be shorter.

```suggestion
- Open the root directory of your Worker or [create a new Worker](/workers/get-started/guide/#1-create-a-new-worker-project)
```

2024-03-04 02:46 UTC, irvinebroque commented on content/workers/testing/vitest/get-started/write-your-first-test.md
> +The `@cloudflare/vitest-pool-workers` package _only_ works with Vitest 1.3.0.
```suggestion
The `@cloudflare/vitest-pool-workers` package _only_ works with Vitest 1.3.0. and later
```

2024-03-04 02:46 UTC, irvinebroque commented on content/workers/testing/vitest/get-started/write-your-first-test.md
> +Next, if you don't already have a `vitest.config` file setup, you'll need to create one. In that file, you'll need the following `import` statements:
Explicit

```suggestion
Next, if you don't already have a `vitest.config.js` or `vitest.config.ts` file, you'll need to create one and import the following modules:
```

2024-03-04 02:46 UTC, irvinebroque commented on content/workers/testing/vitest/get-started/write-your-first-test.md
> +Then, you will add the following within `defineConfig` to define the pool and its options:
We're breaking the same file apart into three distinct steps and it makes this guide feel very long and like there is a lot more to do than there actually is. Simpler to show one complete `vitest.config.js` file, let me quickly copy and paste working example.

2024-03-04 02:46 UTC, irvinebroque commented on content/workers/testing/vitest/get-started/write-your-first-test.md
> +## Write Tests
To the previous point about length — we're pretty far down the page by the time you're up and running writing that first test.

2024-03-04 02:46 UTC, irvinebroque commented on content/workers/testing/vitest/get-started/write-your-first-test.md
> +This Worker receives a request, and returns a response of "Hello World!". In order to test this, create a `test` folder with the following test file:
The `/test` dir seems like an important and easy to miss detail.

2024-03-04 02:46 UTC, irvinebroque commented on content/workers/testing/vitest/get-started/write-your-first-test.md
> +filename: index.spec.js
Dir should be shown in filename if the path is important?

```suggestion
filename: /test/index.spec.js
```

2024-03-04 02:46 UTC, irvinebroque commented on content/workers/testing/vitest/get-started/write-your-first-test.md
> +    if(pathname === "/404") {
```suggestion
    if (pathname === "/404") {
```

2024-03-04 02:46 UTC, irvinebroque commented on content/workers/testing/vitest/get-started/write-your-first-test.md
> +title: Write Your First Test
This guide is fundamentally about writing an Integration test — but it doesn't show me how to write a Unit test.

```suggestion
title: Write Your First Integration Test
```

Seems like separate docs needed for unit testing?

2024-03-04 02:46 UTC, irvinebroque commented on content/workers/testing/vitest/internal-details.md
> +title: Internal details
Naming in one of the subheadings is clearer

```suggestion
title: Test isolation and concurrency
```

2024-03-04 02:46 UTC, irvinebroque commented on content/workers/testing/vitest/internal-details.md
> +6. Watch for changes, re-running test files using the same Workers if the configuration has not changed
```suggestion
6. Watch for changes and re-run test files using the same Workers if the configuration has not changed
```

2024-03-04 02:46 UTC, irvinebroque commented on content/workers/testing/vitest/internal-details.md
> +### `isolatedStorage: ❌ singleWorker: ❌`
Show actual config for clarity.

```suggestion
### `isolatedStorage: false, singleWorker: false`
```

2024-03-04 02:46 UTC, irvinebroque commented on content/workers/testing/vitest/internal-details.md
> +The [`isolatedStorage` and `singleWorker`](/workers/testing/vitest/configuration/#workerspooloptions-definition) configuration options both control isolation and concurrency. The Workers Vitest pool
Which of the modes below do we recommend, and for which use cases?

What config is the default?

2024-03-04 02:46 UTC, irvinebroque commented on content/workers/testing/vitest/internal-details.md
> +The Workers Vitest pool works by running code that Vitest would usually run inside a [Node.js worker thread](https://nodejs.org/api/worker_threads.html) inside a Cloudflare Worker instead. To make th
**This first sentence is the AHA moment that should be brought waaaaay up to the top of the Vitest docs, almost the first thing that you read.** It is the number one thing someone needs to understand before everything else starts to click.

2024-03-04 02:46 UTC, irvinebroque commented on content/workers/testing/vitest/internal-details.md
> +The Workers Vitest pool works by running code that Vitest would usually run inside a [Node.js worker thread](https://nodejs.org/api/worker_threads.html) inside a Cloudflare Worker instead. To make th
Similarly — in reading docs I kept wondering why `nodejs_compat` is needed.

```suggestion
The Workers Vitest pool works by running code that Vitest would usually run inside a [Node.js worker thread](https://nodejs.org/api/worker_threads.html) inside a Cloudflare Worker instead. To make this possible, the pool requires the [`nodejs_compat`](/workers/configuration/compatibility-dates/#nodejs-compatibility-flag) and [`export_commonjs_default`](/workers/configuration/compatibility-dates/#commonjs-modules-do-not-export-a-module-namespace) compatibility flags to be enabled. It also configures `workerd` to use Node-style module resolution and polyfills required `node:*` modules not provided by `nodejs_compat`.
```

2024-03-04 02:46 UTC, irvinebroque commented on content/workers/testing/vitest/internal-details.md
> +This may cause your Worker to behave **differently when deployed than under test**, as Node-style resolution and additional polyfills will be available to your Worker's source code and dependencies t
This seems too important to be way at the bottom of the last page of docs that we might expect someone to read?

2024-03-04 02:46 UTC, irvinebroque commented on content/workers/testing/vitest/test-apis.md
> +The Workers Vitest pool provides runtime helpers for writing tests in the `cloudflare:test` module. This module can only be imported from within test files run by the Workers Vitest pool.
```suggestion
The Workers Vitest pool provides runtime helpers for writing tests in the `cloudflare:test` module. This module is provided by the `@cloudflare/vitest-pool-workers` package, but can only be imported from test files that execute in the Workers Vitest pool.
```

Can't decide if clever or odd how we've done this, but regardless — should be clear about what is providing it.

2024-03-04 02:46 UTC, irvinebroque commented on content/workers/testing/vitest/test-apis.md
> +    ```ts
The first code example someone sees seems like it should be showing something like:

```js
import { env } from "cloudflare:test"
// ...show you how to write a test
```

2024-03-04 02:46 UTC, irvinebroque commented on content/workers/testing/vitest/test-apis.md
> +  - 2nd argument passed to modules-format exported handlers. Contains bindings configured in top-level `miniflare` pool options. To configure the type of this value, use an ambient module type:
```suggestion
  - Exposes the [`env` object](/workers/runtime-apis/handlers/fetch/#parameters) that provides access to [bindings](/workers/runtime-apis/bindings/) that you have [configured in `vitest.config.js`](/workers/testing/vitest/configuration/).
 
To configure the TypeScript type of `env`, use an ambient module type:
```

2024-03-04 02:46 UTC, irvinebroque commented on content/workers/testing/vitest/test-apis.md
> +  - [Service binding](/workers/runtime-apis/service-bindings/) to the default export defined in the `main` Worker. Use this to write integration tests against your Worker. Note this `main` Worker run
In practice this might be a service binding under the hood, but I wouldn't expect someone to necessarily understand the implications?

It seems like the common use case for `SELF` is to use it to import the main Worker that's being tested, and call its [handlers](/workers/runtime-apis/handlers/) directly? Is that accurate? If so — can we say it?

2024-03-04 02:46 UTC, irvinebroque commented on content/workers/testing/vitest/test-apis.md
> +  - Declarative interface for mocking outbound `fetch()` requests. Deactivated by default and reset before running each test file. Refer to [`undici`'s `MockAgent` documentation](https://undici.nodej
"Auxiliarly workers"?  Define?

2024-03-04 02:46 UTC, irvinebroque commented on content/workers/testing/vitest/test-apis.md
> +  - Creates an instance of `ExecutionContext` for use as the 3rd argument to modules-format exported handlers.
```suggestion
  - Creates an instance of the [`context` object](/workers/runtime-apis/handlers/fetch/#parameters)
```

+ show example of this API in use?

2024-03-04 02:46 UTC, irvinebroque commented on content/workers/testing/vitest/test-apis.md
> +  - Waits for all `ExecutionContext#waitUntil()`ed `Promise`s to settle. Only accepts instances of `ExecutionContext` returned by `createExecutionContext()`.
Explain why and how to use this — ex: "Use this to wait for all promises passed to `context.waitUntil()` to settle, before running test assertions."

2024-03-04 02:46 UTC, irvinebroque commented on content/workers/testing/vitest/test-apis.md
> +  - Runs `callback` inside the Durable Object pointed-to by `stub`'s context. Conceptually, this temporarily replaces your Durable Object's `fetch()` handler with `callback`, then sends a request to
```suggestion
  - Runs the provided `callback` inside the Durable Object instance that corresponds to the provided `stub`. 

This temporarily replaces your Durable Object's `fetch()` handler with the `callback` you provide and then sends a request to it, returning the result. This can be used to call/spy-on Durable Object instance methods or seed/get persisted data. Note this can only be used with stubs pointing to Durable Objects defined in the `main` worker.
```

2024-03-04 02:46 UTC, irvinebroque commented on content/workers/testing/vitest/test-apis.md
> +### Durable Objects
@vy-ton re: testing content for DO docs, or any cross-linking.

@kentonv @geelen — wondering how this will interact with the RPC API.

2024-03-04 17:44 UTC, admah commented on content/workers/testing/vitest/recipes/_index.md
> +- [Basic integration tests using an auxiliary Worker](https://github.com/cloudflare/workers-sdk/tree/main/fixtures/vitest-pool-workers-examples/basics-integration-auxiliary)
These are currently still in development 👍  I'll need to double-check they're good before we merge this.

2024-03-11 17:11 UTC, deadlypants1973 reviewed
PCX review part 1

2024-03-11 17:11 UTC, deadlypants1973 commented on components/CodeCopy.vue
> +  box-sizing: border-box;
does this affect any other parts of docs other than what we are looking at in this PR? I am not sure what this does but making sure it doesn't break anything

2024-03-11 17:11 UTC, deadlypants1973 commented on content/workers/testing/_index.md
> +This section provides an overview of the different types of tools that can be used for testing and debugging Workers.
```suggestion
Review the tools available for testing and debugging Workers.
```

2024-03-11 17:11 UTC, deadlypants1973 commented on content/workers/testing/_index.md
> +| Multiple Workers support                  | ✅               | 🚧[^1]           | ✅                   |
```suggestion
| Multiple Worker support                   | ✅               | 🚧[^1]           | ✅                   |
```

2024-03-11 17:11 UTC, deadlypants1973 commented on content/workers/testing/debugging-tools.md
> +We provide a variety of tools to help you with this.
```suggestion
Cloudflare provides a variety of tools to help you debug your Workers.
```

2024-03-11 17:11 UTC, deadlypants1973 commented on content/workers/testing/debugging-tools.md
> +Being able to see how your Workers are functioning at various points in the development cycle are vital to identifying the root causes of bugs or issues.
```suggestion
Being able to assess how your Workers are functioning at various points in the development cycle is vital to identifying the root causes of bugs or issues.
```

2024-03-11 17:11 UTC, deadlypants1973 commented on content/workers/testing/debugging-tools.md
> +Wrangler supports using [Chrome DevTools](https://developer.chrome.com/docs/devtools/) to view logs/sources, set breakpoints, and profile CPU/memory usage. With `wrangler dev` running, press the <kbd
```suggestion
Wrangler supports using [Chrome DevTools](https://developer.chrome.com/docs/devtools/) to view logs/sources, set breakpoints, and profile CPU/memory usage. To open a DevTools session connected to your Worker from any Chromium-based browser, run [`wrangler dev`](/workers/wrangler/commands/#dev) and press the <kbd>d</kbd> key in your terminal.
```

2024-03-11 17:11 UTC, deadlypants1973 commented on content/workers/testing/debugging-tools.md
> +As of Wrangler 3.9.0, you can debug via breakpoints in your Worker. Breakpoints provide the ability to see exactly what is happening at a given point in the execution of your Worker. This functionali
```suggestion
As of Wrangler 3.9.0, you can debug via breakpoints in your Worker. Breakpoints provide the ability to review what is happening at a given point in the execution of your Worker. Breakpoint functionality exists in both DevTools and VS Code.
```

2024-03-11 17:11 UTC, deadlypants1973 commented on content/workers/testing/debugging-tools.md
> +4. At the top of the **Run & Debug** panel, you should see an option to select a configuration. Choose **Wrangler**, and select the play icon. You should see **Wrangler: Remote Process [0]** show up
```suggestion
4. At the top of the **Run & Debug** panel, you should see an option to select a configuration. Choose **Wrangler**, and select the play icon. **Wrangler: Remote Process [0]** should show up in the Call Stack panel on the left.
```

2024-03-11 17:11 UTC, deadlypants1973 commented on content/workers/testing/debugging-tools.md
> +5. Open your browser and go to the Worker's local URL (default `http://127.0.0.1:8787`). The breakpoint should be hit, and you should see details about your code at the specified line.
```suggestion
5. Open your browser and go to the Worker's local URL (default `http://127.0.0.1:8787`). The breakpoint should be hit, and you should be able to review details about your code at the specified line.
```

2024-03-11 17:11 UTC, deadlypants1973 commented on content/workers/testing/debugging-tools.md
> +Note that breakpoint debugging in `wrangler dev` using `--remote` could extend Worker CPU time and incur additional costs since you're testing against actual resources that count against usage limits
```suggestion
Breakpoint debugging in `wrangler dev` using `--remote` could extend Worker CPU time and incur additional costs since you are testing against actual resources that count against usage limits. It is recommended to use `wrangler dev` without the `--remote` option. This ensures you are developing locally.
```

2024-03-11 17:11 UTC, deadlypants1973 commented on content/workers/testing/debugging-tools.md
> +* [Local Development](/workers/testing/local-development) - develop your Workers and connected resources locally via Wrangler and our runtime, workerd, for a fast, accurate feedback loop
```suggestion
* [Local Development](/workers/testing/local-development) - Develop your Workers and connected resources locally via Wrangler and the Cloudflare Workers runtime, [`workerd`](https://github.com/cloudflare/workerd), for a fast, accurate feedback loop.
```

2024-03-11 17:11 UTC, deadlypants1973 commented on content/workers/testing/integration-testing.md
> +An integration test might look like...
```suggestion
An integration test for this Worker might look like the following example:
```

2024-03-11 17:11 UTC, deadlypants1973 commented on content/workers/testing/integration-testing.md
> +Here, instead of importing the `add` function as a unit test would do, you make a direct call to the endpoint, testing that the Worker responds at the endpoint with the appropriate response.
```suggestion
In the above example, instead of importing the `add` function as a unit test would do, you make a direct call to the endpoint, testing that the Worker responds at the endpoint with the appropriate response.
```

2024-03-11 17:11 UTC, deadlypants1973 commented on content/workers/testing/integration-testing.md
> +title: Integration Testing
```suggestion
title: Integration testing
```

2024-03-11 17:11 UTC, deadlypants1973 commented on content/workers/testing/integration-testing.md
> +# Integration Testing
```suggestion
# Integration testing
```

2024-03-11 17:11 UTC, deadlypants1973 commented on content/workers/testing/debugging-tools.md
> +title: Debugging Tools
```suggestion
title: Debugging tools
```

2024-03-11 17:11 UTC, deadlypants1973 commented on content/workers/testing/debugging-tools.md
> +# Debugging Tools
```suggestion
# Debugging tools
```

2024-03-11 17:11 UTC, deadlypants1973 commented on content/workers/testing/debugging-tools.md
> +title: Debugging Tools
Style guide convention, we don't capitalize all words in titles unless they are proper nouns of products.

2024-03-11 17:11 UTC, deadlypants1973 commented on content/workers/testing/debugging-tools.md
> +## DevTools
```suggestion
## Chrome DevTools
```

2024-03-11 17:11 UTC, deadlypants1973 commented on content/workers/testing/integration-testing.md
> +## Vitest Integration
```suggestion
## Vitest integration
```

2024-03-11 17:11 UTC, deadlypants1973 commented on content/workers/testing/integration-testing.md
> +The recommended way to write integration tests for your Workers is by using our [custom Vitest integration](/workers/testing/vitest/get-started/). Vitest can be configured to run integrations against
```suggestion
The recommended way to write integration tests for your Workers is by using [the Workers Vitest integration](/workers/testing/vitest/get-started/). Vitest can be configured to run integrations against a single Worker or multiple Workers.
```

2024-03-11 17:11 UTC, deadlypants1973 commented on content/workers/testing/integration-testing.md
> +If testing a single worker, you can use the `SELF` fetcher provided by the [`@cloudflare/test` API](/workers/testing/vitest-integration/test-apis/).
```suggestion
If testing a single Worker, you can use the `SELF` fetcher provided by the [`@cloudflare/test` API](/workers/testing/vitest-integration/test-apis/). 
```

2024-03-11 17:11 UTC, deadlypants1973 commented on content/workers/testing/integration-testing.md
> +When using `SELF` for integration tests, your worker code runs in the same context as the test runner. This means you can use global mocks to control your worker, but also means your worker uses the
```suggestion
When using `SELF` for integration tests, your Worker code runs in the same context as the test runner. This means you can use global mocks to control your Worker, but also means your Worker uses the same subtly different module resolution behavior provided by Vite. 
```

2024-03-11 17:11 UTC, deadlypants1973 commented on content/workers/testing/integration-testing.md
> +When using `SELF` for integration tests, your worker code runs in the same context as the test runner. This means you can use global mocks to control your worker, but also means your worker uses the
The phrasing of "same subtly different" is a bit confusing - 'same' and 'different' are antonyms. What are we trying to say is happening technically here?

2024-03-11 17:11 UTC, deadlypants1973 commented on content/workers/testing/integration-testing.md
> +Usually this isn't a problem, but if you'd like to run your worker in a fresh environment that's as close to production as possible, using an auxiliary worker may be a good idea - although auxiliary
```suggestion
Usually this is not a problem, but if you would like to run your Worker in a fresh environment that is as close to production as possible, using an auxiliary Worker may be a good idea. Auxiliary Workers have some developer experience (DX) limitations.
```

2024-03-11 17:11 UTC, deadlypants1973 commented on content/workers/testing/integration-testing.md
> +It's also possible to configure Workers for integration testing via `vitest.config.js`. An example config file can be seen [here](https://github.com/cloudflare/workers-sdk/blob/bcoll/vitest-pool-work
```suggestion
It is also possible to configure Workers for integration testing via `vitest.config.js`. An [example `vitest.config.js` configuration file](https://github.com/cloudflare/workers-sdk/blob/bcoll/vitest-pool-workers-examples/fixtures/vitest-pool-workers-examples/basics-integration-auxiliary/vitest.config.ts) on GitHub.
```

2024-03-11 17:11 UTC, deadlypants1973 commented on content/workers/testing/integration-testing.md
> +The Worker can then be referenced like this:
```suggestion
The Worker can then be referenced like the following example:
```

2024-03-11 17:11 UTC, deadlypants1973 commented on content/workers/testing/integration-testing.md
> +Usually this isn't a problem, but if you'd like to run your worker in a fresh environment that's as close to production as possible, using an auxiliary worker may be a good idea - although auxiliary
Can we define what an auxilary Worker is? We have a lot of terms floating around for Workers (consumer Worker, production Worker, tail Worker, etc.) It is good in all of these cases to have a sentence for definition.

We need a sentence that says "An auxiliary Worker is _____." here, and we should add it to the Glossary: https://developers.cloudflare.com/workers/glossary/

2024-03-11 17:11 UTC, deadlypants1973 commented on content/workers/testing/integration-testing.md
> +### Testing via auxilliary workers
```suggestion
### Testing via auxiliary Workers
```

2024-03-11 17:11 UTC, deadlypants1973 commented on content/workers/testing/integration-testing.md
> +Instead of running the Worker-under-test in the same Worker as the test runner like `SELF`, this example defines the Worker-under-test as an _auxiliary_ Worker. This means the Worker runs in a separa
```suggestion
Instead of running the Worker-under-test in the same Worker as the test runner like `SELF`, this example defines the Worker-under-test as an _auxiliary_ Worker. This means the Worker runs in a separate isolate to the test runner, with a different global scope. The Worker-under-test runs in an environment closer to production, but Vite transformations and hot-module-reloading aren't applied to the Worker—you must compile your TypeScript to JavaScript beforehand.
```
clarification needed

2024-03-11 17:11 UTC, deadlypants1973 commented on content/workers/testing/integration-testing.md
> +Auxiliary workers also cannot be configured from `wrangler.toml` files—you must use Miniflare `WorkerOptions` in `vite.config.ts`.
```suggestion
Auxiliary Workers cannot be configured from `wrangler.toml` files. You must use Miniflare [`WorkerOptions`](https://github.com/cloudflare/workers-sdk/tree/main/packages/miniflare#interface-workeroptions) in `vite.config.ts`.
```

2024-03-11 17:11 UTC, deadlypants1973 commented on content/workers/testing/integration-testing.md
> +This method can be useful when you're testing multiple workers. You can define multiple Workers by different names in `vitest.config.js` and reference them via `env`.
```suggestion
This method can be useful when you are testing multiple Workers. You can define multiple Workers by different names in `vitest.config.js` and reference them via `env`.
```
What method? testing with auxiliary Workers?

2024-03-11 17:11 UTC, deadlypants1973 commented on content/workers/testing/integration-testing.md
> +If you do not want to use Vitest and would like to write integration tests for a single worker, consider using [Wrangler's `unstable_dev()` API](/workers/wrangler/api/#unstable_dev). This allows you
```suggestion
If you do not want to use Vitest and would like to write integration tests for a single Worker, consider using [Wrangler's `unstable_dev()` API](/workers/wrangler/api/#unstable_dev). `unstable_dev` allows you to start an HTTP server similar to [`wrangler dev`](/workers/wrangler/commands/#dev) that you can send HTTP requests to. `unstable_dev()` will automatically load options from your Wrangler configuration file. Note that `unstable_dev` is an experimental API subject to breaking changes.
```
The last sentence contradicts the content here: https://developers.cloudflare.com/workers/wrangler/api/#unstable_dev

2024-03-11 17:11 UTC, deadlypants1973 commented on content/workers/testing/integration-testing.md
> +If you have been using `unstable_dev()` for integration testing and want to migrate to our Vitest integration, read this [migration guide](/workers/testing/vitest-integration/get-started/migrate-from
```suggestion
If you have been using `unstable_dev()` for integration testing and want to migrate to Cloudflare's Vitest integration, refer to the [Migrate from `unstable_dev` migration guide](/workers/testing/vitest-integration/get-started/migrate-from-unstable-dev/) for more information.
```

2024-03-11 17:11 UTC, deadlypants1973 commented on content/workers/testing/integration-testing.md
> +If you would like to write integration tests for multiple workers, need direct access to bindings outside your worker in tests, or have another advanced use case, consider using [Miniflare's API](htt
```suggestion
If you would like to write integration tests for multiple Workers, need direct access to [bindings](/workers/configuration/bindings/) outside your Worker in tests, or have another advanced use case, consider using [Miniflare's API](https://github.com/cloudflare/workers-sdk/blob/main/packages/miniflare/README.md) directly. Miniflare is the foundation for the other testing tools on this page, exposing a JavaScript API for the [`workerd` runtime](https://github.com/cloudflare/workerd) and local simulators for the other Developer Platform products. Unlike `unstable_dev()`, Miniflare does not automatically load options from your Wrangler configuration file.
```

2024-03-11 17:11 UTC, deadlypants1973 commented on content/workers/testing/integration-testing.md
> +- More examples of integration tests can be found on the Vitest [Recipes page](/workers/testing/vitest-integration/recipes).
```suggestion
- [Recipes](/workers/testing/vitest-integration/recipes) - Examples of integration tests.
```

2024-03-11 17:11 UTC, deadlypants1973 commented on content/workers/testing/integration-testing.md
> +If you have been using the test environments from Minflare 2 for integration testing and want to migrate to our Vitest integration, read this [migration guide](/workers/testing/vitest-integration/get
```suggestion
If you have been using the test environments from Minflare 2 for integration testing and want to migrate to Cloudflare's Vitest integration, refer to the [Migrate from Miniflare migration guide](/workers/testing/vitest-integration/get-started/migrate-from-miniflare-2/) for more information.
```

2024-03-11 17:11 UTC, deadlypants1973 commented on content/workers/testing/local-development.md
> +In addition to testing Workers locally with `wrangler dev`, the use of Miniflare allows you to test other Developer Platform products locally, such as [R2](/r2/), [KV](/kv/), [D1](/d1/), and [Durable
```suggestion
In addition to testing Workers locally with [`wrangler dev`](/workers/wrangler/commands/#dev), the use of Miniflare allows you to test other Developer Platform products locally, such as [R2](/r2/), [KV](/kv/), [D1](/d1/), and [Durable Objects](/durable-objects/).
```

2024-03-11 17:11 UTC, deadlypants1973 commented on content/workers/testing/local-development.md
> +* [Debugging Tools](/workers/testing/debugging-tools) - tools to help you gain insight into your Workers in order to diagnose issues.
```suggestion
* [Debugging tools](/workers/testing/debugging-tools) - Tools to help you diagnose issues and gain insight into your Workers.
```

2024-03-11 17:11 UTC, deadlypants1973 commented on content/workers/testing/unit-testing.md
> +title: Unit Testing
```suggestion
title: Unit testing
```

2024-03-11 17:11 UTC, deadlypants1973 commented on content/workers/testing/unit-testing.md
> +# Unit Testing
```suggestion
# Unit testing
```

2024-03-11 19:35 UTC, deadlypants1973 commented on content/workers/testing/unit-testing.md
> +In a Workers context, a unit test imports and directly calls functions from your Worker then asserts on their return values. For example, consider you have the following Worker:
```suggestion
In a Workers context, a unit test imports and directly calls functions from your Worker. After calling the functions, the unit test then asserts on the functions' return values. For example, consider you have the following Worker:
```

2024-03-11 19:35 UTC, deadlypants1973 commented on content/workers/testing/unit-testing.md
> +A unit test might look like...
```suggestion
An example unit test for the above Worker may look like the following:
```

2024-03-11 19:35 UTC, deadlypants1973 commented on content/workers/testing/unit-testing.md
> +This test only assets that the `add` function is returning the correct value, but doesn't test the Worker itself like an [integration test](/workers/testing/integration-testing) would do.
```suggestion
This test only assets that the `add` function is returning the correct value, but does not test the Worker itself like an [integration test](/workers/testing/integration-testing) would.
```

2024-03-11 19:35 UTC, deadlypants1973 commented on content/workers/testing/vitest-integration/recipes.md
> +These examples help demonstrate how to write unit tests and integration tests for Workers projects using the [`@cloudflare/vitest-pool-workers`](https://www.npmjs.com/package/@cloudflare/vitest-pool-
```suggestion
Recipes are examples that help demonstrate how to write unit tests and integration tests for Workers projects using the [`@cloudflare/vitest-pool-workers`](https://www.npmjs.com/package/@cloudflare/vitest-pool-workers) package.
```

2024-03-11 19:35 UTC, deadlypants1973 commented on content/workers/testing/unit-testing.md
> +## Vitest Integration
```suggestion
## Vitest integration
```

2024-03-11 19:35 UTC, deadlypants1973 commented on content/workers/testing/unit-testing.md
> +The recommended way to unit test your Workers is by using our custom Vitest integration. For more information on features, as well as installation and setup instructions, please read the [Get Started
```suggestion
The recommended way to unit test your Workers is by using the Workers Vitest integration. For more information on features, as well as installation and setup instructions, refer to the [Vitest integration Get Started guide](/workers/testing/vitest/get-started/)
```

2024-03-11 19:35 UTC, deadlypants1973 commented on content/workers/testing/unit-testing.md
> +- More examples of unit tests can be found on the Vitest [Recipes page](/workers/testing/vitest-integration/recipes).
```suggestion
- [Recipes](/workers/testing/vitest-integration/recipes) - Examples of integration tests.
```

2024-03-11 19:35 UTC, deadlypants1973 commented on content/workers/testing/vitest-integration/_index.md
> +title: Vitest Integration
```suggestion
title: Vitest integration
```

2024-03-11 19:35 UTC, deadlypants1973 commented on content/workers/testing/vitest-integration/_index.md
> +# Vitest Integration
```suggestion
# Vitest integration
```

2024-03-11 19:35 UTC, deadlypants1973 commented on content/workers/testing/vitest-integration/get-started/_index.md
> +For most users, Cloudflare recommends using our [custom Vitest integration](/workers/testing/vitest/get-started/) for testing Workers and [Pages Functions](/pages/functions/) projects. [Vitest](https
```suggestion
For most users, Cloudflare recommends using the [Workers Vitest integration](/workers/testing/vitest/get-started/) for testing Workers and [Pages Functions](/pages/functions/) projects. [Vitest](https://vitest.dev/) is a popular JavaScript testing framework featuring a very fast watch mode, Jest compatibility, and out-of-the-box support for TypeScript. Cloudflare provides a custom pool that allows your Vitest tests to run _inside_ the Workers runtime. Get started with the [Vitest integration Get started guide](/workers/testing/vitest/get-started/), and refer to [Recipes for testing different types of Workers](/workers/testing/vitest/recipes/).
```

2024-03-11 19:35 UTC, deadlypants1973 commented on content/workers/testing/vitest-integration/get-started/_index.md
> +  description: Install and setup the Workers Vitest integration - a robust tool for writing unit and integration tests for Workers.
```suggestion
  description: Install and set up the Workers Vitest integration - a tool for writing unit and integration tests for Workers.
```

2024-03-11 19:35 UTC, deadlypants1973 commented on content/workers/testing/vitest-integration/get-started/_index.md
> +The Workers Vitest integration does not support testing Workers using the Service Worker format. Please [migrate to the ES modules format](/workers/reference/migrate-to-module-workers/) first.
```suggestion
The Workers Vitest integration does not support testing Workers using the service worker format. [Migrate to the ES modules format](/workers/reference/migrate-to-module-workers/) to use the Workers Vitest integration.
```

2024-03-11 19:35 UTC, deadlypants1973 commented on content/workers/testing/vitest-integration/configuration.md
> +Use the `defineWorkersPoolOptions()` function from the `@cloudflare/vitest-pool-workers/config` module for type checking and completions.
```suggestion
The Workers Vitest integration provides additional configuration on top of Vitest's usual options. To configure the Workers Vitest integration, use the `poolOptions.workers` key. Use the [`defineWorkersPoolOptions()`](/workers/testing/vitest-integration/configuration/#functions) function from the `@cloudflare/vitest-pool-workers/config` module for type checking and completions.
```
Can we get links to the items in monospaces here?
1. `poolOptions.workers`
2. `@cloudflare/vitest-pool-workers/config`
Source docs for these needed.

2024-03-11 19:35 UTC, deadlypants1973 commented on content/workers/testing/vitest-integration/get-started/write-your-first-test.md
> +For a full list of available Miniflare options, read the Miniflare [WorkersOptions API docs](https://github.com/cloudflare/workers-sdk/tree/main/packages/miniflare#interface-workeroptions).
```suggestion
For a full list of available Miniflare options, refer to the [Miniflare `WorkersOptions` API documentation](https://github.com/cloudflare/workers-sdk/tree/main/packages/miniflare#interface-workeroptions).
```

2024-03-11 19:35 UTC, deadlypants1973 commented on content/workers/testing/vitest-integration/configuration.md
> +An example configuration would be:
```suggestion

An example configuration would be:
```

2024-03-11 19:35 UTC, deadlypants1973 commented on content/workers/testing/vitest-integration/configuration.md
> +These are exported from the `@cloudflare/vitest-pool-workers/config` module.
```suggestion
The following functions are exported from the `@cloudflare/vitest-pool-workers/config` module.
```

2024-03-11 19:35 UTC, deadlypants1973 commented on content/workers/testing/vitest-integration/configuration.md
> +  - Provide type checking and completions for `WorkersPoolOptions`, similar to [`defineConfig()`](https://vitest.dev/config/file.html) from Vitest.
```suggestion
  - Provides type checking and completions for `WorkersPoolOptions`, similar to [`defineConfig()`](https://vitest.dev/config/file.html) from Vitest.
```

2024-03-11 19:35 UTC, deadlypants1973 commented on content/workers/testing/vitest-integration/configuration.md
> +- {{<code>}}main: {{<type>}}string{{</type>}}{{<prop-meta>}}optional{{</prop-meta>}}{{</code>}}
```suggestion
- {{<code>}}main: {{<type>}}string{{</type>}}{{</code>}}{{<prop-meta>}}optional{{</prop-meta>}}
```

2024-03-11 19:35 UTC, deadlypants1973 commented on content/workers/testing/vitest-integration/configuration.md
> +  - Entrypoint to Worker run in the same isolate/context as tests. This is required to use `import { SELF } from "cloudflare:test"` for integration tests, or Durable Objects without an explicit `scri
```suggestion
  - Entry point to Worker run in the same isolate/context as tests. This is required to use `import { SELF } from "cloudflare:test"` for integration tests, or Durable Objects without an explicit `scriptName` if classes are defined in the same Worker. This___ goes through Vite transforms and can be a TypeScript file. Note also that `import module from "<path-to-main>"` inside tests gives exactly the same `module` instance as is used internally for the `SELF` and Durable Object bindings. If `wrangler.configPath` is defined and this option is not, it will be read from the `main` field in that configuration file.
```
What is this? An option, a field, a key?

2024-03-11 19:35 UTC, deadlypants1973 commented on content/workers/testing/vitest-integration/configuration.md
> +  - Enables per-test isolated storage. If enabled, any writes to storage performed in a test will be undone at the end of the test. The test's storage environment is copied from the containing suite,
```suggestion
  - Enables per-test isolated storage. If enabled, any writes to storage performed in a test will be undone at the end of the test. The test's storage environment is copied from the containing suite, meaning `beforeAll()` hooks can be used to seed data. If this ____ is disabled, all tests will share the same storage. `.concurrent` tests are not supported when isolated storage is enabled. Refer to the [Isolation and concurrency](/workers/testing/vitest/internal-details/) page for more information on the isolation model.
  
  - Defaults to `false`.
```
What is 'this'?

2024-03-11 19:35 UTC, deadlypants1973 commented on content/workers/testing/vitest-integration/configuration.md
> +- {{<code>}}isolatedStorage: {{<type>}}boolean{{</type>}}{{<prop-meta>}}optional{{</prop-meta>}}{{</code>}} — Defaults to `false`
```suggestion
- {{<code>}}isolatedStorage: {{<type>}}boolean{{</type>}}{{</code>}}{{<prop-meta>}}optional{{</prop-meta>}}
```

2024-03-11 19:35 UTC, deadlypants1973 commented on content/workers/testing/vitest-integration/configuration.md
> +- {{<code>}}miniflare: {{<type>}}SourcelessWorkerOptions & { workers?: WorkerOptions[]; }{{</type>}}{{<prop-meta>}}optional{{</prop-meta>}}{{</code>}}
```suggestion
- {{<code>}}miniflare: {{<type>}}SourcelessWorkerOptions & { workers?: WorkerOptions[]; }{{</type>}}{{</code>}}{{<prop-meta>}}optional{{</prop-meta>}}
```

2024-03-11 19:35 UTC, deadlypants1973 commented on content/workers/testing/vitest-integration/configuration.md
> +- {{<code>}}singleWorker: {{<type>}}boolean{{</type>}}{{<prop-meta>}}optional{{</prop-meta>}}{{</code>}} — Defaults to `false`
```suggestion
- {{<code>}}singleWorker: {{<type>}}boolean{{</type>}}{{</code>}}{{<prop-meta>}}optional{{</prop-meta>}}
```

2024-03-11 19:35 UTC, deadlypants1973 commented on content/workers/testing/vitest-integration/configuration.md
> +  - Runs all tests in this project serially in the same Worker, using the same module cache. This can significantly speed up execution if you have lots of small test files. Refer to the [Isolation an
```suggestion
  - Runs all tests in this project serially in the same Worker, using the same module cache. This can significantly speed up execution if you have lots of small test files. Refer to the [Isolation and concurrency](/workers/testing/vitest/internal-details/) page for more information on the isolation model.
  
  - Defaults to `false`.
```

2024-03-11 19:35 UTC, deadlypants1973 commented on content/workers/testing/vitest-integration/get-started/_index.md
> +- 🧩 Supports projects with multiple workers
```suggestion
- Supports both unit tests and integration tests.
- Provides direct access to Workers runtime APIs and bindings.
- Implements isolated per-test storage.
- Runs tests locally using [Miniflare](https://miniflare.dev/).
- Leverages Vitest's hot-module reloading for near instant reruns.
- Provides a declarative interface for mocking outbound requests.
- Supports projects with Multiple workers.
```
There is no item or sentence before this list that explains what this list is describing.

2024-03-11 19:35 UTC, deadlypants1973 commented on content/workers/testing/vitest-integration/configuration.md
> +    - Are not affected by global mocks defined in your tests
```suggestion
    - Cannot have TypeScript entrypoints. You must compile auxiliary Workers to JavaScript first.
    - Use regular Workers module resolution semantics. Refer to the [Isolation and concurrency](/workers/testing/vitest/internal-details/#modules) page for more information.
    - Cannot access the `cloudflare:test` module.
    - Do not require specific compatibility dates or flags.
    - Can be written with the [Service Worker syntax](/workers/reference/migrate-to-module-workers/#service-worker-syntax).
    - Are not affected by global mocks defined in your tests.
```

2024-03-11 19:35 UTC, deadlypants1973 commented on content/workers/testing/vitest-integration/configuration.md
> +  - Miniflare sourceless-[`WorkerOptions`](https://github.com/cloudflare/workers-sdk/tree/main/packages/miniflare#interface-workeroptions) for configuring bindings and compatibility settings. Use the
```suggestion
  - Miniflare sourceless-[`WorkerOptions`](https://github.com/cloudflare/workers-sdk/tree/main/packages/miniflare#interface-workeroptions) for configuring bindings and compatibility settings. Use the `main` option above to configure the entry point, instead of the Miniflare `script`, `scriptPath`, or `modules` options.<br><br>
```

2024-03-11 19:35 UTC, deadlypants1973 commented on content/workers/testing/vitest-integration/configuration.md
> +    If your project makes use of multiple Workers, you can configure _auxiliary Workers_ that run in the same `workerd` process as your tests and can be bound to. Auxiliary Workers are configured usi
```suggestion
    If your project makes use of multiple Workers, you can configure auxiliary Workers that run in the same `workerd` process as your tests and can be bound to. Auxiliary Workers are configured using the `workers` array, containing regular Miniflare [`WorkerOptions`](https://github.com/cloudflare/workers-sdk/tree/main/packages/miniflare#interface-workeroptions) objects. Note that unlike the `main` Worker, auxiliary Workers:
```

2024-03-11 19:35 UTC, deadlypants1973 commented on content/workers/testing/vitest-integration/configuration.md
> +- {{<code>}}wrangler: {{<type>}}{ configPath?: string; }{{</type>}}{{<prop-meta>}}optional{{</prop-meta>}}{{</code>}}
```suggestion
- {{<code>}}wrangler: {{<type>}}{ configPath?: string; }{{</type>}}{{</code>}}{{<prop-meta>}}optional{{</prop-meta>}}
```

2024-03-11 19:35 UTC, deadlypants1973 commented on content/workers/testing/vitest-integration/configuration.md
> +You must define a compatibility date of `2022-10-31` or higher, and include `nodejs_compat` in your compatibility flags to use the Workers Vitest integration.
```suggestion
You must define a compatibility date of `2022-10-31` or higher, and include [`nodejs_compat` in your compatibility flags](/workers/configuration/compatibility-dates/#nodejs-compatibility-flag) to use the Workers Vitest integration.
```

2024-03-11 19:35 UTC, deadlypants1973 commented on content/workers/testing/vitest-integration/configuration.md
> +  - Path to Wrangler configuration file to load `main`, compatibility settings and bindings from. These options will be merged with the `miniflare` option above, with `miniflare` values taking preced
```suggestion
  - Path to Wrangler configuration file to load `main`, compatibility settings and bindings from. These options will be merged with the `miniflare` option above, with `miniflare` values taking precedence. For example, if your Wrangler configuration defined a [service binding](/workers/configuration/bindings/about-service-bindings/) named `SERVICE` to a Worker named `service`, but you included `serviceBindings: { SERVICE(request) { return new Response("body"); } }` in the `miniflare` option, all requests to `SERVICE` in tests would return `body`. Note `configPath` accepts both `.toml` and `.json` files.
```

2024-03-11 19:40 UTC, deadlypants1973 commented on content/workers/testing/_index.md
> +[^1]: Support for multiple workers in `unstable_dev()` relies on `wrangler dev`'s service registry which can be unreliable when running multiple tests in parallel.
```suggestion
[^1]: Support for multiple Workers in [`unstable_dev()`](/workers/wrangler/api/#unstable_dev) relies on `wrangler dev`'s service registry which can be unreliable when running multiple tests in parallel.
```

2024-03-11 19:49 UTC, deadlypants1973 commented on content/workers/testing/local-development.md
> +[^1]: Support for local AI development includes accessing remote resources that count against usage.
```suggestion
[^1]: Using Workers AI always accesses your Cloudflare account in order to run AI models and will incur usage charges even in local development.
```

2024-03-11 19:49 UTC, deadlypants1973 commented on content/workers/testing/vitest-integration/configuration.md
> +  - The same `inject()` function usually imported from the `vitest` module inside tests. This allows you to define `miniflare` config based on injected values from [`globalSetup`](https://vitest.dev/
```suggestion
  - The same `inject()` function usually imported from the `vitest` module inside tests. This allows you to define `miniflare` configuration based on injected values from [`globalSetup`](https://vitest.dev/config/#globalsetup) scripts. Use this if you have a value in your configuration that is dynamically generated and only known at runtime of your tests. For example, a global setup script might start an upstream server on a random port. This port could be `provide()`d and then `inject()`ed in the configuration for an external service binding or [Hyperdrive](/hyperdrive/).
```

2024-03-11 19:49 UTC, deadlypants1973 commented on content/workers/testing/vitest-integration/get-started/migrate-from-miniflare-2.md
> +Miniflare 2 provided custom environments for Jest and Vitest in the `jest-environment-miniflare` and `vitest-environment-miniflare` packages respectively.
```suggestion
[Miniflare 2](https://github.com/cloudflare/miniflare?tab=readme-ov-file) provided custom environments for Jest and Vitest in the `jest-environment-miniflare` and `vitest-environment-miniflare` packages respectively.
```

2024-03-11 19:49 UTC, deadlypants1973 commented on content/workers/testing/vitest-integration/get-started/migrate-from-miniflare-2.md
> +The `@cloudflare/vitest-pool-workers` package provides similar functionality using modern Miniflare versions and the [`workerd` runtime](https://github.com/cloudflare/workerd). This is the exact same
```suggestion
The `@cloudflare/vitest-pool-workers` package provides similar functionality using modern Miniflare versions and the [`workerd` runtime](https://github.com/cloudflare/workerd). `workerd` is a JavaScript/Wasm server runtime based on the same code that powers Cloudflare Workers. Using `workerd` practically eliminates behavior mismatches between your tests and deployed code. Refer to the [Miniflare 3 announcement](https://blog.cloudflare.com/miniflare-and-workerd) for more information.
```

2024-03-11 19:49 UTC, deadlypants1973 commented on content/workers/testing/vitest-integration/get-started/migrate-from-miniflare-2.md
> +The Workers Vitest integration does not support testing Workers using the Service Worker format. Please [migrate to the ES modules format](/workers/reference/migrate-to-module-workers/) first.
```suggestion
The Workers Vitest integration does not support testing Workers using the Service Worker format. [Migrate to ES modules format](/workers/reference/migrate-to-module-workers/) first.
```

2024-03-11 19:49 UTC, deadlypants1973 commented on content/workers/testing/vitest-integration/get-started/migrate-from-miniflare-2.md
> +## Installing the integration
```suggestion
## Install the Workers Vitest integration
```

2024-03-11 20:15 UTC, deadlypants1973 reviewed
PCX review part 2

2024-03-11 20:15 UTC, deadlypants1973 commented on content/workers/testing/debugging-tools.md
> +* [Local Development](/workers/testing/local-development) - Develop your Workers and connected resources locally via Wrangler and the Cloudflare Workers runtime, [`workerd`](https://github.com/cloudf
```suggestion
* [Local Development](/workers/testing/local-development) - Develop your Workers and connected resources locally via Wrangler and {{<glossary-tooltip term_id="workerd" link="https://github.com/cloudflare/workerd">}}`workerd`{{</glossary-tooltip>}}, for a fast, accurate feedback loop.
```

2024-03-11 20:15 UTC, deadlypants1973 commented on content/workers/testing/debugging-tools.md
> +* [Local Development](/workers/testing/local-development) - Develop your Workers and connected resources locally via Wrangler and the Cloudflare Workers runtime, [`workerd`](https://github.com/cloudf
`workerd` is based on the Cloudflare runtime but not the Cloudflare runtime. Correction here to match its definition.

2024-03-11 20:15 UTC, deadlypants1973 commented on content/workers/testing/vitest-integration/get-started/migrate-from-miniflare-2.md
> +First, you will need to uninstall the old _environment_ and install the new _pool_. Vitest environments can only customise the global scope, whereas pools can run tests using a completely different _
```suggestion
First, you will need to uninstall the old environment and install the new pool. Vitest environments can only customize the global scope, whereas pools can run tests using a completely different runtime. In this case, the pool runs your tests inside {{<glossary-tooltip term_id="workerd" link="https://github.com/cloudflare/workerd">}}`workerd`{{</glossary-tooltip>}} instead of Node.js.
```

2024-03-11 20:15 UTC, deadlypants1973 commented on content/workers/testing/vitest-integration/get-started/migrate-from-miniflare-2.md
> +## Updating your Vitest configuration file
```suggestion
## Update your Vitest configuration file
```

2024-03-11 20:15 UTC, deadlypants1973 commented on content/workers/testing/vitest-integration/get-started/migrate-from-miniflare-2.md
> +After that, update your Vitest configuration file to use the pool instead. Most Miniflare configuration previously specified `environmentOptions` can be moved to `poolOptions.workers.miniflare` inste
```suggestion
After installing the Workers Vitest configuration, update your Vitest configuration file to use the pool instead. Most Miniflare configuration previously specified `environmentOptions` can be moved to `poolOptions.workers.miniflare` instead. Refer to [Miniflare's `WorkerOptions` interface](https://github.com/cloudflare/workers-sdk/blob/main/packages/miniflare/README.md#interface-workeroptions) for supported options and the [Miniflare version 2 to 3 migration guide](https://miniflare.dev/get-started/migrating#api-changes) for more information. If you relied on configuration stored in a `wrangler.toml` file, set `wrangler.configPath` too.
```

2024-03-11 20:15 UTC, deadlypants1973 commented on content/workers/testing/vitest-integration/get-started/migrate-from-miniflare-2.md
> +## Updating your TypeScript configuration file
```suggestion
## Update your TypeScript configuration file
```

2024-03-11 20:15 UTC, deadlypants1973 commented on content/workers/testing/vitest-integration/get-started/migrate-from-miniflare-2.md
> +## Accessing bindings
```suggestion
## Access bindings
```

2024-03-11 20:15 UTC, deadlypants1973 commented on content/workers/testing/vitest-integration/get-started/migrate-from-miniflare-2.md
> +If your are using TypeScript, add an ambient `.d.ts` declaration file defining a `ProvidedEnv` `interface` in the `cloudflare:test` module to control the type of `env`:
```suggestion
If you are using TypeScript, add an ambient `.d.ts` declaration file defining a `ProvidedEnv` `interface` in the `cloudflare:test` module to control the type of `env`:
```

2024-03-11 20:15 UTC, deadlypants1973 commented on content/workers/testing/vitest-integration/get-started/migrate-from-miniflare-2.md
> +## Enabling isolated storage
```suggestion
## Enable isolated storage
```

2024-03-11 20:15 UTC, deadlypants1973 commented on content/workers/testing/vitest-integration/get-started/migrate-from-miniflare-2.md
> +## Working with `waitUntil()`
```suggestion
## Work with `waitUntil()`
```

2024-03-11 20:15 UTC, deadlypants1973 commented on content/workers/testing/vitest-integration/get-started/migrate-from-miniflare-2.md
> +## Mocking outbound requests
```suggestion
## Mock outbound requests
```

2024-03-11 20:15 UTC, deadlypants1973 commented on content/workers/testing/vitest-integration/get-started/migrate-from-miniflare-2.md
> +The `getMiniflareFetchMock()` function has been replaced with the new `fetchMock` helper from the `cloudflare:test` module. This has the same type as the return type of `getMiniflareFetchMock()`. The
```suggestion
The `getMiniflareFetchMock()` function has been replaced with the new `fetchMock` helper from the `cloudflare:test` module. ______ has the same type as the return type of `getMiniflareFetchMock()`. There are a couple of differences between `fetchMock` and the previous return value of `getMiniflareFetchMock()`:
```
What is the proper noun of "this"?

2024-03-11 20:15 UTC, deadlypants1973 commented on content/workers/testing/vitest-integration/get-started/migrate-from-miniflare-2.md
> +- `fetchMock` is deactivated by default, whereas previously it would start activated. This prevents unnecessary buffering of request bodies if you are not using `fetchMock`. You will need to call `fe
```suggestion
- `fetchMock` is deactivated by default, whereas previously it would start activated. This deactivation prevents unnecessary buffering of request bodies if you are not using `fetchMock`. You will need to call `fetchMock.activate()` before calling `fetch()` to enable it.
```
Define "this" as a proper noun

2024-03-11 20:15 UTC, deadlypants1973 commented on content/workers/testing/vitest-integration/get-started/migrate-from-miniflare-2.md
> +- `fetchMock` is reset at the start of each test run, whereas previously interceptors added in previous runs would apply to the current one. This ensures test runs are not affected by previous runs.
```suggestion
- `fetchMock` is reset at the start of each test run, whereas previously, interceptors added in previous runs would apply to the current one. This ensures test runs are not affected by previous runs.
```

2024-03-11 20:15 UTC, deadlypants1973 commented on content/workers/testing/vitest-integration/get-started/migrate-from-miniflare-2.md
> +## Using Durable Object helpers
```suggestion
## Use Durable Object helpers
```

2024-03-11 20:15 UTC, deadlypants1973 commented on content/workers/testing/vitest-integration/get-started/migrate-from-miniflare-2.md
> +The `getMiniflareDurableObjectStorage()`, `getMiniflareDurableObjectState()`, `getMiniflareDurableObjectInstance()`, and `runWithMiniflareDurableObjectGates()` functions have all been replaced with a
```suggestion
The `getMiniflareDurableObjectStorage()`, `getMiniflareDurableObjectState()`, `getMiniflareDurableObjectInstance()`, and `runWithMiniflareDurableObjectGates()` functions have all been replaced with a single `runInDurableObject()` function from the `cloudflare:test` module. The ____ functions accepts a `DurableObjectStub` with a callback accepting the Durable Object instance and corresponding `DurableObjectState` as arguments. Consolidating these functions into a single function simplifies the API surface, and ensures instances are accessed with the correct request context and [gating behavior](https://blog.cloudflare.com/durable-objects-easy-fast-correct-choose-three/). Refer to the [Test APIs page](/workers/testing/vitest/test-apis/) for more details.
```
Replace 'this' with the function name

2024-03-11 20:15 UTC, deadlypants1973 commented on content/workers/testing/vitest-integration/get-started/migrate-from-miniflare-2.md
> +The `flushMiniflareDurableObjectAlarms()` function has been replaced with the `runDurableObjectAlarm()` function from the `cloudflare:test` module. This function accepts a single `DurableObjectStub`
```suggestion
The `flushMiniflareDurableObjectAlarms()` function has been replaced with the `runDurableObjectAlarm()` function from the `cloudflare:test` module. The ___ function accepts a single `DurableObjectStub` and returns a `Promise` that resolves to `true` if an alarm was scheduled and the `alarm()` handler was executed, or `false` otherwise. To flush multiple instances' alarms, call `runDurableObjectAlarm()` in a loop.
```
Replace 'this' with the function name

2024-03-11 20:15 UTC, deadlypants1973 commented on content/workers/testing/vitest-integration/get-started/migrate-from-miniflare-2.md
> +Finally, the `getMiniflareDurableObjectIds()` function has been replaced with the `listDurableObjectIds()` function from the `cloudflare:test` module. This function now accepts a `DurableObjectNamesp
```suggestion
Finally, the `getMiniflareDurableObjectIds()` function has been replaced with the `listDurableObjectIds()` function from the `cloudflare:test` module. The ___ function now accepts a `DurableObjectNamespace` instance instead of a namespace `string` to provide stricter typing. The ____ function now respects isolated storage. If enabled, IDs of objects created in other tests will not be returned.
```
Replace 'this' with the name of the function

2024-03-11 20:15 UTC, deadlypants1973 commented on content/workers/testing/vitest-integration/get-started/write-your-first-test.md
> +  description: A guide to help you get set up to write unit tests against Workers.
```suggestion
  description: Write unit tests against Workers.
```

2024-03-11 20:15 UTC, deadlypants1973 commented on content/workers/testing/vitest-integration/get-started/migrate-from-unstable-dev.md
> +title: Migrate from unstable_dev
```suggestion
title: Migrate from `unstable_dev`
```

2024-03-11 20:15 UTC, deadlypants1973 commented on content/workers/testing/vitest-integration/get-started/migrate-from-unstable-dev.md
> +  description: Test your Worker in local development.
```suggestion
  description: Migrate from the [`unstable_dev`](/workers/wrangler/api/#unstable_dev) API to writing tests with thhe Workers Vitest integration.
```
Need a proper description for this guide.

2024-03-11 20:15 UTC, deadlypants1973 commented on content/workers/testing/vitest-integration/get-started/_index.md
> +{{<directory-listing>}}
```suggestion
{{<directory-listing showDescriptions="true">}}
```

2024-03-11 20:15 UTC, deadlypants1973 commented on content/workers/testing/vitest-integration/get-started/migrate-from-miniflare-2.md
> +pcx_content_type: concept
```suggestion
pcx_content_type: concept
meta:
  description: Migrate from [Miniflare 2](https://github.com/cloudflare/miniflare?tab=readme-ov-file) to the Workers Vitest integration.
```

2024-03-11 20:15 UTC, deadlypants1973 commented on content/workers/testing/vitest-integration/get-started/migrate-from-unstable-dev.md
> +This guide demonstrates key differences between tests written with the `unstable_dev` API and the Workers Vitest integration. For more information on writing tests with the Workers Vitest integration
```suggestion
This guide demonstrates key differences between tests written with the `unstable_dev` API and the Workers Vitest integration. For more information on writing tests with the Workers Vitest integration, refer to [Write your first test](/workers/testing/vitest/get-started/write-your-first-test/).
```

2024-03-11 20:15 UTC, deadlypants1973 commented on content/workers/testing/vitest-integration/get-started/migrate-from-unstable-dev.md
> +## Referencing a Worker for Integration Testing
```suggestion
## Reference a Worker for integration testing
```

2024-03-11 20:15 UTC, deadlypants1973 commented on content/workers/testing/vitest-integration/get-started/migrate-from-unstable-dev.md
> +With the Workers Vitest integration, now you can do the same thing using the `SELF` fetcher from `cloudflare:test`:
```suggestion
With the Workers Vitest integration, you can accomplish the same goal using the `SELF` fetcher from `cloudflare:test`:
```

2024-03-11 20:15 UTC, deadlypants1973 commented on content/workers/testing/vitest-integration/get-started/migrate-from-unstable-dev.md
> +## Stopping a Worker
```suggestion
## Stop a Worker
```

2024-03-11 20:15 UTC, deadlypants1973 commented on content/workers/testing/vitest-integration/get-started/migrate-from-unstable-dev.md
> +With the Workers Vitest integration there is no need to stop a Worker via `worker.stop()`. This is handled automatically after tests run.
```suggestion
With the Workers Vitest integration, there is no need to stop a Worker via `worker.stop()`. This functionality is handled automatically after tests run.
```

2024-03-11 20:15 UTC, deadlypants1973 commented on content/workers/testing/vitest-integration/get-started/migrate-from-unstable-dev.md
> +## Importing Wrangler Config
```suggestion
## Import Wrangler configuration
```

2024-03-11 20:15 UTC, deadlypants1973 commented on content/workers/testing/vitest-integration/get-started/migrate-from-unstable-dev.md
> +Via the `unstable_dev` API, you can reference a `wrangler.toml` config file by adding it as an option like this:
```suggestion
Via the `unstable_dev` API, you can reference a `wrangler.toml` configuration file by adding it as an option:
```

2024-03-11 20:15 UTC, deadlypants1973 commented on content/workers/testing/vitest-integration/get-started/migrate-from-unstable-dev.md
> +With the Workers Vitest integration, you can now set this in `vitest.config.js` for all of your tests.
```suggestion
With the Workers Vitest integration, you can now set ___ in `vitest.config.js` for all of your tests:
```
Define 'this', what are you setting?

2024-03-11 20:15 UTC, deadlypants1973 commented on content/workers/testing/vitest-integration/get-started/migrate-from-unstable-dev.md
> +## Testing Service Workers
```suggestion
## Test service Workers
```

2024-03-12 11:24 UTC, deadlypants1973 commented on content/workers/testing/vitest-integration/get-started/migrate-from-unstable-dev.md
> +Unlike the `unstable_dev` API, Workers Vitest integration does not support testing Workers using the Service Worker format. You will need to first [migrate to the ES modules format](/workers/referenc
```suggestion
Unlike the `unstable_dev` API, the Workers Vitest integration does not support testing Workers using the service worker format. You will need to first [migrate to the ES modules format](/workers/reference/migrate-to-module-workers/) in order to use the Workers Vitest integration.
```

2024-03-12 11:24 UTC, deadlypants1973 commented on content/workers/testing/_index.md
> +| Testing Service Workers                   | ❌               | ✅               | ✅                   |
```suggestion
| Testing service Workers                   | ❌               | ✅               | ✅                   |
```

2024-03-12 11:50 UTC, deadlypants1973 commented on content/workers/testing/vitest-integration/configuration.md
> +The following functions are exported from the `@cloudflare/vitest-pool-workers/config` module.
I've never seen any Cloudflare runtime API documentation where we had a `:` symbol next to the option. `:` should denote a return: https://developers.cloudflare.com/workers/runtime-apis/web-crypto/#subtlecrypto-methods and `<>` will denote wat the Promise is returning.

Is this intentional? What is it representing?

2024-03-12 13:03 UTC, deadlypants1973 reviewed
PCX final review commentary

2024-03-12 13:03 UTC, deadlypants1973 commented on content/workers/testing/vitest-integration/get-started/write-your-first-test.md
> +- Open your Worker project's root folder or create a new project via our [Get Started guide](/workers/get-started/guide/#1-create-a-new-worker-project)
```suggestion
- Open your Worker project's root folder or create a new project via the [Workers Get started guide](/workers/get-started/guide/#1-create-a-new-worker-project)
```

2024-03-12 13:03 UTC, deadlypants1973 commented on content/workers/testing/_index.md
> +Review the tools available for testing and debugging Workers.
Will this be applicable to Pages Functions as well? This is called out a few times here and there but not standardized. Let's call this out here if this is true.

2024-03-12 13:03 UTC, deadlypants1973 commented on content/workers/testing/_index.md
> +Review the tools available for testing and debugging Workers.
```suggestion
Review the tools available for testing and debugging Workers and [Pages Functions](/pages/functions/).
```

2024-03-12 13:03 UTC, deadlypants1973 commented on content/workers/testing/vitest-integration/_index.md
> +Information about the Workers Vitest integration - the recommended package for writing unit and integration tests for Workers.
Can this also be used with Pages Functions? If so, let's call that out here.

2024-03-12 13:03 UTC, deadlypants1973 commented on content/workers/testing/vitest-integration/get-started/_index.md
> +  description: Install and set up the Workers Vitest integration - a tool for writing unit and integration tests for Workers.
```suggestion
  description: Install and set up the Workers Vitest integration - a tool for writing unit and integration tests for Workers and Pages Functions.
```

2024-03-12 13:03 UTC, deadlypants1973 commented on content/workers/testing/vitest-integration/get-started/migrate-from-miniflare-2.md
> +  description: Migrate from [Miniflare 2](https://github.com/cloudflare/miniflare?tab=readme-ov-file) to the Workers Vitest integration.
```suggestion
```

2024-03-12 13:03 UTC, deadlypants1973 commented on content/workers/testing/vitest-integration/get-started/write-your-first-test.md
> +This guide will guide you through install and setup of the [`@cloudflare/vitest-pool-workers`](https://workers.cloudflare.com) package, and will help you get started writing tests against your Worker
```suggestion
This guide will guide you through install and setup of the `@cloudflare/vitest-pool-workers` package, and will help you get started writing tests against your Workers using Vitest. This package works by running code that Vitest would usually run inside a [Node.js worker thread](https://nodejs.org/api/worker_threads.html) inside a Cloudflare Worker instead.
```
A GH repo link would be more helpful for the package rather than route to marketing page.

2024-03-12 13:03 UTC, deadlypants1973 commented on content/workers/testing/_index.md
> +Review the tools available for testing and debugging Workers.
@admah let's make a partial aside that says:

```
{{<Aside type="note" header="Pages Functions">}}

The content described on this page is also applicable to [Pages Functions](/pages/functions/). Pages Functions are Cloudflare Workers and can be thought of synonymously with Workers in this context.

{{</Aside>}}
```

and add it to the relevant guides in this PR. I don't want us to go in and change all the wording, I'd rather stick with the Worker wording to align for convergence goals and use the aside as an educational piece.

2024-03-12 13:03 UTC, deadlypants1973 commented on content/workers/testing/integration-testing.md
> +In the above example, instead of importing the `add` function as a unit test would do, you make a direct call to the endpoint, testing that the Worker responds at the endpoint with the appropriate re
```suggestion
In the above example, instead of importing the `add` function as a [unit test](/workers/testing/unit-testing/) would do, you make a direct call to the endpoint, testing that the Worker responds at the endpoint with the appropriate response.
```

2024-03-12 13:03 UTC, deadlypants1973 commented on content/workers/testing/vitest-integration/internal-details.md
> +---
This .md file is named `internal-details`? Should we change it to `isolation-and-concurrency`?

2024-03-12 13:03 UTC, deadlypants1973 commented on content/workers/testing/vitest-integration/internal-details.md
> +In this model, a single `workerd` process is started with a single Worker for all test files. Test files are executed in serial but `.concurrent` tests are supported. Every test will read/write from
making sure that there is nothing that is supposed to go here after serial? seems like an incomplete sentence

2024-03-12 13:03 UTC, deadlypants1973 commented on content/workers/testing/vitest-integration/internal-details.md
> +In this model, a single `workerd` process is started with a single Worker for all test files. Test files are executed in serial and `.concurrent` tests are not supported. Each test will read/write fr
same comment about serial as above

2024-03-12 13:03 UTC, deadlypants1973 commented on content/workers/testing/vitest-integration/internal-details.md
> +The Workers Vitest pool works by running code inside a Cloudflare Worker that Vitest would usually run inside a [Node.js worker thread](https://nodejs.org/api/worker_threads.html). To make this possi
Change 'it' to its proper noun in the last sentence

2024-03-12 13:03 UTC, deadlypants1973 commented on content/workers/testing/vitest-integration/internal-details.md
> +This may cause your Worker to behave differently when deployed than under test, as Node-style resolution and additional polyfills will be available to your Worker's source code and dependencies too.
Change 'this' to the proper noun

2024-03-12 13:03 UTC, deadlypants1973 commented on content/workers/testing/vitest-integration/internal-details.md
> +This may cause your Worker to behave differently when deployed than under test, as Node-style resolution and additional polyfills will be available to your Worker's source code and dependencies too.
```suggestion
___ may cause your Worker to behave differently when deployed than during testing, as Node-style resolution and additional polyfills will be available to your Worker's source code and dependencies.
```

2024-03-12 13:03 UTC, deadlypants1973 commented on content/workers/testing/vitest-integration/test-apis.md
> +The Workers Vitest integration provides runtime helpers for writing tests in the `cloudflare:test` module. This module is provided by the `@cloudflare/vitest-pool-workers` package, but can only be im
```suggestion
The Workers Vitest integration provides runtime helpers for writing tests in the `cloudflare:test` module. The `cloudflare:test` module is provided by the `@cloudflare/vitest-pool-workers` package, but can only be imported from test files that execute in the Workers runtime.
```

2024-03-12 13:03 UTC, deadlypants1973 commented on content/workers/testing/vitest-integration/test-apis.md
> +  - Exposes the [`env` object](/workers/runtime-apis/handlers/fetch/#parameters) for use as the 2nd argument passed to modules-format exported handlers. This provides access to [bindings](/workers/ru
```suggestion
  - Exposes the [`env` object](/workers/runtime-apis/handlers/fetch/#parameters) for use as the second argument passed to ES modules format exported handlers. This provides access to [bindings](/workers/runtime-apis/bindings/) that you have defined in your [Vitest configuration file](/workers/testing/vitest/configuration/).
```

2024-03-12 13:03 UTC, deadlypants1973 commented on content/workers/testing/vitest-integration/test-apis.md
> +  - [Service binding](/workers/runtime-apis/service-bindings/) to the default export defined in the `main` Worker. Use this to write integration tests against your Worker. Note this `main` Worker run
```suggestion
  - [Service binding](/workers/runtime-apis/service-bindings/) to the default export defined in the `main` Worker. Use this to write integration tests against your Worker. The `main` Worker runs in the same isolate/context as tests so any global mocks will apply to it too.
```

2024-03-12 13:03 UTC, deadlypants1973 commented on content/workers/testing/vitest-integration/test-apis.md
> +  - Declarative interface for mocking outbound `fetch()` requests. Deactivated by default and reset before running each test file. Refer to [`undici`'s `MockAgent` documentation](https://undici.nodej
```suggestion
  - Declarative interface for mocking outbound `fetch()` requests. Deactivated by default and reset before running each test file. Refer to [`undici`'s `MockAgent` documentation](https://undici.nodejs.org/#/docs/api/MockAgent) for more information. Note this only mocks `fetch()` requests for the current test runner Worker. Auxiliary Workers should mock `fetch()`es using the Miniflare `fetchMock`/`outboundService` options. Refer to [Configuration](/workers/testing/vitest/configuration/#workerspooloptions) for more information.
```

2024-03-12 13:03 UTC, deadlypants1973 commented on content/workers/testing/vitest-integration/test-apis.md
> +  - Creates an instance of the [`context` object](/workers/runtime-apis/handlers/fetch/#parameters) for use as the 3rd argument to modules-format exported handlers.
```suggestion
  - Creates an instance of the [`context` object](/workers/runtime-apis/handlers/fetch/#parameters) for use as the third argument to ES modules format exported handlers.
```

2024-03-12 13:03 UTC, deadlypants1973 commented on content/workers/testing/vitest-integration/test-apis.md
> +  - Use this to wait for all promises passed to `ctx.waitUntil()` to settle, before running test assertions on any side effects. Only accepts instances of `ExecutionContext` returned by `createExecut
```suggestion
  - Use this to wait for all Promises passed to `ctx.waitUntil()` to settle, before running test assertions on any side effects. Only accepts instances of `ExecutionContext` returned by `createExecutionContext()`.
```

2024-03-12 13:03 UTC, deadlypants1973 commented on content/workers/testing/vitest-integration/test-apis.md
> +    This temporarily replaces your Durable Object's `fetch()` handler with `callback`, then sends a request to it, returning the result. This can be used to call/spy-on Durable Object instance method
```suggestion
    This temporarily replaces your Durable Object's `fetch()` handler with `callback`, then sends a request to it, returning the result. This can be used to call/spy-on Durable Object instance methods or seed/get persisted data. Note this can only be used with `stub`s pointing to Durable Objects defined in the `main` Worker.
```

2024-03-12 13:03 UTC, deadlypants1973 commented on content/workers/testing/vitest-integration/test-apis.md
> +- {{<code>}}runDurableObjectAlarm(stub:{{<param-type>}}DurableObjectStub{{</param-type>}}): {{<type>}}Promise\<boolean>{{</type>}}{{</code>}}
```suggestion
- {{<code>}}runDurableObjectAlarm(stub:{{<param-type>}}DurableObjectStub{{</param-type>}}){{</code>}}: {{<type>}}Promise\<boolean>{{</type>}}
```

2024-03-12 13:03 UTC, deadlypants1973 commented on content/workers/testing/vitest-integration/test-apis.md
> +  - Immediately runs and removes the Durable Object pointed-to by `stub`'s alarm if one is scheduled. Returns `true` if an alarm ran, and `false` otherwise. Note this can only be used with `stub`s po
```suggestion
  - Immediately runs and removes the Durable Object pointed to by `stub`'s alarm if one is scheduled. Returns `true` if an alarm ran, and `false` otherwise. Note this can only be used with `stub`s pointing to Durable Objects defined in the `main` Worker.
```

2024-03-12 13:03 UTC, deadlypants1973 commented on content/workers/testing/vitest-integration/test-apis.md
> +- {{<code>}}listDurableObjectIds(namespace:{{<param-type>}}DurableObjectNamespace{{</param-type>}}): {{<type>}}Promise\<DurableObjectId[]>{{</type>}}{{</code>}}
```suggestion
- {{<code>}}listDurableObjectIds(namespace:{{<param-type>}}DurableObjectNamespace{{</param-type>}}){{</code>}}: {{<type>}}Promise\<DurableObjectId[]>{{</type>}}
```

2024-03-12 13:03 UTC, deadlypants1973 commented on content/workers/testing/vitest-integration/test-apis.md
> +  - Gets the IDs of all objects that have been created in the `namespace`. Respects `isolatedStorage` if enabled, meaning objects created in a different test won't be returned.
```suggestion
  - Gets the IDs of all objects that have been created in the `namespace`. Respects `isolatedStorage` if enabled, meaning objects created in a different test will not be returned.
```

2024-03-12 19:00 UTC, admah commented on content/workers/testing/integration-testing.md
> +When using `SELF` for integration tests, your worker code runs in the same context as the test runner. This means you can use global mocks to control your worker, but also means your worker uses the
This is saying that when using this method, the Worker will act the same way Vite does in terms of module resolution and not the way a Worker traditionally acts.

2024-03-13 13:15 UTC, deadlypants1973 commented on content/workers/testing/integration-testing.md
> +Usually this is not a problem, but if you would like to run your Worker in a fresh environment that is as close to production as possible, using an auxiliary Worker may be a good idea. Auxiliary Work
We need an "An auxiliary Worker is ..." definition for the glossary. @admah @mrbbot

2024-03-13 14:27 UTC, admah commented on content/workers/testing/integration-testing.md
> +Usually this is not a problem, but if you would like to run your Worker in a fresh environment that is as close to production as possible, using an auxiliary Worker may be a good idea. Auxiliary Work
Yes. I will add that 👍

2024-03-13 14:29 UTC, deadlypants1973 commented on content/workers/testing/vitest-integration/configuration.md
> +- {{<code>}}defineWorkersPoolOptions(options:{{<param-type>}}WorkersPoolOptions | ((ctx: WorkersPoolOptionsContext) => WorkersPoolOptions | Promise\<WorkersPoolOptions>){{</param-type>}}){{</code>}}
```suggestion
- {{<code>}}defineWorkersPoolOptions(options:{{<param-type>}}WorkersPoolOptions | ((ctx: WorkersPoolOptionsContext){{</code>}}: WorkersPoolOptions | Promise\<WorkersPoolOptions>){{</param-type>}})
```

2024-03-13 16:46 UTC, admah commented on content/workers/testing/_index.md
> +Review the tools available for testing and debugging Workers.
I've added this and added it to relevant pages.

2024-03-13 16:46 UTC, admah commented on content/workers/testing/vitest-integration/_index.md
> +Information about the Workers Vitest integration - the recommended package for writing unit and integration tests for Workers.
I've added the partial to this page.

2024-03-14 15:04 UTC, petebacondarwin approved these changes

2024-03-14 15:10 UTC, irvinebroque approved these changes

2024-03-14 15:33 UTC, crwaters16 approved these changes

2024-03-14 15:42 UTC, kodster28 approved these changes

2024-03-14 15:45 UTC, merged