Remove dns-over-twitter.md
cloudflare/cloudflare-docs pull request #1313
Opened 2021-05-11 00:25 UTC by MeesJ

It looks like the Twitter account in dns-over-twitter.md is no longer active. That's why this page should be removed from the knowledgebase.

2021-05-11 02:07 UTC, YoutacRSVARs requested changes
Twitter is active youtac_va

2021-05-11 07:40 UTC, MeesJ reviewed
I've tried using the bot, and I haven't got any reply. The last Tweet made by the bot was posted in December 2019. Because of these things, I assume that the bot isn't active anymore.

2021-05-13 07:59 UTC, YoutacRSVARs commented
Don't follow the bots follow me VAR youtac_va

2021-05-13 08:03 UTC, YoutacRSVARs approved these changes

2021-05-20 08:17 UTC, marciocloudflare approved these changes

2021-05-20 08:32 UTC, abracchi-tw approved these changes

2021-05-20 08:34 UTC, merged