add note about DO bindings in the getPlatformProxy docs
cloudflare/cloudflare-docs pull request #13143
Opened 2024-02-25 21:10 UTC by dario-piotrowicz

2024-02-26 15:18 UTC, irvinebroque commented on content/workers/wrangler/api.md
> +    * To use a Durable Object binding with `getPlatformProxy`, you need to always specify a `script_name` for it
```suggestion
    * To use a Durable Object binding with `getPlatformProxy`, you need to always specify a `script_name` for it
```

Someone building an application directly on Workers doesn't normally interact with or know about `getPlatformProxy` — is what you really mean here something like "to use Durable Objects in a Pages project"?

2024-02-26 15:18 UTC, irvinebroque commented on content/workers/wrangler/api.md
> +    * To use a Durable Object binding with `getPlatformProxy`, you need to always specify a `script_name` for it
Oh nvm I get it now where these docs are.

2024-02-26 15:18 UTC, irvinebroque approved these changes

2024-02-27 15:48 UTC, deadlypants1973 commented on content/workers/wrangler/api.md
> +      For example, in your Worker project's `wrangler.toml` file, you have a Durable Object with certain `class_name` and `script_name` set to `"my-worker"`. The same exact `class_name` is also used
Shouldn't `class_name` be set to the name of the class, not the Worker? I am confused about this example.

2024-02-27 15:48 UTC, deadlypants1973 reviewed
Example unclear

2024-02-27 15:51 UTC, deadlypants1973 requested changes

2024-02-27 15:51 UTC, deadlypants1973 commented on content/workers/wrangler/api.md
> +      For example, in your Worker project's `wrangler.toml` file, you have a Durable Object with certain `class_name` and `script_name` set to `"my-worker"`. The same exact `class_name` is also used
```suggestion
      For example, in your Worker project's `wrangler.toml` file, you have a Durable Object with `script_name` set to `"my-worker"` and a certain `class_name`. The same exact `class_name` is also used by a Durable Object binding in your `my-worker` Worker, and you are running the Worker via `wrangler dev`. Calling `getPlatformProxy` will then successfully generate a proxy to the Durable Object defined in the `my-worker` Worker.
```

2024-02-27 15:51 UTC, deadlypants1973 commented on content/workers/wrangler/api.md
> +      For example, in your Worker project's `wrangler.toml` file, you have a Durable Object with certain `class_name` and `script_name` set to `"my-worker"`. The same exact `class_name` is also used
This example needs some clarity as I am not sure by reading how many Workers are involved in this example

2024-02-27 17:18 UTC, dario-piotrowicz commented on content/workers/wrangler/api.md
> +      For example, in your Worker project's `wrangler.toml` file, you have a Durable Object with certain `class_name` and `script_name` set to `"my-worker"`. The same exact `class_name` is also used
I gave it a shot, please have another look 🙏

2024-04-26 13:20 UTC, closed without merging