Create many-cfd-one-tunnel.md
cloudflare/cloudflare-docs pull request #1315
Opened 2021-05-11 02:22 UTC by abelinkinbio

First tutorial. Let me know where questions you have.

2021-05-11 02:32 UTC, adamchalmers requested changes

2021-05-11 02:32 UTC, adamchalmers commented on products/cloudflare-one/src/content/tutorials/many-cfd-one-tunnel.md
> +You can use [Cloudflare Tunnel](/connections/connect-apps) to connect applications and servers to Cloudflare's network. Tunnel relies on a piece of software, `cloudflared`, to create those connection
I suggest making cloudflared here a link to something, maybe github.com/cloudflare/cloudflared

2021-05-11 02:32 UTC, adamchalmers commented on products/cloudflare-one/src/content/tutorials/many-cfd-one-tunnel.md
> +The same Tunnel can also represent multiple, redundant instances of `cloudflared`, giving you the ability to scale instances dynamically in a replica model.
A tunnel doesn't represent a cloudflared, a cloudflared runs a tunnel. I suggest "The same tunnel can be run from multiple instances of cloudflared, giving you the ability to run many cloudflared replicas to scale your system when incoming traffic changes."

2021-05-11 02:32 UTC, adamchalmers commented on products/cloudflare-one/src/content/tutorials/many-cfd-one-tunnel.md
> +In this tutorial, we will walkthrough running an app in a Kubernetes [Service](https://kubernetes.io/docs/concepts/services-networking/service/), and then running `cloudflared` in a separate [Deploym
I think "walkthrough" as a verb should be "walk through"

2021-05-11 02:32 UTC, adamchalmers commented on products/cloudflare-one/src/content/tutorials/many-cfd-one-tunnel.md
> +This architecture allows `cloudflared` instances to proxy internet traffic into whichever Kubernetes Service it was configured to. Alternatively, if your cluster already has an ingress controller (e.
If this tutorial doesn't cover using cloudflared to point at an ingress controller like Envoy, then I suggest removing any reference to that idea.

2021-05-11 02:32 UTC, adamchalmers commented on products/cloudflare-one/src/content/tutorials/many-cfd-one-tunnel.md
> +$ brew install cloudflare/cloudflare/cloudflared
I wouldn't assume users are on MacOS, I'd say something generic instead, like "you can probably find cloudflared in your system's package manager, see <this page> for details"

2021-05-11 02:32 UTC, adamchalmers commented on products/cloudflare-one/src/content/tutorials/many-cfd-one-tunnel.md
> +## Login to to Cloudflare
double 'to'

2021-05-11 02:32 UTC, adamchalmers commented on products/cloudflare-one/src/content/tutorials/many-cfd-one-tunnel.md
> +Now, we'll deploy `cloudflared` by applying its manifest. This will start a [Deployment](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/) for running `cloudflared` and a [Config
"What manifest? This tutorial never mentioned a manifest. Where do I download the manifest from?"
I suggest linking to it, or copying it inline here.

You'll also need to link or explain the example service that's being proxied to. In my example I used "httpbin" and supplied a manifest for it.

2021-05-11 02:57 UTC, abelinkinbio commented on products/cloudflare-one/src/content/tutorials/many-cfd-one-tunnel.md
> +You can use [Cloudflare Tunnel](/connections/connect-apps) to connect applications and servers to Cloudflare's network. Tunnel relies on a piece of software, `cloudflared`, to create those connection
✅

2021-05-11 02:58 UTC, abelinkinbio commented on products/cloudflare-one/src/content/tutorials/many-cfd-one-tunnel.md
> +The same Tunnel can also represent multiple, redundant instances of `cloudflared`, giving you the ability to scale instances dynamically in a replica model.
Fair point - could have led to confusion. ✅

2021-05-11 02:58 UTC, abelinkinbio commented on products/cloudflare-one/src/content/tutorials/many-cfd-one-tunnel.md
> +In this tutorial, we will walkthrough running an app in a Kubernetes [Service](https://kubernetes.io/docs/concepts/services-networking/service/), and then running `cloudflared` in a separate [Deploym
✅

2021-05-11 02:59 UTC, abelinkinbio commented on products/cloudflare-one/src/content/tutorials/many-cfd-one-tunnel.md
> +This architecture allows `cloudflared` instances to proxy internet traffic into whichever Kubernetes Service it was configured to. Alternatively, if your cluster already has an ingress controller (e.
✂️

2021-05-11 02:59 UTC, abelinkinbio commented on products/cloudflare-one/src/content/tutorials/many-cfd-one-tunnel.md
> +$ brew install cloudflare/cloudflare/cloudflared
✅

2021-05-11 02:59 UTC, abelinkinbio commented on products/cloudflare-one/src/content/tutorials/many-cfd-one-tunnel.md
> +## Login to to Cloudflare
✂️

2021-05-11 03:01 UTC, abelinkinbio commented on products/cloudflare-one/src/content/tutorials/many-cfd-one-tunnel.md
> +Now, we'll deploy `cloudflared` by applying its manifest. This will start a [Deployment](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/) for running `cloudflared` and a [Config
I was at a bit of a loss for linking the manifest here. I may simply copy inline. I'll look into it tonight.

2021-05-11 06:53 UTC, TownLake requested changes

2021-05-11 06:53 UTC, TownLake commented on products/cloudflare-one/src/content/tutorials/many-cfd-one-tunnel.md
> +updated: 2021-05-10
Edit for Tuesday to 2021-05-11

2021-05-11 06:53 UTC, TownLake commented on products/cloudflare-one/src/content/tutorials/many-cfd-one-tunnel.md
> +Now, we'll deploy `cloudflared` by applying its manifest. This will start a [Deployment](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/) for running `cloudflared` and a [Config
probably worth walking through the architecture at a high-level here - how the instances scale up or down and describing once again how the tunnel can map to one or many, each instance will use the same credentials file etc

2021-05-11 08:08 UTC, nmldiegues commented on products/cloudflare-one/src/content/tutorials/many-cfd-one-tunnel.md
> +---
Do you want to add a difficulty here? Most other tutorials seem to indicate that.

2021-05-11 08:08 UTC, nmldiegues commented on products/cloudflare-one/src/content/tutorials/many-cfd-one-tunnel.md
> +The same tunnel can be run from multiple instances of `cloudflared`, giving you the ability to run many `cloudflared` replicas to scale your system when incoming traffic changes.
The title says `Tunnel` but here you use `tunnel`. Let's aim for consistency.

2021-05-11 08:08 UTC, nmldiegues commented on products/cloudflare-one/src/content/tutorials/many-cfd-one-tunnel.md
> +In this tutorial, we will walk through running an app in a Kubernetes [Service](https://kubernetes.io/docs/concepts/services-networking/service/), and then running `cloudflared` in a separate [Deploy
> an app

feels overly informal, I'd use "application"

2021-05-11 08:08 UTC, nmldiegues commented on products/cloudflare-one/src/content/tutorials/many-cfd-one-tunnel.md
> +Next, you will need to upload the credential file which was generated to Kubernetes as a secret. You will also need to provide the filepath that the Tunnel credentials file was created under as well.
> Next, you will need to upload the credential file which was generated to Kubernetes as a secret.

This reads strange.
I'd write it as:  "Next, you will upload the generated Tunnel credential file as a secret to your Kubernetes cluster".

2021-05-11 08:08 UTC, nmldiegues commented on products/cloudflare-one/src/content/tutorials/many-cfd-one-tunnel.md
> +Now, we'll deploy `cloudflared` by applying its manifest. This will start a [Deployment](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/) for running `cloudflared` and a [Config
IMO we should heavily delegate to https://github.com/cloudflare/argo-tunnel-examples/tree/master/named-tunnel-k8s

I'd avoid duplicating effort/contents

2021-05-11 08:08 UTC, nmldiegues commented on products/cloudflare-one/src/content/tutorials/many-cfd-one-tunnel.md
> +
Something cool to do at this point would be to manually change the number of replicas for the deployment.

```
kubectl scale --replicas=3 rs/cloudflared
```

2021-05-11 08:08 UTC, nmldiegues commented on products/cloudflare-one/src/content/tutorials/many-cfd-one-tunnel.md
> +We love to hear your feedback! Join a discussion with other community members at https://community.cloudflare.com/c/performance/argo-tunnel
I think we should have a "Wrap up" section that summarizes:
 - The same Tunnel can be ran in many cloudflared processes
 - This allows for elastic scaling
 - But can also be useful for graceful rolling upgrades of cloudfared (changing their binary and/or configuration)

2021-05-11 08:18 UTC, chungthuang commented on products/cloudflare-one/src/content/tutorials/many-cfd-one-tunnel.md
> +In this tutorial, we will walk through running an app in a Kubernetes [Service](https://kubernetes.io/docs/concepts/services-networking/service/), and then running `cloudflared` in a separate [Deploy
I would say it's running an app as a Kubernetes Service.

2021-05-11 08:19 UTC, chungthuang commented on products/cloudflare-one/src/content/tutorials/many-cfd-one-tunnel.md
> +$ cloudflare tunnel login
cloudflared.

2021-05-11 08:20 UTC, chungthuang commented on products/cloudflare-one/src/content/tutorials/many-cfd-one-tunnel.md
> +$ cloudflared tunnel create example-tunnel
Latest cloudflared output looks like this
```
$ cloudflared tunnel create demo
Tunnel credentials written to /Users/cf000197/.cloudflared/416a0fd5-b771-4dda-9949-966cc3652c94.json. cloudflared chose this file based on where your origin certificate was found. Keep this file secret. To revoke these credentials, delete the tunnel.

Created tunnel demo with id 416a0fd5-b771-4dda-9949-966cc3652c94
```

2021-05-11 10:57 UTC, abracchi-tw commented on products/cloudflare-one/src/content/tutorials/many-cfd-one-tunnel.md
> +In the example below, simply change <example-tunnel> to the name you wish to assign to your tunnel.
```suggestion
In the example below, simply change `<example-tunnel>` to the name you wish to assign to your Tunnel.
```

2021-05-11 10:57 UTC, abracchi-tw commented on products/cloudflare-one/src/content/tutorials/many-cfd-one-tunnel.md
> +The same tunnel can be run from multiple instances of `cloudflared`, giving you the ability to run many `cloudflared` replicas to scale your system when incoming traffic changes.
let's stick to `Tunnel`, I think that's what we went for in most other tutorials.

2021-05-11 14:00 UTC, abelinkinbio commented on products/cloudflare-one/src/content/tutorials/many-cfd-one-tunnel.md
> +---
✅

2021-05-11 14:01 UTC, abelinkinbio commented on products/cloudflare-one/src/content/tutorials/many-cfd-one-tunnel.md
> +The same tunnel can be run from multiple instances of `cloudflared`, giving you the ability to run many `cloudflared` replicas to scale your system when incoming traffic changes.
✅

2021-05-11 14:02 UTC, abelinkinbio commented on products/cloudflare-one/src/content/tutorials/many-cfd-one-tunnel.md
> +In this tutorial, we will walk through running an app in a Kubernetes [Service](https://kubernetes.io/docs/concepts/services-networking/service/), and then running `cloudflared` in a separate [Deploy
✅

2021-05-11 14:19 UTC, abelinkinbio commented on products/cloudflare-one/src/content/tutorials/many-cfd-one-tunnel.md
> +Now, we'll deploy `cloudflared` by applying its manifest. This will start a [Deployment](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/) for running `cloudflared` and a [Config
I've linked out to the named-tunnels-k8s tutorial for the cloudflared.yaml and app.yaml references. I agree we should try to have consistency amongst the two, but also want to ensure we're getting full coverage.

2021-05-11 14:38 UTC, abracchi-tw approved these changes

2021-05-11 17:24 UTC, TownLake approved these changes

2021-05-11 18:06 UTC, adamchalmers approved these changes

2021-05-11 18:08 UTC, merged

2021-05-17 11:49 UTC, YoutacRSVARs reviewed
__