[Pages] Document changing Direct Upload production branch with the API
cloudflare/cloudflare-docs pull request #13180
Opened 2024-02-27 17:59 UTC by Erisa

Frequently comes up in Support tickets, included a working curl example like the ones we share with customers.

2024-02-27 18:00 UTC, Erisa commented on content/pages/platform/known-issues.md
> +- Projects configured for [Direct Upload](/pages/get-started/direct-upload/) currently cannot have their production branch changed through the Cloudflare Dashboard, however this can be changed using
Well played bot
```suggestion
- Projects configured for [Direct Upload](/pages/get-started/direct-upload/) currently cannot have their production branch changed through the Cloudflare Dashboard, however this can be changed using the [Update project](/api/operations/pages-project-update-project) API endpoint:
```

2024-02-27 18:04 UTC, WalshyDev approved these changes

2024-02-27 18:04 UTC, WalshyDev commented on content/pages/platform/known-issues.md
> +$ curl --request PATCH --url https://api.cloudflare.com/client/v4/accounts/YOUR_ACCOUNT_IDENTIFIER_HERE/pages/projects/<PROJECT_NAME> \
```suggestion
$ curl --request PATCH --url https://api.cloudflare.com/client/v4/accounts/<YOUR_ACCOUNT_IDENTIFIER_HERE>/pages/projects/<PROJECT_NAME> \
```

2024-03-07 17:41 UTC, deadlypants1973 requested changes
@Erisa can we move this under the Direct Upload page? https://developers.cloudflare.com/pages/get-started/direct-upload/#troubleshoot

Known issues according to a feature of the product should be put on that feature page for discoverability.

2024-03-07 17:41 UTC, deadlypants1973 commented on content/pages/platform/known-issues.md
> +- Projects configured for [Direct Upload](/pages/get-started/direct-upload/) currently cannot have their production branch changed through the Cloudflare Dashboard, however this can be changed using
```suggestion
- Projects configured with [Direct Upload](/pages/get-started/direct-upload/) currently cannot have their production branch changed through the Cloudflare dashboard, however this can be changed using the [Update project](/api/operations/pages-project-update-project) API endpoint:
```

2024-03-07 17:43 UTC, Erisa commented
Sure, I can move it

2024-03-07 18:15 UTC, Erisa commented
@deadlypants1973 it has been moved, new preview here: https://erisa-pages-du-branch-api.cloudflare-docs-7ou.pages.dev/pages/get-started/direct-upload/#troubleshoot

2024-03-14 10:39 UTC, Erisa commented
We are still getting tickets for this, @deadlypants1973 could you review again?

2024-03-14 11:06 UTC, marciocloudflare requested changes

2024-03-14 11:06 UTC, marciocloudflare commented on content/pages/get-started/direct-upload.md
> +Projects configured with [Direct Upload](/pages/get-started/direct-upload/) currently cannot have their production branch changed through the Cloudflare dashboard, however this can be changed using t
```suggestion
Projects configured with [Direct Upload](/pages/get-started/direct-upload/) currently cannot have their production branch changed through the Cloudflare dashboard. However, this can be changed using the [Update project](/api/operations/pages-project-update-project) API endpoint:
```

2024-03-14 11:07 UTC, Erisa commented on content/pages/get-started/direct-upload.md
> +Projects configured with [Direct Upload](/pages/get-started/direct-upload/) currently cannot have their production branch changed through the Cloudflare dashboard, however this can be changed using t
Thank you!

2024-03-14 11:10 UTC, marciocloudflare approved these changes

2024-03-19 11:04 UTC, deadlypants1973 approved these changes

2024-03-19 11:13 UTC, deadlypants1973 commented on content/pages/get-started/direct-upload.md
> +Projects configured with [Direct Upload](/pages/get-started/direct-upload/) currently cannot have their production branch changed through the Cloudflare dashboard. However, this can be changed using
```suggestion
Pages projects configured with Direct Upload currently cannot have their production branch changed through the Cloudflare dashboard. However, this can be changed using the [Update project](/api/operations/pages-project-update-project) API endpoint:
```

2024-03-19 11:13 UTC, deadlypants1973 commented on content/pages/get-started/direct-upload.md
> +$ curl --request PATCH --url https://api.cloudflare.com/client/v4/accounts/<YOUR_ACCOUNT_IDENTIFIER_HERE>/pages/projects/<PROJECT_NAME> \
```suggestion
$ curl --request PATCH --url https://api.cloudflare.com/client/v4/accounts/{account_id}/pages/projects/{project_name} \
```

2024-03-19 11:23 UTC, merged