[Workers] Adds new flag for wrangler commands
cloudflare/cloudflare-docs pull request #13188
Opened 2024-02-27 22:52 UTC by KaiSpencer

A new flag for `wrangler dev` and `wrangler pages dev` is to be added in https://github.com/cloudflare/workers-sdk/pull/5099

This change covers the documentation for this new flag.

NB: the optional meta is ordered differently for each of these, I have stayed consistent with what is currently in place for the other flags in the respective sections.

2024-02-28 14:41 UTC, petebacondarwin commented on content/workers/wrangler/commands.md
> +- `--show-interactive-dev-session` {{<type>}}boolean{{</type>}} {{<prop-meta>}}(default: true){{</prop-meta>}} {{<prop-meta>}}optional{{</prop-meta>}}
Strictly the default is to go with whether the stdin has a TTY or not.

2024-03-19 20:43 UTC, petebacondarwin requested changes

2024-03-19 20:43 UTC, petebacondarwin commented on content/workers/wrangler/commands.md
> +- `--show-interactive-dev-session` {{<type>}}boolean{{</type>}} {{<prop-meta>}}(default: true){{</prop-meta>}} {{<prop-meta>}}optional{{</prop-meta>}}
```suggestion
- `--show-interactive-dev-session` {{<type>}}boolean{{</type>}} {{<prop-meta>}}(default: true if the terminal supports interactivity){{</prop-meta>}} {{<prop-meta>}}optional{{</prop-meta>}}
```

2024-03-19 20:43 UTC, petebacondarwin commented on content/workers/wrangler/commands.md
> +- `--show-interactive-dev-session` {{<type>}}boolean{{</type>}} {{<prop-meta>}}optional{{</prop-meta>}} {{<prop-meta>}}(default: true){{</prop-meta>}}
```suggestion
- `--show-interactive-dev-session` {{<type>}}boolean{{</type>}} {{<prop-meta>}}optional{{</prop-meta>}} {{<prop-meta>}}(default: true if the terminal supports interactivity){{</prop-meta>}} 
```

2024-04-29 18:26 UTC, petebacondarwin approved these changes
Approving subject to the suggested changes.

2024-05-02 16:30 UTC, kodster28 approved these changes

2024-05-02 16:38 UTC, merged