queues: add retry / delay flags
cloudflare/cloudflare-docs pull request #13545
Opened 2024-03-20 16:37 UTC by elithrar

Fixes #13370

2024-03-20 17:34 UTC, pmiguel approved these changes

2024-03-25 10:07 UTC, Maddy-Cloudflare approved these changes

2024-03-25 10:30 UTC, deadlypants1973 commented on content/workers/wrangler/commands.md
> +  - How long a retried message should be delayed for, in seconds. Must be a positive integer.
`--max-concurrency` and `--retry-delay` have the same description. Is this intentional?

2024-03-25 14:40 UTC, pmiguel requested changes
Some updates

2024-03-25 14:40 UTC, pmiguel commented on content/workers/wrangler/commands.md
> +- `--delivery-delay` {{<type>}}number{{</type>}} {{<prop-meta>}}optional{{</prop-meta>}}
The final name for this is `--delivery-delay-secs`.

2024-03-25 14:40 UTC, pmiguel commented on content/workers/wrangler/commands.md
> +- `--retry-delay` {{<type>}}number{{</type>}} {{<prop-meta>}}optional{{</prop-meta>}}
The final name for this is `--retry-delay-secs`

2024-03-25 14:43 UTC, elithrar commented on content/workers/wrangler/commands.md
> +- `--delivery-delay` {{<type>}}number{{</type>}} {{<prop-meta>}}optional{{</prop-meta>}}
```suggestion
- `--delivery-delay-secs` {{<type>}}number{{</type>}} {{<prop-meta>}}optional{{</prop-meta>}}
```

2024-03-25 14:44 UTC, elithrar commented on content/workers/wrangler/commands.md
> +- `--retry-delay` {{<type>}}number{{</type>}} {{<prop-meta>}}optional{{</prop-meta>}}
```suggestion
- `--retry-delay-secs` {{<type>}}number{{</type>}} {{<prop-meta>}}optional{{</prop-meta>}}
```

2024-03-25 14:57 UTC, deadlypants1973 approved these changes

2024-03-25 16:32 UTC, Maddy-Cloudflare approved these changes

2024-03-25 17:55 UTC, pmiguel approved these changes

2024-03-26 18:22 UTC, merged