[Pages] Update type argument in c3 usage docs
cloudflare/cloudflare-docs pull request #13566
Opened 2024-03-21 22:00 UTC by jculvey

The `webFramework` --type argument is being renamed to `web-framework`.

2024-03-22 16:31 UTC, dario-piotrowicz approved these changes

2024-03-25 15:31 UTC, deadlypants1973 approved these changes

2024-03-26 14:02 UTC, dario-piotrowicz requested changes
This should probably not be merged yet

2024-03-26 15:48 UTC, dario-piotrowicz approved these changes

2024-04-01 16:38 UTC, merged