[Workers LP] concepts revision
cloudflare/cloudflare-docs pull request #13572
Opened 2024-03-22 13:39 UTC by deadlypants1973

PCX-

2024-03-22 17:02 UTC, penalosa requested changes

2024-03-22 17:02 UTC, penalosa commented on content/learning-paths/workers/concepts/serverless-computing.md
> +[Cloud computing](https://www.cloudflare.com/learning/cloud/what-is-the-cloud/) is defined as hosting computing resources (such as virtual machines, storage, databases, and networking services) on th
```suggestion
[Cloud computing](https://www.cloudflare.com/learning/cloud/what-is-the-cloud/) is defined as hosting computing resources (such as virtual machines, storage, databases, and networking services) on third-party servers. Cloud computing service providers include Amazon Web Services, Microsoft Azure, Gooogle Cloud Platform, and Cloudflare. The main service models of cloud computing are: Infrastructure-as-a-Service (IaaS), Platform-as-a-Service (Paas), and Software-as-a-Service (SaaS).
```

2024-03-22 17:02 UTC, penalosa commented on content/learning-paths/workers/concepts/serverless-computing.md
> +Cloudflare Workers is under the [Functions-as-a-Service (FaaS)](https://www.cloudflare.com/learning/serverless/glossary/function-as-a-service-faas/) model, which is a serverless way to execute modula
Workers doesn't just support edge computing, with things like smart placement, Durable Objects, and cron triggers all not necessarily running on the edge

2024-03-22 17:02 UTC, penalosa commented on content/learning-paths/workers/concepts/serverless-computing.md
> +#### Resources management
```suggestion
#### Resource management
```

2024-03-22 17:02 UTC, penalosa commented on content/learning-paths/workers/concepts/serverless-computing.md
> +Cloud computing allows organizations to rent a fixed number of servers or server space. To prepare for seasonal or unplanned spikes in request traffic to their applications, organizations may overpur
This disinction isn't really as cut and dry as this. Often cloud computing providers do let you autoscale virtual servers (see https://aws.amazon.com/ec2/autoscaling/, for instance)

2024-03-22 17:02 UTC, penalosa commented on content/learning-paths/workers/concepts/serverless-computing.md
> +Serverless computing differs from traditional cloud computing structures in its cloud architecture. Cloud computing infrastructure includes [virual machines (VM)](https://www.cloudflare.com/learning/
This doesn't really capture the difference between models. Traditional serverless providers (AWS Lambda, for instance) run your functions in a container, and charge based on request duration. Workers are run in V8 isolates, and charge based on CPU time.

2024-03-22 17:02 UTC, penalosa commented on content/learning-paths/workers/concepts/serverless-computing.md
> +title: Serverless computing
I'm a bit confused about this page—who's it targeted at? It seems like a general high-level intro to serverless and cloud computing, but it doesn't really talk about Workers and their advantages. Conflating Workers & traditional serverless understates how unique Workers is compared to things like AWS Lambda in things like execution model and billing.

2024-03-22 17:02 UTC, penalosa commented on content/learning-paths/workers/concepts/serverless-computing.md
> +Developers and organizations using serverless computing are billed on a [usage model](/workers/pricing/) paradigm. Instead of paying for a fixed amount of computing resources that may be underutilize
"Usage model" can mean many things, and isn't generalisable across serverless computing platforms. Lambda and Workers are both serverless computing platforms, for instance, but charge based on usage very differently.

2024-03-22 17:02 UTC, penalosa commented on content/learning-paths/workers/concepts/what-is-cloudflare.md
> +title: What is Cloudflare?
This should link to https://www.cloudflare.com/learning/what-is-cloudflare/

2024-03-22 17:02 UTC, penalosa commented on content/learning-paths/workers/concepts/workers-concepts.md
> +Cloudflare Workers has significant differences in its architecture from other serverless computing providers. The Workers runtime is designed is designed to be JavaScript-standards compliant and web-
```suggestion
Cloudflare Workers has significant differences in its architecture from other serverless computing providers. The Workers runtime is designed to be JavaScript-standards compliant and web-interoperable. It uses the V8 engine — the same engine used by Chromium and Node.js, and has an open-source version, [`workerd`](https://github.com/cloudflare/workerd).
```

2024-03-22 17:02 UTC, penalosa commented on content/learning-paths/workers/concepts/workers-concepts.md
> +2. The [`wrangler.toml` file](/workers/wrangler/configuration/) where you define your project's configuration.
This is potentially _correct_, but I'm not sure it's the right way to phrase it. Workers consist of multiple modules (JS/WASM/Text), along with an optional `wrangler.toml` file depending on whether you're using Wrangler or not.

2024-03-22 17:02 UTC, penalosa commented on content/learning-paths/workers/concepts/workers-concepts.md
> +When an event (such as an HTTP request or a [Cron Trigger](/workers/configuration/cron-triggers/)) invokes a Worker, the Worker code will execute. Workers projects can have complex functionality, run
This paragraph is great, but it feels a bit messy, and like it's re-stating the key idea (workers can do anything) multiple times

2024-03-22 17:02 UTC, penalosa commented on content/learning-paths/workers/concepts/workers-concepts.md
> +Workers run on [Cloudflare's global network](https://www.cloudflare.com/network/) - a growing global network of thousands of machines distributed across hundreds of locations. Only one Workers instan
I feel like "growing" implies that it's currently small. Why did we remove the 300+ marketing?

2024-03-22 17:02 UTC, penalosa commented on content/learning-paths/workers/concepts/workers-concepts.md
> +Workers run on [Cloudflare's global network](https://www.cloudflare.com/network/) - a growing global network of thousands of machines distributed across hundreds of locations. Only one Workers instan
What's an "instance"? I don't see it referenced anywhere else on the page

2024-03-22 17:02 UTC, penalosa commented on content/workers/_partials/_compute-per-request.md
> +{{</tabs>}}
We shouldn't document service workers here—this should have a tab for JS and a tab for TS

2024-03-25 15:46 UTC, deadlypants1973 commented on content/learning-paths/workers/concepts/what-is-cloudflare.md
> +title: What is Cloudflare?
Titles don't get links. This link is highlighted in an aside further on the page.

2024-03-27 17:35 UTC, penalosa approved these changes

2024-03-28 16:50 UTC, kodster28 approved these changes

2024-03-28 16:58 UTC, merged