add new example to use D1 with Prisma ORM
cloudflare/cloudflare-docs pull request #13618
Opened 2024-03-26 10:35 UTC by nikolasburk

A PR that:
- mentions Prisma ORM in community projects: https://developers.cloudflare.com/d1/reference/community-projects/
- adds step-by-step instructions to deploy a CF Worker that queries D1 using Prisma ORM

Let mw know if you have any feedback and/or change requests, happy to make any adjustments!

2024-03-26 11:44 UTC, elithrar commented
Thanks @nikolasburk! We’ll review this week and get this published.

2024-03-26 15:01 UTC, vy-ton commented on content/d1/examples/d1-and-prisma-orm.md
> +database_name = "prisma-demo-db"
Add `database_id` output

2024-03-26 15:01 UTC, vy-ton commented on content/d1/examples/d1-and-prisma-orm.md
> +You now need to use the `wrangler d1 execute`  command to send this SQL statement to D1. Note that this command accepts two options:
This will work, however, the blog post executes SQL files by creating D1 migrations (https://developers.cloudflare.com/d1/reference/migrations/). Let's be consistent in how to execute .sql files

2024-03-26 15:01 UTC, vy-ton commented on content/d1/examples/d1-and-prisma-orm.md
> +-- CreateIndex
helpful to explain why this index was autogenerated.

2024-03-26 15:49 UTC, Maddy-Cloudflare approved these changes

2024-03-26 15:49 UTC, Maddy-Cloudflare commented on content/d1/examples/d1-and-prisma-orm.md
> +[Prisma ORM](https://www.prisma.io/orm) is a next-generation JavaScript and TypeScript ORM that unlocks a new level of developer experience when working with databases thanks to its intuitive data mo
```suggestion
[Prisma ORM](https://www.prisma.io/orm) is a next-generation JavaScript and TypeScript ORM that unlocks a new level of developer experience when working with databases thanks to its intuitive data model, automated migrations, type-safety and auto-completion.
```

2024-03-26 15:49 UTC, Maddy-Cloudflare commented on content/d1/examples/d1-and-prisma-orm.md
> +If you want to learn more about Prisma ORM, you can visit the [documentation](https://www.prisma.io/docs).
```suggestion
To learn more about Prisma ORM, refer to the [Prisma documentation](https://www.prisma.io/docs).
```

2024-03-26 15:49 UTC, Maddy-Cloudflare commented on content/d1/examples/d1-and-prisma-orm.md
> +In this section, you'll find step-by-step instructions to set up and deploy a Cloudflare Worker that's accessing a D1 database from scratch.
```suggestion
This example shows you how to set up and deploy a Cloudflare Worker that is accessing a D1 database from scratch.
```

2024-03-26 15:49 UTC, Maddy-Cloudflare commented on content/d1/examples/d1-and-prisma-orm.md
> +- A Cloudflare account
```suggestion
- A [Cloudflare account](https://dash.cloudflare.com).
```

2024-03-26 15:49 UTC, Maddy-Cloudflare commented on content/d1/examples/d1-and-prisma-orm.md
> +- Node.js and npm installed on your machine
```suggestion
- [`Node.js`](https://nodejs.org/en/) and [`npm`](https://docs.npmjs.com/getting-started) installed on your machine.
```

2024-03-26 15:49 UTC, Maddy-Cloudflare commented on content/d1/examples/d1-and-prisma-orm.md
> +As a first step, go ahead and use `npm create` to bootstrap a plain version of a Cloudflare Worker (using Cloudflare's [`hello-world`](https://github.com/cloudflare/workers-sdk/tree/4fdd8987772d914cf
```suggestion
Open your terminal, and run the following command to create a Cloudflare Worker using Cloudflare's [`hello-world`](https://github.com/cloudflare/workers-sdk/tree/4fdd8987772d914cf50725e9fa8cb91a82a6870d/packages/create-cloudflare/templates/hello-world) template:
```

2024-03-26 15:49 UTC, Maddy-Cloudflare commented on content/d1/examples/d1-and-prisma-orm.md
> +npm create cloudflare@latest prisma-d1-example -- --type hello-world
```suggestion
$ npm create cloudflare@latest prisma-d1-example -- --type hello-world
```

2024-03-26 15:49 UTC, Maddy-Cloudflare commented on content/d1/examples/d1-and-prisma-orm.md
> +This will bring up a CLI wizard. Select all the *default* options by hitting **Enter** every time a question appears.
```suggestion
In your terminal, you will be asked a series of questions related your project:

1. Answer `yes` to using TypeScript.
2. Answer `yes` to deploying your Worker.
```

2024-03-26 15:49 UTC, Maddy-Cloudflare commented on content/d1/examples/d1-and-prisma-orm.md
> +At the end of the wizard, you should have a deployed Cloudflare Worker at the domain `https://prisma-d1-example.USERNAME.workers.dev` which simply renders "Hello World" in the browser.
```suggestion
Once you deploy your Worker, you should be able to preview your Worker at `https://prisma-d1-example.USERNAME.workers.dev`, which returns "Hello World" in the browser.
```

2024-03-26 15:49 UTC, Maddy-Cloudflare commented on content/d1/examples/d1-and-prisma-orm.md
> +With your Worker in place, let's go ahead and set up Prisma ORM.
```suggestion
```

2024-03-26 15:49 UTC, Maddy-Cloudflare commented on content/d1/examples/d1-and-prisma-orm.md
> +First, navigate into the project directory and install the Prisma CLI:
```suggestion
To set up Prisma ORM, go into your project directory, and install the Prisma CLI:
```

2024-03-26 15:49 UTC, Maddy-Cloudflare commented on content/d1/examples/d1-and-prisma-orm.md
> +cd prisma-d1-example
```suggestion
```sh
$ cd prisma-d1-example
```
```

2024-03-26 15:49 UTC, Maddy-Cloudflare commented on content/d1/examples/d1-and-prisma-orm.md
> +npm install prisma --save-dev
```suggestion
$ npm install prisma --save-dev
```

2024-03-26 15:49 UTC, Maddy-Cloudflare commented on content/d1/examples/d1-and-prisma-orm.md
> +Next, install the Prisma Client package as well as the driver adapter for D1:
```suggestion
Next, install the Prisma Client package and the driver adapter for D1:
```

2024-03-26 15:49 UTC, Maddy-Cloudflare commented on content/d1/examples/d1-and-prisma-orm.md
> +```
```suggestion
```sh
```

2024-03-26 15:49 UTC, Maddy-Cloudflare commented on content/d1/examples/d1-and-prisma-orm.md
> + npx prisma init --datasource-provider sqlite
```suggestion
$ npx prisma init --datasource-provider sqlite
```

2024-03-26 15:49 UTC, Maddy-Cloudflare commented on content/d1/examples/d1-and-prisma-orm.md
> +This command did two things:
```suggestion
The command above:
```

2024-03-26 15:49 UTC, Maddy-Cloudflare commented on content/d1/examples/d1-and-prisma-orm.md
> +- It created a new directory called `prisma` that contains your [Prisma schema](https://www.prisma.io/docs/orm/prisma-schema/overview) file.
```suggestion

1.  Creates a new directory called `prisma` that contains your [Prisma schema](https://www.prisma.io/docs/orm/prisma-schema/overview) file.

```

2024-03-26 15:49 UTC, Maddy-Cloudflare commented on content/d1/examples/d1-and-prisma-orm.md
> +- It created a `.env` file which is typically used to configure environment variables that will be read by the Prisma CLI.
```suggestion
2. Creates a `.env` file used to configure environment variables that will be read by the Prisma CLI.
```

2024-03-26 15:49 UTC, Maddy-Cloudflare commented on content/d1/examples/d1-and-prisma-orm.md
> +In this tutorial, you won't need the `.env` file since the connection between Prisma ORM and D1 will happen through a [binding](/workers/configuration/bindings/). You'll find instructions for setting
```suggestion
In this tutorial, you will not need the `.env` file since the connection between Prisma ORM and D1 will happen through a [binding](/workers/configuration/bindings/). The next steps will instruct you through setting up this binding.
```

2024-03-26 15:49 UTC, Maddy-Cloudflare commented on content/d1/examples/d1-and-prisma-orm.md
> +Since you'll be using the [driver adapter](https://www.prisma.io/docs/orm/overview/databases/database-drivers#driver-adapters) feature which is currently in Preview, you need to explicitly enable it
```suggestion
Since you will use the [driver adapter](https://www.prisma.io/docs/orm/overview/databases/database-drivers#driver-adapters) feature which is currently in Preview, you need to explicitly enable it via  the `previewFeatures` field on the `generator` block.
```

2024-03-26 15:49 UTC, Maddy-Cloudflare commented on content/d1/examples/d1-and-prisma-orm.md
> +Open your `schema.prisma` file and adjust the `generator` block to look as follows:
```suggestion
Open your `schema.prisma` file and adjust the `generator` block to reflect as follows:
```

2024-03-26 15:49 UTC, Maddy-Cloudflare commented on content/d1/examples/d1-and-prisma-orm.md
> +In this step, you'll set up your D1 database. There generally are two approaches to this. Either using the Cloudflare Dashboard UI or via the `wrangler` CLI. You'll use the CLI in this tutorial.
```suggestion
In this step, you will set up your D1 database. You can create a D1 database via the Cloudflare Dashboard UI, or via the `wrangler` CLI. This tutorial will use the `wrangler` CLI.
```

2024-03-26 15:49 UTC, Maddy-Cloudflare commented on content/d1/examples/d1-and-prisma-orm.md
> +```
```suggestion
```sh
```

2024-03-26 15:49 UTC, Maddy-Cloudflare commented on content/d1/examples/d1-and-prisma-orm.md
> +npx wrangler d1 create prisma-demo-db
```suggestion
$ npx wrangler d1 create prisma-demo-db
```

2024-03-26 15:49 UTC, Maddy-Cloudflare commented on content/d1/examples/d1-and-prisma-orm.md
> + npx prisma init --datasource-provider sqlite
I'm testing this step-by-step, and it looks like this step works by turning off WARP.

2024-03-26 15:49 UTC, Maddy-Cloudflare commented on content/d1/examples/d1-and-prisma-orm.md
> +If everything went well, you should see an output similar to this:
```suggestion
You should receive the following output on your terminal:
```

2024-03-26 15:49 UTC, Maddy-Cloudflare commented on content/d1/examples/d1-and-prisma-orm.md
> +Note that `__YOUR_D1_DATABASE_ID__` in the snippet above is a placeholder that should be replaced with the database ID of your own D1 instance. If you weren't able to grab this ID from the terminal o
```suggestion
`__YOUR_D1_DATABASE_ID__` should be replaced with the database ID of your D1 instance. If you were not able to fetch this ID from the terminal output, you can also find it in the [Cloudflare Dashboard](https://dash.cloudflare.com/), or by running `npx wrangler d1 info prisma-demo-db` in your terminal.
```

2024-03-26 15:49 UTC, Maddy-Cloudflare commented on content/d1/examples/d1-and-prisma-orm.md
> +Next, you'll create a database table in the database in order to be able to send some queries to D1 using Prisma ORM.
```suggestion
Next, you will create a database table in the database to send queries to D1 using Prisma ORM.
```

2024-03-26 15:49 UTC, Maddy-Cloudflare commented on content/d1/examples/d1-and-prisma-orm.md
> +[Prisma Migrate](https://www.prisma.io/docs/orm/prisma-migrate/understanding-prisma-migrate/overview) doesn't support D1 yet, so you can't follow the "default" migration workflows using `prisma migra
```suggestion
[Prisma Migrate](https://www.prisma.io/docs/orm/prisma-migrate/understanding-prisma-migrate/overview) does not support D1 yet, so you cannot follow the default migration workflows using `prisma migrate dev` or `prisma db push`. However, the Prisma CLI provides tools that allow you to generate SQL statements which you can manually send to D1 via the `wrangler` CLI.
```

2024-03-26 15:49 UTC, Maddy-Cloudflare commented on content/d1/examples/d1-and-prisma-orm.md
> +Open the `schema.prisma` file and add the following `User` model to it:
```suggestion
Open the `schema.prisma` file and add the following `User` model to your schema:
```

2024-03-26 15:49 UTC, Maddy-Cloudflare commented on content/d1/examples/d1-and-prisma-orm.md
> +Next, run the following command in your terminal to generate the SQL statement that creates a `User` table that's equivalent to the `User` model above:
```suggestion
Next, run the following command in your terminal to generate the SQL statement that creates a `User` table equivalent to the `User` model above:
```

2024-03-26 15:49 UTC, Maddy-Cloudflare commented on content/d1/examples/d1-and-prisma-orm.md
> +```
```suggestion
```sh
```

2024-03-26 15:49 UTC, Maddy-Cloudflare commented on content/d1/examples/d1-and-prisma-orm.md
> +npx prisma migrate diff --from-empty --to-schema-datamodel ./prisma/schema.prisma --script > prisma/schema.sql
```suggestion
$ npx prisma migrate diff --from-empty --to-schema-datamodel ./prisma/schema.prisma --script > prisma/schema.sql
```

2024-03-26 15:49 UTC, Maddy-Cloudflare commented on content/d1/examples/d1-and-prisma-orm.md
> +You now need to use the `wrangler d1 execute`  command to send this SQL statement to D1. Note that this command accepts two options:
```suggestion
You now need to use the `wrangler d1 execute`  command to send this SQL statement to D1. This command accepts two options:
```

2024-03-26 15:49 UTC, Maddy-Cloudflare commented on content/d1/examples/d1-and-prisma-orm.md
> +- `--local`: Executes the statement against a _local_ version of D1. This local version of D1 is a SQLite database file that'll be located in the `.wrangler/state` directory of your project. This app
```suggestion
- `--local`: Executes the statement against a _local_ version of D1. This local version of D1 is a SQLite database file that will be located in the `.wrangler/state` directory of your project. Use this approach when you want to develop and test your Worker on your local machine. Refer to [Local development](/d1/configuration/local-development/) to learn more.
```

2024-03-26 15:49 UTC, Maddy-Cloudflare commented on content/d1/examples/d1-and-prisma-orm.md
> +- `--remote`: Executes the statement against your _remote_ version of D1. This version is used by your _deployed_ Cloudflare Workers. Learn more [here](/d1/configuration/remote-development/).
```suggestion
- `--remote`: Executes the statement against your _remote_ version of D1. This version is used by your _deployed_ Cloudflare Workers. Refer to [Remote development](/d1/configuration/remote-development/) to learn more.
```

2024-03-26 15:49 UTC, Maddy-Cloudflare commented on content/d1/examples/d1-and-prisma-orm.md
> +In this tutorial, you'll do both: test the Worker locally _and_ deploy it afterwards. So, you need to run both commands. Open your terminal and paste the following commands:
```suggestion
In this tutorial, you will do local and remote development. You will test the Worker locally and deploy your Worker afterwards. Open your terminal, and run both commands:
```

2024-03-26 15:49 UTC, Maddy-Cloudflare commented on content/d1/examples/d1-and-prisma-orm.md
> +npx wrangler d1 execute prisma-demo-db --file=prisma/schema.sql --local
```suggestion
$ npx wrangler d1 execute prisma-demo-db --file=prisma/schema.sql --local
```
```

2024-03-26 15:49 UTC, Maddy-Cloudflare commented on content/d1/examples/d1-and-prisma-orm.md
> +```
```suggestion
```sh
```

2024-03-26 15:49 UTC, Maddy-Cloudflare commented on content/d1/examples/d1-and-prisma-orm.md
> +npx wrangler d1 execute prisma-demo-db --file=prisma/schema.sql --remote
```suggestion
$ npx wrangler d1 execute prisma-demo-db --file=prisma/schema.sql --remote
```

2024-03-26 15:49 UTC, Maddy-Cloudflare commented on content/d1/examples/d1-and-prisma-orm.md
> +Let's also create some dummy data that we can query once the Worker is running. This time, you'll run the SQL statement without storing it in a file:
```suggestion
Next, create some data that you can query once the Worker is running. This time, you will run the SQL statement without storing it in a file:
```

2024-03-26 15:49 UTC, Maddy-Cloudflare commented on content/d1/examples/d1-and-prisma-orm.md
> +```
```suggestion
```sh
```

2024-03-26 15:49 UTC, Maddy-Cloudflare commented on content/d1/examples/d1-and-prisma-orm.md
> +```
```suggestion
```sh
```

2024-03-26 15:49 UTC, Maddy-Cloudflare commented on content/d1/examples/d1-and-prisma-orm.md
> +npm install @prisma/client
```suggestion
$ npm install @prisma/client
```
```

2024-03-26 15:49 UTC, Maddy-Cloudflare commented on content/d1/examples/d1-and-prisma-orm.md
> +npm install @prisma/adapter-d1
```suggestion
$ npm install @prisma/adapter-d1
```
```

2024-03-26 15:49 UTC, Maddy-Cloudflare commented on content/d1/examples/d1-and-prisma-orm.md
> +In order to query your database from the Worker using Prisma ORM, you need to:
```suggestion
To query your database from the Worker using Prisma ORM, you need to:
```

2024-03-26 15:49 UTC, Maddy-Cloudflare commented on content/d1/examples/d1-and-prisma-orm.md
> +```
```suggestion
```sh
```

2024-03-26 15:49 UTC, Maddy-Cloudflare commented on content/d1/examples/d1-and-prisma-orm.md
> +npx prisma generate
```suggestion
$ npx prisma generate
```

2024-03-26 15:49 UTC, Maddy-Cloudflare commented on content/d1/examples/d1-and-prisma-orm.md
> +With the database query in place and Prisma Client generated, you can go ahead and run the Worker locally:
```suggestion
Now that you have the database query in place and Prisma Client generated, run the Worker locally:
```

2024-03-26 15:49 UTC, Maddy-Cloudflare commented on content/d1/examples/d1-and-prisma-orm.md
> +```
```suggestion
```sh
```

2024-03-26 15:49 UTC, Maddy-Cloudflare commented on content/d1/examples/d1-and-prisma-orm.md
> +npm run dev
```suggestion
$ npm run dev
```

2024-03-26 15:49 UTC, Maddy-Cloudflare commented on content/d1/examples/d1-and-prisma-orm.md
> +Now you can open your browser at [`http://localhost:8787`](http://localhost:8787/) to see the result of the database query:
```suggestion
Open your browser at [`http://localhost:8787`](http://localhost:8787/) to check the result of the database query:
```

2024-03-26 15:49 UTC, Maddy-Cloudflare commented on content/d1/examples/d1-and-prisma-orm.md
> +```
```suggestion
```sh
```

2024-03-26 15:49 UTC, Maddy-Cloudflare commented on content/d1/examples/d1-and-prisma-orm.md
> +npm run deploy
```suggestion
$ npm run deploy
```

2024-03-26 15:49 UTC, Maddy-Cloudflare commented on content/d1/examples/d1-and-prisma-orm.md
> +As before, your deployed Worker is accessible via `https://prisma-d1-example.USERNAME.workers.dev`. If you navigate your browser to that URL, you should see the following data that's queried from you
```suggestion
Access your Worker at `https://prisma-d1-example.USERNAME.workers.dev`. Your browser should display the following data queried from your remote D1 database:
```

2024-03-26 15:49 UTC, Maddy-Cloudflare commented on content/d1/examples/d1-and-prisma-orm.md
> +## Next steps
```suggestion
## Related resources
```

2024-03-26 15:49 UTC, Maddy-Cloudflare commented on content/d1/examples/d1-and-prisma-orm.md
> +Here are some more useful resources to check out if you want to learn more about Prisma ORM:
```suggestion
```

2024-03-26 15:49 UTC, Maddy-Cloudflare commented on content/d1/examples/d1-and-prisma-orm.md
> +- **Docs**: [Get started with Prisma ORM](https://www.prisma.io/docs/getting-started)
```suggestion
- [Prisma documentation](https://www.prisma.io/docs/getting-started).
```

2024-03-26 15:49 UTC, Maddy-Cloudflare commented on content/d1/examples/d1-and-prisma-orm.md
> +- **Help**: Open a new [GitHub Discussion](https://github.com/prisma/prisma/discussions/) or [ask the AI bot in the Prisma docs](https://www.prisma.io/docs)
```suggestion
- To get help, open a new [GitHub Discussion](https://github.com/prisma/prisma/discussions/), or [ask the AI bot in the Prisma docs](https://www.prisma.io/docs).
```

2024-03-26 15:49 UTC, Maddy-Cloudflare commented on content/d1/examples/d1-and-prisma-orm.md
> +- **Examples**: [Ready-to-run examples using Prisma ORM](https://github.com/prisma/prisma-examples/)
```suggestion
- [Ready-to-run examples using Prisma ORM](https://github.com/prisma/prisma-examples/).
```

2024-03-26 15:49 UTC, Maddy-Cloudflare commented on content/d1/examples/d1-and-prisma-orm.md
> +- **Community**: Check out the [Prisma community](https://www.prisma.io/community), follow [Prisma on X](https://www.x.com/prisma) and join the [Prisma Discord](https://pris.ly/discord)
```suggestion
- Check out the [Prisma community](https://www.prisma.io/community), follow [Prisma on X](https://www.x.com/prisma) and join the [Prisma Discord](https://pris.ly/discord).
```

2024-03-26 15:49 UTC, Maddy-Cloudflare commented on content/d1/examples/d1-and-prisma-orm.md
> +- **Blog**: [Developer Experience Redefined: Prisma & Cloudflare Lead the Way to Data DX](https://www.prisma.io/blog/cloudflare-partnership-qerefgvwirjq)
```suggestion
- [Developer Experience Redefined: Prisma & Cloudflare Lead the Way to Data DX](https://www.prisma.io/blog/cloudflare-partnership-qerefgvwirjq)
```

2024-03-26 15:49 UTC, Maddy-Cloudflare commented on content/d1/reference/community-projects.md
> +[Prisma ORM](https://www.prisma.io/orm) is a next-generation JavaScript and TypeScript ORM that unlocks a new level of developer experience when working with databases thanks to its intuitive data mo
```suggestion
[Prisma ORM](https://www.prisma.io/orm) is a next-generation JavaScript and TypeScript ORM that unlocks a new level of developer experience when working with databases thanks to its intuitive data model, automated migrations, type-safety and auto-completion.
```

2024-03-26 15:49 UTC, Maddy-Cloudflare commented on content/d1/examples/d1-and-prisma-orm.md
> +This stores a SQL statement to create a new `User` table in a new file called `schema.sql` in the `prisma` directory. Here's what it looks like:
```suggestion
This stores a SQL statement to create a new `User` table in a new file called `schema.sql` in the `prisma` directory. Your `schema.sql` should look like this:
```

2024-03-26 15:49 UTC, Maddy-Cloudflare commented on content/d1/examples/d1-and-prisma-orm.md
> +To deploy the Worker, run the the following command:
```suggestion
To deploy the Worker, run the following command:
```

2024-03-26 16:00 UTC, Maddy-Cloudflare requested changes
Will review this again once all suggestions have been applied

2024-03-26 16:31 UTC, nikolasburk commented on content/d1/examples/d1-and-prisma-orm.md
> +database_name = "prisma-demo-db"
Ah sorry I missed this 👍

2024-03-26 17:01 UTC, nikolasburk commented on content/d1/examples/d1-and-prisma-orm.md
> +You now need to use the `wrangler d1 execute`  command to send this SQL statement to D1. Note that this command accepts two options:
Ha, good callout! I adjusted the content to have the following flow:

1. create empty migration with `npx wrangler d1 migrations create prisma-demo-db create_user_table`
1. add `model User` to Prisma schema
1. generate SQL statement into migration file: `npx prisma migrate diff --from-empty --to-schema-datamodel ./prisma/schema.prisma --script > migrations/0001_create_user_table.sql`
1. apply migrations locally and remotely with `npx wrangler d1 migrations apply prisma-demo-db`

2024-03-26 17:02 UTC, nikolasburk commented on content/d1/examples/d1-and-prisma-orm.md
> +-- CreateIndex
added this note:

Note that the `UNIQUE INDEX` on the `email` was created because the `User` model in your Prisma schema is using the [`@unique`](https://www.prisma.io/docs/orm/reference/prisma-schema-reference#unique) attribute on its `email` field.

2024-03-26 17:26 UTC, nikolasburk commented
Wow, what an in-depth review! Thanks so much @Maddy-Cloudflare and @vy-ton 🙏 I addressed all of your feedback, let me know if there's anything else that should be changed 😄

2024-03-26 21:53 UTC, vy-ton approved these changes

2024-03-27 11:07 UTC, Maddy-Cloudflare requested changes

2024-03-27 11:07 UTC, Maddy-Cloudflare commented on content/d1/examples/d1-and-prisma-orm.md
> +---
This is a step-by-step tutorial, therefore we can move it under this URL: [/d1/tutorials/](https://developers.cloudflare.com/d1/tutorials/). 

Replace lines 2 to 10 with following:

```
updated: 2024-03-27
difficulty: Beginner
content_type: Tutorial
pcx_content_type: tutorial
title: Query D1 using Prisma ORM
```

2024-03-27 11:07 UTC, Maddy-Cloudflare commented on content/d1/examples/d1-and-prisma-orm.md
> +## What is Prisma ORM?
```suggestion
# What is Prisma ORM?
```

2024-03-27 11:07 UTC, Maddy-Cloudflare commented on content/d1/examples/d1-and-prisma-orm.md
> +
```suggestion
```

2024-03-27 11:07 UTC, Maddy-Cloudflare commented on content/d1/examples/d1-and-prisma-orm.md
> +Since you'll use the [driver adapter](https://www.prisma.io/docs/orm/overview/databases/database-drivers#driver-adapters) feature which is currently in Preview, you need to explicitly enable it via
```suggestion
Since you will use the [driver adapter](https://www.prisma.io/docs/orm/overview/databases/database-drivers#driver-adapters) feature which is currently in Preview, you need to explicitly enable it via  the `previewFeatures` field on the `generator` block.
```

2024-03-27 11:07 UTC, Maddy-Cloudflare commented on content/d1/examples/d1-and-prisma-orm.md
> +### 3. Create D1 database
```suggestion
### 3. Create your D1 database
```

2024-03-27 11:07 UTC, Maddy-Cloudflare commented on content/d1/examples/d1-and-prisma-orm.md
> +In this step, you will set up your D1 database. You can create a D1 database via the Cloudflare Dashboard UI, or via the `wrangler` CLI. This tutorial will use the `wrangler` CLI.
```suggestion
In this step, you will set up your D1 database. You can create a D1 database via the [Cloudflare dashboard](https://dash.cloudflare.com), or via `wrangler`. This tutorial will use the `wrangler` CLI.
```

2024-03-27 11:07 UTC, Maddy-Cloudflare commented on content/d1/examples/d1-and-prisma-orm.md
> +`__YOUR_D1_DATABASE_ID__` should be replaced with the database ID of your D1 instance. If you were not able to fetch this ID from the terminal output, you can also find it in the [Cloudflare Dashboar
```suggestion
`__YOUR_D1_DATABASE_ID__` should be replaced with the database ID of your D1 instance. If you were not able to fetch this ID from the terminal output, you can also find it in the [Cloudflare dashboard](https://dash.cloudflare.com/), or by running `npx wrangler d1 info prisma-demo-db` in your terminal.
```

2024-03-27 11:07 UTC, Maddy-Cloudflare commented on content/d1/examples/d1-and-prisma-orm.md
> +However, D1 comes with its own [migration system](/d1/reference/migrations) and the Prisma CLI provides tools that still allow you to generate SQL statements for schema changes. In the following, you
```suggestion
However, D1 has a [migration system](/d1/reference/migrations), and the Prisma CLI provides tools that allow you to generate SQL statements for schema changes. In the following steps, you will use D1's migration system and the Prisma CLI to create and run a migration against your database.
```

2024-03-27 11:07 UTC, Maddy-Cloudflare commented on content/d1/examples/d1-and-prisma-orm.md
> +First, create a new migration using the `wrangler` CLI:
```suggestion
First, create a new migration using the `wrangler`:
```

2024-03-27 11:07 UTC, Maddy-Cloudflare commented on content/d1/examples/d1-and-prisma-orm.md
> +The command has now created a new directory called `migrations` and an empty file called `0001_create_user_table.sql` inside of it:
```suggestion
The command has now created a new directory called `migrations` and an empty file called `0001_create_user_table.sql` which contains:
```

2024-03-27 11:07 UTC, Maddy-Cloudflare commented on content/d1/examples/d1-and-prisma-orm.md
> +Note that the `UNIQUE INDEX` on the `email` was created because the `User` model in your Prisma schema is using the [`@unique`](https://www.prisma.io/docs/orm/reference/prisma-schema-reference#unique
```suggestion
`UNIQUE INDEX` on `email` was created because the `User` model in your Prisma schema is using the [`@unique`](https://www.prisma.io/docs/orm/reference/prisma-schema-reference#unique) attribute on its `email` field.
```

2024-03-27 11:07 UTC, Maddy-Cloudflare commented on content/d1/examples/d1-and-prisma-orm.md
> +Hit **Enter** both times when you're prompted to confirm that the migration should be applied.
```suggestion
Select **Enter** both times when you are prompted to confirm that the migration should be applied.
```

2024-03-27 11:07 UTC, Maddy-Cloudflare commented on content/d1/examples/d1-and-prisma-orm.md
> +Before running the Worker, you need to generate Prisma Client with the following command:
```suggestion
Before running the Worker, generate Prisma Client with the following command:
```

2024-03-27 11:07 UTC, Maddy-Cloudflare commented on content/d1/examples/d1-and-prisma-orm.md
> +Congratulations, you just deployed a Cloudflare Worker using D1 as a database and querying it via Prisma ORM 🎉
```suggestion
By finishing this tutorial, you have deployed a Cloudflare Worker using D1 as a database and querying it via Prisma ORM.
```

2024-03-27 11:07 UTC, Maddy-Cloudflare commented on content/d1/examples/d1-and-prisma-orm.md
> +-  To get help, open a new [GitHub Discussion](https://github.com/prisma/prisma/discussions/), or [ask the AI bot in the Prisma docs](https://www.prisma.io/docs).
```suggestion
- To get help, open a new [GitHub Discussion](https://github.com/prisma/prisma/discussions/), or [ask the AI bot in the Prisma docs](https://www.prisma.io/docs).
```

2024-03-27 11:07 UTC, Maddy-Cloudflare commented on content/d1/reference/community-projects.md
> +* Example (Coming soon)
```suggestion
* Tutorial (Coming soon)
```

2024-03-27 11:07 UTC, Maddy-Cloudflare commented on content/d1/reference/community-projects.md
> +
```suggestion
```

2024-03-27 12:05 UTC, Maddy-Cloudflare requested changes

2024-03-27 12:05 UTC, Maddy-Cloudflare commented on content/d1/examples/d1-and-prisma-orm.md
> +Once you deploy your Worker, you should be able to preview your Worker at `https://prisma-d1-example.USERNAME.workers.dev`, which returns "Hello World" in the browser.
```suggestion
Once you deploy your Worker, you should be able to preview your Worker at `https://prisma-d1-example.USERNAME.workers.dev`, which displays "Hello World" in the browser.
```

2024-03-27 12:05 UTC, Maddy-Cloudflare commented on content/d1/examples/d1-and-prisma-orm.md
> +When prompted if the command can create a new folder called `migrations`, hit **Enter** to confirm.
```suggestion
Answer `yes` to creating a new folder called `migrations`.
```

2024-03-27 12:05 UTC, Maddy-Cloudflare commented on content/d1/examples/d1-and-prisma-orm.md
> ++model User {
```suggestion
model User {
```

2024-03-27 12:05 UTC, Maddy-Cloudflare commented on content/d1/examples/d1-and-prisma-orm.md
> ++  id    Int     @id @default(autoincrement())
```suggestion
id    Int     @id @default(autoincrement())
```

2024-03-27 12:05 UTC, Maddy-Cloudflare commented on content/d1/examples/d1-and-prisma-orm.md
> ++  email String  @unique
```suggestion
email String  @unique
```

2024-03-27 12:05 UTC, Maddy-Cloudflare commented on content/d1/examples/d1-and-prisma-orm.md
> ++  name  String?
```suggestion
name  String?
```

2024-03-27 12:05 UTC, Maddy-Cloudflare commented on content/d1/examples/d1-and-prisma-orm.md
> ++}
```suggestion
}
```

2024-03-27 12:05 UTC, Maddy-Cloudflare commented on content/d1/examples/d1-and-prisma-orm.md
> ++}
Are these `+` intentional? If not, we can remove them.

2024-03-27 12:07 UTC, Maddy-Cloudflare commented
> Wow, what an in-depth review! Thanks so much @Maddy-Cloudflare and @vy-ton 🙏 I addressed all of your feedback, let me know if there's anything else that should be changed 😄

Thanks for creating this tutorial! I tested this and it works fine.

2024-03-27 12:14 UTC, nikolasburk commented on content/d1/examples/d1-and-prisma-orm.md
> +---
Ah I see! I'll move it under `tutorials` then. FWIW, we'll be adding an actual deployment example with D1 to our `prisma-examples` repo as well. Maybe we can describe that in the `examples` directory.

2024-03-27 12:27 UTC, nikolasburk commented on content/d1/examples/d1-and-prisma-orm.md
> +The command has now created a new directory called `migrations` and an empty file called `0001_create_user_table.sql` inside of it:
can you double-check this suggestion? I think the sentence becomes factually incorrect with it?

2024-03-27 12:29 UTC, nikolasburk commented on content/d1/reference/community-projects.md
> +* Example (Coming soon)
I was referring to the deployment example project that we can link when next Tuesday when it gets merged: https://github.com/prisma/prisma-examples/pull/5793

2024-03-27 12:31 UTC, nikolasburk commented on content/d1/examples/d1-and-prisma-orm.md
> +```
can you double-check this suggestion? the code snippet displays the structure on the file system and is not a sql code snippet.

2024-03-27 12:33 UTC, nikolasburk commented on content/d1/examples/d1-and-prisma-orm.md
> ++}
they were intentional. in combination with the `diff` language annotation, it renders the lines prefixes with a `+` in green, e.g. this markdown:

````
```diff
+model User {
+  id    Int     @id @default(autoincrement())
+  email String  @unique
+  name  String?
+}
```
````

is rendered as followed:

```diff
+model User {
+  id    Int     @id @default(autoincrement())
+  email String  @unique
+  name  String?
+}
```

it's a small detail though and I think we can also remove them (since they may cause some friction when people directly copy the content of this code block).

2024-03-27 12:36 UTC, nikolasburk commented on content/d1/examples/d1-and-prisma-orm.md
> +## What is Prisma ORM?
I chose to use the same H1 heading as in the sidenav and then keep "What is Prisma ORM?" as a title:

```markdown
# Query D1 using Prisma ORM

## What is Prisma ORM?

[Prisma ORM](https://www.prisma.io/orm) is a next-generation JavaScript and TypeScript ORM that unlocks a new level of developer experience when working with databases thanks to its intuitive data model, automated migrations, type-safety and auto-completion.

To learn more about Prisma ORM, refer to the [Prisma documentation](https://www.prisma.io/docs).

```

hope that's ok!

2024-03-27 12:37 UTC, nikolasburk commented on content/d1/reference/community-projects.md
> +* Example (Coming soon)
but maybe we should drop it altogether while it's not there...

```suggestion
```

2024-03-27 12:37 UTC, nikolasburk commented on content/d1/reference/community-projects.md
> +* [Tutorial](/d1/examples/d1-and-prisma-orm/)
but the link to the tutorial needs to be updated to point to the `tutorials` directory I guess?

```suggestion
* [Tutorial](/d1/tutorials/d1-and-prisma-orm/)
```

2024-03-27 12:40 UTC, nikolasburk commented
Thanks again for the follow-up @Maddy-Cloudflare 🙏 I went ahead and incorporated all your suggestions (except for two of them, where I left a comment and asked you double-check because I think they would make the content incorrect).

2024-03-27 12:50 UTC, Maddy-Cloudflare commented on content/d1/reference/community-projects.md
> +* Example (Coming soon)
> but maybe we should drop it altogether while it's not there...
Sorry then, my mistake. We can drop it if it's not there.

2024-03-27 12:55 UTC, Maddy-Cloudflare approved these changes

2024-03-27 12:59 UTC, Maddy-Cloudflare commented
> Thanks again for the follow-up @Maddy-Cloudflare 🙏 I went ahead and incorporated all your suggestions (except for two of them, where I left a comment and asked you double-check because I think they would make the content incorrect).

It's good to be merged, thanks for applying the suggestions!

2024-03-27 15:51 UTC, vy-ton commented
@Maddy-Cloudflare Does the directory structure have to be `content/d1/tutorials/<folder>/index.md`?

2024-03-27 15:54 UTC, vy-ton commented on content/d1/tutorials/d1-and-prisma-orm.md
> +### 2. Initialize Prisma ORM
@nikolasburk Can you mention the required minimum Prisma ORM version

2024-03-27 15:57 UTC, nikolasburk commented on content/d1/tutorials/d1-and-prisma-orm.md
> +### 2. Initialize Prisma ORM
Sure, here's a note:

```suggestion
### 2. Initialize Prisma ORM

> D1 is supported in Prisma ORM as of [v5.12.0](https://github.com/prisma/prisma/releases/tag/5.12.0).
```

2024-03-27 16:47 UTC, Maddy-Cloudflare commented
> @Maddy-Cloudflare Does the directory structure have to be `content/d1/tutorials/<folder>/index.md`?

I just checked and yes, ideally it should be in a folder! @nikolasburk

2024-03-28 07:08 UTC, nikolasburk commented
Thanks for the feedback @vy-ton and @Maddy-Cloudflare, I moved the tutorial into its own directory 🙏

2024-03-28 12:33 UTC, merged

2024-03-28 14:24 UTC, Maddy-Cloudflare commented
> Thanks for the feedback @vy-ton and @Maddy-Cloudflare, I moved the tutorial into its own directory 🙏

This link returns  a `404`, do you have an updated link so I can fix it?