[Network] Update instructions to direct to CF support
cloudflare/cloudflare-docs pull request #13622
Opened 2024-03-26 14:00 UTC by RebeccaTamachiro

PCX-10234

2024-03-26 15:07 UTC, pedrosousa commented on content/network/ip-geolocation.md
> +If you find an incorrect IP location, use the [MaxMind tool](https://www.maxmind.com/en/geoip2-precision-demo) to make sure that Maxmind shows the correct **Country Code**. If the data is incorrect,
Nit: The MaxMind URL seems to redirect users to a different location: `https://www.maxmind.com/en/geoip-web-services-demo`.

2024-03-26 15:28 UTC, cicku requested changes
Maxmind URL has changed.

2024-04-11 12:34 UTC, RebeccaTamachiro commented
After the team has met with Maxmind, latest edits reflect new instructions from PM. Which removes previous URL completely.

2024-04-12 12:46 UTC, cicku approved these changes

2024-04-12 13:59 UTC, angelampcosta approved these changes

2024-04-12 14:04 UTC, merged