Update data-location.md
cloudflare/cloudflare-docs pull request #13672
Opened 2024-03-28 16:44 UTC by Kiki-Y123

To check the region of your database in D1

2024-03-28 16:48 UTC, elithrar requested changes

2024-03-28 16:48 UTC, elithrar commented on content/d1/configuration/data-location.md
I would suggest moving this up and retitling to "## Check current region"

This section needs to also talk about how this is the location of the _leader_ (writer) and show a wrangler example, including cross-linking to https://developers.cloudflare.com/workers/wrangler/commands/#info

2024-04-11 15:21 UTC, Maddy-Cloudflare approved these changes

2024-04-11 15:21 UTC, Maddy-Cloudflare commented on content/d1/configuration/data-location.md
> +## To check the region of your database in D1
```suggestion
## Check the region of your database in D1
```

2024-04-11 15:21 UTC, Maddy-Cloudflare commented on content/d1/configuration/data-location.md
> +You can use API to ([get d1 database](/api/operations/cloudflare-d1-get-database)) and check field `running_in_region` in the output.
```suggestion
You can use the [D1 HTTP API](/api/operations/cloudflare-d1-get-database) and check the field `running_in_region` in the output to view the region of your database in D1.
```

2024-09-27 14:04 UTC, KimJ15 commented
👋Hi there, we’re going to close this PR due to inactivity and web framework migration

2024-09-27 14:04 UTC, closed without merging