Create build-watch-paths
cloudflare/cloudflare-docs pull request #13680
Opened 2024-03-28 20:23 UTC by nevikashah

2024-03-28 21:38 UTC, cmsparks requested changes

2024-03-28 21:38 UTC, cmsparks commented on content/pages/configuration/build-watch-paths
> +When connected to your git source, Pages allows you to watch for specific paths to build. By default, Pages will trigger a deployment any time you commit to your repository. This can be especially he
```suggestion
When connected to your git source, Pages allows you to watch for push events affecting specific paths to build. By default, Pages will trigger a deployment any time you push to your repository. This can be especially helpful if you are using a monorepo project structure and want to limit the amount of builds being kicked off. 
```

I think this wording is a bit more precise, because we trigger on pushes, not necessarily commits.

2024-03-28 21:38 UTC, cmsparks commented on content/pages/configuration/build-watch-paths
> +
We should document the fallback methods if the push event contains 0 file changes OR too many file changes or commits.

```
Pages will bypass the path matching for a push event and build the project if:
* A push event contains 0 file changes, in case a user pushes a dummy push event
* A push event contains 3000+ file changes or 20+ commits
```

2024-03-28 21:38 UTC, cmsparks commented on content/pages/configuration/build-watch-paths
> +* **Static path directories**: Enter the precise name of the directory or file you are looking to include or exclude (for example, `test` or `docs/README.md`).
```suggestion
* **Static filepaths**: Enter the precise name of the file you are looking to include or exclude (for example, `docs/README.md`).
```
Git providers won't report directory changes on their own, it will only report specific filepaths. I think this is because it's generally not possible to add empty directories in git

2024-03-28 21:38 UTC, cmsparks commented on content/pages/configuration/build-watch-paths
> +Because commits to your repo by default trigger an automatic build, you can configure both include and exclude paths for your repository. This way, commits that alter any files within the includes li
```suggestion
Because pushes to your repo by default trigger an automatic build, you can configure both include and exclude paths for your repository. This way, commits that alter any files within the includes list will trigger automatic builds, and commits that alter only files within the excludes list will skip the build. 
```

2024-03-28 21:38 UTC, cmsparks commented on content/pages/configuration/build-watch-paths
> +* **Wildcard syntax:** Use wildcards to match multiple path directories. You can specify wildcards at the start or end of your rule. The order of execution for the configuration is (1) Excludes, (2)
I think we should be a bit more explicit about matching strategy because it's a bit more complex than the branch configuration.

```suggestion
* **Wildcard syntax:** Use wildcards to match multiple path directories. You can specify wildcards at the start or end of your rule. 

These path includes/excludes configuration fields will be evaluated as follows:

* For each filepath
  * If the filepath satisfies any path excludes, check the next filepath
  * If the filepath satisfies any path includes, trigger a build and stop checking filepaths
  * Check the next filepath
* If Pages has checked every filepath and not found a path satisfying path includes, skip the build.
```

Alternatively, we could show the path matching pseudocode, which could remove ambiguity.

2024-04-01 19:42 UTC, irvinebroque commented on content/pages/configuration/build-watch-paths.md
> +title: Build watch paths
This seems like section within a page about builds?

Can builds have its own section within here? There is lot of mixed together content and feels like needs structure:

<img width="310" alt="Screenshot 2024-04-01 at 12 29 11 PM" src="https://github.com/cloudflare/cloudflare-docs/assets/1221592/2b9383fa-a90b-4cc4-9b4a-0f8ef2ac7cbe">

2024-04-01 19:42 UTC, irvinebroque commented on content/pages/configuration/build-watch-paths.md
> +# Build watch paths
Would think about naming here since as-is not really a common term

2024-04-01 19:42 UTC, irvinebroque commented on content/pages/configuration/build-watch-paths.md
> +When connected to your git source, Pages allows you to watch for push events affecting specific paths to build. By default, Pages will trigger a deployment any time you push to your repository. This
```suggestion
When you connect a git repository to Pages, by default a change to any file in the repository will trigger a Pages build.

You can configure Pages to include or exclude specific paths to specify if Pages should skip a build for a given path.

This can be especially helpful if you are using a monorepo project structure and want to limit the amount of builds being kicked off. 
```

2024-04-01 19:42 UTC, irvinebroque commented on content/pages/configuration/build-watch-paths.md
> +Because pushes to your repo by default trigger an automatic build, you can configure both include and exclude paths for your repository. This way, commits that alter any files within the includes lis
Covered above?

2024-04-01 19:42 UTC, irvinebroque commented on content/pages/configuration/build-watch-paths.md
> +To configure deployment options, go to your Pages project > Settings > Builds & deployments > Build watch paths. Pages will default to setting your project’s includes paths to everything ([*]) and ex
```suggestion
To configure which paths are included and excluded, go to your Pages project > Settings > Builds & deployments > Build watch paths. Pages will default to setting your project’s includes paths to everything ([*]) and excludes paths to nothing (`[]`).  
```

2024-04-01 19:42 UTC, irvinebroque commented on content/pages/configuration/build-watch-paths.md
> +The configuration fields can be filled in two ways:
```suggestion
You can specify include and exclude paths using either:
```

2024-04-01 19:42 UTC, irvinebroque commented on content/pages/configuration/build-watch-paths.md
> +* **Wildcard syntax:** Use wildcards to match multiple path directories. You can specify wildcards at the start or end of your rule.
Show example?

2024-04-01 19:42 UTC, irvinebroque commented on content/pages/configuration/build-watch-paths.md
> +For each path in a push event, build watch paths will be evaluated as follows:
```suggestion
For each path in a push event, build watch paths will be evaluated as follows:

```

2024-04-01 19:42 UTC, irvinebroque commented on content/pages/configuration/build-watch-paths.md
> +Pages will bypass the path matching for a push event and default to building the project if:
```suggestion
Pages will bypass the path matching for a push event and default to building the project if: 

```

2024-04-01 19:42 UTC, irvinebroque commented on content/pages/configuration/build-watch-paths.md
> +## Examples
Good one for diagrams

2024-04-02 15:38 UTC, cmsparks commented
cherry picked the changes from this PR into https://github.com/cloudflare/cloudflare-docs/pull/13693/commits

2024-04-02 15:38 UTC, closed without merging

2024-04-02 15:43 UTC, cmsparks commented on content/pages/configuration/build-watch-paths.md
> +# Build watch paths
It's used in local development, so we decided to sort of steal that terminology. We weren't certain of the best option, but other options include:
* path includes/excludes
* include path
* include directory