[DO NOT REVIEW] DO JS RPC
cloudflare/cloudflare-docs pull request #13765
Opened 2024-04-02 18:42 UTC by vy-ton

2024-04-03 01:06 UTC, GregBrimble commented on content/durable-objects/best-practices/access-durable-object-from-a-worker.md
> +# Access Durable Objects from a Worker
File name is still `access-durable-object-from-a-worker`. You might want to rename to `access-durable-objects-from-a-worker`.

2024-04-03 01:07 UTC, GregBrimble commented on content/durable-objects/best-practices/create-durable-object-stubs.md
> -# Create Durable Object stubs
Same here. Consider renaming file when you change the title.

2024-04-03 01:14 UTC, GregBrimble commented on content/durable-objects/best-practices/create-durable-object-stubs.md
> +- Invoking Remote Procedure Call (RPC) methods defined on a Durable Object class as of [compatibility date 2024-04-03](TODO). If handling HTTP requests and responses is not required for your Durable
This reads a bit like a changelog to me. I'd try and rephrase it to be a bit more timeless, if possible. Maybe something like:

```suggestion
- [Sending HTTP requests](/durable-objects/best-practices/create-durable-object-stubs/#send-http-requests) to a Durable Object's `fetch()` handler.
- Invoking [Remote Procedure Call (RPC)](/workers/runtime-apis/rpc/) methods defined on a Durable Object class (available for Workers with a [compatibility date greater than or equal to `2024-04-03`](/workers/configuration/compatibility-dates/#remote-procedure-call-rpc)).
```

2024-04-03 01:15 UTC, GregBrimble commented on content/durable-objects/best-practices/create-durable-object-stubs.md
> +export class Counter extends DurableObject {
You need the import statement here:
```suggestion
import { DurableObject } from "cloudflare:workers";

export class Counter extends DurableObject {
```

2024-04-03 01:17 UTC, GregBrimble commented on content/durable-objects/best-practices/create-durable-object-stubs.md
> +  - An ID constructed using `newUniqueId()`, `idFromName()`, or `idFromString()` on this Durable Object namespace, for details see [Access a Durable Object](/durable-objects/best-practices/access-dur
```suggestion
  - An ID constructed using `newUniqueId()`, `idFromName()`, or `idFromString()` on this Durable Object namespace. For details, see [Access a Durable Object](/durable-objects/best-practices/access-durable-object-from-a-worker/#generate-ids-randomly) .
```

2024-04-03 01:19 UTC, GregBrimble commented on content/durable-objects/examples/build-a-counter.md
>  export class Counter {
You need to extend `DurableObject` here (and import at the top of the file).

2024-04-03 01:21 UTC, GregBrimble commented on content/durable-objects/examples/build-a-counter.md
>    }
No need to set `ctx` or `env` in a constructor of a Durable Object once you're extending the `DurableObject` class.

```suggestion
```

2024-04-03 01:23 UTC, GregBrimble commented on content/durable-objects/examples/build-a-counter.md
> +    this.ctx.storage.put("value", value);
I can't remember if we're clever here and if this isn't _strictly_ necessary, or if, indeed, it is needed.. so for the avoidance of my doubt, and the readers':

```suggestion
    await this.ctx.storage.put("value", value);
```

2024-04-03 01:23 UTC, GregBrimble commented on content/durable-objects/examples/build-a-counter.md
> +    this.ctx.storage.put("value", value);
Same here:

```suggestion
    await this.ctx.storage.put("value", value);
```

2024-04-03 01:24 UTC, GregBrimble commented on content/durable-objects/examples/build-a-counter.md
> +import {DurableObject} from "cloudflare:workers";
Stylistic nit:

```suggestion
import { DurableObject } from "cloudflare:workers";
```

2024-04-03 01:25 UTC, GregBrimble commented on content/durable-objects/examples/build-a-counter.md
> +    let stub = env.COUNTER.get(id);
Here, we're using `COUNTER` in the JS example, but `COUNTERS` in the TS example. We should be consistent.

2024-04-03 01:30 UTC, GregBrimble commented on content/durable-objects/examples/build-a-counter.md
> +		let count = await resp;
You've already awaited the value here, and I think `count` as the return variable name makes more sense than `resp`:

```suggestion
    let count = null;
		switch (url.pathname) {
      case "/increment":
				count = await stub.increment();
        break;
			case "/decrement":
				count = await stub.decrement();
				break;
      case "/":
        // Serves the current value.
				count = await stub.getCounterValue();
        break;
      default:
        return new Response("Not found", { status: 404 });
    }

```

2024-04-03 01:31 UTC, GregBrimble commented on content/durable-objects/examples/build-a-counter.md
> +		let resp = null;
Comments for JS version apply here too.

2024-04-03 01:33 UTC, GregBrimble commented on content/workers/_partials/_durable_objects_pricing.md
Just FYI, @elithrar did a slightly different version here: https://github.com/cloudflare/cloudflare-docs/pull/13235/files

2024-04-03 03:57 UTC, GregBrimble commented on content/workers/_partials/_durable_objects_pricing.md
> +<sup>1</sup> Requests include all incoming HTTP requests, RPC method calls, WebSocket messages, and alarm invocations. A request is needed to create a WebSocket connection. There is no charge for out
Technically, I think it's an RPC _session_ that we'll bill for, rather than method calls.

2024-04-03 04:03 UTC, GregBrimble commented on content/workers/_partials/_durable_objects_pricing.md
> +<sup>1</sup> Requests include all incoming HTTP requests, RPC method calls, WebSocket messages, and alarm invocations. A request is needed to create a WebSocket connection. There is no charge for out
Also, that "Billing-only applies..." sentence could be clarified a bit, imo. Even just changing "Billing-only" to "For the consideration of billing, we..." makes it much more readable.

2024-04-03 09:55 UTC, Maddy-Cloudflare requested changes

2024-04-03 09:55 UTC, Maddy-Cloudflare commented on content/_redirects
> +/durable-objects/configuration/access-durable-object-from-a-worker/ /durable-objects/best-practices/access-durable-object-from-a-worker/ 301
What do you mean by "Best practices"? How do you define a "Best practice"? I'd love to know more about this decision.

2024-04-03 09:55 UTC, Maddy-Cloudflare commented on content/durable-objects/best-practices/create-durable-object-stubs.md
> +title: Create Durable Object stubs & Send Requests
```suggestion
title: Create Durable Object stubs and send requests
```

2024-04-03 09:55 UTC, Maddy-Cloudflare commented on content/durable-objects/best-practices/create-durable-object-stubs.md
> +# Create Durable Object stubs & send requests
```suggestion
# Create Durable Object stubs and send requests
```

2024-04-03 09:55 UTC, Maddy-Cloudflare commented on content/durable-objects/best-practices/create-durable-object-stubs.md
> +## Obtain a Durable Object stub
```suggestion
## Get a Durable Object stub
```

2024-04-03 09:55 UTC, Maddy-Cloudflare commented on content/durable-objects/best-practices/create-durable-object-stubs.md
> +## Requests
```suggestion
## Send requests
```

2024-04-03 09:55 UTC, Maddy-Cloudflare commented on content/durable-objects/best-practices/create-durable-object-stubs.md
> +There are several ways to send requests to a Durable Object.
```suggestion
You can send requests to a Durable Object by:
```

2024-04-03 09:55 UTC, Maddy-Cloudflare commented on content/durable-objects/best-practices/create-durable-object-stubs.md
> +To opt into RPC, a Durable Objects class should extend the built-in type `DurableObject`. Then, public methods on a Durable Objects class are exposed as [RPC methods](/workers/runtime-apis/rpc/), whi
```suggestion
To use RPC, a Durable Objects class should extend the built-in type `DurableObject`. Then, public methods on a Durable Objects class are exposed as [RPC methods](/workers/runtime-apis/rpc/), which you can call from a Durable Object stub in a Worker. All RPC calls are [asynchronous](/workers/runtime-apis/rpc/lifecycle), accept and return [serializable types](/workers/runtime-apis/rpc/supported-types), and [propagate exceptions](/workers/runtime-apis/rpc/error-handling) to the caller without a stack trace. Refer to [Workers RPC](/workers/runtime-apis/rpc/supported-types) for complete details.
```

2024-04-03 09:55 UTC, Maddy-Cloudflare commented on content/durable-objects/best-practices/create-durable-object-stubs.md
> +To opt into RPC, a Durable Objects class should extend the built-in type `DurableObject`. Then, public methods on a Durable Objects class are exposed as [RPC methods](/workers/runtime-apis/rpc/), whi
Would be nice to add one line on what an RPC method (or methods) is at the beginning of the paragraph.

2024-04-03 09:55 UTC, Maddy-Cloudflare commented on content/durable-objects/best-practices/create-durable-object-stubs.md
> +Historically, the `ctx` object for Durable Objects has been given a variety of different names in example code, most commonly `state`. Until introduction of [RPC methods](/workers/runtime-apis/rpc/),
```suggestion
Prior to RPC, the `ctx` object for Durable Objects has been known as `state`. `state` was the name of the Durable Object constructor parameter, so an application could use any other name. With RPC, the `DurableObject` superclass defines these values as properties, so they must have official names. The Durable Objects team has chosen to use `ctx` for consistency between `DurableObject` and `WorkerEntrypoint`.
```

2024-04-03 09:55 UTC, Maddy-Cloudflare commented on content/durable-objects/best-practices/create-durable-object-stubs.md
> +See [Build a Counter](/durable-objects/examples/build-a-counter/) for a full example.
```suggestion
Refer to [Build a Counter](/durable-objects/examples/build-a-counter/) for a full example.
```

2024-04-03 09:55 UTC, Maddy-Cloudflare commented on content/durable-objects/best-practices/create-durable-object-stubs.md
> +- Invoking Remote Procedure Call (RPC) methods defined on a Durable Object class as of [compatibility date 2024-04-03](TODO). If handling HTTP requests and responses is not required for your Durable
Since **_Sending HTTP requests_** is at the top of the list, we should start by explaining that, instead of RPC methods.

2024-04-03 17:11 UTC, vy-ton commented on content/durable-objects/best-practices/create-durable-object-stubs.md
> +- Invoking Remote Procedure Call (RPC) methods defined on a Durable Object class as of [compatibility date 2024-04-03](TODO). If handling HTTP requests and responses is not required for your Durable
HTTP first is for historical reasons. Eventually, we will default to RPC methods everywhere and should start here to draw developer attention

2024-04-03 17:16 UTC, vy-ton commented on content/workers/_partials/_durable_objects_pricing.md
yes, we're going to pull into this PR

2024-04-03 17:34 UTC, vy-ton commented on content/_redirects
> +/durable-objects/configuration/access-durable-object-from-a-worker/ /durable-objects/best-practices/access-durable-object-from-a-worker/ 301
`Best Practices` convey to a developer to start here with DO content to build successful apps. Other suggestions have been proposed like `Starter Guide, 101, Basics, Developer Guide`.

"Best Practices" is what I've settled on because we cannot stick with `Configuration` which does not connote build/develop for our audience

2024-04-03 18:13 UTC, GregBrimble commented on content/durable-objects/examples/build-a-counter.md
> +    this.ctx.storage.put("value", value);
```suggestion
    await this.ctx.storage.put("value", value);
```

2024-04-03 18:13 UTC, GregBrimble commented on content/durable-objects/examples/build-a-counter.md
> +    this.ctx.storage.put("value", value);
```suggestion
    await this.ctx.storage.put("value", value);
```

2024-04-03 19:14 UTC, irvinebroque commented on content/durable-objects/best-practices/create-durable-object-stubs-and-send-requests.md
> +- Invoking [Remote Procedure Call (RPC)](/workers/runtime-apis/rpc/) methods defined on a Durable Object class (available for Workers with a [compatibility date greater than or equal to `2024-04-03`]
Tricky to frame but technically when you call an RPC on a DO, you are not sending a request

2024-04-03 19:14 UTC, irvinebroque commented on content/durable-objects/best-practices/create-durable-object-stubs-and-send-requests.md
> +Prior to [RPC introduction](/workers/configuration/compatibility-dates/#remote-procedure-call-rpc), the `ctx` object for Durable Objects was known as `state`. `state` was the name of the Durable Obje
```suggestion
When you write a Worker that does not extend the [`DurableObject` class](/workers/configuration/compatibility-dates/#remote-procedure-call-rpc), the `ctx` object for Durable Objects was known as `state`. `state` was the name of the Durable Object constructor parameter, so an application could use any other name. With RPC, the `DurableObject` superclass defines these values as properties, so they must have official names. `ctx` was chosen for consistency between `DurableObject` and `WorkerEntrypoint`.
```

it's this, right? that it still works the same way as before if you don't extend from DurableObject

2024-04-03 19:38 UTC, vy-ton commented on content/durable-objects/best-practices/create-durable-object-stubs-and-send-requests.md
> +- Invoking [Remote Procedure Call (RPC)](/workers/runtime-apis/rpc/) methods defined on a Durable Object class (available for Workers with a [compatibility date greater than or equal to `2024-04-03`]
more context [here](https://chat.google.com/room/AAAAVrF5vCc/rHX2avbTVOI/YUTgOkqMAmw?cls=10), will work to clarify

2024-04-04 00:51 UTC, vy-ton commented on content/durable-objects/best-practices/create-durable-object-stubs-and-send-requests.md
> +Prior to [RPC introduction](/workers/configuration/compatibility-dates/#remote-procedure-call-rpc), the `ctx` object for Durable Objects was known as `state`. `state` was the name of the Durable Obje
added suggestion and tweaked wording some more

2024-04-04 05:01 UTC, geelen commented on content/durable-objects/best-practices/create-durable-object-stubs-and-send-requests.md
> +Prior to [RPC introduction](/workers/configuration/compatibility-dates/#remote-procedure-call-rpc), the `ctx` object for Durable Objects was known as `state`. `state` was the name of the Durable Obje
Yeah. Also if you really want, you can do:

```js
export class Counter extends DurableObject {
  state = this.ctx

  // rest of your code here
}
```

It's just that you'll end up with both `this.state` and `this.ctx` pointing to the same thing

2024-04-04 10:27 UTC, Maddy-Cloudflare approved these changes

2024-04-04 10:43 UTC, Maddy-Cloudflare commented on content/_redirects
> +/durable-objects/configuration/access-durable-object-from-a-worker/ /durable-objects/best-practices/access-durable-object-from-a-worker/ 301
I strongly disagree. But you can go ahead. :)

2024-04-04 14:23 UTC, vy-ton commented on content/durable-objects/best-practices/create-durable-object-stubs-and-send-requests.md
> +Prior to [RPC introduction](/workers/configuration/compatibility-dates/#remote-procedure-call-rpc), the `ctx` object for Durable Objects was known as `state`. `state` was the name of the Durable Obje
Separately, we will replace all mentions of `state` with `ctx`. @Maddy-Cloudflare are you able to tackle this next week?

2024-04-05 01:20 UTC, irvinebroque approved these changes

2024-04-05 01:20 UTC, irvinebroque commented on content/durable-objects/best-practices/create-durable-object-stubs-and-send-requests.md
> +When you write a Worker that does not extend the [`DurableObject` class](/workers/configuration/compatibility-dates/#remote-procedure-call-rpc), the `ctx` object for Durable Objects was known as `sta
```suggestion
When you write a Worker that does not extend the [`DurableObject` class](/workers/configuration/compatibility-dates/#remote-procedure-call-rpc), the `ctx` object in your Durable Object is instead called `state`, and is provided as the first argument to the constructor, but not set as a property of your class.

With RPC, the `DurableObject` superclass defines `ctx` and `env` as class properties. What was previously called `state` is now called `ctx` when you extend the `DurableObject` class.

This naming change from `state` to `ctx` was made both to ensure consistency between `DurableObject` and `WorkerEntrypoint`, and to avoid setting the false expectation that directly mutating the value of `state` would persist data.
```

@vy-ton — feel free to take or leave any of this. Tricky one to word, just taking a shot

2024-04-05 01:20 UTC, irvinebroque commented on content/durable-objects/examples/build-a-counter.md
> +This example shows how to build a counter using Durable Objects and Workers with RPC methods that can print, increment, and decrement a `name` provided by the URL query string parameter, for example,
```suggestion
This example shows how to build a counter using Durable Objects and Workers with [RPC methods](/workers/runtime-apis/rpc) that can print, increment, and decrement a `name` provided by the URL query string parameter, for example, `?name=A`.
```

2024-04-05 01:20 UTC, irvinebroque commented on content/workers/_partials/_durable_objects_pricing.md
> +| RPC methods                             | 1 million, + $0.15/million                        |
```suggestion
| RPC sessions                             | 1 million, + $0.15/million                        |
```

+ link to content/workers/runtime-apis/rpc/lifecycle.md from other PR?

(think we need crisp definition of what a session is)

2024-04-05 01:20 UTC, irvinebroque commented on content/durable-objects/best-practices/create-durable-object-stubs-and-send-requests.md
> +- Invoking [Remote Procedure Call (RPC)](/workers/runtime-apis/rpc/) methods defined on a Durable Object class (available for Workers with a [compatibility date greater than or equal to `2024-04-03`]
looks great

2024-04-05 01:20 UTC, irvinebroque commented on content/durable-objects/best-practices/create-durable-object-stubs-and-send-requests.md
> +To use RPC, a Durable Objects class should extend the built-in type `DurableObject`. Then, public methods on a Durable Objects class are exposed as [RPC methods](/workers/runtime-apis/rpc/), which yo
```suggestion
To use RPC, a Durable Objects class must extend the built-in type `DurableObject`. Then, public methods on a Durable Objects class are exposed as [RPC methods](/workers/runtime-apis/rpc/), which you can call from a Durable Object stub in a Worker. All RPC calls are [asynchronous](/workers/runtime-apis/rpc/lifecycle), accept and return [serializable types](/workers/runtime-apis/rpc/supported-types), and [propagate exceptions](/workers/runtime-apis/rpc/error-handling) to the caller without a stack trace. Refer to [Workers RPC](/workers/runtime-apis/rpc/supported-types) for complete details.
```

2024-04-05 01:28 UTC, vy-ton commented on content/workers/_partials/_durable_objects_pricing.md
> +| RPC methods                             | 1 million, + $0.15/million                        |
@irvinebroque Are developers familiar with RPC sessions? Worried developers will struggle to understand RPC sessions in context of DO request billing. For the common case, calling a RPC method on a DO stub is 1 billed request.

I know there's a more advanced use case with `RpcTarget` where subsequent calls on a RPC session are not counted as billed invocations.

2024-04-05 01:48 UTC, vy-ton commented on content/workers/_partials/_durable_objects_pricing.md
> +| RPC methods                             | 1 million, + $0.15/million                        |
took another stab at explain this on the DO pricing page

2024-04-05 01:57 UTC, irvinebroque commented on content/workers/_partials/_durable_objects_pricing.md
> +<sup>1</sup> A [RPC session](/workers/runtime-apis/rpc/lifecycle/) represents a billed request. Every [RPC method call](/durable-objects/best-practices/create-durable-object-stubs-and-send-requests/#
```suggestion
<sup>1</sup> Each [RPC session](/workers/runtime-apis/rpc/lifecycle/) is billed as one request to your Durable Object. Every [RPC method call](/durable-objects/best-practices/create-durable-object-stubs-and-send-requests/#call-rpc-methods) on a [Durable Objects stub](/durable-objects/best-practices/create-durable-object-stubs-and-send-requests/#get-a-durable-object-stub) is its own RPC session and therefore a single billed request.
```

Think that this needs to be tweaked a bit based on content below?

Since only that top-level calls to create new stubs are billed as requests?

i.e.:

```
using foo = await env.MY_DO.bar(); // billed as a request
await foo.baz(); // treated as part of the same session, not billed
```

^ where both of these calls would be considered calls on a stub from a Durable Object?

I wonder if one way to approach would be something like:

"Every time you call a public class method of your Durable Object via RPC, this creates a session, and each session is billed as one request"

@kentonv for correctness ^ — accurate?

2024-04-05 01:59 UTC, irvinebroque commented on content/workers/_partials/_durable_objects_pricing.md
> +RPC method calls can return objects (stubs) extending [`RpcTarget`](/workers/runtime-apis/rpc/lifecycle/#lifetimes-memory-and-resource-management) and invoke calls on those stubs. Subsequent calls on
Maybe this is where to put code example like:

```suggestion
RPC method calls can return objects (stubs) extending [`RpcTarget`](/workers/runtime-apis/rpc/lifecycle/#lifetimes-memory-and-resource-management) and invoke calls on those stubs. Subsequent calls on the returned stub are part of the same RPC session and are not billed as separate requests. For example:

```js
using foo = await env.MY_DO.bar(); // billed as a request
await foo.baz(); // treated as part of the same session, not billed as a request
```
```

2024-04-05 02:25 UTC, vy-ton commented on content/workers/_partials/_durable_objects_pricing.md
> +<sup>1</sup> A [RPC session](/workers/runtime-apis/rpc/lifecycle/) represents a billed request. Every [RPC method call](/durable-objects/best-practices/create-durable-object-stubs-and-send-requests/#
> ^ where both of these calls would be considered calls on a stub from a Durable Object?

but the second line `await foo.baz()` is not a call on the Durable Object stub itself. That's the difference to highlight.

2024-04-05 02:28 UTC, vy-ton commented on content/workers/_partials/_durable_objects_pricing.md
> +RPC method calls can return objects (stubs) extending [`RpcTarget`](/workers/runtime-apis/rpc/lifecycle/#lifetimes-memory-and-resource-management) and invoke calls on those stubs. Subsequent calls on
+1 code example, proposed edits:

```js
let durableObjectStub = OBJECT_NAMESPACE.get(id); // retrieve Durable Object stub
using foo = await durableObjectStub.bar(); // billed as a request
await foo.baz(); // treated as part of the same RPC session created by calling bar(), not billed as a request

2024-04-05 02:31 UTC, irvinebroque commented on content/workers/_partials/_durable_objects_pricing.md
> +RPC method calls can return objects (stubs) extending [`RpcTarget`](/workers/runtime-apis/rpc/lifecycle/#lifetimes-memory-and-resource-management) and invoke calls on those stubs. Subsequent calls on
ship it!

2024-04-05 02:33 UTC, irvinebroque commented on content/workers/_partials/_durable_objects_pricing.md
> +<sup>1</sup> A [RPC session](/workers/runtime-apis/rpc/lifecycle/) represents a billed request. Every [RPC method call](/durable-objects/best-practices/create-durable-object-stubs-and-send-requests/#
yeah, i think we are agreeing, just trying to figure out how to clarify what "is a Durable Object stub" i.e. I read that as somewhat ambiguous, could mean either:

1. Any stub returned by a Durable Object
2. Specifically, the stub "of" the Durable Object itself (in contrast to the stub provided by an `RpcTarget`

Think what you have probably fine since clarified below? Was just wondering about if way to be super explicit

2024-04-05 02:50 UTC, merged