[Logs] IA restructure + adding content types
cloudflare/cloudflare-docs pull request #1378
Opened 2021-05-18 22:06 UTC by crwaters16

2021-05-18 23:19 UTC, tlozoot approved these changes

2021-05-19 14:31 UTC, kodster28 commented on products/logs/src/content/reference/index.md
>  # Reference
Should you change this to a directory listing? You're missing the `log fields` page since I think it's a static list right now.

2021-05-19 14:32 UTC, kodster28 commented on products/logs/src/content/reference/waf-fields.md
>  # WAF fields
Not part of your change, but the 2nd header needs a space.

2021-05-19 14:36 UTC, kodster28 commented on products/logs/src/content/about/index.md
> +## About Logpush
Don't think you need this h2. Maybe just change the h1 to `About Logpush`

2021-05-19 14:37 UTC, kodster28 commented on products/logs/src/content/about/index.md
Did you want a link to the `Get started` section at the bottom?

2021-05-19 14:38 UTC, kodster28 commented on products/logs/src/content/faq/index.md
> +title: FAQ
You don't need the title if it's the same as your `h1`. Applies to more than a few pages.

2021-05-19 14:40 UTC, kodster28 commented on products/logs/src/content/get-started/enable-destinations/index.md
> +<DirectoryListing path="/logs/logpush/enable-destinations"/>
This isn't showing up properly. I believe you just need the path to be `/enable-destinations`

2021-05-19 14:40 UTC, kodster28 commented on products/logs/src/content/get-started/enable-destinations/index.md
> +<DirectoryListing path="/logs/logpush/enable-destinations"/>
https://raw.githubusercontent.com/cloudflare/cloudflare-docs/production/products/bots/src/content/get-started/index.md

2021-05-19 14:41 UTC, kodster28 commented on products/logs/src/content/get-started/index.md
> +Once you've set up the connection between your destination and Cloudflare, configure Logpush using the [Cloudflare UI (Dashboard)](/logpush/logpush-dashboard/) or [API](/logpush/logpush-configuration
Contraction

2021-05-19 14:42 UTC, kodster28 commented on products/logs/src/content/get-started/index.md
> +Before enabling Logpush, ensure you [grant Cloudflare access](/logs/logpush/enable-destinations/) to push to your storage service, SIEM, or log management provider.
Bad relative link

2021-05-19 14:42 UTC, kodster28 commented on products/logs/src/content/get-started/index.md
> +Once you've set up the connection between your destination and Cloudflare, configure Logpush using the [Cloudflare UI (Dashboard)](/logpush/logpush-dashboard/) or [API](/logpush/logpush-configuration
And bad relative links

2021-05-19 14:43 UTC, kodster28 commented on products/logs/src/content/get-started/index.md
> +- [Sumo Logic](/logs/logpush/sumo-logic/)
All the links on this page are bad

2021-05-19 14:43 UTC, kodster28 commented on products/logs/src/content/get-started/index.md
> +- [Microsoft Azure Blob Storage](/logs/logpush/azure/)
Maybe break up with headers? But that might be a personal preference.

2021-05-19 14:44 UTC, kodster28 commented on products/logs/src/content/get-started/logpush-configuration-api/Examples/example-logpush-python.md
> +pcx-content-type: interim
This doesn't appear in the navigation?

2021-05-19 14:45 UTC, kodster28 commented on products/logs/src/content/get-started/logpush-configuration-api/Examples/tutorial-logpush-curl.md
> +pcx-content-type: tutorial
Same, doesn't appear in nav

2021-05-19 14:46 UTC, kodster28 commented on products/logs/src/content/get-started/index.md
> +pcx-content-type: concept
Should this be `interim`? I know we had talked about a `Get started` content type.

2021-05-19 14:47 UTC, kodster28 commented on products/logs/src/content/get-started/logpush-configuration-api/understanding-logpush-api.md
> +pcx-content-type: concept
To me, this feels more like a `reference`

2021-05-19 14:48 UTC, kodster28 commented on products/logs/src/content/index.md
> +Push your request or event logs to your cloud service provider using [Logpush](/logpush/), which can be configured via the Cloudflare dashboard or an API.
Bad relative link. I think you need to rename the URL path for logpush. Currently, it's `logs/about`

2021-05-19 14:48 UTC, kodster28 commented on products/logs/src/content/about/index.md
> +title: Logpush
Might need to rename the file path. Right now, it's just `logs/about`

2021-05-19 14:50 UTC, kodster28 commented on products/logs/src/content/logpull/index.md
>  Logpull is available to customers on the Enterprise plan.
Did you want links out to the sub-pages (directory listing) or specific callouts (basics and enabling log retention)?

2021-05-19 14:50 UTC, kodster28 commented on products/logs/src/content/logpull/understanding-the-basics/index.md
> +You can query for logs starting from 1 minute in the past (relative to the actual time that you're making the query) and going back at least 3 days and up to 7 days.
Contraction

2021-05-19 14:51 UTC, kodster28 commented on products/logs/src/content/reference/pathing-status.md
> +- EdgePathingSrc (pathing source): The stage that made the routing decision
Should these be bolded or italicized?

2021-05-19 14:51 UTC, kodster28 commented on products/logs/src/content/reference/pathing-status.md
> +***EdgePathingSrc*** refers to the system that last handled the request before an error occurred or the request was passed to the cache server. Typically, this will be the macro/reputation list. Poss
sub headings?

2021-05-19 14:53 UTC, kodster28 requested changes
There are a few broken links and some other navigation problems.

2021-05-20 21:31 UTC, crwaters16 commented
@kodster28, I can't figure out why those two files aren't appearing in the TOC - the file structure on my machine is correct but they aren't getting pulled into the build. Any help appreciated!

2021-05-20 21:32 UTC, crwaters16 commented on products/logs/src/content/get-started/logpush-configuration-api/understanding-logpush-api.md
> +pcx-content-type: concept
This page needs some love - I might change to "interim" for now. Tried to scope this ticket mostly to IA updates and planning to tackle some of the bigger content issues in later sprints.

2021-05-21 09:41 UTC, pedrosousa commented
@crwaters16 You "skipped a folder level" -- the `get-started/logpush-configuration-api/Examples` folder, currently with no files, must have at least an `index.md` file. As soon as there's a folder that has no Markdown files, GatsbyJS stops checking the sub-folders.

Also, please rename the `Examples` folder to `examples`.

2021-05-21 13:37 UTC, crwaters16 commented
> @crwaters16 You "skipped a folder level" -- the `get-started/logpush-configuration-api/Examples` folder, currently with no files, must have at least an `index.md` file. As soon as there's a folder that has no Markdown files, GatsbyJS stops checking the sub-folders.
> 
> Also, please rename the `Examples` folder to `examples`.

Pedro I JUST had this realization on my morning walk and am very glad to see it echoed in your rec! Will do, to both. Thank you!

2021-05-21 14:28 UTC, kodster28 commented on products/logs/src/content/faq/index.md
> +When you make a call for the time period of 16:10-16:13, you're actually asking for the logs that were received and processed by our system during that time (hence the endpoint name, _logs/received_)
contraction?

2021-05-21 14:28 UTC, kodster28 commented on products/logs/src/content/faq/index.md
> +When you make a call for the time period of 16:10-16:13, you're actually asking for the logs that were received and processed by our system during that time (hence the endpoint name, _logs/received_)
Capitalize `The _received_ time..`

2021-05-21 14:29 UTC, kodster28 commented on products/logs/src/content/faq/index.md
> +The advantage of basing the responses on the _time received_ rather than the request or edge time is not needing to worry about late-arriving logs. As long as you're calling our API for continuous ti
contraction

2021-05-21 14:30 UTC, kodster28 commented on products/logs/src/content/faq/index.md
> +The advantage of basing the responses on the _time received_ rather than the request or edge time is not needing to worry about late-arriving logs. As long as you're calling our API for continuous ti
`get all your logs without making duplicate calls`?

2021-05-21 14:32 UTC, kodster28 commented on products/logs/src/content/logpull/enabling-log-retention/index.md
> +By default, your HTTP request logs are not retained. When using the Logpull API for the first time, you'll need to enable retention. You can also turn off retention at any time. Note that after reten
Contraction

2021-05-21 14:33 UTC, kodster28 commented on products/logs/src/content/get-started/enable-destinations/aws-s3/index.md
>  # Enable Amazon S3
For the note on the bottom, it takes you to a page named `Uploading and copying objects using multipart upload`

2021-05-21 14:53 UTC, kodster28 requested changes
Still need to address some broken links + the `Examples` files

2021-05-21 14:53 UTC, kodster28 commented on products/logs/src/content/get-started/logpush-configuration-api/understanding-logpush-api.md
> +For concrete examples, see the tutorial [Manage Logpush with cURL](/get-started/logpush-configuration-api/tutorial-logpush-curl/).
Still takes me to a `404` page

2021-05-21 14:53 UTC, kodster28 commented on products/logs/src/content/tutorials/bot-management-dashboard.md
> +- Configure [Logpush](/logpush/) or [Logpull](/logpull/)
The `Logpush` link is broken.

2021-05-21 14:53 UTC, kodster28 commented on products/logs/src/content/tutorials/bot-management-dashboard.md
>  - Follow your analytics provider’s guides for getting logs from AWS S3 or Google Cloud Platform into your analytics platform
Lower in the tutorial, there are broken links for:

- `tutorials for enabling logs and dashboards for several analytics providers`
- `Analytics integrations`
- `analyze log data with Google Cloud`

2021-05-21 18:42 UTC, kodster28 approved these changes

2021-05-21 18:58 UTC, merged