[Logs] Create new reference page in logs docs for firewall field descriptions
cloudflare/cloudflare-docs pull request #1387
Opened 2021-05-20 15:46 UTC by crwaters16

2021-06-17 23:25 UTC, tlozoot approved these changes
This is phenomenal! We should merge this quickly and then iterate on these descriptions in future PRs :)

2021-06-17 23:25 UTC, tlozoot commented on products/logs/src/content/reference/firewall-fields.md
> +| <em><span style="font-weight: 400;">jschallenge</span></em> | Challenge Drop | Unused |
If this is unused, why do we have it here?

2021-06-17 23:25 UTC, tlozoot commented on products/logs/src/content/reference/firewall-fields.md
> +
nit but "allow or block" is pretty redundant here -- maybe we can just strike from these descriptions

2021-06-18 06:29 UTC, soheiokamoto commented on products/logs/src/content/reference/firewall-fields.md
> +| <em><span style="font-weight: 400;">jschallenge</span></em> | Challenge Drop | Unused |
It's not unused, but it is not clear what it should be exactly.
There is some discussion on a docs linked from the internal ticket PCX-975.
@worenga

2021-06-18 10:01 UTC, worenga commented on products/logs/src/content/reference/firewall-fields.md
> +| <em><span style="font-weight: 400;">jschallenge</span></em> | Challenge Drop | Unused |
This is not unused. The description should say "Issue a Javascript challenge"

2021-06-18 10:02 UTC, worenga commented on products/logs/src/content/reference/firewall-fields.md
> +| <em><span style="font-weight: 400;">jschallenge</span></em> | Challenge Drop | Unused |
```suggestion
| <em><span style="font-weight: 400;">jschallenge</span></em> | Challenge Drop | Issue a Javascript challenge |
```

2021-06-18 10:03 UTC, worenga commented on products/logs/src/content/reference/firewall-fields.md
> +| <em><span style="font-weight: 400;">challengeBypassed</span></em> | Allow | CAPTCHA challenge not issued, allow (see challenge status for reason)|
```suggestion
| <em><span style="font-weight: 400;">challengeBypassed</span></em> | Allow | CAPTCHA challenge not issued because the visitor had previously passed a captcha challenge|
```

2021-06-18 10:05 UTC, worenga commented on products/logs/src/content/reference/firewall-fields.md
> +| <em><span style="font-weight: 400;">jschallengeBypassed</span></em> | Allow | Allow if JS challenge bypassed (see challenge status for reason)  |
```suggestion
| <em><span style="font-weight: 400;">jschallengeBypassed</span></em> | Allow | JS challenge not issued because the visitor had previously passed a JS or Captcha challenge  |
```

2021-06-18 10:06 UTC, worenga commented on products/logs/src/content/reference/firewall-fields.md
> +| <em><span style="font-weight: 400;">managedChallengeBypassed</span></em> | Allow | Allow if managed challenge bypassed or not issued because visitor had clearance |
```suggestion
| <em><span style="font-weight: 400;">managedChallengeBypassed</span></em> | Allow | Challenge was not presented because visitor had clearance from previous challenge |
```

2021-06-18 10:08 UTC, worenga commented on products/logs/src/content/reference/firewall-fields.md
> +The Firewall fields contain rules managed by Cloudflare to block requests that contain malicious content.
those are not necessarily "managed" by cloudflare and are not necesarily "malicious". This could be very much customer policy.

2021-06-18 10:08 UTC, worenga requested changes
thx, please see amendmends/suggestions

2021-06-18 13:45 UTC, crwaters16 commented on products/logs/src/content/reference/firewall-fields.md
> +The Firewall fields contain rules managed by Cloudflare to block requests that contain malicious content.
Noted - updating to "The Firewall fields contain rules to block requests that contain specific types of content."

2021-06-18 13:51 UTC, crwaters16 commented on products/logs/src/content/reference/firewall-fields.md
> +
I wanted to lead with a verb for consistency with the descriptions that don't use "allow or block" - going to merge as-is but will consider less redundant phrasing for the future!

2021-06-18 13:51 UTC, crwaters16 commented on products/logs/src/content/reference/firewall-fields.md
> +| <em><span style="font-weight: 400;">challengeBypassed</span></em> | Allow | CAPTCHA challenge not issued, allow (see challenge status for reason)|
Implementing in separate commit to capitalize CAPTCHA

2021-06-18 13:52 UTC, crwaters16 commented on products/logs/src/content/reference/firewall-fields.md
> +| <em><span style="font-weight: 400;">jschallengeBypassed</span></em> | Allow | Allow if JS challenge bypassed (see challenge status for reason)  |
Implementing in separate commit to capitalize CAPTCHA

2021-06-18 13:56 UTC, worenga approved these changes

2021-06-18 14:22 UTC, pedrosousa approved these changes

2021-06-18 14:22 UTC, pedrosousa commented on products/logs/src/content/reference/firewall-fields.md
> +| <em><span style="font-weight: 400;">jschallenge</span></em> | Challenge Drop | Issue a Javascript challenge |
```suggestion
| <em><span style="font-weight: 400;">jschallenge</span></em> | Challenge Drop | Issue a JavaScript challenge |
```

2021-06-18 14:22 UTC, pedrosousa commented on products/logs/src/content/reference/firewall-fields.md
> +| <em><span style="font-weight: 400;">unknown</span></em> | Unknown | Take no other action |
Not sure we need all these `<span style="font-weight: 400;">(...)</span>`... 
Wouldn't the `<em>(...)</em>` tags be enough?

2021-06-18 14:22 UTC, pedrosousa commented on products/logs/src/content/reference/firewall-fields.md
> +| <em><span style="font-weight: 400;">managedChallengeNonInteractiveSolved</span></em> | Allow | Allow once managed challenge solved via non-interactive interstitial page |
The description is slightly cryptic... 
Maybe something like "Allow once the managed challenge was solved via non-interactive interstitial page".
The same comment applies to the next description.

2021-06-18 14:22 UTC, pedrosousa commented on products/logs/src/content/reference/firewall-fields.md
> +| <em><span style="font-weight: 400;">waf</span></em> | Allow or block based on the WAF product settings. This is the old WAF/managed rules system that is being phased out. |
We're not calling it "old WAF" anywhere else (we just say that the new one is "new") -- just an FYI, I have no better suggestion right now.

2021-06-18 14:22 UTC, pedrosousa commented on products/logs/src/content/reference/firewall-fields.md
> +| <em><span style="font-weight: 400;">hot</span></em> | Allow or block based on the Hotlinking Protection product settings |
I'd change it to "Hotlink Protection", like it's written in the dashboard. 
We do have one "Hotlinking" occurrence in Dev Docs that we should probably change.

2021-06-18 14:22 UTC, pedrosousa commented on products/logs/src/content/reference/firewall-fields.md
> +| <em><span style="font-weight: 400;">l7ddos</span></em> | Allow or block based on the L7 DdoS product settings |
```suggestion
| <em><span style="font-weight: 400;">l7ddos</span></em> | Allow or block based on the L7 DDoS product settings |
```

2021-06-18 14:22 UTC, pedrosousa commented on products/logs/src/content/reference/firewall-fields.md
> +| <em><span style="font-weight: 400;">firewallManaged</span></em> | Allow or block based on the Cloudflare managed rules product settings |
```suggestion
| <em><span style="font-weight: 400;">firewallManaged</span></em> | Allow or block based on the Firewall Managed Rules product settings |
```

2021-06-18 14:22 UTC, pedrosousa commented on products/logs/src/content/reference/firewall-fields.md
> +| <em><span style="font-weight: 400;">jschallenge</span></em> | Challenge Drop | Issue a Javascript challenge |
Alternatively, write just `JS`.

2021-06-18 14:55 UTC, crwaters16 commented on products/logs/src/content/reference/firewall-fields.md
> +| <em><span style="font-weight: 400;">waf</span></em> | Allow or block based on the WAF product settings. This is the old WAF/managed rules system that is being phased out. |
Probably better to omit and use "WAF/managed rule system that is being phased out"

2021-06-18 15:11 UTC, merged