[ZT] mDNSResponder troubleshooting
cloudflare/cloudflare-docs pull request #13983
Opened 2024-04-11 23:10 UTC by ranbel

2024-04-15 10:24 UTC, thibault-ml requested changes

2024-04-15 10:24 UTC, thibault-ml commented on content/cloudflare-one/connections/connect-devices/warp/troubleshooting/client-errors.md
> +On macOS, you may see `mDNSResponder` instead of the specific application name -- mDNSResponder is a macOS system process that handles DNS requests for Docker, certain virtual machine (VM) software,
```suggestion
On macOS, you may see `mDNSResponder` instead of the specific application name -- mDNSResponder is a macOS system process that handles DNS requests on behalf of other processes, such as virtual machine software (e.g. Docker, VMware Workstation), and other services (such as macOS' Internet Sharing feature).
```

2024-04-15 10:24 UTC, thibault-ml commented on content/cloudflare-one/connections/connect-devices/warp/troubleshooting/client-errors.md
> +The following third-party software are known to bind to port 53 via mDNSResponder. Rather than try to kill mDNSResponder, you will need to disable or configure the third-party software so that they n
```suggestion
Below is a non-exhaustive list of third-party software that are known to cause `mDNSResponder` to bind to port 53. Rather than try to kill `mDNSResponder`, you can either configure them so that they no longer use port 53, or temporarily disable them before connecting to WARP.
```

2024-04-15 10:24 UTC, thibault-ml commented on content/cloudflare-one/connections/connect-devices/warp/troubleshooting/client-errors.md
> +- **Certain VM software (such as VMWare and Parallel)**: The presence of VM software does not guarantee that it is the offending program, since compatibility with WARP is highly dependent on the VM's
```suggestion
- **Certain VM software (such as VMware Workstation or Parallels)**: The presence of VM software does not guarantee that it is the offending program, since compatibility with WARP is highly dependent on the VM's configuration. To work around the issue, connect to WARP _before_ running any VMs:
```

2024-04-15 10:26 UTC, thibault-ml commented
Is it worth making a note that there are is known way to determine which process triggered `mDNSResponder` to listen to port 53?

2024-04-17 13:32 UTC, thibault-ml commented on content/cloudflare-one/connections/connect-devices/warp/troubleshooting/client-errors.md
> +On macOS, you may see `mDNSResponder` instead of the specific application name -- mDNSResponder is a macOS system process that handles DNS requests on behalf of other processes. There is no known way
```suggestion
On macOS, you may see `mDNSResponder` instead of the specific application name -- `mDNSResponder` is a macOS system process that handles DNS requests on behalf of other processes. There is no known way to determine which process caused `mDNSResponder` to bind to port `53`, but the most common culprits are virtual machine software (for example, Docker and VMware Workstation) and the macOS Internet Sharing feature.
```

2024-04-17 13:33 UTC, thibault-ml approved these changes

2024-04-17 15:05 UTC, marciocloudflare approved these changes

2024-04-17 15:05 UTC, marciocloudflare commented on content/cloudflare-one/connections/connect-devices/warp/troubleshooting/client-errors.md
> +Below is a non-exhaustive list of third-party software that are known to cause `mDNSResponder` to bind to port `53`. Rather than try to kill `mDNSResponder`, you should either configure the third-par
```suggestion
Below is a non-exhaustive list of third-party software that are known to cause `mDNSResponder` to bind to port `53`. Rather than try to stop `mDNSResponder`, you should either configure the third-party software so that they no longer use port `53`, or temporarily disable them before connecting to WARP.
```

2024-04-17 15:05 UTC, marciocloudflare commented on content/cloudflare-one/connections/connect-devices/warp/troubleshooting/client-errors.md
> +Below is a non-exhaustive list of third-party software that are known to cause `mDNSResponder` to bind to port `53`. Rather than try to kill `mDNSResponder`, you should either configure the third-par
"kill" might be too aggressive a word to use in this context

2024-04-17 15:05 UTC, marciocloudflare commented on content/cloudflare-one/connections/connect-devices/warp/troubleshooting/client-errors.md
> +
```suggestion
```

2024-04-17 15:28 UTC, merged