[DLS] Adds GraphQL datastes info to CMB docs
cloudflare/cloudflare-docs pull request #13986
Opened 2024-04-12 09:42 UTC by angelampcosta

2024-04-12 17:12 UTC, soheiokamoto commented on content/data-localization/metadata-boundary/graphql-datasets.md
> +| | Browser Isolation | US and EU <br> Only the field `isIsolated` part of `GatewayL7RequestsAdaptiveGroups` dataset |
To be consistent with other descriptions:
```suggestion
| | Browser Isolation | US and EU <br> Only the field `isIsolated` part of `GatewayL7RequestsAdaptiveGroups`  |
```

2024-04-15 09:41 UTC, pedrosousa approved these changes

2024-04-15 09:41 UTC, pedrosousa commented on content/data-localization/metadata-boundary/graphql-datasets.md
> +| | WAF/L7 Firewall | US and EU <br> [`firewallEventsAdaptive`](/analytics/graphql-api/tutorials/querying-firewall-events/) <br> [`firewallEventsAdaptiveGroups`](https://blog.cloudflare.com/how-we-us
Not sure if it's worth linking `firewallEventsAdaptiveByTimeGroups` to `/logs/reference/change-notices/2023-02-01-security-fields-updates/`: It doesn't contain relevant information about the dataset, just a couple of changes.

2024-04-15 09:41 UTC, pedrosousa commented on content/data-localization/metadata-boundary/graphql-datasets.md
> +| | Workers (deployed on a Zone) | US and EU <br> `workerPlacementAdaptiveGroups` <br> US only <br> `workersZoneInvocationsAdaptiveGroups` <br> `workersZoneSubrequestsAdaptiveGroups` <br> `workersOve
The anchor "#4-query-data-using-graphql-and-sql-api" no longer exists on the target page.

2024-04-16 15:59 UTC, jimhawkridge requested changes
I've cross checked the graphql ones against the config and have some suggestions.

2024-04-16 15:59 UTC, jimhawkridge commented on content/data-localization/metadata-boundary/graphql-datasets.md
> +| | Workers (deployed on a Zone) | US and EU <br> `workerPlacementAdaptiveGroups` <br> US only <br> `workersZoneInvocationsAdaptiveGroups` <br> `workersZoneSubrequestsAdaptiveGroups` <br> `workersOve
`workersAnalyticsEngineAdaptiveGroups` is available in the EU now.

2024-04-16 15:59 UTC, jimhawkridge commented on content/data-localization/metadata-boundary/graphql-datasets.md
> +| | Magic Firewall |  US only <br> [`magicFirewallSamplesAdaptiveGroups`](/magic-firewall/tutorials/graphql-analytics/) <br> [`magicFirewallNetworkAnalyticsAdaptiveGroup`](/magic-firewall/tutorials/g
```suggestion
| | Magic Firewall |  US only <br> [`magicFirewallSamplesAdaptiveGroups`](/magic-firewall/tutorials/graphql-analytics/) <br> [`magicFirewallNetworkAnalyticsAdaptiveGroups`](/magic-firewall/tutorials/graphql-analytics/#example-queries-for-magic-firewall) | 
```

2024-04-16 15:59 UTC, jimhawkridge commented on content/data-localization/metadata-boundary/graphql-datasets.md
> +| | Magic Network Monitoring | US and EU <br> [`mnmFlowDataAdaptiveGroups`](/magic-network-monitoring/tutorials/graphql-analytics/) |
```suggestion
| | Magic Network Monitoring | US only <br> [`mnmFlowDataAdaptiveGroups`](/magic-network-monitoring/tutorials/graphql-analytics/) |
```

2024-04-16 15:59 UTC, jimhawkridge commented on content/data-localization/metadata-boundary/graphql-datasets.md
> +| Platform | GraphQL Analytics API | [All GraphQL Analytics API datasets](/analytics/graphql-api/features/discovery/introspection/) |
Do we mean to say `US and EU` here?

2024-04-16 15:59 UTC, jimhawkridge commented on content/data-localization/metadata-boundary/graphql-datasets.md
> +| | Browser Isolation | US and EU <br> Only the field `isIsolated` part of `GatewayL7RequestsAdaptiveGroups`  |
```suggestion
| | Browser Isolation | US and EU <br> Only the field `isIsolated` part of `gatewayL7RequestsAdaptiveGroups`  |
```

2024-04-16 16:30 UTC, jimhawkridge approved these changes

2024-04-16 16:37 UTC, merged