images beta first commit
cloudflare/cloudflare-docs pull request #1405
Opened 2021-05-24 14:57 UTC by zaidf

2021-05-24 15:59 UTC, sejoker approved these changes

2021-05-24 15:59 UTC, sejoker commented on products/images/src/content/cloudflare-images-beta.md
> +The `default` variant has the following preconfigured settings based on device type:
adding link to https://support.cloudflare.com/hc/en-us/articles/229373388-Understand-Cache-by-Device-Type-Enterprise-plans-only- could be helpful for customers.

2021-05-24 16:46 UTC, marciocloudflare commented on products/images/src/content/cloudflare-images-beta.md
> +Cloudflare Images is currently in closed beta. To request an invite, [click here.](https://docs.google.com/forms/d/1x1caSSYQn10dRjxNLJlG-MdHgLnUa2mnR6iUpa2ahxI/edit)
To improve SEO, this sentence could be "To request an invite, please fill out this Google Forms", instead of "click here".

2021-05-24 16:47 UTC, youtacrsbyvars approved these changes

2021-05-24 16:47 UTC, marciocloudflare requested changes
Hi Zaid. I left a comment on something that could improve our SEO if changed. Let me know what you think.

2021-05-24 16:52 UTC, marciocloudflare approved these changes

2021-05-24 16:53 UTC, merged

2021-06-11 00:54 UTC, youtacrsbyvars reviewed
Z