[D1] Mention underlying database engine
cloudflare/cloudflare-docs pull request #14080
Opened 2024-04-17 13:58 UTC by Maddy-Cloudflare

2024-04-17 14:31 UTC, vy-ton requested changes

2024-04-17 14:31 UTC, vy-ton commented on content/d1/_index.md
> +D1 is Cloudflare’s native serverless database, and it uses SQLite as query engine. D1 allows you to build applications that handle large amounts of users at no extra cost. With D1, you can restore yo
We should add SQL to the `Features` section on this page and link out to https://developers.cloudflare.com/d1/build-with-d1/d1-client-api/. 

I would also mention SQLite query engine/dialect on https://developers.cloudflare.com/d1/build-with-d1/d1-client-api/ instead of it being in the first sentence of D1 overview

2024-04-17 14:32 UTC, marciocloudflare approved these changes

2024-04-17 14:44 UTC, Maddy-Cloudflare commented on content/d1/_index.md
> +D1 is Cloudflare’s native serverless database, and it uses SQLite as query engine. D1 allows you to build applications that handle large amounts of users at no extra cost. With D1, you can restore yo
> I would also mention SQLite query engine/dialect on https://developers.cloudflare.com/d1/build-with-d1/d1-client-api/ instead of it being in the first sentence of D1 overview

It is mentioned here: https://developers.cloudflare.com/d1/build-with-d1/d1-client-api/#parameter-binding

2024-04-17 14:58 UTC, vy-ton commented on content/d1/_index.md
> +D1 is Cloudflare’s native serverless database, and it uses SQLite as query engine. D1 allows you to build applications that handle large amounts of users at no extra cost. With D1, you can restore yo
That's quite hidden. I would mention it in the top paragraph that "D1 leverages SQlite's query engine and SQL dialect"

2024-04-18 14:36 UTC, vy-ton requested changes

2024-04-18 14:36 UTC, vy-ton commented on content/d1/_index.md
> +{{<feature header="SQLite" href="/d1/build-with-d1/d1-client-api/" cta="Learn how D1 uses SQLite">}}
```suggestion
{{<feature header="SQLite" href="/d1/build-with-d1/d1-client-api/" cta="Execute SQL queries">}}
```

2024-04-18 14:36 UTC, vy-ton commented on content/d1/_index.md
> +Learn how D1 uses SQLite as query engine.
```suggestion
Execute SQL with SQLite's SQL compatibility and D1 Client API.
```

2024-04-18 14:36 UTC, vy-ton commented on content/d1/build-with-d1/d1-client-api.md
> +D1 uses SQLite as query engine. D1 client API allows you to interact with a D1 database from within a [Worker](/workers/).
```suggestion
D1 is compatible with most SQLite's SQL convention since it leverages SQLite's query engine. D1 client API allows you to interact with a D1 database from within a [Worker](/workers/). 
```

2024-04-18 14:54 UTC, vy-ton approved these changes

2024-04-18 14:59 UTC, merged