[Workers] Add details on local data and how to interact with it
cloudflare/cloudflare-docs pull request #14098
Opened 2024-04-17 20:29 UTC by admah

Addresses #13493

2024-04-18 14:25 UTC, deadlypants1973 commented
I think @penalosa was against the usage of the words "preview data", tagging for review

2024-04-18 14:28 UTC, penalosa commented
@admah could we remove "preview" from this? Workers don't really have preview data stores (even if we try and fake it in Wrangler with preview_id and the like)

2024-04-18 14:52 UTC, admah commented
@penalosa ah...yes. I can definitely remove that.

2024-04-18 17:06 UTC, deadlypants1973 commented on content/workers/testing/local-development.md
> +This will create a new key `test` with a value of `12345` on the local namespace specified via the binding `MY_KV_NAMESPACE` in `wrangler.toml`. This command also assumes that the local persistence d
What is 'this'? Let's replace with the proper noun(s)
```suggestion
_____ will create a new key `test` with a value of `12345` on the local namespace specified via the binding `MY_KV_NAMESPACE` in `wrangler.toml`. The _____ command also assumes that the local persistence data is set to `worker-local` so `--persist-to` is set to that ensuring the data is created in the correct location. If `--persist-to` was not set, it would create the data at `.wrangler`.
```

2024-04-18 17:07 UTC, deadlypants1973 commented
closes #14079

2024-04-19 12:29 UTC, deadlypants1973 approved these changes

2024-04-23 15:59 UTC, kodster28 commented
closes #13493

2024-04-23 17:11 UTC, penalosa requested changes

2024-04-23 17:11 UTC, penalosa commented on content/workers/testing/local-development.md
> +When you run `wrangler dev` Wrangler creates local resources in a `.wrangler` folder like this:
```suggestion
When you run `wrangler dev` Wrangler stores local resources in a `.wrangler/state` folder, which is automatically created.
```

2024-04-23 17:11 UTC, penalosa commented on content/workers/testing/local-development.md
> +
```suggestion
```

2024-04-23 17:11 UTC, penalosa commented on content/workers/testing/local-development.md
> +This will create a new key `test` with a value of `12345` on the local namespace specified via the binding `MY_KV_NAMESPACE` in `wrangler.toml`. This command also assumes that the local persistence d
```suggestion
This will create a new key `test` with a value of `12345` on the local namespace specified via the binding `MY_KV_NAMESPACE` in `wrangler.toml`. This example command sets the local persistence directory to `worker-local` using `--persist-to`, to ensure that the data is created in the correct location. If `--persist-to` was not set, it would create the data in the `.wrangler` folder.
```

2024-04-23 17:11 UTC, penalosa commented on content/workers/testing/local-development.md
> +If you need to clear local storage entirely, delete the `.wrangler/state` folder. You can also be more fine-tuned and delete specific resource folders within `.wrangler/state`.
```suggestion
If you need to clear local storage entirely, delete the `.wrangler/state` folder. You can also be more fine-grained and delete specific resource folders within `.wrangler/state`.
```

2024-04-23 17:11 UTC, penalosa commented on content/workers/testing/local-development.md
> +## Develop locally using remote resources and bindings
```suggestion
## Develop using remote resources and bindings
```

2024-04-23 17:11 UTC, penalosa commented on content/workers/testing/local-development.md
> +There may be times you want to develop against remote resources and bindings. To run `wrangler dev` in remote mode, add the `--remote` flag:
```suggestion
There may be times you want to develop against remote resources and bindings. To run `wrangler dev` in remote mode, add the `--remote` flag, which will run both your code and resources remotely:
```

2024-04-23 17:13 UTC, deadlypants1973 commented on content/workers/testing/local-development.md
> +This will create a new key `test` with a value of `12345` on the local namespace specified via the binding `MY_KV_NAMESPACE` in `wrangler.toml`. This command also assumes that the local persistence d
Can you change 'this' to actually name the thing and not just be 'this'? We should always be defining 'this' as the proper noun.

2024-04-23 17:14 UTC, penalosa commented on content/workers/testing/local-development.md
> +This will create a new key `test` with a value of `12345` on the local namespace specified via the binding `MY_KV_NAMESPACE` in `wrangler.toml`. This command also assumes that the local persistence d
How's "The above command"?

2024-04-24 11:05 UTC, penalosa approved these changes

2024-04-24 11:06 UTC, merged