[Workers] New Tutorial - Building a Serverless API using Drizzle ORM, Hono & Neon
cloudflare/cloudflare-docs pull request #14243
Opened 2024-04-24 19:07 UTC by chankruze

2024-04-25 14:07 UTC, yusukebe commented on content/workers/tutorials/serverless-api-with-drizzle-hono-and-neon/index.md
> +- Choose `"Hello World" Worker` for the type of application you would like to create.
You can also use the Hono template by choosing `Website or web app` => `Hono`. Both are OK but I recommend this.

![CleanShot 2024-04-25 at 22 55 21@2x](https://github.com/cloudflare/cloudflare-docs/assets/10682/70776f50-6a37-4066-bc97-9c609e7c7ae7)

2024-04-25 14:07 UTC, yusukebe commented on content/workers/tutorials/serverless-api-with-drizzle-hono-and-neon/index.md
> +## 2. Set up Hono.js
`Hono.js` should be `Hono`!

2024-04-25 14:07 UTC, yusukebe commented on content/workers/tutorials/serverless-api-with-drizzle-hono-and-neon/index.md
> +app.get('/', async (c) => {
It's a matter of taste, I prefer not to use`try`/`catch`. In this simple use case, it can be handled with `app.onError()` handler.

```ts
app.get('/', async (c) => {
  const sql = neon(c.env.DATABASE_URL)
  const db = drizzle(sql)
  const result = await db.select().from(products)
  return c.json({ result })
})

app.onError((error, c) => {
  console.log(error)
  return c.json({ error }, 400)
})
```

Then, if users want to make a larger application, they should use a validator that can handle validation errors smartly.
https://hono.dev/guides/validation

2024-04-25 14:08 UTC, yusukebe commented
Hi @chankruze !

Thank you for the great tutorial! I'm glad that this uses Hono as a creator of Hono. I've left some comments. Please check them.

2024-04-25 14:20 UTC, chankruze commented
@yusukebe Thanks for the review. I will update the tutorial with your inputs.

Thanks ☺️

2024-04-25 15:18 UTC, yusukebe commented on content/workers/tutorials/serverless-api-with-drizzle-hono-and-neon/index.md
> +    const sql = neon(c.env.DATABASE_URL);
Can you unify using **2** spaces?

![CleanShot 2024-04-26 at 00 07 34@2x](https://github.com/cloudflare/cloudflare-docs/assets/10682/12a69484-ecb5-4e34-82ba-a94efec83bb4)

2024-04-25 15:29 UTC, yusukebe approved these changes
LGTM!

2024-05-10 15:54 UTC, Maddy-Cloudflare approved these changes

2024-05-10 15:54 UTC, Maddy-Cloudflare commented on content/workers/tutorials/serverless-api-with-drizzle-hono-and-neon/index.md
> +title: Cloudflare Workers - Building a Serverless API using Drizzle ORM, Hono & Neon
```suggestion
title: Cloudflare Workers - Build a serverless API using Drizzle ORM, Hono & Neon
```

2024-05-10 15:54 UTC, Maddy-Cloudflare commented on content/workers/tutorials/serverless-api-with-drizzle-hono-and-neon/index.md
> +# Cloudflare Workers - Building a Serverless API using Drizzle ORM, Hono & Neon
```suggestion
# Cloudflare Workers - Build a serverless API using Drizzle ORM, Hono and Neon
```

2024-05-10 15:54 UTC, Maddy-Cloudflare commented on content/workers/tutorials/serverless-api-with-drizzle-hono-and-neon/index.md
> +- Choose `Website or web app` for the type of application you would like to create.
```suggestion
1. Choose `Website or web app` for the type of application you would like to create.
```

2024-05-10 15:54 UTC, Maddy-Cloudflare commented on content/workers/tutorials/serverless-api-with-drizzle-hono-and-neon/index.md
> +- Choose `Hono` to `Which development framework do you want to use?`
```suggestion
2. Choose `Hono` to `Which development framework do you want to use?`
```

2024-05-10 15:54 UTC, Maddy-Cloudflare commented on content/workers/tutorials/serverless-api-with-drizzle-hono-and-neon/index.md
> +- Answer `Yes` to `Do you want to use git for version control?`
```suggestion
3. Answer `Yes` to `Do you want to use git for version control?`
```

2024-05-10 15:54 UTC, Maddy-Cloudflare commented on content/workers/tutorials/serverless-api-with-drizzle-hono-and-neon/index.md
> +- Answer `No` to `Do you want to deploy your application?`
```suggestion
4. Answer `No` to `Do you want to deploy your application?`
```

2024-05-10 15:54 UTC, Maddy-Cloudflare commented on content/workers/tutorials/serverless-api-with-drizzle-hono-and-neon/index.md
> +Now wait for a bit to finish the setup. It should look similar to this:
```suggestion
Once you complete your setup, you should receive the following output:
```

2024-05-10 15:54 UTC, Maddy-Cloudflare commented on content/workers/tutorials/serverless-api-with-drizzle-hono-and-neon/index.md
> +npm install hono
```suggestion
$ npm install hono
```

2024-05-10 15:54 UTC, Maddy-Cloudflare commented on content/workers/tutorials/serverless-api-with-drizzle-hono-and-neon/index.md
> +Go ahead and create an account if you do not have one already. Next, create a new project. Choose `16` as the Postgres version, pick the region closest to where you want to deploy your app and pick a
```suggestion
Once if you have created your Neon account, you can set up a new project. Choose `16` as the Postgres version, select the region closest to where you want to deploy your app, and select a size for your compute endpoint (you can change this later).
```

2024-05-10 15:54 UTC, Maddy-Cloudflare commented on content/workers/tutorials/serverless-api-with-drizzle-hono-and-neon/index.md
> +After you create the project, you get a connection string that you can use to connect to your database. In the root of your project, create a .dev.vars file and add the connection string as an enviro
```suggestion
After creating your project, you will get a connection string used to connect to your database. In the root of your project, create a `.dev.vars` file and add the connection string as an environment variable. It should be formatted like a `dotenv` file, such as `KEY=VALUE`.
```

2024-05-10 15:54 UTC, Maddy-Cloudflare commented on content/workers/tutorials/serverless-api-with-drizzle-hono-and-neon/index.md
> +npm i drizzle-orm @neondatabase/serverless
```suggestion
$ npm i drizzle-orm @neondatabase/serverless
```

2024-05-10 15:54 UTC, Maddy-Cloudflare commented on content/workers/tutorials/serverless-api-with-drizzle-hono-and-neon/index.md
> +npm i -D drizzle-kit postgres dotenv tsx
```suggestion
$ npm i -D drizzle-kit postgres dotenv tsx
```

2024-05-10 15:54 UTC, Maddy-Cloudflare commented on content/workers/tutorials/serverless-api-with-drizzle-hono-and-neon/index.md
> +You are then installing `drizzle-kit` for generating migrations, `postgres.js` to establish a connection when running migrations, `dotenv` for loading environment variables, and `tsx` for executing T
```suggestion
Then, install `drizzle-kit` for generating migrations, `postgres.js` to establish a connection when running migrations, `dotenv` for loading environment variables, and `tsx` for executing TypeScript files.
```

2024-05-10 15:54 UTC, Maddy-Cloudflare commented on content/workers/tutorials/serverless-api-with-drizzle-hono-and-neon/index.md
> +In your src directory, create a new `db/schema.ts` file. This file will contain the database schema definition in TypeScript. Add the following code to the file you just created:
```suggestion
In your source directory, create a new `db/schema.ts` file. This file will contain the database schema definition in TypeScript. Add the following code to the file you just created:
```

2024-05-10 15:54 UTC, Maddy-Cloudflare commented on content/workers/tutorials/serverless-api-with-drizzle-hono-and-neon/index.md
> +In the project’s root directory, create a `drizzle.config.ts` file and add the following code to it:
```suggestion
In the project’s root directory, create a `drizzle.config.ts` file and add the following code:
```

2024-05-10 15:54 UTC, Maddy-Cloudflare commented on content/workers/tutorials/serverless-api-with-drizzle-hono-and-neon/index.md
> +In this config file, you will specify the location of your schema as well as the output directory, which will contain the generated migrations. In our case, the output directory is called drizzle and
```suggestion
In this config file, you will specify the location of your schema as well as the output directory, which will contain the generated migrations. In this tutorial, the output directory is called drizzle and will be located in the project’s root directory.
```

2024-05-10 15:54 UTC, Maddy-Cloudflare commented on content/workers/tutorials/serverless-api-with-drizzle-hono-and-neon/index.md
> +The next step is to generate the database migrations. To do that, modify your `package.json` file and add a new `db:generate` command in the scripts object:
```suggestion
The next step is to generate the database migrations. To generate database migrations, modify your `package.json` file and add a new `db:generate` command in the scripts object:
```

2024-05-10 15:54 UTC, Maddy-Cloudflare commented on content/workers/tutorials/serverless-api-with-drizzle-hono-and-neon/index.md
> +Now if you run the command npm run db:generate, you will see a newly generated SQL migration file in the `/drizzle` directory. The final step is to apply the migration to the database.
```suggestion
If you run the command `npm run db:generate`, you will receive a newly generated SQL migration file in the `/drizzle` directory. The final step is to apply the migration to the database.
```

2024-05-10 15:54 UTC, Maddy-Cloudflare commented on content/workers/tutorials/serverless-api-with-drizzle-hono-and-neon/index.md
> +In your project’s root directory, create a `migrate.ts` file and add the following code to it:
```suggestion
In your project’s root directory, create a `migrate.ts` file and add the following code:
```

2024-05-10 15:54 UTC, Maddy-Cloudflare commented on content/workers/tutorials/serverless-api-with-drizzle-hono-and-neon/index.md
> +Finally, to be able to execute this `migrate.ts` file, modify your package.json file and add a new `db:migrate` script in the scripts object:
```suggestion
To execute this `migrate.ts` file, modify your package.json file and add a new `db:migrate` script in the scripts object:
```

2024-05-10 15:54 UTC, Maddy-Cloudflare commented on content/workers/tutorials/serverless-api-with-drizzle-hono-and-neon/index.md
> +npm run db:migrate
```suggestion
$ npm run db:migrate
```

2024-05-10 15:54 UTC, Maddy-Cloudflare commented on content/workers/tutorials/serverless-api-with-drizzle-hono-and-neon/index.md
> +Right now, the products table you created is empty. In the Neon console, go to the SQL editor and run the following SQL query to add data to the products table.
```suggestion
Until this step, the `products` table you created has been empty. In the Neon console, go to the SQL editor and run the following SQL query to add data to the products table:
```

2024-05-10 15:54 UTC, Maddy-Cloudflare commented on content/workers/tutorials/serverless-api-with-drizzle-hono-and-neon/index.md
> +The next step is to connect to the database from the worker.
```suggestion
The next step is to connect to the database from the Worker.
```

2024-05-10 15:54 UTC, Maddy-Cloudflare commented on content/workers/tutorials/serverless-api-with-drizzle-hono-and-neon/index.md
> +## 9. Connect to Neon from the worker
```suggestion
## 9. Connect to Neon from the Worker
```

2024-05-10 15:54 UTC, Maddy-Cloudflare commented on content/workers/tutorials/serverless-api-with-drizzle-hono-and-neon/index.md
> +Navigate to your `src/index.ts` and add the following code:
```suggestion
Go to your `src/index.ts` and add the following code:
```

2024-05-10 15:54 UTC, Maddy-Cloudflare commented on content/workers/tutorials/serverless-api-with-drizzle-hono-and-neon/index.md
> +Now, if you start your development server and go to `http://localhost:8787`, you will be able to see data being returned as JSON.
```suggestion
If you start your development server and go to `http://localhost:8787`, your browser will display data being returned as JSON.
```

2024-05-10 15:54 UTC, Maddy-Cloudflare commented on content/workers/tutorials/serverless-api-with-drizzle-hono-and-neon/index.md
> +Now, if you start your development server and go to `http://localhost:8787`, you will be able to see data being returned as JSON.
This one is for accessibility.

2024-05-10 15:54 UTC, Maddy-Cloudflare commented on content/workers/tutorials/serverless-api-with-drizzle-hono-and-neon/index.md
> +## 10. Deploy the worker using wrangler
```suggestion
## 10. Deploy your Worker using wrangler
```

2024-05-10 15:54 UTC, Maddy-Cloudflare commented on content/workers/tutorials/serverless-api-with-drizzle-hono-and-neon/index.md
> +Once logged in, you can run `npx wrangler deploy`, which deploys your worker. If you try to visit the deployed version, you will run into an error because you have not included the `DATABASE_URL` env
```suggestion
Once logged in, run `npx wrangler deploy`, which deploys your Worker. If you try to visit the deployed version, you will run into an error because you have not included the `DATABASE_URL` environment variable. To do that, you will leverage the Neon integration on Cloudflare.
```

2024-05-10 15:54 UTC, Maddy-Cloudflare commented on content/workers/tutorials/serverless-api-with-drizzle-hono-and-neon/index.md
> +Log into the Cloudflare dashboard, select “Workers & Pages” from the sidebar, and then “Overview”.
```suggestion
Log into the Cloudflare dashboard, select **Workers & Pages** from the sidebar, and then **Overview**.
```

2024-05-10 15:54 UTC, Maddy-Cloudflare commented on content/workers/tutorials/serverless-api-with-drizzle-hono-and-neon/index.md
> +Next, choose the Worker you deployed, go to the “Settings” tab, choose “Integrations”, and select “Neon”. After accepting the terms, you will be redirected to an OAuth consent screen where you can au
```suggestion
Next, choose the Worker you deployed, go to the **Settings** tab, choose **Integrations**, and select **Neon**. After accepting the terms, you will be redirected to an OAuth consent screen where you can authorize Cloudflare. Finally, select your project, branch, database, and role to finish setting up the integration.
```

2024-05-10 15:54 UTC, Maddy-Cloudflare commented on content/workers/tutorials/serverless-api-with-drizzle-hono-and-neon/index.md
> +Adding the integration automatically redeploys your worker. So now, when you visit the deployed worker, you will be able to see data returned from the database as JSON.
```suggestion
Adding the integration automatically redeploys your Worker. When you visit the deployed Worker, your browser will display data returned from the database as JSON.
```

2024-05-10 15:54 UTC, Maddy-Cloudflare commented on content/workers/tutorials/serverless-api-with-drizzle-hono-and-neon/index.md
> +In this guide, you learned about Cloudflare workers, Hono, Drizzle ORM, Neon, and how you can use them together to create a serverless API.
```suggestion
In this guide, you learned about [Cloudflare Workers](/workers/), Hono, Drizzle ORM, Neon, and how you can use them together to create a serverless API.
```

2024-05-10 15:54 UTC, Maddy-Cloudflare commented on content/workers/tutorials/serverless-api-with-drizzle-hono-and-neon/index.md
> +To successfully complete this guide, you will need:
```suggestion
To successfully complete this tutorial, you will need:
```

2024-05-12 15:38 UTC, chankruze commented on content/workers/tutorials/serverless-api-with-drizzle-hono-and-neon/index.md
> +npm install hono
It's already a code block with shell (`sh`) type.

2024-05-12 15:48 UTC, chankruze commented on content/workers/tutorials/serverless-api-with-drizzle-hono-and-neon/index.md
> +Finally, to be able to execute this `migrate.ts` file, modify your package.json file and add a new `db:migrate` script in the scripts object:
I believe this is correct already.

2024-05-14 09:10 UTC, dbenCF requested changes

2024-05-14 09:10 UTC, db-cloudflare commented on content/workers/tutorials/serverless-api-with-drizzle-hono-and-neon/index.md
> +1. Choose `Website or web app` for the type of application you would like to create.
```suggestion
1. Select `Website or web app` for the type of application you would like to create.
```

2024-05-14 09:10 UTC, db-cloudflare commented on content/workers/tutorials/serverless-api-with-drizzle-hono-and-neon/index.md
> +2. Choose `Hono` to `Which development framework do you want to use?`
```suggestion
2. Select `Hono` to `Which development framework do you want to use?`
```

2024-05-14 09:10 UTC, db-cloudflare commented on content/workers/tutorials/serverless-api-with-drizzle-hono-and-neon/index.md
> +Once you complete your setup, you should receive the following output:
You can probably remove this example output from the CLI (Lines 45 to 128)

2024-05-14 09:10 UTC, db-cloudflare commented on content/workers/tutorials/serverless-api-with-drizzle-hono-and-neon/index.md
> +Go ahead and create an account if you do not have one already. Next, create a new project. Choose `16` as the Postgres version, select the region closest to where you want to deploy your app and sele
```suggestion
Once you have created your Neon account, go to your Neon console and create a new project. Choose `16` as the Postgres version, select the region closest to where you want to deploy your app and select a size for your compute endpoint (you can change this later).
```

2024-05-14 09:10 UTC, dbenCF commented on content/workers/tutorials/serverless-api-with-drizzle-hono-and-neon/index.md
> +Add the following code to your `src/index.ts` file:
```suggestion
Add the following code to your Worker's `src/index.ts` file:
```

2024-05-15 06:09 UTC, chankruze commented
@dbenCF I have changed the tutorial following your comments. Please check!

2024-05-15 09:16 UTC, dbenCF commented
LGTM! Great work.

2024-05-15 15:58 UTC, dbenCF approved these changes

2024-05-15 17:09 UTC, merged