[Wrangler] Pages secret
cloudflare/cloudflare-docs pull request #14300
Opened 2024-04-29 15:02 UTC by kodster28

closes #13958.

Trying to keep slim to limit repetition in that file.

2024-04-29 16:56 UTC, penalosa commented on content/workers/wrangler/commands.md
> +```txt
```suggestion
```sh
```

2024-04-29 16:57 UTC, penalosa requested changes

2024-04-29 16:57 UTC, penalosa commented on content/workers/wrangler/commands.md
> +All the subcommands and definitions are identical to [`wrangler secret`](#secret).
This isn't quite right—they take slightly different options and `secret:bulk` is called `secret bulk`

2024-04-30 17:12 UTC, kodster28 commented
Closing as this requires a lot more work than I initially thought :)

Thanks for keeping me honest, @penalosa

2024-05-01 17:14 UTC, closed without merging