[Workers Tutorial]How to use Cloudflare Workers to send form submissions from an Astro+Resend app
cloudflare/cloudflare-docs pull request #14451
Opened 2024-05-07 21:17 UTC by CodyDubu

Contribution to Cloudflare’s Developer Spotlight program.

2024-06-12 13:43 UTC, megaconfidence commented on content/workers/tutorials/handle-form-submission-with-astro-resend/index.md
> +npm create cloudflare@latest my-astro-app -- --framework=astro/
It seems the trailing slash in `--framework=astro/` breaks the CLI

2024-06-12 13:48 UTC, megaconfidence commented on content/workers/tutorials/handle-form-submission-with-astro-resend/index.md
> +npm run astro add cloudflare
I guess readers should run this in the project directory yes?

2024-06-13 10:07 UTC, dbenCF requested changes
Looks great! I left a few suggestions for your review. Thank you so much for contributing to our docs.

2024-06-13 10:07 UTC, db-cloudflare commented on content/workers/tutorials/handle-form-submission-with-astro-resend/index.md
> +This article will instruct5 you on how to send emails from Astro and Cloudflare Workers (via Cloudflare SSR Adapter) using Resend.
```suggestion
This tutorial will instruct you on how to send emails from [Astro](https://astro.build/) and Cloudflare Workers using [Resend](https://resend.com/).
```

2024-06-13 10:07 UTC, db-cloudflare commented on content/workers/tutorials/handle-form-submission-with-astro-resend/index.md
> +This adapter allows Astro's Server-Side Rendered (SSR) sites and components to work on Cloudflare Pages and converts Astro's endpoints into Cloudflare Workers.
```suggestion
The [`@astrojs/cloudflare` adapter](https://github.com/withastro/adapters/tree/main/packages/cloudflare#readme) allows Astro's Server-Side Rendered (SSR) sites and components to work on Cloudflare Pages and converts Astro's endpoints into Cloudflare Workers endpoints.
```

2024-06-13 10:07 UTC, db-cloudflare commented on content/workers/tutorials/handle-form-submission-with-astro-resend/index.md
> +	-  Deployed Worker: run the following in your cli and follow the instructions.
```suggestion
	- For local development, create an .env in the root folder of your Astro project and save the API key as RESEND_API_KEY='Api key here' (no quotes).
	-  For a deployed Worker, run the following in your CLI and follow the instructions.
```

2024-06-13 10:07 UTC, db-cloudflare commented on content/workers/tutorials/handle-form-submission-with-astro-resend/index.md
> +```
I'd recommend running a script formatter on the TypeScript code blocks to make sure the spacing is correct.

2024-06-13 10:07 UTC, db-cloudflare commented on content/workers/tutorials/handle-form-submission-with-astro-resend/index.md
> +Next you will need to install the resend SDK.
```suggestion
Next you will need to install the Resend SDK.
```

2024-06-13 10:07 UTC, db-cloudflare commented on content/workers/tutorials/handle-form-submission-with-astro-resend/index.md
> +## 3. Astro Endpoint/Worker
I would change this title to have a call to action, such as 'Create an Astro endpoint'.

2024-06-13 10:07 UTC, db-cloudflare commented on content/workers/tutorials/handle-form-submission-with-astro-resend/index.md
> +After creating the `AstroForm` component, add it to your Astro app, just like any other component [component](https://docs.astro.build/en/basics/astro-components/).
```suggestion
After creating the `AstroForm` component, add it to your Astro app, just like any other [component](https://docs.astro.build/en/basics/astro-components/).
```

2024-06-13 10:07 UTC, db-cloudflare commented on content/workers/tutorials/handle-form-submission-with-astro-resend/index.md
> +After creating the `AstroForm` component, add it to your Astro app, just like any other component [component](https://docs.astro.build/en/basics/astro-components/).
I would also recommend showing the reader how to add/import the component to the app they have built. It's a simple step, but will save readers who are less familiar with software development having to click into more documentation to finish this tutorial.

2024-06-13 10:07 UTC, dbenCF commented on content/workers/tutorials/handle-form-submission-with-astro-resend/index.md
> +
The Resend setup could probably be a numbered step in itself to add clarity between creating the Astro endpoint and setting up the Resend functionality. Something such as 'Send emails using Resend' could work.

2024-06-14 16:31 UTC, CodyDubu commented on content/workers/tutorials/handle-form-submission-with-astro-resend/index.md
> +npm run astro add cloudflare
Yup, this has been fixed in the recent commit

2024-06-14 16:32 UTC, CodyDubu commented on content/workers/tutorials/handle-form-submission-with-astro-resend/index.md
> +
Thanks for all the suggestions! I have made the edits in the most recent commit.

2024-06-17 11:17 UTC, dbenCF commented
LGTM! Great work!

2024-06-17 11:17 UTC, dbenCF approved these changes

2024-06-17 13:04 UTC, dbenCF approved these changes

2024-06-17 15:12 UTC, merged