[queues] correct `DurableObject` to `DurableObjectNamespace` & remove constructor block
cloudflare/cloudflare-docs pull request #14529
Opened 2024-05-12 08:27 UTC by helloimalastair

In the `Env` declaration for the [Use Queues with Durable Objects](https://developers.cloudflare.com/queues/examples/use-queues-with-durable-objects/) example, the `YOUR_DO_CLASS` binding should be an instance of `DurableObjectNamespace` instead of `DurableObject`.

Constructor block for the `YourDurableObject` class contained an extra `}`, causing the `fetch()` to not be recognized. This block has been removed entirely, and the `env` been made `public` to match `state`

2024-05-12 08:59 UTC, garysassano commented
Thanks for the PR.

There's a small snag with the `fetch()` call. Because it's within an if statement, TypeScript needs a return statement outside the if to cover cases where the condition isn't met. Otherwise, it throws a `Function lacks ending return statement and return type does not include 'undefined'` error, as the function might not always return the expected `Promise<Response>`.

2024-05-12 12:25 UTC, helloimalastair commented
@garysassano should be fixed, now returns a 400

2024-05-13 11:13 UTC, Maddy-Cloudflare approved these changes

2024-05-13 15:52 UTC, Maddy-Cloudflare approved these changes

2024-05-14 11:53 UTC, Maddy-Cloudflare requested changes
Change the properties to be private.

2024-05-14 11:53 UTC, Maddy-Cloudflare commented on content/queues/examples/use-queues-with-durable-objects.md
> +  constructor(public state: DurableObjectState, public env: Env) {}
```suggestion
  constructor(private state: DurableObjectState, private env: Env) {}
```

2024-05-14 13:01 UTC, Maddy-Cloudflare approved these changes

2024-05-14 14:20 UTC, merged