Update small issues in TF tutorial docs
cloudflare/cloudflare-docs pull request #1453
Opened 2021-05-28 18:12 UTC by garrettgalow

list of fixes:
hello world
	1. fix provider setup
	2. fix ability to copy the initial config
	3. add instructions to create api token
source control
	1. fix sed replaces
	2. update head command
zone settings
	1. update var.domain to var.zone_id

2021-05-28 18:12 UTC, garrettgalow commented
this fixes internal ticket PCX-967

2021-06-01 16:04 UTC, deadlypants1973 commented on products/terraform/src/content/tutorial/hello-world.md
> -```sh
sh should be retained in ```sh

We follow this syntax in the docs because it makes text highlightable.

2021-06-01 16:06 UTC, deadlypants1973 requested changes
Need to retain sh after ```sh because this makes the text highlightable.

2021-06-01 17:23 UTC, deadlypants1973 commented on products/terraform/src/content/tutorial/hello-world.md
> +```
```suggestion
```sh
```

adding sh back in so that code in the docs remains highlightable.

2021-06-01 17:58 UTC, garrettgalow commented on products/terraform/src/content/tutorial/hello-world.md
> +```
sh blocks being able to copy all of the text window, since this is all input. The current docs have this issue. I think removing the SH will keep it as regular code block which will allow for copying the whole 'code' block.

2021-06-01 18:12 UTC, lukeed commented on products/terraform/src/content/tutorial/hello-world.md
> +```
I agree that it's unfortunate our syntax-highlighting kills text-highlighting (lol) and removes the ability to copy-paste the entire snippet. That said, i feel like it might be better to keep things consistent and then remove the `user-select: none` CSS from the docs-engine/site assets directly. Just my take, wdyt?

2021-06-01 18:13 UTC, lukeed commented on products/terraform/src/content/tutorial/hello-world.md
> +```
Specifically, this is the CSS that kills text selection (for `sh`, at least):

```css
[language=sh] .CodeBlock--token-plain, [language=sh] .CodeBlock--token-unselectable {
    -webkit-user-select: none; /** << THIS **/
    -ms-user-select: none; /** << THIS **/
    user-select: none; /** << THIS **/
    pointer-events: none;
    text-decoration: none;
    transition: opacity .25s ease;
}
```

2021-06-01 18:13 UTC, pedrosousa commented on products/terraform/src/content/tutorial/hello-world.md
> +```
When left empty, the default syntax highlighting is `javascript`... You probably want to use `bash` here, which allows readers to copy the text block. To disable syntax highlighting, use `txt`.

2021-06-01 18:26 UTC, lukeed commented on products/terraform/src/content/tutorial/hello-world.md
> +```
Ah ok cool, thanks for the clarification @pedrosousa – seems like `bash` would be the best bet here imo

2021-06-01 19:07 UTC, garrettgalow commented on products/terraform/src/content/tutorial/hello-world.md
> +```
yeah I didn't realize now keyword would default to js. That's not ideal. bash is probably right. let me test it locally to confirm and I'll update

2021-06-01 20:04 UTC, garrettgalow commented on products/terraform/src/content/tutorial/hello-world.md
> +```
updated it to `bash`. I checked locally and it allows for full text copying while having pretty good syntax highlighting.

2021-06-01 20:33 UTC, deadlypants1973 approved these changes

2021-06-01 21:22 UTC, merged