[SSL for SaaS] add using dashboard for SSL for SaaS and change string processing in uploading_certificates.md
cloudflare/cloudflare-docs pull request #1457
Opened 2021-05-31 10:23 UTC by zechu-cf

- Add docs for using the dashboard for SSL for SaaS.
- Shorten description of obtaining key and zone ID in ##Configure zone with proxy fallback origin since it's a repetition of ## API key and zone ID
- Fix certificate/private key string processing command in uploading-certificates.md . Previously it would cause the certificate to be unable to parse
- Other minor edits for clarity and consistency

2021-06-02 13:57 UTC, kodster28 requested changes

2021-06-02 13:57 UTC, kodster28 commented on products/ssl/src/content/ssl-for-saas/getting-started.md
> +2. Under the **DNS** tab on the dashboard, add a DNS record pointing to the origin IP address (fallback origin) for Cloudflare to send custom hostname traffic. This hostname is not provided to custom
```suggestion
1. Click **DNS**.
1. Add a DNS record pointing to the origin IP address (fallback origin) for Cloudflare to send custom hostname traffic. This hostname is not provided to customers.  Name the hostname according to your naming convention.  For example: `proxy-fallback.saasprovider.com`.
```

2021-06-02 13:57 UTC, kodster28 commented on products/ssl/src/content/ssl-for-saas/getting-started.md
>  3. Set up an additional DNS CNAME record to serve as the CNAME target for your end customers.  CNAME this record to your fallback origin, and use a more user-friendly CNAME target for customers.  Thi
```suggestion
3. Set up an additional DNS CNAME record to serve as the CNAME target for your end customers. CNAME this record to your fallback origin and use a more user-friendly CNAME target for customers. This record can optionally be a wildcard, e.g. `*.customers.saasprovider.com`.
```

2021-06-02 13:57 UTC, kodster28 commented on products/ssl/src/content/ssl-for-saas/getting-started.md
> +4. Upgrade your zone to an Enterprise plan, and contact your Customer Success Manager to enable SSL for SaaS Certificates.
```suggestion
4. Upgrade your zone to an Enterprise plan and contact your Customer Success Manager to enable **SSL for SaaS Certificates**.
```

2021-06-02 13:57 UTC, kodster28 commented on products/ssl/src/content/ssl-for-saas/getting-started.md
> +    * Via the dashboard: Go to **SSL/TLS** > **Custom Hostnames**, add your fallback origin defined in step 2 above and click **Add**.
```suggestion
    * Via the dashboard: Go to **SSL/TLS** > **Custom Hostnames**, add your fallback origin defined in step 2 above, and click **Add**.
```

2021-06-02 13:57 UTC, kodster28 commented on products/ssl/src/content/ssl-for-saas/getting-started.md
> +In this example, HTTP based validation is used ("method":"http") to issue this certificate. This requires HTTP traffic to be proxied through Cloudflare’s edge already, i.e., the CNAME from `app.custo
```suggestion
In this example, HTTP based validation is used ("method":"http") to issue this certificate. This requires HTTP traffic to be proxied through Cloudflare’s edge already, i.e., the CNAME from `app.customer.com` must be [in place for your zone](#setting-cname-at-customer-domain)). If the CNAME is not yet in place, Cloudflare will ask its CA partner to retry until the request can be completed; see the [Validation Backoff Schedule](/ssl-for-saas/validation-backoff-schedule/) for specific timings.
```

2021-06-02 13:57 UTC, kodster28 commented on products/ssl/src/content/ssl-for-saas/getting-started.md
> +1. Add your customer's hostname `app.customer.com` and set the relevant options. Click **Add Custom Hostname**.
```suggestion
1. Add your customer's hostname `app.customer.com` and set the relevant options. 
1. Click **Add Custom Hostname**.
```

2021-06-02 13:57 UTC, kodster28 commented on products/ssl/src/content/ssl-for-saas/getting-started.md
> +1. You will be brought back to the previous screen, which will show “Pending” before it changes to “Active” after a while. If you see an error stating “custom hostname does not CNAME to this zone”, y
Do we have anything more specific than `a while`? Like an upper bound on the time limit?

2021-06-02 13:57 UTC, kodster28 commented on products/ssl/src/content/ssl-for-saas/getting-started.md
> +Your customer needs to set up a CNAME record at their DNS provider, pointing to your CNAME target configured in step 3 [above](#configure-zone-with-proxy-fallback-origin). For example:
```suggestion
Your customer needs to set up a CNAME record at their DNS provider, pointing to your CNAME target configured in [a previous step](#configure-zone-with-proxy-fallback-origin). For example:
```

2021-06-02 13:57 UTC, kodster28 commented on products/ssl/src/content/ssl-for-saas/getting-started.md
> +The fallback origin is where the traffic of your Custom Hostnames will be routed to.  The fallback record is the value of the DNS record you set up via step 2 below.
```suggestion
The fallback origin is where the traffic of your Custom Hostnames will be routed to.  The fallback record is the value of the DNS record you set up via step 2.
```

2021-06-02 13:57 UTC, kodster28 commented on products/ssl/src/content/ssl-for-saas/index.md
> +Cloudflare [SSL for SaaS](https://www.cloudflare.com/saas/) extends the security and performance benefits of Cloudflare’s network to your customers via their own custom or “vanity” domains.  For exam
```suggestion
Cloudflare [SSL for SaaS](https://www.cloudflare.com/saas/) extends the security and performance benefits of Cloudflare’s network to your customers via their own custom or “vanity” domains.  For example, a customer may want to use their “vanity” domain `app.customer.com` to point to an application hosted on your Cloudflare zone `service.saas.com`. Issuing certificates requires minimal interaction from your customer to add a CNAME from their custom hostname to your domain.
```

2021-06-03 01:24 UTC, zechu-cf commented on products/ssl/src/content/ssl-for-saas/getting-started.md
> +1. You will be brought back to the previous screen, which will show “Pending” before it changes to “Active” after a while. If you see an error stating “custom hostname does not CNAME to this zone”, y
```suggestion
1. You will be brought back to the previous screen, which will show “Pending” before it changes to “Active” within 5 minutes. If you see an error stating “custom hostname does not CNAME to this zone”, you need to [set the DNS record at the customer's domain](#setting-cname-at-customer-domain).
```
I've changed it to within 5 minutes.

2021-06-03 13:15 UTC, kodster28 commented on products/ssl/src/content/ssl-for-saas/getting-started.md
> +The fallback origin is where the traffic of your Custom Hostnames will be routed to.  The fallback record is the value of the DNS record you set up via step 2.
```suggestion
The fallback origin is where the traffic of your Custom Hostnames will be routed to. The fallback record is the value of the DNS record you set up via step 2.
```

2021-06-03 13:16 UTC, kodster28 commented on products/ssl/src/content/ssl-for-saas/getting-started.md
> +1. Add a DNS record pointing to the origin IP address (fallback origin) for Cloudflare to send custom hostname traffic. This hostname is not provided to customers.  Name the hostname according to you
```suggestion
1. Add a DNS record pointing to the origin IP address (fallback origin) for Cloudflare to send custom hostname traffic. This hostname is not provided to customers. Name the hostname according to your naming convention. For example: `proxy-fallback.saasprovider.com`.
```

2021-06-03 13:16 UTC, kodster28 commented on products/ssl/src/content/ssl-for-saas/index.md
> +Cloudflare [SSL for SaaS](https://www.cloudflare.com/saas/) extends the security and performance benefits of Cloudflare’s network to your customers via their own custom or “vanity” domains.  For exam
```suggestion
Cloudflare [SSL for SaaS](https://www.cloudflare.com/saas/) extends the security and performance benefits of Cloudflare’s network to your customers via their own custom or “vanity” domains. For example, a customer may want to use their “vanity” domain `app.customer.com` to point to an application hosted on your Cloudflare zone `service.saas.com`. Issuing certificates requires minimal interaction from your customer to add a CNAME from their custom hostname to your domain.
```

2021-06-03 13:16 UTC, kodster28 approved these changes

2021-06-08 20:14 UTC, merged