Zaraz - Create Embeds.md
cloudflare/cloudflare-docs pull request #14578
Opened 2024-05-15 10:05 UTC by ad-astra-via

2024-05-15 11:00 UTC, jonnyparris approved these changes

2024-05-15 11:20 UTC, bjesus commented on content/zaraz/Embeds.md
> +# Embeds
the filename shouldn't start with a capital letter, and the file should start with the normal how-to template like other markdown files start with

2024-05-15 11:20 UTC, bjesus commented on content/zaraz/Embeds.md
> +## Cloudflare Zaraz's Server-Side Rendering for Embeds
no need for a second title

2024-05-15 11:21 UTC, bjesus requested changes
see comments

2024-07-02 15:11 UTC, bjesus approved these changes

2024-07-03 10:13 UTC, marciocloudflare approved these changes

2024-07-03 13:33 UTC, merged