Developer Spotlight - Custom access control for files in R2 using D1 and Workers
cloudflare/cloudflare-docs pull request #14618
Opened 2024-05-16 22:36 UTC by justDMNK

Hi everyone,

I just finished the tutorial called "Custom access control to images in R2 using D1 and Workers" which I proposed for the Developer Spotlight round. Just to address the possible confusion, I slightly adjusted the title to better reflect the content.

I tried to adhere and include the formatting guide as best as possible.
Please let me know if there is anything to be improved, thanks.

2024-05-31 12:35 UTC, megaconfidence commented on content/workers/tutorials/custom-access-control-for-files-in-R2-using-D1-and-Workers
> +4. Choose if you want to init a git repository for this new Worker project. For this tutorial, we will select `Not`, but feel free to choose Yes.
4. Decide if you want to initialize a git repository for this new Worker project. We will select "No" for this tutorial, but feel free to choose "Yes".
5. Choose "No" when asked if you want to deploy your application.

2024-05-31 12:55 UTC, megaconfidence commented
Hey @justDMNK thanks for working on this article. While it's in the middle of a technical review, can you fix the following?
1. Move the content into an `index.md` file and place in a folder i.e `custom-access-control-for-files-in-r2-using-d1-and-workers/` in the same directory?
2. Fix the formatting of the content. This is what it looks like today
<img width="1036" alt="image" src="https://github.com/cloudflare/cloudflare-docs/assets/17744578/a9e4a60b-7152-4dbf-914b-7eae1b90fadf">

Thanks!

2024-06-12 13:36 UTC, megaconfidence commented
Completed tech review. LGTM!

2024-06-13 08:23 UTC, dbenCF requested changes
I left a few suggestions for you to review. Brilliant work!

2024-06-13 08:23 UTC, db-cloudflare commented on content/workers/tutorials/custom-access-control-for-files-in-R2-using-D1-and-Workers/index.md
> +This tutorial gives you an overview on how to create a TypeScript-based Cloudflare Worker which allows you to control file access based on a simple username and password authentication, using a D1 da
```suggestion
This tutorial gives you an overview on how to create a TypeScript-based Cloudflare Worker which allows you to control file access based on a simple username and password authentication. To achieve this, we will use a D1 database for user management and an R2 bucket for file storage. 
```

2024-06-13 08:23 UTC, db-cloudflare commented on content/workers/tutorials/custom-access-control-for-files-in-R2-using-D1-and-Workers/index.md
> +Before you can start to modify the now created worker, you need to create a D1 database.
```suggestion
Now that you have created your Worker, next you will need to create a D1 database.
```

2024-06-13 08:23 UTC, db-cloudflare commented on content/workers/tutorials/custom-access-control-for-files-in-R2-using-D1-and-Workers/index.md
> +But be sure to replace `<YOUR_DATABASE_NAME>` with the name you want to you for your database. Keep in mind that this name can't be changed later on.
```suggestion
Replace `<YOUR_DATABASE_NAME>` with the name you want to you for your database. Keep in mind that this name can't be changed later on.
```

2024-06-13 08:23 UTC, db-cloudflare commented on content/workers/tutorials/custom-access-control-for-files-in-R2-using-D1-and-Workers/index.md
> +To use the database in your worker, you will need to add the binding to your `wrangler.toml` file, by copying the declaration and pasting it into the wrangler file.
I'd say it's worth including an example of what the binding for this would look like in the wrangler.toml file in the same way you gave an example of the R2 binding for step 3. Below is an example.

[[d1_databases]]
binding = "DB" 
database_name = "<YOUR_DATABASE_NAME>"
database_id = "<YOUR_DATABASE_ID>"

2024-06-13 08:23 UTC, db-cloudflare commented on content/workers/tutorials/custom-access-control-for-files-in-R2-using-D1-and-Workers/index.md
> +binding = 'BUCKET'
```suggestion
binding = "BUCKET"
```

2024-06-13 08:23 UTC, db-cloudflare commented on content/workers/tutorials/custom-access-control-for-files-in-R2-using-D1-and-Workers/index.md
> +bucket_name = '<YOUR_BUCKET_NAME>'
Single quotes and double quotes both work, just changing for consistency with the wrangler.toml skeleton generated by C3
```suggestion
bucket_name = "<YOUR_BUCKET_NAME>"
```

2024-06-13 08:23 UTC, db-cloudflare commented on content/workers/tutorials/custom-access-control-for-files-in-R2-using-D1-and-Workers/index.md
> +As this operation only needs to be done once, this will be done through the Wrangler CLI and not in the Workers code.
```suggestion
As this operation only needs to be done once, this will be done through the Wrangler CLI and not in the Worker's code.
```

2024-06-13 08:23 UTC, db-cloudflare commented on content/workers/tutorials/custom-access-control-for-files-in-R2-using-D1-and-Workers/index.md
> +The first thing you will need to do is to implemen the authentication for the requests.
```suggestion
The first thing you will need to do is to implement the authentication for the requests.
```

2024-06-13 08:23 UTC, db-cloudflare commented on content/workers/tutorials/custom-access-control-for-files-in-R2-using-D1-and-Workers/index.md
> +But this time you will need to add the binding to your wrangler file manually.
```suggestion
```

2024-06-13 08:23 UTC, db-cloudflare commented on content/workers/tutorials/custom-access-control-for-files-in-R2-using-D1-and-Workers/index.md
> +The requests will contain, the username and password as a base64 encoded string, which is also called Basic Authentication.
```suggestion
The requests will contain the username and password as a base64 encoded string, which is also called Basic Authentication.
```

2024-06-13 08:23 UTC, db-cloudflare commented on content/workers/tutorials/custom-access-control-for-files-in-R2-using-D1-and-Workers/index.md
> +Now that you prepared the wrangler configuration, you should update the `worker-configuration.d.ts` file to include the new bindings.
It might be also worth describing why this should be done, so that the reader understands what updating the `worker-configuration.d.ts` file does for a typescript app.
```suggestion
Now that you have prepared the Wrangler configuration, you should update the `worker-configuration.d.ts` file to include the new bindings.
```

2024-06-13 08:23 UTC, db-cloudflare commented on content/workers/tutorials/custom-access-control-for-files-in-R2-using-D1-and-Workers/index.md
> +If the username and password are correct, you will retrieve a record, otherwise the response will be empty, and you should return a `401 Unauthorized` response.
```suggestion
If the username and password are correct, you will retrieve a record. If the username or password are incorrect, the response will only contain a `401 Unauthorized` message.
```

2024-06-13 08:23 UTC, db-cloudflare commented on content/workers/tutorials/custom-access-control-for-files-in-R2-using-D1-and-Workers/index.md
> +To handle the authentication, you will need to replace the current code within `old.ts` file with the following code:
Is this supposed to be `index.ts`?
```suggestion
To handle the authentication, you will need to replace the current code within `index.ts` file with the following code:
```

2024-06-13 08:23 UTC, db-cloudflare commented on content/workers/tutorials/custom-access-control-for-files-in-R2-using-D1-and-Workers/index.md
> +3. [`Node.js`](https://nodejs.org/en/) with version `16.17.0` or later
```suggestion
- A Cloudflare account
- [`npm`](https://docs.npmjs.com/getting-started)
- [`Node.js`](https://nodejs.org/en/) with version `16.17.0` or later
```

2024-06-13 08:23 UTC, db-cloudflare commented on content/workers/tutorials/custom-access-control-for-files-in-R2-using-D1-and-Workers/index.md
> +3. insert a test user into the table, so you can test your code later on
```suggestion
1. Create a table in the database which will then be used to store the user data 
2. Create a unique index on the username column, which will speed up database queries and ensure that the username is unique
3. Insert a test user into the table, so you can test your code later on
```

2024-06-13 19:25 UTC, justDMNK commented on content/workers/tutorials/custom-access-control-for-files-in-R2-using-D1-and-Workers/index.md
> +If the username and password are correct, you will retrieve a record, otherwise the response will be empty, and you should return a `401 Unauthorized` response.
I've changed your suggestion slightly to highlight that the returned value from the database is undefined. This is to clarify the difference between the function return and the request response. 

The updated version is as follows, please let me know your thoughts.
"If the username and password are correct, you will retrieve a record from D1. If the username or password is incorrect, undefined will be returned and a `401 Unauthorized` response will be send."

2024-06-13 19:25 UTC, justDMNK commented on content/workers/tutorials/custom-access-control-for-files-in-R2-using-D1-and-Workers/index.md
> +Now that you prepared the wrangler configuration, you should update the `worker-configuration.d.ts` file to include the new bindings.
A small explainer was added

2024-06-13 19:31 UTC, justDMNK commented
Hi @dbenCF, 

thank you for the nice words and your feedback, I appreciate it.
I've applied most of your suggestions directly, but for one of the changes I've adjusted it slightly to clarify the wording.
Please let me know if you have any additional feedback.

2024-06-14 08:47 UTC, dbenCF commented on content/workers/tutorials/custom-access-control-for-files-in-R2-using-D1-and-Workers/index.md
> +If the username and password are correct, you will retrieve a record from D1. If the username or password is incorrect, undefined will be returned and a `401 Unauthorized` response will be send.
```suggestion
If the username and password are correct, you will retrieve a record from D1. If the username or password is incorrect, undefined will be returned and a `401 Unauthorized` response will be sent.
```

2024-06-14 08:49 UTC, dbenCF commented
Looks great! One last small thing to change and then it's ready to publish.

2024-06-14 09:28 UTC, dbenCF approved these changes

2024-06-14 11:49 UTC, KianNH commented on content/workers/tutorials/custom-access-control-for-files-in-R2-using-D1-and-Workers/index.md
> +				authBase64 = new URL(request.url).searchParams.get('Authorization');
```suggestion
				authBase64 = url.searchParams.get('Authorization');
```

It looks like this can use the URL you created on L142.

2024-06-14 11:49 UTC, KianNH commented on content/workers/tutorials/custom-access-control-for-files-in-R2-using-D1-and-Workers/index.md
> +	return new Response(await file.blob());
```suggestion
  const headers = new Headers();
  file.writeHttpMetadata(headers);
	return new Response(file.body, { headers });
```

2024-06-14 11:49 UTC, KianNH commented on content/workers/tutorials/custom-access-control-for-files-in-R2-using-D1-and-Workers/index.md
> +    await env.BUCKET.put(`${user.id}/${url.pathname}`, file);
We can pass the request body stream straight to R2 to avoid buffering.

```suggestion
	// Upload the file to the R2 bucket with the user id followed by a slash as the prefix and then the path of the URL
    await env.BUCKET.put(`${user.id}/${url.pathname}`, request.body);
```

2024-06-14 15:26 UTC, dbenCF requested changes
I think GitGuardian is alerting a false positive, I made two suggestions that should help clear that.

2024-06-14 15:26 UTC, dbenCF commented on content/workers/tutorials/custom-access-control-for-files-in-R2-using-D1-and-Workers/index.md
> +--header 'Authorization: Basic YWRtaW46cGFzc3dvcmQ=' \
```suggestion
--header 'Authorization: Basic <API_CREDENTIALS>' \
```

2024-06-14 15:26 UTC, dbenCF commented on content/workers/tutorials/custom-access-control-for-files-in-R2-using-D1-and-Workers/index.md
> +$ npx wrangler d1 execute <YOUR_DATABASE_NAME> --command "INSERT INTO user (username, password) VALUES ('admin', '5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8')"  --remote
```suggestion
$ npx wrangler d1 execute <YOUR_DATABASE_NAME> --command "INSERT INTO user (username, password) VALUES ('<YOUR_USERNAME>', '<YOUR_PASSWORD>')"  --remote
```

2024-06-14 15:27 UTC, db-cloudflare commented on content/workers/tutorials/custom-access-control-for-files-in-R2-using-D1-and-Workers/index.md
> +--header 'Authorization: Basic YWRtaW46cGFzc3dvcmQ=' \
Let me know if `Basic` should be kept here or not

2024-06-14 17:49 UTC, justDMNK commented
> I think GitGuardian is alerting a false positive, I made two suggestions that should help clear that.

I replaced the two demo secrets with placeholders and then added them as values to use within the text. But I think the GitGuardian is checking every commit and not just the newest one, as the check details still show that the secrets were detected within my first commit. Should I open a new pull request with a clean history?

2024-06-17 08:13 UTC, dbenCF commented
> > I think GitGuardian is alerting a false positive, I made two suggestions that should help clear that.
> 
> I replaced the two demo secrets with placeholders and then added them as values to use within the text. But I think the GitGuardian is checking every commit and not just the newest one, as the check details still show that the secrets were detected within my first commit. Should I open a new pull request with a clean history?



> > I think GitGuardian is alerting a false positive, I made two suggestions that should help clear that.
> 
> I replaced the two demo secrets with placeholders and then added them as values to use within the text. But I think the GitGuardian is checking every commit and not just the newest one, as the check details still show that the secrets were detected within my first commit. Should I open a new pull request with a clean history?

Opening a new PR might be the easiest thing to do unfortunately. Apologies for the inconvenience.

2024-06-17 12:17 UTC, justDMNK commented
> > > I think GitGuardian is alerting a false positive, I made two suggestions that should help clear that.
> > 
> > 
> > I replaced the two demo secrets with placeholders and then added them as values to use within the text. But I think the GitGuardian is checking every commit and not just the newest one, as the check details still show that the secrets were detected within my first commit. Should I open a new pull request with a clean history?
> 
> Opening a new PR might be the easiest thing to do unfortunately. Apologies for the inconvenience.

No worries, I just created another pull request (#15123), which did indeed pass the GitGuardian checks :)

2024-06-17 14:11 UTC, dbenCF commented
Closed, duplicate can be found here https://github.com/cloudflare/cloudflare-docs/pull/15123

2024-06-17 14:11 UTC, closed without merging