[DO] Removes guide to get a paid plan
cloudflare/cloudflare-docs pull request #14649
Opened 2024-05-20 14:23 UTC by megaconfidence

Durable Objects no longer require a paid plan to get started. This PR updates the docs accordingly.

2024-05-20 14:31 UTC, vy-ton commented
@megaconfidence This is not yet true today. We plan to have a Durable Objects free tier later this year.

2024-05-20 14:35 UTC, kodster28 approved these changes

2024-05-20 14:36 UTC, kodster28 requested changes
blocking any merge

2024-05-21 09:32 UTC, megaconfidence commented
@vy-ton I have access to DO on my free personal account

2024-05-23 16:18 UTC, closed without merging