Adding a note to recommend Simply Static instead of WP2Static
cloudflare/cloudflare-docs pull request #1465
Opened 2021-06-01 15:45 UTC by deadlypants1973

Issue: https://github.com/cloudflare/cloudflare-docs/issues/407

2021-06-01 15:50 UTC, signalnerve approved these changes

2021-06-01 16:05 UTC, lukeed commented on products/workers/src/content/tutorials/deploy-a-static-wordpress-site/index.md
> +\* __Warning:__ This tutorial is outdated. As of August 2020, the WP2Static plugin is no longer available. For a free alternative to [WP2Static](https://wordpress.org/plugins/static-html-output-plugi
Is the `\*` significant?

2021-06-01 16:24 UTC, kodster28 requested changes
Content looks good, but to avoid the formatting issue, you might want to just add the `header` attribute to the Aside.
https://developers.cloudflare.com/docs-engine/reference/markdown#asides

![image](https://user-images.githubusercontent.com/26727299/120358329-fcc74700-c2cb-11eb-9978-ce01466f2cef.png)

2021-06-01 16:28 UTC, kodster28 approved these changes

2021-06-01 16:29 UTC, deadlypants1973 commented on products/workers/src/content/tutorials/deploy-a-static-wordpress-site/index.md
> +\* __Warning:__ This tutorial is outdated. As of August 2020, the WP2Static plugin is no longer available. For a free alternative to [WP2Static](https://wordpress.org/plugins/static-html-output-plugi
@lukeed I copied this from another aside that exist in the Workers' docs. I kept it for consistency.

2021-06-01 16:32 UTC, deadlypants1973 commented on products/workers/src/content/tutorials/deploy-a-static-wordpress-site/index.md
> +\* __Warning:__ This tutorial is outdated. As of August 2020, the WP2Static plugin is no longer available. For a free alternative to [WP2Static](https://wordpress.org/plugins/static-html-output-plugi
Actually, I am going to change this to:

<Aside type="warning" header="Warning">

This tutorial is outdated. As of August 2020, the WP2Static plugin is no longer available. For a free alternative to [WP2Static](https://wordpress.org/plugins/static-html-output-plugin/), try [Simply Static](https://wordpress.org/plugins/simply-static/). 

</Aside>

because the header looks better, as Kody mentioned.

2021-06-01 20:37 UTC, lukeed approved these changes

2021-06-02 19:01 UTC, merged

2021-06-04 21:36 UTC, leonstafford commented
https://github.com/cloudflare/cloudflare-docs/issues/407#issuecomment-855000171