Calls documentation updates - 2024-05-22
cloudflare/cloudflare-docs pull request #14700
Opened 2024-05-22 18:01 UTC by renandincer

2024-05-22 20:01 UTC, kodster28 requested changes
Heyo @renandincer, generally we don't include openapi specs in our docs.

Is there a reason that these aren't just references out to https://developers.cloudflare.com/api/operations/calls-apps-list and the other API endpoints?

2024-05-22 20:03 UTC, third774 commented on content/calls/turn/custom-domains.md
> +Cloudflare Calls TURN service supports using custom domains. Custom domains do not affect any of of the performance characteristics of Cloudflare Calls TURN.
Ah, very cool bot! 🙏🏻

2024-05-22 22:57 UTC, renandincer commented
@kodster28 this is not a Cloudflare API at api.cloudflare.com. This is a product specific API with a different endpoint. They are not related.

2024-05-23 11:57 UTC, kodster28 commented
> @kodster28 good question! This is not a Cloudflare API at api.cloudflare.com. This is a product specific API with a different endpoint. They are not related.

Oh... interesting. Gotcha, let me unblock then.

Assuming y'all have a process for updating this when the API changes?

2024-05-23 12:00 UTC, kodster28 commented on content/calls/datachannels.md
> +# Datachannels
Assuming this page is still in progress?

2024-05-23 12:00 UTC, kodster28 commented on content/calls/turn/custom-domains.md
> +Cloudflare Calls TURN service supports using custom domains. Custom domains do not affect any of of the performance characteristics of Cloudflare Calls TURN.
```suggestion
Cloudflare Calls TURN service supports using custom domains. Custom domains do not affect any of the performance characteristics of Cloudflare Calls TURN.
```

2024-05-23 12:00 UTC, kodster28 commented on content/calls/turn/custom-domains.md
> +Any DNS provider, including Cloudflare DNS can be used to set up a CNAME for custom domains. If Cloudflare's DNS is used, the record must be set to ["grey cloud" mode](https://developers.cloudflare.c
```suggestion
Any DNS provider, including Cloudflare DNS can be used to set up a CNAME for custom domains. If Cloudflare's DNS is used, the record must be [DNS-only](/dns/manage-dns-records/reference/proxied-dns-records/#dns-only-records).
```

2024-05-23 12:00 UTC, kodster28 commented on content/calls/turn/faq.md
> +### What is Cloudflare Calls TURN pricing? How exactly is it calculated?
skipped header level

2024-05-23 12:00 UTC, kodster28 commented on content/calls/turn/for-turn-providers.md
> +If you are a existing TURN provider but would like to switch to providing Cloudflare Calls TURN for your customers, there is a few considerations.
Feels like there should be more here?

2024-05-23 12:42 UTC, renandincer commented on content/calls/turn/faq.md
> +### What is Cloudflare Calls TURN pricing? How exactly is it calculated?
Yep it's intensional, it's a FAQ and a in between header did not make sense to me. Do you have other styling suggestion for FAQ style?

2024-05-23 12:43 UTC, renandincer commented
> > @kodster28 good question! This is not a Cloudflare API at api.cloudflare.com. This is a product specific API with a different endpoint. They are not related.
> 
> Oh... interesting. Gotcha, let me unblock then.
> 
> Assuming y'all have a process for updating this when the API changes?

Yes, this _is_ the source of truth now.

2024-05-23 12:45 UTC, renandincer commented
@kodster28 I set `pcx_content_type: get-started` in the markdown header each time, but don't know what it does. Do you have any insight into what this is for?

2024-05-24 12:43 UTC, kodster28 commented
> @kodster28 I set `pcx_content_type: get-started` in the markdown header each time, but don't know what it does. Do you have any insight into what this is for?

Metadata that we add to the rendered page. It helps us group by the type of content for reporting, etc.
Full list of options + values at https://developers.cloudflare.com/style-guide/documentation-content-strategy/content-types/

2024-05-24 16:23 UTC, kodster28 approved these changes
Added a few other comments / suggestions

2024-05-24 16:23 UTC, kodster28 commented on content/calls/turn/faq.md
> +The Cloudflare Calls credential generation function returns a JSON structure similar to the [expired RFC draft "draft-uberti-behave-turn-rest-00"](https://datatracker.ietf.org/doc/html/draft-uberti-b
I'd suggest reframing each of these to clearly answer the question in the first sentence.

i.e., if it's `Does TURN support...`, should start with a `Yes` or `No`. It's present in some answers but not in others.

2024-05-24 16:23 UTC, kodster28 commented on content/calls/turn/generate-credentials.md
> +```sh
```suggestion
```bash
```

2024-05-24 16:23 UTC, kodster28 commented on content/calls/turn/generate-credentials.md
> +```sh
```suggestion
```bash
```

2024-05-24 16:23 UTC, kodster28 commented on content/calls/turn/faq.md
> +Pricing for Cloudflare Calls Serverless SFU and TURN services is $0.05 per GB of data used.
You may want to standardize the pricing / limits info on a separate page.

Sorta stuff that gets very tangled / hard to update if it doesn't live in a centralized place (saw it in a few other locations).

2024-05-24 16:25 UTC, renandincer commented on content/calls/turn/faq.md
> +Pricing for Cloudflare Calls Serverless SFU and TURN services is $0.05 per GB of data used.
Makes sense.

2024-05-24 16:31 UTC, merged