[D1] Minor improvements
cloudflare/cloudflare-docs pull request #14812
Opened 2024-05-29 12:15 UTC by harshil1712

Also, addresses #14579

2024-05-29 12:50 UTC, elithrar commented on content/d1/build-with-d1/import-data.md
> +`_cf_KV` is an unused internal table. You don't have to access to it from D1.
```suggestion
The `_cf_KV` table is a reserved table used by D1's underlying storage system. It cannot be queried and does not incur read/write operations charges against your account.
```

2024-05-29 12:52 UTC, elithrar commented on content/d1/reference/generated-columns.md
> +-- calculates a date (YYYY-MM-dd) 30 days from the timestamp.
Where is `timestamp` defined here? The change here makes this invalid. `timestamp` would need to be a column name.

2024-05-29 12:53 UTC, elithrar requested changes
See comments.

2024-05-29 12:54 UTC, elithrar commented on content/d1/build-with-d1/remote-development.md
> +1. On the top of the page, select **Edit Code**.
Which page and where?

2024-05-29 12:55 UTC, elithrar commented on content/d1/build-with-d1/remote-development.md
I think this being called "Remote development" (esp. vs. "Local development") is confusing.

This should be probably be renamed / folded into a new "Get started" guide - e.g. "Get Started - Command Line" and "Get started - Dashboard" as two paths.

2024-05-29 12:55 UTC, elithrar commented on content/d1/build-with-d1/import-data.md
> +$ wrangler d1 execute example-db --remote --command "SELECT name FROM sqlite_schema WHERE type='table' ORDER BY name;"
If this is changed then the rest of the doc needs to be changed too.

2024-05-29 12:55 UTC, elithrar commented on content/d1/build-with-d1/import-data.md
>  To confirm your table was imported correctly and is queryable, execute a `SELECT` statement against your `users` table directly:
e.g. `users` is now outdated (per below comment)

2024-05-29 12:56 UTC, harshil1712 commented on content/d1/reference/generated-columns.md
> +-- calculates a date (YYYY-MM-dd) 30 days from the timestamp.
This example references the previous example, where the user creates a table with column `timestamp`

2024-05-29 12:56 UTC, elithrar commented on content/d1/build-with-d1/import-data.md
If we're going to rename this page, we should update the URL (and redirect it) and the header:

<img width="693" alt="image" src="https://github.com/cloudflare/cloudflare-docs/assets/18544/b12be2f2-bf72-4f47-b4eb-cc54c16bb1b6">

2024-05-29 13:10 UTC, rozenmd commented on content/d1/build-with-d1/import-data.md
> +The `_cf_KV` table is a reserved table used by D1's underlying storage system. It cannot be queried and does not incur read/write operations charges against your account.
might be worth mentioning that on alpha dbs it was called `d1_kv`

2024-05-29 13:55 UTC, harshil1712 commented on content/d1/build-with-d1/remote-development.md
Agree. I already have this in my ToDo. Since this is a structural change, I need help from PCX. I'll pick it up soon.

2024-05-29 14:22 UTC, harshil1712 commented on content/d1/build-with-d1/import-data.md
Made the changes.

2024-05-29 14:22 UTC, harshil1712 commented on content/d1/build-with-d1/import-data.md
>  To confirm your table was imported correctly and is queryable, execute a `SELECT` statement against your `users` table directly:
Fixed.

2024-05-30 09:17 UTC, Maddy-Cloudflare approved these changes

2024-05-30 09:22 UTC, Maddy-Cloudflare approved these changes

2024-05-30 09:22 UTC, Maddy-Cloudflare commented on content/d1/build-with-d1/import-export-data.md
> +# Import and Export data
```suggestion
# Import and export data
```

2024-05-30 09:22 UTC, Maddy-Cloudflare commented on content/d1/build-with-d1/import-export-data.md
> +D1 also allows you to export a database. This can be useful for local development or testing.
```suggestion
D1 also allows you to export a database. This can be useful for [local development](/d1/build-with-d1/local-development/) or testing.
```

2024-05-30 09:22 UTC, Maddy-Cloudflare commented on content/d1/build-with-d1/import-export-data.md
> +
```suggestion
```

2024-05-30 09:22 UTC, Maddy-Cloudflare commented on content/d1/build-with-d1/remote-development.md
> +1. On worker's page on the Cloudflare dashboard, select **Edit Code** from the top of the page.
```suggestion
1. On the Worker's page on the Cloudflare dashboard, select **Edit Code** at the top of the page.
```

2024-06-03 10:35 UTC, harshil1712 commented
@elithrar, made the suggested changes. Can you approve the changes, if all looks good?

2024-06-10 13:48 UTC, elithrar approved these changes

2024-06-13 09:13 UTC, merged