[Access for SaaS] Jamf Pro and Slack tutorials
cloudflare/cloudflare-docs pull request #15042
Opened 2024-06-11 14:42 UTC by chcyrier

PCX - 8163
PCX - 10968

2024-06-11 19:53 UTC, patriciasantaana commented on content/cloudflare-one/applications/configure-apps/saas-apps/slack-saas.md
> +
```suggestion
```

2024-06-11 19:53 UTC, patriciasantaana commented on content/cloudflare-one/applications/configure-apps/saas-apps/slack-saas.md
> +
```suggestion
```

2024-06-12 09:25 UTC, marciocloudflare requested changes

2024-06-12 09:25 UTC, marciocloudflare commented on content/cloudflare-one/applications/configure-apps/saas-apps/jamf-pro-saas.md
> +4. Open the `metadata.xml` file in a text editor and copy the values for **Entity ID** and **Assertion Consumer Service**.
```suggestion
4. Open the `metadata.xml` file in a text editor, and copy the values for **Entity ID** and **Assertion Consumer Service**.
```

2024-06-12 09:25 UTC, marciocloudflare commented on content/cloudflare-one/applications/configure-apps/saas-apps/jamf-pro-saas.md
> +    - **Identity Provider Metadata Source**: SSO endpoint from application configuration in Cloudflare Zero Trust with `/saml-metadata` appended.
So, customers would have to add `<YOUR_SSO_ENDPOINT>/saml-metadata`? I think an example at the end like the one I wrote (if correct) would be useful to clear any questions about how to enter this.

2024-06-12 09:25 UTC, marciocloudflare commented on content/cloudflare-one/applications/configure-apps/saas-apps/jamf-pro-saas.md
> +5. In the top right, turn on **Single Sign On**.
```suggestion
5. Turn on **Single Sign On**.
```

2024-06-12 09:25 UTC, marciocloudflare commented on content/cloudflare-one/applications/configure-apps/saas-apps/jamf-pro-saas.md
> +5. In the top right, turn on **Single Sign On**.
We avoid giving instructions like this unless completely necessary (because it would otherwise be too hard to find). Interfaces tend to change, and then the instructions would be rendered outdated if it changed from top right to top left, for example.

2024-06-12 09:25 UTC, marciocloudflare commented on content/cloudflare-one/applications/configure-apps/saas-apps/jamf-pro-saas.md
> +2. Select **SaaS**.
```suggestion
2. Select **Add an application** > **SaaS** > **Select**.
```

2024-06-12 09:25 UTC, marciocloudflare commented on content/cloudflare-one/applications/configure-apps/saas-apps/slack-saas.md
> +2. Select **SaaS**.
```suggestion
2. Select **Add an application** > **SaaS** > **Select**.
```

2024-06-12 09:25 UTC, marciocloudflare commented on content/cloudflare-one/applications/configure-apps/saas-apps/slack-saas.md
> +    - **Assertion Consumer Service URL**: `https://<yourdomain>.slack.com/sso/saml`
```suggestion
    - **Assertion Consumer Service URL**: `https://<YOUR_DOMAIN>.slack.com/sso/saml`
```

2024-06-12 09:25 UTC, marciocloudflare commented on content/cloudflare-one/applications/configure-apps/saas-apps/slack-saas.md
> +3. In the top right, turn **Test mode** on. Configuration changes will not apply until **Configuration** is turned on.
```suggestion
3. Enable **Test mode**. Configuration changes will not apply until **Configuration** is turned on.
```

2024-06-12 09:25 UTC, marciocloudflare commented on content/cloudflare-one/applications/configure-apps/saas-apps/slack-saas.md
> +    - **Public Certificate**: Copy the entire x.509 certificate from [2. Create a x.509 certificate](#2-create-a-x.509-certificate).
```suggestion
    - **Public Certificate**: Copy the entire x.509 certificate from step [2. Create a x.509 certificate](#2-create-a-x.509-certificate).
```

2024-06-12 09:25 UTC, marciocloudflare commented on content/cloudflare-one/applications/configure-apps/saas-apps/slack-saas.md
> +6. (Optional) Under **Customize**, enter a Sign in Button Label.
Is `Sign in Button Label` an option? If so, it should be probably bold - depends on what type of action customers are supposed to do here

2024-06-12 09:25 UTC, marciocloudflare commented on content/cloudflare-one/applications/configure-apps/saas-apps/slack-saas.md
> +7. Test your set-up. If all works well, turn **Test** to **Configure**.
```suggestion
7. Test your set-up. If all works well, change **Test mode** to **Configure mode**.
```

2024-06-12 09:25 UTC, marciocloudflare commented on content/cloudflare-one/applications/configure-apps/saas-apps/slack-saas.md
> +7. Test your set-up. If all works well, turn **Test** to **Configure**.
Above, you said to customers had to turn `Test mode` on. I'm assuming you're missing `mode` here as well?

2024-06-12 09:25 UTC, marciocloudflare commented on content/cloudflare-one/applications/configure-apps/saas-apps/slack-saas.md
> +    - **Public Certificate**: Copy the entire x.509 certificate from [2. Create a x.509 certificate](#2-create-a-x.509-certificate).
```suggestion
    - **Public Certificate**: Copy the entire x.509 certificate from step [2. Create a x.509 certificate](#2-create-a-x.509-certificate).
```

2024-06-12 13:21 UTC, marciocloudflare approved these changes

2024-06-13 20:12 UTC, merged