[Workers AI, Vectorize] Add a new tutorial about building product recommendation API
cloudflare/cloudflare-docs pull request #15055
Opened 2024-06-12 01:09 UTC by hideokamoto-stripe

Here is a part of the content of Cloudflare Developer Spotlight program. We're going to introduce the use case based tutorial using Cloudflare AI stacks ( Workers AI and Vectorize ).

If you have any question, feedback, or concern, please feel free let us know.

Thanks.

2024-06-14 05:46 UTC, yusukebe commented on content/workers-ai/tutorials/creating-a-recommendation-api.md
> +```diff
You can use a `highlight` feature instead of the `diff` like the following:

```markdown
```ts
---
filename: src/index.ts
highlight: [3, 4, 5, 6, 7, 8, 9]
---
if (event.type === 'product.created') {
  const product = event.data.object
  const productData = [
    `## ${product.name}`,
    product.description,
    '### metadata',
    Object.entries(product.metadata).map(([key, value]) => `- ${key}: ${value}`).join('\n')
  ].join('\n')
  console.log(productData)
}
```

In this way, you can highlight the specified part while keeping the TypeScript syntax highlighting. I think you should use a highlight for other places for the same purpose, where include the `wrangler.toml`.

2024-06-14 05:46 UTC, yusukebe commented on content/workers-ai/tutorials/creating-a-recommendation-api.md
> +
This line should be removed.

2024-06-14 05:46 UTC, yusukebe commented on content/workers-ai/tutorials/creating-a-recommendation-api.md
> +      console.log(product)
To dump and format it properly, the below would be better.

```ts
console.log(JSON.stringify(product, undefined, 2))
```

2024-06-14 05:46 UTC, yusukebe commented on content/workers-ai/tutorials/creating-a-recommendation-api.md
> +curl http://localhost:8787/products/prod_xxxx
Add `$` at the first.

```markdown
$ curl http://localhost:8787/products/prod_xxxx
```

2024-06-14 05:46 UTC, yusukebe commented on content/workers-ai/tutorials/creating-a-recommendation-api.md
> +npx wrangler vectorize create stripe-products --dimensions=1024 --metric=cosine
Add `$` at the first.

```markdown
$ npx wrangler vectorize create stripe-products --dimensions=1024 --metric=cosine
```

2024-06-14 05:46 UTC, yusukebe commented on content/workers-ai/tutorials/creating-a-recommendation-api.md
> +```sh
With `sh`, we can copy the all lines:

https://github.com/cloudflare/cloudflare-docs/assets/10682/a427a87b-c688-44fd-b26c-5105c2dd0b15

So, how about using another format like a `bash`?

https://github.com/cloudflare/cloudflare-docs/assets/10682/a9b7e0d5-5d1d-4003-8277-c7384a499abf

2024-06-14 05:49 UTC, yusukebe commented
Hey @hideokamoto-stripe !

This is a great tutorial for Hono and Cloudflare AI stacks! I tried it and it works very well. I've left comments about formatting. Can you check them?

2024-06-16 07:32 UTC, hideokamoto-stripe commented
Thank you @yusukebe for reviewing my content!
I've updated this tutorial today.

Please check the diff that I fixed related to the format issues.
Thanks

2024-06-17 03:34 UTC, yusukebe approved these changes
LGTM!

2024-06-18 12:28 UTC, dbenCF requested changes
Absolutely amazing work! I left some suggestions for your review, let me know what you think of them.

2024-06-18 12:28 UTC, db-cloudflare commented on content/workers-ai/tutorials/creating-a-recommendation-api.md
> +# Creating a recommendation system for an e-commerce site using Cloudflare's AI services
```suggestion
# Recommend products on e-commerce sites using Workers AI and Stripe
```

2024-06-18 12:28 UTC, db-cloudflare commented on content/workers-ai/tutorials/creating-a-recommendation-api.md
> +title: Creating a recommendation system for an e-commerce site using Cloudflare's AI services
Adding Workers AI and Stripe to the title should help SEO
```suggestion
title: Recommend products on e-commerce sites using Workers AI and Stripe
```

2024-06-18 12:28 UTC, db-cloudflare commented on content/workers-ai/tutorials/creating-a-recommendation-api.md
> +To efficiently create and manage multiple APIs, let's use [`Hono`](https://hono.dev). [`Hono`](https://hono.dev) is an open-source application framework released by a Cloudflare Developer Advocate. I
The first link should suffice here.
```suggestion
To efficiently create and manage multiple APIs, let's use [`Hono`](https://hono.dev). Hono is an open-source application framework released by a Cloudflare Developer Advocate. It is lightweight and allows for the creation of multiple API paths, as well as efficient request and response handling.
```

2024-06-18 12:28 UTC, db-cloudflare commented on content/workers-ai/tutorials/creating-a-recommendation-api.md
> +create-cloudflare@2.21.6
```suggestion
create-cloudflare@latest
```

2024-06-18 12:28 UTC, db-cloudflare commented on content/workers-ai/tutorials/creating-a-recommendation-api.md
> +Cloudflare Workers applications can be developed and tested in a local environment. Run `npm run dev` to start the application. Using `Wrangler`, the application will start, and you'll see a URL begi
Changing `npm run dev` to `npx wrangler dev` for consistency with the [Workers get started guide](https://developers.cloudflare.com/workers/get-started/guide/). Let me know if this is okay.
```suggestion
Cloudflare Workers applications can be developed and tested in a local environment. On your CLI, change directory into your newly created Workers and run `npx wrangler dev` to start the application. Using `Wrangler`, the application will start, and you'll see a URL beginning with `localhost`.
```

2024-06-18 12:28 UTC, db-cloudflare commented on content/workers-ai/tutorials/creating-a-recommendation-api.md
> +> wrangler dev
```suggestion
```

2024-06-18 12:28 UTC, db-cloudflare commented on content/workers-ai/tutorials/creating-a-recommendation-api.md
> +When this command executes successfully, you will see a message like the following. It provides the items you need to add to `wrangler.toml`. Copy the three lines starting with `[[vectorize]]`.
```suggestion
When this command executes successfully, you will see a message like the following. It provides the items you need to add to `wrangler.toml` to bind the Vectorize index with your Worker application. Copy the three lines starting with `[[vectorize]]`.
```

2024-06-18 12:28 UTC, db-cloudflare commented on content/workers-ai/tutorials/creating-a-recommendation-api.md
> +```js
```suggestion
```ts
```

2024-06-18 12:28 UTC, db-cloudflare commented on content/workers-ai/tutorials/creating-a-recommendation-api.md
> +Finally, rerun the `npm run dev` command. This is necessary because Vectorize indexes are not supported in local mode, so you need to add the `--remote` option. If you see the message, `Vectorize bin
```suggestion
Finally, rerun the `npx wrangler dev` command with the `--remote` option. This is necessary because Vectorize indexes are not supported in local mode. If you see the message, `Vectorize bindings are not currently supported in local mode. Please use --remote if you are working with them.`, rerun the command with the `--remote` option added.
```

2024-06-18 12:28 UTC, db-cloudflare commented on content/workers-ai/tutorials/creating-a-recommendation-api.md
> +$ npm run dev -- --remote
```suggestion
$ npx wrangler dev --remote
```

2024-06-18 12:28 UTC, db-cloudflare commented on content/workers-ai/tutorials/creating-a-recommendation-api.md
> +The Text Generation Model generates new text each time based on the input prompt (questions or product search results). Therefore, even if you send the same request to this API, the response text may
```suggestion
The text generation model generates new text each time based on the input prompt (questions or product search results). Therefore, even if you send the same request to this API, the response text may differ slightly. When developing for production, use features like logging or caching in the [AI Gateway](/ai-gateway/) to set up proper control and debugging.
```

2024-06-18 12:28 UTC, db-cloudflare commented on content/workers-ai/tutorials/creating-a-recommendation-api.md
> +To deploy the created application, run `npx wrangler deploy`. However, since the API keys of external services are defined in `.dev.vars`, this information also needs to be set in your Cloudflare Wor
```suggestion
Before deploying the application, we need to make sure your Worker project has access to the Stripe API keys we created earlier. Since the API keys of external services are defined in `.dev.vars`, this information also needs to be set in your Worker project. To save API keys and secrets, run the `npx wrangler secret put <KEY>` command. In this tutorial, you'll execute the command twice, referring to the values set in `.dev.vars`.
```

2024-06-18 12:28 UTC, db-cloudflare commented on content/workers-ai/tutorials/creating-a-recommendation-api.md
> +Open your terminal and run the following command:
CLI is used elsewhere on the tutorial, using CLI here as well helps with consistency and also lets us make sure readers know what the acronym means.
```suggestion
Open your command line interface (CLI) and run the following command:
```

2024-06-18 12:28 UTC, db-cloudflare commented on content/workers-ai/tutorials/creating-a-recommendation-api.md
> +### Billing notification
```suggestion
### Prerequisites
```

2024-06-18 12:28 UTC, db-cloudflare commented on content/workers-ai/tutorials/creating-a-recommendation-api.md
> +## Create a new Worker project
```suggestion
## 1. Create a new Worker project
```

2024-06-18 12:28 UTC, db-cloudflare commented on content/workers-ai/tutorials/creating-a-recommendation-api.md
> +## Create an API to Import Product Information
```suggestion
## 2. Create an API to import product information
```

2024-06-18 12:28 UTC, db-cloudflare commented on content/workers-ai/tutorials/creating-a-recommendation-api.md
> +This API requires the use of Workers AI and Vectorize. To use these resources from Workers, you need to create and bind the resources. First, let's create a Vectorize index with Wrangler using the co
```suggestion
This API requires the use of Workers AI and Vectorize. To use these resources from a Worker, you will need to first create the resources then [bind](/workers/runtime-apis/bindings/#what-is-a-binding) them to a Worker. First, let's create a Vectorize index with Wrangler using the command `wrangler vectorize create {index_name} --dimensions={number_of_dimensions} --metric={similarity_metric}`. The values for `dimensions` and `metric` depend on the type of [Text Embedding Model](/workers-ai/models/#text-embeddings) you are using for data vectorization (Embedding). For example, if you are using the `bge-large-en-v1.5` model, the command is:
```

2024-06-18 12:28 UTC, db-cloudflare commented on content/workers-ai/tutorials/creating-a-recommendation-api.md
> +To use the created Vectorize index from Workers, let's perform the binding. Open `wrangler.toml` and add the copied lines.
```suggestion
To use the created Vectorize index from your Worker, let's add the binding. Open `wrangler.toml` and add the copied lines.
```

2024-06-18 12:28 UTC, db-cloudflare commented on content/workers-ai/tutorials/creating-a-recommendation-api.md
> +### Implementation of Data Embedding Processing Using Workers AI
Changing this title to be a descriptive command for the end result of this task. Feel free to suggest a different title. I also think this might benefit from being its own step rather than a sub-step of `Create an API to import product information`. Again, let me know if you think this works or if you have any thoughts.
```suggestion
## 3. Convert text into vector data using Workers AI
```

2024-06-18 12:28 UTC, db-cloudflare commented on content/workers-ai/tutorials/creating-a-recommendation-api.md
> +### Saving Vector Data to Vectorize
```suggestion
### Save vector data to Vectorize
```

2024-06-18 12:28 UTC, db-cloudflare commented on content/workers-ai/tutorials/creating-a-recommendation-api.md
> +## Creating a Related Products Search API using Vectorize
```suggestion
## 4. Create a related products search API using Vectorize
```

2024-06-18 12:28 UTC, db-cloudflare commented on content/workers-ai/tutorials/creating-a-recommendation-api.md
> +## Deploying the Application
```suggestion
## 6. Deploy the application
```

2024-06-18 12:28 UTC, db-cloudflare commented on content/workers-ai/tutorials/creating-a-recommendation-api.md
> +## Create a recommendation API that answers user questions.
```suggestion
## 5. Create a recommendation API that answers user questions.
```

2024-06-18 12:28 UTC, db-cloudflare commented on content/workers-ai/tutorials/creating-a-recommendation-api.md
> +So far, we've covered how to create a Cloudflare Workers project and introduced tools and open-source projects like the `C3` command and the `Hono` framework that streamline development with Cloudfla
```suggestion
So far, we've covered how to create a Cloudflare Worker project and introduced tools and open-source projects like the `C3` command and the `Hono` framework that streamline development with Cloudflare. Leveraging these features will help you develop applications on Cloudflare Workers more smoothly.
```

2024-06-18 12:28 UTC, db-cloudflare commented on content/workers-ai/tutorials/creating-a-recommendation-api.md
> +As you can see, using Cloudflare Workers, Workers AI, and Vectorize allows you to easily implement related product or product recommendation APIs. Even if product data is managed on external services
```suggestion
As you can see, using Cloudflare Workers, Workers AI, and Vectorize allows you to easily implement related product or product recommendation APIs. Even if product data is managed on external services like Stripe, you can incorporate them by adding a webhook API. Additionally, though not introduced in this tutorial, you can save information such as user preferences and interested categories in Workers KV or D1. By using this stored information as text generation prompts, you can provide more accurate recommendation functions.
```

2024-06-18 12:28 UTC, dbenCF commented on content/workers-ai/tutorials/creating-a-recommendation-api.md
> +### Bind Workers AI and Vectorize to Workers
```suggestion
### Bind Workers AI and Vectorize to your Worker
```

2024-06-18 12:28 UTC, dbenCF commented on content/workers-ai/tutorials/creating-a-recommendation-api.md
> +### Create a Webhook API to Handle Product Registration Events
```suggestion
### Create a webhook API to handle product registration events
```

2024-06-18 12:28 UTC, dbenCF commented on content/workers-ai/tutorials/creating-a-recommendation-api.md
> +You can receive notifications about product registration and information via POST requests using Webhooks. Let's create an API that accepts POST requests. Open your `src/index.ts` file and add the fo
```suggestion
You can receive notifications about product registration and information via POST requests using webhooks. Let's create an API that accepts POST requests. Open your `src/index.ts` file and add the following code:
```

2024-06-18 12:28 UTC, dbenCF commented on content/workers-ai/tutorials/creating-a-recommendation-api.md
> +### Adding Stripe's API Key to the Project
```suggestion
### Add Stripe's API Key to the project
```

2024-06-18 12:28 UTC, dbenCF commented on content/workers-ai/tutorials/creating-a-recommendation-api.md
> +When developing a Webhook API, you need to ensure that requests from unauthorized sources are rejected. To prevent unauthorized API requests from causing unintended behavior or operational confusion,
```suggestion
When developing a webhook API, you need to ensure that requests from unauthorized sources are rejected. To prevent unauthorized API requests from causing unintended behavior or operational confusion, you need a mechanism to verify the source of API requests. When integrating with Stripe, you can protect the API by generating a signing secret used for webhook verification.
```

2024-06-18 12:28 UTC, dbenCF commented on content/workers-ai/tutorials/creating-a-recommendation-api.md
> +Finally, modify the source code of `src/index.ts` as follows to ensure that the Webhook API cannot be used from sources other than your Stripe account.
```suggestion
Finally, modify the source code of `src/index.ts` as follows to ensure that the webhook API cannot be used from sources other than your Stripe account.
```

2024-06-18 13:42 UTC, kodster28 commented on content/workers-ai/tutorials/creating-a-recommendation-api.md
> +- **Cloudflare Workers**: Execution environment for API applications
```suggestion
- [**Cloudflare Workers**](/workers/): Execution environment for API applications
```

2024-06-18 13:43 UTC, kodster28 commented on content/workers-ai/tutorials/creating-a-recommendation-api.md
> +- **Cloudflare Vectorize**: Vector DB used for related product searches
```suggestion
- [**Cloudflare Vectorize**](/vectorize/): Vector DB used for related product searches
```

2024-06-18 13:43 UTC, kodster28 commented on content/workers-ai/tutorials/creating-a-recommendation-api.md
> +- **Cloudflare Workers AI**: Used for vectorizing data and generating recommendation texts
```suggestion
- [**Cloudflare Workers AI**](/workers-ai/): Used for vectorizing data and generating recommendation texts
```

2024-06-20 00:41 UTC, hideokamoto-stripe commented
Thank you @kodster28 for leaving such detailed feedback!
It's really helpful for me in improving this content.

I've now updated this PR to follow your feedback.
Best regards.

2024-06-20 08:29 UTC, dbenCF approved these changes

2024-06-24 09:44 UTC, merged