Handling Workers AI Errors
cloudflare/cloudflare-docs pull request #15223
Opened 2024-06-20 16:19 UTC by daisyfaithauma

This documentation provides guidelines on handling Workers AI errors from both the REST API and Worker scripts. It includes information on error response structures, handling methods, and lists of common errors with their respective HTTP status codes and descriptions.

2024-06-21 14:11 UTC, kodster28 requested changes
Some feedback referring to specific standards and then a few other tweaks. Bug me internally when you've finished and I'll re-review.

Had a lot of good things in it, including:
- Using code examples and formatting (and indenting) correctly
- Correct header levels and descriptive (but not too long) header text
- General readability

2024-06-21 14:11 UTC, kodster28 commented on content/workers-ai/platform/workers-ai-error-handling.md
> +# Handling Workers AI Errors
```suggestion
---
pcx_content_type: reference
---

# Handling Workers AI Errors
```

2024-06-21 14:11 UTC, kodster28 commented on content/workers-ai/platform/workers-ai-error-handling.md
> +# Handling Workers AI Errors
We use `frontmatter` separated by `---` to add certain properties and metadata to different pages.

- [Reference template](https://developers.cloudflare.com/style-guide/documentation-content-strategy/content-types/reference/#template)
- [Hugo docs](https://gohugo.io/content-management/front-matter/)

This page is also a "type" of reference, more details at the link above. We have several different [content types](https://developers.cloudflare.com/style-guide/documentation-content-strategy/content-types/), each of which has a time and place to be used.

2024-06-21 14:11 UTC, kodster28 commented on content/workers-ai/platform/workers-ai-error-handling.md
> +This documentation provides guidelines on handling Workers AI errors from both the REST API and Worker scripts. It includes information on error response structures, handling methods, and lists of co
```suggestion
Learn how to handle Workers AI errors from both the REST API and Worker scripts. This page includes information on error response structures, handling methods, and lists of common errors with their respective HTTP status codes and descriptions.
```

2024-06-21 14:11 UTC, kodster28 commented on content/workers-ai/platform/workers-ai-error-handling.md
> +This documentation provides guidelines on handling Workers AI errors from both the REST API and Worker scripts. It includes information on error response structures, handling methods, and lists of co
More of a nit, but I'd lean towards a touch less formal here.

2024-06-21 14:11 UTC, kodster28 commented on content/workers-ai/platform/workers-ai-error-handling.md
> +When interacting with Workers AI via the REST API, errors are returned in the JSON payload. The error responses typically include an HTTP status code and a JSON body containing details about the erro
```suggestion
When interacting with Workers AI via the [REST API](/workers-ai/get-started/rest-api/), errors are returned in the JSON payload. The error responses typically include an HTTP status code and a JSON body containing details about the error.
```

2024-06-21 14:11 UTC, kodster28 commented on content/workers-ai/platform/workers-ai-error-handling.md
> +When interacting with Workers AI via the REST API, errors are returned in the JSON payload. The error responses typically include an HTTP status code and a JSON body containing details about the erro
We use cross-links basically wherever we can. The structure of these links are always relative to the overall folder structure (not the immediate file).

Good
- `/workers-ai/get-started/rest-api/

Bad:
- `../../get-started/rest-api/`
- `https://developers.cloudflare.com/rest-api/`

The reason we approach it this way is two-fold:
1. We have some automated checks so the "maintenance cost" of adding an internal link is close to 0.
2. Checking `../` links is really hard for our automated checks and/or if we ever need to find and replace links in the future.

2024-06-21 14:11 UTC, kodster28 commented on content/workers-ai/platform/workers-ai-error-handling.md
> +```javascript
```suggestion
```js
```

2024-06-21 14:11 UTC, kodster28 commented on content/workers-ai/platform/workers-ai-error-handling.md
> +```javascript
Our formatter accepts both

2024-06-21 14:11 UTC, kodster28 commented on content/workers-ai/platform/workers-ai-error-handling.md
> +    'Authorization': 'Bearer YOUR_API_TOKEN'
```suggestion
    'Authorization': 'Bearer <YOUR_API_TOKEN>'
```

2024-06-21 14:11 UTC, kodster28 commented on content/workers-ai/platform/workers-ai-error-handling.md
> +    'Authorization': 'Bearer YOUR_API_TOKEN'
[Angle brackets](https://developers.cloudflare.com/style-guide/formatting/code-conventions-and-format/#angle-brackets---and--) for placeholder values.

2024-06-21 14:11 UTC, kodster28 commented on content/workers-ai/platform/workers-ai-error-handling.md
> +| HTTP Code | Error Code            | Message                                            |
Should [monospace](https://developers.cloudflare.com/style-guide/formatting/code-conventions-and-format/#monospace) all the values for the error codes and HTTP codes.

2024-06-21 14:11 UTC, kodster28 commented on content/workers-ai/platform/workers-ai-error-handling.md
> +When using Workers AI in Worker scripts, errors can be caught using try/catch blocks. The `ai.run` function can throw errors which should be handled appropriately.
```suggestion
When using Workers AI in [Worker scripts](/workers-ai/get-started/workers-wrangler/), errors can be caught using try/catch blocks. The `ai.run` function can throw errors which should be handled appropriately.
```

2024-06-21 14:11 UTC, kodster28 commented on content/workers-ai/platform/workers-ai-error-handling.md
> +```javascript
```suggestion
```js
```

2024-06-21 14:11 UTC, kodster28 commented on content/workers-ai/platform/workers-ai-error-handling.md
> +    const result = await ai.run('model-id', { /* your payload */ });
```suggestion
    const result = await ai.run('<MODEL_ID>', { /* your payload */ });
```

2024-06-21 14:11 UTC, kodster28 commented on content/workers-ai/platform/workers-ai-error-handling.md
> +| Error Code         | Description                                              |
Monospace the error codes

2024-06-24 14:29 UTC, mchenco commented
the page name doesn't show up
<img width="367" alt="image" src="https://github.com/cloudflare/cloudflare-docs/assets/16037646/516396c7-94ee-443a-89a5-8ff9a3c80033">

2024-06-25 09:33 UTC, G4brym commented on content/workers-ai/platform/workers-ai-error-handling.md
> +addEventListener('fetch', event => {
The recommended way of writing workers today is to use ES Modules instead of event Listeners as you are using here.
Please update this example script as described [here](https://developers.cloudflare.com/workers/reference/migrate-to-module-workers/)

2024-06-25 12:31 UTC, Khorous commented
Well ❤️‍🩹❤️‍🩹❤️‍🩹

2024-06-25 12:33 UTC, Khorous commented
@, good

2024-06-25 12:35 UTC, daisyfaithauma commented on content/workers-ai/platform/workers-ai-error-handling.md
> +| Error Code         | Description                                              |
Is it not?

2024-06-25 13:20 UTC, kodster28 commented on content/workers-ai/platform/workers-ai-error-handling.md
> +---
```suggestion
title: Error handling
---
```

2024-06-25 13:20 UTC, kodster28 commented on content/workers-ai/platform/workers-ai-error-handling.md
> +| 400       | INVALID_REQUEST       | The request payload is malformed.                  |
```suggestion
| `400`       | `INVALID_REQUEST`       | The request payload is malformed.                  |
```

2024-06-25 13:20 UTC, kodster28 commented on content/workers-ai/platform/workers-ai-error-handling.md
> +| MODEL_NOT_FOUND    | The specified model does not exist.                      |
```suggestion
| `MODEL_NOT_FOUND`    | The specified model does not exist.                      |
```

2024-06-25 13:20 UTC, kodster28 commented on content/workers-ai/platform/workers-ai-error-handling.md
> +| Error Code         | Description                                              |
Monospacing is what we call enclosing something in backticks, like `this`.

2024-08-12 15:04 UTC, daisyfaithauma commented
Closing this PR. Waiting for tests.

2024-08-12 15:04 UTC, closed without merging