cdnjs should always be lowercase
cloudflare/cloudflare-docs pull request #15348
Opened 2024-06-26 21:45 UTC by MattIPv4

Couldn't see any existing rule for enforcing correct capitalization of brand names (was surprised given Cloudflare vs. CloudFlare), so I've added one as part of this. Haven't written a Vale rule before so it could be wrong!

2024-06-27 02:38 UTC, GregBrimble commented on .github/styles/cloudflare/BrandNames.yml
> +  CloudFlare: Cloudflare
To catch anyone missing the leading capital too :)
```suggestion
  (?!Cloudflare)([cC]loud[fF]lare): Cloudflare
```

2024-06-27 02:40 UTC, GregBrimble commented on .github/styles/cloudflare/BrandNames.yml
> +  (?!cdnjs)([cC][dD][nN]\.?[jJ][sS]): cdnjs
Maybe in a follow up PR if not now.

```suggestion
  (?!cdnjs)([cC][dD][nN]\.?[jJ][sS]): cdnjs
  (?!GitHub)([gG]it\s?[hH]ub): GitHub
  (?!GitLab)([gG]it\s?[lL]ab): GitLab
```

2024-06-27 03:05 UTC, MattIPv4 commented on .github/styles/cloudflare/BrandNames.yml
> +  (?!GitLab)([gG]it\s?[lL]ab): GitLab
```suggestion
  (?!Cloudflare)(?:[cC]loud[fF]lare): Cloudflare
  (?!cdnjs)(?:[cC][dD][nN]\.?[jJ][sS]): cdnjs
  (?!GitHub)(?:[gG]it\s?[hH]ub): GitHub
  (?!GitLab)(?:[gG]it\s?[lL]ab): GitLab
```
Per the CI run, capture groups aren't supported: https://github.com/cloudflare/cloudflare-docs/actions/runs/9689862423/job/26738869158#step:5:50

2024-06-27 03:09 UTC, GregBrimble approved these changes
Looks like a great addition to me! Again, will defer to @KianNH for final approval :)

2024-06-27 06:50 UTC, KianNH requested changes

2024-06-27 06:50 UTC, KianNH commented on .github/styles/cloudflare/BrandNames.yml
> +  (?!GitLab)(?:[gG]it\s?[lL]ab): GitLab
Thanks for putting this together Matt!

It looks like the rule currently matches strings like `create-cloudflare-cli` or `https://github.com/cloudflare`.

It's not pretty, but `(?:^|\s)` at the beginning (whitespace or start of line) and `(?:'s|\s|$)` (`'s`, whitespace or end of line) seems to prevent the false-positives.

This means we don't match `create-cloudflare-cli`, or `github.com/cloudflare`, but can still make sure we don't let `github's` or `CloudFlare's` usage slip through.

I ran the suggestion across all Markdown files in the repository and all of the warnings were valid.

Totally open to any regexes that look a little less ugly!
```suggestion
swap:
  (?:^|\s)(?!Cloudflare)(?:[cC]loud[fF]lare)(?:'s|\s|$): Cloudflare
  (?:^|\s)(?!cdnjs)(?:[cC][dD][nN]\.?[jJ][sS])(?:'s|\s|$): cdnjs
  (?:^|\s)(?!GitHub)(?:[gG]it\s?[hH]ub)(?:'s|\s|$): GitHub
  (?:^|\s)(?!GitLab)(?:[gG]it\s?[lL]ab)(?:'s|\s|$): GitLab
```

2024-06-27 13:22 UTC, MattIPv4 commented on .github/styles/cloudflare/BrandNames.yml
> +  (?!GitLab)(?:[gG]it\s?[lL]ab): GitLab
I think these are going to want to be lookarounds rather than non-capturing groups? Otherwise it's going to want to remove whitespace (or the `'s`) as part of the suggestion?

2024-06-27 13:25 UTC, MattIPv4 commented on .github/styles/cloudflare/BrandNames.yml
> +  (?!GitLab)(?:[gG]it\s?[lL]ab): GitLab
```suggestion
swap:
  (?<=^|\s)(?!Cloudflare)(?:[cC]loud[fF]lare)(?='s|\s|$): Cloudflare
  (?<=^|\s)(?!cdnjs)(?:[cC][dD][nN]\.?[jJ][sS])(?='s|\s|$): cdnjs
  (?<=^|\s)(?!GitHub)(?:[gG]it\s?[hH]ub)(?='s|\s|$): GitHub
  (?<=^|\s)(?!GitLab)(?:[gG]it\s?[lL]ab)(?='s|\s|$): GitLab
```

2024-07-02 22:17 UTC, GregBrimble commented
Not sure whitespace alone is enough. What about something like `Welcome to Cloudflare.`, `platforms like: GitHub, GitLab, etc.` and links (`[GitHub](https://github.com/)`)

2024-07-02 22:47 UTC, MattIPv4 commented
Hmm, I'm not sure there's going to be a good way to do that, while still avoiding what Kian flagged, unless we're doing to allow some non-alphanumeric chars but not others?

2024-07-03 00:08 UTC, GregBrimble commented
I'd personally think that we'd want to warn on all uses, and try to exclude certain ones which we know are valid. The Microsoft Work/Google Docs spellcheck dictionary approach.

So I'd suggest `(?<!https:\/\/[^\s]+)(?<!create-)(?!GitLab)(?:[gG]it\s?[lL]ab)` and equivalents.

2024-07-03 00:09 UTC, GregBrimble commented
Oh, `Next.js` is another one I see get mis-stylized all the time.

2024-07-03 01:13 UTC, MattIPv4 commented on .github/styles/cloudflare/BrandNames.yml
> +  (?<=^|\s)(?!GitLab)(?:[gG]it\s?[lL]ab)(?='s|\s|$): GitLab
```suggestion
  (?<!https?:\/\/[^\s]*)(?<!create-)(?!Cloudflare)(?:[cC]loud[fF]lare)): Cloudflare
  (?<!https?:\/\/[^\s]*)(?<!create-)(?!cdnjs)(?:[cC][dD][nN]\.?[jJ][sS]): cdnjs
  (?<!https?:\/\/[^\s]*)(?<!create-)(?!GitHub)(?:[gG]it\s?[hH]ub): GitHub
  (?<!https?:\/\/[^\s]*)(?<!create-)(?!GitLab)(?:[gG]it\s?[lL]ab): GitLab
```

2024-07-03 01:31 UTC, MattIPv4 commented on .github/styles/cloudflare/BrandNames.yml
> +  (?<!https?:\/\/[^\s]*)(?<!create-)(?!GitLab)(?:[gG]it\s?[lL]ab): GitLab
```suggestion
  (?<!https?:\/\/[^\s]*)(?<!create-)(?!GitLab)(?:[gG]it\s?[lL]ab): GitLab
  (?<!https?:\/\/[^\s]*)(?<!create-)(?!Next\.js)(?:[nN][eE][xX][tT][\s\.]?[jJ[sS]): Next.js
```

2024-07-03 01:31 UTC, MattIPv4 commented on .github/styles/cloudflare/BrandNames.yml
> +  (?<!https?:\/\/[^\s]*)(?<!create-)(?!Next\.js)(?:[nN][eE][xX][tT][\s\.]?[jJ[sS]): Next.js
```suggestion
  (?<!https?:\/\/[^\s]*)(?!cdnjs)(?:[cC][dD][nN]\.?[jJ][sS]): cdnjs
  (?<!https?:\/\/[^\s]*)(?!GitHub)(?:[gG]it\s?[hH]ub): GitHub
  (?<!https?:\/\/[^\s]*)(?!GitLab)(?:[gG]it\s?[lL]ab): GitLab
  (?<!https?:\/\/[^\s]*)(?!Next\.js)(?:[nN][eE][xX][tT][\s\.]?[jJ[sS]): Next.js
```

2024-08-30 15:44 UTC, kodster28 commented
Closing this in favor of #16557, apologies it took so long to get it merged in

2024-08-30 15:44 UTC, closed without merging