[GraphQL] Update examples on GraphQL filtering page
cloudflare/cloudflare-docs pull request #1555
Opened 2021-06-10 20:57 UTC by crwaters16

2021-06-10 21:00 UTC, crwaters16 commented
Curious if https://developers.cloudflare.com/analytics/graphql-api/features/filtering#graphql-003 also needs to change

2021-06-11 07:24 UTC, twalwyn commented
> Curious if https://developers.cloudflare.com/analytics/graphql-api/features/filtering#graphql-003 also needs to change

That example is OK because it does not try to filter on a field that does not exist.

2021-06-11 07:41 UTC, twalwyn reviewed
Thanks for doing this cleanup work! I've suggested a few minor modifications.

2021-06-11 07:41 UTC, twalwyn commented on products/analytics/src/content/graphql-api/features/filtering/index.md
>    myQuery(
This query was really messed up :)

This is an example query that will actually work: 

```suggestion
{
  viewer {
    zones(filter: {zoneTag: $zoneTag}) {
      httpRequestsAdaptiveGroups(filter: {datetime_gt: "2021-06-10T00:00:00Z", clientCountryName: "GB"}, limit: 1) {
        count
      }
    }
  }
}
```

2021-06-11 07:41 UTC, twalwyn commented on products/analytics/src/content/graphql-api/features/filtering/index.md
> +httpRequestsAdaptiveGroups(filter: {datetime: "2018-01-01T10:00:00Z"}) {
The SQL below is incorrect for the given query. 

The SQL should read

```sql
WHERE datetime="2018-01-01T10:00:00Z"
```

2021-06-11 07:41 UTC, twalwyn commented on products/analytics/src/content/graphql-api/features/filtering/index.md
> +          OR:[{clientCountryName: "US"}, {clientCountryName: "UK"}]) {
```suggestion
          OR:[{clientCountryName: "US"}, {clientCountryName: "GB"}]) {
```
UK is not a country name in our analytics DB.

2021-06-11 07:41 UTC, twalwyn commented on products/analytics/src/content/graphql-api/features/filtering/index.md
> +          OR:[{clientCountryName: "US"}, {clientCountryName: "UK"}]) {
The SQL below should also probably be updated.

2021-06-11 15:22 UTC, crwaters16 commented on products/analytics/src/content/graphql-api/features/filtering/index.md
> +          clientCountry: "UK" # all objects having client country equal to "UK"
@twalwyn, does this instance also need to change to "GB", or is that only for clientCountryName?

2021-06-11 15:29 UTC, victor-perov requested changes

2021-06-11 15:29 UTC, victor-perov commented on products/analytics/src/content/graphql-api/features/filtering/index.md
> +{
Lines 105-123 shows incorrect GraphQL query. I think it makes sense to just remove the general example section.

2021-06-11 15:29 UTC, victor-perov commented on products/analytics/src/content/graphql-api/features/filtering/index.md
> +httpRequestsAdaptiveGroups(filter: {datetime: "2018-01-01T10:00:00Z"}) {
So we should either change SQL (remove line 142) or add the country filter. For `httpRequestsAdaptiveGroups` a field responsible for a client's country would be `clientCountryName`.

2021-06-11 15:29 UTC, victor-perov commented on products/analytics/src/content/graphql-api/features/filtering/index.md
> +httpRequestsAdaptiveGroups(filter: {datetime: "2018-01-01T10:00:00Z"}) {
I also don't see how this example differs from #005 below.

2021-06-11 15:29 UTC, kodster28 approved these changes

2021-06-11 19:03 UTC, crwaters16 commented on products/analytics/src/content/graphql-api/features/filtering/index.md
> +{
@victor-perov , think you may've reviewed around the same time as I implemented Tom's suggestions - let me know which of your comments stand with the new commits!

2021-06-14 09:20 UTC, 888520ll19811209ll approved these changes

2021-06-14 09:20 UTC, 888520ll19811209ll approved these changes

2021-06-17 08:38 UTC, twalwyn requested changes
Thanks for the update. I clarified one of my change requests.

2021-06-17 08:38 UTC, twalwyn commented on products/analytics/src/content/graphql-api/features/filtering/index.md
>  {
Sorry if my original comment was not clear - L104 to L123 should be replace with the following:

```
{
  viewer {
    zones(filter: {zoneTag: $zoneTag}) {
      httpRequestsAdaptiveGroups(filter: {datetime_gt: "2021-06-10T00:00:00Z", clientCountryName: "GB"}, limit: 1) {
        count
      }
    }
  }
}
```

2021-06-17 14:00 UTC, twalwyn approved these changes
LGTM!

2021-06-17 19:34 UTC, soheiokamoto commented on products/analytics/src/content/graphql-api/features/filtering/index.md
> +  AND ((clientCountryName = "GB") OR (clientCountryName = "US"))
I don't know if it matters, but maybe keep the order the same as above GraphQL (`US` then `UK`).

2021-06-17 19:35 UTC, soheiokamoto commented on products/analytics/src/content/graphql-api/features/filtering/index.md
> +          OR:[{clientCountryName: "US"}, {clientCountryName: "GB"}]) {
There is still `UK` in the paragraph above.

2021-06-17 20:24 UTC, victor-perov requested changes
Thanks for your work! It looks much better now.
Would you mind changing L153 to align countryName (UK -> GB) with the example?

2021-06-17 20:24 UTC, victor-perov commented on products/analytics/src/content/graphql-api/features/filtering/index.md
> +          OR:[{clientCountryName: "US"}, {clientCountryName: "GB"}]) {
Yep, would be nice to change line 153 as well

2021-06-17 20:41 UTC, victor-perov approved these changes
LGTM
Thanks!

2021-06-17 20:45 UTC, merged