[Crypto] Fixing description of timingSafeEqual
cloudflare/cloudflare-docs pull request #15681
Opened 2024-07-18 11:18 UTC by mschwarzl

2024-07-18 11:57 UTC, kodster28 approved these changes

2024-07-18 12:08 UTC, KianNH requested changes

2024-07-18 12:08 UTC, KianNH commented on content/workers/examples/protect-against-timing-attacks.md
> -    if (a.byteLength !== b.byteLength) {
Could you please explain why this check is being removed? Without this, a comparison between `a` and `à` will cause an exception to be thrown by `timingSafeEqual`.

2024-07-18 13:07 UTC, KianNH approved these changes

2024-07-20 13:41 UTC, Avazbek84 reviewed
Ооо

2024-07-22 13:09 UTC, merged