[Wrangler] add missing --persist-to for pages dev in wrangler commands.md
cloudflare/cloudflare-docs pull request #15747
Opened 2024-07-23 05:21 UTC by teak

### Summary

The `--persist-to` argument works with `wrangler pages dev` but is not listed in the wangler commands documentation.

### Documentation checklist

- [x] The [documentation style guide](https://developers.cloudflare.com/style-guide/) has been adhered to.

2024-07-23 05:56 UTC, petebacondarwin requested changes

2024-07-23 05:56 UTC, petebacondarwin commented on content/workers/wrangler/commands.md
> +  - Specify directory to use for local persistence (for use in combination with `--local`).
There is no `--local` for `wrangler pages dev` it is always local.

2024-07-23 05:56 UTC, petebacondarwin commented on content/workers/wrangler/commands.md
> +  - Specify directory to use for local persistence (for use in combination with `--local`).
So we should remove the --local option above.
If we are fixing up these docs we should make sure they all align. Here is the output from `wrangler pages dev --help`, excluding experimental and deprecated options:

```
      --compatibility-date                         Date to use for compatibility checks  [string]
      --compatibility-flags, --compatibility-flag  Flags to use for compatibility checks  [array]
      --ip                                         The IP address to listen on  [string]
      --port                                       The port to listen on (serve from)  [number]
      --inspector-port                             Port for devtools to connect to  [number]
      --no-bundle                                  Whether to run bundling on `_worker.js`  [boolean] [default: false]
  -b, --binding                                    Bind variable/secret (KEY=VALUE)  [array]
  -k, --kv                                         KV namespace to bind (--kv KV_BINDING)  [array]
      --d1                                         D1 database to bind (--d1 D1_BINDING)  [array]
  -o, --do                                         Durable Object to bind (--do DO_BINDING=CLASS_NAME@SCRIPT_NAME)  [array]
      --r2                                         R2 bucket to bind (--r2 R2_BINDING)  [array]
      --ai                                         AI to bind (--ai AI_BINDING)  [string]
      --version-metadata                           Worker Version metadata (--version-metadata VERSION_METADATA_BINDING)  [string]
      --service                                    Service to bind (--service SERVICE=SCRIPT_NAME)  [array]
      --live-reload                                Auto reload HTML pages when change is detected  [boolean] [default: false]
      --local-protocol                             Protocol to listen to requests on, defaults to http.  [choices: "http", "https"]
      --https-key-path                             Path to a custom certificate key  [string]
      --https-cert-path                            Path to a custom certificate  [string]
      --persist-to                                 Specify directory to use for local persistence (defaults to .wrangler/state)  [string]
      --log-level                                  Specify logging level  [choices: "debug", "info", "log", "warn", "error", "none"]
      --show-interactive-dev-session               Show interactive dev session (defaults to true if the terminal supports interactivity)  [boolean]
```

2024-07-23 06:47 UTC, teak commented on content/workers/wrangler/commands.md
> +  - Specify directory to use for local persistence (for use in combination with `--local`).
Is more out of date than I expected, I removed `--local` and added `--log-level`, but there are still inconsistencies.

2024-07-23 09:32 UTC, petebacondarwin approved these changes
Let's land this as it's an improvement over the previous docs. Thanks @teak 
We should follow up with a further change that fixes the other inconsistencies.

2024-09-27 15:14 UTC, KimJ15 commented
👋Hi there, we’re going to close this PR. All PRs prior to August 12 need to be reworked due to the platform migration to Astro.

2024-09-27 15:14 UTC, closed without merging