[D1] D1 API tutorial
cloudflare/cloudflare-docs pull request #15779
Opened 2024-07-24 16:19 UTC by harshil1712

Tutorial for creating an API to interact with D1 outside of Workers/Pages project

2024-07-24 16:41 UTC, kodster28 commented on content/d1/tutorials/build-an-api-to-access-d1/index.md
> +// update the token value
Would it make more sense to add this as a [secret to your worker](https://developers.cloudflare.com/workers/configuration/secrets/) and then access it that way?

2024-07-24 19:20 UTC, vy-ton commented
@ShaheenFattoe8 Can you run thru this tutorial and leave any user feedback as comments?

2024-07-25 16:52 UTC, ShaheenFattoe8 commented on content/d1/tutorials/build-an-api-to-access-d1/index.md
> +- For the `Do you want to use git for version control?` prompt, select `Yes`.
Question was not triggered on my end.

2024-07-25 16:54 UTC, ShaheenFattoe8 commented on content/d1/tutorials/build-an-api-to-access-d1/index.md
> +## 6. Create a table
Bug in D1: If you leave comments in the .sql file, it will not run and will return an error instead. This is something I've heard from others as well so until that is fixed I'd recommend specifying this in the tutorial.

2024-07-25 16:56 UTC, ShaheenFattoe8 commented on content/d1/tutorials/build-an-api-to-access-d1/index.md
> +$ curl -H "Authorization: Bearer YOUR_SECRET_TOKEN" "http://localhost:8787/api/batch" --data '{"query": "SELECT title FROM posts WHERE id=?", "params":1}'
Encountering an error here, query is not running properly: ```shaheenfattoe@HQC542LKFK d1-http % curl -H "Authorization: Bearer YOUR_SECRET_TOKEN" "http://localhost:8787/api/batch" --data '{"query": "SELECT title FROM posts WHERE id=?", "params":1}'
{"error":"Failed to run query: TypeError: batch is not iterable"}%```

2024-07-25 16:58 UTC, ShaheenFattoe8 commented on content/d1/tutorials/build-an-api-to-access-d1/index.md
> +$ curl -H "Authorization: Bearer YOUR_SECRET_TOKEN" "http://localhost:8787/api/batch" --data '{"query": "INSERT INTO posts (author, title, body, post_slug) VALUES ('Harshil', 'D1 HTTP API', 'Learn to
Encountering an error here, query is not running properly: ```shaheenfattoe@HQC542LKFK d1-http % curl -H "Authorization: Bearer YOUR_SECRET_TOKEN" "http://localhost:8787/api/batch" --data '{"query": "INSERT INTO posts (author, title, body, post_slug) VALUES ('Harshil', 'D1 HTTP API', 'Learn to create an API to query your D1 database.','d1-http-api')" }'
{"error":"Failed to run query: SyntaxError: Unterminated string in JSON at position 81 (line 1 column 82)"}curl: (6) Could not resolve host: HTTP
curl: (3) URL rejected: Malformed input to a URL function
curl: (6) Could not resolve host: to
curl: (6) Could not resolve host: create
curl: (6) Could not resolve host: an
curl: (6) Could not resolve host: API
curl: (6) Could not resolve host: to
curl: (6) Could not resolve host: query
curl: (6) Could not resolve host: your
curl: (6) Could not resolve host: D1
curl: (3) unmatched close brace/bracket in URL position 25:
database.,d1-http-api)" }```

2024-07-25 17:22 UTC, vy-ton commented on content/d1/tutorials/build-an-api-to-access-d1/index.md
> +## 6. Create a table
@ShaheenFattoe8 Can you bring up this, related [ticket](https://jira.cfdata.org/browse/CFSQL-692), to D1 chat or next weekly

2024-07-25 19:38 UTC, ShaheenFattoe8 commented on content/d1/tutorials/build-an-api-to-access-d1/index.md
> +## 6. Create a table
Yep, I can bring it up in the weekly and get some thoughts from the team there. I'll write this up as an example as well.

2024-07-26 08:52 UTC, harshil1712 commented on content/d1/tutorials/build-an-api-to-access-d1/index.md
> +- For the `Do you want to use git for version control?` prompt, select `Yes`.
Ah, that is interesting. Might be a wrangler error? Every time I run the `c3 create` command, I get the question. Let me investigate.

2024-07-26 09:08 UTC, harshil1712 commented on content/d1/tutorials/build-an-api-to-access-d1/index.md
> +## 6. Create a table
Updated the instructions and removed the comments.

2024-07-26 09:09 UTC, harshil1712 commented on content/d1/tutorials/build-an-api-to-access-d1/index.md
> +$ curl -H "Authorization: Bearer YOUR_SECRET_TOKEN" "http://localhost:8787/api/batch" --data '{"query": "INSERT INTO posts (author, title, body, post_slug) VALUES ('Harshil', 'D1 HTTP API', 'Learn to
Updated the body. The issue was with the inconsistent `'` quotes

2024-07-26 10:55 UTC, harshil1712 commented on content/d1/tutorials/build-an-api-to-access-d1/index.md
> +// update the token value
Good call! Updated the steps

2024-07-29 23:06 UTC, vy-ton commented on content/d1/tutorials/build-an-api-to-access-d1/index.md
> +In this tutorial, you will learn how to create an API that allows you to securely run queries against a D1 database. This is useful if you want to access a D1 database outside of a Worker or Pages pr
> outside of a Worker or Pages project

Wording here and in the title are slightly misleading because a Worker is deployed? 

Maybe something like `Build an API to access D1 using a proxy Worker`?

2024-07-29 23:06 UTC, vy-ton commented on content/d1/tutorials/build-an-api-to-access-d1/index.md
> +In this tutorial, you will learn how to create an API that allows you to securely run queries against a D1 database. This is useful if you want to access a D1 database outside of a Worker or Pages pr
> this approach is not recommende due to rate limits and high latency

I would reframe to highlight the positives of a Worker-first strategy. "a proxy Worker approach has better performance and avoids Cloudflare API [rate limits](https://developers.cloudflare.com/fundamentals/api/reference/limits/#:~:text=The%20global%20rate%20limit%20for,receiving%20a%20HTTP%20429%20response.)"

2024-07-29 23:06 UTC, vy-ton commented on content/d1/tutorials/build-an-api-to-access-d1/index.md
> +- For the `What type of application do you want to create?` prompt, select `"Hello World" Worker`.
Have you seen the `API starter (OpenAPI compliant)` sample app in c3? Thoughts on whether should be the starting template?

2024-07-29 23:06 UTC, vy-ton commented on content/d1/tutorials/build-an-api-to-access-d1/index.md
> +To ensure that the API Key is secure, you will add it as a [secret](/workers/configuration/secrets/). To do so, create a `.dev.vars` file in the root directory. Add your API key in the file as follow
Clarify this only applies for local dev

2024-07-29 23:06 UTC, vy-ton commented on content/d1/tutorials/build-an-api-to-access-d1/index.md
> +	DB: D1Database;
Since this code has `DB`, I would have the create database step before or remove then add this in a later step

2024-07-29 23:06 UTC, vy-ton commented on content/d1/tutorials/build-an-api-to-access-d1/index.md
> +})
consistency with ending `;`

2024-07-29 23:06 UTC, vy-ton commented on content/d1/tutorials/build-an-api-to-access-d1/index.md
> +		let { query } = await c.req.json();
No parameters are bound here

2024-07-29 23:06 UTC, vy-ton commented on content/d1/tutorials/build-an-api-to-access-d1/index.md
> +...
If a user copies this snippet, `...` breaks. Maybe replace with a code comment?

2024-07-29 23:06 UTC, vy-ton commented on content/d1/tutorials/build-an-api-to-access-d1/index.md
> +app.post('/api/all', async (c) => {
Comment or link to https://developers.cloudflare.com/d1/build-with-d1/d1-client-api/#await-stmtall to highlight all() vs exec()

2024-07-29 23:06 UTC, vy-ton commented on content/d1/tutorials/build-an-api-to-access-d1/index.md
> +### 9.1 Create the table in the production database
Numbering is off

2024-07-29 23:06 UTC, vy-ton commented on content/d1/tutorials/build-an-api-to-access-d1/index.md
> +Next, execute the `wrangler secret put <KEY>` command to add the `API_KEY` to the deployed project.
Do we typically recommend using the same key for local and remote?

2024-07-29 23:06 UTC, vy-ton commented on content/d1/tutorials/build-an-api-to-access-d1/index.md
> +The tutorial does not cover how to sanitize SQL queries. Please ensure that you sanitize query statements before executing them.
For a reader, single sentence on what is query sanitization and why they might want it. Can be very brief

2024-07-29 23:08 UTC, vy-ton commented
@harshil1712 We should host the full code example somewhere - to be paired with the tutorial.

@nevikashah this could make a good D1 template

2024-07-30 11:24 UTC, harshil1712 commented on content/d1/tutorials/build-an-api-to-access-d1/index.md
> +- For the `What type of application do you want to create?` prompt, select `"Hello World" Worker`.
That's a great template! I believe it is useful when one wants to build a proper API, but not when they want to write custom SQL statements. This tutorial allows the user to send SQL statements, while the starter will restrict that. I'll link this starter in the conclusion to let folks know about this. Maybe we can have a separate tutorial focused on creating an OpenAPI compliant API?!
I also plan to keep this tutorial a bit simple and easy to follow. Which is also a reason to not use `zod` for validation like in [Matt's demo](https://github.com/elithrar/http-api-d1-example).

2024-07-30 12:49 UTC, harshil1712 commented on content/d1/tutorials/build-an-api-to-access-d1/index.md
> +		let { query } = await c.req.json();
This is for the `exec()` method which [doesn't take any parameter](https://arc.net/l/quote/ibfsczcm).

2024-07-30 12:59 UTC, elithrar requested changes

2024-07-30 12:59 UTC, elithrar commented on content/d1/tutorials/build-an-api-to-access-d1/index.md
> +In this tutorial, you will learn how to create an API that allows you to securely run queries against a D1 database. This is useful if you want to access a D1 database outside of a Worker or Pages pr
```suggestion
In this tutorial, you will learn how to create an API that allows you to securely run queries against a D1 database.

This is useful if you want to access a D1 database outside of a Worker or Pages project, customize access controls and/or limit what tables can be queried.

D1's built-in [REST API](/api/operations/cloudflare-d1-create-database) is best suited for administrative use as the global [Cloudflare API rate limit](/fundamentals/api/reference/limits/) applies.
```

2024-07-30 12:59 UTC, elithrar commented on content/d1/tutorials/build-an-api-to-access-d1/index.md
> +The tutorial does not cover how to sanitize SQL queries. Please ensure that you sanitize query statements before executing them.
To add to this - no example code we ship should ever (ever) be vulnerable to SQL injection.

D1 has a parameterized query API.

2024-07-30 12:59 UTC, elithrar commented on content/d1/tutorials/build-an-api-to-access-d1/index.md
> +To ensure that the API Key is secure, you will add it as a [secret](/workers/configuration/secrets/). To do so, create a `.dev.vars` file in the root directory. Add your API key in the file as follow
The API key here is never added as a secret later in the guide.

2024-07-30 12:59 UTC, elithrar commented on content/d1/tutorials/build-an-api-to-access-d1/index.md
> +})
(Format all the code first)

2024-07-30 16:47 UTC, ShaheenFattoe8 commented on content/d1/tutorials/build-an-api-to-access-d1/index.md
> +- For the `Do you want to use git for version control?` prompt, select `Yes`.
This question is only triggered if you have git configured. Chatted with the C3 team and a fix will be coming soon that displays a warning if git is not configured.

2024-07-30 16:54 UTC, harshil1712 commented on content/d1/tutorials/build-an-api-to-access-d1/index.md
> +To ensure that the API Key is secure, you will add it as a [secret](/workers/configuration/secrets/). To do so, create a `.dev.vars` file in the root directory. Add your API key in the file as follow
The API Key is used in the code. In the deployment setup too it is mentioned how to push the secret to production. Is there something I am missing?

2024-07-31 09:53 UTC, harshil1712 commented
@vy-ton agree that we should host the full code somewhere. Let check the process here. I'll update the tutorial with the link.

2024-08-06 10:30 UTC, harshil1712 commented
Made all the suggested changes and have added link to the finished GitHub repo.

2024-08-23 10:54 UTC, harshil1712 commented
Closing in favour of #16412

2024-08-23 10:54 UTC, closed without merging