Marcio/1.1.1.1 revamp
cloudflare/cloudflare-docs pull request #1585
Opened 2021-06-16 14:27 UTC by marciocloudflare

- Revamp of the structure of 1.1.1.1 docs and rewording of several docs. 
- @TownLake please give it a thorough look to see if this makes sense.

2021-06-16 15:11 UTC, TownLake requested changes

2021-06-16 15:11 UTC, TownLake commented on products/1.1.1.1/src/content/1.1.1.1-for-families/dns-over-https.md
> +DNS resolvers are like the Google Maps of the Internet, helping browsers reach the correct place.
This feels too colloquial for our developer documentation?

2021-06-16 15:11 UTC, TownLake commented on products/1.1.1.1/src/content/1.1.1.1-for-families/dns-over-https.md
> +To prevent this and secure your connections, you can send encrypted DNS queries to 1.1.1.1 over HTTPS. If you have a DNS over HTTPS compliant client (such as a router), use the following URLs to use
I'm not sure this is accurate or helpful, particularly the last sentence - if they don't see a place to input or configure DoH, it might still be compliant but just hard to configure?

2021-06-16 15:11 UTC, TownLake commented on products/1.1.1.1/src/content/1.1.1.1-for-families/dns-over-https.md
> +To block all malware use the following URL:
we should add more context; i.e. Cloudflare offers a service that categorizes destinations on the Internet based on the potential that they pose malware, phishing, or other types of security risks... When enabled, we will block resolution...

2021-06-16 15:11 UTC, TownLake commented on products/1.1.1.1/src/content/encrypted-dns/dns-over-https/index.md
> +If you are building a mobile application, browser, operating system, IoT device or router, you can choose for your users to use the DNS over HTTPS (DoH) endpoint that Cloudflare offers instead of sen
This first sentence is confusing; reads like "if you are building a mobile app or an operating system" which is not really the target audience. if a user wants DoH, they can use this (regardless of why they might want it, but building an app is not necessarily a motivator)

2021-06-16 15:11 UTC, TownLake commented on products/1.1.1.1/src/content/encrypted-dns/index.md
> +DoH uses port 443, which is the standard HTTPS traffic port, to wrap the DNS request in an HTTPS request. It uses HTTPS and HTTP/2 to encrypt traffic at the application layer. With DoH, DNS queries a
Why is the network visibility different?

2021-06-16 15:11 UTC, TownLake commented on products/1.1.1.1/src/content/index.md
> +1.1.1.1 is a fast and private way to browse the Internet. It is a DNS resolver — meaning it is kind of like Google Maps for your computer, in that it translates places (like `cloudflare.com`) into ad
please stop referencing google maps

2021-06-17 09:05 UTC, marciocloudflare commented on products/1.1.1.1/src/content/1.1.1.1-for-families/dns-over-https.md
> +To prevent this and secure your connections, you can send encrypted DNS queries to 1.1.1.1 over HTTPS. If you have a DNS over HTTPS compliant client (such as a router), use the following URLs to use
Do you mean you don't feel these 2 paragraphs are accurate / useful or just the last sentence?

2021-06-17 09:18 UTC, marciocloudflare commented on products/1.1.1.1/src/content/encrypted-dns/index.md
> +DoH uses port 443, which is the standard HTTPS traffic port, to wrap the DNS request in an HTTPS request. It uses HTTPS and HTTP/2 to encrypt traffic at the application layer. With DoH, DNS queries a
I'm not sure. I copied this from our Teams glossary regarding DoH and DoT. I'll simplify this and remove extra wording.

2021-06-17 10:12 UTC, marciocloudflare commented on products/1.1.1.1/src/content/1.1.1.1-for-families/dns-over-https.md
> +To block all malware use the following URL:
Added more context in 1.1.1.1 for Families index

2021-08-04 13:36 UTC, closed without merging