[Email Security] Zero Trust Email Security documentation
cloudflare/cloudflare-docs pull request #15928
Opened 2024-08-01 09:51 UTC by Maddy-Cloudflare

### Summary

This PR creates the documentation for the Zero Trust, Email Security product.

2024-08-01 11:15 UTC, marciocloudflare commented on content/cloudflare-one/_partials/email-security/_detect-phish.md
> +| Name Spoof Attacks / Executive Attacks [(BEC)](https://www.cloudflare.com/en-gb/learning/email-security/business-email-compromise-bec/) | Campaigns targeting executives and high-value targets withi
Consider linking this to the BEC part of the dev docs, instead of the marketing website

2024-08-01 14:22 UTC, marciocloudflare requested changes

2024-08-01 14:22 UTC, marciocloudflare commented on content/cloudflare-one/_partials/email-security/_detect-phish.md
> +| Fileless / Linkless campaigns [(BEC)](https://www.cloudflare.com/en-gb/learning/email-security/business-email-compromise-bec/)  | Typically BEC campaigns with an offline call to action (call me, wi
Consider linking this to the BEC part of the dev docs, instead of the marketing website

2024-08-01 14:22 UTC, marciocloudflare commented on content/cloudflare-one/_partials/email-security/_detect-phish.md
> +| IP-based Spam | Volume-based, large scale spam campaigns primarily originating from compromised IP address spaces or botnets. | Sender and IP reputation, history, and volume analysis. |
```suggestion
| IP-based spam | Volume-based, large scale spam campaigns primarily originating from compromised IP address spaces or botnets. | Sender and IP reputation, history, and volume analysis. |
```

2024-08-01 14:22 UTC, marciocloudflare commented on content/cloudflare-one/_partials/email-security/_detect-phish.md
> +| Content-based Spam | Commodity spam largely focused on selling wares. | Sender reputation, history, volume analysis, and message content analysis for commercial intent. |
```suggestion
| Content-based spam | Commodity spam largely focused on selling wares. | Sender reputation, history, volume analysis, and message content analysis for commercial intent. |
```

2024-08-01 14:22 UTC, marciocloudflare commented on content/cloudflare-one/_partials/email-security/_detect-phish.md
> +| Web Phishing  | Directly originated or targeted through web (for example, LinkedIn, Malvertizing, and more). | Web and DNS service and Network device integrations, like web proxies and Firewalls. |
```suggestion
| Web phishing  | Directly originated or targeted through web (for example, LinkedIn, Malvertizing, and more). | Web and DNS service and network device integrations, like web proxies and firewalls. |
```

2024-08-01 14:22 UTC, marciocloudflare commented on content/cloudflare-one/_partials/email-security/_detect-phish.md
> +| Mobile Phishing | Remote employee getting phished while outside the corporate network. | Employee email protection and web and DNS services enforcement in remote users (typically through an MDM int
```suggestion
| Mobile phishing | Remote employee getting phished while outside the corporate network. | Employee email protection and web and DNS services enforcement in remote users (typically through an MDM integration or an always-on VPN solution). |
```

2024-08-01 14:22 UTC, marciocloudflare commented on content/cloudflare-one/_partials/email-security/_detect-phish.md
> +| Network Phishing | C2 communications for lateral spread within the network or malicious phish downloaded from an external host. Typically seen when an end user gets infected outside the organizatio
```suggestion
| Network phishing | C2 communications for lateral spread within the network or malicious phish downloaded from an external host. Typically seen when an end user gets infected outside the organization, comes back into the network and the C2 hosts uses the infected endpoint to download the implant based on the IP address space it is now resident in. | Network device integrations (firewalls) and API-based integrations within existing orchestration services. |
```

2024-08-01 14:22 UTC, marciocloudflare commented on content/cloudflare-one/email-security/_index.md
> +# Email Security
Isn't the name of the product Cloud Email Security?

2024-08-01 14:22 UTC, marciocloudflare commented on content/cloudflare-one/email-security/_index.md
> +Email Security secures your email inbox with [API-first Email Security](/cloudflare-one/email-security/setup/api-deployment/). Email Security integrates with your existing email provider, and it bloc
```suggestion
Email Security secures your email inbox with [API-first email security](/cloudflare-one/email-security/setup/api-deployment/). Email Security integrates with your existing email provider, and blocks phishing attacks, malware, [Business Email Compromise](https://www.cloudflare.com/en-gb/learning/email-security/business-email-compromise-bec/) attacks, and vendor email fraud.
```

2024-08-01 14:22 UTC, marciocloudflare commented on content/cloudflare-one/email-security/_index.md
> +Email Security secures your email inbox with [API-first Email Security](/cloudflare-one/email-security/setup/api-deployment/). Email Security integrates with your existing email provider, and it bloc
I think the second instance of Email Security is a regular noun, not the name of the product; that's why I lowercased it

2024-08-01 14:22 UTC, marciocloudflare commented on content/cloudflare-one/email-security/_index.md
> +- Automatically move messages to specific folders based on a certain disposition.
Consider linking "on a certain disposition" to the disposition pages where we explain what they are.

2024-08-01 14:22 UTC, marciocloudflare commented on content/cloudflare-one/email-security/_index.md
> +- Generate a Phishing Risk Assessment report and submit phishes.
I'm not sure about `submit phishes`. Do people say it like that? To me it'd sound better `submit email phishing reports` or something like it

2024-08-01 14:22 UTC, marciocloudflare commented on content/cloudflare-one/email-security/auto-moves.md
> +title: Auto-moves
```suggestion
title: Auto-move events
```

2024-08-01 14:22 UTC, marciocloudflare commented on content/cloudflare-one/email-security/auto-moves.md
> +title: Auto-moves
I think `Auto-moves` is less informative than `Auto-move events`; hence my suggestion

2024-08-01 14:22 UTC, marciocloudflare commented on content/cloudflare-one/email-security/auto-moves.md
> +Auto-move events are emails automatically moved to different inboxes based on the disposition Email Security assigned.
```suggestion
Auto-move events are events where emails are automatically moved to different inboxes based on the disposition Email Security assigned to them.
```

2024-08-01 14:22 UTC, marciocloudflare commented on content/cloudflare-one/email-security/auto-moves.md
> +Auto-move events are emails automatically moved to different inboxes based on the disposition Email Security assigned.
Consider linking "disposition" to the page where we explain what they are

2024-08-01 14:22 UTC, marciocloudflare commented on content/cloudflare-one/_partials/email-security/_detect-phish.md
> +## Sample attack types and detections
Consider changing this table to something else. We decided recently to avoid big tables bc they don't render correctly on mobile --> https://github.com/cloudflare/cloudflare-docs/pull/15300/files

2024-08-01 14:22 UTC, marciocloudflare commented on content/cloudflare-one/email-security/auto-moves.md
> +   - **Soft delete - user recoverable**: Moves the message to the user’s 'Recoverable Items - Deleted'. Messages can be recovered by the user.
```suggestion
   - **Soft delete - user recoverable**: Moves the message to the user’s **Recoverable Items - Deleted** folder. Messages can be recovered by the user.
```

2024-08-01 14:22 UTC, marciocloudflare commented on content/cloudflare-one/email-security/auto-moves.md
> +   - **Soft delete - user recoverable**: Moves the message to the user’s 'Recoverable Items - Deleted'. Messages can be recovered by the user.
I'm not sure what the correct formatting option is here. I'm assuming this is a special folder the user can then browse, and placed the name in bold. The single quotation marks you had don't add any formatting to the text

2024-08-01 14:22 UTC, marciocloudflare commented on content/cloudflare-one/email-security/detection-settings/additional-detections.md
> +- ACH change from free email detection
What's ACH? Do people know what this stands for?

2024-08-01 14:22 UTC, marciocloudflare commented on content/cloudflare-one/email-security/detection-settings/additional-detections.md
> +Blank email detection detects emails with blank bodies and assign a default disposition. You can choose between Malicious and Suspicious as dispositions.
```suggestion
Blank email detection detects emails with blank bodies and assigns a default disposition. You can choose between **Malicious** and **Suspicious** as dispositions.
```

2024-08-01 14:22 UTC, marciocloudflare commented on content/cloudflare-one/email-security/detection-settings/additional-detections.md
> +ACH change from free email detection detects payroll inquiries or change requests from free email domains and assign a default disposition. You can choose between malicious and suspicious as disposit
```suggestion
ACH change from free email detection detects payroll inquiries or change requests from free email domains and assigns a default disposition. You can choose between malicious and suspicious as dispositions.
```

2024-08-01 14:22 UTC, marciocloudflare commented on content/cloudflare-one/email-security/detection-settings/allow-policies.md
> +     - **(Recommended) Sender verification**: This option enforces DMARC, SPF, or DKIM authentication. If you choose to toggle on this option, Email Security will only honor policies that pass authen
```suggestion
     - **(Recommended) Sender verification**: This option enforces DMARC, SPF, or DKIM authentication. If you choose to enable this option, Email Security will only honor policies that pass authentication.
```

2024-08-01 14:22 UTC, marciocloudflare commented on content/cloudflare-one/email-security/auto-moves.md
> +7. Assign actions based on malicious, spoof, suspicious, spam, and bulk dispositions. Select among:
Sometimes these are uppercase, others lowercase. Maybe lowercased them all?

2024-08-01 14:22 UTC, marciocloudflare commented on content/cloudflare-one/email-security/auto-moves.md
> +   - **(Recommended) Post-delivery response**: Toggling this option allows Email Security to rescan delivered emails at multiple time intervals for previously unknown phishing sites or campaigns.
```suggestion
   - **(Recommended) Post-delivery response**: Enabling this option allows Email Security to rescan delivered emails at multiple time intervals for previously unknown phishing sites or campaigns.
```

2024-08-01 14:22 UTC, marciocloudflare commented on content/cloudflare-one/email-security/auto-moves.md
> +   - **(Recommended) Phish submission response**: Toggling this option allows Email Security to move emails that your users reported as phishing and Email Security determined to be malicious.
```suggestion
   - **(Recommended) Phish submission response**: Enabling this option allows Email Security to move emails that your users reported as phishing and Email Security determined to be malicious.
```

2024-08-01 14:22 UTC, marciocloudflare commented on content/cloudflare-one/email-security/detection-settings/additional-detections.md
> +1. On the **Edit additional detections** page, select **ACH change from free email detection** toggle.
```suggestion
1. On the **Edit additional detections** page, enable **ACH change from free email detection**.
```

2024-08-01 14:22 UTC, marciocloudflare commented on content/cloudflare-one/email-security/detection-settings/additional-detections.md
> +1. On the **Edit additional detections** page, select **HTML attachment email detection** toggle.
```suggestion
1. On the **Edit additional detections** page, enable **HTML attachment email detection**.
```

2024-08-01 14:22 UTC, marciocloudflare commented on content/cloudflare-one/email-security/detection-settings/allow-policies.md
> +   - **Uploading an allow policy**: Upload a file no larger than 150 KB. The file cannot contain other fields, and the first row must be a header row.
This doesn't explain what fields the file can't have. I'm not sure it's clear enough

2024-08-01 14:22 UTC, marciocloudflare commented on content/cloudflare-one/email-security/detection-settings/blocked-senders.md
> +   - **Upload blocked sender list**: Upload a file no larger than 150 KB. The file cannot contain other fields, and the first row must be a header row.
Same comment about what fields the file cannot contain

2024-08-01 14:22 UTC, marciocloudflare commented on content/cloudflare-one/email-security/detection-settings/impersonation-registry.md
> +The impersonation registry contains all variables of potential emails. If there is an email that is on the impersonation registry not listed as an alternative email address, that email will be report
I'm not sure what this first sentence means. 
- What does it mean to contain all variables? What type of variables and related to what?
- What potential emails? The emails of users likely to be impersonated?

2024-08-01 14:22 UTC, marciocloudflare commented on content/cloudflare-one/email-security/detection-settings/impersonation-registry.md
> +3. Select **Settings** > **Impersonation registry** tab.
```suggestion
3. Select **Settings** > **Impersonation registry**.
```

2024-08-01 14:22 UTC, marciocloudflare commented on content/cloudflare-one/email-security/detection-settings/impersonation-registry.md
> +       - **Select directory**: Choose MS directory.
Is `MS` the only option available to users? Does it appear in the UI? If not, what does `MS` mean?

2024-08-01 14:22 UTC, marciocloudflare commented on content/cloudflare-one/email-security/detection-settings/impersonation-registry.md
> +Administrators can edit the name and emails of users if they are from the Email Security directory. Administrators from other integrated directories cannot edit the name and the primary emails of use
In the first sentence, does it mean that:
- Admins can edit if **admins** belong to the Email Security directory OR
- Admins can edit if **users** belong to the Email Security directory?
It's not entirely clear which one it is

2024-08-01 14:22 UTC, marciocloudflare commented on content/cloudflare-one/email-security/auto-moves.md
> +pcx_content_type: concept
```suggestion
pcx_content_type: how-to
```

2024-08-01 14:22 UTC, marciocloudflare commented on content/cloudflare-one/email-security/auto-moves.md
> +pcx_content_type: concept
Concepts are more in-depth; this seems more a how to

2024-08-01 14:22 UTC, marciocloudflare commented on content/cloudflare-one/email-security/detection-settings/_index.md
> +pcx_content_type: concept
```suggestion
pcx_content_type: navigation
```

2024-08-01 14:22 UTC, marciocloudflare commented on content/cloudflare-one/email-security/detection-settings/additional-detections.md
> +pcx_content_type: concept
```suggestion
pcx_content_type: how-to
```

2024-08-01 14:22 UTC, marciocloudflare commented on content/cloudflare-one/email-security/detection-settings/allow-policies.md
> +pcx_content_type: concept
```suggestion
pcx_content_type: how-to
```

2024-08-01 14:22 UTC, marciocloudflare commented on content/cloudflare-one/email-security/detection-settings/blocked-senders.md
> +pcx_content_type: concept
```suggestion
pcx_content_type: how-to
```

2024-08-01 14:22 UTC, marciocloudflare commented on content/cloudflare-one/email-security/detection-settings/impersonation-registry.md
> +pcx_content_type: concept
```suggestion
pcx_content_type: how-to
```

2024-08-01 14:22 UTC, marciocloudflare commented on content/cloudflare-one/email-security/detection-settings/trusted-domains.md
> +pcx_content_type: concept
```suggestion
pcx_content_type: how-to
```

2024-08-01 14:22 UTC, marciocloudflare commented on content/cloudflare-one/email-security/directories/_index.md
> +pcx_content_type: concept
```suggestion
pcx_content_type: how-to
```

2024-08-01 14:22 UTC, marciocloudflare commented on content/cloudflare-one/email-security/directories/manage-es-directories.md
> +pcx_content_type: concept
```suggestion
pcx_content_type: how-to
```

2024-08-01 14:22 UTC, marciocloudflare commented on content/cloudflare-one/email-security/directories/manage-ms-directories.md
> +## Manage directory's users
```suggestion
## Manage users in your directory
```

2024-08-01 14:22 UTC, marciocloudflare commented on content/cloudflare-one/email-security/directories/manage-ms-directories.md
> +## Manage directory's group
```suggestion
## Manage groups in your directory
```

2024-08-01 14:22 UTC, marciocloudflare commented on content/cloudflare-one/email-security/directories/manage-ms-directories.md
> +- Under **Display name**, select the user you want to edit. From here, you can either:
Where, exactly? This is really far away from the beginning of the page where you explain how to get to MS directories, but even so I can't tell which option this pertains to. Is it the Users directory?

2024-08-01 14:22 UTC, marciocloudflare commented on content/cloudflare-one/email-security/directories/manage-ms-directories.md
> +Select the **Impersonation registry** dropdown, and choose one of the following:
I think for all these options you need more steps telling folks where to go. It's becoming really difficult to tell where these options are, and the page is really _really_ long

2024-08-01 14:22 UTC, marciocloudflare commented on content/cloudflare-one/email-security/directories/manage-ms-directories.md
> +pcx_content_type: concept
```suggestion
pcx_content_type: how-to
```

2024-08-01 14:22 UTC, marciocloudflare commented on content/cloudflare-one/email-security/phish-guard.md
> +pcx_content_type: concept
```suggestion
pcx_content_type: how-to
```

2024-08-01 14:22 UTC, marciocloudflare commented on content/cloudflare-one/email-security/phish-guard.md
> +7. Reports
```suggestion
- ROI Calculator
- Insider threat defense
- Email threat hunting
- Actions
- API Status
- Managed email security operations
- Reports
```

2024-08-01 14:22 UTC, marciocloudflare commented on content/cloudflare-one/email-security/phish-guard.md
> +7. Reports
Since these aren't steps the customer has to go through, I think it's better to have an unordered list

2024-08-01 14:22 UTC, marciocloudflare commented on content/cloudflare-one/email-security/phish-guard.md
> +  - **Details**: Details displays information such as delivery disposition, current disposition, ES Alert ID, Message-ID, Timestamp, Subject, and Attempted Fraudulent Amount.
```suggestion
  - **Details**: Displays information such as delivery disposition, current disposition, ES Alert ID, Message-ID, Timestamp, Subject, and Attempted Fraudulent Amount.
```

2024-08-01 14:22 UTC, marciocloudflare commented on content/cloudflare-one/email-security/phish-guard.md
> +  - **Details**: Details displays information such as delivery disposition, current disposition, ES Alert ID, Message-ID, Timestamp, Subject, and Attempted Fraudulent Amount.
To avoid having "displays" twice in a row

2024-08-01 14:22 UTC, marciocloudflare commented on content/cloudflare-one/email-security/reference/dispositions-and-attributes.md
> +Any traffic that flows through Email Security is given a final disposition, which represents our evaluation of that specific message. Each message will only receive one disposition header so your org
```suggestion
Any traffic that flows through Email Security is given a final disposition, which represents our evaluation of that specific message. Each message will receive only one disposition header, so your organization can take clear and specific actions on different message types.
```

2024-08-01 14:22 UTC, marciocloudflare commented on content/cloudflare-one/email-security/reference/dispositions-and-attributes.md
> +| `BULK` | Traffic associated with [Graymail](https://en.wikipedia.org/wiki/Graymail_(email)), that fall in between the definitions of `SPAM` and `SUSPICIOUS`. For example, a marketing email that int
```suggestion
| `BULK` | Traffic associated with [Graymail](https://en.wikipedia.org/wiki/Graymail_(email)), that falls in between the definitions of `SPAM` and `SUSPICIOUS`. For example, a marketing email that intentionally obscures its unsubscribe link. | Monitor or tag |
```

2024-08-01 14:22 UTC, marciocloudflare commented on content/cloudflare-one/email-security/setup/api-deployment/_index.md
> +## Limitations
Many months ago, the team wanted to revise these Benefits/Limiations section. Just calling this out bc I'm not sure if they still wanted to or no

2024-08-01 14:22 UTC, marciocloudflare commented on content/cloudflare-one/email-security/setup/api-deployment/office365-api.md
> +pcx_content_type: get-started
```suggestion
pcx_content_type: how-to
```

2024-08-01 14:22 UTC, marciocloudflare commented on content/cloudflare-one/insights/email-monitoring/_index.md
> +pcx_content_type: concept
```suggestion
pcx_content_type: how-to
```

2024-08-01 14:22 UTC, marciocloudflare commented on content/cloudflare-one/insights/email-monitoring/_index.md
> +7.  Detection settings metrics
```suggestion
- Email activity
- Disposition evaluation
- Detection details
- Impersonations
- Phish submissions
- Auto-move events
- Detection settings metrics
```

2024-08-01 14:22 UTC, marciocloudflare commented on content/cloudflare-one/insights/email-monitoring/_index.md
> +7.  Detection settings metrics
There's an opportunity here to link to other pages from the docs, such as disposition and auto-moves, for example

2024-08-01 14:22 UTC, marciocloudflare commented on content/cloudflare-one/insights/email-monitoring/_index.md
> +To view the live number of email scanned and dispositions scanned, select the toggle to **Live mode**.
```suggestion
To view the live number of email scanned and dispositions scanned, enable **Live mode**.
```

2024-08-01 14:22 UTC, marciocloudflare commented on content/cloudflare-one/insights/email-monitoring/_index.md
> +- **Spoof**: Traffic associated with phishing campaigns that is either non-compliant with your email authentication policies ([SPF](https://www.cloudflare.com/en-gb/learning/dns/dns-records/dns-spf-r
```suggestion
- **Spoof**: Traffic associated with phishing campaigns that is either non-compliant with your email authentication policies ([SPF](https://www.cloudflare.com/en-gb/learning/dns/dns-records/dns-spf-record/), [DKIM](https://www.cloudflare.com/en-gb/learning/dns/dns-records/dns-dkim-record/), [DMARC](https://www.cloudflare.com/en-gb/learning/dns/dns-records/dns-dmarc-record/)) or has mismatching `Envelope From` and `Header From` values.
```

2024-08-01 14:22 UTC, marciocloudflare commented on content/cloudflare-one/insights/email-monitoring/_index.md
> +Disposition evaluation displays the following dispositions:
Since everything in this list duplicates what you have in the table in Dispositions and attributes, consider creating a _partial file to avoid having to track changes to both these places.

2024-08-01 14:22 UTC, marciocloudflare commented on content/cloudflare-one/insights/email-monitoring/_index.md
> +To view impersonated users, select **View impersonated users**.
Just to double-check: did you want this to be a list or a paragraph? Right now this is being rendered as a single paragraph bc in Markdown sentences without spaces between them are glued into a single paragraph

2024-08-01 14:22 UTC, marciocloudflare commented on content/cloudflare-one/insights/email-monitoring/_index.md
> +Auto-move events are emails moved to different inboxes based on the disposition Email Security assigned.
Opportunity to link "disposition" to the respective page explaining what this is

2024-08-01 14:22 UTC, marciocloudflare commented on content/cloudflare-one/insights/email-monitoring/_index.md
> +- **Allowed traffic**: Traffic that Email Security will exempt emails that match certain patterns from normal detection scanning.
I don't understand what Allowed traffic is.

2024-08-01 14:22 UTC, marciocloudflare commented on content/cloudflare-one/email-security/reference/dispositions-and-attributes.md
> +### Available values
Consider transforming this table into something else as tables don't work on mobile (same comment as above, somewhere)

2024-08-01 14:22 UTC, marciocloudflare commented on content/cloudflare-one/insights/email-monitoring/phish-submissions.md
> +5. At the bottom of the page, under **Phish submission**, select **View**.
```suggestion
5. Under **Phish submission**, select **View**.
```

2024-08-01 14:22 UTC, marciocloudflare commented on content/cloudflare-one/insights/email-monitoring/phish-submissions.md
> +5. At the bottom of the page, under **Phish submission**, select **View**.
Bottom of the page might change, and we should avoid these types of sentences.

Also, to submit phish we select the option `View`?

2024-08-01 14:22 UTC, marciocloudflare commented on content/cloudflare-one/insights/email-monitoring/phish-submissions.md
> +PhishNet is an add-in button that helps users to submit directly to Email Security {{<glossary-tooltip term_id="phishing">}}phish{{</glossary-tooltip>}} samples missed by Email Security's detection.
`PhishNet avoids the previous process...`--> you might want to delete this. It refers to a previous process that does not exist for this product, which is new. If it's new, it doesn't make sense to refer to "the previous process of".

2024-08-01 14:22 UTC, marciocloudflare commented on content/cloudflare-one/insights/email-monitoring/phish-submissions.md
> +4. Paste the above URL, verify and complete the wizard.
```suggestion
To set up PhishNet:

1. Log in to the Microsoft admin panel. Go to **Microsoft 365 admin center** > **Settings** > **Integrated Apps**.
2. Select **Upload custom apps**.
3. Choose **Provide link to manifest file** and paste the the following URL:
    ```txt
    https://phishnet-o365.area1cloudflare-webapps.workers.dev?clientId=ODcxNDA0MjMyNDM3NTA4NjQwNDk1Mzc3MDIxNzE0OTcxNTg0Njk5NDEyOTE2NDU5ODQyNjU5NzYzNjYyNDQ3NjEwMzIxODEyMDk1NQ
    ```
4. Verify and complete the wizard.
```

2024-08-01 14:22 UTC, marciocloudflare commented on content/cloudflare-one/insights/email-monitoring/phish-submissions.md
> +pcx_content_type: concept
```suggestion
pcx_content_type: how-to
```

2024-08-01 14:22 UTC, marciocloudflare commented on content/cloudflare-one/insights/email-monitoring/phishing-report.md
> +pcx_content_type: concept
```suggestion
pcx_content_type: how-to
```

2024-08-01 14:22 UTC, marciocloudflare commented on content/cloudflare-one/insights/email-monitoring/phishing-report.md
> +5. Select **Generate and download** at the bottom.
```suggestion
5. Select **Generate and download**.
```

2024-08-01 14:22 UTC, marciocloudflare commented on content/cloudflare-one/insights/email-monitoring/search-email.md
> +pcx_content_type: concept
```suggestion
pcx_content_type: how-to
```

2024-08-01 14:22 UTC, marciocloudflare commented on content/cloudflare-one/insights/email-monitoring/search-email.md
> +5. Choose **Popular**, **Regular**, **Advanced** screen methods.
```suggestion
5. Choose between **Popular**, **Regular**, and **Advanced** screen methods. Refer to the explanation below to learn what each method does.
```

2024-08-01 14:22 UTC, marciocloudflare commented on content/cloudflare-one/insights/email-monitoring/search-email.md
> +   * **Spam emails**: Emails assigned to the SPAM disposition within the last 7 days.
```suggestion
   * **Moved emails**: View emails automatically or manually moved within the last seven days.
   * **Reclassified emails**: Emails that had their disposition reclassified within the last seven days.
   * **Malicious emails**: Emails assigned the malicious disposition within the last seven days.
   * **Spoof emails**: Emails assigned the spoof disposition within the last seven days.
   * **Suspicious emails**: Emails assigned the suspicious disposition within the last seven days.
   * **Spam emails**: Emails assigned to the spam disposition within the last seven days.
```

2024-08-01 14:22 UTC, marciocloudflare commented on content/cloudflare-one/insights/email-monitoring/search-email.md
> +To include all emails as part of the search, select the toggle **Include all mail** at the bottom.
```suggestion
To include all emails as part of the search, enable **Include all mail**.
```

2024-08-01 14:22 UTC, marciocloudflare commented on content/cloudflare-one/insights/email-monitoring/search-email.md
> +The advanced screen criteria gives you the option to narrow message results based on specific criteria. The advanced screen has several options (such as keywords, Subject keywords, sender domain, and
```suggestion
The advanced screen criteria gives you the option to narrow message results based on specific criteria. The advanced screen has several options (such as keywords, subject keywords, sender domain, and more) to scan your inbox.
```

2024-08-01 14:22 UTC, marciocloudflare commented on content/cloudflare-one/insights/email-monitoring/search-email.md
> +To include all emails as part of the search, select the toggle **Include all mail** at the bottom.
```suggestion
To include all emails as part of the search, enable **Include all mail**.
```

2024-08-01 14:22 UTC, marciocloudflare commented on content/cloudflare-one/insights/email-monitoring/search-email.md
> +1. On the **Investigation** page, under **Your matching messages**, select the message you want to reclassify.
Is this still in the search email page?

2024-08-01 14:22 UTC, marciocloudflare commented on content/cloudflare-one/insights/email-monitoring/search-email.md
> +   * **Soft delete (user recoverable)**: Move messages to the user's Deleted Items folder. This option is for Microsoft only.
`is for Microsoft only`--> Microsoft products? Microsoft Exchange? Microsoft 365? Not clear what this means

2024-08-01 14:22 UTC, marciocloudflare commented on content/cloudflare-one/insights/email-monitoring/search-email.md
> +2. Select **Export messages** on the pop-up message. You can only export up to 1,000 rows from the dashboard. To export all matching messages, use the API.
How can users use the API to export messages? Do we have this somewhere?

2024-08-01 14:22 UTC, marciocloudflare commented on content/cloudflare-one/insights/email-monitoring/search-email.md
> +      - **View similar emails**: Find similar emails based on the ```value_edf_hash``` (Electronic Detection Fingerprint hash).
```suggestion
      - **View similar emails**: Find similar emails based on the `value_edf_hash` (Electronic Detection Fingerprint hash).
```

2024-08-01 14:22 UTC, marciocloudflare commented on content/cloudflare-one/roles-permissions.md
> +4. Mail trace
```suggestion
- Details
- Action log
- Raw message
- Mail trace
```

2024-08-01 14:22 UTC, marciocloudflare commented on content/cloudflare-one/roles-permissions.md
> +1. **Threat type**:  Add a link where I explain the most common threat types.
You forgot to add a link here and rephrase the sentence

2024-08-01 14:22 UTC, marciocloudflare commented on content/cloudflare-one/roles-permissions.md
> +5. **Reasons for detections**: Description of why the email was deemed as Malicious, Suspicious, or Spam.
Dispositions are sometimes uppercase, and sometimes lowercase. Please choose one

2024-08-05 13:06 UTC, Maddy-Cloudflare commented on content/cloudflare-one/_partials/email-security/_detect-phish.md
> +| Fileless / Linkless campaigns [(BEC)](https://www.cloudflare.com/en-gb/learning/email-security/business-email-compromise-bec/)  | Typically BEC campaigns with an offline call to action (call me, wi
@marciocloudflare do you mean [this part](https://developers.cloudflare.com/email-security/email-configuration/enhanced-detections/business-email-compromise/) of the dev docs? If so, I wouldn't want to redirect the user to the Area 1 docs.

2024-08-05 13:06 UTC, Maddy-Cloudflare commented on content/cloudflare-one/email-security/_index.md
> +# Email Security
Nope, it has been changed to Email Security now. :)

2024-08-05 13:06 UTC, Maddy-Cloudflare commented on content/cloudflare-one/email-security/detection-settings/impersonation-registry.md
> +       - **Select directory**: Choose MS directory.
Good point! For now, I believe there will `Email Security directory`, and `MS directory`. In the UI it appears as `MS directory`. I'm going to change this to just say `Select your directory` to keep it generic.

2024-08-05 13:06 UTC, Maddy-Cloudflare commented on content/cloudflare-one/insights/email-monitoring/_index.md
> +To view impersonated users, select **View impersonated users**.
List

2024-08-05 13:06 UTC, Maddy-Cloudflare commented on content/cloudflare-one/insights/email-monitoring/phish-submissions.md
> +5. At the bottom of the page, under **Phish submission**, select **View**.
![Screenshot 2024-08-02 at 14 55 12](https://github.com/user-attachments/assets/85972e4e-d6f2-46c7-a139-56bcc9ef3aba)
Yep, you select **View** and it redirects to a page where you can set up PhishNet O365

2024-08-05 13:06 UTC, Maddy-Cloudflare commented on content/cloudflare-one/insights/email-monitoring/search-email.md
> +1. On the **Investigation** page, under **Your matching messages**, select the message you want to reclassify.
Yes! Initially, I called this page **Investigation**, but since it's not action-oriented, I renamed it to **Search email**. However, it appears as **Investigation** on the dashboard.

2024-08-05 13:06 UTC, Maddy-Cloudflare commented on content/cloudflare-one/email-security/directories/manage-ms-directories.md
> +Select the **Impersonation registry** dropdown, and choose one of the following:
I broke down this page further. Let me know what you think. :)

2024-08-05 13:06 UTC, Maddy-Cloudflare commented on content/cloudflare-one/insights/email-monitoring/search-email.md
> +2. Select **Export messages** on the pop-up message. You can only export up to 1,000 rows from the dashboard. To export all matching messages, use the API.
I removed this line because the API documentation is not yet available (I thought it would have been). I'll add it back once it's ready.

2024-08-05 13:06 UTC, Maddy-Cloudflare commented on content/cloudflare-one/email-security/detection-settings/impersonation-registry.md
> +Administrators can edit the name and emails of users if they are from the Email Security directory. Administrators from other integrated directories cannot edit the name and the primary emails of use
This one: 

**_Admins can edit if users belong to the Email Security directory_**

2024-08-06 13:14 UTC, marciocloudflare approved these changes

2024-08-06 13:14 UTC, marciocloudflare commented on content/cloudflare-one/_partials/email-security/_detect-phish.md
> +- **Detections applied**: Display names compared with known executive names for similarity using several matching models including the Levenshtein Algorithm, and if matched, flagged when sender is or
```suggestion
- **Detections applied**: Display names compared with known executive names for similarity using several matching models including the Levenshtein algorithm, and if matched, flagged when sender is originating from an unknown domain.
```

2024-08-06 13:14 UTC, marciocloudflare commented on content/cloudflare-one/email-security/detection-settings/_index.md
> +    title: Detection settings
```suggestion
```

2024-08-06 13:14 UTC, marciocloudflare commented on content/cloudflare-one/email-security/detection-settings/_index.md
> +    title: Detection settings
I think this isn't required bc is the same as the H1

2024-08-06 13:14 UTC, marciocloudflare commented on content/cloudflare-one/email-security/directories/manage-es-directories.md
> +1. Log in to the [Cloudflare dashboard](https://dash.cloudflare.com/).
I've just now remembered something: CF1 products that reside in this dash use the `https://one.dash.cloudflare.com/` URL. I think these how-tos should also use that URL instead of the regular dash.cloudflare.com - which means you probably have to update the steps. Sorry for thinking of this only now :/

2024-08-06 13:14 UTC, marciocloudflare commented on content/cloudflare-one/insights/email-monitoring/search-email.md
> +   * **Soft delete (user recoverable)**: Move messages to the user's Deleted Items folder. This option is for Microsoft 0365 only.
```suggestion
   * **Soft delete (user recoverable)**: Move messages to the user's Deleted Items folder. This option is for Microsoft O365 only.
```

2024-08-09 13:26 UTC, Maddy-Cloudflare commented on content/cloudflare-one/email-security/phish-guard.md
> +- Triage duration: The amount of time in minutes spent triaging the message.
L34 @marciocloudflare

2024-08-09 13:26 UTC, Maddy-Cloudflare commented on content/cloudflare-one/email-security/phish-guard.md
> +Insider threat defense on the dashboard displays **Insider leads** and **Insider reports generated**. **Insider leads** displays the number of emails identified as potential insider threat email. **I
L41 @marciocloudflare

2024-08-23 17:54 UTC, closed without merging

2024-08-23 17:54 UTC, crwaters16 commented
Closing in favor of https://github.com/cloudflare/cloudflare-docs/pull/16425, which aligns with the Starlight requirements