[Chore] Update wrangler generate to c3
cloudflare/cloudflare-docs pull request #15983
Opened 2024-08-05 15:36 UTC by kodster28

### Summary

Update an outdated command with a new version (and use the favored approach to Rust, as discussed in #15834).

2024-08-05 15:39 UTC, elithrar requested changes

2024-08-05 15:39 UTC, elithrar commented on content/cloudflare-one/policies/access/external-evaluation.md
> +   $ npm create cloudflare my-worker --template=https://github.com/cloudflare/workers-access-external-auth-example
This doesn't work. It just silently ignores the `--template` and asks you whatever it wants to ask you.

```
➜  npm create cloudflare my-worker --template=https://github.com/cloudflare/workers-access-external-auth-example

using create-cloudflare version 2.0.8

╭ Create an application with Cloudflare Step 1 of 3
│
├ Where do you want to create your application?
│ dir my-worker
│
├ What type of application do you want to create?
│ type "Hello World" script
│
├ Do you want to use TypeScript?
│ typescript yes
│
├ Copying files from "simple" template
│
╰ Application created
```

2024-08-05 15:45 UTC, kodster28 commented on content/cloudflare-one/policies/access/external-evaluation.md
> +   $ npm create cloudflare my-worker --template=https://github.com/cloudflare/workers-access-external-auth-example
Okay, should be updated by the latest 2 commits.

2024-08-05 15:47 UTC, elithrar commented on content/cloudflare-one/policies/access/external-evaluation.md
> +   $ npm create cloudflare my-worker --template=https://github.com/cloudflare/workers-access-external-auth-example
<img width="776" alt="image" src="https://github.com/user-attachments/assets/7cb625d9-6ab1-497f-841f-079763225b03">

2024-08-05 15:58 UTC, elithrar commented on content/cloudflare-one/policies/access/external-evaluation.md
> +   $ npm create cloudflare my-worker --template=https://github.com/cloudflare/workers-access-external-auth-example
From the source it looks like it is - https://github.com/cloudflare/workers-sdk/blob/eb6f249510a9d36a91d459a2c5918f65b74d2c36/packages/create-cloudflare/src/helpers/args.ts#L176-L188 - but it's not exposed in the help text and is swallowed up.

Correcting to use `npm create cloudflare use-a-template -- --template=https://github.com/cloudflare/workers-access-external-auth-example` with `--` to pass the flag to the `create-cloudflare` SDK instead of `npm` yields no change.


<img width="1112" alt="image" src="https://github.com/user-attachments/assets/e4cb0912-dfd7-4421-b309-a6c7af0d8a5c">

2024-08-05 17:41 UTC, kodster28 commented on content/cloudflare-one/policies/access/external-evaluation.md
> +   $ npm create cloudflare my-worker --template=https://github.com/cloudflare/workers-access-external-auth-example
Okay, these should be addressed now (combo of fixing the arg structure + specifying `@latest` across all our `npm create cloudflare` instances)

2024-08-06 13:45 UTC, KianNH approved these changes

2024-08-06 14:00 UTC, elithrar approved these changes

2024-08-06 14:03 UTC, merged