D1 billing observability
cloudflare/cloudflare-docs pull request #16052
Opened 2024-08-09 16:17 UTC by ShaheenFattoe8

Added a Billing Observability section to the D1 documentation and updated the pricing page with links to address questions regarding billing alerts and usage billable analytics.

2024-08-15 20:19 UTC, joshthoward commented on content/d1/platform/pricing.md
> +- How can I set up billing notifications for my Cloudflare D1 usage?
I am not a fan of documentation which describes how to walk through a web UI. If it's needed the UI is poorly designed (and I don't think it is). It is also burdensome to maintain. I would delete this.

2024-08-15 20:19 UTC, joshthoward commented on content/d1/observability/d1-billing.md
> +1. Log in to the [Cloudflare dashboard](https://dash.cloudflare.com) and select your account.
Same comment as previous.

2024-08-15 20:19 UTC, joshthoward commented on content/d1/observability/d1-billing.md
> +To set up these notifications:
Same comment as previous.

2024-08-15 20:22 UTC, joshthoward requested changes
In general I would leave this as highlighting the features within the dashboard and linking customers to relevant launch points. Most of the edits to wording I could take or leave.

2024-08-16 21:36 UTC, ShaheenFattoe8 commented on content/d1/platform/pricing.md
> +- How can I set up billing notifications for my Cloudflare D1 usage?
Makes sense, my reasoning was to maintain consistency with how other docs pages have done it - Load balancing docs do it similarly [here](https://developers.cloudflare.com/learning-paths/load-balancing/setup/next-steps/#usage-based-notifications)

2024-09-02 19:50 UTC, vy-ton commented on src/content/docs/d1/observability/billing.mdx
> +weight: 10
Page should be after `Observability > Metrics and analytics`

2024-09-02 19:50 UTC, vy-ton approved these changes

2024-09-03 15:00 UTC, kodster28 commented on content/d1/platform/pricing.md
> +- How can I set up billing notifications for my Cloudflare D1 usage?
> I am not a fan of documentation which describes how to walk through a web UI. If it's needed the UI is poorly designed (and I don't think it is). It is also burdensome to maintain. I would delete this.

Howdy @joshthoward, I actually used to be in that boat myself... but you'd be surprised at how often we get requests / feedback around this, especially for newer users and double especially when it touches areas of the UI you aren't in all the time.

The other bit I'd mention is that the maintenance cost here should be less as @Oxyjun has started as a technical writer in this space. He'll be able to help both with these updates + more broadly thinking about how we make stuff like this more maintainable. 

Happy to chat internally if you'd like more context.

2024-09-03 15:13 UTC, vy-ton commented on content/d1/platform/pricing.md
> +- How can I set up billing notifications for my Cloudflare D1 usage?
@Oxyjun Can you take over this PR and help get it across the line?

2024-09-04 08:25 UTC, Oxyjun approved these changes

2024-09-04 08:25 UTC, Oxyjun commented on src/content/docs/d1/observability/billing.mdx
> +weight: 10
```suggestion
sidebar:
  order: 11
```

2024-09-04 08:25 UTC, Oxyjun commented on src/content/docs/d1/observability/billing.mdx
> +# Billing
```suggestion

```

2024-09-04 08:29 UTC, Oxyjun approved these changes

2024-09-04 15:56 UTC, Oxyjun approved these changes

2024-09-05 13:29 UTC, joshthoward approved these changes

2024-09-05 13:29 UTC, merged