NC-5129, NC-5130: Documentation update for Turnstile (flex-width, size, feedback toggle)
cloudflare/cloudflare-docs pull request #16076
Opened 2024-08-12 13:48 UTC by worenga

2024-08-12 13:50 UTC, migueldemoura requested changes

2024-08-12 13:50 UTC, migueldemoura commented on content/turnstile/get-started/client-side-rendering.md
> +| `feedback-enabled` | `data-feedback-enabled` | Allow's Cloudflare to gather visitor feedback upon widget failure. It can be `true` (default) or `false` |
Allows

2024-08-12 13:50 UTC, migueldemoura commented on data/changelogs/turnstile.yaml
> +    - Feedback Report Toggle on Widget Configuration
Add period at the end

2024-08-12 18:28 UTC, patriciasantaana commented on data/changelogs/turnstile.yaml
> +    - Feedback Report toggle on Widget's configuration.
```suggestion
- publish_date: '2024-08-12'
  description: |-
    - Added [`[flexible]`](/turnstile/get-started/client-side-rendering/#widget-size) width widget size.
    - Added new dimensions for Turnstile's compact size.
    - Added a Feedback Report toggle on the widget's configuration.
```

2024-08-12 18:29 UTC, patriciasantaana approved these changes

2024-08-13 06:32 UTC, migueldemoura approved these changes

2024-08-13 22:59 UTC, patriciasantaana commented
@worenga closing this PR in favor of #16108 due to errors from the migration resulting in the need to remake it.

2024-08-13 22:59 UTC, closed without merging