[China Network] Update DNS options
cloudflare/cloudflare-docs pull request #16156
Opened 2024-08-14 20:35 UTC by bjin-cloudflare

### Summary

### Screenshots (optional)

### Documentation checklist

- [ ] The [documentation style guide](https://developers.cloudflare.com/style-guide/) has been adhered to.
- [ ] If a larger change - such as adding a new page- an issue has been opened in relation to any incorrect or out of date information that this PR fixes.
- [ ] Files which have changed name or location have been allocated [redirects](https://developers.cloudflare.com/pages/configuration/redirects/#per-file).

2024-08-16 23:37 UTC, bjin-cloudflare commented
@pedrosousa - would you please review this pull request for China Network?

2024-08-19 20:56 UTC, crwaters16 requested changes
Hey Bill - requested a few changes to align with our style guide. Will approve once they're addressed!

2024-08-19 20:56 UTC, crwaters16 commented on src/content/docs/china-network/concepts/china-dns.mdx
> +By default Cloudflare China Network provides a nearest-to-client nameservice. The DNS request is resolved on the data center nearest to the client out of China. And the Http request is served on the
```suggestion
Cloudflare China Network provides a nearest-to-client nameservice by default. The DNS request is resolved on the data center nearest to the client out of China, and the HTTP request is served on the data center nearest to the client. The closest Cloudflare data center outside of China is adopted for clients outside of China, and the JD Cloud data center in China is adopted for clients in China.
```

2024-08-19 20:56 UTC, crwaters16 commented on src/content/docs/china-network/concepts/china-dns.mdx
> +1. You will need to reach out to your Cloudflare sales team to enable the feature. Currently the feature can't be enabled from the Cloudflare dashboard.
```suggestion
1. Contact your account team to enable the feature. Currently, you cannot enable China Authoritative DNS in the Cloudflare dashboard.
```

^this is standard language we use throughout documentation when we ask users to contact us, just fyi!

2024-08-19 20:56 UTC, crwaters16 commented on src/content/docs/china-network/concepts/china-dns.mdx
> +| Default             | Making use of the nearest DNS server available to eyeball. |
```suggestion
| Default             | Uses the DNS server closest to the end user. |
```

2024-08-19 20:56 UTC, crwaters16 commented on src/content/docs/china-network/concepts/china-dns.mdx
> +| In-China Nameserver | Only use DNS in Mainland China operated by JD Cloud. |
```suggestion
| In-China Nameserver | Uses only DNS in China, operated by JD Cloud. |
```

2024-08-19 20:56 UTC, crwaters16 commented on src/content/docs/china-network/concepts/china-dns.mdx
> +# Default
```suggestion
```

2024-08-19 20:56 UTC, crwaters16 commented on src/content/docs/china-network/concepts/china-dns.mdx
> +# In-China Nameserver
```suggestion
## In-China Nameserver
```

2024-08-19 20:56 UTC, crwaters16 commented on src/content/docs/china-network/concepts/china-dns.mdx
> +    The current China Network supports both a [full setup](/dns/zone-setups/full-setup/) and a [partial setup](/dns/zone-setups/partial-setup/).
```suggestion
    The Cloudflare China Network currently supports domains using a [full setup](/dns/zone-setups/full-setup/) or a [partial setup](/dns/zone-setups/partial-setup/).
```

2024-08-19 20:56 UTC, crwaters16 commented on src/content/docs/china-network/concepts/china-dns.mdx
> +For further assistance, contact your sales team.
```suggestion
For further assistance, contact your account team.
```

2024-08-19 20:56 UTC, crwaters16 commented on src/content/docs/china-network/index.mdx
> +* [In-China Authoritative DNS and in-China nameservers](/china-network/concepts/china-dns/) improve the Time to First Byte (TTFB) performance.
```suggestion
* [In-China Authoritative DNS and in-China nameservers](/china-network/concepts/china-dns/) to improve the Time to First Byte (TTFB) performance.
```

2024-08-19 20:56 UTC, crwaters16 commented on src/content/docs/china-network/concepts/china-dns.mdx
> +    a. Full setup: These nameservers are displayed in the Cloudflare dashboard.
```suggestion
   * Full setup: These nameservers are displayed in the Cloudflare dashboard.
```

2024-08-19 20:56 UTC, crwaters16 commented on src/content/docs/china-network/concepts/china-dns.mdx
> +    b. Partial setup: CNAME to \<host_name\>.cdn.cloudflarecn.net.
```suggestion
    * Partial setup: CNAME to \<host_name\>.cdn.cloudflarecn.net.
```

2024-08-19 20:56 UTC, crwaters16 commented on src/content/docs/china-network/concepts/china-dns.mdx
> +            You have a zone named samplezone.cn. In this zone, you have 2 DNS records: www and media pointing to 2 different Origins. Your Authoritative DNS server needs to set
```suggestion
            You have a zone named samplezone.cn. In this zone, you have two DNS records: www and media, pointing to two different origins. Your Authoritative DNS server needs to set:
```

2024-08-19 21:58 UTC, bjin-cloudflare commented
> Hey Bill - requested a few changes to align with our style guide. Will approve once they're addressed!

Thank you Claire! All suggestions are accepted.

2024-08-20 00:37 UTC, crwaters16 approved these changes

2024-08-20 00:56 UTC, merged