[Cache] Adding Cache content from KB
cloudflare/cloudflare-docs pull request #1636
Opened 2021-06-22 16:13 UTC by dcpena

2021-07-14 16:35 UTC, kodster28 requested changes
Howdy @dcpena, went through and suggested some changes.

Most are minor, but a few ones (links out to other relevant docs + instructions w/in the UI) would be blockers to releasing this.

2021-07-14 16:35 UTC, kodster28 commented on developers.cloudflare.com/src/components/product-grid.js
> +    icon: "byoip",
You'd want to update the `icon` here.

2021-07-14 16:35 UTC, kodster28 commented on developers.cloudflare.com/src/components/product-grid.js
> +$["cache"]                = require("@cloudflare/cloudflare-brand-assets/resources/product-icons/byoip.js").pathD
Would want to update to `cache` here as well.

2021-07-14 16:35 UTC, kodster28 commented on products/cache/docs-config.js
> +  productIconKey: "magic-transit",
Want to update the icon

2021-07-14 16:35 UTC, kodster28 commented on products/cache/docs-config.js
> +    indexName: "developers-cloudflare",
```suggestion
    indexName: "",
```

2021-07-14 16:35 UTC, kodster28 commented on products/cache/docs-config.js
> +    apiKey: "b23088ab4d346409f9d3ece6606344c3",
```suggestion
    apiKey: "",
```

2021-07-14 16:35 UTC, kodster28 commented on products/cache/docs-config.js
> +    algoliaOptions: { 'facetFilters': '["project:cache"]'}
```suggestion
    algoliaOptions: { 'facetFilters': ''}
```

2021-07-14 16:35 UTC, kodster28 commented on products/cache/docs-config.js
> +    algoliaOptions: { 'facetFilters': '["project:cache"]'}
We'll want to fill in these values after the content is live + we've made a PR to the algolia repo. Then, 24 hours later we can add search (they need time to index the content).

2021-07-14 16:35 UTC, kodster28 commented on products/cache/src/content/index.md
> +Cloudflare makes customer websites faster by storing a copy of the website’s content on our servers. Content is either static or dynamic: static content is “cacheable” or eligible for caching, and dy
```suggestion
Cloudflare makes customer websites faster by storing a copy of the website’s content on our servers. Content is either static or dynamic: static content is “cacheable” or eligible for caching and dynamic content is “uncacheable” or ineligible for caching. The copies are physically closer to users, optimized to be fast, and do not require recomputing. 
```

2021-07-14 16:35 UTC, kodster28 commented on products/cache/src/content/index.md
> +- Cache level set at a zone or page rule
```suggestion
- Cache level set at a zone or [page rule](https://support.cloudflare.com/hc/articles/218411427)
```

2021-07-14 16:35 UTC, kodster28 commented on products/cache/src/content/about/edge-browser-cache-ttl.md
> +Edge Cache TTL (Time to Live) specifies how long to cache a resource in the Cloudflare edge network. Edge Cache TTL only takes effect when included in a page rule setting that sets **Cache Level** to
```suggestion
Edge Cache TTL (Time to Live) specifies how long to cache a resource in the Cloudflare edge network. Edge Cache TTL only takes effect when included in a page rule setting that sets **Cache Level** to **Cache Everything**. Edge Cache TTL is not visible in response headers and the minimum Edge Cache TTL depends on plan type.
```

2021-07-14 16:35 UTC, kodster28 commented on products/cache/src/content/about/edge-browser-cache-ttl.md
> +For more information on creating page rules, see Create page rules.
```suggestion
For more information on creating page rules, see [Create page rules](https://support.cloudflare.com/hc/articles/218411427).
```

2021-07-14 16:35 UTC, kodster28 commented on products/cache/src/content/about/edge-browser-cache-ttl.md
> +The Browser Cache TTL sets the expiration for resources cached in a visitor’s browser. By default, Cloudflare honors the cache expiration set in your Expires and `Cache-Control` headers but overrides
Should expires also be `code` since it's a header?

2021-07-14 16:35 UTC, kodster28 commented on products/cache/src/content/about/edge-browser-cache-ttl.md
> +- The value of the `Cache-Control` header from the origin web server is less than the  Browser Cache TTL Cloudflare setting or
```suggestion
- The value of the `Cache-Control` header from the origin web server is less than the Browser Cache TTL Cloudflare setting.
```

2021-07-14 16:35 UTC, kodster28 commented on products/cache/src/content/about/edge-browser-cache-ttl.md
> +- The origin web server does not send a `Cache-Control` or an Expires header.
Same question about `Expires` header.

2021-07-14 16:35 UTC, kodster28 commented on products/cache/src/content/about/edge-browser-cache-ttl.md
> +For more information on setting the Browser Cache TTL, see Set Browser Cache TTL.
Missing link to somewhere else?

2021-07-14 16:35 UTC, kodster28 commented on products/cache/src/content/about/default-cache-behavior.md
> +- Cloudflare does not cache the resource if the `Cache-Control` header is set to `private`, `no-store`, `no-cache`, `max-age=0` or if there is a cookie in the response.
```suggestion
- Cloudflare does not cache the resource if the `Cache-Control` header is set to `private`, `no-store`, `no-cache`, or `max-age=0` or if there is a cookie in the response.
```

2021-07-14 16:35 UTC, kodster28 commented on products/cache/src/content/about/default-cache-behavior.md
> +- Cloudflare caches the resource if the `Cache-Control` header is set to `public`, and the `max-age` is greater than 0 or if the `Expires` header is set to a future date.
```suggestion
- Cloudflare caches the resource in the following scenarios:
    - The `Cache-Control` header is set to `public` and the `max-age` is greater than 0.
    - The `Expires` header is set to a future date.
```

2021-07-14 16:35 UTC, kodster28 commented on products/cache/src/content/about/default-cache-behavior.md
> +Cloudflare only caches based on file extension and does not cache by MIME type. The Cloudflare CDN automatically caches files with specific file extensions but does not cache HTML by default. Additio
```suggestion
Cloudflare only caches based on file extension and not by MIME type. The Cloudflare CDN does not cache HTML by default. Additionally, Cloudflare caches a website’s robot.txt.
```

2021-07-14 16:35 UTC, kodster28 commented on products/cache/src/content/about/default-cache-behavior.md
> +To cache additional content, see Page Rules to create a rule to cache everything.
Missing link?

2021-07-14 16:35 UTC, kodster28 commented on products/cache/src/content/about/default-cache-behavior.md
> +- Caching behavior for individual URLs via Cloudflare Page Rules
Missing link?

2021-07-14 16:35 UTC, kodster28 commented on products/cache/src/content/about/default-cache-behavior.md
> +- 500MB Enterprise by default. Contact Customer Support to request a limit increase.
```suggestion
- 500MB Enterprise by default. Contact [Customer Support](https://support.cloudflare.com/hc/articles/200172476) to request a limit increase.
```

2021-07-14 16:35 UTC, kodster28 commented on products/cache/src/content/about/default-cache-behavior.md
> +If you require a larger upload, group requests smaller than the upload thresholds or upload the full resource through a grey-clouded DNS record.
```suggestion
If you require a larger upload, group requests smaller than the upload thresholds or upload the full resource through an unproxied (grey-clouded) DNS record.
```

2021-07-14 16:35 UTC, kodster28 commented on products/cache/src/content/about/default-cache-behavior.md
> +        Cloudflare generated the response and is not eligible for caching.
Wording is slightly confusing here.

2021-07-14 16:35 UTC, kodster28 commented on products/cache/src/content/about/default-cache-behavior.md
> +        The resource was found in Cloudflare’s cache but expired and served from the origin web server.
```suggestion
        The resource was found in Cloudflare’s cache but was expired and served from the origin web server.
```

2021-07-14 16:35 UTC, kodster28 commented on products/cache/src/content/about/default-cache-behavior.md
> +        The resource was served from Cloudflare’s cache but expired. Cloudflare could not contact the origin to retrieve an updated resource.
```suggestion
        The resource was served from Cloudflare’s cache but was expired. Cloudflare could not contact the origin to retrieve an updated resource.
```

2021-07-14 16:35 UTC, kodster28 commented on products/cache/src/content/about/default-cache-behavior.md
> +        The resource was served from Cloudflare’s cache but expired, and the origin web server is updating the resource. UPDATING is typically only seen for very popular cached resources.
```suggestion
        The resource was served from Cloudflare’s cache and was expired, but the origin web server is updating the resource. UPDATING is typically only seen for very popular cached resources.
```

2021-07-14 16:35 UTC, kodster28 commented on products/cache/src/content/about/default-cache-behavior.md
> +        Cloudflare does not consider the asset eligible to cache and your Cloudflare settings do not explicitly instruct Cloudflare to cache the asset.  Instead, the asset was requested from the orig
```suggestion
        Cloudflare does not consider the asset eligible to cache and your Cloudflare settings do not explicitly instruct Cloudflare to cache the asset. Instead, the asset was requested from the origin web server. Use <a href="https://support.cloudflare.com/hc/articles/218411427">Page Rules</a> to implement custom caching options.
```

2021-07-14 16:35 UTC, kodster28 commented on products/cache/src/content/about/default-cache-behavior.md
> +        Cloudflare does not consider the asset eligible to cache and your Cloudflare settings do not explicitly instruct Cloudflare to cache the asset.  Instead, the asset was requested from the orig
I `think` you can also use Railgun for dynamic content.

2021-07-14 16:35 UTC, kodster28 commented on products/cache/src/content/about/cdn-cache-control.md
> +- Return the `CDN-Cache-Control` response header which Cloudflare evaluates to make caching decisions. `Cache-Control`, if also returned by the origin, isproxied as is and does not affect caching dec
```suggestion
- Return the `CDN-Cache-Control` response header which Cloudflare evaluates to make caching decisions. `Cache-Control`, if also returned by the origin, is proxied as is and does not affect caching decisions made by Cloudflare. Additionally, `CDN-Cache-Control` is proxied downstream in case there are other CDNs between Cloudflare and the browser.
```

2021-07-14 16:35 UTC, kodster28 commented on products/cache/src/content/about/cdn-cache-control.md
> +- Return the `Cloudflare-CDN-Cache-Control` response header. This results in the same behavior as the origin returning `CDN-Cache-Control` except Cloudflare does not proxy `Cloudflare-CDN-Cache-Contr
```suggestion
- Return the `Cloudflare-CDN-Cache-Control` response header. This results in the same behavior as the origin returning `CDN-Cache-Control` except Cloudflare does not proxy `Cloudflare-CDN-Cache-Control` downstream because it’s a header only used to control Cloudflare. This option is beneficial if you want only Cloudflare to have a different caching behavior while all other downstream servers rely on `Cache-Control` or if you do not want Cloudflare to proxy the `CDN-Cache-Control` header downstream.
```

2021-07-14 16:35 UTC, kodster28 commented on products/cache/src/content/about/cdn-cache-control.md
> +An origin can:
Feel like these are some pretty meaty bullet points. Might be worth breaking up or streamlining in another way.

2021-07-14 16:35 UTC, kodster28 commented on products/cache/src/content/about/cdn-cache-control.md
> +      Stale served (seconds) in response to error
The formatting is a bit off in the table.

2021-07-14 16:35 UTC, kodster28 commented on products/cache/src/content/about/edge-browser-cache-ttl.md
> +pcx-content-type: concept
Seems like you're lacking the how-to part of these settings, like where to go in the dashboard.

2021-07-14 16:35 UTC, kodster28 commented on products/cache/src/content/about/cache-control.md
> +`Cache-Control` headers are one way web administrators can tell Cloudflare how to handle content from the origin.
```suggestion
Set `Cache-Control` headers to tell Cloudflare how to handle content from the origin. 
```

2021-07-14 16:35 UTC, kodster28 commented on products/cache/src/content/about/cache-control.md
> +When a user sends an HTTP request, the user’s request URL is matched against a list of cacheable file extensions. If the request matches an extension on this list, Cloudflare serves the resource from
Link for the cacheable file extensions?

2021-07-14 16:35 UTC, kodster28 commented on products/cache/src/content/about/cache-control.md
> +- `no-store` — Indicates any cache (i.e. a client or proxy cache) must not store any part of either the immediate request or response.
```suggestion
- `no-store` — Indicates any cache (i.e., a client or proxy cache) must not store any part of either the immediate request or response.
```

2021-07-14 16:35 UTC, kodster28 commented on products/cache/src/content/about/cache-control.md
> +When using Origin Cache-Control and setting `max-age=0`, Cloudflare prefers to cache and revalidate. With Origin Cache-Control off and `max-age=0`, Cloudflare settings bypass cache. Setting no-cache
Code formatting for `no-cache`?

2021-07-14 16:35 UTC, kodster28 commented on products/cache/src/content/about/cache-control.md
> +`proxy-revalidate` — Has the same meaning as the `must-revalidate` response directive except that it does not apply to private client caches.
```suggestion
- `proxy-revalidate` — Has the same meaning as the `must-revalidate` response directive except that it does not apply to private client caches.
```

2021-07-14 16:35 UTC, kodster28 commented on products/cache/src/content/about/cache-control.md
> +- `stale-while-revalidate=seconds` — When present in an HTTP response, indicates caches may serve the response in which it appears after it becomes stale, up to the indicated number of seconds since
Code formatting for `stale-while-revalidate` and `stale-if-error`? Also, do we need a link out to always online? https://support.cloudflare.com/hc/en-us/articles/200168436-Understanding-Cloudflare-Always-Online

2021-07-14 16:35 UTC, kodster28 commented on products/cache/src/content/about/cache-control.md
> +The `stale-if-error` directive is ignored if Always Online is enabled or if an explicit in-protocol directive is passed. Examples of explicit in-protocol directives include a `no-store` or `no-cache
Should these be broken up into sub-bullets under the stale if?

2021-07-14 16:35 UTC, kodster28 commented on products/cache/src/content/about/cache-control.md
> +- `immutable` — Indicates to clients the response body does not change over time. The resource, if unexpired, is unchanged on the server. The user should not send a conditional revalidation for it (e
```suggestion
- `immutable` — Indicates to clients the response body does not change over time. The resource, if unexpired, is unchanged on the server. The user should not send a conditional revalidation for it (e.g., `If-None-Match` or `If-Modified-Since`) to check for updates, even when the user explicitly refreshes the page. This directive has no effect on public caches like Cloudflare, but does change browser behavior.
```

2021-07-14 16:35 UTC, kodster28 commented on products/cache/src/content/about/cache-control.md
> +        <code>no-cache;</code>
```suggestion
        <code>no-cache</code>
```

2021-07-14 16:35 UTC, kodster28 commented on products/cache/src/content/about/cache-control.md
> +        Won't cache
Should these all be `Will no cache`?

2021-07-14 16:35 UTC, kodster28 commented on products/cache/src/content/about/cache-control.md
> +        Doesn't cache <code>#headers</code> values mentioned in <code>Private=#headers</code> directive.
Does not. A few of them here.

2021-07-14 16:35 UTC, kodster28 commented on products/cache/src/content/about/cache-control.md
> +        <code>Max-age</code> and <code>proxy-revalidate</code>
Is this correct? Just hard to understand the context w/o knowing much about cache.

2021-07-14 16:35 UTC, kodster28 commented on products/cache/src/content/about/cache-control.md
> +        Origin response has <code>Set-Cookie</code> header, and default cache level is used
```suggestion
        Origin response has <code>Set-Cookie</code> header and default cache level is used
```

2021-07-14 16:35 UTC, kodster28 commented on products/cache/src/content/about/cache-control.md
> +        If origin returns <code>private</code> in Cache-control then preserve it
Capitalization of cache-control?

2021-07-14 16:35 UTC, kodster28 commented on products/cache/src/content/about/cache-control.md
> +This configuration indicates the asset is fresh for 600 second. The asset can be served stale for up to an additional 30 seconds to parallel requests for the same resource while the initial synchrono
```suggestion
This configuration indicates the asset is fresh for 600 seconds. The asset can be served stale for up to an additional 30 seconds to parallel requests for the same resource while the initial synchronous revalidation is attempted.
```

2021-07-14 16:35 UTC, kodster28 commented on products/cache/src/content/about/cache-control.md
> +### Browser Cache TTL
Link to the browser cache ttl section?

2021-07-14 16:35 UTC, kodster28 commented on products/cache/src/content/about/cache-control.md
> +Edge Cache TTL Page Rules override `s-maxage` and disable revalidation directives if present. When Origin Cache-Control is enabled at Cloudflare, the original Cache-Control header passes downstream f
Link to edge cache section?

2021-07-14 16:35 UTC, kodster28 commented on products/cache/src/content/about/cache-control.md
> +### Polish
Link to Polish docs?

2021-07-14 16:35 UTC, kodster28 commented on products/cache/src/content/about/cache-control.md
> +### Gzip and Other Compression
Link to compression docs?

2021-07-14 20:52 UTC, dcpena commented on developers.cloudflare.com/src/components/product-grid.js
> +    icon: "byoip",
Done!

2021-07-14 20:52 UTC, dcpena commented on developers.cloudflare.com/src/components/product-grid.js
> +$["cache"]                = require("@cloudflare/cloudflare-brand-assets/resources/product-icons/byoip.js").pathD
Thanks! Done

2021-07-14 20:53 UTC, dcpena commented on products/cache/docs-config.js
> +  productIconKey: "magic-transit",
✔️

2021-07-14 20:53 UTC, dcpena commented on products/cache/docs-config.js
> +    indexName: "developers-cloudflare",
✔️

2021-07-14 20:53 UTC, dcpena commented on products/cache/docs-config.js
> +    apiKey: "b23088ab4d346409f9d3ece6606344c3",
✔️

2021-07-14 20:53 UTC, dcpena commented on products/cache/src/content/about/cache-control.md
> +### Browser Cache TTL
Good idea! Added

2021-07-14 20:53 UTC, dcpena commented on products/cache/src/content/about/cache-control.md
> +This configuration indicates the asset is fresh for 600 second. The asset can be served stale for up to an additional 30 seconds to parallel requests for the same resource while the initial synchrono
Ah, good eye! thank you. Fixed

2021-07-14 20:53 UTC, dcpena commented on products/cache/src/content/about/cache-control.md
> +### Polish
Added!

2021-07-14 20:55 UTC, dcpena commented on products/cache/src/content/about/cache-control.md
> +### Gzip and Other Compression
We have very little in the way of content for Gzip, so I'm not adding this in yet but making note to myself to make sure I find something to link to for this section.

2021-07-14 20:55 UTC, dcpena commented on products/cache/src/content/about/cache-control.md
> +Edge Cache TTL Page Rules override `s-maxage` and disable revalidation directives if present. When Origin Cache-Control is enabled at Cloudflare, the original Cache-Control header passes downstream f
Done!

2021-07-15 21:59 UTC, dcpena commented on products/cache/src/content/about/cache-control.md
> +        <code>Max-age</code> and <code>proxy-revalidate</code>
This was taken from a wiki and reviewed by one of the engineers, so I'm going to say yes?

2021-07-15 22:03 UTC, dcpena commented on products/cache/src/content/about/cache-control.md
> +- `stale-while-revalidate=seconds` — When present in an HTTP response, indicates caches may serve the response in which it appears after it becomes stale, up to the indicated number of seconds since
Thanks for the catch on the formatting. The content from that KB has been migrated into this PR, woohoo! In this case though, I don't think we need a link to Always Online

2021-07-15 22:12 UTC, dcpena commented on products/cache/src/content/about/cache-control.md
> +The `stale-if-error` directive is ignored if Always Online is enabled or if an explicit in-protocol directive is passed. Examples of explicit in-protocol directives include a `no-store` or `no-cache
I _think_ this one can stay as is?

2021-07-15 22:15 UTC, dcpena commented on products/cache/src/content/about/edge-browser-cache-ttl.md
> +pcx-content-type: concept
I cover the that portion in the how-to section for each of these, but I left it out here because I'm not guiding users on how to do modify anything just yet.

2021-07-15 22:16 UTC, dcpena commented on products/cache/src/content/about/cdn-cache-control.md
> +An origin can:
Yeaahhhhh, I agree. I think I'd like to cover cleaning this up in a separate ticket.

2021-07-15 22:17 UTC, dcpena commented on products/cache/src/content/about/cdn-cache-control.md
> +      Stale served (seconds) in response to error
Ah, yeah, I see what you mean. The heading wraps oddly. I'll add this to a separate cleanup ticket!

2021-07-19 21:23 UTC, kodster28 approved these changes

2021-07-19 21:23 UTC, kodster28 commented on products/cache/src/content/about/always-online.md
> +A Cloudflare crawler identifies resources to place in the Always Online cache. When Internet Archive integration is enabled, Cloudflare tells the Internet Archive what pages to crawl and how often. T
```suggestion
A Cloudflare crawler identifies resources to place in the Always Online cache. When Internet Archive integration is enabled, Cloudflare tells the Internet Archive what pages to crawl and how often. To ensure stability of service, Cloudflare limits the crawling interval. Limits vary by Cloudflare plan, and the Always Online crawler ignores robots.txt.
```

2021-07-19 21:23 UTC, kodster28 commented on products/cache/src/content/about/cache-control.md
> +Edge Cache TTL Page Rulesoverride `s-maxage` and disable revalidation directives if present. When Origin Cache-Control is enabled at Cloudflare, the original Cache-Control header passes downstream fr
```suggestion
Edge Cache TTL Page Rules override `s-maxage` and disable revalidation directives if present. When Origin Cache-Control is enabled at Cloudflare, the original Cache-Control header passes downstream from our edge even if Edge Cache TTL overrides are present. Otherwise, when Origin Cache-Control is disabled at Cloudflare (the default), Cloudflare overrides the origin cache control.
```

2021-07-19 21:23 UTC, kodster28 commented on products/cache/src/content/about/cache-keys.md
> +`$scheme` is the protocol (HTTP or HTTPS) sent to your origin web server and not the protocol received from the visitor. Therefore, setting the Cloudflare [SSL option](https://support.cloudflare.com/
```suggestion
`$scheme` is the protocol (HTTP or HTTPS) sent to your origin web server and not the protocol received from the visitor. Therefore, setting the Cloudflare [SSL option](https://support.cloudflare.com/hc/articles/200170416) influences caching decisions. For instance, Cloudflare only attempts to connect to your origin web server via HTTP when [Flexible SSL](https://developers.cloudflare.com/ssl/origin-configuration/ssl-modes#flexible) is utilized. Thus, Cloudflare serves the same cached resource for visitor requests via either HTTP or HTTPS since Flexible SSL instructs Cloudflare to connect to an origin solely over HTTP.
```

2021-07-19 21:23 UTC, kodster28 commented on products/cache/src/content/about/cache-keys.md
> +`${uri_iqs}` is replaced with the request path excluding the query string, so a request for http://example.com/file.jpg?something=123 creates the following Cache Key:
```suggestion
`${uri_iqs}` is replaced with the request path excluding the query string, so a request for `http://example.com/file.jpg?something=123` creates the following Cache Key:
```

2021-07-19 21:23 UTC, kodster28 commented on products/cache/src/content/about/cache-keys.md
> +- Headers that are already included in the custom Cache Key template
Maybe just bring that sub-bullet up to this line?

2021-07-19 21:23 UTC, kodster28 commented on products/cache/src/content/about/cache-keys.md
> +You cannot include cookies specific to Cloudflare. Cloudflare cookies are prefixed with `__cf`, e.g. `__cfuid`
```suggestion
You cannot include cookies specific to Cloudflare. Cloudflare cookies are prefixed with `__cf`, e.g. `__cflb`
```

2021-07-19 21:23 UTC, kodster28 commented on products/cache/src/content/about/cache-keys.md
> +You cannot include cookies specific to Cloudflare. Cloudflare cookies are prefixed with `__cf`, e.g. `__cfuid`
(we just deprecated `__cfuid`)

2021-07-19 21:23 UTC, kodster28 commented on products/cache/src/content/about/default-cache-behavior.md
> +To cache additional content, see [Page Rules]()/how-to/create-page-rules) to create a rule to cache everything.
```suggestion
To cache additional content, see [Page Rules](/how-to/create-page-rules) to create a rule to cache everything.
```

2021-07-19 21:23 UTC, kodster28 commented on products/cache/src/content/best-practices/customize-cache.md
> +Some possible combinations of origin web server settings and Cloudflare Page Rules include:
```suggestion
Some possible combinations of origin web server settings and Cloudflare [Page Rules](/how-to/create-page-rules) include:
```

2021-07-19 21:23 UTC, kodster28 commented on products/cache/src/content/best-practices/activate-polish.md
> +Cloudflare Image Resizing(https://support.cloudflare.com/hc/articles/360028146432) also optimizes images cached in the Cloudflare network, but is only available for Business and Enterprise users.
```suggestion
<a href="https://developers.cloudflare.com/images/">Cloudflare Image Resizing</a> also optimizes images cached in the Cloudflare network, but is only available for Business and Enterprise users.
```

2021-07-19 21:23 UTC, kodster28 commented on products/cache/src/content/best-practices/activate-polish.md
> +Images in the [cache must be purged](https://docs.google.com/document/d/1d914GxRjJol1ETq02WnJ20rCfFKKUt_Zzqumtz4Qkak/edit#heading=h.xhg8ndks215i) or expired before seeing any changes in Polish settin
wrong link?

2021-07-19 21:23 UTC, kodster28 commented on products/cache/src/content/best-practices/activate-polish.md
> +To view a list of common `Cf-Polished` statuses and how to troubleshoot them, see [Common Cf-Polished statuses](/content/reference/common-cf-published-statuses).
```suggestion
To view a list of common `Cf-Polished` statuses and how to troubleshoot them, see [Common Cf-Polished statuses](/reference/common-cf-published-statuses).
```

2021-07-19 21:23 UTC, kodster28 commented on products/cache/src/content/best-practices/always-online.md
> +- **Allow requests from Cloudflare IP addresses.** Origin servers for domains [proxied through Cloudflare](https://support.cloudflare.com/hc/articles/115005138088) receive requests from Cloudflare IP
```suggestion
- **Allow requests from Cloudflare IP addresses.** Origin servers for domains [proxied through Cloudflare](https://support.cloudflare.com/hc/articles/205195708#h_815d1b1e-74cf-4a5f-b477-e441a76ac3fd) receive requests from Cloudflare IP addresses. To avoid blocking these requests, follow the guidelines for [allowing Cloudflare IP addresses](https://support.cloudflare.com/hc/articles/201897700). When you observe the Always Online banner while your origin web server is online, your origin web server or hosting provider is likely blocking or rate limiting Cloudflare requests.
```

2021-07-19 21:23 UTC, kodster28 commented on products/cache/src/content/best-practices/always-online.md
> +- **Allow requests from Cloudflare IP addresses.** Origin servers for domains [proxied through Cloudflare](https://support.cloudflare.com/hc/articles/115005138088) receive requests from Cloudflare IP
Believe this is the right place. The old one sent me to LB docs.

2021-07-19 21:23 UTC, kodster28 commented on products/cache/src/content/best-practices/always-online.md
> +- [Custom Hostnames (SSL for SaaS)](https://support.cloudflare.com/hc/articles/217371987)
```suggestion
- [Custom Hostnames (SSL for SaaS)](https://developers.cloudflare.com/ssl/ssl-for-saas)
```

2021-07-19 21:23 UTC, kodster28 commented on products/cache/src/content/best-practices/always-online.md
> +    - DNS record propagation (can take 24-72 hours), or
```suggestion
    - DNS record propagation (can take 24-72 hours)
```

2021-07-19 21:23 UTC, kodster28 commented on products/cache/src/content/best-practices/always-online.md
> +    - Always Online has not initially crawled the website.
```suggestion
    - Always Online has not initially crawled the website. 
```
```suggestion
    - Always Online has not initially crawled the website
```

2021-07-19 21:23 UTC, kodster28 commented on products/cache/src/content/best-practices/avoid-web-poisoning.md
> +[
```suggestion

```

2021-07-19 21:23 UTC, kodster28 commented on products/cache/src/content/how-to/create-cache-keys.md
> +pcx-content-type: concept
```suggestion
pcx-content-type: how-to
```

2021-07-19 21:23 UTC, kodster28 commented on products/cache/src/content/how-to/create-page-rules.md
> +<Aside type="note" header="note">
```suggestion
<Aside type="note" header="Note">
```

2021-07-19 21:23 UTC, kodster28 commented on products/cache/src/content/how-to/create-page-rules.md
> +Consult Recommended Page Rules to Consider for ideas about the types of page rules you can create.
Either add a link or remove.

2021-07-19 21:23 UTC, kodster28 commented on products/cache/src/content/how-to/enable-always-online.md
> +- Using Cloudflare [Page Rules](/how-to/create-page-rules) to enable Always Online, or
```suggestion
- Using Cloudflare [Page Rules](/how-to/create-page-rules) to enable Always Online
```

2021-07-19 21:23 UTC, kodster28 commented on products/cache/src/content/how-to/enable-always-online.md
> +  1. Disable Always Online,
```suggestion
  1. Disable **Always Online**.
```

2021-07-19 21:23 UTC, kodster28 commented on products/cache/src/content/how-to/purge-cache.md
> +To maintain optimum site performance, Cloudflare strongly recommends using single-file (by URL) purging instead of a complete cache purge.
```suggestion
To maintain optimal site performance, Cloudflare strongly recommends using single-file (by URL) purging instead of a complete cache purge.
```

2021-07-19 21:23 UTC, kodster28 commented on products/cache/src/content/how-to/purge-cache.md
> +Reminder: We highly recommend performing single-file purges.
```suggestion
```

2021-07-19 21:23 UTC, kodster28 commented on products/cache/src/content/how-to/purge-cache.md
> +Cache-tag purging makes multi-file purging easier because you can bulk purge by adding cache-tags to your assets, such as web pages, image files, and etc. Note that Hostname and Tag purges are only a
```suggestion
Cache-tag purging makes multi-file purging easier because you can bulk purge by adding cache-tags to your assets, such as web pages, image files, and more. Note that Hostname and Tag purges are only available for Cloudflare Enterprise.
```

2021-07-19 21:23 UTC, kodster28 commented on products/cache/src/content/how-to/purge-cache.md
> +1. Add tags to the `Cache-Tag HTTP` response header from your origin web server for your web content, such as pages, static assets, and etc.
```suggestion
1. Add tags to the `Cache-Tag HTTP` response header from your origin web server for your web content, such as pages, static assets, etc.
```

2021-07-19 21:23 UTC, kodster28 commented on products/cache/src/content/how-to/purge-cache.md
> +- Removes whitespaces from the header and any before and after cache-tag names: `tag1`, `tag2` and `tag1,tag2` are considered the same.
Confused about the transition into these bullets

2021-07-19 21:23 UTC, kodster28 commented on products/cache/src/content/how-to/purge-cache.md
> +You can purge using cache-tags or hostnames via the Cloudflare API. For more information, see the API documentation for Purging by cache-tag or hostname. You can use up to 30 cache-tags in one API ca
API docs links?

2021-07-19 21:23 UTC, kodster28 commented on products/cache/src/content/how-to/purge-cache.md
> +Enterprise customers can purge their cache by URL prefix or path separators in their URL. For an example URL like https://www.example.com/foo/bar/baz/qux.jpg, valid purge requests include:
```suggestion
Enterprise customers can purge their cache by URL prefix or path separators in their URL. For an example URL like `https://www.example.com/foo/bar/baz/qux.jpg`, valid purge requests include: 
```

2021-07-19 21:23 UTC, kodster28 commented on products/cache/src/content/how-to/purge-cache.md
> +Example: If you purge `foo.com/bar`, any asset that starts with `foo.com/bar` will be purged, for example, f`oo.com/bar/baz`, `foo.com/bar?good=bad`, etc. and purging `foo.com/bar?good=bad` itself wi
```suggestion
Example: If you purge `foo.com/bar`, any asset that starts with `foo.com/bar` will be purged, for example, `foo.com/bar/baz`, `foo.com/bar?good=bad`, etc. and purging `foo.com/bar?good=bad` itself will not work.
```

2021-07-19 21:23 UTC, kodster28 commented on products/cache/src/content/how-to/set-browser-ttl.md
> +- The value of the `Cache-Control` header from the origin web server is less than the **Browser Cache TTL =setting**, or
```suggestion
- The value of the `Cache-Control` header from the origin web server is less than the **Browser Cache TTL =setting**.
```

2021-07-19 21:23 UTC, kodster28 commented on products/cache/src/content/how-to/set-browser-ttl.md
> +Unless specifically set in a Page Rule, Cloudflare does not override or `insert Cache-Control` headers if you set **Browser Cache TTL** to **Respect Existing Headers**.
```suggestion
Unless specifically set in a [Page Rule](/how-to/create-page-rules), Cloudflare does not override or `insert Cache-Control` headers if you set **Browser Cache TTL** to **Respect Existing Headers**.
```

2021-07-19 21:23 UTC, kodster28 commented on products/cache/src/content/index.md
> +- Cache level set at a zone or [page rule](https://support.cloudflare.com/hc/articles/218411427)
```suggestion
- Cache level set at a zone or [page rule](/how-to/create-page-rules)
```

2021-07-19 21:23 UTC, kodster28 commented on products/cache/src/content/reference/common-cf-published-statuses.md
> +- `not_compressed` or not_`needed`: The image was fully optimized at the origin server and no compression was applied.
```suggestion
- `not_compressed` or `not_needed`: The image was fully optimized at the origin server and no compression was applied.
```

2021-07-19 21:23 UTC, kodster28 commented on products/cache/src/content/reference/common-cf-published-statuses.md
> +- webp_bigger: Polish attempted to convert to WebP, but the image was optimized at the origin server or was created using a low quality setting. Because the WebP version doesn’t exist, the status is
```suggestion
- `webp_bigger`: Polish attempted to convert to WebP, but the image was optimized at the origin server or was created using a low quality setting. Because the WebP version doesn’t exist, the status is set on the JPEG/PNG version of the response.
```

2021-07-19 21:23 UTC, kodster28 commented on products/cache/src/content/reference/wildcard-matching.md
> +Avoid creating a redirect where the domain points to itself as the destination. A domain that points to itself can cause an infinite redirect error, which makes your site unservable to visitors.
```suggestion
Avoid creating a redirect where the domain points to itself as the destination. A domain that points to itself can cause an <a href="https://support.cloudflare.com/hc/articles/115000219871#h_af6598f6-bc1c-4a4d-ac5f-538230a704b7">infinite redirect error</a>, which makes your site inaccessible to visitors.
```

2021-07-20 21:11 UTC, dcpena commented on products/cache/src/content/how-to/purge-cache.md
> +- Removes whitespaces from the header and any before and after cache-tag names: `tag1`, `tag2` and `tag1,tag2` are considered the same.
The formatting was weird in the KB and I pasted them in a weird order. 🙃  Sorry about that, but it's fixed!

2021-07-20 21:16 UTC, merged