Add changelog
cloudflare/cloudflare-docs pull request #1639
Opened 2021-06-22 20:44 UTC by signalnerve

Scraped data from our Workers forum posts on the changelog so that we
can document it in the docs

2021-06-22 21:01 UTC, ObsidianMinor commented on products/workers/src/content/platform/changelog.md
> +
Missing [6/11](https://community.cloudflare.com/t/2021-6-11-workers-runtime-release-notes/277410) (looks like it didn't have the WorkersReleaseNotes tag)

2021-06-25 14:54 UTC, deadlypants1973 commented on products/workers/src/content/platform/changelog.md
> +- Wrangler tail now works on Durable Objects. Note that logs from long-lived WebSockets will not be visible until the WebSocket is closed.
Is wrangler tail a command or a concept? Asking for future docs purposes if it needs the backticks or not. In line 51, it is backticked

2021-06-25 14:54 UTC, deadlypants1973 commented on products/workers/src/content/platform/changelog.md
> +- request.cf is no longer missing when writing workers using modules syntax.
Same question for request.cf as the question above

2021-06-25 14:54 UTC, deadlypants1973 commented on products/workers/src/content/platform/changelog.md
> +- WebCrypto.generateKey(), when asked to generate a key pair with algorithm RSA-PSS, would instead return a key pair using algorithm RSASSA-PKCS1-v1\_5. Although the key structure is the same, the si
```suggestion
- `WebCrypto.generateKey()`, when asked to generate a key pair with algorithm RSA-PSS, would instead return a key pair using algorithm RSASSA-PKCS1-v1\_5. Although the key structure is the same, the signature algorithms differ, and therefore signatures generated using the key would not be accepted by a correct implementation of RSA-PSS, and vice versa. Since this would be a pretty obvious problem, but no one ever reported it to us, we guess that currently no one is using this functionality on Workers.
```

2021-06-25 14:54 UTC, deadlypants1973 commented on products/workers/src/content/platform/changelog.md
> +- WebCrypto: Implemented wrapKey() / unwrapKey() for AES algorithms.
Does this line need backticks?

2021-06-25 14:54 UTC, deadlypants1973 commented on products/workers/src/content/platform/changelog.md
> +- The arguments to WebSocket.close() are now optional, as the standard says they should be.
```suggestion
- The arguments to `WebSocket.close()` are now optional, as the standard says they should be.
```

2021-06-25 14:54 UTC, deadlypants1973 commented on products/workers/src/content/platform/changelog.md
> +- For Durable Objects, CPU time limits are now enforced on the object level rather than the request level. Each time a new request arrives, the time limit is “topped up” to 500ms. After the (free) be
```suggestion
- For Durable Objects, CPU time limits are now enforced on the object level rather than the request level. Each time a new request arrives, the time limit is “topped up” to 500ms. After the (free) beta period ends and Durable Objects becomes generally available, we will increase this to 30 seconds.
```

2021-06-25 14:54 UTC, deadlypants1973 commented on products/workers/src/content/platform/changelog.md
> +- Long running Durable Objects are given more subrequest quota as additional WebSocket messages are sent to them, to avoid the problem of a long-running Object being unable to make any more subreques
```suggestion
- Long running Durable Objects are given more subrequest quota as additional WebSocket messages are sent to them, to avoid the problem of a long-running Object being unable to make any more subrequests after it has been held open by a particular WebSocket for a while.
```

2021-06-25 14:54 UTC, deadlypants1973 commented on products/workers/src/content/platform/changelog.md
> +Changes since the last time we posted (which was apparently 3/26):
```suggestion
Changes since the last post on 3/26:
```

2021-06-25 14:54 UTC, deadlypants1973 commented on products/workers/src/content/platform/changelog.md
> +- ScheduledEvent.cron is now set to the original cron string that the event was scheduled for.
```suggestion
- `ScheduledEvent.cron` is now set to the original cron string that the event was scheduled for.
```

2021-06-25 14:54 UTC, deadlypants1973 commented on products/workers/src/content/platform/changelog.md
> +As of this release, we impose a limit on the number of outgoing HTTP requests that a worker can make simultaneously. **For each incoming request**, a worker can make up to 6 concurrent outgoing fetch
```suggestion
As of this release, we impose a limit on the number of outgoing HTTP requests that a worker can make simultaneously. **For each incoming request**, a worker can make up to 6 concurrent outgoing `fetch()` requests.
```

2021-06-25 14:54 UTC, deadlypants1973 commented on products/workers/src/content/platform/changelog.md
> +If a worker’s request handler attempts to call fetch() more than six times (on behalf of a single incoming request) without waiting for previous fetches to complete, then fetches after the sixth will
```suggestion
If a worker’s request handler attempts to call `fetch()` more than six times (on behalf of a single incoming request) without waiting for previous fetches to complete, then fetches after the sixth will be delayed until previous fetches have finished. A worker is still allowed to make up to 50 total subrequests per incoming request, as before; the new limit is only on how many can execute simultaneously.
```

2021-06-25 14:54 UTC, deadlypants1973 commented on products/workers/src/content/platform/changelog.md
> +A very very small number of deployed workers (about 20 total) make more than 6 requests concurrently, wait for all responses to return, and then go back to read the response bodies later. For all kno
```suggestion
A very small number of deployed workers (about 20 total) make more than 6 requests concurrently, wait for all responses to return, and then go back to read the response bodies later. For all known workers that do this, we have temporarily grandfathered your zone into the old behavior, so that your workers will continue to operate. However, we will be communicating with customers one-by-one to request that you update your code to proactively read request bodies, so that it works correctly under the new limit.
```

2021-06-25 14:54 UTC, deadlypants1973 commented on products/workers/src/content/platform/changelog.md
> +- ReadableStream.cancel() and ReadableStream.getReader().cancel() now take an optional, instead of a mandatory, argument, to conform with the Streams spec.
```suggestion
- `ReadableStream.cancel()` and `ReadableStream.getReader().cancel()` now take an optional, instead of a mandatory, argument, to conform with the Streams spec.
```

2021-06-25 14:54 UTC, deadlypants1973 commented on products/workers/src/content/platform/changelog.md
> +It’s been a while since we posted release notes, partly due to the holidays. Here’s what’s new over the past month:
```suggestion
It has been a while since we posted release notes, partly due to the holidays. Here is what is new over the past month:
```

2021-06-25 14:54 UTC, deadlypants1973 commented on products/workers/src/content/platform/changelog.md
> +- Increased total per-request Cache.put() limit to 5GiB.
```suggestion
- Increased total per-request `Cache.put()` limit to 5GiB.
```

2021-06-25 14:54 UTC, deadlypants1973 commented on products/workers/src/content/platform/changelog.md
> +- Increased individual Cache.put() limits to the lesser of 5GiB or the zone’s normal cache limits ([https://support.cloudflare.com/hc/en-us/articles/200172516-Understanding-Cloudflare-s-CDN](<https:/
```suggestion
- Increased individual `Cache.put()` limits to the lesser of 5GiB or the zone’s normal cache limits ([https://support.cloudflare.com/hc/en-us/articles/200172516-Understanding-Cloudflare-s-CDN](<https://support.cloudflare.com/hc/en-us/articles/200172516-Understanding-Cloudflare-s-CDN>)).
```

2021-06-25 17:07 UTC, deadlypants1973 commented on products/workers/src/content/platform/changelog.md
> +- Wrangler tail now works on Durable Objects. Note that logs from long-lived WebSockets will not be visible until the WebSocket is closed.
```suggestion
- `wrangler tail` now works on Durable Objects. Note that logs from long-lived WebSockets will not be visible until the WebSocket is closed.
```

2021-06-25 17:07 UTC, deadlypants1973 commented on products/workers/src/content/platform/changelog.md
> +- request.cf is no longer missing when writing workers using modules syntax.
```suggestion
- `request.cf` is no longer missing when writing workers using modules syntax.
```

2021-06-25 17:08 UTC, deadlypants1973 commented on products/workers/src/content/platform/changelog.md
> +- WebCrypto: Implemented wrapKey() / unwrapKey() for AES algorithms.
```suggestion
- WebCrypto: Implemented `wrapKey()` / `unwrapKey()` for AES algorithms.
```

2021-06-25 17:08 UTC, deadlypants1973 commented on products/workers/src/content/platform/changelog.md
> +- When a Durable Object’s code is updated, or when its isolate is reset due to exceeding the memory limit, all stubs pointing to the object will become invalidated and have to be recreated. This is c
```suggestion
- When a Durable Object’s code is updated, or when its isolate is reset due to exceeding the memory limit, all stubs pointing to the object will become invalidated and have to be recreated. This is consistent with what happens when the CPU time is exceeded, or when stubs become disconnected due to random network errors. This behavior is useful, as apps can now assume that two messages sent to the same stub will be delivered to exactly the same live instance (if they are delivered at all). Apps which do not care about this property should recreate their stubs for every request; there is no performance penalty from doing so.
```

2021-06-28 13:49 UTC, deadlypants1973 requested changes

2021-06-28 13:49 UTC, deadlypants1973 commented on products/workers/src/content/platform/changelog.md
> +- `WebCrypto.generateKey()`, when asked to generate a key pair with algorithm RSA-PSS, would instead return a key pair using algorithm RSASSA-PKCS1-v1\_5. Although the key structure is the same, the
```suggestion
- `WebCrypto.generateKey()`, when asked to generate a key pair with algorithm RSA-PSS, would instead return a key pair using algorithm RSASSA-PKCS1-v1\_5. Although the key structure is the same, the signature algorithms differ, and therefore, signatures generated using the key would not be accepted by a correct implementation of RSA-PSS, and vice versa. Since this would be a pretty obvious problem, but no one ever reported it to us, we guess that currently, no one is using this functionality on Workers.
```

2021-06-28 13:49 UTC, deadlypants1973 commented on products/workers/src/content/platform/changelog.md
> +- Fixed a bug where if two differently-named scripts within the same account had identical content and were deployed to the same zone, they would be treated as the “same worker”, meaning they would s
```suggestion
- Fixed a bug where if two differently-named scripts within the same account had identical content and were deployed to the same zone, they would be treated as the “same Worker”, meaning they would share the same isolate and global variables. This only applied between Workers on the same zone, so was not a security threat, but it caused confusion. Now, two differently-named Worker scripts will never be considered the same Worker even if they have identical content.
```

2021-06-28 13:49 UTC, deadlypants1973 commented on products/workers/src/content/platform/changelog.md
> +- Fixed a bug in the preview service where the CPU time limiter was overly lenient for the first several requests handled by a newly-started worker. The same bug actually exists in production as well
```suggestion
- Fixed a bug in the preview service where the CPU time limiter was overly lenient for the first several requests handled by a newly-started worker. The same bug actually exists in production as well, but we are much more cautious about fixing it there, since doing so might break live sites. If you find your worker now exceeds CPU time limits in preview, then it is likely exceeding time limits in production as well, but only appearing to work because the limits are too lenient for the first few requests. Such Workers will eventually fail in production, too (and always have), so it is best to fix the problem in preview before deploying.
```

2021-06-28 13:49 UTC, deadlypants1973 commented on products/workers/src/content/platform/changelog.md
> +- Fixed a regression which could cause HTMLRewriter.transform() to throw spurious “The parser has stopped.” errors.
```suggestion
- Fixed a regression which could cause `HTMLRewriter.transform()` to throw spurious “The parser has stopped.” errors.
```

2021-06-28 13:49 UTC, deadlypants1973 commented on products/workers/src/content/platform/changelog.md
> +- setTimeout/setInterval can now take additional arguments which will be passed on to the callback, as required by the spec. (Few people use this feature today because it’s usually much easier to use
```suggestion
- `setTimeout`/`setInterval` can now take additional arguments which will be passed on to the callback, as required by the spec. (Few people use this feature today because it’s usually much easier to use lambda captures.)
```

2021-06-28 13:49 UTC, deadlypants1973 commented on products/workers/src/content/platform/changelog.md
> +- Fixed off-by-one line numbers in worker exceptions.
```suggestion
- Fixed off-by-one line numbers in Worker exceptions.
```

2021-06-28 13:49 UTC, deadlypants1973 commented on products/workers/src/content/platform/changelog.md
> +On investigating the use cases for such workers, every case we looked at turned out to be a mistake or otherwise unnecessary. Often, developers were making requests and receiving responses, but they
```suggestion
On investigating the use cases for such Workers, every case we looked at turned out to be a mistake or otherwise unnecessary. Often, developers were making requests and receiving responses, but they only cared about the response status and headers but not the body. So, they threw away the response objects without reading the body, essentially leaking connections. In some other cases, developers had simply accidentally written code that made excessive requests in a loop for no good reason at all. Both of these cases should now cause no problems under the new behavior.
```

2021-06-28 13:49 UTC, deadlypants1973 commented on products/workers/src/content/platform/changelog.md
> +Cloudflare communicates with origin servers using HTTP/1.1, not HTTP/2. Under HTTP/1.1, each concurrent request requires a separate connection. So, workers that make many requests concurrently could
```suggestion
Cloudflare communicates with origin servers using HTTP/1.1, not HTTP/2. Under HTTP/1.1, each concurrent request requires a separate connection. So, Workers that make many requests concurrently could force the creation of an excessive number of connections to origin servers. In some cases, this caused resource exhaustion problems either at the origin server or within our own stack.
```

2021-06-28 13:49 UTC, deadlypants1973 commented on products/workers/src/content/platform/changelog.md
> +A very small number of deployed workers (about 20 total) make more than 6 requests concurrently, wait for all responses to return, and then go back to read the response bodies later. For all known wo
```suggestion
The vast majority of Workers make fewer than six outgoing requests per incoming request. Such Workers are totally unaffected by this change.

Of Workers that do make more than six outgoing requests concurrently for a single incoming request, the vast majority either read the response bodies immediately upon each response returning, or never read the response bodies at all. In either case, these Workers will still work as intended – although they may be a little slower due to outgoing requests after the sixth being delayed.

A very small number of deployed Workers (about 20 total) make more than 6 requests concurrently, wait for all responses to return, and then go back to read the response bodies later. For all known Workers that do this, we have temporarily grandfathered your zone into the old behavior, so that your Workers will continue to operate. However, we will be communicating with customers one-by-one to request that you update your code to proactively read request bodies, so that it works correctly under the new limit.
```

2021-06-28 13:49 UTC, deadlypants1973 commented on products/workers/src/content/platform/changelog.md
> +Our implementation automatically detects if delaying a fetch would cause the worker to deadlock, and prevents the deadlock by cancelling the least-recently-used request. For example, imagine a worker
```suggestion
As of this release, we impose a limit on the number of outgoing HTTP requests that a Worker can make simultaneously. **For each incoming request**, a Worker can make up to 6 concurrent outgoing `fetch()` requests.

If a Worker’s request handler attempts to call `fetch()` more than six times (on behalf of a single incoming request) without waiting for previous fetches to complete, then fetches after the sixth will be delayed until previous fetches have finished. A Worker is still allowed to make up to 50 total subrequests per incoming request, as before; the new limit is only on how many can execute simultaneously.

#### Automatic deadlock avoidance

Our implementation automatically detects if delaying a fetch would cause the Worker to deadlock, and prevents the deadlock by cancelling the least-recently-used request. For example, imagine a Worker that starts 10 requests and waits to receive all the responses *without reading the response bodies*. A fetch is not considered complete until the response body is fully-consumed (e.g. by calling `response.text()` or `response.json()`, or by reading from `response.body`). Therefore, in this scenario, the first six requests will run and their response objects would be returned, but the remaining four requests would not start until the earlier responses are consumed. If the Worker fails to actually read the earlier response bodies and is still waiting for the last four requests, then the Workers Runtime will automatically cancel the first four requests so that the remaining ones can complete. If the Worker later goes back and tries to read the response bodies, exceptions will be thrown.
```

2021-06-28 13:49 UTC, deadlypants1973 commented on products/workers/src/content/platform/changelog.md
> +- Implemented File and Blob APIs, which can be used when constructing FormData in outgoing requests. Unfortunately, FormData from incoming requests at this time will still use strings even when file
```suggestion
- Implemented File and Blob APIs, which can be used when constructing FormData in outgoing requests. Unfortunately, FormData from incoming requests at this time will still use strings even when file metadata was present, in order to avoid breaking existing deployed Workers. We will find a way to fix that in the future.
```

2021-06-28 13:49 UTC, deadlypants1973 commented on products/workers/src/content/platform/changelog.md
> +- A Durable Object’s ID is now provided to it in its constructor. It can be accessed off of the `state` provided as the constructor’s first argument, as in `state.id`.
```suggestion
- When the Workers Runtime itself reloads due to us deploying a new version or config change, we now preload high-traffic Workers in the new instance of the runtime before traffic cuts over. This ensures that users do not observe cold starts for these Workers due to the upgrade, and also fixes a low rate of spurious 503 errors that we had previously been seeing due to overload during such reloads.

(It looks like no release notes were posted the last few weeks, but there were no new user-visible changes to report.)
## 2/11/2021

Changes this week:
- In the preview mode of the dashboard, a Worker that fails during startup will now return a 500 response, rather than getting the default passthrough behavior, which was making it harder to notice when a Worker was failing.
- A Durable Object’s ID is now provided to it in its constructor. It can be accessed off of the `state` provided as the constructor’s first argument, as in `state.id`.
```

2021-06-28 13:49 UTC, deadlypants1973 commented on products/workers/src/content/platform/changelog.md
> +- waitUntil is now supported for module workers. An additional argument called ‘ctx’ is passed after ‘env’, and waitUntil is a method on ‘ctx’.
```suggestion
- `waitUntil` is now supported for module Workers. An additional argument called ‘ctx’ is passed after ‘env’, and `waitUntil` is a method on ‘ctx’.
```

2021-06-28 13:49 UTC, deadlypants1973 commented on products/workers/src/content/platform/changelog.md
> +- passThroughOnException is now available under the ctx argument to module handlers
```suggestion
- `passThroughOnException` is now available under the ctx argument to module handlers
```

2021-06-28 13:49 UTC, deadlypants1973 commented on products/workers/src/content/platform/changelog.md
> +- Fixed bug where crypto.subtle.encrypt() on zero-length inputs would sometimes throw an exception.
```suggestion
- Fixed bug where `crypto.subtle.encrypt()` on zero-length inputs would sometimes throw an exception.
```

2021-06-28 13:49 UTC, deadlypants1973 commented on products/workers/src/content/platform/changelog.md
> +- Fixed bug where crypto.subtle.encrypt() on zero-length inputs would sometimes throw an exception.
```suggestion
- Fixed bug where `crypto.subtle.encrypt()` on zero-length inputs would sometimes throw an exception.
```

2021-06-28 13:49 UTC, deadlypants1973 commented on products/workers/src/content/platform/changelog.md
> +- `request.cf` is no longer missing when writing workers using modules syntax.
```suggestion
- `request.cf` is no longer missing when writing Workers using modules syntax.
```

2021-06-28 13:52 UTC, deadlypants1973 commented on products/workers/src/content/platform/changelog.md
> +- A rare source of daemonDown errors when processing bursty traffic over HTTP/2 has been eliminated.
```suggestion
- A rare source of `daemonDown` errors when processing bursty traffic over HTTP/2 has been eliminated.
```

2021-06-29 15:15 UTC, deadlypants1973 commented on products/workers/src/content/platform/changelog.md
> +- Fixed a regression which could cause HTMLRewriter.transform() to throw spurious “The parser has stopped.” errors.
```suggestion
- Fixed a regression which could cause `HTMLRewriter.transform()` to throw spurious “The parser has stopped.” errors.
```

2021-06-29 15:19 UTC, deadlypants1973 approved these changes

2021-06-29 15:37 UTC, merged