Added fauna integration guide
cloudflare/cloudflare-docs pull request #16470
Opened 2024-08-27 06:39 UTC by Shadid12

### Summary

### Screenshots (optional)

### Documentation checklist

- [ ] The [documentation style guide](https://developers.cloudflare.com/style-guide/) has been adhered to.
- [ ] If a larger change - such as adding a new page- an issue has been opened in relation to any incorrect or out of date information that this PR fixes.
- [ ] Files which have changed name or location have been allocated [redirects](https://developers.cloudflare.com/pages/configuration/redirects/#per-file).

2024-09-05 22:36 UTC, nevikashah reviewed
thanks!

2024-09-05 22:36 UTC, nevikashah commented on src/content/docs/workers/databases/native-integrations/fauna.mdx
> +		![OAuth apps in Fauna](~/assets/images/workers/databases/native-integrations/fauna_oauth.png)
why is "Learn More" highlighted in the images -- seems odd

2024-09-05 22:36 UTC, nevikashah commented on src/content/docs/workers/tutorials/store-data-with-fauna/index.mdx
> +updated: 2024-09-29
```suggestion
updated: 2024-09-05
```

2024-09-05 22:36 UTC, nevikashah commented on src/content/docs/workers/tutorials/store-data-with-fauna/index.mdx
> +For local development, you must manually create a [Fauna authentication key](https://docs.fauna.com/fauna/current/learn/security/keys/) and pass the key's secret to your Worker as a [development secr
we should link to "add your fauna database key for local development" on [development secret] instead

2024-09-05 22:36 UTC, nevikashah commented on src/content/docs/workers/tutorials/store-data-with-fauna/index.mdx
> +You can access the `DATABASE_KEY` environment variable from `c.env.DATABASE_KEY`. Workers run on a [custom JavaScript runtime](https://developers.cloudflare.com/workers/runtime-apis/nodejs/) instead
```suggestion
You can access the `DATABASE_KEY` environment variable from `c.env.DATABASE_KEY`. Workers run on a [custom JavaScript runtime](/workers/runtime-apis/) instead of Node.js, so you cannot use `process.env` to access your environment variables.
```

2024-09-05 22:46 UTC, jrodewig commented on src/content/docs/workers/databases/native-integrations/fauna.mdx
> +		![OAuth apps in Fauna](~/assets/images/workers/databases/native-integrations/fauna_oauth.png)
Replaced in [`b9b1afc` (#16470)](https://github.com/cloudflare/cloudflare-docs/pull/16470/commits/b9b1afcdd1cd2870129d616bbd9827dafde6b9c2).

2024-09-05 22:47 UTC, jrodewig commented on src/content/docs/workers/tutorials/store-data-with-fauna/index.mdx
> +For local development, you must manually create a [Fauna authentication key](https://docs.fauna.com/fauna/current/learn/security/keys/) and pass the key's secret to your Worker as a [development secr
Updated in [`b9b1afc` (#16470)](https://github.com/cloudflare/cloudflare-docs/pull/16470/commits/b9b1afcdd1cd2870129d616bbd9827dafde6b9c2).

2024-09-05 23:29 UTC, nevikashah approved these changes

2024-09-06 13:36 UTC, kodster28 requested changes
Only outstanding thing is the secret pic.

2024-09-06 13:36 UTC, kodster28 commented on src/content/docs/workers/databases/native-integrations/fauna.mdx
> +		![Key tab for a database in the Fauna Dashboard](~/assets/images/workers/databases/native-integrations/fauna_keys_tab.png)
Can we remove this one (i.e., is it super important for someone to see when we could just keep the call out above)? I can almost guarantee it'll get SIRT'd just b/c we have an active group of folks here.

Other alternative would be to add a comment directly above noting that it's a key that's since been deleted and not an exposure risk.

2024-09-06 13:36 UTC, kodster28 commented on src/content/docs/workers/tutorials/store-data-with-fauna/index.mdx
> +- Login to your [Cloudflare dashboard](https://dash.cloudflare.com/).
Numbered list instead?

2024-09-06 13:36 UTC, kodster28 commented on src/content/docs/workers/tutorials/store-data-with-fauna/index.mdx
> +- Select _Finish_.
```suggestion
- Select **Finish**.
```

2024-09-06 13:36 UTC, kodster28 commented on src/content/docs/workers/tutorials/store-data-with-fauna/index.mdx
> +- Navigate to settings tab and select _Variables_. Notice that a new variable `DATABASE_KEY`
```suggestion
- Navigate to **Settings** tab and select **Variables**. Notice that a new variable `DATABASE_KEY`
```

2024-09-06 13:46 UTC, jrodewig commented on src/content/docs/workers/databases/native-integrations/fauna.mdx
> +		![Key tab for a database in the Fauna Dashboard](~/assets/images/workers/databases/native-integrations/fauna_keys_tab.png)
Sure. Removed with [`b975931` (#16470)](https://github.com/cloudflare/cloudflare-docs/pull/16470/commits/b975931b0f745d3fb2cf02f1c98404ac3736e229).

2024-09-06 13:46 UTC, jrodewig commented on src/content/docs/workers/tutorials/store-data-with-fauna/index.mdx
> +- Login to your [Cloudflare dashboard](https://dash.cloudflare.com/).
Updated with `b975931` (#16470)](https://github.com/cloudflare/cloudflare-docs/pull/16470/commits/b975931b0f745d3fb2cf02f1c98404ac3736e229).

2024-09-06 13:47 UTC, jrodewig commented on src/content/docs/workers/tutorials/store-data-with-fauna/index.mdx
> +- Select _Finish_.
Addressed with `b975931` (#16470)](https://github.com/cloudflare/cloudflare-docs/pull/16470/commits/b975931b0f745d3fb2cf02f1c98404ac3736e229).

2024-09-06 13:47 UTC, jrodewig commented on src/content/docs/workers/tutorials/store-data-with-fauna/index.mdx
> +- Navigate to settings tab and select _Variables_. Notice that a new variable `DATABASE_KEY`
Addressed with `b975931` (#16470)](https://github.com/cloudflare/cloudflare-docs/pull/16470/commits/b975931b0f745d3fb2cf02f1c98404ac3736e229).

2024-09-06 13:47 UTC, jrodewig commented
Thanks @kodster28. I addressed your feedback in `b975931` (#16470)](https://github.com/cloudflare/cloudflare-docs/pull/16470/commits/b975931b0f745d3fb2cf02f1c98404ac3736e229).

This is ready for another look at your convenience.

2024-09-06 14:31 UTC, kodster28 approved these changes

2024-09-06 14:31 UTC, kodster28 commented on src/content/docs/workers/tutorials/store-data-with-fauna/index.mdx
> +        ![Selecting the fauna integration](~/assets/images/workers/tutorials/store-data-with-fauna/integrate_fauna.png).
```suggestion
        ![Selecting the fauna integration](~/assets/images/workers/tutorials/store-data-with-fauna/integrate_fauna.png)
```

2024-09-06 14:31 UTC, kodster28 commented on src/content/docs/workers/tutorials/store-data-with-fauna/index.mdx
> +        ![Selecting the fauna integration](~/assets/images/workers/tutorials/store-data-with-fauna/integrate_fauna.png).
Adds an extra line break after the rendered pic

2024-09-09 19:50 UTC, merged