[D1] Improvements to D1 Getting Started page
cloudflare/cloudflare-docs pull request #16477
Opened 2024-08-27 15:12 UTC by Oxyjun

### Summary

Minor wording improvements for enhanced clarity in the Getting Started page from D1.

### Screenshots (optional)

### Documentation checklist

- [ ] The [documentation style guide](https://developers.cloudflare.com/style-guide/) has been adhered to.
- [ ] If a larger change - such as adding a new page- an issue has been opened in relation to any incorrect or out of date information that this PR fixes.
- [ ] Files which have changed name or location have been allocated [redirects](https://developers.cloudflare.com/pages/configuration/redirects/#per-file).

2024-08-27 15:37 UTC, marciocloudflare requested changes

2024-08-27 15:37 UTC, marciocloudflare commented on src/content/docs/d1/get-started.mdx
> +To bind your D1 database to your Worker, copy the following lines from your terminal obtained from step 2, then add the following to the end of your `wrangler.toml` file:
```suggestion
To bind your D1 database to your Worker, copy the lines obtained from step 2 from your terminal, then add the following to the end of your `wrangler.toml` file:
```

2024-08-27 15:37 UTC, marciocloudflare commented on src/content/docs/d1/get-started.mdx
> +To bind your D1 database to your Worker, copy the following lines from your terminal obtained from step 2, then add the following to the end of your `wrangler.toml` file:
I'm not sure it's clear what lines from step 2 this refers to.

2024-08-27 15:37 UTC, marciocloudflare commented on src/content/docs/d1/get-started.mdx
> +- The value (string) you set for `binding` will be used to reference this database in your Worker. In this tutorial, name your binding `DB`.
Is binding a command? Or are you referring to the <BINDING_NAME> the user set? If you use monospace like this, it makes it seem like binding is a command, or a known variable, or some other thing that relates to the product, instead of a variable the user has to set.

2024-08-27 15:37 UTC, marciocloudflare commented on src/content/docs/d1/get-started.mdx
> +- Your binding is available in your Worker at `env.binding` [^1] and the D1 [client API](/d1/build-with-d1/d1-client-api/) is exposed on this binding.
Same question here related to env.binding

2024-08-27 15:37 UTC, marciocloudflare commented on src/content/docs/d1/get-started.mdx
> +[^1]: Note that `binding` refers to your specific binding name. For example, `env.DB`.
Ah, if that's the case, then you should maintain the previous wording since that's what we agreed to use when we refer to variables the user has to enter.

2024-08-27 15:37 UTC, marciocloudflare commented on src/content/docs/d1/get-started.mdx
> +You can also bind your D1 database to a [Pages Function](/pages/functions/index). For more information, refer to [Functions Bindings for D1](/pages/functions/bindings/#d1-databases).
```suggestion
You can also bind your D1 database to a [Pages Function](/pages/functions/). For more information, refer to [Functions Bindings for D1](/pages/functions/bindings/#d1-databases).
```

2024-08-27 15:44 UTC, Oxyjun commented on src/content/docs/d1/get-started.mdx
> +To bind your D1 database to your Worker, copy the following lines from your terminal obtained from step 2, then add the following to the end of your `wrangler.toml` file:
I meant step 2 "Create a database" - I'll make it a link to jump to that header for improved clarity.

Also thanks for catching bad wording, will pay more attention for brevity!

2024-08-27 15:49 UTC, Oxyjun commented on src/content/docs/d1/get-started.mdx
> +- The value (string) you set for `binding` will be used to reference this database in your Worker. In this tutorial, name your binding `DB`.
So I'm referring to the `binding="DB"` line within the terminal output.

![image](https://github.com/user-attachments/assets/7829722e-621e-40ca-8c91-f9b28382bc65)

The issue with `<BINDING_NAME>` is that it never actually appears anywhere throughout the guide (something I noticed when I worked through this page). I felt that we should use the syntax provided by the terminal?

2024-08-27 15:51 UTC, Oxyjun commented on src/content/docs/d1/get-started.mdx
> +You can also bind your D1 database to a [Pages Function](/pages/functions/index). For more information, refer to [Functions Bindings for D1](/pages/functions/bindings/#d1-databases).
Thanks - just for my own understanding, do we not need to specify the index.mdx page?

2024-08-27 15:55 UTC, marciocloudflare commented on src/content/docs/d1/get-started.mdx
> +You can also bind your D1 database to a [Pages Function](/pages/functions/index). For more information, refer to [Functions Bindings for D1](/pages/functions/bindings/#d1-databases).
No need to add the index.md file when creating links to a folder. Just for the other pages inside the folder.

2024-08-28 09:07 UTC, marciocloudflare approved these changes

2024-08-28 09:07 UTC, marciocloudflare commented on src/content/docs/d1/get-started.mdx
> +To bind your D1 database to your Worker, copy the following lines obtained from [step 2](/d1/get-started/#2-create-a-database) from your terminal, then add the following to the end of your `wrangler.
```suggestion
To bind your D1 database to your Worker, copy the lines obtained from [step 2](/d1/get-started/#2-create-a-database) from your terminal. Then, add them to the end of your `wrangler.toml` file:
```

2024-08-28 11:04 UTC, merged