[D1] Location Hints Update
cloudflare/cloudflare-docs pull request #16556
Opened 2024-08-30 15:43 UTC by Oxyjun

### Summary

1. Including `oc` as a valid Location Hint.
2. Ensuring "Location Hint" is made a proper noun (follows from R2 - but there is a general inconsistency, which should be tackled separately).
3. Adding a clarification that Location Hints are unavailable for SAM, AFR, and ME.
4. Adding a clarification that Location Hints do not guarantee that D1 will perform the write in the specified location, but instead write in the nearest location by latency.

### Screenshots (optional)

### Documentation checklist

- [ ] The [documentation style guide](https://developers.cloudflare.com/style-guide/) has been adhered to.
- [ ] If a larger change - such as adding a new page- an issue has been opened in relation to any incorrect or out of date information that this PR fixes.
- [ ] Files which have changed name or location have been allocated [redirects](https://developers.cloudflare.com/pages/configuration/redirects/#per-file).

2024-08-30 15:49 UTC, simonha9 reviewed
Left some nit comments, none I feel too strongly about but worth a consideration.

2024-08-30 15:49 UTC, simonha9 commented on src/content/docs/d1/configuration/data-location.mdx
> +Location Hints are optional parameters you can provide to indicate your desired the geographical location when interacting (creating, writing, and accessing) with your database.
super-nit, creating and writing is a subset of writing but fine if left as-is

2024-08-30 15:49 UTC, simonha9 commented on src/content/docs/d1/configuration/data-location.mdx
> +D1 Location Hints are not available for the following regions:
Maybe slightly better is "not currently supported", but don't feel too strongly about this verbiage

2024-08-30 15:58 UTC, kodster28 approved these changes

2024-08-30 16:00 UTC, Oxyjun commented on src/content/docs/d1/configuration/data-location.mdx
> +D1 Location Hints are not available for the following regions:
Are there plans to introduce it in future? Either way, happy to add it in if desired.

2024-08-30 16:01 UTC, Oxyjun commented
@vy-ton could you please give it a quick look over? 😄

2024-08-30 16:32 UTC, vy-ton requested changes

2024-08-30 16:32 UTC, vy-ton commented on src/content/docs/d1/configuration/data-location.mdx
> +Location Hints are optional parameters you can provide to indicate your desired the geographical location when interacting (creating, writing, and accessing) with your database.
```suggestion
Location Hints are optional parameters you can provide to indicate your desired geographical location for your database.
```

`when interacting` is odd framing

2024-08-30 16:32 UTC, vy-ton commented on src/content/docs/d1/configuration/data-location.mdx
> +Location Hint does not guarantee that D1 will write in your preferred location. However, the write will occur in the nearest possible location (by latency) to your preference.
framing this as `will write, write will` is misleading

location hunt is where you D1 database runs

2024-08-30 16:32 UTC, vy-ton commented on src/content/docs/d1/configuration/data-location.mdx
> +To provide a Location Hint when creating a new database, pass the `--location` flag with a valid Location Hint:
personally, I dont think `Location Hint` should be a pronoun/capitalized

2024-08-30 16:32 UTC, vy-ton commented on src/content/docs/d1/configuration/data-location.mdx
> +D1 Location Hints are not available for the following regions:
+1 not currently supported

I would inline `following regions: South America ...`

2024-08-30 16:58 UTC, rozenmd commented on src/content/docs/d1/configuration/data-location.mdx
> +## Provide location hints
```suggestion
## Provide a location hint
```

It's singular - as an option to the API

2024-08-30 16:58 UTC, rozenmd commented on src/content/docs/d1/configuration/data-location.mdx
> +Location hints are optional parameters you can provide to indicate your desired geographical location for your database.
```suggestion
a location hint is an optional parameter you can provide to indicate your desired geographical location for your database.
```

2024-08-30 16:59 UTC, rozenmd commented on src/content/docs/d1/configuration/data-location.mdx
> +You may want to explicitly provide a location hint in cases where the majority of your writes to a specific database come from a different location than where you are creating the database from. loca
```suggestion
You may want to explicitly provide a location hint in cases where the majority of your writes to a specific database come from a different location than where you are creating the database from. A location hint can be useful when:
```

2024-09-02 09:09 UTC, rozenmd commented on src/content/docs/d1/configuration/data-location.mdx
> +Location hint does not guarantee that D1 runs in your preferred location. Instead, it will run in the nearest possible location (by latency) to your preference.
```suggestion
Providing a location hint does not guarantee that D1 runs in your preferred location. Instead, it will run in the nearest possible location (by latency) to your preference.
```

2024-09-02 11:38 UTC, rozenmd commented on src/content/docs/d1/configuration/data-location.mdx
> +A location hint is an optional parameter you can provide to indicate your desired geographical location for your database.
Reads a bit weird... how about:
```suggestion
Location hint is an optional parameter you can provide to indicate your desired geographical location for your database.
```

2024-09-04 13:56 UTC, vy-ton commented on src/content/docs/d1/configuration/data-location.mdx
> +D1 location hints are not currently supported for South America (`sam`), Africa (`afr`), and the Middle East (`me`)
```suggestion
D1 location hints are not currently supported for South America (`sam`), Africa (`afr`), and the Middle East (`me`). D1 databases do not run in these locations.
```

2024-09-04 13:56 UTC, vy-ton commented on src/content/docs/d1/configuration/data-location.mdx
> +Providing a location hint does not guarantee that D1 runs in your preferred location. Instead, it will run in the nearest possible location (by latency) to your preference.
I'm confused what `by latency` here means.

2024-09-04 14:03 UTC, rozenmd commented on src/content/docs/d1/configuration/data-location.mdx
> +Providing a location hint does not guarantee that D1 runs in your preferred location. Instead, it will run in the nearest possible location (by latency) to your preference.
geographically I might be closer to City A, but by ping/latency I'm closer to City B

2024-09-04 15:29 UTC, vy-ton approved these changes

2024-09-04 15:30 UTC, merged