[Workers] (WIP) Assets
cloudflare/cloudflare-docs pull request #16610
Opened 2024-09-03 17:14 UTC by tanushree-sharma

First pass at docs for assets. This is WIP

2024-09-03 18:48 UTC, kodster28 commented
Hey hey, also since I was in there, slightly updated your PR to take advantage of built-in properties (`title` for code blocks) and new components ([Filetree](https://developers.cloudflare.com/style-guide/components/file-tree/)).

2024-09-04 04:37 UTC, irvinebroque commented on src/content/docs/workers/wrangler/commands.mdx
> +- `--assets` string optional beta
Can we use `beta` label here or put in parens?

@kodster28 — do we have a pattern here to lean on to get wrangler docs (that are hardest hit by this regressions from old docs) to a clearer spot?

2024-09-04 04:37 UTC, irvinebroque commented on src/content/docs/workers/wrangler/commands.mdx
> +  - Root folder of static assets to be served.
I think something here should link to wherever the source of truth docs are about assets. If I land on this page, see this, where do I go to learn more?

2024-09-04 04:37 UTC, irvinebroque commented on src/content/docs/workers/frameworks/index.mdx
> +## Pricing
This needs to go on the pricing page, not here.

2024-09-04 04:37 UTC, irvinebroque commented on src/content/docs/workers/frameworks/index.mdx
> +The following Frameworks will be supported soon:
Think docs are clearest when down to the facts of what works, what doesn't work — and more importantly than coming soon — showing people that there is a path to deploying <framework> to Cloudflare (ex: with Pages).

2024-09-04 04:37 UTC, irvinebroque commented on src/content/docs/workers/frameworks/get-started.mdx
> +git clone https://github.com/tanushree-sharma/workers-assets-template
Why this template if this content is under the frameworks section?

2024-09-04 04:37 UTC, irvinebroque commented on src/content/docs/workers/frameworks/get-started.mdx
> +description: Create a Worker with assets throught the wrangler CLI or through a Git integration.
It feels like this page has a few different goals right now:

- Show a step-by-step guide for creating a new static site
- Show a step-by-step guide for creating a new dynamic site
- Reference content about routing

It feels like there is an opportunity to have a section here:

https://developers.cloudflare.com/workers/runtime-apis/bindings/

...that has reference content about the assets binding — how does it work, how is it configured, what are the different options. And that this page peels back the layers of how it works.

And that there can be guides for specific frameworks, akin to Pages.

2024-09-04 04:37 UTC, irvinebroque commented on src/content/docs/workers/frameworks/configuration.mdx
> +title: Configuration
Similar to other comment, this content seems like a description of the assets binding — not about "configuring a framework", which is how it comes across when this section is under frameworks.

2024-09-04 04:37 UTC, irvinebroque commented on src/content/docs/workers/frameworks/get-started.mdx
> +description: Create a Worker with assets throught the wrangler CLI or through a Git integration.
It may be the case that there's an explicit, separate guide or section about how one could take a directory of static files, deploy them as a Worker to Cloudflare.

It feels like that can live on its own and be linked to?

2024-09-04 04:37 UTC, irvinebroque commented on public/workers/frameworks/index.html
> +<!doctype html>
Accidentally committed file?

2024-09-04 04:39 UTC, irvinebroque commented on src/content/docs/workers/frameworks/index.mdx
> +Requests Workers are billed according to [Workers pricing](/workers/platform/pricing/), except in the case of static assets — **requests to static assets are free and unlimited**. Refer to configurat
This would benefit from an example

2024-09-04 05:00 UTC, irvinebroque reviewed
Consider these pages:

https://developers.cloudflare.com/workers/configuration/sites/
https://developers.cloudflare.com/workers/examples/103-early-hints/
https://developers.cloudflare.com/workers/examples/return-html/

2024-09-04 14:15 UTC, kodster28 commented on src/content/docs/workers/frameworks/get-started.mdx
> +Deploy your Worker via Wrangler to a `*.workers.dev` subdomain or a [Custom Domain](/workers/configuration/routing/custom-domains/).
Hey hey, @tanushree-sharma, just merged production into your branch, which should fix this

2024-09-04 14:15 UTC, kodster28 commented on src/content/docs/workers/wrangler/commands.mdx
> +- `--assets` string optional beta
The easiest pattern at the moment might just be enclosing everything in backticks to at least put it in monospace formatting (which is better, but isn't the best for sure). If that's something we need, that's something I can definitely hop onto.

In terms of the previous behavior, that'd depend on PCX-13275 (which I can try to prioritize, but might bump up against content stuff that I'm trying to wrap my head around).

2024-09-19 11:47 UTC, ToriLindsay commented
Hi @tanushree-sharma 
Another option for the overall structure could be:
- Frameworks
- - Overview
- - - Intro (Currently in “Get Started”)
- - - Supported frameworks
- - Static site
- - - Create
- - - Develop
- - - Deploy
- - - Configure
- - Dynamic site
- - - Create
- - - Develop
- - - Deploy
- - - Configure
- - Full-stack application
- - - Create
- - - Develop
- - - Deploy

I'm still learning about the product so feel free to ignore if this doesn't make sense. Thought I'd start with the higher-level suggestion, but feel free to ping me for more granular copyedits when needed.

2024-09-20 04:54 UTC, tanushree-sharma commented
Thanks @ToriLindsay for the suggestion! Getting the content up and then let's play around with structure, see what flows the best.

2024-09-20 16:46 UTC, cbtexan04 commented on src/content/docs/workers/configuration/assets.mdx
> +Configuring a project with assets requires specifying a [directory](/workers/configuration/assets/#directory) and an optional [assets binding](/workers/configuration/assets/#binding) in the `wrangler
Might just be me, but it could be confusing as to "what one set of assets" means.

2024-09-20 16:46 UTC, cbtexan04 commented on src/content/docs/workers/configuration/assets.mdx
> +Assets are served based on file-based routing. The structure and organization of files in your project's directory determine the routing paths for your application. If a request is found with a match
nit: "based on file-based" routing seems redundant (even though I'm struggling to come up with other phrasing myself 😅 ). Maybe "Assets are served using file-based routing"?

2024-09-20 16:46 UTC, cbtexan04 commented on src/content/docs/workers/configuration/assets.mdx
> +1. **`html_handling`**: Trailing slashes on websites (e.g. example.com/page/ vs. example.com/page) can impact SEO because search engines treat URLs with and without trailing slashes as different, sep
We also have `force-trailing-slash` in EWC, though I'm not sure if that's implemented yet?

2024-09-20 16:46 UTC, cbtexan04 commented on src/content/docs/workers/configuration/assets.mdx
> +Based on the incoming requests, the following assets would be served:
These are soooo good. Thanks to you and @GregBrimble for documenting these!

2024-09-20 16:46 UTC, cbtexan04 commented on src/content/docs/workers/configuration/assets.mdx
> +### not_found_handling
We also have "none" for html handling in EWC code (again, not sure if we want to document)

2024-09-20 21:21 UTC, dcpena commented on src/content/docs/workers/configuration/assets.mdx
> +Configuring a project with assets requires specifying a [directory](/workers/configuration/assets/#directory) and an optional [assets binding](/workers/configuration/assets/#binding) in the `wrangler
```suggestion
Configuring a project with assets requires specifying a [directory](/workers/configuration/assets/#directory) and an optional [assets binding](/workers/configuration/assets/#binding) in the `wrangler.toml` file. Each Worker is limited to only one set of assets.
```

2024-09-20 21:21 UTC, dcpena commented on src/content/docs/workers/configuration/assets.mdx
> +1. **`html_handling`**: Trailing slashes on websites (e.g. example.com/page/ vs. example.com/page) can impact SEO because search engines treat URLs with and without trailing slashes as different, sep
```suggestion
1. **`html_handling`**: Trailing slashes on websites (e.g. `example.com/page/` vs. `example.com/page`) can impact SEO because search engines treat URLs with and without trailing slashes as different, separate pages. This distinction can lead to duplicate content issues, indexing problems, and overall confusion about the correct canonical version of a page.
```

2024-09-20 21:21 UTC, dcpena commented on src/content/docs/workers/configuration/assets.mdx
> +Alternate configuration options are outlined on this page and can be specified in your project's wrangler.toml file. If you're deploying using a Framework[link], these options will be defined by the
```suggestion
Alternate configuration options are outlined on this page and can be specified in your project's `wrangler.toml` file. If you're deploying using a Framework[link], these options will be defined by the Framework provider.
```

2024-09-20 21:21 UTC, dcpena commented on src/content/docs/workers/configuration/assets.mdx
> +Define a custom page to be displayed when there is no match for the requested file by creating a 404.html file. If one is not found in the same directory as the route you are currently requesting, it
```suggestion
Define a custom page to be displayed when there is no match for the requested file by creating a 404.html` file. If one is not found in the same directory as the route you are currently requesting, it will continue to look up the directory tree for a matching 404.html file. This means that you can define custom 404 paths for situations like `/blog/404.html and /404.html`, and Workers will automatically render the correct one depending on the situation.
```

2024-09-20 21:21 UTC, dcpena commented on src/content/docs/workers/frameworks/index.mdx
> +- Angular
Does it make sense to link to add in links for the frameworks in the list? Especially because we provide links to Next.js and Vue in the note.

2024-09-20 21:21 UTC, dcpena commented on src/content/docs/workers/frameworks/get-started.mdx
> +# Deploying a Static Site
```suggestion
## Deploy a static site
```

2024-09-20 21:21 UTC, dcpena commented on src/content/docs/workers/frameworks/get-started.mdx
> +Learn about how assets are configured and how routing works: [asset configuration](/workers/configuration/assets/)
```suggestion
Learn about how assets are configured and how routing works from [Assets configuration](/workers/configuration/assets/).
```

2024-09-20 21:21 UTC, dcpena commented on src/content/docs/workers/frameworks/get-started.mdx
> +# Deploying a Static Site
I would actually make this an H2 because right now the page shows Steps 1-3 twice, and the option to deploy a full-stack application doesn't show up which makes it confusing to know which steps apply to what. Adding the H2 will make this subheading appear in the page nav on the right.

2024-09-20 21:21 UTC, dcpena commented on src/content/docs/workers/frameworks/get-started.mdx
> +# Deploying a full-stack application
```suggestion
## Deploy a full-stack application
```

2024-09-20 21:21 UTC, dcpena commented on src/content/docs/workers/frameworks/get-started.mdx
> +Learn about how assets are configured and how routing works: [asset configuration](/workers/configuration/assets/)
```suggestion
Learn about how assets are configured and how routing works from [Assets configuration](/workers/configuration/assets/)
```

2024-09-20 21:21 UTC, dcpena commented on src/content/docs/workers/frameworks/get-started.mdx
> +### 3. Deploy your Project
```suggestion
### 3. Deploy your project
```

2024-09-20 21:21 UTC, dcpena commented on src/content/docs/workers/frameworks/get-started.mdx
> +### 3. Deploy your Project
Is Project a proper noun or common? If the former, keep capitalized. Just wanted to double-check.

2024-09-20 21:21 UTC, dcpena commented on src/content/docs/workers/frameworks/get-started.mdx
> +### 3. Deploy your Project
It seems like the processes for both are identical minus the template you choose to use during Workers setup. Not worth holding anything up for now, but this would be a good candidate for partials to reuse the content. Will also help with SEO if I'm not mistaken.

2024-09-23 15:43 UTC, tanushree-sharma commented on src/content/docs/workers/frameworks/get-started.mdx
> +  badge: Beta
@dcpena know how we can get the beta pill on the top level nav for "Frameworks" rather than needing it for each page nested underneath?

2024-09-23 16:37 UTC, dcpena commented on src/content/docs/workers/frameworks/get-started.mdx
> +  badge: Beta
Checking in on this now with Kian. He may be able to make a quick change to get that supported. Will keep you updated.

2024-09-23 16:51 UTC, tanushree-sharma commented on src/content/docs/workers/frameworks/get-started.mdx
> +### 3. Deploy your Project
Good point, not a proper noun

2024-09-23 16:52 UTC, tanushree-sharma commented on src/content/docs/workers/frameworks/index.mdx
> +- Angular
Yes! When we get the pages up for Workers we can link from here.

2024-09-23 17:08 UTC, tanushree-sharma commented on src/content/docs/workers/wrangler/commands.mdx
> +- `--assets` string optional beta
Using backticks for now. @dcpena mind checking on this one too?

2024-09-23 19:37 UTC, tanushree-sharma commented on src/content/docs/workers/configuration/assets.mdx
> +1. **`html_handling`**: Trailing slashes on websites (e.g. example.com/page/ vs. example.com/page) can impact SEO because search engines treat URLs with and without trailing slashes as different, sep
I thought `force-trailing-slash` was an option in `html_handling`. @GregBrimble can you clarify?

2024-09-23 19:38 UTC, tanushree-sharma commented on src/content/docs/workers/configuration/assets.mdx
> +### not_found_handling
Missed that one. Adding

2024-09-23 19:59 UTC, WillTaylorDev commented on src/content/docs/workers/configuration/assets.mdx
> +1. **`html_handling`**: Trailing slashes on websites (e.g. example.com/page/ vs. example.com/page) can impact SEO because search engines treat URLs with and without trailing slashes as different, sep
Yup, it is-- I was just calling out I thought it was missing from the docs-- but I see it now! Sorry for the swirl!

2024-09-23 20:37 UTC, emily-shen commented on src/content/docs/workers/configuration/assets.mdx
> +directory = "./public"
don't think you can specify the directory like that, has to be:
`assets = { directory = "public"}`

2024-09-23 20:37 UTC, emily-shen commented on src/content/docs/workers/configuration/assets.mdx
> +### Binding
It might make more sense to talk about bindings/user worker stuff after routing/404 fallback behaviour has been established?

2024-09-23 20:37 UTC, emily-shen commented on src/content/docs/workers/configuration/assets.mdx
> +1. **`html_handling`**: Trailing slashes on websites (for example, example.com/page/ vs. example.com/page) can impact SEO because search engines treat URLs with and without trailing slashes as differ
I think how to "route" to the worker without a "_routes.json" or wrangler.toml "routes" is going to be the first question for a lot of people and I've seen a bit of confusion around it already.

In light of that maybe we should probably establish routing at a high-level early in this section:
1. we first try to serve assets using file-based routing
2. if there are no assets, we fallback to a worker if it exists or just serve a 404 if not.

Then when we develop the routing config, we can put that alongside this bit.

So we have one concept of routing which is 'user worker or assets?'. The other part of routing is all to with asset serving - that's where html_handling/not_found_handling comes in.

But I think that should go second as its more granular and less immediately important maybe - since e.g. for html_handling, expecting "/index.html" at "/" is intuitive and aligns with our defaults, and because a user _can_ still use the exact asset paths if they want, it would just get redirected.

2024-09-23 20:37 UTC, emily-shen commented on src/content/docs/workers/configuration/assets.mdx
> +### Default configuration
It would be cool as well to include an summary of configuration options and defaults - i'm not sure how we usually do this elsewhere in the docs, but maybe a code snippet like this:

```
# defaults to "auto-trailing-slash"
html_handling = "auto-trailing-slash" | "force-trailing-slash" | "drop-trailing-slash" | "none"

# defaults to "none"
not_found_handling = "404-page" | "single-page-application" | "none"
```

2024-09-23 20:37 UTC, emily-shen commented on src/content/docs/workers/configuration/assets.mdx
> +Based on the incoming requests, the following assets would be served:
+1 love these

2024-09-23 20:37 UTC, emily-shen commented on src/content/docs/workers/configuration/assets.mdx
> +### html_handling
I think we're missing `drop-trailing-slash` here as well

2024-09-23 20:37 UTC, emily-shen commented on src/content/docs/workers/configuration/assets.mdx
> +### Directory
not sure where the best place for this is, but we should also mention that the assets config are inheritable keys 

(maybe this is the right spot? https://developers.cloudflare.com/workers/wrangler/configuration/#inheritable-keys )

2024-09-23 20:37 UTC, emily-shen commented on src/content/docs/workers/configuration/assets.mdx
> +2. **`not_found_handling`**: Handling of requests that do not map to an asset.
Technically it should be something like 'Handling of requests that do not map to an asset *and are not handled by a user worker*'?

Basically no matter what this is set to, if there's a worker we will always fall back to the worker if there is no asset at that request path. _Then_, the user can use the assets binding to forward the request for 404 handling. At that point, not_found_handling will control whether you get back an empty response ('none'), a 404.html page, or index.html. 

All of this becomes simpler when we get route config - then its definitely handling of requests that do not map to an asset or worker route.

2024-09-23 20:37 UTC, emily-shen commented on src/content/docs/workers/configuration/assets.mdx
> +2. **`not_found_handling`**: Handling of requests that do not map to an asset.
this slightly convoluted 404 handling is why I think it would be nice to have the binding section _after_ the routing. Then this bit in the example worker code makes a lot more sense.
```
		// Otherwise, serve the static assets.
		// Without this, the Worker will error and no assets will be served.
		return env.ASSETS.fetch(request);
```

2024-09-23 20:37 UTC, emily-shen commented on src/content/docs/workers/configuration/assets.mdx
> +#### 2. `not_found_handling`
I think its a bit misleading to split it up by static site and full stack for each not_found _handling option.

No matter what the not_found_handling is set to, if there's a worker, a 404 will hit the worker. However most people will probably want to still have that final `return env.ASSETS.fetch(request);` in their worker in order to serve 404.html, index.html, nothing etc.

So the main difference is that 404's are handled automatically in a static site, but if you have a user worker you have to use the asset binding to access the 'not_found_handling' behaviour you've set.

2024-09-23 20:37 UTC, emily-shen commented on src/content/docs/workers/configuration/assets.mdx
> +/foo/bar/cat/dog -> 404
I don't think its completely clear that these are paths that don't exist, and i'm not sure what the benefit of the multiple examples are. I think these are taken from the RFC doc, but we were ✨working through some things✨ in there and it's probably not entirely fit for public view as is 😅

2024-09-23 21:22 UTC, tanushree-sharma commented on src/content/docs/workers/configuration/assets.mdx
> +directory = "./public"
Ah you're right! Thanks for catching

2024-09-23 21:33 UTC, tanushree-sharma commented on src/content/docs/workers/configuration/assets.mdx
> +### Directory
Yep adding this in my next set of changes!

2024-09-23 21:35 UTC, tanushree-sharma commented on src/content/docs/workers/configuration/assets.mdx
> +/foo/bar/cat/dog -> 404
updated with more explicit examples

2024-09-23 21:49 UTC, dcpena commented on src/content/docs/workers/frameworks/get-started.mdx
> +  badge: Beta
Kian was able to make the fix to make this possible and got it merged. I will help with this tomorrow morning!

2024-09-23 22:19 UTC, tanushree-sharma commented on src/content/docs/workers/frameworks/get-started.mdx
> +  badge: Beta
Awesome! Mind going into the branch and making the changes directly tomorrow?

2024-09-23 22:20 UTC, tanushree-sharma commented on src/content/docs/workers/configuration/assets.mdx
> +1. **`html_handling`**: Trailing slashes on websites (for example, example.com/page/ vs. example.com/page) can impact SEO because search engines treat URLs with and without trailing slashes as differ
great idea to split the two up. agreed that the first is more important to start with

2024-09-24 02:18 UTC, irvinebroque commented on src/content/docs/workers/configuration/assets/binding.mdx
> +title: Binding
Why is this in the configuration section, rather than part of Runtime APis => Bindings and/or part of a *top-level* Static Assets section that we were talking about doing?

2024-09-24 02:18 UTC, irvinebroque commented on src/content/docs/workers/configuration/assets/binding.mdx
> +description: Create a Worker with assets throught the wrangler CLI or through a Git integration.
`throught`

2024-09-24 02:18 UTC, irvinebroque commented on src/content/docs/workers/configuration/assets/index.mdx
> +description: Use [Cloudflare Pages](/pages/) for hosting full-stack applications
Doesn't seem like the right content for description?

2024-09-24 02:18 UTC, irvinebroque commented on src/content/docs/workers/configuration/assets/index.mdx
> +This guide will instruct you through setting up and deploying a static site or a full-stack application from scratch on Workers. You may prefer to build your website from scratch if:
Just say "without a framework" rather than scratch.

I can build a full stack-app from scratch using a framework, so saying from scratch doesn't imply that you're doing it without a framework necessarily.

2024-09-24 02:18 UTC, irvinebroque commented on src/content/docs/workers/configuration/assets/index.mdx
> +### 3. Deploy your Project
Not biggest deal but we're spelling out same steps twice rather than in first step providing two different commands / things to clone, and then making other steps the same.

2024-09-25 12:21 UTC, irvinebroque commented on src/content/docs/workers/static-assets/index.mdx
> +<Feature header="Full-stack Applications" href="/workers/frameworks/get-started/#deploying-a-dynamic-site" cta="Deploy a full-stack application">
I see where you're going with — on this page be big and loud about — there are two things you can do with this, you can deploy a static site, or you can serve assets from your full-stack app.

Something feels funky about this layout though:

<img width="1169" alt="Screenshot 2024-09-25 at 11 48 29 AM" src="https://github.com/user-attachments/assets/c8e273cb-d578-457d-985f-e77777f6805d">

And just jarring since its what the homepages of products use, and other docs pages don't really use it?

These two headings shouldn't be same size, doesn't feel like there is hierarchy

2024-09-25 12:21 UTC, irvinebroque commented on src/content/docs/workers/static-assets/index.mdx
> +Combine asset hosting with Cloudflare's data and storage products such as [Workers KV](/kv/), [Durable Objects](/durable-objects/), and [R2 Storage](/r2/) to build full-stack applications. Manage bot
```suggestion
You can combine asset hosting with Cloudflare's data and storage products such as [Workers KV](/kv/), [Durable Objects](/durable-objects/), and [R2 Storage](/r2/) to build full-stack applications that serve both frontend and backend in a single Worker.
```

When we have "you" it reads like docs. Without it, reads like marketing.

2024-09-25 12:21 UTC, irvinebroque commented on src/content/docs/workers/static-assets/index.mdx
> +If you're looking for a framework not on this list, it may be supported in [Cloudflare Pages](/pages/). For example, popular frameworks such as [Next.js](/pages/framework-guides/nextjs/) and [Vue](/p
```suggestion
Static Assets for Workers is currently in open beta. If you're looking for a framework not on this list, it may be supported in [Cloudflare Pages](/pages/). Visit [Pages Frameworks guides](/pages/framework-guides/) for a full list.
```

simpler + next.js works + need to say why not supported

2024-09-25 12:21 UTC, irvinebroque commented on src/content/docs/workers/static-assets/index.mdx
> +Have a framework you would like to see supported on Workers or a feature request? Tell us about it on [Cloudflare's Developer Discord](https://discord.gg/dqgZUwcD)!
think this distracts a bit in middle

```suggestion
```

2024-09-25 12:21 UTC, irvinebroque commented on src/content/docs/workers/static-assets/index.mdx
> +Requests to static assets are free and unlimited. Refer to [pricing](/workers/platform/pricing/#example-2) for an example.
I think you actually *do* need an explicit section somewhere that describes the nuance here around whether they're served by running the Worker and calling the binding or not. Think it's hard to follow linked example because it doesn't link to anything that actually explains.

I wonder if just a lot cleaner to have a section here, within the static assets section, that stands on its own and gets into it. Clear and simple thing to discover, to link to, etc.

2024-09-25 12:21 UTC, irvinebroque commented on src/content/docs/workers/static-assets/index.mdx
> +The following limitations apply for Workers with assets:
```suggestion
The following limitations apply for Workers with static assets:
```

Think we want to be consistent and specific?

2024-09-25 12:21 UTC, irvinebroque commented on src/content/docs/workers/static-assets/index.mdx
> +- [Smart Placement](/workers/configuration/smart-placement/) cannot be enabled for projects with Assets. We are actively working on removing this limitation.
```suggestion
- You cannot yet enable [Smart Placement](/workers/configuration/smart-placement/) for Workers that have static assets. This is a temporary limitation — we are working to remove it.
```

2024-09-25 12:21 UTC, irvinebroque commented on src/content/docs/workers/static-assets/index.mdx
> +- Assets cannot be uploaded to [Workers for Platforms](/cloudflare-for-platforms/workers-for-platforms/) [user workers](/cloudflare-for-platforms/workers-for-platforms/reference/how-workers-for-platf
```suggestion
- You cannot upload static assets to [Workers for Platforms](/cloudflare-for-platforms/workers-for-platforms/) [user workers](/cloudflare-for-platforms/workers-for-platforms/reference/how-workers-for-platforms-works/). This is a temporary limitation — we are working to remove it.
```

2024-09-25 12:21 UTC, irvinebroque commented on src/content/docs/workers/static-assets/index.mdx
> +- [RPC](/workers/runtime-apis/bindings/service-bindings/rpc/) communication between service bindings are not supported in `wrangler dev` for Workers with assets. We are working on removing this limit
```suggestion
- In local development, you cannot make [Service Binding RPC calls](/workers/runtime-apis/bindings/service-bindings/rpc/) to a Worker with static assets. This is a temporary limitation — we are working to remove it.
```

2024-09-25 12:21 UTC, irvinebroque commented on src/content/docs/workers/static-assets/index.mdx
> +- Workers with assets cannot run on a [route or domain](/workers/configuration/routing/) with a path. Eg. `example.com` is an acceptable route but `example.com/foo` is not and will throw an error.
```suggestion
- You cannot add a [route or domain](/workers/configuration/routing/) that has a path to a Worker that has static assets. Eg. `example.com` is an acceptable route but `example.com/foo` is not and will throw an error.
```

We need to be _specific_ about what type of error. A runtime error? An error when you try to add the route? etc.

2024-09-25 12:44 UTC, irvinebroque commented on src/content/docs/workers/static-assets/get-started.mdx
> +Alternativley, you use can a number of popular frameworks(LINK) that come with ready-to-use components, a pre-defined structured architecture, and community support. View framework specific guides(LI
I think we _still_ want to lead with this as the recommended path, even here.

i.e. — most people just use frameworks — go over here.

Then — below we'll explain how to do this without a framework

2024-09-25 12:44 UTC, irvinebroque commented on src/content/docs/workers/static-assets/get-started.mdx
> +- You're working on a simple project where a framework might be overkill.
```suggestion
- You're working on a simple project where you might not need a framework
```

2024-09-25 12:44 UTC, irvinebroque commented on src/content/docs/workers/static-assets/get-started.mdx
> +- You require complete control over every aspect of the application.
What about — you want to build your own framework?

2024-09-25 12:44 UTC, irvinebroque commented on src/content/docs/workers/static-assets/get-started.mdx
> +This guide will instruct you through setting up and deploying a static site or a full-stack application without a framework on Workers. You may prefer to build your website from scratch if:
How can we find a way to have fewer words top of this page and get into it?

2024-09-25 12:44 UTC, irvinebroque commented on src/content/docs/workers/static-assets/get-started.mdx
> +/>
I don't know where this component lives – but it can be simplified a lot – it tells you step by step what to select, but these options can be provided directly to the initial C3 command

https://developers.cloudflare.com/pages/get-started/c3/#cli-arguments

2024-09-25 12:44 UTC, irvinebroque commented on src/content/docs/workers/static-assets/binding.mdx
> +title: Binding
Something like, "fetch assets from your Worker" is the language that people might use to describe this. Wonder if there is clearer title that is comprehsnible to new person coming to the platform.

2024-09-25 12:44 UTC, irvinebroque commented on src/content/docs/workers/runtime-apis/bindings/assets.mdx
> +title: Assets
```suggestion
title: Static Assets
```

Do we want to be consistent about saying "Static Assets"?

2024-09-25 12:44 UTC, irvinebroque commented on src/content/docs/workers/runtime-apis/bindings/assets.mdx
> +description: Create a full-stack application on Workers.
I think the description here is about the binding itself though?

2024-09-25 12:44 UTC, irvinebroque commented on src/content/docs/workers/static-assets/binding.mdx
> +The following methods are experimental and subject to change.
This is really not a thing at runtime. We need to discuss this part.

2024-09-25 12:44 UTC, irvinebroque commented on src/content/docs/workers/static-assets/compat-matrix.mdx
> +Cloudflare [Workers with static assets](/workers/static-assets/) and [Pages](/pages/) both have the ability to host frontend applications. The following compatibility matrix shows the features are av
```suggestion
You can deploy frontend applications to both Cloudflare [Workers with static assets](/workers/static-assets/) and [Pages](/pages/), from static websites to full-stack apps. The following compatibility matrix shows which are currently available for each product to help you when choosing which product to start with.
```

2024-09-25 12:44 UTC, irvinebroque commented on src/content/docs/workers/static-assets/compat-matrix.mdx
> +We plan to bridge the gaps between Workers and Pages and provide ways to migrate your Pages projects to Workers.
```suggestion
We are working to bridge gaps between Workers and Pages by bringing Pages-only features to Workers, and Workers-only features to Pages. And we will provide ways to easily migrate Pages projects to Workers.
```

2024-09-25 12:44 UTC, irvinebroque commented on src/content/docs/workers/static-assets/compat-matrix.mdx
> +| Version Metadata                  | ✅                       | ❌    |
@dcpena or @ToriLindsay can we get bit of help adding links to the products/features above? So that reader can quickly learn what each thing is?

2024-09-25 12:44 UTC, irvinebroque commented on src/content/docs/workers/static-assets/compat-matrix.mdx
> +| Dispatcher(Workers for Platforms) | ✅                       | ❌    |
```suggestion
| Dispatcher (Workers for Platforms) | ✅                       | ❌    |
```
Maybe weird one to include here? Since it's more that you use WFP, and then assets is feature, not that dispatcher is feature, and part of either Workers or Pages? (because answer is neither — it's part of WFP)

2024-09-25 12:44 UTC, irvinebroque commented on src/content/docs/workers/static-assets/compat-matrix.mdx
> +<sup>1</sup> Recommend using a Worker infront of the Worker with assets to run
```suggestion
<sup>1</sup> We recommend using a Worker in front of the Worker with assets to run
```

Think this needs more explanation in order to make sense to people. Link to Service Bindings?

2024-09-25 12:44 UTC, irvinebroque commented on src/content/docs/workers/static-assets/compat-matrix.mdx
> +<sup>2</sup> Redirects can be handled in a Worker or using [bulk
```suggestion
<sup>2</sup> You can handle redirects by adding code to your Worker, or use [bulk
```

2024-09-25 12:44 UTC, irvinebroque commented on src/content/docs/workers/static-assets/compat-matrix.mdx
> +<sup>3</sup> Cannot be enabled right now. Actively working on removing this
suggest reusing other language from limits section, see other comments

2024-09-25 13:08 UTC, irvinebroque commented on src/content/docs/workers/static-assets/binding.mdx
> +
Waaaay at the top something needs to show `env.ASSETS.fetch()` in most basic form, for the reader to orient themselves and conceptually "get it", and then move onto other details about configuration, about different options, etc.

2024-09-25 13:08 UTC, irvinebroque commented on src/content/docs/workers/static-assets/routing.mdx
> +## Routing: Worker and assets
```suggestion
## File-based routing
```

2024-09-25 13:08 UTC, irvinebroque commented on src/content/docs/workers/static-assets/routing.mdx
> +## Routing: Asset Serving
```suggestion
## How to configure file-based routing
```

I think this is fundamentally what `html_handling` and `not_found_handling` are — they are ways to configure file-based routing behavior.

2024-09-25 13:08 UTC, irvinebroque commented on src/content/docs/workers/static-assets/routing.mdx
> +#### 1. `html_handling`
Need to show examples here in this section of each of these configured in a `wrangler.toml`, otherwise someone has to jump around between pages to figure out what to add.

2024-09-25 13:08 UTC, irvinebroque commented on src/content/docs/workers/static-assets/routing.mdx
> +`html_handling` configuration determines redirects/rewrites of requests for HTML content. It is used to specify handling that redirects non-canonical URLs to canonical ones, and writes the asset path
"when `html_handling` is enabled, x, y, and z happen

otherwise unclear to me what this actually does.

would refer back to https://developers.google.com/search/blog/2010/04/to-slash-or-not-to-slash, some of the content around this and SEO can be FUD.

2024-09-25 13:08 UTC, irvinebroque commented on src/content/docs/workers/static-assets/routing.mdx
> +Response for requests that do not map to an asset and are not handled by the Worker.
reword

2024-09-25 13:08 UTC, irvinebroque commented on src/content/docs/workers/static-assets/routing.mdx
> +### Default configuration
Weird to have as separate sections. When you introduce each, need to explicitly say – this is enabled/disabled by default. Not clear from reading this?

2024-09-25 13:08 UTC, irvinebroque commented on src/content/docs/workers/static-assets/routing.mdx
> +`auto-trailing-slash` is the default mode if `html_handling` is not explicitly specified.
at this point I don't see where you have defined what `auto-trailing-slash` is before this. How does reader know what it is?

2024-09-25 13:08 UTC, irvinebroque commented on src/content/docs/workers/frameworks/framework-guides/index.mdx
> +title: Framework guides
```suggestion
title: Supported Frameworks
```

2024-09-25 13:08 UTC, irvinebroque commented on src/content/docs/workers/frameworks/framework-guides/index.mdx
> +external_link: /workers/frameworks/
I think this is cause of why there is dupe page in the navbar? (GH not letting me upload image)

2024-09-25 13:08 UTC, irvinebroque commented on src/content/docs/workers/frameworks/framework-guides/nuxt.mdx
> +In this guide, you will create a new [Nuxt](https://nuxt.com/) application and deploy to Cloudflare Workers (with the new [<InlineBadge preset="beta" /> Workers Assets](/workers/static-assets/)).
@tanushree-sharma — seems like we can simplify and build off of this page format?

https://developers.cloudflare.com/pages/framework-guides/nextjs/ssr/get-started/

We need to get to the chase

2024-09-25 13:08 UTC, irvinebroque commented on src/content/docs/workers/frameworks/index.mdx
> +</Description>
this reads as marketing the way it is presented. Just say in docs language.

2024-09-25 13:08 UTC, irvinebroque commented on src/content/docs/workers/frameworks/index.mdx
> +<DirectoryListing folder="workers/frameworks/framework-guides" />
Seems like somewehre below this should talk about Pages, other frameworks, etc.

2024-09-25 13:08 UTC, irvinebroque commented on src/content/docs/workers/frameworks/index.mdx
> +</Description>
There is a way you presented this somewhere else in docs that was good, like, you can use Workers to build frontend and backend logic etc — using framewroks.

Seems like can reuse here.

2024-09-25 13:08 UTC, irvinebroque commented on src/content/docs/workers/static-assets/compat-matrix.mdx
> +title: Compatibility Matrix
Especially if this is going to be under Static Assets, seems more specific to say:

```suggestion
title: Workers vs Pages (compatibility matrix)
```

or something that names workers and pages specifically in title, in nav.

otherwise I read this as "this is a compatibility matrix of static assets" which I don't follow

2024-09-25 16:12 UTC, tanushree-sharma commented on src/content/docs/workers/frameworks/get-started.mdx
> +### 3. Deploy your Project
Keeping as-is for now. We can update as a follow up

2024-09-25 16:20 UTC, tanushree-sharma commented on src/content/docs/workers/static-assets/index.mdx
> +<Feature header="Full-stack Applications" href="/workers/frameworks/get-started/#deploying-a-dynamic-site" cta="Deploy a full-stack application">
updating format to match workers sites: https://developers.cloudflare.com/workers/configuration/sites/

2024-09-25 16:43 UTC, tanushree-sharma commented on src/content/docs/workers/static-assets/get-started.mdx
> +/>
TIL this page exists. Going to keep as is for now. We should pull C3 out of pages + document `--experimental` options as a follow up

2024-09-25 16:49 UTC, tanushree-sharma commented on src/content/docs/workers/static-assets/compat-matrix.mdx
> +| Version Metadata                  | ✅                       | ❌    |
im taking this

2024-09-25 22:37 UTC, irvinebroque commented on src/content/docs/workers/frameworks/index.mdx
> +<DirectoryListing folder="workers/frameworks/framework-guides" />
fyi

<img width="771" alt="Screenshot 2024-09-25 at 11 36 47 PM" src="https://github.com/user-attachments/assets/0f8f36ba-923f-4bca-988d-4be7f1580525">

docs keep looking better though

2024-09-25 22:38 UTC, irvinebroque commented on src/content/docs/workers/static-assets/compatibility-matrix.mdx
> +<sup>1</sup> We recommend using [service
these need line breaks

<img width="768" alt="Screenshot 2024-09-25 at 11 38 17 PM" src="https://github.com/user-attachments/assets/3e24f058-db84-4c00-b2d0-097787d9d7e8">

2024-09-25 22:39 UTC, irvinebroque commented on src/content/docs/workers/static-assets/compatibility-matrix.mdx
> +| [Tail Workers](/workers/observability/logging/tail-workers/)                        | ❌                       | ❌    |
I think you need a way to communicate that Tail Workers _will_ be supported, just temporary limitation

2024-09-25 22:40 UTC, irvinebroque commented on src/content/docs/workers/static-assets/compatibility-matrix.mdx
> +| [Smart Placement](/workers/configuration/smart-placement/)                          | ❌ <sup>3</sup>          | ✅    |
Maybe 🔜 or something?

2024-09-25 22:55 UTC, rita3ko requested changes
couple minor suggestions

2024-09-25 22:55 UTC, rita3ko commented on src/content/docs/workers/wrangler/configuration.mdx
> +  - The binding name used to refer to the assets. Only required when creating full-stack applications.
Let's change to "Only required when executing a Worker alongside the static assets". I think full-stack applications is too vague for reference docs

2024-09-25 22:55 UTC, rita3ko commented on src/content/docs/workers/static-assets/get-started.mdx
> +### 3. Deploy your Project
I think we need another step here of modifying the Worker to make the difference between just static assets and static assets + worker clearer

2024-09-26 02:21 UTC, rita3ko approved these changes

2024-09-26 02:22 UTC, GregBrimble approved these changes

2024-09-26 02:49 UTC, crwaters16 approved these changes

2024-09-26 03:38 UTC, GregBrimble commented on src/content/docs/workers/frameworks/framework-guides/index.mdx
> +title: Framework guides
I prefer "guides" personally. We "support" many frameworks, including ones not in this set, but these are the ones we've written a "guide" for.

2024-09-26 03:39 UTC, GregBrimble commented on src/content/docs/workers/frameworks/framework-guides/index.mdx
> +external_link: /workers/frameworks/
Yeah, this is intentional. I was waiting on getting https://github.com/cloudflare/cloudflare-docs/pull/17081 in which now hides it. This technical feature just didn't exist until I wrote it. You can now redirect an index page and also hide it.

2024-09-26 03:42 UTC, GregBrimble commented on src/content/docs/workers/frameworks/framework-guides/nuxt.mdx
> +In this guide, you will create a new [Nuxt](https://nuxt.com/) application and deploy to Cloudflare Workers (with the new [<InlineBadge preset="beta" /> Workers Assets](/workers/static-assets/)).
words like "guide" and "Workers Assets" will be beneficial in SEO, esp. when we're still competing against ourselves with the Pages guides. If we cookie-cutter the guides across both places, it'll be tricky for SEO to recommend one over the other and, maybe more importantly, for readers to visually grok the difference.

2024-09-26 03:52 UTC, GregBrimble commented on src/content/docs/workers/runtime-apis/bindings/assets.mdx
> +title: Assets
The `wrangler.toml` section is `[assets]`, so I could make the argument either way. Not fussed personally, so just going to leave as-is for now. If we want to change in the future, we easily can :)

2024-09-26 03:54 UTC, GregBrimble commented on src/content/docs/workers/runtime-apis/bindings/assets.mdx
> +description: Create a full-stack application on Workers.
Updated

2024-09-26 04:16 UTC, GregBrimble commented on src/content/docs/workers/static-assets/binding.mdx
> +title: Binding
I've tried to make it a bit more approachable.

2024-09-26 05:25 UTC, GregBrimble commented on src/content/docs/workers/static-assets/routing.mdx
> +#### 1. `html_handling`
Yeah, I agree. I'm going to reshuffle this page around a bit in the coming days so useful and related things are grouped together a bit more cleanly.

2024-09-26 06:18 UTC, merged