[ZT] Tanium attributes
cloudflare/cloudflare-docs pull request #16728
Opened 2024-09-09 19:01 UTC by ranbel

PCX-13213

2024-09-09 22:29 UTC, kokolocomotion1 requested changes

2024-09-09 22:29 UTC, kokolocomotion1 commented on src/content/docs/cloudflare-one/identity/devices/service-providers/taniums2s.mdx
> _Less than 1 hour, 3 hours, 6 hours, 12 hours, 24 hours, 7 days, 30 days, or more than 30 days_

replace with In the last 1 hour, 3 hours, 6 hours, 12 hours, 24 hours, 7 days, 30 days, or more than 30 days

2024-09-09 22:53 UTC, ranbel commented on src/content/docs/cloudflare-one/identity/devices/service-providers/taniums2s.mdx
The current language matches what we have in the Crowdstrike docs. If we're using the same UI and logic, should we also update the Crowdstrike docs? https://developers.cloudflare.com/cloudflare-one/identity/devices/service-providers/crowdstrike/#device-posture-attributes

2024-09-10 21:57 UTC, maxvp approved these changes

2024-09-11 16:46 UTC, kokolocomotion1 approved these changes

2024-09-11 16:47 UTC, merged