[Logs] Adding line about data set availability in Logpush/Logpull
cloudflare/cloudflare-docs pull request #1677
Opened 2021-06-28 19:18 UTC by crwaters16

2021-06-28 19:24 UTC, soheiokamoto commented on products/logs/src/content/reference/log-fields/index.md
> +`https://api.cloudflare.com/client/v4/zones/<zone_id>/logpush/datasets/<dataset>/fields`, where the `dataset` argument indicates the log category (such as `http_requests`, `spectrum_events`, or `fire
We now have `nel_reports` for zone-scoped datasets: https://developers.cloudflare.com/logs/reference/log-fields/nel_reports
We don't need to list all here, but maybe auto-generated page should have the actual dataset name (i.e., `nel_reports`) in addition to the title "NEL reports", otherwise the only way to know the dataset name is by URL.

For this section, maybe change to:
```suggestion
`https://api.cloudflare.com/client/v4/zones/<zone_id>/logpush/datasets/<dataset>/fields`, where the `dataset` argument indicates the log category (such as `http_requests`, `spectrum_events`, `firewall_events`, etc). 
```

2021-06-28 21:35 UTC, soheiokamoto approved these changes

2021-06-28 23:12 UTC, tlozoot requested changes
question for @soheiokamoto

2021-06-28 23:12 UTC, tlozoot commented on products/logs/src/content/reference/log-fields/index.md
> +HTTP requests are available in both Logpush and Logpull. All other data sets are only available through Logpush.
@soheiokamoto I thought Spectrum is in Logpull too? But I'm OK if we want to pretend that's not the case :)

2021-06-29 18:43 UTC, soheiokamoto commented on products/logs/src/content/reference/log-fields/index.md
> +HTTP requests are available in both Logpush and Logpull. All other data sets are only available through Logpush.
Spectrum events dataset is Logpush (v1 and v2) only. Not available on Logpull.

2021-06-29 21:33 UTC, tlozoot approved these changes

2021-06-30 13:25 UTC, kodster28 approved these changes

2021-06-30 13:31 UTC, merged