[Logs] PCX-1695: Add dataset name to Log fields generated files
cloudflare/cloudflare-docs pull request #1679
Opened 2021-06-28 21:52 UTC by soheiokamoto

This adds dataset name to Log fields generated files.

Code to generate is being updated.

2021-06-28 23:11 UTC, tlozoot approved these changes
Looks good but would be good to have @crwaters16 approve

2021-06-29 13:22 UTC, crwaters16 approved these changes

2021-06-29 13:37 UTC, crwaters16 requested changes

2021-06-29 13:37 UTC, crwaters16 commented on products/logs/src/content/reference/log-fields/firewall_events.md
> +dataset: firewall_events
Let's update these descriptions to: The descriptions below detail the fields available for `firewall_events`.

That way we have a little more context leading into each page's table.

2021-06-29 18:58 UTC, soheiokamoto commented on products/logs/src/content/reference/log-fields/firewall_events.md
> +dataset: firewall_events
Updated.

2021-08-05 16:29 UTC, crwaters16 approved these changes
I'm pretty sure this has already been merged in, just cleaning up my github

2021-08-06 20:38 UTC, soheiokamoto commented
> I'm pretty sure this has already been merged in, just cleaning up my github

Yeah, I forgot to merge this one, and updated along with this PR: https://github.com/cloudflare/cloudflare-docs/pull/1861

2021-08-06 20:38 UTC, closed without merging