Lb load shedding
cloudflare/cloudflare-docs pull request #1699
Opened 2021-06-30 14:34 UTC by kodster28

Addresses https://jira.cfops.it/browse/PCX-1452.

Screenshot (for reviewing):
![image](https://user-images.githubusercontent.com/26727299/123979502-6481b800-d986-11eb-9446-70da51370c10.png)

2021-06-30 16:07 UTC, dcpena approved these changes
Approved with two, small non-blocking comments!

2021-06-30 16:07 UTC, dcpena commented on products/load-balancing/src/content/understand-basics/load-shedding.md
> +Using your internal metrics, identify origins at risk of reaching their failure threshold:
This is a nitpick, sorry, but I think you can end this with a period instead of a colon.

2021-06-30 16:07 UTC, dcpena commented on products/load-balancing/src/content/understand-basics/load-shedding.md
> +- Ensures requests from the same IP will hit the same origin, promoting cache hits, consistent latency, and session preservation.
I had to read this line a few times because I didn't realize initially that promoting cache hits, consistent latency, and session preservation were describing the first half of the sentence. 

Maybe saying, "...will hit the same origin, which promote cache hits, consistent latency...".

2021-06-30 18:34 UTC, gofish requested changes
Looks great! Love the details here.

2021-06-30 18:34 UTC, gofish commented on products/load-balancing/src/content/understand-basics/load-shedding.md
> +curl -X PUT "https://api.cloudflare.com/client/v4/accounts/{account-id}/load_balancers/pools/{pool-id}" \
This should be  `PATCH` request.

2021-06-30 18:34 UTC, gofish commented on products/load-balancing/src/content/understand-basics/load-shedding.md
> +     --data '{
I think you want `--data-binary`.

2021-06-30 18:34 UTC, gofish commented on products/load-balancing/src/content/understand-basics/load-shedding.md
> +- May cause requests from the same IP to hit different origins, potentially leading to cache misses, inconsistent latency, or session disruption for [DNS-only load balancers](/understand-basics/proxy
Extra close-paren at EOL (or missing open-paren).

2021-06-30 18:34 UTC, gofish commented on products/load-balancing/src/content/understand-basics/load-shedding.md
> +- Sheds the percentage of IP addresses specified in the *Shed %*.
Possibly more accurate:

> Sheds the percentage of **IP address hash space** specified in the *Shed %*

2021-06-30 18:34 UTC, gofish commented on products/load-balancing/src/content/understand-basics/load-shedding.md
> +- Can over- or under-shed requests, since individual IPs may be responsible for different percentages of your requests. For example, setting a *Shed %* of *50%* may shed between **40%** to **60%** of
The example here is potentially misleading: 50% could potentially shed less than 40% or more than 60% of pool requests, in extreme cases where traffic is heavily skewed. I don't think we should provide any raw numbers and suggest

> Can over- or under-shed requests, since hashing does not guarantee a perfectly even IP distribution and individual IPs may be responsible for different percentages of your requests.

2021-06-30 18:37 UTC, gofish commented on products/load-balancing/src/content/understand-basics/load-shedding.md
> +- Sheds the percentage of IP addresses specified in the *Shed %*.
But could also be more confusing.

2021-06-30 19:39 UTC, kodster28 commented on products/load-balancing/src/content/understand-basics/load-shedding.md
> +     --data '{
Howdy @gofish, I'm pretty sure you're right here, but just curious. What's does the `binary` specify in the API call? Wondering b/c I don't see it anywhere in the API docs.

2021-06-30 20:08 UTC, kodster28 commented
@gofish, should have addressed all your changes. Let me know if a) that didn't happen or b) you see anything else that needs changes.

2021-07-01 16:34 UTC, gofish approved these changes

2021-07-12 13:10 UTC, merged