[ZT] DEX remote captures
cloudflare/cloudflare-docs pull request #17042
Opened 2024-09-24 00:17 UTC by ranbel

PCX-12560

2024-09-24 10:38 UTC, abelinkinbio commented on src/content/docs/cloudflare-one/account-limits.mdx
> +| Remote captures per day |  800 |
I believe we have different limits for paygo and ent which we should call out.

2024-09-24 10:40 UTC, abelinkinbio commented on src/content/docs/cloudflare-one/insights/dex/remote-captures.mdx
> +	- **WARP Diagnostics Logs**: Generates [WARP diagnostic logs](/cloudflare-one/connections/connect-devices/warp/troubleshooting/warp-logs/#warp-diag-logs) by running a `warp-diag` command on the devi
It's a little unclear throughout this page if we're explaining how to use the CLI or the console. Where and how would I specify the `ip route get` command from the UI?

2024-09-24 10:41 UTC, abelinkinbio commented on src/content/docs/cloudflare-one/insights/dex/remote-captures.mdx
> +	- **Failed**: The capture has either timed out or encountered an error. To retry the capture, make sure the WARP client is connected and start a [new capture](/cloudflare-one/insights/dex/remote-cap
We should add a debugging section to the bottom of this page with common failure scenarios and how to work through them.

2024-10-11 16:11 UTC, ranbel commented on src/content/docs/cloudflare-one/connections/connect-devices/warp/troubleshooting/warp-logs.mdx
> +| `dex.log`  | ? |
missing description

2024-10-11 16:11 UTC, ranbel commented on src/content/docs/cloudflare-one/connections/connect-devices/warp/troubleshooting/warp-logs.mdx
> +| `dynamic.log` | ? |
missing description

2024-10-11 16:12 UTC, ranbel commented on src/content/docs/cloudflare-one/insights/dex/remote-captures.mdx
> +| Windows  | ✅            | 2024.9.346.0        |
verify WARP version

2024-10-11 16:16 UTC, ranbel commented on src/content/docs/cloudflare-one/insights/dex/remote-captures.mdx
> +	- **Failed**: The capture has either timed out or encountered an error. To retry the capture, make sure the WARP client is connected and start a [new capture](/cloudflare-one/insights/dex/remote-cap
Good idea. We'll add this section after we have data on what are the most common errors.

2024-10-30 20:58 UTC, samin-cf requested changes

2024-10-30 20:58 UTC, samin-cf commented on src/content/docs/cloudflare-one/connections/connect-devices/warp/troubleshooting/warp-logs.mdx
> +| `installed_applications.text` | |
```suggestion
| `installed_applications.txt` | |
```

2024-10-30 20:58 UTC, samin-cf commented on src/content/docs/cloudflare-one/insights/dex/remote-captures.mdx
> +	- **WARP Diagnostics Logs**: Generates a [WARP diagnostic log](/cloudflare-one/connections/connect-devices/warp/troubleshooting/warp-logs/#warp-diag-logs) of the past 96 hours. To include a routing
It's explicitly stated in the UI, but may also be good to note here that the routing test will likely extend the time the diagnostics take to run as each IP from all split tunnel ranges are tested. If the organization has configured lots of ranges, this will impact the performance (for a brief period) of the device during the routing test.

2024-10-30 20:58 UTC, samin-cf commented on src/content/docs/cloudflare-one/insights/dex/remote-captures.mdx
Somewhere in the doc, it'd be good to mention the device will still upload the zip artifact, even if the pcap/warp-diag capture partially succeeds.

Specifically for the pcap command, a partial success could be a scenario where for example the capture on the primary network interface succeeded, but the tunnel interface capture failed (due to whatever reason). The device will still upload the zip artifact containing the successful pcap. Moreover, the device will **always** include a `results.json` file in the pcap zip file that users can parse to determine what pcaps succeeded and what failed. Here is a sample:
```json
{
  "success": [
    {
      "interface": "en0",
      "pcap": "capture-default-20241009-185152.pcap"
    }
  ],
  "failures": [
    {
      "code": "InterfaceNotFound",
      "interface": "tunnel"
    }
  ]
}
```

2024-10-30 20:58 UTC, samin-cf commented on src/content/docs/cloudflare-one/connections/connect-devices/warp/troubleshooting/warp-logs.mdx
> +| `dex.log`  | ? |
`dex.log` would contain logs related to DEX tests execution.

2024-10-30 20:58 UTC, samin-cf commented on src/content/docs/cloudflare-one/connections/connect-devices/warp/troubleshooting/warp-logs.mdx
> +| `dynamic.log` | ? |
If dynamic logging has been enabled for certain targets using `warp-cli`, this file will be present.

2024-10-30 20:58 UTC, samin-cf commented on src/content/docs/cloudflare-one/insights/dex/remote-captures.mdx
> +| Windows  | ✅            | 2024.9.346.0        |
I will circle back here once the client version is released (targeted for Dec. 16 2024). We won't know the version number ahead of time unfortunately.

2024-10-30 20:58 UTC, samin-cf commented on src/content/docs/cloudflare-one/insights/dex/remote-captures.mdx
Can we add a known limitations list somewhere on this page? On Windows, concurrent remote captures are not supported (i.e. if you have start a remote capture while another is in progress, the 2nd one will fail immediately).

2024-11-05 20:02 UTC, samin-cf requested changes

2024-11-05 20:02 UTC, samin-cf commented on src/content/docs/cloudflare-one/insights/dex/remote-captures.mdx
> +| System   | Availability | Minimum WARP version |
Can we indicate the feature is available for beta testing with client (beta) version `2024.10.537.1` available for download at https://install.appcenter.ms/orgs/cloudflare/apps/1.1.1.1-windows/distribution_groups/beta and https://install.appcenter.ms/orgs/cloudflare/apps/1.1.1.1-macos/distribution_groups/beta?

2024-11-05 22:32 UTC, crwaters16 approved these changes

2024-11-05 22:36 UTC, samin-cf approved these changes

2024-11-05 22:37 UTC, merged