[DO] Add seat booking app tutorial
cloudflare/cloudflare-docs pull request #17063
Opened 2024-09-24 16:01 UTC by harshil1712

### Summary

Adds tutorial for the seat booking app.

#### To Do:

- [ ] Update links

2024-09-24 16:32 UTC, lambrospetrou commented on src/content/docs/durable-objects/tutorials/build-a-seat-booking-app/index.mdx
> +Using Durable Objects, you can write reusable code that can handle coordination and state management for multiple clients. Moreover, writing data to an SQLite database is synchronous, which means tha
> writing data to an SQLite database is synchronous, which means that the code will not block the main thread.

Not sure what you refer to here as main thread, but since SQLite is indeed synchronous, anything you do actually does block the DO. Imagine I execute a query and get back a cursor with the results, then while I am iterating that cursor the DO is blocked. Exception to this is any `await something()` I do that leads to IO.

2024-09-24 16:34 UTC, lambrospetrou commented on src/content/docs/durable-objects/tutorials/build-a-seat-booking-app/index.mdx
> +```html title="public/index.html"
Should we put this code into an expandable closed by default since it's not the main point of the tutorial, and they can expand to copy and then close again?

2024-09-24 16:38 UTC, lambrospetrou commented on src/content/docs/durable-objects/tutorials/build-a-seat-booking-app/index.mdx
> +		if ([...cursor][0].name === "seats") {
It might be the case, but is the result of `PRAGMA table_list` always in the same order? If there is a chance the tables are returned such that the `seats` table is not always first, then this should actually iterate over the cursor checking all the results.

```js
[...cursor].find(t => t.name === "seats")
```

2024-09-24 16:39 UTC, lambrospetrou commented on src/content/docs/durable-objects/tutorials/build-a-seat-booking-app/index.mdx
> +		// For this demo, we populate the table with 60 seats.
```suggestion
		// For this demo, we populate the table with 60 seats.
		// Since SQLite in DOs is fast, we can do a query per INSERT insert of batching them in a transaction.
```

2024-09-24 16:41 UTC, lambrospetrou commented on src/content/docs/durable-objects/tutorials/build-a-seat-booking-app/index.mdx
> +		return new Response(greeting);
This is to be deleted?

2024-09-24 19:47 UTC, vy-ton requested changes

2024-09-24 19:47 UTC, vy-ton commented on src/content/docs/durable-objects/tutorials/build-a-seat-booking-app/index.mdx
> +In this tutorial, you will learn how to build a seat reservation app using Durable Objects. This app will allow users to book a seat for a flight. The app will be written in TypeScript and will use t
Can link to `/durable-objects/best-practices/access-durable-objects-storage/#sql-storage`

2024-09-24 19:47 UTC, vy-ton commented on src/content/docs/durable-objects/tutorials/build-a-seat-booking-app/index.mdx
> +Using Durable Objects, you can write reusable code that can handle coordination and state management for multiple clients. Moreover, writing data to an SQLite database is synchronous, which means tha
blog post url will be: blog.cloudflare.com/sqlite-in-durable-objects

2024-09-24 19:47 UTC, vy-ton commented on src/content/docs/durable-objects/tutorials/build-a-seat-booking-app/index.mdx
> +- The application will create a new Durable Object namespace for the flight number, if it does not already exist.
should be a Durable Object (not namespace) for each flight

The Durable Object namespace represents all flights

2024-09-24 19:47 UTC, vy-ton commented on src/content/docs/durable-objects/tutorials/build-a-seat-booking-app/index.mdx
> +- The application will create a new Durable Object namespace for the flight number, if it does not already exist.
Same comment for mentions of `namespace` in subsequent bullets.

We should link to the updated glossary. `A Durable Object class for flight information. Each flight is a Durable Object`

2024-09-24 19:47 UTC, vy-ton commented on src/content/docs/durable-objects/tutorials/build-a-seat-booking-app/index.mdx
> +	async sayHello(name: string): Promise<string> {
Can we remove all the "hello world" code?

2024-09-24 19:47 UTC, vy-ton commented on src/content/docs/durable-objects/tutorials/build-a-seat-booking-app/index.mdx
> +			return new Response("Flight ID not found", { status: 404 });
Error could tell the user to supply flight id using `?flightid=`

2024-09-24 19:47 UTC, vy-ton commented on src/content/docs/durable-objects/tutorials/build-a-seat-booking-app/index.mdx
> +    async fetch(request: Request) {
We should default to using RPC to communicate between Worker and Durable Object. This fetch logic can live in the Worker instead.

2024-09-24 21:27 UTC, harshil1712 commented on src/content/docs/durable-objects/tutorials/build-a-seat-booking-app/index.mdx
> +Using Durable Objects, you can write reusable code that can handle coordination and state management for multiple clients. Moreover, writing data to an SQLite database is synchronous, which means tha
Ah yes. The words here are not correct. Can you help me with a better sentence? I was trying to highlight that the SQLite operations are synchronous which is an advantage.

2024-09-24 21:40 UTC, harshil1712 commented on src/content/docs/durable-objects/tutorials/build-a-seat-booking-app/index.mdx
> +		return new Response(greeting);
Yes, the code block highlights what needs to be added and what needs to be deleted. Attaching a screenshot from the preview

![Screenshot 2024-09-24 at 23 38 52](https://github.com/user-attachments/assets/8de478fe-daa6-43ec-8e5b-1938f1397fd3)

2024-09-24 21:41 UTC, harshil1712 commented on src/content/docs/durable-objects/tutorials/build-a-seat-booking-app/index.mdx
> +In this tutorial, you will learn how to build a seat reservation app using Durable Objects. This app will allow users to book a seat for a flight. The app will be written in TypeScript and will use t
Thank you!

2024-09-24 21:42 UTC, harshil1712 commented on src/content/docs/durable-objects/tutorials/build-a-seat-booking-app/index.mdx
> +Using Durable Objects, you can write reusable code that can handle coordination and state management for multiple clients. Moreover, writing data to an SQLite database is synchronous, which means tha
Thank you!

2024-09-24 21:48 UTC, harshil1712 commented on src/content/docs/durable-objects/tutorials/build-a-seat-booking-app/index.mdx
> +	async sayHello(name: string): Promise<string> {
Yes, the code block highlights what needs to be added and what needs to be deleted. Attaching a screenshot from the preview

![Screenshot 2024-09-24 at 23 48 10](https://github.com/user-attachments/assets/ee0ab4d2-0324-4ab9-97e5-00e18486553b)

2024-09-25 08:48 UTC, lambrospetrou commented on src/content/docs/durable-objects/tutorials/build-a-seat-booking-app/index.mdx
> +Using Durable Objects, you can write reusable code that can handle coordination and state management for multiple clients. Moreover, writing data to an SQLite database is synchronous, which means tha
I would simplify to: `Moreover, writing data to SQLite in Durable Objects is synchronous and uses local discs, therefore all queries are executed with great performance.`

2024-09-25 14:12 UTC, harshil1712 commented on src/content/docs/durable-objects/tutorials/build-a-seat-booking-app/index.mdx
> +Using Durable Objects, you can write reusable code that can handle coordination and state management for multiple clients. Moreover, writing data to an SQLite database is synchronous, which means tha
Thank you!

2024-09-25 15:35 UTC, vy-ton requested changes

2024-09-25 15:35 UTC, vy-ton commented on src/content/docs/durable-objects/tutorials/build-a-seat-booking-app/index.mdx
> +Using Durable Objects, you can write reusable code that can handle coordination and state management for multiple clients. Moreover, writing data to SQLite in Durable Objects is synchronous and uses
```suggestion
Using Durable Objects, you can write reusable code that can handle coordination and state management for multiple clients. Moreover, writing data to SQLite in Durable Objects is synchronous and uses local disks, therefore all queries are executed with great performance. You can learn more about SQLite storage in Durable Objects in the [SQLite in Durable Objects blog post](https://blog.cloudflare.com/sqlite-in-durable-objects).
```

2024-09-25 15:35 UTC, vy-ton commented on src/content/docs/durable-objects/tutorials/build-a-seat-booking-app/index.mdx
> +	 * The Durable Object exposes an RPC method sayHello which will be invoked when when a Durable
please remove unused code, distracting to the user

2024-09-25 15:35 UTC, vy-ton commented on src/content/docs/durable-objects/tutorials/build-a-seat-booking-app/index.mdx
> +		// We will create a `DurableObjectId` using the pathname from the Worker request
code from "Hello World" example should be deleted. Let's make code copy/paste for the tutorial

2024-09-25 15:35 UTC, vy-ton commented on src/content/docs/durable-objects/tutorials/build-a-seat-booking-app/index.mdx
> +		return stub.fetch(request);
Delete. At this point, Worker has not sent a request to the DO.

If user ran code at this point, error would be returned because DO has no fetch handler.

2024-09-25 15:35 UTC, vy-ton commented on src/content/docs/durable-objects/tutorials/build-a-seat-booking-app/index.mdx
> +		return stub.fetch(request);
should be deleted

2024-09-25 15:35 UTC, vy-ton commented on src/content/docs/durable-objects/tutorials/build-a-seat-booking-app/index.mdx
> +---
For code can we stick with 2 space tab, helps condense presentation on the docs page

2024-09-25 15:35 UTC, vy-ton commented on src/content/docs/durable-objects/tutorials/build-a-seat-booking-app/index.mdx
> +			return new Response(JSON.stringify(await stub.getSeats()), {
`getSeats()` already JSON.stringify its result?

I would be consistent with DO RPC methods returning non-Response and creating the Response in the Worker below?

2024-09-25 15:35 UTC, vy-ton commented on src/content/docs/durable-objects/tutorials/build-a-seat-booking-app/index.mdx
> +Update the URL with the flight ID as `http://localhost:8787?flightId=1234`. The application displays the seats for the flight with the ID `1234`.
dont you need `/seats?flightId=1234`?

2024-09-25 15:35 UTC, vy-ton commented on src/content/docs/durable-objects/tutorials/build-a-seat-booking-app/index.mdx
> +title: Build a seat booking app with Durable Objects
cc @joshthoward for code review

2024-09-25 20:45 UTC, jclee commented on src/content/docs/durable-objects/tutorials/build-a-seat-booking-app/index.mdx
> +new_sqlite_classes = ["MyDurableObject"]
I think we want just the `new_sqlite_classes` property here?  Including both that and `new_classes` seems to throw an error, which is what I'd expect.

2024-09-25 20:51 UTC, harshil1712 commented on src/content/docs/durable-objects/tutorials/build-a-seat-booking-app/index.mdx
> +Update the URL with the flight ID as `http://localhost:8787?flightId=1234`. The application displays the seats for the flight with the ID `1234`.
The front-end handles it so `/seats` is not required.

2024-09-25 20:54 UTC, harshil1712 commented on src/content/docs/durable-objects/tutorials/build-a-seat-booking-app/index.mdx
> +new_sqlite_classes = ["MyDurableObject"]
@jclee, true. The preview highlights this. Unfortunately, it is not visible on GitHub. But I am updating this to remove all the unnecessary code.

2024-09-25 21:22 UTC, harshil1712 commented on src/content/docs/durable-objects/tutorials/build-a-seat-booking-app/index.mdx
> +		return stub.fetch(request);
Added a step to update DO to have a fetch handler. This way, if the user is running the development server, they will not get any errors.

2024-09-25 22:49 UTC, jclee commented on src/content/docs/durable-objects/tutorials/build-a-seat-booking-app/index.mdx
> +    			const ws = new WebSocket(`ws://localhost:8787/ws?flightId=${flightId}`);
I think with the socket statically set to localhost, the project will only work locally?  But not sure if there's an easy way to initialize it correctly in this static asset for both local and deployed workers.

2024-09-26 10:05 UTC, harshil1712 commented on src/content/docs/durable-objects/tutorials/build-a-seat-booking-app/index.mdx
> +    			const ws = new WebSocket(`ws://localhost:8787/ws?flightId=${flightId}`);
Ah, nice catch! Adding a step in the deploy section.

2024-09-26 12:01 UTC, harshil1712 commented on src/content/docs/durable-objects/tutorials/build-a-seat-booking-app/index.mdx
> +    			const ws = new WebSocket(`ws://localhost:8787/ws?flightId=${flightId}`);
I have updated the HTML code to handle this. So need to add another step for the user

2024-09-27 14:41 UTC, Oxyjun approved these changes

2024-09-27 14:58 UTC, vy-ton reviewed
Thanks @harshil1712 for addressing code feedback!

2024-09-27 14:58 UTC, vy-ton commented on src/content/docs/durable-objects/tutorials/build-a-seat-booking-app/index.mdx
> +title: Build a seat booking app with Durable Objects
```suggestion
title: Build a seat booking app with SQLite in Durable Objects
```

2024-09-27 14:58 UTC, vy-ton commented on src/content/docs/durable-objects/tutorials/build-a-seat-booking-app/index.mdx
> +In this tutorial, you will learn how to build a seat reservation app using Durable Objects. This app will allow users to book a seat for a flight. The app will be written in TypeScript and will use t
```suggestion
In this tutorial, you will learn how to build a seat reservation app using Durable Objects. This app will allow users to book a seat for a flight. The app will be written in TypeScript and will use the new [SQLite storage backend in Durable Object](/durable-objects/best-practices/access-durable-objects-storage/#sqlite-storage-backend) to store the data.
```

2024-09-27 14:58 UTC, vy-ton commented on src/content/docs/durable-objects/tutorials/build-a-seat-booking-app/index.mdx
> +The application already has the binding for the Durable Objects class configured in `wrangler.toml`. If you update the name of the Durable Objects class in `src/index.ts`, make sure to also update th
Rename `MyDurableObject` to `Flight` to re-enforce the example

2024-09-27 14:58 UTC, vy-ton commented on src/content/docs/durable-objects/tutorials/build-a-seat-booking-app/index.mdx
> +		let result = [...cursor][0]; // Get the first result from the cursor.
Can we highlight the `one()` method here, https://developers.cloudflare.com/durable-objects/api/storage-api/#returns?

2024-09-27 14:58 UTC, vy-ton commented on src/content/docs/durable-objects/tutorials/build-a-seat-booking-app/index.mdx
> +- used the SQLite storage in Durable Objects to store the seats for a flight.
```suggestion
- used the SQLite storage backend in Durable Objects to store the seats for a flight.
```

2024-09-27 15:29 UTC, harshil1712 commented on src/content/docs/durable-objects/tutorials/build-a-seat-booking-app/index.mdx
> +		let result = [...cursor][0]; // Get the first result from the cursor.
This throws an error if the query doesn't return any output.

<img width="1119" alt="Screenshot 2024-09-27 at 16 27 13" src="https://github.com/user-attachments/assets/3a6c9d5c-b141-4c72-920f-79e50a6b7a6b">

Updating this to instead use the `toArray()` method

2024-09-27 16:18 UTC, Oxyjun approved these changes

2024-09-30 14:10 UTC, vy-ton approved these changes

2024-09-30 14:11 UTC, vy-ton commented
@harshil1712 @Oxyjun I'm not able to merge, possibly need to rebase?

2024-09-30 14:22 UTC, merged