Workers AI Model Catalog & Model Pages
cloudflare/cloudflare-docs pull request #17068
Opened 2024-09-24 17:14 UTC by hturan

### Summary

This PR updates how content for Workers AI is generated and presented, opting to pull from the API at build time. This means that model information (such as model updates, schemas, etc.) will be updated automatically without the need for changes to this repo.

Alongside this, we've updated the main models list to have search, along with the ability to filter by task type, author, and model capabilities. Individual model pages have also been redesigned to show parameters based on the individual model schemas. Model pages also now act in a similar fashion to the rest of the docs, with a table of contents and matching headers.

### Screenshots
![Screenshot 2024-09-24 at 18 13 04](https://github.com/user-attachments/assets/0789bbae-9c1e-4622-8e07-ae450742b729)

![Screenshot 2024-09-24 at 18 13 10](https://github.com/user-attachments/assets/1b33aa34-a4e2-43e2-bec5-a2ed3b1ff4d2)

![Screenshot 2024-09-24 at 18 13 15](https://github.com/user-attachments/assets/c44fa81c-0dd3-42aa-a5bd-34d876c1be45)

### Documentation checklist

- [x] The [documentation style guide](https://developers.cloudflare.com/style-guide/) has been adhered to.
- [ ] If a larger change - such as adding a new page- an issue has been opened in relation to any incorrect or out of date information that this PR fixes.

2024-09-24 17:16 UTC, hturan commented on astro.config.mjs
> +		react(),
These changes seem to mostly be `prettier`, this is the only addition.

2024-09-24 17:17 UTC, hturan commented on src/components/models/data.ts
This could probably be cleaned up a little, or integrated into a static `collection`.

2024-09-24 17:20 UTC, hturan commented on src/content/docs/workers-ai/models/index.mdx
It's worth touching on this a little —

`src/content/docs/workers-ai/models/index.mdx` renders `src/pages/workers-ai/models/index.astro` which renders `src/components/ModelCatalog.jsx`. This is because Starlight doesn't add `.astro` files in `/pages` to the sidebar, and Starlight can't handle JSX imports from within MDX `content` files. Ideally there'd be a cleaner solution here, but for now, this is all that works.

2024-09-25 17:43 UTC, KianNH requested changes

2024-09-25 17:43 UTC, KianNH commented on src/pages/workers-ai/models/[name].astro
> +	</div>
I think we'd want to use the `Code` component here: https://starlight.astro.build/components/code/

2024-09-25 17:43 UTC, KianNH commented on src/components/ModelCatalog.jsx
> +					return (
Can we make these cards have the same height? It looks a little off when there's a model with a short description.

<img width="602" alt="image" src="https://github.com/user-attachments/assets/66317c3c-a74b-4735-b992-e2c0995ccdd3">

2024-09-25 17:43 UTC, KianNH commented on src/components/ModelCatalog.jsx
> +					</span>
Could this filter be controlled by a query param, i.e to link people to a filtered catalog of just "Text Generation"?

In the past we've had an ask for it, and we use that same pattern for `/products/`.

2024-09-25 17:43 UTC, KianNH commented on src/components/ModelCatalog.jsx
> +									/>
The OpenAI SVG is hard to see on dark mode - can we use their white logo if dark mode is enabled?

<img width="281" alt="image" src="https://github.com/user-attachments/assets/d87afea6-d740-4f29-9512-166c2a603ea5">

2024-09-25 17:43 UTC, KianNH commented on src/components/models/SchemaRow.astro
> +	<code class="mr-2 font-mono rounded-md bg-gray-100">
It looks like we always get trailing whitespace here:

<img width="262" alt="image" src="https://github.com/user-attachments/assets/079e58eb-7d2e-466d-a228-26de9934e5d9">

2024-09-25 17:43 UTC, KianNH commented on src/components/models/SchemaRow.astro
> +	}
There is a `MetaInfo` component which we use in other spots (i.e Wrangler commands): https://developers.cloudflare.com/style-guide/components/type-highlighting/#metainfo

2024-09-25 17:43 UTC, KianNH commented on src/pages/workers-ai/models/[name].astro
> +	<Tabs>
I wonder if word-wrapping these schemas would make sense, as they have some fairly long lines - but if it looks weird wrapped then happy to leave it as-is!

https://expressive-code.com/key-features/code-component/#wrap

2024-09-25 17:43 UTC, KianNH commented on src/pages/workers-ai/models/[name].astro
> +	<Tabs>
I wonder if word-wrapping these schemas would make sense, as they have some fairly long lines - but if it looks weird wrapped then happy to leave it as-is!

https://expressive-code.com/key-features/code-component/#wrap

2024-09-25 17:47 UTC, Cherry reviewed
There's a lot of custom tailwind styles here, which make this page feel quite a bit more disjunct than the rest of the docs. Colours, badges, layouts, padding, are all just a bit different - was there a reason for this instead of using more Starlight/repo-native components that already handle light/dark mode and such without issues, and will be more maintained?

Examples:

<details>
<summary>Details</summary>

- Input box highlighting:
![](https://i.james.pub/file/2024/09/0e92c04b-b122-4db8-ad10-3f871a73afef.png)

- Box focus states:
![](https://i.james.pub/file/2024/09/3c6f1aba-701c-4b5c-a843-ebfa92830115.png)

- Mismatched beta badges
![](https://i.james.pub/file/2024/09/c945709c-d685-45ce-9d0f-7884805973f8.png)

- Logo visibility on dark mode
![](https://i.james.pub/file/2024/09/b58399fa-f207-410d-99dc-ff3f4b3965e4.png)

</details>

---

If I search for something that doesn't exist, like "chatgpt" as a newbie to AI might) the [Models page](https://hturan-model-cards.cloudflare-docs-7ou.pages.dev/workers-ai/models/) just becomes empty - there's nothing indicating that nothing matched my search.

![](https://i.james.pub/file/2024/09/053aa4bf-0ea1-4b1e-8dc1-ffedc9edbb4e.png)

---

2024-09-25 17:47 UTC, Cherry commented on src/components/ModelCatalog.jsx
> +import { useState } from "react";
Most other files here use strict typing and TS / TSX files - why JSX out of interest? Are the types for AI not that strong?

2024-09-25 17:47 UTC, Cherry commented on src/components/models/SchemaRow.astro
> +---
type errors that need addressing: https://github.com/cloudflare/cloudflare-docs/actions/runs/11038101046/job/30660497241?pr=17068#step:7:55

2024-09-25 17:47 UTC, Cherry commented on src/components/models/SchemaViewer.astro
> +---
type errors that need addressing: https://github.com/cloudflare/cloudflare-docs/actions/runs/11038101046/job/30660497241?pr=17068#step:7:60

2024-09-25 17:47 UTC, Cherry commented on src/pages/workers-ai/models/[name].astro
> +	headings={[
type errors: https://github.com/cloudflare/cloudflare-docs/actions/runs/11038101046/job/30660497241?pr=17068#step:7:103

2024-09-25 17:47 UTC, Cherry commented on src/pages/workers-ai/models/[name].astro
> +const author = authorData[model.name.split("/")[1]];
type errors: https://github.com/cloudflare/cloudflare-docs/actions/runs/11038101046/job/30660497241?pr=17068#step:7:108

2024-09-26 09:37 UTC, hturan commented on src/components/ModelCatalog.jsx
> +import { useState } from "react";
Yeah! This actually didn't land in time — mostly when building out features that are in flux I work in JSX and then type after the fact. When this feature lands it'll definitely be in TSX.

2024-09-26 09:40 UTC, hturan commented on src/components/ModelCatalog.jsx
> +import { useState } from "react";
No real reason here — the models and data are strongly typed, but this page was changing up until the last minute, and I prefer not to use TS for things in flux. We'll type this up (along with some other pieces) soon!

2024-09-26 09:42 UTC, hturan commented on src/pages/workers-ai/models/[name].astro
> +	<Tabs>
I think we'll want to keep the formatting as showing nesting for keys works well. I think I'll improve schema handing in the future with some dedicated components for showing raw schemas and parsed params.

2024-09-26 12:19 UTC, mchenco approved these changes

2024-09-26 12:51 UTC, Cherry reviewed
It's also extremely concerning that an external API can now entirely prevent docs builds if it fails, and will moving forward in completely unrelated PRs. In my own monitoring, the AI models API regularly hits issues so this is going to cause problems in other PRs at some point.

2024-09-26 13:40 UTC, hturan commented
> It's also extremely concerning that an external API can now entirely prevent docs builds if it fails, and will moving forward in completely unrelated PRs. In my own monitoring, the AI models API regularly hits issues so this is going to cause problems in other PRs at some point.

Very fair. This API has ended up being less stable than anticipated (despite heavy caching both in and out). I've updated this to make model data static JSON files (akin to the old YAML) and have placed a quick updater script in `bin`. Local dev and other builds now no longer reliant on that API.

2024-09-26 14:42 UTC, KianNH approved these changes

2024-09-26 14:42 UTC, merged