fixes to Environment in Workers Docs
cloudflare/cloudflare-docs pull request #1717
Opened 2021-07-02 18:25 UTC by deadlypants1973

closes https://github.com/cloudflare/cloudflare-docs/issues/18

2021-07-02 22:30 UTC, deadlypants1973 commented on products/workers/src/content/cli-wrangler/configuration.md
> -</Aside>
@signalnerve , can this be deleted? It seems out of place.

2021-07-06 19:01 UTC, deadlypants1973 commented on products/workers/src/content/cli-wrangler/configuration.md
> +account id = "your-other-account-id"
```suggestion
account_id = "your-other-account-id"
```

2021-07-06 20:20 UTC, signalnerve approved these changes

2021-07-06 20:20 UTC, signalnerve commented on products/workers/src/content/cli-wrangler/configuration.md
> -</Aside>
yes plz

2021-07-06 20:23 UTC, signalnerve commented on products/workers/src/content/cli-wrangler/configuration.md
> +  - The command used to build your Worker. On Linus and macOS system, the command is executed in the `sh` shell and the `cmd` shell for Windows. The `&&` and `||` shell operators may be used.
```suggestion
  - The command used to build your Worker. On Linux and macOS system, the command is executed in the `sh` shell and the `cmd` shell for Windows. The `&&` and `||` shell operators may be used.
```

2021-07-06 20:23 UTC, signalnerve commented on products/workers/src/content/cli-wrangler/configuration.md
> +In the future, Modules will become the default format for writing Workers scripts. Until then, Cloudflare is still working on "full" support, so consider Modules as a beta feature.
```suggestion
Modules support in Cloudflare Workers is currently in beta.
```

Can we rephrase this? I don't love the style of saying "we are going to change everything and this is fundamentally not ready yet" -- IMO this reads better. cc @lukeed

2021-07-06 20:23 UTC, signalnerve commented
sorry, caught a few things after initial review, couple fixes needed before merge

2021-07-06 20:34 UTC, lukeed reviewed
super tiny things, typos mostly :)

2021-07-06 20:34 UTC, lukeed commented on products/workers/src/content/cli-wrangler/configuration.md
> +Your project will need some configuration before you can publish your Worker. Configuration is done through changes to keys and values stored in a `wrangler.toml` file. You must manually edit this fi
Optional, but to address the "do we say where this goes" thought you had

```suggestion
Your project will need some configuration before you can publish your Worker. Configuration is done through changes to keys and values stored in a `wrangler.toml` file located in the root of your project directory. You must manually edit this file to edit your keys and values before you can publish.
```

2021-07-06 20:34 UTC, lukeed commented on products/workers/src/content/cli-wrangler/configuration.md
> +Top-level configuration is the collection of values you specify at the top of your `wrangler.toml` file. These values will be inherited by all environments, unless otherwise specified in the environm
unsure of this, mostly just looking at it:

```suggestion
Top-level configuration is the collection of values you specify at the top of your `wrangler.toml` file. These values will be inherited by all environments and, in most cases, can have environment-specific overrides.
```

2021-07-06 20:34 UTC, lukeed commented on products/workers/src/content/cli-wrangler/configuration.md
> +There are three type of keys present in a `wrangler.toml` file:
```suggestion
There are three types of keys in a `wrangler.toml` file: 
```

2021-07-06 20:34 UTC, lukeed commented on products/workers/src/content/cli-wrangler/configuration.md
> +`vars` defines a table of [environment variables](/workers/platform/environments#environment-variables) provided to your Worker script. These are plaintext values.
```suggestion
The `vars` key defines a table of [environment variables](/workers/platform/environments#environment-variables) provided to your Worker script. All values are plaintext values.
```

2021-07-06 20:34 UTC, lukeed commented on products/workers/src/content/cli-wrangler/configuration.md
> +`kv_namespaces` defines a list of KV namespace bindings for your Worker.
Like `vars`, should we add a line somewhere here about the alternative format? Both formats are used throughout this file (sorry) but we could add it here too for consistency/visibility.

2021-07-06 20:34 UTC, lukeed commented on products/workers/src/content/cli-wrangler/configuration.md
> +  - The directory containing your static assets. It must be a path relative to your `wrangler.toml`file. Example: `bucket = "./public"`
```suggestion
  - The directory containing your static assets. It must be a path relative to your `wrangler.toml` file. Example: `bucket = "./public"`
```

2021-07-06 20:34 UTC, lukeed commented on products/workers/src/content/cli-wrangler/configuration.md
> +  - The IP address for the local `wrangler dev` server to listen on, defaults to 127.0.0.1.
```suggestion
  - The IP address for the local `wrangler dev` server to listen on, defaults to `127.0.0.1`.
```

2021-07-06 20:34 UTC, lukeed commented on products/workers/src/content/cli-wrangler/configuration.md
> +  - Port for local `wrangler dev` server to listen on, defaults to 8787.
```suggestion
  - Port for local `wrangler dev` server to listen on, defaults to `8787`.
```

2021-07-06 20:34 UTC, lukeed commented on products/workers/src/content/cli-wrangler/configuration.md
> +  - Protocol that local `wrangler dev` server listen to requests on, defaults to http.
```suggestion
  - Protocol that local `wrangler dev` server listen to requests on, defaults to `http`.
```

2021-07-06 20:34 UTC, lukeed commented on products/workers/src/content/cli-wrangler/configuration.md
> +  - Protocol that `wrangler dev` forwards requests on, defaults to https.
```suggestion
  - Protocol that `wrangler dev` forwards requests on, defaults to `https`.
```

2021-07-06 20:34 UTC, lukeed commented on products/workers/src/content/cli-wrangler/configuration.md
> +  - The command used to build your Worker. On Linus and macOS system, the command is executed in the `sh` shell and the `cmd` shell for Windows. The `&&` and `||` shell operators may be used.
```suggestion
  - The command used to build your Worker. On Linux and macOS, the command is executed in the `sh` shell and the `cmd` shell for Windows. The `&&` and `||` shell operators may be used.
```

2021-07-06 20:34 UTC, lukeed commented on products/workers/src/content/cli-wrangler/configuration.md
> +Uploaded modules may `import` other uploaded ES Modules. If using the CommonJS format, you may `require` other uploaded CommonJS modules.
```suggestion
An uploaded module may `import` other uploaded ES Modules. If using the CommonJS format, you may `require` other uploaded CommonJS modules.
```

2021-07-06 20:34 UTC, lukeed commented on products/workers/src/content/platform/environments.md
> +The layout of an example `[end.dev]` environment is displayed below:
```suggestion
The layout of an example `[env.dev]` environment is displayed below:
```

2021-07-06 20:34 UTC, lukeed commented on products/workers/src/content/platform/environments.md
> +The `wrangler.toml` file below adds two environments, `[env.staging]` and `[env.production]`, to the `wrangler.toml` file. Note that you must provide a [`route`/`routes` key](/workers/cli-wrangler/co
```suggestion
The `wrangler.toml` file below adds two environments, `[env.staging]` and `[env.production]`, to the `wrangler.toml` file. Note that you must provide a [`route` or `routes` key](/workers/cli-wrangler/configuration#keys) for each environment if you are deploying to a custom domain.
```

2021-07-06 20:34 UTC, lukeed commented on products/workers/src/content/platform/environments.md
> +Your default `wrangler build`, `wrangler preview`, and `wrangler publish` commands will all build with `webpack.dev.js`. Any commnds tied to the staging environment will also use this configuration;
```suggestion
Your default `wrangler build`, `wrangler preview`, and `wrangler publish` commands will all build with `webpack.dev.js`. Any commands tied to the staging environment will also use this configuration; for example, `wrangler build -e staging`, `wrangler preview -e staging`, and `wrangler publish -e staging`.
```

2021-07-06 20:39 UTC, lukeed commented on products/workers/src/content/cli-wrangler/configuration.md
> +In the future, Modules will become the default format for writing Workers scripts. Until then, Cloudflare is still working on "full" support, so consider Modules as a beta feature.
Makes sense, although to some extent, being "in beta" implies that anyway. 😄 
Just fixed up what the the DO team had written, but I like your suggestion.

2021-07-06 22:53 UTC, kodster28 commented on products/workers/src/content/cli-wrangler/configuration.md
> +Your project will need some configuration before you can publish your Worker. Configuration is done through changes to keys and values stored in a `wrangler.toml` file. You must manually edit this fi
```suggestion
Your project will need some configuration before you can publish your Worker. Configuration is done through changes to keys and values stored in a `wrangler.toml` file. You must manually edit the keys and values in this file before you can publish.
```

2021-07-06 22:54 UTC, kodster28 commented on products/workers/src/content/cli-wrangler/configuration.md
> +Top-level configuration is the collection of values you specify at the top of your `wrangler.toml` file. These values will be inherited by all environments, unless otherwise specified in the environm
```suggestion
The top-level configuration is the collection of values you specify at the top of your `wrangler.toml` file. These values will be inherited by all environments, unless otherwise specified in the environment.
```

2021-07-06 22:57 UTC, kodster28 commented on products/workers/src/content/cli-wrangler/configuration.md
>  Environments is a feature that allows you to deploy the same project to multiple places under multiple names. These environments are utilized with the `--env` or `-e` flag on the commands that are de
```suggestion
Environments is a feature that allows you to deploy the same project to multiple places under multiple names. These environments are utilized with the `--env` or `-e` flag on the commands deploying live Worker scripts:
```

2021-07-06 23:00 UTC, kodster28 commented on products/workers/src/content/cli-wrangler/configuration.md
>  Environments is a feature that allows you to deploy the same project to multiple places under multiple names. These environments are utilized with the `--env` or `-e` flag on the commands that are de
Also, might be b/c I don't understand the source material, but the organization feels a touch confusing here. Like, we're talking about the generic layout of a wranger file and then jumping to info about a completely different topic (environments).

Thinking everything above this line might belong in the first section (`Background`) or a new section right above?

2021-07-06 23:04 UTC, kodster28 commented on products/workers/src/content/cli-wrangler/configuration.md
> +* **Top level only** keys are required to be configured at the top level of your `wrangler.toml` file only; multiple environments on the same project must share this key's value.
If not a term from the UI, change to `Top-level only keys`.

2021-07-06 23:04 UTC, kodster28 commented on products/workers/src/content/cli-wrangler/configuration.md
> +* **Top level only** keys are required to be configured at the top level of your `wrangler.toml` file only; multiple environments on the same project must share this key's value.
```suggestion
* **Top level only** keys must be configured at the top level of your `wrangler.toml` file only. Multiple environments on the same project must share this key's value.
```

2021-07-06 23:05 UTC, kodster28 commented on products/workers/src/content/cli-wrangler/configuration.md
> +* **Inherited** keys can be configured at the top level and/or environment. If the key is defined only at the top level, the environment will use the key's value from the top level. If the key is def
`At the top and/or environment level.`?

2021-07-06 23:10 UTC, kodster28 commented on products/workers/src/content/cli-wrangler/configuration.md
> +  - This is the ID of the zone or domain you want to run your script on. It can also be specified through the `CF_ZONE_ID` environment variable. This key is optional if you are using only a [workers.
Is it a problem that the `workers.dev` redirects to https://workers.cloudflare.com/?

2021-07-06 23:11 UTC, kodster28 commented on products/workers/src/content/cli-wrangler/configuration.md
> +`vars` defines a table of [environment variables](/workers/platform/environments#environment-variables) provided to your Worker script. These are plaintext values.
Broken link.

2021-07-06 23:11 UTC, kodster28 commented on products/workers/src/content/cli-wrangler/configuration.md
> +  - The name of the global variable your code will reference. It will be provided as a [KV runtime instance](/workers/runtime-apis/kv).
Broken link

2021-07-06 23:12 UTC, kodster28 commented on products/workers/src/content/cli-wrangler/configuration.md
> +To learn more about the optional `include` and `exclude` fields, refer to [Ignoring Subsets of Static Assets](#ignoring-subsets-of-static-assets).
Broken link, I believe

2021-07-06 23:15 UTC, kodster28 commented on products/workers/src/content/platform/environments.md
> +The most common use case for environments is deploying to a staging subdomain before your production environment. `wrangler publish` will determine its destination by your top-level configuration in
Broken links for wrangler.toml file + env.name configuration

2021-07-06 23:16 UTC, kodster28 commented on products/workers/src/content/platform/environments.md
> +The `wrangler.toml` file below adds two environments, `[env.staging]` and `[env.production]`, to the `wrangler.toml` file. Note that you must provide a [`route`/`routes` key](/workers/cli-wrangler/co
Broken link for the `routes` key.

2021-07-06 23:17 UTC, kodster28 commented on products/workers/src/content/platform/environments.md
> +Any defined environment variables (the [`vars`](/workers/cli-wrangler/configuration#vars) key) are exposed as global variables to your Worker.
Broken link

2021-07-06 23:17 UTC, kodster28 commented on products/workers/src/content/platform/environments.md
> +* **KV Namespaces** are defined via the [`kv_namespaces`](/workers/cli-wrangler/configuration#kv_namespaces) config in your `wrangler.toml` and are always provided as [KV runtime instances](/workers/
2 broken links here

2021-07-06 23:18 UTC, kodster28 commented on products/workers/src/content/platform/environments.md
> +    ```toml
This example doesn't render correctly? Or is that the point?

2021-07-06 23:27 UTC, kodster28 commented on products/workers/src/content/cli-wrangler/configuration.md
> +  - Arguments for `wrangler dev`, configure local server.
```suggestion
  - Arguments for `wrangler dev` that configure local server.
```
??

2021-07-06 23:27 UTC, kodster28 commented on products/workers/src/content/cli-wrangler/configuration.md
> +  - Configures cron triggers for executing a Worker on a schedule.
```suggestion
  - Configures cron triggers for running a Worker on a schedule.
```
??

2021-07-06 23:29 UTC, kodster28 commented on products/workers/src/content/cli-wrangler/configuration.md
> +  - Allows configuring a custom build step to be run by Wrangler when building your Worker. See the [custom builds documentation](#build) for more details.
Maybe `Configures a custom build setup for your Workers. See... `

2021-07-06 23:36 UTC, kodster28 commented on products/workers/src/content/cli-wrangler/configuration.md
> +Workers Sites projects use webpack by default. You can [bring your own webpack config](/cli-wrangler/webpack#using-with-workers-sites), however it is important to be aware of your `entry` and `contex
```suggestion
Workers Sites projects use webpack by default. Though you can [bring your own webpack config](/cli-wrangler/webpack#using-with-workers-sites), be aware of your `entry` and `context` settings.
```

2021-07-06 23:39 UTC, kodster28 commented on products/workers/src/content/cli-wrangler/configuration.md
> +  - The directory to watch for changes while using `wrangler dev`, defaults to "src" relative to the project root directory.
```suggestion
  - The directory to watch for changes while using `wrangler dev`, defaults to the `src` relative to the project root directory.
```

2021-07-06 23:39 UTC, kodster28 commented on products/workers/src/content/cli-wrangler/configuration.md
> +    - The format of the Worker script, must be "service-worker".
```suggestion
    - The format of the Worker script, must be `service-worker`.
```

2021-07-06 23:42 UTC, kodster28 commented on products/workers/src/content/cli-wrangler/configuration.md
> +  - The command used to build your Worker. On Linus and macOS system, the command is executed in the `sh` shell and the `cmd` shell for Windows. The `&&` and `||` shell operators may be used.
```suggestion
  - The command used to build your Worker. On Linux and macOS system, the command is executed in the `sh` shell and the `cmd` shell for Windows. The `&&` and `||` shell operators may be used.
```

2021-07-06 23:43 UTC, kodster28 commented on products/workers/src/content/cli-wrangler/configuration.md
> +  - The directory to watch for changes while using `wrangler dev`, defaults to "src" relative to the project root directory.
```suggestion
  - The directory to watch for changes while using `wrangler dev`, defaults to the `src` relative to the project root directory.
```

2021-07-06 23:44 UTC, kodster28 commented on products/workers/src/content/cli-wrangler/configuration.md
> +  - The directory you wish to upload your modules from, defaults to "dist" relative to the project root directory.
```suggestion
  - The directory you wish to upload your modules from, defaults to the `dist` relative to the project root directory.
```

2021-07-06 23:45 UTC, kodster28 commented on products/workers/src/content/platform/environments.md
> +Environments are different contexts that your code runs in. The Workers platform allows you to create and manage different environments. Through environments, users are able to deploy the same projec
```suggestion
Environments are different contexts that your code runs in. The Workers platform allows you to create and manage different environments. Through environments, you can deploy the same project to multiple places under multiple names.
```

2021-07-06 23:46 UTC, kodster28 commented on products/workers/src/content/platform/environments.md
> +These environments are utilized with the `--env` or `-e` flag on `wrangler build`, `wrangler dev`, `wrangler preview`, `wrangler publish` and `wrangler secret`.
```suggestion
These environments are utilized with the `--env` or `-e` flag on `wrangler build`, `wrangler dev`, `wrangler preview`, `wrangler publish`, and `wrangler secret`.
```

2021-07-06 23:49 UTC, kodster28 commented on products/workers/src/content/platform/environments.md
> +The most common use case for environments is deploying to a staging subdomain before your production environment. `wrangler publish` will determine its destination by your top-level configuration in
```suggestion
You will likely use environments to deploy Workers to a staging subdomain before your production environment. `wrangler publish` will determine its destination by the top-level configuration in your `wrangler.toml` [file](/workers/cli-wrangler/commands#generate). You can create other environments beneath the top-level configuration in the `wrangler.toml` file by adding an [`[env.name]` configuration](/workers/cli-wrangler/configuration#environments) and specifying additional keys and values. For details on what keys are inherited by environments from the top-level configuration, see [`wrangler.toml` configuration](/cli-wrangler/configuration#keys).
```

2021-07-06 23:50 UTC, kodster28 commented on products/workers/src/content/platform/environments.md
> +You cannot specify multiple environments with the same name. If this were allowed, publishing each environment would overwrite your previously deployed Worker, and the behavior would not be clear.
```suggestion
You cannot specify multiple environments with the same name. If this were allowed, publishing each environment would overwrite your previously deployed Worker and the behavior would not be clear.
```

2021-07-06 23:51 UTC, kodster28 commented on products/workers/src/content/platform/environments.md
> +`*.workers.dev` allows you to deploy your Workers script [without a registered Cloudflare domain](https://blog.cloudflare.com/announcing-workers-dev/). To claim a `*workers.dev` subdomain, select the
```suggestion
`*.workers.dev` allows you to deploy your Workers script [without a registered Cloudflare domain](https://blog.cloudflare.com/announcing-workers-dev/). To claim a `*workers.dev` subdomain, select the **Workers** icon on your account home or **Workers** then **Manage Workers** on your zone's dashboard, and begin setup on the right side of the Workers' dashboard under **Your subdomain**.
```

2021-07-06 23:52 UTC, kodster28 commented on products/workers/src/content/platform/environments.md
> +`*.workers.dev` allows you to deploy your Workers script [without a registered Cloudflare domain](https://blog.cloudflare.com/announcing-workers-dev/). To claim a `*workers.dev` subdomain, select the
Are the differences between `*.workers.dev` and `*workers.dev` intentional?

2021-07-06 23:54 UTC, kodster28 commented on products/workers/src/content/platform/environments.md
> +An environment may be defined by specifying an `[env.name]` block with its own values in your `wrangler.toml` file. Values within this block may override top-level configuration values with the same
```suggestion
You can define an environment by specifying an `[env.name]` block with its own values in your `wrangler.toml` file. Values within this block may override top-level configuration values with the same key. 
```

2021-07-06 23:54 UTC, kodster28 commented on products/workers/src/content/platform/environments.md
> +Environments enable users to write and deploy projects to multiple places.
```suggestion
Environments enable you to write and deploy projects to multiple places. 
```

2021-07-06 23:55 UTC, kodster28 commented on products/workers/src/content/platform/environments.md
> +The `wrangler.toml` file below adds two environments, `[env.staging]` and `[env.production]`, to the `wrangler.toml` file. Note that you must provide a [`route`/`routes` key](/workers/cli-wrangler/co
```suggestion
The `wrangler.toml` file below adds two environments, `[env.staging]` and `[env.production]`, to the `wrangler.toml` file. If you are deploying to a custom domain, you must provide a [`route` or `routes` key](/workers/cli-wrangler/configuration#keys) for each environment.
```

2021-07-06 23:55 UTC, kodster28 commented on products/workers/src/content/platform/environments.md
>  ### workers.dev as a first class target
```suggestion
### workers.dev as a first-class target
```

2021-07-06 23:56 UTC, kodster28 commented on products/workers/src/content/platform/environments.md
>  ### workers.dev as a first class target
```suggestion
### workers.dev as a first-class target
```

2021-07-06 23:58 UTC, kodster28 commented on products/workers/src/content/platform/environments.md
> +* **environment variables** are defined via the `[vars]` config in your `wranger.toml` file and are always plaintext values.
Is there a reason why these are lowercased?

2021-07-06 23:59 UTC, kodster28 commented on products/workers/src/content/platform/environments.md
> +* **secrets** are defined by running [`wrangler secret put <NAME>`](/cli-wrangler/commands#secret) in your terminal, where `<NAME>` is the name of your binding. You may assign environment-specific se
```suggestion
* **secrets** are defined by running [`wrangler secret put <NAME>`](/cli-wrangler/commands#secret) in your terminal, where `<NAME>` is the name of your binding. You may assign environment-specific secrets by re-running the command `wrangler secret put <NAME> -e` or `wrangler secret put <NAME> --env`. Keep a list of the secrets used in your code in your `wrangler.toml` file, like the example under `[secrets]`:
```

2021-07-07 00:00 UTC, kodster28 commented on products/workers/src/content/platform/environments.md
> +With this configuration, no errors will be thrown. However, only `type = "webpack"` will be used, even in a `--env production` setting.
```suggestion
With this configuration, no errors will be thrown. However, only `type = "webpack"` will be used, even in an `--env production` setting.
```

2021-07-07 00:00 UTC, kodster28 commented on products/workers/src/content/platform/environments.md
> +Wrangler will fail to deploy when both  `workers_dev = true` and `route` (or `routes`) are defined. If you are trying to deploy to a `*.workers.dev` domain, you must remove the `route` or `routes` va
```suggestion
Wrangler will fail to deploy when both  `workers_dev = true` and `route` (or `routes`) are defined. If you are trying to deploy to a `*.workers.dev` domain, remove the `route` or `routes` value.
```

2021-07-07 00:01 UTC, kodster28 requested changes
Looks mostly good except for a few broken links (and small grammar things throughout)

2021-07-07 12:11 UTC, deadlypants1973 commented on products/workers/src/content/cli-wrangler/configuration.md
> +  - Arguments for `wrangler dev`, configure local server.
@lukeed - I think we passed this one on review but does it make sense with the 'that' added?

2021-07-07 15:14 UTC, lukeed commented on products/workers/src/content/cli-wrangler/configuration.md
> +  - Arguments for `wrangler dev`, configure local server.
Yup

2021-07-07 16:21 UTC, lukeed commented on products/workers/src/content/cli-wrangler/configuration.md
> +  - The command used to build your Worker. On Linux and macOS system, the command is executed in the `sh` shell and the `cmd` shell for Windows. The `&&` and `||` shell operators may be used.
```suggestion
  - The command used to build your Worker. On Linux and macOS, the command is executed in the `sh` shell and the `cmd` shell for Windows. The `&&` and `||` shell operators may be used.
```

2021-07-07 20:13 UTC, lukeed commented
Kate and I resolved/fixed up `git` state together

2021-07-08 13:05 UTC, deadlypants1973 commented on products/workers/src/content/cli-wrangler/configuration.md
>  Environments is a feature that allows you to deploy the same project to multiple places under multiple names. These environments are utilized with the `--env` or `-e` flag on the commands that are de
```suggestion
Environments is a feature that allows you to deploy the same project to multiple places under multiple names. These environments are utilized with the `--env` or `-e` flag on the [commands](/cli-wrangler/commands) that are deploying live Worker scripts:
```

2021-07-08 13:18 UTC, deadlypants1973 commented on products/workers/src/content/cli-wrangler/configuration.md
> +
```suggestion
]
```
Alternatively, you can define `kv namespaces` like so:

```toml
[[kv_namespaces]]
binding = "FOO"
preview_id = "abc456"
id = "abc123"

[[kv_namespaces]]
binding = "BAR"
preview_id = "xyz456"
id = "xyz123"
```
Much like environment variables and secrets, the `binding` names are available to your Worker as global variables.

```

2021-07-08 13:20 UTC, deadlypants1973 commented on products/workers/src/content/cli-wrangler/configuration.md
> +Much like environment variables and secrets, the `binding` names are available to your Worker as global variables.
```suggestion
Alternatively, you can define `kv namespaces` like so:

```toml
[[kv_namespaces]]
binding = "FOO"
preview_id = "abc456"
id = "abc123"

[[kv_namespaces]]
binding = "BAR"
preview_id = "xyz456"
id = "xyz123"
```
Much like environment variables and secrets, the `binding` names are available to your Worker as global variables.
```

2021-07-08 13:35 UTC, deadlypants1973 commented on products/workers/src/content/cli-wrangler/configuration.md
> +Alternatively, you can define `kv namespaces` like so:
@lukeed can you double check this?

2021-07-08 14:11 UTC, kodster28 approved these changes
Hey @deadlypants1973, just a few small changes and this is good to go.

2021-07-08 14:11 UTC, kodster28 commented on products/workers/src/content/cli-wrangler/configuration.md
> +* Not inherited keys must be defined for every environment individually.
```suggestion
* Non-inherited keys must be defined for every environment individually.
```

2021-07-08 14:11 UTC, kodster28 commented on products/workers/src/content/platform/environments.md
> +You will likely use environments to deploy Workers to a staging subdomain before your production environment. `wrangler publish` will determine its destination by the top-level configuration in your
```suggestion
You will likely use environments to deploy Workers to a staging subdomain before your production environment. `wrangler publish` will determine its destination by the top-level configuration in your `wrangler.toml` [file](/cli-wrangler/commands#generate). You can create other environments beneath the top-level configuration in the `wrangler.toml` file by adding an [`[env.name]` configuration](https://developers.cloudflare.com/workers/cli-wrangler/configuration#environments) and specifying additional keys and values. For details on what keys are inherited by environments from the top-level configuration, see [`wrangler.toml` configuration](/cli-wrangler/configuration#keys).
```

2021-07-08 14:11 UTC, kodster28 commented on products/workers/src/content/platform/environments.md
> +You will likely use environments to deploy Workers to a staging subdomain before your production environment. `wrangler publish` will determine its destination by the top-level configuration in your
Ideally, want to use the relative URL so they don't appear as external links.

2021-07-08 14:11 UTC, kodster28 commented on products/workers/src/content/platform/environments.md
> +This example will publish to your `*workers.dev` subdomain because `workers_dev` has been set to `true`.
```suggestion
This example will publish to your `*.workers.dev` subdomain because `workers_dev` has been set to `true`.
```

2021-07-08 14:11 UTC, kodster28 commented on products/workers/src/content/platform/environments.md
> +Any defined environment variables (the [`vars`](https://developers.cloudflare.com/workers/cli-wrangler/configuration#vars) key) are exposed as global variables to your Worker.
```suggestion
Any defined environment variables (the [`vars`](/cli-wrangler/configuration#vars) key) are exposed as global variables to your Worker.
```

2021-07-08 14:11 UTC, kodster28 commented on products/workers/src/content/platform/environments.md
> +* KV namespaces are defined via the [`kv_namespaces`](https://developers.cloudflare.com/workers/cli-wrangler/configuration#kv_namespaces) config in your `wrangler.toml` and are always provided as [KV
```suggestion
* KV namespaces are defined via the [`kv_namespaces`](/cli-wrangler/configuration#kv_namespaces) config in your `wrangler.toml` and are always provided as [KV runtime instances](/runtime-apis/kv).
```

2021-07-08 14:11 UTC, kodster28 commented on products/workers/src/content/platform/environments.md
> +* Secrets are defined by running [`wrangler secret put <NAME>`](https://developers.cloudflare.com/workers/cli-wrangler/commands#secret) in your terminal, where `<NAME>` is the name of your binding. Y
```suggestion
* Secrets are defined by running [`wrangler secret put <NAME>`](/cli-wrangler/commands#secret) in your terminal, where `<NAME>` is the name of your binding. You may assign environment-specific secrets by re-running the command `wrangler secret put <NAME> -e` or `wrangler secret put <NAME> --env`. Keep a list of the secrets used in your code in your `wrangler.toml` file, like the example under `[secrets]`:
```

2021-07-08 14:11 UTC, kodster28 commented on products/workers/src/content/platform/environments.md
> +\* __Warning:__ Do not use plaintext environment variables to store sensitive information. Use [`wrangler secret put`](https://developers.cloudflare.com/workers/cli-wrangler/commands#secret) instead.
```suggestion
\* __Warning:__ Do not use plaintext environment variables to store sensitive information. Use [`wrangler secret put`](/cli-wrangler/commands#secret) instead.
```

2021-07-08 14:11 UTC, kodster28 commented on products/workers/src/content/cli-wrangler/configuration.md
> +The `vars` key defines a table of [environment variables](https://developers.cloudflare.com/workers/platform/environments#environment-variables) provided to your Worker script. All values are plainte
```suggestion
The `vars` key defines a table of [environment variables](/platform/environments#environment-variables) provided to your Worker script. All values are plaintext values.
```

2021-07-08 14:11 UTC, kodster28 commented on products/workers/src/content/cli-wrangler/configuration.md
> +  - The name of the global variable your code will reference. It will be provided as a [KV runtime instance](https://developers.cloudflare.com/workers/runtime-apis/kv).
```suggestion
  - The name of the global variable your code will reference. It will be provided as a [KV runtime instance](/runtime-apis/kv).
```

2021-07-08 14:11 UTC, kodster28 commented on products/workers/src/content/platform/environments.md
> +The `wrangler.toml` file below adds two environments, `[env.staging]` and `[env.production]`, to the `wrangler.toml` file. If you are deploying to a custom domain, you must provide a [`route` or `rou
```suggestion
The `wrangler.toml` file below adds two environments, `[env.staging]` and `[env.production]`, to the `wrangler.toml` file. If you are deploying to a custom domain, you must provide a [`route` or `routes` key](/cli-wrangler/configuration#keys) for each environment if you are deploying to a custom domain.
```

2021-07-08 14:11 UTC, kodster28 commented on products/workers/src/content/platform/environments.md
> +* Secrets are defined by running [`wrangler secret put <NAME>`](https://developers.cloudflare.com/workers/cli-wrangler/commands#secret) in your terminal, where `<NAME>` is the name of your binding. Y
```suggestion
* Secrets are defined by running [`wrangler secret put <NAME>`](/cli-wrangler/commands#secret) in your terminal, where `<NAME>` is the name of your binding. You may assign environment-specific secrets by re-running the command `wrangler secret put <NAME> -e` or `wrangler secret put <NAME> --env`. Keep a list of the secrets used in your code in your `wrangler.toml` file, like the example under `[secrets]`:
```

2021-07-08 17:16 UTC, lukeed approved these changes

2021-07-08 17:26 UTC, merged