Add how to deploy Workers via UI for Pages users
cloudflare/cloudflare-docs pull request #1719
Opened 2021-07-02 22:49 UTC by Albertozhao

@signalnerve did a tad heavier reformatting than expected but lmk any changes I should make.

2021-07-02 22:50 UTC, Albertozhao commented
Sorry, let me redo this one.

2021-07-06 12:45 UTC, deadlypants1973 requested changes

2021-07-06 12:45 UTC, deadlypants1973 commented on products/pages/src/content/how-to/add-custom-http-headers.md
> +The easiest way to start deploying your Workers function is typing [workers.new](https://workers.new/) in the browser. You'll sign-in to your account and automatically be directed to the Workers UI.
```suggestion
The easiest way to start deploying your Workers function is by typing [workers.new](https://workers.new/) in the browser. Log into your account to be automatically directed to the Workers dashboard. From the Workers dashboard, write your function or use one of the [examples from the Workers documentation](/workers/examples/). 
```

2021-07-06 12:45 UTC, deadlypants1973 commented on products/pages/src/content/how-to/add-custom-http-headers.md
> +Click "Save and Deploy" when it's ready and set a [route](https://developers.cloudflare.com/workers/platform/routes/) in your domain's zone settings.
```suggestion
Click "Save and Deploy" when your script is ready and set a [route](/workers/platform/routes/) in your domain's zone settings.
```

2021-07-06 12:45 UTC, deadlypants1973 commented on products/pages/src/content/how-to/add-custom-http-headers.md
> +For example, here is a Workers script you can copy/paste into the UI that sets common security headers whenever a request hits your Pages URL.
```suggestion
For example, below is a Workers script you can copy and paste into the Workers dashboard that sets common security headers whenever a request hits your Pages URL. 
```

2021-07-06 12:45 UTC, deadlypants1973 commented on products/pages/src/content/how-to/add-custom-http-headers.md
> +## Deploying a Workers function in the UI
```suggestion
## Deploying a Workers function in the dashboard
```

2021-07-06 16:03 UTC, deadlypants1973 approved these changes

2021-07-06 16:04 UTC, deadlypants1973 commented
Approved but @signalnerve to check the code.

2021-07-06 20:26 UTC, signalnerve commented on products/pages/src/content/how-to/add-custom-http-headers.md
> +For example, below is a Workers script you can copy and paste into the Workers dashboard that sets common security headers whenever a request hits your Pages URL.
IMO link to the example page instead of dropping all the code in here. since we link to `/workers/examples` in a previous paragraph, this could be a paragraph calling out a _specific_ example ("Setting security headers")

2021-07-06 20:26 UTC, signalnerve commented on products/pages/src/content/how-to/add-custom-http-headers.md
> -
make sure we put the `<Aside>` back here, it was removed at line 45

2021-07-07 20:53 UTC, rita3ko requested changes

2021-07-07 20:53 UTC, rita3ko commented on products/pages/src/content/how-to/add-custom-http-headers.md
> +Here are some [examples](https://developers.cloudflare.com/rules/transform/request-header-modification/examples) of Transform Rules you can get started with.
can we actually include some screenshots of how to add the same headers that were added with the worker above?

2021-07-08 01:03 UTC, rita3ko commented on products/pages/src/content/how-to/add-custom-http-headers.md
> +![image](https://user-images.githubusercontent.com/67480168/124844616-6802d980-df5a-11eb-8eb9-e5aaa700f3ed.png)
we should host these images ourselves (i imagine this is from uploading via github editor)

2021-07-08 01:03 UTC, rita3ko commented on products/pages/src/content/how-to/add-custom-http-headers.md
> +You can set or remove HTTP request headers directly in the dashboard's Rules tab using [Transform Rules](https://developers.cloudflare.com/rules/transform/request-header-modification/create-dashboard
could we also add a line about where to find Transform Rules in the UI?

Go to your Cloudflare zone, click on X, etc…

2021-07-08 04:12 UTC, Albertozhao commented on products/pages/src/content/how-to/add-custom-http-headers.md
> +   ![transform-rules-adjust-header-value](./how-to/media/transform-rules-adjust-header-value.png)
I messed up image uploading...will fix in the morning.

2021-07-08 18:42 UTC, signalnerve approved these changes

2021-07-08 19:14 UTC, signalnerve commented
@Albertozhao plz hold off on merging! i just found an issue w/ this we should sync up on, will msg you

2021-07-12 16:06 UTC, greg-mckeon requested changes

2021-07-12 16:06 UTC, greg-mckeon commented on products/workers/src/content/runtime-apis/kv.md
> +Using [Wrangler](/cli-wrangler/commands#kv), you can create a namespace by running this subcommand that will generate a binding (which is referred to as FIRST_KV below) and a namespace ID.
can we move "A binding makes your namespace accessible from within a Worker. In fact, multiple Workers can access the same namespace if they use the same binding." up to line 40?

2021-07-12 16:06 UTC, greg-mckeon commented on products/workers/src/content/runtime-apis/kv.md
> +Here is an example on how to add your binding to a Worker.
"Once your Worker has been bound, you can access the KV namespace from within a Worker.

2021-07-12 18:22 UTC, rita3ko requested changes

2021-07-12 18:22 UTC, rita3ko commented on products/workers/src/content/runtime-apis/kv.md
> +A namespace is a container for key-value pairs in your account.
`container` feels like a bit of a loaded word. maybe "A namespace encapsulates a KV instance that hold key-value pairs"... something like that

2021-07-12 18:22 UTC, rita3ko commented on products/workers/src/content/runtime-apis/kv.md
> +A binding makes your namespace accessible from within a Worker. In fact, multiple Workers can access the same namespace if they use the same binding.
i think the binding is different (since they're different workers), the namespace is the same.

2021-07-12 18:22 UTC, rita3ko commented on products/workers/src/content/runtime-apis/kv.md
> +Using [Wrangler](/cli-wrangler/commands#kv), you can create a namespace by running this subcommand that will generate a binding (which is referred to as FIRST_KV below) and a namespace ID.
Make it more clear (explicit) that the command both: creates a namespace, and generates a binding

2021-07-12 18:22 UTC, rita3ko commented on products/workers/src/content/runtime-apis/kv.md
> +Here is an example on how to add your binding to a Worker.
I don't think the example below adds the binding to the Worker — that's how you invoke the binding in the worker. the binding is created usually in the TOML.

2021-07-12 18:22 UTC, rita3ko commented on products/workers/src/content/runtime-apis/kv.md
> +Here is an example on how to add your binding to a Worker.
(do we have a doc somewhere that shows how to do that that we can link to?)

2021-07-13 15:00 UTC, Albertozhao commented
@rita3ko incorporated your comments but also got immense editorial help from @lukeed. Let me know how you feel about the re-wording!

2021-07-13 15:14 UTC, rita3ko requested changes

2021-07-13 15:14 UTC, rita3ko commented on products/workers/src/content/runtime-apis/kv.md
> +### Creating a KV namespace
Change suggestion: rename section to "Creating a binding" or "Referencing KV from a Worker". This also shouldn't go under "Methods".

I just reread the Background section:
<img width="727" alt="Screen Shot 2021-07-13 at 8 08 47 AM" src="https://user-images.githubusercontent.com/2414910/125476831-97d0b9d5-50eb-46b3-9a61-23d81b2177c4.png">

Based on that, and rereading the rest of the current doc, here's what I suggest (sorry, there's a tiny bit of scope creep): 

- Create a new section called "KV bindings" or "Creating KV bindings" or "Using KV bindings" (up to you which one is best) but make it at the end of the doc (after "Methods", before "See also"). 
- Deep link to that section from the "Background" section
- The section that's currently at the top ("Using KV with Durable Objects"). It actually just describes how to use the binding in a module syntax. It should now become a sub-section of the "KV bindings" section (nested under it).

2021-07-13 15:16 UTC, rita3ko commented
@Albertozhao @lukeed — the new wording is good, but looking at the doc at a higher level, it doesn't really fit in the broader structure of the document. Made a suggestion for how to reconfigure.

2021-07-13 16:43 UTC, koeninger commented on products/workers/src/content/runtime-apis/kv.md
> +### Creating a KV namespace
I'd be concerned about moving the description of module syntax to the end, because all of the examples use a global variable, which isn't going to work in module syntax.  I think it's better to have the note about the difference up front so someone reading top to bottom doesn't reach a method example, try it out, and get confused about why it doesn't work.

2021-07-16 19:44 UTC, greg-mckeon requested changes

2021-07-16 19:44 UTC, greg-mckeon commented on products/workers/src/content/runtime-apis/kv.md
> +To use Workers KV you must create a KV namespace and add a [binding](https://developers.cloudflare.com/workers/runtime-apis/kv#kv-bindings) to your worker. See the [instructions for Wrangler KV comma
nit: capitalize Worker.

2021-07-16 19:44 UTC, greg-mckeon commented on products/workers/src/content/runtime-apis/kv.md
> +To use Workers KV you must create a KV namespace and add a [binding](https://developers.cloudflare.com/workers/runtime-apis/kv#kv-bindings) to your worker. See the [instructions for Wrangler KV comma
second nit: url should be /runtime-apis/kv#kv-bindings

2021-07-16 19:44 UTC, greg-mckeon commented on products/workers/src/content/runtime-apis/kv.md
> +A KV namespace is a key-value database that replicates at Cloudflare's edge. To connect to a KV namespace from within a Worker, you must define a binding that points to the namespace's ID.
nit: "that is replicated to"

2021-07-16 19:44 UTC, greg-mckeon commented on products/workers/src/content/runtime-apis/kv.md
> +A KV namespace is a key-value database that replicates at Cloudflare's edge. To connect to a KV namespace from within a Worker, you must define a binding that points to the namespace's ID.
I would say: "A KV namespace is a key-value database that is replicated to Cloudflare's edge. To connect to a KV namespace from within a Worker, you must define a binding that links a variable in your Worker to the namespace's ID."

We could optionally link "binding" to the binding overview page.

2021-07-16 19:44 UTC, greg-mckeon commented on products/workers/src/content/runtime-apis/kv.md
> +The name of your binding **does not** need to match the KV namespace's name. Instead, the binding should be a valid JavaScript identifier because it will exist as a global variable within your Worker
after this, I'd put an aside describing how this is not the case when using modules.

2021-07-16 19:44 UTC, greg-mckeon commented on products/workers/src/content/runtime-apis/kv.md
> +For example, assume you create a KV namespace called "My Tasks - 2021" that receives a generated namespace ID of "abcd1234". You then associate your Workers script with "My Tasks - 2021" by using the
I would say: 

"For example, assume you create a KV namespace called "My Tasks - 2021" that receives a generated namespace ID of "abcd1234". The binding associates the `TODO` global variable in your script with the KV namespace:"

2021-07-16 19:44 UTC, greg-mckeon commented on products/workers/src/content/runtime-apis/kv.md
> +  // Get the value for the "todo:123" key
nit: todo should be to-do

2021-07-16 19:44 UTC, greg-mckeon commented on products/workers/src/content/runtime-apis/kv.md
> +Now, to deploy this Worker correctly, the `kv_namespaces` portion of your `wrangler.toml` file needs to be either created or modified.
"For this Worker to execute properly, we need to define the binding.  In the `kv_namespaces` portion of your `wrangler.toml` file, add:"

2021-07-16 19:44 UTC, greg-mckeon commented on products/workers/src/content/runtime-apis/kv.md
> +You can create a namespace [using Wrangler](https://developers.cloudflare.com/workers/cli-wrangler/commands#getting-started) or in the [Workers dashboard](https://dash.cloudflare.com/) on the KV page
should this step come first? we've sort of assumed they have a namespace already.

2021-07-16 19:44 UTC, greg-mckeon commented on products/workers/src/content/runtime-apis/kv.md
> +You can create a namespace [using Wrangler](https://developers.cloudflare.com/workers/cli-wrangler/commands#getting-started) or in the [Workers dashboard](https://dash.cloudflare.com/) on the KV page
I would also separate creating a namespace and creating a binding via the UI into two separate sentences.

2021-07-16 19:44 UTC, greg-mckeon commented on products/workers/src/content/runtime-apis/kv.md
> +The docs below assume you're using the original service worker syntax, where binding a KV namespace makes it available as a global variable with the name you chose, e.g. `NAMESPACE`. Durable Objects
nit: docs above

2021-07-16 19:44 UTC, greg-mckeon commented on products/workers/src/content/runtime-apis/kv.md
> +### Referencing KV from Durable Objects
"Referencing KV from Durable Objects / Workers using Modules Syntax

2021-07-16 20:55 UTC, Albertozhao commented on products/workers/src/content/runtime-apis/kv.md
> +You can create a namespace [using Wrangler](https://developers.cloudflare.com/workers/cli-wrangler/commands#getting-started) or in the [Workers dashboard](https://dash.cloudflare.com/) on the KV page
Yeah I see your point. However, the reason why we didn't start with this step first is we wanted to properly define binding and namespace. Some users don't intuitively get the way we label things, especially if we mean: 

binding = variable
namespace = database

Also we think linked the how-to stuff at the end, so a user, now with a full understanding of those terms, can be set up better.

2021-07-16 20:57 UTC, Albertozhao commented on products/workers/src/content/runtime-apis/kv.md
> +  // Get the value for the "todo:123" key
ugh, good catch, thanks

2021-07-16 21:36 UTC, rita3ko commented on products/workers/src/content/runtime-apis/kv.md
> +You can create a namespace [using Wrangler](https://developers.cloudflare.com/workers/cli-wrangler/commands#getting-started) or in the [Workers dashboard](https://dash.cloudflare.com/) on the KV page
It feels like we have a need for a section under Platform for "KV". Once we have that, we should just have a sentence in the beginning that says "Before creating a binding, you must create a namespace" and make "create a namespace" a link. I'm a bit worried about too much of this leaking into the runtime doc part of it.

I think we should address that you need to create it at the top (per Greg's point, doesn't really make sense to bind something that doesn't exist), but I agree about hand holding you through the mental model. 

Proposed next steps: 

- [ ] In line 277, rephrase "For example, assume you create a KV namespace called" to "When you create a namespace (see note below), it will have a name you choose (e.g. "My tasks"), and an assigned ID (e.g. "abc123" <- we should use something here that looks like a real ID so users can validate they're looking at the right thing)
- [ ] Split out line 303 into two sentences, and make it an `<Aside>`
- [ ] Create an issue for creating a platform doc for KV.

2021-07-16 21:38 UTC, rita3ko commented on products/workers/src/content/runtime-apis/kv.md
> +This is not the case with modules, which you can see more in the [next section below](/runtime-apis/kv#referencing-kv-from-durable-objects-and-Workers-using-modules-syntax).
"which you can see more in the" -> just "see next section"

2021-07-19 16:41 UTC, Albertozhao commented on products/workers/src/content/runtime-apis/kv.md
> +You can create a namespace [using Wrangler](https://developers.cloudflare.com/workers/cli-wrangler/commands#getting-started) or in the [Workers dashboard](https://dash.cloudflare.com/) on the KV page
@rita3ko thank you, updated the file with your suggestions.

GitHub issue: https://github.com/cloudflare/cloudflare-docs/issues/1814

2021-07-21 21:51 UTC, rita3ko approved these changes

2021-07-21 22:08 UTC, merged