[ZT] RBI chrome extension
cloudflare/cloudflare-docs pull request #17236
Opened 2024-09-30 20:20 UTC by ranbel

PCX-11917

2024-09-30 20:22 UTC, ranbel commented on src/content/docs/cloudflare-one/policies/browser-isolation/setup/clientless-browser-isolation.mdx
> +To install the browser extension:
What is the setup procedure?

2024-09-30 20:23 UTC, ranbel commented on src/content/docs/cloudflare-one/policies/browser-isolation/setup/clientless-browser-isolation.mdx
> +
Unclear why the browser extension enables phish-resistant MFA.

2024-10-08 02:10 UTC, cf-chase reviewed
Added one comment with a slight change we should make for the time beng. Otherwise, it looks good!

2024-10-08 02:10 UTC, cf-chase commented on src/content/docs/cloudflare-one/policies/browser-isolation/setup/clientless-browser-isolation.mdx
> +
To clarify, it will enable phish-resistant MFA support for the clientless on-ramps. (There are technical reasons why customers would run into issues for clientless but not with WARP/proxy on-ramp.)

Honestly, this portion of the extension has a couple issues so I'm thinking we remove the last sentence "The extension also enables support for phish-resistant MFA in the remote browser" and add it back in a few weeks once we've been able to make sure updates.

2024-10-08 02:12 UTC, cdisher requested changes
Added one small suggestion for a change. Once we remove the one line, the rest LGTM. Thank you Ranbel!

2024-10-08 02:12 UTC, cdisher commented on src/content/docs/cloudflare-one/policies/browser-isolation/setup/clientless-browser-isolation.mdx
> +
To clarify, it will enable phish-resistant MFA support for the clientless on-ramps. (There are technical reasons why customers would run into issues for clientless but not with WARP/proxy on-ramp.)

Honestly, this portion of the extension has a couple issues so I'm thinking we remove the last sentence "The extension also enables support for phish-resistant MFA in the remote browser" and add it back in a few weeks once we've been able to make sure updates.

2024-10-08 15:37 UTC, ranbel commented on src/content/docs/cloudflare-one/policies/browser-isolation/setup/clientless-browser-isolation.mdx
> +The Cloudflare One Chrome extension allows a user to seamlessly access isolated and non-isolated applications without needing to re-authenticate. The user can log in once to their identity provider (
```suggestion
The Cloudflare One Chrome extension allows a user to seamlessly access isolated and non-isolated applications without needing to re-authenticate. The user can log in once to their identity provider (whether through a Clientless Web Isolation link or their local browser) and gain access to all applications behind the SSO login.
```

2024-10-08 15:41 UTC, Oxyjun approved these changes

2024-10-08 15:53 UTC, merged