Make Compat Matrix more comprehensive
cloudflare/cloudflare-docs pull request #17303
Opened 2024-10-03 14:06 UTC by irvinebroque

2024-10-03 15:07 UTC, tanushree-sharma commented on src/content/docs/workers/static-assets/compatibility-matrix.mdx
> +| [Testing](/workers/testing)                                                         | ✅                       | ✅    |
```suggestion
| [Testing tools](/workers/testing)                                                         | ✅                       | ✅    |
```

2024-10-03 15:09 UTC, tanushree-sharma commented
Would be good to add a legend for the table:
✅ Supported
⏳ Coming soon
🟡 Unsupported, workaround available
❌ Unsupported

2024-10-03 15:11 UTC, tanushree-sharma commented
Since scope is now more broach, should we move this up for vis into the get started guides for Workers and Pages

2024-10-03 15:13 UTC, tanushree-sharma commented on src/content/docs/workers/static-assets/compatibility-matrix.mdx
> +| [Customize HTTP headers of static assets](/pages/configuration/headers/)            | 🟡 <sup>2</sup>          | ✅    |
```suggestion
| [Custom HTTP headers for static assets](/pages/configuration/headers/)            | 🟡 <sup>2</sup>          | ✅    |
```

2024-10-03 15:15 UTC, tanushree-sharma commented on src/content/docs/workers/static-assets/compatibility-matrix.mdx
> +| [Durable Objects](/durable-objects/api/)                                            | ✅                       | 🟡 <sup>7</sup>    |
Why is DO here? Would expect this to be under bindings

2024-10-03 15:20 UTC, tanushree-sharma commented
SSL for SaaS + WFP would be good ones to add here. SSL for SaaS not supported for Pages (people need to use pages custom domains for this). WFP in progress for Workers (hoping to do this Q4)

2024-10-03 15:56 UTC, tanushree-sharma commented on src/content/docs/workers/static-assets/compatibility-matrix.mdx
> +<sup>1</sup> For more details on which bindings are supported in remote development, [refer to the docs]((/workers/testing/local-development/#supported-resource-bindings-in-different-environments)
```suggestion
<sup>1</sup> For more details on which bindings are supported in remote development, [refer to the docs](/workers/testing/local-development/#supported-resource-bindings-in-different-environments)
```

2024-10-03 15:59 UTC, tanushree-sharma commented on src/content/docs/workers/static-assets/compatibility-matrix.mdx
> +<sup>1</sup> For more details on which bindings are supported in remote development, [refer to the docs]((/workers/testing/local-development/#supported-resource-bindings-in-different-environments)
Need to add the assets binding on the local dev page. I can do in a follow up PR.

2024-10-04 02:56 UTC, bllchmbrs commented on src/content/docs/workers/static-assets/compatibility-matrix.mdx
> +<sup>1</sup> For more details on which bindings are supported in remote development, [refer to the docs]((/workers/testing/local-development/#supported-resource-bindings-in-different-environments)
We updated our model to better handle this case. Should be updated soon.

Bill, _Hyperlint dev_

2024-10-09 15:54 UTC, irvinebroque commented on src/content/docs/workers/static-assets/compatibility-matrix.mdx
> +| [Durable Objects](/durable-objects/api/)                                            | ✅                       | 🟡 <sup>7</sup>    |
A DO is a singleton Worker, as fundamental a compute primitive to the platform as a Worker. We need to stop treating it just as binding but as first-class compute primitive. Can move back to bindings for now from here but it is apples vs. oranges to other bindings.

@vy-ton re: framing, I think we have habit of bucketing DO with other bindings but feels different

2024-10-09 16:09 UTC, vy-ton commented on src/content/docs/workers/static-assets/compatibility-matrix.mdx
> +| [Durable Objects](/durable-objects/api/)                                            | ✅                       | 🟡 <sup>7</sup>    |
+1 grouping DO under Runtime APIs, DO team has https://github.com/cloudflare/cloudflare-docs/pull/17411#discussion_r1793760018 to create `Runtime APIs` section in DO docs

2024-10-09 16:21 UTC, thomasgauvin commented on src/content/docs/workers/static-assets/compatibility-matrix.mdx
> +You can deply full-stack applications, including front-end static assets and back-end APIs and server-side rendered pages (SSR), to both Cloudflare [Workers](/workers/static-assets/) and [Pages](/pag
```suggestion
You can deploy full-stack applications, including front-end static assets and back-end APIs and server-side rendered pages (SSR), to both Cloudflare [Workers](/workers/static-assets/) and [Pages](/pages/). The compatibility matrix below shows which features are available for each, to help you choose whether to build with Workers or Pages. Unless otherwise stated below, what works in Pages works in Workers, and what works in Workers works in Pages. Think something is missing from this list? [Open a pull request](https://github.com/cloudflare/cloudflare-docs/edit/production/src/content/docs/workers/static-assets/compatibility-matrix.mdx) or [create a GitHub issue](https://github.com/cloudflare/cloudflare-docs/issues/new).
```

2024-10-09 16:22 UTC, irvinebroque commented
> Since scope is now more broad, should we move this up for vis into the get started guides for Workers and Pages?

@tanushree-sharma maybe not in Getting Started section but yes, somewhere discoverable + I think Pages needs to explicitly link to in top-level of docs

2024-10-09 16:30 UTC, dcpena reviewed
Small punctuation edits

2024-10-09 16:30 UTC, dcpena commented on src/content/docs/workers/static-assets/compatibility-matrix.mdx
> +<sup>1</sup> For more details on which bindings are supported in remote development, [refer to the docs](/workers/testing/local-development/#supported-resource-bindings-in-different-environments)
```suggestion
<sup>1</sup> For more details on which bindings are supported in remote development, [refer to the docs](/workers/testing/local-development/#supported-resource-bindings-in-different-environments).
```

2024-10-09 16:30 UTC, dcpena commented on src/content/docs/workers/static-assets/compatibility-matrix.mdx
>  This is a temporary limitation, we are working to remove it.
```suggestion
This is a temporary limitation we are working to remove.
```

2024-10-09 16:30 UTC, dcpena commented on src/content/docs/workers/static-assets/compatibility-matrix.mdx
> +<sup>7</sup> To [use Durable Objects with your Cloudflare Pages project](/pages/functions/bindings/#durable-objects), you must create a separate Worker with a Durable Object, and then declare a bindi
```suggestion
<sup>7</sup> To [use Durable Objects with your Cloudflare Pages project](/pages/functions/bindings/#durable-objects), you must create a separate Worker with a Durable Object and then declare a binding to it in both your Production and Preview environments. Using Durable Objects with Workers is simpler and recommended.
```

2024-10-09 16:30 UTC, dcpena commented on src/content/docs/workers/static-assets/compatibility-matrix.mdx
> +<sup>9</sup> Everything that is possible with Pages Functions, can also be achieved by adding code to your Worker, or using framework-specific plugins for relevant third party tools.
```suggestion
<sup>9</sup> Everything that is possible with Pages Functions can also be achieved by adding code to your Worker or by using framework-specific plugins for relevant third party tools.
```

2024-10-09 16:30 UTC, dcpena commented on src/content/docs/workers/static-assets/compatibility-matrix.mdx
>  This is a temporary limitation, we are working to remove it.
```suggestion
This is a temporary limitation  we are working to remove.
```

2024-10-18 14:37 UTC, anonrig approved these changes

2024-10-18 14:40 UTC, petebacondarwin approved these changes

2024-10-18 16:10 UTC, dcpena approved these changes

2024-10-18 16:17 UTC, merged

2024-10-18 16:19 UTC, GregBrimble requested changes

2024-10-18 16:19 UTC, GregBrimble commented on src/content/docs/workers/static-assets/compatibility-matrix.mdx
> +You can deploy full-stack applications, including front-end static assets and back-end APIs and server-side rendered pages (SSR), to both Cloudflare [Workers](/workers/static-assets/) and [Pages](/pa
```suggestion
You can deploy full-stack applications, including front-end static assets and back-end APIs, as well as server-side rendered pages (SSR), to both Cloudflare [Workers](/workers/static-assets/) and [Pages](/pages/). The compatibility matrix below shows which features are available for each, to help you choose whether to build with Workers or Pages. Unless otherwise stated below, what works in Pages works in Workers, and what works in Workers works in Pages. Think something is missing from this list? [Open a pull request](https://github.com/cloudflare/cloudflare-docs/edit/production/src/content/docs/workers/static-assets/compatibility-matrix.mdx) or [create a GitHub issue](https://github.com/cloudflare/cloudflare-docs/issues/new).
```

2024-10-18 16:19 UTC, GregBrimble commented on src/content/docs/workers/static-assets/compatibility-matrix.mdx
> +<sup>2</sup> Similar to <sup>1</sup>, to customize the HTTP headers that
```suggestion
<sup>2</sup> Similar to <sup>3</sup>, to customize the HTTP headers that
```

2024-10-18 16:19 UTC, GregBrimble commented on src/content/docs/workers/static-assets/compatibility-matrix.mdx
> +<sup>1</sup> For more details on which bindings are supported in remote development, [refer to the docs](/workers/testing/local-development/#supported-resource-bindings-in-different-environments).
```suggestion
<sup>1</sup> Does not currently support Workers with static assets. For more details on which bindings are supported in remote development, [refer to the docs](/workers/testing/local-development/#supported-resource-bindings-in-different-environments).
```

2024-10-18 16:19 UTC, GregBrimble commented on src/content/docs/workers/static-assets/compatibility-matrix.mdx
> +| [Remote Development (`--remote`)](/workers/wrangler/commands/)                      | ✅ <sup>1</sup>          | ❌    |
```suggestion
| [Remote Development (`--remote`)](/workers/wrangler/commands/)                      | 🟡 <sup>1</sup>          | ❌    | 
```

2024-10-18 16:19 UTC, GregBrimble commented on src/content/docs/workers/static-assets/compatibility-matrix.mdx
>  | [Assets](/workers/static-assets/binding/)                                           | ✅                       | ❌    |
```suggestion
| [Assets](/workers/static-assets/binding/)                                           | ✅                       | ✅    |
```

2024-10-18 16:19 UTC, GregBrimble commented on src/content/docs/workers/static-assets/compatibility-matrix.mdx
> +| [Build Watch Paths](/pages/configuration/build-watch-paths/)                        | ❌                       | ✅    |
Just added?