Initial commit
cloudflare/cloudflare-docs pull request #17319
Opened 2024-10-04 14:30 UTC by securitypedant

### Summary

### Screenshots (optional)

### Documentation checklist

- [ ] The [documentation style guide](https://developers.cloudflare.com/style-guide/) has been adhered to.
- [ ] If a larger change - such as adding a new page- an issue has been opened in relation to any incorrect or out of date information that this PR fixes.
- [ ] Files which have changed name or location have been allocated [redirects](https://developers.cloudflare.com/pages/configuration/redirects/#per-file).

2024-10-04 14:32 UTC, securitypedant commented on src/content/docs/reference-architecture/diagrams/bots/bot-management.mdx
> +1. Client request is sent to the closest Cloudflare Data Center via Anycast ensuring low latency.
@crwaters16 do you think Anycast should be lowercase?

2024-10-04 16:02 UTC, patriciasantaana commented on src/content/docs/reference-architecture/diagrams/bots/bot-management.mdx
> +Cloudflare has bot management capabilities to help identify and mitigate automated traffic to protect domains from bad bots. [Bot Fight Mode](/bots/get-started/free/) and [Super Bot Fight Mode](/bots
```suggestion
Cloudflare has bot management capabilities to help identify and mitigate automated traffic to protect domains from bad bots. [Bot Fight Mode](/bots/get-started/free/) and [Super Bot Fight Mode](/bots/get-started/biz-and-ent/) are options available on Free and Pro/Business accounts respectively. They offer a subset of features and capabilities available for Enterprise accounts. This reference architecture diagram focuses on [Enterprise Bot Management](/bots/get-started/bm-subscription/) available for Enterprise customers.
```

2024-10-04 16:09 UTC, patriciasantaana commented on src/content/docs/reference-architecture/diagrams/bots/bot-management.mdx
> +With [Enterprise Bot Management](/bots/get-started/bm-subscription/) customers have the maximum protection and features/capability. A [bot score](/bots/concepts/bot-score/) is exposed for every reque
```suggestion
With [Enterprise Bot Management](/bots/get-started/bm-subscription/) customers have the maximum protection, and features and capabilities. A [bot score](/bots/concepts/bot-score/) is exposed for every request. Scores below 30 are commonly associated with bot traffic. Customers can take action on this score by using [WAF custom rules](/waf/custom-rules/) or [Workers](/workers/runtime-apis/request/#incomingrequestcfproperties). Additionally, customers can view this score along with other bot specifics like bot score source, [bot detection IDs](/bots/concepts/detection-ids/), and [bot detection tags](/bots/concepts/detection-ids/#detection-tags) in the Bots, Security Analytics, and Events dashboards. These fields can also be seen in more detailed logs in Log Explorer or exported to third party SIEMs or Analytics platforms using Log Push.
```

2024-10-04 16:13 UTC, patriciasantaana commented on src/content/docs/reference-architecture/diagrams/bots/bot-management.mdx
> +Cloudflare applies a layered detection approach to Bot Management with several detection engines that cumulatively can impact the bot score given to every request. A bot score is a score from 1 to 99
This paragraph is a bit repetitive, detailing the same information as the previous paragraph.

2024-10-04 16:14 UTC, patriciasantaana commented on src/content/docs/reference-architecture/diagrams/bots/bot-management.mdx
> +- **Bot Score:** A [bot score](/bots/concepts/cloudflare-bot-tags/) is a score from 1 to 99 that indicates how likely that request came from a bot. A score of 1 means Cloudflare is quite certain the
```suggestion
- **Bot Score:** A [bot score](/bots/concepts/cloudflare-bot-tags/) is a score from 1 to 99 that indicates how likely that request came from a bot. A score of 1 means Cloudflare is certain the request was automated.
```

2024-10-04 16:26 UTC, patriciasantaana commented on src/content/docs/reference-architecture/diagrams/bots/bot-management.mdx
> +- **Bot Detection ID:** [Detection IDs](/bots/concepts/cloudflare-bot-tags/) are static rules used to detect predictable bot behavior with no overlap with human traffic. Detection IDs cause a bot to
```suggestion
- **Bot Detection ID:** [Detection IDs](/bots/concepts/detection-ids/) are static rules used to detect predictable bot behavior with no overlap with human traffic. Detection IDs cause a bot to receive a score source of heuristics with a score of 1\.
```

2024-10-04 16:27 UTC, patriciasantaana commented on src/content/docs/reference-architecture/diagrams/bots/bot-management.mdx
> +- **AI Bots:** [If the feature is enabled](/bots/concepts/bot/), Cloudflare will detect and block verified AI bots that respect robots.txt and crawl rate, and do not hide their behavior from your web
```suggestion
- **AI Bots:** [If the feature is enabled](/bots/concepts/bot/#ai-bots), Cloudflare will detect and block verified AI bots that respect `robots.txt` and crawl rate, and do not hide their behavior from your website. The rule has also been expanded to include more signatures of AI bots that do not follow the rules.
```

2024-10-04 16:28 UTC, patriciasantaana commented on src/content/docs/reference-architecture/diagrams/bots/bot-management.mdx
> +- **Heuristics:** Cloudflare conducts a number of heuristic checks to identify automated traffic, and requests are matched against a growing database of malicious fingerprints. The Heuristics engine
```suggestion
- **Heuristics:** Cloudflare conducts a number of heuristic checks to identify automated traffic, and requests are matched against a growing database of malicious fingerprints. The Heuristics engine immediately gives automated requests a score of 1.
```

2024-10-04 16:29 UTC, patriciasantaana commented on src/content/docs/reference-architecture/diagrams/bots/bot-management.mdx
> +- **Machine Learning (ML):** The ML engine accounts for the majority of all detections, human and bot. The ML model leverages Cloudflare's global network, which proxies billions of requests daily, to
```suggestion
- **Machine Learning (ML):** The [ML engine](/bots/concepts/bot-score/#machine-learning) accounts for the majority of all detections, human and bot. The ML model leverages Cloudflare's global network, which proxies billions of requests daily, to identify both automated and human traffic. The ML engine produces scores 2 through 99.
```

2024-10-04 16:30 UTC, patriciasantaana commented on src/content/docs/reference-architecture/diagrams/bots/bot-management.mdx
> +- **Anomaly Detection (AD):** The AD engine is an optional detection engine that uses a form of unsupervised learning. Cloudflare records a baseline of a domain's traffic and uses the baseline to int
```suggestion
- **Anomaly Detection (AD):** The [AD engine](/bots/concepts/bot-score/#anomaly-detection) is an optional detection engine that uses a form of unsupervised learning. Cloudflare records a baseline of a domain's traffic and uses the baseline to intelligently detect outlier requests. Anomaly Detection is user agent-agnostic and can be turned on or off by your account team. Cloudflare does not recommend AD for domains that use [Cloudflare for SaaS](/cloudflare-for-platforms/cloudflare-for-saas/security/certificate-management/) or expect large amounts of API traffic. The AD engine immediately gives automated requests a score of 1.
```

2024-10-04 16:30 UTC, patriciasantaana commented on src/content/docs/reference-architecture/diagrams/bots/bot-management.mdx
> +- [**JavaScript Detections (JSD)**](/bots/reference/javascript-detections/)**:** The JSD engine identifies headless browsers and other malicious fingerprints. This engine performs a lightweight, invi
```suggestion
- **JavaScript Detections (JSD)**: The [JSD engine](/bots/concepts/bot-score/#javascript-detections) identifies headless browsers and other malicious fingerprints. This engine performs a lightweight, invisible JavaScript injection on the client side of any request. The JSD engine either blocks, challenges, or passes requests to other engines. JSD is enabled by default but is completely optional.
```

2024-10-04 16:31 UTC, patriciasantaana commented on src/content/docs/reference-architecture/diagrams/bots/bot-management.mdx
> +- **Bots Dashboard:**
```suggestion
- **Bots dashboard:**
```

2024-10-04 16:31 UTC, patriciasantaana commented on src/content/docs/reference-architecture/diagrams/bots/bot-management.mdx
> +  Customers can easily see bot activity up to 30 days back and filter on bot score and other bot/traffic/request filters. The bot feedback loop allows customers to report back to Cloudflare any false
```suggestion
  Customers can easily see bot activity up to 30 days back and filter on bot score and other bot, traffic, and request filters. The [bot feedback loop](/bots/concepts/feedback-loop/) allows customers to report back to Cloudflare any false positives or false negatives for further investigation.
```

2024-10-04 16:32 UTC, patriciasantaana commented on src/content/docs/reference-architecture/diagrams/bots/bot-management.mdx
> +  Events displays all events the WAF took action on. Events/logs can easily be filtered by bot score and other bot/traffic/request criteria.
```suggestion
  Events displays all events the WAF took action on. Events and logs can easily be filtered by bot score and other bot, traffic, or request criteria.
```

2024-10-04 16:32 UTC, patriciasantaana commented on src/content/docs/reference-architecture/diagrams/bots/bot-management.mdx
> +  Customers can use Log Explorer to pull additional detailed log data. Logs can easily be filtered by bot score and other bot/traffic/request criteria.
```suggestion
  Customers can use Log Explorer to pull additional detailed log data. Logs can easily be filtered by bot score and other bot, traffic, or request criteria.
```

2024-10-04 16:32 UTC, patriciasantaana commented on src/content/docs/reference-architecture/diagrams/bots/bot-management.mdx
> +  Customers can also export logs to a 3rd party SIEM or analytics platform. Bot score, bot score source, bot detection IDs, and bot detection tags can all be exported as part of the logs.
```suggestion
  Customers can also export logs to a third party SIEM or Analytics platform. Bot score, bot score source, bot detection IDs, and bot detection tags can all be exported as part of the logs.
```

2024-10-04 16:33 UTC, patriciasantaana commented on src/content/docs/reference-architecture/diagrams/bots/bot-management.mdx
> +2. Cloudflare applies a layered approach for bot detection; each detection mechanism impacts the bot score assigned by Cloudflare to every request. Every request is assigned a bot score between 1 \-
```suggestion
2. Cloudflare applies a layered approach for bot detection; each detection mechanism impacts the bot score assigned by Cloudflare to every request. Every request is assigned a bot score between 1-99 inclusive.
```

2024-10-04 16:35 UTC, patriciasantaana commented on src/content/docs/reference-architecture/diagrams/bots/bot-management.mdx
> +4. Cloudflare provides analytics and insights into traffic/requests traversing the Cloudflare network. Customers can use the Bots, Security Analytics, Events, and Log Explorer dashboards to understan
```suggestion
4. Cloudflare provides analytics and insights into traffic and requests traversing the Cloudflare network. Customers can use the Bots, Security Analytics, Events, and Log Explorer dashboards to understand the overall traffic and bots activity across their site. Customers can also export logs to third party SIEM and Analytics Platforms.
```

2024-10-04 16:36 UTC, patriciasantaana commented on src/content/docs/reference-architecture/diagrams/bots/bot-management.mdx
> +- [Video: Cloudflare Bot Management and Turnstile with Demo](https://youtu.be/6EnekTohO7I?si=tk8FUB0xtk1PxsJV)
```suggestion
- [Cloudflare Bot Management Product Page](https://www.cloudflare.com/application-services/products/bot-management/)
- [Cloudflare Blog - Bot Management](https://blog.cloudflare.com/tag/bot-management/)
- [Bots documentation](/bots/)
- [Video: Cloudflare Bot Management and Turnstile with Demo](https://youtu.be/6EnekTohO7I?si=tk8FUB0xtk1PxsJV)
```

2024-10-04 16:37 UTC, patriciasantaana requested changes
A few styling updates + content edits

2024-10-05 09:12 UTC, securitypedant commented on src/content/docs/reference-architecture/diagrams/bots/bot-management.mdx
> +Cloudflare applies a layered detection approach to Bot Management with several detection engines that cumulatively can impact the bot score given to every request. A bot score is a score from 1 to 99
Ok, the original author, Humair, has updated this section based on your feedback.

2024-10-05 09:20 UTC, securitypedant commented
> A few styling updates + content edits

Ok, all changes have been reviewed and commited.

The PR still has Claire as a reviewer and she's out till later in the month. Any chance we can approve this before she gets back?

2024-10-05 18:36 UTC, patriciasantaana approved these changes

2024-10-05 18:38 UTC, merged