Updated s3-compatible-endpoints page
cloudflare/cloudflare-docs pull request #1743
Opened 2021-07-08 10:27 UTC by cf-vnkr

Added note that we only support standard 443 port.

2021-08-05 16:34 UTC, crwaters16 requested changes

2021-08-05 16:34 UTC, crwaters16 commented on products/logs/src/content/get-started/enable-destinations/s3-compatible-endpoints/index.md
> +
We use asides for our notes in dev docs - update to:

<Aside type="note">
 
S3-compatible destinations must use the standard HTTPS port 443 to work with Logpush.
 
</Aside>

2021-08-10 14:24 UTC, cf-vnkr commented on products/logs/src/content/get-started/enable-destinations/s3-compatible-endpoints/index.md
> +
Done, thank you.

2022-07-20 17:49 UTC, KimJ15 commented
This PR was opened before the developer doc site was moved to Cloudflare Pages. There are many conflicting branches. I'm going to close it now, but feel free to open a new issue or ask any questions.

2022-07-20 17:49 UTC, closed without merging