[Vectorize] Announcement for the anticipated blocking of legacy index creation
cloudflare/cloudflare-docs pull request #17593
Opened 2024-10-17 10:44 UTC by garvit-gupta

### Summary

 Announcement for the anticipated blocking of legacy index creation.

### Documentation checklist

- [x] The [documentation style guide](https://developers.cloudflare.com/style-guide/) has been adhered to.

2024-10-17 11:09 UTC, netgusto commented on src/content/docs/vectorize/reference/transition-vectorize-legacy.mdx
> +Furthemore, the creation of legacy Vectorize indexes would be blocked by December 2024. Other operations would be unaffected and would remain functional.
I'd replace would by will in there.

2024-10-17 11:17 UTC, sejoker commented on src/content/docs/vectorize/reference/transition-vectorize-legacy.mdx
> +Furthemore, the creation of legacy Vectorize indexes would be blocked by December 2024. Other operations would be unaffected and would remain functional.
```suggestion
Furthemore, the creation of legacy Vectorize indexes will be blocked by December 2024. Other operations would be unaffected and would remain functional.
```

2024-10-17 11:18 UTC, sejoker commented on src/content/partials/vectorize/vectorize-legacy.mdx
> +Please note that the creation of legacy Vectorize indexes would be blocked by December 2024. Other operations would remain functional.
```suggestion
Please note that the creation of legacy Vectorize indexes will be blocked by December 2024. Other operations will remain functional.
```

2024-10-17 11:19 UTC, sejoker requested changes

2024-10-17 11:19 UTC, sejoker commented on src/content/docs/vectorize/reference/transition-vectorize-legacy.mdx
> +Furthemore, the creation of legacy Vectorize indexes will be blocked by December 2024. Other operations would be unaffected and would remain functional.
```suggestion
Furthemore, the creation of legacy Vectorize indexes will be blocked by December 2024. Other operations will be unaffected and will remain functional.
```

2024-10-17 11:20 UTC, sejoker approved these changes

2024-10-17 11:30 UTC, garvit-gupta commented on src/content/docs/vectorize/reference/transition-vectorize-legacy.mdx
> +Furthemore, the creation of legacy Vectorize indexes would be blocked by December 2024. Other operations would be unaffected and would remain functional.
@sejoker fixed this.

2024-10-22 12:18 UTC, Oxyjun commented on src/content/docs/vectorize/reference/transition-vectorize-legacy.mdx
> +Furthemore, the creation of legacy Vectorize indexes will be blocked by December 2024. Other operations will be unaffected and will remain functional.
```suggestion
Furthermore, you will no longer be able to create legacy Vectorize indexes by December 2024. Other operations will be unaffected and will remain functional.
```

2024-10-22 12:19 UTC, Oxyjun commented on src/content/partials/vectorize/vectorize-legacy.mdx
> +Please note that the creation of legacy Vectorize indexes will be blocked by December 2024. Other operations will remain functional.
```suggestion
Please note that by December 2024, you will not be able to create legacy Vectorize indexes. Other operations will remain functional.
```

2024-10-22 12:19 UTC, Oxyjun approved these changes

2024-10-22 13:26 UTC, merged