[Durable Objects] Docs enhancement part 1
cloudflare/cloudflare-docs pull request #17794
Opened 2024-10-25 17:00 UTC by Oxyjun

### Summary

1. Improving the **Overview** page:
    - Added "What is a Durable Object?". Lifted paragraphs from [this blog post](https://blog.cloudflare.com/sqlite-in-durable-objects/#refresher-what-are-durable-objects).
    - Added "Utilize Durable Objects". Lifted one paragraph from the blog post.
    - Added "Get started" button.
2. Added glossary tooltips across the docs.
3. Moved Changelog out of "Platform", and into its own item.
4. Moved up REST API link to sit under "Runtime API".
5. Moved Glossary into "Reference".

The full restructure can be tackled in a separate PR to even out the review burden.

### Screenshots (optional)

### Documentation checklist

- [ ] The [documentation style guide](https://developers.cloudflare.com/style-guide/) has been adhered to.
- [ ] If a larger change - such as adding a new page- an issue has been opened in relation to any incorrect or out of date information that this PR fixes.
- [ ] Files which have changed name or location have been allocated [redirects](https://developers.cloudflare.com/pages/configuration/redirects/#per-file).

2024-10-28 16:18 UTC, vy-ton requested changes

2024-10-28 16:18 UTC, vy-ton commented on src/content/docs/durable-objects/index.mdx
> +<LinkButton href="/durable-objects/get-started/walkthrough/">Get started</LinkButton>
Too much text before user arrives at `Get started` button

2024-10-28 16:18 UTC, vy-ton commented on src/content/docs/durable-objects/index.mdx
> +Durable Objects are intended to be small and numerous. A single application can create billions of Durable Objects distributed across our global network. Cloudflare automatically decides [where a Dur
This is too much detail for the `Overview` page. Should have a 1-2 sentence description. 

Can we remove Overview copy text from this PR? Let's start a draft in a google doc so we land the messaging

2024-10-28 16:45 UTC, Oxyjun commented on src/content/docs/durable-objects/index.mdx
> +Durable Objects are intended to be small and numerous. A single application can create billions of Durable Objects distributed across our global network. Cloudflare automatically decides [where a Dur
Understood! Reverted the wording (but have left the "Get started" button, I think that's a nice addition).

2024-10-31 15:31 UTC, vy-ton approved these changes

2024-10-31 15:55 UTC, Maddy-Cloudflare approved these changes

2024-10-31 15:55 UTC, Maddy-Cloudflare commented on src/content/glossary/durable-objects.yaml
> +    A Durable Object is an individual instance of a Durable Object class. A Durable Object is globally unique (referenced by ID), provides a global point of coordination for all methods/requests sent
There is an opportunity here to link this page: https://developers.cloudflare.com/durable-objects/api/id/

2024-10-31 15:58 UTC, Oxyjun commented on src/content/glossary/durable-objects.yaml
> +    A Durable Object is an individual instance of a Durable Object class. A Durable Object is globally unique (referenced by ID), provides a global point of coordination for all methods/requests sent
Ah thanks for that suggestion! In this particular instance I think I'd prefer to leave it as a short definition without linking out, but I'll keep an eye out to see if there are other sections where I might be able to cross-reference :D

2024-10-31 15:59 UTC, merged