Workflows: NonRetryableErrors Section Improvement
cloudflare/cloudflare-docs pull request #17819
Opened 2024-10-28 15:41 UTC by bruxodasilva

### Summary

Reenforce that for NonRetryableErrors, users need to manage the error or the Workflow will fail

2024-10-28 15:48 UTC, elithrar requested changes

2024-10-28 15:48 UTC, elithrar commented on src/content/docs/workflows/build/sleeping-and-retrying.mdx
> +## Force a Workflow Instance to fail
```suggestion
## Force a Workflow instance to fail
```

2024-10-28 15:48 UTC, elithrar commented on src/content/docs/workflows/build/sleeping-and-retrying.mdx
> +Users can catch this error if they intend to continue the Workflow execution. Otherwise, the Workflow will fail.
```suggestion
Catching this exception within the same step as it was thrown will cause it to be ignored. If the exception propagates outside of the step, the step and the Workflow instance itself will subsequently fail.
```

2024-10-28 16:15 UTC, sidharthachatterjee commented on src/content/docs/workflows/build/sleeping-and-retrying.mdx
> +Users can catch this error if they intend to continue the Workflow execution. Otherwise, the Workflow will fail.
```suggestion
Like other Errors, any uncaught exceptions that propagate to the top level will cause the Workflow to end execution in an Errored state. Catch the `NonRetryableError` to continue Workflow execution. 
```

2024-10-29 14:36 UTC, elithrar reviewed
.

2024-11-07 15:04 UTC, elithrar commented on src/content/docs/workflows/build/sleeping-and-retrying.mdx
> +## Avoid a Workflow instance to fail
```suggestion
## Catch Workflow errors
```

2024-11-07 15:05 UTC, elithrar commented on src/content/docs/workflows/build/sleeping-and-retrying.mdx
> +Any uncaught exceptions that propagate to the top level, or any steps that reach their retry limit, will cause the Workflow to end execution in an Errored state. However, this may not be intended, as
```suggestion
Any uncaught exceptions that propagate to the top level, or any steps that reach their retry limit, will cause the Workflow to end execution in an `Errored` state.

If you want to avoid this, you can catch exceptions emitted by a `step`. This can be useful if you need to trigger clean-up tasks or have conditional logic that triggers additional steps.
```

2024-11-07 15:05 UTC, elithrar commented on src/content/docs/workflows/build/sleeping-and-retrying.mdx
> +To allow the Workflow to continue its execution, surround the intended steps that are allowed to fail with a try/catch.
```suggestion
To allow the Workflow to continue its execution, surround the intended steps that are allowed to fail with a `try-catch` block.
```

2024-11-07 15:06 UTC, elithrar commented on src/content/docs/workflows/build/sleeping-and-retrying.mdx
> +Simple example of a Worflow with a cleanup step:
```suggestion
```

2024-11-07 15:06 UTC, elithrar commented on src/content/docs/workflows/build/sleeping-and-retrying.mdx
> +} catch {
```suggestion
} catch(e as Error) {
```

2024-11-07 15:06 UTC, elithrar commented on src/content/docs/workflows/build/sleeping-and-retrying.mdx
> +    console.log('error was thrown');
```suggestion
    console.log(`Step failed: ${e.message}`);
```

2024-11-07 15:07 UTC, elithrar commented on src/content/docs/workflows/build/sleeping-and-retrying.mdx
> +await step.do('cleanup-task', async() => {
I would put this into the `catch` block?

2024-11-08 13:02 UTC, bruxodasilva commented
@cloudflare/pcx-technical-writing can you please check this and merge?

2024-11-08 13:12 UTC, pedrosousa approved these changes

2024-11-08 13:14 UTC, pedrosousa commented
@bruxodasilva I've approved the PR, but I can't merge it since @elithrar requested changes. 
He must approve or else we'll need a repo admin to merge.

2024-11-14 12:33 UTC, celso approved these changes

2024-11-14 12:57 UTC, elithrar approved these changes

2024-11-14 16:29 UTC, merged