PCX-14416 adding crosslinking between RAD and tutorial on BQ + Workers AI
cloudflare/cloudflare-docs pull request #17823
Opened 2024-10-28 17:16 UTC by alekrumkamp

### Summary

Adds crosslinking between RAD and tutorial on BQ + Workers AI (/reference-architecture/diagrams/ai/bigquery-workers-ai/)  to tutorial (/workers-ai/tutorials/using-bigquery-with-workers-ai/) and viceversa.

2024-10-28 21:10 UTC, daisyfaithauma commented on src/content/docs/workers-ai/tutorials/using-bigquery-with-workers-ai.mdx
> +If, instead of displaying the results of ingesting the data to the AI model in a browser, your workflow requires fetching and store data (for example in [R2](/r2/) or [D1](/d1/)) on regular intervals
```Consider reviewing the Reference Architecture Diagrams on [Ingesting BigQuery Data into Workers AI](/reference-architecture/diagrams/ai/bigquery-workers-ai/).```

2024-10-28 21:10 UTC, daisyfaithauma requested changes
Are you able to make this change?

2024-10-28 21:32 UTC, securitypedant commented on src/content/docs/workers-ai/tutorials/using-bigquery-with-workers-ai.mdx
> +If, instead of displaying the results of ingesting the data to the AI model in a browser, your workflow requires fetching and store data (for example in [R2](/r2/) or [D1](/d1/)) on regular intervals
This will require approval and merge from PCX. I don't have rights to make changes outside of the reference architecture section.

2024-10-28 23:37 UTC, alekrumkamp commented
done, @daisyfaithauma 👍

2024-10-29 14:41 UTC, daisyfaithauma approved these changes

2024-10-29 14:56 UTC, merged