Added docs for cache: no-store
cloudflare/cloudflare-docs pull request #17926
Opened 2024-11-01 17:28 UTC by AdityaAtulTewari

### Summary

Update Documentation for adding `cache: no-store`.

### Documentation checklist

- [ ] The [documentation style guide](https://developers.cloudflare.com/style-guide/) has been adhered to.
- [ ] If a larger change - such as adding a new page- an issue has been opened in relation to any incorrect or out of date information that this PR fixes.
- [ ] Files which have changed name or location have been allocated [redirects](https://developers.cloudflare.com/pages/configuration/redirects/#per-file).

2024-11-02 09:47 UTC, mhart commented on src/content/compatibility-dates/cache-no-store.md
> +const response = await fetch("https://example.com", { cache: 'no-store'});
Suggestion: add an example for `new Request()` too? We support it there too right?

2024-11-07 06:31 UTC, irvinebroque reviewed
@mikenomitch FYI

2024-11-07 06:31 UTC, irvinebroque commented on src/content/compatibility-dates/cache-no-store.md
> +When this flag is enabled, the cache header becomes available within the [`fetch()` API](/workers/runtime-apis/fetch/). The option for `no-store` is enabled.
What this enables is this:

https://developer.mozilla.org/en-US/docs/Web/API/Request/cache

The `cache` property of `Request`.

I see where you're going describing it in terms of headers, but "the header becomes available" not quite right.

We should be precise here and elsewhere:

```suggestion
When you enable the `cache_option_enabled` compatibility flag, you can specify a value for the `cache` property of the `Request` interface. When this compatibility flag is not enabled, or `cache_option_disabled` is set, the Workers runtime will throw an error if you attempt to specify the `cache` property.

For example, when this flag is enabled you can instruct Cloudflare not to cache the response from a subrequest you make from your Worker, using the [`fetch()` API](/workers/runtime-apis/fetch/):

<example using no-store>

...then show how this maps to headers, as you do below on line 16
```

2024-11-07 06:31 UTC, irvinebroque commented on src/content/docs/workers/examples/cache-using-fetch.mdx
> +Currently we only support the `no-store` header for controlling cache.
This is out of context, need to back up here

2024-11-07 06:31 UTC, irvinebroque commented on src/content/docs/workers/examples/cache-using-fetch.mdx
> +fetch(event.request, { cache: 'no-store'});
Why does this use `event.request`? That seems like leftover service worker thing?

2024-11-07 06:31 UTC, irvinebroque commented on src/content/docs/workers/examples/cache-using-fetch.mdx
> +For cross-zone requests this simply forwards the `Pragma: no-cache` and `Cache-Control: no-cache` headers to the origin.
This example content shouldn't be our reference material here.

This kind of content should be here:

https://developers.cloudflare.com/workers/runtime-apis/fetch/

2024-11-07 06:31 UTC, irvinebroque commented on src/content/docs/workers/runtime-apis/request.mdx
> +	* Standard HTTP `cache` header. Only `cache: no-store` is supported.
Can we explain what the behavior here is if you attempt to set a value other than `no-store`?

2024-11-07 23:16 UTC, mikenomitch commented on src/content/compatibility-dates/cache-no-store.md
> +For grey-cloud subrequests this bypasses the Cloudflare's cache.
We sometimes use grey cloud in external docs, but for the most part I think we shouldn't. We know what it means internally, but average new user won't.

2024-11-07 23:17 UTC, mikenomitch commented on src/content/compatibility-dates/cache-no-store.md
> +When this flag is enabled, the cache header becomes available within the [`fetch()` API](/workers/runtime-apis/fetch/). The option for `no-store` is enabled.
+1 to the wording change. Was a bit hard to follow exactly what you can now do originally.

2024-11-07 23:17 UTC, mikenomitch commented on src/content/compatibility-dates/cache-no-store.md
> +For a cross-zone request this simply specifies the headers `Pragma: no-cache` and `Cache-Control: no-cache` to the origin.
style nitpick: I'd replace "simply" with "just" or just drop the word.

2024-11-07 23:18 UTC, mikenomitch commented on src/content/compatibility-dates/cache-no-store.md
> +For a cross-zone request this simply specifies the headers `Pragma: no-cache` and `Cache-Control: no-cache` to the origin.
Also, I think this reads slightly off "specifies headers to the origin" - specifies headers in the request to the origin?

2024-11-07 23:19 UTC, mikenomitch commented on src/content/docs/workers/examples/cache-using-fetch.mdx
> +Currently we only support the `no-store` header for controlling cache.
+1

Maybe you start by explaining how the cache normally works (Brendan's next comment), and then explain the header?

2024-11-07 23:21 UTC, mikenomitch commented on src/content/docs/workers/examples/cache-using-fetch.mdx
> +For grey-cloud requests this bypasses the use of Cloudflare's caches.
Noting the other "grey-cloud" use (see above)

2024-11-11 15:54 UTC, AdityaAtulTewari commented on src/content/compatibility-dates/cache-no-store.md
> +For grey-cloud subrequests this bypasses the Cloudflare's cache.
do we want to do the same with cross-zone?

2024-11-11 16:07 UTC, AdityaAtulTewari commented on src/content/docs/workers/examples/cache-using-fetch.mdx
> +For grey-cloud requests this bypasses the use of Cloudflare's caches.
Same question here about cross-zone.

2024-11-11 23:48 UTC, mhart commented on src/content/compatibility-dates/cache-no-store.md
> +const request = new Response("https://example.com", { cache: 'no-store'});
This should be `Request`, not `Response`

2024-11-12 00:05 UTC, mikenomitch requested changes

2024-11-12 00:05 UTC, mikenomitch commented on src/content/compatibility-dates/cache-no-store.md
> +'RequestInitializerDict is not implemented.`
nit - I think missing a ' after RequestInitializerDict (or added one before it inadvertantly

2024-11-12 00:05 UTC, mikenomitch commented on src/content/compatibility-dates/cache-no-store.md
> +For example, when this flag is enabled you can instruct Cloudflare not to cache the response from a subrequest you make from your Worker, using the [`fetch()` API](/workers/runtime-apis/fetch/):
The "For example" feels a bit odd here because that's more or less the only thing you can do at this point right. Maybe just drop that?

And then add comma after "when this flag is enabled"

Also, I think the comma before "using" can be dropped?

2024-11-12 00:05 UTC, mikenomitch commented on src/content/compatibility-dates/cache-no-store.md
> +Any other value will cause the Workers runtime to throw a `TypeError` with the message `Unsupported cache mode: <the-mode-you-specified>`.
nit - maybe: "Specifying any other value will throw a throw a `TypeError` with the message `Unsupported cache mode: <the-mode-you-specified>`."

2024-11-12 00:05 UTC, mikenomitch commented on src/content/compatibility-dates/cache-no-store.md
> +* For a cross-zone request the headers `Pragma: no-cache` and `Cache-Control: no-cache` are sent to the origin.
I try to make the bullet points read well with the header

If you read it like "When no-store is specified for a cross zone", the "for" sounds kind of weird

So I'd do:

When `no-store` is specified:
* All requests have the headers `Pragma: no-cache` and `Cache-Control: no-cache` set
* Subrequests to origins outside of Cloudflare bypass Cloudflare's cache

2024-11-12 00:05 UTC, mikenomitch commented on src/content/compatibility-dates/cache-no-store.md
> +You can also create a Response object to pass around:
Maybe just: "The cache value can also be set on Request"

"to pass around" isn't doing much here

2024-11-12 00:05 UTC, mikenomitch commented on src/content/compatibility-dates/cache-no-store.md
> +```js
Maybe add a little text about this one specifically, so it's similar to to the one below.

Maybe just: "The 'cache' have can be passed into the options for `fetch`"

2024-11-12 00:05 UTC, mikenomitch commented on src/content/compatibility-dates/cache-no-store.md
> +Examples using `cache: 'no-store'`.
This isn't a sentence, so we shouldn't have a period. Maybe our lowest lever of header would render well? Or just replace the period with a ":"?

2024-11-12 00:05 UTC, mikenomitch commented on src/content/docs/workers/examples/cache-using-fetch.mdx
> +The `cache` mode can be set on fetches.
"can be set in `fetch` options" maybe? - A little more specific

2024-11-12 00:05 UTC, mikenomitch commented on src/content/docs/workers/examples/cache-using-fetch.mdx
> +Currently we only support the `no-store` mode for controlling the cache.
s/we only support/Workers only supports

2024-11-12 00:05 UTC, mikenomitch commented on src/content/docs/workers/examples/cache-using-fetch.mdx
> +When `no-store` is supplied the cache is bypassed both on the way to the origin and on the way back.
What does "on the way back" mean in this case?

2024-11-12 00:05 UTC, mikenomitch commented on src/content/docs/workers/runtime-apis/fetch.mdx
> +			* For requests to origins not hosted by Cloudflare, `no-store` bypasses the use of Cloudflare's caches.
Its a bit unclear reading this if non-Cloudflare get the headers or not. Reading above it sounds like it does.

2024-11-12 03:07 UTC, AdityaAtulTewari commented on src/content/docs/workers/runtime-apis/fetch.mdx
> +			* For requests to origins not hosted by Cloudflare, `no-store` bypasses the use of Cloudflare's caches.
They get the headers.

2024-11-12 03:07 UTC, AdityaAtulTewari commented on src/content/docs/workers/runtime-apis/fetch.mdx
> +			* For requests to origins not hosted by Cloudflare, `no-store` bypasses the use of Cloudflare's caches.
I will fix the wording.

2024-11-12 04:49 UTC, mikenomitch approved these changes
LGTM now - thanks for making the changes

2024-11-12 04:54 UTC, merged