[D1] Creating proper API documentation
cloudflare/cloudflare-docs pull request #17923
Opened 2024-11-01 16:48 UTC by Oxyjun

### Summary

1. Adds a new "Worker API" folder on the sidebar.
2. Adds new API chapters within "Worker API"
3. Reshuffles the the sidebar to accommodate the new API folder.

### Screenshots (optional)

### Documentation checklist

- [ ] The [documentation style guide](https://developers.cloudflare.com/style-guide/) has been adhered to.
- [ ] If a larger change - such as adding a new page- an issue has been opened in relation to any incorrect or out of date information that this PR fixes.
- [ ] Files which have changed name or location have been allocated [redirects](https://developers.cloudflare.com/pages/configuration/redirects/#per-file).

2024-11-07 17:06 UTC, lambrospetrou commented on src/content/docs/d1/worker-api/query.mdx
> +title: D1 query
The whole page refers to statements, not queries, so it should be `D1 Prepared Statement`

2024-11-07 17:07 UTC, lambrospetrou commented on src/content/docs/d1/worker-api/query.mdx
> +You can modify the query results which has been obtained after executing a `.db()` method.
There is not `.db()` method... What are you referring to here?

In this section you should briefly mention how to get a prepared statement, and what it is. You have similar content in the `D1 Database` page, but here you need to explain it since it's the D1 PreparedStatement details page.

2024-11-07 17:08 UTC, lambrospetrou commented on src/content/docs/d1/worker-api/query.mdx
> +Runs the query (or queries) and returns results.
```suggestion
Runs the prepared query (or queries) and returns results.
```

2024-11-07 17:10 UTC, lambrospetrou commented on src/content/docs/d1/worker-api/database.mdx
> +title: D1 database
```suggestion
title: D1 Database
```

2024-11-07 17:11 UTC, lambrospetrou commented on src/content/docs/d1/worker-api/database.mdx
> +Example of a prepared statement:
```suggestion
Example of a prepared statement with dynamically bound value:
```

2024-11-07 17:12 UTC, lambrospetrou commented on src/content/docs/d1/worker-api/database.mdx
> +const stmt = db.prepare("SELECT * FROM users WHERE name = ?1").bind(someVariable);
```suggestion
// Dynamically generate the value to use.
const someVariable = "John Doe";
const stmt = db.prepare("SELECT * FROM users WHERE name = ?1").bind(someVariable);
```

2024-11-07 17:12 UTC, lambrospetrou commented on src/content/docs/d1/worker-api/database.mdx
> +// This is a static statement.
```suggestion
// `stmt` will also be a prepared statement.
```

2024-11-07 17:13 UTC, lambrospetrou commented on src/content/docs/d1/worker-api/database.mdx
> +// This is a prepared statement.
```suggestion
// `stmt` is a prepared statement.
```

2024-11-07 17:13 UTC, lambrospetrou commented on src/content/docs/d1/worker-api/database.mdx
> +  - You can only pass parameters to the last query.
```suggestion
  - You can only bind parameters to the last query.
```

2024-11-07 17:14 UTC, lambrospetrou commented on src/content/docs/d1/worker-api/database.mdx
> +	]);
```suggestion
]);
```

2024-11-07 17:14 UTC, lambrospetrou commented on src/content/docs/d1/worker-api/database.mdx
> + ]
```suggestion
]
```

2024-11-07 17:16 UTC, lambrospetrou commented on src/content/docs/d1/worker-api/query.mdx
> +const { results } = await stmt.run();
The example below should show the full returned value, not just the `.results` field otherwise it's not a good example of what the user should expect. Update the example to show the full object returned.

```suggestion
const runResult = await stmt.run();
```

2024-11-07 17:26 UTC, Oxyjun commented on src/content/docs/d1/worker-api/query.mdx
> +title: D1 query
```suggestion
title: D1 prepared statement
```

2024-11-12 15:51 UTC, vy-ton requested changes

2024-11-12 15:51 UTC, vy-ton commented on src/content/docs/d1/worker-api/prepare-a-statement.mdx
> +title: Prepare a statement
`Prepare a statement` title is misleading; section covers more than that

2024-11-12 15:51 UTC, vy-ton commented on src/content/docs/d1/worker-api/prepare-a-statement.mdx
> +### `db.prepare()`
Should be grouped with prepared statement content.

2024-11-12 15:51 UTC, vy-ton commented on src/content/docs/d1/worker-api/prepare-a-statement.mdx
> +This chapter documents how to prepare a statement and how to execute them.
batch(), exec() are not related to this chapter description.

So options could be :
- A: page with all prepared statement content (both db. and stmt. methods)
- B: Database-level methods vs prepared statements

2024-11-12 15:51 UTC, vy-ton commented on src/content/docs/d1/sql-api/sql-statements.mdx
I would intro this page by explaining that D1 uses SQLites query semantics.

2024-11-12 15:51 UTC, vy-ton commented on src/content/docs/d1/worker-api/return-object.mdx
> +The methods `stmt.run()` and `db.batch()` return a typed `D1Result` object for each query statement. This object contains:
and `db.exec()`. This should be the return object for all statement executions

2024-11-12 15:55 UTC, vy-ton commented
@Oxyjun did an initial review pass focused on docs structure. Let's adjust structure based on the comments I left then I can do a thorough review of individual methods.

I propose a Worker Binding API structure like:
- `Overview`: db. methods, link out to prepared statements for db.prepare
- `Prepared statements`: repeat summary of db.prepare
- `Return object`

2024-11-12 16:35 UTC, Oxyjun commented on src/content/docs/d1/worker-api/prepare-a-statement.mdx
> +title: Prepare a statement
Good point - I've reshuffled the layout

2024-11-14 17:20 UTC, vy-ton commented
![image](https://github.com/user-attachments/assets/f8281a6d-9bb8-46c4-a3e9-4ca1d6faa0bb)

double "API" is busy, not sure if we can change this

2024-11-14 17:22 UTC, vy-ton approved these changes
Thrilled we're finally get D1 API separate docs, left a few suggestions, good to merge after

2024-11-14 17:22 UTC, vy-ton commented on src/content/docs/d1/worker-api/run-a-statement.mdx
> +title: Run a prepared statement
If we keep `db.batch|exec|dump` here, then title should not be `run a prepared statement` just `run a statement`

2024-11-14 17:22 UTC, vy-ton commented on src/content/docs/d1/worker-api/run-a-statement.mdx
> +#### Parameters
Remove here and `return values` if none

2024-11-14 17:22 UTC, vy-ton commented on src/content/docs/d1/worker-api/index.mdx
> +You can execute queries on your D1 database through SQL query statements. To do this, you need to perform the following steps:
```suggestion
You can execute SQL queries on your D1 database from a Worker using the Worker Binding API. To do this, you can perform the following steps:
```

2024-11-14 17:22 UTC, vy-ton commented on src/content/docs/d1/worker-api/index.mdx
> +When using the [query statement methods](#query-statement-methods) `stmt.run()`, `stmt.raw()` and `stmt.first()`, you can provide a type representing each database row. D1's API will [return the resu
`query statement methods` link should go to page with these methods

2024-11-14 17:22 UTC, vy-ton commented on src/content/docs/d1/worker-api/index.mdx
> +D1 Worker Bindings API is fully-typed via the `@cloudflare/workers-types` package, and also supports [generic types](https://www.typescriptlang.org/docs/handbook/2/generics.html#generic-types) as par
A link to use for `worker-types`?

2024-11-14 17:22 UTC, vy-ton commented on src/content/docs/d1/worker-api/index.mdx
> +    // const returnValue = await stmt.run();
extra comment

2024-11-14 17:22 UTC, vy-ton commented on src/content/docs/d1/worker-api/prepare-a-statement.mdx
> +- You can pass multiple queries into a single `.prepare()` statement. Simply delineate each query with a semi-colon.
Let's put the parameter binding bullets above multiple queries

2024-11-14 17:22 UTC, vy-ton commented on src/content/changelogs/d1.yaml
> +  - publish_date: "2024-11-18"
I believe this release went live earlier, we can backdate the publish date

2024-11-15 09:47 UTC, Oxyjun commented on src/content/docs/d1/worker-api/index.mdx
> +You can execute queries on your D1 database through SQL query statements. To do this, you need to perform the following steps:
Applying suggestion manually along with other changes.

2024-11-15 10:46 UTC, Oxyjun commented on src/content/docs/d1/worker-api/run-a-statement.mdx
> +#### Parameters
I've specified "None." explicitly, rather than leaving blank. The blank bullets were placeholders.

2024-11-15 10:52 UTC, Oxyjun commented on src/content/changelogs/d1.yaml
> +  - publish_date: "2024-11-18"
Confirmed that 2024.11.0 release went out on 2024-11-01, have edited.

2024-11-15 11:33 UTC, Oxyjun commented
> ![image](https://private-user-images.githubusercontent.com/13694532/386300424-f8281a6d-9bb8-46c4-a3e9-4ca1d6faa0bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2NjM1MDgsIm5iZiI6MTczMTY2MzIwOCwicGF0aCI6Ii8xMzY5NDUzMi8zODYzMDA0MjQtZjgyODFhNmQtOWJiOC00NmM0LWEzZTktNGNhMWQ2ZmFhMGJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE1VDA5MzMyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhNWRmZTgyM2UyZTA1ZTMzN2UyZDc3ODAyODI3N2Q2OGYyM2IzYmEzYWU2OTgxYzNhZGY1ODc2NDgyNTZiOWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.VbSQ3HUEdd8vxvGvwOR7Kbpl7ZwJuc-S0fE0ZOtpfQ8)
> 
> double "API" is busy, not sure if we can change this

I'll look into it - it might be a case where we can't change just this single one.

2024-11-15 14:37 UTC, marciocloudflare approved these changes

2024-11-15 14:37 UTC, marciocloudflare commented on src/content/docs/d1/get-started.mdx
> +- Learn how to use the [D1 Worker Binding API](/d1/worker-api/) within your Worker, and test them from the [API playground](/d1/worker-api/#api-playground).
```suggestion
- Learn how to use the [D1 Worker Binding API](/d1/worker-api/) within your Worker, and test it from the [API playground](/d1/worker-api/#api-playground).
```

2024-11-15 14:37 UTC, marciocloudflare commented on src/content/docs/d1/get-started.mdx
> +- Learn how to use the [D1 Worker Binding API](/d1/worker-api/) within your Worker, and test them from the [API playground](/d1/worker-api/#api-playground).
If you're referring to API, it's singular right?

2024-11-15 14:37 UTC, marciocloudflare commented on src/content/docs/d1/sql-api/sql-statements.mdx
> +## Supported SQLite Extensions
```suggestion
## Supported SQLite extensions
```

2024-11-15 14:37 UTC, marciocloudflare commented on src/content/docs/d1/worker-api/index.mdx
> +## Typescript support
```suggestion
## TypeScript support
```

2024-11-15 14:37 UTC, marciocloudflare commented on src/content/docs/d1/worker-api/index.mdx
> +D1 Worker Bindings API is fully-typed via the [`@cloudflare/workers-types`](/workers/languages/typescript/#typescript) package, and also supports [generic types](https://www.typescriptlang.org/docs/h
Why is "type parameter" italicized? If it's a command or parameter, it should be monospaced.

2024-11-15 14:37 UTC, marciocloudflare commented on src/content/docs/d1/worker-api/index.mdx
> +Replace the contents of your `index.js` file with the below to view the effect of each API.
```suggestion
Replace the contents of your `index.js` file with the code below to view the effect of each API.
```

2024-11-15 14:37 UTC, marciocloudflare commented on src/content/docs/d1/worker-api/prepare-a-statement.mdx
> +	| `?`    | Anonymous | A question mark that is not followed by a number creates a parameter with a number one greater than the largest parameter number already assigned. If this means the parameter
```suggestion
	| `?`    | Anonymous | A question mark that is not followed by a number creates a parameter with a number one greater than the largest parameter number already assigned. If this means the parameter number is greater than `SQLITE_MAX_VARIABLE_NUMBER`, it is an error. This parameter format is provided for compatibility with other database engines. But because it is easy to miscount the question marks, the use of this parameter format is discouraged. Programmers are encouraged to use one of the symbolic formats below or the `?NNN` format above instead. |
```

2024-11-15 14:37 UTC, marciocloudflare commented on src/content/docs/d1/worker-api/run-a-statement.mdx
> +- `results` is empty for write operations such as UPDATE, DELETE, or INSERT.
```suggestion
- `results` is empty for write operations such as `UPDATE`, `DELETE`, or `INSERT`.
```

2024-11-15 14:37 UTC, marciocloudflare commented on src/content/docs/d1/worker-api/run-a-statement.mdx
> +- `results` is empty for write operations such as UPDATE, DELETE, or INSERT.
I'm treating these as other commands, such as `PUT` or `GET`, which are monospaced

2024-11-15 14:37 UTC, marciocloudflare commented on src/content/docs/d1/worker-api/run-a-statement.mdx
> +{/* ### `stmt.all()`
Any reason why this was commented out up until line 270? I'm guessing it was a mistake?

2024-11-15 14:37 UTC, marciocloudflare commented on src/content/docs/d1/worker-api/run-a-statement.mdx
> +{/* ### `stmt.all()`
```suggestion
### `stmt.all()`
```

2024-11-15 14:37 UTC, marciocloudflare commented on src/content/docs/d1/worker-api/run-a-statement.mdx
> +- When using TypeScript, you can pass a [type parameter](/d1/build-with-d1/d1-client-api/#typescript-support) to `all()` to return a typed result object. */}
```suggestion
- When using TypeScript, you can pass a [type parameter](/d1/build-with-d1/d1-client-api/#typescript-support) to `all()` to return a typed result object.
```

2024-11-15 14:52 UTC, Oxyjun commented on src/content/docs/d1/get-started.mdx
> +- Learn how to use the [D1 Worker Binding API](/d1/worker-api/) within your Worker, and test them from the [API playground](/d1/worker-api/#api-playground).
Nice catch - I actually want it both to be plural, will fix.

2024-11-15 14:55 UTC, Oxyjun commented on src/content/docs/d1/worker-api/run-a-statement.mdx
> +{/* ### `stmt.all()`
Hmm, it's basically all correct content that we didn't want to draw attention to. I'll just delete the comment block.

2024-11-15 15:29 UTC, joshthoward requested changes

2024-11-15 15:29 UTC, joshthoward commented on src/content/docs/d1/worker-api/index.mdx
> +title: D1 Worker Binding API
Nit: I would name this "Worker Binding API". It's already long and D1 is redundant.

2024-11-15 15:29 UTC, joshthoward commented on src/content/docs/d1/worker-api/index.mdx
> +When using the [query statement methods](/d1/worker-api/run-a-statement) `stmt.run()`, `stmt.raw()` and `stmt.first()`, you can provide a type representing each database row. D1's API will [return th
We should at a minimum document the full scope of actions that you can take on a D1Database binding:
```
declare abstract class D1Database {
  prepare(query: string): D1PreparedStatement;
  dump(): Promise<ArrayBuffer>;
  batch<T = unknown>(statements: D1PreparedStatement[]): Promise<D1Result<T>[]>;
  exec(query: string): Promise<D1ExecResult>;
}
```
I think that there is an artificial emphasis on prepared statements because the other methods are omitted.

2024-11-15 15:29 UTC, joshthoward commented on src/content/docs/d1/worker-api/return-object.mdx
> +title: Return objects
The title of this doc is confusing because it doesn't map to a type. We should be specific that this is a return type of either exec or a prepared statement. I would split each interface into it's own page personally so that the docs have a consistent structure, but that is more of a nit.
```
declare interface D1Result<T = unknown> {
  results: T[];
  success: true;
  meta: any;
  error?: never;
}
declare interface D1ExecResult {
  count: number;
  duration: number;
}
```

2024-11-15 15:29 UTC, joshthoward commented on src/content/docs/d1/worker-api/prepare-a-statement.mdx
> +import { Type, MetaInfo, Details } from "~/components";
To follow a consistent structure, `prepare` should be documented on the binding rather than in this document. We need a page outlining the usage of prepared statements, e.g. 
```
declare abstract class D1PreparedStatement {
  bind(...values: unknown[]): D1PreparedStatement;
  first<T = unknown>(colName: string): Promise<T | null>;
  first<T = Record<string, unknown>>(): Promise<T | null>;
  run<T = Record<string, unknown>>(): Promise<D1Result<T>>;
  all<T = Record<string, unknown>>(): Promise<D1Result<T>>;
  raw<T = unknown[]>(): Promise<T[]>;
}
```

2024-11-19 10:00 UTC, Oxyjun commented on src/content/docs/d1/worker-api/prepare-a-statement.mdx
> +import { Type, MetaInfo, Details } from "~/components";
I've included `.prepare()` into the D1 bindings chapter (alongside other methods supported by `D1Database`).

The page outlining the usage of prepared statement would correspond to the "Prepared statement methods" chapter (which was previously called "Run a statement").

2024-11-19 10:01 UTC, Oxyjun commented on src/content/docs/d1/worker-api/return-object.mdx
> +title: Return objects
I've left it as-is for now, I'm not sure if splitting it individually would be more useful than having a place where I can explain that some methods return a typed return object. We can hyperlink to the correct object header from other chapters?

2024-11-19 10:02 UTC, Oxyjun commented on src/content/docs/d1/worker-api/index.mdx
> +When using the [query statement methods](/d1/worker-api/run-a-statement) `stmt.run()`, `stmt.raw()` and `stmt.first()`, you can provide a type representing each database row. D1's API will [return th
I've renamed "Prepare a statement" to "D1 binding", and have tried to capture this information. The four methods supported by `D1Database` has been listed together, rather than "db.prepare()" being taken out separately.

2024-11-19 15:54 UTC, joshthoward approved these changes
Approved pending my comments. This is some substantial work. Awesome!

2024-11-19 15:54 UTC, joshthoward commented on src/content/docs/d1/worker-api/index.mdx
> +title: Worker Binding API
Nit: The screenshot you have shows "Worker Bindings API" rather than "Worker Binding API". I prefer the latter. If the screenshot is out of date, then disregard.

2024-11-19 15:54 UTC, joshthoward commented on src/content/docs/d1/worker-api/d1-binding.mdx
> +title: D1 binding
Nit: The name in the code is "D1 Database". I would be consistent here in the hope that a user searching that term would be brought here first.

2024-11-19 15:54 UTC, joshthoward commented on src/content/docs/d1/worker-api/d1-binding.mdx
> +### `db.prepare()`
Nit: We know that this is a method on D1 Database, so this can just be `prepare`. Same goes for all methods and properties.

2024-11-19 15:54 UTC, joshthoward commented on src/content/docs/d1/worker-api/d1-binding.mdx
> +- <code>sqlQuery</code>: <Type text="String"/> <MetaInfo text="Required"/>
Nit: Name in type definitions is `query`.

2024-11-19 15:54 UTC, joshthoward commented on src/content/docs/d1/worker-api/d1-binding.mdx
> +  - An array of `db.prepare()` statements.
We should link to the type definition of prepared statements as well now that this is documented. We can also link our users back up to the `prepare` method.

2024-11-19 15:54 UTC, joshthoward commented on src/content/docs/d1/worker-api/d1-binding.mdx
> +- <code>queryString</code>: <Type text="String"/> <MetaInfo text="Required"/>
Nit: To be consistent with the type definitions, just use query. We know it's a string, so we should avoid types in variable and parameter names.

2024-11-19 15:54 UTC, joshthoward commented on src/content/docs/d1/worker-api/prepared-statements.mdx
> +### `stmt.run()`
Nit: Again, just `run`.

2024-11-19 15:54 UTC, joshthoward commented on src/content/docs/d1/worker-api/prepared-statements.mdx
> +#### Guidance
Just putting this here, but it would apply to every "Guidance" section and we should be consistent whatever we choose. I put "Guidance" under the level 3 `###` section header before the parameters and return values. I'm fine with either, but I thought an initial example would be helpful for context.

2024-11-19 15:54 UTC, joshthoward commented on src/content/docs/d1/worker-api/prepared-statements.mdx
> +const returnValue = await stmt.raw(); // columnName not specified
`stmt.raw()` doesn't take a column name. 
```
declare abstract class D1PreparedStatement {
  ...
  raw<T = unknown[]>(): Promise<T[]>;
}
```

2024-11-19 15:54 UTC, joshthoward commented on src/content/docs/d1/worker-api/prepared-statements.mdx
> +const returnValue = await stmt.raw(); // columnName not specified
If this works LMK and we should dig into why this is.

2024-11-19 15:54 UTC, joshthoward commented on src/content/docs/d1/worker-api/prepared-statements.mdx
> +- <code>firstRow</code>: <Type text="Object"/>
I would document this an an optional return value of object, note that it will be null in the event that there are no rows to return, and also comment that it will be filtered to a specific attribute of the full object if `columnName` is specified.

2024-11-19 15:54 UTC, joshthoward commented on src/content/docs/d1/worker-api/return-object.mdx
> +The method `db.exec()` returns a typed `D1ExecResult` object for each query statement. This object contains:
I would generally use `D1Database::exec` rather than `db.exec()` because that doesn't require the user to hold the context of what you are naming variables in their head. This applies all over the docs.

2024-11-19 16:26 UTC, Oxyjun commented on src/content/docs/d1/worker-api/return-object.mdx
> +The method `db.exec()` returns a typed `D1ExecResult` object for each query statement. This object contains:
Applied for all instances where I've referenced `db.something` outside code examples.

2024-11-19 16:49 UTC, Oxyjun commented on src/content/docs/d1/worker-api/d1-binding.mdx
> +  - An array of `db.prepare()` statements.
Using `D1PreparedStatement` as the type, and replacing `stmt` when it's used outside code.

2024-11-19 16:49 UTC, Oxyjun commented on src/content/docs/d1/worker-api/prepared-statements.mdx
> +#### Guidance
As discussed offline, we'll keep the structure as-is for now. Can review feedback from users and iterate 😄

2024-11-19 17:16 UTC, merged