[Workers] Add tutorial: Live cursors & RPC with Next.js and Durable Objects
cloudflare/cloudflare-docs pull request #18008
Opened 2024-11-06 01:13 UTC by exectx

### Summary

Hi, here's the tutorial for the Cloudflare Developer Spotlight program. It's covers using Next.js Workers with Durable Objects and Workers RPC to visualize connected users cursors via WebSockets. I've also shortened the original title a bit

### Documentation checklist
- [x] The [documentation style guide](https://developers.cloudflare.com/style-guide/) has been adhered to.

2024-11-06 20:42 UTC, bllchmbrs commented on src/content/docs/workers/tutorials/live-cursors-with-nextjs-rpc-do/index.mdx
> +	```json title="package.json" ins={14-17}
Hyperlint dev here, just to make sure I understand, this indentation is significant, right? It's a part of the step by step workflow and therefore indented?

2024-11-06 21:31 UTC, exectx commented on src/content/docs/workers/tutorials/live-cursors-with-nextjs-rpc-do/index.mdx
> +	```json title="package.json" ins={14-17}
You’re right, it actually fails to build if the indentation is removed. There’s something about MDX here that might be causing it. I tried using spaces, but it looks like tabs are required

2024-11-07 11:54 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/live-cursors-with-nextjs-rpc-do/index.mdx
> +## Create a Next.js Workers Project
```suggestion
## 1. Create a Next.js Workers Project
```

2024-11-07 11:54 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/live-cursors-with-nextjs-rpc-do/index.mdx
> +## Create a Durable Object Worker
```suggestion
## 2. Create a Durable Object Worker
```

2024-11-07 11:54 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/live-cursors-with-nextjs-rpc-do/index.mdx
> +## Setup Workers
```suggestion
```

2024-11-07 11:54 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/live-cursors-with-nextjs-rpc-do/index.mdx
> +1. Initialize Durable Object class:
```suggestion
2. Initialize the Durable Object class:
```

2024-11-07 11:54 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/live-cursors-with-nextjs-rpc-do/index.mdx
> +1. Update the Durable Object to manage WebSockets:
```suggestion
3. Update the Durable Object to manage WebSockets:
```

2024-11-07 11:54 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/live-cursors-with-nextjs-rpc-do/index.mdx
> +1. Initialize Durable Object class:
It would also be worth specifying the file being edited here.

2024-11-07 11:54 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/live-cursors-with-nextjs-rpc-do/index.mdx
> +### Worker project
```suggestion
## 2. Build Durable Object Worker functionality
```

2024-11-07 11:54 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/live-cursors-with-nextjs-rpc-do/index.mdx
> +### Next.js project
```suggestion
## 3. Build Next.js Worker functionality
```

2024-11-07 11:54 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/live-cursors-with-nextjs-rpc-do/index.mdx
> +## Deploy the project
```suggestion
## 4. Deploy the project
```

2024-11-07 11:54 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/live-cursors-with-nextjs-rpc-do/index.mdx
> +1. Extend the `WorkerEntrypoint` class for RPC:
```suggestion
4. Extend the `WorkerEntrypoint` class for RPC:
```

2024-11-07 11:54 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/live-cursors-with-nextjs-rpc-do/index.mdx
> +1. Run the Worker locally:
```suggestion
5. Run the Worker locally:
```

2024-11-07 11:54 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/live-cursors-with-nextjs-rpc-do/index.mdx
> +1. Add the Worker host as a Next.js public environment variable:
```suggestion
6. Add the Worker host as a Next.js public environment variable:
```

2024-11-07 11:54 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/live-cursors-with-nextjs-rpc-do/index.mdx
> +1. Create server actions that make use of RPC methods:
```suggestion
2. Create server actions that make use of RPC methods:
```

2024-11-07 11:54 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/live-cursors-with-nextjs-rpc-do/index.mdx
> +1. Create a client component to manage WebSocket and mouse movement events:
```suggestion
3. Create a client component to manage WebSocket and mouse movement events:
```

2024-11-07 11:54 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/live-cursors-with-nextjs-rpc-do/index.mdx
> +1. Run Next.js locally:
```suggestion
4. Run Next.js locally:
```

2024-11-07 11:54 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/live-cursors-with-nextjs-rpc-do/index.mdx
> +1. Change into your root directory and deploy your Next.js app:
```suggestion
2. Change into your root directory and deploy your Next.js app:
```

2024-11-07 11:54 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/live-cursors-with-nextjs-rpc-do/index.mdx
> +	Install [nanoid](https://www.npmjs.com/package/nanoid):
```suggestion
3. Install [nanoid](https://www.npmjs.com/package/nanoid) so that string IDs can be generated for clients:
```

2024-11-07 11:54 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/live-cursors-with-nextjs-rpc-do/index.mdx
> +3. Define workspaces for each Worker:
```suggestion
4. Define workspaces for each Worker:
```

2024-11-07 11:54 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/live-cursors-with-nextjs-rpc-do/index.mdx
> +	Install [nanoid](https://www.npmjs.com/package/nanoid):
If the added description on how nanoid is used isn't accurate feel free to change the copy.

2024-11-07 11:54 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/live-cursors-with-nextjs-rpc-do/index.mdx
> +	The Service binding `RPC_SERVICE` is used instead of invoking Durable Object RPC methods because of the limitation mentioned in the note above.
I'd suggest adding some copy to describe how nanoid is used in the code block as well.

2024-11-07 11:54 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/live-cursors-with-nextjs-rpc-do/index.mdx
> +title: Live cursors & RPC with Next.js and Durable Objects
```suggestion
title:  Display live cursors with RPC, Next.js and Durable Objects
```

2024-11-07 11:54 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/live-cursors-with-nextjs-rpc-do/index.mdx
> +title: Live cursors & RPC with Next.js and Durable Objects
I suggest making the title a present tense action to match our other tutorials. Maybe something like my suggested example, but feel free to change it.

2024-11-18 02:54 UTC, exectx commented on src/content/docs/workers/tutorials/live-cursors-with-nextjs-rpc-do/index.mdx
> +			"deploy": "cloudflare && wrangler deploy",
The command `cloudflare` comes from the open nextjs package, I can't change it

2024-11-18 02:59 UTC, exectx commented on src/content/docs/workers/tutorials/live-cursors-with-nextjs-rpc-do/index.mdx
> +			"worker"
In this case `"worker"` is the name of a directory

2024-11-18 03:07 UTC, exectx commented on src/content/docs/workers/tutorials/live-cursors-with-nextjs-rpc-do/index.mdx
> +	import { DurableObject } from 'cloudflare:workers';
The indentation is necessary to prevent MDX from crashing and is part of the step-by-step workflow.
`'cloudflare:workers'` is a Cloudflare module, it is case-sensitive and cannot be changed.

2024-11-25 11:30 UTC, ToriLindsay approved these changes
Fixing typos and grammar

2024-11-25 11:30 UTC, ToriLindsay commented on src/content/docs/workers/tutorials/live-cursors-with-nextjs-rpc-do/index.mdx
> +In this tutorial, you will learn how to build a real-time [Next.js](https://nextjs.org/) app that displays the live cursor location of each connected user using [Durable Objects](/durable-objects/),
```suggestion
In this tutorial, you will learn how to build a real-time [Next.js](https://nextjs.org/) app that displays the live cursor location of each connected user using [Durable Objects](/durable-objects/), the Workers' built-in [RPC (Remote Procedure Call)](/workers/runtime-apis/rpc/) system, and the [OpenNext](https://opennext.js.org/cloudflare) Cloudflare adapter.
```
For clarity

2024-11-25 11:30 UTC, ToriLindsay commented on src/content/docs/workers/tutorials/live-cursors-with-nextjs-rpc-do/index.mdx
> +This Worker will manage the Durable Object and also have internal API's
```suggestion
This Worker will manage the Durable Object and also have internal APIs
```
Grammar fix

2024-11-25 11:30 UTC, ToriLindsay commented on src/content/docs/workers/tutorials/live-cursors-with-nextjs-rpc-do/index.mdx
> +	- The main `fetch` handler routes requests with a `/ws` URL to the `CursorSessions` Durable Object where a WebSocket connection is stablished.
```suggestion
	- The main `fetch` handler routes requests with a `/ws` URL to the `CursorSessions` Durable Object where a WebSocket connection is established.
```
Typo

2024-11-25 11:30 UTC, ToriLindsay commented on src/content/docs/workers/tutorials/live-cursors-with-nextjs-rpc-do/index.mdx
> +		- When a new WebSocket connection is established, the Durable Object broadcasts a `join` message to all connected clients; similaryly, a `quit` message is broadcasted when a client disconnects.
```suggestion
		- When a new WebSocket connection is established, the Durable Object broadcasts a `join` message to all connected clients; similarly, a `quit` message is broadcast when a client disconnects.
```
Typo / Grammar

2024-11-26 10:41 UTC, harshil1712 requested changes
Hey @exectx, this is a great tutorial! I have left a few comments. Will it be possible to simplify the Cursor component? Not a huge issue, but if it can be simplified, it will help the reader follow more easily. Rest looks good! I am excited to see this go live

2024-11-26 10:41 UTC, harshil1712 commented on src/content/docs/workers/tutorials/live-cursors-with-nextjs-rpc-do/index.mdx
> +"preview": "Cloudflare && wrangler dev",
Shouldn't it be `cloudflare` and not `Cloudflare`?

2024-11-26 10:41 UTC, harshil1712 commented on src/content/docs/workers/tutorials/live-cursors-with-nextjs-rpc-do/index.mdx
> +		pkg="cloudflare@latest next-rpc"
We should move `next-rpc` to the `args` parameter

2024-11-26 10:41 UTC, harshil1712 commented on src/content/docs/workers/tutorials/live-cursors-with-nextjs-rpc-do/index.mdx
> +			lang: "JavaScript / TypeScript",
Since we are using TypeScript, let's specify that here. This should be updated to `lang: "TypeScript"`

2024-11-26 10:41 UTC, harshil1712 commented on src/content/docs/workers/tutorials/live-cursors-with-nextjs-rpc-do/index.mdx
> +2. Initialize the Durable Object class in your `worker/src/index.ts` file:
We should add a few lines here explaining the intention of the code below

2024-11-26 10:41 UTC, harshil1712 commented on src/content/docs/workers/tutorials/live-cursors-with-nextjs-rpc-do/index.mdx
> +
We should modify the sentences here. It sounds like we have already implemented this in the code. Either move it after the code block, or reword it to let the user know this is what the below code block implements

2024-11-26 10:41 UTC, harshil1712 commented on src/content/docs/workers/tutorials/live-cursors-with-nextjs-rpc-do/index.mdx
> +			this.sessions.forEach((session, ws) => {
Since you are using the WebSocket Hibernation API, we should use the [`getWebSockets` method](https://developers.cloudflare.com/durable-objects/api/state/#getwebsockets)

2024-11-26 10:41 UTC, harshil1712 commented on src/content/docs/workers/tutorials/live-cursors-with-nextjs-rpc-do/index.mdx
> +5. Run the Worker locally:
- Should this be run from the worker directory or the root (next.js) directory?
- What should be expected here? After starting the development server, should I go to localhost:8787?

2024-11-26 10:41 UTC, harshil1712 commented on src/content/docs/workers/tutorials/live-cursors-with-nextjs-rpc-do/index.mdx
> +1. In your `wrangler.toml` file, declare the external Durable Object binding and the Service binding to `SessionsRPC`:
Should it be the `next-rpc/wrangler.toml` file or the worker's?

2024-11-26 10:41 UTC, harshil1712 commented on src/content/docs/workers/tutorials/live-cursors-with-nextjs-rpc-do/index.mdx
> +		| { type: "get-cursors-response"; sessions: Session[] };
`Session` is never declared. VS Code shows an error whenever the `Session` type is being referred

2024-11-26 10:41 UTC, harshil1712 commented on src/content/docs/workers/tutorials/live-cursors-with-nextjs-rpc-do/index.mdx
> +	- It sends the user's cursor coordinates to the WebSocket server, which broadcasts them to all active WebSocket clients.
While the overview is good, a detailed explanation would be really helpful here.

2024-11-26 10:41 UTC, harshil1712 commented on src/content/docs/workers/tutorials/live-cursors-with-nextjs-rpc-do/index.mdx
> +	<PackageManagers type="run" pkg="dev" frame="none" />
I get an error in the console. I build the worker app and started the Next.js server. Do I need to run the worker as well?

We should encourage the user to open the app in the browser and test it out

2024-11-27 17:36 UTC, exectx commented on src/content/docs/workers/tutorials/live-cursors-with-nextjs-rpc-do/index.mdx
> +5. Run the Worker locally:
it doesn't really matter where, the resulting address will be used in the next command. I make sure the readers leave the worker running for the local setup to work correctly, for instance the local websocket server

2024-11-27 17:36 UTC, exectx commented on src/content/docs/workers/tutorials/live-cursors-with-nextjs-rpc-do/index.mdx
> +1. In your `wrangler.toml` file, declare the external Durable Object binding and the Service binding to `SessionsRPC`:
Here I'm updating the `next-rpc/wrangler.toml`, i'll be more explicit

2024-11-27 17:38 UTC, exectx commented on src/content/docs/workers/tutorials/live-cursors-with-nextjs-rpc-do/index.mdx
> +	<PackageManagers type="run" pkg="dev" frame="none" />
Did the build fail? I got eslint warnings, mainly caused by the code that highlights incoming/outgoing ws messages, which isn't directly relevant to the main content of the tutorial.

Yes, the durable object worker needs to be running. I'm adding a note

2024-11-27 18:44 UTC, exectx commented on src/content/docs/workers/tutorials/live-cursors-with-nextjs-rpc-do/index.mdx
> +	- It sends the user's cursor coordinates to the WebSocket server, which broadcasts them to all active WebSocket clients.
Ok I added more details about how the client side logic works and updated the code to reflect a realistic scenario. the part responsible for animating the cursor, switching from css transitions to position interpolation.

2024-11-27 19:00 UTC, bllchmbrs commented
@exectx , I would recommend adding the label `hyperlink-ignore` to this PR. The indentation isn't something we support well today and this is just too chatty to be useful (IMO). Up to you, but that might help remove some of the extraneous suggestions while we look at how best to support the indentation.

2024-11-27 19:48 UTC, exectx commented
@bllchmbrs, thank you for the information but I don't have the necessary permissions for that. Perhaps @harshil1712 or @ToriLindsay could?

2024-11-29 13:42 UTC, harshil1712 requested changes
Hey @exectx,
Thank you for making the changes. We are at the finish line! I have left two more comments. Once we have resolved them, we should be good to go 🚀

2024-11-29 13:42 UTC, harshil1712 commented on src/content/docs/workers/tutorials/live-cursors-with-nextjs-rpc-do/index.mdx
> +
Should I copy the whole URL? I copied the whole URL and ran into issues. Let's explicitly tell the reader to only paste the host and not the protocol (`https`)

2024-11-29 13:42 UTC, harshil1712 commented on src/content/docs/workers/tutorials/live-cursors-with-nextjs-rpc-do/index.mdx
> +2. Change into your root directory and deploy your Next.js app:
Do we still want to use Service bindings in the production? Earlier we told the user we are using it only for local development. So maybe we want to update the steps here?

2024-11-30 02:03 UTC, exectx commented on src/content/docs/workers/tutorials/live-cursors-with-nextjs-rpc-do/index.mdx
> +2. Change into your root directory and deploy your Next.js app:
I think it can be an optional step. i'm adding a note mentioning the user can use the durable object rpc method instead of service bindings if they want.

2024-12-02 12:56 UTC, harshil1712 approved these changes
Thank you for making the changes!

2024-12-02 16:48 UTC, db-cloudflare commented
Amazing work. @exectx Once your author details are confirmed by email and have been updated on this PR then this should be ready to merge!

2024-12-03 13:00 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/live-cursors-with-nextjs-rpc-do/index.mdx
> +  - Durable Objects
```suggestion
  - Durable Objects
  - Developer Spotlight
spotlight:
  author: Ivan Buendia
  author_bio_link: https://www.linkedin.com/in/ibctx/
  author_bio_source: LinkedIn
```

2024-12-03 13:12 UTC, merged