Migration Guide: GitHub Pages -> Cloudflare Pages
cloudflare/cloudflare-docs pull request #1802
Opened 2021-07-16 17:56 UTC by elithrar

Provides a migration guide for migrating an existing Jekyll-based (the most common framework) site on GitHub Pages to Cloudflare Pages.

I recently ran through this myself (https://twitter.com/elithrar/status/1415733165641986049?s=20) after realizing that Cloudflare Pages wasn't successfully building my GitHub Pages repo out-of-the-box - due to the missing `Gemfile`(s).

First draft and open to further feedback!

2021-07-16 21:37 UTC, elithrar commented
Improved the intro paragraph to add more context, and added a time estimate to help reduce the friction/barrier to entry for users considering a migration.

2021-07-19 14:28 UTC, deadlypants1973 requested changes
Review #1

2021-07-19 14:28 UTC, deadlypants1973 commented on products/pages/src/content/migrations/migrating-from-github-pages.md
> +This tutorial shows how to migrate an existing [GitHub Pages site using Jekyll](https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/about-github-pages-and-jekyll) to Cloudflar
```suggestion
This tutorial shows how to migrate an existing [GitHub Pages site using Jekyll](https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/about-github-pages-and-jekyll) to Cloudflare Pages. Jekyll has been one of the most popular static site generators used with GitHub Pages, and migrating your GitHub Pages site to Cloudflare Pages will take a few short steps.
```

2021-07-19 14:28 UTC, deadlypants1973 commented on products/pages/src/content/migrations/migrating-from-github-pages.md
> +3. You know how to use a few basic Git operations, including `add`, `commit`, `push`, `pull`.
```suggestion
3. You know how to use a few basic Git operations, including `add`, `commit`, `push`, and `pull`.
```

2021-07-19 14:28 UTC, deadlypants1973 commented on products/pages/src/content/migrations/migrating-from-github-pages.md
> +If you don't have Rubygems (`gem`) or Bundler (`bundle`) installed on your machine, refer to the installation guides for [Rubygems](https://rubygems.org/pages/download) and [Bundler](https://bundler.
```suggestion
If you do not have Rubygems (`gem`) or Bundler (`bundle`) installed on your machine, refer to the installation guides for [Rubygems](https://rubygems.org/pages/download) and [Bundler](https://bundler.io/).
```

2021-07-19 14:28 UTC, deadlypants1973 commented on products/pages/src/content/migrations/migrating-from-github-pages.md
> +**If your GitHub Pages repo already has a `Gemfile` and `Gemfile.lock` present, you can skip this step entirely.** The GitHub Pages environment assumes a default set of Jekyll plugins that aren't exp
```suggestion
If your GitHub Pages repository already has a `Gemfile` and `Gemfile.lock` present, you can skip this step entirely. The GitHub Pages environment assumes a default set of Jekyll plugins that are not explicitly specified in a `Gemfile`.
```

2021-07-19 14:28 UTC, deadlypants1973 commented on products/pages/src/content/migrations/migrating-from-github-pages.md
> +<Aside>
```suggestion
<Aside type="note">
```

2021-07-19 14:28 UTC, deadlypants1973 commented on products/pages/src/content/migrations/migrating-from-github-pages.md
> +Specifically, we need to create a `Gemfile` and install the `github-pages` gem, which includes all of the dependencies that the GitHub Pages environment assumes.
```suggestion
Specifically, you will need to create a `Gemfile` and install the `github-pages` gem, which includes all of the dependencies that the GitHub Pages environment assumes.
```

2021-07-19 14:28 UTC, deadlypants1973 commented on products/pages/src/content/migrations/migrating-from-github-pages.md
> +We can now run `bundle update`, which will install the `github-pages` gem for us, and create a `Gemfile.lock` file with the resolved dependency versions.
```suggestion
Run `bundle update`, which will install the `github-pages` gem for you, and create a `Gemfile.lock` file with the resolved dependency versions.
```

2021-07-19 14:28 UTC, deadlypants1973 commented on products/pages/src/content/migrations/migrating-from-github-pages.md
> +This should complete successfully. If not, make sure you've copied the `github-pages` line above exactly, and have *not* commented it out with a leading `#`.
```suggestion
This should complete successfully. If not, verify that you have copied the `github-pages` line above exactly, and have not commented it out with a leading `#`.
```

2021-07-19 14:28 UTC, deadlypants1973 commented on products/pages/src/content/migrations/migrating-from-github-pages.md
> +You'll now need to commit these files to your repository so that Cloudflare Pages can reference them in the following steps:
```suggestion
You will now need to commit these files to your repository so that Cloudflare Pages can reference them in the following steps:
```

2021-07-19 14:28 UTC, deadlypants1973 commented on products/pages/src/content/migrations/migrating-from-github-pages.md
> +With your GitHub Pages project now explicitly specifying its dependencies, we can now configure Cloudflare Pages. The process is almost identical to [deploying a Jekyll site](/framework-guides/deploy
```suggestion
With your GitHub Pages project now explicitly specifying its dependencies, you can start configuring Cloudflare Pages. The process is almost identical to [deploying a Jekyll site](/framework-guides/deploy-a-jekyll-site).
```

2021-07-19 14:28 UTC, deadlypants1973 commented on products/pages/src/content/migrations/migrating-from-github-pages.md
> +<Aside>
```suggestion
<Aside type="note">
```

2021-07-19 14:28 UTC, deadlypants1973 commented on products/pages/src/content/migrations/migrating-from-github-pages.md
> +Configuring Cloudflare Pages for the first time? Refer to the [Getting started guide](/getting-started), which covers how to connect your existing GitHub repository to Cloudflare Pages.
```suggestion
If you are configuring your Cloudflare Pages site for the first time, refer to the [Getting started guide](/getting-started#connect-to-github), which explains how to connect your existing GitHub repository to Cloudflare Pages.
```

2021-07-19 14:28 UTC, deadlypants1973 commented on products/pages/src/content/migrations/migrating-from-github-pages.md
> +You can deploy your site to Cloudflare Pages by going to the dashboard and creating a new site. Select the *existing* GitHub repository you use for your GitHub Pages site, and in the configuration se
```suggestion
Begin deployment of your site to Cloudflare Pages by going to your Pages dashboard through the account home and select **Create a project**. Choose the existing GitHub repository you use for your GitHub Pages site, and select **Install & Authorize** and **Begin setup** to continue. After you are directed to the Set up builds and deployments section, provide the following information:
```

2021-07-19 14:28 UTC, deadlypants1973 commented on products/pages/src/content/migrations/migrating-from-github-pages.md
> +Once you've configured your site, you can begin your first deploy. You should see Cloudflare Pages installing `jekyll`, your project dependencies, and building your site, before deploying it.
```suggestion
After you have configured your site, you can begin your first deploy. You should see Cloudflare Pages installing `jekyll`, your project dependencies, and building your site, before deploying it.
```

2021-07-19 14:28 UTC, deadlypants1973 commented on products/pages/src/content/migrations/migrating-from-github-pages.md
> +<Aside>
```suggestion
<Aside type="note">
```

2021-07-19 14:28 UTC, deadlypants1973 commented on products/pages/src/content/migrations/migrating-from-github-pages.md
> +For the complete guide to deploying your first site to Cloudflare Pages, check out [our Getting Started guide](/getting-started).
```suggestion
For the complete guide to deploying your first site to Cloudflare Pages, refer to [the Get started guide](/getting-started).
```

2021-07-19 14:28 UTC, deadlypants1973 commented on products/pages/src/content/migrations/migrating-from-github-pages.md
> +Once you've deployed your site, you'll receive a unique subdomain for your project on `pages.dev`. Every time you commit new code to your Jekyll site, Cloudflare Pages will automatically rebuild your
```suggestion
After you have deployed your site, you will receive a unique subdomain for your project on `pages.dev`. Every time you commit new code to your Jekyll site, Cloudflare Pages will automatically rebuild your project and deploy it. You will also get access to [preview deployments](/platform/preview-deployments) on new pull requests, so you can preview how changes look to your site before deploying them to production.
```

2021-07-19 14:28 UTC, deadlypants1973 commented on products/pages/src/content/migrations/migrating-from-github-pages.md
> +If you're using a [custom domain with GitHub Pages](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site), you'll need to update your DNS record(s) to point at your
```suggestion
If you are using a [custom domain with GitHub Pages](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site), you must update your DNS record(s) to point at your new Cloudflare Pages deployment. This will require you to update the `CNAME` record at the DNS provider for your domain to point to `<your-pages-site>.pages.dev`, replacing `<your-username>.github.io`.
```

2021-07-19 14:28 UTC, deadlypants1973 commented on products/pages/src/content/migrations/migrating-from-github-pages.md
> +Refer to the [adding a custom domain](/getting-started#adding-a-custom-domain) section of the Getting Started guide for a list of detailed steps.
```suggestion
Refer to the [adding a custom domain](/getting-started#adding-a-custom-domain) section of the Get started guide for a list of detailed steps.
```

2021-07-19 15:11 UTC, elithrar commented
Incorporated changes - thanks Kate!

And excuse the commit spam, I didn’t notice the new “batch changes” feature until after the first few.

2021-07-19 15:32 UTC, signalnerve commented
yo @elithrar !!! ty for the PR :) 

my gut feeling is yes, we should merge this - just wondering if it makes sense to generalize this to be migrating from github pages to CF pages, without any specific framework attached to it. at the same time, there's some great insight here on jekyll-specific deploys on pages (something i don't know a ton about): maybe we could bring some of that into the jekyll framework guide?

cc @lukeed - what do you think?

2021-07-19 15:44 UTC, elithrar commented
@signalnerve I’m not opposed to generalizing it, but I think the challenge is that you are using _a_ framework with GitHub Pages, and so the guide runs the risk of being too general by half without the Jekyll bits.

Since Jekyll-on-GitHub-Pages is effectively a (very) opinionated Jekyll install, and was (still is?) GitHub’s default recommendation, the general Jekyll guide doesn’t do the trick.

We should (IMO) consider - 

1. Folding this into the Jekyll guide as an optional step - without making that guide too GitHub specific (?)
2. Ensuring there is still a happy, discoverable path for GitHub Pages users (who may not identify as Jekyll users!) to find the migration guide for them.

2021-07-19 16:50 UTC, deadlypants1973 reviewed
I know that the link says "getting" but the title of the content type on the webpage itself is "Get started" so adding this one additional small change in.

2021-07-19 16:50 UTC, deadlypants1973 commented on products/pages/src/content/migrations/migrating-from-github-pages.md
> +If you are configuring your Cloudflare Pages site for the first time, refer to the [Getting started guide](/getting-started#connect-to-github), which explains how to connect your existing GitHub repo
```suggestion
If you are configuring your Cloudflare Pages site for the first time, refer to the [Get started guide](/getting-started#connect-to-github), which explains how to connect your existing GitHub repository to Cloudflare Pages.
```

2021-07-20 09:22 UTC, ItsYoutacRRS approved these changes

2021-07-27 14:14 UTC, elithrar commented
Updated - reframed as Jekyll-specific. I've also cross-linked the generic Jekyll and the GitHub Pages specific Jekyll guides.

2021-07-27 14:55 UTC, deadlypants1973 approved these changes
Approved with style guide changes.

2021-07-27 14:55 UTC, deadlypants1973 commented on products/pages/src/content/framework-guides/deploy-a-jekyll-site.md
> +
```suggestion
<Aside type="note">

If you have an existing Jekyll site on GitHub Pages, refer to [the Jekyll migration guide](/pages/migrating-jekyll-from-github-pages/).

</Aside>

```

2021-07-27 14:55 UTC, deadlypants1973 commented on products/pages/src/content/framework-guides/deploy-a-jekyll-site.md
>  Jekyll is written in Ruby, meaning that you'll need a functioning Ruby installation in order to install Jekyll.
```suggestion
Jekyll is written in Ruby, meaning that you will need a functioning Ruby installation in order to install Jekyll.
```

2021-07-27 14:55 UTC, deadlypants1973 commented on products/pages/src/content/migrations/migrating-jekyll-from-github-pages.md
> +
```suggestion
<Aside type="note">

If you have a Jekyll-based site not deployed on GitHub Pages, refer to [the Jekyll framework guide](/pages/deploy-a-jekyll-site).

</Aside>

```

2021-07-27 16:04 UTC, elithrar commented
Applied - thanks again Kate!

2021-07-27 17:28 UTC, signalnerve approved these changes

2021-08-03 19:22 UTC, merged