Adding a new tutorial for Turnstile [Developer Spotlight program]
cloudflare/cloudflare-docs pull request #18035
Opened 2024-11-07 06:51 UTC by hideokamoto-stripe

### Summary

Here is a part of the content of Cloudflare Developer Spotlight program. 
We're going to introduce the use case based tutorial using Cloudflare Turnstile.

If you have any question, feedback, or concern, please feel free let us know.

Thanks.

### Screenshots (optional)

<img width="1209" alt="スクリーンショット 2024-11-07 15 51 12" src="https://github.com/user-attachments/assets/8cb924c6-a420-4501-8df9-649e82274a14">

### Documentation checklist

- [ ] The [documentation style guide](https://developers.cloudflare.com/style-guide/) has been adhered to.

2024-11-11 14:59 UTC, db-cloudflare commented on src/content/docs/turnstile/tutorials/protecting-your-payment-form-from-attackers-bots-using-turnstile.mdx
> +- You must have a Stripe account
```suggestion
## Before you begin

<Render file="prereqs" product="workers" />
3. Sign up for a [Stripe](https://stripe.com) account.
```

2024-11-11 14:59 UTC, db-cloudflare commented on src/content/docs/turnstile/tutorials/protecting-your-payment-form-from-attackers-bots-using-turnstile.mdx
> +## Get Your Turnstile sitekey and secret key
```suggestion
## 1. Get Your Turnstile sitekey and secret key
```

2024-11-11 14:59 UTC, db-cloudflare commented on src/content/docs/turnstile/tutorials/protecting-your-payment-form-from-attackers-bots-using-turnstile.mdx
> +## 1. Create a new Worker project
```suggestion
## 2. Create a new Worker project
```

2024-11-11 14:59 UTC, db-cloudflare commented on src/content/docs/turnstile/tutorials/protecting-your-payment-form-from-attackers-bots-using-turnstile.mdx
> +## 2. Preparation for the building web application
```suggestion
```

2024-11-11 14:59 UTC, db-cloudflare commented on src/content/docs/turnstile/tutorials/protecting-your-payment-form-from-attackers-bots-using-turnstile.mdx
> +### Change the file extension to support JSX
```suggestion
## 3. Change index script file extension to .JSX
```

2024-11-11 14:59 UTC, db-cloudflare commented on src/content/docs/turnstile/tutorials/protecting-your-payment-form-from-attackers-bots-using-turnstile.mdx
> +### Register Stripe API key and Turnstile key as environment variables
```suggestion
## 4. Add Stripe API key and Turnstile key as environment variables
```

2024-11-11 14:59 UTC, db-cloudflare commented on src/content/docs/turnstile/tutorials/protecting-your-payment-form-from-attackers-bots-using-turnstile.mdx
> +Let's register API keys as environment variables to use both Stripe and Cloudflare Turnstile.
```suggestion
To connect your web application to both Stripe and Turnstile, you must register the necessary API keys for Stripe and Turnstile as environment variables within your application.
```

2024-11-11 14:59 UTC, db-cloudflare commented on src/content/docs/turnstile/tutorials/protecting-your-payment-form-from-attackers-bots-using-turnstile.mdx
> +Since we'll use JSX to dynamically create HTML, let's change `src/index.ts` to `src/index.tsx`.
```suggestion
Since we will use JSX to dynamically create HTML, you will need to change `src/index.ts` to `src/index.tsx`.
```

2024-11-11 14:59 UTC, db-cloudflare commented on src/content/docs/turnstile/tutorials/protecting-your-payment-form-from-attackers-bots-using-turnstile.mdx
> +By adding this implementation, the order form submission process will be disabled until the Turnstile bot detection process is completed and it is confirmed that the access is not from a bot.
```suggestion
By adding this implementation, the order form submission process will be disabled until the Turnstile bot detection process is completed and it is confirmed that the access request is not from a bot.
```

2024-11-11 14:59 UTC, db-cloudflare commented on src/content/docs/turnstile/tutorials/protecting-your-payment-form-from-attackers-bots-using-turnstile.mdx
> +Here, we're loading the Turnstile script file with a `script` tag. The `_turnstileCB` function is executed when the script file loading is complete, triggered by the `onload=_turnstileCB` in the quer
```suggestion
This will load the Turnstile script file with a `script` tag. The `_turnstileCB` function is executed when the script file loading is complete, triggered by the `onload=_turnstileCB` in the query string.
```

2024-11-11 14:59 UTC, db-cloudflare commented on src/content/docs/turnstile/tutorials/protecting-your-payment-form-from-attackers-bots-using-turnstile.mdx
> +This simple implementation prevents order operations for accesses that Cloudflare identifies as bots.
```suggestion
This implementation blocks order operations for any requests that Cloudflare identifies as being made by a bots.
```

2024-11-11 14:59 UTC, db-cloudflare commented on src/content/docs/turnstile/tutorials/protecting-your-payment-form-from-attackers-bots-using-turnstile.mdx
> +## 3. Implementing Bot Detection with Turnstile
```suggestion
## 5. Implementing Bot Detection with Turnstile
```

2024-11-11 14:59 UTC, db-cloudflare commented on src/content/docs/turnstile/tutorials/protecting-your-payment-form-from-attackers-bots-using-turnstile.mdx
> +## 4. Integrating Turnstile with a Stripe Payment Form
```suggestion
## 6. Integrating Turnstile with a Stripe Payment Form
```

2024-11-11 14:59 UTC, db-cloudflare commented on src/content/docs/turnstile/tutorials/protecting-your-payment-form-from-attackers-bots-using-turnstile.mdx
> +1. Log in to the [Cloudflare dashboard](https://dash.cloudflare.com/) and select your account.
```suggestion
First, you will need to prepare a Cloudflare Turnstile widget to use for this application.

1. Log in to the [Cloudflare dashboard](https://dash.cloudflare.com/) and select your account.
```

2024-11-11 14:59 UTC, db-cloudflare commented on src/content/docs/turnstile/tutorials/protecting-your-payment-form-from-attackers-bots-using-turnstile.mdx
> +First, let's create a Cloudflare Workers project.
```suggestion
Now that your Turnstile widget it ready to use, you can create your Worker application.
```

2024-11-11 14:59 UTC, db-cloudflare commented on src/content/docs/turnstile/tutorials/protecting-your-payment-form-from-attackers-bots-using-turnstile.mdx
> +https://developers.cloudflare.com/turnstile/reference/testing/
```suggestion
You can obtain test site keys and secret keys for Turnstile from the [Turnstile documentation.](https://developers.cloudflare.com/turnstile/reference/testing/)
```

2024-11-11 14:59 UTC, db-cloudflare commented on src/content/docs/turnstile/tutorials/protecting-your-payment-form-from-attackers-bots-using-turnstile.mdx
> +https://dashboard.stripe.com/test/apikeys
```suggestion
Get the publishable key and secret key for Stripe from the [Stripe dashboard].(https://dashboard.stripe.com/test/apikeys)
```

2024-11-11 14:59 UTC, db-cloudflare commented on src/content/docs/turnstile/tutorials/protecting-your-payment-form-from-attackers-bots-using-turnstile.mdx
> +Next, let's implement the code to create a payment form in `src/index.tsx`.
```suggestion
Next, implement the code to create a payment form in `src/index.tsx`. The following code creates a [Payment Intent](https://docs.stripe.com/api/payment_intents) on the server side:
```

2024-11-11 14:59 UTC, db-cloudflare commented on src/content/docs/turnstile/tutorials/protecting-your-payment-form-from-attackers-bots-using-turnstile.mdx
> +For a more practical example, let's integrate Turnstile with a Stripe payment form. First, install the Stripe SDK:
```suggestion
To integrate Turnstile with a Stripe payment form, first you will need to install the Stripe SDK:
```

2024-11-11 14:59 UTC, db-cloudflare commented on src/content/docs/turnstile/tutorials/protecting-your-payment-form-from-attackers-bots-using-turnstile.mdx
> +First, create a [Payment Intent](https://docs.stripe.com/api/payment_intents) on the server side:
```suggestion
```

2024-11-11 14:59 UTC, db-cloudflare commented on src/content/docs/turnstile/tutorials/protecting-your-payment-form-from-attackers-bots-using-turnstile.mdx
> +And adding JavaScript code to display the payment form. Edit `src/index.tsx`:
```suggestion
Then, add the following code to display the payment form. Edit `src/index.tsx`:
```

2024-11-11 14:59 UTC, db-cloudflare commented on src/content/docs/turnstile/tutorials/protecting-your-payment-form-from-attackers-bots-using-turnstile.mdx
> +This way, you can block requests trying to manipulate the payment form using bots, such as card testing attacks.
```suggestion
This way, you can block requests that use bots to try and manipulate the payment form, such as card testing attacks.
```

2024-11-11 14:59 UTC, db-cloudflare commented on src/content/docs/turnstile/tutorials/protecting-your-payment-form-from-attackers-bots-using-turnstile.mdx
> +Let's add a step to verify that the token generated by the Turnstile widget is valid and not forged.
```suggestion
Next, add a step to verify that the token generated by the Turnstile widget is valid and not forged.
```

2024-11-11 14:59 UTC, db-cloudflare commented on src/content/docs/turnstile/tutorials/protecting-your-payment-form-from-attackers-bots-using-turnstile.mdx
> +First, for easier testing, let's remove the `disabled` attribute from the `button` tag:
```suggestion
For easier testing, remove the `disabled` attribute from the `button` tag:
```

2024-11-11 14:59 UTC, db-cloudflare commented on src/content/docs/turnstile/tutorials/protecting-your-payment-form-from-attackers-bots-using-turnstile.mdx
> +Next, let's add an API for server-side verification. Please add the following code to `src/index.tsx`.
```suggestion
Next, add an API for server-side verification. Please add the following code to `src/index.tsx`.
```

2024-11-11 14:59 UTC, db-cloudflare commented on src/content/docs/turnstile/tutorials/protecting-your-payment-form-from-attackers-bots-using-turnstile.mdx
> +## 5. Adding Server-Side Validation
```suggestion
## 7. Add Server-Side Validation
```

2024-11-11 14:59 UTC, db-cloudflare commented on src/content/docs/turnstile/tutorials/protecting-your-payment-form-from-attackers-bots-using-turnstile.mdx
> +title: Protecting your payment form from attackers' bots using Turnstile
```suggestion
title: Protect payment forms from malicious bots using Turnstile
```

2024-11-11 14:59 UTC, db-cloudflare commented on src/content/docs/turnstile/tutorials/protecting-your-payment-form-from-attackers-bots-using-turnstile.mdx
> +This tutorial shows how you can build a more secure payment form using Turnstile. You can learn how to block bot access on the checkout page and trigger additional authentication flows by integrating
```suggestion
This tutorial shows how you can build a more secure payment form using Cloudflare Turnstile. You can learn how to block bot access on the checkout page and trigger additional authentication flows by integrating Turnstile with Stripe
```

2024-11-11 14:59 UTC, db-cloudflare commented on src/content/docs/turnstile/tutorials/protecting-your-payment-form-from-attackers-bots-using-turnstile.mdx
> +At the same time, let's change the filename specified in the `wrangler.toml`.
```suggestion
At the same time, change the filename specified in the `wrangler.toml`.
```

2024-11-11 14:59 UTC, db-cloudflare commented on src/content/docs/turnstile/tutorials/protecting-your-payment-form-from-attackers-bots-using-turnstile.mdx
> +Let's start by creating a form that uses Turnstile to detect bot access. Add the following code to `src/index.tsx` to create a simple form:
```suggestion
Start by creating a form that uses Turnstile to detect bot access. Add the following code to `src/index.tsx` to create a simple form:
```

2024-11-11 14:59 UTC, db-cloudflare commented on src/content/docs/turnstile/tutorials/protecting-your-payment-form-from-attackers-bots-using-turnstile.mdx
> +Let's add JavaScript code to our application to implement bot detection using Turnstile.
```suggestion
Add JavaScript code to our application to implement bot detection using Turnstile.
```

2024-11-11 14:59 UTC, db-cloudflare commented on src/content/docs/turnstile/tutorials/protecting-your-payment-form-from-attackers-bots-using-turnstile.mdx
> +Note: After completing the tests, let's make sure to revert the Turnstile SITE_KEY back to its original value.
```suggestion
:::note
After completing the tests, make sure to revert the Turnstile `SITE_KEY` back to its original value.
:::
```

2024-11-11 15:00 UTC, db-cloudflare commented
Amazing work! Left come small suggestions throughout. Once both the style guide review and technical review have been complete we can merge this PR.

2024-11-12 15:48 UTC, patriciasantaana commented on src/content/docs/turnstile/tutorials/protecting-your-payment-form-from-attackers-bots-using-turnstile.mdx
> +This tutorial shows how you can build a more secure payment form using Turnstile. You can learn how to block bot access on the checkout page and trigger additional authentication flows by integrating
```suggestion
This tutorial shows how you can build a more secure payment form using Turnstile. You can learn how to block bot access on the checkout page and trigger additional authentication flows by integrating Turnstile with Stripe.
```

2024-11-12 16:42 UTC, patriciasantaana commented on src/content/docs/turnstile/tutorials/protecting-your-payment-form-from-attackers-bots-using-turnstile.mdx
> +- You must have a Stripe account
@db-cloudflare I think the other tutorials for Turnstile actually use "Before you begin"

2024-11-12 17:01 UTC, patriciasantaana commented on src/content/docs/turnstile/tutorials/protecting-your-payment-form-from-attackers-bots-using-turnstile.mdx
> +Open your command line interface (CLI) and run the following command:
```suggestion
To efficiently create and manage multiple APIs, let's use [`Hono`](https://hono.dev). Hono is an open-source application framework released by a Cloudflare Developer Advocate. It is lightweight and allows for the creation of multiple API paths, as well as efficient request and response handling.

Open your command line interface (CLI) and run the following command:
```

2024-11-12 17:07 UTC, patriciasantaana commented on src/content/docs/turnstile/tutorials/protecting-your-payment-form-from-attackers-bots-using-turnstile.mdx
> +And place each keys into the `.dev.vars` file like the following:
```suggestion
Then, place each keys into the `.dev.vars` file like the following:
```

2024-11-12 17:07 UTC, patriciasantaana commented on src/content/docs/turnstile/tutorials/protecting-your-payment-form-from-attackers-bots-using-turnstile.mdx
> +```sh
```suggestion
After that, you can generate TypeScript type definition by running the `npm run cf-typegen` command.

```sh
```

2024-11-12 17:08 UTC, patriciasantaana commented on src/content/docs/turnstile/tutorials/protecting-your-payment-form-from-attackers-bots-using-turnstile.mdx
> +Now we're ready for application development. In the next steps, we'll develop a payment form using Turnstile and Stripe.
```suggestion
Now we are ready for application development. In the next steps, we will develop a payment form using Turnstile and Stripe.
```

2024-11-12 17:11 UTC, patriciasantaana commented on src/content/docs/turnstile/tutorials/protecting-your-payment-form-from-attackers-bots-using-turnstile.mdx
> +If you restart the application now, you'll notice that you can't submit the payment form.
```suggestion
If you restart the application now, you will notice that you cannot submit the payment form.
```

2024-11-12 17:12 UTC, patriciasantaana commented on src/content/docs/turnstile/tutorials/protecting-your-payment-form-from-attackers-bots-using-turnstile.mdx
> +Note: After completing the tests, let's make sure to revert the Turnstile SITE_KEY back to its original value.
Might be better as a note aside

2024-11-12 17:12 UTC, patriciasantaana commented on src/content/docs/turnstile/tutorials/protecting-your-payment-form-from-attackers-bots-using-turnstile.mdx
> +By executing this before calling Stripe's JavaScript SDK in the form's submit event, we can decide whether to proceed with the payment based on the server-side validation result:
```suggestion
Then, add the process to call the created API.

By executing this before calling Stripe's JavaScript SDK in the form's submit event, we can decide whether to proceed with the payment based on the server-side validation result:
```

2024-11-12 17:13 UTC, patriciasantaana commented on src/content/docs/turnstile/tutorials/protecting-your-payment-form-from-attackers-bots-using-turnstile.mdx
> +Since we're saving the Turnstile authentication result in the Stripe data, it's also easier to investigate if a user reports a payment failure.
```suggestion
By adding this step, we now perform a two-stage check using Turnstile before the payment process.

Since we are saving the Turnstile authentication result in the Stripe data, it is also easier to investigate if a user reports a payment failure.
```

2024-11-12 17:13 UTC, patriciasantaana commented on src/content/docs/turnstile/tutorials/protecting-your-payment-form-from-attackers-bots-using-turnstile.mdx
> +In online payments, it's necessary to protect applications from bot attacks such as card testing and DDoS.
```suggestion
In online payments, it is necessary to protect applications from bot attacks such as card testing and DDoS attacks.

```

2024-11-12 17:13 UTC, patriciasantaana approved these changes
Added a few edits!

2024-11-12 17:48 UTC, db-cloudflare commented on src/content/docs/turnstile/tutorials/protecting-your-payment-form-from-attackers-bots-using-turnstile.mdx
> +So far, we've covered how to create a Cloudflare Worker project and introduced tools and open-source projects like the `C3` command and the `Hono` framework that streamline development with Cloudflar
```suggestion
So far, we've covered how to create a Worker project using `C3` and introduced the open source `Hono` framework that streamlines web-application development with Workers.
```

2024-11-12 17:48 UTC, db-cloudflare commented on src/content/docs/turnstile/tutorials/protecting-your-payment-form-from-attackers-bots-using-turnstile.mdx
> +- You must have a Stripe account
Good point, this might be something to change across the board then rather than just on this one. Will revert it to 'Before you begin' for now.

2024-11-20 00:39 UTC, hideokamoto-stripe commented
Thank you @db-cloudflare  and @patriciasantaana for reviewing!
I updated this draft 👍

2024-12-12 11:23 UTC, megaconfidence requested changes
I shared some suggestions, but otherwise this article looks good to me.

2024-12-12 11:23 UTC, megaconfidence commented on src/content/docs/turnstile/tutorials/protecting-your-payment-form-from-attackers-bots-using-turnstile.mdx
> +To efficiently create and manage multiple APIs, let's use [`Hono`](https://hono.dev). Hono is an open-source application framework released by a Cloudflare Developer Advocate. It is lightweight and a
```suggestion
To efficiently create and manage multiple APIs, let's use [`Hono`](https://hono.dev). It is lightweight and allows for the creation of multiple API paths, as well as efficient request and response handling.
```

2024-12-12 11:23 UTC, megaconfidence commented on src/content/docs/turnstile/tutorials/protecting-your-payment-form-from-attackers-bots-using-turnstile.mdx
> +Get the publishable key and secret key for Stripe from the [Stripe dashboard].(https://dashboard.stripe.com/test/apikeys)
```suggestion
Get the publishable key and secret key for Stripe from the [Stripe dashboard](https://dashboard.stripe.com/test/apikeys).
```

2024-12-12 11:23 UTC, megaconfidence commented on src/content/docs/turnstile/tutorials/protecting-your-payment-form-from-attackers-bots-using-turnstile.mdx
> +```diff
```suggestion
```diff lang="ts"
```

2024-12-12 11:23 UTC, megaconfidence commented on src/content/docs/turnstile/tutorials/protecting-your-payment-form-from-attackers-bots-using-turnstile.mdx
> +```diff
```suggestion
```diff lang="ts"
```

2024-12-12 11:23 UTC, megaconfidence commented on src/content/docs/turnstile/tutorials/protecting-your-payment-form-from-attackers-bots-using-turnstile.mdx
> +```diff
```suggestion
```diff lang="ts"
```

2024-12-12 11:23 UTC, megaconfidence commented on src/content/docs/turnstile/tutorials/protecting-your-payment-form-from-attackers-bots-using-turnstile.mdx
> +```diff
```suggestion
```diff lang="ts"
```

2024-12-12 11:23 UTC, megaconfidence commented on src/content/docs/turnstile/tutorials/protecting-your-payment-form-from-attackers-bots-using-turnstile.mdx
> +In online payments, it ss necessary to protect applications from bot attacks such as card testing and DDoS attacks.
```suggestion
In online payments, it is necessary to protect applications from bot attacks such as card testing and DDoS attacks.
```

2024-12-13 00:21 UTC, hideokamoto-stripe commented
@megaconfidence 
Thanks you for reviewing my post! 
I updated this draft.

Best.

2024-12-16 10:40 UTC, megaconfidence approved these changes
Thanks!

2024-12-17 16:21 UTC, merged

2025-01-01 18:12 UTC, punkeel commented
Thanks for the tutorial @hideokamoto-stripe! Do you think it would be interesting to record `metadata.ephemeral_id` (see [server side validation docs](https://developers.cloudflare.com/turnstile/get-started/server-side-validation/)) as a Stripe metadata, if returned by the /siteverify endpoint?