Add content version management system tutorial
cloudflare/cloudflare-docs pull request #18088
Opened 2024-11-10 10:24 UTC by shinchan79

### Summary

Add a new tutorial "Content Version Management System using Cloudflare Workers and Durable Objects."

### Screenshots (optional)

### Documentation checklist

- [x] The [documentation style guide](https://developers.cloudflare.com/style-guide/) has been adhered to.
- [x] If a larger change - such as adding a new page- an issue has been opened in relation to any incorrect or out of date information that this PR fixes.

### Proposed changes
Added a new tutorial in the `src/content/docs/workers/tutorials/build-a-content-version-system` directory.

The functions which we will be covering in this tutorial are as follows:
- Create a new content
- Update the content
- Get the content (specific version and list of all versions)
- Revert to a specific version
- Publish or unpublish a version
- Detailed history of modifications
- Tag a version
- Delete a version (in case you do not need it anymore)

The functions are implemented on Cloudflare Workers and the states of the contents are managed on Durable Objects. 

The tutorial used TypeScript code and Bash commands. 
Code snippets and examples adhere to the Cloudflare documentation style guide.

2024-11-20 15:40 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +title: Building a Content Version Management System with Cloudflare Workers and Durable Objects
```suggestion
title: Build a version control system with Cloudflare Workers and Durable Objects
```

2024-11-20 15:40 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +title: Building a Content Version Management System with Cloudflare Workers and Durable Objects
Very impressive work. I have a few questions that will help me make sure I conduct the style guide review properly. Would version control system be a better term to describe the project? For SEO purposes, I think VCS might be more direct as content version management system might get confused with a CMS. I may be wrong, so let me know what you think.

2024-11-20 15:40 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +title: Building a Content Version Management System with Cloudflare Workers and Durable Objects
Also two other questions I have:

1. Are there any restrictions on the file types this project is capable of handling for version control? For example, can it record versions for file types such as .ts, .js, .txt and so on?

2. Can it handle multiple files at a time or only one file at a time?

2024-11-21 14:19 UTC, shinchan79 commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +title: Building a Content Version Management System with Cloudflare Workers and Durable Objects
@db-cloudflare Here are my answers for your questions: 

**Question 1: Would version control system be a better term to describe the project?** => I think that it's OK, because the first thing I think about when create project is building from scratch something similar to Git using Cloudflare products. 
2. **Are there any restrictions on the file types this project is capable of handling for version control? For example, can it record versions for file types such as .ts, .js, .txt and so on?** => No, there's no limit, I just want it to have an experience similar to git diff because I like this style.
**3. Can it handle multiple files at a time or only one file at a time?** => Now it's only one file at a time now. I will continue to support diff multiple file in near future

2024-11-22 15:24 UTC, shinchan79 commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +title: Building a Content Version Management System with Cloudflare Workers and Durable Objects
@db-cloudflare  I have deployed a demo of how to utilize this guide. This is only an example, there are also other ways to use a version management: 

Management content version website: https://version-control-frontend.pages.dev/
Main site: https://content-version-system.trinhhaiyen79.workers.dev/ (Only published version are shown here) 

Hope that my example demo help you understand more about my app.

2024-11-26 13:12 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +An important advantage concerning Content Versioning Management System is that content can have several versions, which can always be backtracked to at any point in time. In this tutorial, the conten
```suggestion
Version Control Systems allow you record several versions of a project or file, which can be backtracked to at any point in time. Git is an example of a version control system.

In this tutorial, you will build a version control system powered by Cloudflare that can track changes made to content such as files of text or code. Cloudflare Workers will be used to handle functions such as creating versions for content, and Durable Objects will be used to record version states.
```

2024-11-26 13:12 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +```
```suggestion
```

2024-11-26 13:12 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +```
We generally don't recommend installing wrangler globally to prevent incompatibilities between different projects that may require different versions of wrangler. Using C3 will install the latest version of wrangler locally to the worker project.

2024-11-26 13:12 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +<summary>src/types.ts</summary>
The `<details>` dropdown is better suited for secondary information that is not essential to complete the tutorial. For long code blocks that are required for the tutorial, I recommend taking them out of the dropdowns and try to do either of the following:

A: Use a paragraph to describe in detail the purpose for the functions within a code block

or 

B: For very long code blocks, you can break them down into sub steps where you can describe the purpose of that individual step. You can add TODO comments where a block of code requires additional functions added in a future step to help readers not get lost across the multiple steps either.

2024-11-26 13:18 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +title: Building a Content Version Management System with Cloudflare Workers and Durable Objects
This is amazing! Thank you very much for sharing these live examples.

2024-11-26 16:18 UTC, shinchan79 commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +<summary>src/types.ts</summary>
@db-cloudflare Updated, please review again and let me know if there is anything that I should improve. Thank you for your help!

2024-11-26 17:48 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +## 0. Install tools.
### 
```suggestion
## 1. Set up Worker project and Durable Objects
```

2024-11-26 17:48 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +- Basic knowledge of TypeScript
```suggestion
A Cloudflare account with a [Workers Paid plan](/workers/platform/pricing/#workers) is required so that you can use Durable Objects.
```

2024-11-26 17:48 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +In this file, we will define data structures that will be used in the Durable Objects and the Worker. The purpose is to make sure that the data structures are consistent and more efficiently state ma
```suggestion
The data structures that will be used by the Durable Object and the Worker to handle state management must first be defined. In this step the following data will be defined:

- The different states a content version can have (`draft`, `published` and `archived`).
- The core data structure for version management, such as a version id number, the contained content and the attached version message.
- The data structure to track version events and history.
- The API response structure.

Add the following code to the `src/types.ts` file:
```

2024-11-26 17:48 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +```
```suggestion
```

2024-11-26 17:48 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +## 1. Create a new Workers project.
```suggestion
```

2024-11-26 17:48 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +We will start by creating a new Workers project using the Wrangler CLI.
```suggestion
To create a Worker project that is ready to use Durable Objects, run [C3 (create-cloudflare-cli)](https://github.com/cloudflare/workers-sdk/tree/main/packages/create-cloudflare) in your CLI.
```

2024-11-26 17:48 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +When you run the command above, you will be asked to provide some information about your project. You can use the following values:
```suggestion
After running the command above, you will be asked to provide information on what kind of project you would like to create. Use the following values:
```

2024-11-26 17:48 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +After done, we will have a new Workers project with the name `content-version-system` that contains following files and directories:
```suggestion
### Configure the Worker and Durable Object binding

Once `C3` has finished running, you should now have Workers project with the name `content-version-system` that contains Cloudflare's development tool [Wrangler](/workers/wrangler/) along following files and directories:
```

2024-11-26 17:48 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +We will modify the `wrangler.toml` file to specify our configuration for the Durable Objects.
```suggestion
Modify the `wrangler.toml` configuration file by adding a Durable Objects binding that enables the Worker application to communicate with the Durable Object.
```

2024-11-26 17:48 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +then run `npm install` to install the dependencies.
```suggestion
Then run `npm install` to install the dependencies.
```

2024-11-26 17:48 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +Replace the `package.json` with following content:
```suggestion
### Install required packages

Replace the `package.json` with following content:
```

2024-11-26 17:48 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +Replace the `package.json` with following content:
It would be good to mention which packages are being installed here.

2024-11-26 17:48 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +
```suggestion

### Configure tsconfig.json file

```

2024-11-26 17:48 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +Edit the content of the `tsconfig.json` file:
Would be good to mention why the `tsconfig.json` file has to be edited and what part needs to be edited, even if it's just a simple package compatibility reason.

2024-11-26 17:48 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +
```suggestion
## 2. Define the data structures for a version control system

```

2024-11-26 17:48 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +
```suggestion
 ## 3. Handle requests sent to the Durable Object
 
```

2024-11-26 17:48 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +In the flow of this file, Cloudflare Workers will acts as a router, route the incoming requests to the Durable Objects instance. The Durable Objects instance will process the request, and then provid
```suggestion
Cloudflare Workers will route incoming requests to the Durable Objects instance. The Durable Objects instance then processes the request, and provides the appropriate response to the Worker.

To handle incoming requests, add the following code to `src/index.ts`:
```

2024-11-26 17:48 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +**src/index.ts: Entrypoint for request routing and presentation**
```suggestion
```

2024-11-26 17:48 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +**src/types.ts: Interface definitions for data structures**
```suggestion
```

2024-11-26 17:48 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +/**
There's a lot of different functionality happening here. I would break these steps out into multiple code blocks to make it easier to digest. Each code block could be a separate tutorial step with the `###` styling for the step title (Doesn't need a number, just the title for the sub step section works). I've commented on the code that I think could be separated out into multiple code blocks and sub steps as an example.

2024-11-26 17:48 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +
Initial setup and HTML could be step 1

2024-11-26 17:48 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +export { ContentDO };
CORS headers and version management helper could be step 2

2024-11-26 17:48 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +};
Request handling could be step 3

2024-11-26 17:48 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +**src/contentDO.ts: The core business logic**
```suggestion
## 4. Build the core version control system logic
```

2024-11-26 17:48 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +- Flows of operation: reading the state → making changes → writing the changes
```suggestion
This file allow you to perform Create - Update - Delete - Read (CRUD) operations on the content versions and the version tags. Additionally, it is possible to either publish or unpublish a version, obtain detailed information on the modification history, compare versions (similar to the git `diff command`), and go back to a particular version.
- All the states are recorded in the Durable Object storage.
- Operations occur in the following order: read the state → process changes → write the changes.
```

2024-11-26 17:48 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +
Similar to my above suggestion about separating out the `index.ts` code block, the `contentDO.ts` code block could be seperated out as well into multiple sub steps and code blocks. See my suggestions on separating it out below.

2024-11-26 17:48 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +
Initial setup, CORS configuration and Durable Object Class setup could be step 1.

2024-11-26 17:48 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +
Request handling and route management could be step 2

2024-11-26 17:48 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +
Core version control functions could be step 3

2024-11-26 17:48 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +
Version tag management could be step 4

2024-11-26 17:48 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +  }
Publishing system could be step 5

2024-11-26 17:48 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +}
Diff handling and version control operations could be step 6

2024-11-26 17:48 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +## 4. Additional tutorial tips
```suggestion
## 4. Additional resources
```

2024-11-26 17:48 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +```
```suggestion
To handle version control functions, add the following code to `src/contentDO.ts`:
```
```

2024-11-26 20:23 UTC, shinchan79 commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +```
@db-cloudflare  nearly rewrite the content. Thank you so much for guiding me. Hope that it's better now. Please review once again

2024-11-27 12:11 UTC, db-cloudflare reviewed
A few more suggestions but the style guide review is almost complete! Then the technical review to check that the finished application can be built from the tutorial will begin. Great work 👍

2024-11-27 12:11 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +Once `C3` has finished running, you should now have Workers project with the name `content-version-system` that contains Cloudflare's development tool [Wrangler](/workers/wrangler/) along following f
```suggestion
Once `C3` has finished running, you should now have a Workers project with the name `content-version-system` that contains Cloudflare's development tool [Wrangler](/workers/wrangler/) along following files and directories:
```

2024-11-27 12:11 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +You can find source code for this project on: [GitHub](https://github.com/shinchan79/content-version-system.git). Next parts will explain the main components of this project.
```suggestion
```

2024-11-27 12:11 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +Now, we will create code files inside the 'src' directory to implement out functions. File structute will be as follows:
```suggestion
Create the files 'types.ts' and 'contentDO.ts' inside the 'src' directory. The file structure will be as follows:
```

2024-11-27 12:11 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +`;
```suggestion
`;
// TODO: CORS and helper functions
```

2024-11-27 12:11 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +### CORS and Helper Functions
```suggestion
### CORS and helper functions
```

2024-11-27 12:11 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +You need to set up CORS headers to allow cross-origin requests. Add CORS headers and version management helper as below:
```suggestion
Set up CORS headers to allow cross-origin requests, then add a function to retrieve the latest published version of content from durable objects. Add the following code to `src/index.ts`:
```

2024-11-27 12:11 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +}
```suggestion
}

// TODO: Request handler
```

2024-11-27 12:11 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +### Request Handler
```suggestion
### Request handler
```

2024-11-27 12:11 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +The following code will handle the main requests.
```suggestion
Add the following code to `src/index.ts` to handle requests for the Durable Object:
```

2024-11-27 12:11 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +- There are 2 important things you have to pay attention to: First, you need to setup the CORS headers to allow cross-origin requests. Second, the class name of the Durable Object must match the name
```suggestion
- All the states are recorded in the Durable Object storage.
- Operations occur in the following order: read the state → process changes → write the changes.
- All operations are asynchronous because of storage communications.

For this Durable Object to work correctly, you need to setup the CORS headers to allow cross-origin requests in the `src/contentDO.ts` file. The class name of the Durable Object must also match the name defined in the wrangler.toml file, otherwise you will encounter an error when deploying this project with `wrangler deploy` later on.
```

2024-11-27 12:11 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +}
```suggestion
}
// TODO: Request handling and routing
```

2024-11-27 12:11 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +### Request Handling and Routing
```suggestion
### Request handling and routing
```

2024-11-27 12:11 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +}
```suggestion
}
// TODO: Core version control functionality
```

2024-11-27 12:11 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +To handle version control functions, add the following code to `src/contentDO.ts`:
```suggestion
```

2024-11-27 12:11 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +
```suggestion

To handle version control functions, add the following code to `src/contentDO.ts`:

```

2024-11-27 12:11 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +This file allow you to perform Create - Update - Delete - Read (CRUD) operations on the content versions and the version tags. Additionally, it is possible to either publish or unpublish a version, o
```suggestion
The `src/contentDO.ts` file allows users to perform Create - Update - Delete - Read (CRUD) operations on the content versions and the version tags. Additionally, it is possible to either publish or unpublish a version, obtain detailed information on the modification history, compare versions (similar to the git `diff command`), and go back to a particular version.
```

2024-11-27 12:11 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +Add request handling methods:
```suggestion
Add the request handling methods to `src/contentDO.ts`:
```

2024-11-27 12:11 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +### Core Version Control Functions
```suggestion
### Core version control functions
```

2024-11-27 12:11 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +Following are the basic version control operations. For complete implementation details, see GitHub repository:
```suggestion
Add the following version control operation functions to `src/contentDO.ts`
```

2024-11-27 12:11 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +}
```suggestion
}

async deleteVersion(id: number): Promise<{ success: boolean; message: string }> {
    const data = await this.initialize();
    const versionIndex = data.versions.findIndex(v => v.id === id);
    if (versionIndex === -1) throw new Error("Version not found");

    data.versions.splice(versionIndex, 1);
    if (data.currentVersion === id) {
      const lastVersion = data.versions[data.versions.length - 1];
      data.currentVersion = lastVersion ? lastVersion.id : 0;
      data.content = lastVersion ? lastVersion.content : null;
    }

    await this.state.storage.put("content", data);
    return { success: true, message: `Version ${id} deleted successfully` };
  }
  
//TODO: Tag management functions
```

2024-11-27 12:11 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +}
Are the delete versions functions missing here?

2024-11-27 12:11 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +### Tag Management functions
```suggestion
### Tag management functions
```

2024-11-27 12:11 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +}
```suggestion
}

async updateTag(oldName: string, newName: string): Promise<Tag> {
    const data = await this.initialize();
    const oldTag = data.tags[oldName];
    if (!oldTag) throw new Error("Tag not found");
    if (oldName !== newName && data.tags[newName]) throw new Error("New tag exists");

    const updatedTag = {
      ...oldTag,
      name: newName,
      updatedAt: new Date().toISOString()
    };
    delete data.tags[oldName];
    data.tags[newName] = updatedTag;
    await this.state.storage.put("content", data);
    return updatedTag;
  }
  
 //TODO: Publish and unpublish functions
```

2024-11-27 12:11 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +}
Is the `updateTag` function missing here?

2024-11-27 12:11 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +### Publishing and Unpublishing functions
```suggestion
### Publish and unpublish functions
```

2024-11-27 12:11 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +}
```suggestion
}

// TODO: Diff and version control operations
```

2024-11-27 12:11 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +### Diff and Version Control Operations
```suggestion
### Diff and version control operations
```

2024-11-27 12:11 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +}
I think there might be a missing `}` at the end here?

2024-11-27 12:11 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +## 5. Testing and Deployment
```suggestion
## 5. Test and deploy
```

2024-11-27 12:11 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +### Version Management Operations
```suggestion
### Version management operations
```

2024-11-27 12:11 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +### Tag Operations
```suggestion
### Tag operations
```

2024-11-27 12:11 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +### Publishing and Unpublishing Operations
```suggestion
### Publish and unpublish operations
```

2024-11-27 12:11 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +You can find source code for this project on: [GitHub](https://github.com/shinchan79/content-version-system.git). Next parts will explain the main components of this project.
I think leaving the github link until the end should be okay, as we can also include a link to your github at the top of the tutorial.

2024-11-27 12:11 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +### Initial Setup and HTML Template
```suggestion
### Initial setup and HTML template
```

2024-11-27 12:11 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +    // Add other route handlers here (You can see the full code on GitHub repository)
I would add the full route handler code back here so readers can still complete a full project from reading this page alone if they want.

2024-11-27 12:11 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +// For full HTML template and styling details, see the GitHub repository.
If the HTML template and styling details are needed to complete this project you can include them here.

2024-11-28 11:13 UTC, shinchan79 commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +// For full HTML template and styling details, see the GitHub repository.
@db-cloudflare  I have added all the necessary code and verify again the correctness of the code. As long as you implement all the code in: Request handling and routing, Core version control functions, Tag management functions, Publishing and unpublishing functions, Diff and version control operations inside the ContentDO class, as the note that I added in the guide: "Please note that all code snippets in the following sections are implemented inside the ContentDO class." The application should work.

2024-11-28 11:17 UTC, shinchan79 commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +// For full HTML template and styling details, see the GitHub repository.
You can refer to the deployed version: Deployment of the 1st time (The time deployed as PoC for this guide): https://content-version-system.trinhhaiyen79.workers.dev/

Re-deploy in another workspace to verify the  correctness of this guide: https://content-version-system.sycu-lee.workers.dev/

2024-11-29 11:59 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +// For full HTML template and styling details, see the GitHub repository.
Thank you very much for the update. Super impressive work! Once the technical review by a second reviewer is completed we can then merge this PR.

2024-12-03 10:04 UTC, harshil1712 requested changes
Hey @shinchan79, this is great tutorial! However, I believe it needs some more work before it can be published. I have left a few comments, and here's my general feedback:
- Can we have explanation for the code blocks? The comments in the code are excellent, but an explanation outside of that will be helpful
- I get TypeScript errors when following the flow you describe: adding code to index.ts, handling request in DO, and then adding code functionality in DO. You reference methods and variables that are defined in the later steps. Seeing these errors can confuse the reader. Can we change the order?
- I am not sure if a front-end is needed for the tutorial. Your deployed link takes me to a Next.js app. However, I don't see that in here. Can you clarify that for me?

Thank you again for the contribution. This is a great tutorial and I am excited to see this get published.

2024-12-03 10:04 UTC, harshil1712 commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +```
Let's use components for this. Here's an example: https://github.com/cloudflare/cloudflare-docs/blob/production/src/content/docs/durable-objects/tutorials/build-a-seat-booking-app/index.mdx#1-create-a-new-project

2024-12-03 10:04 UTC, harshil1712 commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +Modify the `wrangler.toml` configuration file by adding a Durable Objects binding that enables the Worker application to communicate with the Durable Object.
Since we are using the Durable Object starter template, bindings are already available. Let's ask the reader to update the values instead

2024-12-03 10:04 UTC, harshil1712 commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +### Install required packages
Can we update this section? The list of packages makes me think that I need to install of these packages, which is not true. Let's also ask the user to install the packages using the npm directly, instead of asking them to update package.json first.

2024-12-03 10:04 UTC, harshil1712 commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +### Configure tsconfig.json file
The default config file worked fine for me. Is this required?

2024-12-03 10:04 UTC, harshil1712 commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +interface Env {
Let's follow the best practices here. We should update the `worker-configuration.d.ts` to add the type for ContentDO. You can use the command `npm run cf-typegen` to create the bindings.

2024-12-03 10:04 UTC, harshil1712 commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +To handle incoming requests, add the following code to `src/index.ts`:
Should I add the code, or replace the existing code?

2024-12-03 10:04 UTC, harshil1712 commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +- `itty-router` - A tiny, zero-dependency router designed for Cloudflare Workers
Do we need this package? I couldn't find where this was used?

2024-12-03 10:04 UTC, harshil1712 commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +    <a href="http://localhost:3000" class="button">Content Version Management</a>
This will result in a 404. Is there front-end coding missing with this project?

2024-12-03 10:04 UTC, harshil1712 commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +};
Since we are handling CORS in the worker, do we really need it here? When the request is made, it first goes through the Worker and only then to the Durable Object

2024-12-03 10:04 UTC, harshil1712 commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +In your browser, navigate to `http://localhost:8787` to preview your project.
What do we expect the user to see here? Is there anything that they need to do (click a button, make CURL request) to test the functionality?

2024-12-03 10:04 UTC, harshil1712 commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +wrangler deploy
We should use `npx wrangler deploy`. The reader might not have wrangler globally installed

2024-12-03 10:04 UTC, harshil1712 commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +You can find source code for this project on: [GitHub](https://github.com/shinchan79/content-version-system.git)
While these are good, we should have more resources that can help the reader know about the next steps

2024-12-03 14:39 UTC, db-cloudflare commented
A small suggestion, It might be also worth changing the folder name from `build-a-content-version-system` to `build-a-version-control-system` to match the new title.

2024-12-03 14:45 UTC, shinchan79 commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +### Configure tsconfig.json file
When I tried to deploy in the first time, I got error and have to modify. After that, I have change codes sometimes, I will test once more with default and remove if it is not needed.

2024-12-03 14:49 UTC, shinchan79 commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +    <a href="http://localhost:3000" class="button">Content Version Management</a>
Actually because of the fact that the tutorial is quite long, I  have remove the front end code, and add the link link to front end repo in the README of backend repo: https://github.com/shinchan79/content-version-system/blob/main/README.md. Maybe I will remove this button if it makes reader confused

2024-12-03 14:52 UTC, shinchan79 commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +In your browser, navigate to `http://localhost:8787` to preview your project.
navigate to `http://localhost:8787` => They might just follow the link shown in the Terminal, or copy the link and paste into browser, and make CURL is also OK, just a step to confirm that the backend code works.

2024-12-03 14:54 UTC, shinchan79 commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +To handle incoming requests, add the following code to `src/index.ts`:
Replace the code with my code. I will update here to clarify

2024-12-09 11:34 UTC, shinchan79 commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +You can find source code for this project on: [GitHub](https://github.com/shinchan79/content-version-system.git)
@harshil1712  orry for the late reply. I was sick last week, and only today I'm able to work and update the PR based on your comments. 

Please check and let me know if there is anything I should improve. Thank you so much!

2024-12-15 05:08 UTC, shinchan79 commented
@harshil1712 just want to ask if any other things should I improve after my most updated commit?

2024-12-17 08:42 UTC, harshil1712 commented
> @harshil1712 just want to ask if any other things should I improve after my most updated commit?

Thank you for making the changes. I wasn't sure if it was ready for review. I will review it this week. Thank you!

2024-12-27 18:24 UTC, harshil1712 reviewed
Hey, I like where we are going with this! I have left a few comments. I was also wondering, do we need the front-end like we have in your finished demo? If so, can we add it in the tutorial? The front-end part can be something they can git clone, maybe? Also, we can use Workers Static Assets to serve the front-end. This will allow us to have it all in a single repo

2024-12-27 18:24 UTC, harshil1712 commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +mode = "smart"
This is good to have, but not required. If we want to keep it, it would be nice to add one-two line telling the reader what it is and link it to the docs

2024-12-27 18:24 UTC, harshil1712 commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +  }
Let's update to something as follows:
```json
"scripts": {
...
    "lint": "npx eslint . --ext .ts --fix",
    "format": "prettier --write .",
    "test": "vitest run",
    "test:watch": "vitest"
  }
```
If the reader simply copy pastes this, they might overwrite the existing scripts and run into error when running commands like `npm run dev`

2024-12-27 18:24 UTC, harshil1712 commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +};
When running the command `npm run cf-typegen` we are already getting this type. We don't need to define it again.

2024-12-27 18:24 UTC, harshil1712 commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +import { ContentDO } from './contentDO';
We haven't defined the DO class. This will throw an error. We should move the DO code before this, or add note letting the user know that an error is expected.

2024-12-27 18:24 UTC, harshil1712 commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +- Sets up CORS headers for cross-origin requests
Why do we need CORS? Since we are not calling the worker from another URL, this shouldn't be required.

2024-12-27 18:24 UTC, harshil1712 commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +- Sets up necessary imports and CORS headers
Same as the previous comment on CORS

2024-12-29 04:36 UTC, shinchan79 commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +mode = "smart"
@harshil1712  I have read all your comment. Thanks for helping me write a better article. Please give me some days, I will try my best to resolves all the comments next week. Thank you so much!

2024-12-29 04:37 UTC, shinchan79 commented on src/content/docs/workers/tutorials/build-a-content-version-system/index.mdx
> +mode = "smart"
I will also edit a little bit in the front-end repo so that the code is more understandable, and will insert the link in the tutorial for whoever need frontend part.

2025-05-28 17:56 UTC, kodster28 commented
This PR has been sitting for quite a while without any updates (or response to the comments dropped by @harshil1712).

Going to close it out for now. If you want to continue with the work, you'll need to make a new one.

2025-05-28 17:56 UTC, closed without merging