Product Directory Refresh
cloudflare/cloudflare-docs pull request #18133
Opened 2024-11-12 18:32 UTC by hturan

### Summary
This PR gives a visual and functional refresh to the Products page (https://developers.cloudflare.com/products), including iconography, product descriptions, and the ability to search.

### Screenshots (optional)
![Screenshot 2024-11-12 at 15 43 53](https://github.com/user-attachments/assets/75cb9900-ee9e-4371-9870-8dcfcd4efcb5)
![Screenshot 2024-11-12 at 15 44 02](https://github.com/user-attachments/assets/12462b17-5721-465c-8ab5-38f784fe1ca4)
![Screenshot 2024-11-12 at 15 44 16](https://github.com/user-attachments/assets/9264c49d-8643-4840-a343-11166c45e1b6)
![Screenshot 2024-11-12 at 15 45 29](https://github.com/user-attachments/assets/66d7bc9b-da34-4a68-b48c-d49b14fb4e18)
![Screenshot 2024-11-12 at 18 31 27](https://github.com/user-attachments/assets/738c9c26-8816-4189-8ea3-b8bb1e87ed9f)

### Documentation checklist
- [x] The [documentation style guide](https://developers.cloudflare.com/style-guide/) has been adhered to.

2024-11-12 18:33 UTC, hturan commented on src/components/ProductCatalog.tsx
Lots of room for us to de-dupe this and `ModelCatalog` in the future. Left it be for now until we tackle a third instance of this pattern.

2024-11-12 18:35 UTC, hturan commented on src/pages/products.astro
> +import iconCollection from "virtual:astro-icon";
I got 90% of the way through this work and then realised we have no good way to render icon / SVGs in `react`, and `astro-icon` does some interesting integration/optmimization under the hood. This code here replicates a little of what the `Icon` component does (https://github.com/natemoo-re/astro-icon/blob/531db17ec5367e22df7958d8f7abdeb880d8342b/packages/core/components/Icon.astro#L92) but just passes optimised SVG data through to React to render.

2024-11-12 18:35 UTC, hturan commented on src/pages/products.astro
> +import iconCollection from "virtual:astro-icon";
I originally had this in the `jsx` component, but due to how Astro works it was trying to import `node` modules into the client-side and breaking.

2024-11-12 18:36 UTC, hturan commented on src/pages/products.astro
> +import iconCollection from "virtual:astro-icon";
I also tried directly importing the icons (using `import` URLs), but you can't style SVG when used as an `img` `src`.

2024-11-13 15:23 UTC, KimJ15 approved these changes

2024-11-20 13:39 UTC, KianNH requested changes
Awesome work, the styling is perfect! This looks great.

I found a few small issues which are hopefully quick fixes.

2024-11-20 13:39 UTC, KianNH commented on src/pages/products.astro
> -		const groups = params.get("product-group");
It looks like we're missing this functionality now - we rely on it on the homepage using links like `/products/?product-group=Developer+platform`

2024-11-20 13:39 UTC, KianNH commented on src/components/index.ts
> -export { default as ThreeCardGrid } from "./ThreeCardGrid.astro";
Can we delete the component file itself too? I think the products grid was the only usage of it.

2024-11-20 13:39 UTC, KianNH commented on src/pages/products.astro
> +	<ProductCatalog products={products} client:load />
CI is failing due to a type error on `products` here: https://github.com/cloudflare/cloudflare-docs/actions/runs/11820899830/job/32934322983?pr=18133#step:6:46

2024-11-21 10:49 UTC, hturan commented on src/pages/products.astro
> -		const groups = params.get("product-group");
Ah, sorry! Totally missed this, my bad. I'll add it via stetting initial state in React.

2024-11-21 11:04 UTC, hturan commented on src/pages/products.astro
> +	<ProductCatalog products={products} client:load />
Thanks! I've made a more specific `ProductData` type for the `ProductCatalog` (including icons and groups).

2024-11-21 14:29 UTC, KianNH approved these changes
❤️

2024-11-21 14:29 UTC, merged