[Web Analytics] Migrating Browser Insights content + updating how-tos for UI changes
cloudflare/cloudflare-docs pull request #1832
Opened 2021-07-20 20:27 UTC by crwaters16

2021-07-20 20:36 UTC, crwaters16 commented on products/analytics/src/content/web-analytics/about/index.md
> +Web Analytics only reports data from 10% of page loads. If Cloudflare has handled fewer than 10 page loads, we likely won't have metrics to report. Check back after more users have visited your websi
Still accurate?

2021-07-20 20:36 UTC, crwaters16 commented on products/analytics/src/content/web-analytics/getting-started/index.md
>  1. Wait for the redirect to the Web Analytics page or click **View Analytics**. It may take a few minutes for Web Analytics data to appear.
Does this redirect still happen?

2021-07-20 20:36 UTC, crwaters16 commented on products/analytics/src/content/web-analytics/about/index.md
> +Web Analytics only reports data from 10% of page loads. If Cloudflare has handled fewer than 10 page loads, we likely will not have metrics to report. Check back after more users have visited your we
10% reporting still accurate?

2021-07-20 20:37 UTC, crwaters16 commented on products/analytics/src/content/web-analytics/understanding-web-analytics/index.md
> -View your website’s page views, visits, [page load time](/web-analytics/understanding-web-analytics/page-load-time-summary/), and [Core Web Vitals](/web-analytics/understanding-web-analytics/core-web
Removed the content that's included in navigation (view page views/visits/page load time/core vitals) and moved the info about data being RUM to the About page.

2021-07-20 22:16 UTC, youngrumtest requested changes
added some comments, let me know if you have any other questions.

2021-07-20 22:16 UTC, cf-ypark commented on products/analytics/src/content/web-analytics/about/index.md
> +Web Analytics only reports data from 10% of page loads. If Cloudflare has handled fewer than 10 page loads, we likely will not have metrics to report. Check back after more users have visited your we
This statement is no longer valid (it's 100% now) however, we do use ABR instead of sampling, so for higher traffic, they might see that their analytics data is from sampled ABR. @thepmer @jeehoon-cf do you guys think it's worth mentioning ABR here?

2021-07-20 22:16 UTC, youngrumtest commented on products/analytics/src/content/web-analytics/about/index.md
> +Note: Web Analytics now includes the functionality formerly enabled through Browser Insights.
👍

2021-07-20 22:16 UTC, youngrumtest commented on products/analytics/src/content/web-analytics/configuring-web-analytics/rules/index.md
> +Use **Rules** to configure whether to track Web Analytics for specific websites or paths.
should we mention whether if rules are not configured, the JS Snippet (=beacon js) will be injected for all existing websites under the zone?

2021-07-20 22:16 UTC, youngrumtest commented on products/analytics/src/content/web-analytics/getting-started/index.md
> +1. Enter your website’s hostname. Automatic setup is enabled by default.
This should be `Automatic setup is enabled by default if the hostname selected is from the existing Cloudflare website`. Since for grey clouded domain, automatic setup is not enabled by default and the customer needs to install JS snippet manually.

2021-07-20 22:16 UTC, youngrumtest commented on products/analytics/src/content/web-analytics/getting-started/index.md
>  1. Wait for the redirect to the Web Analytics page or click **View Analytics**. It may take a few minutes for Web Analytics data to appear.
yes it does.

2021-07-20 22:16 UTC, youngrumtest commented on products/analytics/src/content/web-analytics/getting-started/index.md
> +Repeat steps 4-6 for all of the websites you want to track with Web Analytics. For more information on how many sites you can track, refer to [Limits](../understanding-web-analytics/limits/).
i think `For more information on how many sites you can track` should be changed to `For more information on how many rules you can have`

2021-07-20 22:16 UTC, youngrumtest commented on products/analytics/src/content/web-analytics/getting-started/index.md
> +3. Enter your website’s hostname. Automatic setup is enabled by default.
please see the other comment made on this. Same text should be applied.

2021-07-20 22:16 UTC, youngrumtest commented on products/analytics/src/content/web-analytics/getting-started/index.md
> +5. Wait for the redirect to the Web Analytics page or click **View Analytics**. It may take a few minutes for Web Analytics data to appear.
This step applies only if this is the first site the user is registering. Once they registered a site, adding a site would go through a regular flow (not the onboarding flow)

2021-07-20 22:16 UTC, youngrumtest commented on products/analytics/src/content/web-analytics/getting-started/index.md
> +## Advanced options
This `advanced options` are available only if the selected hostname is orange clouded. Maybe we should have `(Only if proxied through Cloudflare)` something like this.

2021-07-20 22:16 UTC, youngrumtest commented on products/analytics/src/content/web-analytics/understanding-web-analytics/data-origin-and-collection/index.md
> +Web Analytics does not insert the beacon on every page load. Instead, it inserts a beacon in a random sample of web pages and uses the information collected to estimate your web pages’ traffic and pe
This sentence is no longer valid.

2021-07-20 22:16 UTC, youngrumtest commented on products/analytics/src/content/web-analytics/understanding-web-analytics/data-origin-and-collection/index.md
> +Beacon data is sent back to `https://<yourdomainname>/cdn-cgi/beacon/performance`. Core Web Vital metrics are reported when the `visibilityState` is hidden for the first time after the page load even
Beacon data is sent back to `https://<yourdomainname>/cdn-cgi/rum` if the domain is proxied through Cloudflare, otherwise it is sent back to `https://cloudflareinsights.com/cdn-cgi/rum`.

2021-07-20 22:16 UTC, youngrumtest commented on products/analytics/src/content/web-analytics/understanding-web-analytics/index.md
> -View your website’s page views, visits, [page load time](/web-analytics/understanding-web-analytics/page-load-time-summary/), and [Core Web Vitals](/web-analytics/understanding-web-analytics/core-web
👍

2021-07-21 17:43 UTC, jeehoon-cf commented on products/analytics/src/content/web-analytics/about/index.md
> +Web Analytics only reports data from 10% of page loads. If Cloudflare has handled fewer than 10 page loads, we likely will not have metrics to report. Check back after more users have visited your we
I don't think it's a bad idea to briefly mention ABR, since we get questions about it (even though it's not that frequent).
If you think adding this is proper, feel free to update/polish the following:
"Web Analytics support ABR, an appropriate resolution will be chosen on each chart/table depending on the size of the data, date range, and other factors. More details can be found at https://blog.cloudflare.com/explaining-cloudflares-abr-analytics/"

2021-07-21 21:07 UTC, crwaters16 commented on products/analytics/src/content/web-analytics/getting-started/index.md
> +## Advanced options
@youngrumtest, what does a grey-clouded user see then, since they have to manually install the JS snippet to enable WA? No "Advanced options" and just the JS snippet?

2021-07-21 21:09 UTC, crwaters16 commented on products/analytics/src/content/web-analytics/getting-started/index.md
> +Repeat steps 4-6 for all of the websites you want to track with Web Analytics. For more information on how many sites you can track, refer to [Limits](../understanding-web-analytics/limits/).
I'd like to leave this as "sites" because in this context we're talking about tracking WA for websites and not how to configure rules

2021-07-21 21:17 UTC, youngrumtest commented on products/analytics/src/content/web-analytics/getting-started/index.md
> +## Advanced options
correct. No `Advanced Options` but just the snippet.

2021-07-21 21:17 UTC, crwaters16 commented on products/analytics/src/content/web-analytics/understanding-web-analytics/limits/index.md
> +| Proxied through Cloudflare                     | No limit           | No limit           |
@youngrumtest / @thepmer, can we change this to only display the soft limit or the hard limit? From a user's perspective it's not really clear what the distinction is (feels a little like internal documentation seeping into our external docs)

2021-07-21 21:18 UTC, youngrumtest commented on products/analytics/src/content/web-analytics/getting-started/index.md
> +Repeat steps 4-6 for all of the websites you want to track with Web Analytics. For more information on how many sites you can track, refer to [Limits](../understanding-web-analytics/limits/).
ahh.. got it. i misunderstood.

2021-07-21 21:19 UTC, youngrumtest commented on products/analytics/src/content/web-analytics/understanding-web-analytics/limits/index.md
> +| Proxied through Cloudflare                     | No limit           | No limit           |
we should remove the hard limit and keep to soft limit. we don't need to mention `soft limit` but just `limit`.

2021-07-21 22:26 UTC, youngrumtest requested changes

2021-07-21 22:26 UTC, youngrumtest commented on products/analytics/src/content/web-analytics/about/index.md
> +The data displayed in Web Analytics is real user monitoring (RUM). For more information, refer to [What is Real-User Monitoring?](https://smartbear.com/learn/performance-monitoring/what-is-real-user-
wasn't aware of this link. Is this okay? @thepmer 
maybe we should use a link from Wikipedia? https://en.wikipedia.org/wiki/Real_user_monitoring

2021-07-22 21:42 UTC, crwaters16 commented on products/analytics/src/content/web-analytics/about/index.md
> +The data displayed in Web Analytics is real user monitoring (RUM). For more information, refer to [Real User Monitoring](https://en.wikipedia.org/wiki/Real_user_monitoring).
We usually try to avoid linking to wikipedia, but all of the other links I can find are descriptions from companies that also offer analytics products.

2021-07-22 22:03 UTC, youngrumtest approved these changes
LGTM!

2021-07-22 22:16 UTC, jeehoon-cf commented on products/analytics/src/content/web-analytics/about/index.md
> +The data displayed in Web Analytics is real user monitoring (RUM). For more information, refer to [Real User Monitoring](https://en.wikipedia.org/wiki/Real_user_monitoring).
I understand try avoiding wikipedia links, but it's not good to have competitors' page here as well. It would be best if we have an post/article in Cloudflare blog for RUM.

2021-07-22 22:16 UTC, jeehoon-cf approved these changes

2021-07-27 18:35 UTC, deadlypants1973 approved these changes

2021-07-27 18:35 UTC, deadlypants1973 commented on products/analytics/src/content/web-analytics/configuring-web-analytics/rules/index.md
> +Use **Rules** to configure whether to track Web Analytics for specific websites or paths. If you do not configure any rules, Web Analytics injects the JS snippet for all sites.
```suggestion
Use **Rules** to configure whether to track Web Analytics for specific websites or paths. If you do not configure any rules, Web Analytics injects the JavaScript (JS) snippet for all sites.
```

2021-07-27 18:35 UTC, deadlypants1973 commented on products/analytics/src/content/web-analytics/configuring-web-analytics/rules/index.md
> +1. From **Quick Actions**, click View Web Analytics sites.
```suggestion
1. From **Quick Actions**, click **View Web Analytics sites**.
```

Does this need a bold?

2021-07-27 18:35 UTC, deadlypants1973 commented on products/analytics/src/content/web-analytics/configuring-web-analytics/rules/index.md
> +4. Select the Action and fill in the Host name and Path(s) you want to add a rule for.
```suggestion
4. Select the **Action** and fill in the Host name and Path(s) you want to add a rule for.
```
Does this need a bold?

2021-07-27 18:52 UTC, merged