[D1] Cleaning up Build with D1
cloudflare/cloudflare-docs pull request #18321
Opened 2024-11-21 14:14 UTC by Oxyjun

### Summary

1. Moved "Error" and "Error list" section out of "Query D1", and into Observability/Debug D1/.
2. Added a redirect for "Query D1" into "Workers Binding API".
3.  TBC

### Screenshots (optional)

### Documentation checklist

- [ ] The [documentation style guide](https://developers.cloudflare.com/style-guide/) has been adhered to.
- [ ] If a larger change - such as adding a new page- an issue has been opened in relation to any incorrect or out of date information that this PR fixes.
- [ ] Files which have changed name or location have been allocated [redirects](https://developers.cloudflare.com/pages/configuration/redirects/#per-file).

2024-11-22 19:14 UTC, daisyfaithauma approved these changes

2024-11-22 19:18 UTC, daisyfaithauma requested changes

2024-11-22 19:18 UTC, daisyfaithauma commented on public/_redirects
I think one of these redirects if failing the builds

2024-11-25 14:02 UTC, marciocloudflare approved these changes

2024-12-05 17:22 UTC, vy-ton requested changes
![image](https://github.com/user-attachments/assets/4f203cb8-3cff-4f92-bb12-d2e016c2ab7c)
 
- Can we put `Remote development` under `local development`
- I want to rename `Build with D1` to `Best practices`

2024-12-05 17:22 UTC, vy-ton commented on src/content/docs/d1/build-with-d1/query-d1.mdx
> +title: Query D1
Let's call this `Query database`

2024-12-05 17:22 UTC, vy-ton commented on src/content/docs/d1/build-with-d1/import-export-data.mdx
> +From here, you can now query our new table from our Worker [using the D1 Workers Binding API](/d1/worker-api/).
`Foreign key constraints` section should go under import or troubleshooting heading - it's a bit lost in the current structure

2024-12-05 17:22 UTC, vy-ton commented on src/content/docs/d1/rest-api/index.mdx
> +title: REST API
Should be `CLI & REST API` if we're putting wrangler here

2024-12-05 17:22 UTC, vy-ton commented on src/content/docs/d1/build-with-d1/query-d1.mdx
> +## Query D1 with SQL API
This content should be under section above on `Workers Binding API`.

2024-12-05 17:22 UTC, vy-ton commented on src/content/docs/d1/build-with-d1/query-d1.mdx
> +3. Using [D1 Wrangler commands](/d1/rest-api/wrangler-commands/).
Given we list 3 ways, I would expect to see a wrangler section below

2024-12-05 17:22 UTC, vy-ton commented on src/content/docs/d1/build-with-d1/query-d1.mdx
> +There are three primary ways you can query a D1 database:
I would want to see more examples in a best practices/intro guide rather than just navigation to reference sections. To start, at least aim for 1 example per section. If we want to defer to the next PR, that's ok

In examples, we should be using a consistent schema

2024-12-05 17:33 UTC, vy-ton commented on src/content/docs/d1/observability/debug-d1.mdx
> +### Errors
I'm ok moving this content to a Reference section but we should think about what a Troubleshooting best practice section should look like

2024-12-05 17:33 UTC, vy-ton commented on src/content/docs/d1/build-with-d1/query-d1.mdx
> +There are three primary ways you can query a D1 database:
`foreign key constraints` and `query json` should be material we fold best practices in here, then deeper content goes into the `SQL API`

2024-12-05 18:05 UTC, Oxyjun commented on src/content/docs/d1/rest-api/index.mdx
> +title: REST API
Agreed offline to separate these - have been actioned.

2024-12-06 10:31 UTC, Oxyjun commented on src/content/docs/d1/observability/debug-d1.mdx
> +### Errors
I think this will be a separate PR - we'll want to overhaul error documentation (we have internal tickets for this)

2024-12-06 17:51 UTC, vy-ton commented on src/content/docs/d1/build-with-d1/query-d1.mdx
> +There are three primary ways you can query a D1 database:
> foreign key constraints and query json should be material we fold best practices in here, then deeper content goes into the SQL API

@Oxyjun foreign keys and json querying are "how to do this in SQL" topics, which is why they are best introduced here but then further detailed content, like https://developers.cloudflare.com/d1/build-with-d1/foreign-keys/#foreign-key-actions, should be in the SQL reference

2024-12-06 18:28 UTC, vy-ton approved these changes
![image](https://github.com/user-attachments/assets/57b9921a-6811-4b94-af92-306e4b84c3ef)

- For `Rest` and `Wrangler` we should remove the D1 in the section title

2024-12-06 18:28 UTC, vy-ton commented on src/content/docs/d1/best-practices/query-d1.mdx
> +npx wrangler d1 execute prod-d1-tutorial --local --command="SELECT * FROM Customers"
This should be the example for the `with Wrangler commands` section, it doesn't use the SQL API

2024-12-06 18:28 UTC, vy-ton commented on src/content/docs/d1/best-practices/query-d1.mdx
> +D1 is compatible with most SQLite's SQL convention since it leverages SQLite's query engine.
Can we put this info in the intro paragraph? SQL API doesnt make sense at its own section equal to workers binding, rest, and wrangler

2024-12-09 10:02 UTC, Oxyjun commented on src/content/docs/d1/best-practices/query-d1.mdx
> +npx wrangler d1 execute prod-d1-tutorial --local --command="SELECT * FROM Customers"
Then what's an example that uses SQL API? All of the examples in the SQL statement section are run through the REST API (Wrangler).

2024-12-09 10:09 UTC, Oxyjun commented on src/content/docs/d1/best-practices/query-d1.mdx
> +D1 is compatible with most SQLite's SQL convention since it leverages SQLite's query engine.
I was trying to copy the structure of the sidebar, which now looks like this after the latest round of changes:

<img width="364" alt="image" src="https://github.com/user-attachments/assets/3d4be5dc-07ea-4a1c-9ac3-f87a4075dcbd">

Would you prefer it if we removed "Query D1 with SQL API" entirely from this chapter?

2024-12-09 14:52 UTC, vy-ton commented on src/content/docs/d1/best-practices/query-d1.mdx
> +D1 is compatible with most SQLite's SQL convention since it leverages SQLite's query engine.
"Query D1 with SQL API" would be the section that we highlight SQL best practices (what I mentioned about eventually folding in foreign keys, json, etc). If right now, the section just mentions SQLite compatibility then I would leave out and mention the SQLite compatibility in the initial overview (important for users to know what SQL semantics D1 supports).

2024-12-09 14:53 UTC, vy-ton commented on src/content/docs/d1/best-practices/query-d1.mdx
> +npx wrangler d1 execute prod-d1-tutorial --local --command="SELECT * FROM Customers"
I view SQL API as a more specific term for Workers Binding API

2024-12-09 14:53 UTC, vy-ton commented on src/content/docs/d1/best-practices/query-d1.mdx
> +D1 is compatible with most SQLite's SQL convention since it leverages SQLite's query engine.
> I was trying to copy the structure of the sidebar, which now looks like this after the latest round of changes:
> 
> <img alt="image" width="364" src="https://private-user-images.githubusercontent.com/177844691/393791179-3d4be5dc-07ea-4a1c-9ac3-f87a4075dcbd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3NTU5NzEsIm5iZiI6MTczMzc1NTY3MSwicGF0aCI6Ii8xNzc4NDQ2OTEvMzkzNzkxMTc5LTNkNGJlNWRjLTA3ZWEtNGExYy05YWMzLWY4N2E0MDc1ZGNiZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwOVQxNDQ3NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MDMyOWVkNWJiZWU4YmIxMDFiNTM4OTA0MTBmOTQ4Yzk4OTA5NTYwODhmYmNmZWYzMjA0OTM0NWNiNDFlNDY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.CNSY0FRYzJNf4hotZMnT_nbXCZZWxcOWsMqD84BSCJs">

For Rest and Wrangler we should remove the D1 in the section title

2024-12-11 09:43 UTC, daisyfaithauma approved these changes

2024-12-11 09:43 UTC, merged