First Blog Draft
cloudflare/cloudflare-docs pull request #18384
Opened 2024-11-25 13:11 UTC by mohdlatif

# Add Dynamic OG Image Generation Tutorial

### Summary

This PR adds a new tutorial that guides users through creating a dynamic Open Graph (OG) image generator using Cloudflare Workers. The tutorial covers:

- Setting up a Cloudflare Worker with TypeScript and React
- Implementing dynamic image generation using @vercel/og
- Configuring font loading strategies
- Adding caching mechanisms
- Deploying the solution

The tutorial aims to help developers leverage Cloudflare's edge network for fast, scalable social media image generation.

### Screenshots

![Style 1 Preview](https://img.playbook.com/NCDQskLa2E1MMJl7Ba8294ROlGUH_XGjvj6Rh53IGIs/Z3M6Ly9wbGF5Ym9v/ay1hc3NldHMtcHVi/bGljLzkzMGMzMjYw/LWM4ZjUtNGRlYS1i/MWFkLWNmZTg5ZDBm/Y2E1MQ)

### Documentation checklist

- [x] The [documentation style guide](https://developers.cloudflare.com/style-guide/) has been adhered to
- [x] Content has been reviewed for technical accuracy
- [x] Code examples have been tested and verified
- [x] All images include appropriate alt text
- [x] Links have been verified and are working

2024-11-27 13:10 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/Generate Dynamic OG Images using Cloudflare Workers/index.mdx
> +If you haven't installed Wrangler yet, you can do so using any of these package managers:
`C3` Installs the latest version of Wrangler locally to that project when created. We try to avoid recommending users to globally install Wrangler now as it can add complexity when working with multiple projects that require different versions of Wrangler. You can remove this note and it shouldn't affect project setup.

2024-11-29 12:19 UTC, db-cloudflare reviewed
Left some more style guide suggestions. Once the technical review has been completed by a second reviewer this PR should be ready to merge. Great work!

2024-11-29 12:19 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/Generate Dynamic OG Images using Cloudflare Workers/index.mdx
> +## Before you begin
```suggestion
## Prerequisites
```

2024-11-29 12:19 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/Generate Dynamic OG Images using Cloudflare Workers/index.mdx
> +
```suggestion
<Render file="prereqs" product="workers" />

3. [Bun](https://bun.sh/) installed on your machine.
4. Basic familiarity with TypeScript and React.
5. A text editor or IDE of your choice.

```

2024-11-29 12:19 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/Generate Dynamic OG Images using Cloudflare Workers/index.mdx
> +What you'll accomplish:
```suggestion
By completing this tutorial you will create an application that can:
```

2024-11-29 12:19 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/Generate Dynamic OG Images using Cloudflare Workers/index.mdx
> +By the end, you'll have a robust solution to enhance your social media presence.
```suggestion
By the end, you will have a robust solution to enhance your social media presence.
```

2024-11-29 12:19 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/Generate Dynamic OG Images using Cloudflare Workers/index.mdx
> +By leveraging Cloudflare Workers, you get a serverless edge-computing environment that's not only cost-efficient but also perfectly optimized for modern web applications.
```suggestion
By leveraging Cloudflare Workers, you get a serverless edge-computing environment that is not only cost-efficient but also perfectly optimized for modern web applications.
```

2024-11-29 12:19 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/Generate Dynamic OG Images using Cloudflare Workers/index.mdx
> +Here's how the process flows:
```suggestion
Here is how the process flows:
```

2024-11-29 12:19 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/Generate Dynamic OG Images using Cloudflare Workers/index.mdx
> +The `nodejs_compat_v2` flag enables runtime compatibility features required by the OG image generation library, even when using Bun. While we're using Bun as our development runtime, this flag ensure
```suggestion
The `nodejs_compat_v2` flag enables runtime compatibility features required by the OG image generation library, even when using Bun. While using Bun as our development runtime, this flag ensures all necessary APIs are available in the Workers environment. The `assets` configuration maps your Worker's public directory, allowing direct access to static files like fonts, images, and favicons through URL paths (for example, `/fonts/Inter.ttf`, `/images/logo.png`).
```

2024-11-29 12:19 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/Generate Dynamic OG Images using Cloudflare Workers/index.mdx
> +If no style parameter is provided or an invalid value is used, the generator defaults to Style1. Here's how to use each style:
```suggestion
If no style parameter is provided or an invalid value is used, the generator defaults to Style1. Here is how to use each style:
```

2024-11-29 12:19 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/Generate Dynamic OG Images using Cloudflare Workers/index.mdx
> +Here's how to implement caching with customizable durations:
```suggestion
Add the following code to implement caching with customizable durations:
```

2024-11-29 12:19 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/Generate Dynamic OG Images using Cloudflare Workers/index.mdx
> +Let's create our type definitions to ensure smooth TypeScript integration. Create a new file `src/type.d.ts`:
```suggestion
Create a new file `src/type.d.ts`, then add the following code to the new file to create type definitions to ensure smooth TypeScript integration:
```

2024-11-29 12:19 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/Generate Dynamic OG Images using Cloudflare Workers/index.mdx
> +With these definitions in place, you'll get full TypeScript support and autocompletion throughout your project. This makes development smoother and helps catch potential issues early.
```suggestion
With these definitions in place, you will get full TypeScript support and autocompletion throughout your project. This makes development smoother and helps catch potential issues early.
```

2024-11-29 12:19 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/Generate Dynamic OG Images using Cloudflare Workers/index.mdx
> +Congratulations! You've successfully harnessed the power of Cloudflare Workers to build a dynamic OG image generator. By leveraging the global edge network and serverless architecture, your applicati
```suggestion
Congratulations! You have successfully harnessed the power of Cloudflare Workers to build a dynamic OG image generator. By leveraging the global edge network and serverless architecture, your application now delivers high-performance visuals with ease. Whether you are scaling for millions of users or iterating on design tweaks, Cloudflare Workers ensure your images are always fast, reliable, and stunning.
```

2024-11-29 12:19 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/Generate Dynamic OG Images using Cloudflare Workers/index.mdx
> +- [Cloudflare Workers documentation](https://developers.cloudflare.com/workers/)
```suggestion
- [Cloudflare Workers documentation](/workers/)
```

2024-11-29 12:19 UTC, db-cloudflare commented on src/content/docs/workers/tutorials/Generate Dynamic OG Images using Cloudflare Workers/index.mdx
> +- [Cloudflare page plugin vercel/og](https://developers.cloudflare.com/pages/functions/plugins/vercel-og/)
```suggestion
- [Cloudflare page plugin vercel/og](/pages/functions/plugins/vercel-og/)
```

2024-11-29 16:21 UTC, pedrosousa commented on src/content/docs/workers/tutorials/Generate Dynamic OG Images using Cloudflare Workers/index.mdx
Please update the name of the folder you're adding so that it's in lowercase and uses dashes (hyphens) instead of spaces. You can omit some of the words in the title.

For example:

`src/content/docs/workers/tutorials/generate-dynamic-og-images-using-workers/index.mdx`

instead of:

`src/content/docs/workers/tutorials/Generate Dynamic OG Images using Cloudflare Workers/index.mdx`

2024-12-10 17:10 UTC, craigsdennis commented on src/content/docs/workers/tutorials/generate-dynamic-og-images-using-workers/index.mdx
> +      // "@cloudflare/workers-types", // Cloudflare Workers API types
Should we remove the commented out bits here?

2024-12-16 06:52 UTC, mohdlatif commented
Sorry, but what is the status on this ?

2024-12-18 22:09 UTC, dcpena requested changes

2024-12-18 22:09 UTC, dcpena commented on src/content/docs/workers/tutorials/generate-dynamic-og-images-using-workers/index.mdx
> +    - Customize visuals with flexible fonts and design options..
```suggestion
    - Customize visuals with flexible fonts and design options.
```

2024-12-18 22:09 UTC, dcpena commented on src/content/docs/workers/tutorials/generate-dynamic-og-images-using-workers/index.mdx
> +Building OG image generators can be challenging, especially when it comes to ensuring global performance, scalability, and speed. This is where Cloudflare Workers excel:
```suggestion
Building OG image generators can be challenging, especially when it comes to ensuring global performance, scalability, and speed. This is where Cloudflare Workers excel.
```

2024-12-18 22:09 UTC, dcpena commented on src/content/docs/workers/tutorials/generate-dynamic-og-images-using-workers/index.mdx
> +3. [Bun](https://bun.sh/) installed on your machine.
```suggestion
3. Install [Bun](https://bun.sh/) on your machine.
```

2024-12-18 22:09 UTC, dcpena commented on src/content/docs/workers/tutorials/generate-dynamic-og-images-using-workers/index.mdx
> +- **Edge Computing**: Generates images at the edge using Cloudflare Workers
```suggestion
- **Edge computing**: Generates images at the edge using Cloudflare Workers
```

2024-12-18 22:09 UTC, dcpena commented on src/content/docs/workers/tutorials/generate-dynamic-og-images-using-workers/index.mdx
> +- **Modern Rendering**: Utilizes Vercel's Satori library for high-quality image generation
```suggestion
- **Modern rendering**: Utilizes Vercel's Satori library for high-quality image generation
```

2024-12-18 22:09 UTC, dcpena commented on src/content/docs/workers/tutorials/generate-dynamic-og-images-using-workers/index.mdx
> +- **Flexible Styling**: Supports both Tailwind CSS and inline styles
```suggestion
- **Flexible styling**: Supports both Tailwind CSS and inline styles
```

2024-12-18 22:09 UTC, dcpena commented on src/content/docs/workers/tutorials/generate-dynamic-og-images-using-workers/index.mdx
> +- **Font Versatility**: Multiple font loading strategies for different use cases
```suggestion
- **Font versatility**: Multiple font loading strategies for different use cases
```

2024-12-18 22:09 UTC, dcpena commented on src/content/docs/workers/tutorials/generate-dynamic-og-images-using-workers/index.mdx
> +- **Performance Optimized**: Built-in caching and optimization
```suggestion
- **Performance optimized**: Built-in caching and optimization
```

2024-12-18 22:09 UTC, dcpena commented on src/content/docs/workers/tutorials/generate-dynamic-og-images-using-workers/index.mdx
> +- **Developer Friendly**: TypeScript support and modular architecture
```suggestion
- **Developer friendly**: TypeScript support and modular architecture
```

2024-12-18 22:09 UTC, dcpena commented on src/content/docs/workers/tutorials/generate-dynamic-og-images-using-workers/index.mdx
> +First, create a new Cloudflare Workers project using the Hono framework:
```suggestion
Create a new Cloudflare Workers project using the Hono framework:
```

2024-12-18 22:09 UTC, dcpena commented on src/content/docs/workers/tutorials/generate-dynamic-og-images-using-workers/index.mdx
> +   - Best for: Popular web fonts with dynamic text
```suggestion
   - Best for popular web fonts with dynamic text
```

2024-12-18 22:09 UTC, dcpena commented on src/content/docs/workers/tutorials/generate-dynamic-og-images-using-workers/index.mdx
> +   - Best for: Stable, version-controlled fonts
```suggestion
   - Best for stable, version-controlled fonts
```

2024-12-18 22:09 UTC, dcpena commented on src/content/docs/workers/tutorials/generate-dynamic-og-images-using-workers/index.mdx
> +   - Best for: Self-hosted or third-party fonts
```suggestion
   - Best for self-hosted or third-party fonts
```

2024-12-18 22:09 UTC, dcpena commented on src/content/docs/workers/tutorials/generate-dynamic-og-images-using-workers/index.mdx
> +   - Best for: Custom or licensed fonts
```suggestion
   - Best for custom or licensed fonts
```

2024-12-18 22:09 UTC, dcpena commented on src/content/docs/workers/tutorials/generate-dynamic-og-images-using-workers/index.mdx
> +First, create a `fonts` directory inside your `public` folder to store any local font files:
```suggestion
Create a `fonts` directory inside your `public` folder to store any local font files:
```

2024-12-18 22:09 UTC, dcpena commented on src/content/docs/workers/tutorials/generate-dynamic-og-images-using-workers/index.mdx
> +The OG image generator includes 4 distinct styles that can be selected via the `style` query parameter. The style selection is handled through a simple query parameter in the URL:
```suggestion
The OG image generator includes four distinct styles that can be selected via the `style` query parameter. The style selection is handled through a simple query parameter in the URL:
```

2024-12-18 22:09 UTC, dcpena commented on src/content/docs/workers/tutorials/generate-dynamic-og-images-using-workers/index.mdx
> +If no style parameter is provided or an invalid value is used, the generator defaults to Style1. Here's how to use each style:
```suggestion
If no style parameter is provided or an invalid value is used, the generator defaults to Style 1. Here's how to use each style:
```

2024-12-18 22:09 UTC, dcpena commented on src/content/docs/workers/tutorials/generate-dynamic-og-images-using-workers/index.mdx
> +These type definitions are crucial for our project:
```suggestion
These type definitions are crucial for our project because they:
```

2024-12-18 22:09 UTC, dcpena commented on src/content/docs/workers/tutorials/generate-dynamic-og-images-using-workers/index.mdx
> +- They enable TypeScript to understand Cloudflare's cache storage
```suggestion
- Enable TypeScript to understand Cloudflare's cache storage
```

2024-12-18 22:09 UTC, dcpena commented on src/content/docs/workers/tutorials/generate-dynamic-og-images-using-workers/index.mdx
> +Generate OG images by making GET requests:
```suggestion
Generate OG images by making `GET` requests:
```

2024-12-19 00:38 UTC, mohdlatif commented
@dcpena Amazing work. Thank you

2024-12-19 10:08 UTC, pedrosousa commented on src/content/docs/workers/tutorials/generate-dynamic-og-images-using-workers/index.mdx
> +# Generate Dynamic OG Images using Cloudflare Workers
```suggestion
import { PackageManagers, Render } from "~/components";
```
No need for the H1 here; the H1 text comes from `title` in the frontmatter.
Also, we need to import the `PackageManagers` and `Render` components used below.

2024-12-19 10:09 UTC, pedrosousa commented on src/content/docs/workers/tutorials/generate-dynamic-og-images-using-workers/index.mdx
> +What you'll accomplish:
```suggestion
What you will accomplish:
```
According to our style guide, we should [avoid using contractions](https://developers.cloudflare.com/style-guide/grammar/parts-of-speech/contractions/).

2024-12-19 10:09 UTC, pedrosousa commented on src/content/docs/workers/tutorials/generate-dynamic-og-images-using-workers/index.mdx
> +By the end, you'll have a robust solution to enhance your social media presence.
```suggestion
By the end, you will have a robust solution to enhance your social media presence.
```

2024-12-19 10:09 UTC, pedrosousa commented on src/content/docs/workers/tutorials/generate-dynamic-og-images-using-workers/index.mdx
> +By leveraging Cloudflare Workers, you get a serverless edge-computing environment that's not only cost-efficient but also perfectly optimized for modern web applications.
```suggestion
By leveraging Cloudflare Workers, you get a serverless edge-computing environment that is not only cost-efficient but also perfectly optimized for modern web applications.
```

2024-12-19 10:10 UTC, pedrosousa commented on src/content/docs/workers/tutorials/generate-dynamic-og-images-using-workers/index.mdx
> +Here's how the process flows:
```suggestion
Here is how the process flows:
```

2024-12-19 10:15 UTC, pedrosousa commented on src/content/docs/workers/tutorials/generate-dynamic-og-images-using-workers/index.mdx
> +---
```suggestion
```json title="tsconfig.json"
```
Since we migrated to Starlight there's a [different syntax](https://developers.cloudflare.com/style-guide/components/code/) for specifying a code block title or a filename.

2024-12-19 10:16 UTC, pedrosousa commented on src/content/docs/workers/tutorials/generate-dynamic-og-images-using-workers/index.mdx
> +
```suggestion
```typescript title="src/getFonts.ts"
```

2024-12-19 10:16 UTC, pedrosousa commented on src/content/docs/workers/tutorials/generate-dynamic-og-images-using-workers/index.mdx
> +
```suggestion
```typescript title="src/loadImage.ts"
```

2024-12-19 10:17 UTC, pedrosousa commented on src/content/docs/workers/tutorials/generate-dynamic-og-images-using-workers/index.mdx
> +
```suggestion
```typescript title="src/og.tsx"
```

2024-12-19 10:19 UTC, pedrosousa commented on src/content/docs/workers/tutorials/generate-dynamic-og-images-using-workers/index.mdx
> +```url
```suggestion
```txt
```
`url` is not a supported language. Use `txt` instead.

2024-12-19 10:19 UTC, pedrosousa commented on src/content/docs/workers/tutorials/generate-dynamic-og-images-using-workers/index.mdx
> +```url
```suggestion
```txt
```

2024-12-19 10:20 UTC, pedrosousa commented on src/content/docs/workers/tutorials/generate-dynamic-og-images-using-workers/index.mdx
> +```url
```suggestion
```txt
```

2024-12-19 10:20 UTC, pedrosousa commented on src/content/docs/workers/tutorials/generate-dynamic-og-images-using-workers/index.mdx
> +
```suggestion
```typescript title="src/index.ts"
```

2024-12-19 10:21 UTC, pedrosousa commented on src/content/docs/workers/tutorials/generate-dynamic-og-images-using-workers/index.mdx
> +
```suggestion
```typescript title="src/og.tsx"
```

2024-12-19 10:21 UTC, pedrosousa commented on src/content/docs/workers/tutorials/generate-dynamic-og-images-using-workers/index.mdx
> +
```suggestion
```typescript title="src/index.ts"
```

2024-12-19 10:22 UTC, pedrosousa commented on src/content/docs/workers/tutorials/generate-dynamic-og-images-using-workers/index.mdx
> +
```suggestion
```typescript title="src/type.d.ts"
```

2024-12-19 10:23 UTC, pedrosousa commented on src/content/docs/workers/tutorials/generate-dynamic-og-images-using-workers/index.mdx
> +```url
```suggestion
```txt
```

2024-12-19 10:24 UTC, mohdlatif commented on src/content/docs/workers/tutorials/Generate Dynamic OG Images using Cloudflare Workers/index.mdx
> +3. [Bun](https://bun.sh/) installed on your machine.
Shouldn't this start from 1 instead of 3 ?

2024-12-19 10:24 UTC, mohdlatif commented on src/content/docs/workers/tutorials/Generate Dynamic OG Images using Cloudflare Workers/index.mdx
Done

2024-12-19 10:24 UTC, mohdlatif commented on src/content/docs/workers/tutorials/generate-dynamic-og-images-using-workers/index.mdx
> +      // "@cloudflare/workers-types", // Cloudflare Workers API types
Comments removed

2024-12-19 10:26 UTC, pedrosousa commented on src/content/docs/workers/tutorials/generate-dynamic-og-images-using-workers/index.mdx
> +---
Tip: To accept suggestions, use the **Commit suggestion** or **Add suggestion to batch** buttons near each suggestion. Resolving a conversation will _not_ incorporate those changes in your PR, which means you will have to make those changes yourself.

2024-12-19 15:25 UTC, dcpena commented on src/content/docs/workers/tutorials/generate-dynamic-og-images-using-workers/index.mdx
> +---
Hi Pedro! 😁  I'm going to mark this as resolved because I applied the edits we needed to address before merging.

2024-12-19 15:28 UTC, dcpena approved these changes

2024-12-19 16:32 UTC, pedrosousa approved these changes

2024-12-19 16:35 UTC, merged