Update WebSocket examples
cloudflare/cloudflare-docs pull request #18535
Opened 2024-12-03 16:22 UTC by harshil1712

### Summary

Updates the WebSocket and WebSocket Hibernation examples.

2024-12-03 16:44 UTC, Oxyjun approved these changes

2025-08-04 14:59 UTC, Oxyjun commented
Closes https://github.com/cloudflare/cloudflare-docs/issues/24141

2025-08-06 14:11 UTC, lambrospetrou commented on src/content/docs/durable-objects/examples/websocket-hibernation-server.mdx
> +      if (ws.deserializeAttachment()) {
This seems wrong?

2025-08-06 14:12 UTC, lambrospetrou commented on src/content/docs/durable-objects/examples/websocket-hibernation-server.mdx
> +        this.sessions.set(ws, { ...session });
Why the spreading and then recollecting? Just pass `attachment` or if you only want its properties spread that directly.

```suggestion
        this.sessions.set(ws, { ...attachment });
```

2025-08-06 14:13 UTC, lambrospetrou commented on src/content/docs/durable-objects/examples/websocket-hibernation-server.mdx
> +    });
Combine these two loops?

2025-08-06 14:14 UTC, lambrospetrou commented on src/content/docs/durable-objects/examples/websocket-server.mdx
> +});
Formatting indentation is messed up here, and below.

2025-08-06 14:14 UTC, lambrospetrou commented on src/content/docs/durable-objects/examples/websocket-server.mdx
> +    	});
Merge the loops.

2025-08-06 14:14 UTC, joshthoward commented on src/content/docs/durable-objects/examples/websocket-hibernation-server.mdx
> -			return stub.fetch(request);
Other than removing the extra stub.fetch, what's the diff here?

2025-08-06 14:16 UTC, joshthoward commented on src/content/docs/durable-objects/examples/websocket-hibernation-server.mdx
> +			return stub.fetch(request);
Please fix this. It seems to worsen a subsequent diff by a lot.

2025-08-06 14:19 UTC, joshthoward requested changes
@harshil1712 `git rebase -i production` is your friend. There are a lot of changes here which are unsubstantiated, e.g. large changes which only adjust indentation, and inconsistent, e.g. changing ```` to ``` in some cases. Please clean up this PR so that it can be reviewed properly.

2025-08-06 14:21 UTC, joshthoward commented
> @harshil1712 `git rebase -i production` is your friend. There are a lot of changes here which are unsubstantiated, e.g. large changes which only adjust indentation, and inconsistent, e.g. changing ```` to ``` in some cases. Please clean up this PR so that it can be reviewed properly.

Oh sorry @harshil1712... @Oxyjun contributed the later commits. The advice still stands... Please clean up this PR so that it can be reviewed properly.

2025-08-07 09:24 UTC, harshil1712 commented on src/content/docs/durable-objects/examples/websocket-hibernation-server.mdx
> +    });
The loops are kept separate to make it easy for users to simply copy-paste based on their use-case.

2025-08-07 09:40 UTC, Oxyjun commented
We're now tracking this here: https://github.com/cloudflare/cloudflare-docs/pull/24234

2025-08-07 09:50 UTC, closed without merging