[ZT] WARP Intune Android instructions
cloudflare/cloudflare-docs pull request #18545
Opened 2024-12-03 20:26 UTC by ranbel

Recreates https://github.com/cloudflare/cloudflare-docs/pull/15961
PCX-11381

2024-12-04 00:03 UTC, j-bibodi requested changes

2024-12-04 00:03 UTC, j-bibodi commented on src/content/docs/cloudflare-one/connections/connect-devices/warp/deployment/mdm-deployment/partners/intune.mdx
> +
We can remove this extra line.

2024-12-04 00:03 UTC, j-bibodi commented on src/content/docs/cloudflare-one/connections/connect-devices/warp/deployment/mdm-deployment/partners/intune.mdx
> +    ```
I would like to add `display_name` along with `organization` in this json example because those 2 are the required params in the multi-org format. Otherwise, the config is ignored. Also, it would be good to give example with two configs instead of one.

JSON structure would look something like below:

```
{
    "kind": "androidenterprise#managedConfiguration",
    "productId": "app:com.cloudflare.cloudflareoneagent",
    "managedProperty": [
        {
            "key": "app_config_bundle_list",
            "valueBundleArray": [
                {
                    "managedProperty": [
                        {
                            "key": "organization",
                            "valueString": "your-team-name"
                        },
                        {
                            "key": "display_name",
                            "valueString": "unique display-name for config 1"
                        },
                        {
                            "key": "service_mode",
                            "valueString": "warp"
                        },
                        {
                            "key": "onboarding",
                            "valueBool": false
                        },
                        {
                            "key": "support_url",
                            "valueString": "https://support.example.com/"
                        }
                    ]
                },
                {
                    "managedProperty": [
                        {
                            "key": "organization",
                            "valueString": "your-team-name"
                        },
                        {
                            "key": "display_name",
                            "valueString": "unique display-name for config 2"
                        }
                    ]
                }
            ]
        }
    ]
}
```

2024-12-04 17:17 UTC, ranbel commented on src/content/docs/cloudflare-one/connections/connect-devices/warp/deployment/mdm-deployment/partners/intune.mdx
> +        "kind": "androidenterprise#managedConfiguration",
@j-bibodi is it ok to change this JSON formatting to 2-space indents?

2024-12-05 17:47 UTC, j-bibodi commented on src/content/docs/cloudflare-one/connections/connect-devices/warp/deployment/mdm-deployment/partners/intune.mdx
> +        "kind": "androidenterprise#managedConfiguration",
I don't think spacing matters here in the json structure. So, yes, it is ok to change the JSON formatting to 2-space indents.

2024-12-05 17:49 UTC, j-bibodi approved these changes
LGTM

2024-12-05 21:38 UTC, patriciasantaana approved these changes

2024-12-05 21:38 UTC, patriciasantaana commented on src/content/docs/cloudflare-one/connections/connect-devices/warp/deployment/mdm-deployment/partners/intune.mdx
> +    Alternatively, if you do not want to copy/paste the JSON data, you can change **Configuration settings format** to _Use configuration designer_ and manually configure each deployment parameter.
```suggestion
    Alternatively, if you do not want to copy and paste the JSON data, you can change **Configuration settings format** to _Use configuration designer_ and manually configure each deployment parameter.
```

2024-12-05 21:50 UTC, merged