Added notes for cache request hostnames
cloudflare/cloudflare-docs pull request #18634
Opened 2024-12-09 17:37 UTC by ToriLindsay

Added notes - Do not use dynamic or invalid hostnames in cache requests. This can cause DNS cache failures and latency.

2024-12-09 17:42 UTC, Oxyjun approved these changes

2024-12-09 17:44 UTC, mikenomitch commented on src/content/docs/workers/runtime-apis/cache.mdx
> +Do not use dynamic or invalid hostnames in cache requests. This can cause DNS cache failures and latency.
I think we should be more explicit. We should say that the hostname used in the cache request should match your hostname.

And then instead of "DNS cache failures" I'd say "a DNS lookup" which will significantly increase latency.

2024-12-09 17:48 UTC, mikenomitch commented on src/content/docs/workers/runtime-apis/cache.mdx
> +Do not use dynamic or invalid hostnames in cache requests. This can cause DNS cache failures and latency.
I think if they use "request.headers.host" that'd be the correct hostname to use in all cases? I could be wrong about this though

2024-12-10 06:27 UTC, irvinebroque requested changes
Needs more context — show vs. just tell

2024-12-13 15:09 UTC, ToriLindsay commented on src/content/docs/workers/runtime-apis/cache.mdx
> +Do not use dynamic or invalid hostnames in cache requests. This can cause DNS cache failures and latency.
```suggestion
To avoid unnecessary DNS lookups and cache inefficiencies, do not override the hostname in cache requests. Always use the hostname that matches the domain associated with your Worker.
```

2024-12-13 15:09 UTC, ToriLindsay commented on src/content/docs/workers/runtime-apis/cache.mdx
> +Do not use dynamic or invalid hostnames in cache requests. This can cause DNS cache failures and latency.
```suggestion
To avoid unnecessary DNS lookups and cache inefficiencies, do not override the hostname in cache requests. Always use the hostname that matches the domain associated with your Worker.
```

2024-12-13 15:15 UTC, ToriLindsay commented
@mikenomitch @irvinebroque Thank you for the feedback! I updated the note with the details from Mike. An example could also be included if you think that's necessary to show it more explicitly? Let me know your thoughts.

2025-01-07 16:10 UTC, irvinebroque reviewed
Same feedback as previously — show vs. tell

2025-02-04 16:38 UTC, mikenomitch commented on src/content/docs/workers/runtime-apis/cache.mdx
> +async fetch(request, env, ctx) {
Indentation on this JS is a bit off. Everything within the brackets should be indented once.

Though actually, this also isn't valid fetch code. You would need to `return` the response from `myCache.match(request)` in order for it to be valid.

But... that doesn't really make sense because you might have a cache miss and you'd have to handle that (see this full code - https://developers.cloudflare.com/workers/examples/cache-api/)

I think since we don't want to show all of that code in here, what we should do is just drop the fetch() bits completely? It might be a tad less clear where `request` is coming from in this case, but I think it's fine.

So I'd just do 

```
// avoid overriding the URL in request or passing a new request into the cache API
request.url = "https://some-overridden-value.com/";

let myCache = await caches.open('custom:cache');
let response = await myCache.match(request);
```

If it'll never work then I'd add this above the last line "// will never work because URL doesn't match Worker's domain"

2025-02-04 16:38 UTC, mikenomitch commented on src/content/docs/workers/runtime-apis/cache.mdx
> +When using the cache API, avoid overriding the hostname in cache requests, as this can lead to unnecessary DNS lookups and cache inefficiencies. Always use the hostname that matches the domain associ
Should we wrap this all in `:::note`?

2025-02-26 15:45 UTC, mikenomitch approved these changes
Looks good!

2025-03-05 17:46 UTC, ToriLindsay commented
@irvinebroque Ready for your re-review. I believe I need your approval as well for this to be unblocked. Thank you!

2025-03-20 01:41 UTC, irvinebroque reviewed
Seems like we should suggest what people _should_ do instead?

2025-03-20 01:41 UTC, irvinebroque commented on src/content/docs/workers/runtime-apis/cache.mdx
> +// avoid overriding the URL in request or passing a new request into the cache API
```suggestion
// Do not do this
```

it was ambiguous when i read this what was meant by the comment — assume it's trying to tell people not to do this

2025-03-31 14:39 UTC, ToriLindsay commented
> Seems like we should suggest what people _should_ do instead?

@irvinebroque Makes sense. I updated it again. Ready for your review when you have a chance. Thank you!

2025-04-21 14:26 UTC, irvinebroque approved these changes

2025-04-22 14:46 UTC, merged