Update account owned tokens
cloudflare/cloudflare-docs pull request #18684
Opened 2024-12-11 16:53 UTC by jhutchings1

### Summary
👋🏻  I made some quick updates to the account owned tokens page to reflect: 
1. Update description to reflect GA status
2. Add procedural instructions
3. Sort the compatibility matrix alphabetically

One piece that I wasn't sure how to do properly was link to an API that's only documented in the beta docs site (at least I couldn't find it on the regular site). @crwaters16 not sure if you have thoughts on the best way to do that. 

### Screenshots (optional)

### Documentation checklist

- [x] The [documentation style guide](https://developers.cloudflare.com/style-guide/) has been adhered to.
- [ ] If a larger change - such as adding a new page- an issue has been opened in relation to any incorrect or out of date information that this PR fixes.
- [ ] Files which have changed name or location have been allocated [redirects](https://developers.cloudflare.com/pages/configuration/redirects/#per-file).

2024-12-11 22:40 UTC, patriciasantaana commented on src/content/partials/fundamentals/account-owned-tokens.mdx
> +While user tokens act on behalf of a particular user, and inherit a subset of that user's permissions, account owned tokens allow you to set up durable integrations that can act as service principals
```suggestion
While user tokens act on behalf of a particular user and inherit a subset of that user's permissions, account owned tokens allow you to set up durable integrations that can act as service principals with their own specific set of permissions. This approach is ideal for scenarios like CI/CD, or building integrations with external services like SEIMs where it is important that the integration continues working, even long after the user who configured the integration may have left your organization altogether. User tokens are better for ad hoc tasks like scripting, where acting as the user is ideal and durability is less of a concern. 
```

2024-12-11 22:40 UTC, patriciasantaana commented on src/content/partials/fundamentals/account-owned-tokens.mdx
> +## Creating an account owned token
```suggestion
## Create an account owned token
```

2024-12-11 22:41 UTC, patriciasantaana commented on src/content/partials/fundamentals/account-owned-tokens.mdx
> +Creating an account owned token requires Super Administrator permission on the account
```suggestion
The Super Administrator permission is required to create an account owned token on your account.
```

2024-12-11 22:53 UTC, patriciasantaana commented on src/content/partials/fundamentals/account-owned-tokens.mdx
> +6. Review the details, and finally click **Create Token**
These revised steps are based off of the flow that I can currently see on my dashboard -- are there upcoming updates that I'm not seeing that cause for the slight differences in labels or steps? @jhutchings1 

```suggestion
1. Log into the [Cloudflare dashboard](https://dash.cloudflare.com).
2. Go to **My Profile** >  **API Tokens**.
4. Select **Create Token** and **Create custom token**.
5. Fill in the token name, permissions, and the optional expiration date for the token. 
6. Select **Continue to summary** and review the details.
7. Select **Create Token**.
```

2024-12-11 22:54 UTC, patriciasantaana commented on src/content/partials/fundamentals/account-owned-tokens.mdx
> +You can alternatively create a token using the [account owned token creation API](/api-next/resources/accounts/subresources/tokens/methods/create/).
```suggestion
Alternatively, you can create a token using the [account owned token creation API](/api-next/resources/accounts/subresources/tokens/methods/create/).
```

2024-12-11 22:54 UTC, patriciasantaana commented on src/content/partials/fundamentals/account-owned-tokens.mdx
> +Account owned tokens are generally available in all accounts. Some services may not support account owned tokens yet. Please see the compatibility matrix below for the latest status.
```suggestion
Account owned tokens are generally available for all accounts. Some services may not support account owned tokens yet. Refer to the compatibility matrix below for the latest status. 
```

2024-12-11 22:54 UTC, patriciasantaana commented on src/content/partials/fundamentals/account-owned-tokens.mdx
> +| :---- | :---- |
```suggestion
| --- | --- |
```

2024-12-11 22:56 UTC, patriciasantaana requested changes
Left a few comments! @jhutchings1

2024-12-11 23:56 UTC, jhutchings1 commented on src/content/partials/fundamentals/account-owned-tokens.mdx
> +Creating an account owned token requires Super Administrator permission on the account
@patriciasantaana isn't this one passive voice? (I had a former boss that was a content editor, so it's been beaten into me to avoid it)

2024-12-12 00:02 UTC, jhutchings1 commented on src/content/partials/fundamentals/account-owned-tokens.mdx
> +6. Review the details, and finally click **Create Token**
> 2. Go to **My Profile** > **API Tokens**.

That is the correct flow for user tokens, but the entry point is different for account owned tokens, matching what I described earlier. You have to be a Super Admin of the account to see this. Let me know if you want me to invite you to an account to see it if you can't.

2024-12-12 00:03 UTC, jhutchings1 commented on src/content/partials/fundamentals/account-owned-tokens.mdx
> +You can alternatively create a token using the [account owned token creation API](/api-next/resources/accounts/subresources/tokens/methods/create/).
Does it work for you if it's fully qualified? The linter complained at me for having the full URL, but this content is part of a microsite that's not part of the repo. This loads on my end. https://developers.cloudflare.com/api-next/resources/accounts/subresources/subscriptions/methods/delete/

2024-12-12 16:42 UTC, patriciasantaana commented on src/content/partials/fundamentals/account-owned-tokens.mdx
> +Creating an account owned token requires Super Administrator permission on the account
I think I was mainly avoiding starting the sentence with a verb. Totally get what you mean to avoid passive voice though

2024-12-12 16:47 UTC, patriciasantaana commented on src/content/partials/fundamentals/account-owned-tokens.mdx
> +6. Review the details, and finally click **Create Token**
@jhutchings1 revised the wording to fit the steps you initially had. Let me know if I missed something!

2024-12-12 16:58 UTC, crwaters16 commented
Good q @jhutchings1 - if it's appearing in vNext but not on the existing site, that's a bug to the existing site. We're doing the site cutover on Monday, so the easiest path forward is to omit the link to that endpoint for now and add it in on Monday/Tuesday. Using the fully qualified link to the /api-next/ in the interim should also work, though.

2024-12-12 17:04 UTC, jhutchings1 commented
> Good q @jhutchings1 - if it's appearing in vNext but not on the existing site, that's a bug to the existing site. We're doing the site cutover on Monday, so the easiest path forward is to omit the link to that endpoint for now and add it in on Monday/Tuesday. Using the fully qualified link to the /api-next/ in the interim should also work, though.

We can sit on this PR until next week if it makes life easier.

2024-12-16 23:16 UTC, patriciasantaana commented on src/content/partials/fundamentals/account-owned-tokens.mdx
> +Alternatively, you can create a token using the [account owned token creation API](/api-next/resources/accounts/subresources/tokens/methods/create/).
```suggestion
Alternatively, you can create a token using the [account owned token creation API](/api/resources/accounts/subresources/tokens/methods/create/).
```

2024-12-17 17:08 UTC, jhutchings1 commented
@patriciasantaana We should be good to go with this one now that the API docs changes have shipped. Do you want to rereview?

2024-12-17 19:39 UTC, patriciasantaana approved these changes

2024-12-17 21:47 UTC, merged