Add miniflare docs
cloudflare/cloudflare-docs pull request #18690
Opened 2024-12-11 18:13 UTC by penalosa

Adds the contents of https://miniflare.dev/, with non-relevant sections removed/modified. There are two commits—one with a full import of the content, and one with sections removed.

2024-12-17 15:02 UTC, CarmenPopoviciu commented on src/content/docs/workers/miniflare/get-started/index.md
> ----
instead of removing this whole page, let's perhaps keep it in a more condensed form, and keep stuff that is relevant to miniflare 3, and remove all the miniflare 2 specific bits 🙏

2024-12-17 15:03 UTC, CarmenPopoviciu commented on src/content/docs/workers/miniflare/index.mdx
> -<LinkButton variant="primary" href="/workers/get-started/guide/">
if we keep the get started page, we'll prolly wanna keep the btn as well :)

2024-12-17 15:03 UTC, CarmenPopoviciu commented on src/content/docs/workers/miniflare/migrations/from-v2.mdx
> +title: ⬆️Migrating from Version 2
re-add the space here

2024-12-17 15:05 UTC, CarmenPopoviciu commented on src/content/docs/workers/miniflare/migrations/from-v2.mdx
> -[Getting Started guide for the new API docs](/get-started).
we should add this get started link back

2024-12-17 16:36 UTC, CarmenPopoviciu approved these changes
Thank you so much @penalosa for working on this ♥️ . This is awesome!!

2024-12-17 17:31 UTC, irvinebroque requested changes
Should not be top-level in dev docs:
<img width="356" alt="Screenshot 2024-12-17 at 9 28 30 AM" src="https://github.com/user-attachments/assets/5090cd33-582e-4540-90b9-d46aadb98ab8" />

And certainly not above other content that is currently below it.

Suggestion would be:

- The content itself is part of `/workers/testing` — we already talk about Miniflare [here](https://penalosa-miniflare-docs.cloudflare-docs-7ou.pages.dev/workers/testing/).
- It should be linked to from [`/workers/wrangler/api`](https://penalosa-miniflare-docs.cloudflare-docs-7ou.pages.dev/workers/wrangler/api/)

Docs for Miniflare lead with:

<img width="735" alt="Screenshot 2024-12-17 at 9 30 36 AM" src="https://github.com/user-attachments/assets/108ea521-0443-4b69-b95b-b345c9e49377" />

Things in the left-hand nav of Workers docs should be things that in the base case, people building Workers need to interact with and understand.

2024-12-17 23:24 UTC, penalosa commented
@irvinebroque I've moved it to the testing folder. I'm a bit hesitant to link to it from Wrangler's API page though, since for most users it won't provide what they want from an API (especially for a Wrangler user, since it won't read their Wrangler config file). What do you think?

2024-12-18 05:54 UTC, irvinebroque commented
@penalosa I'm good with that

2024-12-18 05:54 UTC, irvinebroque approved these changes

2024-12-18 09:59 UTC, ToriLindsay approved these changes

2024-12-18 14:53 UTC, nevikashah approved these changes

2024-12-18 20:15 UTC, merged