JeffH - Updated Sphinx Framework Guide
cloudflare/cloudflare-docs pull request #1876
Opened 2021-07-26 23:33 UTC by jeffh-cloudflare

This request is in support of the following issues that I submitted:

https://github.com/cloudflare/cloudflare-docs/issues/1443
https://github.com/cloudflare/cloudflare-docs/issues/1444

Updated to ensure the Python 3.7 requirement is more noticeable, additional detail on the installation and usage of pipenv, improved examples of using git, added a table for the environment variables, and various other minor enhancements.

The git examples should be usable for other framework guides.

2021-07-27 03:47 UTC, sabir010110 commented
i should be awaited were you do so. therefor you also disputed their on merging blocks.

2021-07-27 12:10 UTC, deadlypants1973 requested changes
Style guide and format review

2021-07-27 12:10 UTC, deadlypants1973 commented on products/pages/src/content/framework-guides/deploy-a-sphinx-site.md
> +***NOTE: If you are already running a version of Python 3.7, please ensure that Python version 3.7 is also installed on your computer before you begin as this is the latest version at the time of wri
```suggestion
<Aside type="note">

If you are already running a version of Python 3.7, ensure that Python version 3.7 is also installed on your computer before you begin this guide. Python 3.7 is the latest version supported by Cloudflare Pages.
 
</Aside>

```

2021-07-27 12:10 UTC, deadlypants1973 commented on products/pages/src/content/framework-guides/deploy-a-sphinx-site.md
> +The latest version of Python 3.7 (at the time this was written) is 3.7.11:
```suggestion
The latest version of Python 3.7 is 3.7.11:
```

2021-07-27 12:10 UTC, deadlypants1973 commented on products/pages/src/content/framework-guides/deploy-a-sphinx-site.md
> +Please refer to the official Python docs on installing for your platform at their relevant pages:
```suggestion
Refer to the official Python documentation for installation guidance:
```

2021-07-27 12:10 UTC, deadlypants1973 commented on products/pages/src/content/framework-guides/deploy-a-sphinx-site.md
> +Wonderful, by now you should have Python installed. If you already had Python installed, please be mindful that any other global packages you may have installed could interfere with the following ste
```suggestion
If you already had an earlier version of Python installed before installing version 3.7, other global packages you may have installed could interfere with the following steps to install Pipenv, or your other Python projects which depend on global packages.
```

2021-07-27 12:10 UTC, deadlypants1973 commented on products/pages/src/content/framework-guides/deploy-a-sphinx-site.md
> +[Pipenv](https://pipenv.pypa.io/en/latest/) is a Python based package manager that makes managing virtual environments super simple. If you're not familiar with it yet, don't worry, it's easy to pick
```suggestion
[Pipenv](https://pipenv.pypa.io/en/latest/) is a Python-based package manager that makes managing virtual environments simple. This guide will not require you to have prior experience with or knowledge of Pipenv to complete your Sphinx site deployment. Cloudflare Pages natively supports the use of Pipenv and, by default, has the latest version installed.
```

2021-07-27 12:10 UTC, deadlypants1973 commented on products/pages/src/content/framework-guides/deploy-a-sphinx-site.md
>  In this guide you'll create a new Sphinx project and deploy it using Cloudflare Pages.
```suggestion
In this guide, you will create a new Sphinx project and deploy it using Cloudflare Pages.
```

2021-07-27 12:10 UTC, deadlypants1973 commented on products/pages/src/content/framework-guides/deploy-a-sphinx-site.md
> +[Sphinx](https://www.sphinx-doc.org/) is a tool that makes it easy to create beautiful documentation, originally created for Python documentation. It has found favour among many for its simplicity an
```suggestion
[Sphinx](https://www.sphinx-doc.org/) is a tool that makes it easy to create documentation and was originally made for the publication of Python documentation. It is well known for its simplicity and ease of use.
```

2021-07-27 12:10 UTC, deadlypants1973 commented on products/pages/src/content/framework-guides/deploy-a-sphinx-site.md
> +This will install Pipenv to your user level directory and will make it accessible via your terminal. You can confirm this by running the following command and seeing the expected output:
```suggestion
This command will install Pipenv to your user level directory and will make it accessible via your terminal. You can confirm this by running the following command and reviewing the expected output:
```

2021-07-27 12:10 UTC, deadlypants1973 commented on products/pages/src/content/framework-guides/deploy-a-sphinx-site.md
> +### Create Sphinx Project Directory
```suggestion
### Creating a Sphinx project directory
```

2021-07-27 12:10 UTC, deadlypants1973 commented on products/pages/src/content/framework-guides/deploy-a-sphinx-site.md
> +From your terminal run the following commands to create a new directory and navigate within it:
```suggestion
From your terminal, run the following commands to create a new directory and navigate to it:
```

2021-07-27 12:10 UTC, deadlypants1973 commented on products/pages/src/content/framework-guides/deploy-a-sphinx-site.md
> +Pipenv allows you to specify which version of Python to associate with a virtual environment. As was mentioned earlier, we need to ensure the virtual environment for your Sphinx project uses Python 3
```suggestion
Pipenv allows you to specify which version of Python to associate with a virtual environment. For the purpose of this guide, the virtual environment for your Sphinx project must use Python 3.7.
```

2021-07-27 12:10 UTC, deadlypants1973 commented on products/pages/src/content/framework-guides/deploy-a-sphinx-site.md
> +Just one last step before can install Sphinx, we first have to create the directory we want our project to live in.
```suggestion
Before installing Sphinx, create the directory you want your project to live in.
```

2021-07-27 12:10 UTC, deadlypants1973 commented on products/pages/src/content/framework-guides/deploy-a-sphinx-site.md
>  We're finally ready to install Sphinx. From your terminal run the following command to install Sphinx:
```suggestion
From your terminal, run the following command to install Sphinx:
```

2021-07-27 12:10 UTC, deadlypants1973 commented on products/pages/src/content/framework-guides/deploy-a-sphinx-site.md
> +This will install sphinx into a new virtual environment managed by Pipenv, you should see a directory structure like this:
```suggestion
This will install Sphinx into a new virtual environment managed by Pipenv. You should see a directory structure like this:
```

2021-07-27 12:10 UTC, deadlypants1973 commented on products/pages/src/content/framework-guides/deploy-a-sphinx-site.md
> +With Sphinx installed you can now run the quickstart command to create a template project for you. This command will only work within the Pipenv environment we created in the previous step. To enter
```suggestion
With Sphinx installed, you can now run the quickstart command to create a template project for you. This command will only work within the Pipenv environment you created in the previous step. To enter that environment, run the following command from your terminal:
```

2021-07-27 12:10 UTC, deadlypants1973 commented on products/pages/src/content/framework-guides/deploy-a-sphinx-site.md
> +You now have everything you need to start deploying your site to Cloudflare Pages. For learning how to create beautiful documentation with Sphinx please see the official docs [here](https://www.sphin
```suggestion
You now have everything you need to start deploying your site to Cloudflare Pages. For learning how to create documentation with Sphinx, refer to the official [Sphinx documentation](https://www.sphinx-doc.org/en/master/usage/quickstart.html).
```

2021-07-27 12:10 UTC, deadlypants1973 commented on products/pages/src/content/framework-guides/deploy-a-sphinx-site.md
> +Create a new GitHub repository by visiting [repo.new](https://repo.new). Once you've created a new repository, you can push your local application to GitHub:
```suggestion
Create a new GitHub repository by visiting [repo.new](https://repo.new). After creating a new repository, push your local application to GitHub:
```

2021-07-27 12:10 UTC, deadlypants1973 commented on products/pages/src/content/framework-guides/deploy-a-sphinx-site.md
> +You can deploy your site to Cloudflare Pages by going to the dashboard, and creating a new site. Select your new GitHub repository that you created above, and in the configuration section, provide th
```suggestion
You can deploy your site to Cloudflare Pages by going to the Account Home > Pages > **Create a project**. Select your new GitHub repository that you created above, and in the configuration section, provide the following information:
```

2021-07-27 12:10 UTC, deadlypants1973 commented on products/pages/src/content/framework-guides/deploy-a-sphinx-site.md
> +Once you've configured your site, you can begin your first deploy. You should see Cloudflare Pages installing `Pipenv`, your project dependencies, and building your site, before deploying it.
```suggestion
After configuring your site, you can begin your first deploy. You should see Cloudflare Pages installing `Pipenv`, your project dependencies, and building your site, before deployment.
```

2021-07-27 12:10 UTC, deadlypants1973 commented on products/pages/src/content/framework-guides/deploy-a-sphinx-site.md
> +For the complete guide to deploying your first site to Cloudflare Pages, check out our [Getting Started guide](/getting-started).
```suggestion
For the complete guide to deploying your first site to Cloudflare Pages, refer to the [Get started guide](/getting-started).
```

2021-07-27 12:10 UTC, deadlypants1973 commented on products/pages/src/content/framework-guides/deploy-a-sphinx-site.md
> +Once you've deployed your site, you'll receive a unique subdomain for your project on `pages.dev`. Every time you commit new code to your Hugo site, Cloudflare Pages will automatically rebuild your p
```suggestion
After deploying your site, you will receive a unique subdomain for your project on `pages.dev`. Every time you commit new code to your Sphinx site, Cloudflare Pages will automatically rebuild your project and deploy it.
```

2021-07-27 12:10 UTC, deadlypants1973 commented on products/pages/src/content/framework-guides/deploy-a-sphinx-site.md
> +You'll also get access to [preview deployments](/platform/preview-deployments) on new pull requests, so you can preview how changes look to your site before deploying them to production.
```suggestion
You will also get access to [preview deployments](/platform/preview-deployments) on new pull requests and you will be able to preview how changes look to your site before deploying them to production.
```

2021-07-27 12:10 UTC, deadlypants1973 commented on products/pages/src/content/framework-guides/deploy-a-sphinx-site.md
> +Congrats, you've deployed your Sphinx site on Cloudflare Pages! To learn more about what you can do with the platform, check out our [How-To section](/how-to).
```suggestion
By completing this guide, you have successfully deployed your Sphinx site on Cloudflare Pages. To learn more about what you can do with the platform, refer to the [How-To section](/how-to).
```

2021-07-27 17:26 UTC, signalnerve commented on products/pages/src/content/framework-guides/deploy-a-sphinx-site.md
> +~my-wonderful-new-sphinx-project$
this is `tree`-style output, shouldn't need the prompt syntax here
```suggestion
my-wonderful-new-sphinx-project
```

2021-07-27 17:26 UTC, signalnerve commented on products/pages/src/content/framework-guides/deploy-a-sphinx-site.md
> +~/my-wonderful-new-sphinx-project$
```suggestion
my-wonderful-new-sphinx-project
```

2021-08-04 15:32 UTC, jeffh-cloudflare commented on products/pages/src/content/framework-guides/deploy-a-sphinx-site.md
> +***NOTE: If you are already running a version of Python 3.7, please ensure that Python version 3.7 is also installed on your computer before you begin as this is the latest version at the time of wri
In your suggested change, did the "pipenv" link above the "aside" get removed? It's hard to tell with this example.

2021-08-04 15:33 UTC, jeffh-cloudflare commented on products/pages/src/content/framework-guides/deploy-a-sphinx-site.md
> +The latest version of Python 3.7 (at the time this was written) is 3.7.11:
This is fine - I just need to figure out how to merge your suggestion

2021-08-04 15:34 UTC, jeffh-cloudflare commented on products/pages/src/content/framework-guides/deploy-a-sphinx-site.md
> +Please refer to the official Python docs on installing for your platform at their relevant pages:
Most of this content was written before I picked it up. I was tempted to clean up quite a bit more but did not want to offend whoever wrote it previously.

2021-08-04 15:35 UTC, jeffh-cloudflare commented on products/pages/src/content/framework-guides/deploy-a-sphinx-site.md
> +Wonderful, by now you should have Python installed. If you already had Python installed, please be mindful that any other global packages you may have installed could interfere with the following ste
As stated in my last comment, most of this content was written before I picked it up. I was tempted to clean up quite a bit more but did not want to offend whoever wrote it previously. I will take another pass and clean up the grammar.

2021-08-04 21:53 UTC, deadlypants1973 commented on products/pages/src/content/framework-guides/deploy-a-sphinx-site.md
> +***NOTE: If you are already running a version of Python 3.7, please ensure that Python version 3.7 is also installed on your computer before you begin as this is the latest version at the time of wri
@jeffh-cloudflare no, it did not :) I just changed the **note** to an aside instead to conform with docs style guide.

2021-08-04 21:56 UTC, deadlypants1973 commented on products/pages/src/content/framework-guides/deploy-a-sphinx-site.md
>  <Aside>
```suggestion
<Aside type="note">
```

2021-08-04 21:59 UTC, deadlypants1973 approved these changes

2021-08-04 22:00 UTC, merged

2021-08-05 20:51 UTC, jeffh-cloudflare commented on products/pages/src/content/framework-guides/deploy-a-sphinx-site.md
> +### Creating a Sphinx project directory
This is not a valid heading - the following steps are technically installing Sphinx with pipenv. The creation of the Sphinx directory comes in when you run sphinx-quickstart.

2021-08-09 15:50 UTC, jeffh-cloudflare reviewed
There's only one issue with the corrections - lines 51 (and the revision in line 58). The title of that section should be "Installing Sphinx" not "Creating a Sphinx Project Directory". The 'pipenv install sphinx' is the installation of the Python package. The 'sphinx-quickstart' section further down is where the Sphinx project directory gets created.

2021-08-09 21:29 UTC, jeffh-cloudflare reviewed
@signalnerve - I see this was already merged. I was unsure of what needed to be done. My apologies for not getting it done in a more timely fashion.

There was one section where the revised version was not accurate:
Line 51 was deleted: "Installing Sphinx"
Replaced with line 58: "Creating a Sphinx project directory"

The original "Installing Sphinx" is technically correct. The content that was on line 89 got pushed down to line 151 - that is technically where "Creating a Sphinx Project Directory" should have been used.

I can do another pull, then revise it and push the changes. It's a quick change.

2021-08-10 12:59 UTC, deadlypants1973 commented
> @signalnerve - I see this was already merged. I was unsure of what needed to be done. My apologies for not getting it done in a more timely fashion.
> 
> There was one section where the revised version was not accurate:
> Line 51 was deleted: "Installing Sphinx"
> Replaced with line 58: "Creating a Sphinx project directory"
> 
> The original "Installing Sphinx" is technically correct. The content that was on line 89 got pushed down to line 151 - that is technically where "Creating a Sphinx Project Directory" should have been used.
> 
> I can do another pull, then revise it and push the changes. It's a quick change.

Hi @jeffh-cloudflare , I opened a revised PR. https://github.com/cloudflare/cloudflare-docs/pull/2021 Can you please check when you have the time? :)