[Pages] Build configuration updates
cloudflare/cloudflare-docs pull request #1880
Opened 2021-07-27 14:05 UTC by deadlypants1973

2021-07-27 14:59 UTC, deadlypants1973 commented on products/pages/src/content/platform/framework-build-presets.md
> -# Build configuration
@signalnerve if I changed the name of this .md file, this means I need to update through little redirector, right?

2021-07-27 15:03 UTC, deadlypants1973 commented on products/pages/src/content/platform/framework-build-presets.md
> -# Build configuration
@lukeed can this be Framework build configuration or is that weird? I am trying to avoid little redirector lol

2021-07-27 15:46 UTC, signalnerve requested changes
I can't comment directly on the section of the file here, but it's worth mentioning that this build-configuration page has more information than just framework-specific config: environment variables are another part of that page as well. 

I'm -1 on these changes as it stands, we'll need to migrate the environment variables section to a new page, if we make this "Framework build presets".

2021-07-27 15:46 UTC, signalnerve commented on products/pages/src/content/platform/framework-build-presets.md
> -# Build configuration
you'll only need to make a redirect if you change the filename - here you have `build-configuration` -> `framework-build-presets`, so you'll need to set up a redirect.

2021-07-27 16:00 UTC, lukeed requested changes

2021-07-27 16:00 UTC, lukeed commented on products/pages/src/content/framework-guides/deploy-anything.md
> +Unlike many of our How-To guides, the build command and build directory for your site are going to be completely custom. If you do not need a build step, input  `exit 0` into the **Build command** fi
```suggestion
Unlike many of our How-To guides, the build command and build directory for your site are going to be completely custom. If you do not need a build step, input  `exit 0` into the **Build command** field.
```

Also, not always true – in the table above you have/left `youroutputdir` value, which could be totally valid.

2021-07-27 16:00 UTC, lukeed commented on products/pages/src/content/framework-guides/deploy-anything.md
> +For the complete guide to deploying your first site to Cloudflare Pages, refr to [the Get Started guide](/getting-started).
```suggestion
For the complete guide to deploying your first site to Cloudflare Pages, refer to [the Get Started guide](/getting-started).
```

2021-07-27 16:00 UTC, lukeed commented on products/pages/src/content/framework-guides/deploy-anything.md
> +For the complete guide to deploying your first site to Cloudflare Pages, refr to [the Get Started guide](/getting-started).
```suggestion
For the complete guide to deploying your first site to Cloudflare Pages, refr to [the Getting Started guide](/getting-started).
```

2021-07-27 16:00 UTC, lukeed commented on products/pages/src/content/getting-started/index.md
> +Our deployment dashboard provides a number of presets, which are pre-filling values for many common deployment scenarios. If you are unsure what the correct values are for this section, refer to our
```suggestion
Our deployment dashboard provides a number of framework-specific presets, which provide the default values for the selected framework. If you are unsure what the correct values are for this section, refer to our documentation on [build configuration](/platform/build-configuration). If you do not need a build step, you may input  `exit 0` into the **Build command** field.
```

2021-07-27 16:00 UTC, lukeed commented on products/pages/src/content/platform/framework-build-presets.md
> +# Framework build presets
```suggestion
# Framework presets
```

2021-07-27 16:00 UTC, lukeed commented on products/pages/src/content/platform/framework-build-presets.md
> +Below are some standard build commands and directories for popular frameworks and tools. If you are not using a framework, you may input `exit 0` into the **Build command** field and leave **Build ou
```suggestion
Below are some standard build commands and directories for popular frameworks and tools. If you are not using a framework, you may input `exit 0` into the **Build command** field.
```

2021-07-27 16:00 UTC, lukeed commented on products/pages/src/content/platform/framework-build-presets.md
> +If you want to set a specific version of a framework your Cloudflare Pages project is using, note that Pages will respect your package manager of choice during your build process. For example, if you
```suggestion
If you want to set a specific version of a framework your Cloudflare Pages project is using, note that Pages will respect your package manager of choice during your build process. For example, if you use Gatsby.js, your `package.json` should indicate a version of the `gatsby` npm package, which will be installed using `npm install` as your project builds on Cloudflare Pages.
```

npm never has capitalization. it's part of their branding guide

2021-07-27 18:15 UTC, lukeed commented on products/pages/src/content/getting-started/index.md
>  Depending on the framework, tool, or project you are deploying to Cloudflare Pages, you will need to specify the site's **build command** and **publish directory** to tell Cloudflare Pages how to dep
```suggestion
Depending on the framework, tool, or project you are deploying to Cloudflare Pages, you will need to specify the site's **build command** and **build output directory** to tell Cloudflare Pages how to deploy your site. The contents of this directory are uploaded to Cloudflare Pages as your website's contents.
```

2021-07-27 19:31 UTC, signalnerve approved these changes

2021-07-28 14:43 UTC, marciocloudflare approved these changes

2021-07-28 15:39 UTC, lukeed approved these changes

2021-07-28 16:07 UTC, merged