[Pages] How to specify root directory in get started
cloudflare/cloudflare-docs pull request #1882
Opened 2021-07-27 16:20 UTC by deadlypants1973

2021-07-27 17:27 UTC, signalnerve approved these changes

2021-07-27 17:54 UTC, deadlypants1973 commented on products/pages/src/content/getting-started/index.md
> +Cloudflare Pages will deploy files that are stored in the root of your Github repository. If your content files are stored in a folder of your repository, specify this path in the **Root directory (a
```suggestion
Cloudflare Pages begins by working from your repository's root directory. The entire build pipeline, including the installation steps, will begin from this location. If you would like to change this, specify a new root directory location through the **Root directory (advanced)** > **Path** field.
```

2021-07-27 18:14 UTC, lukeed approved these changes

2021-07-27 19:43 UTC, kodster28 requested changes

2021-07-27 19:43 UTC, kodster28 commented on products/pages/src/content/getting-started/index.md
> +![Root directory](root-directory.png)
You'll need to fix the image link.

2021-07-28 13:48 UTC, kodster28 approved these changes

2021-07-28 13:53 UTC, merged