[ZT] WARP changelog
cloudflare/cloudflare-docs pull request #18927
Opened 2024-12-23 22:30 UTC by ranbel

PCX-15144

2024-12-23 23:10 UTC, kokolocomotion1 requested changes
Hey I left just two small changes needed. otherwise good to go. thanks Ranbel!

2024-12-23 23:10 UTC, kokolocomotion1 commented on src/content/changelogs/warp.yaml
> +    title: WARP client for Windows (version 2024.11.688.1)
My bad, the version for the windows beta published 2024-12-13 is version 2024.12.326.1

2024-12-23 23:10 UTC, kokolocomotion1 commented on src/content/changelogs/warp.yaml
> +    title: Cloudflare One Agent for Android (version 2.3 (4616))
actually let's leave teh version description as just:  version 2.3

2024-12-23 23:38 UTC, ranbel commented on src/content/changelogs/warp.yaml
> +      A new GA release for the macOS WARP client is now available in the [App Center](https://install.appcenter.ms/orgs/cloudflare/apps/1.1.1.1-macos-1/distribution_groups/release). This release cont
@kokolocomotion1 should we keep the version # that is in parentheses? `(20241218.36)`

2024-12-23 23:38 UTC, ranbel commented on src/content/changelogs/warp.yaml
> +    title: Cloudflare One Agent for Android (version 2.3 (4616))
```suggestion
    title: Cloudflare One Agent for Android (version 2.3)
```

2024-12-23 23:39 UTC, ranbel commented on src/content/changelogs/warp.yaml
> +    title: WARP client for Windows (version 2024.11.688.1)
```suggestion
    title: WARP client for Windows (version 2024.12.326.1)
```

2024-12-24 05:58 UTC, kokolocomotion1 commented on src/content/changelogs/warp.yaml
> +      A new GA release for the macOS WARP client is now available in the [App Center](https://install.appcenter.ms/orgs/cloudflare/apps/1.1.1.1-macos-1/distribution_groups/release). This release cont
@ranbel let's not include it so we keep the same formatting as our past changelogs

2024-12-24 05:58 UTC, kokolocomotion1 approved these changes

2024-12-26 16:00 UTC, ranbel commented on src/content/changelogs/warp.yaml
> +      A new GA release for the macOS WARP client is now available in the [App Center](https://install.appcenter.ms/orgs/cloudflare/apps/1.1.1.1-macos-1/distribution_groups/release). This release cont
```suggestion
      A new GA release for the macOS WARP client is now available in the [App Center](https://install.appcenter.ms/orgs/cloudflare/apps/1.1.1.1-macos-1/distribution_groups/release). This release contains improvements to support custom Gateway certificate installation in addition to the changes and improvements included in version 2024.12.492.0.
```

2024-12-26 16:11 UTC, merged