Builds and It's Completely Different but Also Still Build
cloudflare/cloudflare-docs pull request #18955
Opened 2024-12-29 23:58 UTC by aninibread

### Summary

Revamp builds documentation for Workers and Pages. Focused on git ingtegration.

### Screenshots (optional)

### Documentation checklist

- [ ] The [documentation style guide](https://developers.cloudflare.com/style-guide/) has been adhered to.
- [ ] If a larger change - such as adding a new page- an issue has been opened in relation to any incorrect or out of date information that this PR fixes.
- [ ] Files which have changed name or location have been allocated [redirects](https://developers.cloudflare.com/pages/configuration/redirects/#per-file).

2024-12-30 15:57 UTC, Maximo-Guk commented on src/content/docs/pages/configuration/git-integration/github-integration.mdx
> +You can deploy projects to Cloudflare Workers from your open-source team, company, or side project on GitHub using the [Cloudflare Workers & Pages GitHub App](https://github.com/apps/cloudflare-worke
Does it make sense to specify "open-source" for team?

2024-12-30 16:10 UTC, Maximo-Guk commented on src/content/docs/pages/configuration/git-integration/github-integration.mdx
> +Note that removing access to GitHub will disable new builds for Workers and Pages project that were connected to those repositories, though the last build of your project will continue to be hosted v
Maybe this should be "your previous deployments will continue to be hosted" or something like that

2024-12-30 20:05 UTC, Maximo-Guk commented on src/content/docs/workers/ci-cd/builds/git-integration/github-integration.mdx
> +A GitHub account should only point to one Cloudflare account. If you are setting up Cloudflare with GitHub for your organization, Cloudflare recommends that you limit the scope of the application to
> build with Pages

Should probably be modified to be for workers builds

2024-12-30 20:10 UTC, Maximo-Guk commented on src/content/docs/workers/ci-cd/builds/git-integration/gitlab-integration.mdx
> +You can remove Cloudflare Workers' access to your GitLab account by navigating to [Authorized Applications page](https://gitlab.com/-/profile/applications) on GitLab. Find the applications called Clo
We should probably rename the Gitlab app to Cloudflare Workers and Pages yet to match GitHub app name at some point

2024-12-30 20:14 UTC, Maximo-Guk commented on src/content/docs/workers/ci-cd/builds/troubleshoot.mdx
> +If you are running into errors associated with your Git integration, you can try removing access to your GitHub or GitLab integration from Cloudflare, then reinstalling the Git integration.
Maybe we could add a docs link here on how to reinstall?

2024-12-31 06:11 UTC, irvinebroque approved these changes
👏 👏 👏 

ship it

2024-12-31 06:11 UTC, irvinebroque commented on src/content/docs/pages/configuration/build-caching.mdx
> +The first build to occur after enabling build caching on your Pages project will save to cache. Every subsequent build will restore from cache unless configured otherwise.
```suggestion
After you enable build caching on your Pages project, the first build that runs will populate the build cache. Each subsequent build will restore from cache unless otherwise configured.
```

"otherwise configured" == you purge cache?

2024-12-31 06:11 UTC, irvinebroque commented on src/content/docs/pages/configuration/build-caching.mdx
> +1. Navigate to [Workers & Pages Overview](https://dash.cloudflare.com) on the Dashboard.
```suggestion
1. Navigate to [Workers & Pages Overview](https://dash.cloudflare.com/?to=/:account/workers-and-pages/) on the Dashboard.
```

2024-12-31 06:11 UTC, irvinebroque commented on src/content/docs/pages/configuration/build-caching.mdx
> +1. Navigate to [Workers & Pages Overview](https://dash.cloudflare.com) on the Dashboard.
```suggestion
1. Navigate to [Workers & Pages Overview](https://dash.cloudflare.com/?to=/:account/workers-and-pages) on the Dashboard.
```

2024-12-31 06:11 UTC, irvinebroque commented on src/content/docs/pages/configuration/git-integration/github-integration.mdx
> +Cloudflare supports connecting Cloudflare Pages to your GitHub repositories, and will automatically deploy your code everytime you push a change to a branch.
```suggestion
You can connect each Cloudflare Pages project to a GitHub repository, and Cloudflare will automatically deploy your code every time you push a change to a branch.
```

2024-12-31 06:11 UTC, irvinebroque commented on src/content/docs/pages/configuration/git-integration/github-integration.mdx
> +Suppose you have a custom Git workflow that uses specific branches to represent your project's production build. In that case, you can specify a custom branch when creating (or managing an existing)
This could be more specific, right?

It's really just — if a branch other than the default branch (ex: `main` or `master`) represents your project's production build, do x.

"custom Git workflow" sounds like it could mean many things

2024-12-31 06:11 UTC, irvinebroque commented on src/content/docs/pages/configuration/git-integration/github-integration.mdx
> +You can also use [preview deployments](/pages/configuration/preview-deployments/) to preview how the new version of your project looks before merging into `production`. In addition, Pages allows you
```suggestion
You can also use [preview deployments](/pages/configuration/preview-deployments/) to preview how the new version of your project looks before merging into your production branch, and deploying to production. In addition, Pages allows you to configure which of your preview branches are built and deployed by using [branch build controls](/pages/configuration/branch-build-controls/).
```

2024-12-31 06:11 UTC, irvinebroque commented on src/content/docs/pages/configuration/git-integration/github-integration.mdx
> +Every time you open a new pull request on your GitHub repository, Cloudflare Pages will create a unique preview URL, which will stay updated as you continue to push new commits to the branch. Note th
```suggestion
Every time you open a new pull request on your GitHub repository, Cloudflare Pages will create a unique preview URL, which will stay updated as you continue to push new commits to the branch. Note that preview URLs will not be created for pull requests created from forks of your repository. Learn more in [Preview Deployments](/pages/configuration/preview-deployments/).
```

Suggest being most specific, I understood reading note below, but think possible to bring that up.

2024-12-31 06:11 UTC, irvinebroque commented on src/content/docs/pages/configuration/git-integration/github-integration.mdx
> +Without any configuration required, you can choose to skip a deployment on an adhoc basis. By adding the `[CI Skip]`, `[CI-Skip]`, `[Skip CI]`, `[Skip-CI]`, or `[CF-Pages-Skip]` flag as a prefix in y
TIL!

2024-12-31 06:11 UTC, irvinebroque commented on src/content/docs/pages/configuration/git-integration/github-integration.mdx
> +![GitHub status](~/assets/images/workers/platform/ci-cd/gh-status-check-runs.png)
Nice one with images

2024-12-31 06:11 UTC, irvinebroque commented on src/content/docs/pages/configuration/git-integration/github-integration.mdx
> +### Reinstall a Git installation
```suggestion
### How to reinstall the Cloudflare GitHub App
```

2024-12-31 06:11 UTC, irvinebroque commented on src/content/docs/pages/configuration/git-integration/github-integration.mdx
> +When encountering Git integration related issues, one potential troubleshooting step is attempting to uninstall and reinstall the GitHub application associated with the Cloudflare Pages installation.
```suggestion
If you see errors where Cloudflare Pages cannot access your git repository, you should attempt to uninstall and reinstall the GitHub application associated with the Cloudflare Pages installation.
```

2024-12-31 06:11 UTC, irvinebroque commented on src/content/docs/pages/configuration/git-integration/github-integration.mdx
> +   - Navigate to **Settings > Builds** for the Pages project and click **Manage** under Git Repository.
I didn't totally follow this part becuase it seemed like the first part talks about Pages projects, but the top-level heading is about the settings page on Github?

2024-12-31 06:11 UTC, irvinebroque commented on src/content/docs/pages/configuration/git-integration/github-integration.mdx
> +title: GitHub integration
At some point (doesn't need to be in this PR) at the top of this, a `note` or `aside` that pointed people to 

https://anni-wb-checkruns.cloudflare-docs-7ou.pages.dev/workers/ci-cd/builds/

...would be awesome, especially now that the docs around Workers are really good. So that people know that (much) of they're going to read on this page is also possible with Workers.

2024-12-31 06:11 UTC, irvinebroque commented on src/content/docs/pages/configuration/git-integration/gitlab-integration.mdx
> +Cloudflare supports connecting Cloudflare Pages to your GitLab repositories, and will automatically deploy your code everytime you push a change to a branch.
```suggestion
You can connect each Cloudflare Pages project to a GitLab repository, and Cloudflare will automatically deploy your code every time you push a change to a branch.
```

2024-12-31 06:11 UTC, irvinebroque commented on src/content/docs/pages/configuration/git-integration/index.mdx
> +Cloudflare supports connecting Cloudflare Pages to your [GitHub](/pages/configuration/git-integration/github-integration) and [GitLab](/pages/configuration/git-integration/gitlab-integration) reposit
```suggestion
You can connect each Cloudflare Pages project to a [GitHub](/pages/configuration/git-integration/github-integration) or [GitLab](/pages/configuration/git-integration/gitlab-integration) repository, and Cloudflare will automatically deploy your code every time you push a change to a branch.
```

2024-12-31 06:11 UTC, irvinebroque commented on src/content/docs/pages/configuration/git-integration/index.mdx
> +Using Git integration with Cloudflare also provides:
```suggestion
When you connect a git repository to your Cloudflare Pages project, Cloudflare will also:
```

2024-12-31 06:11 UTC, irvinebroque commented on src/content/docs/pages/configuration/git-integration/index.mdx
> +- **Preview deployments for custom branches**, generating preview URLs for a commit to any branch in the repository without affecting your production deployment.
Doesn't seem like this one should be first in the list, since first you kind of have to understand what a preview url is

2024-12-31 06:11 UTC, irvinebroque commented on src/content/docs/pages/configuration/git-integration/index.mdx
> +:::caution[You cannot switch to Direct Upload later]
Worth calling out that this is not the case with Workers?

2024-12-31 06:11 UTC, irvinebroque commented on src/content/docs/pages/configuration/git-integration/index.mdx
> +Cloudflare Pages supports the following Git providers:
It seems simpler to say — we support GitHub and GitLab, except not if you self-host — right?

The pricing/plan level stuff isn't really the relevant detail, it's whether what you're running is cloud hosted or self hosted.

2024-12-31 06:11 UTC, irvinebroque commented on src/content/docs/pages/configuration/git-integration/index.mdx
> +- Start with a Direct Upload project and deploy using a [CI/CD provider with Wrangler CLI](/pages/how-to/use-direct-upload-with-continuous-integration/).
This seems like the actual recommended path — worth saying `GitHub Actions` by name here since we're talking about GitHub anyways

2024-12-31 06:11 UTC, irvinebroque commented on src/content/docs/pages/configuration/git-integration/index.mdx
> +- Or, [disable automatic deployments](/pages/configuration/git-integration/#disable-automatic-deployments) in a Git-integrated project and use a [CI/CD provider with Wrangler CLI](/pages/how-to/use-d
This is confusing if I'm starting anything new? Is it necessary to call out in a way here where it's a recommended path? This is a workaround for being restrictive/prescriptive about not mixing together direct upload and pages builds, right?

2025-01-03 11:52 UTC, ToriLindsay requested changes

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/pages/configuration/git-integration/index.mdx
> +## Troubleshooting
Maybe you'd also want to consider breaking Troubleshooting into it's own article, beneath the other three in the "Git Integration" sections for both Workers and Pages?

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/pages/configuration/git-integration/index.mdx
> +## Adding Git Integration
```suggestion
## Add a Git integration
```
Could also be "Set up a Git integration" or any other direct verb.
Also, "integration" should be lowercase for consistency.

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/pages/configuration/git-integration/index.mdx
> +## Managing Git Integration
```suggestion
## Manage a Git integration
```
Same as above. It could also be "Manage the Git integration" or "Manage your Git integration". Whatever you think is best.

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/pages/configuration/git-integration/index.mdx
> +Using the same GitHub/GitLab repository across separate Cloudflare accounts is disallowed. To use the repository for a Pages project in that Cloudflare account, you should delete any Pages projects u
```suggestion
You cannot use the same GitHub/GitLab repository with multiple Cloudflare accounts. To use a Pages project with a different Cloudflare account, delete it from the current Cloudflare account first.
```
Just simplifying the wording

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/pages/configuration/git-integration/index.mdx
> +To resolve any errors displayed in the Cloudflare Pages dashboard, follow the steps listed below.
```suggestion
To resolve an error displayed in the Cloudflare Pages dashboard, find it below and follow the instructions.
```
Minor. Just thought this is clearer since there aren't actually "steps" listed anywhere below here.

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/workers/ci-cd/builds/git-integration/github-integration.mdx
> +Cloudflare supports connecting your GitHub repository to your Cloudflare Worker, and will automatically deploy your code everytime you push a change to a selected branch.
```suggestion
Cloudflare supports connecting your GitHub repository to your Cloudflare Worker, and will automatically deploy your code every time you push a change to a selected branch.
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/workers/ci-cd/builds/git-integration/gitlab-integration.mdx
> +Cloudflare supports connecting your GitLab repository to your Cloudflare Worker, and will automatically deploy your code everytime you push a change to a selected branch.
```suggestion
Cloudflare supports connecting your GitLab repository to your Cloudflare Worker, and will automatically deploy your code every time you push a change to a selected branch.
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/workers/ci-cd/builds/git-integration/index.mdx
> +Cloudflare supports connecting your [GitHub](/workers/ci-cd/builds/git-integration/github-integration/) and [GitLab](/workers/ci-cd/builds/git-integration/gitlab-integration/) repository to your Clou
```suggestion
Cloudflare supports connecting your [GitHub](/workers/ci-cd/builds/git-integration/github-integration/) and [GitLab](/workers/ci-cd/builds/git-integration/gitlab-integration/) repository to your Cloudflare Worker, and will automatically deploy your code every time you push a change to a selected branch.
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/pages/configuration/git-integration/index.mdx
> +If you don't have a Git account linked to your Cloudflare account, you'll be prompted to set up an installation to GitHub or GitLab when [connecting to Git](/pages/get-started/git-integration/) for t
```suggestion
If you do not have a Git account linked to your Cloudflare account, you will be prompted to set up an installation to GitHub or GitLab when [connecting to Git](/pages/get-started/git-integration/) for the first time, or when adding a new Git account. Follow the prompts and authorize the Cloudflare Git integration.
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/workers/ci-cd/builds/advanced-setups.mdx
> +1. [Deploy via Wrangler](/workers/wrangler/commands/#deploy) to create the Workers for your environments on the Dashboard, if you don't already have them.
```suggestion
1. [Deploy via Wrangler](/workers/wrangler/commands/#deploy) to create the Workers for your environments on the Dashboard, if you do not already have them.
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/workers/ci-cd/builds/advanced-setups.mdx
>  Imagine you have a Worker named `my-worker`, and you want to set up two environments `staging` and `production` set in the `wrangler.toml`. If you haven't already, you can deploy `my-worker` for each
```suggestion
Imagine you have a Worker named `my-worker`, and you want to set up two environments `staging` and `production` set in the `wrangler.toml`. If you have not already, you can deploy `my-worker` for each environment using the commands `wrangler deploy --env staging` and `wrangler deploy --env production`.
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/workers/ci-cd/builds/configuration.mdx
> +If you've added a Wrangler deploy command as a script in your `package.json`, then you can run it by setting it as your deploy command. For example, `npm run deploy`.
```suggestion
If you have added a Wrangler deploy command as a script in your `package.json`, then you can run it by setting it as your deploy command. For example, `npm run deploy`.
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/workers/ci-cd/builds/git-integration/github-integration.mdx
> +You can remove Cloudflare Workers' access to your GitHub repository or account by viewing the [Applications page](https://github.com/settings/installations) on GitHub (if you're in an organization, s
```suggestion
You can remove Cloudflare Workers' access to your GitHub repository or account by viewing the [Applications page](https://github.com/settings/installations) on GitHub (if you are in an organization, select Switch settings context to access your GitHub organization settings) or going to [manage Git installation](/workers/ci-cd/builds/git-integration/#managing-a-git-installation) on the dashboard. The GitHub App is named Cloudflare Workers and Pages, and it is shared between Workers and Pages projects.
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/workers/ci-cd/builds/git-integration/index.mdx
> +If you don't have a Git account linked to your Cloudflare account, you'll be prompted to set up an installation to GitHub or GitLab when [connecting a repository](/workers/ci-cd/builds/#get-started)
```suggestion
If you do not have a Git account linked to your Cloudflare account, you will be prompted to set up an installation to GitHub or GitLab when [connecting a repository](/workers/ci-cd/builds/#get-started) for the first time, or when adding a new Git account. Follow the prompts and authorize the Cloudflare Git integration.
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/workers/ci-cd/builds/git-integration/index.mdx
> +- [GitHub Applications page](https://github.com/settings/installations) (if you're in an organization, select **Switch settings context** to access your GitHub organization settings)
```suggestion
- [GitHub Applications page](https://github.com/settings/installations) (if you are in an organization, select **Switch settings context** to access your GitHub organization settings)
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/workers/ci-cd/builds/index.mdx
> +2. Select the Git provider you'd like to connect to or select **Connect** and follow the prompts to install the Cloudflare [Git integration](/workers/ci-cd/builds/git-integration/) on your Git accoun
```suggestion
2. Select the Git provider you would like to connect to or select **Connect** and follow the prompts to install the Cloudflare [Git integration](/workers/ci-cd/builds/git-integration/) on your Git account.
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/workers/ci-cd/builds/troubleshoot.mdx
> +When connecting a Git repository to your Workers project, the specified name for the Worker on the Cloudflare dashboard must match the `name` argument in the wrangler.toml file located in the specifi
```suggestion
When connecting a Git repository to your Workers project, the specified name for the Worker on the Cloudflare dashboard must match the `name` argument in the wrangler.toml file located in the specified root directory. If it does not match, update the name field in your wrangler.toml file to match the name of the Worker on the dashboard.
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/workers/ci-cd/builds/git-integration/index.mdx
> +If you use a different Git provider (e.g. Bitbucket), you can use an [external CI/CD provider](/workers/ci-cd/external-cicd/) and deploy using [Wrangler CLI](/workers/wrangler/commands/#deploy).
```suggestion
If you use a different Git provider, such as Bitbucket, you can use an [external CI/CD provider](/workers/ci-cd/external-cicd/) and deploy using [Wrangler CLI](/workers/wrangler/commands/#deploy).
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/workers/ci-cd/builds/git-integration/index.mdx
> +## Adding Git Integration
```suggestion
## Add a Git Integration
```
Same as in other article

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/workers/ci-cd/builds/git-integration/index.mdx
> +## Managing Git Integration
```suggestion
## Manage a Git Integration
```
Same as other article

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/workers/ci-cd/builds/git-integration/index.mdx
> +Adding a Git integration also lets you monitor build statuses directly in your Git provider using [check runs](/workers/ci-cd/builds/git-integration/github-integration/#check-run) or [commit statuses
```suggestion
Adding a Git integration also lets you monitor build statuses directly in your Git provider using [check runs](/workers/ci-cd/builds/git-integration/github-integration/#check-run) or [commit statuses](/workers/ci-cd/builds/git-integration/gitlab-integration/#commit-status), so you can manage deployments without leaving your workflow.
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/workers/ci-cd/builds/git-integration/index.mdx
> +You can check the below pages to see if your Git integration has been installed:
```suggestion
You can check the following pages to see if your Git integration has been installed:
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/workers/ci-cd/builds/git-integration/index.mdx
> +For details on providing access to organization accounts, see [GitHub Organizational Access](/workers/ci-cd/builds/git-integration/github-integration/#organizational-access) and [GitLab Organizationa
```suggestion
For details on providing access to organization accounts, see [GitHub organizational access](/workers/ci-cd/builds/git-integration/github-integration/#organizational-access) and [GitLab organizational access](/workers/ci-cd/builds/git-integration/gitlab-integration/#organizational-access).
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/pages/configuration/git-integration/index.mdx
> +### Project Creation
```suggestion
### Project creation
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/workers/ci-cd/builds/build-caching.mdx
> +### Package Managers
```suggestion
### Package managers
```
If this phrase isn't capitalized generally, it should be lowercase in the heading

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/workers/ci-cd/builds/configuration.mdx
> +### Deploy Command
```suggestion
### Deploy command
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/workers/ci-cd/builds/configuration.mdx
> +### API Token
```suggestion
### API token
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/workers/ci-cd/builds/git-integration/gitlab-integration.mdx
> +### Commit Status
```suggestion
### Commit status
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/workers/ci-cd/builds/troubleshoot.mdx
> +### Workers Name Requirement
```suggestion
### Workers name requirement
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/workers/ci-cd/builds/troubleshoot.mdx
> +### Missing Wrangler.toml
```suggestion
### Missing wrangler.toml
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/workers/ci-cd/builds/troubleshoot.mdx
> +### Incorrect Account_id
```suggestion
### Incorrect account_id
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/workers/ci-cd/builds/troubleshoot.mdx
> +### Stale API Token
```suggestion
### Stale API token
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/workers/ci-cd/builds/troubleshoot.mdx
> +### Build Timed Out
```suggestion
### Build timed out
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/workers/ci-cd/builds/troubleshoot.mdx
> +### Git Integration Issues
```suggestion
### Git integration issues
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/workers/ci-cd/builds/build-caching.mdx
> +### Enable Build Caching
```suggestion
### Enable build caching
```
Heading shouldn't be capitalized

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/pages/configuration/git-integration/gitlab-integration.mdx
> +## Managing Access
```suggestion
## Managing access
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/pages/configuration/git-integration/index.mdx
> +## Supported Git Providers
```suggestion
## Supported Git providers
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/pages/configuration/git-integration/index.mdx
> +## Disable Automatic Deployments
```suggestion
## Disable automatic deployments
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/pages/configuration/git-integration/index.mdx
> +### Project Creation
```suggestion
### Project creation
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/workers/ci-cd/builds/advanced-setups.mdx
> +## Wrangler Environments
```suggestion
## Wrangler environments
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/workers/ci-cd/builds/build-caching.mdx
> +### Clear Cache
```suggestion
### Clear cache
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/workers/ci-cd/builds/build-caching.mdx
> +## How Build Caching Works
```suggestion
## How build caching works
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/workers/ci-cd/builds/build-watch-paths.mdx
> +## Configure Paths
```suggestion
## Configure paths
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/workers/ci-cd/builds/configuration.mdx
>  ## Build Settings
```suggestion
## Build settings
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/workers/ci-cd/builds/configuration.mdx
> +## Framework Support
```suggestion
## Framework support
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/workers/ci-cd/builds/git-integration/index.mdx
> +## Supported Git Providers
```suggestion
## Supported Git providers
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/workers/ci-cd/builds/index.mdx
>  ## Get Started
```suggestion
## Get started
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/workers/ci-cd/builds/index.mdx
> +## View Build and Preview URL
```suggestion
## View build and preview URL
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/workers/ci-cd/builds/index.mdx
> +## Disconnecting Builds
```suggestion
## Disconnect builds
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/workers/ci-cd/builds/troubleshoot.mdx
> +## For Additional Support
```suggestion
## For additional support
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/workers/ci-cd/index.mdx
>  ## Workers Builds
```suggestion
## Workers builds
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/pages/configuration/git-integration/github-integration.mdx
> +Suppose you have a custom Git workflow that uses specific branches to represent your project's production build. In that case, you can specify a custom branch when creating (or managing an existing)
```suggestion
Suppose you have a custom Git workflow that uses specific branches to represent your project's production build. In that case, you can specify a custom branch when creating (or managing an existing) project in the Pages dashboard by going to **Settings** > **Builds** > **Branch control**. To change the production branch, select the **Production branch** dropdown menu and choose any other branch.
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/pages/configuration/git-integration/github-integration.mdx
> +   - Navigate to **Settings > Builds** for the Pages project and click **Manage** under Git Repository.
```suggestion
   - Navigate to **Settings > Builds** for the Pages project and select **Manage** under Git Repository.
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/pages/configuration/git-integration/github-integration.mdx
> +   - Alternatively, visit these links to find the Cloudflare Workers and Pages installation and click **Configure**:
```suggestion
   - Alternatively, visit these links to find the Cloudflare Workers and Pages installation and select **Configure**:
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/pages/configuration/git-integration/github-integration.mdx
> +3. Go back to the [**Workers & Pages** overview](https://dash.cloudflare.com) page. Click **Create application** > **Pages** > **Connect to Git**
```suggestion
3. Go back to the [**Workers & Pages** overview](https://dash.cloudflare.com) page. Select **Create application** > **Pages** > **Connect to Git**.
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/pages/configuration/git-integration/github-integration.mdx
> +4. Click the **+ Add account** button, click the GitHub account you want to add, and then click **Install & Authorize**.
```suggestion
4. Select the **+ Add account** button, select the GitHub account you want to add, and then select **Install & Authorize**.
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/pages/configuration/git-integration/gitlab-integration.mdx
> +Suppose you have a custom Git workflow that uses specific branches to represent your project's production build. In that case, you can specify a custom branch when creating (or managing an existing)
```suggestion
Suppose you have a custom Git workflow that uses specific branches to represent your project's production build. In that case, you can specify a custom branch when creating (or managing an existing) project in the Pages dashboard by going to **Settings** > **Builds & deployments** > **Configure Production deployments**. To change the production branch, select the **production branch** dropdown menu and choose any other branch.
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/pages/configuration/git-integration/gitlab-integration.mdx
> +Check runs will appear like the following in your repository. You can click on one of the statuses to view the [preview URL](/pages/configuration/preview-deployments/) for that deployment.
```suggestion
Check runs will appear like the following in your repository. You can select one of the statuses to view the [preview URL](/pages/configuration/preview-deployments/) for that deployment.
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/pages/configuration/git-integration/gitlab-integration.mdx
> +2. Click the "Revoke" button on your Cloudflare Pages installation if it exists.
```suggestion
2. Select the **Revoke** button on your Cloudflare Pages installation if it exists.
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/pages/configuration/git-integration/gitlab-integration.mdx
> +3. Go back to the **Workers & Pages** overview page at `https://dash.cloudflare.com/[YOUR_ACCOUNT_ID]/workers-and-pages`. Click **Create application** > **Pages** > **Connect to Git**
```suggestion
3. Go back to the **Workers & Pages** overview page at `https://dash.cloudflare.com/[YOUR_ACCOUNT_ID]/workers-and-pages`. Select **Create application** > **Pages** > **Connect to Git**.
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/pages/configuration/git-integration/gitlab-integration.mdx
> +4. Select the **GitLab** tab at the top, click the **+ Add account** button, click the GitLab account you want to add, and then click **Authorize** on the modal titled "Authorize Cloudflare Pages to
```suggestion
4. Select the **GitLab** tab at the top, select the **+ Add account** button, select the GitLab account you want to add, and then select **Authorize** on the modal titled "Authorize Cloudflare Pages to use your account?".
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/pages/configuration/git-integration/index.mdx
> +Click **Configure** on the Cloudflare Pages application. Scroll down to the bottom of the page and click **Unsuspend** to allow Cloudflare Pages to make future deployments.
```suggestion
Select **Configure** on the Cloudflare Pages application. Scroll down to the bottom of the page and select **Unsuspend** to allow Cloudflare Pages to make future deployments.
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/pages/configuration/git-integration/index.mdx
> +Click **Configure** on the Cloudflare Pages application. Under **Repository access**, ensure that the repository associated with your Cloudflare Pages project is included in the list.
```suggestion
Select **Configure** on the Cloudflare Pages application. Under **Repository access**, ensure that the repository associated with your Cloudflare Pages project is included in the list.
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/workers/ci-cd/builds/git-integration/github-integration.mdx
> +   - Navigate to **Settings > Builds** for the Workers or Pages project and click **Manage** under Git Repository.
```suggestion
   - Navigate to **Settings > Builds** for the Workers or Pages project and select **Manage** under Git Repository.
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/workers/ci-cd/builds/git-integration/github-integration.mdx
> +   - Alternatively, visit these links to find the Cloudflare Workers and Pages installation and click **Configure**:
```suggestion
   - Alternatively, visit these links to find the Cloudflare Workers and Pages installation and select **Configure**:
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/workers/ci-cd/builds/git-integration/github-integration.mdx
> +3. Go back to the [**Workers & Pages** overview](https://dash.cloudflare.com) page. Click **Create application** > **Pages** > **Connect to Git**
```suggestion
3. Go back to the [**Workers & Pages** overview](https://dash.cloudflare.com) page. Select **Create application** > **Pages** > **Connect to Git**.
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/workers/ci-cd/builds/git-integration/github-integration.mdx
> +4. Click the **+ Add account** button, click the GitHub account you want to add, and then click **Install & Authorize**.
```suggestion
4. Select the **+ Add account** button, select the GitHub account you want to add, and then select **Install & Authorize**.
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/workers/ci-cd/builds/git-integration/gitlab-integration.mdx
> +2. Click the "Revoke" button on your Cloudflare Pages installation if it exists.
```suggestion
2. Select the **Revoke** button on your Cloudflare Pages installation if it exists.
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/workers/ci-cd/builds/git-integration/gitlab-integration.mdx
> +3. Go back to the [**Workers & Pages** overview](https://dash.cloudflare.com) page. Click **Create application** > **Pages** > **Connect to Git**
```suggestion
3. Go back to the [**Workers & Pages** overview](https://dash.cloudflare.com) page. Select **Create application** > **Pages** > **Connect to Git**.
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/workers/ci-cd/builds/git-integration/gitlab-integration.mdx
> +4. Click the **+ Add account** button, click the GitLab account you want to add, and then click **Install & Authorize**.
```suggestion
4. Select the **+ Add account** button, select the GitLab account you want to add, and then select **Install & Authorize**.
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/pages/configuration/git-integration/github-integration.mdx
> +Without any configuration required, you can choose to skip a deployment on an adhoc basis. By adding the `[CI Skip]`, `[CI-Skip]`, `[Skip CI]`, `[Skip-CI]`, or `[CF-Pages-Skip]` flag as a prefix in y
```suggestion
Without any configuration required, you can choose to skip a deployment on an ad hoc basis. By adding the `[CI Skip]`, `[CI-Skip]`, `[Skip CI]`, `[Skip-CI]`, or `[CF-Pages-Skip]` flag as a prefix in your commit message, and Pages will omit that deployment. The prefixes are not case sensitive.
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/pages/configuration/git-integration/gitlab-integration.mdx
> +Without any configuration required, you can choose to skip a deployment on an adhoc basis. By adding the `[CI Skip]`, `[CI-Skip]`, `[Skip CI]`, `[Skip-CI]`, or `[CF-Pages-Skip]` flag as a prefix in y
```suggestion
Without any configuration required, you can choose to skip a deployment on an ad hoc basis. By adding the `[CI Skip]`, `[CI-Skip]`, `[Skip CI]`, `[Skip-CI]`, or `[CF-Pages-Skip]` flag as a prefix in your commit message, Pages will omit that deployment. The prefixes are not case sensitive.
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/pages/configuration/git-integration/github-integration.mdx
> +Without any configuration required, you can choose to skip a deployment on an adhoc basis. By adding the `[CI Skip]`, `[CI-Skip]`, `[Skip CI]`, `[Skip-CI]`, or `[CF-Pages-Skip]` flag as a prefix in y
```suggestion
Without any configuration required, you can choose to skip a deployment on an adhoc basis. By adding the `[CI Skip]`, `[CI-Skip]`, `[Skip CI]`, `[Skip-CI]`, or `[CF-Pages-Skip]` flag as a prefix in your commit message, Pages will omit that deployment. The prefixes are not case sensitive.
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/pages/configuration/git-integration/github-integration.mdx
> +If you have one or multiple projects connected to a repository (i.e. a [monorepo](/pages/configuration/monorepos/)), you can check on the status of each build within GitHub via [GitHub check runs](ht
```suggestion
If you have one or multiple projects connected to a repository (as in a [monorepo](/pages/configuration/monorepos/)), you can check on the status of each build within GitHub via [GitHub check runs](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/collaborating-on-repositories-with-code-quality-features/about-status-checks#checks).
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/pages/configuration/git-integration/github-integration.mdx
> +If a build skips for any reason (i.e. CI Skip, build watch paths, or branch deployment controls), the check run/commit status will not appear.
```suggestion
If a build skips for any reason (for example, CI Skip, build watch paths, or branch deployment controls), the check run/commit status will not appear.
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/workers/ci-cd/builds/git-integration/github-integration.mdx
> +If you have one or multiple Workers connected to a repository (i.e. a [monorepo](/workers/ci-cd/builds/advanced-setups/#monorepos)), you can check on the status of each build within GitHub via [GitHu
```suggestion
If you have one or multiple Workers connected to a repository (as in a [monorepo](/workers/ci-cd/builds/advanced-setups/#monorepos)), you can check on the status of each build within GitHub via [GitHub check runs](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/collaborating-on-repositories-with-code-quality-features/about-status-checks#checks).
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/workers/ci-cd/builds/git-integration/github-integration.mdx
> +To add Cloudflare Workers installation to an organization, your user account must be an owner or have the appropriate role within the organization (i.e. the GitHub Apps Manager role). More informatio
```suggestion
To add Cloudflare Workers installation to an organization, your user account must be an owner or have the appropriate role within the organization (which is the GitHub Apps Manager role). More information on these roles can be seen on [GitHub's documentation](https://docs.github.com/en/organizations/managing-peoples-access-to-your-organization-with-roles/roles-in-an-organization#github-app-managers).
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/workers/ci-cd/builds/git-integration/gitlab-integration.mdx
> +If you have one or multiple Workers connected to a repository (i.e. a [monorepo](/workers/ci-cd/builds/advanced-setups/#monorepos)), you can check on the status of each build within GitLab via [GitLa
```suggestion
If you have one or multiple Workers connected to a repository (as in a [monorepo](/workers/ci-cd/builds/advanced-setups/#monorepos)), you can check on the status of each build within GitLab via [GitLab commit status](https://docs.gitlab.com/ee/user/project/merge_requests/status_checks.html).
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/workers/ci-cd/builds/git-integration/gitlab-integration.mdx
> +You can see the statuses by selecting on the status icon next to a commit or by going to **Build** > **Pipelines** within your GitLab repository. In the example below, you can select on the green che
```suggestion
You can see the statuses by selecting the status icon next to a commit or by going to **Build** > **Pipelines** within your GitLab repository. In the example below, you can select on the green check mark to see the results of the check run.
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/pages/configuration/git-integration/github-integration.mdx
> +You can see the checks by selecting on the status icon next to a commit within your GitHub repository. In the example below, you can select the green check mark to see the results of the check run.
```suggestion
You can see the checks by selecting the status icon next to a commit within your GitHub repository. In the example below, you can select the green check mark to see the results of the check run.
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/pages/configuration/git-integration/gitlab-integration.mdx
> +You can see the statuses by selecting on the status icon next to a commit or by going to **Build** > **Pipelines** within your GitLab repository. In the example below, you can select the green check
```suggestion
You can see the statuses by selecting the status icon next to a commit or by going to **Build** > **Pipelines** within your GitLab repository. In the example below, you can select the green check mark to see the results of the check run.
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/pages/configuration/git-integration/github-integration.mdx
> +To remove Cloudflare Workers and Pages access to your entire Git account, you can navigate to **Uninstall "Cloudflare Workers and Pages"**, then select **Uninstall**. Removing access to the Cloudflar
```suggestion
To remove Cloudflare Workers and Pages access to your entire Git account, you can navigate to **Uninstall "Cloudflare Workers and Pages"**, then select **Uninstall**. Removing access to the Cloudflare Workers and Pages app will revoke Cloudflare's access to _all repositories_ from that GitHub account. If you want to only disable automatic builds and deployments, follow the [disable automatic deployments](/pages/configuration/git-integration/#disable-automatic-deployments) instructions.
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/pages/configuration/git-integration/github-integration.mdx
> +![GitHub Preview Urls](~/assets/images/pages/configuration/ghpreviewurls.png)
```suggestion
![GitHub Preview URLs](~/assets/images/pages/configuration/ghpreviewurls.png)
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/pages/configuration/preview-deployments.mdx
> +![GitHub Preview Urls](~/assets/images/pages/configuration/ghpreviewurls.png)
```suggestion
![GitHub Preview URLs](~/assets/images/pages/configuration/ghpreviewurls.png)
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/pages/configuration/git-integration/github-integration.mdx
> +You can remove Cloudflare Pages' access to your GitHub repository or account by viewing the [Applications page](https://github.com/settings/installations) on GitHub (if you're in an organization, sel
This section is a bit confusing to me. It seems like this first paragraph is explaining how to remove Workers & Pages access to a GitHub account (or an individual repo?). Then, it explains how to remove it from an individual repo (but doesn't explain how that's different). And then it explains (again?) how to remove it from your "entire" account. The difference between these isn't clear to me.
Perhaps you can break it into sub-headings. For example:
- Remove Cloudflare access to an individual GitHub repo
- Remove Cloudflare access to your entire GitHub account
- (+ Another distinction, if needed)

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/pages/configuration/git-integration/index.mdx
> +If you use [GitHub Enterprise Server](https://docs.github.com/en/enterprise-server@3.10/admin/overview/about-github-enterprise-server), [Self-Managed GitLab](https://about.gitlab.com/pricing/), or an
```suggestion
If you use [GitHub Enterprise Server](https://docs.github.com/en/enterprise-server@3.10/admin/overview/about-github-enterprise-server), [Self-Managed GitLab](https://about.gitlab.com/pricing/), or another Git provider (such as Bitbucket), you can:
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/workers/ci-cd/builds/configuration.mdx
> +| **Build command** _(Optional)_                                               | Set a build command if your project requires a build step (e.g. `npm run build`). This is necessary, for example, when
```suggestion
| **Build command** _(Optional)_                                               | Set a build command if your project requires a build step (for example, `npm run build`). This is necessary, for example, when using a [front-end framework](/workers/ci-cd/builds/configuration/#framework-support) such as Next.js or Remix.                                                                                                                                                                                                                                                 |
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/workers/ci-cd/builds/git-integration/github-integration.mdx
> +In Beta, Workers Builds supports automatic builds and deployments only from a single selected branch (e.g. `main`).
```suggestion
In Beta, Workers Builds supports automatic builds and deployments only from a single selected branch (for example, `main`).
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/workers/ci-cd/builds/git-integration/gitlab-integration.mdx
> +In Beta, Workers Builds supports automatic builds and deployments only from a single selected branch (e.g. `main`).
```suggestion
In Beta, Workers Builds supports automatic builds and deployments only from a single selected branch (for example, `main`).
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/workers/ci-cd/builds/troubleshoot.mdx
> +`✘ [ERROR] Missing entry-point: The entry-point should be specified via the command line (e.g. wrangler deploy path/to/script) or the main config field.`
```suggestion
`✘ [ERROR] Missing entry-point: The entry-point should be specified via the command line (for example, wrangler deploy path/to/script) or the main config field.`
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/workers/ci-cd/index.mdx
> +[Workers Builds](/workers/ci-cd/builds) is Cloudflare's native CI/CD system that allows you to integrate with GitHub or GitLab to automatically deploy changes with each new push to a selected branch
```suggestion
[Workers Builds](/workers/ci-cd/builds) is Cloudflare's native CI/CD system that allows you to integrate with GitHub or GitLab to automatically deploy changes with each new push to a selected branch (for example, `main`).
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/pages/configuration/git-integration/github-integration.mdx
> +A GitHub account should only point to one Cloudflare account. If you are setting up Cloudflare with GitHub for your organization, Cloudflare recommends that you limit the scope of the application to
```suggestion
A GitHub account should only point to one Cloudflare account. If you are setting up Cloudflare with GitHub for your organization, Cloudflare recommends that you limit the scope of the application to only the repositories you intend to build with Pages. To modify these permissions, go to the [Applications page](https://github.com/settings/installations) on GitHub and select **Switch settings context** to access your GitHub organization settings. Then, select **Cloudflare Workers & Pages** > For **Repository access**, select **Only select repositories** > select your repositories.
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/workers/ci-cd/builds/git-integration/github-integration.mdx
> +A GitHub account should only point to one Cloudflare account. If you are setting up Cloudflare with GitHub for your organization, Cloudflare recommends that you limit the scope of the application to
```suggestion
A GitHub account should only point to one Cloudflare account. If you are setting up Cloudflare with GitHub for your organization, Cloudflare recommends that you limit the scope of the application to only the repositories you intend to build with Pages. To modify these permissions, go to the [Applications page](https://github.com/settings/installations) on GitHub and select **Switch settings context** to access your GitHub organization settings. Then, select **Cloudflare Workers & Pages** > For **Repository access**, select **Only select repositories** > select your repositories.
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/workers/ci-cd/builds/git-integration/github-integration.mdx
> +You can remove Cloudflare Workers' access to your GitHub repository or account by viewing the [Applications page](https://github.com/settings/installations) on GitHub (if you're in an organization, s
See my comment on the GitHub Pages article. Same thing applies here.

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/workers/ci-cd/builds/git-integration/github-integration.mdx
> +When encountering Git integration related issues, a troubleshooting step is attempting to uninstall and reinstall the GitHub app associated with the Cloudflare Workers & Pages installation.
```suggestion
When encountering Git integration related issues, one potential troubleshooting step is attempting to uninstall and reinstall the GitHub or GitLab application associated with the Cloudflare Pages installation. The process for each Git provider is provided below.
```
Changed this to copy the same sentence from the Pages article since I think it's clearer.

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/workers/ci-cd/builds/git-integration/github-integration.mdx
> +3. Go back to the [**Workers & Pages** overview](https://dash.cloudflare.com) page. Click **Create application** > **Pages** > **Connect to Git**
Should this say Workers instead of Pages?

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/pages/configuration/git-integration/gitlab-integration.mdx
> +By authorizing Cloudflare Pages to access your GitLab account, you will automatically allow access to organizations, groups, and namespaces your GitLab account can access for use by Cloudflare Pages.
```suggestion
When you authorize Cloudflare Pages to access your GitLab account, you automatically give Cloudflare Pages access to organizations, groups, and namespaces accessed by your GitLab account. Managing access to these organizations and groups is handled by GitLab.
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/workers/ci-cd/builds/git-integration/gitlab-integration.mdx
> +By authorizing Cloudflare Workers to access your GitLab account, you will automatically allow access to organizations, groups, and namespaces your GitLab account can access for use by Cloudflare Work
```suggestion
When you authorize Cloudflare Workers to access your GitLab account, you automatically give Cloudflare Workers access to organizations, groups, and namespaces accessed by your GitLab account.  Managing access to these organizations and groups is handled by GitLab.
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/workers/ci-cd/builds/troubleshoot.mdx
> +If you discover additional issues or would like to provide feedback, please reach out to us in the [Cloudflare Developers Discord](https://discord.com/channels/595317990191398933/1052656806058528849)
```suggestion
If you discover additional issues or would like to provide feedback, reach out to us in the [Cloudflare Developers Discord](https://discord.com/channels/595317990191398933/1052656806058528849).
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/workers/ci-cd/builds/troubleshoot.mdx
> +## Investigate Build Errors and Retry
```suggestion
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/workers/ci-cd/builds/troubleshoot.mdx
> +Workers Builds provides build logs for each build. To view a Worker's build history, go to **Worker project** > **Deployments** > **View Build History** (located at the bottom of the Deployments tab)
```suggestion
To view your build history, go to your Worker project in the Cloudflare dashboard, select **Deployment**, select **View Build History** at the bottom of the page, and select the build you want to view. To retry a build, select the ellipses next to the build and select **Retry build**. Alternatively, you can select **Retry build** on the Build Details page.
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/workers/ci-cd/builds/troubleshoot.mdx
> +To retry a build, click **•••** next to the desired build in the Build History page and select **Retry build**, or use the **Retry build** button on the Build Details page.
```suggestion
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/workers/ci-cd/builds/troubleshoot.mdx
> +## Known Issues or Limitations
```suggestion
# Known issues and limitations
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/workers/ci-cd/builds/troubleshoot.mdx
> +This guide teaches you how to investigate build errors and troubleshoot common errors within the Workers Build's build and deployment process.
```suggestion
This guide explains how to identify and resolve build errors, as well as troubleshoot common issues in the Workers Builds deployment process.
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/workers/ci-cd/builds/troubleshoot.mdx
> +title: Troubleshooting builds
```suggestion
title: Troubleshooting
```
I think we should keep this as Troubleshooting since adding "builds" seems redundant and this is more consistent with the other docs.

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/workers/ci-cd/builds/troubleshoot.mdx
> +For example, a Worker named `my-worker-staging` on the dashboard can be deployed from a repository that contains a wrangler.toml with the arguemnts `name = my-worker` and `[env.staging]` using the de
```suggestion
For example, a Worker named `my-worker-staging` on the dashboard can be deployed from a repository that contains a wrangler.toml with the arguments `name = my-worker` and `[env.staging]` using the deploy command `npx wrangler deploy --env staging`.
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/workers/ci-cd/builds/configuration.mdx
> +Note that when you update and save build settings, the updated settings will be applied to your **next** build. When you **retry** a build, the build configurations that exist when the build is retri
```suggestion
Note that when you update and save build settings, the updated settings will be applied to your _next_ build. When you _retry_ a build, the build configurations that exist when the build is retried will be applied.
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/workers/ci-cd/builds/configuration.mdx
> +| **Git account**                                                              | Select the Git account you would like to use. After initial connection, you can continue to use this Git account for f
```suggestion
| **Git account**                                                              | Select the Git account you would like to use. After the initial connection, you can continue to use this Git account for future projects.                                                                                                                                                                                                                                                                                                                                                  |
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/workers/ci-cd/builds/configuration.mdx
> +You can run your deploy command using your package manager of choice.
```suggestion
You can run your deploy command using the package manager of your choice.
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/workers/ci-cd/builds/configuration.mdx
> +When you select to **Create new token**, a new API token will be created automatically with the following permissions:
```suggestion
When you select **Create new token**, a new API token will be created automatically with the following permissions:
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/workers/ci-cd/builds/index.mdx
> +description: Use Workers Builds to integrate with Git and automatically build and deploy your Worker when push a change
```suggestion
description: Use Workers Builds to integrate with Git and automatically build and deploy your Worker when pushing a change
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/workers/ci-cd/builds/index.mdx
> +Workers Builds allows you to connect an **existing Worker** to its GitHub or GitLab repository, enabling automated builds and deployments for your project on push.
```suggestion
Workers Builds allows you to connect an _existing Worker_ to its GitHub or GitLab repository, enabling automated builds and deployments for your project on push.
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/workers/ci-cd/builds/index.mdx
> +Support for creating a **new Worker** from importing a Git repository is coming soon.
```suggestion
Support for creating a _new Worker_ from importing a Git repository is coming soon.
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/workers/ci-cd/builds/index.mdx
> +1. Select your Worker in the [Workers & Pages Dashboard](https://dash.cloudflare.com) and navigate to **Settings > Build**
```suggestion
1. Select your Worker in the [Workers & Pages Dashboard](https://dash.cloudflare.com) and navigate to **Settings > Build**.
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/workers/ci-cd/builds/index.mdx
> +When connecting a repository to a Workers project, the Worker name in the Cloudflare dashboard must match the `name` in the wrangler.toml file in the specified root directory, or the build will fail.
```suggestion
When connecting a repository to a Workers project, the Worker name in the Cloudflare dashboard must match the `name` in the wrangler.toml file in the specified root directory, or the build will fail. This ensures that the Worker deployed from the repository is consistent with the Worker registered in the Cloudflare dashboard. For details, see [Workers name requirement](/workers/ci-cd/builds/troubleshoot/#workers-name-requirement).
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/workers/ci-cd/builds/index.mdx
> +If you prefer to disable only automatic deployments while still allowing builds to run automatically and save as [Versions](/workers/configuration/versions-and-deployments/) (without promoting them t
```suggestion
To disable automatic deployments while still allowing builds to run automatically and save as [versions](/workers/configuration/versions-and-deployments/) (without promoting them to an active deployment), update your deploy command to: `npx wrangler versions upload`.
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/workers/ci-cd/builds/index.mdx
> +To set up Builds for your Worker:
```suggestion
To set up builds for your Worker:
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/workers/ci-cd/builds/index.mdx
> +:::note[Builds, Versions, Deployments]
```suggestion
:::note[Builds, versions, deployments]
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/workers/ci-cd/builds/index.mdx
> +To disable automatic builds and deployments from your Git repository, go to **Settings** > **Builds** and select **Disconnect** under **Git Repositories**. If you want to switch to a different reposi
```suggestion
To disable automatic builds and deployments from your Git repository, go to **Settings** > **Builds** and select **Disconnect** under **Git Repositories**. If you want to switch to a different repository for your Worker, you must first disable builds, then reconnect to select the new repository.
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/workers/ci-cd/builds/index.mdx
> +If the build is successful, you can also view the build details by selecting **View build** in the associated new [version](/workers/configuration/versions-and-deployments/) created under Version His
```suggestion
If the build is successful, you can view the build details by selecting **View build** in the associated new [version](/workers/configuration/versions-and-deployments/) created under Version History. There you will also find the [preview URL](/workers/configuration/previews/) generated by the version under Version ID.
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/pages/configuration/build-caching.mdx
>  ## Requirements
I find the headings in this article to be a slightly overkill and the organization seems a little mixed up. Maybe it could be something like:
- About build caching
- - Requirements
- - Package managers
- - Frameworks
- - Limits
- Enable build caching
- Clear build caching

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/pages/get-started/git-integration.mdx
> +In this guide, you will get started with Cloudflare Pages, and deploy your first website to the Pages platform through Git integration. The Git integration enables automatic builds and deployments ev
```suggestion
In this guide, you will get started with Cloudflare Pages and deploy your first website to the Pages platform through Git integration. The Git integration enables automatic builds and deployments every time you push a change to your connected [GitHub](/pages/configuration/git-integration/github-integration/) or [GitLab](/pages/configuration/git-integration/gitlab-integration/) repository.
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/workers/ci-cd/builds/build-caching.mdx
> +Improve Workers Builds build times by caching dependencies and build output between builds with a project-wide shared cache.
```suggestion
Improve Workers build times by caching dependencies and build output between builds with a project-wide shared cache.
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/workers/ci-cd/builds/build-caching.mdx
>  ## Configuration
I left some feedback on the structure of the Pages build-caching article (above). It would still be good for the articles to mirror each other, so consider the same approach for this one.

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/workers/get-started/dashboard.mdx
> +- Push your project to a GitHub or GitLab respoitory then [connect to Builds](/workers/ci-cd/builds/#get-started) to enable automatic builds and deployments.
```suggestion
- Push your project to a GitHub or GitLab respoitory then [connect to builds](/workers/ci-cd/builds/#get-started) to enable automatic builds and deployments.
```

2025-01-03 11:52 UTC, ToriLindsay commented on src/content/docs/workers/get-started/guide.mdx
> +- Push your project to a GitHub or GitLab respoitory then [connect to Builds](/workers/ci-cd/builds/#get-started) to enable automatic builds and deployments.
```suggestion
- Push your project to a GitHub or GitLab respoitory then [connect to builds](/workers/ci-cd/builds/#get-started) to enable automatic builds and deployments.
```

2025-01-03 11:56 UTC, ToriLindsay commented
@aninibread I don't want to block you if you need to move ahead with this quickly, so let me know, but I think 90% of the changes I suggested can be resolved quickly since they are mostly grammar and typos.  It's up to you what you have time for in terms of the broader structural suggestions.

2025-01-28 01:55 UTC, aninibread commented on src/content/docs/workers/ci-cd/builds/git-integration/gitlab-integration.mdx
> +You can remove Cloudflare Workers' access to your GitLab account by navigating to [Authorized Applications page](https://gitlab.com/-/profile/applications) on GitLab. Find the applications called Clo
done!

2025-01-28 08:42 UTC, ToriLindsay approved these changes

2025-01-28 14:11 UTC, merged