[Zaraz] Add docs for logpush support in Zaraz
cloudflare/cloudflare-docs pull request #18960
Opened 2024-12-30 12:12 UTC by omarmosid

### Summary

### Screenshots (optional)

### Documentation checklist

- [ ] The [documentation style guide](https://developers.cloudflare.com/style-guide/) has been adhered to.
- [ ] If a larger change - such as adding a new page- an issue has been opened in relation to any incorrect or out of date information that this PR fixes.
- [ ] Files which have changed name or location have been allocated [redirects](https://developers.cloudflare.com/pages/configuration/redirects/#per-file).

2024-12-30 12:32 UTC, jonnyparris requested changes

2024-12-30 12:32 UTC, jonnyparris commented on src/content/docs/zaraz/reference/settings.mdx
> +Refer to the [Context Enricher](/zaraz/advanced/logpush/) for more information on this setting.
```suggestion
Refer to [Logpush](/zaraz/advanced/logpush/) for more information on this setting.
```

2024-12-30 12:32 UTC, jonnyparris commented on src/content/docs/zaraz/reference/settings.mdx
> +- **Remove URL query parameters**: Removes all query parameters from URLs. For example, `https://example.com/?q=hello` becomes `https://example.com/`.
let's remove this fomatting noise from the PR please - probably an update to editor settings needed

2024-12-30 12:32 UTC, jonnyparris commented on src/content/docs/zaraz/advanced/logpush.mdx
> +| URL            | `String` | The Zaraz URL to which the request was made to.
```suggestion
| URL            | `String` | The Zaraz URL to which the request was made.                                                                                                                                |
```

2024-12-30 12:32 UTC, jonnyparris commented on src/content/docs/zaraz/advanced/logpush.mdx
> +| Event Type     | `String` | The Event type that occured. Can be one of the following: `server_request`, `server_response`, `action_triggered`, `ecommerce_triggered`, `client_request`, `component_er
```suggestion
| Event Type     | `String` | Can be one of the following: `server_request`, `server_response`, `action_triggered`, `ecommerce_triggered`, `client_request`, `component_error`. |
```

2025-02-04 14:35 UTC, Refaerds approved these changes

2025-02-11 11:13 UTC, jonnyparris approved these changes
Let's add a changelog entry too then it's ready to merge 👍🏾

2025-02-12 09:08 UTC, omarmosid commented
> Let's add a changelog entry too then it's ready to merge 👍🏾

Added 🙏🏽

2025-02-12 09:43 UTC, merged