Add tutorial on how to use Workers KV directly from Rust
cloudflare/cloudflare-docs pull request #1902
Opened 2021-07-28 19:32 UTC by fkettelhoit

During a call with @Albertozhao today he mentioned that a code sample showing how to use Workers KV directly from a Rust worker could be a suitable addition to the existing docs. This PR is a tutorial that shows how to wrap a subset of the Workers KV API in rust and use it to create a worker that exposes simple get and put operations, with the following end result:

```sh
$ curl 'localhost:8787/foo'
""
$ curl -X PUT 'localhost:8787/foo?value=bar'
$ curl 'localhost:8787/foo'
"bar"
```

2021-07-28 21:05 UTC, koeninger commented on products/workers/src/content/tutorials/workers-kv-from-rust/index.md
> +    async fn put_text(&self, key: &str, value: &str, ttl: u64) -> Result<(), JsValue> {
The note below makes it clear you're not intending to handle all options, but I'd still suggest naming this parameter expirationTtl to match the option exactly, given that there are other options with ttl in the name.

2021-07-28 21:16 UTC, fkettelhoit commented on products/workers/src/content/tutorials/workers-kv-from-rust/index.md
> +    async fn put_text(&self, key: &str, value: &str, ttl: u64) -> Result<(), JsValue> {
Good point, done!

(I named it `expiration_ttl` to follow Rust's snake_case naming convention.)

2021-08-02 15:39 UTC, signalnerve commented
this is awesome!! do you mind doing a soft wrap instead of hard wrap throughout this file? will make it easier to review. we'll rope in some members of the team to check this out once i can take an initial look

2021-08-02 16:00 UTC, fkettelhoit commented
@signalnerve sure, done!

2021-08-02 17:00 UTC, fkettelhoit commented
By the way, the following PR might also be relevant in the context of Rust workers: https://github.com/cloudflare/wrangler-action/pull/61

(I'm mentioning it here since I wasn't sure how actively the wrangler-action repo is being maintained.)

2021-08-02 18:32 UTC, deadlypants1973 requested changes
Style guide revision.

2021-08-02 18:32 UTC, deadlypants1973 commented on products/workers/src/content/tutorials/workers-kv-from-rust/index.md
> +import TutorialsBeforeYouStart from "../../_partials/_tutorials-before-you-start.md"
```suggestion
import TutorialsBeforeYouStart from "../../_partials/_tutorials-before-you-start.md"

<TutorialsBeforeYouStart/>
```

2021-08-02 18:32 UTC, deadlypants1973 commented on products/workers/src/content/tutorials/workers-kv-from-rust/index.md
> +This tutorial will show you how to read and write to Workers KV directly from Rust, by using `wasm_bindgen` and a simple custom wrapper around the JS Workers KV API.
```suggestion
In this tutorial, you will learn how to read and write to Workers KV directly from Rust, by using `wasm_bindgen` and a simple custom wrapper around the JS Workers KV API.
```

2021-08-02 18:32 UTC, deadlypants1973 commented on products/workers/src/content/tutorials/workers-kv-from-rust/index.md
> +To get started, we will let `wrangler` generate a basic project using the [rustwasm-worker template](https://github.com/cloudflare/rustwasm-worker-template/), `cd` into it and use the current state o
```suggestion
To get started, run the following `wrangler` command to generate a basic project using the [rustwasm-worker template](https://github.com/cloudflare/rustwasm-worker-template/). After running the `wrangler generate` command, `cd` into the new project, and use the current state of the git repository as the initial commit by running the `git add` and `git commit` commands in your terminal:
```

2021-08-02 18:32 UTC, deadlypants1973 commented on products/workers/src/content/tutorials/workers-kv-from-rust/index.md
> +## Create & bind a KV namespace
```suggestion
## Create and bind a KV namespace
```

2021-08-02 18:32 UTC, deadlypants1973 commented on products/workers/src/content/tutorials/workers-kv-from-rust/index.md
> +To be able to access Workers KV, we need to define a binding for a particular KV namespace in `wrangler.toml`. If you do not have an existing namespace, you can quickly create one using wrangler. For
```suggestion
To be able to access Workers KV, define a binding for a particular KV namespace in the `wrangler.toml` file generated in your new project's directory. If you do not have an existing namespace, create one using `wrangler`. For example, a namespace called `KV_FROM_RUST` would be created by running:
```

2021-08-02 18:32 UTC, deadlypants1973 commented on products/workers/src/content/tutorials/workers-kv-from-rust/index.md
> +Now add this binding to `wrangler.toml`:
```suggestion
Now add this binding to the `wrangler.toml` file:
```

2021-08-02 18:32 UTC, deadlypants1973 commented on products/workers/src/content/tutorials/workers-kv-from-rust/index.md
> +We can now access this KV namespace as the variable `KV_FROM_RUST` in JS. To read or write from the namespace in Rust, we need to pass the whole object to our Rust handler function:
```suggestion
You can now access this KV namespace as the variable `KV_FROM_RUST` in JS. To read or write from the namespace in Rust, you need to pass the whole object to the Rust handler function:
```

2021-08-02 18:32 UTC, deadlypants1973 commented on products/workers/src/content/tutorials/workers-kv-from-rust/index.md
> +Note that the signature of our Rust handler differs from the template, which merely returns a `String` from Rust and keeps the request and response handling purely on the JS side. In this tutorial we
```suggestion
Note that the signature of your Rust handler differs from the template, which merely returns a `String` from Rust and keeps the request and response handling purely on the JS side. This tutorial will try to do as much as possible in Rust and thus pass the request directly to the wasm handler, which will then construct and return a response. To do this, declare `web-sys` as one of your Rust dependencies and explicitly enable the `Request`, `Response` and `ResponseInit` features (the `Url` and `UrlSearchParams` features will be used later in this tutorial):
```

2021-08-02 18:32 UTC, deadlypants1973 commented on products/workers/src/content/tutorials/workers-kv-from-rust/index.md
> +We can now use `Request` and `Response` in Rust to create a very simple handler that completely ignores the request and always responds with a `200 OK` status:
```suggestion
You can now use `Request` and `Response` in Rust to create a very simple handler that completely ignores the request and always responds with a `200 OK` status:
```

2021-08-02 18:32 UTC, deadlypants1973 commented on products/workers/src/content/tutorials/workers-kv-from-rust/index.md
> +We are now ready to create a type binding using `wasm_bindgen` to access the KV object. Since the KV API returns JS promises, we first need to add `wasm-bindgen-futures` and `js-sys` as dependencies:
```suggestion
You are now ready to create a type binding using `wasm_bindgen` to access the KV object. Since the KV API returns JS promises, you must first add `wasm-bindgen-futures` and `js-sys` as dependencies:
```

2021-08-02 18:32 UTC, deadlypants1973 commented on products/workers/src/content/tutorials/workers-kv-from-rust/index.md
> +Now we can add the wrapper and change the type of the `kv` argument of our handler accordingly:
```suggestion
Add the wrapper and change the type of the `kv` argument of your handler accordingly:
```

2021-08-02 18:32 UTC, deadlypants1973 commented on products/workers/src/content/tutorials/workers-kv-from-rust/index.md
> +We could start using the `kv` parameter as it is, but the function signatures generated by `wasm_bindgen` are somewhat cumbersome to work with in Rust. It thus makes sense to create a simple struct a
```suggestion
You could start using the `kv` parameter as it is, but the function signatures generated by `wasm_bindgen` are somewhat difficult to work with in Rust. For an easier experience, create a simple struct around the `WorkersKvJs` type that wraps it with a more Rust-friendly API:
```

2021-08-02 18:32 UTC, deadlypants1973 commented on products/workers/src/content/tutorials/workers-kv-from-rust/index.md
> +We can now finally use the wrapper to get and put values from and to our KV namespace. The following function is a simple example handler that writes the key `foo` with the value `bar` to KV if a `PU
```suggestion
You are now ready to use the wrapper to get and put values from and to our KV namespace. The following function is a simple example handler that writes the key `foo` with the value `bar` to KV if a `PUT` request is made to `/foo?value=bar` and reads and returns the value of key `foo` from KV if a `GET` request is made to `/foo` (note that `handle` is now async and that we are using the `Url` and `UrlSearchParams` features that we declared earlier in `Cargo.toml`):
```

2021-08-02 18:32 UTC, deadlypants1973 commented on products/workers/src/content/tutorials/workers-kv-from-rust/index.md
> +We can now run `wrangler preview`, `wrangler dev` or `wrangler publish` to test the worker. Here is an example invocation using `wrangler dev`:
```suggestion
Choose between [`wrangler preview`](/cli-wrangler/commands#preview), [`wrangler dev`](/cli-wrangler/commands#dev) or [`wrangler publish`](/cli-wrangler/commands#publish) to test the Worker. Here is an example invocation using `wrangler dev`:
```

2021-08-02 18:32 UTC, deadlypants1973 commented on products/workers/src/content/tutorials/workers-kv-from-rust/index.md
> +If you followed all the steps, the final `lib.rs` should look as follows:
```suggestion
With all previous steps complete, the final `lib.rs` should look as follows:
```

2021-08-06 16:18 UTC, signalnerve commented on products/workers/src/content/tutorials/workers-kv-from-rust/index.md
> +You are now ready to use the wrapper to get and put values from and to our KV namespace. The following function is a simple example handler that writes the key `foo` with the value `bar` to KV if a `
```suggestion
You are now ready to use the wrapper to get and put values from and to our KV namespace. The following function is a simple example handler that writes the key `foo` with the value `bar` to KV, if a `PUT` request is made to `/foo?value=bar`, and reads and returns the value of key `foo` from KV, if a `GET` request is made to `/foo`. Note that `handle` is now asynchronous, and that we are using the `Url` and `UrlSearchParams` features that we declared earlier in `Cargo.toml`:
```

2021-08-06 16:18 UTC, signalnerve commented on products/workers/src/content/tutorials/workers-kv-from-rust/index.md
> +Choose between [`wrangler preview`](/cli-wrangler/commands#preview), [`wrangler dev`](/cli-wrangler/commands#dev) or [`wrangler publish`](/cli-wrangler/commands#publish) to test the Worker. Here is a
```suggestion
You can use [`wrangler dev`](/cli-wrangler/commands#dev) to test the Worker:
```

2021-08-06 16:18 UTC, signalnerve commented on products/workers/src/content/tutorials/workers-kv-from-rust/index.md
> +```
Is there an example repo that can be linked down here in a conclusion paragraph?

2021-08-06 18:11 UTC, fkettelhoit commented on products/workers/src/content/tutorials/workers-kv-from-rust/index.md
> +```
I have now pushed the full example to https://github.com/fkettelhoit/workers-kv-from-rust and added a short note in the last paragraph. Feel free to move the code over to some Cloudflare repository, if you would prefer not to link to external repositories.

2021-08-09 11:22 UTC, deadlypants1973 reviewed
final review comments

2021-08-09 11:22 UTC, deadlypants1973 commented on products/workers/src/content/tutorials/workers-kv-from-rust/index.md
> +Let's also create a preview id so that we can use the namespace with `wrangler preview`:
```suggestion
Create a preview ID to use the namespace with `wrangler preview`:
```

2021-08-09 11:22 UTC, deadlypants1973 commented on products/workers/src/content/tutorials/workers-kv-from-rust/index.md
> +Now add this binding to the `wrangler.toml` file:
```suggestion
Add this binding to the `wrangler.toml` file:
```

2021-08-09 11:22 UTC, deadlypants1973 commented on products/workers/src/content/tutorials/workers-kv-from-rust/index.md
> +Note that the signature of your Rust handler differs from the template, which merely returns a `String` from Rust and keeps the request and response handling purely on the JS side. This tutorial will
```suggestion
Note that the signature of your Rust handler differs from the template, which merely returns a `String` from Rust and keeps the request and response handling purely on the JS side. This tutorial will try to do as much as possible in Rust and pass the request directly to the wasm handler, which will then construct and return a response. To do this, declare `web-sys` as one of your Rust dependencies and explicitly enable the `Request`, `Response` and `ResponseInit` features (the `Url` and `UrlSearchParams` features will be used later in this tutorial):
```

2021-08-09 11:22 UTC, deadlypants1973 commented on products/workers/src/content/tutorials/workers-kv-from-rust/index.md
> +You could start using the `kv` parameter as it is, but the function signatures generated by `wasm_bindgen` are somewhat difficult to work with in Rust. For an easier experience, create a simple struc
```suggestion
You could start using the `kv` parameter as is, but the function signatures generated by `wasm_bindgen` can be difficult to work within Rust. For an easier experience, create a simple struct around the `WorkersKvJs` type that wraps it with a more Rust-friendly API:
```

2021-08-09 11:23 UTC, deadlypants1973 approved these changes
Approved from style guide review but need @signalnerve to give final okay.

2021-08-11 18:40 UTC, signalnerve approved these changes

2021-08-12 15:03 UTC, merged