PCX-1042 SSL-Restore missing content
cloudflare/cloudflare-docs pull request #191
Opened 2020-10-28 18:49 UTC by aaron-ruby

## User story

Port the content for PCX-877 to the new cloudflare-docs Github repository so that customers have access to published content that was omitted when the SSL docs were migrated.

2020-11-11 17:09 UTC, adamschwartz commented on products/ssl/src/content/ssl-for-saas/status-codes/custom-csrs.md
>  order: 2
I would add a shorter frontmatter for the sidebar:

```txt
title: Custom CSRs
```

2020-11-11 17:10 UTC, adamschwartz requested changes
One small change.

2020-11-16 06:56 UTC, aaron-ruby commented on products/ssl/src/content/ssl-for-saas/status-codes/custom-csrs.md
>  order: 2
Done.

2020-11-16 17:19 UTC, adamschwartz requested changes

2020-11-16 17:19 UTC, adamschwartz commented on products/ssl/src/content/ssl-for-saas/issuing-certificates.md
> +```sh
The`sh` code block line should start with `$`. See:
https://developers.cloudflare.com/docs-engine/reference/markdown#terminals

2020-11-16 17:19 UTC, adamschwartz commented on products/ssl/src/content/ssl-for-saas/issuing-certificates.md
> +```sh
(The line below)

2020-11-16 23:32 UTC, adamschwartz approved these changes

2020-11-16 23:35 UTC, merged