Added section about multiple questions in DoH
cloudflare/cloudflare-docs pull request #1915
Opened 2021-07-30 10:28 UTC by marciocloudflare

Hi @vavrusa. This is the PR I made regarding how to ask multiple questions in DoH. Could you check it and see if everything makes sense? Thanks!

2021-07-30 16:48 UTC, vavrusa requested changes

2021-07-30 16:48 UTC, vavrusa commented on products/1.1.1.1/src/content/dns-over-https/request-structure.md
> +Sending more than one question when making requests using POST depends on the HTTP version used, as each DNS query maps to exactly one HTTP request. HTTP/2 and HTTP/3 have multiplexing and you can st
delete `using POST`

2021-07-30 17:08 UTC, vavrusa approved these changes

2021-08-02 08:46 UTC, pedrosousa approved these changes

2021-08-02 08:46 UTC, pedrosousa commented on products/1.1.1.1/src/content/dns-over-https/request-structure.md
> +**Sending multiple questions example:**
I'd use a shorter Heading 3 (`### Example`) or a full sentence (`The following example sends two questions in a query:`), avoiding the bold.

2021-08-02 08:46 UTC, pedrosousa commented on products/1.1.1.1/src/content/dns-over-https/request-structure.md
> +$ curl --http2 -H 'accept: application/dns-json' https://1.1.1.1/dns-query?name=cloudflare.com --next --http2 -H 'accept: application/dns-json' https://1.1.1.1/dns-query?name=cloudflare.com
Should the two questions be about the same domain (`cloudflare.com`)? Looks odd.

2021-08-02 08:46 UTC, pedrosousa commented on products/1.1.1.1/src/content/dns-over-https/request-structure.md
> +You can learn more about how DoH works in the RFC8484 document, more specifically [the HTTP layer requirements](https://datatracker.ietf.org/doc/html/rfc8484#section-5.2).
```suggestion
You can learn more about how DoH works in RFC 8484, more specifically [the HTTP layer requirements](https://datatracker.ietf.org/doc/html/rfc8484#section-5.2).
```

2021-08-02 08:51 UTC, marciocloudflare commented on products/1.1.1.1/src/content/dns-over-https/request-structure.md
> +**Sending multiple questions example:**
Will do

2021-08-02 08:51 UTC, marciocloudflare commented on products/1.1.1.1/src/content/dns-over-https/request-structure.md
> +$ curl --http2 -H 'accept: application/dns-json' https://1.1.1.1/dns-query?name=cloudflare.com --next --http2 -H 'accept: application/dns-json' https://1.1.1.1/dns-query?name=cloudflare.com
I'll double check with the engineer about this

2021-08-02 09:16 UTC, merged