[CF1] Limitations for lb tunnels
cloudflare/cloudflare-docs pull request #2010
Opened 2021-08-09 17:52 UTC by kodster28

Addresses https://jira.cfops.it/browse/PCX-1730

2021-08-09 18:14 UTC, kodster28 commented
Screenshot of output
![Screen Shot 2021-08-09 at 1 11 35 PM](https://user-images.githubusercontent.com/26727299/128753596-2f40cd90-719b-41c6-96da-3ad0090438bf.png)

2021-08-09 18:50 UTC, kodster28 commented on products/cloudflare-one/src/content/connections/connect-apps/routing-to-tunnel/lb.md
> +If you see dropped sessions when using Named Tunnels [running as replicas](/connections/connect-apps/run-tunnel/deploy-cloudflared-replicas), you will need to either enable Local Traffic Management o
What is the customer-facing name for `Local Traffic Management`?

2021-09-07 18:10 UTC, abracchi-tw commented on products/cloudflare-one/src/content/connections/connect-apps/routing-to-tunnel/lb.md
> +If you see dropped sessions when using Named Tunnels [running as replicas](/connections/connect-apps/run-tunnel/deploy-cloudflared-replicas), you will need to either enable Local Traffic Management o
@abelinkinbio @nmldiegues would love your help here! 😄

2021-09-08 16:26 UTC, gofish requested changes

2021-09-08 16:26 UTC, gofish commented on products/cloudflare-one/src/content/connections/connect-apps/routing-to-tunnel/lb.md
> +If you have a tunnel to a port or ssh port, you **cannot** run a TCP health check.
Technically this is permitted currently but not advisable, so we might use **should not**.

2021-09-08 16:26 UTC, gofish commented on products/cloudflare-one/src/content/connections/connect-apps/routing-to-tunnel/lb.md
> +Instead, set up a health check endpoint in `cloudflared` — for example, an ingress entry that returns a fixed http status response — and create an **HTTP** [monitor](https://developers.cloudflare.com
> for example, an ingress entry ...

This would benefit from an actual example, or a link back to the [ingress rules](https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/configuration/configuration-file/ingress) docs.
```yaml
ingress:
  - hostname: "*"
    path: "^/_healthcheck$"
    service: http_status:200
```

2021-09-08 16:26 UTC, gofish commented on products/cloudflare-one/src/content/connections/connect-apps/routing-to-tunnel/lb.md
> +If you see dropped sessions when using Named Tunnels [running as replicas](/connections/connect-apps/run-tunnel/deploy-cloudflared-replicas), you will need to either enable Local Traffic Management o
> If you see dropped sessions [...] set up each named tunnel as a separate origin

This phrasing is passive and potentially confusing, especially since it's not possible to configure a Named Tunnel as *multiple* origins within a pool. Perhaps something along these lines:

> Session affinity is maintained across an entire Named Tunnel as a Load Balancing origin, not between tunnel replicas. To maintain affinity to individual service instances behind tunnel replicas, use Local Traffic Management or use different Named Tunnel IDs.

2021-09-08 16:26 UTC, gofish commented on products/cloudflare-one/src/content/connections/connect-apps/routing-to-tunnel/lb.md
> +This issue is caused by how our load balancers identify tunnels. A named tunnel ID will be treated as a single origin (regardless of the number of replicas), meaning that [Session Affinity](https://d
This gives more detail about the restriction above, but has too much (slightly wrong) technical information and should not suggest that requests will reach the "incorrect origin server".

2021-09-08 16:26 UTC, gofish commented on products/cloudflare-one/src/content/connections/connect-apps/routing-to-tunnel/lb.md
> +Currently, `cloudflared` connections give preference to whichever data center was associated with the end user's first request. This behavior can impact how connections are weighted and traffic is di
Drop "Currently, " and add clarify that "preference" is given when the tunnel terminates in the same data center, i.e. there is a "local connection".

2021-09-08 16:26 UTC, gofish commented on products/cloudflare-one/src/content/connections/connect-apps/routing-to-tunnel/lb.md
> +- If running Named Tunnels (using a shared ID), set each tunnel up as a different origin
- If running Named Tunnels replicas, switch to separate Named Tunnels as distinct origins.

2021-09-09 14:58 UTC, kodster28 commented on products/cloudflare-one/src/content/connections/connect-apps/routing-to-tunnel/lb.md
> +This issue is caused by how our load balancers identify tunnels. A named tunnel ID will be treated as a single origin (regardless of the number of replicas), meaning that [Session Affinity](https://d
Howdy @gofish, I pushed some changes to (hopefully) address your comments. Let me know if I'm still missing the mark.

2021-09-10 16:29 UTC, gofish approved these changes
Looks great! Thanks Kody.

2021-09-10 17:13 UTC, dcpena approved these changes

2021-09-10 17:13 UTC, dcpena commented on products/cloudflare-one/src/content/connections/connect-apps/routing-to-tunnel/lb.md
> +The application will default to the Cloudflare settings of the hostname in your account that includes the Cloudflare Tunnel Load Balancer records, including [cache rules](https://support.cloudflare.c
"The application will default to the Cloudflare settings of the hostname in your account that includes the Cloudflare Tunnel Load Balancer records" feels kinda roundabout. 

Would something like "The application will default to the hostname's Cloudflare settings that include the Cloudflare Tunnel Load Balancer records" help a bit?

2021-09-10 17:13 UTC, dcpena commented on products/cloudflare-one/src/content/connections/connect-apps/routing-to-tunnel/lb.md
> +The application will default to the Cloudflare settings of the hostname in your account that includes the Cloudflare Tunnel Load Balancer records, including [cache rules](https://support.cloudflare.c
```suggestion
The application will default to the Cloudflare settings of the hostname in your account that includes the Cloudflare Tunnel Load Balancer records, including [cache rules](https://developers.cloudflare.com/cache/best-practices/customize-cache) and [firewall policies](https://developers.cloudflare.com/firewall/). You can changes these settings for your hostname in Cloudflare's dashboard.
```

2021-09-10 17:13 UTC, dcpena commented on products/cloudflare-one/src/content/connections/connect-apps/routing-to-tunnel/lb.md
> +The solution depends on the type of tunnel being used:
We should use bulleted lists for three or more items.

2021-09-10 19:03 UTC, merged