[Pages] Sphinx framework guide fix
cloudflare/cloudflare-docs pull request #2021
Opened 2021-08-10 12:58 UTC by deadlypants1973

2021-08-16 15:10 UTC, signalnerve requested changes

2021-08-16 15:10 UTC, signalnerve commented on products/pages/src/content/framework-guides/deploy-a-sphinx-site.md
> +### Installing Sphinx
In this case, the initial header is correct - can we update in the style we prefer, but keep the idea of "Creating a Sphinx project directory"?

2021-08-17 16:59 UTC, deadlypants1973 commented on products/pages/src/content/framework-guides/deploy-a-sphinx-site.md
> +### Installing Sphinx
I edited it according to this https://github.com/cloudflare/cloudflare-docs/pull/1876#pullrequestreview-725827484

2021-08-17 17:00 UTC, deadlypants1973 commented on products/pages/src/content/framework-guides/deploy-a-sphinx-site.md
> +### Installing Sphinx
It seems like "### Creating a Sphinx project directory" needs to go later in the tutorial

2021-08-18 18:39 UTC, signalnerve commented on products/pages/src/content/framework-guides/deploy-a-sphinx-site.md
> +### Installing Sphinx
I think we install sphinx on L100, maybe @jeffh-cloudflare can clarify what he has in mind here?

2021-08-18 19:44 UTC, jeffh-cloudflare commented on products/pages/src/content/framework-guides/deploy-a-sphinx-site.md
> +### Installing Sphinx
I think this is an issue of use of us not using consistent terminology (my bad):

There are three operations as part of installing/configuring Sphinx:

1. Create a directory on local filesystem used for managing the project
2. Installing sphinx with Pipenv
3. Running sphinx-quickstart - that creates the actual Sphinx Project (this is where I think the terminology goes sideways) :-)

Does that help? I apologize - the GitHub repository workflow is very confusing to me.

2021-08-23 19:48 UTC, closed without merging