Add new page for logging from Workers
cloudflare/cloudflare-docs pull request #2107
Opened 2021-08-18 21:36 UTC by jkup

1. I split Debugging Workers out into 2 pages: Debugging Workers (covers `wrangler dev`) and Logging from Workers (covers `wrangler tail`).
2. Rearranged the order to put the new page directly below Debugging Workers.
3. Added new sections to Logging from Workers (Intro, Adding custom logs, Accessing production logs with the dashboard)

cc @deadlypants1973 for content review! Would love any advice you have :)

2021-08-19 13:32 UTC, deadlypants1973 requested changes
PCX revision

2021-08-19 13:32 UTC, deadlypants1973 commented on products/workers/src/content/learning/logging-workers.md
> +The Workers platform captures all `console.log`'s and uncaught exceptions, in addition to information about the event itself. All of this can be viewed with either `wrangler tail` or the dashboard.
```suggestion
The Workers platform captures all `console.log`'s and uncaught exceptions, in addition to information about the event itself. All of this can be viewed with either `wrangler tail` or on the dashboard through your **Account Home** > **Workers** > your **Workers script** > **Logs**.
```

2021-08-19 13:32 UTC, deadlypants1973 commented on products/workers/src/content/learning/logging-workers.md
> +If you deploy that, run `wrangler tail`, and then access the Worker, it will display:
```suggestion
Deploy the above code, run `wrangler tail` in your terminal, and then access your Worker. It will display:
```

2021-08-19 13:32 UTC, deadlypants1973 commented on products/workers/src/content/learning/logging-workers.md
> +Here is an example of a Worker with a `console.log` inside the request handler.
Is this sentence saying that if someone runs the below script it will do the action of 'adding a custom log'?

2021-08-19 13:32 UTC, deadlypants1973 commented on products/workers/src/content/learning/logging-workers.md
> +With your Workers application deployed, you may want to inspect incoming traffic. This can be useful for situations where a user is running into issues or errors that you can’t reproduce. `wrangler t
```suggestion
With your Workers application deployed, you may want to inspect incoming traffic. This can be useful for situations where a user is running into issues or errors that they cannot reproduce. `wrangler tail` allows developers to “tail” their Workers application’s logs, giving real-time access to information about incoming requests.
```

2021-08-19 13:32 UTC, deadlypants1973 commented on products/workers/src/content/learning/logging-workers.md
> +You can also view the production logs associated with any Worker from the [Cloudflare dashboard](https://dash.cloudflare.com?to=/:account/workers/overview). Click on any Worker and then click "Logs."
```suggestion
You can also view the production logs associated with any Worker by [logging into the Cloudflare dashboard](https://dash.cloudflare.com?to=/:account/workers/overview). From your **Account Home** > go to *Workers** > select your **Worker script** > and select **Logs**. Logging is available for all customers, from free to enterprise plans.
```

2021-08-19 13:32 UTC, deadlypants1973 commented on products/workers/src/content/learning/logging-workers.md
> +- These logs are not stored. You can start and stop the stream at any time to view them, but they do not persist.
```suggestion
- Workers logs are not stored. You can start and stop the stream at any time to view them, but they do not persist.
```

2021-08-19 13:32 UTC, deadlypants1973 commented on products/workers/src/content/learning/logging-workers.md
> +- Logs from any [Durable Objects](/learning/using-durable-objects) your Worker is using will show up here.
```suggestion
- Logs from any [Durable Objects](/learning/using-durable-objects) your Worker is using will show up in the dashboard.
```

2021-08-19 13:32 UTC, deadlypants1973 commented on products/workers/src/content/learning/logging-workers.md
> +Other 11xx errors generally indicate a problem with the Workers runtime itself — please check our [status page](https://www.cloudflarestatus.com) if you see one.
```suggestion
Other 11xx errors generally indicate a problem with the Workers runtime itself — refer to the [status page](https://www.cloudflarestatus.com) if you are experiencing an error.
```

2021-08-19 13:32 UTC, deadlypants1973 commented on products/workers/src/content/learning/logging-workers.md
> +Additionally, you can find out whether your application is experiencing any downtime, or returning any errors by navigating to Workers Metrics in the dashboard.
```suggestion
You can find out whether your application is experiencing any downtime, or returning any errors by navigating from *Account Home** > to **Workers** > your **Worker script** > **Metrics** in the dashboard.
```

2021-08-19 13:32 UTC, deadlypants1973 commented on products/workers/src/content/learning/logging-workers.md
> +Once you’ve identified your Workers application is returning exceptions, you can use `wrangler tail` to inspect, and fix the exceptions.
```suggestion
After you have identified your Workers application is returning exceptions, use `wrangler tail` to inspect, and fix the exceptions.
```

2021-08-19 13:32 UTC, deadlypants1973 commented on products/workers/src/content/learning/logging-workers.md
> +Exceptions will show up under the `exceptions` field in the JSON returned by `wrangler tail`. Once you’ve identified the exception that is causing errors, you may redeploy your code with a fix, and c
```suggestion
Exceptions will show up under the `exceptions` field in the JSON returned by `wrangler tail`. After you have identified the exception that is causing errors, redeploy your code with a fix, and continue trailing the logs to confirm that it is fixed.
```

2021-08-19 13:32 UTC, deadlypants1973 commented on products/workers/src/content/learning/logging-workers.md
> +Exceptions will show up under the `exceptions` field in the JSON returned by `wrangler tail`. Once you’ve identified the exception that is causing errors, you may redeploy your code with a fix, and c
By 'trailing' are we saying 'reviewing' or does this have a different meaning?

2021-08-19 13:32 UTC, deadlypants1973 commented on products/workers/src/content/learning/logging-workers.md
> +When logging using this strategy, remember that outstanding asynchronous tasks are canceled as soon as a Worker finishes sending its main response body to the client. To ensure that a logging subrequ
```suggestion
When logging using this strategy, remember that outstanding asynchronous tasks are canceled as soon as a Worker finishes sending its main response body to the client. To ensure that a logging subrequest completes, pass the request promise to [`event.waitUntil()`](https://developer.mozilla.org/en-US/docs/Web/API/ExtendableEvent/waitUntil). For example:
```

2021-08-19 13:32 UTC, deadlypants1973 commented on products/workers/src/content/learning/logging-workers.md
> +By using `event.passThroughOnException`, your Workers application will pass requests to your origin if it throws an exception. This allows you to add logging, tracking, or other features with Workers
```suggestion
By using [`event.passThroughOnException`](/runtime-apis/fetch-event#methods), your Workers application will pass requests to your origin if it throws an exception. This allows you to add logging, tracking, or other features with Workers, without degrading your website’s functionality.
```

2021-08-19 16:41 UTC, jkup commented on products/workers/src/content/learning/logging-workers.md
> +Exceptions will show up under the `exceptions` field in the JSON returned by `wrangler tail`. Once you’ve identified the exception that is causing errors, you may redeploy your code with a fix, and c
This is existing content that I moved to a new file, but I believe it's a typo and supposed to say "continue tailing the logs".

cc @signalnerve

2021-08-19 16:56 UTC, jkup commented on products/workers/src/content/learning/logging-workers.md
> +Here is an example of a Worker with a `console.log` inside the request handler.
Yes! Maybe change to:

"You can add custom logs to your Worker with `console.log`. Any `console.log`'s you add will show up in both the dashboard and `wrangler tail`. Here is an example of a Worker with a custom log inside the request handler."

Or something like that?

2021-08-19 19:01 UTC, signalnerve reviewed
amazing! few things to note but this is definitely on the right track, congrats on (i think?) your first PR!

2021-08-19 19:01 UTC, signalnerve commented on products/workers/src/content/learning/logging-workers.md
> +### Identifying error: Workers Metrics
```suggestion
### Identifying errors: Workers Metrics
```

2021-08-19 19:01 UTC, signalnerve commented on products/workers/src/content/learning/logging-workers.md
> +Exceptions will show up under the `exceptions` field in the JSON returned by `wrangler tail`. Once you’ve identified the exception that is causing errors, you may redeploy your code with a fix, and c
I think it's supposed to be tailing too!

2021-08-19 19:01 UTC, signalnerve commented on products/workers/src/content/learning/logging-workers.md
> +You can also view the production logs associated with any Worker from the [Cloudflare dashboard](https://dash.cloudflare.com?to=/:account/workers/overview). Click on any Worker and then click "Logs."
would be awesome to have a screenshot here!

2021-08-19 20:48 UTC, lukeed commented on products/workers/src/content/learning/logging-workers.md
> +Here is an example of a Worker with a `console.log` inside the request handler.
```suggestion
Any `console.log` statements within your Worker will appear within `wrangler tail` and the dashboard output. The following example demonstrates a custom `console.log` within a Worker request handler.
```

2021-08-19 20:48 UTC, lukeed commented on products/workers/src/content/learning/logging-workers.md
> +})
```suggestion
})

```

2021-08-19 20:48 UTC, lukeed commented on products/workers/src/content/learning/logging-workers.md
> +With your Workers application deployed, you may want to inspect incoming traffic. This can be useful for situations where a user is running into issues or errors that they cannot reproduce. `wrangler
```suggestion
With your Workers application deployed, you may want to inspect incoming traffic. This may be useful in situations where a user is running into production issues that you cannot easily reproduce. In these instances, `wrangler tail` allows developers to “tail” their Workers application’s logs, giving real-time insight into their application's incoming requests.
```

2021-08-19 20:48 UTC, lukeed commented on products/workers/src/content/learning/logging-workers.md
> +You can also view the production logs associated with any Worker by [logging into the Cloudflare dashboard](https://dash.cloudflare.com?to=/:account/workers/overview). From your **Account Home** > go
```suggestion
You can also view the production logs associated with any Worker by [logging into the Cloudflare dashboard](https://dash.cloudflare.com?to=/:account/workers/overview). From your **Account Home** > go to *Workers** > select your **Worker script** > and select **Logs**. Logging is available for all customers, including those on the free plan.
```

2021-08-19 20:48 UTC, lukeed commented on products/workers/src/content/learning/logging-workers.md
> +Other 11xx errors generally indicate a problem with the Workers runtime itself — refer to the [status page](https://www.cloudflarestatus.com) if you are experiencing an error.
```suggestion
Other `11xx` errors generally indicate a problem with the Workers runtime itself. Please refer to the [status page](https://www.cloudflarestatus.com) if you are experiencing an error.
```

2021-08-19 20:48 UTC, lukeed commented on products/workers/src/content/learning/logging-workers.md
> +After you have identified your Workers application is returning exceptions, use `wrangler tail` to inspect, and fix the exceptions.
```suggestion
After you have identified your Workers application is returning exceptions, use `wrangler tail` to inspect and fix the exceptions.
```

2021-08-19 20:48 UTC, lukeed commented on products/workers/src/content/learning/logging-workers.md
> +When logging using this strategy, remember that outstanding asynchronous tasks are canceled as soon as a Worker finishes sending its main response body to the client. To ensure that a logging subrequ
```suggestion
When using an external logging strategy, remember that outstanding asynchronous tasks are canceled as soon as a Worker finishes sending its main response body to the client. To ensure that a logging subrequest completes, pass the request promise to [`event.waitUntil()`](https://developer.mozilla.org/en-US/docs/Web/API/ExtendableEvent/waitUntil). For example:
```

2021-08-19 20:48 UTC, lukeed commented on products/workers/src/content/learning/logging-workers.md
> +  // or may not complete.
```suggestion
  // Without event.waitUntil(), the `postLog` function may or may not complete.
```

2021-08-19 20:48 UTC, lukeed commented on products/workers/src/content/learning/logging-workers.md
> +By using [`event.passThroughOnException`](/runtime-apis/fetch-event#methods), your Workers application will pass requests to your origin if it throws an exception. This allows you to add logging, tra
```suggestion
By using [`event.passThroughOnException`](/runtime-apis/fetch-event#methods), a Workers application will forward requests to your origin if an exception is thrown during the Worker's execution. This allows you to add logging, tracking, or other features with Workers, without degrading your website’s functionality.
```

2021-08-19 20:48 UTC, lukeed commented on products/workers/src/content/learning/logging-workers.md
> +
```suggestion
```

2021-08-19 20:54 UTC, jkup commented
Incorporated all the changes!

cc @deadlypants1973 @signalnerve @lukeed

2021-08-19 21:16 UTC, lukeed approved these changes
🎉

2021-08-20 00:09 UTC, Electroid reviewed
Yay, this is awesome! ❤️  I added a few nit suggestions.

2021-08-20 00:09 UTC, Electroid commented on products/workers/src/content/learning/logging-workers.md
> +  const { city, country  } = cf
```suggestion
  const { city, country } = cf
```
nit: there was an extra space

2021-08-20 00:09 UTC, Electroid commented on products/workers/src/content/learning/logging-workers.md
> +## Accessing production logs with `wrangler tail`
```suggestion
## View logs using `wrangler tail`
```

2021-08-20 00:09 UTC, Electroid commented on products/workers/src/content/learning/logging-workers.md
> +## Accessing production logs with the dashboard
```suggestion
## View logs from the dashboard
```

2021-08-20 00:09 UTC, Electroid commented on products/workers/src/content/learning/logging-workers.md
> +You can access logs and exceptions for your Workers from the dashboard and via `wrangler tail`.
```suggestion
You can access logs and exceptions for your Workers using the dashboard or `wrangler tail`.
```

2021-08-20 00:15 UTC, jkup commented
@Electroid love it! updated!

2021-08-20 12:33 UTC, deadlypants1973 requested changes
round 2

2021-08-20 12:33 UTC, deadlypants1973 commented on products/workers/src/content/learning/logging-workers.md
> +You can also view the production logs associated with any Worker by [logging into the Cloudflare dashboard](https://dash.cloudflare.com?to=/:account/workers/overview). From your **Account Home** > go
```suggestion
You can review the production logs associated with any Worker by [logging into the Cloudflare dashboard](https://dash.cloudflare.com?to=/:account/workers/overview). From your **Account Home** > go to *Workers** > select your **Worker script** > and select **Logs**. Logging is available for all customers, including those on the free plan.
```

2021-08-20 12:33 UTC, deadlypants1973 commented on products/workers/src/content/learning/logging-workers.md
> +Other `11xx` errors generally indicate a problem with the Workers runtime itself. Please refer to the [status page](https://www.cloudflarestatus.com) if you are experiencing an error.
```suggestion
Other `11xx` errors generally indicate a problem with the Workers runtime itself. Refer to the [status page](https://www.cloudflarestatus.com) if you are experiencing an error.
```

2021-08-20 12:33 UTC, deadlypants1973 commented on products/workers/src/content/learning/logging-workers.md
> +You can find out whether your application is experiencing any downtime, or returning any errors by navigating from *Account Home** > to **Workers** > your **Worker script** > **Metrics** in the dashb
```suggestion
You can find out whether your application is experiencing any downtime, or returning any errors by navigating from **Account Home** > to **Workers** > your **Worker script** > **Metrics** in the dashboard.
```

2021-08-20 12:33 UTC, deadlypants1973 commented on products/workers/src/content/learning/logging-workers.md
> +<!-- TODO: include screenshots -->
Is this still happening?

2021-08-20 12:33 UTC, deadlypants1973 commented on products/workers/src/content/learning/logging-workers.md
> +<!-- TODO: include example -->
And this.

2021-08-20 12:33 UTC, deadlypants1973 commented on products/workers/src/content/learning/logging-workers.md
> +A Worker can make HTTP requests to any HTTP service on the public internet. You can use a service like [Sentry](https://sentry.io) to collect error logs from your Worker, by making an HTTP request to
```suggestion
A Worker can make HTTP requests to any HTTP service on the public Internet. You can use a service like [Sentry](https://sentry.io) to collect error logs from your Worker, by making an HTTP request to the service to report the error. Refer to your service’s API documentation for details on what kind of request to make.
```

2021-08-20 12:33 UTC, deadlypants1973 commented on products/workers/src/content/learning/logging-workers.md
> +A Worker can make HTTP requests to any HTTP service on the public internet. You can use a service like [Sentry](https://sentry.io) to collect error logs from your Worker, by making an HTTP request to
Internet is always capitalized at CF. Blog and docs rule.

2021-08-20 12:33 UTC, deadlypants1973 commented on products/workers/src/content/learning/logging-workers.md
> +### Go to Origin on Error
```suggestion
### Go to origin on error
```

2021-08-20 12:33 UTC, deadlypants1973 commented on products/workers/src/content/learning/logging-workers.md
> +### Setup a logging service
```suggestion
### Set up a logging service
```

2021-08-20 12:33 UTC, deadlypants1973 commented on products/workers/src/content/learning/logging-workers.md
> +You can access logs and exceptions for your Workers using the dashboard or `wrangler tail`.
```suggestion
You can access logs and exceptions for your Workers using the dashboard or [`wrangler tail`](/cli-wrangler/commands#tail).
```

2021-08-20 12:33 UTC, deadlypants1973 commented on products/workers/src/content/learning/logging-workers.md
> +You can customize how `wrangler tail` works to fit your needs: see [the docs](/cli-wrangler/commands#tail) for available configuration options.
```suggestion
You can customize how `wrangler tail` works to fit your needs: refer to [the `wrangler tail` documentation](/cli-wrangler/commands#tail) for available configuration options.
```

2021-08-20 12:33 UTC, deadlypants1973 commented on products/workers/src/content/learning/logging-workers.md
> +By using [`event.passThroughOnException`](/runtime-apis/fetch-event#methods), a Workers application will forward requests to your origin if an exception is thrown during the Worker's execution. This
```suggestion
By using [`event.passThroughOnException`](/runtime-apis/fetch-event#methods), a Workers application will forward requests to your origin if an exception is thrown during the Worker's execution. This allows you to add logging, tracking, or other features with Workers, without degrading your application's functionality.
```
Is 'website' being referred to here the application that the Workers script is running on? In that case, it is best to switch to 'application'.

2021-08-20 12:33 UTC, deadlypants1973 commented on products/workers/src/content/learning/logging-workers.md
> +With your Workers application deployed, you may want to inspect incoming traffic. This may be useful in situations where a user is running into production issues that you cannot easily reproduce. In
```suggestion
With your Workers application deployed, you may want to inspect incoming traffic. This may be useful in situations where a user is running into production issues that they cannot easily reproduce. In these instances, `wrangler tail` allows developers to “tail” their Workers application’s logs, giving real-time insight into their application's incoming requests.
```
Fixing for subject-verb agreement, unless 'user' and 'you' is referring to 'end user' and 'developer' here.

2021-08-20 12:33 UTC, deadlypants1973 commented on products/workers/src/content/learning/logging-workers.md
> +After you deploy the above code, run `wrangler tail` in your terminal, and then access your Worker. It will display:
Sorry @jkup , can we specify 'it'?

2021-08-20 16:08 UTC, jkup commented
@deadlypants1973 updated!

2021-08-20 18:19 UTC, signalnerve approved these changes

2021-08-23 16:40 UTC, deadlypants1973 approved these changes

2021-08-23 17:42 UTC, merged