clearer instructions when using workers subdomain
cloudflare/cloudflare-docs pull request #2120
Opened 2021-08-20 12:56 UTC by stephanwesten

Note that the command `wrangler preview --watch` directed me to example.com. So changes I made the index.html were not reflected.

2021-08-20 14:32 UTC, deadlypants1973 reviewed
content revision

2021-08-20 14:32 UTC, deadlypants1973 commented on products/workers/src/content/platform/sites/start-from-scratch.md
> +5. Decide where you’d like to publish your site to: [a workers.dev subdomain](/get-started/guide#configure-for-deploying-to-workersdev) or your [personal domain](/get-started/guide#optional-configure
```suggestion
5. Choose whether you would like to publish your site to: [a `*.workers.dev` subdomain](/get-started/guide#configure-for-deploying-to-workersdev) or your [personal domain](/get-started/guide#optional-configure-for-deploying-to-a-registered-domain) registered with Cloudflare. Then, update your `wrangler.toml` file accordingly:
```

2021-08-20 14:32 UTC, deadlypants1973 commented on products/workers/src/content/platform/sites/start-from-scratch.md
> +
```suggestion
Configure `route` to match your `*.workers.dev` subdomain: 

  ```toml
  route = "your-workers-subdomain.workers.dev/*"
  ```

```

2021-08-20 14:32 UTC, deadlypants1973 commented on products/workers/src/content/platform/sites/start-from-scratch.md
> +  **workers.dev**: Make sure `workers_dev` is set to true. This is the default.
```suggestion
  **`*.workers.dev`**: Make sure `workers_dev` is set to true. This is the default.
```

2021-08-20 19:35 UTC, lukeed requested changes
I thi

2021-08-20 19:35 UTC, lukeed commented on products/workers/src/content/platform/sites/start-from-scratch.md
> +5. Choose whether you would like to publish your site to: [a `*.workers.dev` subdomain](/get-started/guide#configure-for-deploying-to-workersdev) or your [personal domain](/get-started/guide#optional
While this _could be_ said for the original text, the new text makes it sound like you can **only** pick one or the other.

When `workers_dev` is true, then it deploys to the subdomain & all routes are assumed. I'm fairly certain it cannot be modified and/or narrowed down to explicit paths on the subdomain.

You must define a `zone_id` and `route` (or `routes`) combination in order to deploy to a custom zone.

2021-08-20 19:35 UTC, lukeed commented on products/workers/src/content/platform/sites/start-from-scratch.md
> +  **`*.workers.dev`**: Make sure `workers_dev` is set to true. This is the default.
It is not on by default: https://developers.cloudflare.com/workers/cli-wrangler/configuration#keys

```suggestion
  **`*.workers.dev`**: Enable the `workers_dev` configuration.
```

2021-08-20 19:35 UTC, lukeed commented on products/workers/src/content/platform/sites/start-from-scratch.md
> +  route = "your-workers-subdomain.workers.dev/*"
```suggestion
  workers_dev = true
```

2021-08-20 19:35 UTC, lukeed commented on products/workers/src/content/platform/sites/start-from-scratch.md
> +  Or
lol – what to do here?

```suggestion
  And/Or
```

2021-09-13 16:01 UTC, lukeed approved these changes

2021-09-13 17:25 UTC, deadlypants1973 reviewed
content review

2021-09-13 17:25 UTC, deadlypants1973 commented on products/workers/src/content/platform/sites/start-from-scratch.md
>    <Aside>
```suggestion
  <Aside type="note">
```

2021-09-13 17:25 UTC, deadlypants1973 commented on products/workers/src/content/platform/sites/start-from-scratch.md
> +  __Note:__ Check out documentation on [Routes](/platform/routes) to configure `route` properly.
```suggestion
Refer to the documentation on [Routes](/platform/routes) to configure `route` properly.
```

2021-09-13 17:26 UTC, deadlypants1973 approved these changes

2021-09-14 16:07 UTC, deadlypants1973 commented on products/workers/src/content/platform/sites/start-from-scratch.md
> +    Refer to the documentation on [Routes](/platform/routes) to configure `route` properly.
```suggestion
Refer to the documentation on [Routes](/platform/routes) to configure `route` properly.
```

2021-09-14 16:49 UTC, lukeed commented
@deadlypants1973 The markdown parsing here is unhappy. I know spacing looks off, but this is the (currently) the build error, which signifies that it thinks the list item is closing sooner than it should be:

<img width="422" alt="Screen Shot 2021-09-14 at 9 47 04 AM" src="https://user-images.githubusercontent.com/5855893/133300063-9b13d6e4-d4d6-4f3e-9a39-9072abf9fcf0.png">

2021-09-14 17:01 UTC, lukeed commented
This PR is now building correctly. The failing CI has to do with "Publish preview" failing, which is failing because external forks are not given access to the base repo's CI secrets.

Thank you!

2021-09-14 17:01 UTC, merged