Adding new guide for the 11ty framework
cloudflare/cloudflare-docs pull request #2125
Opened 2021-08-20 22:12 UTC by jkup

I copy / pasted from https://developers.cloudflare.com/pages/framework-guides/deploy-a-gatsby-site and made some changes. I also deployed a demo of it to https://11ty-pages.pages.dev/ but wasn't sure if it would be appropriate to link to that or not?

cc @rita3ko @deadlypants1973

2021-08-20 22:18 UTC, lukeed approved these changes

2021-08-20 22:24 UTC, rita3ko requested changes
Looks great! Left a couple minor edits / suggestions.

2021-08-20 22:24 UTC, rita3ko commented on products/pages/src/content/framework-guides/deploy-an-eleventy-site.md
> +Eleventy is a simpler static site generator. In this guide, you will create a new Eleventy site and deploy it using Cloudflare Pages. You will be using the `eleventy` CLI to create a new Eleventy sit
s/ simpler / simple

2021-08-20 22:24 UTC, rita3ko commented on products/pages/src/content/framework-guides/deploy-an-eleventy-site.md
> +Eleventy is a simpler static site generator. In this guide, you will create a new Eleventy site and deploy it using Cloudflare Pages. You will be using the `eleventy` CLI to create a new Eleventy sit
(we seem to be inconsistent about doing this across the different guides, but would be good to link to eleventy's site)

2021-08-20 22:24 UTC, rita3ko commented on products/pages/src/content/framework-guides/deploy-an-eleventy-site.md
> +There are a lot of [starter projects](https://www.11ty.dev/docs/starter/) available on the Eleventy website. As an example, use the `eleventy-base-blog` project by running the following commands in y
```suggestion
There are a lot of [starter projects](https://www.11ty.dev/docs/starter/) available on the Eleventy website. As an example, use the `eleventy-base-blog` project by running the following commands in your terminal:
```

2021-08-21 01:29 UTC, jkup commented
@rita3ko updated!

2021-08-21 01:58 UTC, rita3ko approved these changes
woot!

2021-08-23 18:18 UTC, merged