Clarify Pages caching behavior
cloudflare/cloudflare-docs pull request #2177
Opened 2021-08-31 00:41 UTC by Albertozhao

This tells Pages users how to ensure the latest build gets served. Sometimes pre-existing cache settings/Page Rules can mess with the default caching behavior for Pages, leading to stale assets being served.

2021-08-31 00:55 UTC, jkup approved these changes
Looks good to me! As a customer, I'm always curious why my cache % is lower than I'd like it to be!

2021-08-31 01:23 UTC, rita3ko commented on products/pages/src/content/platform/serving-pages.md
> +As much as possible, Pages sets `ETag` and `If-None-Match` headers to allow clients to also cache content in their browsers — for more details on these behaviors, refer to the MDN [HTTP Caching page]
we should be able to provide more clarity than "As much as possible". Can we say anything more specific about why we wouldn't? And why that's the approach we take to caching.

2021-08-31 01:59 UTC, jkup commented on products/pages/src/content/platform/serving-pages.md
> +As much as possible, Pages sets `ETag` and `If-None-Match` headers to allow clients to also cache content in their browsers — for more details on these behaviors, refer to the MDN [HTTP Caching page]
That's a good point. Also, for the "Gzip and Brotli" section - I think that's configureable via the Dashboard? Is it Gzip by default and you can upgrade to Brotli on the Speed page. Or is Brotli a Pro only feature?

2021-08-31 19:49 UTC, Albertozhao commented on products/pages/src/content/platform/serving-pages.md
> +As much as possible, Pages sets `ETag` and `If-None-Match` headers to allow clients to also cache content in their browsers — for more details on these behaviors, refer to the MDN [HTTP Caching page]
@rita3ko totally, we definitely can elaborate more, but just going to double check with Cina on how much to publicly disclose once he's back from break. 

@jkup that section is referring to the pre-processing of assets we do during the build step, not the zone settings that allow other compression options. But that definitely should be explained more clearly. :)

2021-09-01 15:20 UTC, deadlypants1973 commented on products/pages/src/content/platform/serving-pages.md
> +If Page Rules or other cache settings are used on your custom domain, that may lead to stale assets being served after a new build. You can resolve this quickly by clicking <a href="https://developer
```suggestion
If Page Rules or other cache settings are used on your custom domain, that may lead to stale assets being served after a new build. You can resolve this by clicking <a href="https://developers.cloudflare.com/cache/how-to/purge-cache#purge-everything">Purge Everything</a> in **Caching** > **Configuration** within the dashboard to ensure the latest build gets served."
```

2021-09-01 15:21 UTC, deadlypants1973 commented on products/pages/src/content/platform/serving-pages.md
> +Pages includes good caching defaults. That means that every time you deploy an asset to Pages, it remains cached on the Cloudflare CDN until your next deploy.
```suggestion
Pages includes good caching defaults. Every time you deploy an asset to Pages, the asset remains cached on the Cloudflare CDN until your next deployment. 
```

2021-09-14 20:11 UTC, lukeed reviewed
I've seen the question of Pages caching & Range requests (`206`) come up a few times. Maybe that's worth mentioning here too?

2021-09-14 20:38 UTC, lukeed commented on products/pages/src/content/platform/serving-pages.md
> +Pages currently returns `200` responses for HTTP range requests, however, the team is working on adding support for `206` and other responses.
```suggestion
Pages currently returns `200` responses for HTTP range requests; however, the team is working on adding spec-compliant `206` partial responses.
```

2021-09-14 21:06 UTC, lukeed approved these changes

2021-09-14 22:01 UTC, rita3ko requested changes

2021-09-14 22:01 UTC, rita3ko commented on products/pages/src/content/platform/serving-pages.md
> +Pages includes highly performant caching defaults, so you should avoid setting Page Rules or custom caching on your site. Every time you deploy an asset to Pages, the asset remains cached on the Clou
```suggestion
Pages comes with built in caching defaults that are optimized for caching as much as possible, while providing the most up to date content. Every time you deploy an asset to Pages, the asset remains cached on the Cloudflare CDN until your next deployment. Therefore, you should avoid setting Page Rules or custom caching on your site. 
```

2021-09-15 17:10 UTC, merged

2022-04-09 14:10 UTC, johtso commented
Is there any update on support for range requests? Does Cloudflare Pages currently not support range requests at all?

2023-01-11 15:26 UTC, rickybassom commented
I'm also interested in when range requests will be supported. Is there any news on this?