2021 icon update 1
cloudflare/cloudflare-docs pull request #2202
Opened 2021-09-01 22:22 UTC by gganch

Part 1 of the process of moving to a new way to display and use icons. 

In this PR: Still using the old process of requiring in and using cloudflare-brand-assets but with the new svgs included in all of the product folders in order to prep for step 2

After merging this piece of code, part 2 will be to merge in new code for clooudflare-docs-engine.

Part 3, 4 will be going back to the 2 repos and removing the old way of displaying icons and adding in the new way officially.

2021-09-10 15:31 UTC, jrf0110 requested changes

2021-09-10 15:31 UTC, jrf0110 commented on developers.cloudflare.com/gatsby-node.js
> +const {products} = require('./current-products-list')
Probably need to run prettier on this file

2021-09-10 15:31 UTC, jrf0110 commented on developers.cloudflare.com/gatsby-node.js
> +      const data = fs.readFileSync(`../products/${product.icon}/src/content/icons/${product.icon}.svg` , 'utf8')
It's generally best practice when working with file paths in scripts to use a combination of `path.join` and `__dirname` to get to the correct path you're looking for. This smooths over any ambiguities around script execution directory vs current directory.

```javascript

const path = require('path')

...
const data = fs.readFileSync(
  path.join(
    __dirname,
    'src/content/icons',
    `${product.icon}.svg`
  ), 'utf8')

```

2021-09-10 15:31 UTC, jrf0110 commented on developers.cloudflare.com/gatsby-node.js
> +       let dataStr = data.toString()
```suggestion
       const logoSVGContent = data.toString()
```

2021-09-10 15:31 UTC, jrf0110 commented on developers.cloudflare.com/gatsby-node.js
> +         logoSVGContent: dataStr,
```suggestion
         logoSVGContent,
```

2021-09-10 15:31 UTC, jrf0110 commented on developers.cloudflare.com/src/components/product-grid.js
> +const ProductsQuery = () => {
Since this returns the result of a hook `useStaticQuery`, this function is a hook too. By convention, you should prefix hook names with `use`

```suggestion
const useProducts = () => {
```

2021-09-10 15:31 UTC, jrf0110 commented on developers.cloudflare.com/src/components/product-grid.js
> +          wrap
Do we need `href` as well?

2021-09-10 15:31 UTC, jrf0110 commented on developers.cloudflare.com/src/components/product-grid.js
> +  const productsData = ProductsQuery()
Probably comment this out too

2021-09-10 15:31 UTC, jrf0110 commented on developers.cloudflare.com/src/css/components/product-grid.css
> +  fill: #6d767b;
Do we not have variables for colors?

2021-09-10 15:31 UTC, jrf0110 commented on products/1.1.1.1/docs-config.js
> +  logoSVGContent: fs.readFileSync(`../src/content/icons/1.1.1.1.svg` , 'utf8'),
Should path and __dirname here too

```suggestion
  logoSVGContent: fs.readFileSync(path.join(__dirname, 'src/content/icons/1.1.1.1.svg') , 'utf8'),
```

2021-09-10 17:04 UTC, gganch commented on developers.cloudflare.com/src/components/product-grid.js
> +  const productsData = ProductsQuery()
commented out!

2021-09-10 20:55 UTC, gganch commented on developers.cloudflare.com/src/components/product-grid.js
> +          wrap
yes including it in query

2021-09-10 20:56 UTC, gganch commented on developers.cloudflare.com/src/css/components/product-grid.css
> +  fill: #6d767b;
global vars are in cloudflare-brand-assets repo and this color is not currently in global.css

2021-09-10 21:29 UTC, gganch commented on developers.cloudflare.com/gatsby-node.js
> +      const data = fs.readFileSync(`../products/${product.icon}/src/content/icons/${product.icon}.svg` , 'utf8')
changed!

2021-09-14 13:20 UTC, pedrosousa commented on products/bots/docs-config.js
> +    path.join(__dirname, `../src/content/icons/${productIconKey}.svg`),
@gganch You should probably remove the `../` path segment, since `src` is a sub-folder of the current folder (`/products/bots`). The same applies to other products.

2021-09-14 14:35 UTC, pedrosousa commented on products/ruleset-engine/docs-config.js
> +const path = require("path");
@gganch I had to add this require for `path.join(...)` used below.

Also, the build is still outputting some GraphQL-related errors. This is probably affecting other products and not just `ruleset-engine`:
`Cannot query field "fields" on type "Mdx".`
`Cannot query field "headings" on type "Mdx".`
`Cannot query field "tableOfContents" on type "Mdx".`

Here's a failing build: https://github.com/cloudflare/cloudflare-docs/runs/3599358966

2021-09-17 15:35 UTC, gganch commented on products/bots/docs-config.js
> +    path.join(__dirname, `../src/content/icons/${productIconKey}.svg`),
removed!

2021-09-17 15:36 UTC, gganch commented on products/ruleset-engine/docs-config.js
> +const path = require("path");
these failures were caused due to the corresponding cloudflare-docs-engine not being merged in, but updated all products to also require path

2021-09-21 22:24 UTC, jrf0110 commented on developers.cloudflare.com/src/components/product-grid.js
> +        <svg viewBox="0 0 48 48"><path d={$[product.icon]}/></svg>
At some point (feel free to do it now), we should fix this little almost-bug where we'er passing `product.icon` in as an array `[product.icon]`

Since `Array.prototype.toString`'s implementation just joins each element's result of `*.prototype.toString` by comma. Since this array only has one item, the result is just `product.icon.toString()`

2021-09-22 08:43 UTC, pedrosousa commented on developers.cloudflare.com/src/components/product-grid.js
> +        <svg viewBox="0 0 48 48"><path d={$[product.icon]}/></svg>
It seems that here we're accessing a property of the `$` object (defined in line 30). The exact property name is defined by the value of `product.icon`.

2021-09-22 22:06 UTC, jrf0110 commented on developers.cloudflare.com/src/components/product-grid.js
> +        <svg viewBox="0 0 48 48"><path d={$[product.icon]}/></svg>
Oh lawd you're right. I was thinking this was inside of a template literal string!

2021-09-22 22:15 UTC, jrf0110 approved these changes

2021-09-23 08:50 UTC, abracchi-tw approved these changes

2021-09-24 03:48 UTC, merged