[Workers] Update changelog with recent release notes
cloudflare/cloudflare-docs pull request #2211
Opened 2021-09-03 10:37 UTC by harrishancock

Pulled from https://community.cloudflare.com/tag/workersreleasenotes

2021-09-03 13:42 UTC, a-robinson approved these changes

2021-09-03 14:49 UTC, deadlypants1973 requested changes
Content style guide changes

2021-09-03 14:49 UTC, deadlypants1973 commented on products/workers/src/content/platform/changelog.md
> +- The crypto.randomUUID() method can be used to generate a new random version 4 UUID.
```suggestion
- The `crypto.randomUUID()` method can be used to generate a new random version 4 UUID.
```

2021-09-03 14:49 UTC, deadlypants1973 commented on products/workers/src/content/platform/changelog.md
> +- Durable Objects are now scheduled more evenly around a colo.
```suggestion
- Durable Objects are now scheduled more evenly around a colocation (colo).
```

2021-09-03 14:49 UTC, deadlypants1973 commented on products/workers/src/content/platform/changelog.md
> +- Fixed a hang in Durable Objects when reading more than 16MB of data at once (for example, with a large list() operation).
```suggestion
- Fixed a hang in Durable Objects when reading more than 16MB of data at once (for example, with a large `list()` operation).
```

2021-09-03 14:49 UTC, deadlypants1973 commented on products/workers/src/content/platform/changelog.md
> +- Added a new compatibility flag `html_rewriter_treats_esi_include_as_void_tag` which causes `HTMLRewriter` to treat `<esi:include>` and `<esi:comment>` as void tags, such that they are considered to
```suggestion
- Added a new compatibility flag `html_rewriter_treats_esi_include_as_void_tag` which causes `HTMLRewriter` to treat `<esi:include>` and `<esi:comment>` as void tags, such that they are considered to have neither an end tag nor nested content. To opt a worker into the new behavior, you must use wrangler 1.19.0 or newer and specify the flag in `wrangler.toml`. Refer to the [wrangler compatibility flag notes](https://github.com/cloudflare/wrangler/pull/2009) for details.
```

2021-09-03 14:49 UTC, deadlypants1973 commented on products/workers/src/content/platform/changelog.md
> +- Major changes to Durable Objects implementation, the details of which will be the subject of an upcoming blog post. In theory, the changes should not harm existing apps, except to make them faster.
```suggestion
- Major changes to Durable Objects implementation, the details of which will be the subject of an upcoming blog post. In theory, the changes should not harm existing apps, except to make them faster. Let your account team know if you observe anything odd or report your issue in the [Workers Discord](https://discord.gg/cloudflaredev).
```

2021-09-03 14:49 UTC, deadlypants1973 commented on products/workers/src/content/platform/changelog.md
> +- Durable Object constructors may now initiate I/O, such as fetch() calls.
```suggestion
- Durable Object constructors may now initiate I/O, such as `fetch()` calls.
```

2021-09-03 14:49 UTC, deadlypants1973 commented on products/workers/src/content/platform/changelog.md
> +- Added Durable Objects state.blockConcurrencyWhile() API useful for delaying delivery of requests and other events while performing some critical state-affecting task. For example, this can be used
```suggestion
- Added Durable Objects `state.blockConcurrencyWhile()` API useful for delaying delivery of requests and other events while performing some critical state-affecting task. For example, this can be used to perform start-up initialization in an object’s constructor.
```

2021-09-03 14:49 UTC, deadlypants1973 commented on products/workers/src/content/platform/changelog.md
> +- In Durable Objects, the callback passed to storage.transaction() can now return a value, which will be propagated as the return value of the transaction() call.
```suggestion
- In Durable Objects, the callback passed to `storage.transaction()` can now return a value, which will be propagated as the return value of the `transaction()` call.
```

2021-09-03 14:49 UTC, deadlypants1973 commented on products/workers/src/content/platform/changelog.md
>  - The preview service now prints a warning in the devtools console when a script uses Response/Request.clone() but does not read one of the cloned bodies. Such a situation forces the runtime to buffe
```suggestion
- The preview service now prints a warning in the devtools console when a script uses `Response/Request.clone()` but does not read one of the cloned bodies. Such a situation forces the runtime to buffer the entire message body in memory, which reduces performance. [Find an example here](https://cloudflareworkers.com/#823fbe463bfafd5a06bcfeabbdf5eeae:https://tutorial.cloudflareworkers.com).
```

2021-09-03 20:54 UTC, signalnerve commented
thank you so much for doing this!!!

2021-09-07 16:12 UTC, deadlypants1973 commented on products/workers/src/content/platform/changelog.md
> +- Major changes to Durable Objects implementation, the details of which will be the subject of an upcoming blog post. In theory, the changes should not harm existing apps, except to make them faster.
```suggestion
- Major changes to Durable Objects implementation, the details of which will be the subject of an upcoming blog post. In theory, the changes should not harm existing apps, except to make them faster. Let your account team know if you observe anything unusal or report your issue in the [Workers Discord](https://discord.gg/cloudflaredev).
```

2021-09-07 16:12 UTC, deadlypants1973 approved these changes

2021-09-07 21:19 UTC, merged