DRAFT : Performance inprovement options
cloudflare/cloudflare-docs pull request #2230
Opened 2021-09-07 13:59 UTC by Ekwuno

Documenting upcoming speed week improvements to pages.

2021-09-08 15:52 UTC, WalshyDev commented on products/pages/src/content/platform/performace-improvements.md
> +Polish improves image loading time by optimizing image hosted on your “domain.pages.dev”. It reduces image file size by removing metadata(date and time, camera manufacturer, model, etc.) by compressi
```suggestion
Polish improves image loading time by optimizing image hosted on your “domain.pages.dev”. It reduces image file size by removing metadata (date and time, camera manufacturer, model, etc.) by compressing images where possible, smaller images mean faster load time for images and web apps.
```
Spacing

2021-09-08 15:52 UTC, WalshyDev commented on products/pages/src/content/platform/performace-improvements.md
> +Lossless image option reduces the size of image files without impacting the visual quality. In this option, metadata is removed from PNG, GIF and JPEG but the lossless compression is done on GIF and
```suggestion
Lossless image option reduces the size of image files without impacting the visual quality. In this option, metadata is removed from PNG, GIF and JPEG but the lossless compression is done on GIF and PNG.
```
Consistency

2021-09-08 15:52 UTC, WalshyDev commented on products/pages/src/content/platform/performace-improvements.md
> +This polish option, reduces the file size of JPEG images using lossy compression which may reduce image quality
```suggestion
This polish option, reduces the file size of JPEG images using lossy compression which may reduce image quality.
```
Consistency

2021-09-14 17:47 UTC, deadlypants1973 requested changes
pcx review

2021-09-14 17:47 UTC, deadlypants1973 commented on products/pages/src/content/platform/performace-improvements.md
> +## Brotli compression.
```suggestion
## Brotli compression
```

2021-09-14 17:47 UTC, deadlypants1973 commented on products/pages/src/content/platform/performace-improvements.md
> +**Note: ** If you have a custom domain tied to your Pages project, configuring your performance settings in the Speed tab will override the performance settings configured in Pages.
```suggestion
<Aside type="note">

If you have a custom domain tied to your Pages project, configuring your performance settings in **Speed** on the Cloudflare dashbaord will override the performance settings configured in Pages. 

</Aside>
```

2021-09-14 17:47 UTC, deadlypants1973 commented on products/pages/src/content/platform/performace-improvements.md
> +Cloudflare applies Brotli compression to help speed up page load times for your visitors.  Brotli compression is selected as the preferred content encoding method if multiple compression methods are
```suggestion
Cloudflare applies [Brotli](https://www.brotli.pro/) compression to help speed up page load times for your visitors. Brotli compression is selected as the preferred content-encoding method if multiple compression methods are supported by the client. If the client does not indicate that Brotli is supported, the gzip compression will be applied. 
```

2021-09-14 17:47 UTC, deadlypants1973 commented on products/pages/src/content/platform/performace-improvements.md
> +This option is automatically turned on for all Pages sites and cannot be turned off through the Pages dashboard.
```suggestion
The Brotli compression option is automatically turned on for all Pages sites and cannot be turned off in the **Pages** dashboard.
```

2021-09-14 17:47 UTC, deadlypants1973 commented on products/pages/src/content/platform/performace-improvements.md
> +However, if your project is tied to a custom domain, you may adjust your Brotli settings in the Speed tab.
```suggestion
However, if your project is tied to a custom domain, you may adjust your Brotli settings in **Speed** > **Optimization** > moving the **Brotli** toggle to **Off*.
```

2021-09-14 17:47 UTC, deadlypants1973 commented on products/pages/src/content/platform/performace-improvements.md
> +You can learn more about [how cloudflare handles compression](https://support.cloudflare.com/hc/en-us/articles/200168396-What-will-Cloudflare-compress-) in this support document.
```suggestion
You can learn more about [how Cloudflare handles compression by reviewing this support article](https://support.cloudflare.com/hc/en-us/articles/200168396-What-will-Cloudflare-compress-).
```

2021-09-14 17:47 UTC, deadlypants1973 commented on products/pages/src/content/platform/performace-improvements.md
> +Polish improves image loading time by optimizing images hosted on your [domain].pages.dev. It reduces image file size by removing metadata (date and time, camera manufacturer, model, etc.) by compres
```suggestion
Polish improves image loading time by optimizing images hosted on your `*.pages.dev`site. It reduces image file size by removing metadata (date and time, camera manufacturer, model, etc.) by compressing images where possible. Smaller images result in faster load time for images and web applications. 
```

2021-09-14 17:47 UTC, deadlypants1973 commented on products/pages/src/content/platform/performace-improvements.md
> +There are two options for configuration with different performance effects on images -- Lossless and Lossy.
```suggestion
There are two options for configuration with different performance effects on images -- _Lossless_ and _Lossy_. You can choose between these two options by going to **Speed** > **Optimization** > **Polish**.
```

2021-09-14 17:47 UTC, deadlypants1973 commented on products/pages/src/content/platform/performace-improvements.md
> +This polish option, reduces the file size of JPEG images using lossy compression which may reduce image quality.
```suggestion
This Polish option reduces the file size of JPEG images using lossy compression which may reduce image quality.
```

2021-09-14 17:47 UTC, deadlypants1973 commented on products/pages/src/content/platform/performace-improvements.md
> +> Making the decision on what form of optimization to use is mostly based on use case. There are a lot of resources to show [the differnce between lossy and lossless image compression](https://imagif
```suggestion
> Making the decision on what form of optimization to use is mostly based on your individual use case. You can review the variety of resources to learn more about [the difference between Lossy and Lossless image compression on Imagify's blog](https://imagify.io/blog/lossless-vs-lossy-image-compression/).
```

2021-09-14 17:47 UTC, deadlypants1973 commented on products/pages/src/content/platform/performace-improvements.md
> +> Making the decision on what form of optimization to use is mostly based on use case. There are a lot of resources to show [the differnce between lossy and lossless image compression](https://imagif
Is there a reason this has a > ?

2021-09-14 17:47 UTC, deadlypants1973 commented on products/pages/src/content/platform/performace-improvements.md
> +Whether you are choosing Lossy or Lossless, you also have the option of enabling WebP for your images. If the client requesting the image supports the WebP image codec, Cloudflare will serve a WebP v
```suggestion
Whether you choose _Lossy_ or _Lossless_, you also have the option of enabling WebP for your images. If the client requesting the image supports the WebP image codec, Cloudflare will serve a WebP version of the image if offering a performance advantage over the existing format. 
```

2021-09-14 17:47 UTC, deadlypants1973 commented on products/pages/src/content/platform/performace-improvements.md
> +Whether you are choosing Lossy or Lossless, you also have the option of enabling WebP for your images. If the client requesting the image supports the WebP image codec, Cloudflare will serve a WebP v
There are two 'if' clauses here which is w bit confusing. Can we reword this for clarity?

2021-09-14 17:47 UTC, deadlypants1973 commented on products/pages/src/content/platform/performace-improvements.md
> +**Note: ** Large Jpeg images are converted to progressive images. Visitors will see increasingly detailed images as file is downloaded.
```suggestion
Large JPEG images are converted to progressive images with WebP enabled. Visitors will see increasingly detailed images as the file is downloaded. 
```

2021-09-14 17:47 UTC, deadlypants1973 commented on products/pages/src/content/platform/performace-improvements.md
> +By default, all new projects will have Polish enabled with the Lossy and WebP setting. Navigate to the Settings, then General to update or add your configuration.
Is this happening on the CF dashboard? or somewhere else?

2021-09-14 17:49 UTC, Ekwuno commented on products/pages/src/content/platform/performace-improvements.md
> +By default, all new projects will have Polish enabled with the Lossy and WebP setting. Navigate to the Settings, then General to update or add your configuration.
Yea, this happens oh the CF dashboard

2021-09-14 22:44 UTC, Ekwuno commented on products/pages/src/content/platform/performace-improvements.md
> +> Making the decision on what form of optimization to use is mostly based on use case. There are a lot of resources to show [the differnce between lossy and lossless image compression](https://imagif
I was trying to highlight this section, I think the Aside component should be better for this.

2021-09-14 22:54 UTC, CryptoGodfatherVA approved these changes

2021-09-15 15:08 UTC, deadlypants1973 requested changes

2021-09-15 15:08 UTC, deadlypants1973 commented on products/pages/src/content/platform/performace-improvements.md
> +Cloudflare Pages now includes performance improvements to serve pages of your projects by removing the overhead on media assets and offering compressions.
```suggestion
Cloudflare Pages now includes performance improvements by removing the overhead on media assets and offering image compression. 
```

2021-09-15 15:08 UTC, deadlypants1973 commented on products/pages/src/content/platform/performace-improvements.md
> +By default, all new projects will have Polish enabled with the Lossy and WebP setting.  Navigate to the Settings, then General to update or add your configuration.
```suggestion
By default, all new projects will have Polish enabled with the _Lossy_ and the **WebP** setting.  To update your configuration, log into the Cloudflare dashboard and go to **Speed** > **Optimization** > **Polish**.
```

2021-09-15 15:08 UTC, deadlypants1973 commented on products/pages/src/content/platform/performace-improvements.md
> +If you have a custom domain tied to your Pages project, configuring your performance settings in **Speed** on the Cloudflare dashbaord will override the performance settings configured in Pages.
```suggestion
If you have a custom domain set up in your Pages project, configuring your performance settings in **Speed** on the Cloudflare dashboard will override the performance settings configured in Pages. 
```

2021-09-15 16:17 UTC, nevikashah commented on products/pages/src/content/platform/performace-improvements.md
> +By default, all new projects will have Polish enabled with the Lossy and WebP setting. Navigate to the Settings, then General to update or add your configuration.
@deadlypants1973 it happens within the Pages dash

2021-09-15 16:36 UTC, nevikashah commented on products/pages/src/content/platform/performace-improvements.md
> +Whether you choose _Lossy_ or _Lossless_, you also have the option of enabling WebP for your images. If the client requesting the image supports the WebP image codec, Cloudflare will serve a WebP ver
```suggestion
```

2021-09-15 16:38 UTC, nevikashah commented on products/pages/src/content/platform/performace-improvements.md
> +
```suggestion
```
removing this section to add webp description under lossy as that will be the only option supporting webp

2021-09-15 16:39 UTC, nevikashah commented on products/pages/src/content/platform/performace-improvements.md
> +This Polish option reduces the file size of JPEG images using lossy compression which may reduce image quality.
```suggestion
This Polish option reduces the file size of JPEG images using lossy compression which may reduce image quality. Using Lossy also enables WebP for your images. If the client requesting the image supports the WebP image codec, Cloudflare will serve a WebP version of the image if offering a performance advantage over the existing format.
```

moving webp info to lossy

2021-09-15 16:41 UTC, nevikashah commented on products/pages/src/content/platform/performace-improvements.md
> +</Aside>
```suggestion
```

move this to the lossy section

2021-09-15 16:47 UTC, deadlypants1973 requested changes

2021-09-15 16:47 UTC, deadlypants1973 commented on products/pages/src/content/platform/performace-improvements.md
> +Cloudflare Pages now includes performance improvements by removing the overhead on media assets and offering image compression.
```suggestion
Cloudflare Pages supports performance improvement by removing the overhead on media assets and offering image compression. 
```

2021-09-15 16:47 UTC, deadlypants1973 commented on products/pages/src/content/platform/performace-improvements.md
> +If you have a custom domain set up in your Pages project, configuring your performance settings in **Speed** on the Cloudflare dashboard will override the performance settings configured in Pages.
```suggestion
If you have a custom domain set up in your Pages project, configuring your performance settings in **Speed** on the Cloudflare dashboard will override the performance settings configured in your **Pages project**. 
```

2021-09-15 16:47 UTC, deadlypants1973 commented on products/pages/src/content/platform/performace-improvements.md
> +Cloudflare applies [Brotli](https://www.brotli.pro/) compression to help speed up page load times for your visitors. Brotli compression is selected as the preferred content-encoding method if multipl
```suggestion
Cloudflare applies [Brotli](https://www.brotli.pro/) compression to speed up load times for your visitors. If multiple compression methods are supported by the client, Brotli compression is selected as the preferred content-encoding method. If the client does not indicate that Brotli is supported, the gzip compression will be applied. 
```

2021-09-15 16:47 UTC, deadlypants1973 commented on products/pages/src/content/platform/performace-improvements.md
> +However, if your project is tied to a custom domain, you may adjust your Brotli settings in **Speed** > **Optimization** > moving the **Brotli** toggle to **Off*.
```suggestion
However, if your Pages project has a custom domain set up, you may adjust your Brotli settings in the Cloudflare dashboard by going to **Speed** > **Optimization** > moving the **Brotli** toggle to **Off*.
```

2021-09-15 16:47 UTC, deadlypants1973 commented on products/pages/src/content/platform/performace-improvements.md
> +Polish improves image loading time by optimizing images hosted on your `*.pages.dev`site. It reduces image file size by removing metadata (date and time, camera manufacturer, model, etc.) by compress
```suggestion
Polish improves image load time by optimizing images hosted on your `*.pages.dev`site. Polish reduces image file size by removing metadata (such as date, time, camera manufacturer, model) by compressing images where possible. Smaller file size results in faster load time for images and web applications. 
```

2021-09-15 16:47 UTC, deadlypants1973 commented on products/pages/src/content/platform/performace-improvements.md
> +There are two options for configuration with different performance effects on images -- _Lossless_ and _Lossy_. You can choose between these two options by going to **Speed** > **Optimization** > **P
```suggestion
There are two options for Polish configuration -- _Lossless_ and _Lossy_ -- with different performance effects on images. You can choose between these two options by going to **Speed** > **Optimization** > **Polish**.
```

2021-09-15 16:47 UTC, deadlypants1973 commented on products/pages/src/content/platform/performace-improvements.md
> +Lossless image option reduces the size of image files without impacting the visual quality. In this option, metadata is removed from PNG, GIF and JPEG but the lossless compression is done on GIF and
```suggestion
The _Lossless_ Polish option reduces the size of image files without impacting the visual quality. With _Lossless_, metadata is removed from PNG, GIF, and JPEGs but the Lossless compression is applied to  GIF and PNGs only.
```

2021-09-15 16:47 UTC, deadlypants1973 commented on products/pages/src/content/platform/performace-improvements.md
> +Lossless image option reduces the size of image files without impacting the visual quality. In this option, metadata is removed from PNG, GIF and JPEG but the lossless compression is done on GIF and
Is this saying that metadata is removed but compression is not applied to JPEGs? I edited the sentence to reflect this.

2021-09-15 16:47 UTC, deadlypants1973 commented on products/pages/src/content/platform/performace-improvements.md
> +This Polish option reduces the file size of JPEG images using lossy compression which may reduce image quality.
```suggestion
The _Lossy_ Polish option reduces the file size of JPEG images using Lossy compression. This option may reduce image quality.
```

2021-09-15 16:47 UTC, deadlypants1973 commented on products/pages/src/content/platform/performace-improvements.md
> +Making the decision on what form of optimization to use is mostly based on your individual use case. You can review the variety of resources to learn more about [the difference between Lossy and Loss
```suggestion
Your individual use case will determine which form of optimization is right for your project. You can refer to [the difference between Lossy and Lossless image compression on Imagify's blog](https://imagify.io/blog/lossless-vs-lossy-image-compression/) to learn more about which option is right for you.
```

2021-09-15 20:22 UTC, neynah commented
Really excited about this! In the dashboard we're going to link to `https://developers.cloudflare.com/pages/platform/performance-improvements`. However, it looks like there might be a small typo in your file name `performace-improvements.md`.

2021-09-15 20:27 UTC, Ekwuno commented
@neynah I'll rename it now! Thanks for pointing this out 😅

2021-09-15 21:41 UTC, londonzhang commented on products/pages/src/content/platform/performace-improvements.md
> +If you have a custom domain set up in your Pages project, configuring your performance settings in **Speed** on the Cloudflare dashboard will override the performance settings configured in Pages.
In the UI we are using "precedence" instead of "override" to make it clear that it doesn't impact the Pages setting itself.

What about

"performance settings configured in **Speed** on the Cloudflare dashboard will take precedence for that domain."

2021-09-15 21:53 UTC, londonzhang commented on products/pages/src/content/platform/performace-improvements.md
> +Polish improves image loading time by optimizing images hosted on your `*.pages.dev`site. It reduces image file size by removing metadata (date and time, camera manufacturer, model, etc.) by compress
Polish will be turned on for all domains on the Pages project including pages.dev site.

How do you feel about

"Polish improves image load time by optimizing images hosted on your project's domains."

2021-09-15 22:00 UTC, londonzhang commented on products/pages/src/content/platform/performace-improvements.md
> +Making the decision on what form of optimization to use is mostly based on your individual use case. You can review the variety of resources to learn more about [the difference between Lossy and Loss
How do we feel about linking to Cloudflare docs instead? (https://support.cloudflare.com/hc/en-us/articles/360000607372-Using-Cloudflare-Polish-to-compress-images) In case there are differences between Cloudflare Lossless/Lossy and Imagify docs.

2022-07-20 17:50 UTC, KimJ15 commented
This PR was opened before the developer doc site was moved to Cloudflare Pages. There are many conflicting branches. I'm going to close it now, but feel free to open a new issue or ask any questions.

2022-07-20 17:50 UTC, closed without merging