Document cron triggers wrangler config format
cloudflare/cloudflare-docs pull request #227
Opened 2020-11-02 21:07 UTC by ObsidianMinor

cc: @sgraden

2020-11-02 23:50 UTC, adamschwartz requested changes
Small formatting nit, otherwise LGTM.

2020-11-02 23:50 UTC, adamschwartz commented on products/workers/src/content/cli-wrangler/configuration.md
> +   * A set of cron expressions, where each expression is a separate schedule to run the Worker on.
Indentation needs cleanup.

2020-11-03 22:17 UTC, adamschwartz approved these changes
LGTM

2020-11-04 17:21 UTC, mkevanz approved these changes

2020-11-04 21:16 UTC, merged