Add delete site from Cloudflare section
cloudflare/cloudflare-docs pull request #2374
Opened 2021-09-24 16:11 UTC by Ekwuno

Adding a section to address #2271.

2021-10-06 17:09 UTC, deadlypants1973 requested changes

2021-10-06 17:09 UTC, deadlypants1973 commented on products/pages/src/content/get-started/index.md
> +The Cloudflare dashboard has a list of services that your pages project can leverage on, such as Analytics, speed, and, SSL/TLS. When trying to remove your project from Cloudfalre you will not be abl
```suggestion
If your DNS is handled by Cloudflare, you must delete any custom domain associated with your Pages project before removing your project from the **Pages** dashboard.  
```

2021-10-06 17:09 UTC, deadlypants1973 commented on products/pages/src/content/get-started/index.md
> +
```suggestion
Log in to the Cloudflare dashboard and use the **Account Home** or drop-down menu to select your website.
```

2021-10-06 17:09 UTC, deadlypants1973 commented on products/pages/src/content/get-started/index.md
> +and click on **remove site from Cloudflare** this will bring up a modal and if you confirm, your site will be deleted from Cloudflare.
```suggestion
After you select your website, you will be directed to **Overview** on the dashboard. On **Overview**:
1. Scroll down to **Advanced Actions**.
2. Select **Remove Site from Cloudflare**.
3. To delete your website from Cloudflare, select **Confirm**.
```

2021-10-06 17:09 UTC, deadlypants1973 commented on products/pages/src/content/get-started/index.md
> +Now if you return to the pages dashboard and go to **settings** > **delete project**. You can now remove your project from Cloudflare pages.
```suggestion
Go back to the **Account Home** or use the drop-down menu at the top of the dashboard and select **Pages**. You can now remove your project by selecting your **Pages project** > **Settings** > **Delete project**.
```

2021-10-07 16:25 UTC, kristianfreeman commented on products/pages/src/content/get-started/index.md
> +The Cloudflare dashboard has a list of services that your pages project can leverage on, such as Analytics, speed, and, SSL/TLS. When trying to remove your project from Cloudfalre you will not be abl
general note - make sure we use `Pages` not `pages` when opening PRs!

2021-10-08 16:37 UTC, Ekwuno commented on products/pages/src/content/get-started/index.md
> +The Cloudflare dashboard has a list of services that your pages project can leverage on, such as Analytics, speed, and, SSL/TLS. When trying to remove your project from Cloudfalre you will not be abl
Got it!

2021-10-08 18:42 UTC, BOYKHMER commented on products/pages/src/content/get-started/index.md
> +The Cloudflare dashboard has a list of services that your pages project can leverage on, such as Analytics, speed, and, SSL/TLS. When trying to remove your project from Cloudfalre you will not be abl
https://api.bscscan.com/api
   ?module=account
   &action=balancehistory
   &address=0x0DB011018728D1B91dDB3C77933a40B9B68C9fa7
   &blockno=2000000
   &apikey=YourApiKeyToken

2021-10-14 18:15 UTC, kristianfreeman approved these changes

2021-10-14 18:15 UTC, signalnerve commented
@Ekwuno lgtm, merge when ready

2021-10-18 14:18 UTC, deadlypants1973 approved these changes

2021-10-18 14:19 UTC, merged