Marcio/images merge single tile
cloudflare/cloudflare-docs pull request #2423
Opened 2021-10-01 10:46 UTC by marciocloudflare

Merge Cloudflare Images and Image Resizing into a single tile

2021-10-04 11:35 UTC, sejoker requested changes

2021-10-04 11:35 UTC, sejoker commented on products/images/src/content/faq.md
> +Cloudflare Images is an end-to-end solution that offers storage, resizing, optimization, and delivery. Image Resizing only offers resizing and optimization.
We need to rewrite the answer in terms of following criteria's:
- where images are stored
- differences in billing
- differences in delivery
- differences in available optimizations
- differences in availability

## where images are stored
Cloudflare Images (CI) - we store images at Cloudflare
Image resizing (IR) - images can be stored anywhere on the Internet with public access.

## differences in billing
CI - billing for cache misses
IR - billing for images served (regardless cached or not), and images stored

## differences in delivery
CI - images served from imagedelivdery.net
IR - images served from customers domain on Cloudflare 


## differences in available optimizations
CI - https://developers.cloudflare.com/images/resizing-images
IR - https://developers.cloudflare.com/image-resizing/url-format#options

## differences in availability
CI - any plan
IR - Pro, Biz, Ent.

2021-10-04 11:35 UTC, sejoker commented on products/images/src/content/index.md
> +Optimize and serve images in a fast and secure manner.
We need to rewrite the answer in terms of following criteria's:
- where images are stored
- differences in billing
- differences in delivery
- differences in available optimizations
- differences in availability

## where images are stored
Cloudflare Images (CI) - we store images at Cloudflare
Image resizing (IR) - images can be stored anywhere on the Internet with public access.

## differences in billing
CI - billing for cache misses
IR - billing for images served (regardless cached or not), and images stored

## differences in delivery
CI - images served from imagedelivdery.net
IR - images served from customers domain on Cloudflare 


## differences in available optimizations
CI - https://developers.cloudflare.com/images/resizing-images
IR - https://developers.cloudflare.com/image-resizing/url-format#options

## differences in availability
CI - any plan
IR - Pro, Biz, Ent.

2021-10-04 11:35 UTC, sejoker commented on products/images/src/content/faq.md
>  ## How much does Cloudflare Images cost?
If we talk about Cloudflare Images cost we should add section: "How much does Image resizing cost?"

2021-10-04 11:35 UTC, sejoker commented on products/images/src/content/faq.md
> -title: FAQ
this FAQ to Cloudflare Images specific. We should move it under Cloudflare Images section.

2021-10-12 14:34 UTC, marciocloudflare commented on products/images/src/content/faq.md
> +Cloudflare Images is an end-to-end solution that offers storage, resizing, optimization, and delivery. Image Resizing only offers resizing and optimization.
I've added this info to the FAQ

2021-10-12 14:36 UTC, marciocloudflare commented on products/images/src/content/index.md
> +Optimize and serve images in a fast and secure manner.
I've added a link to the FAQ and explained readers can learn more about the differences regarding the two products there

2021-10-12 14:37 UTC, marciocloudflare commented on products/images/src/content/faq.md
>  ## How much does Cloudflare Images cost?
I've removed the cost from this because the dev docs shouldn't have info regarding pricing.

2021-10-12 14:38 UTC, marciocloudflare commented on products/images/src/content/faq.md
> -title: FAQ
I've changed this to reflect it

2021-10-18 09:25 UTC, marciocloudflare commented
Closing due to conflicts and opening new PR

2021-10-18 09:25 UTC, closed without merging