Re-work the tutorial of exporting data from GraphQL API in CSV format
cloudflare/cloudflare-docs pull request #2494
Opened 2021-10-13 19:20 UTC by victor-perov

This commit refactors a python tutorial and adds more details
a user should be aware of. It also removes not needed header and
query fields which makes the example simpler.

The initial python logic was not changed much and it still has
the same idea of querying last N day (with the specified offset)
of minutely aggregated attack activity.

Some texts were rephrased and indentation of the query was fixed
to make them clearer.

2021-10-13 19:32 UTC, victor-perov commented on products/analytics/src/content/graphql-api/tutorials/export-graphql-to-csv/index.md
> +There are two ways to authentificate the request to GraphQL API:
Maybe we can even drop this part from here and rely on the Authorization header only.

2021-10-15 14:04 UTC, kodster28 commented on products/analytics/src/content/graphql-api/tutorials/export-graphql-to-csv/index.md
> +There are two ways to authentificate the request to GraphQL API:
I think so.

2021-10-15 14:14 UTC, pedrosousa commented on products/analytics/src/content/graphql-api/tutorials/export-graphql-to-csv/index.md
> +There are two ways to authentificate the request to GraphQL API:
FYI: The Network Analytics v2 documentation that I'm ready to merge is going to [update this exact tutorial](https://github.com/cloudflare/cloudflare-docs/pull/2501/files#diff-9da15ac88ddf1561077b4d95f6a4c09987af22f1227879c573df7d4100bf4b38). We should probably compare the proposed changes so that we don't lose information or mix two different implementations.

2021-10-15 14:19 UTC, kodster28 commented on products/analytics/src/content/graphql-api/tutorials/export-graphql-to-csv/index.md
> +There are two ways to authentificate the request to GraphQL API:
Why don't you go ahead and merge in your changes and then I could create a new branch with this info.

2021-10-26 12:16 UTC, victor-perov reviewed
The script I'm proposing to use was tested.

2021-10-26 12:16 UTC, victor-perov commented on products/analytics/src/content/graphql-api/tutorials/export-graphql-to-csv/index.md
> +There are two ways to authentificate the request to GraphQL API:
FYI: @pedrosousa @kodster28, as we discussed earlier, some changes made in #2501 were reverted.

2021-10-26 13:47 UTC, kodster28 requested changes
Added a few comments that need to be addressed for clarity.

2021-10-26 13:47 UTC, kodster28 commented on products/analytics/src/content/graphql-api/tutorials/export-graphql-to-csv/index.md
>  <Aside type="warning">
We'll want to move this below the initial description of the tutorial b/c the SEO description usually gets generated from the first few lines of text.

2021-10-26 13:47 UTC, kodster28 commented on products/analytics/src/content/graphql-api/tutorials/export-graphql-to-csv/index.md
>  <Aside type='note' header='Note'>
I'd actually remove this aside entirely (if it's too long, the info generally gets lost) and instead add another section right above this one.

Something like, 

## Prerequisites

This tutorial assumes that you already have a Cloudflare API token for authentication to the Analytics GraphQL API (`Account Analytics: read` permission). If you do not already have one, refer to [Configure an Analytics API token](/graphql-api/getting-started/authentication/api-token-auth).

The scripts also require Python 3.6 or higher.

2021-10-26 13:47 UTC, kodster28 commented on products/analytics/src/content/graphql-api/tutorials/export-graphql-to-csv/index.md
> +Please note: the braces used in the GraphQL query are doubled to escape them in
```suggestion
The braces used in the GraphQL query are doubled to escape them in
```

2021-10-26 13:47 UTC, kodster28 commented on products/analytics/src/content/graphql-api/tutorials/export-graphql-to-csv/index.md
> +Keep also in mind, that GraphQL requires a query to be a single-line text,
```suggestion
GraphQL also requires a query to be a single-line text,
```

2021-10-26 13:47 UTC, kodster28 commented on products/analytics/src/content/graphql-api/tutorials/export-graphql-to-csv/index.md
> +before conversion—normalizing the data, selecting only the desired data, and
```suggestion
before conversion — normalizing the data, selecting only the desired data, and
```

2021-10-26 14:47 UTC, victor-perov commented on products/analytics/src/content/graphql-api/tutorials/export-graphql-to-csv/index.md
>  <Aside type="warning">
Do you want me to help with moving it down, despite the fact it was approved and merged in #2501? Sure, I can place it after the description block.

2021-10-26 14:49 UTC, victor-perov commented on products/analytics/src/content/graphql-api/tutorials/export-graphql-to-csv/index.md
>  <Aside type='note' header='Note'>
Having a prerequisites section sounds good to me.

2021-10-26 15:00 UTC, victor-perov commented
@kodster28, addressed your comments, please have a look.

2021-10-26 15:20 UTC, kodster28 approved these changes

2021-10-26 15:23 UTC, merged