[docs engine] add github best practices
cloudflare/cloudflare-docs pull request #250
Opened 2020-11-06 00:26 UTC by abracchi-tw

- add github best practices
- add codeowners page + small tweaks
- formatting

@adamschwartz feel free to suggest another location for the `codeowners.md` file

2020-11-06 01:05 UTC, adamschwartz requested changes
Thanks so much for getting this started! Please see my review comments below.

2020-11-06 01:05 UTC, adamschwartz commented on products/docs-engine/src/content/contributing/content/working-with-github.md
> +</Aside>
Clean up:

```mdx
<Aside>

The __goal__ is to ensure that PRs are easily __retrievable__ and __readable__.

</Aside>
```

2020-11-06 01:05 UTC, adamschwartz commented on products/docs-engine/src/content/contributing/content/working-with-github.md
> +</Aside>
I’d also question whether this needs to be an `<Aside/>`. Maybe just a regular paragraph?

Similar to the top of https://developers.cloudflare.com/docs-engine/contributing/content/content-framework

2020-11-06 01:05 UTC, adamschwartz commented on products/docs-engine/src/content/contributing/content/working-with-github.md
> + <b>Tip</b>: when you’re working on several files or making significant changes in your local repo, try to split work into smaller commits.
Use an `<Aside/>` for tips.

2020-11-06 01:05 UTC, adamschwartz commented on products/docs-engine/src/content/contributing/content/working-with-github.md
> +1. Make commit messages informative.
Remove trailing whitespace.

2020-11-06 01:05 UTC, adamschwartz commented on products/docs-engine/src/content/contributing/content/working-with-github.md
> +</table>
Use a Markdown table.

2020-11-06 01:05 UTC, adamschwartz commented on products/docs-engine/src/content/contributing/content/working-with-github.md
> +</table>
Use a Markdown table.

2020-11-06 01:05 UTC, adamschwartz commented on products/docs-engine/src/content/contributing/content/working-with-github.md
> +5. Request a review from the **code owner**.
Remove trailing whitespace.

2020-11-06 01:05 UTC, adamschwartz commented on products/docs-engine/src/content/contributing/content/working-with-github.md
> +   * `product:1.1.1.1`
Fix indentation.

2020-11-06 01:05 UTC, adamschwartz commented on products/docs-engine/src/content/reference/codeowners.md
> +products/workers/ @cloudflare/workers-docs
Rather than duplicating this information, which could easily get out of date, I think we should link to the CODEOWNERS document at https://github.com/cloudflare/cloudflare-docs/blob/production/.github/CODEOWNERS.

2020-11-06 09:55 UTC, abracchi-tw commented on products/docs-engine/src/content/contributing/content/working-with-github.md
> +</Aside>
makes sense, done

2020-11-06 09:55 UTC, abracchi-tw commented on products/docs-engine/src/content/contributing/content/working-with-github.md
> + <b>Tip</b>: when you’re working on several files or making significant changes in your local repo, try to split work into smaller commits.
done

2020-11-06 09:57 UTC, abracchi-tw commented on products/docs-engine/src/content/contributing/content/working-with-github.md
> +</table>
this was the only way I could include a bullet-point list within a table. do you know of a markdown solution that allows this?

2020-11-06 10:35 UTC, abracchi-tw commented on products/docs-engine/src/content/contributing/content/working-with-github.md
> +   * `product:1.1.1.1`
what about indentation? these bullet points should be aligned with the text within the `4.` element

2020-11-06 10:35 UTC, abracchi-tw commented on products/docs-engine/src/content/contributing/content/working-with-github.md
> +</table>
fixed

2020-11-06 10:37 UTC, abracchi-tw commented on products/docs-engine/src/content/reference/codeowners.md
> +products/workers/ @cloudflare/workers-docs
> Rather than duplicating this information, which could easily get out of date, I think we should link to the CODEOWNERS document at https://github.com/cloudflare/cloudflare-docs/blob/production/.github/CODEOWNERS.

2020-11-06 10:42 UTC, abracchi-tw commented on products/docs-engine/src/content/contributing/content/working-with-github.md
> +</table>
nevermind, I guess different lines can work

2020-11-10 17:01 UTC, adamschwartz requested changes
A few more tweaks.

2020-11-10 17:01 UTC, adamschwartz commented on products/docs-engine/src/content/contributing/content/working-with-github.md
> +  See [here](https://github.com/cloudflare/cloudflare-docs/blob/production/.github/CODEOWNERS) a list of code owners per product.
Please use descriptive link text. (See https://developers.cloudflare.com/docs-engine/contributing/content/accessibility)

2020-11-10 17:01 UTC, adamschwartz commented on products/docs-engine/src/content/contributing/content/working-with-github.md
> +    * `product:1.1.1.1`
I would make this just a sentence:

```markdown
Product labels follow the structure `product:$productName`, e.g. `product:access`.
```

2020-11-10 17:01 UTC, adamschwartz commented on products/docs-engine/src/content/contributing/content/working-with-github.md
> +</Aside>
There should be a new line above and below the paragraph, and the single space indentation before "When" should be removed:

```markdown
<Aside>

When you’re working on several files or making significant changes in your local repo, try to split work into smaller commits.

</Aside>
```

See: https://developers.cloudflare.com/docs-engine/reference/markdown#asides

2020-11-10 22:43 UTC, adamschwartz approved these changes

2020-11-10 23:05 UTC, merged