Merge images and image resizing tile - new
cloudflare/cloudflare-docs pull request #2507
Opened 2021-10-18 10:46 UTC by marciocloudflare

New PR to solve conflict errors

2021-10-18 14:41 UTC, sejoker requested changes

2021-10-18 14:41 UTC, sejoker commented on developers.cloudflare.com/src/components/product-grid.js
> -$["images"]               = require("@cloudflare/cloudflare-brand-assets/resources/product-icons/images.js").pathD
I don't think we need to leave commented out code, just remove it altogether. We have git history for that purpose.

2021-10-18 14:41 UTC, sejoker commented on products/images/src/content/cloudflare-images/delete-images.md
> +curl -X DELETE https://api.cloudflare.com/client/v4/account/:account_id/images/v1/:image_id \
it should be `accounts` in plural.

2021-10-18 14:41 UTC, sejoker commented on products/images/src/content/cloudflare-images/index.md
> +Photos you upload to Cloudflare Images are not attached to any domain in your Cloudflare account and you do not need a domain on Cloudflare to use the Cloudflare Images product.
Photos is too specific in this context. It's either image or asset.

2021-10-18 14:41 UTC, sejoker commented on products/images/src/content/faq/cloudflare-images/index.md
> +## What is the difference between Cloudflare Images and Image Resizing products?
I don't like the fact we have duplicated info in two separate pages. Could we have it in a single document?

2021-10-18 14:41 UTC, sejoker commented on products/images/src/content/faq/cloudflare-images/index.md
> +**CI** - Mote info on Cloudflare Images optimizations can be found in [Resizing Images](../../cloudflare-images/resize-images).
typo in More

2021-10-18 14:41 UTC, sejoker commented on products/images/src/content/faq/image-resizing/index.md
> +**CI** - Mote info on Cloudflare Images optimizations can be found in [Resizing Images](../../cloudflare-images/resize-images).
typo in More

2021-10-18 14:41 UTC, sejoker commented on products/images/src/content/faq/image-resizing/index.md
> +## How much does Cloudflare Images cost?
How much Image Resizing cost?

2021-10-18 14:43 UTC, sejoker commented on products/images/src/content/faq/cloudflare-images/index.md
> +## Can Cloudflare Images convert my images to AVIF?
I would add one more section:
```
## Can Cloudflare Images be served from custom domain?

Soon! We will be introducing custom domain support in the near future.
```

2021-10-18 16:04 UTC, marciocloudflare commented on developers.cloudflare.com/src/components/product-grid.js
> -$["images"]               = require("@cloudflare/cloudflare-brand-assets/resources/product-icons/images.js").pathD
I was having problems this morning with my local build when I tried to build dev docs home page, and forgot to delete this. Done.

2021-10-18 16:05 UTC, marciocloudflare commented on products/images/src/content/cloudflare-images/delete-images.md
> +curl -X DELETE https://api.cloudflare.com/client/v4/account/:account_id/images/v1/:image_id \
done

2021-10-18 16:06 UTC, marciocloudflare commented on products/images/src/content/cloudflare-images/index.md
> +Photos you upload to Cloudflare Images are not attached to any domain in your Cloudflare account and you do not need a domain on Cloudflare to use the Cloudflare Images product.
Done

2021-10-18 16:09 UTC, marciocloudflare commented on products/images/src/content/faq/cloudflare-images/index.md
> +## What is the difference between Cloudflare Images and Image Resizing products?
Yup

2021-10-18 16:09 UTC, marciocloudflare commented on products/images/src/content/faq/cloudflare-images/index.md
> +**CI** - Mote info on Cloudflare Images optimizations can be found in [Resizing Images](../../cloudflare-images/resize-images).
Thanks!

2021-10-18 16:09 UTC, marciocloudflare commented on products/images/src/content/faq/image-resizing/index.md
> +## How much does Cloudflare Images cost?
Done. Thanks!

2021-10-18 16:10 UTC, marciocloudflare commented on products/images/src/content/faq/cloudflare-images/index.md
> +## Can Cloudflare Images convert my images to AVIF?
Done

2021-10-18 16:10 UTC, marciocloudflare commented on products/images/src/content/faq/image-resizing/index.md
> +**CI** - Mote info on Cloudflare Images optimizations can be found in [Resizing Images](../../cloudflare-images/resize-images).
Thanks

2021-10-19 11:07 UTC, kornelski commented on developers.cloudflare.com/src/components/product-grid.js
> +    title: "Cloudflare Image Optimization",
Could we use "Cloudflare Image Optimization" in user-visible text, but keep the previous short `/images` path?

2021-10-19 11:13 UTC, marciocloudflare commented on developers.cloudflare.com/src/components/product-grid.js
> +    title: "Cloudflare Image Optimization",
Sure. I'll work on it

2021-10-19 11:29 UTC, marciocloudflare commented on developers.cloudflare.com/src/components/product-grid.js
> +    title: "Cloudflare Image Optimization",
Hey @kornelski. Should be ok now :)

2021-10-19 12:20 UTC, kornelski approved these changes

2021-10-19 13:37 UTC, sejoker commented on products/images/src/content/image-resizing/index.md
> +  <Button type="secondary" href="/image-resizing/resizing-with-workers">View the Workers docs</Button>
I suggest we should make `type="primary"` for image resizing button as well.

2021-10-19 13:40 UTC, sejoker approved these changes

2021-10-19 13:40 UTC, sejoker commented on products/images/src/content/faq/index.md
> +Refer to our [Cloudflare Images](https://www.cloudflare.com/en-gb/products/cloudflare-images/) page for up-to-date information on pricing.
please use internation link: https://www.cloudflare.com/products/cloudflare-images.

2021-10-19 18:13 UTC, pedrosousa approved these changes

2021-10-19 18:13 UTC, pedrosousa commented on products/image-resizing/src/content/index.md
> +This content has moved
I guess you will delete this file later, right?

2021-10-19 18:13 UTC, pedrosousa commented on products/images/docs-config.js
> +      "Choose between Cloudflare Images and Cloudflare Image Resizing, two products tailored for your different needs.",
Is it "tailored for" or "tailored to"...?

2021-10-19 18:13 UTC, pedrosousa commented on products/images/src/content/cloudflare-images/delete-images.md
> +# Delete Images
```suggestion
# Delete images
```
I think "images" in this context is not the product name, right?

2021-10-19 18:13 UTC, pedrosousa commented on products/images/src/content/cloudflare-images/delete-variants.md
> +# Delete Variants
```suggestion
# Delete variants
```

2021-10-19 18:13 UTC, pedrosousa commented on products/images/src/content/cloudflare-images/index.md
> +## Making Your First API Request
```suggestion
## Making your first API request
```

2021-10-19 18:13 UTC, pedrosousa commented on products/images/src/content/cloudflare-images/resize-images.md
> +# Resize Images
```suggestion
# Resize images
```

2021-10-19 18:13 UTC, pedrosousa commented on products/images/src/content/cloudflare-images/serve-images/index.md
> +# Serve Images
```suggestion
# Serve images
```

2021-10-19 18:13 UTC, pedrosousa commented on products/images/src/content/cloudflare-images/upload-images/index.md
> +# Upload Images
```suggestion
# Upload images
```

2021-10-19 18:13 UTC, pedrosousa commented on products/images/src/content/index.md
> +With Cloudflare Images you have an option of building a scalable image pipeline on Cloudflare servers, to store, resize, optimize and deliver images in a fast and secure manner.
```suggestion
With Cloudflare Images you can build a scalable image pipeline on Cloudflare servers, to store, resize, optimize, and deliver images in a fast and secure manner.
```

2021-10-19 18:13 UTC, pedrosousa commented on products/images/src/content/index.md
>  pcx-content-type: landing-page
```suggestion
pcx-content-type: overview
```
The content type is now named `overview`, according to our guidelines.

2021-10-19 18:13 UTC, pedrosousa commented on products/images/src/content/faq/index.md
> +pcx-content-type: navigation
```suggestion
pcx-content-type: faq
```

2021-10-19 18:13 UTC, pedrosousa commented on products/images/src/content/faq/index.md
> +# FAQs
```suggestion
# FAQ
```
I think we always use singular here.

2021-10-19 18:13 UTC, pedrosousa commented on products/images/src/content/faq/index.md
> +Cloudflare Images (CI) is an end-to-end solution that offers storage, resizing, optimization, and delivery. Image Resizing (IR) only offers resizing and optimization:
```suggestion
Cloudflare Images (CI) is an end-to-end solution that offers storage, resizing, optimization, and delivery; Image Resizing (IR) only offers resizing and optimization:
```
I wouldn't use a full stop because it would seem that the next sections (after the colon) were only about Image Resizing.

2021-10-19 18:13 UTC, pedrosousa commented on products/images/src/content/faq/index.md
> +**CI** - images are stored at Cloudflare.
```suggestion
**CI** - Images are stored at Cloudflare.
```
I'd start with an upper case letter after the dash (also applies to other sentences below).

2021-10-19 18:13 UTC, pedrosousa commented on products/images/src/content/faq/index.md
> +**IR** - images can be stored anywhere on the Internet as long as it has public access.
```suggestion
**IR** - Images can be stored anywhere on the Internet as long as they have public access.
```

2021-10-19 18:13 UTC, pedrosousa commented on products/images/src/content/faq/index.md
> +**IR** - images are served from a customers' domain on Cloudflare.
```suggestion
**CI** - Images are served from `imagedelivery.net`.

**IR** - Images are served from one of your domains on Cloudflare.
```

2021-10-19 18:13 UTC, pedrosousa commented on products/images/src/content/faq/index.md
> +**IR** - More info on Image Resizing optimizations can be found in [URL format options](../../image-resizing/url-format#options).
```suggestion
**CI** - For more information on Cloudflare Images optimizations refer to [Resize images](../../cloudflare-images/resize-images).

**IR** - For more information on Image Resizing optimizations refer to [URL format options](../../image-resizing/url-format#options).
```

2021-10-19 18:13 UTC, pedrosousa commented on products/images/src/content/faq/index.md
> +**IR** - available with Pro, Biz, and Ent plans.
```suggestion
**CI** - Available to any plan.

**IR** - Available with Pro, Business, and Enterprise plans.
```

2021-10-19 18:13 UTC, pedrosousa commented on products/images/src/content/faq/index.md
> +Refer to our [Cloudflare Images](https://www.cloudflare.com/products/cloudflare-images/) page for up-to-date information on pricing.
```suggestion
Refer to [Cloudflare Images](https://www.cloudflare.com/products/cloudflare-images/) for up-to-date information on pricing.
```

2021-10-19 18:13 UTC, pedrosousa commented on products/images/src/content/faq/index.md
> +No, you only get billed for the number of original images. There is no extra cost for generating variants. You can configure upto 20 variants.
```suggestion
No, you only get billed for the number of original images. There is no extra cost for generating variants. You can configure up to 20 variants.
```

2021-10-19 18:13 UTC, pedrosousa commented on products/images/src/content/faq/index.md
> +Cloudflare Images supports most common file formats as input files. These include JPGs, GIFs, PNGs and WebP.
```suggestion
Cloudflare Images supports most common file formats as input files. These include JPEG, GIF, PNG, and WebP.
```
I'd use the singular form of each file format. Also, the format name that appears in other topics in this PR is JPEG instead of JPG.

2021-10-19 18:13 UTC, pedrosousa commented on products/images/src/content/faq/index.md
> +Refer to our [Plans page](https://www.cloudflare.com/plans/) page for up-to-date information on pricing.
```suggestion
Refer to our [Plans](https://www.cloudflare.com/plans/) page for up-to-date information on pricing.
```

2021-10-19 18:13 UTC, pedrosousa commented on products/images/src/content/image-resizing/control-origin-access.md
> +When testing Image Resizing, please deploy the script, and test it from a regular web browser window. The preview in the Dashboard does not simulate Image Resizing.
```suggestion
When testing Image Resizing, make sure you deploy the script and test it from a regular web browser window. The preview in the Dashboard does not simulate Image Resizing.
```

2021-10-19 18:13 UTC, pedrosousa commented on products/images/src/content/image-resizing/control-origin-access.md
> +You do not have to include actual pixel dimensions in the URL. You can embed sizes in the Worker script, and select the size in some other way, e.g. by naming a preset in the URL:
```suggestion
You do not have to include actual pixel dimensions in the URL. You can embed sizes in the Worker script, and select the size in some other way — for example, by naming a preset in the URL:
```

2021-10-19 18:13 UTC, pedrosousa commented on products/images/src/content/image-resizing/control-origin-access.md
> +You can perform per-request access control in the Worker. If the images are personalized at the origin server, put the personalization options in the image URL.
```suggestion
You can perform per-request access control in the Worker. If the images are personalized at the origin server, include the personalization options in the image URL.
```

2021-10-19 18:13 UTC, pedrosousa commented on products/images/src/content/image-resizing/draw-overlays.md
> +# Draw overlays & watermarks
```suggestion
# Draw overlays and watermarks
```

2021-10-19 18:13 UTC, pedrosousa commented on products/images/src/content/image-resizing/draw-overlays.md
> +This feature is available only in [Workers](/image-resizing/resizing-with-workers). To draw overlay images, add an array of drawing commands to options of `fetch()` requests. The drawing options are
```suggestion
This feature is available only in [Workers](/image-resizing/resizing-with-workers). To draw overlay images, add an array of drawing commands to options of `fetch()` requests. The drawing options are nested in `options.cf.image.draw`, like in the following example:
```

2021-10-19 18:13 UTC, pedrosousa commented on products/images/src/content/image-resizing/draw-overlays.md
>  The `draw` property is an array. Overlays are drawn in the order they appear in the array (last array entry is the topmost layer). Each item in the `draw` array is an object, which can have the follo
```suggestion
The `draw` property is an array. Overlays are drawn in the order they appear in the array (the last array entry is the topmost layer). Each item in the `draw` array is an object, which can have the following properties:
```

2021-10-19 18:13 UTC, pedrosousa commented on products/images/src/content/image-resizing/index.md
> +- Image processing [integrates well with Workers](/image-resizing/resizing-with-workers), which enables advanced integrations such as custom URL schemes, content negotiation and responsive images bas
```suggestion
- Integrate [image processing with Workers](/image-resizing/resizing-with-workers), which enables advanced integrations such as custom URL schemes, content negotiation, and responsive images based on Client Hints.
```
The original sentence "Cloudflare Image Resizing lets you:" didn't follow up nicely with the previous version of this sentence.

2021-10-19 18:13 UTC, pedrosousa commented on products/images/src/content/image-resizing/index.md
> +Image Resizing is currently available for Pro, Business and Enterprise customers. To begin, ensure you have [enabled Image Resizing](/image-resizing/enable-image-resizing) in the Cloudflare dashboard
```suggestion
Image Resizing is currently available for Pro, Business, and Enterprise customers. To begin, ensure you have [enabled Image Resizing](/image-resizing/enable-image-resizing) in the Cloudflare dashboard.
```

2021-10-19 18:13 UTC, pedrosousa commented on products/images/src/content/image-resizing/integration-with-frameworks.md
> +Image Resizing can be used automatically with Next.js' `next/image` [component](https://nextjs.org/docs/api-reference/next/image). With a [custom loader](https://nextjs.org/docs/api-reference/next/im
I preferred the previous link with two words instead of just "component".

2021-10-19 18:13 UTC, pedrosousa commented on products/images/src/content/image-resizing/index.md
> +  <Button type="secondary" href="/image-resizing/resizing-with-workers">View the Workers docs</Button>
```suggestion
  <Button type="secondary" href="/image-resizing/resize-with-workers">View the Workers docs</Button>
```

2021-10-19 18:13 UTC, pedrosousa commented on products/images/src/content/image-resizing/resize-with-workers.md
> +* You can use a custom URL scheme. Instead of specifying pixel dimensions in image URLs, use preset names such as `thumbnail` and `large`.
```suggestion
* Use a custom URL scheme. Instead of specifying pixel dimensions in image URLs, use preset names such as `thumbnail` and `large`.
```
Makes all the bullets start with a verb. 
Also, consider putting the first sentence ("Use a custom URL scheme.") in bold — you'd have to find a way to address this in the last bullet.

2021-10-19 18:13 UTC, pedrosousa commented on products/images/src/content/image-resizing/resize-with-workers.md
>        - Resizes to the maximum size that fits within the given `width` and `height`. If only a single dimension is given (e.g. only `width`), the image will be shrunk or enlarged to exactly match tha
```suggestion
      - Resizes to the maximum size that fits within the given `width` and `height`. If only a single dimension is given (for example, only `width`), the image will be shrunk or enlarged to exactly match that dimension. Aspect ratio is always preserved.
```

2021-10-19 18:13 UTC, pedrosousa commented on products/images/src/content/image-resizing/resize-with-workers.md
>        - Resizes to the maximum size that fits within the given `width` and `height`, and then fills the remaining area with a `background` color (white by default). Use of this mode is not recommende
```suggestion
      - Resizes to the maximum size that fits within the given `width` and `height`, and then fills the remaining area with a `background` color (white by default). This mode is not recommended, since you can achieve the same effect more efficiently with the `contain` mode and the CSS `object-fit: contain` property.
```

2021-10-19 18:13 UTC, pedrosousa commented on products/images/src/content/image-resizing/resize-with-workers.md
>    - When cropping with `fit: "cover"` and `fit: "crop"`, this defines the side or point that should be left uncropped.
```suggestion
  - When cropping with `fit: "cover"` and `fit: "crop"`, this parameter defines the side or point that should be left uncropped.
```

2021-10-19 18:13 UTC, pedrosousa commented on products/images/src/content/image-resizing/resize-with-workers.md
> +    - A string `"left"`, `"right"`, `"top"`, `"bottom"` or `"center"` (the default). `{fit: "cover", gravity: "top"}` will crop bottom or left and right sides as necessary, but will not crop anything
```suggestion
    - A string `"left"`, `"right"`, `"top"`, `"bottom"`, or `"center"` (the default). `{fit: "cover", gravity: "top"}` will crop bottom or left and right sides as necessary, but will not crop anything from the top.
```

2021-10-19 18:13 UTC, pedrosousa commented on products/images/src/content/image-resizing/resize-with-workers.md
>    - Background color to add underneath the image. Applies only to images with transparency (e.g. PNG). Accepts any CSS color (`#RRGGBB`, `rgba(…)`, etc.).
```suggestion
  - Background color to add underneath the image. Applies only to images with transparency (for example, PNG). Accepts any CSS color, such as `#RRGGBB` and `rgba(…)`.
```

2021-10-19 18:13 UTC, pedrosousa commented on products/images/src/content/image-resizing/resize-with-workers.md
> +  - Number of degrees (`90`, `180`, `270`) to rotate the image by. `width` and `height` options refer to axes after rotation.
```suggestion
  - Number of degrees (`90`, `180`, or `270`) to rotate the image by. `width` and `height` options refer to axes after rotation.
```
Assuming that you cannot use any custom values other than the three listed.

2021-10-19 18:13 UTC, pedrosousa commented on products/images/src/content/image-resizing/resize-with-workers.md
> +## Configure a worker
```suggestion
## Configure a Worker
```

2021-10-19 18:13 UTC, pedrosousa commented on products/images/src/content/image-resizing/resize-with-workers.md
> +Create a new script in the Workers section of the Cloudflare Dashboard. Scope your worker script to a path dedicated to serving assets, such as `/images/*`, `/assets/*`, etc. Only supported image for
```suggestion
Create a new script in the Workers section of the Cloudflare Dashboard. Scope your Worker script to a path dedicated to serving assets, such as `/images/*` or `/assets/*`. Only supported image formats can be resized. Attempting to resize any other type of resource (CSS, HTML) will result in an error.
```

2021-10-19 18:13 UTC, pedrosousa commented on products/images/src/content/image-resizing/resize-with-workers.md
> +You must detect which requests have to go straight to the origin server. When the `image-resizing` string is present in the `Via` header, that is a request coming from another Worker, and should be d
```suggestion
You must detect which requests must go directly to the origin server. When the `image-resizing` string is present in the `Via` header, it means that it is a request coming from another Worker and should be directed to the origin server:
```

2021-10-19 18:13 UTC, pedrosousa commented on products/images/src/content/image-resizing/resize-with-workers.md
> +The script preview of the Worker editor ignores `fetch()` options, and will always fetch unresized images. To see the effect of Image Resizing you must deploy the worker script and use it outside of
```suggestion
The script preview of the Worker editor ignores `fetch()` options, and will always fetch unresized images. To see the effect of Image Resizing you must deploy the Worker script and use it outside of the editor.
```

2021-10-19 18:13 UTC, pedrosousa commented on products/images/src/content/image-resizing/resize-with-workers.md
> +When an image cannot be resized, e.g. because the image does not exist, or resizing parameters were invalid, the response will have an HTTP status indicating an error (e.g. 400, 404, 502, etc.).
```suggestion
When an image cannot be resized — for example, because the image does not exist or the resizing parameters were invalid — the response will have an HTTP status indicating an error (for example, 400, 404, or 502).
```

2021-10-19 18:13 UTC, pedrosousa commented on products/images/src/content/image-resizing/resize-with-workers.md
> +Assuming you [set up a worker](https://developers.cloudflare.com/workers/learning/getting-started) on `https://example.com/image-resizing` to handle URLs like `https://example.com/image-resizing?widt
```suggestion
Assuming you [set up a Worker](https://developers.cloudflare.com/workers/learning/getting-started) on `https://example.com/image-resizing` to handle URLs like `https://example.com/image-resizing?width=80&image=https://example.com/uploads/avatar1.jpg`:
```

2021-10-19 18:13 UTC, pedrosousa commented on products/images/src/content/image-resizing/responsive-images.md
> +1. For an image with a fixed size in terms of CSS pixels, but adapting to high-DPI screens (also known as Retina displays). These images take the same amount of space on the page regardless of screen
I would use a bulleted list instead of a numbered list (these items don't have an associated order).

2021-10-19 18:13 UTC, pedrosousa commented on products/images/src/content/image-resizing/responsive-images.md
> +If we breakout the URL path used in this example, the `src` attribute is for images with the usual "1x" density. `/cdn-cgi/image/` is a special path for resizing images. This is followed by `width=96
I'd avoid "we".

2021-10-19 18:13 UTC, pedrosousa commented on products/images/src/content/image-resizing/responsive-images.md
> +`srcset` is useful for pixel-based formats such as PNG, JPEG and WebP. It is unnecessary for vector-based SVG images.
```suggestion
`srcset` is useful for pixel-based formats such as PNG, JPEG, and WebP. It is unnecessary for vector-based SVG images.
```

2021-10-19 18:13 UTC, pedrosousa commented on products/images/src/content/image-resizing/responsive-images.md
> +1. You can enable the Polish feature with automatic WebP conversion. This will convert all images on the site.
Consider using a bulleted list.

2021-10-19 18:13 UTC, pedrosousa commented on products/images/src/content/image-resizing/troubleshooting.md
> +  * There’s another Worker running on the same request. Resizing is "forgotten" as soon as one Worker calls another. Do not use Workers scoped to the entire domain `/*`.
```suggestion
  * There is another Worker running on the same request. Resizing is "forgotten" as soon as one Worker calls another. Do not use Workers scoped to the entire domain `/*`.
```

2021-10-19 18:13 UTC, pedrosousa commented on products/images/src/content/image-resizing/url-format.md
> +      - Image will be shrunk in size to fully fit within the given `width` or `height`, but wwill not be enlarged.
```suggestion
      - Image will be shrunk in size to fully fit within the given `width` or `height`, but will not be enlarged.
```

2021-10-19 18:13 UTC, pedrosousa commented on products/images/src/content/image-resizing/url-format.md
>        - If a side (`left`, `right`, `top`, `bottom`) or coordinates specified on a scale from `0.0` (top or left) to `1.0` (bottom or right), `0.5` being the center. The X and Y coordinates are separ
```suggestion
      - If a side (`left`, `right`, `top`, `bottom`) or coordinates specified on a scale from `0.0` (top or left) to `1.0` (bottom or right), `0.5` being the center. The X and Y coordinates are separated by lowercase `x`. For example, `0x1` means left and bottom, `0.5x0.5` is the center, `0.5x0.33` is a point in the top third of the image.
```

2021-10-19 18:13 UTC, pedrosousa commented on products/images/src/content/image-resizing/url-format.md
> +  - Specifies quality for images in JPEG, WebP and AVIF formats. The quality is in 1-100 scale, but useful values are between `50` (low quality, small file size) and `90` (high quality, large file si
```suggestion
  - Specifies quality for images in JPEG, WebP, and AVIF formats. The quality is in 1-100 scale, but useful values are between `50` (low quality, small file size) and `90` (high quality, large file size). `85` is the default. When using the PNG format, an explicit quality setting allows use of PNG8 (palette) variant of the format.
```

2021-10-19 18:13 UTC, pedrosousa commented on products/images/src/content/image-resizing/url-format.md
> +Ideally, images sizes should match exactly the size they are displayed on the page. If the page contains thumbnails with markup such as `<img width="200" …>`, then images should be resized to `width=
```suggestion
Ideally, image sizes should match exactly the size they are displayed on the page. If the page contains thumbnails with markup such as `<img width="200" …>`, then images should be resized to `width=200`. If the exact size is not known ahead of time, use the [responsive images technique](/image-resizing/responsive-images).
```

2021-10-19 18:13 UTC, pedrosousa commented on products/images/src/content/image-resizing/url-format.md
> +If you cannot use the `<img srcset>` markup, and have to hardcode specific maximum sizes, here are the sizes we recommend:
```suggestion
If you cannot use the `<img srcset>` markup, and have to hardcode specific maximum sizes, Cloudflare recommends the following sizes:
```

2021-10-19 18:13 UTC, pedrosousa commented on products/images/src/content/image-resizing/url-format.md
> +You can detect device type by enabling the `CF-Device-Type` header [via Page Rule](https://support.cloudflare.com/hc/en-us/articles/229373388-Cache-Content-by-Device-Type-Mobile-Tablet-Desktop-).
```suggestion
You can detect device type by enabling the `CF-Device-Type` header [via Page Rule](https://support.cloudflare.com/hc/articles/229373388).
```

2021-10-20 08:15 UTC, marciocloudflare commented on products/image-resizing/src/content/index.md
> +This content has moved
Yes.

2021-10-20 08:17 UTC, marciocloudflare commented on products/images/docs-config.js
> +      "Choose between Cloudflare Images and Cloudflare Image Resizing, two products tailored for your different needs.",
A quick search tells me they're both correct and mean the same, but `tailored to` is more commonly used. Changing.

2021-10-20 08:38 UTC, marciocloudflare commented on products/images/src/content/image-resizing/integration-with-frameworks.md
> +Image Resizing can be used automatically with Next.js' `next/image` [component](https://nextjs.org/docs/api-reference/next/image). With a [custom loader](https://nextjs.org/docs/api-reference/next/im
I changed it because with a link you loose the backtick formatting. Changing back!

2021-10-20 08:39 UTC, pedrosousa commented on products/images/src/content/image-resizing/integration-with-frameworks.md
> +Image Resizing can be used automatically with Next.js' `next/image` [component](https://nextjs.org/docs/api-reference/next/image). With a [custom loader](https://nextjs.org/docs/api-reference/next/im
I never noticed the issue you mention, but I can test it.
Update: I checked a few occurrences and it seems to work without issues.

2021-10-20 08:40 UTC, marciocloudflare commented on products/images/src/content/image-resizing/responsive-images.md
> +1. For an image with a fixed size in terms of CSS pixels, but adapting to high-DPI screens (also known as Retina displays). These images take the same amount of space on the page regardless of screen
Done

2021-10-20 09:15 UTC, merged