Update list of datasets
cloudflare/cloudflare-docs pull request #258
Opened 2020-11-09 18:21 UTC by tlozoot

* Document the existence of several new adaptive datasets (HTTP requests, Load Balancing, LB Health Checks, Browser Insights)
* Deprecate some non-adaptive variants of these older datasets
* Remove references to deleted datasets

2020-11-09 23:48 UTC, victor-perov requested changes

2020-11-09 23:48 UTC, victor-perov commented on products/analytics/src/content/graphql-api/features/data-sets/index.md
> -| HTTP Requests               | `httpRequests1mGroups` `httpRequests1hGroups` `httpRequests1dGroups` `httpRequests1mByColoGroups` `httpRequests1dByColoGroups` |
I think we agreed to deprecate `httpRequests1[md]ByColoGroups`. Should we use put them here in that case?

2020-11-09 23:48 UTC, victor-perov commented on products/analytics/src/content/graphql-api/features/data-sets/index.md
Should we add `httpRequest1[md]ByColoGroups` here (replacement Node `httpRequestsAdaptiveGroups`)?

2020-11-10 00:36 UTC, soheiokamoto approved these changes

2020-11-10 01:14 UTC, tlozoot commented on products/analytics/src/content/graphql-api/features/data-sets/index.md
Yep, updated.

2020-11-10 01:14 UTC, tlozoot commented on products/analytics/src/content/graphql-api/features/data-sets/index.md
> -| HTTP Requests               | `httpRequests1mGroups` `httpRequests1hGroups` `httpRequests1dGroups` `httpRequests1mByColoGroups` `httpRequests1dByColoGroups` |
Yes, updated.

2020-11-10 10:54 UTC, victor-perov approved these changes

2020-11-11 16:56 UTC, merged