TUN-3510: Argo Tunnel docs now use ingress rules (not CLI) to configure origins
cloudflare/cloudflare-docs pull request #260
Opened 2020-11-09 21:12 UTC by adamchalmers

The docs now tell users to configure the local services running on their origin via Ingress Rules, not via the CLI. I've added a new page explaining how ingress rules work, and another new page with all the various ingress rule config options. 

Origin-related CLI arguments have been moved into their own page and marked as legacy. This PR should not result in any broken links.

2020-11-09 21:25 UTC, TownLake commented on products/argo-tunnel/src/content/configuration/origins-via-ingress.md
> +Remember you can [validate](/routing-to-tunnel/ingress#validating-your-configuration) and [test](/routing-to-tunnel/ingress#testing-your-configuration)
Could remove "Remember" and start "You can" for users who have not reviewed that section yet.

2020-11-09 21:25 UTC, TownLake commented on products/argo-tunnel/src/content/configuration/config.md
> +You can specify a particular Tunnel in the config file by name or ID. When the following stanza is present in the file, the command `cloudflared tunnel run` will be treated as if `cloudflared tunnel
thanks for the catch

2020-11-09 21:30 UTC, TownLake commented on products/argo-tunnel/src/content/routing-to-tunnel/ingress.md
> +built-in Hello World test server, or configure cloudflared to just respond with 404.
`cloudflared`

2020-11-10 01:27 UTC, adamchalmers commented on products/argo-tunnel/src/content/configuration/origins-via-ingress.md
> +Remember you can [validate](/routing-to-tunnel/ingress#validating-your-configuration) and [test](/routing-to-tunnel/ingress#testing-your-configuration)
Done

2020-11-10 01:28 UTC, adamchalmers commented on products/argo-tunnel/src/content/routing-to-tunnel/ingress.md
> +built-in Hello World test server, or configure cloudflared to just respond with 404.
Fixed

2020-11-10 10:36 UTC, abracchi-tw requested changes
left some comments. @adamchalmers let me know what you think

2020-11-10 10:36 UTC, abracchi-tw commented on products/argo-tunnel/src/content/routing-to-tunnel/ingress.md
> +`cloudflared` know which local service a request should be proxied to? It checks the Ingress Rules that you'll
`cloudflared` can accept traffic from many different domains, and proxy it to many different local services. Ingress rules let you specify which local services a request should be proxied to. You can configure ingress rules in the configuration file.

2020-11-10 10:36 UTC, abracchi-tw commented on products/argo-tunnel/src/content/routing-to-tunnel/ingress.md
> +
When `cloudflared` gets an incoming request, it evaluates each ingress rule from top to bottom to find which one matches the request. Rules can match the hostname and/or path of an incoming request. The last rule you list in the config file must be a catch-all rule that matches all traffic. If a rule doesn't specify a hostname, all hostnames will be matched. If a rule doesn't specify a path, all paths will be matched.

This is an example config file that specifies several different rules:

2020-11-10 10:36 UTC, abracchi-tw commented on products/argo-tunnel/src/content/routing-to-tunnel/ingress.md
> +doesn't specify a hostname, all hostnames will be matched. If a rule doesn't specify a path, all paths will be matched.
I incorporated this in my comment above

2020-11-10 10:36 UTC, abracchi-tw commented on products/argo-tunnel/src/content/routing-to-tunnel/ingress.md
> +# Ingress Rules
Ingress **rules** (we should use sentence-style capitalization)

2020-11-10 10:36 UTC, abracchi-tw commented on products/argo-tunnel/src/content/routing-to-tunnel/ingress.md
> +built-in Hello World test server, or configure `cloudflared` to just respond with 404.
@adamchalmers see if this makes sense: 

`cloudflared` doesn’t just support proxying traffic to an HTTP service running on localhost. Other options include SSH, RDP, arbitrary TCP services, and unix sockets. You can also route traffic to the built-in Hello World test server, or configure `cloudflared` to just respond with 404.

2020-11-10 10:36 UTC, abracchi-tw commented on products/argo-tunnel/src/content/routing-to-tunnel/ingress.md
> +configure the service, for example:
To proxy traffic to _one_  single local service, you can:

- Configure the service using the **configuration file** (the scenario covered so far)
- Configure the service using **command-line flags**, for example:

2020-11-10 14:41 UTC, abracchi-tw approved these changes

2020-11-10 15:12 UTC, merged