Update with new Pages _headers feature
cloudflare/cloudflare-docs pull request #2601
Opened 2021-10-28 20:30 UTC by michaelkennedy

2021-10-28 21:12 UTC, WalshyDev requested changes

2021-10-28 21:12 UTC, WalshyDev commented on products/pages/src/content/how-to/add-custom-http-headers.md
> +Cloudflare provides HTTP header customization for Pages projects by ading a `_headers` file to your project. Check out the [documentation](https://developers.cloudflare.com/pages/platform/headers). Y
I would recommend making this a note so it stands out more. Also fixed a typo

```suggestion
<Aside type="note">

Cloudflare provides HTTP header customization for Pages projects by adding a `_headers` file to your project. Check out the [documentation](https://developers.cloudflare.com/pages/platform/headers). You may want to add, remove, or alter HTTP headers for security or performance reasons.

</Aside>
```

2021-10-29 15:03 UTC, deadlypants1973 commented on products/pages/src/content/how-to/add-custom-http-headers.md
> +Cloudflare provides HTTP header customization for Pages projects by adding a `_headers` file to your project. Check out the [documentation](https://developers.cloudflare.com/pages/platform/headers).
```suggestion
Cloudflare provides HTTP header customization for Pages projects by adding a `_headers` file to your project. Refer to the [documentation](https://developers.cloudflare.com/pages/platform/headers) for more information.
```

2021-10-29 15:04 UTC, deadlypants1973 approved these changes
PCX review

2021-10-29 15:04 UTC, deadlypants1973 commented on products/pages/src/content/how-to/add-custom-http-headers.md
> +More advanced customisation of HTTP headers is available through Cloudflare Workers [serverless functions](https://www.cloudflare.com/learning/serverless/what-is-serverless/).
```suggestion
More advanced customization of HTTP headers is available through Cloudflare Workers [serverless functions](https://www.cloudflare.com/learning/serverless/what-is-serverless/). 
```

2021-10-29 15:22 UTC, kristianfreeman approved these changes

2021-10-29 16:20 UTC, jkup approved these changes
Thanks for this!

2021-10-29 16:20 UTC, merged