added minimum tls and corrected index
cloudflare/cloudflare-docs pull request #2616
Opened 2021-11-02 12:11 UTC by angelampcosta

2021-11-02 12:33 UTC, marciocloudflare commented on products/ssl/src/content/edge-certificates/additional-options/index.md
> +- [Minimum TLS Version](minimum-tls): <MinimumTLSDefinition/>
Is there a reason for `TLS 1.3` in the `MinimumTLSDefinition` partial to be in bold?

2021-11-02 12:34 UTC, marciocloudflare commented on products/ssl/src/content/edge-certificates/additional-options/index.md
> +- [TLS 1.3](tls-13): <TLS13Definition/>
Is there a reason for `TLS 1.3` in the `MinimumTLSDefinition` partial to be in bold?

2021-11-02 12:34 UTC, marciocloudflare commented on products/ssl/src/content/edge-certificates/additional-options/index.md
> +- [Minimum TLS Version](minimum-tls): <MinimumTLSDefinition/>
Is there a reason for `Minimum TLS` in the `MinimumTLSDefinition` partial to be in bold?

2021-11-02 12:37 UTC, marciocloudflare commented on products/ssl/src/content/edge-certificates/additional-options/minimum-tls.md
> +For example, if TLS 1.1 is selected, visitors attempting to connect with TLS 1.0 will be rejected while visitors attempting to connect using TLS 1.1, 1.2, or 1.3 (if enabled) will be allowed to conne
I'd break this sentence into two parts to make it easier to read. Example: `For example, if TLS 1.1 is selected, visitors attempting to connect with TLS 1.0 will be rejected. Visitors attempting to connect using TLS 1.1, 1.2, or 1.3 (if enabled) will be allowed to connect.`

2021-11-02 12:57 UTC, marciocloudflare requested changes

2021-11-02 12:57 UTC, marciocloudflare commented on products/ssl/src/content/edge-certificates/additional-options/minimum-tls.md
> +To configure cipher suites, use the API. [Learn More](https://developers.cloudflare.com/ssl/ssl-tls/cipher-suites).
```suggestion
You can use the API to [configure cipher suites](https://developers.cloudflare.com/ssl/ssl-tls/cipher-suites).
```

2021-11-02 12:57 UTC, marciocloudflare commented on products/ssl/src/content/edge-certificates/additional-options/minimum-tls.md
> +To configure cipher suites, use the API. [Learn More](https://developers.cloudflare.com/ssl/ssl-tls/cipher-suites).
Hyperlinks should have context, so you should avoid links like `Learn more`

2021-11-02 12:57 UTC, marciocloudflare commented on products/ssl/src/content/edge-certificates/additional-options/minimum-tls.md
> +# Minimum TLS Version
I think it's confusing to have a page title with `Minimum TLS Version` and then an `Overview`. Consider moving the info you have in this first part to somewhere below the sentence `In this case, it means that Cloudflare also accepts requests encrypted with all TLS versions beyond 1.0.`

2021-11-02 12:57 UTC, marciocloudflare commented on products/ssl/src/content/edge-certificates/additional-options/minimum-tls.md
> +pcx-content-type: interim
Is there a reason for this to be an `interim` page? Why not a `concept` or ´reference`?

2021-11-02 12:57 UTC, marciocloudflare commented on products/ssl/src/content/edge-certificates/additional-options/minimum-tls.md
> +You can manage the TLS version that your domain uses when proxied through Cloudflare by setting the **Minimum TLS Version** in the **SSL/TLS** tab of the Cloudflare dashboard.
```suggestion
You can manage the TLS version your domain uses when proxied through Cloudflare by setting the **Minimum TLS Version** in the **SSL/TLS** tab of the Cloudflare dashboard. 
```

2021-11-02 12:57 UTC, marciocloudflare commented on products/ssl/src/content/edge-certificates/additional-options/minimum-tls.md
> +</Aside>
I don't understand the intent of this message. What's the context?

2021-11-02 12:57 UTC, marciocloudflare commented on products/ssl/src/content/edge-certificates/additional-options/minimum-tls.md
> +To properly test supported TLS versions, attempt a request to your Cloudflare domain while specifying a TLS version.  For example, use the curl command to test TLS 1.1 (replace `www.example.com` with
```suggestion
To properly test supported TLS versions, attempt a request to your Cloudflare domain while specifying a TLS version.  For example, use a `curl` command to test TLS 1.1 (replace `www.example.com` with your Cloudflare domain and hostname):
```

2021-11-02 12:57 UTC, marciocloudflare commented on products/ssl/src/content/edge-certificates/additional-options/minimum-tls.md
> +If the TLS version is blocked by Cloudflare, the TLS handshake does not complete and instead returns errors such as:
```suggestion
If the TLS version you are testing for is blocked by Cloudflare, the TLS handshake does not complete and returns an error:
```

2021-11-02 12:57 UTC, marciocloudflare commented on products/ssl/src/content/edge-certificates/additional-options/minimum-tls.md
> +Consider using TLS 1.0 or 1.1 for sites with a broad user base, particularly non-transactional sites. This way, you minimize the possibility that some clients might not be able to connect to your sit
```suggestion
Consider using TLS 1.0 or 1.1 for sites with a broad user base, particularly non-transactional sites. This way, you minimize the possibility for some clients not being able to connect to your site securely.
```

2021-11-02 12:57 UTC, marciocloudflare commented on products/ssl/src/content/edge-certificates/additional-options/minimum-tls.md
> +It is not recommended to set the minimum TLS to 1.3 as this will likely cause issues with search engine crawlers and certain browsers. It should only be set to TLS 1.3 where there is a specific use c
```suggestion
It is not recommended to set the minimum TLS to 1.3 as this will likely cause issues with search engine crawlers and certain browsers. You should only set your minimum TLS requirement to TLS 1.3 where you have specific use case needs.
```

2021-11-02 12:57 UTC, marciocloudflare commented on products/ssl/src/content/edge-certificates/additional-options/minimum-tls.md
> +It is not recommended to set the minimum TLS to 1.3 as this will likely cause issues with search engine crawlers and certain browsers. It should only be set to TLS 1.3 where there is a specific use c
Not sure about the last part of the sentence, but I feel it's lacking something to be complete - for example, which use cases are those that need TLS 1.3?

2021-11-02 12:57 UTC, marciocloudflare commented on products/ssl/src/content/edge-certificates/additional-options/minimum-tls.md
> +### More articles on PCI compliance
I think you should either remove the `More articles on PCI compliance` and `TLS and PCI compliance` H3 titles or change the later to an H4. As it is it's weird because you only have one article below `More articles on PCI compliance`, although it's plural.

Also, consider writing a description for `Transport Layer Security` and `PCI Security Standards Council` as you did for `PCI Compliance`

2021-11-02 14:02 UTC, angelampcosta commented on products/ssl/src/content/edge-certificates/additional-options/index.md
> +- [TLS 1.3](tls-13): <TLS13Definition/>
I didn't edit the definition in the partial, but I can remove the bold.

2021-11-02 14:04 UTC, angelampcosta commented on products/ssl/src/content/edge-certificates/additional-options/index.md
> +- [Minimum TLS Version](minimum-tls): <MinimumTLSDefinition/>
I'll remove the bolds from the partial definitions.

2021-11-02 14:08 UTC, angelampcosta commented on products/ssl/src/content/edge-certificates/additional-options/minimum-tls.md
> +For example, if TLS 1.1 is selected, visitors attempting to connect with TLS 1.0 will be rejected while visitors attempting to connect using TLS 1.1, 1.2, or 1.3 (if enabled) will be allowed to conne
Agree

2021-11-02 14:13 UTC, angelampcosta commented on products/ssl/src/content/edge-certificates/additional-options/minimum-tls.md
> +pcx-content-type: interim
Makes sense. I'll change to "concept".

2021-11-02 14:27 UTC, angelampcosta commented on products/ssl/src/content/edge-certificates/additional-options/minimum-tls.md
> +If the TLS version is blocked by Cloudflare, the TLS handshake does not complete and instead returns errors such as:
Do you agree with "If the TLS version you are testing is blocked by Cloudflare, the TLS handshake is not completed and returns an error:"?

2021-11-02 14:29 UTC, angelampcosta commented on products/ssl/src/content/edge-certificates/additional-options/minimum-tls.md
> +Consider using TLS 1.0 or 1.1 for sites with a broad user base, particularly non-transactional sites. This way, you minimize the possibility that some clients might not be able to connect to your sit
Do you agree with: "Consider using TLS 1.0 or 1.1 for sites with a broad user base, particularly non-transactional sites. This way, you minimize the possibility of some clients not being able to connect to your site securely."?

2021-11-02 14:38 UTC, angelampcosta commented on products/ssl/src/content/edge-certificates/additional-options/minimum-tls.md
> +</Aside>
From what I understood there are tools, like [SSL Labs](https://www.ssllabs.com/ssltest/) that analyze SSL, but apparently it's not very accurate. It's not essencial information. I think it's probably better to remove.

2021-11-02 14:53 UTC, angelampcosta commented on products/ssl/src/content/edge-certificates/additional-options/minimum-tls.md
> +### More articles on PCI compliance
How about removing the 2 subtitles and having the 3 links under "Related resources"?

2021-11-02 17:57 UTC, marciocloudflare commented on products/ssl/src/content/edge-certificates/additional-options/minimum-tls.md
> +If the TLS version is blocked by Cloudflare, the TLS handshake does not complete and instead returns errors such as:
Yes :)

2021-11-02 17:59 UTC, marciocloudflare commented on products/ssl/src/content/edge-certificates/additional-options/minimum-tls.md
> +Consider using TLS 1.0 or 1.1 for sites with a broad user base, particularly non-transactional sites. This way, you minimize the possibility that some clients might not be able to connect to your sit
Yes, but I'd defer this one to native speakers

2021-11-02 17:59 UTC, marciocloudflare commented on products/ssl/src/content/edge-certificates/additional-options/minimum-tls.md
> +### More articles on PCI compliance
Sounds good

2021-11-03 10:39 UTC, angelampcosta commented on products/ssl/src/content/edge-certificates/additional-options/index.md
> +- [TLS 1.3](tls-13): <TLS13Definition/>
Done.

2021-11-03 10:40 UTC, angelampcosta commented on products/ssl/src/content/edge-certificates/additional-options/index.md
> +- [Minimum TLS Version](minimum-tls): <MinimumTLSDefinition/>
Done.

2021-11-03 11:52 UTC, marciocloudflare approved these changes

2021-11-03 11:52 UTC, marciocloudflare commented on products/ssl/src/content/edge-certificates/additional-options/minimum-tls.md
> +type: overview
```suggestion
```

2021-11-03 12:01 UTC, merged