Tile for Email Routing
cloudflare/cloudflare-docs pull request #2626
Opened 2021-11-03 16:25 UTC by marciocloudflare

2021-11-03 17:57 UTC, WalshyDev requested changes
Spacing

2021-11-03 17:57 UTC, WalshyDev commented on products/email-routing/src/content/email-routing-options.md
> +* **Drop**: Accepts emails but deletes them without routing to the specified Destination address.This can be useful if you want to make an email address appear valid for privacy reasons.
```suggestion
* **Drop**: Accepts emails but deletes them without routing to the specified Destination address. This can be useful if you want to make an email address appear valid for privacy reasons.
```

2021-11-03 17:57 UTC, WalshyDev commented on products/email-routing/src/content/enable-email-routing.md
> +After creating your email alias and verifying your destination address, Cloudflare needs to add the relevant  MX and TXT records to DNS records for Email Routing to work. This step is automatic and i
```suggestion
After creating your email alias and verifying your destination address, Cloudflare needs to add the relevant MX and TXT records to DNS records for Email Routing to work. This step is automatic and is only needed the first time you configure Email Routing. It is meant to ensure you have the proper records configured in your zone.
```

2021-11-18 15:33 UTC, pedrosousa commented on .github/workflows/build.yml
> +              - 'products/events/**'
```suggestion
              - 'products/email-routing/**'
```

2021-11-18 15:33 UTC, pedrosousa commented on products/email-routing/src/content/icons/email.js
> +module.exports = {
Why don't you name this file also `email-routing.js`? It would make things more predictable in the configuration side (in the `developers.cloudflare.com/src/components/product-grid.js` and `products/email-routing/docs-config.js` files).

2021-11-18 15:33 UTC, pedrosousa commented on products/email-routing/src/content/index.md
> +pcx-content-type: landing-page
```suggestion
pcx-content-type: overview
```

2021-11-18 15:33 UTC, pedrosousa commented on .github/workflows/build.yml
> +      email-routing: ${{ steps.filter.outputs.events }}
```suggestion
      email-routing: ${{ steps.filter.outputs.email-routing }}
```

2021-11-18 15:33 UTC, pedrosousa commented on products/email-routing/src/content/enable-email-routing.md
> +1. Log in to the [Cloudflare dashboard](https://dash.cloudflare.com/) and select your account and domain. Go to **Email**.
```suggestion
1. Log in to the [Cloudflare dashboard](https://dash.cloudflare.com/) and select your account and domain.
1. Go to **Email**.
```

2021-11-18 15:33 UTC, pedrosousa commented on products/email-routing/src/content/enable-email-routing.md
> +When Email Routing is configured and running, no other email services can be active for this domain. If other MX records are already configured in DNS, the user is offered the opportunity to delete t
```suggestion
When Email Routing is configured and running, no other email services can be active in the domain you are configuring. If there are other MX records already configured in DNS, Cloudflare will ask you if you wish to delete them. If you do not delete existing MX records, Email Routing will not be enabled.
```

2021-11-18 15:33 UTC, pedrosousa commented on products/email-routing/src/content/index.md
> +Cloudflare Email Routing is designed to simplify the way you create and manage email addresses, without needing to keep an eye on additional mailboxes. With Email Routing, you can create any number o
```suggestion
Cloudflare Email Routing is designed to simplify the way you create and manage email addresses, without needing to keep an eye on additional mailboxes. With Email Routing, you can create any number of custom email addresses that you can use in situations where you do not want to share your primary email address, such as when you subscribe to a new service or newsletter. Emails are then routed to your preferred email inbox, without you ever having to expose your primary email address.
```
I believe you expose mail addresses, not inboxes directly.

2021-11-18 15:33 UTC, pedrosousa commented on products/email-routing/src/content/index.md
> +Email Routing is free, private by design and Cloudflare doesn’t store or access the emails routed to your inbox.
```suggestion
Email Routing is free for all Cloudflare users and private by design. Cloudflare will not store or access the emails routed to your inbox.
```

2021-11-18 15:33 UTC, pedrosousa commented on products/email-routing/src/content/enable-email-routing.md
> +title: Getting Started
```suggestion
title: Get started
```

2021-11-18 15:33 UTC, pedrosousa commented on products/email-routing/README.md
> +# Cloudflare Email Routing Rules docs
```suggestion
# Cloudflare Email Routing docs
```

2021-11-18 15:33 UTC, pedrosousa commented on products/email-routing/README.md
> +[Read contributor guidelines →](https://developers.cloudflare.com/docs-engine/contributing/content-framework)
Nit: You should also add a new row to table in the [main `README.md` file](https://github.com/cloudflare/cloudflare-docs/blob/production/README.md).

2021-11-18 15:33 UTC, pedrosousa commented on products/email-routing/docs-config.js
> +  search: {
I'd remove the search configuration values before opening a PR on the Algolia repository.

An empty search configuration looks like the following:

```javascript
search: {
  indexName: "",
  apiKey: "",
  algoliaOptions: { facetFilters: '' },
}
```

2021-11-18 15:33 UTC, pedrosousa commented on products/email-routing/docs-config.js
> +    image: "data:image/x-icon;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQEAYAAABPYyMiAAAABmJLR0T///////8JWPfcAAAACXBIWXMAAABIAAAASABGyWs+AAAAF0lEQVRIx2NgGAWjYBSMglEwCkbBSAcACBAAAeaR9cIAAAAASUVORK5CYII="
```suggestion
    image: "https://www.cloudflare.com/img/cf-twitter-card.png",
```
We should use the standard preview image, unless there's a specific reason not to.

2021-11-18 15:33 UTC, pedrosousa commented on products/email-routing/src/content/email-routing-options.md
> +In this section you can create as many custom email addresses as you want for your domain. Each of those custom addresses is then linked to a destination address, forming a **rule**. Rules can be tog
```suggestion
In this section you can create as many custom email addresses as you want for your domain. Each of those custom addresses is then linked to a destination address, forming a **rule**. You can toggle a rule on or off.
```

2021-11-18 15:33 UTC, pedrosousa commented on products/email-routing/src/content/email-routing-options.md
> +To create your rule, you also have to specify an **Action** between the email alias and the destination address:
```suggestion
When creating a rule, you must specify an **Action**:
```

2021-11-18 15:33 UTC, pedrosousa commented on products/email-routing/src/content/email-routing-options.md
> +* **Send to**: emails will be routed to your Destination address. This is the default action.
You should probably use italics for `Send to` and `Drop`, since the user will be selecting one option or the other, but I'm not sure if it's a dropdown or a couple of radio buttons.

2021-11-18 15:33 UTC, pedrosousa commented on products/email-routing/src/content/email-routing-options.md
> +* **Send to**: emails will be routed to your Destination address. This is the default action.
Also, should Destination address be capitalized? If it's a UI label, it should appear in bold. If it's not a specific Cloudflare concept, I would write "destination address".

2021-11-18 15:33 UTC, pedrosousa commented on products/email-routing/src/content/email-routing-options.md
> +This feature enables Cloudflare to “catch” every variation of emails, in order to make them valid for the specified domain. For example, if you created a rule for `john@yourdomain.com` and a sender a
```suggestion
This feature enables Cloudflare to “catch” every variation of email addresses to make them valid for the specified domain. For example, if you created a rule for `john@yourdomain.com` and a sender accidentally types `jonh@yourdomain.com`, the email will still be correctly handled if you have Catch-all addresses enabled.
```

2021-11-18 15:33 UTC, pedrosousa commented on products/email-routing/src/content/email-routing-options.md
> +This feature enables Cloudflare to “catch” every variation of emails, in order to make them valid for the specified domain. For example, if you created a rule for `john@yourdomain.com` and a sender a
Also, not sure if "Catch-all addresses" should appear in bold.

2021-11-18 15:33 UTC, pedrosousa commented on products/email-routing/src/content/email-routing-options.md
> +You must also specify an **Action** to Catch-all:
```suggestion
You must also specify an **Action** for Catch-all:
```

2021-11-18 15:33 UTC, pedrosousa commented on products/email-routing/src/content/email-routing-options.md
> +* **Send to**: emails will be routed to your Destination address. This is the default action.
```suggestion
* **Send to**: Emails will be routed to your Destination address. This is the default action.
```

2021-11-18 15:33 UTC, pedrosousa commented on products/email-routing/src/content/email-routing-options.md
> +* **Send to**: emails will be routed to your Destination address. This is the default action.
```suggestion
* **Send to**: Emails will be routed to your Destination address. This is the default action.
```

2021-11-18 15:33 UTC, pedrosousa commented on products/email-routing/src/content/email-routing-options.md
> +* **Drop**: Accepts emails but deletes them without routing to the specified Destination address.This can be useful if you want to make an email address appear valid for privacy reasons.
```suggestion
* **Drop**: Accepts emails but deletes them without routing to the specified Destination address. This can be useful if you want to make an email address appear valid for privacy reasons.
```

2021-11-18 15:33 UTC, pedrosousa commented on products/email-routing/src/content/email-routing-options.md
> +All DNS records needed for Email Routing to work are shown here. You can check which records you need to add or remove, and this step can be done automatically by clicking **Add records automatically
```suggestion
This section will display all the DNS records needed for Email Routing to work. You can check which records you need to add or remove, and this step can be done automatically by clicking **Add records automatically**. Cloudflare also shows you the correct DNS records in case you want to add or remove them manually. This is also where you can confirm if there are any conflicts that may result in unexpected behaviors.
```

2021-11-18 15:33 UTC, pedrosousa commented on products/email-routing/src/content/email-routing-options.md
> +In this section there is a list of Destination addresses that have already been verified. This is also where you can resend a verification email, or delete Destination addresses.
```suggestion
In this section there is a list of Destination addresses that have already been verified. You can resend verification emails or delete Destination addresses.
```

2021-11-18 15:33 UTC, pedrosousa commented on products/email-routing/src/content/enable-email-routing.md
> +1. Log in to the [Cloudflare dashboard](https://dash.cloudflare.com/) and select your account and domain. Go to **Email**.
```suggestion
1. Log in to the [Cloudflare dashboard](https://dash.cloudflare.com/) and select your account and domain.
1. Go to **Email**.
```

2021-11-18 15:33 UTC, pedrosousa commented on products/email-routing/src/content/enable-email-routing.md
> +1. In **Custom addresses**, click **Create address**. Enter the email address you want to use in the **Custom address** field (for example, `my-new-email`).
```suggestion
1. In **Custom addresses**, click **Create address**. Enter the email address you want to use in **Custom address** (for example, `my-new-email`).
```

2021-11-18 15:33 UTC, pedrosousa commented on products/email-routing/src/content/enable-email-routing.md
> +Cloudflare will send you a verification email to the address provided in the Destination address field. You must click **Verify email address** in the verification email to activate Email Routing.
```suggestion
Cloudflare will send a verification email to the address provided in the Destination address field. You must click **Verify email address** in the verification email to activate Email Routing.
```

2021-11-18 15:33 UTC, pedrosousa commented on products/email-routing/src/content/enable-email-routing.md
> +After creating your email alias and verifying your destination address, Cloudflare needs to add the relevant MX and TXT records to DNS records for Email Routing to work. This step is automatic and is
I don't think we called it "alias" before. Should it be "email custom address" also?

2021-11-18 16:00 UTC, marciocloudflare commented on products/email-routing/src/content/enable-email-routing.md
> +After creating your email alias and verifying your destination address, Cloudflare needs to add the relevant MX and TXT records to DNS records for Email Routing to work. This step is automatic and is
Yes!

2021-11-18 16:02 UTC, marciocloudflare commented on products/email-routing/src/content/icons/email.js
> +module.exports = {
Will do

2021-11-18 16:06 UTC, marciocloudflare commented on products/email-routing/README.md
> +[Read contributor guidelines →](https://developers.cloudflare.com/docs-engine/contributing/content-framework)
Good catch!

2021-11-18 16:12 UTC, marciocloudflare commented on products/email-routing/docs-config.js
> +  search: {
done

2021-11-18 19:16 UTC, pedrosousa approved these changes

2021-11-19 08:49 UTC, merged