Migrate Automatic HTTPS rewrites and remove bold from definition in p…
cloudflare/cloudflare-docs pull request #2627
Opened 2021-11-03 16:49 UTC by angelampcosta

…artials

2021-11-03 17:08 UTC, kodster28 commented
Oh, also don't forget to update the main `Index` page with the new link to dev docs (vs the current support link).

2021-11-03 17:08 UTC, kodster28 requested changes

2021-11-03 17:08 UTC, kodster28 commented on products/ssl/src/content/_partials/_automatic-https-rewrites-definition.md
> +Automatic HTTPS Rewrites prevents end users from seeing "mixed content" errors by rewriting URLs from `http` to `https` for resources or links on your web site that can be served with HTTPS.
```suggestion
Automatic HTTPS Rewrites prevent end users from seeing "mixed content" errors by rewriting URLs from `http` to `https` for resources or links on your web site that can be served with HTTPS.
```

2021-11-03 17:08 UTC, kodster28 commented on products/ssl/src/content/edge-certificates/additional-options/automatic-https-rewrites.md
> +Enable **Automatic HTTPS Rewrites** via the **SSL/TLS** app to rewrite HTTP resources as HTTPS at Cloudflare without making any changes to the HTML source at your origin server.
I'd separate this out into another section, maybe change this one to `Additional details` and make the how to `Enable Automatic HTTPS Rewrites`.

2021-11-03 17:08 UTC, kodster28 commented on products/ssl/src/content/edge-certificates/additional-options/automatic-https-rewrites.md
> +The HTTP resources are checked to ensure they are accessible via HTTPS before a rewrite is applied. In cases where a resource is not available over HTTPS, Cloudflare cannot rewrite the URL.
I'd consolidate this into one sentence and remove the passive voice if possible.

2021-11-03 17:08 UTC, kodster28 commented on products/ssl/src/content/edge-certificates/additional-options/automatic-https-rewrites.md
> +## Related Resources
I'd move these related resources into the body of the description and remove this section entirely, if possible.

2021-11-04 20:36 UTC, kodster28 approved these changes

2021-11-05 09:37 UTC, merged

2021-11-22 16:43 UTC, Soeparmadi commented
How are you?