Image resizing origin-auth
cloudflare/cloudflare-docs pull request #2633
Opened 2021-11-04 15:38 UTC by marciocloudflare

1st draft

2021-11-04 15:52 UTC, xtuc commented on products/images/src/content/image-resizing/control-origin-access.md
> +Clouflare supports resizing images through Workers on an authenticated ASW S3 origin:
```suggestion
Clouflare supports resizing images through Workers on an authenticated AWS S3 origin:
```

2021-11-04 15:55 UTC, xtuc commented on products/images/src/content/image-resizing/control-origin-access.md
> +Clouflare supports resizing images through Workers on an authenticated ASW S3 origin:
Note that this feature isn't only meant for S3. When enabled, any origins will be able to see the eyeball headers image resizing proxy now passes through. 

The work was driven by the S3 use-case and we even have S3 specific headers.

2021-11-04 15:57 UTC, marciocloudflare commented on products/images/src/content/image-resizing/control-origin-access.md
> +Clouflare supports resizing images through Workers on an authenticated ASW S3 origin:
I originally had `on authenticated origins, such as AWS S3:` but changed it at the last minute. Does it make more sense to change it to the way I had originally @xtuc ?

2021-11-04 16:05 UTC, xtuc commented on products/images/src/content/image-resizing/control-origin-access.md
> +Clouflare supports resizing images through Workers on an authenticated ASW S3 origin:
Yeah I think what you had makes more sense

2021-11-04 16:16 UTC, sejoker requested changes

2021-11-04 16:16 UTC, sejoker commented on products/images/src/content/image-resizing/control-origin-access.md
> +Clouflare supports resizing images through Workers on an authenticated ASW S3 origin:
```suggestion
In order to ensure good performance Cloudflare Image Resizing has to cache resized images. It would be unsafe to share images that are personalised for individual visitors. That's why it's generally not recommended to resize images stored with a restricted access. However in cases when customer is fine to store such images in the public cache Cloudflare supports resizing images through Workers on authenticated origins, such as AWS S3:
```

2021-11-04 16:16 UTC, sejoker commented on products/images/src/content/image-resizing/control-origin-access.md
> +For more information related to AWS S3 cookies and settings, refer to [Authenticating Requests (AWS Signature Version 4)](https://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-authenticating-request
```suggestion
For more information refer to [Authenticating Requests (AWS Signature Version 4)](https://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-authenticating-requests.html).
```

2021-11-04 16:16 UTC, sejoker commented on products/images/src/content/image-resizing/control-origin-access.md
>  ## Origin cache is shared
The whole "Origin cache is shared" section is obsolete and should be removed.

2021-11-04 16:16 UTC, sejoker commented on products/images/src/content/image-resizing/control-origin-access.md
> +## `origin-auth` option
```suggestion
## authenticated origin
```

2021-11-04 16:24 UTC, marciocloudflare commented on products/images/src/content/image-resizing/control-origin-access.md
>  ## Origin cache is shared
Will do

2021-11-04 17:01 UTC, sejoker approved these changes

2021-11-04 17:47 UTC, xtuc approved these changes

2021-11-04 18:13 UTC, pedrosousa approved these changes

2021-11-04 18:13 UTC, pedrosousa commented on products/images/src/content/image-resizing/control-origin-access.md
> +In order to ensure good performance, Cloudflare Image Resizing has to cache resized images. It would be unsafe to share images that are customized for individual visitors. This is why it is generally
```suggestion
To ensure good performance, Cloudflare Image Resizing caches resized images. Since it would not be safe to share images customized for individual visitors, it is generally not recommended to resize images stored with a restricted access. However, in cases where customer agrees to store such images in public cache, Cloudflare supports resizing images through Workers on authenticated origins, such as AWS S3:
```
I feel that "it would not be safe" sounds more natural than "it would be unsafe", but it's your call.

2021-11-04 18:13 UTC, pedrosousa commented on products/images/src/content/image-resizing/control-origin-access.md
> +When this option is enabled, the following headers are passed through to the origin, and allow your request to be successful:
If there's a specific line that you wish to highlight in the example code block above (maybe line 117?), consider adding a [highlight](https://developers.cloudflare.com/docs-engine/reference/markdown#highlight) to the code block on that single line.

Nit: I'd probably repeat the option name here:
> When the authenticated origin option is enabled, ...

2021-11-04 18:13 UTC, pedrosousa commented on products/images/src/content/image-resizing/control-origin-access.md
> +* Authorization
Not sure if these should appear with monospaced formatting (I've used it for HTTP header names in the Support KB).

2021-11-05 08:59 UTC, marciocloudflare commented on products/images/src/content/image-resizing/control-origin-access.md
> +When this option is enabled, the following headers are passed through to the origin, and allow your request to be successful:
I'll check it with Yevgen if we need to highlight something in the code

2021-11-05 08:59 UTC, marciocloudflare commented on products/images/src/content/image-resizing/control-origin-access.md
> +* Authorization
Good catch!

2021-11-05 10:24 UTC, merged