[Workers] Added a tutorial for storing data with Fauna in tutorials/store-data-with-fauna/index.md
cloudflare/cloudflare-docs pull request #2646
Opened 2021-11-05 14:06 UTC by rts-rob

* Added a tutorial for storing data with Fauna

2021-11-08 22:15 UTC, lukeed reviewed
This is really great! 🤩 Thanks for adding this @rts-rob !

Majority of these are related to our style guide / formatting... no real content changes. I'll comb back thru and batch-commit those, leaving the _actual_ comments behind for viewing

2021-11-08 22:15 UTC, lukeed commented on products/workers/src/content/tutorials/store-data-with-fauna/index.md
> +* How to use [Worktop][worktop]] to add routing to your Workers.
```suggestion
* How to use [Worktop][worktop] to add routing to your Workers.
```

2021-11-08 22:15 UTC, lukeed commented on products/workers/src/content/tutorials/store-data-with-fauna/index.md
> +Building with Fauna, Workers, and Worktop enables you to create a globally distributed, strongly consistent, fully serverless REST API in a single repository. You can develop and reason about your ap
```suggestion
Building with Fauna, Workers, and Worktop enables you to create a globally distributed, strongly consistent, fully serverless REST API in a single repository. You can develop and reason about your application as if it were a monolith but gain the resilience and reduced latency of a distributed application running at the edge.
```

2021-11-08 22:15 UTC, lukeed commented on products/workers/src/content/tutorials/store-data-with-fauna/index.md
> +Fauna is a document-based database with a flexible schema. Your product documents include the following data:
Think we need a sentence or two before listing off the properties. Something like this maybe:

```suggestion
Fauna is a document-based database with a flexible schema. This allows you to define the structure of your data – whatever it may be – and store document that adhere to that structure. In this tutorial, you will be building a product inventory, where each `product` document must contain the following properties:
```

2021-11-08 22:15 UTC, lukeed commented on products/workers/src/content/tutorials/store-data-with-fauna/index.md
> +Documents are stored in the **Products** [collection][fauna-collections]. Collections in Fauna are simply buckets of documents.
```suggestion
Documents are stored in the **Products** [collection][fauna-collections]. A collection is Faun's terminology for a  bucket of related documents.
```

2021-11-08 22:15 UTC, lukeed commented on products/workers/src/content/tutorials/store-data-with-fauna/index.md
> +For simplicity's sake, the endpoints of your API will be public. For more information on authenticating users to your applications with Fauna, see [Choosing an authentication strategy with Fauna][fau
```suggestion
For this tutorial all API endpoints will be public; however, Fauna also offers multiple avenues for securing endpoints and collections. Refer to [Choosing an authentication strategy with Fauna][fauna-choosing-authentication-strategy] for more information on authenticating users to your Fauna applications.
```

2021-11-08 22:15 UTC, lukeed commented on products/workers/src/content/tutorials/store-data-with-fauna/index.md
> +> **Note**: If you do not have a Fauna account, you can [sign up for one][fauna-signup] and deploy this template using the free tier!
```suggestion
<Aside type="note" header="Fauna Account">

If you do not have a Fauna account, you can [sign up for one][fauna-signup] and deploy this template using the free tier!

</Aside>
```

2021-11-08 22:15 UTC, lukeed commented on products/workers/src/content/tutorials/store-data-with-fauna/index.md
> +Choose *Create database*, provide a valid name, select the *Classic* [Region Group][fauna-region-groups], and choose *Create*.
@deadlypants1973 I forget the formatting here, but these are steps / UI elements.

2021-11-08 22:15 UTC, lukeed commented on products/workers/src/content/tutorials/store-data-with-fauna/index.md
> +$ npm install worktop@0.6.3
@rts-rob This could probably be `worktop@0.7` – I haven't looked at the code yet but the only possible breaking change is that the `uid` util from `worktop/utils` now has a different dictionary. 

worktop@0.8 will have significant breaking changes, but specifying `worktop@0.7` won't pick those up :)

2021-11-08 22:15 UTC, lukeed commented on products/workers/src/content/tutorials/store-data-with-fauna/index.md
> +
```suggestion
```

2021-11-08 22:15 UTC, lukeed commented on products/workers/src/content/tutorials/store-data-with-fauna/index.md
> +The **customFetch()** function is necessary for the Fauna client because the Workers runtime uses a custom version of **fetch**. You can learn more about this in the [Fauna JavaScript driver document
```suggestion
The `customFetch` function is necessary for the Fauna client because the Workers runtime uses a custom `fetch` implementation. You can learn more about this in the [Fauna JavaScript driver documentation][fauna-js-docs].
```

2021-11-08 22:15 UTC, lukeed commented on products/workers/src/content/tutorials/store-data-with-fauna/index.md
> +The **customFetch()** function is necessary for the Fauna client because the Workers runtime uses a custom version of **fetch**. You can learn more about this in the [Fauna JavaScript driver document
This comment isn't quite right, but we can resolve this later. Remind me to play w/ this if I don't circle back soon :)

2021-11-08 22:15 UTC, lukeed commented on products/workers/src/content/tutorials/store-data-with-fauna/index.md
> +The **getFaunaError()** function extracts the [HTTP response status codes][http-status-codes] and description for the most common errors returned by Fauna.
```suggestion
The `getFaunaError` function extracts the [HTTP response status codes][http-status-codes] and description for the most common errors returned by Fauna.
```

2021-11-08 22:15 UTC, lukeed commented on products/workers/src/content/tutorials/store-data-with-fauna/index.md
> +Replace the contents of your **index.js** file with the skeleton of your API:
For our docs, all filenames are in code ticks

```suggestion
Replace the contents of your `index.js` file with the skeleton of your API:
```

2021-11-08 22:15 UTC, lukeed commented on products/workers/src/content/tutorials/store-data-with-fauna/index.md
> +Add your first Worktop route to the **index.js** file. This route accepts POST requests to the **/products** endpoint:
```suggestion
Add your first Worktop route to the `index.js` file. This route accepts `POST` requests to the `/products` URL endpoint:
```

2021-11-08 22:15 UTC, lukeed commented on products/workers/src/content/tutorials/store-data-with-fauna/index.md
> +Examining the route you create, when the query is successful, the **id** of the newly created document is returned in the response body:
```suggestion
Examining the route you create, when the query is successful, the ID of the newly created document is returned in the response body:
```

2021-11-08 22:15 UTC, lukeed commented on products/workers/src/content/tutorials/store-data-with-fauna/index.md
> +header: Returning the new document id
```suggestion
header: Returning the new document ID
```

2021-11-08 22:15 UTC, lukeed commented on products/workers/src/content/tutorials/store-data-with-fauna/index.md
> +Finally, if Fauna returns any error, an exception will be raised by the client. We'll catch that exception and respond with the result from the **getFaunaError()** utility function:
```suggestion
Finally, if Fauna returns any error, an exception will be raised by the client. We'll catch that exception and respond with the result from the `getFaunaError` utility function:
```

2021-11-08 22:15 UTC, lukeed commented on products/workers/src/content/tutorials/store-data-with-fauna/index.md
> +Add the following route to your **index.js** file. This route accepts **GET** requests at the **/products/:productId** endpoint:
```suggestion
Add the following route to your `index.js` file. This route accepts `GET` requests at the `/products/:productId` URL endpoint:
```

2021-11-08 22:15 UTC, lukeed commented on products/workers/src/content/tutorials/store-data-with-fauna/index.md
> +The logic to delete product documents is similar to the logic for retrieving products. Add the following route to your **index.js** file:
```suggestion
The logic to delete product documents is similar to the logic for retrieving products. Add the following route to your `index.js` file:
```

2021-11-08 22:15 UTC, lukeed commented on products/workers/src/content/tutorials/store-data-with-fauna/index.md
> +
```suggestion
```

2021-11-08 22:15 UTC, lukeed commented on products/workers/src/content/tutorials/store-data-with-fauna/index.md
> +
```suggestion
```

2021-11-08 22:15 UTC, lukeed commented on products/workers/src/content/tutorials/store-data-with-fauna/index.md
> +You should receive a **200** response similar to the following:
```suggestion
You should receive a `200` response similar to the following output:
```

2021-11-08 22:15 UTC, lukeed commented on products/workers/src/content/tutorials/store-data-with-fauna/index.md
> +> **Note**: Copy and save the *productId* for use in the remaining test queries.
```suggestion
<Aside type="note"

Copy the `productId` value for use in the remaining test queries.

</Aside>
```

2021-11-08 22:15 UTC, lukeed commented on products/workers/src/content/tutorials/store-data-with-fauna/index.md
> +```console
```suggestion
```sh
```

2021-11-08 22:15 UTC, lukeed commented on products/workers/src/content/tutorials/store-data-with-fauna/index.md
> +Finally, deploy your Worker using the wrangler [publish][wrangler-publish] command:
```suggestion
Finally, deploy your Worker using the [`wrangler publish`][wrangler-publish] command:
```

2021-11-08 22:15 UTC, lukeed commented on products/workers/src/content/tutorials/store-data-with-fauna/index.md
> +This publishes your Worker to Cloudflare and makes it available on your **workers.dev** subdomain.
```suggestion
This publishes the Worker to your `*.workers.dev` subdomain.
```

2021-11-08 22:15 UTC, lukeed commented on products/workers/src/content/tutorials/store-data-with-fauna/index.md
> +As a last step, you implement a route to update the quantity of a product in your inventory, which by default is **0**.
```suggestion
As a last step, you implement a route to update the quantity of a product in your inventory, which `0` by default.
```

2021-11-08 22:15 UTC, lukeed commented on products/workers/src/content/tutorials/store-data-with-fauna/index.md
> +Instead, you can read and update the quantity of a product in a single FQL transaction. It's important to mention that all FQL queries are in fact transactions. If anything fails, all changes are rev
```suggestion
Instead, Fauna allows you to solve this by reading and updating the quantity of a product in a single FQL transaction. It's important to mention that all FQL queries are, in fact, transactions. If anything fails, all changes are reverted back thanks to Fauna's ACID properties.
```

2021-11-08 22:15 UTC, lukeed commented on products/workers/src/content/tutorials/store-data-with-fauna/index.md
> +Add the following route to your **index.js** file. This route responds to HTTP **PATCH** requests on the **/products/:productId/add-quantity** endpoint:
```suggestion
Add the following route to your `index.js` file. This route responds to HTTP `PATCH` requests on the `/products/:productId/add-quantity` URL endpoint:
```

2021-11-08 22:15 UTC, lukeed commented on products/workers/src/content/tutorials/store-data-with-fauna/index.md
> +
```suggestion
```

2021-11-08 22:15 UTC, lukeed commented on products/workers/src/content/tutorials/store-data-with-fauna/index.md
> +
```suggestion
```

2021-11-08 22:15 UTC, lukeed commented on products/workers/src/content/tutorials/store-data-with-fauna/index.md
> +After declaring the variables, **Let** accepts an FQL expression as a second parameter. This expression is where you update your document:
```suggestion
You can access the values of variables created by `Let` in any subsequent FQL expressions by using the FQL [Var][fql-var] function.

After declaring the variables, `Let` accepts an FQL expression as a second parameter. This expression is where you update your document:
```

2021-11-08 22:15 UTC, lukeed commented on products/workers/src/content/tutorials/store-data-with-fauna/index.md
> +Finally, this query calculates the new total quantity by adding the value of **quantity** to **currentQuantity** using the FQL [Add][fql-add] function.
```suggestion
The FQL [Update][fql-update] function *only* updates the provided properties of a document. In this example, only the `quantity` property is updated.

Finally, this query calculates the new total quantity by adding the value of `quantity` to `currentQuantity` using the FQL [Add][fql-add] function.
```

2021-11-08 22:15 UTC, lukeed commented on products/workers/src/content/tutorials/store-data-with-fauna/index.md
> +> **Note**: Even if multiple Workers update this quantity from different parts of the world, Fauna guarantees the consistency of the data across all Fauna regions! [This article][fauna-blog-consisten
```suggestion
<Aside type="note" header="Consistency guarantees in Fauna">

Even if multiple Workers update this quantity from different parts of the world, Fauna guarantees the consistency of the data across all Fauna regions! [This article][fauna-blog-consistency-without-clocks] explains how Fauna's distributed protocol works without the need for atomic clocks.

</Aside>
```

2021-11-08 22:15 UTC, lukeed commented on products/workers/src/content/tutorials/store-data-with-fauna/index.md
> +```console
```suggestion
```sh
```

2021-11-08 22:17 UTC, lukeed commented
JK – it's not letting me apply suggestions. Is the "allow maintainers to edit" option checked?

2021-11-08 23:55 UTC, rts-rob commented
> JK – it's not letting me apply suggestions. Is the "allow maintainers to edit" option checked?

Odd - it doesn't give me the option. It's not that it _isn't_ checked, it just isn't there at all.

Ok with you if I push a new commit integrating your requested changes?

2021-11-09 00:18 UTC, lukeed commented
Yes of course! It's just a lot more manual/tedious for you that way. Sorry about that

2021-11-09 14:16 UTC, rts-rob commented on products/workers/src/content/tutorials/store-data-with-fauna/index.md
> +* How to use [Worktop][worktop]] to add routing to your Workers.
Added to next commit as is.

2021-11-09 14:42 UTC, rts-rob reviewed
Commented on each individual issue as I updated on the original branch.

I believe this leaves two open items:

1. Line 47: @lukeed and @deadlypants1973 formatting for steps / UI elements
2. Line 116: @lukeed and @rts-rob to discuss Worktop `0.6.3` -> `0.7` migration

Thanks for the quick and thorough review, @lukeed!

2021-11-09 14:42 UTC, rts-rob commented on products/workers/src/content/tutorials/store-data-with-fauna/index.md
> +Building with Fauna, Workers, and Worktop enables you to create a globally distributed, strongly consistent, fully serverless REST API in a single repository. You can develop and reason about your ap
Added to next commit as is.

2021-11-09 14:42 UTC, rts-rob commented on products/workers/src/content/tutorials/store-data-with-fauna/index.md
> +Fauna is a document-based database with a flexible schema. Your product documents include the following data:
Added to next commit with minor changes, e.g., "document" -> "documents", future tense to present tense.

2021-11-09 14:42 UTC, rts-rob commented on products/workers/src/content/tutorials/store-data-with-fauna/index.md
> +Documents are stored in the **Products** [collection][fauna-collections]. Collections in Fauna are simply buckets of documents.
Added to next commit as: "Collections in document databases are groups of related documents."

2021-11-09 14:42 UTC, rts-rob commented on products/workers/src/content/tutorials/store-data-with-fauna/index.md
> +For simplicity's sake, the endpoints of your API will be public. For more information on authenticating users to your applications with Fauna, see [Choosing an authentication strategy with Fauna][fau
Added to next commit with minor changes, e.g.: future tense -> present, replace semicolon

2021-11-09 14:42 UTC, rts-rob commented on products/workers/src/content/tutorials/store-data-with-fauna/index.md
> +> **Note**: If you do not have a Fauna account, you can [sign up for one][fauna-signup] and deploy this template using the free tier!
Added to next commit as is.

2021-11-09 14:42 UTC, rts-rob commented on products/workers/src/content/tutorials/store-data-with-fauna/index.md
> +$ npm install worktop@0.6.3
@lukeed I'm happy to make it `worktop@0.7` if you can walk me through the workaround for webpack.

2021-11-09 14:42 UTC, rts-rob commented on products/workers/src/content/tutorials/store-data-with-fauna/index.md
> +
Removed in next commit.

2021-11-09 14:42 UTC, rts-rob commented on products/workers/src/content/tutorials/store-data-with-fauna/index.md
> +The **customFetch()** function is necessary for the Fauna client because the Workers runtime uses a custom version of **fetch**. You can learn more about this in the [Fauna JavaScript driver document
Yeah we've been asking that internally - would like to get this language right (and remove `customFetch` if possible).

2021-11-09 14:42 UTC, rts-rob commented on products/workers/src/content/tutorials/store-data-with-fauna/index.md
> +The **customFetch()** function is necessary for the Fauna client because the Workers runtime uses a custom version of **fetch**. You can learn more about this in the [Fauna JavaScript driver document
Made other changes in next commit as is.

2021-11-09 14:42 UTC, rts-rob commented on products/workers/src/content/tutorials/store-data-with-fauna/index.md
> +The **getFaunaError()** function extracts the [HTTP response status codes][http-status-codes] and description for the most common errors returned by Fauna.
Added to next commit as is.

2021-11-09 14:42 UTC, rts-rob commented on products/workers/src/content/tutorials/store-data-with-fauna/index.md
> +Replace the contents of your **index.js** file with the skeleton of your API:
Added to next commit as is.

2021-11-09 14:42 UTC, rts-rob commented on products/workers/src/content/tutorials/store-data-with-fauna/index.md
> +Add your first Worktop route to the **index.js** file. This route accepts POST requests to the **/products** endpoint:
Added to next commit as is.

2021-11-09 14:42 UTC, rts-rob commented on products/workers/src/content/tutorials/store-data-with-fauna/index.md
> +Examining the route you create, when the query is successful, the **id** of the newly created document is returned in the response body:
Added to next commit as is.

2021-11-09 14:42 UTC, rts-rob commented on products/workers/src/content/tutorials/store-data-with-fauna/index.md
> +header: Returning the new document id
Added to next commit as is.

2021-11-09 14:42 UTC, rts-rob commented on products/workers/src/content/tutorials/store-data-with-fauna/index.md
> +Finally, if Fauna returns any error, an exception will be raised by the client. We'll catch that exception and respond with the result from the **getFaunaError()** utility function:
Added with minor changes (1st person to 2nd person, future tense to present tense).

2021-11-09 14:42 UTC, rts-rob commented on products/workers/src/content/tutorials/store-data-with-fauna/index.md
> +Add the following route to your **index.js** file. This route accepts **GET** requests at the **/products/:productId** endpoint:
Added as is in the next commit.

2021-11-09 14:42 UTC, rts-rob commented on products/workers/src/content/tutorials/store-data-with-fauna/index.md
> +The logic to delete product documents is similar to the logic for retrieving products. Add the following route to your **index.js** file:
Added as is to the next commit.

2021-11-09 14:42 UTC, rts-rob commented on products/workers/src/content/tutorials/store-data-with-fauna/index.md
> +
Removed in next commit.

2021-11-09 14:42 UTC, rts-rob commented on products/workers/src/content/tutorials/store-data-with-fauna/index.md
> +
Removed in next commit.

2021-11-09 14:42 UTC, rts-rob commented on products/workers/src/content/tutorials/store-data-with-fauna/index.md
> +You should receive a **200** response similar to the following:
Added as is to next commit

2021-11-09 14:42 UTC, rts-rob commented on products/workers/src/content/tutorials/store-data-with-fauna/index.md
> +> **Note**: Copy and save the *productId* for use in the remaining test queries.
Added as is to the next commit.

2021-11-09 14:42 UTC, rts-rob commented on products/workers/src/content/tutorials/store-data-with-fauna/index.md
> +```console
Added as is to the next commit.

2021-11-09 14:42 UTC, rts-rob commented on products/workers/src/content/tutorials/store-data-with-fauna/index.md
> +Finally, deploy your Worker using the wrangler [publish][wrangler-publish] command:
Added as is to next commit.

2021-11-09 14:42 UTC, rts-rob commented on products/workers/src/content/tutorials/store-data-with-fauna/index.md
> +```console
Did a find/replace on ```` ```console```` -> ```` ```sh```` throughout the document

2021-11-09 14:42 UTC, rts-rob commented on products/workers/src/content/tutorials/store-data-with-fauna/index.md
> +This publishes your Worker to Cloudflare and makes it available on your **workers.dev** subdomain.
Added to next commit as is.

2021-11-09 14:42 UTC, rts-rob commented on products/workers/src/content/tutorials/store-data-with-fauna/index.md
> +As a last step, you implement a route to update the quantity of a product in your inventory, which by default is **0**.
Added to next commit with minor modification, e.g. "which _is_ `0`"

2021-11-09 14:42 UTC, rts-rob commented on products/workers/src/content/tutorials/store-data-with-fauna/index.md
> +Instead, you can read and update the quantity of a product in a single FQL transaction. It's important to mention that all FQL queries are in fact transactions. If anything fails, all changes are rev
Added to next commit with minor changes, e.g., "Fauna solves this by..."

2021-11-09 14:42 UTC, rts-rob commented on products/workers/src/content/tutorials/store-data-with-fauna/index.md
> +Add the following route to your **index.js** file. This route responds to HTTP **PATCH** requests on the **/products/:productId/add-quantity** endpoint:
Added to next commit as is.

2021-11-09 14:42 UTC, rts-rob commented on products/workers/src/content/tutorials/store-data-with-fauna/index.md
> +
Removed in next commit.

2021-11-09 14:42 UTC, rts-rob commented on products/workers/src/content/tutorials/store-data-with-fauna/index.md
> +
Removed in next commit.

2021-11-09 14:42 UTC, rts-rob commented on products/workers/src/content/tutorials/store-data-with-fauna/index.md
> +After declaring the variables, **Let** accepts an FQL expression as a second parameter. This expression is where you update your document:
Added to next commit as is.

2021-11-09 14:42 UTC, rts-rob commented on products/workers/src/content/tutorials/store-data-with-fauna/index.md
> +Finally, this query calculates the new total quantity by adding the value of **quantity** to **currentQuantity** using the FQL [Add][fql-add] function.
Added to next commit as is.

2021-11-09 14:42 UTC, rts-rob commented on products/workers/src/content/tutorials/store-data-with-fauna/index.md
> +> **Note**: Even if multiple Workers update this quantity from different parts of the world, Fauna guarantees the consistency of the data across all Fauna regions! [This article][fauna-blog-consisten
Added to next commit as is

2021-11-09 14:42 UTC, rts-rob commented on products/workers/src/content/tutorials/store-data-with-fauna/index.md
> +```console
Added to next commit as is.

2021-11-09 18:38 UTC, lukeed commented on products/workers/src/content/tutorials/store-data-with-fauna/index.md
> +<Aside type="note"
```suggestion
<Aside type="note">
```

2021-11-09 22:58 UTC, lukeed commented
We took care of the `worktop@0.7` upgrade here: https://github.com/fauna-labs/fauna-workers/pull/1
The PR also removes the `customFetch` util, which wasn't needed.

2021-11-11 12:16 UTC, deadlypants1973 approved these changes

2021-11-11 12:16 UTC, deadlypants1973 commented on products/workers/src/content/tutorials/store-data-with-fauna/index.md
> +<Aside type="warning" header="Protect your keys!">
```suggestion
<Aside type="warning" header="Protect your keys">
```

2021-11-11 12:16 UTC, deadlypants1973 commented on products/workers/src/content/tutorials/store-data-with-fauna/index.md
> +Server keys can read and write all documents in all collections and can call all [user-defined functions][fauna-udfs] (UDFs). Protect server keys and do not commit them to source control repositories
```suggestion
Server keys can read and write all documents in all collections and can call all [user-defined functions][fauna-udfs] (UDFs). Protect server keys and do not commit them to source control repositories.
```

2021-11-11 13:08 UTC, deadlypants1973 requested changes

2021-11-11 13:08 UTC, deadlypants1973 commented on products/workers/src/content/tutorials/store-data-with-fauna/index.md
> +Open the [Fauna dashboard][fauna-dashboard] in your browser and login to your Fauna account.
```suggestion
Open the [Fauna dashboard][fauna-dashboard] in your browser and log into your Fauna account. 
```

2021-11-11 13:08 UTC, deadlypants1973 commented on products/workers/src/content/tutorials/store-data-with-fauna/index.md
> +If you do not have a Fauna account, you can [sign up for one][fauna-signup] and deploy this template using the free tier!
```suggestion
If you do not have a Fauna account, you can [sign up][fauna-signup] and deploy this template using the free tier.
```

2021-11-11 13:08 UTC, deadlypants1973 commented on products/workers/src/content/tutorials/store-data-with-fauna/index.md
> +Choose *Create database*, provide a valid name, select the *Classic* [Region Group][fauna-region-groups], and choose *Create*.
```suggestion
In the Fauna dashboard:
1. Select **Create database**.
2. Provide a valid name.
3. Select the **Classic** [Region Group][fauna-region-groups].
4. Select **Create**.
```

2021-11-11 13:08 UTC, deadlypants1973 commented on products/workers/src/content/tutorials/store-data-with-fauna/index.md
> +Next, choose *New Collection* to create the **Products** collection that stores your inventory documents.
```suggestion
Next, select **New Collection** to create the **Products** collection that stores your inventory documents.
```

2021-11-11 13:08 UTC, deadlypants1973 commented on products/workers/src/content/tutorials/store-data-with-fauna/index.md
> +Navigate to the *Security* tab in the dashboard and create a new key with the *Server* role:
```suggestion
Navigate to the **Security** tab in the Fauna dashboard and create a new key with the **Server** role:
```

2021-11-11 13:08 UTC, deadlypants1973 commented on products/workers/src/content/tutorials/store-data-with-fauna/index.md
> +The dashboard displays the key's secret. Copy and save this server key to use in a later step.
```suggestion
The Fauna dashboard displays the key's secret. Copy and save this server key to use in a later step.
```

2021-11-11 13:08 UTC, deadlypants1973 commented on products/workers/src/content/tutorials/store-data-with-fauna/index.md
> +Worktop solves common needs such as routing, path parameters, HTTP methods, and more.
```suggestion
Worktop solves common needs such as routing, path parameters, and  HTTP methods.
```

2021-11-11 13:08 UTC, deadlypants1973 commented on products/workers/src/content/tutorials/store-data-with-fauna/index.md
> +Edit the `wrangler.toml` file that wrangler generates. Make sure the type is set to `"javascript"` (**not** `"webpack"`) and add the `[build]` and `[build.upload]` sections as shown in the following
```suggestion
Edit your `wrangler.toml` file found in your Worker's project directory. Set the type to `"javascript"` (not `"webpack"`) and add the `[build]` and `[build.upload]` sections as shown in the following snippet:
```

2021-11-11 13:08 UTC, deadlypants1973 commented on products/workers/src/content/tutorials/store-data-with-fauna/index.md
> +Create the **utils.js** file in the project folder and paste the following code:
```suggestion
Create a `utils.js` file in the project folder and paste the following code:
```

2021-11-11 13:08 UTC, deadlypants1973 commented on products/workers/src/content/tutorials/store-data-with-fauna/index.md
> +To see what a document looks like, navigate to the *Shell* tab in the Fauna dashboard and run the following query:
```suggestion
To see what a document looks like, navigate to the **Shell** tab in the Fauna dashboard and run the following query:
```

2021-11-11 13:08 UTC, deadlypants1973 commented on products/workers/src/content/tutorials/store-data-with-fauna/index.md
> +As a last step, you implement a route to update the quantity of a product in your inventory, which is `0` by default.
```suggestion
As the last step, implement a route to update the quantity of a product in your inventory, which is `0` by default.
```

2021-11-11 13:08 UTC, deadlypants1973 commented on products/workers/src/content/tutorials/store-data-with-fauna/index.md
> +This presents a problem though. To calculate the total quantity of a product, you first need to determine how many items there currently are in your inventory. If you solve this in two queries, first
```suggestion
This will present a problem. To calculate the total quantity of a product, you first need to determine how many items there currently are in your inventory. If you solve this in two queries, first reading the quantity and then updating it, the original data might change.
```

2021-11-11 13:08 UTC, deadlypants1973 commented on products/workers/src/content/tutorials/store-data-with-fauna/index.md
> +The FQL [Update][fql-update] function *only* updates the provided properties of a document. In this example, only the `quantity` property is updated.
```suggestion
The FQL [Update][fql-update] function only updates the provided properties of a document. In this example, only the `quantity` property is updated.
```

2021-11-11 13:08 UTC, deadlypants1973 commented on products/workers/src/content/tutorials/store-data-with-fauna/index.md
> +Even if multiple Workers update this quantity from different parts of the world, Fauna guarantees the consistency of the data across all Fauna regions! [This article][fauna-blog-consistency-without-c
```suggestion
Even if multiple Workers update this quantity from different parts of the world, Fauna guarantees the consistency of the data across all Fauna regions. [This article][fauna-blog-consistency-without-clocks] explains how Fauna's distributed protocol works without the need for atomic clocks.
```

2021-11-11 13:08 UTC, deadlypants1973 commented on products/workers/src/content/tutorials/store-data-with-fauna/index.md
> +Update your Worker by publishing it to Cloudflare, and you're done!
```suggestion
Update your Worker by publishing it to Cloudflare.
```

2021-11-11 13:08 UTC, deadlypants1973 commented on products/workers/src/content/tutorials/store-data-with-fauna/index.md
> +To remove the resources you create in this tutorial, first delete your Worker from its *Settings* tab in the Cloudflare dashboard:
```suggestion
To remove the resources you create in this tutorial, delete your Worker in the Cloudflare dashboard > **Workers** > **Manage Workers** > **your Worker** > **Settings** > **Delete**:
```

2021-11-11 13:08 UTC, deadlypants1973 commented on products/workers/src/content/tutorials/store-data-with-fauna/index.md
> +To build your own production-ready applications, check out the [Fauna Workers quickstart](https://github.com/fauna-labs/fauna-workers). The quickstart implements suggested practices like a least-priv
```suggestion
To build your own production-ready applications, refer to the [Fauna Workers quickstart](https://github.com/fauna-labs/fauna-workers). The quickstart implements suggested practices like a least-privilege security model and business logic encapsulation in user-defined functions.
```

2021-11-11 13:12 UTC, deadlypants1973 commented
> Commented on each individual issue as I updated on the original branch.
> 
> I believe this leaves two open items:
> 
> 1. Line 47: @lukeed and @deadlypants1973 formatting for steps / UI elements
> 2. Line 116: @lukeed and @rts-rob to discuss Worktop `0.6.3` -> `0.7` migration
> 
> Thanks for the quick and thorough review, @lukeed!

@rts-rob Hi Rob, thank you for the tutorial :) I've just added my comments on UI directions and style guide formatting.

2021-11-11 14:16 UTC, deadlypants1973 approved these changes

2021-11-11 14:55 UTC, merged