Update 1.1.1.1 docs for DoH JSON API
cloudflare/cloudflare-docs pull request #2681
Opened 2021-11-11 20:26 UTC by xofyarg

Deprecates the use of "ct" parameter according to RFC-8484.

2021-11-11 21:12 UTC, elithrar requested changes
Minor suggestion.

2021-11-11 21:12 UTC, elithrar commented on products/1.1.1.1/src/content/encrypted-dns/dns-over-https/make-api-requests/dns-json.md
> +JSON formatted queries are sent using a `GET` request. When making requests using `GET`, the DNS query is encoded into the URL. The client should include an HTTP Accept request header field to indica
... an HTTP `Accept` request header field with a MIME type of `application/dns-json` to indicate that the client is able to accept a JSON response from the DNS over HTTPS resolver.

(replace to the end of the sentence)

2021-11-11 21:18 UTC, xofyarg commented on products/1.1.1.1/src/content/encrypted-dns/dns-over-https/make-api-requests/dns-json.md
> +JSON formatted queries are sent using a `GET` request. When making requests using `GET`, the DNS query is encoded into the URL. The client should include an HTTP Accept request header field to indica
Updated, thanks.

2021-11-12 09:13 UTC, marciocloudflare approved these changes

2021-11-12 09:13 UTC, merged