Style changes, clarify websocket pricing for DO
cloudflare/cloudflare-docs pull request #2713
Opened 2021-11-15 17:00 UTC by greg-mckeon

2021-11-16 12:52 UTC, deadlypants1973 approved these changes

2021-11-16 17:56 UTC, koeninger commented on products/workers/src/content/runtime-apis/durable-objects.md
> +The API for listing objects in a namespace is available [here](https://api.cloudflare.com/client/v4/accounts/$YOUR_ACCOUNT_ID/workers/durable_objects/namespaces/$NAMESPACE_ID/objects).
same comment as original pr - this shouldn't be a hyperlink, the url is the information we're trying to conver, and isn't useful until someone replaces their account id / namespace id in it

2021-11-17 16:18 UTC, deadlypants1973 commented on products/workers/src/content/runtime-apis/durable-objects.md
> +The API for listing namespaces is available [here](https://api.cloudflare.com/client/v4/accounts/$YOUR_ACCOUNT_ID/workers/durable_objects/namespaces).
```suggestion
The API for listing namespaces is available at https://api.cloudflare.com/client/v4/accounts/$YOUR_ACCOUNT_ID/workers/durable_objects/namespaces.
```

2021-11-17 16:18 UTC, deadlypants1973 commented on products/workers/src/content/runtime-apis/durable-objects.md
> +The API for listing objects in a namespace is available [here](https://api.cloudflare.com/client/v4/accounts/$YOUR_ACCOUNT_ID/workers/durable_objects/namespaces/$NAMESPACE_ID/objects).
```suggestion
The API for listing objects in a namespace is available at https://api.cloudflare.com/client/v4/accounts/$YOUR_ACCOUNT_ID/workers/durable_objects/namespaces/$NAMESPACE_ID/objects.
```

2021-11-17 17:24 UTC, koeninger commented on products/workers/src/content/runtime-apis/durable-objects.md
> +The API for listing objects in a namespace is available [here](https://api.cloudflare.com/client/v4/accounts/$YOUR_ACCOUNT_ID/workers/durable_objects/namespaces/$NAMESPACE_ID/objects).
v4 api docs for durable objects are now live at

https://api.cloudflare.com/#durable-objects-namespace-list-namespaces
and
https://api.cloudflare.com/#durable-objects-namespace-list-objects

if we want to link there instead

2021-12-06 17:03 UTC, koeninger requested changes

2021-12-06 17:03 UTC, koeninger commented on products/workers/src/content/runtime-apis/durable-objects.md
> +The API for listing objects in a namespace is available at https://api.cloudflare.com/client/v4/accounts/$YOUR_ACCOUNT_ID/workers/durable_objects/namespaces/$NAMESPACE_ID/objects.
This section is correct in production as of https://github.com/cloudflare/cloudflare-docs/pull/2824 and shouldn't be changed back here.

2022-07-18 11:25 UTC, closed without merging