[Workers] learning revision
cloudflare/cloudflare-docs pull request #2783
Opened 2021-11-24 20:46 UTC by deadlypants1973

2021-11-24 20:50 UTC, lukeed commented on products/workers/src/content/learning/how-workers-works.md
> +The differences between JavaScript written for the browser or Node.js happen at runtime. Rather than running on an individual's machine (for example, [a browser application or on a centralized server
```suggestion
The differences between JavaScript written for the browser or Node.js happen at runtime. Rather than running on an individual's machine; for example, [a browser application or on a centralized server](https://www.cloudflare.com/learning/serverless/glossary/client-side-vs-server-side/), Workers functions run on [Cloudflare's Edge Network](https://www.cloudflare.com/network) - a growing global network of thousands of machines distributed across hundreds of locations.
```

2021-11-24 20:50 UTC, lukeed commented on products/workers/src/content/learning/how-workers-works.md
> +- a suspicious script - anything seen as trying to break out of the isolate sandbox.
```suggestion
- a suspicious script - anything seen as trying to break out of the Isolate sandbox.
```

2021-11-24 20:51 UTC, lukeed approved these changes

2021-11-25 10:30 UTC, marciocloudflare requested changes

2021-11-25 10:30 UTC, marciocloudflare commented on products/workers/src/content/learning/how-workers-works.md
> +The differences between JavaScript written for the browser or Node.js happen at runtime. Rather than running on an individual's machine; for example, [a browser application or on a centralized server
```suggestion
The differences between JavaScript written for the browser or Node.js happen at runtime. Rather than running on an individual's machine (for example, [a browser application or on a centralized server](https://www.cloudflare.com/learning/serverless/glossary/client-side-vs-server-side/)), Workers functions run on [Cloudflare's Edge Network](https://www.cloudflare.com/network) - a growing global network of thousands of machines distributed across hundreds of locations.
```

2021-11-25 10:30 UTC, marciocloudflare commented on products/workers/src/content/learning/how-workers-works.md
> +Each of these machines hosts an instance of the Workers runtime, and each of those runtimes is capable of running thousands of user-defined apps. This guide will understand some of those differences.
Shouldn't the guide `explain` some of the differences? I don't think a guide `understands` differences. Maybe I'm missing some context here?

2021-11-25 10:30 UTC, marciocloudflare commented on products/workers/src/content/learning/how-workers-works.md
> +[V8](https://v8.dev) orchestrates isolates: lightweight contexts that group variables with the code allowed to mutate them. You could even consider an isolate a sandbox for your function to run in.
I have no idea what this sentence means. What's the `code` referred here? The `code allowed to mutate them`? I think I understand the beginning of the sentence, but this last part makes no sense to me. So the V8 engine coordinates isolates. Isolates are "lightweight contexts" that group variables with some code. Is this correct up until here? The rest I don't understand.

2021-11-25 10:30 UTC, marciocloudflare commented on products/workers/src/content/learning/how-workers-works.md
> +When a request to your `*.workers.dev` subdomain or to your Cloudflare-managed domain is received by any of Cloudflare's runtimes, the Workers script is passed a [`FetchEvent`](/runtime-apis/fetch-ev
```suggestion
When a request to your `*.workers.dev` subdomain or to your Cloudflare-managed domain is received by any of Cloudflare's runtimes, the Workers script is passed a [`FetchEvent`](/runtime-apis/fetch-event) argument to the event handler defined in the script. From there you can generate a [`Response`](/runtime-apis/response) by computing a response on the spot, calling to another server using [`fetch`](/runtime-apis/fetch), etc.. The CPU cycles needed to get to the point of the `respondWith` call all contribute to the compute time. For example, a `setInterval` timeout does not consume CPU cycles while waiting.
```

2021-11-25 10:30 UTC, marciocloudflare commented on products/workers/src/content/learning/how-workers-works.md
> +When a request to your `*.workers.dev` subdomain or to your Cloudflare-managed domain is received by any of Cloudflare's runtimes, the Workers script is passed a [`FetchEvent`](/runtime-apis/fetch-ev
The sentence is so long I think `needed` makes it easier to understand, especially to non-natives.

2021-11-29 13:38 UTC, deadlypants1973 commented on products/workers/src/content/learning/how-workers-works.md
> +Each of these machines hosts an instance of the Workers runtime, and each of those runtimes is capable of running thousands of user-defined apps. This guide will understand some of those differences.
```suggestion
Each of these machines hosts an instance of the Workers runtime, and each of those runtimes is capable of running thousands of user-defined applications. This guide will review some of those differences.
```

2021-12-09 17:21 UTC, deadlypants1973 commented on products/workers/src/content/learning/how-workers-works.md
> +[V8](https://v8.dev) orchestrates isolates: lightweight contexts that group variables with the code allowed to mutate them. You could even consider an isolate a sandbox for your function to run in.
```suggestion
[V8](https://v8.dev) orchestrates isolates: lightweight contexts that provide your code with variables it can access and a safe environment to be executed within. You could even consider an isolate a sandbox for your function to run in.
```

2021-12-09 17:29 UTC, marciocloudflare approved these changes

2021-12-09 17:34 UTC, merged

2021-12-24 10:01 UTC, Juu33 reviewed
Lhttps://github.com/cloudflare/cloudflare-docs/pull/2783/files/5fdf026fd834625e30b98681fd0a9ddba36728e3#r756746851

2021-12-24 10:01 UTC, Juu33 commented on products/workers/src/content/learning/how-workers-works.md
> +[V8](https://v8.dev) orchestrates isolates: lightweight contexts that group variables with the code allowed to mutate them. You could even consider an isolate a sandbox for your function to run in.
https://github.com/cloudflare/cloudflare-docs/pull/2783/files/5fdf026fd834625e30b98681fd0a9ddba36728e3#r756746851

2021-12-24 10:01 UTC, Juu33 commented
> Lhttps://github.com/[/pull/2783](https://github.com/cloudflare/cloudflare-docs/pull/2783)/files/5fdf026fd834625e30b98681fd0a9ddba36728e3#r756746851