1.1.1.1: add operators page
cloudflare/cloudflare-docs pull request #2818
Opened 2021-11-30 16:11 UTC by elithrar

Summary:

* Adds a page for Network Operators using 1.1.1.1
* Re-orders the side-bar to accommodate

2021-11-30 16:11 UTC, elithrar commented
cc/ @marciocloudflare

2021-12-02 09:55 UTC, marciocloudflare requested changes

2021-12-02 09:55 UTC, marciocloudflare commented on products/1.1.1.1/src/content/network-operators.md
> +Network operators, including Internet Service Providers (ISPs), device manufacturers, public WiFi networks, municipal broadband providers, and security scanning services can use 1.1.1.1 and [1.1.1.1
```suggestion
Network operators, including Internet Service Providers (ISPs), device manufacturers, public WiFi networks, municipal broadband providers, and security scanning services can use [1.1.1.1](/setup-1.1.1.1) and [1.1.1.1 for Families](/1.1.1.1-for-families) in place of operating their own recursive DNS infrastructure.
```

2021-12-02 09:55 UTC, marciocloudflare commented on products/1.1.1.1/src/content/network-operators.md
> +The 1.1.1.1 resolver was designed with a privacy-first approach. Refer to our [data and privacy policies](https://developers.cloudflare.com/1.1.1.1/privacy/public-dns-resolver) for what is logged and
```suggestion
The 1.1.1.1 resolver was designed with a privacy-first approach. Refer to our [data and privacy policies](/privacy/public-dns-resolver) for what is logged and retained by 1.1.1.1.
```

2021-12-02 09:55 UTC, marciocloudflare commented on products/1.1.1.1/src/content/network-operators.md
> +* Having a DNS proxy on a edge router make requests to 1.1.1.1 on behalf of all connected devices
```suggestion
* Including a [DNS over HTTPS](/encrypted-dns/dns-over-https) or [DNS over TLS](/encrypted-dns/dns-over-tls) proxy on end-user routers or devices (best for privacy).
* Pushing 1.1.1.1 to devices via DHCP/PPP within an operator network (recommended; most practical).
* Having a DNS proxy on a edge router make requests to 1.1.1.1 on behalf of all connected devices.
```

2021-12-02 09:55 UTC, marciocloudflare commented on products/1.1.1.1/src/content/network-operators.md
> +You may wish to provide end-users options to change from the default 1.1.1.1 resolver to one of the [1.1.1.1 for Families](https://developers.cloudflare.com/1.1.1.1/1.1.1.1-for-families) endpoints.
```suggestion
You may wish to provide end-users options to change from the default 1.1.1.1 resolver to one of the [/1.1.1.1-for-families) endpoints.
```

2021-12-02 09:55 UTC, marciocloudflare commented on products/1.1.1.1/src/content/network-operators.md
> +If you're a network operator and still have outstanding questions, contact `resolver@cloudflare.com` with your use-case and we'll be happy to discuss further.
Do we really want to include this email address here?

2021-12-02 09:56 UTC, marciocloudflare commented
Hi @elithrar. Could you change the hyperlinks please? Thanks!

2021-12-13 17:14 UTC, marciocloudflare approved these changes

2021-12-13 17:14 UTC, merged

2021-12-13 17:19 UTC, elithrar commented
Thanks @marciocloudflare!

2021-12-13 17:22 UTC, marciocloudflare commented
Sure thing :)