Add Same-URL A/B Testing to Examples
cloudflare/cloudflare-docs pull request #2857
Opened 2021-12-06 18:19 UTC by helloimalastair

Resolves [transparent A/B on same URL?#2693](https://github.com/cloudflare/cloudflare-docs/issues/2693) issue.
This example supports the default A/B testing setup shown [here](https://developers.cloudflare.com/workers/examples/ab-testing), with one key difference. When the `/control` or `/test` paths are accessed directly, cookies are ignored, and the request is forwarded directly to the desired environment on the origin.

Please edit the title and summary as y'all see fit. I mostly just wrote them as a placeholder.

2021-12-10 15:59 UTC, signalnerve commented
Thanks! Can you update this to replace the existing A/B test example

2021-12-12 20:39 UTC, helloimalastair commented
> Thanks! Can you update this to replace the existing A/B test example

Done

2021-12-14 17:54 UTC, signalnerve requested changes

2021-12-14 17:54 UTC, signalnerve commented on products/workers/src/content/examples/ab-testing.md
> +    if(group === "control") url.pathname = "/control" + url.pathname;
can we do long-form if/else here with `{}`?

2021-12-14 17:54 UTC, signalnerve commented on products/workers/src/content/examples/ab-testing.md
> +  if (cookie && cookie.includes(`${NAME}=control`)) url.pathname = "/control" + url.pathname;
same question as below `if/else` `{}`

2021-12-14 17:54 UTC, signalnerve commented on products/workers/src/content/examples/ab-testing.md
> +  if(url.pathname.startsWith("/control") || url.pathname.startsWith("/test")) return fetch(req);
```suggestion
  if (url.pathname.startsWith("/control") || url.pathname.startsWith("/test")) return fetch(req);
```

2021-12-16 00:39 UTC, signalnerve approved these changes

2021-12-16 00:41 UTC, signalnerve commented
@jkup can you review this when you have time?

2021-12-16 00:44 UTC, WalshyDev requested changes

2021-12-16 00:44 UTC, WalshyDev commented on products/workers/src/content/examples/ab-testing.md
> +addEventListener('fetch', e => {
Double quotes, keep it consistent

2021-12-16 00:44 UTC, WalshyDev commented on products/workers/src/content/examples/ab-testing.md
> +    (cookie && cookie.includes(`${NAME}=test`)) url.pathname = "/test" + url.pathname;
Else if was broken here

2021-12-16 00:44 UTC, WalshyDev commented on products/workers/src/content/examples/ab-testing.md
> +async function ABTestingWithPassthrough(req) {
nitpick: function name not camelCase - may be fine for the docs though

2022-01-04 17:25 UTC, deadlypants1973 commented on products/workers/src/content/examples/ab-testing.md
> +# A/B Testing with Same-URL Direct Access
```suggestion
# A/B testing with same-URL direct access
```

2022-01-04 17:25 UTC, deadlypants1973 approved these changes

2022-01-04 18:16 UTC, jkup approved these changes
Looks good!

2022-01-05 09:34 UTC, merged