Stream: Clarify usage of `name` in the TUS upload metadata
cloudflare/cloudflare-docs pull request #286
Opened 2020-11-13 22:09 UTC by renandincer

2020-11-13 22:30 UTC, adamschwartz approved these changes

2020-11-16 15:50 UTC, Everlag requested changes

2020-11-16 15:50 UTC, Everlag commented on products/stream/src/content/uploading-videos/upload-video-file.md
> +- `name`
In dash, I see `filename c21hbGwubXA0` in `Upload-Metadata` when I upload a video; I think this is supposed to be `filename`?

2020-11-18 17:27 UTC, Everlag commented on products/stream/src/content/uploading-videos/upload-video-file.md
> +- `name`
Actually, while looking at unrelated work, I see `name` in `Upload-Metadata` as well. Uppy seems to send both and the UI picks to show `name`.

So, you're right here, some of the internal code I was looking at is wrong.

2020-11-24 19:19 UTC, adamschwartz commented
@renandincer Is this OK to merge?

2020-11-24 19:22 UTC, merged