Correct X-Forwarded-For example
cloudflare/cloudflare-docs pull request #2956
Opened 2021-12-15 02:07 UTC by ad8-bdl

X-Forwarded-For example currently incorrectly shows the proxy addresses being prepended; they are appended.

2021-12-15 02:15 UTC, ad8-bdl commented
FTR: I haven't validated Cf's behaviour with `X-Forwarded-For` - I trust it correctly _appends_ proxy addresses, leaving the client IP at the beginning of the list. Ref. https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For

Then I found this: https://community.cloudflare.com/t/x-forwarded-for-documentaiton-seems-wrong/221504

2022-01-04 10:31 UTC, abracchi-tw approved these changes

2022-01-04 17:21 UTC, kodster28 requested changes
Actually, we need to verify this example internally

2022-01-05 14:50 UTC, kodster28 approved these changes

2022-01-05 14:50 UTC, merged

2022-01-05 14:50 UTC, kodster28 commented
Thanks for the correction, @ad8-bdl