docs: update QR Code Generator tutorial
cloudflare/cloudflare-docs pull request #296
Opened 2020-11-16 22:29 UTC by arthurdenner

Hi! 👋🏽 

I followed the "Build a QR code generator" tutorial today and liked it very much!

While going through it, I thought about simplifying and organizing it a bit, trying to make it more beginner-friendly by:

- Returning `Response`s directly;
- Adding a missing `headers` variable and highlighting it;
- Adding a note about `type="webpack"` - I know it's in the "Getting Started" section but one may overlook that and get confused with the `require is not defined` error;
- Standardizing the code examples, e.g. always destructing `text` from `await request.json`;

PS: I didn't create an issue for this as it's a proposal for improving the docs as feedback from a first-time user. Let me know if you want me to follow the contributing guidelines and create an issue 👍🏽

2020-11-17 16:18 UTC, signalnerve requested changes
thank you SO much for doing this! just a quick fix to make and then we're 👍  to merge. amazing!!

2020-11-17 16:18 UTC, signalnerve commented on products/workers/src/content/tutorials/build-a-qr-code-generator/index.md
> +**Note:** You must set `type = "webpack"` in your `wrangler.toml` in order for Wrangler to use webpack to bundle your worker scripts. No other types will build your script with webpack.
Can we remove this `Aside` and instead add these instructions in the Publish section? We should be able to show a code snippet with `wrangler.toml` and highlight the change

2020-11-17 19:24 UTC, arthurdenner commented on products/workers/src/content/tutorials/build-a-qr-code-generator/index.md
> +**Note:** You must set `type = "webpack"` in your `wrangler.toml` in order for Wrangler to use webpack to bundle your worker scripts. No other types will build your script with webpack.
I'm glad the changes are helpful, Kristian! I added the `Aside` in this section because without it one can't proceed following the tutorial (and eventually get to the Publish section) if doing step-by-step.

Would be helpful if we show a diff of the `wrangler.toml` in this section as well? Maybe turn the note into a paragraph? What do you think?

2020-11-17 20:04 UTC, signalnerve commented on products/workers/src/content/tutorials/build-a-qr-code-generator/index.md
> +**Note:** You must set `type = "webpack"` in your `wrangler.toml` in order for Wrangler to use webpack to bundle your worker scripts. No other types will build your script with webpack.
oh, right! that makes sense. yes, let's go ahead with putting it here 👍

2020-11-17 20:18 UTC, arthurdenner commented on products/workers/src/content/tutorials/build-a-qr-code-generator/index.md
> +**Note:** You must set `type = "webpack"` in your `wrangler.toml` in order for Wrangler to use webpack to bundle your worker scripts. No other types will build your script with webpack.
Sorry, but I didn't get if you'd like me to extend the note and show the diff of `wrangler.toml` or leave as it is?

2020-11-18 15:00 UTC, signalnerve commented on products/workers/src/content/tutorials/build-a-qr-code-generator/index.md
> +**Note:** You must set `type = "webpack"` in your `wrangler.toml` in order for Wrangler to use webpack to bundle your worker scripts. No other types will build your script with webpack.
yes, please feel free to extend the note and show the diff!

2020-11-19 19:15 UTC, arthurdenner commented on products/workers/src/content/tutorials/build-a-qr-code-generator/index.md
> +**Note:** You must set `type = "webpack"` in your `wrangler.toml` in order for Wrangler to use webpack to bundle your worker scripts. No other types will build your script with webpack.
I've extended the note to show the diff. I based the content on the [Getting Started 6d](http://localhost:4000/learning/getting-started#6d-configuring-your-project) section.

2020-11-24 19:22 UTC, adamschwartz commented
@signalnerve @arthurdenner is this good to go now?

2021-01-06 07:11 UTC, arthurdenner commented
@signalnerve - is this good to go now?

2021-01-24 09:40 UTC, arthurdenner commented
@adamschwartz and @signalnerve ping.

2021-02-25 17:03 UTC, merged

2021-02-25 17:04 UTC, signalnerve commented
thanks so much, sorry for the delay!