Add clarification on Logpush Sumo Logic integration
cloudflare/cloudflare-docs pull request #2971
Opened 2021-12-16 09:42 UTC by angelampcosta

2021-12-16 11:21 UTC, deadlypants1973 approved these changes

2021-12-16 22:41 UTC, tanushreesharma-cf commented
Hey Anglea. The description you're adding should mention that the same collector can be used - 

"Note that the same collector can be used for multiple Logpush jobs, but each job must have a dedicated source address."

2021-12-17 00:09 UTC, soheiokamoto approved these changes

2021-12-17 00:22 UTC, tanushreesharma-cf requested changes
See my comment above!

2021-12-17 15:16 UTC, tanushreesharma-cf approved these changes

2021-12-17 15:17 UTC, merged