Fix typo
cloudflare/cloudflare-docs pull request #298
Opened 2020-11-17 03:22 UTC by delroh

This or maybe "retrieve and put data in the cloudflare cache" ? not sure.

2020-11-17 16:20 UTC, signalnerve requested changes
thanks for removing that extra word, little suggestion for a diff part of the paragraph

2020-11-17 16:20 UTC, signalnerve commented on products/workers/src/content/learning/getting-started.md
> +The example outlined in this guide is just a starting point. There are many Workers [runtime APIs](/runtime-apis) available to manipulate requests and generate responses. For example, you can use [HT
```suggestion
The example outlined in this guide is just a starting point. There are many Workers [runtime APIs](/runtime-apis) available to manipulate requests and generate responses. For example, you can use [HTMLRewriter](/runtime-apis/html-rewriter) to parse and transform HTML on the fly, use the [Cache API](/runtime-apis/cache) to retrieve data from and put data into [the Cloudflare cache](/learning/how-the-cache-works), compute a custom response right from the edge, redirect the request to another service, and so much more.
```

2020-11-18 00:25 UTC, delroh commented on products/workers/src/content/learning/getting-started.md
> +The example outlined in this guide is just a starting point. There are many Workers [runtime APIs](/runtime-apis) available to manipulate requests and generate responses. For example, you can use [HT
Great, will do! Should "API" also be added to HTMLRewriter? Initially I added "API" to Cache but then removed it because I was not sure if it was intentionally omitted in HTMLRewriter, given that it is talking about available runtime APIs and therefor all subsequently mentioned are APIs. Got a little tangled there on should add or not so just followed the omitting like on HMLTRewriter.

2020-11-18 14:59 UTC, signalnerve commented on products/workers/src/content/learning/getting-started.md
> +The example outlined in this guide is just a starting point. There are many Workers [runtime APIs](/runtime-apis) available to manipulate requests and generate responses. For example, you can use [HT
oh good question - sure, let's go with "use the HTMLRewriter API". thanks!!

2020-11-29 03:50 UTC, delroh commented on products/workers/src/content/learning/getting-started.md
> +The example outlined in this guide is just a starting point. There are many Workers [runtime APIs](/runtime-apis) available to manipulate requests and generate responses. For example, you can use [HT
Almost forgot about this. Added the suggested changes. 😁

2020-12-09 21:38 UTC, adamschwartz approved these changes

2020-12-09 21:39 UTC, merged