[Magic Firewall] Added About and updated landing page
cloudflare/cloudflare-docs pull request #2980
Opened 2021-12-16 22:18 UTC by dcpena

Added an About section and updated the information on the landing page about Magic Firewall. Addresses [PCX-2941](https://jira.cfops.it/browse/PCX-2941).

2021-12-16 22:29 UTC, arges requested changes

2021-12-16 22:29 UTC, arges commented on products/magic-firewall/src/content/about/analytics.md
> +Use the GraphQL Analytics API to view data for requests passing through Cloudflare's network. For more information about using the GraphQL Analytics API and getting started, refer to [GraphQL Analyti
This could link here: https://developers.cloudflare.com/analytics/graphql-api/tutorials/querying-magic-firewall-samples

2021-12-16 22:29 UTC, arges commented on products/magic-firewall/src/content/about/analytics.md
> +# Magic Firewall Analytics
I would suggest removing this section for now, currently Network Analytics shows more about DDoS protections than Magic Firewall analytics.

2021-12-16 22:29 UTC, arges commented on products/magic-firewall/src/content/index.md
> +Additionally, Magic Transit users can view how many packets were mitigated from attacks through **Network Analytics**.
I'd remove this sentence.

2021-12-16 22:39 UTC, dcpena commented on products/magic-firewall/src/content/about/analytics.md
> +# Magic Firewall Analytics
Done

2021-12-16 22:40 UTC, dcpena commented on products/magic-firewall/src/content/about/analytics.md
> +Use the GraphQL Analytics API to view data for requests passing through Cloudflare's network. For more information about using the GraphQL Analytics API and getting started, refer to [GraphQL Analyti
Thanks for the link. Updated

2021-12-16 22:40 UTC, dcpena commented on products/magic-firewall/src/content/index.md
> +Additionally, Magic Transit users can view how many packets were mitigated from attacks through **Network Analytics**.
Done

2021-12-16 23:39 UTC, arges approved these changes

2021-12-17 09:58 UTC, pedrosousa approved these changes

2021-12-17 09:58 UTC, pedrosousa commented on products/magic-firewall/src/content/index.md
> +Magic Firewall is a firewall-as-a-service (FWaaS) delivered from the Cloudflare global network to protect office networks and cloud infrastructure with advanced, scalable protection. With Magic Firew
Regarding this part of the sentence:
```
you can apply policies that filter rules
```
While we use "rule filters" to filter traffic, I'm not sure if we "filter rules"... We essentially "filter [unwanted] traffic", as you also say later in the sentence.

2021-12-17 09:58 UTC, pedrosousa commented on products/magic-firewall/src/content/about/traffic-types.md
> +Magic Firewall supports layers three and four — network and transport — protocols including TCP, UDP, and ICMP for example. Any type of layer three or four protocols can go through Magic Firewall and
```suggestion
Magic Firewall supports layers three and four — network and transport — protocols such as TCP, UDP, and ICMP. Any type of layer three or four protocols can go through Magic Firewall and then be matched on those protocols.
```

2021-12-17 09:58 UTC, pedrosousa commented on products/magic-firewall/src/content/about/traffic-types.md
> +To view the list of fields, refer to [Magic Firewall fields](/reference/magic-firewall-fields).
```suggestion
To view the list of available fields, refer to [Magic Firewall fields](/reference/magic-firewall-fields).
```

2021-12-17 09:58 UTC, pedrosousa commented on products/magic-firewall/src/content/about/analytics.md
> +---
I would add explicit `order: ` fields (and values) to these topics, just to make sure they stay where they are if we eventually rename them.

2021-12-17 09:58 UTC, pedrosousa commented on products/magic-firewall/src/content/about/list-types.md
> +Cloudflare sees approximately 28 million HTTP requests each second and blocks 76 billion cyber threats each day. Cloudflare uses that data to detect malicious actors on the Internet and turns that in
```suggestion
Cloudflare sees approximately 28 million HTTP requests each second and blocks 76 billion cyber threats each day. Cloudflare uses that data to detect malicious actors on the Internet and turns that information into a list of known malicious IP addresses. Cloudflare also integrates with a number of third-party vendors to augment the coverage.
```

2021-12-17 09:58 UTC, pedrosousa commented on products/magic-firewall/src/content/about/list-types.md
> +The threat intelligence feed categories include Malware, Anonymizer, and Botnet Command-and-Control centers. Malware and Botnet lists cover properties on the Internet distributing malware and known c
```suggestion
The threat intelligence feed categories include Malware, Anonymizer, and Botnet Command-and-Control centers. Malware and Botnet lists cover properties on the Internet distributing malware and known command-and-control centers. Anonymizers contain a list of known forward proxies that allow attackers to hide their IP addresses.
```

2021-12-17 09:58 UTC, pedrosousa commented on products/magic-firewall/src/content/about/list-types.md
> +IP lists can be used to easily group services in networks, like webservers, or for lists of known bad IPs to make managing good network endpoints easier. IP lists are helpful for users with very expa
```suggestion
IP lists can be used to easily group services in networks, like web servers, or for lists of known bad IP addresses to make managing good network endpoints easier. IP lists are helpful for users with very expansive Firewall Rules with many IP lists. You can add up to 100,000 IPs per list.
```
FYI: I believe I capitalized "IP Lists" in the Firewall Rules docs, but we can agree on not doing so. :)

2021-12-17 16:15 UTC, dcpena commented on products/magic-firewall/src/content/about/analytics.md
> +---
Done

2021-12-17 16:15 UTC, dcpena commented on products/magic-firewall/src/content/about/list-types.md
> +IP lists can be used to easily group services in networks, like webservers, or for lists of known bad IPs to make managing good network endpoints easier. IP lists are helpful for users with very expa
Fixed!

2021-12-17 16:15 UTC, dcpena commented on products/magic-firewall/src/content/index.md
> +Magic Firewall is a firewall-as-a-service (FWaaS) delivered from the Cloudflare global network to protect office networks and cloud infrastructure with advanced, scalable protection. With Magic Firew
Also fixed this as well

2021-12-17 16:15 UTC, merged