Add remix framework to framework guide
cloudflare/cloudflare-docs pull request #3002
Opened 2021-12-22 14:53 UTC by Ekwuno

2022-01-03 13:56 UTC, deadlypants1973 requested changes

2022-01-03 13:56 UTC, deadlypants1973 commented on products/pages/src/content/framework-guides/remix.md
> +Start by installing the latest version of Remix. Create a new project directory and then intialize a Remix project by running:
```suggestion
## Setting up a new project

Start by installing the latest version of Remix. Create a new project directory and then intialize a Remix project by running:
```

2022-01-03 13:56 UTC, deadlypants1973 commented on products/pages/src/content/framework-guides/remix.md
> +
```suggestion
$ npx create-remix@latest
```

2022-01-03 13:56 UTC, deadlypants1973 commented on products/pages/src/content/framework-guides/remix.md
> +By selecting Cloudfalre Pages as your deploy option your folder will have a `functions/[[path]].ts` file. This is the functions integration where we serve your Remix application on all paths of your
```suggestion
By selecting Cloudflare Pages as your deploy option, your folder will have a `functions/[[path]].ts` file. This is the functions integration where we serve your Remix application on all paths of your website. After this change directory to your project and see your project by running the following command: 
```

1) Can this part be more clear? How does the user select CF Pages? Is there a menu? Or do they type it in?
2) What is the 'functions integration'? The file? Is this saying that CF Pages will use the `functions/[[path]].ts` file to serve the Remix application.
3) Last sentence needs some revision. "After this" -> define "this". Seems to be some word missing the makes the sentence incomplete.

2022-01-04 12:24 UTC, deadlypants1973 commented on products/pages/src/content/framework-guides/remix.md
> +After running the above command, you will be prompted in the CLI to name your project and select your deploy method. This guide uses Cloudflare Pages.
```suggestion
After running the above command, you will be prompted to name your project in your terminal and select your deploy method. This guide uses Cloudflare Pages. 
```

2022-01-04 12:24 UTC, deadlypants1973 commented on products/pages/src/content/framework-guides/remix.md
> +By selecting Cloudflare Pages as your deploy option in the CLI drop down, your folder will have a `functions/[[path]].ts` file. This is the functions integration where we serve your Remix application
```suggestion
By selecting *Cloudflare Pages* as your deployment option in the terminal drop-down menu, your folder will have a `functions/[[path]].ts` file. This file is the functions integration where Cloudflare serves your Remix application on all function paths of your website. After selecting your deployment option, change the directory to your project and render your project by running the following command: 
```

2022-01-04 19:26 UTC, lukeed commented on products/pages/src/content/framework-guides/remix.md
> +By selecting *Cloudflare Pages* as your deployment option in the terminal drop-down menu, your folder will have a `functions/[[path]].ts` file. This file is the functions integration where Cloudflare
```suggestion
By selecting *Cloudflare Pages* as your deployment option in the terminal drop-down menu, your folder will have a `functions/[[path]].ts` file. The `[[path]]` filename indicates that this file will handle requests to all incoming URLs; refer to [Path segments](https://developers.cloudflare.com/pages/platform/functions#path-segments) to learn more.  

After selecting your deployment option, change the directory to your project and render your project by running the following command: 
```

2022-01-07 14:55 UTC, deadlypants1973 approved these changes

2022-01-07 16:00 UTC, merged