Update collect-pcaps.md
cloudflare/cloudflare-docs pull request #3078
Opened 2022-01-06 13:16 UTC by zeinjaber

filter_v1 uses a wirefilter expression to filter the pcap.

2022-01-06 16:37 UTC, pedrosousa commented on products/magic-firewall/src/content/how-to/collect-pcaps.md
> +`filter_v1` uses Wirefilter expressions to filter the PCAP. This field can be left empty to collect all packets without any filtering.
```suggestion
Field values in the `filter_v1` object use Wirefilter expressions to filter the PCAP. Leaving this object empty will collect all packets without any filtering. 
```
There are several fields inside the `filter_v1` object, so I tried to make it more clear. However, there are still a couple of questions:
- Can you enter a Wirefilter expression for each field value (`source_address`, `source_port`, etc.), or will the different field values be combined to form a single Wirefilter expression?
- Do you need to add the object without any fields when you don't want to perform any filtering (e.g., `"filter_v1": {}`), or can you omit it?

Also, avoided passive voice in the second sentence.

2022-01-06 16:41 UTC, dcpena commented on products/magic-firewall/src/content/how-to/collect-pcaps.md
> +`filter_v1` uses Wirefilter expressions to filter the PCAP. This field can be left empty to collect all packets without any filtering.
@arges and @zeinjaber, would you all be able to provide a little more insight to the questions Pedro posed? thanks so much!

2022-02-01 18:14 UTC, arges requested changes

2022-02-01 18:14 UTC, arges commented on products/magic-firewall/src/content/how-to/collect-pcaps.md
> +`filter_v1` uses Wirefilter expressions to filter the PCAP. This field can be left empty to collect all packets without any filtering.
As it is written does not seem correct. We do not support generic wirefilter expressions in `filter_v1`.

2022-02-01 18:37 UTC, tejaswi-cf commented on products/magic-firewall/src/content/how-to/collect-pcaps.md
> +`filter_v1` uses Wirefilter expressions to filter the PCAP. This field can be left empty to collect all packets without any filtering.
Hey @pedrosousa,

> Can you enter a Wirefilter expression for each field value (source_address, source_port, etc.), or will the different field values be combined to form a single Wirefilter expression?

Each field value is a single address/port/protocol. It cannot be set to a wirefilter expression, it has to be a single value. We don't want to expose how these values will internally be used to filter traffic.

> Do you need to add the object without any fields when you don't want to perform any filtering (e.g., "filter_v1": {}), or can you omit it?

Either way is fine. In both these cases traffic will not be filtered. The existing sentence about `filter_v1` looks correct.

2022-02-01 18:48 UTC, pedrosousa commented on products/magic-firewall/src/content/how-to/collect-pcaps.md
> +`filter_v1` uses Wirefilter expressions to filter the PCAP. This field can be left empty to collect all packets without any filtering.
As discussed with @tejaswi-cf, I'll remove the "Wirefilter expression" reference (since it doesn't apply here) and just fix the passive voice in a separate commit.

2022-02-01 19:46 UTC, tejaswi-cf approved these changes
Looks good. Thanks Pedro!

2022-07-20 17:53 UTC, KimJ15 commented
This PR was opened before the developer doc site was moved to Cloudflare Pages. There are many conflicting branches. I'm going to close it now, but feel free to open a new issue or ask any questions.

2022-07-20 17:53 UTC, closed without merging