Namecheap no longer provides the "approve" url
cloudflare/cloudflare-docs pull request #308
Opened 2020-11-17 22:19 UTC by barthazar01

Instead of the "approve"/"expedite" url as described by the prior version of the paragraph Namecheap now includes a URL for cancellation only.

2020-11-24 19:18 UTC, adamschwartz commented
@TownLake any reason not to merge this?

2020-11-24 20:27 UTC, TownLake requested changes

2020-11-24 20:27 UTC, TownLake commented on products/registrar/src/content/transfer-instructions/namecheap.md
> +Unfortunately, the email confirmation which Namecheap sends as of Nov, 2020 contains a link to _cancel_ rather than _expedite_ or _approve_ the transfer. No alternative funtionality exists in the dom
Just a note on our documentation style guide - can you remove the adverb "Unfortunately".

2020-12-05 01:13 UTC, hui37210 approved these changes

2021-02-24 13:19 UTC, barthon-b commented on products/registrar/src/content/transfer-instructions/namecheap.md
> +Unfortunately, the email confirmation which Namecheap sends as of Nov, 2020 contains a link to _cancel_ rather than _expedite_ or _approve_ the transfer. No alternative funtionality exists in the dom
It's done, thanks for the feedback!

2021-04-07 18:51 UTC, KimJ15 commented
Commit addressed by PR referenced above.

2021-04-07 18:51 UTC, closed without merging