[Pages] Adding tutorials for HTML and React forms with Formspree
cloudflare/cloudflare-docs pull request #3090
Opened 2022-01-07 06:47 UTC by colevscode

* Added `Adding a React form with Formspree`
* Added `Adding an HTML form with Formspree`

2022-01-07 18:23 UTC, deadlypants1973 requested changes
Style guide review

2022-01-07 18:23 UTC, deadlypants1973 commented on products/pages/src/content/tutorials/add-a-react-form-with-formspree/index.md
> +Almost every React website needs a form to collect user data. [Formspree](https://formspree.io/) is a backend service that handles form processing and storage, allowing developers to include forms on
```suggestion
Almost every React website needs a form to collect user data. [Formspree](https://formspree.io/) is a back-end service that handles form processing and storage, allowing developers to include forms on their website without writing server-side code or functions.
```

2022-01-07 18:23 UTC, deadlypants1973 commented on products/pages/src/content/tutorials/add-a-react-form-with-formspree/index.md
> +In this tutorial, you will create a `<form>` component using React and add it to a “single page app” built with `create-react-app`. Though we’re using CRA, the concepts will apply to any React framew
```suggestion
In this tutorial, you will create a `<form>` component using React and add it to a single page application built with `create-react-app`. Though you are using `create-react-app` (CRA), the concepts will apply to any React framework including Next.js, Gatsby, and more. You will use Formspree to collect the submitted data and send out email notifications when new submissions arrive, without requiring any server-side coding.
```

2022-01-07 18:23 UTC, deadlypants1973 commented on products/pages/src/content/tutorials/add-a-react-form-with-formspree/index.md
> +We’ll deploy our site to Cloudflare Pages. Refer to the [Get started guide](/get-started) guide to familiarize yourself with the platform.
```suggestion
You will deploy your site to Cloudflare Pages. Refer to the [Get started guide](/get-started) guide to familiarize yourself with the platform. 
```

2022-01-07 18:23 UTC, deadlypants1973 commented on products/pages/src/content/tutorials/add-a-react-form-with-formspree/index.md
> +You may now begin modifying the React app in the `new-app` directory you created.
```suggestion
You may now modify the React application in the `new-app` directory you created.
```

2022-01-07 18:23 UTC, deadlypants1973 commented on products/pages/src/content/tutorials/add-a-react-form-with-formspree/index.md
> +## The Front-end Code
```suggestion
## The front-end code
```

2022-01-07 18:23 UTC, deadlypants1973 commented on products/pages/src/content/tutorials/add-a-react-form-with-formspree/index.md
> +The starting point for `create-react-app` includes a simple “hello world” website. You’ll be adding a “contact us” form that accepts a name, email address and message. The form code is adapted from t
```suggestion
The starting point for `create-react-app` includes a simple Hello World website. You will be adding a Contact Us form that accepts a name, email address, and message. The form code is adapted from the HTML Forms tutorial. For a more in-depth explanation of how HTML forms work and additional learning resources, refer to the [HTML Forms tutorial](/tutorials/forms).
```

2022-01-07 18:23 UTC, deadlypants1973 commented on products/pages/src/content/tutorials/add-a-react-form-with-formspree/index.md
> +First create a new react component called `ContactForm.js` and place it in the `src` folder alongside `App.js`.
```suggestion
First, create a new react component called `ContactForm.js` and place it in the `src` folder alongside `App.js`.
```

2022-01-07 18:23 UTC, deadlypants1973 commented on products/pages/src/content/tutorials/add-a-react-form-with-formspree/index.md
> +Next we’ll build the form component using a helper library from Formspree, [`@formspree/react`](https://github.com/formspree/formspree-react). This library contains a `useForm` hook to simplify the p
```suggestion
Next, you will build the form component using a helper library from Formspree, [`@formspree/react`](https://github.com/formspree/formspree-react). This library contains a `useForm` hook to simplify the process of handling form submission events and managing form state. 
```

2022-01-07 18:23 UTC, deadlypants1973 commented on products/pages/src/content/tutorials/add-a-react-form-with-formspree/index.md
> +- For the sake of clarity, this form doesn’t include any styling, but in the github project (**[https://github.com/formspree/formspree-example-cloudflare-react](https://github.com/formspree/formspree
```suggestion
- Currently, the form contains a placeholder `YOUR_FORM_ID`. You replace this with your own form endpoint later in this tutorial.
- The `useForm` hook returns a `state` object and a `handleSubmit` function which you pass to the `onSubmit` form attribute. Combined, these provide a way to submit the form data via AJAX and update form state depending on the response received.
- `ValidationError` components are helpers that display error messages for field errors, or general form errors (if no `field` attribute is provided).
- For clarity, this form does not include any styling, but in the GitHub project ([https://github.com/formspree/formspree-example-cloudflare-react](https://github.com/formspree/formspree-example-cloudflare-react)) you can review an example of how to apply styles to the form.
```
Because the first point mentions a present state and step relevant to the tutorial, this should be moved out of the aside, along with the second point. The third point (For clarity...) would be the best standalone point to leave in this aside.

2022-01-07 18:23 UTC, deadlypants1973 commented on products/pages/src/content/tutorials/add-a-react-form-with-formspree/index.md
> +To add this form to your website, first import the component like so:
```suggestion
To add this form to your website, import the component:
```

2022-01-07 18:23 UTC, deadlypants1973 commented on products/pages/src/content/tutorials/add-a-react-form-with-formspree/index.md
> +For example, you can update your `src/App.js` file to add the form like this:
```suggestion
For example, you can update your `src/App.js` file to add the form:
```

2022-01-07 18:23 UTC, deadlypants1973 commented on products/pages/src/content/tutorials/add-a-react-form-with-formspree/index.md
> +Now you have an single page app containing a "Contact-Us" form with a few fields for the user to fill out. However you haven't set up the form to submit to a valid form endpoint yet. You'll do that i
```suggestion
Now you have a single-page application containing a Contact Us form with several fields for the user to fill out. However, you have not set up the form to submit to a valid form endpoint yet. You will do that in the next section.
```

2022-01-07 18:23 UTC, deadlypants1973 commented on products/pages/src/content/tutorials/add-a-react-form-with-formspree/index.md
> +<Aside type="info" header="GitHub Repository">
```suggestion
<Aside type="info" header="GitHub repository">
```

2022-01-07 18:23 UTC, deadlypants1973 commented on products/pages/src/content/tutorials/add-a-react-form-with-formspree/index.md
> +The React form is complete, however, when the user submits this form, you’ll get a “Form not found” error. To fix that, create a new Formspree form, and copy its unique ID into the form's `useForm` i
```suggestion
The React form is complete, however, when the user submits this form, they will get a `Form not found` error. To fix this, create a new Formspree form, and copy its unique ID into the form's `useForm` invocation.
```

2022-01-07 18:23 UTC, deadlypants1973 commented on products/pages/src/content/tutorials/add-a-react-form-with-formspree/index.md
> +To create a Formspree form, first [sign up for an account on Formspree](https://formspree.io/register). Then create a new form with the `+ New form` button, call it "Contact-us form" and update the r
```suggestion
To create a Formspree form, sign up for [an account on Formspree](https://formspree.io/register). Then create a new form with the **+ New form** button. Name your new form `Contact-us form` and update the recipient email to an email where you wish to receive your form submissions. Finally, select **Create Form**.
```

2022-01-07 18:23 UTC, deadlypants1973 commented on products/pages/src/content/tutorials/add-a-react-form-with-formspree/index.md
> +You’ll then be presented with instructions on how to integrate your new form. Copy the form’s `hashid` (the last 6 alphanumeric characters from the URL) and paste it into the `useForm` function in th
```suggestion
You will be presented with instructions on how to integrate your new form. Copy the form’s `hashid` (the last 6 alphanumeric characters from the URL) and paste it into the `useForm` function in the ContactForm component you created above.
```

2022-01-07 18:23 UTC, deadlypants1973 commented on products/pages/src/content/tutorials/add-a-react-form-with-formspree/index.md
> +In this tutorial, you built and deployed a website using Cloudflare Pages and Formspree to handle form submissions. You created a React app with a form that communicates with Formspree to process and
```suggestion
In this tutorial, you built and deployed a website using Cloudflare Pages and Formspree to handle form submissions. You created a React application with a form that communicates with Formspree to process and store submission requests and send notifications.
```

2022-01-07 18:23 UTC, deadlypants1973 commented on products/pages/src/content/tutorials/add-a-react-form-with-formspree/index.md
> +For more help setting up Formspree you can check out the following resources:
```suggestion
For more help setting up Formspree, refer to the following resources:
```

2022-01-07 18:23 UTC, deadlypants1973 commented on products/pages/src/content/tutorials/add-a-react-form-with-formspree/index.md
> +- For general help with formspree check out the [Formspree help site](https://help.formspree.io/hc/en-us)
```suggestion
- For general help with Formspree, refer to the [Formspree help site](https://help.formspree.io/hc/en-us).
```

2022-01-07 18:23 UTC, deadlypants1973 commented on products/pages/src/content/tutorials/add-a-react-form-with-formspree/index.md
> +- For more help creating forms in React, see the [formspree-react docs](https://help.formspree.io/hc/en-us/articles/360055613373-The-Formspree-React-library)
```suggestion
- For more help creating forms in React, refer to the [formspree-react documentation](https://help.formspree.io/hc/en-us/articles/360055613373-The-Formspree-React-library)
```

2022-01-07 18:23 UTC, deadlypants1973 commented on products/pages/src/content/tutorials/add-a-react-form-with-formspree/index.md
> +- For tips on integrating Formspree with popular platforms like Next.js, Gatsby and Eleventy, check out the [Formspree guides](https://formspree.io/guides).
```suggestion
- For tips on integrating Formspree with popular platforms like Next.js, Gatsby and Eleventy, refer to the [Formspree guides](https://formspree.io/guides).
```

2022-01-07 18:23 UTC, deadlypants1973 commented on products/pages/src/content/tutorials/add-a-react-form-with-formspree/index.md
> +After clicking the **Save and Deploy** button, your Pages project will begin its first deployment. When successful, you will be presented with a unique `*.pages.dev` subdomain and a link to your live
```suggestion
After selecting **Save and Deploy**, your Pages project will begin its first deployment. When successful, you will be presented with a unique `*.pages.dev` subdomain and a link to your live demo.
```

2022-01-07 18:23 UTC, deadlypants1973 commented on products/pages/src/content/tutorials/add-an-html-form-with-formspree/index.md
> +Almost every website, whether it's a simple HTML portfolio page, or a complex javascript application, will need a form to collect user data. [Formspree](https://formspree.io) is a backend service tha
```suggestion
Almost every website, whether it is a simple HTML portfolio page or a complex JavaScript application, will need a form to collect user data. [Formspree](https://formspree.io) is a back-end service that handles form processing and storage, allowing developers to include forms on their website without writing server-side code or functions.
```

2022-01-07 18:23 UTC, deadlypants1973 commented on products/pages/src/content/tutorials/add-an-html-form-with-formspree/index.md
> +In this tutorial, you will create a `<form>` using plain HTML and CSS and add it to a static HTML website hosted on Cloudflare Pages. Refer to the [Get started guide](/get-started) guide to familiari
```suggestion
In this tutorial, you will create a `<form>` using plain HTML and CSS and add it to a static HTML website hosted on Cloudflare Pages. Refer to the [Get started guide](/get-started) guide to familiarize yourself with the platform. You will use Formspree to collect the submitted data and send out email notifications when new submissions arrive, without requiring any JavaScript or back-end coding.
```

2022-01-07 18:23 UTC, deadlypants1973 commented on products/pages/src/content/tutorials/add-an-html-form-with-formspree/index.md
> +### The Website Markup
```suggestion
### The website markup
```

2022-01-07 18:23 UTC, deadlypants1973 commented on products/pages/src/content/tutorials/add-an-html-form-with-formspree/index.md
> +You will only be using plain HTML for this example project. The home page will include a simple "Contact Us" form that accepts a name, email address and message.
```suggestion
You will only be using plain HTML for this example project. The home page will include a Contact Us form that accepts a name, email address, and message. 
```

2022-01-07 18:23 UTC, deadlypants1973 commented on products/pages/src/content/tutorials/add-an-html-form-with-formspree/index.md
> +The form code is adapted from the [HTML Forms tutorial](/tutorials/forms). For a more in-depth explanation of how HTML forms work, and additional learning resources, please refer to that tutorial.
```suggestion
The form code is adapted from the HTML Forms tutorial. For a more in-depth explanation of how HTML forms work and additional learning resources, refer to the [HTML Forms tutorial](/tutorials/forms).
```

2022-01-07 18:23 UTC, deadlypants1973 commented on products/pages/src/content/tutorials/add-an-html-form-with-formspree/index.md
> +Here's the form code:
```suggestion
The form code:
```

2022-01-07 18:23 UTC, deadlypants1973 commented on products/pages/src/content/tutorials/add-an-html-form-with-formspree/index.md
> +</Aside>
```suggestion
The `action` attribute determines where the form data is sent. You will update this later to send form data to Formspree. All `<input>` tags must have a unique `name` in order to capture the user's data. The `for` and `id` values must match in order to link the `<label>` with the corresponding `<input>` for accessibility tools like screen readers.

<Aside type="note">

Refer to the [HTML Forms tutorial](/tutorials/forms#Overview) on how to build an HTML form.

</Aside>

```

2022-01-07 18:23 UTC, deadlypants1973 commented on products/pages/src/content/tutorials/add-an-html-form-with-formspree/index.md
> +To add this form to your website, first create a `public/index.html` in your project directory. The `public` directory should contain all front-end assets, and this `index.html` file will serve as th
```suggestion
To add this form to your website, first, create a `public/index.html` in your project directory. The `public` directory should contain all front-end assets, and the `index.html` file will serve as the home page for the website.
```

2022-01-07 18:23 UTC, deadlypants1973 commented on products/pages/src/content/tutorials/add-an-html-form-with-formspree/index.md
> +Now you have an HTML document containing a "Contact-Us" form with a few fields for the user to fill out. However you haven't set the `action` attribute yet to a server that can handle the form data.
```suggestion
Now you have an HTML document containing a Contact-Us form with several fields for the user to fill out. However, you have not yet set the `action` attribute to a server that can handle the form data. You will do this in the next section of this tutorial.
```

2022-01-07 18:23 UTC, deadlypants1973 commented on products/pages/src/content/tutorials/add-an-html-form-with-formspree/index.md
> +### The Formspree Backend
```suggestion
### The Formspree back end
```

2022-01-07 18:23 UTC, deadlypants1973 commented on products/pages/src/content/tutorials/add-an-html-form-with-formspree/index.md
> +To create a Formspree form, first [sign up for an account on Formspree](https://formspree.io/register).
```suggestion
To create a Formspree form, sign up for [an account on Formspree](https://formspree.io/register).
```

2022-01-07 18:23 UTC, deadlypants1973 commented on products/pages/src/content/tutorials/add-an-html-form-with-formspree/index.md
> +Next, create a new form with the `+ New form` button, call it "Contact-us form" and update the recipient email to an email where you wish to receive your form submissions. Then click `Create Form`.
```suggestion
Next, create a new form with the **+ New form** button. Name it `Contact-us form` and update the recipient email to an email where you wish to receive your form submissions. Then select **Create Form**.
```

2022-01-07 18:23 UTC, deadlypants1973 commented on products/pages/src/content/tutorials/add-an-html-form-with-formspree/index.md
> +You’ll then be presented with instructions on how to integrate your new form.
```suggestion
You will then be presented with instructions on how to integrate your new form. 
```

2022-01-07 18:23 UTC, deadlypants1973 commented on products/pages/src/content/tutorials/add-an-html-form-with-formspree/index.md
> +For more help setting up Formspree you can check out the following resources:
```suggestion
For more help setting up Formspree, refer to the following resources:
```

2022-01-07 18:23 UTC, deadlypants1973 commented on products/pages/src/content/tutorials/add-an-html-form-with-formspree/index.md
> +- For tips on integrating Formspree with popular platforms like Next.js, Gatsby and Eleventy, check out the [Formspree guides](https://formspree.io/guides)
```suggestion
- For general help with Formspree, refer to the [Formspree help site](https://help.formspree.io/hc/en-us).
- For examples and inspiration for your own HTML forms, review the [Formspree form library](https://formspree.io/library).
- For tips on integrating Formspree with popular platforms like Next.js, Gatsby and Eleventy, refer to the [Formspree guides](https://formspree.io/guides).
```

2022-01-08 02:56 UTC, mrdadosone123 commented
www.googleadservices.com

2022-01-08 03:01 UTC, colevscode commented
^^^ phishing / spam ? I'm not clicking it.

2022-01-10 18:20 UTC, deadlypants1973 commented on products/pages/src/content/tutorials/add-an-html-form-with-formspree/index.md
> +Now you have an HTML document containing a Contact-Us form with several fields for the user to fill out. However, you have not yet set the `action` attribute to a server that can handle the form data
```suggestion
Now you have an HTML document containing a Contact Us form with several fields for the user to fill out. However, you have not yet set the `action` attribute to a server that can handle the form data. You will do this in the next section of this tutorial.
```

2022-01-10 18:20 UTC, deadlypants1973 commented on products/pages/src/content/tutorials/add-a-react-form-with-formspree/index.md
> +Now when you submit your form, you should be shown a thank-you message. The form data will be submitted to your account on Formspree.io.
```suggestion
Now when you submit your form, you should be shown a Thank You message. The form data will be submitted to your account on [Formspree.io](formspree.io).
```

2022-01-10 18:20 UTC, deadlypants1973 commented on products/pages/src/content/tutorials/add-a-react-form-with-formspree/index.md
> +You will be presented with instructions on how to integrate your new form. Copy the form’s `hashid` (the last 6 alphanumeric characters from the URL) and paste it into the `useForm` function in the C
```suggestion
You will be presented with instructions on how to integrate your new form. Copy the form’s `hashid` (the last 6 alphanumeric characters from the URL) and paste it into the `useForm` function in the `ContactForm` component you created above.
```

2022-01-10 18:20 UTC, deadlypants1973 commented on products/pages/src/content/tutorials/add-a-react-form-with-formspree/index.md
> +Then change the `useForm` hook in your ContactForm.js file so that it is initialized with an environment variable, rather than a string:
```suggestion
Then change the `useForm` hook in your `ContactForm.js` file so that it is initialized with an environment variable, rather than a string:
```

2022-01-10 18:20 UTC, deadlypants1973 commented on products/pages/src/content/tutorials/add-a-react-form-with-formspree/index.md
> +## The Formspree Backend
```suggestion
## The Formspree back end
```

2022-01-10 18:20 UTC, deadlypants1973 commented on products/pages/src/content/tutorials/add-a-react-form-with-formspree/index.md
> +To set up production and development forms first create a second form in Formspree. Name this form Contact Us Testing, and note the form's [hashid](https://help.formspree.io/hc/en-us/articles/3600151
```suggestion
To set up production and development forms first create a second form in Formspree. Name this form Contact Us Testing, and note the form's [`hashid`](https://help.formspree.io/hc/en-us/articles/360015130174-Getting-your-form-s-hashid-). 
```

2022-01-10 18:20 UTC, deadlypants1973 commented on products/pages/src/content/tutorials/add-a-react-form-with-formspree/index.md
> +In your Cloudflare Pages project settings, add the `REACT_APP_FORM_ID` environment variable to both the Production and Preview environments. Use your original form's hashid for Production, and the ne
```suggestion
In your Cloudflare Pages project settings, add the `REACT_APP_FORM_ID` environment variable to both the Production and Preview environments. Use your original form's `hashid` for Production, and the new test form's `hashid` for the Preview environment:
```

2022-01-10 18:20 UTC, deadlypants1973 commented on products/pages/src/content/tutorials/add-a-react-form-with-formspree/index.md
> +Create React App uses the prefix `REACT_APP_` to designate environment variables that are accessible to front end javascript code. A different framework will use a different prefix to expose environm
```suggestion
Create React App uses the prefix `REACT_APP_` to designate environment variables that are accessible to front-end JavaScript code. A different framework will use a different prefix to expose environment variables. For example, in the case of Next.js, the prefix is `NEXT_PUBLIC_`. Consult the documentation of your front-end framework to determine how to access environment variables from your React code.
```

2022-01-10 18:20 UTC, deadlypants1973 commented on products/pages/src/content/tutorials/add-an-html-form-with-formspree/index.md
> +Now when you submit your form, you should be redirected to a thank-you page. The form data will be submitted to your account on Formspree.io.
```suggestion
Now when you submit your form, you should be redirected to a Thank You page. The form data will be submitted to your account on [Formspree.io](formspree.io). 
```

2022-01-10 18:20 UTC, deadlypants1973 commented on products/pages/src/content/tutorials/add-an-html-form-with-formspree/index.md
> +From here you can adjust your form processing logic to change the [redirect page](https://help.formspree.io/hc/en-us/articles/360012378333--Thank-You-redirect), update the [notification email address
```suggestion
You can now adjust your form processing logic to change the [redirect page](https://help.formspree.io/hc/en-us/articles/360012378333--Thank-You-redirect), update the [notification email address](https://help.formspree.io/hc/en-us/articles/115008379348-Changing-a-form-email-address), or add plugins like [Google Sheets](https://help.formspree.io/hc/en-us/articles/360036563573-Use-Google-Sheets-to-send-your-submissions-to-a-spreadsheet), [Slack](https://help.formspree.io/hc/en-us/articles/360045648933-Send-Slack-notifications) and more.
```

2022-01-10 18:20 UTC, deadlypants1973 commented on products/pages/src/content/tutorials/add-an-html-form-with-formspree/index.md
> +If this is your first Cloudflare Pages project, refer to the [Get started guide](/get-started) for a complete walkthrough. After selecting the appropriate GitHub repository, you must configure your p
```suggestion
If this is your first Cloudflare Pages project, refer to [Get started](/get-started) for a complete setup guide. After selecting the appropriate GitHub repository, you must configure your project with the following build settings:
```

2022-01-10 18:20 UTC, deadlypants1973 commented on products/pages/src/content/tutorials/add-an-html-form-with-formspree/index.md
> +After clicking the **Save and Deploy** button, your Pages project will begin its first deployment. When successful, you will be presented with a unique `*.pages.dev` subdomain and a link to your live
```suggestion
After selecting **Save and Deploy**, your Pages project will begin its first deployment. When successful, you will be presented with a unique `*.pages.dev` subdomain and a link to your live demo.
```

2022-01-10 18:20 UTC, deadlypants1973 commented on products/pages/src/content/tutorials/add-a-react-form-with-formspree/index.md
> +# Add a React Form with Formspree
```suggestion
# Add a React form with Formspree
```

2022-01-10 18:21 UTC, deadlypants1973 commented on products/pages/src/content/tutorials/add-a-react-form-with-formspree/index.md
> +## Tip: Using environment variables
```suggestion
## Using environment variables with forms
```

2022-01-10 18:21 UTC, deadlypants1973 commented on products/pages/src/content/tutorials/add-an-html-form-with-formspree/index.md
> +# Add an HTML Form with Formspree
```suggestion
# Add an HTML form with Formspree
```

2022-01-10 18:22 UTC, deadlypants1973 reviewed
Final style guide review

2022-01-10 18:22 UTC, deadlypants1973 requested changes
Final style guide review

2022-01-13 13:35 UTC, deadlypants1973 approved these changes

2022-01-13 14:12 UTC, merged