wip: services
cloudflare/cloudflare-docs pull request #3175
Opened 2022-01-18 16:28 UTC by eidam

2022-01-18 19:35 UTC, jkup reviewed
This is awesome! I had been working on a similar guide for Service environments so I copy/pasted some of my guide on top of yours. Would love to know what you think!

2022-01-18 19:35 UTC, jkup commented on products/workers/src/content/learning/using-services/index.md
> +Services are the new building block for deploying applications on Cloudflare Workers. Unlike the script, a service is composable, which allows services to talk to each other, allowing to develop new
```suggestion
Services are the new building block for deploying applications on Cloudflare Workers. Services are made of environments, which are scripts that can contain bindings to KV stores, Durable Objects or even other services. Services can have multiple environments and can set up pipelines for promoting a service from one environment to another.

Unlike the script, a service is composable, which allows services to talk to each other; allowing you to develop new kinds of services like routers, middlewares, or traffic gateways. Services also support multiple environments, allowing you to test changes in a preview environment, then promote to production when you’re confident.
```

2022-01-18 19:35 UTC, jkup commented on products/workers/src/content/learning/using-services/index.md
> +To enable a seamless transition to services, we’ve automatically migrated every script to become a service with one “production” environment — no action needed.
```suggestion
To enable a seamless transition to services, all scripts have been automatically migrated to services with one “production” environment — no action needed.
```

2022-01-18 19:35 UTC, jkup commented on products/workers/src/content/learning/using-services/index.md
> +Each environment is resolvable at a unique hostname, which is automatically generated when you create or rename the environment. There’s no waiting around after you deploy. Everything you need, like
```suggestion
Wrangler supports an older version of environments. With Wrangler environments, you create custom contexts for your code to run in by adding keys to your `wrangler.toml` file. Wrangler will then generate a separate script for each environment. If you make a “staging” and “prod” environment for example, Wrangler will generate `my-worker-staging` and `my-worker-prod`. 

Service environments take a cleaner approach. You can create and edit environments directly in the Dashboard. Unlike Wrangler environments, Service environments don’t create extra scripts. They are, however, able to connect to their own KV stores and Durable Objects.

Each environment is resolvable at a unique hostname, which is automatically generated when you create or rename the environment. There’s no waiting around after you deploy. Everything you need, like DNS records, SSL certificates, and more, is ready-to-go seconds later. If you’d like a more advanced setup, you can also add custom routes from your domain to an environment.
```

2022-01-18 19:35 UTC, jkup commented on products/workers/src/content/learning/using-services/index.md
> +Services are composable, allowing one service to talk to another service. To support this, we’re introducing a new API to facilitate service-to-service communication: service bindings.
Do we have a link for the new API?

```suggestion
Services are composable, allowing one service to talk to another. To support this, we’re introducing a new API to facilitate service-to-service communication: service bindings.
```

2022-01-19 10:18 UTC, eidam commented
@jkup great suggestions!! I just applied them :)

2022-01-19 21:06 UTC, jgentes commented on products/workers/src/content/learning/using-services/index.md
> +Services also support multiple environments, which allow you to test changes in a preview environment, then promote to production when you’re confident it worked.
This is a dup of the previous sentence.

2022-01-19 21:09 UTC, jgentes commented on products/workers/src/content/learning/using-services/index.md
> +Unlike the script, a service is composable, which allows services to talk to each other; allowing you to develop new kinds of services like routers, middlewares, or traffic gateways. Services also su
I don't think service-to-service works on the same zone, does it? It's coming, but not yet as far as I know.

2022-01-19 22:17 UTC, jgentes commented on products/workers/src/content/learning/using-services/index.md
> +Service environments take a cleaner approach. You can create and edit environments directly in the Dashboard. Unlike Wrangler environments, Service environments don’t create extra scripts. They are,
It may be worth adding that different environments can have different code, meaning the 'production' environment for 'james-test' service can have completely different code than 'staging'. This is intentional, as you would want to test the new version of your script in staging before pushing it to prod. But the name of the service is consistent across the different environments.

2022-01-20 15:35 UTC, JacobMGEvans commented on products/workers/src/content/learning/using-services/index.md
> +While the interface among services is HTTP, the networking is not. In fact, there is no networking! Unlike the typical “microservice architecture,” where services communicate over a network and can s
note: talked to @jkup about this particular section.

2022-01-20 19:49 UTC, jkup commented on products/workers/src/content/learning/using-services/index.md
> +Service environments take a cleaner approach. You can create and edit environments directly in the Dashboard. Unlike Wrangler environments, Service environments don’t create extra scripts. They are,
Great idea!

2022-01-20 19:55 UTC, jkup approved these changes

2022-01-22 11:52 UTC, eidam commented on products/workers/src/content/learning/using-services/index.md
> +Service environments take a cleaner approach. You can create and edit environments directly in the Dashboard. Unlike Wrangler environments, Service environments don’t create extra scripts. They are,
Thank you both! :)

2022-01-26 14:22 UTC, deadlypants1973 requested changes
PCX first review - need to follow up with Kabir and Ashcon on capitalization for services. Do not merge.

2022-01-26 14:22 UTC, deadlypants1973 commented on products/workers/src/content/learning/using-services/index.md
> +Unlike a script, a service is composable, which allows services to talk to each other; allowing you to develop new kinds of services like routers, middlewares, or traffic gateways. Services also supp
```suggestion
Unlike a script, a Workers Service is composable, which allows services to talk to each other; allowing you to develop new kinds of services like routers, middlewares, or traffic gateways. Services also support multiple environments, allowing you to test changes in a preview environment, then promote those changes to production when you are ready.
```

2022-01-26 14:22 UTC, deadlypants1973 commented on products/workers/src/content/learning/using-services/index.md
> +To enable a seamless transition to services, all scripts have been automatically migrated to services with one “production” environment — no action needed.
```suggestion
To enable a seamless transition to Services, all scripts have been automatically migrated to Services with one production environment. No action on the user's part is required.
```

2022-01-26 14:22 UTC, deadlypants1973 commented on products/workers/src/content/learning/using-services/index.md
> +To enable a seamless transition to services, all scripts have been automatically migrated to services with one “production” environment — no action needed.
Is this saying that Cloudflare has done the migration and the user doesn't have to do anything?

2022-01-26 14:22 UTC, deadlypants1973 commented on products/workers/src/content/learning/using-services/index.md
> +Each service comes with a production environment and the ability to create or clone dozens of preview environments. Every aspect of an environment is overridable: the code, environment variables, and
```suggestion
Each Workers Service comes with a production environment and the ability to create or clone dozens of preview environments. Every aspect of an environment is overridable: the code, environment variables, and resource bindings, like KV namespaces and Durable Objects. You can create and switch between environments in the dashboard, go to **Account Home** > **Workers** > **choose your Worker** > **production** > **Create environment**.
```

2022-01-26 14:22 UTC, deadlypants1973 commented on products/workers/src/content/learning/using-services/index.md
> +Currently, the dashboard is the only way to interact with service environments. Support in Wrangler is coming in [v2.1](https://github.com/cloudflare/wrangler2/issues/27)
```suggestion
As of January 2022, the dashboard is the only way to interact with Service environments. Support in Wrangler is coming in [v2.1](https://github.com/cloudflare/wrangler2/issues/27)
```

2022-01-26 14:22 UTC, deadlypants1973 commented on products/workers/src/content/learning/using-services/index.md
> +Wrangler supports an older version of environments. With Wrangler environments, you create custom contexts for your code to run in by adding keys to your `wrangler.toml` file. Wrangler will then gene
```suggestion
Wrangler supports an older version of environments. With Wrangler environments, you create custom contexts for your code to run in by adding keys to your `wrangler.toml` file. Wrangler will then generate a separate script for each environment. If you make a staging and production environment, for example, Wrangler will generate `my-worker-staging` and `my-worker-prod`. 
```

2022-01-26 14:22 UTC, deadlypants1973 commented on products/workers/src/content/learning/using-services/index.md
> +Service environments take a cleaner approach. You can create and edit environments directly in the Dashboard. Unlike Wrangler environments, Service environments don’t create extra scripts. They are,
```suggestion
Service environments take a cleaner approach. You can create and edit environments directly in the dashboard. Log in to the Cloudflare dashboard -> select your **Account** > **Workers** > select your **Service** > **Quick edit**.

Unlike Wrangler environments, Service environments do not create extra scripts. They are, however, able to connect to their own KV stores and Durable Objects. The code for any environment can be changed directly in the dashboard via the quick editor. A common workflow is to create an environment for a test feature, edit the code via the quick editor until you are satisfied with it, and then promote it to production when the code is ready.
```

2022-01-26 14:22 UTC, deadlypants1973 commented on products/workers/src/content/learning/using-services/index.md
> +Each environment is resolvable at a unique hostname, which is automatically generated when you create or rename the environment. There’s no waiting around after you deploy. Everything you need, like
```suggestion
Each environment is resolvable at a unique hostname, which is automatically generated when you create or rename the environment. There is no wait after you deploy. Everything you need, like DNS records and SSL certificates, is ready seconds later. If you would like a more advanced setup, you can add custom routes from your domain to an environment.
```

2022-01-26 14:22 UTC, deadlypants1973 commented on products/workers/src/content/learning/using-services/index.md
> +Each environment in a service has its own version history. Every time there is a code change or an environment variable is updated, the version number of that environment is incremented. You can also
```suggestion
Each environment in a Workers Service has its own version history. Every time there is a code change or an environment variable is updated, the version number of that environment is incremented. You can also append additional metadata to each version, like a `git commit` or a `deployment` tag.
```

2022-01-26 14:22 UTC, deadlypants1973 commented on products/workers/src/content/learning/using-services/index.md
> +Services are composable, allowing one service to talk to another. To support this, we’re introducing a new API to facilitate worker-to-worker communication: service bindings.
```suggestion
Workers Service bindings are an API that facilitate Worker-to-Worker communication.
```

2022-01-26 14:22 UTC, deadlypants1973 commented on products/workers/src/content/learning/using-services/index.md
> +Service bindings are in closed beta currently. Visit [Service Bindings closed beta sign up](https://www.cloudflare.com/en-gb/service-bindings-closed-beta-sign-up/) page to request access.
```suggestion
Workers Service bindings are in closed beta as of January 2022. Go to the [Workers Service bindings closed beta signup page](https://www.cloudflare.com/en-gb/service-bindings-closed-beta-sign-up/) to request access.
```

2022-01-26 14:22 UTC, deadlypants1973 commented on products/workers/src/content/learning/using-services/index.md
> +A service binding allows you to send HTTP requests to another Worker, without those requests necessarily going over the Internet. That means you can invoke other Workers directly from your code! Serv
```suggestion
A Workers Service binding allows you to send HTTP requests to another Worker without those HTTP requests going over the Internet. Because the request doesn't leave the Cloudflare edge network, latency is reduced and performance improves. You can invoke other Workers directly from your code because Service bindings allow more composability. In the example below, requests are validated by an authentication service.
```

2022-01-26 14:22 UTC, deadlypants1973 commented on products/workers/src/content/learning/using-services/index.md
> +Service bindings use the standard fetch API, so you can continue to use your existing utilities and libraries - a service binding will trigger a FetchEvent. You can also change the environment of a s
```suggestion
Workers Service bindings use the standard [Fetch API](/runtime-apis/fetch). You can continue to use your existing utilities and libraries - a service binding will trigger a `FetchEvent`. You can also change the environment of a service binding, so you can test a new version of a service. 

In the next example, 1% of requests are routed to a `CANARY` deployment of a Worker. If a request to the `CANARY` fails, it is sent to the production deployment for another chance.
```

2022-01-26 14:22 UTC, deadlypants1973 commented on products/workers/src/content/learning/using-services/index.md
> +While the interface among services is HTTP, the networking is not. In fact, there is no networking to think about! Unlike the typical “microservice architecture,” where services communicate over a ne
```suggestion
While the interface among Workers Services is HTTP, the networking is not. Unlike the typical microservice architecture, where services communicate over a network and can suffer from latency or interruption, Workers Service bindings are a zero-cost abstraction. When one Worker invokes another, there is no network delay and the request is executed immediately.
```

2022-01-26 14:22 UTC, deadlypants1973 commented on products/workers/src/content/learning/using-services/index.md
> +### Auth service
```suggestion
### Authentication service
```

2022-01-26 14:22 UTC, deadlypants1973 commented on products/workers/src/content/learning/using-services/index.md
> +Following auth service code responds with 200 in case `x-custom-token` request matches `SECRET_TOKEN` secret binding.
```suggestion
Following authentication service code responds with `200` in case `x-custom-token` request matches `SECRET_TOKEN` secret binding.
```

2022-01-26 14:22 UTC, deadlypants1973 commented on products/workers/src/content/learning/using-services/index.md
> +A service binding allows you to send HTTP requests to another Worker, without those requests necessarily going over the Internet. That means you can invoke other Workers directly from your code! Serv
If they are not going over the Internet, how are they going? This needs to be clarified.

2022-01-26 14:22 UTC, deadlypants1973 commented on products/workers/src/content/learning/using-services/index.md
> +Each service comes with a production environment and the ability to create or clone dozens of preview environments. Every aspect of an environment is overridable: the code, environment variables, and
We need step-by-step instructions on how you can switch between environments on the dashboard in the last sentence.

2022-01-26 14:22 UTC, deadlypants1973 commented on products/workers/src/content/learning/using-services/index.md
> +This zero-cost model enables teams to share and reuse code within their organizations, without sacrificing latency or performance. Forget the days of convoluted YAML templates or exponential back off
```suggestion
```

2022-01-26 14:22 UTC, deadlypants1973 commented on products/workers/src/content/learning/using-services/index.md
> +Overall, Service Bindings will allow you to:
```suggestion
Service Bindings allow you to:
```

2022-01-26 14:22 UTC, deadlypants1973 commented on products/workers/src/content/learning/using-services/index.md
> +- Create private microservices, to be conditionally invoked from other edge facing services
```suggestion
- Segment multiple use cases into separate Services that can be explicitly invoked from your code.
- Achieve better composability on the Workers platform using Service-oriented architecture.
- Create private microservices, to be conditionally invoked from other edge-facing Services.
```

2022-01-26 14:22 UTC, deadlypants1973 commented on products/workers/src/content/learning/using-services/index.md
> +Workers services are composable, allowing one service to talk to each other. Complex applications can be composed from many smaller Workers, allowing organisations to separate concerns across individ
```suggestion
```

2022-01-26 14:22 UTC, deadlypants1973 commented on products/workers/src/content/learning/using-services/index.md
> +Workers services are composable, allowing one service to talk to each other. Complex applications can be composed from many smaller Workers, allowing organisations to separate concerns across individ
Could be wrong but I don't think this needs to be here. It seems like it is repeating information and more of a blog talking point than a technical documentation need.

2022-01-26 14:22 UTC, deadlypants1973 commented on products/workers/src/content/learning/using-services/index.md
> +This auth service does not need to have workers.dev or custom domain public endpoint, it will accessed through a service binding from the other service script directly.
```suggestion
This authentication service does not need to have `*.workers.dev` or custom domain public endpoint, it is accessed through a Service Binding from the other Service script directly.
```

2022-01-26 14:22 UTC, deadlypants1973 commented on products/workers/src/content/learning/using-services/index.md
> +### Gateway Worker and service bindings usage
```suggestion
### Gateway Worker and Service Bindings usage
```

2022-01-26 14:22 UTC, deadlypants1973 commented on products/workers/src/content/learning/using-services/index.md
> +
```suggestion
```

2022-01-26 14:22 UTC, deadlypants1973 commented on products/workers/src/content/learning/using-services/index.md
> +In order to bind and call auth service above, the app service needs to setup a service binding. You can manage service bindings in `Settings -> Variables` under the Workers Service settings.
```suggestion
In order to bind and call the [authentication Service above](/#authentication-service), the application Service needs to set up a Service Binding. You can manage Service Bindings in **Workers** > select your **Worker** > **Settings** -> **Variables** > **Service Bindings** > **Edit variables**.
```

2022-01-26 14:22 UTC, deadlypants1973 commented on products/workers/src/content/learning/using-services/index.md
> +
```suggestion
```

2022-01-26 14:22 UTC, deadlypants1973 commented on products/workers/src/content/learning/using-services/index.md
> +Once added, app service can access the service binding directly from the code, as in example below.
```suggestion
Once added, the application Service can access the Service Binding directly from the code, as in the example below.
```

2022-01-26 14:22 UTC, deadlypants1973 commented on products/workers/src/content/learning/using-services/index.md
> +Note that [requests](/runtime-apis/request) can only be read once; if you need to use a request object multiple times, be sure to clone your incoming request objects.
```suggestion
Note that [Requests](/runtime-apis/request) can only be read once. If you need to use a Request object multiple times, clone your incoming Request objects.
```

2022-01-26 14:22 UTC, deadlypants1973 commented on products/workers/src/content/learning/using-services/index.md
> +
```suggestion
```

2022-01-26 14:22 UTC, deadlypants1973 commented on products/workers/src/content/learning/using-services/index.md
> +In this setup, only the Gateway Worker is exposed to the internet, and _(privately)_ communicating with the Auth Worker using a Workers service binding.
```suggestion
In this setup, only the Gateway Worker is exposed to the internet, and privately communicating with the authentication Worker using a Workers Service Binding.
```

2022-01-27 15:32 UTC, kabirsikand commented on products/workers/src/content/learning/using-services/index.md
> +Services are the new building block for deploying applications on Cloudflare Workers. Services are made of environments, which are scripts that can contain bindings to KV stores, Durable Objects or e
```suggestion
Services are the new building block for deploying applications on Cloudflare Workers. Workers Services are made of environments, which are scripts that can contain bindings to KV stores, Durable Objects or even other services, as well as environment variables and secrets. Workers Services can have multiple environments and can set up pipelines for promoting a service from one environment to another.
```

2022-01-27 15:36 UTC, kabirsikand commented on products/workers/src/content/learning/using-services/index.md
> +Each service comes with a production environment and the ability to create or clone dozens of preview environments. Every aspect of an environment is overridable: the code, environment variables, and
Workers Service

2022-01-27 15:36 UTC, kabirsikand commented on products/workers/src/content/learning/using-services/index.md
> +Each environment in a service has its own version history. Every time there is a code change or an environment variable is updated, the version number of that environment is incremented. You can also
Each Environment in a Workers Service

2022-01-27 15:37 UTC, kabirsikand commented on products/workers/src/content/learning/using-services/index.md
> +Services are composable, allowing one service to talk to another. To support this, we’re introducing a new API to facilitate worker-to-worker communication: service bindings.
Workers Service bindings

2022-01-27 15:37 UTC, kabirsikand commented on products/workers/src/content/learning/using-services/index.md
> +Service bindings are in closed beta currently. Visit [Service Bindings closed beta sign up](https://www.cloudflare.com/en-gb/service-bindings-closed-beta-sign-up/) page to request access.
Workers Service bindings

2022-01-28 13:50 UTC, deadlypants1973 commented on products/workers/src/content/learning/using-services/index.md
> +To enable a seamless transition to Services, all scripts have been automatically migrated to Services with one production environment. No action on the user's part is required.
```suggestion
To enable a seamless transition to Services, all scripts have been automatically migrated to Services with one production environment. No action is needed from the user. 
```

2022-01-28 14:04 UTC, deadlypants1973 approved these changes

2022-01-28 14:32 UTC, merged

2022-06-03 19:37 UTC, Greatshopping reviewed
Did it fix

2022-06-03 19:39 UTC, Greatshopping reviewed
Apply