[Magic Firewall] Added best practice content
cloudflare/cloudflare-docs pull request #3323
Opened 2022-02-01 21:47 UTC by dcpena

- Added best practice content for Magic Firewall rules
- Updated order for a few existing pages
- Fixed a typo in one topic and updated header style

Addresses [PCX-3091](https://jira.cfops.it/browse/PCX-3091).

2022-02-01 22:00 UTC, annikagarbers approved these changes
Hooray! So excited to have this content added

2022-02-01 22:43 UTC, kodster28 approved these changes

2022-02-01 22:43 UTC, kodster28 commented on products/magic-firewall/src/content/how-to/add-rules.md
> +By default, you can create a maximum of 100 rules, and you can create lists of IP addresses for referencing within rules to minimize the number of rules you need to configure.
```suggestion
By default, you can create a maximum of 100 rules. We recommend you create lists of IP addresses to reference within rules to streamline rule management.
```

2022-02-01 22:43 UTC, kodster28 commented on products/magic-firewall/src/content/how-to/add-rules.md
> +By default, you can create a maximum of 100 rules, and you can create lists of IP addresses for referencing within rules to minimize the number of rules you need to configure.
Or something breaking up the thoughts a bit.

2022-02-01 22:43 UTC, kodster28 commented on products/magic-firewall/src/content/best-practices/magic-transit-egress.md
> +The suggestions in the [Minimal ruleset](/best-practices/minimal-ruleset) and [Extended rulseet](/best-practices/extended-ruleset) are recommendations for ingress traffic.
```suggestion
The suggestions in the [Minimal ruleset](/best-practices/minimal-ruleset) and [Extended ruleset](/best-practices/extended-ruleset) are recommendations for ingress traffic.
```

2022-02-01 22:43 UTC, kodster28 commented on products/magic-firewall/src/content/best-practices/magic-transit-egress.md
> +- If you have Magic Firewall "default drop" catchall rule for ingress traffic, you will need to add an earlier rule to permit traffic sourced from your Magic Transit prefix with the destination as **
```suggestion
- If you have Magic Firewall "default drop" catchall rule for ingress traffic, you will need to add an earlier rule to permit traffic sourced from your Magic Transit prefix with the destination as **any** to allow outbound egress traffic.
```

2022-02-01 22:43 UTC, kodster28 commented on products/magic-firewall/src/content/best-practices/index.md
> +By default, Magic Firewall permits all ingress traffic that has passed through Cloudflare's core DDoS mitigations. In order to proactively mitigate attacks and minimize your attack surface and leakag
```suggestion
By default, Magic Firewall permits all ingress traffic that has passed through Cloudflare's core DDoS mitigations. To proactively mitigate attacks and minimize your attack surface and leakage of attack traffic into your environment, we recommend implementing your Magic Firewall rules using the following guidelines.
```

2022-02-01 22:43 UTC, kodster28 commented on products/magic-firewall/src/content/about/ruleset-logic.md
> +You have two options for configuring a security policy: enforce a positive security model and only permit required traffic and block everything else or begin with a minimal ruleset to block specific
Maybe break this up? I know we don't normally like a two-item bulleted list, but it's hard to know where one option stops and the other begins when scanning.

Either that, or separate each option (positive security model and negative) into a separate sentence?

2022-02-01 22:43 UTC, kodster28 commented on products/magic-firewall/src/content/about/ruleset-logic.md
> +Cloudflare-sourced traffic is also subject to the Magic Firewall rules you configure.  If you block all ICMP traffic, you will also block Cloudflare's endpoint health checks from being sent. To restr
```suggestion
Cloudflare-sourced traffic is also subject to the Magic Firewall rules you configure.  If you block all ICMP traffic, you will also block Cloudflare's endpoint health checks. To restrict the inbound ICMP traffic, ensure your rules first allow ICMP sourced from Cloudflare public IPs to your prefix endpoint IPs before applying a block ICMP rule. 
```

2022-02-01 22:43 UTC, kodster28 commented on products/magic-firewall/src/content/best-practices/minimal-ruleset.md
> +Note that this is a suggested list and not an exhaustive list. Please check what fits for your environment and add more rules as necessary.
```suggestion
This is a suggested list and not an exhaustive list. Review your environment and add more rules as necessary.
```

2022-02-01 22:43 UTC, kodster28 commented on products/magic-firewall/src/content/best-practices/extended-ruleset.md
> +pcx-content-type: tutorial
Think this falls more under a `configuration` guide personally.

2022-02-01 22:43 UTC, kodster28 commented on products/magic-firewall/src/content/best-practices/extended-ruleset.md
> +- [Internal routers](#internal-routerfirewall-ips)
```suggestion
- [Internal routers](#internal-routerfirewall-ip-addresses)
```

2022-02-01 22:43 UTC, kodster28 commented on products/magic-firewall/src/content/best-practices/extended-ruleset.md
> +- They receive traffic from standard common ports, for example 80,443, towards their ephemeral ports, above 32768 in modern operating systems (1025 in older XP).
```suggestion
- They receive traffic from standard common ports — for example 80 or 443 — towards their ephemeral ports, above 32768 in modern operating systems (1025 in older XP).
```

2022-02-01 22:43 UTC, kodster28 commented on products/magic-firewall/src/content/best-practices/extended-ruleset.md
> +- They receive traffic from standard common ports, for example 80,443, towards their ephemeral ports, above 32768 in modern operating systems (1025 in older XP).
Figured having dashes helps break up the comma logjam a bit.

2022-02-01 22:43 UTC, kodster28 commented on products/magic-firewall/src/content/best-practices/extended-ruleset.md
> +**Description**: Endpoints (clients) will receive traffic destined for ephemeral ports. Blocks inbound SYN-only traffic. (i.e. SYN-ACKs are permitted) <br/>
```suggestion
**Description**: Endpoints (clients) will receive traffic destined for ephemeral ports. Blocks inbound SYN-only traffic. (meaning SYN-ACKs are permitted) <br/> 
```

2022-02-01 22:43 UTC, kodster28 commented on products/magic-firewall/src/content/best-practices/extended-ruleset.md
> +**Match**: `ip.proto eq "tcp" and ip.dst in $endpoints and tcp.dstport in {32768..60999} and not (tcp.flags.syn and not tcp.flags.ack` <br/>
Are you missing a parentheses somewhere in this rule? There's one around `(tcp.flags.syn` but no closing one?

2022-02-01 22:43 UTC, kodster28 commented on products/magic-firewall/src/content/best-practices/extended-ruleset.md
> +1. Create a list, **Internal routers** for example, list your IP addresses.
```suggestion
1. Create [a list](https://developers.cloudflare.com/firewall/cf-dashboard/rules-lists), **Internal routers** for example, list your IP addresses.
```

2022-02-01 22:43 UTC, kodster28 commented on products/magic-firewall/src/content/best-practices/extended-ruleset.md
> +**Description**: Permit limited ICMP traffic inbound: examples here are
Confused on the formatting related to `examples here are`, is this phrase needed?

2022-02-01 22:43 UTC, kodster28 commented on products/magic-firewall/src/content/best-practices/extended-ruleset.md
> +- Type 11 = Time Exceeded <br/>
```suggestion
- Type 11 - Time Exceeded <br/>
```

2022-02-01 22:43 UTC, kodster28 commented on products/magic-firewall/src/content/best-practices/extended-ruleset.md
> +The following is an example of suggested rules, but you should only make changes based on your specific requirements. For example, if you are not proxied by Cloudflare Layer 7 protection, and you exp
```suggestion
The following is an example of suggested rules, but you should only make changes based on your specific requirements. For example, if you are not proxied by Cloudflare Layer 7 protection and you expect traffic sourced from the web towards your web servers:
```

2022-02-01 22:43 UTC, kodster28 commented on products/magic-firewall/src/content/best-practices/extended-ruleset.md
> +1. Create a list, **web servers** for example, to list IP addresses for your web servers.
```suggestion
1. Create [a list](https://developers.cloudflare.com/firewall/cf-dashboard/rules-lists), **web servers** for example, to list IP addresses for your web servers.
```

2022-02-01 22:43 UTC, kodster28 commented on products/magic-firewall/src/content/best-practices/extended-ruleset.md
> +Alternatively, if you have Cloudflare Layer 7 protection, the Cloudflare Public IP addresses can be permitted as the source IP addresses to the destination IP addresses for the HTTP/HTTPS inbound tra
I would just move this section down into the next header.

Additionally, I would recommend you just tell them to create an IP list with Cloudflare's IP addresses and then reference that fake rule instead of listing out all our public IP addresses. Thinking that might be better b/c a) it's the recommended solution and b) our IP addresses might change in the future.

2022-02-01 22:51 UTC, arges requested changes

2022-02-01 22:51 UTC, arges commented on products/magic-firewall/src/content/about/ruleset-logic.md
> +Magic Firewall rules are performed after Cloudflare's DDoS mitigations have been applied. The two systems are not related, and therefore, permitting traffic inside Magic Firewall does not allow it wi
Can we change "the two systems are not related" to something more specific?  Maybe "The two systems are independent"

2022-02-01 22:51 UTC, arges commented on products/magic-firewall/src/content/about/ruleset-logic.md
> +Magic Firewall does not have implicit deny logic, and all traffic is permitted unless it has been blocked by a rule. If no rules are configured, all traffic is permitted after Cloudflare’s DDoS mitig
Can this be worded differently? "Magic Firewall by default permits all traffic until explicitly blocked by a rule."

2022-02-01 22:51 UTC, arges commented on products/magic-firewall/src/content/about/ruleset-logic.md
> +You have two options for configuring a security policy: enforce a positive security model and only permit required traffic and block everything else or begin with a minimal ruleset to block specific
This sentence is unclear, could it be broken up into multiple sentences.

2022-02-01 22:51 UTC, arges commented on products/magic-firewall/src/content/about/ruleset-logic.md
> +Traffic is matched in order of the configured rules. As soon as traffic is matched by a rule, it is no longer validated against the later rules. For example, permitting all TCP traffic in a rule #4 w
"As soon as traffic is matched by an enabled rule, it is no longer validated against the later rules. Traffic will pass through disabled rules."

Also how do we express what rule order is here? Visually in the UI this is Top-Down.

2022-02-01 22:51 UTC, arges commented on products/magic-firewall/src/content/about/ruleset-logic.md
> +Cloudflare-sourced traffic is also subject to the Magic Firewall rules you configure.  If you block all ICMP traffic, you will also block Cloudflare's endpoint health checks from being sent. To restr
"To restrict the inbound ICMP traffic" -> "When blocking ICMP traffic"

2022-02-01 22:51 UTC, arges commented on products/magic-firewall/src/content/best-practices/index.md
> +The best approach is to replicate your current ingress perimeter firewall rules in Magic Firewall. If you are unable to export your current perimeter firewall rules, contact your Implementation Manag
These two paragraphs are duplicated in other areas. Is this intentional?

2022-02-01 22:51 UTC, arges commented on products/magic-firewall/src/content/best-practices/magic-transit-egress.md
> +- If you have Magic Firewall "default drop" catchall rule for ingress traffic, you will need to add an earlier rule to permit traffic sourced from your Magic Transit prefix with the destination as **
"If you have Magic Firewall" -> "If you have a Magic Firewall"

2022-02-01 22:52 UTC, dcpena commented on products/magic-firewall/src/content/about/ruleset-logic.md
> +You have two options for configuring a security policy: enforce a positive security model and only permit required traffic and block everything else or begin with a minimal ruleset to block specific
Good call. I think a two bullet list is easier to read.

2022-02-01 22:52 UTC, dcpena commented on products/magic-firewall/src/content/best-practices/extended-ruleset.md
> +pcx-content-type: tutorial
Agreed

2022-02-01 22:52 UTC, dcpena commented on products/magic-firewall/src/content/best-practices/extended-ruleset.md
> +**Match**: `ip.proto eq "tcp" and ip.dst in $endpoints and tcp.dstport in {32768..60999} and not (tcp.flags.syn and not tcp.flags.ack` <br/>
Yes! Good eye, thank you for catching that.

2022-02-01 22:52 UTC, dcpena commented on products/magic-firewall/src/content/best-practices/extended-ruleset.md
> +**Description**: Permit limited ICMP traffic inbound: examples here are
Fixed

2022-02-01 22:54 UTC, dcpena commented on products/magic-firewall/src/content/best-practices/extended-ruleset.md
> +Alternatively, if you have Cloudflare Layer 7 protection, the Cloudflare Public IP addresses can be permitted as the source IP addresses to the destination IP addresses for the HTTP/HTTPS inbound tra
I'm going to make note of this and address it in a separate PR so I can get formatting correct.

2022-02-01 23:06 UTC, dcpena commented on products/magic-firewall/src/content/best-practices/index.md
> +The best approach is to replicate your current ingress perimeter firewall rules in Magic Firewall. If you are unable to export your current perimeter firewall rules, contact your Implementation Manag
I kept the information and removed it where it was duplicated in the other topic.

2022-02-01 23:07 UTC, dcpena commented on products/magic-firewall/src/content/about/ruleset-logic.md
> +Magic Firewall rules are performed after Cloudflare's DDoS mitigations have been applied. The two systems are not related, and therefore, permitting traffic inside Magic Firewall does not allow it wi
Fixed

2022-02-01 23:07 UTC, dcpena commented on products/magic-firewall/src/content/about/ruleset-logic.md
> +Magic Firewall does not have implicit deny logic, and all traffic is permitted unless it has been blocked by a rule. If no rules are configured, all traffic is permitted after Cloudflare’s DDoS mitig
Good suggestion! fixed

2022-02-02 15:24 UTC, dcpena commented on products/magic-firewall/src/content/about/ruleset-logic.md
> +Traffic is matched in order of the configured rules. As soon as traffic is matched by a rule, it is no longer validated against the later rules. For example, permitting all TCP traffic in a rule #4 w
After the sentence you mentioned, I added "In the dashboard under **Magic Firewall**, rule order begins from the top and flows down your list of rules." Do you think that is sufficient?

2022-02-02 15:24 UTC, dcpena commented on products/magic-firewall/src/content/about/ruleset-logic.md
> +Cloudflare-sourced traffic is also subject to the Magic Firewall rules you configure.  If you block all ICMP traffic, you will also block Cloudflare's endpoint health checks from being sent. To restr
Fixed

2022-02-02 15:24 UTC, dcpena commented on products/magic-firewall/src/content/best-practices/magic-transit-egress.md
> +- If you have Magic Firewall "default drop" catchall rule for ingress traffic, you will need to add an earlier rule to permit traffic sourced from your Magic Transit prefix with the destination as **
Fixed

2022-02-02 15:29 UTC, dcpena commented on products/magic-firewall/src/content/about/ruleset-logic.md
> +You have two options for configuring a security policy: enforce a positive security model and only permit required traffic and block everything else or begin with a minimal ruleset to block specific
I split this out into two bullets for easier reading. I think it improves the readability.

2022-02-02 19:28 UTC, arges approved these changes

2022-02-02 19:29 UTC, merged