Add bulk redirects to Pages how to section.
cloudflare/cloudflare-docs pull request #3454
Opened 2022-02-13 15:16 UTC by Ekwuno

We recommend using bulk redirects when you have a maximum of 100 redirect rules. Also in place of existing Pages Rules. This PR adds a new "how-to" on Using bulk redirects and recommends it when the `_redirects` file hits the limit.

Addresses #3372

2022-02-22 12:14 UTC, geelen commented on products/pages/src/content/how-to/www-redirect.md
> +It is recommended to use [Bulk Redirects](https://developers.cloudflare.com/pages/how-to/use-bulk-redirects.md) instead of Page Rules for redirecting domains. However, using Pages Rules will work as
This sentence confuses me a little. Are we saying this article (using page rules) is the right way or the wrong way? 

If it's right, this maybe should say "Although generally recommended to use [Bulk Redirects] when redirecting between domains, in the simple case where you just want a single redirect from `www.example.com` to `example.com`, a single Page Rule will work just as well." or something.

If it's wrong, it feels there should be an equivalent how-to for www->apex but using bulk redirects

2022-02-22 12:14 UTC, geelen commented on products/pages/src/content/how-to/use-bulk-redirects.md
> +In this tutorial, you will learn how to use Bulk redirects to handle redirects that are over `100` on your Pages projects. Since [`_redirects`](https://developers.cloudflare.com/pages/platform/limits
> that are over `100`...

replace with

> if you need more than the 100 supported by the [`_redirects`] file.

2022-02-22 12:14 UTC, geelen commented on products/pages/src/content/how-to/use-bulk-redirects.md
> +
Should we add a note here that these apply _in addition to_ and _in front of_ any redirects in your _redirects file?

2022-02-22 13:40 UTC, Ekwuno commented on products/pages/src/content/how-to/www-redirect.md
> +It is recommended to use [Bulk Redirects](https://developers.cloudflare.com/pages/how-to/use-bulk-redirects.md) instead of Page Rules for redirecting domains. However, using Pages Rules will work as
I think you are right, bulk redirects is a Page rule but recommended for more than our pages _redirects can handle at this time. I will update

2022-02-22 13:44 UTC, Ekwuno commented on products/pages/src/content/how-to/use-bulk-redirects.md
> +
Yea, I will add a note as well.

2022-02-22 18:09 UTC, deadlypants1973 requested changes

2022-02-22 18:09 UTC, deadlypants1973 commented on products/pages/src/content/how-to/use-bulk-redirects.md
> +</Aside>
```suggestion
<Aside type="Note">

The redirects defined in the _redirects file of your build folder can work together with your Bulk Redirects. In case of duplicates, Bulk redirects will run infront of your Pages project where your other redirects live.

</Aside>
```

2022-02-22 18:09 UTC, deadlypants1973 commented on products/pages/src/content/how-to/use-bulk-redirects.md
> +To do this, go to the [project overview dashboard](https://dash.cloudflare.com?to=/:account/:zone/rules) and under **Rules** select Bulk Redirects.
```suggestion
To do this, log in to the [Cloudflare dashboard](https://dash.cloudflare.com?to=/:account/:zone/rules) > **Rules** > **Bulk Redirects**.
```

2022-02-22 18:09 UTC, deadlypants1973 commented on products/pages/src/content/how-to/use-bulk-redirects.md
> +This will take you to the bulk redirects UI where you will create a new Bulk Redirects list.
```suggestion
In **Bulk Redirects**, select **Create a new Bulk Redirects list**.
```

2022-02-22 18:09 UTC, deadlypants1973 commented on products/pages/src/content/how-to/use-bulk-redirects.md
> +Then create a new list, and in the content type select Redirect. This will lead you to add your redirect Source URL and Target URL, you can also specific the status code for each redirect.
```suggestion
Create a new list, and in the content type, select **Redirect**. You will be prompted to add your redirect **Source URL** and **Target URL**. You can also specify the **Status** code for each redirect.
```

2022-02-22 18:09 UTC, deadlypants1973 commented on products/pages/src/content/how-to/use-bulk-redirects.md
> +After this, go back to the create Bulk Redirects button and select the list you just created. You would have to set a name for the **Page Rule** you are creating.
```suggestion
<Aside type="note">

You can upload a CSV file of all your redirects. However, your redirects cannot be a relative path.

</Aside>

If you set the **Source URL** to `https://www.example.dev/examples` and the **Target URL** to `https://www.example.dev/pages/examples` with a status code of `301`, whenever the **Source URL** is requested, it will be permanently redirected to the **Target URL**.

After this, go back to **Bulk Redirects** > **Create Bulk Redirects**  > set a **Rule name** > and select the desired list.
```

2022-02-22 18:09 UTC, deadlypants1973 commented on products/pages/src/content/how-to/www-redirect.md
> +</Aside>
```suggestion
<Aside type= "note">

Although it is generally recommended to use [Bulk Redirects](./use-bulk-redirects.md) when redirecting between domains, for smaller use cases, such as a single redirect from `www.example.com` to `example.com`, a single Page Rule will work just as well.

</Aside>
```

2022-02-22 23:06 UTC, WalshyDev requested changes

2022-02-22 23:06 UTC, WalshyDev commented on products/pages/src/content/platform/limits.md
> +A `_redirects` file can have a maximum of 100 redirect rules. It is recommended to use [Bulk Redirects](../how-to/use-bulk-redirects.md) when you have more than 100 redirects rules.
nitpick
```suggestion
A `_redirects` file can have a maximum of 100 redirect rules. It is recommended to use [Bulk Redirects](../how-to/use-bulk-redirects.md) when you have more than 100 redirect rules.
```

2022-02-22 23:06 UTC, WalshyDev commented on products/pages/src/content/how-to/use-bulk-redirects.md
> +Finally, select **Save and deploy** and wait a few seconds for your rule to propagate.
We should probably also mention some of the options Bulk Redirects have. Mentioning that having like `example.com/` with "Subpath mathing" will match `example.com/*`
(I'm not actually sure on the specifics of how this works but it's a common thing people want so worth mentioning)

2022-02-23 14:22 UTC, deadlypants1973 approved these changes

2022-02-23 14:35 UTC, deadlypants1973 approved these changes

2022-02-23 14:35 UTC, deadlypants1973 commented on products/pages/src/content/how-to/use-bulk-redirects.md
> +In this tutorial, you will learn how to use Bulk redirects to handle redirects if you need more than the 100 supported by the [`_redirects`](https://developers.cloudflare.com/pages/platform/limits#re
```suggestion
In this tutorial, you will learn how to use [Bulk Redirects (beta)](https://developers.cloudflare.com/rules/bulk-redirects) to handle redirects that surpasses the 100 redirect rules limit set by Pages. A [`_redirects`](https://developers.cloudflare.com/pages/platform/limits#redirects) file has a maximum of 100 redirect rules.
```

2022-02-23 14:35 UTC, deadlypants1973 commented on products/pages/src/content/how-to/use-bulk-redirects.md
> +The redirects defined in the _redirects file of your build folder can work together with your Bulk Redirects. In case of duplicates, Bulk redirects will run infront of your Pages project where your o
```suggestion
The redirects defined in the `_redirects` file of your build folder can work together with your Bulk Redirects. In case of duplicates, Bulk Redirects will run in front of your Pages project, where your other redirects live.
```

2022-02-23 14:35 UTC, deadlypants1973 commented on products/pages/src/content/how-to/use-bulk-redirects.md
> +To do this, log in to the [Cloudflare dashboard](https://dash.cloudflare.com?to=/:account/:zone/rules) > **Rules** > **Bulk Redirects**.
```suggestion
To use Bulk Redirects, log in to the [Cloudflare dashboard](https://dash.cloudflare.com?to=/:account/:zone/rules) > **Rules** > **Bulk Redirects**.
```

2022-02-23 14:46 UTC, merged