Update Netlify to Pages Migration docs
cloudflare/cloudflare-docs pull request #3521
Opened 2022-02-18 13:13 UTC by Ekwuno

Updating the Migration guide to show things we currently support for Netlify users looking to Migrate to Pages

This PR addresses #3265

2022-02-22 18:01 UTC, deadlypants1973 requested changes
PCX first review

2022-02-22 18:01 UTC, deadlypants1973 commented on products/pages/src/content/how-to/use-bulk-redirects.md
> +In this tutorial, you will learn how to use Bulk redirects to handle redirects that are over `100` on your Pages projects. Since [`_redirects`](https://developers.cloudflare.com/pages/platform/limits
```suggestion
In this tutorial, you will learn how to use [Bulk Redirects (beta)](https://developers.cloudflare.com/rules/bulk-redirects) to handle redirects that surpasses the 100 redirect rules limit set by Pages. A [`_redirects`](https://developers.cloudflare.com/pages/platform/limits#redirects) file has a maximum of 100 redirect rules.
```

2022-02-22 18:01 UTC, deadlypants1973 commented on products/pages/src/content/how-to/use-bulk-redirects.md
> +To do this, go to the [project overview dashboard](https://dash.cloudflare.com?to=/:account/:zone/rules) and under **Rules** select Bulk Redirects.
```suggestion
To use Bulk Redirects, log in to the [Cloudflare dashboard](https://dash.cloudflare.com?to=/:account/:zone/rules) > **Rules** > **Bulk Redirects**.
```

2022-02-22 18:01 UTC, deadlypants1973 commented on products/pages/src/content/how-to/use-bulk-redirects.md
> +This will take you to the bulk redirects UI where you will create a new Bulk Redirects list.
```suggestion
In **Bulk Redirects**, select **Create a new Bulk Redirects list**. 
```

2022-02-22 18:01 UTC, deadlypants1973 commented on products/pages/src/content/how-to/www-redirect.md
> +</Aside>
```suggestion
<Aside type= "note">

It is recommended to use [Bulk Redirects](https://developers.cloudflare.com/pages/how-to/use-bulk-redirects.md) instead of Page Rules for redirecting domains. However, using Pages Rules will work as expected.

</Aside>
```

2022-02-22 18:01 UTC, deadlypants1973 commented on products/pages/src/content/how-to/use-bulk-redirects.md
> +Then create a new list, and in the content type select Redirect. This will lead you to add your redirect Source URL and Target URL, you can also specific the status code for each redirect.
```suggestion
Create a new list, and in the content type, select **Redirect**. You will be prompted to add your redirect **Source URL** and **Target URL**. You can also specify the **Status** code for each redirect. 
```

2022-02-22 18:01 UTC, deadlypants1973 commented on products/pages/src/content/how-to/use-bulk-redirects.md
> +You can also upload a CSV file of all your redirects, however your redirects can not be a relative path.
```suggestion
You can upload a CSV file of all your redirects. However, your redirects cannot be a relative path.
```

2022-02-22 18:01 UTC, deadlypants1973 commented on products/pages/src/content/how-to/use-bulk-redirects.md
> +If for example you set the Source URL to `https://www.example.dev/examples` and the target to `https://www.example.dev/pages/examples` with a status code of `301`, whenever the Source is requested it
```suggestion
If you set the **Source URL** to `https://www.example.dev/examples` and the **Target URL** to `https://www.example.dev/pages/examples` with a status code of `301`, whenever the **Source URL** is requested, it will be permanently redirected to the **Target URL**.
```

2022-02-22 18:01 UTC, deadlypants1973 commented on products/pages/src/content/how-to/use-bulk-redirects.md
> +After this, go back to the create Bulk Redirects button and select the list you just created. You would have to set a name for the **Page Rule** you are creating.
```suggestion
After this, go back to **Bulk Redirects** > **Create Bulk Redirects**  > set a **Rule name** > and select the desired list.
```

2022-02-22 18:01 UTC, deadlypants1973 commented on products/pages/src/content/how-to/use-bulk-redirects.md
> +
```suggestion
```

2022-02-22 18:01 UTC, deadlypants1973 commented on products/pages/src/content/migrations/migrating-from-netlify/index.md
> +If your site includes a `_redirects` folder in your publish directory you can use the same file in Cloudflare Pages and your redirects will work the same. If your redirects are in your `netlify.toml`
```suggestion
If your site includes a `_redirects` file in your publish directory, you can use the same file in Cloudflare Pages and your redirects will execute successfully. If your redirects are in your `netlify.toml` file, you will need to add them to the `_redirects` folder. Cloudflare Pages currently offers limited [supports for advanced redirects](https://developers.cloudflare.com/pages/platform/redirects). In the case where you have redirects rules over 100, it is recommended to use [Bulk Redirects](https://developers.cloudflare.com/rules/bulk-redirects/create-dashboard).
```

2022-02-22 18:01 UTC, deadlypants1973 commented on products/pages/src/content/migrations/migrating-from-netlify/index.md
> +Redirects execute before headers, so in the case of a request matching rules in both files, the redirect will win out.
```suggestion
Redirects execute before headers. In the case of a request matching rules in both files, the redirect will take precedence.
```

2022-02-22 18:01 UTC, deadlypants1973 commented on products/pages/src/content/migrations/migrating-from-netlify/index.md
> +Your header files can also be moved into a `_headers` folder in your publish directory. It is important to note that Custom headers defined in the `_headers` file are not currently applied to respons
```suggestion
Your header files can also be moved into a `_headers` folder in your publish directory. It is important to note that custom headers defined in the `_headers` file are not currently applied to responses from functions, even if the function route matches the URL pattern. To learn more about how to [handle headers, refer to Headers](https://developers.cloudflare.com/pages/platform/headers).
```

2022-02-22 18:01 UTC, deadlypants1973 commented on products/pages/src/content/migrations/migrating-from-netlify/index.md
> +## Serverless Functions
```suggestion
## Serverless functions 
```

2022-02-22 18:01 UTC, deadlypants1973 commented on products/pages/src/content/migrations/migrating-from-netlify/index.md
> +In your form component remove the `data-netlify = "true"` atrribute or netlify attribute from the `<form>` tag. You can now put your form logic as a Pages Function and collect the entries to a databa
```suggestion
In your form component, remove the `data-netlify = "true"` attribute or the Netlify attribute from the `<form>` tag. You can now put your form logic as a Pages Function and collect the entries to a database or an Airtable. Refer to the [handling form submissions with Pages Functions](https://developers.cloudflare.com/pages/tutorials/forms) tutorial for more information.
```

2022-02-22 18:01 UTC, deadlypants1973 commented on products/pages/src/content/migrations/migrating-from-netlify/index.md
> +
```suggestion
```

2022-02-22 18:01 UTC, deadlypants1973 commented on products/pages/src/content/migrations/migrating-from-netlify/index.md
> +## Other Netlify Config
```suggestion
## Other Netlify configurations
```

2022-02-22 18:01 UTC, deadlypants1973 commented on products/pages/src/content/migrations/migrating-from-netlify/index.md
> +Your `netlify.toml` might have other configurations that are supported by Pages in the Pages UI, by default such as preview deployment, specifying publish directory and plugins. You can delete the fi
```suggestion
Your `netlify.toml` file might have other configurations that are supported by Pages, such as, preview deployment, specifying publish directory, and plugins. You can delete the file after migrating your configurations. 
```

2022-02-22 18:01 UTC, deadlypants1973 commented on products/pages/src/content/migrations/migrating-from-netlify/index.md
> +You can migrate your access management to [Cloudflare's Zero Trust](https://developers.cloudflare.com/cloudflare-one/) which allows you to manage authentication of users in your apps, event logging a
```suggestion
You can migrate your access management to [Cloudflare Zero Trust](https://developers.cloudflare.com/cloudflare-one/) which allows you to manage user authentication for your applications, event logging and requests.

```

2022-02-22 18:01 UTC, deadlypants1973 commented on products/pages/src/content/migrations/migrating-from-netlify/index.md
> +### Functions Syntax
```suggestion
### Functions syntax
```

2022-02-22 18:01 UTC, deadlypants1973 commented on products/pages/src/content/migrations/migrating-from-netlify/index.md
> +Netlify functions export an async event handler that accepts and event and a context as arguments. In the case of a Pages Functions you will have to export a single `OnRequest` function that accepts
@Ekwuno

2022-02-22 18:01 UTC, deadlypants1973 commented on products/pages/src/content/migrations/migrating-from-netlify/index.md
> +Netlify functions and Pages Functions share the same filesystem convention using a `Functions` directory in the base of your project to handle your serverless functions the file can be stored directl
@Ekwuno

2022-02-22 22:47 UTC, Ekwuno commented on products/pages/src/content/migrations/migrating-from-netlify/index.md
> +If your site includes a `_redirects` folder in your publish directory you can use the same file in Cloudflare Pages and your redirects will work the same. If your redirects are in your `netlify.toml`
```suggestion
If your site includes a `_redirects` file in your publish directory you can use the same file in Cloudflare Pages and your redirects will work the same. If your redirects are in your `netlify.toml` file you will have to add them to the `_redirects` folder. Cloudflare Pages currently offers limited [supports for advanced redirects](https://developers.cloudflare.com/pages/platform/redirects). In the case where you have redirects rules over 100, it is recommended to use [Bulk redirects](https://developers.cloudflare.com/rules/bulk-redirects/create-dashboard).
```

2022-02-23 02:18 UTC, WalshyDev requested changes

2022-02-23 02:18 UTC, WalshyDev commented on products/pages/src/content/migrations/migrating-from-netlify/index.md
> +Netlify functions and Pages Functions share the same filesystem convention using a `Functions` directory in the base of your project to handle your serverless functions the file can be stored directl
```suggestion
Netlify functions and Pages Functions share the same filesystem convention using a `functions` directory in the base of your project to handle your serverless functions the file can be stored directly under the functions directory or in a subdirectory dedicated to the function. However, the syntax and how the functions are deployed defers. Your Netlify Edge handlers can be regular Pages Functions because Pages Functions under the hood are Cloudflare Workers and they by default run on the Edge. 
```

2022-02-23 02:18 UTC, WalshyDev commented on products/pages/src/content/migrations/migrating-from-netlify/index.md
> +<Aside type='note'>
```suggestion
<Aside type="note">
```

2022-02-23 02:18 UTC, WalshyDev commented on products/pages/src/content/how-to/www-redirect.md
> +</Aside>
```suggestion
<Aside type="note">

It is recommended to use [Bulk Redirects](https://developers.cloudflare.com/pages/how-to/use-bulk-redirects.md) instead of Page Rules for redirecting domains. However, using Pages Rules will work as expected.

</Aside>
```

2022-02-23 02:18 UTC, WalshyDev commented on products/pages/src/content/migrations/migrating-from-netlify/index.md
> +Netlify functions export an async event handler that accepts and event and a context as arguments. In the case of a Pages Functions you will have to export a single `OnRequest` function that accepts
```suggestion
Netlify functions export an async event handler that accepts an event and a context as arguments. In the case of Pages Functions, you will have to export a single `onRequest` function that accepts a `context` object which contains all the information for the request such as request, env, params, and returns a new Response. You can learn more about [writing your first function](https://developers.cloudflare.com/pages/platform/functions#writing-your-first-function)
```

2022-02-23 02:18 UTC, WalshyDev commented on products/pages/src/content/migrations/migrating-from-netlify/index.md
> +exports.handler = async function (event, context) {
Which method is this accepting? The Pages function should reflect that

2022-02-23 02:18 UTC, WalshyDev commented on products/pages/src/content/migrations/migrating-from-netlify/index.md
> +  return new Response(`Hello world`);
Keep consistent with the Netlify example
```suggestion
  return new Response(JSON.stringify({ message: "Hello world" }), { headers: { 'Content-Type': 'application/json' } });
```

2022-02-23 02:24 UTC, Ekwuno commented on products/pages/src/content/migrations/migrating-from-netlify/index.md
> +  return new Response(`Hello world`);
I feel like this can get a lot more complicated with adding the header. There is a link to Pages Functions docs the code block is to show similarities.

2022-02-23 02:30 UTC, Ekwuno commented on products/pages/src/content/migrations/migrating-from-netlify/index.md
> +exports.handler = async function (event, context) {
The event object contains responses like body, header, HTTP method

2022-02-23 03:07 UTC, WalshyDev commented on products/pages/src/content/migrations/migrating-from-netlify/index.md
> +  return new Response(`Hello world`);
Yeah, fair, stringifying would still be good though I think. I'll edit my suggestion

2022-02-23 13:59 UTC, deadlypants1973 commented on products/pages/src/content/migrations/migrating-from-netlify/index.md
> +## Migrating Redirects and Headers
```suggestion
## Migrating redirects and headers
```

2022-02-23 14:05 UTC, deadlypants1973 commented on products/pages/src/content/migrations/migrating-from-netlify/index.md
> +Netlify functions and Pages Functions share the same filesystem convention using a `Functions` directory in the base of your project to handle your serverless functions the file can be stored directl
Editted Walshy's suggestion and added PCX fix to it for easy merge.

2022-02-23 14:10 UTC, deadlypants1973 commented on products/pages/src/content/migrations/migrating-from-netlify/index.md
> +Netlify function Hello world:
```suggestion
Netlify Hello World function:
```

2022-02-23 14:11 UTC, deadlypants1973 commented on products/pages/src/content/migrations/migrating-from-netlify/index.md
> +Pages Functions Hello world:
```suggestion
Hello World with Pages Functions:
```

2022-02-23 14:12 UTC, deadlypants1973 commented on products/pages/src/content/migrations/migrating-from-netlify/index.md
> +Netlify function Hello world:
```suggestion
Hello World with Netlify functions:
```

2022-03-02 17:14 UTC, Ekwuno commented
Closing this, will open a new PR.

2022-03-02 17:14 UTC, closed without merging