Update note for new URL implementation, add URLPattern docs
cloudflare/cloudflare-docs pull request #3661
Opened 2022-03-01 20:07 UTC by jasnell

The new URL landed a few weeks ago, URLPattern is in the release this week.

2022-03-01 20:13 UTC, lukeed requested changes

2022-03-01 20:13 UTC, lukeed commented on content/workers/runtime-apis/web-standards.md
> +If you would like to use another URL implementation, you can [shim the URL class using webpack](/cli-wrangler/webpack/#shimming-globals).
Links now require the product's URL segment to construct a _full_ absolute path. Old engine was replaced

```suggestion
If you would like to use another URL implementation, you can [shim the URL class using webpack](/workers/cli-wrangler/webpack/#shimming-globals).
```

2022-03-01 20:13 UTC, lukeed approved these changes

2022-03-03 16:08 UTC, deadlypants1973 approved these changes

2022-03-03 16:08 UTC, deadlypants1973 commented on content/workers/runtime-apis/web-standards.md
> +[Refer to the MDN documentation for more information](https://developer.mozilla.org/en-US/docs/Web/API/URLPattern)
```suggestion
[Refer to the MDN documentation for more information](https://developer.mozilla.org/en-US/docs/Web/API/URLPattern).
```

2022-03-03 16:10 UTC, merged