Added questions about Logpush V1/V2 and reformatted FAQs.
cloudflare/cloudflare-docs pull request #3675
Opened 2022-03-02 16:14 UTC by angelampcosta

2022-03-02 18:10 UTC, soheiokamoto commented on content/logs/faq/logpush.md
> +You   cannot   use   the   Logpush   UI   for   creating   v2   jobs – the   API   must   be used.   However,   once   a   job   is   created,   it   will   show   up   in   the   UI   and   can   be
Aside from strange spacing here, this statement doesn't seem correct.
All new jobs created are Logpush v2, either created via UI or directly with API.
Also, `logstream` flag have been somewhat internal, shared with certain customers, but we are planning to switch to `version` or some thing like that soon. Not sure if we want to add this to public docs right now.
CC @tanushreesharma-cf

2022-03-03 10:43 UTC, angelampcosta commented on content/logs/faq/logpush.md
> +You   cannot   use   the   Logpush   UI   for   creating   v2   jobs – the   API   must   be used.   However,   once   a   job   is   created,   it   will   show   up   in   the   UI   and   can   be
Perhaps we should not add the question "How can I update my logpush job from v1 to v2?" to the FAQs for now and only add it when we switch to `version`. What do you think @soheiokamoto @tanushreesharma-cf?

2022-03-03 15:00 UTC, tanushreesharma-cf requested changes

2022-03-03 15:00 UTC, tanushree-sharma commented on content/logs/faq/_index.md
> +## Logpush
The links to the sections don't seem to be working for me

2022-03-03 15:00 UTC, tanushree-sharma commented on content/logs/faq/logpush.md
> +You   cannot   use   the   Logpush   UI   for   creating   v2   jobs – the   API   must   be used.   However,   once   a   job   is   created,   it   will   show   up   in   the   UI   and   can   be
Maybe something is wrong with the way I deployed the branch but I don't see the "How can I check my Logpush job version" and "How can I update my Logpush job from v1 to v2" on there. 

My thoughts based on the text though:
- Yeah, Logpush jobs by default are v2 and the upgrade can only be done using the API
- Hmm, I think you're right Sohei. We should hold off on this until we switch to the new identifier

@angelampcosta For now, lets get this content switched over to a google doc to share out when questions come up instead of posting publicly.

2022-03-03 16:43 UTC, angelampcosta commented on content/logs/faq/logpush.md
> +You   cannot   use   the   Logpush   UI   for   creating   v2   jobs – the   API   must   be used.   However,   once   a   job   is   created,   it   will   show   up   in   the   UI   and   can   be
@soheiokamoto @tanushreesharma-cf I removed that question and will move it to a google doc. 
Is it ok to leave "How can I check my Logpush job version" or is there anything there that we also don't want to share?

2022-03-03 17:16 UTC, angelampcosta commented on content/logs/faq/_index.md
> +## Logpush
They are working in my local build. Could you try again?

2022-03-04 10:30 UTC, angelampcosta commented on content/logs/faq/_index.md
> +## Logpush
Did you check the preview link https://5f04e9e2.cloudflare-docs-7ou.pages.dev/logs/faq/?

2022-03-04 12:12 UTC, deadlypants1973 approved these changes

2022-03-04 12:12 UTC, deadlypants1973 commented on content/logs/faq/_index.md
> +layout: list
Double checking that weight 130 and layout list is correct.

2022-03-04 12:12 UTC, deadlypants1973 commented on content/logs/faq/_index.md
> +Below you will find answers to the most commonly asked questions regarding Cloudflare Logs. If you cannot find the answer you are looking for, feel free to head over to our [community page](https://c
```suggestion
Below you will find answers to the most commonly asked questions regarding Cloudflare Logs. If you cannot find the answer you are looking for, go to the [community page](https://community.cloudflare.com/) and post your question there.
```

Removing colloquial speech.

2022-03-04 12:12 UTC, deadlypants1973 commented on content/logs/faq/common-calculations.md
> +The best way to calculate bytes served by the origin is to use the `CacheResponseBytes` field in Cloudflare Logs, and to filter only requests that come from origin. Make sure to filter out `OriginRes
```suggestion
The best way to calculate bytes served by the origin is to use the `CacheResponseBytes` field in Cloudflare Logs, and to filter only requests that come from the origin. Make sure to filter out `OriginResponseStatus` values `0` and `304`, which indicate a revalidated response.
```

2022-03-04 12:12 UTC, deadlypants1973 commented on content/logs/faq/common-calculations.md
> +Bandwidth (or data transfer) can be calculated by adding the `EdgeResponseBytes` field in HTTP request logs. There are some types of requests that are not factored into bandwidth calculations. In ord
```suggestion
Bandwidth (or data transfer) can be calculated by adding the `EdgeResponseBytes` field in HTTP request logs. There are some types of requests that are not factored into bandwidth calculations. In order to only include relevant requests in calculations, add the filter `ClientRequestSource = 'eyeball'`.
```

2022-03-04 12:12 UTC, deadlypants1973 commented on content/logs/faq/general-faq.md
> +When using **Logpush**, logs are pushed in batches as soon as possible. For example, if you receive a file at 10:10, the file consists of logs that were processed shortly before 10:10.
```suggestion
When using **Logpush**, logs are pushed in batches as soon as possible. For example, if you receive a file at 10:10, the file consists of logs that were processed before 10:10.
```

2022-03-04 12:12 UTC, deadlypants1973 commented on content/logs/faq/general-faq.md
> +When using **Logpull**, logs become available in approximately one to five minutes. Cloudflare requires that calls to the **Logpull API** to be for time periods of at least one minute in the past. Fo
```suggestion
When using **Logpull**, logs become available in approximately one to five minutes. Cloudflare requires that calls to the **Logpull API** to be for time periods of at least one minute in the past. For example, if it is 9:43 now, you can ask for logs processed between 9:41 and 9:42. The response will include logs for requests that passed through our network between 9:41 and 9:42 and potentially earlier. It is normal for Cloudflare's processing to take between three and four minutes, so when you ask for that same time period, you may also see logs of requests that passed through our network at 9:39 or earlier.
```

2022-03-04 12:12 UTC, deadlypants1973 commented on content/logs/faq/general-faq.md
> +Not at this time. Talk to your account manager or Cloudflare Support if you are interested in other formats and we will consider them for the future.
```suggestion
Not at this time. Talk to your Cloudflare account team or [Cloudflare Support](https://support.cloudflare.com/hc/en-us/articles/200172476-Contacting-Cloudflare-Support) if you are interested in other formats and we will consider them for the future.
```

2022-03-04 12:12 UTC, deadlypants1973 commented on content/logs/faq/logpush.md
> +* The certificate for Splunk Server is not properly configured. Certificates generated by Splunk/third-party certificates should have the **Common Name** field in the certificate match the Splunk ser
```suggestion
* The certificate for Splunk Server is not properly configured. Certificates generated by Splunk/third-party certificates should have the **Common Name** field in the certificate match the Splunk server’s domain name. Otherwise, you may see errors like: `x509: certificate is valid for SplunkServerDefaultCert, not <YOUR_INSTANCE>.splunkcloud.com.`
```

2022-03-04 12:12 UTC, deadlypants1973 commented on content/logs/faq/logpush.md
> +Yes. See [Cloudflare App for Splunk](https://splunkbase.splunk.com/app/4501/) for more information. As long as you ingest logs using the `cloudflare:json` source type, you can use the Cloudflare Splu
```suggestion
Yes. Refer to [Cloudflare App for Splunk](https://splunkbase.splunk.com/app/4501/) for more information. As long as you ingest logs using the `cloudflare:json` source type, you can use the Cloudflare Splunk App.
```

Per style guide.

2022-03-04 15:25 UTC, tanushreesharma-cf commented
New format for the FAQ looks awesome! 

We'll likely change the way we check the Logpush version as well within the next couple months so lets hold off on adding this to the public docs until then.

2022-03-04 15:54 UTC, tanushreesharma-cf commented on content/logs/faq/_index.md
> +For questions about commons calculations.
@angelampcosta small typo here. Should be common calculations.

2022-03-04 15:58 UTC, angelampcosta commented on content/logs/faq/_index.md
> +For questions about commons calculations.
Fixed it.

2022-03-07 16:05 UTC, tanushreesharma-cf approved these changes

2022-03-07 16:56 UTC, merged