Coveo search
cloudflare/cloudflare-docs pull request #3681
Opened 2022-03-02 19:37 UTC by eidam

2022-03-03 18:39 UTC, lukeed commented
Deploy Preview is here: https://c8b02ea7.cloudflare-docs-7ou.pages.dev/
(Pages build finished before PR was opened, hence no bot comment)

2022-03-03 18:42 UTC, eidam commented
sorry, forgot to mention this is still WIP - waiting for UAT results, but any upcoming changes would be styles only - so feel free to review the rest

2022-03-03 18:43 UTC, lukeed requested changes
The integration code is fine, but I have a few UX problems with Coveo that I personally consider this to be a blocker:

1. The search results are absolutely awful. the current production site's results are useful & even offer sub-section result matches. These Coveo results can't even find entire pages.
2. The search input isn't interactive. This is a major let-down & loss compared to what we have. 
3. The JS library loaded on every page is 200+ kB & it can't possibly be doing anything since there's no interactivity or anything... Pressing <kbd>ENTER</kbd> is effectively a redirect to `/search/#q=KEYWORDS` – why is this script needed?

---

And not necessarily blockers, but:

1. Searching should pre-check the `Developer docs` results filter. Users are coming from documentation & tying to search within the documentation, so this is a safe assumption to make
2. The `Developer docs` label should be renamed to `Documentation`
3. Clicking a `Documentation` result link **should not be hardcoded** to the `developers.cloudflare.com` hostname. I recognize this may not be possible, but it's also a loss as it means reviews can go from a preview deployment (`[hash].cloudflare-docs.pages.dev`) to the production site without realizing

2022-03-03 19:25 UTC, kodster28 commented
Hey @lukeed, a couple responses to your comments.

Blockers:
1. Once we get in https://jira.cfops.it/browse/WDC-508, I think that'll address some of your concern, as well as non-blocker #1. We can key off your search context to promote that info more heavily. As to the other piece... we're trying to intentionally stay a more unopinionated during the initial rollout so we can get more accurate data to feed Coveo's built-in M/L models. Once those start kicking in, they should help tailor the results. I know that isn't a super satisfying answer, but we should be able to fast-follow to make the results significantly better. The other benefit -- probably bigger for other doc areas than for workers -- is that the new search allows us to pull in content from the Learning Center, Blog, and KB.
2. (also relates to 3) There's no interactivity at the moment of searching b/c we don't have enough data to safely populate their query suggestion M/L model. It basically auto-fills with suggested queries based on past user inputs. We actually went live w/ that functionality in the KB and... uh... basically folks started hammering our search with inappropriate phrases to the point that it was auto-completing phrases like `sexy videos` and others. Again, understand that it isn't super satisfying, but it should get corrected soonish (we also have some logic to try and avoid getting NSFW queries put into our data in the first place)
3. The JS library is used for the query suggestion component. So it's not technically necessary now... but it's what pre-populates search queries.

Non-blockers:
1. Valid point. I'd prefer the slightly softer approach of weighting dev doc content a bit heavier (instead of just excluding everything else). Might just be a personal preference... but I can envision folks not realizing that a filter was pre-selected and getting frustrated.
2. We can definitely change it. At this point, we sorta have to standardize that verbiage across the other domains, so it might require a bit of communication to do so.
3. Can't really speak to the tech side, but definitely a valid point.

2022-03-03 19:39 UTC, lukeed commented
Thanks @kodster28 

Until that ticket lands, I don't think this can be merged or even reviewed fairly. The search experience is so degraded right now that it dramatically impairs the entire devdocs experience. Adding in a few results from other Cloudflare properties in no way justifies losing the ability to search – accurately and/or at all – our ~1600 documentation pages.

Without good search, content remains hidden unless & until a user takes the time to painstakingly comb through our sidebars & keep the content organization/ladder memorized for future visits.

2022-03-03 19:47 UTC, lukeed commented
Did something change in the last hour? Previously I had 4 DevDocs results when searching for "logging workers" and none of them were the [Logging from Workers](https://developers.cloudflare.com/workers/learning/logging-workers/) page I was looking for. (similar experience with `ab test` and other terms.) Now there are 28 and the desired page is the 1st result

2022-03-03 19:50 UTC, kodster28 commented
Ah.... so I think the change in sitemaps may have basically excluded dev docs from our index. I changed that earlier in the day, but maybe it's something to do with caching?

2022-03-03 19:58 UTC, kodster28 commented
Actually, @lukeed, do you know why those changes would've just appeared now? Just wondering b/c I looked back and the re-indexing took place ~4 hours ago... but then didn't appear in your testing.

That would be a potential concern for pushing live.

2022-03-03 20:15 UTC, lukeed commented
I noticed the poor results yesterday & verified they were still occurring when I left my review today. Nothing different on my end & it was always same search terms /shrug

Do you have the updated sitemap? Not sure what you need from me.

Also, since the dropdown will come in a later iteration, can we move the Coveo JS out of this PR? 
Using this [example production page](https://developers.cloudflare.com/workers/learning/logging-workers/), there is:

* a total of 308kB total transferred
* where 58.4kB of that is JS 
* and 20kB is CSS.

The same page with [this Coveo PR](https://c8b02ea7.cloudflare-docs-7ou.pages.dev/workers/learning/logging-workers/) bumps it up to:

* **555 kB** total transfer
* **241 kB** of JS 
* **71 kB** of CSS

I know this is my personal quest, but I find this concerning... 4x'ing our JS & 3.5X'ing our CSS for what's effectively a redirect. I know it's prep-work for future dropdown, but this is a massive (performance) price to pay for what's essentially some keyboard listeners, an HTTP call, and some DOM updates.

2022-03-03 20:19 UTC, lukeed commented
The Lighthouse performance score for the live/production `Logging from Workers` page is **98**

The score for the same page in the Coveo version is **74** — this will extend to **all** Dev Doc pages

IMO this verifies my concern w/ their SDK files

<img width="500" alt="Screen Shot 2022-03-03 at 12 18 39 PM" src="https://user-images.githubusercontent.com/5855893/156646106-07313ee1-75ba-4a0d-bd81-e787f600fdd3.png">

<img width="500" alt="Screen Shot 2022-03-03 at 12 18 29 PM" src="https://user-images.githubusercontent.com/5855893/156646098-1e360be2-d69c-446b-a6ab-34a4374fd39f.png">

2022-03-03 20:33 UTC, kodster28 commented
I think that's a valid concern on the script and -- since we aren't rolling it out yet -- it seems like it'd make sense to keep it off.

We can also add that (and potentially you or another dev advocate) to our next meeting with them to pass along that feedback.

2022-03-03 20:37 UTC, codewithkristian commented
> Also, since the dropdown will come in a later iteration, can we move the Coveo JS out of this PR?

Agreed on this -- since we aren't using any live functionality on most pages, I think we should remove any JS we can at the moment, and just have it redirect to that query page when someone types in a search query.

In the future, we'll obviously want to include dropdown and proper "on-page" search functionality. At that point, we should investigate if there's optimizations we can do in order to lessen the performance implications on each page across the docs. That work could probably also benefit other CF properties (MRK, support, etc.) as well, so it's definitely worth doing.

@eidam -- can you update the PR accordingly with @lukeed's suggested change? To meet our deadlines, we still want to move on this PR ASAP; I agree with @kodster28's point that any issues we may have with functionality should probably be brought up in a future group meeting for the project.

2022-03-03 20:43 UTC, lukeed commented
I've added the necessary changes to defer the new script. Will remeasure the lighthouse impact after build completes.

From there, if it's still significant, I will remove the SDK files entirely & replace with a redirect for the time being until dropdown-version is ready. 

I don't know who Coveo is or where they came from, but since this is here to stay, I'd **much rather not** use their SDK files _at all_ and apply equivalent functionality here at 1/20th the cost.

2022-03-03 20:45 UTC, lukeed commented
<img width="753" alt="Screen Shot 2022-03-03 at 12 44 50 PM" src="https://user-images.githubusercontent.com/5855893/156649926-9ceb9722-1d66-4d23-a321-3cba45cb07db.png">

2022-03-03 21:13 UTC, lukeed commented
In my last commit, I removed Coveo SDK files everywhere except the `/search/` page. Instead, all other pages' search input will redirect to the `/search/` page (which was already the behavior).

And I pre-selected the `Developer Docs` filter, because that makes the most sense & feels the best to me. (Easy to remove)

Will reply with the updated Lighthouse score, but it **should be** a `98` for all pages _except_ the `/search/` page, which should be a `81` now (see previous comment)

2022-03-03 21:16 UTC, kodster28 commented
This is **super** late notice, so apologies, but we should delay the pushing this live until at least Monday.

Saying that not b/c there's any issues I'm seeing with the code ... but b/c I'm actually moving up to Colorado tomorrow and just found out that my phone isn't eligible to enroll in Okta for access to GChat or gmail. Was really not anticipating that second part :(.

Talking with Jenna, she thinks we should push it back to Monday since I won't be available in case we run into any issues. I wouldn't _think_ we would... but like if something weird happened with the Dev Docs source in pipeline like it did yesterday/today or something else unanticipated, it wouldn't be the best.

2022-03-03 21:20 UTC, lukeed commented
<img width="762" alt="Screen Shot 2022-03-03 at 1 19 09 PM" src="https://user-images.githubusercontent.com/5855893/156654561-2b44523f-5f76-4a39-8a37-f3f1930640b1.png">

> Source: https://cea3ac07.cloudflare-docs-7ou.pages.dev/workers/learning/logging-workers/

It got better because we dropped the ~45kB of JS for the old search too :)

2022-03-07 13:58 UTC, kodster28 commented
Hey @lukeed or @eidam, before launching this, can we actually remove `Developer docs` as a pre-selected filter?

I agree that it does make sense in the Workers and Pages docs... but there's a lot of other areas where we aren't as... let's say _thorough_ in our documentation. We still have some pretty glaring holes for SSL, Speed features, etc. for example.

It'll actually be incredibly helpful to see when and for what documents folks are leaving dev docs and going to blog, community, and KB. That way, we can identify gaps in our content and prioritize fixes.

2022-03-07 17:54 UTC, lukeed commented on assets/search.redirect.ts
> +        redirect += '&f:source=[Developer%20docs]';
```suggestion
        // redirect += '&f:source=[Developer%20docs]';
```

2022-03-08 16:25 UTC, kodster28 commented
Oh, also... as a note, if the unfiltered view gets too annoying from a Pages/Workers perspective, we can do some fancy stuff for those docs specifically once we implement https://jira.cfops.it/browse/WDC-508

2022-03-08 17:03 UTC, kodster28 requested changes
Before pushing this live, we'll want to test out the Production pipeline and verify that everything looks correct.

Other than that, approved from a PCX perspective (with post-MVP tasks noted in https://jira.cfops.it/browse/WDC-508 and https://jira.cfops.it/browse/WDC-531).

2022-03-08 17:22 UTC, kristianfreeman approved these changes
Next steps: @eidam and @kodster28 to update this with production pipeline details tomorrow (3/9) for further testing, and merge later this week.

+1 from an eng perspective on our side

2022-03-09 11:49 UTC, eidam commented
@kodster28 config switched to production one

2022-03-09 15:56 UTC, kodster28 reviewed
Approved from a PCX perspective and Coveo analytics perspective.

However, we don't yet have the green light from the higher ups... so we can't push this live quite yet :(.

2022-03-11 18:03 UTC, kodster28 approved these changes
Got steerco approval. Ready to go when y'all are!
(will let an actual developer hit the merge button though)

2022-03-11 18:05 UTC, lukeed approved these changes

2022-03-11 18:06 UTC, merged