How to Refactor worker to pages function
cloudflare/cloudflare-docs pull request #3744
Opened 2022-03-08 00:41 UTC by Ekwuno

2022-03-08 01:06 UTC, lukeed commented on content/pages/how-to/refactor-a-worker-to-pages-functions.md
> +However, when you handle things like forms submissions or want to ship a small piece of logic that is unique to your project. The logic can live in the same file system as your project while running
These should be absolute paths, not fully qualified URLs.

```suggestion
However, when you handle things like forms submissions or want to ship a small piece of logic that is unique to your project. The logic can live in the same file system as your project while running on Cloudflare's edge network. You can now use [Pages Functions](/pages/platform/functions/).
```

2022-03-08 01:07 UTC, lukeed commented on content/pages/how-to/refactor-a-worker-to-pages-functions.md
> +However, when you handle things like forms submissions or want to ship a small piece of logic that is unique to your project. The logic can live in the same file system as your project while running
Here are all the instances in this document: https://github.com/cloudflare/cloudflare-docs/runs/5457778345?check_suite_focus=true#step:8:14

2022-03-09 09:57 UTC, deadlypants1973 requested changes
First review

2022-03-09 09:57 UTC, deadlypants1973 commented on content/pages/how-to/refactor-a-worker-to-pages-functions.md
> +# Refactor a Worker to a Pages Function.
```suggestion
# Refactor a Worker to a Pages Function
```

2022-03-09 09:57 UTC, deadlypants1973 commented on content/pages/how-to/refactor-a-worker-to-pages-functions.md
> +When building with Workers there is the option of running your worker separately from your application. A good usecase for this is if the logic in your worker is used by more than one application.
```suggestion
When building with Workers, you may want to run your Worker separately from your application if the logic in your Worker is used by more than one application. 
```

2022-03-09 09:57 UTC, deadlypants1973 commented on content/pages/how-to/refactor-a-worker-to-pages-functions.md
> +However, when you handle things like forms submissions or want to ship a small piece of logic that is unique to your project. The logic can live in the same file system as your project while running
@Ekwuno I don't think the first sentence isn't a full sentence, can you please review this paragraph again?

2022-03-09 09:57 UTC, deadlypants1973 commented on content/pages/how-to/refactor-a-worker-to-pages-functions.md
> +
@Ekwuno There needs to be a sentence here that tells the user what this how to is for. "In this guide, you will..." Because this is missing right now, the point of the this guide is missing.

2022-03-09 09:57 UTC, deadlypants1973 commented on content/pages/how-to/refactor-a-worker-to-pages-functions.md
> +[Airtable](https://airtable.com/) can be used to store entires of information in different tables for the same account, which makes it a good usecase for handling specific forms for differnt projects
@Ekwuno this needs more context.

This paragraph should:
1) Define Airtable.
2) Define Pages Functions.
3) Define how they work together.

2022-03-09 09:57 UTC, deadlypants1973 commented on content/pages/how-to/refactor-a-worker-to-pages-functions.md
> +In the Airtable code below, you have a `submitHandler` async function that can be reached if the pathname of the work is `/submit`. This function checks that the request method is a `POST` request an
@Ekwuno there are three different concepts here: Workers, Pages Functions and Airtable - and none of them have been connected so far.

2022-03-09 09:57 UTC, deadlypants1973 commented on content/pages/how-to/refactor-a-worker-to-pages-functions.md
> +For example, an airtable function that handles a form submission will have the default worker response to a `fetch` action that responsed to a `request` with a handler.
Is an 'airtable function' a Worker that the user made?

2022-03-09 11:25 UTC, Ekwuno commented on content/pages/how-to/refactor-a-worker-to-pages-functions.md
> +In the Airtable code below, you have a `submitHandler` async function that can be reached if the pathname of the work is `/submit`. This function checks that the request method is a `POST` request an
@deadlypants1973 I see. I will rephrase this paragraph to focus more on Airtable and the Worker.

2022-03-09 19:26 UTC, lukeed commented on content/pages/how-to/refactor-a-worker-to-pages-functions.md
> +The above code takes a `request` and `env` as argumnents which passes this props down to the `submitHandler` fucntion. Which stays the same as the original Worker function. However, becasue Functions
```suggestion
The above code takes a `request` and `env` as argumnents which passes this props down to the `submitHandler` function. Which stays the same as the original Worker function. However, becasue Functions allow you to specify the HTTPS request type you can remove the `request.method` check, as this is handled by naming the request type. 
```

2022-03-09 19:26 UTC, lukeed commented on content/pages/how-to/refactor-a-worker-to-pages-functions.md
> +The above code takes a `request` and `env` as argumnents which passes this props down to the `submitHandler` fucntion. Which stays the same as the original Worker function. However, becasue Functions
```suggestion
The above code takes a `request` and `env` as arguments which passes this props down to the `submitHandler` fucntion. Which stays the same as the original Worker function. However, becasue Functions allow you to specify the HTTPS request type you can remove the `request.method` check, as this is handled by naming the request type. 
```

2022-03-09 19:28 UTC, lukeed commented on content/pages/how-to/refactor-a-worker-to-pages-functions.md
> +The above code takes a `request` and `env` as argumnents which passes this props down to the `submitHandler` fucntion. Which stays the same as the original Worker function. However, becasue Functions
```suggestion
The above code takes a `request` and `env` as argumnents which passes this props down to the `submitHandler` fucntion, which remains unchanged from the original Worker. However, becasue Functions allow you to specify the HTTPS request type you can remove the `request.method` check, as this is handled by naming the request type. 
```

2022-03-09 19:28 UTC, lukeed commented on content/pages/how-to/refactor-a-worker-to-pages-functions.md
> +The above code takes a `request` and `env` as argumnents which passes this props down to the `submitHandler` fucntion. Which stays the same as the original Worker function. However, becasue Functions
```suggestion
The above code takes a `request` and `env` as argumnents which passes this props down to the `submitHandler` fucntion. Which stays the same as the original Worker function. However, because Functions allow you to specify the HTTPS request type you can remove the `request.method` check, as this is handled by naming the request type. 
```

2022-03-09 19:35 UTC, lukeed commented on content/pages/how-to/refactor-a-worker-to-pages-functions.md
> +  return new Response.redirect(FORM_URL);
The Worker would pass through to the origin, which is assumed to be the Pages app. This architecture/layout can be explained before the code, too. Also means the `FORM_URL` variable can be removed from the code & work for all users as presented

```suggestion
  return fetch(request.url);
```

2022-03-09 21:59 UTC, KunBuong approved these changes

2022-03-18 16:44 UTC, GregBrimble commented on content/pages/how-to/refactor-a-worker-to-pages-functions.md
> +title: Refactor a Worker to a Pages Function.
No other titles have full stops.

```suggestion
title: Refactor a Worker to a Pages Function
```

2022-03-18 16:46 UTC, GregBrimble commented on content/pages/how-to/refactor-a-worker-to-pages-functions.md
> +# Using a Pages Functions
```suggestion
# Using Pages Functions
```

2022-04-18 15:41 UTC, deadlypants1973 reviewed
PCX first review

2022-04-18 15:41 UTC, deadlypants1973 commented on content/pages/how-to/refactor-a-worker-to-pages-functions.md
> +In this guide, you will learn how to refactor a Worker to a Pages Function that can be hosted with your application on Cloudflare Pages. You may want to do this if you handle some logic that your app
```suggestion
In this guide, you will learn how to refactor a Worker to a Pages Function that can be hosted with your application on Cloudflare Pages. You may want to do this if you manage a serverless function that your application depends on and wish to ship the logic without managing a Worker as a separate service.
```

2022-04-18 15:41 UTC, deadlypants1973 commented on content/pages/how-to/refactor-a-worker-to-pages-functions.md
> +An example of a functionality that can be handled by a Worker but can also be a good usecase for Pages Functions is a simple form. This is because, forms are most times specific to a particular appli
```suggestion
An example of a functionality that can be handled by a Worker but can also be a good use case for Pages Functions is a simple form. This is because forms are most times specific to a particular application. 
```

2022-04-18 15:41 UTC, deadlypants1973 commented on content/pages/how-to/refactor-a-worker-to-pages-functions.md
> +Assuming you are already using a Worker for this, you would have deployed this Worker and then pointed your form action to the URL of the Worker. When you change how Worker handles your submissions,
```suggestion
Assuming you are already using a Worker to handle your form, you would have deployed this Worker and then pointed your form action to the URL of the Worker. When you change how the Worker handles your submissions, you do so separately from your client. If the logic in your Worker is used by more than one application, it makes sense to leave it this way.  
```

2022-04-18 15:41 UTC, deadlypants1973 commented on content/pages/how-to/refactor-a-worker-to-pages-functions.md
> +However, it can be beneficial to use a [Pages Function](/pages/platform/functions/), which is a serverless function that lives within the same filesystem as your application and is deployed with your
```suggestion
However, it can be beneficial to use a [Pages Function](/pages/platform/functions/), which is a serverless function that lives within the same filesystem as your application and is deployed with Cloudflare Pages. Building your application this way can help you manage your client and serverless logic from the same place and make it easier to use and debug your code. 
```

2022-04-18 15:41 UTC, deadlypants1973 commented on content/pages/how-to/refactor-a-worker-to-pages-functions.md
> + An [Airtable](https://airtable.com/) is a low-code platform for building collaborative apps. It helps customize your workflow, collaborate, handle form submissions and achieve ambitious outcomes. Fo
```suggestion
 An [Airtable](https://airtable.com/) is a low-code platform for building collaborative applications. It helps customize your workflow, collaborate, and handle form submissions. For this example, you will utilize Airtable's form submission feature.
```

2022-04-18 15:41 UTC, deadlypants1973 commented on content/pages/how-to/refactor-a-worker-to-pages-functions.md
> +[Airtables](https://airtable.com/) can be used to store entries of information in different tables for the same account. When creating a Worker for handling the submission logic, the first step is to
```suggestion
[Airtables](https://airtable.com/) can be used to store entries of information in different tables for the same account. When creating a Worker for handling the submission logic, the first step is to use [Wrangler](/workers/cli-wrangler/install-update/) to initialize a new Worker within a specific folder or at the root of your application. 
```

2022-04-18 15:41 UTC, deadlypants1973 commented on content/pages/how-to/refactor-a-worker-to-pages-functions.md
> +[Airtables](https://airtable.com/) can be used to store entries of information in different tables for the same account. When creating a Worker for handling the submission logic, the first step is to
Are you asking the user to run a Wrangler command here? If so, the command should be included?

2022-04-18 15:41 UTC, deadlypants1973 commented on content/pages/how-to/refactor-a-worker-to-pages-functions.md
> +This step creates the boilerplate to write your Airtable submission Worker. After writing your Worker, you can deploy it to Cloudflare's Edge network with your credentials. You can check the Workers
```suggestion
This step creates the boilerplate to write your Airtable submission Worker. After writing your Worker, you can deploy it to Cloudflare's edge network after you [configure your project for deployment](/workers/get-started/guide/#7-configure-your-project-for-deployment). Review the Workers documentation for a full tutorial on how to [handle form submission with Workers](/workers/tutorials/handle-form-submissions-with-airtable/).
```

2022-04-18 15:41 UTC, deadlypants1973 commented on content/pages/how-to/refactor-a-worker-to-pages-functions.md
> +Every Worker will have the default response to a `fetch` action with a `request` handler. Here you have a `submitHandler` async function that is called if the pathname of the work is `/submit`. This
```suggestion
Every Worker will have the default response to a `fetch` action with a `request` handler. In the example below, you have a `submitHandler` async function that is called if the pathname of the work is `/submit`. This function checks that the request method is a `POST` request and then proceeds to parse and post the form entries to Airtable using your credentials, which you can store using [wrangler secret](/workers/cli-wrangler/commands/#secret).
```

2022-04-18 15:41 UTC, deadlypants1973 commented on content/pages/how-to/refactor-a-worker-to-pages-functions.md
> +## Refactoring the worker
```suggestion
## Refactoring your Worker
```

2022-04-18 15:41 UTC, deadlypants1973 commented on content/pages/how-to/refactor-a-worker-to-pages-functions.md
> +[Pages Functions](/pages/platform/functions/) are serverless functions that run on Cloudflare Pages together with your application. They enable you to run server-side code to enable dynamic functiona
```suggestion
[Pages Functions](/pages/platform/functions/) are serverless functions that run on Cloudflare Pages together with your application. They enable you to run server-side code to enable dynamic functionality without running a dedicated server. While the above code works perfectly, you can handle the form submission logic for your client in the same application with Pages Functions.
```

2022-04-18 15:41 UTC, deadlypants1973 commented on content/pages/how-to/refactor-a-worker-to-pages-functions.md
> +Every Worker has an `addEventListener` to listen for fetch events, but you will not need this in a Pages Function. Instead, you will `export` a single `OnRequest` function, and depending on the HTTPS
```suggestion
Every Worker has an `addEventListener` to listen for `fetch` events, but you will not need this in a Pages Function. Instead, you will `export` a single `OnRequest` function, and depending on the HTTPS request it handles, you will name it accordingly.  
```

2022-04-18 15:41 UTC, deadlypants1973 commented on content/pages/how-to/refactor-a-worker-to-pages-functions.md
> +In the case of accepting form submissions and posting to an airtable you will export a single `OnRequestPost` function like so:
```suggestion
In the case of accepting form submissions and posting to an Airtable, you will export a single `OnRequestPost` function like the example below:
```

2022-04-18 15:41 UTC, deadlypants1973 commented on content/pages/how-to/refactor-a-worker-to-pages-functions.md
> +The code block above shows that we pass the `env` parameter as props so we can access it in the `HandleAirtableData` function below. This function does a `POST` request to Airtable using your Airtabl
```suggestion
The code block above shows that you pass the `env` parameter as props so we can access it in the `HandleAirtableData` function below. This function does a `POST` request to Airtable using your Airtable credentials.  
```

2022-04-18 15:41 UTC, deadlypants1973 commented on content/pages/how-to/refactor-a-worker-to-pages-functions.md
> +This step creates the boilerplate to write your Airtable submission Worker. After writing your Worker, you can deploy it to Cloudflare's Edge network with your credentials. You can check the Workers
Not sure if credentials meant Cloudflare credentials but I added a link to the configuration portion of the Workers guide to make it more clear.

2022-04-18 15:41 UTC, deadlypants1973 commented on content/pages/how-to/refactor-a-worker-to-pages-functions.md
> +
```suggestion
```

2022-04-18 15:41 UTC, deadlypants1973 commented on content/pages/how-to/refactor-a-worker-to-pages-functions.md
> +You can test your function [locally using wrangler 2](/pages/platform/functions/#develop-and-preview-locally).
```suggestion
You can test your function [locally using Wrangler 2](/pages/platform/functions/#develop-and-preview-locally).
```

2022-04-18 15:41 UTC, deadlypants1973 commented on content/pages/how-to/refactor-a-worker-to-pages-functions.md
> +3.Handle logic must be executed before or after route handles with middleware. Learn more about [using Middleware](/pages/platform/functions/#adding-middleware) in the Functions documentation.
```suggestion
3. Handle logic must be executed before or after route handles with middleware. Learn more about [using Middleware](/pages/platform/functions/#adding-middleware) in the Functions documentation.
```

2022-04-18 15:41 UTC, deadlypants1973 commented on content/pages/how-to/refactor-a-worker-to-pages-functions.md
> +2. Pass the `context` object as an argment to your new `OnRequest` method to access your `request`,`env`,`params` and `next`.
```suggestion
2. Pass the `context` object as an argument to your new `OnRequest` method to access your `request`,`env`,`params` and `next`.
```
Are `request`,`env`,`params` and `next` parameters? or props?

2022-04-19 00:07 UTC, Ekwuno commented on content/pages/how-to/refactor-a-worker-to-pages-functions.md
> +[Airtables](https://airtable.com/) can be used to store entries of information in different tables for the same account. When creating a Worker for handling the submission logic, the first step is to
No, I am describing the steps to using Wrangler to set up a Worker.

2022-04-19 08:30 UTC, Ekwuno commented on content/pages/how-to/refactor-a-worker-to-pages-functions.md
> +2. Pass the `context` object as an argment to your new `OnRequest` method to access your `request`,`env`,`params` and `next`.
I'd say they're parameters

2022-04-19 08:55 UTC, GregBrimble commented on content/pages/how-to/refactor-a-worker-to-pages-functions.md
> +2. Pass the `context` object as an argment to your new `OnRequest` method to access your `request`,`env`,`params` and `next`.
Nope, they're properties of the `context` parameter.

2022-04-19 10:16 UTC, Ekwuno commented on content/pages/how-to/refactor-a-worker-to-pages-functions.md
> +2. Pass the `context` object as an argment to your new `OnRequest` method to access your `request`,`env`,`params` and `next`.
Ah thanks!

2022-07-12 15:55 UTC, deadlypants1973 requested changes

2022-07-12 15:55 UTC, deadlypants1973 commented on content/pages/how-to/refactor-a-worker-to-pages-functions.md
> +2. If you are migrating your Worker to Pages Functions and want to leverage on the routing and middleware capabilities of Pages Functions.
```suggestion
In this guide, you will learn how to refactor a Worker to a Pages Function that can be hosted with your application on Cloudflare Pages. You may want to do this:

1. If you manage a serverless function that your Pages application depends on and wish to ship the logic without managing a Worker as a separate service.
2. If you are migrating your Worker to Pages Functions and want to use the routing and middleware capabilities of Pages Functions.
```

2022-07-12 15:55 UTC, deadlypants1973 commented on content/pages/how-to/refactor-a-worker-to-pages-functions.md
> +{{<Aside type= "note" header="Note">}}
```suggestion
{{<Aside type= "note">}}
```

2022-07-12 15:55 UTC, deadlypants1973 commented on content/pages/how-to/refactor-a-worker-to-pages-functions.md
> +You can import your Worker to a Pages project without using Functions by creating a `_worker.js` file in the in the output directory of your Pages project. This [Advanced mode](/pages/platform/functi
```suggestion
You can import your Worker to a Pages project without using Functions by creating a `_worker.js` file in the in the output directory of your Pages project. This [Advanced mode](/pages/platform/functions/#advanced-mode) requires writing your Worker with [Module syntax](/workers/learning/migrating-to-module-workers/). 
```

2022-07-12 15:55 UTC, deadlypants1973 commented on content/pages/how-to/refactor-a-worker-to-pages-functions.md
> +1. Remove the `addEventListener()` method and its event response and replace it with the appropriate `OnRequest` method. Refer to [Function documentation](/pages/platform/functions/#writing-your-firs
```suggestion
1. Remove the `addEventListener()` method and its event response and replace it with the appropriate `OnRequest` method. Refer to [Functions](/pages/platform/functions/#writing-your-first-function) to select the appropriate method for your Function.
```

2022-07-12 15:55 UTC, deadlypants1973 commented on content/pages/how-to/refactor-a-worker-to-pages-functions.md
> +However, it can be beneficial to use a [Pages Function](/pages/platform/functions/), which is a serverless function that lives within the same filesystem as your application and is deployed with Clou
```suggestion
However, it can be beneficial to use a [Pages Function](/pages/platform/functions/) when you would like to organize your function logic in the same project directory as your application.
```

2022-07-12 15:55 UTC, deadlypants1973 commented on content/pages/how-to/refactor-a-worker-to-pages-functions.md
> +In this guide, you will learn how to refactor a Worker to a Pages Function that can be hosted with your application on Cloudflare Pages. You may want to do this for one of these reasons:
```suggestion
In this guide, you will learn how to refactor a Worker made to intake form submissions to a Pages Function that can be hosted on your Cloudflare Pages application. [Pages Functions](/pages/platform/functions/) is a serverless function that lives within the same project directory as your application and is deployed with Cloudflare Pages. It enables you to run server-side code that adds dynamic functionality without running a dedicated server. You may want to refactor a Worker to a Pages Function for one of these reasons: 
```

2022-07-12 15:55 UTC, deadlypants1973 commented on content/pages/how-to/refactor-a-worker-to-pages-functions.md
> +Building your application this way, can help you manage your client and serverless logic from the same place and make it easier to use and debug your code.
```suggestion
Building your application using Pages Functions can help you manage your client and serverless logic from the same place and make it easier to write and debug your code. 
```

2022-07-12 15:55 UTC, deadlypants1973 commented on content/pages/how-to/refactor-a-worker-to-pages-functions.md
> +## Handling form entries with Airtable and Workers
```suggestion
## Handle form entries with Airtable and Workers
```

2022-07-12 15:55 UTC, deadlypants1973 commented on content/pages/how-to/refactor-a-worker-to-pages-functions.md
> +### Refactoring your Worker
```suggestion
### Refactor your Worker
```

2022-07-12 15:55 UTC, deadlypants1973 commented on content/pages/how-to/refactor-a-worker-to-pages-functions.md
> +
```suggestion
```

2022-07-12 15:55 UTC, deadlypants1973 commented on content/pages/how-to/refactor-a-worker-to-pages-functions.md
> +3. Handle logic that must be executed before or after route handles with middleware. Learn more about [using Middleware](/pages/platform/functions/#adding-middleware) in the Functions documentation.
```suggestion
3. Use middleware to handle logic that must be executed before or after route handlers. Learn more about [using Middleware](/pages/platform/functions/#adding-middleware) in the Functions documentation.
```

2022-07-12 15:55 UTC, deadlypants1973 commented on content/pages/how-to/refactor-a-worker-to-pages-functions.md
> +Assuming you are already using a Worker to handle your form, you would have deployed this Worker and then added the URL to your form action attribute in your HTML form. This means that when you chang
```suggestion
Assuming you are already using a Worker to handle your form, you would have deployed this Worker and then added the URL to your form action attribute in your HTML form. This means that when you change how the Worker handles your submissions, you must make changes to the Worker script. If the logic in your Worker is used by more than one application, Pages Functions would not be a good use case.
```

2022-07-12 15:55 UTC, deadlypants1973 commented on content/pages/how-to/refactor-a-worker-to-pages-functions.md
> +## Handle form submission example
```suggestion
## Background
```

2022-07-12 15:55 UTC, deadlypants1973 commented on content/pages/how-to/refactor-a-worker-to-pages-functions.md
> +Every Worker will have the default response to a `fetch` action with a `request` handler. In the example below, you have a `submitHandler` async function that is called if the pathname of the work is
```suggestion
Every Worker will have the default response to a `fetch` action with a `request` handler. The `submitHandler` async function is called if the pathname of the work is `/submit`. This function checks that the request method is a `POST` request and then proceeds to parse and post the form entries to Airtable using your credentials, which you can store using [Wrangler `secret`](/workers/wrangler/commands/#secret).
```

2022-07-12 15:55 UTC, deadlypants1973 commented on content/pages/how-to/refactor-a-worker-to-pages-functions.md
> +The code block below shows an example of a Worker that handles Airtable form submission.
```suggestion
The following code block shows an example of a Worker that handles Airtable form submission.
```

2022-07-12 15:55 UTC, deadlypants1973 commented on content/pages/how-to/refactor-a-worker-to-pages-functions.md
> +
```suggestion
```

2022-07-12 15:55 UTC, deadlypants1973 commented on content/pages/how-to/refactor-a-worker-to-pages-functions.md
> +In the case of accepting form submissions and posting to an Airtable, you will export a single `OnRequestPost` function like the example below:
```suggestion
To refactor the above Worker, go to your Pages project directory and create a `/functions` folder. In `/functions`, create a `form.js` file. This file will handle form submissions. 

Then, in the `form.js` file, export a single `onRequestPost`:
```

2022-07-12 15:55 UTC, deadlypants1973 commented on content/pages/how-to/refactor-a-worker-to-pages-functions.md
> +The above code takes a `request` and `env` as arguments which passes these props down to the `submitHandler` function, which remains unchanged from the original Worker. However, because Functions all
```suggestion
Every Worker has an `addEventListener` to listen for `fetch` events, but you will not need this in a Pages Function. Instead, you will `export` a single `onRequest` function, and depending on the HTTPS request it handles, you will name it accordingly. Refer to [Function documentation](/pages/platform/functions/#writing-your-first-function) to select the appropriate method for your function.

The above code takes a `request` and `env` as arguments which pass these properties down to the `submitHandler` function, which remains unchanged from the [original Worker](#handle-form-entries-with-airtable-and-workers). However, because Functions allow you to specify the HTTPS request type, you can remove the `request.method` check in your Worker. This is now handled by Pages Functions by naming the `onRequest` handler.

Now, you will introduce the `submitHandler` function and pass the `env` parameter as a property. This will allow you to access `env` in the `HandleAirtableData` function below. This function does a `POST` request to Airtable using your Airtable credentials:
```

2022-07-12 15:55 UTC, deadlypants1973 commented on content/pages/how-to/refactor-a-worker-to-pages-functions.md
> +The code block above shows that you pass the `env` parameter as props so we can access it in the `HandleAirtableData` function below. This function does a `POST` request to Airtable using your Airtab
```suggestion
Finally, create a `HandleAirtableData` function. This function will send a `fetch` request to Airtable with your Airtable credentials and the body of your request:
```

2022-07-12 15:55 UTC, deadlypants1973 commented on content/pages/how-to/refactor-a-worker-to-pages-functions.md
> +Now that you have seen Pages Functions in a production example. You can refer the [documentation](/pages/platform/functions/) to learn more. You can also check out these tutorials and documentaion fo
```suggestion
```

2022-07-12 15:55 UTC, deadlypants1973 commented on content/pages/how-to/refactor-a-worker-to-pages-functions.md
> +
```suggestion
```

2022-07-12 15:55 UTC, deadlypants1973 commented on content/pages/how-to/refactor-a-worker-to-pages-functions.md
> +You can test your function [locally using Wrangler](/pages/platform/functions/#develop-and-preview-locally).
```suggestion
You can test your Function [locally using Wrangler](/pages/platform/functions/#develop-and-preview-locally). By completing this guide, you have successfully refactored your form submission Worker to a form submission Pages Function.
```

2022-07-12 21:30 UTC, Ekwuno commented on content/pages/how-to/refactor-a-worker-to-pages-functions.md
> +In this guide, you will learn how to refactor a Worker to a Pages Function that can be hosted with your application on Cloudflare Pages. You may want to do this:
```suggestion
In this guide, you will learn how to refactor a Worker made to intake form submissions to a Pages Function that can be hosted on your Cloudflare Pages application. [Pages Functions](/pages/platform/functions/) is a serverless function that lives within the same project directory as your application and is deployed with Cloudflare Pages. It enables you to run server-side code that adds dynamic functionality without running a dedicated server. You may want to refactor a Worker to a Pages Function for one of these reasons: 
```

2022-07-13 13:25 UTC, deadlypants1973 approved these changes

2022-07-13 13:28 UTC, merged