Update linux.md
cloudflare/cloudflare-docs pull request #3835
Opened 2022-03-17 03:45 UTC by tenaciousdlg

Removed the wget method of installing cloudflared and instead pointed to the install docs which show how to install it via a package manager or a lower level package manager. Also added pre-requisite criteria before running the commands to install `cloudflared` as a service.

2022-04-15 21:20 UTC, abelinkinbio commented
This one looks good to me 👍 

cc: @abracchi-tw @ranbel

2022-04-15 21:42 UTC, ranbel requested changes

2022-04-15 21:42 UTC, ranbel commented on content/cloudflare-one/connections/connect-apps/run-tunnel/as-a-service/linux.md
> +Instructions on how to install `cloudflared` for Linux can be found [here](https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/install-and-setup/installation/#linux).
```suggestion
```

2022-04-15 21:42 UTC, ranbel commented on content/cloudflare-one/connections/connect-apps/run-tunnel/as-a-service/linux.md
> +Instructions on how to install `cloudflared` for Linux can be found [here](https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/install-and-setup/installation/#linux).
This is Step 1 in the link below.

2022-04-15 21:42 UTC, ranbel commented on content/cloudflare-one/connections/connect-apps/run-tunnel/as-a-service/linux.md
> +Follow up to step 4 [here](https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/install-and-setup/tunnel-guide/#4-create-a-configuration-file) then proceed with the following. At
```suggestion
Complete steps 1 through 4 in the [CLI setup guide](/cloudflare-one/connections/connect-apps/install-and-setup/tunnel-guide/). At this point `cloudflared` should be installed, authenticated, and have a `config.yml` file in the `.cloudflared` directory. 
```

2022-04-18 13:38 UTC, ranbel approved these changes

2022-04-18 13:39 UTC, merged