workers Response encodeBody property
cloudflare/cloudflare-docs pull request #384
Opened 2020-11-30 02:25 UTC by adaptive

closes #375 
new Response `encodeBody` property
src: https://stackoverflow.com/questions/64836479/accessing-compressed-data-for-cloudflare-workers-sites/64849685#64849685

2020-11-30 04:26 UTC, heathermercer197610 commented
let resp = await getAssetFromKV(event, { mapRequestToAsset, cacheControl });

// Make a new response with the same body but using manual encoding.
resp = new Response(resp.body, {
  status: resp.status,
  headers: resp.headers,
  encodeBody: "manual"
});

// Modify headers and return.
resp.headers.set("Content-Encoding", "gzip");
return resp;

2020-11-30 04:27 UTC, heathermercer197610 requested changes
let resp = await getAssetFromKV(event, { mapRequestToAsset, cacheControl });

// Make a new response with the same body but using manual encoding.
resp = new Response(resp.body, {
  status: resp.status,
  headers: resp.headers,
  encodeBody: "manual"
});

// Modify headers and return.
resp.headers.set("Content-Encoding", "gzip");
return resp;

2020-12-14 19:07 UTC, signalnerve approved these changes

2020-12-14 19:07 UTC, signalnerve commented
tyvm!

2020-12-14 19:07 UTC, merged