[Notifications] Added new SSL notifications
cloudflare/cloudflare-docs pull request #3918
Opened 2022-03-24 14:50 UTC by marciocloudflare

Also added H2 to organize by product.
Addresses [PCX-3377](https://jira.cfops.it/browse/PCX-3377)

2022-03-24 16:25 UTC, kodster28 commented
As part of this PR, could you also kill and redirect https://developers.cloudflare.com/ssl/notifications/?

2022-03-24 16:26 UTC, kodster28 requested changes
We need review from Dina on the expiring mTLS language before this should go live.

2022-03-24 16:26 UTC, kodster28 commented on content/fundamentals/notifications/notification-available.md
> +Upload a [renewed certificate](/ssl/ssl-for-saas/custom-certificates/).
```suggestion
Upload a [renewed certificate](/cloudflare-one/identity/devices/mutual-tls-authentication/#add-mtls-authentication-to-your-access-configuration).
```

2022-03-24 16:26 UTC, kodster28 commented on content/fundamentals/notifications/notification-available.md
> +Upload a [renewed certificate](/ssl/ssl-for-saas/custom-certificates/).
Might need to run this by Dina, but believe this should actually reference the client cert page (which is different from a custom cert) and then you would also I think need to update your access policy.

Have not done either... so just guessing based on some recent docs updates.

2022-03-24 16:26 UTC, kodster28 commented on content/fundamentals/notifications/notification-available.md
> +Action only needed if notification is about a certificate that failed to be issued. Refer to [SSL expired or SSL mismatch errors](https://support.cloudflare.com/hc/en-us/articles/200170566#h_c1a6e78e
```suggestion
Action only needed if notification is about a certificate that failed to be issued. Refer to [SSL expired or SSL mismatch errors](https://support.cloudflare.com/hc/articles/200170566#h_c1a6e78e-150d-4db6-89ab-eec7cb1ab03f) for more information.
```

2022-03-24 16:26 UTC, kodster28 commented on content/fundamentals/notifications/notification-available.md
> +Customers that upload their own certificate to use with zone-level AOP to secure connections from Cloudflare to their Origin server.
```suggestion
Customers that upload their own certificate to use with zone-level Authenticated Origin Pull (AOP) to secure connections from Cloudflare to their origin server.
```

2022-03-24 16:26 UTC, kodster28 commented on content/fundamentals/notifications/notification-available.md
> +Upload a renewed certificate to use for zone-level AOP.
```suggestion
Upload a renewed certificate to use for [zone-level AOP](/ssl/origin-configuration/authenticated-origin-pull/set-up/). 
```

2022-03-24 16:26 UTC, kodster28 commented on content/fundamentals/notifications/notification-available.md
> +Upload a renewed certificate to use for [hostname-level AOP](/ssl/origin-configuration/authenticated-origin-pull/).
```suggestion
Upload a renewed certificate to use for [hostname-level AOP](/ssl/origin-configuration/authenticated-origin-pull/set-up/#per-hostname--customer-certificates). 
```

2022-03-24 17:50 UTC, pedrosousa commented on content/fundamentals/notifications/notification-available.md
> +## DoS Protection
```suggestion
## DDoS Protection
```

2022-03-28 20:22 UTC, lgarofalo commented on content/fundamentals/notifications/notification-available.md
> +Upload a [renewed certificate](/ssl/ssl-for-saas/custom-certificates/).
Yea, the existing reference to custom-certificates is not correct.  Your change looks correct to me, except "/ssl/" should be removed from the path for the cloudlare one documentation link, right?

https://developers.cloudflare.com/cloudflare-one/identity/devices/mutual-tls-authentication/#add-mtls-authentication-to-your-access-configuration

2022-03-28 21:18 UTC, kodster28 commented on content/fundamentals/notifications/notification-available.md
> +Upload a [renewed certificate](/ssl/ssl-for-saas/custom-certificates/).
Howdy @lgarofalo, slightly adjusted the wording here.

I might be misunderstanding the process, but you'd want to do those two steps in separate areas of the dash, correct? First create a new cert (SSL) and then update your policy (CF one dash).

Or is the first step not required?

2022-03-30 13:05 UTC, marciocloudflare commented on content/fundamentals/notifications/notification-available.md
> +## DoS Protection
This is actually `DoS` in the dash, @pedrosousa

2022-03-30 13:15 UTC, pedrosousa commented on content/fundamentals/notifications/notification-available.md
> +## DoS Protection
I'll ask the PM if it's correct. Thanks for checking!

2022-03-31 15:09 UTC, kodster28 commented on content/fundamentals/notifications/notification-available.md
> +Upload a [renewed certificate](/ssl/ssl-for-saas/custom-certificates/).
Updated based on background info from Kenny.

2022-03-31 15:13 UTC, kodster28 approved these changes

2022-03-31 16:16 UTC, merged