Add applications page redirect
cloudflare/cloudflare-docs pull request #3929
Opened 2022-03-25 15:35 UTC by ranbel

2022-03-25 15:41 UTC, marciocloudflare requested changes

2022-03-25 15:45 UTC, marciocloudflare requested changes

2022-03-25 15:45 UTC, marciocloudflare commented on content/_redirects
> +/cloudflare-one/policies/filtering/http-policies/application-app-types/ /cloudflare-one/policies/filtering/application-app-types/ 301
```suggestion
/cloudflare-one/policies/filtering/http-policies/application-app-types/ /cloudflare-one/policies/filtering/application-app-types/ 301
/cloudflare-one/policies/filtering/http-policies/application-app-types /cloudflare-one/policies/filtering/application-app-types/ 301
```

2022-03-25 15:58 UTC, marciocloudflare approved these changes

2022-03-25 15:59 UTC, merged

2022-03-28 07:41 UTC, IvanMX13 commented on content/_redirects
> +/cloudflare-one/policies/filtering/http-policies/application-app-types /cloudflare-one/policies/filtering/application-app-types/ 301
#3934