Replaced deprecated data nodes
cloudflare/cloudflare-docs pull request #3939
Opened 2022-03-28 13:16 UTC by angelampcosta

2022-03-28 16:20 UTC, tlozoot requested changes
`browserPerf1mGroups1` has been removed completely, and is not replaced by `firewallEventsAdaptive`. Should have João Sousa Botto review and suggest changes

2022-03-30 10:00 UTC, pedrosousa approved these changes

2022-03-30 10:00 UTC, pedrosousa commented on content/analytics/graphql-api/features/data-sets/index.md
> +| `browserPerf1mGroups`<br/>`browserInsightsAdaptiveGroups`<br/>`webVitalsAdaptiveGroups` | `rumPerformanceEventsAdaptiveGroups`<br/>`rumPageloadEventsAdaptiveGroups`<br/>`rumWebVitalsEventsAdaptiveG
This is the only entry that doesn't have a specific day for the sunset date. Can we add one?
Also, was it really in July 2021?

2022-03-30 10:00 UTC, pedrosousa commented on content/analytics/graphql-api/limits/index.md
> +| `rumPerformanceEventsAdaptiveGroups`          | 6 months | 6 months | 6 months |   6 months |
Currently we didn't use any units above `day` (we even had `365 days`)... Should we convert months to days here?

2022-03-30 10:00 UTC, pedrosousa commented on content/analytics/graphql-api/features/data-sets/index.md
> +| `browserPerf1mGroups`<br/>`browserInsightsAdaptiveGroups`<br/>`webVitalsAdaptiveGroups` | `rumPerformanceEventsAdaptiveGroups`<br/>`rumPageloadEventsAdaptiveGroups`<br/>`rumWebVitalsEventsAdaptiveG
Maybe we could order the list by sunset date (not sure if we're following a specific order right now).

2022-03-30 10:07 UTC, angelampcosta commented on content/analytics/graphql-api/features/data-sets/index.md
> +| `browserPerf1mGroups`<br/>`browserInsightsAdaptiveGroups`<br/>`webVitalsAdaptiveGroups` | `rumPerformanceEventsAdaptiveGroups`<br/>`rumPageloadEventsAdaptiveGroups`<br/>`rumWebVitalsEventsAdaptiveG
I wasn't able to get a precise date, only month and year.

2022-03-30 10:11 UTC, angelampcosta commented on content/analytics/graphql-api/limits/index.md
> +| `rumPerformanceEventsAdaptiveGroups`          | 6 months | 6 months | 6 months |   6 months |
We also have months and 1 year in the table. I don't think we have a standard unit for all dates. Should we change this @jeehoon-cf?

2022-03-30 11:31 UTC, pedrosousa commented on content/analytics/graphql-api/limits/index.md
> +| `rumPerformanceEventsAdaptiveGroups`          | 6 months | 6 months | 6 months |   6 months |
Oh, we do have `6 months` already... missed it, sorry!

2022-03-30 15:59 UTC, cf-ypark approved these changes
LGTM

2022-03-30 16:31 UTC, jeehoon-cf commented on content/analytics/graphql-api/limits/index.md
> +| `rumPerformanceEventsAdaptiveGroups`          | 6 months | 6 months | 6 months |   6 months |
If we are to change it to days rather than months, 184 days is equivalent.

2022-03-30 16:31 UTC, jeehoon-cf approved these changes

2022-03-31 15:28 UTC, tlozoot approved these changes

2022-03-31 15:29 UTC, merged