feat: extract `product-grid` shared shortcode
cloudflare/cloudflare-docs pull request #3992
Opened 2022-04-01 18:08 UTC by lukeed

Extract a new `product-grid` shortcode so that the process of adding new CF products touches fewer files.

With this PR:

1. Create the `data/<name>.yaml` file with necessary information. A product must have a `product` block now with `title` and `url` keys. The `wrap` key is optional
2. Insert the new `<name>` in the desired position within the `layouts/shortcodes/product-grid.html` file's `$order` variable. These are (and will be) the only products that appear in the grid – and **in the specified order**. <br>
> **NOTE:** Our product grid isn't alphasorted, hence the manual ordering.

2022-04-01 18:10 UTC, lukeed commented
Pages affected (for review):
* https://a59dade4.cloudflare-docs-7ou.pages.dev/
* https://a59dade4.cloudflare-docs-7ou.pages.dev/docs/

2022-04-05 09:28 UTC, pedrosousa requested changes

2022-04-05 09:28 UTC, pedrosousa commented on data/ddos-protection.yml
> +  url: /byoip/
```suggestion
  url: /ddos-protection/
```

2022-04-05 15:29 UTC, pedrosousa approved these changes

2022-04-05 16:31 UTC, merged