Pages Plugins
cloudflare/cloudflare-docs pull request #4027
Opened 2022-04-05 15:43 UTC by GregBrimble

Documentation for a new Pages Functions feature: Pages Plugins.

2022-05-03 12:58 UTC, deadlypants1973 requested changes
PCX review

2022-05-03 12:58 UTC, deadlypants1973 commented on content/pages/platform/functions/plugins.md
> +A Pages Plugin is a Pages Functions distributable which includes routing and functionality built-in. Developers can include a plugin as a part of their Pages project wherever they chose, and can pass
```suggestion
A Pages Plugin is a Pages Functions distributable which includes built-in routing and functionality. Developers can include a Plugin as a part of their Pages project wherever they chose, and can pass it some configuration options. The full power of Functions is available to Plugins, including middleware, parameterized routes, and static assets.
```

2022-05-03 12:58 UTC, deadlypants1973 commented on content/pages/platform/functions/plugins.md
> +- report errors and track performance
```suggestion
- Intercept HTML pages and inject in a third-party script.
- Proxy a third-party service's API.
- Validate authorization headers.
- Provide a full admin web app experience.
- Store data in KV or Durable Objects.
- Server-side render (SSR) Pages with data from a CMS.
- Report errors and track performance.
```

2022-05-03 12:58 UTC, deadlypants1973 commented on content/pages/platform/functions/plugins.md
> +Developers can enhance their projects by mounting a Pages Plugin at some route of their app. Plugins will provide instructions of where they should typically be mounted (e.g. an admin interface might
```suggestion
Developers can enhance their projects by mounting a Pages Plugin at a route of their application. Plugins will provide instructions of where they should typically be mounted (for example, an admin interface might be mounted at `functions/admin/[[path]].ts`, and an error logger might be mounted at `functions/_middleware.ts`). Additionally, each Plugin may take some configuration (for example, with an API token).
```

2022-05-03 12:58 UTC, deadlypants1973 commented on content/pages/platform/functions/plugins.md
> +In this example, we'll build a Pages Plugin and then include it in a project.
```suggestion
In this example, you will build a Pages Plugin and then include it in a project.
```

2022-05-03 12:58 UTC, deadlypants1973 commented on content/pages/platform/functions/plugins.md
> +## Static Form Example
```suggestion
## Static form example
```

2022-05-03 12:58 UTC, deadlypants1973 commented on content/pages/platform/functions/plugins.md
> +- respond to submissions with a developer's custom response
```suggestion
- intercept HTML forms.
- store the form submission in [KV](/workers/runtime-apis/kv/).
- respond to submissions with a developer's custom response.
```

2022-05-03 12:58 UTC, deadlypants1973 commented on content/pages/platform/functions/plugins.md
> +`index.js` will be the entrypoint to your plugin. It's a generated file (built by wrangler with the `npm run build` command), so add `index.js` to your `.gitignore`.
```suggestion
`index.js` will be the entrypoint to your Plugin. This is a generated file built by Wrangler with the `npm run build` command. Add `index.js` to your `.gitignore`.
```

2022-05-03 12:58 UTC, deadlypants1973 commented on content/pages/platform/functions/plugins.md
> +Next, create a `functions` directory and get started coding your Plugin! The `functions` folder will be mounted at some route by the developer, so consider how to structure your files. Generally:
```suggestion
Next, create a `functions` directory and start coding your Plugin. The `functions` folder will be mounted at some route by the developer, so consider how you want to structure your files. Generally:
```

2022-05-03 12:58 UTC, deadlypants1973 commented on content/pages/platform/functions/plugins.md
> +- and if you want your plugin to intercept requests but fallback on either other Functions or the project's static assets, create a `functions/_middleware.ts` file.
```suggestion
- if you want your Plugin to run on a single route of the developer's choice (for example, `/foo`), create a `functions/index.ts` file.
- if you want your Plugin to be mounted and serve all requests beyond a certain path (for example, `/admin/login` and `/admin/dashboard`), create a `functions/[[path]].ts` file.
- if you want your Plugin to intercept requests but fallback on either other Functions or the project's static assets, create a `functions/_middleware.ts` file.
```

2022-05-03 12:58 UTC, deadlypants1973 commented on content/pages/platform/functions/plugins.md
> +{{<Aside type="note" header="Don't include the mounted path in your Plugin">}}
```suggestion
{{<Aside type="note" header="Do not include the mounted path in your Plugin">}}
```

2022-05-03 12:58 UTC, deadlypants1973 commented on content/pages/platform/functions/plugins.md
> +Your Plugin shouldn't have use the mounted path anywhere in the file structure (e.g. `/foo` or `/admin`). Developers should be free to mount your Plugin whereever they choose, but of course, you can
```suggestion
Your Plugin should not have use the mounted path anywhere in the file structure (for example, `/foo` or `/admin`). Developers should be free to mount your Plugin whereever they choose, but you can make recommendations of how you expect this to be mounted in your `README.md`.
```

2022-05-03 12:58 UTC, deadlypants1973 commented on content/pages/platform/functions/plugins.md
> +Your Plugin shouldn't have use the mounted path anywhere in the file structure (e.g. `/foo` or `/admin`). Developers should be free to mount your Plugin whereever they choose, but of course, you can
First sentence of this paragraph appears to be missing a word?

2022-05-03 12:58 UTC, deadlypants1973 commented on content/pages/platform/functions/plugins.md
> +You are free to use as many different files as you need. The structure of a Plugin is exactly the same as Functions in a Pages project today, except that the handlers receive a new property of their
"You can use this to receive from developers" feels like it is missing something?

2022-05-03 12:58 UTC, deadlypants1973 commented on content/pages/platform/functions/plugins.md
> +Returning to our static form example, if we want to intercept requests and override the behavior of an HTML form, we should create a `functions/_middleware.ts`. Developers could then mount our Plugin
```suggestion
Returning to oyur static form example, if you want to intercept requests and override the behavior of an HTML form, you need to create a `functions/_middleware.ts`. Developers could then mount your Plugin on a single route, or on their entire project.
```

2022-05-03 12:58 UTC, deadlypants1973 commented on content/pages/platform/functions/plugins.md
> +In the `index.d.ts`, export a function which takes your `pluginArgs` and returns a `PagesFunction`. For our static form example, we take two properties, `kv`, a KV namespace, and `respondWith`, a fun
```suggestion
In the `index.d.ts`, export a function which takes your `pluginArgs` and returns a `PagesFunction`. For your static form example, you take two properties, `kv`, a KV namespace, and `respondWith`, a function which takes an object with a `formData` property (`FormData`) and returns a `Promise` of a `Response`:
```

2022-05-03 12:58 UTC, deadlypants1973 commented on content/pages/platform/functions/plugins.md
> +We're still working on creating a great testing experience for Pages Plugins authors. Please bear with us until all those pieces come together. In the meantime, you can create an example project and
```suggestion
We are still working on creating a great testing experience for Pages Plugins authors. Please be patient with us until all those pieces come together. In the meantime, you can create an example project and include your Plugin manually for testing.
```

2022-05-03 12:58 UTC, deadlypants1973 commented on content/pages/platform/functions/plugins.md
> +We're still working on creating a great testing experience for Pages Plugins authors. Please bear with us until all those pieces come together. In the meantime, you can create an example project and
Is this section entirely meant to be an aside?

2022-05-03 12:58 UTC, deadlypants1973 commented on content/pages/platform/functions/plugins.md
> +You can distribute your Plugin however you choose. Popular options include publishing on [npm](https://www.npmjs.com/), showcasing it in the #what-i-built or #pages-plugins channels in our [Developer
```suggestion
You can distribute your Plugin however you choose. Popular options include publishing on [npm](https://www.npmjs.com/), showcasing it in the #what-i-built or #pages-plugins channels in our [Developer Discord](https://discord.com/invite/cloudflaredev), and open-sourcing on [GitHub](https://github.com/). 
```

2022-05-03 12:58 UTC, deadlypants1973 commented on content/pages/platform/functions/plugins.md
> +Make sure you're including the generated `index.js` and your typings `index.d.ts` as well as a `README.md` with instructions on how developers can use your Plugin.
```suggestion
Make sure you are including the generated `index.js` and your typings `index.d.ts` as well as a `README.md` with instructions on how developers can use your Plugin.
```

2022-05-03 12:58 UTC, deadlypants1973 commented on content/pages/platform/functions/plugins.md
> +If you're wanting to include a Pages Plugin in your application, the first step is to install that plugin to your project. If you're not yet using `npm` in your project, run `npm init` to create a `p
```suggestion
If you want to include a Pages Plugin in your application, you need to first install that Plugin to your project. 

If you are not yet using `npm` in your project, run `npm init` to create a `package.json` file. The Plugin's `README.md` will typically include an installation command (for example, `npm install --save @cloudflare/static-form-interceptor`).
```

2022-05-03 12:58 UTC, deadlypants1973 commented on content/pages/platform/functions/plugins.md
> +Again, the `README.md` of the Plugin will likely include instructions for how to mount the Plugin in your application. Generally, this will involve:
```suggestion
The `README.md` of the Plugin will likely include instructions for how to mount the Plugin in your application. You will need to:
```

2022-05-03 12:58 UTC, deadlypants1973 commented on content/pages/platform/functions/plugins.md
> +3. import the Plugin and export an `onRequest` method in this file, initializing the Plugin with any arguments it requires.
```suggestion
1. Create a `functions` directory, if you do not already have one.
2. Decide where you want this Plugin to run and create a corresponding file in the `functions` directory.
3. Import the Plugin and export an `onRequest` method in this file, initializing the Plugin with any arguments it requires.
```

2022-05-03 12:58 UTC, deadlypants1973 commented on content/pages/platform/functions/plugins.md
> +In our static form example, the Plugin we have created already was created as a middleware. This means it can run on either a single route, or across our entire project. If we had a single contact fo
```suggestion
In the static form example, the Plugin you have created already was created as a middleware. This means it can run on either a single route, or across your entire project. If you had a single contact form on your website at `/contact`, you could create a `functions/contact.ts` file to intercept just that route. You could also create a `functions/_middleware.ts` file to intercept all other routes and any other future forms you might create. As the developer, you can choose where this Plugin can run.
```

2022-05-03 12:58 UTC, deadlypants1973 commented on content/pages/platform/functions/plugins.md
> +A plugin's default export is a function which takes the same context parameter that a normal Pages Functions handler is given.
```suggestion
A Plugin's default export is a function which takes the same context parameter that a normal Pages Functions handler is given.
```

2022-05-03 12:58 UTC, deadlypants1973 commented on content/pages/platform/functions/plugins.md
> +As normal, you can use `wrangler pages dev` to test a Pages project, including any Plugins you have installed. Remember to include an KV bindings and environment variables etc. that the Plugin is exp
```suggestion
You can use `wrangler pages dev` to test a Pages project, including any Plugins you have installed. Remember to include KV bindings and environment variables that the Plugin is expecting.
```

2022-05-03 12:58 UTC, deadlypants1973 commented on content/pages/platform/functions/plugins.md
> +With our Plugin mounted on the `/contact` route, a corresponding HTML file might look like this:
```suggestion
With your Plugin mounted on the `/contact` route, a corresponding HTML file might look like this:
```

2022-05-03 12:58 UTC, deadlypants1973 commented on content/pages/platform/functions/plugins.md
> +Our plugin should pick up the `data-static-form-name="contact"` attribute, set the `method="POST"`, inject in an `<input type="hidden" name="static-form-name" value="contact" />` element, and capture
```suggestion
Your plugin should pick up the `data-static-form-name="contact"` attribute, set the `method="POST"`, inject in an `<input type="hidden" name="static-form-name" value="contact" />` element, and capture `POST` submissions.
```

2022-05-03 12:58 UTC, deadlypants1973 commented on content/pages/platform/functions/plugins.md
> +### 8. Deploying a Pages project
```suggestion
### 8. Deploy your Pages project
```

2022-05-03 12:58 UTC, deadlypants1973 commented on content/pages/platform/functions/plugins.md
> +### 7. Testing a Pages Plugin
```suggestion
### 7. Test a Pages Plugin
```

2022-05-03 12:58 UTC, deadlypants1973 commented on content/pages/platform/functions/plugins.md
> +### 6. Mounting a Pages Plugin
```suggestion
### 6. Mount a Pages Plugin
```

2022-05-03 12:58 UTC, deadlypants1973 commented on content/pages/platform/functions/plugins.md
> +### 5. Installing a Pages Plugin
```suggestion
### 5. Install a Pages Plugin
```

2022-05-03 12:58 UTC, deadlypants1973 commented on content/pages/platform/functions/plugins.md
> +### 4. Publishing your Pages Plugin
```suggestion
### 4. Publish your Pages Plugin
```

2022-05-03 12:58 UTC, deadlypants1973 commented on content/pages/platform/functions/plugins.md
> +### 3. Testing your Pages Plugin
```suggestion
### 3. Test your Pages Plugin
```

2022-05-03 12:58 UTC, deadlypants1973 commented on content/pages/platform/functions/plugins.md
> +### 3. Testing your Pages Plugin
This section is the same title as # 7.

2022-05-03 12:58 UTC, deadlypants1973 commented on content/pages/platform/functions/plugins.md
> +## Authoring a Pages Plugin
```suggestion
## Author a Pages Plugin
```

2022-05-03 12:58 UTC, deadlypants1973 commented on content/pages/platform/functions/plugins.md
> +- report errors and track performance
"- Server-side render (SSR) Pages with data from a CMS." did not start with a verb, so my revision could be sloppy. Need a double-check from Greg that this sentence is accurate.

2022-05-03 12:58 UTC, deadlypants1973 commented on content/pages/platform/functions/plugins.md
> +Ensure the new Plugin has been added to your `package.json` and that everything works locally as you'd expect. You can then `git commit` and `git push` to trigger a Cloudflare Pages deployment and tr
```suggestion
Make sure the new Plugin has been added to your `package.json` and that everything works locally as you would expect. You can then `git commit` and `git push` to trigger a Cloudflare Pages deployment.
```

2022-05-03 12:58 UTC, deadlypants1973 commented on content/pages/platform/functions/plugins.md
> +If you experience any problems with any one Plugin, please file an issue on that Plugin's bug tracker.
```suggestion
If you experience any problems with any one Plugin, file an issue on that Plugin's bug tracker.
```

2022-05-03 12:58 UTC, deadlypants1973 commented on content/pages/platform/functions/plugins.md
> +If you experience any problems with Plugins in general, we'd love to hear feedback in the #pages-plugins channel in [Discord](https://discord.com/invite/cloudflaredev)! We're very excited to see what
```suggestion
If you experience any problems with Plugins in general, we would appreciate your feedback in the #pages-plugins channel in [Discord](https://discord.com/invite/cloudflaredev)! We are excited to see what you build with Plugins and welcome any feedback about the authoring or developer experience. Let us know in the Discord channel if there is anything you need to make Plugins even more powerful.
```

2022-05-03 12:58 UTC, deadlypants1973 commented on content/pages/platform/functions/plugins.md
> +## Including Static Assets with a Plugin (alpha)
```suggestion
## Include a Static Assets with a Plugin (alpha)
```

2022-05-03 12:58 UTC, deadlypants1973 commented on content/pages/platform/functions/plugins.md
> +A Pages Plugin can also bring along static assets to be included in user's Pages project. This is useful if you want to build a full experience for your Plugin (e.g. an admin interface for users to i
```suggestion
A Pages Plugin can also bring along static assets to be included in a user's Pages project. This is useful if you want to build a full experience for your Plugin (for example, an admin interface for users to interact with).
```

2022-05-03 12:58 UTC, deadlypants1973 commented on content/pages/platform/functions/plugins.md
> +## Chaining Plugins
```suggestion
## Chain a Plugin
```

2022-05-03 12:58 UTC, deadlypants1973 commented on content/pages/platform/functions/plugins.md
> +Finally, as with Pages Functions generally, it is possible to chain together Plugins in order to combine together different features. `_middleware`'s higher up in the filesystem will run before other
Second sentence is a tad confusing to read. Is 'higher up' referring to a noun?

2022-05-04 14:36 UTC, GregBrimble commented on content/pages/platform/functions/plugins.md
> +## Including Static Assets with a Plugin (alpha)
```suggestion
## Include Static Assets with a Plugin (alpha)
```

2022-05-04 14:39 UTC, GregBrimble commented on content/pages/platform/functions/plugins.md
> +As normal, you can use `wrangler pages dev` to test a Pages project, including any Plugins you have installed. Remember to include an KV bindings and environment variables etc. that the Plugin is exp
```suggestion
You can use `wrangler pages dev` to test a Pages project, including any Plugins you have installed. Remember to include any KV bindings and environment variables that the Plugin is expecting.
```

2022-05-04 14:41 UTC, GregBrimble commented on content/pages/platform/functions/plugins.md
> +### 3. Testing your Pages Plugin
"Test a ..." vs. "Test your ..." will be enough to generate unique links :)

2022-05-04 14:42 UTC, GregBrimble commented on content/pages/platform/functions/plugins.md
> +Returning to our static form example, if we want to intercept requests and override the behavior of an HTML form, we should create a `functions/_middleware.ts`. Developers could then mount our Plugin
```suggestion
Returning to your static form example, if you want to intercept requests and override the behavior of an HTML form, you need to create a `functions/_middleware.ts`. Developers could then mount your Plugin on a single route, or on their entire project.
```

2022-05-04 14:43 UTC, GregBrimble commented on content/pages/platform/functions/plugins.md
> +Your Plugin shouldn't have use the mounted path anywhere in the file structure (e.g. `/foo` or `/admin`). Developers should be free to mount your Plugin whereever they choose, but of course, you can
```suggestion
Your Plugin should not use the mounted path anywhere in the file structure (for example, `/foo` or `/admin`). Developers should be free to mount your Plugin wherever they choose, but you can make recommendations of how you expect this to be mounted in your `README.md`.
```

2022-05-11 17:15 UTC, GregBrimble commented on content/pages/platform/functions/plugins.md
> +- report errors and track performance
"to render" is my verb. Specifically, "to server-side render". And I meant webpages, rather than Cloudflare Pages. I'll make it `Server-side render (SSR) webpages with data from a CMS.`.

2022-05-11 17:17 UTC, GregBrimble commented on content/pages/platform/functions/plugins.md
> +You are free to use as many different files as you need. The structure of a Plugin is exactly the same as Functions in a Pages project today, except that the handlers receive a new property of their
I'll take out "from developers" to simplify. I don't think that phrase adds much.

2022-05-11 17:19 UTC, GregBrimble commented on content/pages/platform/functions/plugins.md
> +We're still working on creating a great testing experience for Pages Plugins authors. Please bear with us until all those pieces come together. In the meantime, you can create an example project and
You're right, that does look a bit naff. Removing the aside and just keeping this as regular text.

2022-05-11 21:08 UTC, GregBrimble commented on content/pages/platform/functions/plugins.md
> +Finally, as with Pages Functions generally, it is possible to chain together Plugins in order to combine together different features. `_middleware`'s higher up in the filesystem will run before other
Changed to "Middleware defined higher up in the filesystem will run before other handlers, and individual files can chain together Functions in an array like so:"

2022-05-12 08:57 UTC, deadlypants1973 approved these changes
Approved with comment

2022-05-12 08:57 UTC, deadlypants1973 commented on content/pages/platform/functions/plugins/_index.md
> +### 1. Creating a new Pages Plugin
```suggestion
### 1. Create a new Pages Plugin
```

2022-05-12 08:57 UTC, deadlypants1973 commented on content/pages/platform/functions/plugins/_index.md
> +### 2. Typing your Pages Plugin
```suggestion
### 2. Type your Pages Plugin
```

2022-05-12 08:57 UTC, deadlypants1973 commented on content/pages/platform/functions/plugins/_index.md
> +### 5. Install a Pages Plugin
```suggestion
### 5. Install your Pages Plugin
```

2022-05-12 08:57 UTC, deadlypants1973 commented on content/pages/platform/functions/plugins/_index.md
> +### 6. Mount a Pages Plugin
```suggestion
### 6. Mount your Pages Plugin
```

2022-05-12 08:57 UTC, deadlypants1973 commented on content/pages/platform/functions/plugins/_index.md
> +### 7. Test a Pages Plugin
```suggestion
### 7. Test your Pages Plugin
```

2022-05-12 08:57 UTC, deadlypants1973 commented on content/pages/platform/functions/plugins/_index.md
> +## Chain a Plugin
```suggestion
## Chain your Plugin
```

2022-05-12 08:57 UTC, deadlypants1973 commented on content/pages/platform/functions/plugins/cloudflare-access.md
> +The Plugin takes an object with two properties: the `domain` of your Cloudflare Access account, and the policy `aud` (audience) to validate against. Any requests which fail validation will be returne
```suggestion
The Plugin takes an object with two properties: the `domain` of your Cloudflare Access account, and the policy `aud` (audience) to validate against. Any requests which fail validation will be returned a `403` status code.
```

2022-05-12 08:57 UTC, deadlypants1973 commented on content/pages/platform/functions/plugins/cloudflare-access.md
> +### Accessing the JWT payload
```suggestion
### Access the JWT payload
```

2022-05-12 08:57 UTC, deadlypants1973 commented on content/pages/platform/functions/plugins/cloudflare-access.md
> +If you need to use the JWT payload in your application (e.g. you need the user's email address), this Plugin will make this available for you at `data.cloudflareAccess.JWT.payload`.
```suggestion
If you need to use the JWT payload in your application (for example, you need the user's email address), this Plugin will make this available for you at `data.cloudflareAccess.JWT.payload`.
```

2022-05-12 08:57 UTC, deadlypants1973 commented on content/pages/platform/functions/plugins/cloudflare-access.md
> +The [entire JWT payload](https://developers.cloudflare.com/cloudflare-one/identity/users/validating-json/#payload) will be made available on `data.cloudflareAccess.JWT.payload`. Be aware that the fie
```suggestion
The [entire JWT payload](https://developers.cloudflare.com/cloudflare-one/identity/users/validating-json/#payload) will be made available on `data.cloudflareAccess.JWT.payload`. Be aware that the fields available differ between identity authorizations (for example, a user in a browser) and non-identity authorizations (for example, a service token).
```

2022-05-12 08:57 UTC, deadlypants1973 commented on content/pages/platform/functions/plugins/_index.md
> +## Using a Pages Plugin
```suggestion
## Use a Pages Plugin
```

2022-05-12 08:57 UTC, deadlypants1973 commented on content/pages/platform/functions/plugins/cloudflare-access.md
> +This Plugin is a middleware to validate Cloudflare Access JWT assertions. It also includes an API to lookup additional information about a given user's JWT.
```suggestion
The Cloudflare Access Pages Plugin is a middleware to validate Cloudflare Access JWT assertions. It also includes an API to lookup additional information about a given user's JWT.
```

2022-05-12 08:57 UTC, deadlypants1973 commented on content/pages/platform/functions/plugins/cloudflare-access.md
> +In order to get more information about a given user's identity, you can use the provided `getIdentity` API function:
```suggestion
In order to get more information about a given user's identity, use the provided `getIdentity` API function:
```

2022-05-12 08:57 UTC, deadlypants1973 commented on content/pages/platform/functions/plugins/cloudflare-access.md
> +If you want to force a login or logout, you can use these utility functions to generate URLs and redirect a user:
```suggestion
If you want to force a login or logout, use these utility functions to generate URLs and redirect a user:
```

2022-05-12 08:57 UTC, deadlypants1973 commented on content/pages/platform/functions/plugins/google-chat.md
> +This Plugin creates a Google Chat bot which can respond to messages. It also includes an API for interacting with Google Chat (for example, for creating messages) without the need for user input. Thi
```suggestion
The Google Chat Pages Plugin creates a Google Chat bot which can respond to messages. It also includes an API for interacting with Google Chat (for example, for creating messages) without the need for user input. This API is useful for situations such as alerts.
```

2022-05-12 08:57 UTC, deadlypants1973 commented on content/pages/platform/functions/plugins/google-chat.md
> +![A screenshot of the Google Cloud Console 'Connection Settings' for the Google Chat API. It shows 'App URL' selected and 'https://example.com/google-chat' entered into the 'App URL' text input.](/pa
```suggestion
![Google Cloud Console's Connection Settings for the Google Chat API showing 'App URL' selected and 'https://example.com/google-chat' entered into the 'App URL' text input.](/pages/platform/functions/plugins/google-chat.png)
```

2022-05-12 08:57 UTC, deadlypants1973 commented on content/pages/platform/functions/plugins/graphql.md
> +This Plugin creates a GraphQL server which can respond to `application/json` and `application/graphql` `POST` requests. It responds with [the GraphQL Playground](https://github.com/graphql/graphql-pl
```suggestion
The GraphQL Pages Plugin creates a GraphQL server which can respond to `application/json` and `application/graphql` `POST` requests. It responds with [the GraphQL Playground](https://github.com/graphql/graphql-playground) for `GET` requests.
```

2022-05-12 08:57 UTC, deadlypants1973 commented on content/pages/platform/functions/plugins/hcaptcha.md
> +This Plugin validates hCaptcha tokens.
```suggestion
The hCaptcha Pages Plugin validates hCaptcha tokens.
```

2022-05-12 08:57 UTC, deadlypants1973 commented on content/pages/platform/functions/plugins/hcaptcha.md
> +This Plugin only exposes a single route, so wherever it is mounted is wherever it will be available. In the above example, because it is mounted in `functions/register.ts`, it will validate requests
```suggestion
This Plugin only exposes a single route. It will be available wherever it is mounted . In the above example, because it is mounted in `functions/register.ts`, it will validate requests to `/register`. The Plugin is mounted with a single object parameter with the following properties.
```

2022-05-12 08:57 UTC, deadlypants1973 commented on content/pages/platform/functions/plugins/hcaptcha.md
> +`onError` is an optional function which takes the Pages Function context object and returns a `Promise` of a `Response`. By default, it'll return a human-readable error `Response`.
```suggestion
`onError` is an optional function which takes the Pages Function context object and returns a `Promise` of a `Response`. By default, it will return a human-readable error `Response`.
```

2022-05-12 08:57 UTC, deadlypants1973 commented on content/pages/platform/functions/plugins/honeycomb.md
> +This Plugin automatically create
```suggestion
The Honeycomb Pages Plugin automatically creates _________.
```

2022-05-12 08:57 UTC, deadlypants1973 commented on content/pages/platform/functions/plugins/google-chat.md
> +The Plugin takes a function, which in turn takes an incoming message and returns a `Promise` of a response message (or `void` if there should not be any response).
```suggestion
The Plugin takes a function, which in turn takes an incoming message, and returns a `Promise` of a response message (or `void` if there should not be any response).
```

2022-05-12 08:57 UTC, deadlypants1973 commented on content/pages/platform/functions/plugins/honeycomb.md
> +Ensure that you enable the option to "Automatically unpack nested JSON" and set the "Maximum unpacking depth" to 5 in your Honeycomb dataset settings.
```suggestion
Ensure that you enable the option to **Automatically unpack nested JSON** and set the **Maximum unpacking depth** to **5** in your Honeycomb dataset settings.
```

2022-05-12 08:57 UTC, deadlypants1973 commented on content/pages/platform/functions/plugins/honeycomb.md
> +![A screenshot of the dataset settings panel in the Honeycomb dashboard showing the "Automatically unpack nested JSON" setting toggled on and "Maximum unpacking depth" option set to 5](/pages/platfor
```suggestion
![Follow the instructions above to toggle on Automatically unpack nested JSON and set the Maximum unpacking depth option to 5 in the Honeycomb dashboard](/pages/platform/functions/plugins/honeycomb.png)
```

2022-05-12 08:57 UTC, deadlypants1973 commented on content/pages/platform/functions/plugins/honeycomb.md
> +- `data.honeycomb.tracer.log` which takes a single argument, a `String`
```suggestion
- `data.honeycomb.tracer.log` which takes a single argument, a `String`.
```

2022-05-12 08:57 UTC, deadlypants1973 commented on content/pages/platform/functions/plugins/sentry.md
> +The Plugin uses [Toucan](https://github.com/robertcepa/toucan-js) behind-the-scenes, so can take any of [these following options](https://github.com/robertcepa/toucan-js#other-options). `context`, `r
```suggestion
The Plugin uses [Toucan](https://github.com/robertcepa/toucan-js). Refer to the Toucan readme to [review the options it can take](https://github.com/robertcepa/toucan-js#other-options). `context`, `request`, and `event` are automatically populated and should not be manually configured.
```

2022-05-12 08:57 UTC, deadlypants1973 commented on content/pages/platform/functions/plugins/sentry.md
> +### Additional Context
```suggestion
### Additional context
```

2022-05-12 08:57 UTC, deadlypants1973 commented on content/pages/platform/functions/plugins/sentry.md
> +If you need to set additional context for Sentry (e.g. user information or additional logs), you may use the `data.sentry` instance in any Function below the Plugin in the execution chain.
```suggestion
If you need to set additional context for Sentry (for example, user information or additional logs), use the `data.sentry` instance in any Function below the Plugin in the execution chain.
```

2022-05-12 08:57 UTC, deadlypants1973 commented on content/pages/platform/functions/plugins/stytch.md
> +The Stytch Plugin takes a single argument, an object with several properties. `project_id` and `secret` are mandatory strings and can be found in [Stytch's dashboard](https://stytch.com/dashboard/api
```suggestion
The Stytch Plugin takes a single argument, an object with several properties. `project_id` and `secret` are mandatory strings and can be found in [Stytch's dashboard](https://stytch.com/dashboard/api-keys). By default, the Plugin validates a `session_token` cookie of the incoming request, but you can also optionally pass in a `session_token` or `session_jwt` string yourself if you are using some other mechanism to identify user sessions. Finally, you can also pass in a `session_duration_minutes` in order to extend the lifetime of the session. More information on these parameters can be found in [Stytch's documentation](https://stytch.com/docs/api/session-auth).
```

2022-05-12 11:42 UTC, merged