[Tutorial] Add GitHub login option to your application with OAuth2.0 and Pages Functions
cloudflare/cloudflare-docs pull request #4108
Opened 2022-04-14 17:37 UTC by Ekwuno

This Tutorial is a Functions example that shows how to use  OAuth 2.0 flow for authentication, using a GitHub OAuth app and Pages Functions for handling server interactions.

2022-04-15 16:57 UTC, codewithkristian requested changes

2022-04-15 16:57 UTC, kristianfreeman commented on content/pages/tutorials/github-Oauth-app-with-pages-functions/index.md
> +## Get Authorization from OAuth App.
```suggestion
## Get Authorization from OAuth App
```

style guide thing: we shouldn't end headers with periods like this. there's a few instances in this doc that need to be updated

2022-04-15 16:57 UTC, kristianfreeman commented on content/pages/tutorials/github-Oauth-app-with-pages-functions/index.md
> +title: Add GitHub login Option to your application with OAuth2.0 and Pages Functions
this title should be cleaned up (and shortened)

in addition, the filename casing is inconsistent right now - `github-Oauth-app-with-pages-functions`. let's land on a shorter title, and update the filename to match it

2022-04-15 16:57 UTC, kristianfreeman commented on content/pages/tutorials/github-Oauth-app-with-pages-functions/index.md
> +# Add GitHub login Option to your application with OAuth2.0 and Pages Functions
update title accordingly here

2022-04-15 16:57 UTC, kristianfreeman commented on content/pages/tutorials/github-Oauth-app-with-pages-functions/index.md
> +In this tutorial, you will build an Oauth app with GitHub apps and Pages Functions. You will learn about JWTs, Oauth apps and how to intercept requests between client-side JavaScript and serverless f
the casing for OAuth is inconsistent across the doc - Oauth vs OAuth vs OAuth2.0 - let's pick one (I think `OAuth`) and update

2022-04-15 16:57 UTC, kristianfreeman commented on content/pages/tutorials/github-Oauth-app-with-pages-functions/index.md
> +In this tutorial, you will build an Oauth app with GitHub apps and Pages Functions. You will learn about JWTs, Oauth apps and how to intercept requests between client-side JavaScript and serverless f
I would change `GitHub apps` to just `GitHub`

2022-04-15 16:57 UTC, kristianfreeman commented on content/pages/tutorials/github-Oauth-app-with-pages-functions/index.md
> +In this tutorial, you will build an Oauth app with GitHub apps and Pages Functions. You will learn about JWTs, Oauth apps and how to intercept requests between client-side JavaScript and serverless f
fill in more here too - what are JWTs? what are Oauth apps? I think telling the reader what they are building may be more effective than what they're _using_ - e.g. "you will learn how to build authentication into your application using OAuth, GitHub, ..."

2022-04-15 16:57 UTC, kristianfreeman commented on content/pages/tutorials/github-Oauth-app-with-pages-functions/index.md
> +This tutorial assumes you have registered a  GitHub OAuth app. If you have not, [create a new GitHub OAuth app](https://github.com/settings/applications/new) and set your homepage URL and authorizati
The setup here should be more detailed. What is a homepage URL? What is an authorization callback URL? A screenshot or a table would make sense here

2022-04-15 16:57 UTC, kristianfreeman commented on content/pages/tutorials/github-Oauth-app-with-pages-functions/index.md
> +This tutorial will make heavy use of Cloudflare Pages [Workers integration, Pages Functions](/pages/platform/functions/) and GitHub Authorization credentials. Refer to the [Get started guide](/pages/
What is the correct way to refer to Pages Functions here? The way this link is written is odd to me - can it just be "Pages Functions" or is that not the right way to refer to the product?

2022-04-15 16:57 UTC, kristianfreeman commented on content/pages/tutorials/github-Oauth-app-with-pages-functions/index.md
> +To ensure the user information is secure, you will sign the user information as a payload with a secret in a JSON Web Token format (JWT) and then set this `JWT` to the localStorage to check  who is l
Is `JWT` a variable, and that's why it's written in backticks?

2022-04-15 16:57 UTC, kristianfreeman commented on content/pages/tutorials/github-Oauth-app-with-pages-functions/index.md
> +Below is an example of what the Client HTML will look like:
This code is also found a few lines later when they begin following along with the tutorial. I would remove it here as it seems to be a duplicate

2022-04-15 16:57 UTC, kristianfreeman commented on content/pages/tutorials/github-Oauth-app-with-pages-functions/index.md
> +To begin, create a `client/index.html` at the root of your project to serve the static part of your application. Then, in the same client directory, create an `index.js` file; this is where you will
It may make it easier for people to follow along if we give them a GitHub repo or template of some kind to begin with. This could be a good place to link to that, so they can go look at the finished product (and the file/folder structure) while still following the guide here to implement file-by-file

2022-04-15 16:57 UTC, kristianfreeman commented on content/pages/tutorials/github-Oauth-app-with-pages-functions/index.md
> +Copy and paste the following content into your `client/index.html` file; this file contains :
```suggestion
Copy the following content into `client/index.html`:
```

2022-04-15 16:57 UTC, kristianfreeman commented on content/pages/tutorials/github-Oauth-app-with-pages-functions/index.md
> +  <link rel="stylesheet" href="style.css">
Where does this CSS come from? I don't see it defined in the rest of the tutorial

2022-04-15 16:57 UTC, kristianfreeman commented on content/pages/tutorials/github-Oauth-app-with-pages-functions/index.md
> +Your REDIRECT_URL should be the same URL you used as your callback URL while setting up your application.
```suggestion
Your `REDIRECT_URL` should be the same URL you used as your callback URL while setting up your application.
```

2022-04-15 16:57 UTC, kristianfreeman commented on content/pages/tutorials/github-Oauth-app-with-pages-functions/index.md
> +import qs from "query-string";
This requires installing the package and defining it in `package.json`, right? Add `npm install query-string` instructions before this section

Generally, when a new package is introduced into the project, you should take a paragraph to explain _what_ we're installing, _why_ we're installing it, and _how_ to install it (`npm install <package>`)

2022-04-15 16:57 UTC, kristianfreeman commented on content/pages/tutorials/github-Oauth-app-with-pages-functions/index.md
> +import config from "../config";
**Blocker/must-fix:**

I see that we're importing `config` directly into our client-side JavaScript. The `config.js` file includes our `CLIENT_SECRET`, which AFAIK is not safe to expose to the client.

I think it makes sense to update `config.js` with two separate objects, one that is safe to import into the frontend (containing the vars we need: `REDIRECT_URL`, `CLIENT_ID`), and another that we use inside the functions code that contains the `CLIENT_SECRET`.

2022-04-15 16:57 UTC, kristianfreeman commented on content/pages/tutorials/github-Oauth-app-with-pages-functions/index.md
> +  <script src="./index.js" type="module" ></script>
I think if you put this code after the end of the body tag (it may be fine here too), you don't need the `onload` method you use in that file. It should be executed after the browser has processed the DOM tree in `body` and be able to attach to your `a` and `btn` tags accordingly

2022-04-15 16:57 UTC, kristianfreeman commented on content/pages/tutorials/github-Oauth-app-with-pages-functions/index.md
> +window.onload = function () {
Per comment above, you shouldn't need this because the script is loading after the DOM. You can simply call `getAppAuthorization()` at the top level of your script

2022-04-15 16:57 UTC, codewithkristian commented on content/pages/tutorials/github-Oauth-app-with-pages-functions/index.md
> +function  getAppauthorization() {
```suggestion
function getAppAuthorization() {
```

use consistent casing in function names

2022-04-15 16:57 UTC, codewithkristian commented on content/pages/tutorials/github-Oauth-app-with-pages-functions/index.md
> +From the code block above, you will notice we called an onload method to the window, and we do this so the functions will be fired when the whole page has loaded, including all dependent resources su
Remove this para when related `onload` code

2022-04-15 16:57 UTC, codewithkristian commented on content/pages/tutorials/github-Oauth-app-with-pages-functions/index.md
> +  REDIRECT_URL: "http://localhost:8788/",
**Blocker/must-fix**

This localhost URL is hardcoded a few times in the tutorial. This will fail in production once it's deployed, right? 

I don't see any mention of wrangler/miniflare in the tutorial so I assume that while you were writing this, you were testing locally (which is fine!). I'd update the tutorial to either 

1) Use wrangler/miniflare for local development and show people _how_ localhost can be used while building
2) Remove localhost usage altogether, and tell developers that this URL will ultimately be your Pages production URL, and use a placeholder that you resolve at the end of the tutorial with a final URL (perhaps using your production URL that you made while writing this tutorial)

2022-04-15 16:57 UTC, codewithkristian commented on content/pages/tutorials/github-Oauth-app-with-pages-functions/index.md
> +    const server = "http://localhost:8788/api/code"
Hard-coded use of localhost worries me here, this should be a production URL, right? We also could parameterize this as something in `config.js` like `SERVER_URL`

2022-04-15 16:57 UTC, codewithkristian commented on content/pages/tutorials/github-Oauth-app-with-pages-functions/index.md
> +
Before moving into the Functions section, I would show the completed code for the client-side JavaScript here as a single code block

2022-04-15 16:57 UTC, codewithkristian commented on content/pages/tutorials/github-Oauth-app-with-pages-functions/index.md
> +"`js
```suggestion
`js
```

this should fix the JavaScript rendering here in GitHub. as a heads-up, I would always check the GitHub preview of your doc once you've submitted the PR to make sure it renders like you would expect

2022-04-15 16:57 UTC, codewithkristian commented on content/pages/tutorials/github-Oauth-app-with-pages-functions/index.md
> +"`txt
```suggestion
`txt
```

this should fix the code block rendering here in GitHub. as a heads-up, I would always check the GitHub preview of your doc once you've submitted the PR to make sure it renders like you would expect

2022-04-15 16:57 UTC, codewithkristian commented on content/pages/tutorials/github-Oauth-app-with-pages-functions/index.md
> +The `handleCode` function will send `POST` requests, which means that the `functions/api/code.js` file needs to export an `OnRequestPost` handler:
```suggestion
The `handleCode` function will send `POST` requests, which means that the `functions/api/code.js` file needs to export an `onRequestPost` handler:
```

2022-04-15 16:57 UTC, codewithkristian commented on content/pages/tutorials/github-Oauth-app-with-pages-functions/index.md
> + * Post /api/code
```suggestion
 * POST /api/code
```

2022-04-15 16:57 UTC, codewithkristian commented on content/pages/tutorials/github-Oauth-app-with-pages-functions/index.md
> +   * 2. Use acess token to fetch user info
```suggestion
   * 2. Use access token to fetch user info
```

2022-04-15 16:57 UTC, codewithkristian commented on content/pages/tutorials/github-Oauth-app-with-pages-functions/index.md
> +  /** TODO:
love this!

2022-04-15 16:57 UTC, codewithkristian commented on content/pages/tutorials/github-Oauth-app-with-pages-functions/index.md
> +The `context` parameter is an object filled with several values of potential interest. For this example, you only need the [`Request`](/workers/runtime-apis/request/) object and the [`env`](/pages/pl
```suggestion
The `context` parameter is an object filled with several values of potential interest. For this example, you only need the [`request`](/workers/runtime-apis/request/) and [`env`](/pages/platform/functions/#writing-your-first-function), objects:
```

2022-04-15 16:57 UTC, codewithkristian commented on content/pages/tutorials/github-Oauth-app-with-pages-functions/index.md
> +As mentioned, the code is sent to `/api/code.js`. You can access it from within the request object and use a `JSON()` to request a Readable stream. You then want to pass the code to a function to exc
```suggestion
In your client-side JavaScript code, you made a POST request to `/api/code`, sending the GitHub authorization code. In this file, you will set up the corresponding function, using `onRequestPost`. 

In that function, you can access the authorization code by parsing the request body as JSON. You can then pass the code to a function, to exchange it for a GitHub access token:
```

2022-04-15 16:57 UTC, codewithkristian commented on content/pages/tutorials/github-Oauth-app-with-pages-functions/index.md
> +### Exchange Code for Access token.
```suggestion
### Exchange Code for Access token. 
```

Exchange what code for access token to what? Tense is weird here too, I would say "Exchanging" instead of "Exchange" but maybe @deadlypants1973 can correct me if that's not how we do it

2022-04-15 16:57 UTC, codewithkristian commented on content/pages/tutorials/github-Oauth-app-with-pages-functions/index.md
> +  const res = await fetch(TokenURL, {
Since we seem to only use `TokenURL` once, I'd prefer dropping that variable and just using `config.TOKEN_ENDPOINT` directly

2022-04-15 16:57 UTC, codewithkristian commented on content/pages/tutorials/github-Oauth-app-with-pages-functions/index.md
> +    client_secret: config.CLIENT_SECRET,
Just to follow up on my comment earlier, since this is the only time you use `CLIENT_SECRET` in the codebase, we need to clean up the config file so that it isn't exposed on the client-side. We can safely use it here but should not reveal it to our users in the client.

2022-04-15 16:57 UTC, codewithkristian commented on content/pages/tutorials/github-Oauth-app-with-pages-functions/index.md
> +  console.log(parsedData.access_token);
remove `console.log` unless we are testing/verifying using local dev

2022-04-15 16:57 UTC, codewithkristian commented on content/pages/tutorials/github-Oauth-app-with-pages-functions/index.md
> +  const parsedData = qs.parse(data);
I don't think `qs` has been imported in this file before now

2022-04-15 16:57 UTC, codewithkristian commented on content/pages/tutorials/github-Oauth-app-with-pages-functions/index.md
> +"`js
```suggestion
`js
```

2022-04-15 16:57 UTC, codewithkristian commented on content/pages/tutorials/github-Oauth-app-with-pages-functions/index.md
> +In the fetchUser function, you will need to construct a user URL using your `RESOURCE_ENDPOINT` and a user parameter like `config.RESOURCE_ENDPOINT + "user";`. The authorization object value will be
```suggestion
In the fetchUser function, you will need to construct a user URL using your `RESOURCE_ENDPOINT` and a user parameter like `config.RESOURCE_ENDPOINT + "user";`. The authorization object value will be your Access token. The `onRequestPost` function will need to be updated to await your `fetchUser` function.
```

need to be very careful how you refer to that function, the casing has been inconsistent throughout the tutorial. unlike many function/variable names, `onRequestPost` can only be written in one way and the inconsistency even outside of sample code can be very harmful to DX

2022-04-15 16:57 UTC, codewithkristian commented on content/pages/tutorials/github-Oauth-app-with-pages-functions/index.md
> +    const user = await fetchUser(token); // New Line
```suggestion
    const user = await fetchUser(token);
```

???

2022-04-15 16:57 UTC, codewithkristian commented on content/pages/tutorials/github-Oauth-app-with-pages-functions/index.md
> +  console.log(data);
remove

2022-04-15 16:57 UTC, codewithkristian commented on content/pages/tutorials/github-Oauth-app-with-pages-functions/index.md
> +      "User-Agent": "Mozilla/5.0", // Add user agent for GitHub API when using workers
IIRC this is required, but I would explain to readers why you need to do this in a longer comment above this line. also, i would recommend setting a unique `User-Agent` instead of using Mozilla's

2022-04-15 16:57 UTC, codewithkristian commented on content/pages/tutorials/github-Oauth-app-with-pages-functions/index.md
> +      "User-Agent": "Mozilla/5.0", // Add user agent for GitHub API when using workers
Also, "when using workers" -- we're writing a function in Pages, right? If a user is going through this and sees "workers" they are going to be confused

2022-04-15 16:57 UTC, codewithkristian commented on content/pages/tutorials/github-Oauth-app-with-pages-functions/index.md
> +The User information is sensitive and will be used on the client-side. To ensure that this information is secure and isn't manipulated by a 3rd party, we will use JSON Web Token (JWT).
```suggestion
A user's information is sensitive and will be used on the client-side. To ensure that this information is secure and isn't manipulated by a 3rd party, we will use JSON Web Tokens (JWTs).
```

2022-04-15 16:57 UTC, codewithkristian commented on content/pages/tutorials/github-Oauth-app-with-pages-functions/index.md
> +A [Json web tokens](https://jwt.io/introduction) is a proposed Internet standard for creating data with optional signature and optional encryption whose payload holds JSON that asserts some number of
```suggestion
A [JSON Web Token](https://jwt.io/introduction) is a proposed Internet standard for creating data with an optional signature, and optional encryption, whose payload holds JSON that asserts some number of claims to resources.
```

2022-04-15 16:57 UTC, codewithkristian commented on content/pages/tutorials/github-Oauth-app-with-pages-functions/index.md
> +Your secret key can be any set of strings. In the `code.js` file, import the package and use the `.sign` method to sign the jwtPayload and your secret string.
Copying my comment from previous review in regards to `@tsndr/cloudflare-worker-jwt`

Generally, when a new package is introduced into the project, you should take a paragraph to explain _what_ we're installing, _why_ we're installing it, and _how_ to install it (`npm install <package>`)

2022-04-15 16:57 UTC, codewithkristian commented on content/pages/tutorials/github-Oauth-app-with-pages-functions/index.md
> +const myVerySecretString = "*********"
I don't think we have actual secrets in Pages deployments (cc @nevikashah, am I wrong on that?) but I would prefer this to be a environment variable at least, instead of hardcoding this as plaintext into the code.

2022-04-15 16:57 UTC, codewithkristian commented on content/pages/tutorials/github-Oauth-app-with-pages-functions/index.md
> +....
```suggestion
// ....
```

2022-04-15 16:57 UTC, codewithkristian commented on content/pages/tutorials/github-Oauth-app-with-pages-functions/index.md
> +[Workers Kv](/workers/runtime-apis/kv/) is a global low-latency, key-value data store. It can be used to cache information that has been received from a server, and in this case, you will use it to c
```suggestion
[Workers KV](/workers/runtime-apis/kv/) is a global low-latency, key-value data store. It can be used to cache information that has been received from a server, and in this case, you will use it to cache user information. 
```

2022-04-15 16:57 UTC, codewithkristian commented on content/pages/tutorials/github-Oauth-app-with-pages-functions/index.md
> +## Cache User infomation in KV
```suggestion
## Cache user information in Workers KV
```

2022-04-15 16:57 UTC, codewithkristian commented on content/pages/tutorials/github-Oauth-app-with-pages-functions/index.md
> +You will use the `env` argument to access your kv store, KV takes the first value as a string, and then the next value can be JSON. We want to use the user ID as the key and stringify the user inform
```suggestion
You will use the `env` argument to access your Workers KV store. Workers KV takes the first value as a string, and then the next value can be JSON. We want to use the user ID as the key and stringify the user information and access token as the value.
```

2022-04-15 16:57 UTC, codewithkristian commented on content/pages/tutorials/github-Oauth-app-with-pages-functions/index.md
> +You will use the `env` argument to access your kv store, KV takes the first value as a string, and then the next value can be JSON. We want to use the user ID as the key and stringify the user inform
> Workers KV takes the first value as a string, and then the next value can be JSON

What is "the first value" and "the next value"? I believe this is in reference to the `.put` method, so I would rephrase that in terms of the method taking a "key" and "value".

> We want to use the user ID as the key and stringify the user information and access token as the value.

The next sentence _kinda_ clarifies this, but it is unclear that the connection is between "the first value" and "the next value" -> "key" and "value"

2022-04-15 16:57 UTC, codewithkristian commented on content/pages/tutorials/github-Oauth-app-with-pages-functions/index.md
> +Since the user information is cached, we will not need to make any network request for the user info if we want to fetch for repos, as you will see in the next section.
Clarify more: the user information is cached _where_? Now that it's cached, we won't make a network request to _where_?

2022-04-15 16:57 UTC, codewithkristian commented on content/pages/tutorials/github-Oauth-app-with-pages-functions/index.md
> +To take it a step further, you will check that `JWT` is available before allowing the application to fetch repos by first getting the `JWT` from the localStorage and verifying it to make sure your se
This speaks to the overall purpose of this tutorial and what you'll ultimately build. I would clean up this section to summarize the overall flow of the tutorial:

```suggestion
In this tutorial, you'll build an authorization flow to allow users to sign in with GitHub to your application. Once they've signed in, you'll use Pages Functions and Workers KV to store the user's information and make an authorized GitHub API request on their behalf, to show a list of their repositories in a web page.
```

2022-04-15 16:57 UTC, codewithkristian commented on content/pages/tutorials/github-Oauth-app-with-pages-functions/index.md
> +Since the user information is cached, we will not need to make any network request for the user info if we want to fetch for repos, as you will see in the next section.
> if we want to fetch for repos, as you will see in the next section

I would find this jarring as a reader, because we've been very in-depth in the auth code/access token exchange until now. It's likely that the user needs a reminder that the purpose for all of this is to retrieve a list of repos (CTRL-F for "This speaks to the overall purpose of this tutorial" as earlier review comment) 

```suggestion
Since the user information is cached, we will not need to make any network request for the user info.
```

Clean up the first sentence as per my first review comment, and then add a new sentence that restates why we've been doing this:

```
With our user information cached in Workers KV, we can use it to an authorized request to GitHub for a list of the user's repositories
```

2022-04-15 16:57 UTC, codewithkristian commented on content/pages/tutorials/github-Oauth-app-with-pages-functions/index.md
> +    ) // New Line
```suggestion
    )
```

2022-04-15 16:57 UTC, codewithkristian commented on content/pages/tutorials/github-Oauth-app-with-pages-functions/index.md
> +    console.log(body) // use request.json  to make request body a readable stream
remove console.logs in this function

2022-04-15 16:57 UTC, codewithkristian commented on content/pages/tutorials/github-Oauth-app-with-pages-functions/index.md
> +## Use JWT for Client login validation and fetching User Repos.
remove period, fix inconsistent casing (Client, User Repos)

2022-04-15 16:57 UTC, codewithkristian commented on content/pages/tutorials/github-Oauth-app-with-pages-functions/index.md
> +"`js
```suggestion
```js
```

2022-04-15 16:57 UTC, codewithkristian commented on content/pages/tutorials/github-Oauth-app-with-pages-functions/index.md
> +    const server = "http://localhost:8788/api/code"
Hardcoded localhost URL

2022-04-15 16:57 UTC, codewithkristian commented on content/pages/tutorials/github-Oauth-app-with-pages-functions/index.md
> +Since we authenticate using a JWT, we can create some restrictions based on the presence of this JWT. For example, in the `client/index.html` file, we have a fetch repos button, and we can make this
```suggestion
Since we authenticate using a JWT, we can create some restrictions based on the presence of this JWT. For example, in the `client/index.html` file, we have a "Fetch repos" button, and we can make this button inaccessible if the JWT isn't present. 
```

2022-04-15 16:57 UTC, codewithkristian commented on content/pages/tutorials/github-Oauth-app-with-pages-functions/index.md
> +If a user hasn't authorized the application and has a JWT, they will not be allowed to fetch repos.
duplicate of last paragraph, remove

2022-04-15 16:57 UTC, codewithkristian commented on content/pages/tutorials/github-Oauth-app-with-pages-functions/index.md
> +To do this, create a `ProtectedTask` function and within this function, use the `querySelector` method to get the button and set the display to none. Then check that the JWT is present in the localSt
generally, I prefer a verbal explanation of what we're about to do in a code block, and then the code shows you how to actually do it. 

In this case, the explanation here is actually more confusing than showing the code: the function is called `protectedRequest` but referred to here as `ProtectedTask`, the reference to "set the display" and "change the display" can be confusing when the actual code is `style.display`. 

Finally, there is a non-code (no backticks) reference to `onClick`, but we use `addEventListener("click", ...`, so if the reader looks for `onClick` in the code, they may not understand the connection.

I would rewrite this paragraph to say:

```
To do this, we'll create a new function that will conditionally show the "Fetch repos" button based on the presence of a `jwt` key in `localStorage`. If the `jwt` is found, we'll add a new event listener that calls the `fetchRepos` function when the button is clicked:

2022-04-15 16:57 UTC, codewithkristian commented on content/pages/tutorials/github-Oauth-app-with-pages-functions/index.md
> +      console.log("hellloo ", data)
remove

2022-04-15 16:57 UTC, codewithkristian commented on content/pages/tutorials/github-Oauth-app-with-pages-functions/index.md
> +      localStorage.setItem("jwt", data.jwtencoded); // New line
```suggestion
      localStorage.setItem("jwt", data.jwtencoded);
```

2022-04-15 16:57 UTC, codewithkristian commented on content/pages/tutorials/github-Oauth-app-with-pages-functions/index.md
> +The `fetchRepos` function makes a request to the server and sends the JWT in local storage to `api/code`
```suggestion
Make a new `fetchRepos` function, which makes a request to the `/api/repos` endpoint, using `jwt` as part of the `Authorization` header:
```

you reference `api/code` here (should be `/api/code`, with leading slash), but use `/api/repos` in the `server` variable. make sure to double-check these URLs when writing, especially if you change the URLs during the process

2022-04-15 16:57 UTC, codewithkristian commented on content/pages/tutorials/github-Oauth-app-with-pages-functions/index.md
> +
we will do something with this data later, leave a comment to show that this function is not finished until we implement the server-side code

2022-04-15 16:57 UTC, codewithkristian commented on content/pages/tutorials/github-Oauth-app-with-pages-functions/index.md
> +You now have your user information and can now use that to get repos. Since you are making a `GET` request, you will need to send this request to another server route. The `fetchRepos` function will
usage of localhost is confusing - should be `/api/repos`

2022-04-15 16:57 UTC, codewithkristian commented on content/pages/tutorials/github-Oauth-app-with-pages-functions/index.md
> +Create a `functions/api/repos. js' file, and your files should look like this now
No need to restate file/folder structure here

2022-04-15 16:57 UTC, codewithkristian commented on content/pages/tutorials/github-Oauth-app-with-pages-functions/index.md
> +"`txt
```suggestion
```txt
```

almost every code sample in this tut uses this format - which does not render correctly in GitHub's preview or in preview deployment (see pic below)

<img width="772" alt="Screen Shot 2022-04-15 at 11 48 42 AM" src="https://user-images.githubusercontent.com/922353/163598016-94d4bb62-82fb-4f6c-8b65-7d436a8a0297.png">

recommend checking staging deployment _and_ github's preview to ensure that you've formatted correctly

2022-04-15 16:57 UTC, codewithkristian commented on content/pages/tutorials/github-Oauth-app-with-pages-functions/index.md
> +In the `repos.js` file export an async `onRequestGet` function to match the `GET` request.
```suggestion
In the `/api/repos.js` file, export an async `onRequestGet` function to match the `GET` request. 
```

2022-04-15 16:57 UTC, codewithkristian commented on content/pages/tutorials/github-Oauth-app-with-pages-functions/index.md
> +import { myVerySecretString } from "./code";
highly recommend moving this to an environment variable and pulling it directly out of Pages' attached bindings to this deployment

2022-04-15 16:57 UTC, codewithkristian commented on content/pages/tutorials/github-Oauth-app-with-pages-functions/index.md
> +    // res.json(repos); // Send repos to client
this looks like express code, but i'm unsure why it's here

2022-04-15 16:57 UTC, codewithkristian commented on content/pages/tutorials/github-Oauth-app-with-pages-functions/index.md
> +async function fetchRepos() {
it's unclear here that we're back in the client side JavaScript code. `showRepos` is our API/server function, and `fetchRepos` (very similarly named) is our client-side code. I would recommend adding a comment to each file (or using our header syntax to show the filename) in a code block to help reader's understand what they're looking at

2022-04-15 16:57 UTC, codewithkristian commented on content/pages/tutorials/github-Oauth-app-with-pages-functions/index.md
> +    } //New line
```suggestion
    }
```

2022-04-15 16:57 UTC, codewithkristian commented on content/pages/tutorials/github-Oauth-app-with-pages-functions/index.md
> +
**Blocker/must-fix**

I would expect there to be some portion of the guide here that actually shows users how to deploy the application

right now, the tutorial sets up a bunch of localhost routes and API requests, and if a user tried to deploy this, it would fail in production

add a new section that shows creating the project in pages, how to deploy the function, and get people excited about actually being able to share this project they built with other people. they have a prod URL they can share in their portfolios or with their friends!

2022-04-15 16:57 UTC, codewithkristian commented on content/pages/tutorials/github-Oauth-app-with-pages-functions/index.md
> +- [Functions](/pages/platform/functions/)
imagine that the reader is now hyped that they built a real-world example of auth with Cloudflare Pages + Functions: where would they go next? are there other tutorials or use-cases they should check out to continue their journey with the platform?

2022-04-15 16:57 UTC, codewithkristian commented on content/pages/tutorials/github-Oauth-app-with-pages-functions/index.md
> +---
Leaving some tutorial-wide feedback here so that it isn't missed

1. run every code sample here (particularly the JS ones) using prettier
2. code samples in general could benefit greatly from metadata that shows `filename`, or a `header` clarifying what the code does, as well as `lines` to indicate changed code in successive code blocks that iterate on a concept. see [example elsewhere in pages docs](https://github.com/cloudflare/cloudflare-docs/blob/production/content/pages/tutorials/build-a-blog-using-nuxt-and-sanity/index.md#rendering-content-for-a-blog-post)
3. there are a number of must-fix things that are hard blockers on this merging - see "Must-fix/blockers" called out in review comments. happy to set up time w/ you to chat about them if you're confused

2022-04-17 17:12 UTC, Ekwuno commented on content/pages/tutorials/github-Oauth-app-with-pages-functions/index.md
> +    // res.json(repos); // Send repos to client
I built it out in out in express at first and then I refactored to Functions

2022-04-18 01:57 UTC, Ekwuno commented on content/pages/tutorials/github-Oauth-app-with-pages-functions/index.md
> +  const res = await fetch(TokenURL, {
Since I split the config exports into two, I have a longer variable name and I think it might be a lot more readable to have a variable for the `TokenURL`.  I also use a variable for `oAuthQueryParams` below.

2022-04-18 02:05 UTC, Ekwuno commented on content/pages/tutorials/github-Oauth-app-with-pages-functions/index.md
> +const myVerySecretString = "*********"
We don’t have secrets in Pages deployment yet, but yes this should be in a `.env`. I'll update this and add steps to add this environment variable in the Pages environment when deploying.

2022-04-21 18:00 UTC, kristianfreeman requested changes

2022-04-21 18:00 UTC, codewithkristian commented on content/pages/tutorials/Add GitHub Oauth authorization with Pages Functions/index.md
> +In your OAuth App you have set the authorization callback URL and HomePage URL to `http://localhost:8788/` while working in dev mode, now you will have to update this URL to the URL of your deployed
Show how to do this

2022-04-21 18:00 UTC, kristianfreeman commented on content/pages/tutorials/Add GitHub Oauth authorization with Pages Functions/index.md
> +---
i'm glad hugo is able to take a folder name with spaces and properly convert it to a valid URL, but terminals don't work super well with folders with spaces in them. in addition, this folder name is super crucial to SEO and the URL that's generated based on it is one of 2-3 things google uses to match search results. i would change this to something more action oriented like "Build an OAuth application with GitHub", and match the folder (`build-an-oauth-application-with-github`)

2022-04-21 18:00 UTC, codewithkristian commented on content/pages/tutorials/Add GitHub Oauth authorization with Pages Functions/index.md
> +# Add GitHub Oauth authorization with Pages Functions
still seeing inconsistency between usage of `OAuth` and `Oauth`

2022-04-21 18:00 UTC, codewithkristian commented on content/pages/tutorials/Add GitHub Oauth authorization with Pages Functions/index.md
> +You will then encode the user information gotten from GitHub using JSON Web Tokens(JWTs) which allows you to share user secrets securly by encrypting them with a secret key. Then finally show a list
```suggestion
You will then encode the user information gotten from GitHub using JSON Web Tokens (JWTs), which allows you to share user secrets securely by encrypting them with a secret key. Using that JWT, you will be able to show a list of the user's repositories in a web page.
```

2022-04-21 18:00 UTC, kristianfreeman commented on content/pages/tutorials/Add GitHub Oauth authorization with Pages Functions/index.md
> +In this tutorial, you will learn how to build authentication into your application using OAuth, GitHub, and handle server requests using [Pages Functions](/pages/platform/functions/)and GitHub creden
```suggestion
In this tutorial, you will learn how to build authentication into your application using OAuth, GitHub, and handle server requests using [Pages Functions](/pages/platform/functions/) and GitHub credentials.
```

2022-04-21 18:00 UTC, codewithkristian commented on content/pages/tutorials/Add GitHub Oauth authorization with Pages Functions/index.md
> +
remove extra space

2022-04-21 18:00 UTC, codewithkristian commented on content/pages/tutorials/Add GitHub Oauth authorization with Pages Functions/index.md
> +You will run your project locally using [Wrangler 2](/pages/platform/functions/#develop-and-preview-locally), which hosts your project at http://localhost:8788/.
```suggestion
You will run your project locally using [Wrangler 2](/pages/platform/functions/#develop-and-preview-locally), which hosts your project at `http://localhost:8788/`.
```

2022-04-21 18:00 UTC, codewithkristian commented on content/pages/tutorials/Add GitHub Oauth authorization with Pages Functions/index.md
> +Set both URLs to http://localhost:8788/ so you can test locally, this will be changed when you deploy your application to production later in the tutorial.
```suggestion
Set both URLs to `http://localhost:8788/` so you can test locally. This will be changed when you deploy your application to production later in the tutorial.
```

2022-04-21 18:00 UTC, codewithkristian commented on content/pages/tutorials/Add GitHub Oauth authorization with Pages Functions/index.md
> +## Live example
remove additional header, following paragraph is OK to have in intro

2022-04-21 18:00 UTC, codewithkristian commented on content/pages/tutorials/Add GitHub Oauth authorization with Pages Functions/index.md
> +The source code for this application is [available on GitHub](https://github.com/Ekwuno/Cloudflare-functions-Oauth-example). It is a live Pages application with a [live demo](https://test-functions.c
we'll need to do additional review on the github repo before this PR is merged, including writing a README, adding licenses, etc. here's an example - https://github.com/cloudflare/workers-airtable-form

2022-04-21 18:00 UTC, codewithkristian commented on content/pages/tutorials/Add GitHub Oauth authorization with Pages Functions/index.md
> +  CLIENT_ID: "********",
document that this should be given to you by github

2022-04-21 18:00 UTC, codewithkristian commented on content/pages/tutorials/Add GitHub Oauth authorization with Pages Functions/index.md
> +  CLIENT_ID: "********",
document that these fields should be given to you by github

2022-04-21 18:00 UTC, codewithkristian commented on content/pages/tutorials/Add GitHub Oauth authorization with Pages Functions/index.md
> +
remove extra space

2022-04-21 18:00 UTC, codewithkristian commented on content/pages/tutorials/Add GitHub Oauth authorization with Pages Functions/index.md
> +Your `REDIRECT_URL` should be the same URL you used as your callback URL while setting up your application. For the sake of this tutorial and testing locally the `REDIRECT_URL` is set to http://local
```suggestion
Your `REDIRECT_URL` should be the same URL you used as your callback URL while setting up your application. For the sake of this tutorial and testing locally the `REDIRECT_URL` is set to `http://localhost:8788/`. However, after testing locally you will update this to the URL of your deployed site.
```

2022-04-21 18:00 UTC, codewithkristian commented on content/pages/tutorials/Add GitHub Oauth authorization with Pages Functions/index.md
> +Since your `CLIENT_SECRET` should not be exposed to the client you will have to define a  credential object specifically for the client and another for the server.
```suggestion
Since your `CLIENT_SECRET` should not be exposed to the client you will have to define two credential objects -- `client_credentials` for client configuration, and `server_credentials` for server configuration.
```

2022-04-21 18:00 UTC, codewithkristian commented on content/pages/tutorials/Add GitHub Oauth authorization with Pages Functions/index.md
> +Before you continue, you will need to install [query-string](https://www.npmjs.com/package/query-string) package, which allows you to parse and stringify URL query strings. Do this by running `npm in
```suggestion
Before you continue, you will need to install the [query-string](https://www.npmjs.com/package/query-string) package, which allows you to parse and stringify URL query strings. Do this by running `npm install query-string` at the root of your project.
```

2022-04-21 18:00 UTC, codewithkristian commented on content/pages/tutorials/Add GitHub Oauth authorization with Pages Functions/index.md
> +import  client_credentials from "../config";
```suggestion
import { client_credentials } from "../config";
```

This should be imported in the correct format

2022-04-21 18:00 UTC, codewithkristian commented on content/pages/tutorials/Add GitHub Oauth authorization with Pages Functions/index.md
> +      const repo = document.createElement("div")
The repo rendering isn't particularly exciting, and is completely unstyled. Can you add a CSS class to these divs and space it similarly to the CTA buttons 

<img width="686" alt="Screen Shot 2022-04-21 at 12 36 11 PM" src="https://user-images.githubusercontent.com/922353/164518417-574a7973-ac4a-4d92-8acb-c9968879eb68.png">

2022-04-21 18:00 UTC, kristianfreeman commented on content/pages/tutorials/Add GitHub Oauth authorization with Pages Functions/index.md
> +function  getAppauthorization() {
Still need to fix the casing here - `getAppAuthorization`

2022-04-21 18:00 UTC, codewithkristian commented on content/pages/tutorials/Add GitHub Oauth authorization with Pages Functions/index.md
> +From the code block above, you will notice we called an onload method to the window, and we do this so the functions will be fired when the whole page has loaded, including all dependent resources su
```suggestion
By calling the `getAppAuthorization` function inside of `window.onload`, the function will be fired when the whole page has loaded, including all dependent resources such as stylesheets and images. 
```

2022-04-21 18:00 UTC, kristianfreeman commented on content/pages/tutorials/Add GitHub Oauth authorization with Pages Functions/index.md
> +Notice the response type is a code; you will need to send this code to the server to be able to get the access token. We need to get the response code from the URL to do this. In the same file create
```suggestion
Notice the response type is a code; you will need to send this code to the server to be able to get the access token. We need to get the response code from the URL to do this. In the same file, create a `handleCode` function and update the `window.onload` function
```

2022-04-21 18:00 UTC, codewithkristian commented on content/pages/tutorials/Add GitHub Oauth authorization with Pages Functions/index.md
> +Notice the response type is a code; you will need to send this code to the server to be able to get the access token. We need to get the response code from the URL to do this. In the same file create
> Notice the response type is a code

Where does the reader notice this?

2022-04-21 18:00 UTC, codewithkristian commented on content/pages/tutorials/Add GitHub Oauth authorization with Pages Functions/index.md
> +|         └── Code.js
```suggestion
|         └── code.js
```

2022-04-21 18:00 UTC, kristianfreeman commented on content/pages/tutorials/Add GitHub Oauth authorization with Pages Functions/index.md
> +├── Client
```suggestion
├── client
```

need to be more careful about folder/file casing in tutorials

2022-04-21 18:00 UTC, codewithkristian commented on content/pages/tutorials/Add GitHub Oauth authorization with Pages Functions/index.md
> +The `handleCode` function will send `POST` requests, which means that the `functions/api/code.js` file needs to export an `onRequestPost` handler:
```suggestion
The `handleCode` function in the client-side JavaScript will send `POST` requests, which means that the `functions/api/code.js` file needs to export an `onRequestPost` handler:
```

2022-04-21 18:00 UTC, codewithkristian commented on content/pages/tutorials/Add GitHub Oauth authorization with Pages Functions/index.md
> +In the same `code.js` file, you will create an async function called `exchangeCodeForToken` that will take the code as an argument. You will need to use the config file parameters to query the `TOKEN
> you will use the query string package

This is `query-string`, right?

2022-04-21 18:00 UTC, codewithkristian commented on content/pages/tutorials/Add GitHub Oauth authorization with Pages Functions/index.md
> +Import qs from "query-string" and called the `.parse` method on the response; you can get the access token by getting the value of `access_token`. As seen in the code block below:
```suggestion
Import `qs` from `query-string` and called the `.parse` method on the response; you can get the access token by getting the value of `access_token`, as seen in the code block below: 
```

> Import qs from "query-string"

Use backticks for module names, package names, etc.

> you can get the access token by getting the value of `access_token`. As seen in the code block below: 

sentence fragment

2022-04-21 18:00 UTC, codewithkristian commented on content/pages/tutorials/Add GitHub Oauth authorization with Pages Functions/index.md
> +After installing, in `/api/code` import `jwt` from the the Cloudflare-Worker-JWT package to encode and decode the JWT.
The code sample down in line 487 shows how to actually import this package. Either show a smaller version of that code sample (just importing `jwt`) or move this paragraph down to right before that code sample, right now this paragraph is isolated from any code sample and is unclear

2022-04-21 18:00 UTC, codewithkristian commented on content/pages/tutorials/Add GitHub Oauth authorization with Pages Functions/index.md
> +Your secret key can be any set of strings and will be available in the `code.js` file, using `env`.
> any set of strings

what does this mean?

2022-04-21 18:00 UTC, codewithkristian commented on content/pages/tutorials/Add GitHub Oauth authorization with Pages Functions/index.md
> +    redirect_url: server_credentials.REDIRECT_URL,
`server_credentials` is used here before it is imported later in the tutorial

2022-04-21 18:00 UTC, codewithkristian commented on content/pages/tutorials/Add GitHub Oauth authorization with Pages Functions/index.md
> +import server_credentials from "../config";
Import as module here

```suggestion
import { server_credentials } from "../config";
```

My concern reading this and my previous review on `client_credentials` earlier in the tutorial is that this may not have been tested in production after rewriting the content. currently, the way this is referenced would mean that the whole file would be imported as `server_credentials`, and referencing the actual `server_credentials` object _inside_ of that file would mean writing `server_credentials.server_credentials.REDIRECT_URL`. have you tested this new code in production?

2022-04-21 18:00 UTC, codewithkristian commented on content/pages/tutorials/Add GitHub Oauth authorization with Pages Functions/index.md
> +    console.log(jwtencoded);
remove

2022-04-21 18:00 UTC, codewithkristian commented on content/pages/tutorials/Add GitHub Oauth authorization with Pages Functions/index.md
> +To access your Workers KV namespace when using Wrangler locally, update your run command to:
```suggestion
To access your Workers KV namespace when using Wrangler locally, restart your locally running application with the `--kv` flag:
```

2022-04-21 18:00 UTC, codewithkristian commented on content/pages/tutorials/Add GitHub Oauth authorization with Pages Functions/index.md
> +While you can use JWTs for validating users, you can also use them to know when a user is logged in or not and then give them access to other parts of your application based on this JWT.
```suggestion
While you can use JWTs for validating users, you can also use them to know when a user is logged, and give them access to other parts of your application based on the presence of a JWT. 
```

2022-04-21 18:00 UTC, codewithkristian commented on content/pages/tutorials/Add GitHub Oauth authorization with Pages Functions/index.md
> +In your application, you can do this by setting the JWT to localStorage. In the `client/index.js` file, you will update your `handleCode` function to set the encoded JWT from the server to a JWT valu
```suggestion
In your application, you can do this by setting the JWT to `localStorage`. In the `client/index.js` file, you will update your `handleCode` function to set the encoded JWT from the server to a JWT value: 
```

2022-04-21 18:00 UTC, codewithkristian commented on content/pages/tutorials/Add GitHub Oauth authorization with Pages Functions/index.md
> +    requestButton.style.display = "block";
shouldn't we also hide the login button if this JWT is available?

2022-04-21 18:00 UTC, codewithkristian commented on content/pages/tutorials/Add GitHub Oauth authorization with Pages Functions/index.md
> +import server_credentials from "../config";
fix import

2022-04-21 18:00 UTC, codewithkristian commented on content/pages/tutorials/Add GitHub Oauth authorization with Pages Functions/index.md
> +So far, you have been testing locally with Wrangler. To have a production site you can deploy to Cloudflare Pages using GitHub or GitLab. After creating a new repository, prepare and push your local
> To have a production site you can deploy to Cloudflare Pages using GitHub or GitLab.

sentence fragment

2022-04-21 18:00 UTC, codewithkristian commented on content/pages/tutorials/Add GitHub Oauth authorization with Pages Functions/index.md
> +Deploy you site by logging into the [Cloudflare dashboard](https://dash.cloudflare.com/) > **Account Home** > **Pages** and selecting **Create a project**. Select the new GitHub repository that you c
```suggestion
Deploy your site by logging into the [Cloudflare dashboard](https://dash.cloudflare.com/) > **Account Home** > **Pages** and selecting **Create a project**. Select the new GitHub repository that you created and, in the **Set up builds and deployments** section, provide the following information:
```

2022-04-21 18:00 UTC, codewithkristian commented on content/pages/tutorials/Add GitHub Oauth authorization with Pages Functions/index.md
> +<div>
are these divs needed?

2022-04-21 18:00 UTC, codewithkristian commented on content/pages/tutorials/Add GitHub Oauth authorization with Pages Functions/index.md
> +In the **Environment variables (advanced)** section add the variable name and value as it is in your `.env` file to be able to use in production and preview. Then click save and deploy
```suggestion
In the **Environment variables (advanced)** section, add the variable name and value, matching the same information in your `.env` file.
```

screenshot here

2022-04-21 18:00 UTC, codewithkristian commented on content/pages/tutorials/Add GitHub Oauth authorization with Pages Functions/index.md
> +In your OAuth App you have set the authorization callback URL and HomePage URL to `http://localhost:8788/` while working in dev mode, now you will have to update this URL to the URL of your deployed
```suggestion
While working on the application locally, the authorization callback URL and homepage URL were set to `http://localhost:8788/`. With a deployed application, you will have to update these URLs to your deployed Pages URL, such as `FILL_ME_IN_WITH_EXAMPLE_PRODUCTION_PAGES_DEV_URL`.
```

2022-04-21 18:00 UTC, codewithkristian commented on content/pages/tutorials/Add GitHub Oauth authorization with Pages Functions/index.md
> +By doing this, you will enable your OAuth app interact with your project as expected.
```suggestion
By doing this, you will enable your OAuth app interact with your project as expected.
```

?

2022-04-21 18:00 UTC, codewithkristian commented on content/pages/tutorials/Add GitHub Oauth authorization with Pages Functions/index.md
> +After you have deployed your application, you will have to update your KV bindings. Currently, there is no way to automatically move the binding from your `.mf` folder to the dashboard.
```suggestion
After you have deployed your application, you will have to update your KV bindings. Currently, there is no way to automatically move the binding from your `.mf` folder to the dashboard. 
```

I know `.mf` is miniflare, but considering that you haven't talked about Miniflare or this folder, this is confusing

2022-04-21 18:00 UTC, codewithkristian commented on content/pages/tutorials/Add GitHub Oauth authorization with Pages Functions/index.md
> +To add your KV bindings Within Pages, first create your KV namespace by going to **Workers** > **KV** > **Create Namespace**.
```suggestion
To add your KV bindings within your Pages applicaiton, first  your KV namespace by going to **Workers** > **KV** > **Create Namespace**. 
```

Screenshot or other guidance on where to find this is always useful

2022-04-21 18:00 UTC, codewithkristian commented on content/pages/tutorials/Add GitHub Oauth authorization with Pages Functions/index.md
> +The KV Namespace on Pages must be the same as the Namespace used in your local environment.
```suggestion
The KV Namespace on Pages must be the same as the Namespace used in your local environment.
```

Show - what is the namespace you had devs use so far in this tutorial?

2022-04-21 18:00 UTC, codewithkristian commented on content/pages/tutorials/Add GitHub Oauth authorization with Pages Functions/index.md
> +After creating your namespace, choose from the list of KV namespaces that you created from the dashboard by going to **your Pages project** > **Settings** > **Functions** > **KV namespace bindings**.
screenshot

2022-04-21 18:00 UTC, codewithkristian commented on content/pages/tutorials/Add GitHub Oauth authorization with Pages Functions/index.md
> +Select *Add binding* and input a Variable name, and select a KV namespace from the list of your existing Workers KV namespaces. You will need to repeat this for both the Production and Preview enviro
screenshot

2022-04-21 18:00 UTC, codewithkristian commented on content/pages/tutorials/Add GitHub Oauth authorization with Pages Functions/index.md
> +In this tutorial, you built and deployed an OAuth app and its back-end logic using Cloudflare Pages with its Workers integration. You created serverless routes that handled Authentication, fetched us
think this was removed from my last set of review, but again - now what? If someone wants to continue to level up, where do they go next?

2022-04-21 18:00 UTC, codewithkristian commented on content/pages/tutorials/Add GitHub Oauth authorization with Pages Functions/index.md
> +---
**IMPORTANT**

I've left a number of review comments here that will be hidden if you rename the file/folder - Git isn't smart and will think this is a brand new file. Please address feedback and then move the file/folder once we've completed this phase of review, _in a separate commit_

2022-04-21 19:06 UTC, Ekwuno commented on content/pages/tutorials/Add GitHub Oauth authorization with Pages Functions/index.md
> +      const repo = document.createElement("div")
I have this as a todo after this initial reviews are don't for this Tutorial. Disregard the styling of the demo for now.

2022-04-21 19:09 UTC, Ekwuno commented on content/pages/tutorials/Add GitHub Oauth authorization with Pages Functions/index.md
> +After you have deployed your application, you will have to update your KV bindings. Currently, there is no way to automatically move the binding from your `.mf` folder to the dashboard.
I think it's unnecessary to go into detail of the `.mf` file since it's only created when you're using KV or DO locally. Unless we'd like to discuss how wrangler 2 is powered locally, which I think it's a bit out of scope.

2022-04-22 11:49 UTC, GregBrimble commented on content/pages/tutorials/Add GitHub Oauth authorization with Pages Functions/index.md
> +  CLIENT_SECRET: "***********",
These shouldn't exist in source code. You should use environment variables (and once we support for them, secrets).

2022-04-22 11:50 UTC, GregBrimble commented on content/pages/tutorials/Add GitHub Oauth authorization with Pages Functions/index.md
> +Set up Wrangler in your project by running `npm install wrangler@beta` at the root of your project. You can see your project locally by running the following command:
Depending on when this goes out, you'll want to remove `@beta`.

2022-04-22 11:52 UTC, GregBrimble commented on content/pages/tutorials/Add GitHub Oauth authorization with Pages Functions/index.md
> +Before you continue, you will need to install [query-string](https://www.npmjs.com/package/query-string) package, which allows you to parse and stringify URL query strings. Do this by running `npm in
It's cleaner to use the platform's built-in [`URLSearchParams`](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams).

```js
export const onRequest = ({ request }) => {
  const url = new URL(request.url)
  const searchParams = url.searchParams
  return new Response(searchParams.get('code'))
}
```

2022-04-22 11:53 UTC, GregBrimble commented on content/pages/tutorials/Add GitHub Oauth authorization with Pages Functions/index.md
> +Before you continue, you will need to install [query-string](https://www.npmjs.com/package/query-string) package, which allows you to parse and stringify URL query strings. Do this by running `npm in
```js
const url = new URL(location.href)
const searchParams = url.searchParams
console.log(searchParams.get('code'))
```

Or this if you're doing it client-side ^

2022-04-22 11:54 UTC, GregBrimble commented on content/pages/tutorials/Add GitHub Oauth authorization with Pages Functions/index.md
> +  const query = qs.stringify(oAuthQueryParams);
new URLSearchParams(oAuthQueryParams).toString()

2022-04-22 11:56 UTC, GregBrimble commented on content/pages/tutorials/Add GitHub Oauth authorization with Pages Functions/index.md
> +window.onload = function () {
`addEventListener` is a bit better because it supports registering multiple handlers.

2022-04-22 11:57 UTC, GregBrimble commented on content/pages/tutorials/Add GitHub Oauth authorization with Pages Functions/index.md
> +filename: client/index.js
This whole piece could be done with HTMLRewriter and not require any client-side JS.

2022-04-22 11:58 UTC, GregBrimble commented on content/pages/tutorials/Add GitHub Oauth authorization with Pages Functions/index.md
> +filename: client/index.js
Same again here. I'd do this as an `onRequestGet` Function which does all of this server-side, so you don't need to have a separate `/api` at all.

2022-04-22 12:01 UTC, GregBrimble commented on content/pages/tutorials/Add GitHub Oauth authorization with Pages Functions/index.md
> +import jwt from "@tsndr/cloudflare-worker-jwt";
I would be hesitant to trust a somewhat obscure JWT lib. There are _so many_ examples of libraries which have had vulns because they didn't implement checking logic correctly. I'd rather go with a more established library: https://jwt.io/libraries

2022-04-22 12:05 UTC, GregBrimble commented on content/pages/tutorials/Add GitHub Oauth authorization with Pages Functions/index.md
> +    await env.kv_userDatabase.put(
This binding is different to the one you configure with the command: `KV_NAMESPACE`

2022-11-04 13:55 UTC, closed without merging