[Pages] How-to for custom branch aliases
cloudflare/cloudflare-docs pull request #4132
Opened 2022-04-17 13:59 UTC by KianNH

Guide on creating custom hostnames for specific branches on Pages.

2022-04-19 13:29 UTC, deadlypants1973 requested changes

2022-04-19 13:29 UTC, deadlypants1973 commented on content/pages/how-to/custom-branch-aliases.md
> +In this tutorial, you will learn how to add a custom branch alias (`staging.example.com`) that will point to a specific branch (`staging`) on your pages project.
```suggestion
In this guide, you will learn how to add a custom domain (`staging.example.com`) that will point to a specific branch (`staging`) on your pages project.
```

2022-04-19 13:29 UTC, deadlypants1973 commented on content/pages/how-to/custom-branch-aliases.md
> +At the moment, this setup is only supported when using Cloudflare DNS.
```suggestion
Currently, this setup is only supported when using Cloudflare DNS.
```

2022-04-19 13:29 UTC, deadlypants1973 commented on content/pages/how-to/custom-branch-aliases.md
> +If you attempt to follow this tutorial using an external DNS provider, your custom alias will be sent to the production branch of the Pages project.
```suggestion
If you attempt to follow this guide using an external DNS provider, your custom alias will be sent to the production branch of your Pages project.
```

2022-04-19 13:29 UTC, deadlypants1973 commented on content/pages/how-to/custom-branch-aliases.md
> +In this tutorial, you will learn how to add a custom branch alias (`staging.example.com`) that will point to a specific branch (`staging`) on your pages project.
Hello, this is a great addition to the docs, thank you! If I may, can I add some content notes to make this publish ready?

This intro paragraph has a 'what will the user do' sentence. Could you include a 'why the user will do this' and 'how the user will do this' sentence to flesh out the purpose of this guide?

2022-04-19 13:29 UTC, deadlypants1973 commented on content/pages/how-to/custom-branch-aliases.md
> +Firstly, make sure that you've made a commit on the branch you'd like to set up an alias for - this will prompt a build in pages.
```suggestion
First, make sure that you have made a commit on the branch you would like to set up an alias for. This will prompt a build in Pages.
```

2022-04-19 13:29 UTC, deadlypants1973 commented on content/pages/how-to/custom-branch-aliases.md
> +5.  Click on **Continue** and then **Activate domain**
```suggestion
1.  Log in to the [Cloudflare dashboard](https://dash.cloudflare.com/login).
2. In Account Home, go to **Pages**.
3.  Select your project.
4.  Select **Custom domains** > **Setup a custom domain**.
5. Input the domain you would like to use as the custom branch alias, such as `staging.example.com`
6.  Select **Continue** > **Activate domain**
```

2022-04-19 13:29 UTC, deadlypants1973 commented on content/pages/how-to/custom-branch-aliases.md
> +![Pages Custom Domains Overview](../media/pages_custom_domain-1.png)
```suggestion
![Follow the instructions below to access the custom domains overview in the Pages dashboard.](../media/pages_custom_domain-1.png)
```

2022-04-19 13:29 UTC, deadlypants1973 commented on content/pages/how-to/custom-branch-aliases.md
> +![Pages Custom Domains Activation](../media/pages_custom_domain-2.png)
```suggestion
![After selecting your custom domain, you will be asked to activate it.](../media/pages_custom_domain-2.png)
```

2022-04-19 13:29 UTC, deadlypants1973 commented on content/pages/how-to/custom-branch-aliases.md
> +![Pages Custom Domains Activation](../media/pages_custom_domain-2.png)
Both of these screenshots need to be the white background version.

2022-04-19 13:29 UTC, deadlypants1973 commented on content/pages/how-to/custom-branch-aliases.md
> +After doing this, you'll want to go into the [DNS settings](https://dash.cloudflare.com/?to=/:account/:zone/dns) for the
```suggestion
After activating your custom domain, go to [DNS](https://dash.cloudflare.com/?to=/:account/:zone/dns) for the `example.com` zone and change the `staging` record's value to include our branch alias.
```

2022-04-19 13:29 UTC, deadlypants1973 commented on content/pages/how-to/custom-branch-aliases.md
> +`example.com` zone and change the `staging` record's value to include our branch alias.
```suggestion
```

2022-04-19 13:29 UTC, deadlypants1973 commented on content/pages/how-to/custom-branch-aliases.md
> +After doing this, you'll want to go into the [DNS settings](https://dash.cloudflare.com/?to=/:account/:zone/dns) for the
Is this sentence asking for the user to find the ('staging') Name and change the Content to the branch alias value (`staging.your-project.pages.dev`) ? It is best that the instructional wording match the wording of the dashboard to avoid confusion.

2022-04-19 13:29 UTC, deadlypants1973 commented on content/pages/how-to/custom-branch-aliases.md
> +In this instance, we'll want to change `your-project.pages.dev` to `staging.your-project.pages.dev`.
```suggestion
In this instance, change `your-project.pages.dev` to `staging.your-project.pages.dev`.
```

2022-04-19 14:15 UTC, deadlypants1973 commented
> Guide on creating custom hostnames for specific branches on Pages.

Also! before you make edits: this is a great addition but @WalshyDev let me know that we are going to be adding support for this in a month or so, it may not be worth the effort to publish this. But we can merge in after edits, temporarily. It's up to you how much effort you'd like to put into it at this stage as the writer. After the UI support is added, the guide content will need to change.

2022-04-19 14:17 UTC, KianNH commented
Currently it's just on https://03544d2c.cloudflare-docs-github.pages.dev/pages/how-to/custom-branch-aliases/ from my own Pages project which I link to in the Discord when people ask - if it's going to be changing fairly soon then it might be worth holding off & just adapting this in the future when the native functionality is in the dashboard.

2022-04-23 22:00 UTC, KianNH commented on content/pages/how-to/custom-branch-aliases.md
> +At the moment, this setup is only supported when using Cloudflare DNS.
Added suggestion into latest commit.

2022-04-23 22:00 UTC, KianNH commented on content/pages/how-to/custom-branch-aliases.md
> +If you attempt to follow this tutorial using an external DNS provider, your custom alias will be sent to the production branch of the Pages project.
Added suggestion into latest commit.

2022-04-23 22:00 UTC, KianNH commented on content/pages/how-to/custom-branch-aliases.md
> +Firstly, make sure that you've made a commit on the branch you'd like to set up an alias for - this will prompt a build in pages.
Added suggestion into latest commit.

2022-04-23 22:01 UTC, KianNH commented on content/pages/how-to/custom-branch-aliases.md
> +5.  Click on **Continue** and then **Activate domain**
Added suggestion into latest commit.

2022-04-23 22:01 UTC, KianNH commented on content/pages/how-to/custom-branch-aliases.md
> +![Pages Custom Domains Activation](../media/pages_custom_domain-2.png)
Added suggestion into latest commit.

2022-04-23 22:01 UTC, KianNH commented on content/pages/how-to/custom-branch-aliases.md
> +![Pages Custom Domains Overview](../media/pages_custom_domain-1.png)
Added suggestion into latest commit.

2022-04-23 22:01 UTC, KianNH commented on content/pages/how-to/custom-branch-aliases.md
> +After doing this, you'll want to go into the [DNS settings](https://dash.cloudflare.com/?to=/:account/:zone/dns) for the
Added suggestion into latest commit.

2022-04-23 22:03 UTC, KianNH commented on content/pages/how-to/custom-branch-aliases.md
> +`example.com` zone and change the `staging` record's value to include our branch alias.
Added suggestion into latest commit.

2022-04-23 22:03 UTC, KianNH commented on content/pages/how-to/custom-branch-aliases.md
> +In this instance, we'll want to change `your-project.pages.dev` to `staging.your-project.pages.dev`.
Added suggestion into latest commit.

2022-04-23 22:04 UTC, KianNH commented
Added the changes from the review & added in another screenshot at the end regarding changing the DNS record.

2022-04-24 01:15 UTC, WalshyDev requested changes

2022-04-24 01:15 UTC, WalshyDev commented on content/pages/how-to/custom-branch-aliases.md
> +In this tutorial, you will learn how to add a custom branch alias (`staging.example.com`) that will point to a specific branch (`staging`) on your Pages project.
You're adding a custom domain rather than a branch alias. Branch aliases already exist, you're using that rather than making a new one.

2022-04-24 01:15 UTC, WalshyDev commented on content/pages/how-to/custom-branch-aliases.md
> +First, make sure that you have made a commit on the branch you would like to set up an alias for. This will prompt a build in Pages.
I'd change this to make sure you have at least 1 successful deployment.

builds won't exist for direct uploads

2022-04-24 01:15 UTC, WalshyDev commented on content/pages/how-to/custom-branch-aliases.md
> +Next, add a custom domain under your Pages project for `staging.example.com`.
for `staging.example.com` (Or what you'd want your custom subdomain to be).

---

Kate can probably give better wording...

2022-04-25 13:00 UTC, KianNH commented on content/pages/how-to/custom-branch-aliases.md
> +Next, add a custom domain under your Pages project for `staging.example.com`.
> for your desired custom domain, i.e `staging.example.com`

Something like that?

2022-04-26 13:18 UTC, KianNH commented on content/pages/how-to/custom-branch-aliases.md
> +In this tutorial, you will learn how to add a custom branch alias (`staging.example.com`) that will point to a specific branch (`staging`) on your Pages project.
```suggestion
In this tutorial, you will learn how to add a custom domain (`staging.example.com`) that will point to a specific branch (`staging`) on your Pages project.
```

2022-04-26 13:18 UTC, KianNH commented on content/pages/how-to/custom-branch-aliases.md
> +First, make sure that you have made a commit on the branch you would like to set up an alias for. This will prompt a build in Pages.
```suggestion
First, make sure that you have a successful deployment on the branch you would like to set up an alias for.
```

2022-04-26 13:18 UTC, KianNH commented on content/pages/how-to/custom-branch-aliases.md
> +Next, add a custom domain under your Pages project for `staging.example.com`.
```suggestion
Next, add a custom domain under your Pages project for your desired custom domain, i.e `staging.example.com`.
```

2022-04-26 13:36 UTC, WalshyDev commented on content/pages/how-to/custom-branch-aliases.md
> +Next, add a custom domain under your Pages project for `staging.example.com`.
yep that's good

2022-05-03 12:28 UTC, deadlypants1973 commented on content/pages/how-to/custom-branch-aliases.md
> +First, make sure that you have made a commit on the branch you would like to set up an alias for. This will prompt a build in Pages.
Should alias be changed to custom domain here? @WalshyDev

2022-05-03 12:29 UTC, WalshyDev commented on content/pages/how-to/custom-branch-aliases.md
> +First, make sure that you have made a commit on the branch you would like to set up an alias for. This will prompt a build in Pages.
yes, good spot

```suggestion
First, make sure that you have a successful deployment on the branch you would like to set up a custom domain for.
```

2022-05-03 12:39 UTC, deadlypants1973 commented on content/pages/how-to/custom-branch-aliases.md
> +# Adding custom branch aliases
same inquiry as before @WalshyDev

2022-05-03 12:43 UTC, deadlypants1973 commented on content/pages/how-to/custom-branch-aliases.md
> +# Adding custom branch aliases
```suggestion
# Add a custom domain to a branch
```

2022-05-03 12:43 UTC, deadlypants1973 commented on content/pages/how-to/custom-branch-aliases.md
> +title: Adding custom branch aliases
```suggestion
title: Add a custom domain to a branch
```

2022-05-03 12:43 UTC, deadlypants1973 approved these changes

2022-05-03 12:48 UTC, WalshyDev approved these changes
LGTM, let's go!

2022-05-03 12:52 UTC, merged