[ZT] Add SSH logging page
cloudflare/cloudflare-docs pull request #4151
Opened 2022-04-18 22:11 UTC by ranbel

2022-04-19 12:18 UTC, kennyj42 commented on content/cloudflare-one/_partials/_ssh-modify-sshd.md
> +The following procedure makes two changes to the `sshd_config` file on the remote target machine. The first change requires that you uncomment a field already set in most default configurations; the
Should we add a callout that their sshd_config file may differ and this is just a baseline configuration?

2022-04-19 12:19 UTC, kennyj42 commented on content/cloudflare-one/identity/users/short-lived-certificates.md
> -## 1. **Secure a server behind Cloudflare Access**.
We can't delete the existing Short-lived certs documentation because this is still a valid way to enable SSH access using Cloudflared. This needs to be in addition

2022-04-19 12:20 UTC, kennyj42 requested changes
Looks good. Biggest change is that we need to do this in addition to existing Short Lived Certs docs

2022-04-19 13:25 UTC, ranbel commented on content/cloudflare-one/identity/users/short-lived-certificates.md
> -## 1. **Secure a server behind Cloudflare Access**.
The short-lived cert page should still be there: https://0ff9bbf2.cloudflare-docs-7ou.pages.dev/cloudflare-one/identity/users/short-lived-certificates/

I moved some of the duplicate content into a "partial" so that it can be easily reused across different pages.

2022-04-19 13:32 UTC, ranbel commented on content/cloudflare-one/_partials/_ssh-modify-sshd.md
> +The following procedure makes two changes to the `sshd_config` file on the remote target machine. The first change requires that you uncomment a field already set in most default configurations; the
I don't think users would get confused about their file being different if we're not providing an example sshd_config to compare against.

2022-04-19 20:52 UTC, kennyj42 commented on content/cloudflare-one/identity/users/short-lived-certificates.md
> -## 1. **Secure a server behind Cloudflare Access**.
Gotcha, makes sense

2022-04-19 20:52 UTC, kennyj42 approved these changes

2022-04-21 13:26 UTC, abracchi-tw approved these changes

2022-04-21 13:26 UTC, abracchi-tw commented on content/cloudflare-one/_partials/_ssh-restart-server.md
> +Once you have modified your SSHD configuration, you still need to restart the SSH service on the remote machine. Commands are also provided below for servers running systemd. You can execute both `re
```suggestion
Once you have modified your SSHD configuration, you still need to restart the SSH service on the remote machine. Commands are also provided below for servers running systemd. You can execute both `restart` commands.
```
This made me wonder, why should I run both? Could we give more details? (also should we backtick `systemd`?)

2022-04-21 13:26 UTC, abracchi-tw commented on content/cloudflare-one/_partials/_ssh-usernames.md
> +In order to match a user to their SSO identity, the user's **Unix username must match their email address prefix**. For example, `jdoe` must be registered in your Okta or GSuite organization as `jdoe
Bold is normally only used for UI element names (like buttons) and as more of a visual device for items in bullet point contexts (e.g. first word of a bulleted element). If you think this sentence should be emphasized, have you thought about having an `Aside`?

2022-04-21 13:26 UTC, abracchi-tw commented on content/cloudflare-one/policies/filtering/network-policies/ssh-logging.md
> +## Configure SSH Command Logging
I see why you would want to incorporate this under step 7. I think it's fine here (otherwise that step would become huge), but maybe we can add `(Optional)` to the header so that the user won't think it's yet another step they have to take after step 8?

2022-04-21 14:01 UTC, ranbel commented on content/cloudflare-one/_partials/_ssh-restart-server.md
> +Once you have modified your SSHD configuration, you still need to restart the SSH service on the remote machine. Commands are also provided below for servers running systemd. You can execute both `re
Maybe we can leave out the last two sentences. Users who don't know how to restart can run both commands by default.

2022-04-21 14:02 UTC, ranbel commented on content/cloudflare-one/_partials/_ssh-usernames.md
> +In order to match a user to their SSO identity, the user's **Unix username must match their email address prefix**. For example, `jdoe` must be registered in your Okta or GSuite organization as `jdoe
```suggestion
In order to match a user to their SSO identity, the user's Unix username must match their email address prefix. For example, `jdoe` must be registered in your Okta or GSuite organization as `jdoe@example.com`.
```

2022-04-21 14:04 UTC, ranbel commented on content/cloudflare-one/_partials/_ssh-usernames.md
> +In order to match a user to their SSO identity, the user's **Unix username must match their email address prefix**. For example, `jdoe` must be registered in your Okta or GSuite organization as `jdoe
Good point. The phrase is already in the heading so I think we can unbold it.

2022-04-21 14:09 UTC, ranbel commented on content/cloudflare-one/policies/filtering/network-policies/ssh-logging.md
> +## Configure SSH Command Logging
```suggestion
## (Optional) Configure SSH Command Logging
```

2022-04-21 14:09 UTC, ranbel commented on content/cloudflare-one/policies/filtering/network-policies/ssh-logging.md
> +6. (Optional) Enable **SSH Command Logging**. Follow [these required steps](#configure-ssh-command-logging) to complete the configuration.
```suggestion
6. (Optional) Enable **SSH Command Logging**. Follow [these required steps](#(optional)-configure-ssh-command-logging) to complete the configuration.
```

2022-04-21 14:16 UTC, ranbel commented on content/cloudflare-one/policies/filtering/network-policies/ssh-logging.md
> +## Configure SSH Command Logging
Would `(Optional)` be confusing if we call it `required` in Step 7?

2022-04-21 14:19 UTC, abracchi-tw commented on content/cloudflare-one/policies/filtering/network-policies/ssh-logging.md
> +## Configure SSH Command Logging
You're right, but don't we also call it `(Optional)` in step 7.6? maybe we should rephrase that step too

2022-04-21 16:57 UTC, merged