Update Worker site to Pages migration guide
cloudflare/cloudflare-docs pull request #4233
Opened 2022-04-27 12:28 UTC by Ekwuno

Update the migration guide to show support for Pages Functions,  Redirects and Headers.

2022-04-27 12:50 UTC, WalshyDev requested changes

2022-04-27 12:50 UTC, WalshyDev commented on content/pages/migrations/migrating-from-workers/index.md
> +Cloudflare Pages provides built-in defaults for every aspect of serving your site. You can port custom behaviour in your Workers script — such as custom caching logic — to your Cloudflare Pages. Usin
```suggestion
Cloudflare Pages provides built-in defaults for every aspect of serving your site. You can port custom behaviour in your Workers script — such as custom caching logic — to your Cloudflare Pages project using [Functions](/pages/platform/functions/). This enables an easy to use file-based routing system. You can also migrate your custom headers and redirects to Pages. 
```

2022-04-27 12:50 UTC, WalshyDev commented on content/pages/migrations/migrating-from-workers/index.md
> +A project is limited to 1,000 static redirects and 100 dynamic redirects, for a combined total of 1,100 redirects. Each redirect declaration has a 1,000-character limit. Malformed definitions are ign
```suggestion
A project is limited to 2,000 static redirects and 100 dynamic redirects, for a combined total of 2,100 redirects. Each redirect declaration has a 1,000-character limit. Malformed definitions are ignored. If there are multiple redirects for the same source path, the topmost redirect is applied. 
```

2022-04-27 12:50 UTC, WalshyDev commented on content/pages/migrations/migrating-from-workers/index.md
> +In addition to an `_redirects` file, Cloudflare Pages currently offers [Bulk Redirects(beta)](/pages/how-to/use-bulk-redirects/), which handles redirects that surpasses the 1,100 redirect rules limit
```suggestion
In addition to an `_redirects` file, Cloudflare Pages currently offers [Bulk Redirects (beta)](/pages/how-to/use-bulk-redirects/), which handles redirects that surpasses the 1,100 redirect rules limit set by Pages.
```

2022-04-27 12:50 UTC, WalshyDev commented on content/pages/migrations/migrating-from-workers/index.md
> +Your header files can also be moved into a `_headers` folder in your publish directory. It is important to note that custom headers defined in the `_headers` file are not currently applied to respons
```suggestion
Your custom headers can also be moved into a `_headers` file in your publish directory. It is important to note that custom headers defined in the `_headers` file are not currently applied to responses from Functions, even if the Function route matches the URL pattern. To learn more about handling headers, refer to [Headers](/pages/platform/headers/).
```

2022-04-27 12:50 UTC, WalshyDev commented on content/pages/migrations/migrating-from-workers/index.md
>  ## Cleaning up your old application and assigning the domain
We don't actually say how to link the custom domain in here. We only say to remove the Worker. This leaves the user with only their pages.dev and a domain without anything being served.

2022-04-27 13:04 UTC, Ekwuno commented on content/pages/migrations/migrating-from-workers/index.md
> +A project is limited to 1,000 static redirects and 100 dynamic redirects, for a combined total of 1,100 redirects. Each redirect declaration has a 1,000-character limit. Malformed definitions are ign
I'll have to update the limit in the other places redirects are mentioned.

2022-04-27 13:33 UTC, Ekwuno commented on content/pages/migrations/migrating-from-workers/index.md
>  ## Cleaning up your old application and assigning the domain
The steps for linking can be found in the getting started guide linked a few lines up. I will make it more obvious.

2022-05-03 09:50 UTC, deadlypants1973 reviewed
PCX review (1)

2022-05-03 09:50 UTC, deadlypants1973 commented on content/pages/migrations/migrating-from-workers/index.md
> +Cloudflare Pages provides built-in defaults for every aspect of serving your site. You can port custom behaviour in your Workers script — such as custom caching logic — to your Cloudflare Pages proje
```suggestion
Cloudflare Pages provides built-in defaults for every aspect of serving your site. You can port custom behavior in your Worker — such as custom caching logic — to your Cloudflare Pages project using [Functions](/pages/platform/functions/). This enables an easy-to-use file-based routing system. You can also migrate your custom headers and redirects to Pages. 
```

2022-05-03 09:50 UTC, deadlypants1973 commented on content/pages/migrations/migrating-from-workers/index.md
>  1.  An application built with a [static site tool](/pages/how-to/) or a static collection of HTML, CSS and JavaScript
```suggestion
1.  An application built with a [static site tool](/pages/how-to/) or a static collection of HTML, CSS and JavaScript.
```

2022-05-03 09:50 UTC, deadlypants1973 commented on content/pages/migrations/migrating-from-workers/index.md
> +2. If using a static site tool, a build directory (called `bucket` in `wrangler.toml`) where the static project builds HTML, CSS, and JS
```suggestion
2. If using a static site tool, a build directory (called `bucket` in `wrangler.toml`) where the static project builds HTML, CSS, and JavaScript.
```

2022-05-03 09:50 UTC, deadlypants1973 commented on content/pages/migrations/migrating-from-workers/index.md
> +3. A Workers application for serving that directory
```suggestion
3. A Worker application for serving that build directory.
```

2022-05-03 09:50 UTC, deadlypants1973 commented on content/pages/migrations/migrating-from-workers/index.md
> +When moving to Cloudflare Pages, remove the Workers application and any associated `wrangler.toml` configuration files or build output. Instead, note and record your **build command** (if you have on
```suggestion
When moving to Cloudflare Pages, remove the Workers application and any associated `wrangler.toml` configuration files or build output. Instead, note and record your build command (if you have one), and the `bucket` field, or build directory, from the `wrangler.toml` file in your project's directory.
```
Are 'build command' and 'build directory' fields in the wrangler.toml file? If so, we should put them in backticks.

2022-05-03 09:50 UTC, deadlypants1973 commented on content/pages/migrations/migrating-from-workers/index.md
> +You can migrate your redirects to Pages, by creating a `_redirects` file in your publish directory. Cloudflare currently offers limited support for advanced redirects. More support will be added in t
```suggestion
You can migrate your redirects to Pages, by creating a `_redirects` file in your publish directory. Cloudflare currently offers limited support for advanced redirects. More support will be added in the future. For a list of support types, refer to the [Redirects documentaion](/pages/platform/redirects/). 
```

2022-05-03 09:50 UTC, deadlypants1973 commented on content/pages/migrations/migrating-from-workers/index.md
> +
```suggestion
```

2022-05-03 09:50 UTC, deadlypants1973 commented on content/pages/migrations/migrating-from-workers/index.md
> +Before you deploy, you will need to delete the Workers application to start sending requests to Cloudflare Pages.
Is this the user's old Workers Sites project?

2022-05-03 09:50 UTC, deadlypants1973 commented on content/pages/migrations/migrating-from-workers/index.md
> +Before you deploy, you will need to delete the Workers application to start sending requests to Cloudflare Pages.
```suggestion
Before you deploy, you will need to delete your Workers application to start sending requests to Cloudflare Pages.
```

2022-05-03 13:58 UTC, Ekwuno commented on content/pages/migrations/migrating-from-workers/index.md
> +Before you deploy, you will need to delete the Workers application to start sending requests to Cloudflare Pages.
It is, but also refers to any functionalities they were handling with Workers.

2022-05-03 15:20 UTC, deadlypants1973 reviewed
Cleaning up header titles

2022-05-03 15:20 UTC, deadlypants1973 commented on content/pages/migrations/migrating-from-workers/index.md
>  ## Migrating Headers and Redirects.
```suggestion
## Migrate headers and redirects
```

2022-05-03 15:20 UTC, deadlypants1973 commented on content/pages/migrations/migrating-from-workers/index.md
>  ## Cleaning up your old application and assigning the domain
```suggestion
## Clean up your old application and assign a domain
```

2022-05-03 15:23 UTC, deadlypants1973 commented on content/pages/migrations/migrating-from-workers/index.md
>  ## Removing unnecessary code
```suggestion
## Remove unnecessary code
```

2022-05-03 15:23 UTC, deadlypants1973 commented on content/pages/migrations/migrating-from-workers/index.md
> +Before you deploy, you will need to delete your Workers application to start sending requests to Cloudflare Pages.
```suggestion
Before you deploy, you will need to delete your old Workers application to start sending requests to Cloudflare Pages.
```

2022-05-03 15:23 UTC, deadlypants1973 commented on content/pages/migrations/migrating-from-workers/index.md
>  ## Creating a new Pages project
```suggestion
## Create a new Pages project
```

2022-05-03 16:16 UTC, Ekwuno commented on content/pages/migrations/migrating-from-workers/index.md
> +When moving to Cloudflare Pages, remove the Workers application and any associated `wrangler.toml` configuration files or build output. Instead, note and record your **build command** (if you have on
Build is a field and build directory refers to the actual value of the bucket 

`[site]
bucket = "./public" # Build directory 
entry-point = "workers-site"`

2022-05-03 16:22 UTC, rita3ko commented on content/pages/migrations/migrating-from-workers/index.md
> +Before you deploy, you will need to delete the Workers application to start sending requests to Cloudflare Pages.
Do we want to recommend that they delete the entire application? Why not just the route? Seems scary.

2022-05-03 16:37 UTC, deadlypants1973 commented on content/pages/migrations/migrating-from-workers/index.md
> +1.  An application built with a [static site tool](/pages/how-to/) or a static collection of HTML, CSS and JavaScript.
```suggestion
1. An application built with a [static site tool](/pages/how-to/) or a static collection of HTML, CSS and JavaScript.
```

2022-05-06 16:18 UTC, Cherry commented on content/pages/migrations/migrating-from-workers/index.md
> +3. A Worker application for serving that build directory.
I'd suggest mentioning the `workers-site` directory here, since that's the default used by most (all?) Workers Sites templates, and "Worker application" confused me a little when reading.

```suggestion
3. A Worker application for serving that build directory. For most projects, this is likely to be the `workers-site` directory.
```

2022-05-06 16:20 UTC, WalshyDev requested changes

2022-05-06 16:20 UTC, WalshyDev commented on content/pages/migrations/migrating-from-workers/index.md
> +By Migrating to Cloudflare Pages, you will be able to access features like [preview deployments](/pages/platform/preview-deployments/) and automatic branch deploys with no extra configuration needed.
```suggestion
By migrating to Cloudflare Pages, you will be able to access features like [preview deployments](/pages/platform/preview-deployments/) and automatic branch deploys with no extra configuration needed.
```

2022-05-06 16:20 UTC, WalshyDev commented on content/pages/migrations/migrating-from-workers/index.md
> +You can migrate your redirects to Pages, by creating a `_redirects` file in your publish directory. Cloudflare currently offers limited support for advanced redirects. More support will be added in t
It's been called output throughout this so far. 
```suggestion
You can migrate your redirects to Pages, by creating a `_redirects` file in your output directory. Pages currently offers limited support for advanced redirects. More support will be added in the future. For a list of support types, refer to the [Redirects documentaion](/pages/platform/redirects/). 
```

2022-05-06 16:20 UTC, WalshyDev commented on content/pages/migrations/migrating-from-workers/index.md
> +In addition to an `_redirects` file, Cloudflare Pages currently offers [Bulk Redirects (beta)](/pages/how-to/use-bulk-redirects/), which handles redirects that surpasses the 2,100 redirect rules limi
We don't own the bulk redirects product, probably shouldn't sound like we do
```suggestion
In addition to an `_redirects` file, Cloudflare also offers [Bulk Redirects (beta)](/pages/how-to/use-bulk-redirects/), which handles redirects that surpasses the 2,100 redirect rules limit set by Pages.
```

2022-05-06 16:20 UTC, WalshyDev commented on content/pages/migrations/migrating-from-workers/index.md
> +Your custom headers can also be moved into a `_headers` file in your publish directory. It is important to note that custom headers defined in the `_headers` file are not currently applied to respons
```suggestion
Your custom headers can also be moved into a `_headers` file in your output directory. It is important to note that custom headers defined in the `_headers` file are not currently applied to responses from Functions, even if the Function route matches the URL pattern. To learn more about handling headers, refer to [Headers](/pages/platform/headers/).
```

2022-05-10 11:19 UTC, deadlypants1973 approved these changes

2022-05-10 11:19 UTC, deadlypants1973 commented on content/pages/migrations/migrating-from-workers/index.md
> +Cloudflare Pages provides built-in defaults for every aspect of serving your site. You can port custom behavior in your Worker — such as custom caching logic — to your Cloudflare Pages project using
```suggestion
Cloudflare Pages provides built-in defaults for every aspect of serving your site. You can port custom behavior in your Worker — such as custom caching logic — to your Cloudflare Pages project using [Functions](/pages/platform/functions/). This enables an easy-to-use, file-based routing system. You can also migrate your custom headers and redirects to Pages. 
```

2022-05-10 11:19 UTC, deadlypants1973 commented on content/pages/migrations/migrating-from-workers/index.md
> +1. An application built with a [static site tool](/pages/how-to/) or a static collection of HTML, CSS and JavaScript.
```suggestion
1. An application built with a [static site tool](/pages/how-to/) or a static collection of HTML, CSS and JavaScript files.
```

2022-05-10 11:19 UTC, deadlypants1973 commented on content/pages/migrations/migrating-from-workers/index.md
> +2. If using a static site tool, a build directory (called `bucket` in `wrangler.toml`) where the static project builds HTML, CSS, and JavaScript.
```suggestion
2. If using a static site tool, a build directory (called `bucket` in `wrangler.toml`) where the static project builds your HTML, CSS, and JavaScript files.
```

2022-05-10 11:19 UTC, deadlypants1973 commented on content/pages/migrations/migrating-from-workers/index.md
> +## Migrating headers and redirects
```suggestion
## Migrate headers and redirects
```

2022-05-10 11:19 UTC, deadlypants1973 commented on content/pages/migrations/migrating-from-workers/index.md
>  ## Removing unnecessary code
```suggestion
## Remove unnecessary code
```

2022-05-10 11:19 UTC, deadlypants1973 commented on content/pages/migrations/migrating-from-workers/index.md
>  ## Creating a new Pages project
```suggestion
## Create a new Pages project
```

2022-05-10 11:19 UTC, deadlypants1973 commented on content/pages/migrations/migrating-from-workers/index.md
> +### Using git provider
```suggestion
### Connect to your git provider
```

2022-05-10 11:19 UTC, deadlypants1973 commented on content/pages/migrations/migrating-from-workers/index.md
>  After you have recorded your **build command** and **build directory** in a separate location, remove everything else from your application, and push the new version of your project up to GitHub. Fol
```suggestion
After you have recorded your **build command** and **build directory** in a separate location, remove everything else from your application, and push the new version of your project up to your git provider. Follow the [Get started guide](/pages/get-started/) to add your project to Cloudflare Pages, using the **build command** and **build directory** that you saved earlier.
```
Does this work for GitLab too? If so, changed to git provider to reflect that.

2022-05-10 11:19 UTC, deadlypants1973 commented on content/pages/migrations/migrating-from-workers/index.md
> +If your Workers site has its custom build settings, you can bring your pre-built assets to Pages with [Direct uploads](/pages/platform/direct-upload/). In addition, you can serve your website's asset
```suggestion
If your Workers site has its custom build settings, you can bring your prebuilt assets to Pages with [Direct Uploads](/pages/platform/direct-upload/). In addition, you can serve your website's assets right to the Cloudflare edge network by either using the [Wrangler CLI](/workers/wrangler/get-started/) or the drag and drop option. 
```

2022-05-10 11:55 UTC, WalshyDev approved these changes

2022-05-10 11:55 UTC, merged