use-worker-for-ab-testing-in-pages
cloudflare/cloudflare-docs pull request #4300
Opened 2022-05-05 13:02 UTC by Ekwuno

WIP doc for ab testing with Workers in Pages.

2022-05-23 13:25 UTC, deadlypants1973 requested changes

2022-05-23 13:25 UTC, deadlypants1973 commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +In this guide, you will learn how to use [Page Functions](/pages/platform/functions/) for A/B testing in your Pages projects. A/B testing is a user experience research methodology applied when compar
```suggestion
In this guide, you will learn how to use [Pages Functions](/pages/platform/functions/) for A/B testing in your Pages projects. A/B testing is a user experience research methodology applied when comparing two or more versions of a webpage or application. With A/B testing, you can serve two or more versions of a webpage to users and divide traffic to your site.
```

2022-05-23 13:25 UTC, deadlypants1973 commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +## Settting up your Pages Function
```suggestion
## Set up your Pages Function
```

2022-05-23 13:25 UTC, deadlypants1973 commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +## Adding middleware logic
```suggestion
## Add middleware logic
```

2022-05-23 13:25 UTC, deadlypants1973 commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +
```suggestion
```

2022-05-23 13:25 UTC, deadlypants1973 commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +# Deploy to Cloudflare Pages
```suggestion
## Deploy to Cloudflare Pages
```

2022-05-23 13:25 UTC, deadlypants1973 commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +While setting up different versions of your application to determine the experience for your users with A/B testing is unique to your specific use case, the process of setting up A/B testing can be b
```suggestion
Configuring different versions of your application for A/B testing will be unique to your specific use case. For all developers, A/B testing setup can be simplified into a few helpful principles.
```

2022-05-23 13:25 UTC, deadlypants1973 commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +Depending on the number of versions you have(this guide uses two), you can assign your users into experimental groups. To ensure that a user remains in the group you have given, a cookie will be set
```suggestion
Depending on the number of application versions you have (this guide uses two), you can assign your users into experimental groups. To ensure that a user remains in the group you have given, a cookie will be set and stored in the browser. Then, based on the value of the cookie, the browser will sever the route associated with that cookie.
```

2022-05-23 13:25 UTC, deadlypants1973 commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +It is helpful to use cookies because you want users to be served the same version every time they come to your application, even when they refresh. This will help keep things consistent for future ro
```suggestion
Cookies are helpful because they allow users to be served the same version of your application every time they visit and when they refresh the site. This will help keep the version served consistent for future rollouts. 
```

2022-05-23 13:25 UTC, deadlypants1973 commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +It is helpful to use cookies because you want users to be served the same version every time they come to your application, even when they refresh. This will help keep things consistent for future ro
What are 'things'? This needs to be descriptive.

2022-05-23 13:25 UTC, deadlypants1973 commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +Depending on the number of versions you have(this guide uses two), you can assign your users into experimental groups. To ensure that a user remains in the group you have given, a cookie will be set
What route is severed here? This part is unclear.

2022-05-23 13:25 UTC, deadlypants1973 commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +After you have gotten the value from the cookie, you can then have a conditional rendering set up that checks the value of the existing cookie and then assigns a group. Without a cookie, you will giv
Were there steps before this to explain cookie setup? 
How did the user get to 'getting a value'? 
What does getting a cookie look like?

2022-05-23 13:25 UTC, deadlypants1973 commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +In your project, you can handle the logic for A/B testing using [Pages Functions](/pages/platform/functions/). Pages Functions allows you to handle server logic from within your Pages project. Create
```suggestion
In your project, you can handle the logic for A/B testing using [Pages Functions](/pages/platform/functions/). Pages Functions allows you to handle server logic from within your Pages project. 

To begin, go to your Pages project and create a `/functions` directory. Your application server logic will live in the `/functions` folder. 
```

2022-05-23 13:25 UTC, deadlypants1973 commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +Pages Functions have utility functions that can reuse chunks of logic which are executed before and/or after route handlers. These are called [middleware](/pages/platform/functions/#adding-middleware
```suggestion
Then, in your `/functions` directory, create a `_middleware.js` file. Pages Functions have utility functions that can reuse chunks of logic which are executed before and/or after route handlers. These are called [middleware](/pages/platform/functions/#adding-middleware). Following this guide, you want to intercept the request before it gets to the server, making ideal use of middleware.
```

2022-05-23 13:25 UTC, deadlypants1973 commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +Creating your middleware file at the base of your functions folder means that it will run for all routes on your project. To learn more about [middleware routing](/pages/platform/functions/#middlewar
```suggestion
When you create your `_middleware.js` file at the base of your `/functions` folder, the middleware will run for all routes on your project. Learn more about [middleware routing](/pages/platform/functions/#middleware-routing).
```

2022-05-23 13:25 UTC, deadlypants1973 commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +Creating your middleware file at the base of your functions folder means that it will run for all routes on your project. To learn more about [middleware routing](/pages/platform/functions/#middlewar
What is "it"? Change to a proper noun.

2022-05-23 13:25 UTC, deadlypants1973 commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +Following the functions naming convention, the `_middleware.js` file export a single async `OnRequest` function that accepts a `request`, `env` and `next`  as an argument.
```suggestion
Following the Functions naming convention, the `_middleware.js` file exports a single async `OnRequest` function that accepts a `request`, `env` and `next`  as an argument. 
```

2022-05-23 13:25 UTC, deadlypants1973 commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +Following the functions naming convention, the `_middleware.js` file export a single async `OnRequest` function that accepts a `request`, `env` and `next`  as an argument.
Is this referring to Pages Functions naming convention? or just general JS functions?

2022-05-23 13:25 UTC, deadlypants1973 commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +To identify the cookie, we assign it in the browser. We will give it a unique name; for this example, create a variable above your async function. You can also define your routes. We will call the se
```suggestion
To identify the cookie, assign it in the browser and give it a unique name. For this example, create a variable above your async function. You can also define your routes. Following this guide, call the second route `/test`.
```

2022-05-23 13:25 UTC, deadlypants1973 commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +In our A/B testing, we want to be able to send a user to particular routes based on the presence of a cookie value. First, we need to intercept the URL request.
```suggestion
In your A/B testing, you want to be able to send a user to particular routes based on the presence of a cookie value. To do this, you must first intercept the URL request. 
```

2022-05-23 13:25 UTC, deadlypants1973 commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +Based on the URL pathname, we will check what cookie value is present in the header, and based on the value; we will either set the base route or the `/test` route and fetch the assets for that route
```suggestion
Based on the URL pathname, check what cookie value is present in the header. Based on the value, you will either set the base route or the `/test` route and fetch the assets for that route. 
```

2022-05-23 13:25 UTC, deadlypants1973 commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +On the other hand, if the cookie isn't present, you will have to assign one. You can generate numbers randomly by using the `Math.random()` Javascript method and getting whole numbers by calling a `M
```suggestion
If the cookie value is not present, you will have to assign one. You can generate numbers randomly by using the `Math.random()` Javascript method and getting whole numbers by calling a `Math.floor()` on the function.
```

2022-05-23 13:25 UTC, deadlypants1973 commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +On the other hand, if the cookie isn't present, you will have to assign one. You can generate numbers randomly by using the `Math.random()` Javascript method and getting whole numbers by calling a `M
Being clear here, is what is not present the cookie or the cookie header?

2022-05-23 13:25 UTC, deadlypants1973 commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +To make the values into percentages, multiple `Math.random()` by 100 and call`Math.floor()` so that all the percentages can be whole numbers. Our default version is given a value of `current`.
```suggestion
To make the number genrated into percentages, multiple `Math.random()` by 100 and call `Math.floor()` so that all the percentages can be whole numbers. Your default cookie version is given a value of `current`.
```

2022-05-23 13:25 UTC, deadlypants1973 commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +To make the values into percentages, multiple `Math.random()` by 100 and call`Math.floor()` so that all the percentages can be whole numbers. Our default version is given a value of `current`.
Is there more than one cookie? Is that why 'values' instead of 'value'?

2022-05-23 13:25 UTC, deadlypants1973 commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +If the percentage is lower than 50, you will assign the version to `new` and based on the value randomly generated; we will set the cookie and serve the assets. After the conditional block pass the r
What does the percentage represent, a cookie value? 
What is the version? The application version or cookie?

2022-05-23 13:25 UTC, deadlypants1973 commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +Now that you have set up your `functions/_middleware.js` file in your project. Deploy your site to Pages by logging in to the Cloudflare dashboard > Account Home > Pages and selecting Create a projec
```suggestion
Now that you have set up your `functions/_middleware.js` file in your project you are ready to deploy your project. Deploy your site to Pages by logging in to the [Cloudflare dashboard](https://dash.cloudflare.com/login) > **Account Home** > **Pages** and selecting **Create a project**. Select your git repository that you created and, in the **Set up builds and deployments** section, provide the following information:
```

2022-05-23 13:25 UTC, deadlypants1973 commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +Now that you have set up your `functions/_middleware.js` file in your project. Deploy your site to Pages by logging in to the Cloudflare dashboard > Account Home > Pages and selecting Create a projec
Is this feature only possible with GitHub? if not, this needs a correction.

2022-05-23 13:25 UTC, deadlypants1973 commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +After you have deployed your application, you will see your middleware Function under Functions > Configuration in the current build.
```suggestion
After you have deployed your application, you will see your middleware Function under **Pages** > **Settings** > **Functions** > Configuration in the current build. 
```
"Configuration in the current build. " this doesn't show up on my dash, do you have a screenshot?

2022-05-23 13:43 UTC, Ekwuno commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +Depending on the number of versions you have(this guide uses two), you can assign your users into experimental groups. To ensure that a user remains in the group you have given, a cookie will be set
The route that is associated with the cookie will be served. It depends on the route to cookie assignment defined by the developer. In the guide, I show that the `current` cookie will be served the `/` route and `new` cookie will give `/test`.

2022-05-23 13:45 UTC, Ekwuno commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +It is helpful to use cookies because you want users to be served the same version every time they come to your application, even when they refresh. This will help keep things consistent for future ro
Updated

2022-05-23 13:48 UTC, Ekwuno commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +Following the functions naming convention, the `_middleware.js` file export a single async `OnRequest` function that accepts a `request`, `env` and `next`  as an argument.
Pages Functions convention.

2022-05-23 13:49 UTC, Ekwuno commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +On the other hand, if the cookie isn't present, you will have to assign one. You can generate numbers randomly by using the `Math.random()` Javascript method and getting whole numbers by calling a `M
The cookie header

2022-05-23 13:51 UTC, Ekwuno commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +Now that you have set up your `functions/_middleware.js` file in your project. Deploy your site to Pages by logging in to the Cloudflare dashboard > Account Home > Pages and selecting Create a projec
Should be git provider, you are right.

2022-05-23 13:55 UTC, Ekwuno commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +After you have deployed your application, you will see your middleware Function under Functions > Configuration in the current build.
It shows up when you deploy a function under Configuration.

2022-05-23 14:50 UTC, Ekwuno commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +Depending on the number of application versions you have (this guide uses two), you can assign your users into experimental groups. To ensure that a user remains in the group you have given, a cookie
Add the names of application versions

2022-05-23 15:08 UTC, deadlypants1973 commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +After you have deployed your application, you will see your middleware Function under **Pages** > **Settings** > **Functions** > Configuration.
I don't see this in my dash. Can you provide a screenshot?

2022-05-24 12:07 UTC, Ekwuno commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +After you have deployed your application, you will see your middleware Function under **Pages** > **Settings** > **Functions** > Configuration.
@deadlypants1973 you don't see build output directory?

2022-05-24 13:34 UTC, Ekwuno commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +After you have gotten the value from the cookie, you can then have a conditional rendering set up that checks the value of the existing cookie and then assigns a group. Without a cookie, you will giv
I have updated the section. Let me know if it reads better now.

2022-05-24 13:50 UTC, Ekwuno commented
@deadlypants1973 I realised that the file name is `use-worker-for-ab-testing-in-pages.md` and the title is `Use Pages Functions for A/B testing`. I will change this after PCX reviews so we keep the comments while you are reviewing.

2022-05-24 13:54 UTC, Ekwuno commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +After you have deployed your application, you will see your middleware Function under **Pages** > **Settings** > **Functions** > Configuration.
<img width="702" alt="Screenshot 2022-05-24 at 14 54 12" src="https://user-images.githubusercontent.com/35943047/170052766-b99a1517-6a9c-43d4-9422-f305393f421a.png">

2022-05-24 14:00 UTC, Ekwuno commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +If the percentage is lower than 50, you will assign the version to `new` and based on the value randomly generated; we will set the cookie and serve the assets. After the conditional block pass the r
```suggestion
If the percentage of the number genrated is lower than 50, you will assign the cookie version to `new` and based on the percentage randomly generated; we will set the cookie and serve the assets. After the conditional block pass the request to `next()`, this will pass the request back to the browser.
```

2022-05-24 14:10 UTC, Ekwuno commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +To make the values into percentages, multiple `Math.random()` by 100 and call`Math.floor()` so that all the percentages can be whole numbers. Our default version is given a value of `current`.
I have updated this, let me know how it reads now.

2022-05-24 14:10 UTC, Ekwuno commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +If the percentage is lower than 50, you will assign the version to `new` and based on the value randomly generated; we will set the cookie and serve the assets. After the conditional block pass the r
How does it read now?

2022-05-25 09:56 UTC, deadlypants1973 commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +After you have deployed your application, you will see your middleware Function under **Pages** > **Settings** > **Functions** > Configuration.
```suggestion
After you have deployed your application, you will see your middleware Function in the Cloudflare dashboard under **Pages** > **Settings** > **Functions** > **Configuration**. 
```

2022-05-25 14:05 UTC, deadlypants1973 requested changes

2022-05-25 14:05 UTC, deadlypants1973 commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +In this guide, you will learn how to use [Pages Functions](/pages/platform/functions/) for A/B testing in your Pages projects. A/B testing is a user experience research methodology applied when compa
```suggestion
In this guide, you will learn how to use [Pages Functions](/pages/platform/functions/) for A/B testing in your Pages projects. A/B testing is a user experience research methodology applied when comparing two or more versions of a web page or application. With A/B testing, you can serve two or more versions of a webpage to users and divide traffic to your site.
```

2022-05-25 14:05 UTC, deadlypants1973 commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +Depending on the number of application versions you have (this guide uses two), you can assign your users into experimental groups. The experimental groups in this guide are the base route `/` and th
"(this guide uses two)" are these "/" and "/test"?

2022-05-25 14:05 UTC, deadlypants1973 commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +You can use any cookie library for example, [Js cookie](https://www.npmjs.com/package/js-cookie) to generate cookies. This guide assigns a local value to a `cookieName` variable and uses that as the
```suggestion
You can use any cookie library (for example, [`js-cookie`](https://www.npmjs.com/package/js-cookie)) to generate cookies. This guide assigns a local value to a `cookieName` variable and uses that as the cookie value. Depending on the cookie value, a route is served. 

The cookie assignment is done randomly by using `Math.random()` which generates a list of random decimal numbers. You can make the numbers a whole number by calling the `Math.floor()` method on `Math.random()` like this: `Math.floor(Math.random())` and to make sure that you have a maximum range of numbers you can multiply by 100. This means that you can now think of your assignments in terms of percentages.

Your percentage generator code should look like this `Math.floor(Math.random() * 100)`.
```

`Math.floor(Math.random() * 100)` sticks out very randomly here. Can we integrate it into a sentence?

2022-05-25 14:05 UTC, deadlypants1973 commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +Cookies are helpful because they allow users to be served the same version of your application every time they visit and when they refresh the site. This will help keep the version served consistent
```suggestion
Cookies are helpful because they allow users to be served the same version of your application every time they visit and refresh your site. This will help keep the served version consistent for future rollouts. 
```

2022-05-25 14:05 UTC, deadlypants1973 commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +After you have gotten the value from the cookie, you can then have a conditional rendering set up that checks the value of the existing cookie and then assigns a group. Without a cookie, you will giv
Rather than 'gotten' isn't it set? Because the cookie value is something the developer needs to set themselves?

2022-05-25 14:05 UTC, deadlypants1973 commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +Then, in your `/functions` directory, create a `_middleware.js` file. Pages Functions have utility functions that can reuse chunks of logic which are executed before and/or after route handlers. Thes
```suggestion
Pages Functions have utility functions that can reuse chunks of logic which are executed before and/or after route handlers. These are called [middleware](/pages/platform/functions/#adding-middleware). Following this guide, you will want to intercept requests before they get to your origin server, making ideal use of middleware.

In your `/functions` directory, create a `_middleware.js` file. 


```

2022-05-25 14:05 UTC, deadlypants1973 commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +Then, in your `/functions` directory, create a `_middleware.js` file. Pages Functions have utility functions that can reuse chunks of logic which are executed before and/or after route handlers. Thes
I edited the last sentence, is this what you were trying to say?

2022-05-25 14:05 UTC, deadlypants1973 commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +To identify the cookie, assign it in the browser and give it a unique name. For this example, create a variable above your async function. You can also define your routes. Following this guide, call
```suggestion
To identify the cookie, assign it in the browser and give it a unique name. Create a variable above your async function. Here, you can define the second route as `newHomepagePathName` and assign it to the`/test. As seen in the code below:
```

2022-05-25 14:05 UTC, deadlypants1973 commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +To identify the cookie, assign it in the browser and give it a unique name. For this example, create a variable above your async function. You can also define your routes. Following this guide, call
"You can also define your routes." Is this being done in the example below? Where?

2022-05-25 14:05 UTC, deadlypants1973 commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +If the cookie value is not present, you will have to assign one. You can generate numbers randomly by using the `Math.random()` Javascript method and getting whole numbers by calling a `Math.floor()`
```suggestion
If the cookie value is not present, you will have to assign one. You can generate numbers randomly by using the `Math.random()` method and getting whole numbers by calling a `Math.floor()` on the function.
```

2022-05-25 14:05 UTC, deadlypants1973 commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +If the percentage of the number generated is lower than 50, you will assign the cookie version to `new` and based on the percentage randomly generated; we will set the cookie and serve the assets. Af
```suggestion
If the percentage of the number generated is lower than 50, you will assign the cookie version to `new`. Based on the percentage randomly generated, you will set the cookie and serve the assets. After the conditional block, pass the request to `next()`. This will pass the request back to the browser.
```

2022-05-25 14:05 UTC, deadlypants1973 commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +Now that you have set up your `functions/_middleware.js` file in your project you are ready to deploy your project. Deploy your site to Pages by logging in to the [Cloudflare dashboard](https://dash.
```suggestion
Now that you have set up your `functions/_middleware.js` file in your project you are ready to deploy with Pages. Log in to the [Cloudflare dashboard](https://dash.cloudflare.com/login) > **Account Home** > **Pages** and select **Create a project**. Select your git repository that you created and, in the **Set up builds and deployments** section, provide the following information:
```

2022-05-25 15:05 UTC, Ekwuno commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +After you have gotten the value from the cookie, you can then have a conditional rendering set up that checks the value of the existing cookie and then assigns a group. Without a cookie, you will giv
Yea that makes sense. 
```suggestion
After you have set the value from the cookie, you can then have a conditional rendering set up that checks the value of the existing cookie and then assigns a group. Without a cookie, you will give one and set the URL. 
```

2022-05-25 15:10 UTC, Ekwuno commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +Then, in your `/functions` directory, create a `_middleware.js` file. Pages Functions have utility functions that can reuse chunks of logic which are executed before and/or after route handlers. Thes
Yea! I flipped the sentences to introduce middleware before the file creation. Let me know how this reads.

2022-05-25 15:17 UTC, Ekwuno commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +To identify the cookie, assign it in the browser and give it a unique name. For this example, create a variable above your async function. You can also define your routes. Following this guide, call
I updated that section, how does it read now?

2022-05-25 15:22 UTC, Ekwuno commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +Depending on the number of application versions you have (this guide uses two), you can assign your users into experimental groups. The experimental groups in this guide are the base route `/` and th
Yes, they are. I think the sentence shows this already since it's only dealing with two groups and versions.

2022-05-26 15:10 UTC, Ekwuno commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +You can use any cookie library for example, [Js cookie](https://www.npmjs.com/package/js-cookie) to generate cookies. This guide assigns a local value to a `cookieName` variable and uses that as the
Let me know how it reads now. I couldn’t think of what to call it so I went with "percentage generator code"

2022-05-31 13:53 UTC, deadlypants1973 commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +To make the number genrated into percentages, multiple `Math.random()` by 100 and call `Math.floor()` so that all the percentages can be whole numbers. Your default cookie version is given a value of
```suggestion
To make the number genrated into percentages, multiply `Math.random()` by `100` and call `Math.floor()` so that all the percentages can be whole numbers. Your default cookie version is given a value of `current`.
```

2022-05-31 13:53 UTC, deadlypants1973 commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +If the percentage of the number generated is lower than 50, you will assign the cookie version to `new`. Based on the percentage randomly generated, you will set the cookie and serve the assets. Afte
```suggestion
If the percentage of the number generated is lower than `50`, you will assign the cookie version to `new`. Based on the percentage randomly generated, you will set the cookie and serve the assets. After the conditional block, pass the request to `next()`. This will pass the request back to the browser.
```

2022-05-31 13:53 UTC, deadlypants1973 commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +The cookie assignment is done randomly by using `Math.random()` which generates a list of random decimal numbers. You can make the numbers a whole number by calling the `Math.floor()` method on `Math
```suggestion
The cookie assignment is done randomly by using `Math.random()` which generates a list of random decimal numbers. You can make the numbers a whole number by calling the `Math.floor()` method on `Math.random()` like this: `Math.floor(Math.random())` and to make sure that you have a maximum range of numbers you can multiply by `100`. This means that you can now think of your assignments in terms of percentages.
```

2022-05-31 13:53 UTC, deadlypants1973 commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +
```suggestion
```

2022-05-31 13:53 UTC, deadlypants1973 commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +Following the Functions naming convention, the `_middleware.js` file exports a single async `OnRequest` function that accepts a `request`, `env` and `next`  as an argument.
```suggestion
Following the Functions naming convention, the `_middleware.js` file exports a single async `OnRequest` function that accepts a `request`, `env` and `next` as an argument. 
```

2022-05-31 13:53 UTC, deadlypants1973 commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +To identify the cookie, assign it in the browser and give it a unique name. Create a variable above your async function. Here, you can define the second route as `newHomepagePathName` and assign it t
```suggestion
To identify the cookie, assign it in the browser and give it a unique name. Create a variable above your async function. Here, you can define the second route as `newHomepagePathName` and assign it to`/test`:
```

2022-06-01 13:24 UTC, WalshyDev requested changes

2022-06-01 13:24 UTC, WalshyDev commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +You can use any cookie library (for example, [`js-cookie`](https://www.npmjs.com/package/js-cookie)) to generate cookies. This guide assigns a local value to a `cookieName` variable and uses that as
> This guide assigns a local value to a `cookieName` variable and uses that as the cookie value.

I feel this sentence can just be simplified to "This guide will assign a value for the A/B experiment and create a cookie."

It took me a few reads to understand what this was saying

2022-06-01 13:24 UTC, WalshyDev commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +The cookie assignment is done randomly by using `Math.random()` which generates a list of random decimal numbers. You can make the numbers a whole number by calling the `Math.floor()` method on `Math
Technically pseudo-random but err, not sure we care to make to say that (cc: @deadlypants1973)

```suggestion
The cookie assignment is done randomly by using `Math.random()` which generates a random decimal number. You can make the number a whole number by calling the `Math.floor()` method on `Math.random()` like this: `Math.floor(Math.random())` and to make sure that you have a maximum range of numbers you can multiply by `100`. This means that you can now think of your assignments in terms of percentages.
```

2022-06-01 13:24 UTC, WalshyDev commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +Following the Functions naming convention, the `_middleware.js` file exports a single async `OnRequest` function that accepts a `request`, `env` and `next` as an argument.
```suggestion
Following the Functions naming convention, the `_middleware.js` file exports a single async `onRequest` function that accepts a `request`, `env` and `next` as an argument. 
```

2022-06-01 13:24 UTC, WalshyDev commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +const abtest = async({request, next, env}) => {
Do we want to do object deconstruction? Assuming we're targeting this at users who aren't really experienced at JS this adds a barrier to entry.

```suggestion
const abTest = async ({request, next, env}) => {
```

2022-06-01 13:24 UTC, WalshyDev commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +export const onRequest = [abtest]
```suggestion
export const onRequest = [abTest]
```

2022-06-01 13:24 UTC, WalshyDev commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +To identify the cookie, assign it in the browser and give it a unique name. Create a variable above your async function. Here, you can define the second route as `newHomepagePathName` and assign it t
```suggestion
To identify the cookie, assign it in the browser and give it a unique name. Create a variable above your async function. Here, you can define the second route as `newHomepagePathName` and assign it `/test`:
```

2022-06-01 13:24 UTC, WalshyDev commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +const abtest = async({request, next, env}) => {
```suggestion
const abTest = async ({request, next, env}) => {
```

2022-06-01 13:24 UTC, WalshyDev commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +export const onRequest = [abtest]
```suggestion
export const onRequest = [abTest]
```

2022-06-01 13:24 UTC, WalshyDev commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +In your A/B testing, you want to be able to send a user to particular routes based on the presence of a cookie value. To do this, you must first intercept the URL request.
```suggestion
In your A/B testing, you want to be able to send a user to particular routes based on the presence of a cookie value. To do this, you must first intercept the request. 
```

2022-06-01 13:24 UTC, WalshyDev commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +
```suggestion
const cookieName = "ab-test-cookie"
const newHomepagePathName = "/test"

const abTest = async ({request, next, env}) => {
  /*
  Todo: 
  1. Assign cookies based on randomly genrated percentage, then serve
  */

  const url = new URL(request.url)
  if (url.pathname === "/") {
    // if cookie ab-test-cookie=new then change the request to go to /test
    // if no cookie set, pass x% of traffic and set a cookie value to "current" or "new"

    let cookie = request.headers.get("cookie")
    // is cookie set?
    if (cookie && cookie.includes(`${cookieName}=new`)) {
      // Change the request to go to /test (as set in the newHomepagePathName variable)
      url.pathname = newHomepagePathName
      return env.ASSETS.fetch(url)
    }
  }
}

export const onRequest = [abTest]
```

2022-06-01 13:24 UTC, WalshyDev commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +To make the number genrated into percentages, multiply `Math.random()` by `100` and call `Math.floor()` so that all the percentages can be whole numbers. Your default cookie version is given a value
This is already mentioned above, no need to repeat it.

```suggestion
If the cookie value is not present, you will have to assign one. You can generate a percentage (from 0-99) as already mentioned above with the code `Math.floor(Math.random() * 100)`. Your default cookie version is given a value of `current`.
```

2022-06-01 13:24 UTC, WalshyDev commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +If the percentage of the number generated is lower than `50`, you will assign the cookie version to `new`. Based on the percentage randomly generated, you will set the cookie and serve the assets. Af
```suggestion
If the percentage of the number generated is lower than `50`, you will assign the cookie version to `new`. Based on the percentage randomly generated, you will set the cookie and serve the assets. After the conditional block, pass the request to `next()`. This will pass the request back to the browser. This will result in 50% of users getting the new homepage.
```

2022-06-01 13:24 UTC, WalshyDev commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +export const onRequest = [abtest];
```suggestion
const cookieName = "ab-test-cookie"
const newHomepagePathName = "/test"

const abTest = async ({ request, next, env }) => {
  const url = new URL(request.url)
  // if homepage
  if (url.pathname === "/") {
    // if cookie ab-test-cookie=new then change the request to go to /test
    // if no cookie set, pass x% of traffic and set a cookie value to "current" or "new"

    let cookie = request.headers.get("cookie")
    // is cookie set?
    if (cookie && cookie.includes(`${cookieName}=new`)) {
      // pass the request to /test
      url.pathname = newHomepagePathName
      return env.ASSETS.fetch(url)
    } else {
      const percentage = Math.floor(Math.random() * 100)
      let version = "current" // default version
      // change pathname and version name for 50% of traffic 
      if (percentage < 50) {
        url.pathname = newHomepagePathName
        version = "new"
      }
      // get the static file from ASSETS, and attach a cookie
      const asset = await env.ASSETS.fetch(url)
      let response = new Response(asset.body, asset)
      response.headers.append("Set-Cookie", `${cookieName}=${version}; path=/`)
      return response
    }
  }
  return next()
};

export const onRequest = [abTest];
```

2022-06-01 13:24 UTC, WalshyDev commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +Now that you have set up your `functions/_middleware.js` file in your project you are ready to deploy with Pages. Log in to the [Cloudflare dashboard](https://dash.cloudflare.com/login) > **Account H
Feels like they would probably already have a project if they're reading this page. Do we want to make this as if they don't @deadlypants1973 ?

If so... this flow has changed with direct uploads. So, we would need to add in both setup cases.

2022-06-01 13:25 UTC, WalshyDev commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +You can use any cookie library (for example, [`js-cookie`](https://www.npmjs.com/package/js-cookie)) to generate cookies. This guide assigns a local value to a `cookieName` variable and uses that as
Also, we talk about a lib but never use it. Can we just remove this library comment?

2022-06-02 14:41 UTC, Ekwuno commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +You can use any cookie library (for example, [`js-cookie`](https://www.npmjs.com/package/js-cookie)) to generate cookies. This guide assigns a local value to a `cookieName` variable and uses that as
It's more of a suggestion, to let people know that there are more secure ways to generate cookies.

2022-06-02 15:58 UTC, Ekwuno commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +const abtest = async({request, next, env}) => {
Most of our Functions examples use object deconstruction, for consistency let's leave it this way.

2022-06-02 16:07 UTC, Ekwuno commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +Now that you have set up your `functions/_middleware.js` file in your project you are ready to deploy with Pages. Log in to the [Cloudflare dashboard](https://dash.cloudflare.com/login) > **Account H
I think we can add in the intro that this tutorial assumes that you already have a project because anyone trying to do a/b testing would usually have a project and other variations of the project to test.

2022-06-07 17:44 UTC, deadlypants1973 reviewed
pcx review

2022-06-07 17:44 UTC, deadlypants1973 commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +To ensure that a user remains in the group you have given, a cookie will be set and stored in the browser and depending on cookie value the corresponding route will be served.
```suggestion
To ensure that a user remains in the group you have given, you will set and store a cookie in the browser and depending on the cookie value you have set, the corresponding route will be served.
```

2022-06-07 17:44 UTC, deadlypants1973 commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +You can use any cookie library (for example, [`js-cookie`](https://www.npmjs.com/package/js-cookie)) to generate cookies. This guide assigns a local value to a `cookieName` variable and uses that as
```suggestion
```

2022-06-07 17:44 UTC, deadlypants1973 commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +You can use any cookie library (for example, [`js-cookie`](https://www.npmjs.com/package/js-cookie)) to generate cookies. This guide assigns a local value to a `cookieName` variable and uses that as
```suggestion
```

2022-06-07 17:44 UTC, deadlypants1973 commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +The cookie assignment is done randomly by using `Math.random()` which generates a list of random decimal numbers. You can make the numbers a whole number by calling the `Math.floor()` method on `Math
```suggestion
```

2022-06-07 17:44 UTC, deadlypants1973 commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +
```suggestion
```

2022-06-07 17:44 UTC, deadlypants1973 commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +After you have set the value from the cookie, you can then have a conditional rendering set up that checks the value of the existing cookie and then assigns a group. Without a cookie, you will give o
```suggestion
```

2022-06-07 17:44 UTC, deadlypants1973 commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +To begin, go to your Pages project and create a `/functions` directory. Your application server logic will live in the `/functions` folder.
```suggestion
To begin:

 1. Go to your Pages project directory on your local machine.
 2. Create a `/functions` directory. Your application server logic will live in the `/functions` directory. 
```

2022-06-07 17:44 UTC, deadlypants1973 commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +Pages Functions have utility functions that can reuse chunks of logic which are executed before and/or after route handlers. These are called [middleware](/pages/platform/functions/#adding-middleware
```suggestion
Pages Functions have utility functions that can reuse chunks of logic which are executed before and/or after route handlers. These are called [middleware](/pages/platform/functions/#adding-middleware). Following this guide, middleware will allow you to intercept requests to your Pages project before they reach your site.
```

2022-06-07 17:44 UTC, deadlypants1973 commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +To identify the cookie, assign it in the browser and give it a unique name. Create a variable above your async function. Here, you can define the second route as `newHomepagePathName` and assign it `
```suggestion
To set the cookie, create the `cookieName` variable and assign any value. Then create the `newHomepagePathName` variable and assign it `/test`:
```

2022-06-07 17:44 UTC, deadlypants1973 commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +In your A/B testing, you want to be able to send a user to particular routes based on the presence of a cookie value. To do this, you must first intercept the request.
```suggestion
```

2022-06-07 17:44 UTC, deadlypants1973 commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +Based on the URL pathname, check what cookie value is present in the header. Based on the value, you will either set the base route or the `/test` route and fetch the assets for that route.
```suggestion
Based on the URL pathname, check that the cookie value is equal to `new` (`  if (cookie && cookie.includes(`${cookieName}=new`)) {`). If the value is `new`, then `newHomepagePathName` will be served.
```

2022-06-07 17:44 UTC, deadlypants1973 commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +If the cookie value is not present, you will have to assign one. You can generate numbers randomly by using the `Math.random()` method and getting whole numbers by calling a `Math.floor()` on the fun
```suggestion
You will now assign a cookie value. You can generate numbers randomly by using the `Math.random()` method and getting whole numbers by calling a `Math.floor()` on the function.
```

2022-06-07 17:44 UTC, deadlypants1973 commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +If the percentage of the number generated is lower than `50`, you will assign the cookie version to `new`. Based on the percentage randomly generated, you will set the cookie and serve the assets. Af
```suggestion
If the percentage of the number generated is lower than `50`, you will assign the cookie version to `new`. Based on the percentage randomly generated, you will set the cookie and serve the assets. After the conditional block, pass the request to `next()`. This will pass the request to Pages. This will result in 50% of users getting the new homepage.
```

2022-06-07 17:44 UTC, deadlypants1973 commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +Now that you have set up your `functions/_middleware.js` file in your project you are ready to deploy with Pages. Log in to the [Cloudflare dashboard](https://dash.cloudflare.com/login) > **Account H
```suggestion
Now that you have set up your `functions/_middleware.js` file in your project you are ready to deploy with Pages. If you are working with an existing Git project in the dashboard, push your project changes to GitHub/GitLab. If using Direct Uploads, refer to the [Direct Upload guide](/pages/platform/direct-upload/) to publish and deploy your project.
```

2022-06-07 17:44 UTC, deadlypants1973 commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +</div>
```suggestion
```

2022-06-07 17:49 UTC, deadlypants1973 commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +
```suggestion
```

2022-06-07 17:50 UTC, deadlypants1973 commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +Based on the URL pathname, check that the cookie value is equal to `new` (`  if (cookie && cookie.includes(`${cookieName}=new`)) {`). If the value is `new`, then `newHomepagePathName` will be served.
```suggestion
Based on the URL pathname, check that the cookie value is equal to `new`. If the value is `new`, then `newHomepagePathName` will be served.
```

2022-06-07 17:55 UTC, deadlypants1973 approved these changes

2022-06-07 17:56 UTC, WalshyDev approved these changes

2022-06-07 18:13 UTC, deadlypants1973 commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +Now that you have set up your `functions/_middleware.js` file in your project you are ready to deploy with Pages. If you are working with an existing Git project in the dashboard, push your project c
```suggestion
Now that you have set up your `functions/_middleware.js` file in your project you are ready to deploy with Pages. If you are working with an existing Git project in the dashboard, push your project changes to GitHub/GitLab. If using Direct Uploads, refer to the [Direct Upload guide](/pages/platform/direct-upload) to publish and deploy your project.
```

2022-06-07 18:55 UTC, deadlypants1973 commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +Now that you have set up your `functions/_middleware.js` file in your project you are ready to deploy with Pages. If you are working with an existing Git project in the dashboard, push your project c
```suggestion
Now that you have set up your `functions/_middleware.js` file in your project you are ready to deploy with Pages. If you are working with an existing Git project in the dashboard, push your project changes to GitHub/GitLab. If you are building your project locally and uploading with Direct Uploads, refer to the [Direct Uploads guide](/pages/platform/direct-upload/) to publish and deploy your project.
```

2022-06-07 18:58 UTC, deadlypants1973 commented on content/pages/how-to/use-worker-for-ab-testing-in-pages.md
> +Now that you have set up your `functions/_middleware.js` file in your project you are ready to deploy with Pages. If you are working with an existing Git project in the dashboard, push your project c
```suggestion
Now that you have set up your `functions/_middleware.js` file in your project you are ready to deploy with Pages. Push your project changes to GitHub/GitLab.
```

2022-06-07 19:06 UTC, merged