[R2] Add extensions and unicode interop documentation
cloudflare/cloudflare-docs pull request #4330
Opened 2022-05-09 16:19 UTC by vlovich

Document Unicode metadata behavior. Document object Unicode name issues.
The unicode interop doc page is similar in style to the GCS page:
https://cloud.google.com/storage/docs/gsutil/addlhelp/Filenameencodingandinteroperabilityproblems

2022-05-09 19:32 UTC, lukeed requested changes

2022-05-09 19:32 UTC, lukeed commented on content/r2/platform/s3-compatibility/extensions.md
> +  title: Extensions
Dont need this when matches the title
```suggestion
```

2022-05-09 19:32 UTC, lukeed commented on content/r2/platform/s3-compatibility/extensions.md
> +R2 implements some extensions on top of the stock S3 API. This page outlines those additional features that are available:
```suggestion
R2 implements some extensions on top of the basic S3 API. This page outlines these additional features that are available.
```

2022-05-09 19:32 UTC, lukeed commented on content/r2/platform/s3-compatibility/extensions.md
> +in the R2 S3-compatible API endpoint.
```suggestion
The [Workers R2 API](/workers/runtime-apis/r2/) supports Unicode in keys and values natively without requiring any additional encoding or decoding for the `customMetadata` field. These fields map to the `x-amz-meta-`-prefixed headers used within the R2 S3-compatible API endpoint.
```

2022-05-09 19:32 UTC, lukeed commented on content/r2/platform/s3-compatibility/extensions.md
> +that.
```suggestion
If using Unicode in object key names, refer to the [Unicode Interoperability technical notes](/r2/platform/unicode-interoperability/).
```

2022-05-09 19:32 UTC, lukeed commented on content/r2/platform/s3-compatibility/extensions.md
> +need to use `REPLACE`.
```suggestion
The `x-amz-metadata-directive` allows a `MERGE` value, in addition to the standard `COPY` and `REPLACE` options. When used, `MERGE` is a combination of `COPY` and `REPLACE`, which will `COPY` any metadata keys from the source object and `REPLACE` those that are specified in the request with the new value. You cannot use `MERGE` to remove existing metadata keys from the source — use `REPLACE` instead.
```

2022-05-09 19:32 UTC, lukeed commented on content/r2/platform/unicode-interoperability.md
> +  title: Filename encoding and interoperability problems
```suggestion
```

2022-05-09 19:32 UTC, lukeed commented on content/r2/platform/unicode-interoperability.md
> +equivalence](https://en.wikipedia.org/wiki/Unicode_equivalence).
```suggestion
Since R2 is built on top of Workers, it supports Unicode natively. One nuance of Unicode that is often overlooked is the issue of [filename interoperability](https://en.wikipedia.org/wiki/Filename#Encoding_indication_interoperability) due to [Unicode
equivalence](https://en.wikipedia.org/wiki/Unicode_equivalence).
```

2022-05-09 19:32 UTC, lukeed commented on content/r2/platform/unicode-interoperability.md
> +`Héllo` and `Héllo` are the same object in R2 but different objects in other storage providers.
@vlovich Can you provide the byte codes so that the two `Héllo` are noticeably different?

```suggestion
Based on user feedback, Cloudflare will NFC-normalize key names before storing by default. This means `Héllo` and `Héllo` are the same object in R2 but different objects in other storage providers.
```

2022-05-09 19:32 UTC, lukeed commented on content/r2/platform/unicode-interoperability.md
> +R2 is encoding-preserving for display though. When you list the objects, you'll get back the last encoding you uploaded with.
Not sure what you mean by "for display though" @vlovich 

```suggestion
R2 preserves the encoding for display though. When you list the objects, you'll get back the last encoding you uploaded with.
```

2022-05-09 19:32 UTC, lukeed commented on content/r2/platform/unicode-interoperability.md
> +team.
```suggestion
There are still some platform-specific differences to consider:

* Windows filenames are case-insensitive while R2, Linux, and macOS are not.
* Windows console support for Unicode can be error-prone. Make sure to run `chcp 65001` before using command-line tools or use Cygwin if your object names appear to be incorrect.
* Linux allows distinct files that are unicode-equivalent because filenames are byte streams. Unicode-equivalent filenames on Linux will point to the same R2 object.

If it's important for you to be able to bypass the unicode equivalence and use byte-oriented key names, contact your Cloudflare account team.
```

2022-05-09 19:32 UTC, lukeed commented on content/r2/platform/s3-compatibility/extensions.md
> +values applies on the decoded Unicode value.
```suggestion
HTTP header names and values may only contain ASCII characters, which is a small subset of the Unicode character library. To easily accommodate users, R2 adheres to [RFC2047](https://datatracker.ietf.org/doc/html/rfc2047) and automatically decodes all `x-amz-meta-*` header values before storage. On retrieval, any metadata values with unicode are RFC2047-encoded before rendering the response. The length limit for metadata values is applied to the decoded Unicode value.
```

2022-05-09 19:32 UTC, lukeed commented on content/r2/platform/s3-compatibility/extensions.md
> +they are stripped when returning responses through S3 and the `x-amz-missing-meta` header is set to the number of keys that were omitted.
```suggestion
{{<Aside type="warning" header="Metadata variance">
Be mindful when using both Workers and S3 API endpoints to access the same data. 

If the R2 metadata keys contain Unicode, they are stripped when accessed through the through S3 API and the `x-amz-missing-meta` header is set to the number of keys that were omitted.
{{</Aside>}}
```

2022-05-09 19:32 UTC, lukeed commented on content/r2/platform/s3-compatibility/extensions.md
> +`httpMetadata` field in the R2 bindings:
Stated above, dont think need to repeat

```suggestion
These headers map to the `httpMetadata` field in the R2 bindings:
```

2022-05-09 19:32 UTC, lukeed commented on content/r2/platform/s3-compatibility/extensions.md
> +* `Expires`
I think this would be better served as a table with the `HTTP header` and `property name` columns

2022-05-09 19:36 UTC, lukeed commented on content/r2/platform/s3-compatibility/extensions.md
> +in the R2 S3-compatible API endpoint.
We dont have this Runtime API page btw, so linking to it breaks CI

2022-05-09 19:50 UTC, vlovich commented on content/r2/platform/s3-compatibility/extensions.md
> +in the R2 S3-compatible API endpoint.
Yup - I'll rebase once @greg-mckeon pushes the right page

2022-05-09 20:09 UTC, lukeed requested changes
reapply force-pushed orphans

2022-05-09 20:09 UTC, lukeed commented on content/r2/api.md
> +  title: API
```suggestion
```

2022-05-09 20:09 UTC, lukeed commented on content/r2/platform/s3-compatibility/extensions.md
> +R2 S3-compatible API endpoint.
```suggestion
The [Workers R2 API](/r2/api/) supports Unicode in keys and values natively without requiring any additional encoding or decoding for the `customMetadata` field. These fields map to the `x-amz-meta-`-prefixed headers used within the R2 S3-compatible API endpoint.
```

2022-05-09 20:09 UTC, lukeed commented on content/r2/platform/s3-compatibility/extensions.md
> +the response. The length limit for metadata values is applied to the decoded Unicode value.
```suggestion
`x-amz-meta-*` header values before storage. On retrieval, any metadata values with unicode are RFC2047-encoded before rendering the response. The length limit for metadata values is applied to the decoded Unicode value.
```

2022-05-09 20:09 UTC, lukeed commented on content/r2/platform/s3-compatibility/extensions.md
> +omitted.
```suggestion
Be mindful when using both Workers and S3 API endpoints to access the same data. If the R2 metadata keys contain Unicode, they are stripped when accessed through the through S3 API and the `x-amz-missing-meta` header is set to the number of keys that were omitted.
```

2022-05-09 20:09 UTC, lukeed commented on content/r2/platform/s3-compatibility/extensions.md
> +{{<table-wrap>}}
```suggestion

{{<table-wrap>}}
```

2022-05-09 20:09 UTC, lukeed commented on content/r2/platform/s3-compatibility/extensions.md
> +source — use `REPLACE` instead.
```suggestion
The `x-amz-metadata-directive` allows a `MERGE` value, in addition to the standard `COPY` and `REPLACE` options. When used, `MERGE` is a combination of `COPY` and `REPLACE`, which will `COPY` any metadata keys from the source object and `REPLACE` those that are specified in the request with the new value. You cannot use `MERGE` to remove existing metadata keys from the source — use `REPLACE` instead.
```

2022-05-09 20:13 UTC, lukeed commented on content/r2/platform/unicode-interoperability.md
> +equivalence](https://en.wikipedia.org/wiki/Unicode_equivalence).
```suggestion
Since R2 is built on top of Workers, it supports Unicode natively. One nuance of Unicode that is often overlooked is the issue of [filename interoperability](https://en.wikipedia.org/wiki/Filename#Encoding_indication_interoperability) due to [Unicode equivalence](https://en.wikipedia.org/wiki/Unicode_equivalence).
```

2022-05-09 20:36 UTC, lukeed reviewed
Awaiting PCX review & clarification on the `Hèllo` and "for display" review comments

2022-05-09 20:37 UTC, lukeed approved these changes
Just removing my "requesting changes" blocker. See previous comment for PR status

2022-05-10 12:30 UTC, deadlypants1973 reviewed
PCX review

2022-05-10 12:30 UTC, deadlypants1973 commented on content/r2/api.md
> +weight: 1
I think we can take this off? It will just be alphabetical on the side menu cc: @lukeed

2022-05-10 12:30 UTC, deadlypants1973 commented on content/r2/platform/s3-compatibility/extensions.md
> +pcx-content-type: reference
```suggestion
pcx-content-type: concept
```

2022-05-10 12:30 UTC, deadlypants1973 commented on content/r2/platform/s3-compatibility/extensions.md
> +## Extended Metadata Using Unicode
```suggestion
## Extended metadata using Unicode
```

2022-05-10 12:30 UTC, deadlypants1973 commented on content/r2/platform/s3-compatibility/extensions.md
> +R2 implements some extensions on top of the basic S3 API. This page outlines these additional features that are available.
```suggestion
R2 implements some extensions on top of the basic S3 API. This page outlines these additional, available features.
```

2022-05-10 12:30 UTC, deadlypants1973 commented on content/r2/platform/unicode-interoperability.md
> +Based on feedback from our users, we've chosen to NFC-normalize key names before storing by default. This means `Héllo` and `Héllo` are the same object in R2 but different objects in other storage p
```suggestion
Based on feedback from our users, we have chosen to NFC-normalize key names before storing by default. This means `Héllo` and `Héllo` are the same object in R2 but different objects in other storage providers.
```

2022-05-10 12:30 UTC, deadlypants1973 commented on content/r2/platform/unicode-interoperability.md
> +If it's important for you to be able to bypass the unicode equivalence and use byte-oriented key names, contact your Cloudflare account team.
```suggestion
If it is important for you to be able to bypass the unicode equivalence and use byte-oriented key names, contact your Cloudflare account team.
```

2022-05-10 15:32 UTC, lukeed commented on content/r2/api.md
> +weight: 1
Sounds good

2022-05-10 15:36 UTC, deadlypants1973 commented on content/r2/api.md
> +weight: 1
```suggestion
```

2022-05-11 02:46 UTC, vlovich commented on content/r2/api.md
> +weight: 1
This is a placeholder. @greg-mckeon's PR will replace all this.

2022-05-11 03:59 UTC, merged