[R2] Document writeHttpMetadata method on R2Object
cloudflare/cloudflare-docs pull request #4452
Opened 2022-05-16 02:29 UTC by KianNH

2022-05-16 02:29 UTC, KianNH commented
Admittedly, the `{{foo}}` tags might not be correct for this - never used them in a PR before. :woozy_face:

2022-05-16 10:56 UTC, deadlypants1973 requested changes
thank you as always, kian :)

'refer to' > 'see' for docs

2022-05-16 10:56 UTC, deadlypants1973 commented on content/r2/runtime-apis.md
> +  -  Retrieves the `httpMetadata` from the R2Object and writes to a Headers object. See [HTTP Metadata](#http-metadata).
```suggestion
  -  Retrieves the `httpMetadata` from the R2Object and writes to a Headers object. Refer to [HTTP Metadata](#http-metadata).
```

2022-05-16 11:03 UTC, KianNH commented
squish squashed

on another note - do you want the code suggestion commits to be squashed or just left as-is?

2022-05-16 11:12 UTC, deadlypants1973 commented on content/r2/runtime-apis.md
> +  -  Retrieves the `httpMetadata` from the R2Object and writes to a Headers object. Refer to [HTTP Metadata](#http-metadata).
```suggestion
  -  Retrieves the `httpMetadata` from the `R2Object` and writes to a `Headers` object. Refer to [HTTP Metadata](#http-metadata).
```

2022-05-16 11:25 UTC, KianNH commented
![image](https://user-images.githubusercontent.com/94662631/168582547-e39929dc-12dc-4527-99b3-ca9396599079.png)

Didn't realise that the merge into `production` 'squashed' them into a single commit - which was the only reason I was squashing them, so it didn't appear as a handful of separate commits.

TIL

2022-05-17 15:27 UTC, deadlypants1973 approved these changes

2022-05-17 17:00 UTC, kris-evans approved these changes

2022-05-17 18:09 UTC, lukeed approved these changes

2022-05-17 18:09 UTC, lukeed commented on content/r2/runtime-apis.md
> +  -  Retrieves the `httpMetadata` from the `R2Object` and writes to a `Headers` object. Refer to [HTTP Metadata](#http-metadata).
```suggestion
  -  Retrieves the `httpMetadata` from the `R2Object` and applies their corresponding HTTP headers to the `Headers` input object. Refer to [HTTP Metadata](#http-metadata).
```

2022-05-18 07:33 UTC, merged