[1.1.1.1] code fixes to 1.1.1.1 pages
cloudflare/cloudflare-docs pull request #448
Opened 2020-12-08 16:56 UTC by abracchi-tw

2020-12-08 17:03 UTC, Lekensteyn commented on products/1.1.1.1/src/content/dns-over-https/json-format.md
>      curl -H 'accept: application/dns-json' 'https://cloudflare-dns.com/dns-query?name=example.com&type=AAAA'
Should the indentation be removed here and below for the JSON response?

2020-12-08 18:18 UTC, adamschwartz requested changes
Lots of little tweaks needed.

2020-12-08 18:18 UTC, adamschwartz commented on products/1.1.1.1/src/content/dns-over-https/cloudflared-proxy.md
> +sudo cloudflared proxy-dns
Add `$` before `sudo`.

2020-12-08 18:18 UTC, adamschwartz commented on products/1.1.1.1/src/content/dns-over-https/cloudflared-proxy.md
> +```
Add `$` before `cloudflared`.

https://developers.cloudflare.com/docs-engine/reference/markdown#terminals

![image](https://user-images.githubusercontent.com/154613/101523658-e06ad300-3956-11eb-973d-d4007d788431.png)

2020-12-08 18:18 UTC, adamschwartz commented on products/1.1.1.1/src/content/dns-over-https/cloudflared-proxy.md
> +dig +short @127.0.0.1 cloudflare.com AAAA
Add `$` before `dig`.

2020-12-08 18:18 UTC, adamschwartz commented on products/1.1.1.1/src/content/dns-over-https/cloudflared-proxy.md
> +cat << EOF > /usr/local/etc/cloudflared/config.yml
Add `$` before `mkdir` and `cat`, each.

2020-12-08 18:18 UTC, adamschwartz commented on products/1.1.1.1/src/content/dns-over-https/cloudflared-proxy.md
> +sudo cloudflared service install
Add `$` before `sudo`.

2020-12-08 18:18 UTC, adamschwartz commented on products/1.1.1.1/src/content/dns-over-https/cloudflared-proxy.md
> +dig +short @127.0.0.1 cloudflare.com AAAA
Add `$` before `dig`.

2020-12-08 18:18 UTC, adamschwartz commented on products/1.1.1.1/src/content/dns-over-https/cloudflared-proxy.md
> +dnscrypt-proxy -version
Add `$` before `dnscrypt-proxy`.

2020-12-08 18:18 UTC, adamschwartz commented on products/1.1.1.1/src/content/dns-over-https/cloudflared-proxy.md
>  Step 3: Set up the configuration file using the [official instructions](https://github.com/jedisct1/dnscrypt-proxy/wiki/installation#setting-up-dnscrypt-proxy), and add 'cloudflare' and 'cloudflare-i
Missing `.` at end of sentence.

2020-12-08 18:18 UTC, adamschwartz commented on products/1.1.1.1/src/content/dns-over-https/cloudflared-proxy.md
> +```
Missing code block syntax highlighting hint. If you want no syntax highlighting, use `txt`. (See https://developers.cloudflare.com/docs-engine/contributing/content/formatting#general-formatting)

2020-12-08 18:18 UTC, adamschwartz commented on products/1.1.1.1/src/content/dns-over-https/cloudflared-proxy.md
> +dnscrypt-proxy -resolve cloudflare-dns.com
Add `$` before `dnscrypt-proxy`.

2020-12-08 18:18 UTC, adamschwartz commented on products/1.1.1.1/src/content/dns-over-https/json-format.md
>      }
Remove four spaces of indentation on entire JSON block.

2020-12-08 18:18 UTC, adamschwartz commented on products/1.1.1.1/src/content/dns-over-https/wireformat.md
> +```
Add syntax highlighting hint. (Use `txt` if you want no syntax highlighting.) See 
 https://developers.cloudflare.com/docs-engine/contributing/content/formatting#general-formatting

2020-12-08 18:18 UTC, adamschwartz commented on products/1.1.1.1/src/content/dns-over-https/wireformat.md
> +```
Add syntax highlighting hint. (Use `txt` if you want no syntax highlighting.) See 
 https://developers.cloudflare.com/docs-engine/contributing/content/formatting#general-formatting

2020-12-08 18:18 UTC, adamschwartz commented on products/1.1.1.1/src/content/dns-over-https/wireformat.md
>      echo -n 'q80BAAABAAAAAAAAA3d3dwdleGFtcGxlA2NvbQAAAQAB' | base64 -D | curl -H 'content-type: application/dns-message' --data-binary @- https://cloudflare-dns.com/dns-query -o - | hexdump
Remove four spaces of indentation and add `$` before `echo`.

2020-12-08 18:18 UTC, adamschwartz commented on products/1.1.1.1/src/content/dns-over-tls/index.md
>      ;; From 1.1.1.1@853(TCP) in 12.6 ms
Remove four spaces of indentation.

2020-12-08 18:18 UTC, adamschwartz commented on products/1.1.1.1/src/content/dns-over-https/wireformat.md
>      0000031
Remove four spaces of indentation/

2020-12-09 10:50 UTC, abracchi-tw commented
> Lots of little tweaks needed.

@adamschwartz thanks for taking the time, appreciate it. I should've cleaned everything up

2020-12-09 21:29 UTC, adamschwartz requested changes
Just a couple more! We’re almost there.

2020-12-09 21:29 UTC, adamschwartz commented on products/1.1.1.1/src/content/dns-over-https/cloudflared-proxy.md
> +dnscrypt-proxy -resolve cloudflare-dns.com
This line still needs `$` prefix.

2020-12-09 21:29 UTC, adamschwartz commented on products/1.1.1.1/src/content/dns-over-https/json-format.md
> +curl -H 'accept: application/dns-json' 'https://cloudflare-dns.com/dns-query?name=example.com&type=AAAA'
Need `$` prefix here.

2021-03-09 12:11 UTC, closed without merging