Update ingress.md
cloudflare/cloudflare-docs pull request #450
Opened 2020-12-08 22:36 UTC by TownLake

2020-12-08 23:04 UTC, adamchalmers requested changes

2020-12-08 23:04 UTC, adamchalmers commented on products/argo-tunnel/src/content/configuration/ingress.md
> +The file also includes the Tunnel UUID, path to the credentials file, and two hostname-service pairs. The Tunnel UUID can alternatively be specified in the `tunnel run` command and the path to the cr
1. "Tunnel UUID" should be "Tunnel UUID or name", names work here just fine
2. Let's not say "hostname-service pairs", that phrase never appears anywhere else. Let's say "two ingress rules" instead. 
3. Replace "available in the default location" with "located at a default filepath" (more idiomatic)

2020-12-09 11:37 UTC, abracchi-tw approved these changes

2020-12-09 16:52 UTC, adamchalmers approved these changes

2020-12-09 21:02 UTC, merged