R2 example using aws-sdk-ruby
cloudflare/cloudflare-docs pull request #4514
Opened 2022-05-20 01:07 UTC by csuhta

Similar to the other pages, this one provides an example config for Ruby using the official AWS gem

2022-06-01 22:18 UTC, vlovich commented on content/r2/examples/aws-sdk-ruby.md
> +  force_path_style: true,
This isn't necessary - we support virtual bucket naming.

2022-06-01 22:18 UTC, vlovich approved these changes
Not a ruby expert. If there's issues I'd prefer to just land this & fixup later as issues are raised.

2022-06-02 00:30 UTC, csuhta commented on content/r2/examples/aws-sdk-ruby.md
> +  force_path_style: true,
Ah ok. I copied that from a different doc example. Removed in latest commit.

2022-06-02 12:44 UTC, deadlypants1973 commented on content/r2/examples/aws-sdk-ruby.md
> +You must [generate an Access Key](/r2/platform/s3-compatibility/tokens/) before getting started. All examples will utilities `access_key_id` and `access_key_secret` variables which represent the **Ac
```suggestion
You must [generate an Access Key](/r2/platform/s3-compatibility/tokens/) before getting started. All examples will utilize `access_key_id` and `access_key_secret` variables which represent the **Access Key ID** and **Secret Access Key** values you generated. Many Ruby projects also store these credentials in environment variables instead.
```
I am assuming this was supposed to be a verb?

2022-06-02 12:45 UTC, deadlypants1973 requested changes
PCX review, one comment on opening sentence

2022-06-02 12:50 UTC, deadlypants1973 approved these changes

2022-06-02 12:50 UTC, merged