Add Load Balancing Limitations to Dev Docs
cloudflare/cloudflare-docs pull request #4581
Opened 2022-05-26 19:00 UTC by patriciasantaana

https://jira.cfops.it/browse/PCX-2028

2022-05-26 21:46 UTC, kodster28 requested changes

2022-05-26 21:46 UTC, kodster28 commented on content/load-balancing/understand-basics/limitations.md
> +pcx-content-type: concept
```suggestion
pcx-content-type: reference
```

2022-05-26 21:46 UTC, kodster28 commented on content/load-balancing/understand-basics/limitations.md
> +# Limitations
```suggestion

# Limitations
```

2022-05-26 21:46 UTC, kodster28 commented on content/load-balancing/understand-basics/limitations.md
> +| Name | Non-Enterprise | Enterprise | Maximum/Minimum Value for Enterprise |
```suggestion
| Name | Non-Enterprise | Enterprise | 
```

2022-05-26 21:46 UTC, kodster28 commented on content/load-balancing/understand-basics/limitations.md
> +| Load balancers | 20 | 20 | 100 |
```suggestion
| Load balancers | 20 | 100 |
```

2022-05-26 21:46 UTC, kodster28 commented on content/load-balancing/understand-basics/limitations.md
> +| Monitor intervals | 60, 3600 | 10, 3600 | 10, 3600 |
```suggestion
| Monitor intervals | 60 (min), 3600 (max) | 10 (min), 3600 (max) |
```

2022-05-26 21:46 UTC, kodster28 commented on content/load-balancing/understand-basics/limitations.md
> +| Monitors | N/A | N/A | N/A |
```suggestion
| Monitors | 1.5x the number of pools | 1.5x the number of pools | 
```

2022-05-26 21:46 UTC, kodster28 commented on content/load-balancing/understand-basics/limitations.md
> +| Origin pools | 2 | 1 | 250 |
```suggestion
| Origin servers | 20 | 250 |
```

2022-05-26 21:46 UTC, kodster28 commented on content/load-balancing/understand-basics/limitations.md
> +| Pools | 20 | 20 | 100 |
```suggestion
| Pools | 20 | 100 |
```

2022-05-26 22:18 UTC, ranbel approved these changes

2022-05-26 22:18 UTC, ranbel commented on content/load-balancing/understand-basics/limitations.md
> +| Monitor intervals | 60 (min), 3600 (max) | 10 (min), 3600 (max) |
```suggestion
| Monitor intervals | minimum 60, maximum 3,600 | minimum 10, maximum 3,600 |
```

2022-05-26 22:18 UTC, ranbel commented on content/load-balancing/understand-basics/limitations.md
> +| Monitor intervals | 60 (min), 3600 (max) | 10 (min), 3600 (max) |
style guide says to add commas to large #s.
https://wiki.cfops.it/display/Prod/Numbers

2022-05-27 17:03 UTC, kodster28 approved these changes

2022-05-27 17:04 UTC, merged