[R2] Added Postman guide
cloudflare/cloudflare-docs pull request #4653
Opened 2022-06-01 18:07 UTC by mpint

* Adds Postman guide to help users quickly get started on the platform (`content/r2/examples/postman.md`)
* Added supporting static images (`content/r2/static`)

2022-06-02 21:19 UTC, codewithkristian commented on content/r2/examples/postman.md
> +layout: example
@deadlypants1973 I noticed that this page is missing the TOC on the side, is that because of this field?

2022-06-07 19:57 UTC, lukeed commented on content/r2/examples/postman.md
> +layout: example
Yes :) All examples use this `layout`: https://github.com/cloudflare/cloudflare-docs/blob/production/layouts/_default/example.html Matches Workers' examples too

2022-06-09 13:16 UTC, deadlypants1973 requested changes

2022-06-09 13:16 UTC, deadlypants1973 commented on content/r2/examples/postman.md
> +Before getting started, you'll need an R2 subscription. [Learn more](https://developers.cloudflare.com/r2/get-started/#purchase-r2) about setting up your subscription.
```suggestion
This guide assumes that you have made a Cloudflare account and [purchased R2](https://developers.cloudflare.com/r2/get-started/#purchase-r2).
```

2022-06-09 13:16 UTC, deadlypants1973 commented on content/r2/examples/postman.md
> +Click on the `Cloudflare R2` collection and navigate to the `Variables` tab. Here, you can set variables within the R2 collection. They will be used to authenticate and interact with the R2 platform.
```suggestion
In the [Postman dashboard](https://www.postman.com/cloudflare-r2/workspace/cloudflare-r2/collection/20913290-14ddd8d8-3212-490d-8647-88c9dc557659?action=share&creator=20913290&ctx=documentation), select the **Cloudflare R2** collection and navigate to **Variables**. In **Variables**, you can set variables within the R2 collection. They will be used to authenticate and interact with the R2 platform. Remember to always select **Save** after updating a variable.
```

2022-06-09 13:16 UTC, deadlypants1973 commented on content/r2/examples/postman.md
> +![Postman Variables](/r2/static/postman-variables.png)
```suggestion
![Select **Variables** in the Postman dashboard to continue with the example](/r2/static/postman-variables.png)
```

2022-06-09 13:16 UTC, deadlypants1973 commented on content/r2/examples/postman.md
> +Navigate to the [Cloudflare dashboard](https://dash.cloudflare.com/?account=r2) and select the account to use with R2. On the R2 overview page, copy your Cloudflare account ID in the from the right h
```suggestion
To do this:

1. Log in to the [Cloudflare dashboard](https://dash.cloudflare.com/?account=r2).
2. In **Account Home**, select **R2**.
3. In **R2**, under **Manage R2 API Tokens** on the right side of the dashboard, copy your Cloudflare account ID.
4. Go back to the Postman dashboard.
5. Set the **CURRENT VALUE** of `account-id` to your Cloudflare account ID and select **Save**.
```

2022-06-09 13:16 UTC, deadlypants1973 commented on content/r2/examples/postman.md
> +Next, navigate back to the R2 overview page to set up your `r2-access-key` and `r2-secret-id`. On the right hand sidebar, click the _Manage R2 API Tokens_ link to create an R2 API Token called `Postm
```suggestion
Next, generate an R2 API token:

1. Go back to the Cloudflare dashboard > **R2**.
2. On the right hand sidebar, select **Manage R2 API Tokens**.
3. Select **Create API token**.
4. Name your token **Postman** by selecting the pencil icon next to the API name and grant it the `Edit` permission.
```

2022-06-09 13:16 UTC, deadlypants1973 commented on content/r2/examples/postman.md
> +![Generate an R2 API token for Postman](/r2/static/postman-r2-api-token.png)
```suggestion
![Generate an R2 API token for Postman by following the instructions above](/r2/static/postman-r2-api-token.png)
```

2022-06-09 13:16 UTC, deadlypants1973 commented on content/r2/examples/postman.md
> +To execute some basic operations, we must set `account-id`, `r2-access-key`, and `r2-secret-id`.
```suggestion
To execute basic operations, you must set `account-id`, `r2-access-key`, and `r2-secret-id` ___(noun needed to describe what these are) in __(where are you setting these)____.
```
Are these environment variables?

2022-06-09 13:16 UTC, deadlypants1973 commented on content/r2/examples/postman.md
> +Guard this token closely. Anyone with this information can fully interact with all of your buckets.
Are you guarding the token? Or are you guarding the values of Access Key ID and Secret Access Key?

2022-06-09 13:16 UTC, deadlypants1973 commented on content/r2/examples/postman.md
> +Once created, copy the token’s `Access Key ID` value into Postman’s `r2-secret-id` variable and the `Secret Access Key` value into Postman’s `r2-access-key` variable and press Save.
```suggestion
After you have created you API token in the Cloudflare dashboard:

1. Go back to the [Postman dashboard](https://www.postman.com/cloudflare-r2/workspace/cloudflare-r2/collection/20913290-14ddd8d8-3212-490d-8647-88c9dc557659?action=share&creator=20913290&ctx=documentation) > **Variables**.
2. Copy `Access Key ID` value from the Cloudflare dashboard and paste it into Postman’s `r2-secret-id` variable value and select **Save**.
3. Copy the `Secret Access Key` value value from the Cloudflare dashboard and paste into Postman’s `r2-access-key` variable value and select **Save**.
```

2022-06-09 13:16 UTC, deadlypants1973 commented on content/r2/examples/postman.md
> +To execute some basic operations, we must set `account-id`, `r2-access-key`, and `r2-secret-id`.
@mpint please review the question and fill in the blanks.

2022-06-09 13:16 UTC, deadlypants1973 commented on content/r2/examples/postman.md
> +By now, you should have `account-id`, `r2-secret-id`, and `r2-access-key` set in Postman. To verify the token, navigate to the `ListBuckets` request and press `Send`. The Postman collection uses AWS
```suggestion
By now, you should have `account-id`, `r2-secret-id`, and `r2-access-key` set in Postman. 

To verify the token:

1. In the Postman dashboard, select the **Cloudflare R2** folder dropdown arrow > **Buckets** folder dropdown arrow > **`GET`ListBuckets**. 
2. Select **Send**. 

The Postman collection uses AWS SigV4 authentication to complete the handshake.
```

2022-06-09 13:16 UTC, deadlypants1973 commented on content/r2/examples/postman.md
> +Now, let’s have some fun. In your `Variables` tab, think of a fun name for a bucket and set it as the `r2-bucket` variable and press Save. Then, select the `CreateBucket` request and press `Send`.
```suggestion
In the Postman dashboard:

1. Go to **Variables**. 
2. Set the `r2-bucket` variable value as the name of your R2 bucket and select **Save**. 
3. Select the **Cloudflare R2** folder dropdown arrow > **Buckets** folder dropdown arrow > **`PUT`CreateBucket** and select **Send**.
```

2022-06-09 13:16 UTC, deadlypants1973 commented on content/r2/examples/postman.md
> +![CreateBucket in Postman](/r2/static/postman-r2-create-bucket.png)
```suggestion
![Follow the instructions above to navigate to CreateBucket in the Postman dashboard](/r2/static/postman-r2-create-bucket.png)
```

2022-06-09 13:16 UTC, deadlypants1973 commented on content/r2/examples/postman.md
> +A bucket isn’t very interesting without some stuff inside so let’s add an object. On the `Variables` tab, we set `r2-object` to `cat-pic.jpg` and press Save. Then, we select the `PutObject` request,
```suggestion
You will now add an object to your bucket:

1. Go to**Variables** in the Postman dashboard.
2. Set `r2-object` to `cat-pic.jpg` and select **Save**. 
3. Select **Cloudflare R2** folder dropdown arrow > **Objects** folder dropdown arrow > **Multipart** folder dropdown arrow > **`PUT`PutObject** and select **Send**. 
4. Go to **Body** and choose **binary** before attaching your cat picture. 
5. Select **Send** to add the cat picture to your R2 bucket.
```

2022-06-09 13:16 UTC, deadlypants1973 commented on content/r2/examples/postman.md
> +![PutObject in Postman](/r2/static/postman-r2-put-object.png)
```suggestion
![Follow the instructions above to PutObject in the Postman dashboard](/r2/static/postman-r2-put-object.png)
```

2022-06-09 13:16 UTC, deadlypants1973 commented on content/r2/examples/postman.md
> +![GetObject in Postman](/r2/static/postman-r2-get-object.png)
```suggestion
![Follow the instructions above to GetObject in the Postman dashboard](/r2/static/postman-r2-get-object.png)
```

2022-06-09 13:16 UTC, deadlypants1973 commented on content/r2/examples/postman.md
> +It only takes one more click to download our cat friend using the `GetObject` request.
```suggestion
To download your cat picture, select **Cloudflare R2** folder dropdown arrow > **Objects** folder dropdown arrow > **`GET`GetObject**.
```

Does the user need to press Send here or do something when they are on this page?

2022-06-09 13:16 UTC, deadlypants1973 commented on content/r2/examples/postman.md
> +You can explore the rest of the R2 Postman collection by playing with other operations. We’ll keep this collection up to date as we expand our feature set so stay tuned for updates.
```suggestion
The R2 team will keep this collection up to date as we expand R2 features set. You can explore the rest of the R2 Postman collection by experimenting with other operations. 
```

2022-06-09 14:42 UTC, mpint commented on content/r2/examples/postman.md
> +Guard this token closely. Anyone with this information can fully interact with all of your buckets.
Yep, guarding of these values (but especially the secret) which comprise the token.

2022-06-09 14:44 UTC, mpint commented on content/r2/examples/postman.md
> +It only takes one more click to download our cat friend using the `GetObject` request.
Whoops, yep.  Looks like I ran out of steam here.

2022-06-09 14:58 UTC, deadlypants1973 commented on content/r2/examples/postman.md
> +1. Select the **Cloudflare R2** folder dropdown arrow > **Objects** folder dropdown arrow > **`GET`GetObject** and select **Send**.
```suggestion
1. Select the **Cloudflare R2** folder dropdown arrow > **Objects** folder dropdown arrow > **`GET`GetObject**.
2. Select **Send**.
```

2022-06-09 14:58 UTC, deadlypants1973 commented on content/r2/examples/postman.md
> +Guard this token closely. Anyone with this information can fully interact with all of your buckets.
```suggestion
Guard this token and the **Access Key ID** and **Secret Access Key** closely. You will not be able to review these values again after finishing this step. Anyone with this information can fully interact with all of your buckets.
```

2022-06-09 14:58 UTC, deadlypants1973 commented on content/r2/examples/postman.md
> +4. Name your token **Postman** by selecting the pencil icon next to the API name and grant it the `Edit` permission.
```suggestion
4. Name your token **Postman** by selecting the pencil icon next to the API name and grant it the **Edit** permission.
```

2022-06-09 14:58 UTC, deadlypants1973 commented on content/r2/examples/postman.md
> +1. Select the **Cloudflare R2** folder dropdown arrow > **Objects** folder dropdown arrow > **`GET`GetObject** and select **Send**.
Do they need to do anything else on this screen other than pressing Send?

2022-06-09 14:58 UTC, deadlypants1973 commented on content/r2/examples/postman.md
> +To execute basic operations, you must set the `account-id`, `r2-access-key`, and `r2-secret-id` variables in the **Variables** tab.
```suggestion
To execute basic operations, you must set the `account-id`, `r2-access-key`, and `r2-secret-id` variables in the Postman dashboard > **Variables**.
```

2022-06-09 15:44 UTC, mpint commented on content/r2/examples/postman.md
> +1. Select the **Cloudflare R2** folder dropdown arrow > **Objects** folder dropdown arrow > **`GET`GetObject** and select **Send**.
Not unless we add "Enjoy the cute cat pic." 😆

2022-06-09 17:06 UTC, deadlypants1973 commented on content/r2/examples/postman.md
> +4. Go back to the Postman dashboard.
```suggestion
4. Go back to the [Postman dashboard](https://www.postman.com/cloudflare-r2/workspace/cloudflare-r2/collection/20913290-14ddd8d8-3212-490d-8647-88c9dc557659?action=share&creator=20913290&ctx=documentation).
```

2022-06-09 17:07 UTC, deadlypants1973 commented on content/r2/examples/postman.md
> +1. Go back to the Cloudflare dashboard > **R2**.
```suggestion
1. Go to the Cloudflare dashboard > **R2**.
```

2022-06-09 17:07 UTC, deadlypants1973 commented on content/r2/examples/postman.md
> +1. Go back to the [Postman dashboard](https://www.postman.com/cloudflare-r2/workspace/cloudflare-r2/collection/20913290-14ddd8d8-3212-490d-8647-88c9dc557659?action=share&creator=20913290&ctx=document
```suggestion
1. Go to the [Postman dashboard](https://www.postman.com/cloudflare-r2/workspace/cloudflare-r2/collection/20913290-14ddd8d8-3212-490d-8647-88c9dc557659?action=share&creator=20913290&ctx=documentation) > **Variables**.
```

2022-06-09 17:07 UTC, deadlypants1973 approved these changes

2022-06-09 17:08 UTC, deadlypants1973 commented on content/r2/examples/postman.md
> +After you have created you API token in the Cloudflare dashboard:
```suggestion
After you have created your API token in the Cloudflare dashboard:
```

2022-06-09 17:13 UTC, deadlypants1973 commented on content/r2/examples/postman.md
> +![ListBuckets in Postman](/r2/static/postman-r2-list-buckets.png)
```suggestion
![Follow the instructions above to access ListBuckets in the Postman dashboard](/r2/static/postman-r2-list-buckets.png)
```

2022-06-09 17:21 UTC, merged