[Analytics] Created Workers Analytics Engine section.
cloudflare/cloudflare-docs pull request #4743
Opened 2022-06-08 15:08 UTC by angelampcosta

2022-06-08 17:26 UTC, cmackenzie1 commented on content/analytics/analytics-engine/get-started.md
> +    { name = <EVENT_NAME> }
```suggestion
    { name = "<EVENT_NAME>" }
```

2022-06-08 17:27 UTC, cmackenzie1 commented on content/analytics/analytics-engine/get-started.md
> +```bash
```suggestion
```toml
```

2022-06-08 17:28 UTC, cmackenzie1 commented on content/analytics/analytics-engine/get-started.md
> +```bash
```suggestion
```js
```

2022-06-08 17:29 UTC, cmackenzie1 commented on content/analytics/analytics-engine/get-started.md
> +Data can be queried using either GraphQL or SQL API.
```suggestion
Data can be queried using either [GraphQL](/analytics/graphql-api/) or SQL API.
```

2022-06-08 17:30 UTC, cmackenzie1 commented on content/analytics/analytics-engine/get-started.md
> +The GraphQL UI powers our dashboard and is better suited for building interactive dashboards. At this time, the GraphQL API exposes a highly simplified schema, though we plan to support a richer sche
```suggestion
The GraphQL API powers our dashboard and is better suited for building interactive dashboards. At this time, the GraphQL API exposes a highly simplified schema, though we plan to support a richer schema over time.
```

2022-06-08 17:30 UTC, cmackenzie1 commented on content/analytics/analytics-engine/get-started.md
> +```bash
```suggestion
```sql
```

2022-06-08 17:31 UTC, cmackenzie1 commented on content/analytics/analytics-engine/get-started.md
> +Workers Analytics Engine is optimized for powering time series analytics that can be visualized using tools like Grafana. Every event written from the runtime is automatically populated with a `datet
```suggestion
Workers Analytics Engine is optimized for powering time series analytics that can be visualized using tools like Grafana. Every event written from the runtime is automatically populated with a `timestamp` field. It is expected that most time series will round, and then GROUP BY the `timestamp`. For example:
```

2022-06-08 17:32 UTC, cmackenzie1 commented on content/analytics/analytics-engine/get-started.md
> +```bash
```suggestion
```sql
```

2022-06-08 17:33 UTC, cmackenzie1 commented on content/analytics/analytics-engine/get-started.md
> +SELECT label_1 as city, avg(metric_2) as avg_humidity
@46bit are these column names correct? I don't recall there being an underscore.

2022-06-09 09:18 UTC, marciocloudflare approved these changes

2022-06-09 09:18 UTC, marciocloudflare commented on content/analytics/analytics-engine/_index.md
> +Also as our customer, you may need to expose analytics to your customers. With Workers Analytics Engine, you can quickly deploy analytics about your own product that your customers can use.
```suggestion
Also, as our customer you may need to expose analytics to your customers. With Workers Analytics Engine, you can quickly deploy analytics about your own product that your customers can use.
```

2022-06-09 09:18 UTC, marciocloudflare commented on content/analytics/analytics-engine/get-started.md
> +All data in Workers Analytics Engine is written to a dataset. A dataset is conceptually like a “table” in SQL; the rows and columns should have consistent meaning.
```suggestion
All data in Workers Analytics Engine is written to a dataset. A dataset is conceptually like a table in SQL: the rows and columns should have consistent meaning.
```

2022-06-09 09:18 UTC, marciocloudflare commented on content/analytics/analytics-engine/get-started.md
> +All data in Workers Analytics Engine is written to a dataset. A dataset is conceptually like a “table” in SQL; the rows and columns should have consistent meaning.
I think in one of our content critiques, we decided on not using quotes in this way

2022-06-09 09:18 UTC, marciocloudflare commented on content/analytics/analytics-engine/get-started.md
> +In the following example, we use the SQL API to query the top 10 cities that had the highest average humidity readings when the temperature was above 0:
```suggestion
In the following example, we use the SQL API to query the top 10 cities that had the highest average humidity readings when the temperature was above zero:
```

2022-06-09 09:18 UTC, marciocloudflare commented on content/analytics/analytics-engine/get-started.md
> +Workers Analytics Engine is optimized for powering time series analytics that can be visualized using tools like Grafana. Every event written from the runtime is automatically populated with a `times
```suggestion
Workers Analytics Engine is optimized for powering time series analytics that can be visualized using tools like Grafana. Every event written from the runtime is automatically populated with a `timestamp` field. It is expected that most time series will round, and then `GROUP BY` the `timestamp`. For example:
```

2022-06-09 09:18 UTC, marciocloudflare commented on content/analytics/analytics-engine/get-started.md
> +Workers Analytics Engine is optimized for powering time series analytics that can be visualized using tools like Grafana. Every event written from the runtime is automatically populated with a `times
I think `GROUP BY` is an SQL statement, and should be in between backticks. If not, please change to small caps as this makes it seem like we're shouting at the reader :)

2022-06-09 09:18 UTC, marciocloudflare commented on content/analytics/analytics-engine/get-started.md
> +This query first rounds the datetime field to the nearest five minutes. Then we group by that field and city and calculate the average humidity in each city for a five minute period.
```suggestion
This query first rounds the datetime field to the nearest five minutes. Then we group by that field and city, and calculate the average humidity in each city for a five minute period. 
```

2022-06-09 12:31 UTC, 46bit commented on content/analytics/analytics-engine/get-started.md
> +SELECT label_1 as city, avg(metric_2) as avg_humidity
@cmackenzie1 Yep, they're correct. `label_N` and `metric_N`. :)

2022-06-09 12:35 UTC, 46bit commented
I've had a read through - content looks good, and all the SQL examples should work 👍🏻 thanks!

2022-06-09 12:36 UTC, WalshyDev commented on content/analytics/analytics-engine/get-started.md
> +      labels: ["Seattle", "USA", "pro_sensor_9000”],
Fixed good old mac smart quotes
```suggestion
      labels: ["Seattle", "USA", "pro_sensor_9000"],
```

2022-06-09 13:04 UTC, 46bit commented on content/analytics/analytics-engine/get-started.md
> +  AND timestamp >= now() - 86400
We now support `INTERVAL`, so this could be rewritten to teach people about that feature

```suggestion
  AND timestamp >= now() - INTERVAL '1' DAY
```

2022-06-15 13:29 UTC, 46bit commented on content/analytics/analytics-engine/get-started.md
> +```
We'll need to implement that in the Wrangler CLI. As of right now the syntax is:

```toml
[[unsafe.bindings]]
type = "analytics_engine"
name = "<BINDING_NAME>"
```

That defaults to the dataset name being the same as the binding name, but you can also specify the dataset name:

```
[[unsafe.bindings]]
type = "analytics_engine"
name = "<BINDING_NAME>"
dataset = "<DATASET_NAME>"
```

Not sure whether to actually change the docs, we should PR wrangler instead?

2022-06-21 16:36 UTC, 46bit commented on content/analytics/analytics-engine/_index.md
> +At the moment, Workers Analytics Engine it is only available as an invite-only beta, open beta will start soon.
```suggestion
At the moment, Workers Analytics Engine is only available as an invite-only beta, open beta will start soon.
```

2022-06-21 16:44 UTC, 46bit commented on content/analytics/analytics-engine/get-started.md
> +  avg(metric_2) as avg_humidity,
Trailing comma:
```suggestion
  avg(metric_2) as avg_humidity
```

2022-06-21 16:44 UTC, 46bit commented on content/analytics/analytics-engine/get-started.md
> +  intDiv(datetime, 300) * 300 as t,
```suggestion
  intDiv(timestamp, 300) * 300 as t, 
```

2022-06-21 17:14 UTC, victor-perov reviewed
LGTM, just a few suggestions

2022-06-21 17:14 UTC, victor-perov commented on content/analytics/analytics-engine/get-started.md
> +The GraphQL API powers our dashboard and is better suited for building interactive dashboards. At this time, the GraphQL API exposes a highly simplified schema, though we plan to support a richer sch
I think we can add a few bits about the node and available dimensions. An example of GQL query would be also useful. Please let me know if I can help with that.

2022-06-21 17:14 UTC, victor-perov commented on content/analytics/analytics-engine/get-started.md
> +To access your dataset from the Workers runtime, you need to create a binding. A binding is an [environment variable](/workers/platform/environment-variables/) that you can use in the Workers runtime
```suggestion
To access your dataset from the Workers runtime, you need to create a binding. A binding is an [environment variable](/workers/platform/environment-variables/) that you can use in the Workers runtime which enables you to write to a dataset. A dataset is created implicitly after you define your binding and begin writing to it from a Worker.
```

2022-06-21 17:21 UTC, 46bit commented on content/analytics/analytics-engine/get-started.md
> +  intDiv(timestamp, 300) * 300 as t,
```suggestion
  intDiv(toUInt32(timestamp), 300) * 300 as t, 
```

2022-06-21 17:29 UTC, angelampcosta commented on content/analytics/analytics-engine/get-started.md
> +The GraphQL API powers our dashboard and is better suited for building interactive dashboards. At this time, the GraphQL API exposes a highly simplified schema, though we plan to support a richer sch
@victor-perov It would be great, if you could help.

2022-06-22 11:38 UTC, harrishancock commented on content/analytics/analytics-engine/get-started.md
> +To access your dataset from the Workers runtime, you need to create a binding. A binding is an [environment variable](/workers/platform/environment-variables/) that you can use in the Workers runtime
```suggestion
To access your dataset from the Workers runtime, you need to create a binding. A binding is like an [environment variable](/workers/platform/environment-variables/) that you can use in the Workers runtime which enables you to write to a dataset. A dataset is created implicitly after you define your binding and begin writing to it from a Worker.
```
Environment variables are one example of a binding, but not all bindings are environment variables.

2022-06-22 11:38 UTC, harrishancock commented on content/analytics/analytics-engine/get-started.md
> +## 3. Query data using GraphQL and SQL API.
```suggestion
## 3. Query data using GraphQL and SQL API
```
This was the only of the three numbered headings with terminal punctuation.

2022-06-22 11:38 UTC, harrishancock commented on content/analytics/analytics-engine/get-started.md
> +This query first rounds the datetime field to the nearest five minutes. Then we group by that field and city, and calculate the average humidity in each city for a five minute period.
```suggestion
This query first rounds the `timestamp` field to the nearest five minutes. Then we group by that field and city, and calculate the average humidity in each city for a five minute period. 
```

2022-06-22 11:38 UTC, harrishancock commented on content/analytics/analytics-engine/get-started.md
> +The SQL API is available as an HTTP rest endpoint at `/v4/$accountTag/analytics_engine/sql` using the `POST` and `GET` method.
```suggestion
The SQL API is available as an HTTP endpoint at `/v4/$accountTag/analytics_engine/sql` using the `POST` and `GET` method.
```

Or capitalize REST, if we're really using a REST architecture.

Separately, an example of how we expect SQL to be encoded in a GET method (e.g., in the URL's query parameters?) would be useful.

2022-06-22 19:32 UTC, victor-perov commented on content/analytics/analytics-engine/get-started.md
> +## 2. Write data from the Workers Runtime API
```suggestion

## 2. Write data from the Workers Runtime API
```

2022-06-22 19:32 UTC, victor-perov commented on content/analytics/analytics-engine/get-started.md
> +The GraphQL API powers our dashboard and is better suited for building interactive dashboards. At this time, the GraphQL API exposes a highly simplified schema, though we plan to support a richer sch
I can submit a commit to this branch with an example added to the bottom of this file.

2022-06-22 20:48 UTC, angelampcosta commented on content/analytics/analytics-engine/get-started.md
> +The GraphQL API powers our dashboard and is better suited for building interactive dashboards. At this time, the GraphQL API exposes a highly simplified schema, though we plan to support a richer sch
If it's easier for you, you can also add it to google doc https://docs.google.com/document/d/1j-T1Uc_nZ9Ie4pTPn3ikdlNpAHjwPNaMCoF60o9lYXU/edit# and I'll add it.

2022-06-24 13:25 UTC, twalwyn commented on content/analytics/analytics-engine/get-started.md
> +  async fetch(request: Request, env) {
```
 [WARNING] Processing wrangler.toml configuration:

    - "unsafe" fields are experimental and may change or break at any time.


✘ [ERROR] Expected ")" but found ":"

    src/index.js:12:21:
      12 │   async fetch(request: Request, env) {
         │                      ^
         ╵                      )


✘ [ERROR] Build failed with 1 error:

  src/index.js:12:21: ERROR: Expected ")" but found ":"
  ```
  
  I get the above error when running "wrangler publish" with this code snippet in a JS worker.

2022-06-24 20:59 UTC, twalwyn commented on content/analytics/analytics-engine/get-started.md
> +  async fetch(request: Request, env) {
```suggestion
  async fetch(request, env) {
```

It works if I remove the `:Request`

2022-06-24 21:00 UTC, cmackenzie1 commented on content/analytics/analytics-engine/get-started.md
> +  async fetch(request: Request, env) {
the `:Request` is TypeScript - should be removed since this is a JS example.

2022-06-24 21:03 UTC, twalwyn commented on content/analytics/analytics-engine/get-started.md
> +```sql
```suggestion
```sql
SELECT blob1 as city, avg(double2) as avg_humidity FROM analytics_engine WHERE dataset = 'WEATHER' AND double1 > 0 GROUP BY city ORDER BY avg_humidity DESC LIMIT 10
```

There are a number of issues with the query:
* There is a missing `GROUP BY city`
* For some reason, the query only executes if the whole statement is on a single line (I think this is a bug that needs to be fixed @46bit)

2022-06-24 21:06 UTC, twalwyn commented on content/analytics/analytics-engine/get-started.md
> +  label_1 as city,
```suggestion
  blob1 as city, 
```

2022-06-24 21:07 UTC, twalwyn commented on content/analytics/analytics-engine/get-started.md
> +  avg(metric_2) as avg_humidity
```suggestion
  avg(double2) as avg_humidity
```

2022-06-24 21:07 UTC, twalwyn commented on content/analytics/analytics-engine/get-started.md
> +  AND metric_1 > 0
```suggestion
  AND double1 > 0
```

2022-06-27 15:35 UTC, twalwyn commented on content/analytics/analytics-engine/get-started.md
> +      labels: ["Seattle", "USA", "pro_sensor_9000"],
```suggestion
      blobs: ["Seattle", "USA", "pro_sensor_9000"],
```

2022-06-27 15:35 UTC, twalwyn commented on content/analytics/analytics-engine/get-started.md
> +      metrics: [25, 0.5]
```suggestion
      doubles: [25, 0.5]
```

2022-06-27 15:36 UTC, tlozoot reviewed
I marked the paragraphs where we should change `labels` -> `blobs` and `metrics` -> `doubles`

2022-06-27 15:36 UTC, tlozoot commented on content/analytics/analytics-engine/get-started.md
> +      labels: ["Seattle", "USA", "pro_sensor_9000"],
update

2022-06-27 15:36 UTC, tlozoot commented on content/analytics/analytics-engine/get-started.md
> +SELECT blob1 as city, avg(double2) as avg_humidity FROM analytics_engine WHERE dataset = 'WEATHER' AND double1 > 0 GROUP BY city ORDER BY avg_humidity DESC LIMIT 10
update

2022-06-27 15:36 UTC, tlozoot commented on content/analytics/analytics-engine/get-started.md
> +  blob1 as city,
update

2022-06-27 15:36 UTC, tlozoot commented on content/analytics/analytics-engine/get-started.md
> +A metric is just a number type field that can be aggregated in some way – for example, it could be summed, averaged, or quantiled. A label is a string type field that can be used for grouping or filt
update

2022-06-27 15:37 UTC, tlozoot commented on content/analytics/analytics-engine/get-started.md
> +SELECT label_1 as city, avg(metric_2) as avg_humidity
This SQL query should be deleted

2022-06-27 15:40 UTC, twalwyn commented on content/analytics/analytics-engine/get-started.md
> +```sql
The code block below also needs to be a single line too

2022-06-27 15:44 UTC, twalwyn commented on content/analytics/analytics-engine/get-started.md
> +Once a binding is declared in Wrangler and your worker is deployed, you get a new environment variable in the Workers runtime that represents your Workers Analytics Engine dataset. This variable has
```suggestion
Once a binding is declared in Wrangler and your worker is deployed, you get a new environment variable in the Workers runtime that represents your Workers Analytics Engine dataset. This variable has a method, `writeDataPoint()`. A data point is a structured event which consists of a vector of blobs and a vector of doubles.
```

2022-06-27 15:45 UTC, twalwyn commented on content/analytics/analytics-engine/get-started.md
> +A metric is just a number type field that can be aggregated in some way – for example, it could be summed, averaged, or quantiled. A label is a string type field that can be used for grouping or filt
```suggestion
A double is just a number type field that can be aggregated in some way – for example, it could be summed, averaged, or quantiled. A blob is a string type field that can be used for grouping or filtering.
```

2022-06-27 15:45 UTC, twalwyn commented on content/analytics/analytics-engine/get-started.md
> +For example, suppose you are collecting air quality samples. Each data point would represent a reading from your weather sensor. Metrics might include numbers like the temperature or air pressure rea
```suggestion
For example, suppose you are collecting air quality samples. Each data point would represent a reading from your weather sensor. Doubles might include numbers like the temperature or air pressure reading. The blobs could include the location of the sensor and the hardware identifier of the sensor.
```

2022-06-27 15:46 UTC, tlozoot commented on content/analytics/analytics-engine/get-started.md
> +Note that, for our initial version, labels and metrics are accessed via names that have 1-based indexing. In the future, when we let developers name labels and metrics in their binding, these names w
update labels/metrics

2022-06-27 16:55 UTC, 46bit commented on content/analytics/analytics-engine/get-started.md
> +The SQL API is available as an HTTP endpoint at `/v4/$accountTag/analytics_engine/sql` using the `POST` and `GET` method.
```suggestion
The SQL API is available as an HTTP endpoint at `/v4/$accountTag/analytics_engine/sql` using the `POST` and `GET` method. You need to supply a Cloudflare [API Token](https://dash.cloudflare.com/profile/api-tokens) that has the `Account Analytics Read` permission.
```

2022-06-27 17:01 UTC, 46bit commented on content/analytics/analytics-engine/get-started.md
> +In the following example, we use the SQL API to query the top 10 cities that had the highest average humidity readings when the temperature was above zero:
```suggestion
In the following example, we use the SQL API to query the top 10 cities that had the highest average humidity readings when the temperature was above zero.
```

2022-06-27 17:02 UTC, 46bit commented on content/analytics/analytics-engine/get-started.md
> +```sql
```suggestion
Here's how we represent that as SQL:

```sql
```

2022-06-27 18:06 UTC, 46bit commented on content/analytics/analytics-engine/get-started.md
> +
```suggestion
You can then perform the query using any HTTP client. Here's an example of doing it using cURL:
```
curl -X GET "https://api.cloudflare.com/client/v4/accounts/YOUR_ACCOUNT_ID/analytics_engine/sql" -H "Authorization: Bearer YOUR_API_TOKEN" -H "Content-Type:application/json" -X POST -d "SELECT blob1 as city, avg(double2) as avg_humidity FROM analytics_engine WHERE dataset = 'WEATHER' AND double1 > 0 GROUP BY city ORDER BY avg_humidity DESC LIMIT 10"
```
```

2022-06-27 21:30 UTC, tlozoot requested changes
Renaming blobs ad doubles

2022-06-27 21:30 UTC, tlozoot commented on content/analytics/analytics-engine/get-started.md
> +In our initial version, developers are responsible for **providing fields in a consistent order**, so that they have the same semantics when querying. In a future iteration, we plan to let developers
```suggestion
In our initial version, developers are responsible for **providing fields in a consistent order**, so that they have the same semantics when querying. In a future iteration, we plan to let developers name their blobs and doubles in the binding, and then use these names when writing data points in the runtime.
```

2022-06-27 21:30 UTC, tlozoot commented on content/analytics/analytics-engine/get-started.md
> +Note that, for our initial version, labels and metrics are accessed via names that have 1-based indexing. In the future, when we let developers name labels and metrics in their binding, these names w
```suggestion
Note that, for our initial version, blobs and doubles are accessed via names that have 1-based indexing. In the future, when we let developers name blobs and doubles in their binding, these names will also be available via the SQL API.
```

2022-06-27 21:30 UTC, tlozoot commented on content/analytics/analytics-engine/get-started.md
> +SELECT label_1 as city, avg(metric_2) as avg_humidity
```suggestion
```

2022-06-27 21:30 UTC, tlozoot commented on content/analytics/analytics-engine/get-started.md
> +FROM analytics_engine
```suggestion
```

2022-06-27 21:30 UTC, tlozoot commented on content/analytics/analytics-engine/get-started.md
> +WHERE
```suggestion
```

2022-06-27 21:30 UTC, tlozoot commented on content/analytics/analytics-engine/get-started.md
> +  dataset = 'WEATHER'
```suggestion
```

2022-06-27 21:30 UTC, tlozoot commented on content/analytics/analytics-engine/get-started.md
> +```
```suggestion
```

2022-06-27 21:30 UTC, tlozoot commented on content/analytics/analytics-engine/get-started.md
> +LIMIT 10
```suggestion
```

2022-06-27 21:30 UTC, tlozoot commented on content/analytics/analytics-engine/get-started.md
> +LIMIT 10
```suggestion
```

2022-06-27 21:30 UTC, tlozoot commented on content/analytics/analytics-engine/get-started.md
> +ORDER BY avg_humidity DESC
```suggestion
```

2022-06-27 21:30 UTC, tlozoot commented on content/analytics/analytics-engine/get-started.md
> +  AND metric_1 > 0
```suggestion
```

2022-06-27 21:30 UTC, tlozoot commented on content/analytics/analytics-engine/get-started.md
> +      blobs: ["Seattle", "USA", "pro_sensor_9000"],
```suggestion
      'blobs': ["Seattle", "USA", "pro_sensor_9000"],
```

2022-06-27 21:30 UTC, tlozoot commented on content/analytics/analytics-engine/get-started.md
> +      doubles: [25, 0.5]
```suggestion
      'doubles': [25, 0.5]
```

2022-06-27 21:43 UTC, tlozoot approved these changes
Renaming blobs ad doubles

2022-06-27 21:48 UTC, merged