refactored direct uploads docs :)
cloudflare/cloudflare-docs pull request #4760
Opened 2022-06-09 17:33 UTC by nevikashah

2022-06-15 13:09 UTC, deadlypants1973 requested changes

2022-06-15 13:09 UTC, deadlypants1973 commented on content/pages/platform/direct-upload.md
> +Within a direct uploads project, you can switch between creating deployments with either Wrangler or Drag and Drop. However, you cannot create deployments with these methods on a standard Git integra
```suggestion
Within a direct uploads project, you can switch between creating deployments with either Wrangler or Drag and Drop. However, you cannot create deployments with these methods on a standard Git integrated project.
```

2022-06-15 13:09 UTC, deadlypants1973 commented on content/pages/platform/direct-upload.md
> +* Drag and drop: A zip file or single folder of assets
```suggestion
* Drag and Drop: A zip file or single folder of assets.
```
Capitalization consistency.

2022-06-15 13:09 UTC, deadlypants1973 commented on content/pages/platform/direct-upload.md
> +* Wrangler: A single folder of assets
```suggestion
* Wrangler: A single folder of assets. (Zip files are not supported.)
```

2022-06-15 13:09 UTC, deadlypants1973 commented on content/pages/platform/direct-upload.md
> +Once you have logged into Wrangler, it’s time to create your first project. Execute the following command:
```suggestion
Log in to Wrangler with the `wrangler login` command then run the following command:
```

2022-06-15 13:09 UTC, deadlypants1973 commented on content/pages/platform/direct-upload.md
> +You will then be prompted to specify the project name. Your project will be served at `<project-name>.pages.dev`. You will also be prompted to specify your production branch.
```suggestion
You will then be prompted to specify the project name. Your project will be served at `<PROJECT_NAME>.pages.dev`. You will also be prompted to specify your production branch. 
```

2022-06-15 13:09 UTC, deadlypants1973 commented on content/pages/platform/direct-upload.md
> +#### Publish your assets
```suggestion
#### Publish your assets

```

2022-06-15 13:09 UTC, deadlypants1973 commented on content/pages/platform/direct-upload.md
> +$ wrangler pages publish <output-directory>
```suggestion
$ wrangler pages publish <OUTPUT_DIRECTORY>
```

2022-06-15 13:09 UTC, deadlypants1973 commented on content/pages/platform/direct-upload.md
> +Your production deployment will be available at `<project-name>.pages.dev`.
```suggestion
Your production deployment will be available at `<PROJECT_NAME>.pages.dev`.
```

2022-06-15 13:09 UTC, deadlypants1973 commented on content/pages/platform/direct-upload.md
> +Before using the publish command, you will need to make sure you are inside the project. If not, you can also pass in the project path.
```suggestion
Before using the `wrangler publish` command, you will need to make sure you are inside the project. If not, you can also pass in the project path. 
```

2022-06-15 13:09 UTC, deadlypants1973 commented on content/pages/platform/direct-upload.md
> +
```suggestion
```

2022-06-15 13:09 UTC, deadlypants1973 commented on content/pages/platform/direct-upload.md
> +
```suggestion
 
```

2022-06-15 13:09 UTC, deadlypants1973 commented on content/pages/platform/direct-upload.md
> +
```suggestion
 
```

2022-06-15 13:09 UTC, deadlypants1973 commented on content/pages/platform/direct-upload.md
> +$ wrangler pages publish <output-directory> --branch=<branch-name>
```suggestion
$ wrangler pages publish <OUTPUT_DIRECTORY> --branch=<BRANCH_NAME>
```

2022-06-15 13:09 UTC, deadlypants1973 commented on content/pages/platform/direct-upload.md
> +However, to publish assets to a preview environment, you can execute:
```suggestion
However, to publish assets to a preview environment, run: 
```

2022-06-15 13:09 UTC, deadlypants1973 commented on content/pages/platform/direct-upload.md
> +
```suggestion

For every branch you create, a branch alias will be available to you at `<BRANCH_NAME>.<PROJECT_NAME>.pages.dev`. 

```

2022-06-15 13:09 UTC, deadlypants1973 commented on content/pages/platform/direct-upload.md
> +If you would like to streamline the project creation and asset publishing steps, you can also use the publish command to both create and publish assets at the same time. If you execute this command f
```suggestion
If you would like to streamline the project creation and asset publishing steps, you can also use the publish command to both create and publish assets at the same time. If you execute this command first, you will still be prompted to specify your project name and production branch. These values will still be cached for subsequent deployments as stated above. If the cache already exists and you would like to create a new project, you will need to run the [`create` command](#create-your-project). 
```

2022-06-15 13:09 UTC, deadlypants1973 commented on content/pages/platform/direct-upload.md
> +Your project will be served from `<project-name>.pages.dev`. Next drag and drop your build output directory into the uploading frame. Once your files have been successfully uploaded, select **Save an
```suggestion
Your project will be served from `<PROJECT_NAME>.pages.dev`. Next drag and drop your build output directory into the uploading frame. Once your files have been successfully uploaded, select **Save and Deploy** and continue to your newly deployed project. 
```
all caps for input values is a CF style guide convention

2022-06-15 13:09 UTC, deadlypants1973 commented on content/pages/platform/direct-upload.md
> +* For Drag and Drop uploads: there is a 1,000 file limit
```suggestion

Regarding file count:

* For Wrangler uploads, there is a 20,000 file limit.
* For Drag and Drop uploads, there is a 1,000 file limit.
```

2022-06-15 16:52 UTC, isaac-mcfadyen commented on content/pages/platform/direct-upload.md
> +You will then be prompted to specify the project name. Your project will be served at `<project-name>.pages.dev`. You will also be prompted to specify your production branch.
Is this accurate? If the name is already taken Pages appends a random 3 letter/number string to the end, should that be mentioned?

2022-06-15 17:23 UTC, deadlypants1973 approved these changes

2022-06-15 17:23 UTC, deadlypants1973 commented on content/pages/platform/direct-upload.md
>  ## Methods to uploading
```suggestion
## Upload methods
```

2022-06-15 17:37 UTC, deadlypants1973 commented on content/pages/platform/direct-upload.md
> +With Direct Uploads, you can bring your prebuilt assets right to Pages. Bring your own Continuous Integration (CI) tooling to handle the build and deploy your website's assets straight to the Cloudfl
```suggestion
With Direct Uploads, you can bring your prebuilt assets directly to Pages. Bring your own Continuous Integration (CI) tooling to handle the build and deploy your website's assets straight to the Cloudflare edge network.
```

2022-06-15 17:44 UTC, deadlypants1973 requested changes

2022-06-15 17:44 UTC, deadlypants1973 commented on content/pages/platform/direct-upload.md
> +With Direct Uploads, you can bring your prebuilt assets directly to Pages. Bring your own Continuous Integration (CI) tooling to handle the build and deploy your website's assets straight to the Clou
This opener needs to be rewritten to state:
1. what is direct uploads
2. how it works
3. what this guide will instruct developer to do

2022-06-15 17:44 UTC, deadlypants1973 commented on content/pages/platform/direct-upload.md
>  Once you have your prebuilt assets ready, there are two ways to begin uploading:
```suggestion
After you have your prebuilt assets ready, there are two ways to begin uploading: 
```

2022-06-15 17:44 UTC, deadlypants1973 commented on content/pages/platform/direct-upload.md
> +Within a direct uploads project, you can switch between creating deployments with either Wrangler or Drag and Drop. However, you cannot create deployments with these methods on a standard Git integra
```suggestion
Within a Direct Uploads project, you can switch between creating deployments with either Wrangler or Drag and Drop. However, you cannot create deployments with these methods on a standard Git integrated project.
```

2022-06-15 17:44 UTC, deadlypants1973 commented on content/pages/platform/direct-upload.md
> +Within a direct uploads project, you can switch between creating deployments with either Wrangler or Drag and Drop. However, you cannot create deployments with these methods on a standard Git integra
What is the second sentence saying?

2022-06-15 17:44 UTC, deadlypants1973 commented on content/pages/platform/direct-upload.md
>  * [Wrangler](/pages/platform/direct-upload/#wrangler-cli).
```suggestion
* [Wrangler](/pages/platform/direct-upload/#wrangler-cli): the Workers CLI.
```

2022-06-15 17:44 UTC, deadlypants1973 commented on content/pages/platform/direct-upload.md
> +$ wrangler pages project create
There is no need to specify a directory right? specifically what is the developer not able to do?

2022-06-15 17:44 UTC, deadlypants1973 commented on content/pages/platform/direct-upload.md
> +* [Drag and Drop](/pages/platform/direct-upload/#drag-and-drop).
```suggestion
* [Drag and Drop](/pages/platform/direct-upload/#drag-and-drop): 
```

2022-06-15 17:44 UTC, deadlypants1973 commented on content/pages/platform/direct-upload.md
> +* [Drag and Drop](/pages/platform/direct-upload/#drag-and-drop).
This needs a short description. Also is drag and drop even included in this guide?

2022-06-15 17:44 UTC, deadlypants1973 commented on content/pages/platform/direct-upload.md
>  If using the drag and drop method, a red warning symbol will appear next to an asset if too large and thus unsuccessfully uploaded. In this case, you may choose to delete that asset but you cannot re
```suggestion
If using the Drag and Drop method, a red warning symbol will appear next to an asset if too large and thus unsuccessfully uploaded. In this case, you may choose to delete that asset but you cannot replace it. In order to do so, you must reupload the entire project.
```

2022-06-15 18:26 UTC, isaac-mcfadyen commented on content/pages/platform/direct-upload.md
> +You will then be prompted to specify the project name. Your project will be served at `<PROJECT_NAME>.pages.dev`. You will also be prompted to specify your production branch.
```suggestion
You will then be prompted to specify the project name. Your project will be served at `<PROJECT_NAME>.pages.dev` (or your project name plus a few random characters if your project name is already taken). You will also be prompted to specify your production branch. 
```

2022-06-29 15:52 UTC, deadlypants1973 commented on content/pages/platform/direct-upload.md
> +With Direct Uploads, you can bring your prebuilt assets directly to Pages. Bring your own Continuous Integration (CI) tooling to handle the build and deploy your website's assets straight to the Clou
```suggestion
Direct Uploads enable you to upload your prebuilt assets to the Pages platform and deploy them to the Cloudflare edge network. This guide will instruct you how to upload your assets using Wrangler or the Drag and Drop method.
```

2022-06-29 15:53 UTC, deadlypants1973 approved these changes

2022-07-06 14:09 UTC, merged