DO NOT MERGE [LB] Notification updates
cloudflare/cloudflare-docs pull request #4912
Opened 2022-06-23 18:47 UTC by kodster28

PCX-1453

2022-06-24 08:38 UTC, marciocloudflare approved these changes

2022-06-24 08:38 UTC, marciocloudflare commented on content/load-balancing/_partials/_pool-create.md
> +    *   **Pool Notifications**: You can set up new alerts - and view existing alerts - to be notified when pools are enabled or disabled or pools or origins have changes in their [health status](/loa
```suggestion
    *   **Pool Notifications**: You can set up new alerts - and view existing alerts - to be notified when pools are enabled or disabled, or pools or origins have changes in their [health status](/load-balancing/understand-basics/health-details/).
```

2022-06-24 08:38 UTC, marciocloudflare commented on content/load-balancing/reference/migration-guides/health-monitor-notifications.md
> +Cloudflare is migrating the notifications used by load balancing [health monitors](/load-balancing/understand-basics/monitors) to use Cloudflare's centralized [Notifications Service](/fundamentals/no
```suggestion
Cloudflare is migrating the notifications used by load balancing [health monitors](/load-balancing/understand-basics/monitors/) to use Cloudflare's centralized [Notifications Service](/fundamentals/notifications/).
```

2022-06-24 08:38 UTC, marciocloudflare commented on content/load-balancing/reference/migration-guides/health-monitor-notifications.md
> +1. For **Health Check Notifications**, check the value is toggled to **On**.
```suggestion
1. Log into the [Cloudflare dashboard](https://dash.cloudflare.com) and select your account and domain.
2. Go to **Traffic** > **Load Balancing**.
3. Click **Manage Pools**.
4. On a pool, click **Edit**.
5. For **Health Check Notifications**, check the value is toggled to **On**.
```

2022-06-24 08:38 UTC, marciocloudflare commented on content/load-balancing/reference/migration-guides/health-monitor-notifications.md
> +- If using the [Cloudflare API](https://api.cloudflare.com/#account-load-balancer-pools-list-pools), check the `notification_filter` object. Health checks with enabled legacy notifications will have
```suggestion
If using the [Cloudflare API](https://api.cloudflare.com/#account-load-balancer-pools-list-pools), check the `notification_filter` object. Health checks with enabled legacy notifications will have something like:
```

2022-06-24 08:38 UTC, marciocloudflare commented on content/load-balancing/reference/migration-guides/health-monitor-notifications.md
> +- If using the [Cloudflare API](https://api.cloudflare.com/#account-load-balancer-pools-list-pools), check the `notification_filter` object. Health checks with enabled legacy notifications will have
I removed this as it seemed weird to have an unordered list with only one item. Feel free to ignore me if there's something I'm missing here :)

2022-06-24 08:38 UTC, marciocloudflare commented on content/load-balancing/reference/migration-guides/health-monitor-notifications.md
> +If using the Cloudflare API, send a [PATCH](https://api.cloudflare.com/#account-load-balancer-pools-patch-pool) request that includes the following objects.
```suggestion
If using the Cloudflare API, send a [`PATCH`](https://api.cloudflare.com/#account-load-balancer-pools-patch-pool) request that includes the following objects.
```

2022-06-24 08:38 UTC, marciocloudflare commented on content/load-balancing/reference/migration-guides/health-monitor-notifications.md
> +"notification_email": "",
Should this field include something like `<YOUR_EMAIL>`?

2022-06-24 16:13 UTC, kodster28 commented on content/load-balancing/reference/migration-guides/health-monitor-notifications.md
> +"notification_email": "",
It's actually meant to remove the email value.

2022-08-18 14:38 UTC, tc80 requested changes

2022-08-18 14:38 UTC, tc80 commented on content/load-balancing/reference/migration-guides/health-monitor-notifications.md
> +Cloudflare’s account-level [Notifications Service](/fundamentals/notifications/) is now the centralized location for most Cloudflare services. This change promotes consistency and streamlined adminis
```suggestion
Cloudflare’s account-level [Notifications Service](/fundamentals/notifications/) is now the centralized location for most Cloudflare services. This change promotes consistency and streamlined administration, as well as gives you more options for notification delivery such as configuring webhooks or associating multiple pools with the same notification. These new notifications will also be managed at the account level instead of the zone level.
```

2022-08-18 14:38 UTC, tc80 commented on content/load-balancing/reference/migration-guides/health-monitor-notifications.md
> +If using the [Cloudflare API](https://api.cloudflare.com/#account-load-balancer-pools-list-pools), check the `notification_filter` object. Health checks with enabled legacy notifications will have so
Maybe we should also include that this only matters for pools that have `notification_email` set. If a pool does not have a `notification_email` (i.e. it is an empty string `""`), then `notification_filter` does not really matter, since no emails will be fired anyway.

2022-08-18 14:38 UTC, tc80 commented on content/load-balancing/reference/migration-guides/health-monitor-notifications.md
> +If using the Cloudflare API, send a [`PATCH`](https://api.cloudflare.com/#account-load-balancer-pools-patch-pool) request that includes the following objects.
I'm wondering if this is overkill to also clear out `notification_filter`, but it should be fine either way.

Clearing out only the `notification_email` is sufficient, and will line-up with our implementation for the new PATCH pools endpoint (https://api.staging.cloudflare.com/#account-load-balancer-pools-patch-pools)

2022-08-18 14:38 UTC, tc80 commented on content/load-balancing/reference/migration-guides/health-monitor-notifications.md
> +</details>
On somewhere on this page, we should mention that notifications for all pools can be cleared out at once using the new bulk-PATCH endpoint https://api.staging.cloudflare.com/#account-load-balancer-pools-patch-pools  

So once a customer has migrated all of their alerts, the customer can just call this endpoint once with `{notification_email: ""}`, which will set all emails to `""`, effectively removing the possibility of firing these deprecated notifications. We also need to clarify that this new endpoint uses the pagination parameters (Pagination under https://api.cloudflare.com/#getting-started-requests), so the number of pools affected by a single bulk-PATCH may not include all of the pools. We currently only support the query params `limit`/`offset` or `per_page`/`page` (these are equivalent, just user preference whether to use one or another), but not `direction` nor `order` for this endpoint. 

I don't think we need to document this anywhere, but just FYI I believe `limit` and `per_page` are 25 by default, and must be at least 5. `offset` and `page` need to be a multiple of `limit`/`per_page`, so for example `limit=5&offset=2` is not ok, but `limit=5&offset=0` or `limit=5&offset=5` is okay.

2022-08-18 15:45 UTC, tc80 requested changes

2022-08-18 15:45 UTC, tc80 commented on content/load-balancing/reference/migration-guides/health-monitor-notifications.md
> +You should also pay attention to the `notification_emails` parameter. Even if the `notification_filter` indicates that a health checks should send notifications, those will only be sent if there are
```suggestion
You should also pay attention to the `notification_email` parameter. Even if the `notification_filter` indicates that health checks should send notifications, those will only be sent if an email address is present in `notification_email`.
```

2022-08-18 15:45 UTC, tc80 commented on content/load-balancing/reference/migration-guides/health-monitor-notifications.md
> +If using the Cloudflare API, we recently added a [`PATCH`](https://api.cloudflare.com/#account-load-balancer-pools-patch-pool) endpoint so you can easily remove email notifications from multiple pool
```suggestion
If using the Cloudflare API, we recently added a [`PATCH`](https://api.cloudflare.com/#account-load-balancer-pools-patch-pools) endpoint so you can easily remove email notifications from multiple pools at the same time.
```

2022-08-18 15:52 UTC, tc80 approved these changes
lgtm! thanks for getting this out

2022-08-18 17:07 UTC, kodster28 commented
This branch got into too weird of a state, changing to #5568

2022-08-18 17:07 UTC, closed without merging