Add docs for Oblivious DNS over HTTPS
cloudflare/cloudflare-docs pull request #493
Opened 2020-12-14 21:25 UTC by tanyav2

2020-12-15 11:50 UTC, Lekensteyn requested changes
This should not just be a statement of work that we have done. It should be rewritten to be more user-centric:

- How can can a user use ODoH?
- How can someone set up a proxy or target?
- Which draft version is implemented?

It should emphasize the this is experimental, users should not rely on it for critical purposes.

2020-12-28 18:39 UTC, abracchi-tw requested changes

2020-12-28 18:39 UTC, abracchi-tw commented on products/1.1.1.1/src/content/fun-stuff/oblivious-dns-over-https.md
> +Oblivious DNS over HTTPS (or ODoH) is a new DNS protocol still in the works that separates client IP addresses from their DNS queries by routing the DNS queries over a proxy, so that the DNS resolver
Please note that this protocol and all related implementations are currently **experimental**.

2020-12-28 18:39 UTC, abracchi-tw commented on products/1.1.1.1/src/content/fun-stuff/oblivious-dns-over-https.md
> +Follow the progress of ODoH by following the IETF draft [here](https://datatracker.ietf.org/doc/draft-pauly-dprive-oblivious-doh/).
To follow the progress of ODoH, check out this [IETF draft](https://datatracker.ietf.org/doc/draft-pauly-dprive-oblivious-doh/).

2020-12-28 18:39 UTC, abracchi-tw commented on products/1.1.1.1/src/content/fun-stuff/oblivious-dns-over-https.md
> +We have open sourced our interoperable ODoH library implementations in Rust, [odoh-rs](https://github.com/cloudflare/odoh-rs), and Go, [odoh-go](https://github.com/cloudflare/odoh-go), which you can
You can use our open-source, interoperable ODoH library implementation (both in [Rust](https://github.com/cloudflare/odoh-rs) and [Go](https://github.com/cloudflare/odoh-go)) to implement your own client or target resolver. Our test clients are also open source in both [Rust](https://github.com/cloudflare/odoh-client-rs) and [Go](https://github.com/cloudflare/odoh-client-go), which you can use to demo ODoH queries.

2020-12-28 18:39 UTC, abracchi-tw commented on products/1.1.1.1/src/content/fun-stuff/oblivious-dns-over-https.md
> +We are not aware of any DNS clients like [dnscrypt-proxy](https://github.com/DNSCrypt/dnscrypt-proxy) that currently implement ODoH, but watch out for developments in the future!
do we need to specify this? can we re-word it to just say:

For the time being, DNS clients like [dnscrypt-proxy](https://github.com/DNSCrypt/dnscrypt-proxy) don't implement ODoH.

2020-12-28 18:39 UTC, abracchi-tw commented on products/1.1.1.1/src/content/fun-stuff/oblivious-dns-over-https.md
> +In one terminal, start the proxy:
1. In a Terminal window, start the proxy:

2020-12-28 18:39 UTC, abracchi-tw commented on products/1.1.1.1/src/content/fun-stuff/oblivious-dns-over-https.md
> +From another terminal, use the client to send queries:
2. Open a second Terminal window and use the client to send queries:

2021-03-26 12:01 UTC, abracchi-tw commented
hey @Lekensteyn I see there are some changes still pending - happy to chat about them if needed, but I'd like to close out/merge this one!

2021-06-10 13:13 UTC, 888520ll19811209ll approved these changes

2021-07-21 09:52 UTC, marciocloudflare commented
Closing as this is outdated

2021-07-21 09:52 UTC, closed without merging