[Workers] Document wrangler's proxy support
cloudflare/cloudflare-docs pull request #5047
Opened 2022-07-06 13:11 UTC by rozenmd

2022-07-06 13:14 UTC, rozenmd commented on content/workers/wrangler/configuration.md
> +The first non-empty environment variable named https_proxy, HTTPS_PROXY, http_proxy or HTTP_PROXY will be used when wrangler makes outgoing requests.
```suggestion
The first non-empty environment variable named `https_proxy`, `HTTPS_PROXY`, `http_proxy` or `HTTP_PROXY` will be used when wrangler makes outgoing requests.
```

2022-07-07 13:19 UTC, deadlypants1973 requested changes

2022-07-07 13:19 UTC, deadlypants1973 commented on content/workers/wrangler/configuration.md
> +## Proxy Support
```suggestion
## Proxy support
```

2022-07-07 13:19 UTC, deadlypants1973 commented on content/workers/wrangler/configuration.md
> +The first non-empty environment variable named `https_proxy`, `HTTPS_PROXY`, `http_proxy` or `HTTP_PROXY` will be used when wrangler makes outgoing requests.
Is this an action that the user is doing or observing? It needs directions if this is something the user is doing. For example:

To __(goal:what is dev doing?)___, go to __(place: dashboard? terminal?)___, and ___(action that dev needs to do)___.

2022-07-07 13:19 UTC, deadlypants1973 commented on content/workers/wrangler/configuration.md
> +For example, on macOS this can be done by adding `HTTP_PROXY=http://<YOUR_PROXY_HOST>:<YOUR_PROXY_PORT>` before your wrangler commands, as shown below:
Do you need to set up environment variables before doing this step?

2022-07-07 13:19 UTC, deadlypants1973 commented on content/workers/wrangler/configuration.md
> +Wrangler supports the use of proxies via environment variables.
Need to answer "why" would a dev do this and "how".

2022-07-07 13:23 UTC, rozenmd commented on content/workers/wrangler/configuration.md
> +For example, on macOS this can be done by adding `HTTP_PROXY=http://<YOUR_PROXY_HOST>:<YOUR_PROXY_PORT>` before your wrangler commands, as shown below:
This step explains how to set up the environment variables

2022-07-08 08:37 UTC, rozenmd commented on content/workers/wrangler/configuration.md
> +Wrangler supports the use of proxies via environment variables.
```suggestion
When using Wrangler in corporate environments that require the use of a VPN or HTTP proxy, you may come across a `UNABLE_TO_GET_ISSUER_CERT_LOCALLY` error.

You can use Wrangler with your VPN or HTTP proxy via environment variables. 
```

2022-07-08 08:37 UTC, rozenmd commented on content/workers/wrangler/configuration.md
> +The first non-empty environment variable named `https_proxy`, `HTTPS_PROXY`, `http_proxy` or `HTTP_PROXY` will be used when wrangler makes outgoing requests.
```suggestion
To use Wrangler behind a proxy, you'll need to set an environment variable pointing to your proxy.

Wrangler supports the following environment variable names:
- `https_proxy`
- `HTTPS_PROXY`
- `http_proxy`
- `HTTP_PROXY`

The first non-empty environment variable in this list will be used when wrangler makes outgoing requests.
```

2022-07-08 08:41 UTC, rozenmd commented on content/workers/wrangler/configuration.md
> +To use Wrangler behind a proxy, you'll need to set an environment variable pointing to your proxy.
```suggestion
```

2022-07-08 08:42 UTC, rozenmd commented on content/workers/wrangler/configuration.md
> +
```suggestion
```

2022-07-08 08:42 UTC, rozenmd commented on content/workers/wrangler/configuration.md
> +To use Wrangler behind a proxy, you'll need to set an environment variable pointing to your proxy.
```suggestion
```

2022-07-08 12:25 UTC, deadlypants1973 commented on content/workers/wrangler/configuration.md
> +The first non-empty environment variable in this list will be used when wrangler makes outgoing requests.
```suggestion
The first non-empty environment variable in this list will be used when Wrangler makes outgoing requests.
```

2022-07-08 13:36 UTC, rozenmd commented on content/workers/wrangler/configuration.md
> +When using Wrangler in corporate environments that require the use of a VPN or HTTP proxy, you may come across a `UNABLE_TO_GET_ISSUER_CERT_LOCALLY` error.
```suggestion
When using Wrangler in corporate environments that require the use of a VPN or HTTP proxy, you may come across a `UNABLE_TO_GET_ISSUER_CERT_LOCALLY` error, or your IT team may ask you to use a proxy.
```

2022-07-08 13:48 UTC, rozenmd commented on content/workers/wrangler/configuration.md
> +
```suggestion
For example, to configure this on macOS add `HTTP_PROXY=http://<YOUR_PROXY_HOST>:<YOUR_PROXY_PORT>` before your wrangler commands, as shown below:
```

2022-07-08 13:49 UTC, rozenmd commented on content/workers/wrangler/configuration.md
> +For example, on macOS this can be done by adding `HTTP_PROXY=http://<YOUR_PROXY_HOST>:<YOUR_PROXY_PORT>` before your wrangler commands, as shown below:
```suggestion
```

2022-07-08 13:49 UTC, rozenmd commented on content/workers/wrangler/configuration.md
> +For example, to configure this on macOS add `HTTP_PROXY=http://<YOUR_PROXY_HOST>:<YOUR_PROXY_PORT>` before your wrangler commands, as shown below:
```suggestion

For example, to configure this on macOS add `HTTP_PROXY=http://<YOUR_PROXY_HOST>:<YOUR_PROXY_PORT>` before your wrangler commands, as shown below:
```

2022-07-08 13:49 UTC, rozenmd commented on content/workers/wrangler/configuration.md
> +The first non-empty environment variable in this list will be used when Wrangler makes outgoing requests.
```suggestion
```

2022-07-08 13:50 UTC, rozenmd commented on content/workers/wrangler/configuration.md
> +
```suggestion
```

2022-07-08 14:08 UTC, rozenmd commented on content/workers/wrangler/configuration.md
> +You can use Wrangler with your VPN or HTTP proxy via your computer's environment variables.
```suggestion
You can use Wrangler with your VPN or HTTP proxy by configuring your computer's environment variables. 
```

2022-07-11 13:40 UTC, deadlypants1973 requested changes

2022-07-11 13:40 UTC, deadlypants1973 commented on content/workers/wrangler/configuration.md
> +You can use Wrangler with your VPN or HTTP proxy by configuring your computer's environment variables.
```suggestion
To enable proxy setup, use Wrangler with your VPN or HTTP proxy by configuring your computer's environment variables. Note that when using Wrangler in corporate environments that require the use of a VPN or HTTP proxy, you may come across a `UNABLE_TO_GET_ISSUER_CERT_LOCALLY` error. This error can be fixed with the use of environment variables.
```

2022-07-11 13:40 UTC, deadlypants1973 commented on content/workers/wrangler/configuration.md
> +
```suggestion
```

2022-07-11 13:40 UTC, deadlypants1973 commented on content/workers/wrangler/configuration.md
> +You can use Wrangler with your VPN or HTTP proxy by configuring your computer's environment variables.
Because proxy support is the main purpose of this paragraph, I rearranged this section to align with that.

2022-07-11 14:05 UTC, deadlypants1973 approved these changes

2022-07-11 14:05 UTC, merged