[Workers] Use suggested notation for kv_namespaces
cloudflare/cloudflare-docs pull request #5051
Opened 2022-07-06 14:58 UTC by emielvanseveren

implementation of https://github.com/cloudflare/cloudflare-docs/pull/4576

2022-07-06 16:37 UTC, koeninger commented
if we're changing kv examples to use the double bracket syntax, can you add a second example namespace for the benefit of people who aren't familiar with toml?

2022-07-06 17:21 UTC, emielvanseveren commented
@koeninger, sure, what about r2 buckets? Personally I'd change the default syntax as well, it decreases the chance of similar problems.

2022-07-06 19:17 UTC, koeninger commented
I can't speak for the R2 team, but I agree it seems less error prone

2022-07-06 21:03 UTC, koeninger approved these changes

2022-07-13 15:19 UTC, deadlypants1973 requested changes

2022-07-13 15:19 UTC, deadlypants1973 commented on content/workers/wrangler/configuration.md
> +  preview_id = ""
```suggestion
  binding = "<YOUR_NAMESPACE_0>"
  id = "<YOUR_ID>"
  preview_id = "<YOUR_PREVIEW_ID>"
```

2022-07-13 15:19 UTC, deadlypants1973 commented on content/workers/wrangler/configuration.md
> +  preview_id = ""
```suggestion
  binding = "<YOUR_NAMESPACE_1>"
  id = "<YOUR_ID>"
  preview_id = "<YOUR_PREVIEW_ID>"
```

2022-07-13 15:20 UTC, codewithkristian commented on content/workers/wrangler/configuration.md
> +  binding = "TEST_NAMESPACE_0"
Do these need to be space-indented like this?

2022-07-15 14:00 UTC, deadlypants1973 approved these changes

2022-07-15 14:01 UTC, merged