[R2] Document cf-create-bucket-if-missing
cloudflare/cloudflare-docs pull request #5058
Opened 2022-07-06 21:20 UTC by vlovich

2022-07-15 15:34 UTC, deadlypants1973 commented on content/r2/platform/s3-compatibility/extensions.md
> +See [above](#auto-creating-buckets-on-upload) for a more detailed explanation of when to use it. Usually it's better to split those operations out.
```suggestion
Add the `cf-create-bucket-if-missing` header with the value `true` to implicitly create the bucket if it does not exist yet. Refer to [above](#auto-creating-buckets-on-upload) for a more detailed explanation of when to use this.
```

2022-07-15 15:36 UTC, deadlypants1973 requested changes

2022-07-15 15:36 UTC, deadlypants1973 commented on content/r2/platform/s3-compatibility/extensions.md
> +See [above](#auto-creating-buckets-on-upload) for a more detailed explanation of when to use it. Usually it's better to split those operations out.
Split those operations out = what is this referring to?

2022-07-15 15:36 UTC, deadlypants1973 commented on content/r2/platform/s3-compatibility/extensions.md
> +See [above](#auto-creating-buckets-on-upload) for a more detailed explanation of when to use it. Usually it's better to split those operations out.
```suggestion
Add a header value of `cf-create-bucket-if-missing` with the value `true` to implicitly create the bucket if it does not exist yet. Refer to [above](#auto-creating-buckets-on-upload) for a more detailed explanation of when to use it. It is advised to split those operations out.
```

2022-07-25 15:28 UTC, vlovich commented on content/r2/platform/s3-compatibility/extensions.md
> +See [above](#auto-creating-buckets-on-upload) for a more detailed explanation of when to use it. Usually it's better to split those operations out.
`CreateBucket` + `PutObject`

2022-07-27 13:58 UTC, deadlypants1973 commented on content/r2/platform/s3-compatibility/extensions.md
> +ongoing network transfers instead of overlapping in the background.
```suggestion
If creating buckets on demand, you might initiate an upload with the assumption that a target bucket exists. When the `NoSuchBucket` error is returned, you may want to issue a `CreateBucket` operation. However, this is operationally problematic. If the body has already been partially consumed, the upload will need to be aborted. To solve this, developers use the [HTTP `100`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/100) response to detect whether the body should be sent or if the bucket needs to be created and the upload retried. This is how other object storage providers typically solve this error. However, Cloudflare does not support the HTTP `100` response. Additionally, if the HTTP `100` response was supported, there is still additional latency due to the round trips involved.
```

2022-07-27 13:58 UTC, deadlypants1973 commented on content/r2/platform/s3-compatibility/extensions.md
> +never returned. The bucket is instantiated with the equivalent of the following `CreateBucket` request:
```suggestion
To support being able to send an upload with a streaming body to a bucket that may not exist yet, uploads (such as, `PutObject` / `CreateMultipartUpload`) support a header being specified that will ensure the `NoSuchBucket` error is not returned. If it does not exist at the time of upload, the bucket is implicitly instantiated with the following `CreateBucket` request:
```

2022-07-27 13:58 UTC, deadlypants1973 commented on content/r2/platform/s3-compatibility/extensions.md
> +greater than 1000 buckets may also be useful.
```suggestion
This is only useful if you are creating buckets spontaneously because you do not know the name of the bucket or preferred access location ahead of time. For example, you have one bucket per one of your customers and the bucket is created on first upload to the bucket and not during account registration. In these cases, the [ListBuckets extension](#ListBuckets) to support accounts with greater than 1000 buckets may also be useful.
```

2022-07-27 14:05 UTC, deadlypants1973 approved these changes

2022-07-27 14:06 UTC, deadlypants1973 commented on content/r2/platform/s3-compatibility/extensions.md
> +
```suggestion
To support being able to send an upload with a streaming body to a bucket that may not exist yet, uploads (such as, `PutObject` / `CreateMultipartUpload`) support a header being specified that will ensure the `NoSuchBucket` error is not returned. If it does not exist at the time of upload, the bucket is implicitly instantiated with the following `CreateBucket` request:

```
PUT / HTTP/1.1
Host: bucket.account.r2.cloudflarestorage.com
<CreateBucketConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
   <LocationConstraint>auto</LocationConstraint>
</CreateBucketConfiguration>
```

```

2022-07-27 14:06 UTC, deadlypants1973 commented on content/r2/platform/s3-compatibility/extensions.md
> +To support being able to send an upload with a streaming body to a bucket that may not exist yet, uploads (such as, `PutObject` / `CreateMultipartUpload`) support a header being specified that will e
```suggestion
To support being able to send an upload with a streaming body to a bucket that may not exist yet, uploads (such as, `PutObject` / `CreateMultipartUpload`) support a header being specified that will ensure the `NoSuchBucket` error is not returned. If it does not exist at the time of upload, the bucket is implicitly instantiated with the following `CreateBucket` request:

```

2022-07-27 14:06 UTC, deadlypants1973 commented on content/r2/platform/s3-compatibility/extensions.md
>  If using Unicode in object key names, refer to the [Unicode Interoperability technical notes](/r2/learning/unicode-interoperability/).
```suggestion
If using Unicode in object key names, refer to [Unicode Interoperability](/r2/learning/unicode-interoperability/).
```

2022-07-27 14:22 UTC, pedrosousa approved these changes

2022-07-27 14:22 UTC, pedrosousa commented on content/r2/platform/s3-compatibility/extensions.md
> +To support being able to send an upload with a streaming body to a bucket that may not exist yet, uploads (such as, `PutObject` / `CreateMultipartUpload`) support a header being specified that will e
```suggestion
To support sending an upload with a streaming body to a bucket that may not exist yet, upload operations such as `PutObject` or `CreateMultipartUpload` allow you to specify a header that will ensure the `NoSuchBucket` error is not returned. If the bucket does not exist at the time of upload, it is implicitly instantiated with the following `CreateBucket` request:
```

2022-07-27 14:22 UTC, pedrosousa commented on content/r2/platform/s3-compatibility/extensions.md
> +```
```suggestion
```txt
```

2022-07-27 14:22 UTC, pedrosousa commented on content/r2/platform/s3-compatibility/extensions.md
> +This is only useful if you are creating buckets spontaneously because you do not know the name of the bucket or preferred access location ahead of time. For example, you have one bucket per one of yo
```suggestion
This is only useful if you are creating buckets on demand because you do not know the name of the bucket or the preferred access location ahead of time. For example, you have one bucket per one of your customers and the bucket is created on first upload to the bucket and not during account registration. In these cases, the [ListBuckets extension](#ListBuckets) to support accounts with more than 1000 buckets may also be useful.
```

2022-07-27 14:22 UTC, pedrosousa commented on content/r2/platform/s3-compatibility/extensions.md
> +If creating buckets on demand, you might initiate an upload with the assumption that a target bucket exists. When the `NoSuchBucket` error is returned, you may want to issue a `CreateBucket` operatio
```suggestion
If you are creating buckets on demand, you might initiate an upload with the assumption that a target bucket exists. In this situation, if you received a `NoSuchBucket` error, you would probably issue a `CreateBucket` operation. However, following this approach can cause issues: if the body has already been partially consumed, the upload will need to be aborted. A common solution to this issue, followed by other object storage providers, is to use the [HTTP `100`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/100) response to detect whether the body should be sent, or if the bucket must be created before retrying the upload. However, Cloudflare does not support the HTTP `100` response. Even if the HTTP `100` response was supported, you would still have additional latency due to the round trips involved.
```

2022-07-27 14:22 UTC, pedrosousa commented on content/r2/platform/s3-compatibility/extensions.md
> +Add a `cf-create-bucket-if-missing` header with the value `true` to implicitly create the bucket if it does not exist yet. Refer to [above](#auto-creating-buckets-on-upload) for a more detailed expla
```suggestion
Add a `cf-create-bucket-if-missing` header with the value `true` to implicitly create the bucket if it does not exist yet. Refer to the [Auto-creating buckets on upload](#auto-creating-buckets-on-upload) section for a more detailed explanation of when to add this header.
```

2022-07-27 14:22 UTC, pedrosousa commented on content/r2/platform/s3-compatibility/extensions.md
> +Add the `cf-create-bucket-if-missing` header with the value `true` to implicitly create the bucket if it does not exist yet. Refer to [above](#auto-creating-buckets-on-upload) for a more detailed exp
```suggestion
Add a `cf-create-bucket-if-missing` header with the value `true` to implicitly create the bucket if it does not exist yet. Refer to the [Auto-creating buckets on upload](#auto-creating-buckets-on-upload) section for a more detailed explanation of when to add this header.
```

2022-07-28 13:45 UTC, deadlypants1973 approved these changes

2022-07-28 13:45 UTC, merged