[R2] Document r2_list_honor_include compat flag.
cloudflare/cloudflare-docs pull request #5062
Opened 2022-07-06 23:34 UTC by vlovich

2022-07-06 23:34 UTC, vlovich commented
This should be merged after the validator has been updated.

2022-07-08 17:01 UTC, vlovich commented
Release isn't going out this week. The compat date will be pushed out.

2022-07-21 16:22 UTC, deadlypants1973 requested changes

2022-07-21 16:22 UTC, deadlypants1973 commented on content/r2/runtime-apis.md
> +    as `include: ['httpMetadata', 'customMetadata']` regardless of what is provided.
```suggestion
  - The [compatibility date](/workers/platform/compatibility-dates/) must be set to `2022-07-14` or later. If not, then the `r2_list_honor_include` compatibility flag must be set. It is treated as `include: ['httpMetadata', 'customMetadata']` regardless of what is provided.
```

2022-07-21 16:22 UTC, deadlypants1973 commented on content/r2/runtime-apis.md
> +    as `include: ['httpMetadata', 'customMetadata']` regardless of what is provided.
"Must be set...." in the wrangler.toml file?

2022-07-25 15:28 UTC, vlovich commented on content/r2/runtime-apis.md
> +    as `include: ['httpMetadata', 'customMetadata']` regardless of what is provided.
I think there's work ongoing to let you set compat dates / flags outside wrangler but it might be the only way currently. Wasn't sure if we wanted the wording to be explicit or just refer them to https://developers.cloudflare.com/workers/platform/compatibility-dates/ as that page will get updated with any changes.

2022-08-02 14:22 UTC, deadlypants1973 commented on content/workers/platform/compatibility-dates.md
> +Previously it had accidentally been a no-op.
```suggestion
With the `r2_list_honor_include` flag set, the `include` argument to R2 `list` options is honored.
```

2022-08-02 14:23 UTC, deadlypants1973 commented on content/workers/platform/compatibility-dates.md
> +<table>
```suggestion
### `R2` bucket `list` supports `include` option

<table>
```

2022-08-02 14:23 UTC, deadlypants1973 approved these changes

2022-08-03 08:49 UTC, deadlypants1973 commented
Waiting on runtime changes to take effect before merging. @vlovich, can you fix the merge conflict?

2022-09-15 18:11 UTC, KianNH reviewed
Looks like it's in the runtime now - made two suggestions since the API is returning a default date of `2022-08-04`

2022-09-15 18:11 UTC, KianNH commented on content/workers/platform/compatibility-dates.md
> +      <td>2022-07-14</td>
```suggestion
      <td>2022-08-04</td>
```

Ref: `The compatibility flag r2_list_honor_include became the default as of 2022-08-04 so does not need to be specified anymore.`

2022-09-15 18:11 UTC, KianNH commented on content/r2/runtime-apis.md
> +  - The [compatibility date](/workers/platform/compatibility-dates/) must be set to `2022-07-14` or later in your `wrangler.toml` file. If not, then the `r2_list_honor_include` compatibility flag mus
```suggestion
  - The [compatibility date](/workers/platform/compatibility-dates/) must be set to `2022-08-04` or later in your `wrangler.toml` file. If not, then the `r2_list_honor_include` compatibility flag must be set. It is treated as `include: ['httpMetadata', 'customMetadata']` regardless of what is provided.
```

Ref: `The compatibility flag r2_list_honor_include became the default as of 2022-08-04 so does not need to be specified anymore.`

2022-09-15 20:58 UTC, KianNH commented on content/r2/runtime-apis.md
> +  - The [compatibility date](/workers/platform/compatibility-dates/) must be set to `2022-07-14` or later in your `wrangler.toml` file. If not, then the `r2_list_honor_include` compatibility flag mus
nit: This reads to me as "set this date. if not, set this flag. it is treated as <include metadata> regardless of what is provided." I feel like it's missing a 'if not' before the 'it is treated as'.

Should it be "if neither of these are set, list operations will be treated as `include: ['httpMetadata', 'customMetadata']` regardless of what input you provide."

2022-09-22 16:14 UTC, vlovich commented on content/r2/runtime-apis.md
> +  - The [compatibility date](/workers/platform/compatibility-dates/) must be set to `2022-07-14` or later in your `wrangler.toml` file. If not, then the `r2_list_honor_include` compatibility flag mus
The [compatibility date](/workers/platform/compatibility-dates/) must be set to `2022-08-04` or later in your `wrangler.toml` file. If not, then the `r2_list_honor_include` compatibility flag must be set. Otherwise it is treated as `include: ['httpMetadata', 'customMetadata']` regardless of what the `include` option provided actually is.

2022-09-22 16:15 UTC, KianNH commented on content/r2/runtime-apis.md
> +  - The [compatibility date](/workers/platform/compatibility-dates/) must be set to `2022-07-14` or later in your `wrangler.toml` file. If not, then the `r2_list_honor_include` compatibility flag mus
👍 - sounds good!

2022-09-22 16:34 UTC, deadlypants1973 approved these changes

2022-09-22 16:34 UTC, deadlypants1973 commented on content/r2/data-access/workers-api/workers-api-reference.md
> +  - The [compatibility date](/workers/platform/compatibility-dates/) must be set to `2022-08-04` or later in your `wrangler.toml` file. If not, then the `r2_list_honor_include` compatibility flag mus
```suggestion
  - The [compatibility date](/workers/platform/compatibility-dates/) must be set to `2022-08-04` or later in your `wrangler.toml` file. If not, then the `r2_list_honor_include` compatibility flag must be set. Otherwise, it is treated as `include: ['httpMetadata', 'customMetadata']` regardless of the `include` option provided.
```

2022-09-22 16:34 UTC, deadlypants1973 commented on content/workers/_partials/_platform-compatibility-dates/r2-list-honor-includes.md
> +as `include: ["httpMetadata", "customMetadata"]`.
```suggestion
With the `r2_list_honor_include` flag set, the `include` argument to R2 `list` options is honored. With an older compatability date and without this flag, the `include` argument behaves implicitly as `include: ["httpMetadata", "customMetadata"]`.
```

2022-09-22 16:38 UTC, merged