[Pages]: Update Sveltekit adapter
cloudflare/cloudflare-docs pull request #5081
Opened 2022-07-08 15:00 UTC by Ekwuno

This PR updates the recommended adapter for deploying SvelteKit applications on Pages

2022-07-09 21:04 UTC, isaac-mcfadyen commented
Sooo... mostly!

The one caveat that I've run into with `adapter-auto` is that it *doesn't build locally*.

When building locally, `adapter-auto` has no way to know what platform you're going to deploy to, so the build fails with an error.

The main concerns I can see with that, and that we might want to mention in the docs, are:
- direct uploads won't work if people can't build locally to upload
- `wrangler pages dev` won't work for the same reason (you *can* run it on the SvelteKit server but this is actually worse than building and running on built files because SvelteKit endpoints don't get KV/DO/other bindings since it's a Vite dev server)

That's why, when I first create a SvelteKit site, I update my adapter as the first thing that I do (since most of my sites are Direct Uploads these days).

Final, **important** thing. SvelteKit dropped Node 14 support in May so we should be recommending 16 (LTS) or higher.

2022-07-09 22:24 UTC, isaac-mcfadyen commented
One thing that I thought of (and one thing @WalshyDev discovered):
- SvelteKit detects Pages via the CF_PAGES environment variable. So, if we want people to be able to build locally using `adapter-auto`, we should tell them to change their build command from `vite build` to `CF_PAGES=1 vite build`
- another consideration here is Functions. We should point out that with `adapter-auto` it *will* use Functions and so they will be capped at 100k while Functions are in beta (perhaps we want to leave the old guide around with a warning that it's for static building only?)

2022-07-09 23:08 UTC, Ekwuno commented
@isaac-mcfadyen thanks for highlighting these points. I've been thinking about it and there seems to be three users Journeys for SvelteKit users with the three adapters. 

I think maybe it'll be beneficial if we pointed out three adapters and there local dev and production benefits. In the mean I'll update the PR to remove Node 14 support. 

I agree, it seems like we should leave the static adapter and add the local dev and production advantages.

2022-07-10 00:54 UTC, Nuttapon43 reviewed
Duplicate of #

2022-07-10 20:19 UTC, isaac-mcfadyen commented
For the `adapter-static`, the default output directory is `build`, not `adapter-cloudflare`. Also it has a few more setup steps [here](https://github.com/sveltejs/kit/tree/master/packages/adapter-static) (I think they changed them after the last guide was created) 🙂

2022-07-11 19:04 UTC, isaac-mcfadyen commented
Just a heads-up: I noticed that there doesn't seem to be diff colors/formatting on the code previews 🙂

2022-07-11 19:51 UTC, Ekwuno commented
> Just a heads-up: I noticed that there doesn't seem to be diff colors/formatting on the code previews 🙂

Yea, our code highlighter doesn't pick that up. I will look into it.

2022-07-12 16:38 UTC, deadlypants1973 requested changes

2022-07-12 16:38 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-svelte-site.md
> +Currently, SvekteKit has three available adapters that you can use to deploy a SvelteKit project to Cloudflare Pages.
```suggestion
Currently, SvekteKit has three available adapters that you can use to deploy a SvelteKit project to Cloudflare Pages.
```

2022-07-12 16:38 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-svelte-site.md
> +**Important:** SvelteKit requires Node.js v16.x or later to build successfully. You must expand the **Environment Variables (advanced)** section and add a `NODE_VERSION` variable with a value of `16`
```suggestion
**Important:** SvelteKit requires Node.js v16.x or later to build successfully. Log in to the [Cloudflare dashboard](https://dash.cloudflare.com/login) > **Pages** > **Settings** > **Environment Variables** section and add a `NODE_VERSION` variable with a value of `16` or greater.
```
Is this only updatable

2022-07-12 16:38 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-svelte-site.md
> +The SvelteKit project's default configuration uses [`@sveltejs/adapter-auto`](https://www.npmjs.com/package/@sveltejs/adapter-auto), which automatically chooses the adapter for your current environme
```suggestion
The SvelteKit project's default configuration uses [`@sveltejs/adapter-auto`](https://www.npmjs.com/package/@sveltejs/adapter-auto), which automatically chooses the adapter for your current environment. While you can use this default adapter when deploying to Cloudflare Pages by setting your **Build directory** to `.svelte-kit/cloudflare`, local development has a few disadvantages.
```

2022-07-12 16:38 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-svelte-site.md
> +When building locally, [`@sveltejs/adapter-auto`](https://www.npmjs.com/package/@sveltejs/adapter-auto) has no way to know what platform you're going to deploy to, so the build fails. Also, since the
```suggestion
When building locally, [`@sveltejs/adapter-auto`](https://www.npmjs.com/package/@sveltejs/adapter-auto) has no way to know what platform you are going to deploy to, so the build will fail. Since the environment variables are not set, you cannot use Cloudflare Pages features, like Direct Uploads or use Functions, locally. 
```

2022-07-12 20:54 UTC, WalshyDev commented on content/pages/framework-guides/deploy-a-svelte-site.md
> +The `GET` request handler here will correspond to an `OnRequestGet` in Pages Functions.
```suggestion
The `GET` request handler here will correspond to an `onRequestGet` in Pages Functions. 
```

2022-07-12 20:54 UTC, WalshyDev commented on content/pages/framework-guides/deploy-a-svelte-site.md
>  ## Learn more
```suggestion

## Learn more
```

2022-07-14 15:51 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-svelte-site.md
> +While Functions are in beta, they don't have error logs yet. So your alternative right now is to use a reporting platform like Sentry.
```suggestion
Logs are not available as Pages Functions is currently in beta. A third-party alternative, such as Sentry, can be used for logging with Pages Functions.
```

2022-07-14 15:51 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-svelte-site.md
> +[`@sveltejs/adapter-cloudflare`](https://www.npmjs.com/package/@sveltejs/adapter-cloudflare) supports all SvelteKit features and builds for Cloudflare Pages. The Cloudflare adapter is recommended bec
```suggestion
[`@sveltejs/adapter-cloudflare`](https://www.npmjs.com/package/@sveltejs/adapter-cloudflare) supports all SvelteKit features and builds for Cloudflare Pages. The Cloudflare adapter is recommended because it supports expected local development and production behaviours. 
```

2022-07-14 15:51 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-svelte-site.md
> +
```suggestion
1. Install the Cloudflare Adapter by running `npm i --save-dev @sveltejs/adapter-cloudflare` in your terminal. 
```

2022-07-14 15:51 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-svelte-site.md
> +2. Include the adapter in the `svelte.config.js`
```suggestion
2. Include the adapter in `svelte.config.js`:
```

2022-07-14 15:51 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-svelte-site.md
> +You can add this adapter to your application in the following steps:
```suggestion
To add the SvelteKit Cloudflare adapter to your application: 
```

2022-07-14 15:51 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-svelte-site.md
> +3. Include support for environment variables; the `env` object containing KV namespaces etc, is passed to SvelteKit via the platform property along with context and caches, meaning you can access it
```suggestion
3. Include support for environment variables. The `env` object, containing KV namespaces and other storage objects, is passed to SvelteKit via the platform property along with context and caches, meaning you can access it in hooks and endpoints. For example:
```

2022-07-14 15:51 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-svelte-site.md
> +In your component access bindings like KV and durable objects namespace with `env` :
Is this supposed to be instructions? What is this sentence asking the developer to do?

2022-07-14 15:51 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-svelte-site.md
> +When deploying with the with [`@sveltejs/adapter-cloudflare`](https://www.npmjs.com/package/@sveltejs/adapter-cloudflare) or [`@sveltejs/adapter-auto`](https://www.npmjs.com/package/@sveltejs/adapter
```suggestion
When deploying with [`@sveltejs/adapter-cloudflare`](https://www.npmjs.com/package/@sveltejs/adapter-cloudflare) or [`@sveltejs/adapter-auto`](https://www.npmjs.com/package/@sveltejs/adapter-auto), select the new GitHub repository that you created and, in **Set up builds and deployments** of your Pages project setup, provide the following information:
```

2022-07-14 15:51 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-svelte-site.md
> +| Environment Variables | `NODE_VERSION: 16 or 14`|
Is this how you actually write the environment variable?

2022-07-14 15:51 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-svelte-site.md
> +The static adapter only produces client-side static assets; compatible with Cloudflare Pages. To use this adapter first, install the [`@sveltejs/adapter-static`](https://www.npmjs.com/package/@svelte
```suggestion
The static adapter only produces client-side static assets and is compatible with Cloudflare Pages. To use this adapter, install the [`@sveltejs/adapter-static`](https://www.npmjs.com/package/@sveltejs/adapter-static) package:
```

2022-07-14 15:51 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-svelte-site.md
> +{{<Aside>}}
Why is one aside deleted but the closing aside is still there?

2022-07-14 15:51 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-svelte-site.md
> +In SvelteKit, functions are written as endpoints and Functions contained in the `/functions` directory at the project's root will not be included in the deployment, which compiles to a single _worker
```suggestion
In SvelteKit, functions are written as endpoints. Functions contained in the `/functions` directory at the project's root will not be included in the deployment, which compiles to a single `_worker.js` file. 
```

2022-07-14 15:51 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-svelte-site.md
> +In other to have the correct request handlers in Pages functions. When writing your endpoints in SveleteKit, attach the corresponding `onRequest` handler to your SvelteKit endpoint. For example:
```suggestion
When writing your endpoints in SveleteKit, attach the corresponding `onRequest` handler to your SvelteKit endpoint. For example:
```
The first sentence is not a full sentence?

2022-07-14 15:51 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-svelte-site.md
>  ## Learn more
```suggestion
## Related resources
```

2022-07-14 16:04 UTC, Ekwuno commented on content/pages/framework-guides/deploy-a-svelte-site.md
> +| Environment Variables | `NODE_VERSION: 16 or 14`|
```suggestion
| Environment Variables | `NODE_VERSION: 16 `|
```

2022-07-14 20:17 UTC, Ekwuno commented on content/pages/framework-guides/deploy-a-svelte-site.md
> +{{<Aside>}}
I am not sure what you mean. I can't see the aside in the preview.

2022-07-15 15:04 UTC, deadlypants1973 approved these changes

2022-07-15 15:04 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-svelte-site.md
> +
```suggestion
```

2022-07-15 15:04 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-svelte-site.md
> +When building locally, [`@sveltejs/adapter-auto`](https://www.npmjs.com/package/@sveltejs/adapter-auto) has no way to know what platform you are going to deploy to, so the build will fail. Since the
```suggestion
When building locally, [`@sveltejs/adapter-auto`](https://www.npmjs.com/package/@sveltejs/adapter-auto) has no way to know what platform you are going to deploy to. This will cause the build to fail. Since the environment variables are not set, you cannot use Cloudflare Pages features, like Direct Uploads or Functions, locally. 
```

2022-07-15 15:04 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-svelte-site.md
> +However, in production, to deploy your Sveltekit application on Pages, First update the **Build directory** to `.svelte-kit/cloudflare`; this lets the [`@sveltejs/adapter-auto`](https://www.npmjs.com
```suggestion
To deploy your Sveltekit application in production, update the **Build directory** to `.svelte-kit/cloudflare`. This lets the [`@sveltejs/adapter-auto` package](https://www.npmjs.com/package/@sveltejs/adapter-auto) know you are deploying to a Cloudflare Pages environment.
```

2022-07-15 15:14 UTC, isaac-mcfadyen commented on content/pages/framework-guides/deploy-a-svelte-site.md
> +4. Access the added KV or Durable objects namespace in your component with `env` :
```suggestion
4. Access the added KV or Durable objects namespace in your endpoint with `env` : 
```
SvelteKit components are different than endpoints so this should be clarified a bit.

2022-07-15 15:14 UTC, isaac-mcfadyen commented on content/pages/framework-guides/deploy-a-svelte-site.md
> +**Important:** SvelteKit requires Node.js v16.x or later to build successfully. Log in to the [Cloudflare dashboard](https://dash.cloudflare.com/login) > **Pages** > **Settings** > **Environment Vari
```suggestion
**Important:** SvelteKit requires Node.js v16.9 or later to build successfully. Log in to the [Cloudflare dashboard](https://dash.cloudflare.com/login) > **Pages** > **Settings** > **Environment Variables** section and add a `NODE_VERSION` variable with a value of `16` or greater to use the latest 16 LTS version of Node.js.
```

Strangely they now require v16.9 or greater because of a bug with earlier versions (will happen once `16` is specified because it will use the latest `16` version).

2022-07-15 15:14 UTC, isaac-mcfadyen commented on content/pages/framework-guides/deploy-a-svelte-site.md
> +The static adapter only produces client-side static assets and is compatible with Cloudflare Pages. To use this adapter, install the [`@sveltejs/adapter-static`](https://www.npmjs.com/package/@svelte
```suggestion
The static adapter only produces client-side static assets (no server-side rendering) and is compatible with Cloudflare Pages. To use this adapter, install the [`@sveltejs/adapter-static`](https://www.npmjs.com/package/@sveltejs/adapter-static) package:
```

2022-07-15 15:14 UTC, isaac-mcfadyen commented on content/pages/framework-guides/deploy-a-svelte-site.md
> +When writing your endpoints in SveleteKit, attach the corresponding `onRequest` handler to your SvelteKit endpoint. For example:
```suggestion
When writing your endpoints in SvelteKit, attach the corresponding `onRequest` handler to your SvelteKit endpoint. For example:
```
Small typo.

2022-07-15 15:14 UTC, isaac-mcfadyen commented on content/pages/framework-guides/deploy-a-svelte-site.md
> +
```suggestion
{{<Aside type= "note" header="SvelteKit Endpoints">}}
For more information about SvelteKit Endpoints, see the [SvelteKit docs](https://kit.svelte.dev/docs/routing#endpoints).
{{</Aside>}}
```

2022-07-15 15:18 UTC, isaac-mcfadyen commented on content/pages/framework-guides/deploy-a-svelte-site.md
> +**Important:** SvelteKit requires Node.js v16.x or later to build successfully. Log in to the [Cloudflare dashboard](https://dash.cloudflare.com/login) > **Pages** > **Settings** > **Environment Vari
On second thought this info isn't really *required* per-say. If the user does `16` it will work, it just won't if they do `16.8` or something strange like that.

2022-07-15 15:34 UTC, Ekwuno commented on content/pages/framework-guides/deploy-a-svelte-site.md
> +**Important:** SvelteKit requires Node.js v16.x or later to build successfully. Log in to the [Cloudflare dashboard](https://dash.cloudflare.com/login) > **Pages** > **Settings** > **Environment Vari
I'll just leave it as 16. So it always defaults to the latest.

2022-07-15 15:37 UTC, merged