[Pages]: Update Mailchannel plugin doc
cloudflare/cloudflare-docs pull request #5096
Opened 2022-07-10 18:18 UTC by Ekwuno

This PR adds steps to generating and using DomainKeys Identified Mail (DKIM) with our Mailchannel plugin.

2022-07-10 18:57 UTC, fariborz4 commented
Ok

2022-07-11 10:07 UTC, GregBrimble requested changes

2022-07-11 10:07 UTC, GregBrimble commented on content/pages/platform/functions/plugins/mailchannels.md
> +The MailChannels API also allows you add a DomainKeys Identified Mail (DKIM) which is an email authentication standard that helps you to sign email messages from your domain with a digital signature
I think this DKIM should follow at the end of the page, rather than be right up at the top. It should also be clear that this is an optional thing.

Probably also worth linking to our [Cloudflare's learning page on DKIM](https://www.cloudflare.com/en-ca/learning/dns/dns-records/dns-dkim-record/) and the [relevant MailChannels documentation](https://mailchannels.zendesk.com/hc/en-us/articles/7122849237389-Adding-a-DKIM-Signature).

2022-07-11 10:07 UTC, GregBrimble commented on content/pages/platform/functions/plugins/mailchannels.md
> +To add a DKIM signature to a message, add the following fields to the personalization object for the message:
```suggestion
To add a DKIM signature to a message, add the following fields to the `personalization` object for the message:
```

2022-07-11 10:07 UTC, GregBrimble commented on content/pages/platform/functions/plugins/mailchannels.md
> +**dkim_private_key**: The base-64 encoded private key.
```suggestion
**`dkim_domain`**: This is the domain (`d=`) field for the DKIM signature. To pass DMARC, this should be aligned with the domain in the From header address.

**`dkim_selector`**: This is the selector (`s=`) field for the DKIM signature. It specifies where to find the associated public key in the DNS - see the DKIM specification for more details.

**`dkim_private_key`**: The base-64 encoded private key.
```

2022-07-11 10:07 UTC, GregBrimble commented on content/pages/platform/functions/plugins/mailchannels.md
> +You can generate your DKIM credentials using any DKIM generator of your choice. To add your generated credentials to your project on the Cloudflare dashboard, do the following:
```suggestion
You can generate your DKIM credentials using any DKIM generator of your choice. To add your generated credentials to your zone on the Cloudflare dashboard, do the following:
```

2022-07-11 10:07 UTC, GregBrimble commented on content/pages/platform/functions/plugins/mailchannels.md
> +You can generate your DKIM credentials using any DKIM generator of your choice. To add your generated credentials to your project on the Cloudflare dashboard, do the following:
It would be nice to have the OpenSSL commands here to copy-and-paste.

2022-07-11 10:07 UTC, GregBrimble commented on content/pages/platform/functions/plugins/mailchannels.md
> +5. Enter the Public key into your DNS server record as a text(TXT) entry. The name of your DNS record must follow this convention `[selector key]._domainkey.<Your domain>`.
I think a screenshot here would be useful. The way you enter this into the Cloudflare DNS table is not super intuitive.

You need to omit the zone from the "name" field in the record (as it is automatically added).

This is a record on my zone (don't use this picture since it's a bit different), but you get the idea. Something like this.

<img width="1008" alt="image" src="https://user-images.githubusercontent.com/8484333/178240653-f9a58641-64c4-4cbd-a9fa-3bed4b16aff1.png">

2022-07-11 10:07 UTC, GregBrimble commented on content/pages/platform/functions/plugins/mailchannels.md
> +5. Enter the Public key into your DNS server record as a text(TXT) entry. The name of your DNS record must follow this convention `[selector key]._domainkey.<Your domain>`.
```suggestion
5. Enter the DKIM record into your DNS server record as a text (TXT) entry. The name of your DNS record must follow this convention `[selector key]._domainkey.<Your domain>`. 
```

2022-07-11 10:07 UTC, GregBrimble commented on content/pages/platform/functions/plugins/mailchannels.md
> +6. Add the value of your Public key in the content field.
```suggestion
6. Add the value of your DKIM record in the content field.
```

2022-07-11 10:07 UTC, GregBrimble commented on content/pages/platform/functions/plugins/mailchannels.md
> +7. Enter the Private key into your email server.
This doesn't happen. There is no email server to add it to. Instead, you add the private key to your Pages Function so that you can send it to MailChannels.

2022-07-11 10:22 UTC, Ekwuno commented on content/pages/platform/functions/plugins/mailchannels.md
> +You can generate your DKIM credentials using any DKIM generator of your choice. To add your generated credentials to your project on the Cloudflare dashboard, do the following:
Yea I found a helpful repo, I will add that in.

2022-07-11 10:24 UTC, Ekwuno commented on content/pages/platform/functions/plugins/mailchannels.md
> +7. Enter the Private key into your email server.
Removed!

2022-07-11 15:43 UTC, Ekwuno commented on content/pages/platform/functions/plugins/mailchannels.md
> +5. Enter the Public key into your DNS server record as a text(TXT) entry. The name of your DNS record must follow this convention `[selector key]._domainkey.<Your domain>`.
Done!

2022-07-12 16:14 UTC, deadlypants1973 commented on content/pages/platform/functions/plugins/mailchannels.md
> +
```suggestion
```

2022-07-13 16:46 UTC, deadlypants1973 requested changes

2022-07-13 16:46 UTC, deadlypants1973 commented on content/pages/platform/functions/plugins/mailchannels.md
> +### Addition information
```suggestion
### Related resources
```

2022-07-13 16:46 UTC, deadlypants1973 commented on content/pages/platform/functions/plugins/mailchannels.md
> +- [Mailchannel article on adding DKIM with Workers](https://mailchannels.zendesk.com/hc/en-us/articles/7122849237389-Adding-a-DKIM-Signature)
```suggestion
* [Adding a DKIM Signature](https://mailchannels.zendesk.com/hc/en-us/articles/7122849237389-Adding-a-DKIM-Signature)
```

2022-07-13 16:46 UTC, deadlypants1973 commented on content/pages/platform/functions/plugins/mailchannels.md
> +- [Cloudflare + MailChannels Email Sending with DKIM](https://github.com/maggie-j-liu/mail)
```suggestion
* [How to create a DKIM record with OpenSSL](https://www.mailhardener.com/kb/how-to-create-a-dkim-record-with-openssl)
* [Cloudflare + MailChannels Email Sending with DKIM](https://github.com/maggie-j-liu/mail)
```

2022-07-13 16:46 UTC, deadlypants1973 commented on content/pages/platform/functions/plugins/mailchannels.md
> +{{</Aside>}}
```suggestion
{{<Aside type= "note" header="Selector value">}}
You can choose any value as the selector, as long as it is permitted as a DNS hostname (that is, all lowercase letters, numbers and hyphens). It is recommended to use the name of the service and a date indicator. This makes it easy to remember where this key is used, for example, `cloudflare2022`.
{{</Aside>}}
```

2022-07-13 16:46 UTC, deadlypants1973 commented on content/pages/platform/functions/plugins/mailchannels.md
> +
Describe what the user needs to do with this code block.

2022-07-14 13:30 UTC, GregBrimble requested changes

2022-07-14 13:30 UTC, GregBrimble commented on content/pages/platform/functions/plugins/mailchannels.md
> +When using the MailChannel plugin adding DKIM is optional.
```suggestion
Setting up DKIM for use in your MailChannels Pages Plugin is optional, but will improve the deliverability of your emails. Clients will be less likely to mark your emails as spam or junk because, when configured correctly, DKIM allows clients to verify that you own the domain you're sending from.
```

2022-07-14 13:30 UTC, GregBrimble commented on content/pages/platform/functions/plugins/mailchannels.md
> +**`dkim_domain`**: This is the domain (`d=`) field for the DKIM signature. To pass DMARC, this should be aligned with the domain in the From header address.
```suggestion
**`dkim_domain`**: This is the domain you're sending the email from. For example, if you're sending an email from `support@example.com`, set this to `example.com`.
```

2022-07-14 13:30 UTC, GregBrimble commented on content/pages/platform/functions/plugins/mailchannels.md
> +**`dkim_selector`**: This is the selector (`s=`) field for the DKIM signature. It specifies where to find the associated public key in the DNS - see the DKIM specification for more details.
```suggestion
**`dkim_selector`**: This specifies where to find the associated public key in your DNS records. For example, if you make the DKIM record available at `mailchannels._domainkey.example.com`, set this to `mailchannels`.
```

2022-07-14 13:30 UTC, GregBrimble commented on content/pages/platform/functions/plugins/mailchannels.md
> +1. Generate your private key and DNS credentials by running the command below in your terminal:
```suggestion
1. Generate your private key and DNS record by running the command below in your terminal: 
```

2022-07-14 13:30 UTC, GregBrimble commented on content/pages/platform/functions/plugins/mailchannels.md
> +`openssl rsa -outform der | openssl base 64 -A`, which converts the key from PEM format to DER format, then base64 encodes it (this essentially removes the header from the PEM formatted key). The out
This still isn't quite right. We had to transform the private key further, in order to get it working in our testing yesterday. What was that repo someone had that we were referencing?

2022-07-14 13:30 UTC, GregBrimble commented on content/pages/platform/functions/plugins/mailchannels.md
> +2. Copy the private key from `private_key.pem`file and add it to your Function
```suggestion
2. Copy the contents of the `private_key.pem` file and add it as an environment variable to your Pages project name `DKIM_PRIVATE_KEY` or similar.
```

2022-07-14 13:30 UTC, GregBrimble commented on content/pages/platform/functions/plugins/mailchannels.md
> +1. Select the Zone to add DKIM records.
I'd just combine this together so the list continues onto steps 3 and 4. I'd also not mention `dkim_record.txt` until we copy its value later on, otherwise you're just repeating steps.

2022-07-14 13:30 UTC, GregBrimble commented on content/pages/platform/functions/plugins/mailchannels.md
> +4. Enter your domain name.
Where?

2022-07-14 13:30 UTC, GregBrimble commented on content/pages/platform/functions/plugins/mailchannels.md
> +5. Enter the DKIM record into your DNS server as a text (TXT) entry. The name of your DNS record must follow this convention `[selector key]._domainkey.<Your domain>`.
```suggestion
5. Enter the DKIM record into your DNS server as a text (`TXT`) entry. The name of your DNS record must follow this convention `<selector key>._domainkey`. For example, `mailchannels._domainkey`.
```

2022-07-14 13:30 UTC, GregBrimble commented on content/pages/platform/functions/plugins/mailchannels.md
> +You can choose any value as the selector, as long as it is permitted as a DNS hostname (that is, all lowercase letters, numbers and hyphens). It is recommended to use the name of the service and a da
```suggestion
You can choose any value as the selector, as long as it is permitted as a DNS hostname (that is, all lowercase letters, numbers and hyphens).
```

2022-07-14 13:30 UTC, GregBrimble commented on content/pages/platform/functions/plugins/mailchannels.md
> +7. Add the private key to your Pages Function.
We've already done this in step 2?

2022-07-14 13:30 UTC, GregBrimble commented on content/pages/platform/functions/plugins/mailchannels.md
> +      to: [{ name: "ACME Member Support", email: "members@example.com" }],
```suggestion
      to: [{ name: "Some User", email: "user@cloudflare.com" }],
```

2022-07-14 13:30 UTC, GregBrimble commented on content/pages/platform/functions/plugins/mailchannels.md
> +      "dkim_domain": "example.com", // The value has to be the Zone you added DKIM records to
```suggestion
      "dkim_domain": "example.com", // The value has to be the domain you added DKIM records to and where you're sending your email from
```

2022-07-14 13:30 UTC, GregBrimble commented on content/pages/platform/functions/plugins/mailchannels.md
> +      "dkim_selector": "mcdkim",
```suggestion
      "dkim_selector": "mailchannels",
```

2022-07-14 13:30 UTC, GregBrimble commented on content/pages/platform/functions/plugins/mailchannels.md
> +      "dkim_private_key": "<base64 encoded privatekey>"
Let's update this example to use `env.DKIM_PRIVATE_KEY`.

2022-07-14 13:30 UTC, GregBrimble commented on content/pages/platform/functions/plugins/mailchannels.md
> +The required fields are `dkim_domain`,`dkim_selector`, `dkim_private_key`. The value of these fields must match the genrated values from your DNS records.
```suggestion
The required fields are `dkim_domain`,`dkim_selector`, `dkim_private_key`. The value of these fields must match the values we used earlier.
```

2022-07-14 13:30 UTC, GregBrimble commented on content/pages/platform/functions/plugins/mailchannels.md
> +When adding your `dkim_private_key` value, ensure that you remove any whitespaces between the value content as they might result in errors.
Again, we can do this automatically. Let's add it to the command so the user doesn't need to worry about it.

2022-07-14 13:30 UTC, GregBrimble commented on content/pages/platform/functions/plugins/mailchannels.md
> +The following code block shows an example of using DKIM credentials with the Mailchannel plugin.
```suggestion
The following code block shows an example of using DKIM with the MailChannels Pages Plugin.
```

2022-07-14 15:41 UTC, Ekwuno commented on content/pages/platform/functions/plugins/mailchannels.md
> +`openssl rsa -outform der | openssl base 64 -A`, which converts the key from PEM format to DER format, then base64 encodes it (this essentially removes the header from the PEM formatted key). The out
I've updated and tested the commands. The repo is linked in the last section under related resources

2022-07-15 12:08 UTC, GregBrimble commented on content/pages/platform/functions/plugins/mailchannels.md
> +4. Enter your domain name in the name field.
```suggestion
```

2022-07-15 12:12 UTC, GregBrimble commented on content/pages/platform/functions/plugins/mailchannels.md
> +$ openssl genrsa 2048 | tee private_key.pem | openssl rsa -outform der | openssl base64 -A
```suggestion
$ openssl genrsa 2048 | openssl rsa -outform der | openssl base64 -A > private_key.txt
```

2022-07-15 12:14 UTC, GregBrimble commented on content/pages/platform/functions/plugins/mailchannels.md
> +`openssl rsa -outform der | openssl base 64 -A`, which converts the key from PEM format to DER format, then base64 encodes it (this essentially removes the header from the PEM formatted key).
```suggestion
`openssl genrsa 2048` generates a 2048-bit RSA key. The output is passed to

`openssl rsa -outform der | openssl base 64 -A`, which converts the key from PEM format to DER format, then base64 encodes it. Finally, we take this output into

`> private_key.txt` which saves the contents to `private_key.txt`.
```

2022-07-15 12:17 UTC, GregBrimble commented on content/pages/platform/functions/plugins/mailchannels.md
> +2. Copy the contents of the `private_key.pem` file and add that as an environment variable to your Pages project by logging into the [Cloudflare dashboard](https://dash.cloudflare.com/login) > **Page
```suggestion
2. Copy the contents of the `private_key.txt` file and add that as an environment variable to your Pages project by logging into the [Cloudflare dashboard](https://dash.cloudflare.com/login) > **Pages** > select project > **Settings** > **Environment Variables** section > click **Add variables**. Set the variable name as `DKIM_PRIVATE_KEY` and the value as the contents of `private_key.txt` file.
```

2022-07-15 12:18 UTC, GregBrimble commented on content/pages/platform/functions/plugins/mailchannels.md
> +5. Enter the DKIM record into your DNS server as a text (`TXT`) entry. The name of your DNS record must follow this convention `<selector key>._domainkey`. For example, `mailchannels._domainkey`.
```suggestion
4. Enter the DKIM record into your DNS server as a text (`TXT`) entry. The name of your DNS record must follow this convention `<selector key>._domainkey`. For example, `mailchannels._domainkey`.
```

2022-07-15 12:18 UTC, GregBrimble commented on content/pages/platform/functions/plugins/mailchannels.md
> +6. Add the content of your `dkim_record.txt` file in the content field.
```suggestion
5. Add the content of your `dkim_record.txt` file in the content field.
```

2022-07-15 12:19 UTC, GregBrimble commented on content/pages/platform/functions/plugins/mailchannels.md
> +The required fields are `dkim_domain`,`dkim_selector`, `dkim_private_key`. The value of these fields must match the values you generated earlier.
```suggestion
The required fields are `dkim_domain`, `dkim_selector`, `dkim_private_key`. The value of these fields must match the values you generated earlier.
```

2022-07-15 12:20 UTC, GregBrimble commented on content/pages/platform/functions/plugins/mailchannels.md
> +});
```suggestion
export const onRequest: PagesFunction = (context) => mailChannelsPlugin({
  personalizations: [
    {
      to: [{ name: "Some User", email: "user@cloudflare.com" }],
      "dkim_domain": "example.com", // The value has to be the domain you added DKIM records to and where you're sending your email from
      "dkim_selector": "mailchannels",
      "dkim_private_key": context.env.DKIM_PRIVATE_KEY
    },
  ],
  from: {
    name: "ACME Support",
    email: "support@example.com",
  },
  respondWith: () => {
    return new Response(
      `Thank you for submitting your enquiry. A member of the team will be in touch shortly.`
    );
  },
})(context);
```

2022-07-15 12:21 UTC, GregBrimble approved these changes
With these final suggestions, I'm happy with the PR now. Thanks!

2022-07-15 15:13 UTC, deadlypants1973 commented on content/pages/platform/functions/plugins/mailchannels.md
> +## DKIM support for Mailchannel API
```suggestion
## DKIM support for Mailchannels API
```

2022-07-15 15:13 UTC, deadlypants1973 commented on content/pages/platform/functions/plugins/mailchannels.md
> +Setting up DKIM for use in your MailChannels Pages Plugin is optional, but will improve the deliverability of your emails. Clients will be less likely to mark your emails as spam or junk because, whe
```suggestion
Setting up DKIM for use in your MailChannels Pages Plugin is optional, but will improve the deliverability of your emails. Clients will be less likely to mark your emails as spam or junk, because, when configured correctly, DKIM allows clients to verify that you own the domain you are sending from.
```

2022-07-15 15:13 UTC, deadlypants1973 commented on content/pages/platform/functions/plugins/mailchannels.md
> +The MailChannels API also allows you add a DomainKeys Identified Mail (DKIM) which is an email authentication standard that helps you to sign email messages from your domain with a digital signature
add a DKIM to what?

2022-07-15 15:13 UTC, deadlypants1973 commented on content/pages/platform/functions/plugins/mailchannels.md
> +**`dkim_domain`**: This is the domain you're sending the email from. For example, if you're sending an email from `support@example.com`, set this to `example.com`.
```suggestion
**`dkim_domain`**: The domain you are sending the email from. For example, if you are sending an email from `support@example.com`, set this to `example.com`.
```

2022-07-15 15:13 UTC, deadlypants1973 commented on content/pages/platform/functions/plugins/mailchannels.md
> +**`dkim_selector`**: This specifies where to find the associated public key in your DNS records. For example, if you make the DKIM record available at `mailchannels._domainkey.example.com`, set this
```suggestion
**`dkim_selector`**: Specifies where to find the associated public key in your DNS records. For example, if you make the DKIM record available at `mailchannels._domainkey.example.com`, set this to `mailchannels`.
```

2022-07-15 15:13 UTC, deadlypants1973 commented on content/pages/platform/functions/plugins/mailchannels.md
> +`> private_key.txt` which saves the contents to `private_key.txt`.
```suggestion
`openssl genrsa 2048` generates a 2048-bit RSA key. The output is passed to `tee private_key.pem`, which writes the key to the `private_key.pem` file, and passes the key to `openssl rsa -outform der | openssl base 64 -A`, which converts the key from PEM format to DER format, then base64 encodes it. Take this output into `> private_key.txt` which saves the contents to `private_key.txt`.
```

2022-07-15 15:13 UTC, deadlypants1973 commented on content/pages/platform/functions/plugins/mailchannels.md
> +{{<Aside type="note" header="Command breakdown">}}
```suggestion
```

2022-07-15 15:13 UTC, deadlypants1973 commented on content/pages/platform/functions/plugins/mailchannels.md
> +
```suggestion
```

2022-07-15 15:13 UTC, deadlypants1973 commented on content/pages/platform/functions/plugins/mailchannels.md
> +2. Copy the contents of the `private_key.txt` file and add that as an environment variable to your Pages project by logging into the [Cloudflare dashboard](https://dash.cloudflare.com/login) > **Page
```suggestion
2. Copy the contents of the `private_key.txt` file and add that as an environment variable to your Pages project by logging into the [Cloudflare dashboard](https://dash.cloudflare.com/login) > **Pages** > your Pages project > **Settings** > **Environment Variables* > **Add variables**. Set the variable name as `DKIM_PRIVATE_KEY` and the value as the contents of `private_key.txt` file.
```

2022-07-15 15:13 UTC, deadlypants1973 commented on content/pages/platform/functions/plugins/mailchannels.md
> +
```suggestion
```

2022-07-15 15:13 UTC, deadlypants1973 commented on content/pages/platform/functions/plugins/mailchannels.md
> +Next, look in your generated `dkim_record.txt` file for your DKIM credentials, and add them to your Zone on the Cloudflare dashboard. Follow the steps below:
```suggestion
Next, look in your generated `dkim_record.txt` file for your DKIM credentials, and add them to your website in the Cloudflare dashboard. Follow the steps below:
```

2022-07-15 15:13 UTC, deadlypants1973 commented on content/pages/platform/functions/plugins/mailchannels.md
> +1. Select the Zone to add DKIM records.
```suggestion
1. In Account Home, select the website you would like to add a DKIM record. 
```

2022-07-15 15:13 UTC, deadlypants1973 commented on content/pages/platform/functions/plugins/mailchannels.md
> +3. In the drop-down menu, select **TXT** as the type of record.
```suggestion
3. In the dropdown menu, select **TXT** as the type of record.  
```

2022-07-15 15:13 UTC, deadlypants1973 commented on content/pages/platform/functions/plugins/mailchannels.md
> +![Follow the instructions above to add DKIM credentials to your Zone DNS records](/pages/platform/functions/plugins/mailchannel_DKIM_DNS_setup.png)
```suggestion
![Follow the instructions above to add DKIM credentials to your DNS records](/pages/platform/functions/plugins/mailchannel_DKIM_DNS_setup.png)
```

2022-07-15 15:13 UTC, deadlypants1973 commented on content/pages/platform/functions/plugins/mailchannels.md
> +
```suggestion
```

2022-07-15 15:20 UTC, Ekwuno commented on content/pages/platform/functions/plugins/mailchannels.md
> +The MailChannels API also allows you add a DomainKeys Identified Mail (DKIM) which is an email authentication standard that helps you to sign email messages from your domain with a digital signature
```suggestion
The MailChannels API also allows you add a DomainKeys Identified Mail (DKIM) to your DNS records. DKIM is an email authentication standard that helps you to sign email messages from your domain with a digital signature using public-key cryptography. Refer to [Cloudflare DNS DKIM guide](https://www.cloudflare.com/en-ca/learning/dns/dns-records/dns-dkim-record/) to learn more.
```

2022-07-15 15:29 UTC, deadlypants1973 commented on content/pages/platform/functions/plugins/mailchannels.md
> +The MailChannels API also allows you add a DomainKeys Identified Mail (DKIM) to your DNS records. DKIM is an email authentication standard that helps you to sign email messages from your domain with
```suggestion
The MailChannels API also allows you add a DomainKeys Identified Mail (DKIM) credential to your DNS records. DKIM is an email authentication standard that helps you to sign email messages from your domain with a digital signature using public-key cryptography. Refer to [Cloudflare DNS DKIM guide](https://www.cloudflare.com/en-ca/learning/dns/dns-records/dns-dkim-record/) to learn more.
```
```suggestion
The MailChannels API also allows you add a DomainKeys Identified Mail (DKIM) to your DNS records. DKIM is an email authentication standard that helps you to sign email messages from your domain with a digital signature using public-key cryptography. Refer to [Cloudflare DNS DKIM guide](https://www.cloudflare.com/en-ca/learning/dns/dns-records/dns-dkim-record/) to learn more.
```

2022-07-15 15:30 UTC, deadlypants1973 approved these changes

2022-07-15 15:36 UTC, merged