[Access] new policies section
cloudflare/cloudflare-docs pull request #510
Opened 2020-12-16 20:23 UTC by abracchi-tw

- Took out most information from `Getting started > Policy management`
- Created brand new `Policies and rules` section to give more visibility to everything policy-related
- Cleaned up lots of capitalization + old link issues
- Added gif for login customization

@kennyj42 ptal

2020-12-17 17:02 UTC, kennyj42 commented on products/access/src/content/policies-and-rules/how-policies-work.md
> +| Include | Exception | Require |
Should be "Exclude"
instead of Exception

2020-12-17 17:03 UTC, kennyj42 requested changes
One small change needed in the common configurations section

2020-12-17 17:09 UTC, abracchi-tw commented on products/access/src/content/policies-and-rules/how-policies-work.md
> +| Include | Exception | Require |
it does say `Exception` in the UI right now (I agree it should be `Exclude`, though)

2020-12-17 17:39 UTC, kennyj42 commented on products/access/src/content/policies-and-rules/how-policies-work.md
> +| Include | Exception | Require |
Ah, that's my fault, you're right. :)

2020-12-17 17:41 UTC, kennyj42 approved these changes

2020-12-21 17:42 UTC, jbampton commented on products/access/src/content/policies-and-rules/app-paths.md
> +* When applying Policy B to `dashboard.com/eng/`exec, the more specific policy takes precedence. The `/exec` path is gated by policy B instead of relying on the rules in policy A.
```suggestion
* When applying Policy B to `dashboard.com/eng/exec`, the more specific policy takes precedence. The `/exec` path is gated by policy B instead of relying on the rules in policy A.
```

2020-12-21 17:48 UTC, TownLake approved these changes

2020-12-21 18:07 UTC, merged