[Pages]: Add binding instructions to remix sites
cloudflare/cloudflare-docs pull request #5120
Opened 2022-07-12 09:58 UTC by Ekwuno

This PR updates adding bindings instructions for Remix projects. Addresses #5094

2022-07-12 10:51 UTC, WalshyDev requested changes

2022-07-12 10:51 UTC, WalshyDev commented on content/pages/framework-guides/remix.md
> +## Adding binding to Remix project
We should add before we deploy otherwise they just need to deploy again

2022-07-12 12:19 UTC, Ekwuno commented on content/pages/framework-guides/remix.md
> +## Adding binding to Remix project
I noticed the workflow is a bit weird currently, there is no way to add bindings when creating a new project. Like how you would an environment variable.

2022-07-12 16:44 UTC, WalshyDev commented on content/pages/framework-guides/remix.md
> +## Adding binding to Remix project
Oh whoops, I didn't see the deploy section talked about creating a project. I thought it was deploying an existing one

nevermind me

2022-07-13 17:49 UTC, WalshyDev commented
Can we get an example on how to use the bindings? That's what brought up the initial ticket.

these frameworks all have their own ways to use it and we should document it in here

2022-07-14 15:55 UTC, deadlypants1973 commented on content/pages/framework-guides/remix.md
> +### Using binding in your Remix application
```suggestion
### Using a binding in your Remix application
```

2022-07-14 15:55 UTC, deadlypants1973 commented on content/pages/framework-guides/remix.md
> +For example, if you create a KV namespace binding called `PRODUCTS_KV`, you will access it in your Remix application by first importing the `LoaderFunction` from `@remix-run/cloudflare-pages`. The `L
```suggestion
If you have created a KV namespace binding called `PRODUCTS_KV`, you will access it in your Remix application by first importing the `LoaderFunction` from `@remix-run/cloudflare-pages`. The `LoaderFunction` allows you to access data from different points in your Remix application. 
```

2022-07-14 15:55 UTC, deadlypants1973 commented on content/pages/framework-guides/remix.md
> +The following code block shows an example of accessing a KV namespace in Remix.
Where does this codeblock go?

2022-07-14 15:55 UTC, deadlypants1973 commented on content/pages/framework-guides/remix.md
> +
```suggestion
```

2022-07-14 15:55 UTC, deadlypants1973 commented on content/pages/framework-guides/remix.md
> +The following code block shows an example of accessing a KV namespace in Remix.
What about the other storage objects? How does a user configure this for DO?

2022-07-14 19:20 UTC, WalshyDev requested changes

2022-07-14 19:20 UTC, WalshyDev commented on content/pages/framework-guides/remix.md
> +    await PRODUCTS_KV.get(`product-${params.productId}`, {
```suggestion
```

2022-07-14 19:20 UTC, WalshyDev commented on content/pages/framework-guides/remix.md
> +      <p>{} Products</p>
Were the brackets here meant for some code? If not, can we remove them

2022-07-14 21:37 UTC, Ekwuno commented on content/pages/framework-guides/remix.md
> +      <p>{} Products</p>
```suggestion
      <p>Products</p>
```

2022-07-15 12:30 UTC, GregBrimble commented on content/pages/framework-guides/remix.md
>  By completing this guide, you have successfully deployed your Remix.js site to Cloudflare Pages. To get started with other frameworks, [refer to the list of Framework guides](/pages/framework-guides/
```suggestion
By completing this guide, you have successfully deployed your Remix site to Cloudflare Pages. To get started with other frameworks, [refer to the list of Framework guides](/pages/framework-guides/).
```

2022-07-15 12:30 UTC, GregBrimble commented on content/pages/framework-guides/remix.md
>  {{</Aside>}}
Remove this section?

2022-07-25 13:29 UTC, Ekwuno commented on content/pages/framework-guides/remix.md
>  {{</Aside>}}
Done!

2022-08-02 14:02 UTC, WalshyDev approved these changes

2022-08-02 14:02 UTC, WalshyDev commented on content/pages/framework-guides/remix.md
> +If you have created a KV namespace binding called `PRODUCTS_KV`, you will access it in your Remix application by first importing the `LoaderFunction` from `@remix-run/cloudflare-pages`. The `LoaderFu
the importing is only relevant to TS, you can make a Remix project with just JS right? 🤔

2022-08-02 14:02 UTC, WalshyDev commented on content/pages/framework-guides/remix.md
> +```typescript
it'd be cool to use the new tabs here 👀

2022-08-02 14:04 UTC, Ekwuno commented on content/pages/framework-guides/remix.md
> +```typescript
We are trying to roll it out slowly, so in the coming weeks my team will be adding the new  tabs 😁

2022-08-02 15:33 UTC, Ekwuno commented on content/pages/framework-guides/remix.md
> +If you have created a KV namespace binding called `PRODUCTS_KV`, you will access it in your Remix application by first importing the `LoaderFunction` from `@remix-run/cloudflare-pages`. The `LoaderFu
I think the default setup is in TS. I might be wrong, but LoaderFunction isn't just for TS. https://remix.run/docs/en/v1/api/remix#useloaderdata

2022-08-03 15:41 UTC, WalshyDev commented on content/pages/framework-guides/remix.md
> +If you have created a KV namespace binding called `PRODUCTS_KV`, you will access it in your Remix application by first importing the `LoaderFunction` from `@remix-run/cloudflare-pages`. The `LoaderFu
LoaderFunction is the type though, you create a loader function but no import is needed for that. The import is the function for grabbing that loader data (`useLoaderData`) for component rendering

2022-08-03 16:28 UTC, deadlypants1973 requested changes
1) Needs a DO code example.
2) Has to be clear on where the binding code goes in Remix directory.

2022-08-03 16:28 UTC, deadlypants1973 commented on content/pages/framework-guides/remix.md
> +Currently, the only way to use Durable Objects when using Cloudflare Pages is by having a separate Worker, creating a binding, and accessing it in `context`.
This needs a codeblock with an example.

2022-08-03 16:28 UTC, deadlypants1973 commented on content/pages/framework-guides/remix.md
> +Refer to the Durable Objects documentation to learn about deploying a [Durable Object](/workers/learning/using-durable-objects/)
```suggestion
Refer to the Durable Objects documentation to learn about deploying a [Durable Object](/workers/learning/using-durable-objects/).
```

2022-08-03 22:57 UTC, GregBrimble commented on content/pages/framework-guides/remix.md
> +You have to do this because there is currently no way to export the Durable Object class from a Pages Function.
```suggestion
You have to do this because there is no way to export the Durable Object class from a Pages Function. 
```

It's unlikely that we ever (directly) add this in the future. We have other plans on how we can make deploying Durable Objects easy from a Pages project, but it'll be very unlikely that this is done by exporting DO classes from Functions.

2022-08-03 22:57 UTC, GregBrimble commented on content/pages/framework-guides/remix.md
> +  const product = useLoaderData();
```suggestion
  const product = useLoaderData<typeof loader>();
```

2022-08-03 22:58 UTC, GregBrimble commented on content/pages/framework-guides/remix.md
> +    await context.PRODUCTS_KV.get(`product-${params.productId}`, {
```suggestion
    await context.PRODUCTS_KV.get<{ name: string }>(`product-${params.productId}`, {
```

2022-08-03 23:04 UTC, GregBrimble commented on content/pages/framework-guides/remix.md
> +  params,
```suggestion
  context,
  params,
```

2022-08-03 23:05 UTC, GregBrimble commented on content/pages/framework-guides/remix.md
> +highlight: [9,10,11,12,13,18,21]
Update these numbers if you accept my suggestions.

2022-08-03 23:06 UTC, GregBrimble commented on content/pages/framework-guides/remix.md
> +The following code block shows an example of accessing a KV namespace in Remix.
https://github.com/cloudflare/cloudflare-docs/pull/5120/files#diff-681df135c308ab29fcec511f4fb223227c9d283d1d9c1bef838c70b338b2aadbR85

A full filename and path is given here. Are you meaning something else?

2022-08-03 23:09 UTC, GregBrimble commented on content/pages/framework-guides/remix.md
> +If you have created a KV namespace binding called `PRODUCTS_KV`, you will access it in your Remix application by first importing the `LoaderFunction` from `@remix-run/cloudflare-pages`. The `LoaderFu
```suggestion
If you have created a KV namespace binding called `PRODUCTS_KV`, you can access its data in a [Remix `loader` function](https://remix.run/docs/en/v1/guides/data-loading#cloudflare-kv). 
```

2022-08-03 23:10 UTC, GregBrimble commented on content/pages/framework-guides/remix.md
> +export const loader: LoaderFunction = async ({
```suggestion
export const loader = async ({
```

2022-08-03 23:10 UTC, GregBrimble commented on content/pages/framework-guides/remix.md
> +import type { LoaderFunction } from "@remix-run/cloudflare";
```suggestion
import type { LoaderArgs } from "@remix-run/cloudflare";
```

2022-08-03 23:10 UTC, GregBrimble commented on content/pages/framework-guides/remix.md
> +}) => {
```suggestion
}: LoaderArgs) => {
```

2022-08-03 23:13 UTC, GregBrimble commented on content/pages/framework-guides/remix.md
> +Currently, the only way to use Durable Objects when using Cloudflare Pages is by having a separate Worker, creating a binding, and accessing it in `context`.
Assuming a binding of `FOO`, it's pretty much the same thing, @Ekwuno . Untested, but here's the gist:

```ts
export const loader = async ({ params, context, request }: LoaderArgs) => {
  const id = context.FOO.idFromName(params.id)
  const stub = context.FOO.get(id)
  const response = await stub.fetch(request)
  const data = await response.json() as { name: string }
  return json(data)
}
```

2022-11-30 11:07 UTC, GregBrimble commented on content/pages/framework-guides/remix.md
> +A [binding](/pages/platform/functions/#adding-bindings) is how your Function (Worker) interacts with external resources. You can add KV, Durable Object, and plain-text bindings to your project. A bin
```suggestion
With a [binding](/pages/platform/functions/bindings/), your application can interact with external resources. You can add KV, Durable Object, R2, D1, Service, plain-text and secret bindings to your project. A binding is a runtime variable that the Workers runtime provides to your code. You can also use these bindings in development with [Wrangler](https://developers.cloudflare.com/workers/wrangler/get-started/).
```

2022-11-30 11:07 UTC, GregBrimble commented on content/pages/framework-guides/remix.md
> +To add a KV namespace or Durable Object binding to your Remix application, refer to [Functions](/pages/platform/functions/#adding-bindings).
```suggestion
To add a binding to your Remix application, refer to [Bindings](/pages/platform/functions/bindings/).
```

2022-11-30 11:07 UTC, GregBrimble commented on content/pages/framework-guides/remix.md
> +highlight: [9,10,11,12,13,18,21]
```suggestion
highlight: [9,10,11,12,13,17,24]
```

2022-11-30 11:07 UTC, GregBrimble commented on content/pages/framework-guides/remix.md
> +Currently, the only way to use Durable Objects when using Cloudflare Pages is by having a separate Worker, creating a binding, and accessing it in `context`.
```suggestion
Currently, the only way to use Durable Objects when using Cloudflare Pages is by having a separate Worker, creating a binding, and accessing it in `context`. For example:

```ts
export const loader = async ({
  context,
  params,
}: LoaderArgs) => {
  const id = context.PRODUCTS_DO.idFromName(params.productId);
  const stub = context.PRODUCTS_DO.get(id);
  const response = await stub.fetch(request);
  const data = await response.json() as { name: string };
  return json(data);
};
```
```

2022-11-30 12:30 UTC, deadlypants1973 commented on content/pages/framework-guides/remix.md
> +## Creating and adding a binding to your Remix application
```suggestion
## Create and add a binding to your Remix application
```

2022-11-30 12:30 UTC, deadlypants1973 commented on content/pages/framework-guides/remix.md
> +### Using a binding in your Remix application
```suggestion
### Use a binding in your Remix application
```

2022-11-30 12:34 UTC, deadlypants1973 commented on content/pages/framework-guides/remix.md
> +A [binding](/pages/platform/functions/bindings/) allows your application to interact with Cloudflare developer products, such as KV, Durable Object, R2, and D1.
```suggestion
A [binding](/pages/platform/functions/bindings/) allows your application to interact with Cloudflare developer products, such as [KV](https://developers.cloudflare.com/workers/learning/how-kv-works/), [Durable Object](/workers/learning/using-durable-objects/), [R2](/r2/), and [D1](https://blog.cloudflare.com/introducing-d1/). 
```

2022-11-30 12:34 UTC, deadlypants1973 approved these changes

2022-11-30 12:50 UTC, deadlypants1973 commented on content/pages/framework-guides/remix.md
>  After configuring your site, you can begin your first deploy. You should see Cloudflare Pages installing `npm`, your project dependencies, and building your site before deploying it.
```suggestion
{{<Aside type="warning">}}

Currently Cloudflare uses Node `12.18.0` in the Pages build environment, but Remix requires a newer node version greater than `14.0.0` to build on Cloudflare Pages. To set the Node version, go to your Pages project > **Settings** > **Environment Variables** > **Production** and add `NODE_VERSION` environment variable with a value of `14` or greater in your Production option.

{{</Aside>}}

After configuring your site, you can begin your first deploy. You should see Cloudflare Pages installing `npm`, your project dependencies, and building your site before deploying it.
```

2022-11-30 13:32 UTC, merged