link to Worker template for AWS DynamoDB SQS
cloudflare/cloudflare-docs pull request #52
Opened 2020-10-07 16:49 UTC by koeninger

@greg-mckeon

2020-10-07 23:10 UTC, adamschwartz requested changes
Whitespace nit

2020-10-07 23:10 UTC, adamschwartz commented on products/workers/src/content/starters/index.md
> +/>
Missing new line after component.

2020-10-08 19:01 UTC, adamschwartz approved these changes

2020-10-08 20:42 UTC, adamschwartz approved these changes

2020-10-08 20:42 UTC, merged

2020-10-09 16:35 UTC, greg-mckeon commented
After the fact LGTM.