document PutObject supporting conditional uploads
cloudflare/cloudflare-docs pull request #5303
Opened 2022-07-26 20:07 UTC by Frederik-Baetens

Thanks to @vlovich for the wording.

Suggestions for further improved wording are of course welcome.

2022-07-27 12:21 UTC, KianNH commented
> as documented in the HTTP spec

Might be worth throwing in a link to [RFC 7232](https://datatracker.ietf.org/doc/html/rfc7232) like we do for the R2 -> Runtime APIs documentation.

![image](https://user-images.githubusercontent.com/94662631/181245424-be83aa78-042a-4271-9c44-5e57a7dc1793.png)

2022-07-27 13:30 UTC, Frederik-Baetens commented
I instead linked to the MDN page about conditional requests, that seems more accessible for the average user reading our docs.

2022-07-27 14:09 UTC, deadlypants1973 requested changes
Cloudflare style guide review

2022-07-27 14:09 UTC, deadlypants1973 commented on content/r2/platform/s3-compatibility/extensions.md
> +PutObject supports [conditional uploads](https://developer.mozilla.org/en-US/docs/Web/HTTP/Conditional_requests) via the [If-Match](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-Match)
```suggestion
PutObject supports [conditional uploads](https://developer.mozilla.org/en-US/docs/Web/HTTP/Conditional_requests) via the [If-Match](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-Match), [If-None-Match](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-None-Match), [If-Modified-Since](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-Modified-Since), and [If-Unmodified-Since](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-Unmodified-Since) headers. These operate as documented in the HTTP spec and behave similarly to how `GetObject`/`HeadObject` interpret these headers, rejecting uploads with `304 NotModified` or `412 PreconditionFailed` as appropriate when an upload is not necessary or the preceding state does not match respectively.
```

2022-07-27 14:09 UTC, deadlypants1973 commented on content/r2/platform/s3-compatibility/extensions.md
> +### Conditional operations in PutObject
```suggestion
### Conditional operations in `PutObject`
```

2022-07-27 14:44 UTC, KianNH commented
> I instead linked to the MDN page about conditional requests, that seems more accessible for the average user reading our docs. Is that all right with you?

I might have to do the same in the runtime APIs - maybe not everyone enjoys reading RFCs as much as me haha. Good call!

2022-07-28 12:53 UTC, deadlypants1973 commented on content/r2/platform/s3-compatibility/extensions.md
> +PutObject supports [conditional uploads](https://developer.mozilla.org/en-US/docs/Web/HTTP/Conditional_requests) via the [If-Match](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-Match)
```suggestion
`PutObject` supports [conditional uploads](https://developer.mozilla.org/en-US/docs/Web/HTTP/Conditional_requests) via the [`If-Match`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-Match), [`If-None-Match`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-None-Match), [`If-Modified-Since`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-Modified-Since), and [`If-Unmodified-Since`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-Unmodified-Since) headers. These headers operate as documented in the HTTP spec. They behave similarly to how `GetObject` and `HeadObject` interpret these headers, rejecting uploads with `304 NotModified` or `412 PreconditionFailed` error codes when an upload is not necessary or the preceding state does not match, respectively.
```

2022-07-28 13:05 UTC, deadlypants1973 approved these changes

2022-07-28 13:05 UTC, merged