Clarify API token permission needed
cloudflare/cloudflare-docs pull request #5310
Opened 2022-07-27 14:50 UTC by irvinebroque

refs https://jira.cfops.it/browse/PCX-4384

Specify the exact permission that an API token must have in order to make requests to the Stream GraphQL Analytics API

@dcpena for edits on how to frame the "prerequisite" part of this in the context of an ordered list of steps.

2022-07-27 15:28 UTC, irvinebroque commented
@dcpena - something funky going on here with indentation

https://92f4b32f.cloudflare-docs-7ou.pages.dev/stream/getting-analytics/fetching-bulk-analytics/

<img width="1117" alt="Screen Shot 2022-07-27 at 8 27 08 AM" src="https://user-images.githubusercontent.com/1221592/181287196-2bcf3252-2945-446c-8772-cb5597ce8f6d.png">

2022-07-27 15:41 UTC, dcpena commented
> @dcpena - something funky going on here with indentation
> 
> https://92f4b32f.cloudflare-docs-7ou.pages.dev/stream/getting-analytics/fetching-bulk-analytics/
> 
> <img alt="Screen Shot 2022-07-27 at 8 27 08 AM" width="1117" src="https://user-images.githubusercontent.com/1221592/181287196-2bcf3252-2945-446c-8772-cb5597ce8f6d.png">

Ooo, that is wonky. I checked if this behavior was occurring in other parts of the docs, and it is so I imagine it's a CSS thing that needs fixed. I can file a ticket with the DA team to get it corrected.

2022-08-09 18:29 UTC, victor-perov requested changes

2022-08-09 18:29 UTC, victor-perov commented on content/stream/getting-analytics/fetching-bulk-analytics.md
> +2.  Include your Cloudflare API token in the headers (see cURL example included on this page).
Recently I made some improvements for GraphQL API tutorials and it would be nice if we can use the same way of showing `curl` examples.

Please check this as an example: https://github.com/cloudflare/cloudflare-docs/blob/65db1d09aa4c53b6501125b7764603fa0a60817c/content/analytics/graphql-api/tutorials/end-customer-analytics/index.md?plain=1#L14-L46
So the idea is that you can provide readable query and still use it as a payload by stripping '\n' out. This will also allow you to drop lines 92-125 below.

The same can be applied to other GQL snippets on this page.

2022-08-09 18:29 UTC, victor-perov commented on content/stream/getting-analytics/fetching-bulk-analytics.md
> +3.  Be sure to change the `$ACCOUNT\_ID` with your account ID and the date range.
Please replace `$ACCOUNT_ID` with `CLOUDFLARE_ACCOUNT_ID`, and `$TOKEN` with `CLOUDFLARE_API_TOKEN` to be consistent with other examples.

2022-08-14 20:05 UTC, irvinebroque commented
Updated to show simple request/response in GraphQL format, rather than kludge it all into a cURL request.

2022-08-17 15:24 UTC, victor-perov commented on content/stream/getting-analytics/fetching-bulk-analytics.md
> +*   Each object inside videoPlaybackEventsAdaptiveGroups represents one video
```suggestion
* Each object inside videoPlaybackEventsAdaptiveGroups represents one video
```

2022-08-17 15:24 UTC, victor-perov commented on content/stream/getting-analytics/fetching-bulk-analytics.md
> +*   Each object inside videoPlaybackEventsAdaptiveGroups represents one video
It seems that this indentation is a pattern in this file, but I'm not sure why.

2022-08-17 15:59 UTC, dcpena commented
At the top of the page, an aside is included that says users need the account analytics permission. Do we want to keep the aside, or do we want to remove it in favor of the prerequisite line? I have no preference, especially because I believe this page will get tidied up a bit in a later phase of the docs refresh.

2022-08-17 16:18 UTC, irvinebroque commented
@dcpena nice catch, moved this up on the page into the aside in https://github.com/cloudflare/cloudflare-docs/pull/5310/commits/28b7bd949e5ff8f3ffdaf421bc88b97824137503

<img width="768" alt="Screen Shot 2022-08-17 at 9 17 01 AM" src="https://user-images.githubusercontent.com/1221592/185190936-c7145473-b876-4e17-aa9f-3df57af1349a.png">

2022-08-17 16:23 UTC, dcpena approved these changes

2022-08-26 19:04 UTC, irvinebroque commented
@victor-perov — can you please take another look? Decided it's simpler here to just show the GraphQL queries, with proper syntax highlighting, rather than curl requests.

2022-09-06 19:45 UTC, irvinebroque commented
Closing in favor of https://github.com/cloudflare/cloudflare-docs/pull/5752

2022-09-06 19:45 UTC, closed without merging