[Pages]: Add R2 and D1 sections to Functions docs
cloudflare/cloudflare-docs pull request #5436
Opened 2022-08-03 20:45 UTC by Ekwuno

This PR adds documentation for R2 and D1 support in local dev and on the Pages dashboard.

2022-08-04 12:19 UTC, WalshyDev requested changes

2022-08-04 12:19 UTC, WalshyDev commented on content/pages/platform/functions/_index.md
> +### R2
I think R2 and D1 should be under DOs

2022-08-04 12:19 UTC, WalshyDev commented on content/pages/platform/functions/_index.md
> +### R2
KV + DO already follow this pattern
```suggestion
### R2 bucket
```

2022-08-04 12:19 UTC, WalshyDev commented on content/pages/platform/functions/_index.md
> +### D1
```suggestion
### D1 database
```

2022-08-04 12:19 UTC, WalshyDev commented on content/pages/platform/functions/_index.md
> +Cloudflare D1 is Cloudflare's first SQL database built on SQLite. Since D1 is currently in closed beta, you will need access to use it in your account. If you have access to D1, within Pages, you can
We should probably have an aside saying this is in private beta

2022-08-04 12:19 UTC, WalshyDev commented on content/pages/platform/functions/_index.md
> +export async function onRequestGet({ env }) => {
```suggestion
export async function onRequestGet({ env }) {
```

2022-08-04 12:19 UTC, WalshyDev commented on content/pages/platform/functions/_index.md
> +}
```suggestion
export async function onRequestGet({ env }) {
  const ps = env.NORTHWIND_DB.prepare('SELECT * from users');
  const data = await ps.first();

  return Response.json(data);
}
```

2022-08-04 12:19 UTC, WalshyDev commented on content/pages/platform/functions/_index.md
> +
double space
```suggestion
```

2022-08-04 12:19 UTC, WalshyDev commented on content/pages/platform/functions/_index.md
> +
```suggestion
```

2022-08-04 12:19 UTC, WalshyDev commented on content/pages/platform/functions/_index.md
> +While developing locally, you can interact with an R2 bucket by adding `--r2=<BINDING>` to your run command. For example, if your bucket is bound to `R2`, you can access this bucket in local dev by r
```suggestion
While developing locally, you can interact with an R2 bucket by adding `--r2=<BINDING>` to your run command. For example, if your bucket is bound to `R2`, you can access this bucket in local dev by running `npx wrangler pages dev dist --r2=BUCKET`. The can interact with this binding by using `context.env` (e.g. `context.env.BUCKET`). 
```

2022-08-04 12:19 UTC, WalshyDev commented on content/pages/platform/functions/_index.md
> +While developing locally, you can interact with a D1 database by adding `--d1=<BINDING> ` to your run command. For example, if your database is bound to `NORTHWIND_DB`, you can access this database i
```suggestion
While developing locally, you can interact with a D1 database by adding `--d1=<BINDING> ` to your run command. For example, if your database is bound to `NORTHWIND_DB`, you can access this database in local dev by running `npx wrangler pages dev dist --d1=NORTHWIND_DB`. The can interact with this binding by using `context.env` (e.g. `context.env. NORTHWIND_DB `).
```

2022-08-04 13:45 UTC, Ekwuno commented on content/pages/platform/functions/_index.md
> +Cloudflare D1 is Cloudflare's first SQL database built on SQLite. Since D1 is currently in closed beta, you will need access to use it in your account. If you have access to D1, within Pages, you can
done

2022-08-05 00:06 UTC, WalshyDev requested changes

2022-08-05 00:06 UTC, WalshyDev commented on content/pages/platform/functions/_index.md
> +While developing locally, you can interact with an R2 bucket by adding `--r2=<BINDING>` to your run command. For example, if your bucket is bound to `R2`, you can access this bucket in local dev by r
```suggestion
While developing locally, you can interact with an R2 bucket by adding `--r2=<BINDING>` to your run command. For example, if your bucket is bound to `BUCKET`, you can access this bucket in local dev by running `npx wrangler pages dev dist --r2=BUCKET`. The can interact with this binding by using `context.env` (e.g. `context.env.BUCKET`). 
```

2022-08-05 00:06 UTC, WalshyDev commented on content/pages/platform/functions/_index.md
> +  const obj = await env.R2.get('some-key');
```suggestion
  const obj = await env.BUCKET.get('some-key');
```

2022-08-05 12:40 UTC, WalshyDev approved these changes

2022-08-07 19:47 UTC, Cyb3r-Jak3 reviewed
Found a couple of extra spaces

2022-08-07 19:47 UTC, Cyb3r-Jak3 commented on content/pages/platform/functions/_index.md
> +While developing locally, you can interact with a D1 database by adding `--d1=<BINDING> ` to your run command. For example, if your database is bound to `NORTHWIND_DB`, you can access this database i
Space after "\<BINDING\> `"

2022-08-07 19:47 UTC, Cyb3r-Jak3 commented on content/pages/platform/functions/_index.md
> +While developing locally, you can interact with a D1 database by adding `--d1=<BINDING> ` to your run command. For example, if your database is bound to `NORTHWIND_DB`, you can access this database i
Space between `context.env` and `NORTHWIND_DB` as between `NORTHWIND_DB` and `

2022-08-07 19:48 UTC, WalshyDev commented on content/pages/platform/functions/_index.md
> +While developing locally, you can interact with a D1 database by adding `--d1=<BINDING> ` to your run command. For example, if your database is bound to `NORTHWIND_DB`, you can access this database i
```suggestion
While developing locally, you can interact with a D1 database by adding `--d1=<BINDING>` to your run command. For example, if your database is bound to `NORTHWIND_DB`, you can access this database in local dev by running `npx wrangler pages dev dist --d1=NORTHWIND_DB`. The can interact with this binding by using `context.env` (e.g. `context.env. NORTHWIND_DB `).
```

2022-08-08 17:05 UTC, WalshyDev commented
Dashboard is now going live, merging.

2022-08-08 17:05 UTC, merged