Doc: Access: Kubectl: add AKS-specific info
cloudflare/cloudflare-docs pull request #545
Opened 2020-12-22 15:51 UTC by xens

This commit adds more info on how to access Azure AKS clusters that are exposed through Cloudflare Access.

2020-12-28 18:28 UTC, abracchi-tw requested changes

2020-12-28 18:28 UTC, abracchi-tw commented on products/access/src/content/protocols-and-connections/kubectl.md
> +If you want to use Cloudflare Access to protect an Azure AKS cluster you'll need to exclude the [login + refresh-token endpoints](https://docs.microsoft.com/en-us/azure/aks/concepts-identity#webhook-
If you want to use Cloudflare Access to protect an Azure AKS cluster, exclude the [login and refresh_token endpoints](https://docs.microsoft.com/en-us/azure/aks/concepts-identity#webhook-and-api-server) from the `HTTPS_PROXY` first. This will prevent the login and refresh mechanisms from going through the proxy and failing.

2020-12-30 14:05 UTC, xens commented on products/access/src/content/protocols-and-connections/kubectl.md
> +If you want to use Cloudflare Access to protect an Azure AKS cluster you'll need to exclude the [login + refresh-token endpoints](https://docs.microsoft.com/en-us/azure/aks/concepts-identity#webhook-
agree better phrasing, corrected !

2021-01-04 09:43 UTC, abracchi-tw approved these changes

2021-01-04 09:43 UTC, merged