Improve copy to clipboard for code snippets
cloudflare/cloudflare-docs pull request #5467
Opened 2022-08-08 19:16 UTC by Ekwuno

This PR adds improves on the existing copy to clipboard feature. https://update-copy-svg.cloudflare-docs-7ou.pages.dev/pages/platform/functions/

2022-08-09 09:03 UTC, lauragift21 commented on assets/events.ts
> +        button.innerHTML = `<svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 16 16" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg"  style= "width:1rem; pointe
I like the copy and check icon switch, can I suggest a minimal looking icon instead.
 
![Screenshot 2022-08-09 at 11 00 03](https://user-images.githubusercontent.com/17781315/183609258-2f0e2c6f-4d7d-4177-924c-26145d4b372f.png)

Check Icon:
```html
<svg width="459" height="459" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M257.327 142.577a21.513 21.513 0 0 1 29.905.226 21.516 21.516 0 0 1 .79 29.896l-114.463 143.15a21.507 21.507 0 0 1-23.817 5.314 21.498 21.498 0 0 1-7.165-4.74L66.67 240.516a21.518 21.518 0 0 1-5.282-23.799 21.516 21.516 0 0 1 35.69-6.61l60.072 60.043 99.603-126.942c.179-.222.37-.432.574-.631Zm-26.393 147.454 26.393 26.392a21.508 21.508 0 0 0 15.599 6.284 21.51 21.51 0 0 0 15.355-6.858l114.52-143.15a21.513 21.513 0 0 0 4.587-23.954 21.513 21.513 0 0 0-35.885-5.537L271.871 270.15l-13.913-13.942-27.052 33.823h.028Z" fill="#000"/></svg>

```

Copy Icon

```html
<svg width="492" height="492" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M369 399.75a61.497 61.497 0 0 1-61.5 61.5H92.25a61.498 61.498 0 0 1-61.5-61.5V184.5a61.499 61.499 0 0 1 61.5-61.5v30.75A30.753 30.753 0 0 0 61.5 184.5v215.25a30.752 30.752 0 0 0 30.75 30.75H307.5c8.155 0 15.977-3.24 21.744-9.006a30.755 30.755 0 0 0 9.006-21.744H369Z" fill="#000"/><path d="M184.5 61.5a30.752 30.752 0 0 0-30.75 30.75V307.5c0 8.155 3.24 15.977 9.006 21.744a30.755 30.755 0 0 0 21.744 9.006h215.25c8.155 0 15.977-3.24 21.744-9.006A30.755 30.755 0 0 0 430.5 307.5V92.25a30.753 30.753 0 0 0-30.75-30.75H184.5Zm0-30.75h215.25a61.499 61.499 0 0 1 61.5 61.5V307.5a61.497 61.497 0 0 1-61.5 61.5H184.5a61.497 61.497 0 0 1-61.5-61.5V92.25a61.498 61.498 0 0 1 61.5-61.5Z" fill="#000"/></svg>
```

2022-08-11 16:35 UTC, rita3ko requested changes
+1 to gift's icon suggestion. otherwise looks good

2022-08-11 16:35 UTC, rita3ko commented on assets/events.ts
> +        button.innerHTML = `<svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 16 16" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg"  style= "width:1rem; pointe
i like gift's suggested icons!

2022-08-12 08:55 UTC, lauragift21 approved these changes

2022-08-12 15:31 UTC, rita3ko approved these changes

2022-08-12 15:36 UTC, merged