devcomquickwins: Add custom domain for images example
cloudflare/cloudflare-docs pull request #5471
Opened 2022-08-09 08:29 UTC by lauragift21

Write an example on how to use workers to serve images from a custom domain.

Fixes: https://github.com/cloudflare/cloudflare-docs/issues/2383

2022-08-09 14:35 UTC, rita3ko commented
@lauragift21 do you want to try using the code switched for this one and add a TS example too? :)

2022-08-09 14:59 UTC, eidam reviewed
lgtm, and it would make a very nice template for cloudlfare/templates repository :)

2022-08-12 11:23 UTC, deadlypants1973 requested changes

2022-08-12 11:23 UTC, deadlypants1973 commented on content/workers/examples/images-workers.md
> +Another way you can serve images from a custom domain is by using the `cdn-cgi/imagedelivery` prefix path which is used as path to trigger cdn-cgi image proxy.
```suggestion
Another way you can serve images from a custom domain is by using the `cdn-cgi/imagedelivery` prefix path which is used as path to trigger `cdn-cgi` image proxy.
```

2022-08-12 11:23 UTC, deadlypants1973 commented on content/workers/examples/images-workers.md
> +Here's an example, the hostname is a Cloudflare proxied domain under the same account as the Image, followed with the prefix path and the image `<ACCOUNT_HASH>`, `<IMAGE_ID>` and `<VARIANT_NAME>` whi
```suggestion
Below is an example showing the hostname as a Cloudflare proxied domain under the same account as the Image, followed with the prefix path and the image `<ACCOUNT_HASH>`, `<IMAGE_ID>` and `<VARIANT_NAME>` which can be found in the **Images** on the Cloudflare dashboard.
```

2022-08-12 11:23 UTC, deadlypants1973 commented on content/workers/examples/images-workers.md
> +To serve images from a custom domain, you can create Worker like the example below:
```suggestion
To serve images from a custom domain:

1. Log in to the [Cloudflare dashboard](https://dash.cloudflare.com).
2. Select you account > select **Workers**.
3. Select **Create a service**.
4. In your Workers, select **Quick edit** and paste the following code.
```

2022-08-12 11:23 UTC, deadlypants1973 commented on content/workers/examples/images-workers.md
> +```js
Making sure that this spacing is intentional?  Should there be another space between 16 and 17?

2022-08-12 11:23 UTC, deadlypants1973 commented on content/workers/examples/images-workers.md
> +```ts
Same comment as above.

2022-08-12 11:23 UTC, deadlypants1973 commented on content/workers/examples/images-workers.md
> +{{</tab>}}
Same comment as above.

2022-08-12 15:52 UTC, lauragift21 commented on content/workers/examples/images-workers.md
> +```js
This is fine, adding a space between the tab and the code block doesn't change the way it displays the code block.

2022-08-19 09:21 UTC, lauragift21 commented
> lgtm, and it would make a very nice template for cloudlfare/templates repository :)

Thanks @eidam, I will add it in when this is merged.

2022-08-19 13:54 UTC, deadlypants1973 approved these changes

2022-08-22 09:37 UTC, merged