Add Vite3 deployment guide
cloudflare/cloudflare-docs pull request #5533
Opened 2022-08-15 18:38 UTC by codewithkristian

2022-08-16 13:12 UTC, deadlypants1973 requested changes

2022-08-16 13:12 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-vite3-project.md
> +[Vite](https://vitejs.dev) is a next-generation build tool for frontend developers. With [the recent release of Vite 3](https://vitejs.dev/blog/announcing-vite3.html), developers can make use of new
```suggestion
[Vite](https://vitejs.dev) is a next-generation build tool for front-end developers. With [the release of Vite 3](https://vitejs.dev/blog/announcing-vite3.html), developers can make use of new command line (CLI) improvements, starter templates, and [more](https://github.com/vitejs/vite/blob/main/packages/vite/CHANGELOG.md#300-2022-07-13) to help build their front-end applications.
```

2022-08-16 13:12 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-vite3-project.md
> +Cloudflare Pages has native support for Vite 3 projects in our build environment. And with the recent improvements to our [build process](https://blog.cloudflare.com/cloudflare-pages-build-improvemen
```suggestion
Cloudflare Pages has native support for Vite 3 projects. Refer to the blog post on [improvements to the Pages build process](https://blog.cloudflare.com/cloudflare-pages-build-improvements/), including sub-second build initialization, for more information on using Vite 3 and Cloudflare Pages to optimize your application's build tooling.
```

2022-08-16 13:12 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-vite3-project.md
> +If you want to start a new project, and deploy it to Cloudflare Pages, Vite 3's new templating system makes it a breeze to select and create a new project with the defaults you need to hit the ground
This paragraph needs to be replaced (it's blog language) with an explanation of what the user will do and how they will do it. "You will ___ by ___:" Explain the codeblock.

2022-08-16 13:12 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-vite3-project.md
> +Done. Now run:
"done" what did they do?

2022-08-16 13:12 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-vite3-project.md
> +Get started deploying a Vite 3-powered Vue application to Cloudflare Pages with a single command:
Is this the third step in the flow?

2022-08-16 13:12 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-vite3-project.md
> +With a generated project, deploying to Cloudflare Pages just takes a few minutes. You can create a new GitHub repository, and push your code, using [GitHub's `gh` CLI](https://cli.github.com):
```suggestion
You will now create a new GitHub repository, and push your code using [GitHub's `gh` command line (CLI)](https://cli.github.com):
```

2022-08-16 13:12 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-vite3-project.md
> +Finally, using the "Environment variables" section, configure `NODE_VERSION` to any version of Node greater than v14.18 -- in our example, we'll use `16`:
```suggestion
To deploy your project with Pages:

1. Log in to the [Cloudflare dashboard](https://dash.cloudflare.com) and select your account.
2. Go to **Pages** > **Create a project ** > *Connect to git*.
3. Select your new GitHub repository.
4. In the **Set up builds and deployments**, set `npm run dev` as the **Build command**, and `dist` as the **Build output directory**.
5. Select **Environment variables (advanced)** > **+ Add variable** > configure a `NODE_VERSION` variable with a value of any version of Node greater than `14.18` -- this example uses `16`:
```

2022-08-16 13:12 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-vite3-project.md
> +![Environment variables](/pages/framework-guides/media/vite3-guide-environment-variables.png)
I don't think either of these are necessary. We don't include screenshots in any other framework guide.

2022-08-16 13:12 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-vite3-project.md
> +In just a few seconds, your project will be deployed to Pages. Check out an example of it at [vite-on-pages.pages.dev](https://vite-on-pages.pages.dev)!
```suggestion
After completing configuration, select Save and Deploy.

You will see your first deploy pipeline in progress. Pages installs all dependencies and builds the project as specified. After you have deployed your project, it will be available at the `<YOUR_PROJECT_NAME>.pages.dev` subdomain. Find your project's subdomain in **Pages** > select your project > **Deployments**.

Cloudflare Pages will automatically rebuild your project and deploy it on every new pushed commit.

Additionally, you will have access to [preview deployments](https://developers.cloudflare.com/pages/platform/preview-deployments/), which repeat the build-and-deploy process for pull requests. With these, you can preview changes to your project with a real URL before deploying them to production.
```

2022-08-16 13:12 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-vite3-project.md
> +
```suggestion
## Learn more

By completing this guide, you have successfully deployed your Vite3 site to Cloudflare Pages. To get started with other frameworks, [refer to the list of Framework guides](https://developers.cloudflare.com/pages/framework-guides/).
```

2022-08-16 15:01 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-vite3-project.md
> +It’s easy to get started with Cloudflare Pages – sign up at [pages.cloudflare.com](https://pages.cloudflare.com), connect a GitHub or GitLab account, and deploy your first project in just minutes. If
```suggestion
```

2022-08-16 15:02 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-vite3-project.md
> +
```suggestion
```

2022-08-18 16:28 UTC, codewithkristian commented on content/pages/framework-guides/deploy-a-vite3-project.md
> +If you want to start a new project, and deploy it to Cloudflare Pages, Vite 3's new templating system makes it a breeze to select and create a new project with the defaults you need to hit the ground
wow oops! sorry about that

2022-08-18 16:28 UTC, codewithkristian commented on content/pages/framework-guides/deploy-a-vite3-project.md
> +Done. Now run:
this part is command output so i'm going to leave it as is

2022-08-19 13:55 UTC, deadlypants1973 approved these changes

2022-08-19 13:55 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-vite3-project.md
> +# Deploying a Vite 3 project
```suggestion
# Deploy a Vite 3 project
```

2022-08-19 13:55 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-vite3-project.md
> +After completing configuration, select Save and Deploy.
```suggestion
After completing configuration, select **Save and Deploy**.
```

2022-08-19 14:52 UTC, merged