Update about YARN_VERSION
cloudflare/cloudflare-docs pull request #5560
Opened 2022-08-18 05:38 UTC by iiome

The script downloads version from https://github.com/yarnpkg/yarn/releases

The download of v2 or v3 are not yet possible. Those versions are delivered through Corepack https://yarnpkg.com/getting-started/instal

2022-08-18 14:06 UTC, deadlypants1973 approved these changes

2022-08-30 19:26 UTC, WalshyDev requested changes

2022-08-30 19:26 UTC, WalshyDev commented on content/pages/platform/build-configuration.md
> +| sqlite3     | Version 3.11.0                              | Any version                       |                      |
You can't change this therefore it isn't true that any version is supported.
```suggestion
| sqlite3     | Version 3.11.0                              |                                   |                      |
```

2022-08-31 10:27 UTC, WalshyDev approved these changes

2022-08-31 10:27 UTC, merged