[ZT] add DLP for google drive
cloudflare/cloudflare-docs pull request #5579
Opened 2022-08-19 18:58 UTC by ranbel

PCX-4472

2022-08-19 19:00 UTC, ranbel commented
Preview link: https://597f6283.cloudflare-docs-7ou.pages.dev/cloudflare-one/policies/filtering/http-policies/data-loss-prevention/configuration-guides/

2022-09-06 22:51 UTC, cloudflare-noelle requested changes
One change recommended based on quick ship, thanks sooo much for your patience here

2022-09-06 22:51 UTC, cloudflare-noelle commented on content/cloudflare-one/policies/filtering/http-policies/data-loss-prevention/configuration-guides/google-drive.md
> +## Policy recommendations
I know I took way too long to review this, but with the wait, we can now remove lines 12-22.  We removed these URLs from scanning in a quick SHIP to get ready for GA.

2022-09-08 20:46 UTC, ranbel commented on content/cloudflare-one/policies/filtering/http-policies/data-loss-prevention/_index.md
> +{{<beta>}} Data Loss Prevention {{</beta>}}
@cloudflare-noelle Should we remove the beta flag?

2022-09-08 20:48 UTC, ranbel commented on content/cloudflare-one/policies/filtering/http-policies/data-loss-prevention/configuration-guides/google-drive.md
> +To inspect Google Drive traffic in Chrome, you will need to [disable QUIC in Chrome](/cloudflare-one/policies/filtering/http-policies/incompatible-traffic/#disable-quic-in-google-chrome).
Do users still need to disable QUIC, now that Gateway automatically configures Chrome to fall back to H2?
https://developers.cloudflare.com/cloudflare-one/policies/filtering/http-policies/http3/

2022-09-08 21:06 UTC, ranbel commented on content/cloudflare-one/policies/filtering/http-policies/data-loss-prevention/configuration-guides/google-drive.md
> +DLP for Google Drive is compatible with all popular browsers.
Which browsers are supported?

2022-09-08 21:26 UTC, cloudflare-noelle commented on content/cloudflare-one/policies/filtering/http-policies/data-loss-prevention/configuration-guides/google-drive.md
> +DLP for Google Drive is compatible with all popular browsers.
The site or application being used is more likely to affect visibility than the browser. I have tested on Chrome, Firefox, and Safari, and I haven't received any feedback from customers on issues with a different browser.

2022-09-08 21:36 UTC, cloudflare-noelle commented on content/cloudflare-one/policies/filtering/http-policies/data-loss-prevention/configuration-guides/google-drive.md
> +To inspect Google Drive traffic in Chrome, you will need to [disable QUIC in Chrome](/cloudflare-one/policies/filtering/http-policies/incompatible-traffic/#disable-quic-in-google-chrome).
Oo good catch here, we can pull this line too, thanks!

2022-09-08 21:37 UTC, cloudflare-noelle commented on content/cloudflare-one/policies/filtering/http-policies/data-loss-prevention/_index.md
> +{{<beta>}} Data Loss Prevention {{</beta>}}
DLP is going GA on Monday the 19th, would it be possible to pull the beta flag next friday or that Monday?

2022-09-09 14:28 UTC, ranbel commented on content/cloudflare-one/policies/filtering/http-policies/data-loss-prevention/_index.md
> +{{<beta>}} Data Loss Prevention {{</beta>}}
yes let's pull it on Monday (I'm OOO on Friday)

2022-09-09 20:07 UTC, kodster28 approved these changes

2022-09-09 21:06 UTC, merged