Add myself to Pages reviews
cloudflare/cloudflare-docs pull request #5696
Opened 2022-08-30 19:24 UTC by WalshyDev

2022-08-30 21:00 UTC, crwaters16 requested changes

2022-08-30 21:00 UTC, crwaters16 commented on .github/actions/owners.ts
> +  pages: ["deadlypants1973", "WalshyDev"],
```suggestion
  pages: ["deadlypants1973"],
```

2022-08-30 21:00 UTC, crwaters16 commented on .github/actions/owners.ts
> +  pages: ["deadlypants1973", "WalshyDev"],
We restrict owners to PCX reviewers (happy to chat about why separately) - you're welcome to add yourself to to `export const REVIEWERS` in the same way the logs/analytics products have in lines 63-65 to add yourself to reviews.

2022-08-30 21:21 UTC, WalshyDev commented on .github/actions/owners.ts
> +  pages: ["deadlypants1973", "WalshyDev"],
Added myself to REVIEWERS 👍 

Is there any difference between the two in terms of being assigned? My goal here is just to be assigned on all Pages PRs/issues so I can review them. I review them all anyway but just want to reduce the friction of me looking for them or them being sent to me.

2022-08-30 21:38 UTC, WalshyDev commented on .github/actions/owners.ts
> +  pages: ["deadlypants1973", "WalshyDev"],
Ah ok I see this: https://github.com/cloudflare/cloudflare-docs/pull/5612

It would still be nice to have myself added to PRs opened by PCX just to reduce friction on needing to be pinged later.

2022-09-01 19:31 UTC, crwaters16 approved these changes

2022-09-01 19:42 UTC, merged