[Magic Firewall] Added content for Managed Rulesets
cloudflare/cloudflare-docs pull request #5711
Opened 2022-08-31 18:51 UTC by dcpena

Added content for Managed Rulesets to address PCX-4383.

2022-08-31 21:54 UTC, arges requested changes

2022-08-31 21:54 UTC, arges commented on content/magic-firewall/about/ruleset-logic.md
> +The Root phase is maintained by the network owners, and rule expressions, order of execution, and rule action
Who are the network owners? Should this just say `user` or `account owner`?
Also should this sentence have all these ands?

Idea:
The Magic Firewall Root phase is a set of rules defined by the user. The expression, order and actions of those rules can be customized by the user.

In addition, a user can add a rule in this root phase to override the behavior of a rule in the managed phase.

2022-08-31 21:54 UTC, arges commented on content/magic-firewall/about/ruleset-logic.md
> +Managed Phase rulesets are updated and maintained by Cloudflare and based on rogue traffic patterns.
Our rulesets can be based on a number of things beyond 'rogue traffic patterns'. Can we use a more generic term?   
Suggestion:
Cloudflare creates these rules based on best practices, known malicious patterns, and other criteria.

2022-08-31 21:54 UTC, arges commented on content/magic-firewall/about/ruleset-logic.md
> +Cloudflare maintains the expressions and order of execution for rules in the managed phase, and rules
Should this be two sentences for clarity?

2022-08-31 21:54 UTC, arges commented on content/magic-firewall/how-to/enable-managed-rulesets.md
> +Before you can begin using Managed Rulesets with Magic Firewall, your account must be set up to use Managed Rulesets.
Should we replace 'set up' with 'entitled'?
Also how will a user go about doing this? Should we mention 'talk with your account representative'?

2022-09-01 14:45 UTC, tejaswi-cf commented on content/magic-firewall/about/ruleset-logic.md
> +Magic Firewall processes traffic in two phases: in the first phase, Magic Firewall matches packets against rules in the Root phase. In the second phase, Magic Firewall matches packets against rules i
Can you replace Root phase with Custom phase?
It was my mistake, I wrote it this way in notes I shared.

2022-09-01 14:47 UTC, tejaswi-cf commented on content/magic-firewall/how-to/enable-managed-rulesets.md
> +To enabled or disable a rule, you can specify which properties should be overriden. The overrides occur in the managed phase, root kind ruleset. Currently, you can only have one rule in the root rule
Can you clarify that though we can have one rule, the rule can have multiple overrides in it?
i.e. the number of overrides the customer can add is not limited to one. They just have to put all the overrides into a single rule.

2022-09-01 15:03 UTC, tejaswi-cf commented on content/magic-firewall/how-to/enable-managed-rulesets.md
> +- `action`: The value can only be set to `log` if the rule's default action is not applied. When this occurs, the rule only produces logs.
The action & effect order is not right.
I think this line should be 
```
The value can be set to `log` so the rule only produces logs instead of applying the rule's default action
```

2022-09-01 15:07 UTC, tejaswi-cf commented on content/magic-firewall/how-to/enable-managed-rulesets.md
> +           "enabled": true
"action": "log" needs to be added since we want to set the category in log mode.

2022-09-01 20:35 UTC, dcpena commented on content/magic-firewall/how-to/enable-managed-rulesets.md
> +           "enabled": true
Fixed

2022-09-01 20:35 UTC, dcpena commented on content/magic-firewall/about/ruleset-logic.md
> +The Root phase is maintained by the network owners, and rule expressions, order of execution, and rule action
Fixed

2022-09-01 20:36 UTC, dcpena commented on content/magic-firewall/about/ruleset-logic.md
> +Cloudflare maintains the expressions and order of execution for rules in the managed phase, and rules
Good call! Fixed

2022-09-01 20:36 UTC, dcpena commented on content/magic-firewall/how-to/enable-managed-rulesets.md
> +Before you can begin using Managed Rulesets with Magic Firewall, your account must be set up to use Managed Rulesets.
Agreed. Fixed

2022-09-01 20:36 UTC, dcpena commented on content/magic-firewall/about/ruleset-logic.md
> +Managed Phase rulesets are updated and maintained by Cloudflare and based on rogue traffic patterns.
I like that! fixed

2022-09-01 20:36 UTC, dcpena commented on content/magic-firewall/about/ruleset-logic.md
> +Magic Firewall processes traffic in two phases: in the first phase, Magic Firewall matches packets against rules in the Root phase. In the second phase, Magic Firewall matches packets against rules i
Done. Let me know if any other instances need corrected

2022-09-01 20:36 UTC, dcpena commented on content/magic-firewall/how-to/enable-managed-rulesets.md
> +- `action`: The value can only be set to `log` if the rule's default action is not applied. When this occurs, the rule only produces logs.
Fixed

2022-09-01 20:37 UTC, dcpena commented on content/magic-firewall/how-to/enable-managed-rulesets.md
> +To enabled or disable a rule, you can specify which properties should be overriden. The overrides occur in the managed phase, root kind ruleset. Currently, you can only have one rule in the root rule
done

2022-09-01 21:25 UTC, ranbel commented on content/magic-firewall/about/ruleset-logic.md
> +Managed Phase rulesets are updated and maintained by Cloudflare, and Cloudflare creates these rules based on best practices, known malicious patterns, and other criteria.
What's the capitalization standard for "Managed phase"? In this doc I see "managed phase", "Managed phase", and "Managed Phase".

2022-09-01 21:26 UTC, ranbel commented on content/magic-firewall/how-to/enable-managed-rulesets.md
> +- `managed_ruleset_id`: The ID of the Managed Phase Managed Kind ruleset the contains the rule you want to enable.
```suggestion
- `managed_ruleset_id`: The ID of the Managed Phase Managed Kind ruleset that contains the rule you want to enable.
```

2022-09-01 21:27 UTC, ranbel commented on content/magic-firewall/how-to/enable-managed-rulesets.md
> +The example below contains a request for a Managed Phase Managed Kind  ruleset.
```suggestion
The example below contains a request for a Managed Phase Managed Kind ruleset.
```

2022-09-01 21:27 UTC, ranbel commented on content/magic-firewall/how-to/enable-managed-rulesets.md
> +The example below contains a request for a Managed Phase Managed Kind  ruleset.
same question about capitalization for "Managed Phase Managed Kind"

2022-09-01 21:27 UTC, ranbel commented on content/magic-firewall/how-to/enable-managed-rulesets.md
> +header: Example request - Create a Managed Phase Managed Kind  ruleset
```suggestion
header: Example request - Create a Managed Phase Managed Kind ruleset
```

2022-09-01 21:28 UTC, ranbel approved these changes

2022-09-02 14:39 UTC, tejaswi-cf approved these changes

2022-09-06 14:46 UTC, arges approved these changes

2022-09-06 18:40 UTC, dcpena commented on content/magic-firewall/about/ruleset-logic.md
> +Managed Phase rulesets are updated and maintained by Cloudflare, and Cloudflare creates these rules based on best practices, known malicious patterns, and other criteria.
Fixed! Thanks for calling that out

2022-09-06 18:43 UTC, merged