[Workers][WIP] Document wrangler's new unstable_dev API
cloudflare/cloudflare-docs pull request #5739
Opened 2022-09-05 11:28 UTC by rozenmd

[WIP]

Closes #5721

2022-09-05 15:24 UTC, petebacondarwin commented on content/workers/wrangler/api.md
> +Wrangler offers an API to programmatically manage your Cloudflare Workers
```suggestion
Wrangler offers an experimental API to programmatically manage your Cloudflare Workers
```

2022-09-05 15:24 UTC, petebacondarwin commented on content/workers/wrangler/api.md
> +    *   Optional API options object containing `disableExperimentalWarning`. Set `disableExperimentalWarning` to true to disable wrangler's warning about using `unstable_` prefixed APIs.
And `testMode`?

2022-09-05 15:24 UTC, petebacondarwin commented on content/workers/wrangler/api.md
> +### Usage
Can we have a little preamble to the usage, that explains about how and when you need to call `worker.stop()`

2022-09-05 15:24 UTC, petebacondarwin commented on content/workers/wrangler/api.md
> +Start a local server for testing your Worker.
Could you expand a bit to explain that this literally starts an HTTP server but that you can use the `worker.fetch()` method to interact with the server without having to know about the ports, etc.

2022-09-05 15:24 UTC, petebacondarwin commented on content/workers/wrangler/api.md
> +
Can we have a section describing the return type and its methods?

2022-09-07 16:07 UTC, rozenmd commented on content/workers/wrangler/api.md
> +    *   Optional API options object containing `disableExperimentalWarning`. Set `disableExperimentalWarning` to true to disable wrangler's warning about using `unstable_` prefixed APIs.
Intentionally not documenting `testMode`, tbh it's there because we let Pages use unstable_dev before we had time to finish building it for tests

2022-09-07 16:11 UTC, petebacondarwin commented on content/workers/wrangler/api.md
> +    *   Optional API options object containing `disableExperimentalWarning`. Set `disableExperimentalWarning` to true to disable wrangler's warning about using `unstable_` prefixed APIs.
👍

2022-09-12 17:31 UTC, deadlypants1973 requested changes

2022-09-12 17:31 UTC, deadlypants1973 commented on content/workers/wrangler/api.md
> +Wrangler offers an experimental API to programmatically manage your Cloudflare Workers
```suggestion
Wrangler offers an experimental API to programmatically manage your Cloudflare Workers.
```

2022-09-12 17:31 UTC, deadlypants1973 commented on content/workers/wrangler/api.md
> +Once called, `unstable_dev` will return a `fetch` function for invoking your Worker without needing to know the address or port, as well as a `stop` function to shut-down the HTTP server.
```suggestion
Once called, `unstable_dev` will return a `fetch` function for invoking your Worker without needing to know the address or port, as well as a `stop` function to shut down the HTTP server.
```

2022-09-12 17:31 UTC, deadlypants1973 commented on content/workers/wrangler/api.md
> +There are no known bugs at the moment and it is safe to use. If you discover any bugs, please open a [GitHub Issue](https://github.com/cloudflare/wrangler2/issues/new/choose) and we'll fix them as so
```suggestion
There are no known bugs at the moment and it is safe to use. If you discover any bugs, please open a [GitHub Issue](https://github.com/cloudflare/wrangler2/issues/new/choose) and we will review the issue.
```

2022-09-12 17:31 UTC, deadlypants1973 commented on content/workers/wrangler/api.md
> +    *   Optional API options object containing `disableExperimentalWarning`. Set `disableExperimentalWarning` to true to disable wrangler's warning about using `unstable_` prefixed APIs.
```suggestion
    *   Optional API options object containing `disableExperimentalWarning`. Set `disableExperimentalWarning` to true to disable Wrangler's warning about using `unstable_` prefixed APIs.
```

2022-09-12 17:31 UTC, deadlypants1973 commented on content/workers/wrangler/api.md
> +    *   Send a request to your worker. Returns a promise that resolves with a [`Response`](/workers/runtime-apis/response) object.
```suggestion
    *   Send a request to your Worker. Returns a Promise that resolves with a [`Response`](/workers/runtime-apis/response) object.
```

2022-09-12 17:31 UTC, deadlypants1973 commented on content/workers/wrangler/api.md
> +Typically, you'll want to start each test suite with a `beforeAll` function that starts `unstable_dev`. We use the `beforeAll` function because starting the dev server takes a few hundred millisecond
```suggestion
When initiating each test suite, a `beforeAll` function starts `unstable_dev`. The `beforeAll` function is used to address latency. Starting the dev server takes a few hundred milliseconds, starting and stopping for each individual test adds up quickly, slowing your tests down.
```

2022-09-12 17:31 UTC, deadlypants1973 commented on content/workers/wrangler/api.md
> +In each test case you'll call `await worker.fetch`, and check that the response is what you expect.
```suggestion
In each test case, call `await worker.fetch`, and check that the response is what you expect. 
```

2022-09-12 17:31 UTC, deadlypants1973 commented on content/workers/wrangler/api.md
> +To wrap up a test suite, you should call `await worker.stop` in an `afterAll` function.
```suggestion
To wrap up a test suite, call `await worker.stop` in an `afterAll` function.
```

2022-09-12 17:32 UTC, deadlypants1973 reviewed
PCX technical review

2022-09-12 20:13 UTC, rozenmd commented on content/workers/wrangler/api.md
> +Typically, you'll want to start each test suite with a `beforeAll` function that starts `unstable_dev`. We use the `beforeAll` function because starting the dev server takes a few hundred millisecond
```suggestion
When initiating each test suite, a `beforeAll` function starts `unstable_dev`. The `beforeAll` function is used to minimize overhead: starting the dev server takes a few hundred milliseconds, starting and stopping for each individual test adds up quickly, slowing your tests down.
```
Maybe more like this @deadlypants1973 ?

2022-09-12 21:59 UTC, petebacondarwin requested changes

2022-09-12 21:59 UTC, petebacondarwin commented on content/workers/wrangler/api.md
> +    *   A string containing a path to your Worker script.
A path relative to what? I think the current working directory?

2022-09-12 21:59 UTC, petebacondarwin commented on content/workers/wrangler/api.md
> +Typically, you'll want to start each test suite with a `beforeAll` function that starts `unstable_dev`. We use the `beforeAll` function because starting the dev server takes a few hundred millisecond
How about?

```suggestion
When initiating each test suite, use a `beforeAll` function to start `unstable_dev`. The `beforeAll` function is used to minimize overhead: starting the dev server takes a few hundred milliseconds, starting and stopping for each individual test adds up quickly, slowing your tests down.
```

2022-09-12 21:59 UTC, petebacondarwin commented on content/workers/wrangler/api.md
> +*   `fetch` {{<type>}}Promise\<Response>{{</type>}}
Generally I believe that when referring to functions we should include parentheses.

```suggestion
*   `fetch()` {{<type>}}Promise\<Response>{{</type>}}
```

Similarly throughout.

2022-09-12 21:59 UTC, petebacondarwin commented on content/workers/wrangler/api.md
> +`unstable_dev` returns an object containing the following functions:
Should functions that are contained in an object be referred to as methods?

2022-09-12 21:59 UTC, petebacondarwin commented on content/workers/wrangler/api.md
> +*   `fetch` {{<type>}}Promise\<Response>{{</type>}}
Moreover, could we describe what parameters this function accepts? Especially since we are saying that it is different to a normal `fetch()` (e.g. doesn't need to know the URL and port).

2022-09-12 21:59 UTC, petebacondarwin commented on content/workers/wrangler/api.md
> +In each test case, call `await worker.fetch`, and check that the response is what you expect.
```suggestion
In each test case, call `await worker.fetch()`, and check that the response is what you expect. 
```

2022-09-12 21:59 UTC, petebacondarwin commented on content/workers/wrangler/api.md
> +To wrap up a test suite, call `await worker.stop` in an `afterAll` function.
```suggestion
To wrap up a test suite, call `await worker.stop()` in an `afterAll` function.
```

(you get the idea)

2022-09-12 21:59 UTC, petebacondarwin commented on content/workers/wrangler/api.md
> +{{<tab label="js" default="true">}}
Should we not be encouraging people to use TS by making it the default?

2022-09-13 07:46 UTC, rozenmd commented on content/workers/wrangler/api.md
> +    *   A string containing a path to your Worker script.
Relative to your package.json, I think - not sure how to express that idea

2022-09-13 07:54 UTC, rozenmd commented
@petebacondarwin - looks like the order of the tabs has to be JS -> TS, otherwise the component breaks 😬

2022-09-13 08:31 UTC, petebacondarwin commented on content/workers/wrangler/api.md
> +{{<tab label="js" default="true">}}
Can we leave the order in place but just change the default?

2022-09-13 09:49 UTC, rozenmd commented on content/workers/wrangler/api.md
> +{{<tab label="js" default="true">}}
Apparently not, no @petebacondarwin:
<img width="738" alt="image" src="https://user-images.githubusercontent.com/3822106/189870351-fbb57e17-71b0-4b3a-b2a1-6dd8467d3ed2.png">

2022-09-13 09:55 UTC, rozenmd commented on content/workers/wrangler/api.md
> +Once called, `unstable_dev` will return a `fetch` function for invoking your Worker without needing to know the address or port, as well as a `stop` function to shut down the HTTP server.
```suggestion
Once called, `unstable_dev` will return a `fetch()` function for invoking your Worker without needing to know the address or port, as well as a `stop()` function to shut down the HTTP server.
```

2022-09-13 09:55 UTC, rozenmd commented on content/workers/wrangler/api.md
> +When initiating each test suite, use a `beforeAll` function to start `unstable_dev`. The `beforeAll` function is used to minimize overhead: starting the dev server takes a few hundred milliseconds, s
```suggestion
When initiating each test suite, use a `beforeAll()` function to start `unstable_dev`. The `beforeAll` function is used to minimize overhead: starting the dev server takes a few hundred milliseconds, starting and stopping for each individual test adds up quickly, slowing your tests down.
```

2022-09-13 09:56 UTC, rozenmd commented on content/workers/wrangler/api.md
> +The `unstable_dev` function has an `unstable_` prefix because the API may change in the future.
```suggestion
The `unstable_dev()` function has an `unstable_` prefix because the API may change in the future. 
```

2022-09-13 14:05 UTC, deadlypants1973 approved these changes

2022-09-14 08:24 UTC, rozenmd commented on content/workers/wrangler/api.md
> +import { unstable_dev } from 'wrangler'
```suggestion
const { unstable_dev } = require("wrangler");
```

2022-09-14 08:26 UTC, rozenmd commented on content/workers/wrangler/api.md
> +    *   A string containing a path to your Worker script.
```suggestion
    *   A string containing a path to your Worker script, relative to your Worker project's root directory.
```

2022-09-14 09:23 UTC, petebacondarwin approved these changes

2022-09-14 09:24 UTC, merged