[Cache] Added section about purge by prefix normalization
cloudflare/cloudflare-docs pull request #5767
Opened 2022-09-07 17:52 UTC by angelampcosta

2022-09-08 10:41 UTC, marciocloudflare requested changes

2022-09-08 10:41 UTC, marciocloudflare commented on content/cache/how-to/purge-cache.md
> +Currently, when a purge by prefix request comes into Cloudflare for a normalized URL path, the purge service does not respect the [URL normalization](https://developers.cloudflare.com/rules/normaliza
```suggestion
Currently, when a purge by prefix request comes into Cloudflare for a normalized URL path, the purge service does not respect the [URL normalization](/rules/normalization/). Cloudflare is changing the purge by prefix functionality so that normalized URLs will be purged as expected. We plan for this change to occur on <needs to be added>.
```

2022-09-08 10:41 UTC, marciocloudflare commented on content/cache/how-to/purge-cache.md
> +As an example of this behavior change, take the following website as an example: `https://cloudflare.com/انشاء-موقع-الكتروني/img_1.jpg`. The table below shows you how Cloudflare’s cache views these p
```suggestion
As an example of this behavior change, take the following website as an example: `https://cloudflare.com/انشاء-موقع-الكتروني/img_1.jpg`. The table below shows you how Cloudflare’s cache views these paths with [normalization on/off](/rules/normalization/).
```

2022-09-08 10:41 UTC, marciocloudflare commented on content/cache/how-to/purge-cache.md
> +        <code>https://cloudflare.com/hello/img_1.jpg</code>
These all seem to be the same links. Are these all supposed to be here?

2022-09-08 10:41 UTC, marciocloudflare commented on content/cache/how-to/purge-cache.md
> +This means that if the prefix being purged does not match what Cloudflare’s cache sees, regardless of how the URL looked when it hit the edge, purge by prefix will not work. Specifically:
```suggestion
This means that if the prefix being purged does not match what Cloudflare’s cache sees  purge by prefix will not work, regardless of how the URL looked when it hit the edge. Specifically:
```

2022-09-08 10:41 UTC, marciocloudflare commented on content/cache/how-to/purge-cache.md
> +- Currently, if a visitor request was for `https://cloudflare.com/انشاء-موقع-الكتروني/img_1.jpg` and URL normalization is ON, then currently purge by prefix will not be able to purge this asset since
```suggestion
- Currently, if a visitor request was for `https://cloudflare.com/انشاء-موقع-الكتروني/img_1.jpg` and URL normalization is **ON**, then currently purge by prefix will not be able to purge this asset since it will be cached as if `https://cloudflare.com/%D8%A7%D9%86%D8%B4%D8%A7%D8%A1-%D9%85%D9%88%D9%82%D8%B9-%D8%A7%D9%84%D9%83%D8%AA%D8%B1%D9%88%D9%86%D9%8A/img_1.jpg` was requested and, similarly to the first point, we can not purge this with the current behaviour. If, on the other hand, URL normalization is **OFF**, then purging by prefix `cloudflare.com/انشاء-موقع-الكتروني/` will purge `https://cloudflare.com/انشاء-موقع-الكتروني/img_1.jpg`.
```

2022-09-08 10:41 UTC, marciocloudflare commented on content/cache/how-to/purge-cache.md
> +  With the new behavior, in order to purge by prefix the asset that was cached by the visitor request `https://cloudflare.com/انشاء-موقع-الكتروني/img_1.jpg`, you can purge by prefix `cloudflare.com/ا
Not entirely sure what this sentence means, but I understood correctly I think it would be easier to read by adding `()` to that first URL: 
```
With the new behavior, in order to purge by prefix the asset that was cached by the visitor request (`https://cloudflare.com/انشاء-موقع-الكتروني/img_1.jpg`), you can purge by prefix `cloudflare.com/انشاء-موقع-الكتروني/`.
```

2022-09-08 10:42 UTC, marciocloudflare commented on content/cache/how-to/purge-cache.md
> +Currently, when a purge by prefix request comes into Cloudflare for a normalized URL path, the purge service does not respect the [URL normalization](https://developers.cloudflare.com/rules/normaliza
This is missing a date in We plan for this change to occur on <needs to be added>.

2022-09-08 10:43 UTC, pedrosousa commented on content/cache/how-to/purge-cache.md
> +        <code>https://cloudflare.com/%D8%A7%D9%86%D8%B4%D8%A7%D8%A1-%D9%85%D9%88%D9%82%D8%B9-%D8%A7%D9%84%D9%83%D8%AA%D8%B1%D9%88%D9%86%D9%8A/img_1.jp</code>
```suggestion
        <code>https://cloudflare.com/%D8%A7%D9%86%D8%B4%D8%A7%D8%A1-%D9%85%D9%88%D9%82%D8%B9-%D8%A7%D9%84%D9%83%D8%AA%D8%B1%D9%88%D9%86%D9%8A/img_1.jpg</code>
```

2022-09-20 09:26 UTC, marciocloudflare approved these changes

2022-09-20 09:27 UTC, merged