New guide: added guide for honojs based site
cloudflare/cloudflare-docs pull request #5798
Opened 2022-09-10 06:18 UTC by rishavs

Added a guide to deploy Honojs sites
https://honojs.dev/

2022-09-10 12:28 UTC, WalshyDev reviewed
Thank you for the PR 🙂 

Left some initial comments

2022-09-10 12:28 UTC, WalshyDev commented on content/pages/framework-guides/deploy-a-honojs-site.md
> +$ npm i --save-dev wrangler hono esbuild npm-run-all
```suggestion

# Make sure Hono is installed
$ npm install hono

# Install the required dependencies. 
# ESBuild is needed to bundle the hono app code
# npm-run-all enables us to run multiple npm commands at once 
$ npm install --save-dev wrangler esbuild npm-run-all 
```

2022-09-10 12:28 UTC, WalshyDev commented on content/pages/framework-guides/deploy-a-honojs-site.md
> +[Hono](https://honojs.dev/) - [炎] means flame🔥 in Japanese - is a small, simple, and ultrafast web framework for Cloudflare Workers, Deno, Bun, and others. Fast, but not only fast.  In this guide, yo
```suggestion
[Hono](https://honojs.dev/) - [炎] means flame🔥 in Japanese - is a small, simple, and ultrafast web framework for Cloudflare Pages/Workers, Deno, Bun, and others. Fast, but not only fast.  In this guide, you will create a new Honojs application and deploy it using Cloudflare Pages.
```

2022-09-10 12:28 UTC, WalshyDev commented on content/pages/framework-guides/deploy-a-honojs-site.md
> +```
Don't think we need this part 
```suggestion
```

2022-09-10 12:28 UTC, WalshyDev commented on content/pages/framework-guides/deploy-a-honojs-site.md
> +import { Hono } from 'hono'
@deadlypants1973 do we have any style guides on code formatting? I feel like it's currently a bit all over

If not, can we work on one?

2022-09-10 12:28 UTC, WalshyDev commented on content/pages/framework-guides/deploy-a-honojs-site.md
> +app.get('/', (c) => c.text('Hello world, this is Hono!!'))
Can Hono serve static assets? If so, can we have an example?

I'd also like to add a fallback that falls through to our ASSETS.fetch

2022-09-11 07:25 UTC, rishavs commented on content/pages/framework-guides/deploy-a-honojs-site.md
> +```
Have made the change directly to the code. Marking as resolved.

2022-09-11 07:27 UTC, rishavs commented on content/pages/framework-guides/deploy-a-honojs-site.md
> +app.get('/', (c) => c.text('Hello world, this is Hono!!'))
Added the lines in the code.

2022-09-11 07:27 UTC, rishavs commented on content/pages/framework-guides/deploy-a-honojs-site.md
> +import { Hono } from 'hono'
Anything actionable for me?

2022-10-13 16:30 UTC, deadlypants1973 requested changes

2022-10-13 16:30 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-honojs-site.md
> +[Hono](https://honojs.dev/) - [炎] means flame🔥 in Japanese - is a small, simple, and ultrafast web framework for Cloudflare Pages/Workers, Deno, Bun, and others. Fast, but not only fast.  In this gui
```suggestion
[Hono](https://honojs.dev/) is a small, simple, and ultrafast web framework for Cloudflare Pages and Workers, Deno, and Bun. In this guide, you will create a new Honojs application and deploy it using Cloudflare Pages.
```

2022-10-13 16:30 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-honojs-site.md
> +## Creating a new project
```suggestion
## Create a new project
```

2022-10-13 16:30 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-honojs-site.md
> +Now open the project in your code editor of choice.
```suggestion
Open the project in your code editor of choice.
```

2022-10-13 16:30 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-honojs-site.md
> +This will cause all the files in the `pub` folder within `dist` to be served in your app.
```suggestion

This will cause all the files in the `pub` folder within `dist` to be served in your application.
```

2022-10-13 16:30 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-honojs-site.md
> +Start your dev workflow using
```suggestion
Start your dev workflow by running:
```

2022-10-13 16:30 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-honojs-site.md
> +You should be able to see the generated web app in http://localhost:8788
```suggestion
You should be able to review your generated web application at `http://localhost:8788`.
```

2022-10-13 16:30 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-honojs-site.md
> +## Creating a GitHub repository
```suggestion
## Create a GitHub repository
```

2022-10-13 16:30 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-honojs-site.md
> +## Deploying with Cloudflare Pages
```suggestion
## Deploy with Cloudflare Pages
```

2022-10-13 16:30 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-honojs-site.md
> +Here `npm-run-all` enables us to use a single command `npm run dev` to run `npm run dev:wrangler` and `npm run dev:esbuild` together simultaneously in watch mode.
```suggestion
Here `npm-run-all` enables you to use a single command `npm run dev` to run `npm run dev:wrangler` and `npm run dev:esbuild` together simultaneously in watch mode.
```

2022-10-13 16:30 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-honojs-site.md
> +Now, open your `package.json` file and update the `scripts` section.
```suggestion
Open your `package.json` file and update the `scripts` section:
```

2022-10-13 16:30 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-honojs-site.md
> +In the project, add a `src/server.js` file.
```suggestion
In your project, create a `src/server.js` file.
```

2022-10-13 16:30 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-honojs-site.md
> +# Install the required dependencies.
```suggestion
# Install the required dependencies
```

2022-10-13 16:33 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-honojs-site.md
> +Add the following content to the file.
```suggestion
Open your project and create a `src/server.js` file. Add the following content to your file:
```

2022-10-13 16:33 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-honojs-site.md
> +## Running in local
```suggestion
## Run in local dev
```

2022-10-13 16:35 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-honojs-site.md
> +If you want to serve any static files like css, image or js files, you will need to add this bit code
```suggestion
If you want to serve static files like CSS, image or JavaScript files, you will need to add the following to your `src/server.js` file:
```

2022-10-13 16:40 UTC, WalshyDev commented on content/pages/framework-guides/deploy-a-honojs-site.md
> +    return await c.env.ASSETS.fetch(c.req)
```suggestion
app.get('/public/*', async (ctx) => {
    return await ctx.env.ASSETS.fetch(ctx.req)
```

2022-10-13 16:40 UTC, WalshyDev commented on content/pages/framework-guides/deploy-a-honojs-site.md
> +This will cause all the files in the `pub` folder within `dist` to be served in your app.
```suggestion

This will cause all the files in the `public` folder within `dist` to be served in your application.
```

2022-10-13 16:40 UTC, WalshyDev commented on content/pages/framework-guides/deploy-a-honojs-site.md
> +app.get('/', (c) => c.text('Hello world, this is Hono!!'))
```suggestion
app.get('/', (ctx) => ctx.text('Hello world, this is Hono!!'))
```

2022-10-14 13:40 UTC, deadlypants1973 approved these changes

2022-10-14 13:50 UTC, merged