[Docs Site] Tab Switcher fixes
cloudflare/cloudflare-docs pull request #5867
Opened 2022-09-16 00:35 UTC by KianNH

This PR fixes several bugs:

1) A JavaScript Service Worker has two labels, one being `js-sw`

![image](https://user-images.githubusercontent.com/94662631/190531204-5f2a259c-f9bd-454b-b968-9da03dbe4213.png)

This is due to the un-necessary `end` conditional in `tabs.html`.

```html
{{ end }} {{ if or (eq $link "js-esm") }}
```

2) `js` and `js-sw` have `tab-label active` by default, even if not active or defaulted.

![image](https://user-images.githubusercontent.com/94662631/190531465-3f4da83f-ad95-4454-91c8-d92a88d4a372.png)

```html
{{ if or (eq $link "js") }}
<a class="tab-label active" href="#" data-link="tab-{{$link}}" data-id="{{$unique_id}}">
        
{{ else if (eq $link "js-sw") }}
<a class="tab-label active" href="#" data-link="tab-{{$link}}" data-id="{{$unique_id}}">
```

3) Defaults other than the first tab do not render correctly.

![image](https://user-images.githubusercontent.com/94662631/190531514-c8a7f9d2-0120-46ab-92da-cce79a921aef.png)

This is because the current code will always set the first tab to display as well as set the default to display.

```js
// Set the first tab in a group to display
(tabs[0] as HTMLElement).style.display = "block";
```

4) The actively selected tab is not highlighted.

![image](https://user-images.githubusercontent.com/94662631/190531766-2274221a-3138-4698-ab5b-ededbcdb2adc.png)

This is because there is nothing to set this as `active` - this includes both the default tab and when selecting a tab.

5) Aria labels

The `role` aria label is meant for the `path` element so moved it to the appropriate place, as well as given it the `graphics-symbol` appropriate for logos.

2022-09-16 00:37 UTC, KianNH commented on assets/events.ts
> +          const tabId = defaultTab.id.split("-").slice(0, 3).join("-");
I'll admit - I only ever write Workers, nothing to do with the DOM. Is there nicer ways to do this?

2022-09-16 00:37 UTC, KianNH commented on assets/events.ts
> +          labels.forEach((label) => {
As an alternative, I also had `const defaultTabLabel = wrappers[i].querySelector(`a[data-link=${tabId}]`);` working if that's a better solution.

2022-09-16 00:37 UTC, KianNH commented on assets/events.ts
> +          (labels[0] as HTMLElement).classList.add("active");
`(labels[0] as HTMLElement).classList.add("active");` is new and means that if there is no default, the first tab label will be shown as active.

2022-09-16 00:48 UTC, KianNH commented
cc @Ekwuno @WalshyDev

2022-09-20 14:03 UTC, rozenmd requested changes
One small tweak for readability

2022-09-20 14:03 UTC, rozenmd commented on assets/events.ts
> +          const tabId = defaultTab.id.split("-").slice(0, 3).join("-");
There are other ways to do this, but the comment explaining it does the job tbh

2022-09-20 14:03 UTC, rozenmd commented on assets/events.ts
> +              if (labelId === tabId) { defaultTabLabel = label; found = true }
```suggestion
              if (labelId === tabId) { 
                defaultTabLabel = label; 
                found = true;
               }
```

2022-09-20 14:07 UTC, rozenmd approved these changes
LGTM 👍

2022-09-20 14:14 UTC, KianNH commented on assets/events.ts
> +          const tabId = defaultTab.id.split("-").slice(0, 3).join("-");
I've just realised whilst testing it on the `unstable_dev` API page that it doesn't work with `tab-js`/`tab-es` since it's assuming it'll be `tab-js-esm`/etc

2022-09-20 14:22 UTC, KianNH commented on assets/events.ts
> +          const tabId = defaultTab.id.split("-").slice(0, 3).join("-");
```js
// split by - and get the length of the array
let parts = defaultTab.id.split("-").length;
// if there is 3, the id is tab-js-id
// otherwise the id is tab-js-esm-id
const end = parts = 3 ? 2 : 3
// changes an id (i.e tab-js-esm-6f3904f86f90c21d) into just the type (tab-js-esm)
const tabId = defaultTab.id.split("-").slice(0, end).join("-")
```

This _works_ but I don't like it.

2022-09-20 14:24 UTC, KianNH commented on assets/events.ts
> +          const tabId = defaultTab.id.split("-").slice(0, 3).join("-");
```js
const tabId = defaultTab.id.split("-").slice(0, parts - 1).join("-")
```

Of course I can just do this. Rubber ducky always works.

2022-09-20 16:00 UTC, WalshyDev commented on assets/events.ts
> +            }
no need for an inner if
```suggestion
            if (!found && labelId === tabId) {
              defaultTabLabel = label; 
              found = true;
            }
```

2022-09-20 16:00 UTC, WalshyDev commented on assets/events.ts
> +          labels.forEach((label) => {
yeah I was surprised you didn't do this. I'd prefer this

2022-09-20 16:00 UTC, WalshyDev commented on layouts/shortcodes/tabs.html
> -            xmlns="http://www.w3.org/2000/svg" data-link="tab-{{$link}}" role="presentation">
noob with a11y but why did the role move from the svg to the path?

2022-09-20 16:10 UTC, KianNH commented on layouts/shortcodes/tabs.html
> -            xmlns="http://www.w3.org/2000/svg" data-link="tab-{{$link}}" role="presentation">
The current `role="presentation"` isn't valid for `svg` iirc & the proper role, `graphics-symbol`, is only accepted on the `path` since that's the actual image.

Before:
<img width="137" alt="image" src="https://user-images.githubusercontent.com/94662631/191309647-c0a45dbe-d181-4d81-ae2e-c2ad74f41a54.png">

After:
<img width="123" alt="image" src="https://user-images.githubusercontent.com/94662631/191309687-c0110fd2-07f8-4fda-9791-44e35dad70e3.png">

2022-09-20 16:15 UTC, WalshyDev commented on layouts/shortcodes/tabs.html
> -            xmlns="http://www.w3.org/2000/svg" data-link="tab-{{$link}}" role="presentation">
interesting, it was James who said to add that. Sounds good :)

2022-09-20 16:17 UTC, KianNH commented on layouts/shortcodes/tabs.html
> -            xmlns="http://www.w3.org/2000/svg" data-link="tab-{{$link}}" role="presentation">
`role="img"` seems happy - just not `presentation`

<img width="293" alt="image" src="https://user-images.githubusercontent.com/94662631/191311174-4a18be4f-3e89-437e-aa5e-1eaac22c3fd3.png">

<img width="121" alt="image" src="https://user-images.githubusercontent.com/94662631/191311203-d55583d3-8c66-45bd-90b5-c70ed8b313ab.png">

2022-09-20 16:23 UTC, Cherry commented on layouts/shortcodes/tabs.html
> -            xmlns="http://www.w3.org/2000/svg" data-link="tab-{{$link}}" role="presentation">
The reason I suggested this was so a screen-reader didn't read the SVG title, and then the human-written too, so you don't get "JavaScript JavaScript" read out with both the `title` in the SVG and the text outside.

Seems like `aria-hidden=true` would be better solution though - the SVG provides no semantic meaning here (does it?) so simply hiding it would be ideal: https://www.unimelb.edu.au/accessibility/techniques/accessible-svgs

2022-09-20 16:25 UTC, KianNH commented on layouts/shortcodes/tabs.html
> -            xmlns="http://www.w3.org/2000/svg" data-link="tab-{{$link}}" role="presentation">
> Assigning role="[presentation](https://www.w3.org/TR/wai-aria-1.0/roles#presentation)" should be avoided, because it doesn't hide the SVG. It just cancels the native role.

That'll be why WebStorm got upset at me then

> In order to hide an SVG, it is best to give it an attribute of aria-hidden='"true". This functions in a similar way to display:none in CSS.

Are there any good extensions/DevTools to test stuff like this? Safari has an accessibility audit but it seems to be more critical stuff.

2022-09-20 16:34 UTC, KianNH commented on layouts/shortcodes/tabs.html
> -            xmlns="http://www.w3.org/2000/svg" data-link="tab-{{$link}}" role="presentation">
It doesn't look like we actually have any title/content in the `svg` for a screen reader to use - we have `JavaScript` as the content for the `a` element.

`a`
<img width="231" alt="image" src="https://user-images.githubusercontent.com/94662631/191314463-32936cf7-614f-44d4-b0a8-1478158c1b58.png">

`svg`
<img width="223" alt="image" src="https://user-images.githubusercontent.com/94662631/191314509-4b7f8e49-2f7e-403c-b2d8-ef11a8a8c650.png">

2022-09-20 16:35 UTC, Cherry commented on layouts/shortcodes/tabs.html
> -            xmlns="http://www.w3.org/2000/svg" data-link="tab-{{$link}}" role="presentation">
> It doesn't look like we actually have any title/content in the `svg` for a screen reader to use - we have `JavaScript` as the content for the `a` element.
> 
> `a` <img alt="image" width="231" src="https://user-images.githubusercontent.com/94662631/191314463-32936cf7-614f-44d4-b0a8-1478158c1b58.png">
> 
> `svg` <img alt="image" width="223" src="https://user-images.githubusercontent.com/94662631/191314509-4b7f8e49-2f7e-403c-b2d8-ef11a8a8c650.png">

Sweet, this can probably just be removed then. There was a time there was a `<title>` element in the SVG, but seems that's no longer the case.

2022-10-04 04:06 UTC, WalshyDev approved these changes

2022-10-04 04:07 UTC, WalshyDev commented
Appreciate it @KianNH 👍 

Tested this out and it's good to

2022-10-04 04:07 UTC, merged