[Wrangler] Add information about wrangler login to a remote machine
cloudflare/cloudflare-docs pull request #5981
Opened 2022-09-26 10:01 UTC by cameron-robey

Having had people ask for support multiple times (https://github.com/cloudflare/wrangler2/issues/884, https://github.com/cloudflare/wrangler2/issues/1885) with using wrangler on a remote server, it is best we add some documentation about a work around.

2022-09-27 14:54 UTC, rozenmd commented on content/workers/wrangler/get-started.md
> +### Using `wrangler login` in a remote machine
```suggestion
### Using `wrangler login` on a remote machine
```

2022-09-27 14:55 UTC, JacobMGEvans approved these changes

2022-09-27 14:58 UTC, rozenmd requested changes
doing a review

2022-09-27 15:00 UTC, rozenmd commented on content/workers/wrangler/get-started.md
> +If you are using wrangler from a remote machine but run the login flow from your local browser, you will get an error after logging in that `This site can't be reached`. To finish the login flow, you
```suggestion
If you are using wrangler from a remote machine, but run the login flow from your local browser, after logging in you will see the following error message: `This site can't be reached`. 

To finish the login flow, you can use `curl` or an equivalent request library on the remote machine to fetch this `localhost` url.
```

2022-09-27 15:01 UTC, rozenmd commented on content/workers/wrangler/get-started.md
> +In a second terminal session:
```suggestion
In a second terminal session, run:
```

2022-09-27 15:02 UTC, rozenmd commented on content/workers/wrangler/get-started.md
> +```
```suggestion
```sh
```

2022-09-27 15:05 UTC, JacobMGEvans commented on content/workers/wrangler/get-started.md
> +### Using `wrangler login` in a remote machine
Aren't these grammatically equivalent in this instance?

2022-09-27 15:06 UTC, JacobMGEvans commented on content/workers/wrangler/get-started.md
> +If you are using wrangler from a remote machine but run the login flow from your local browser, you will get an error after logging in that `This site can't be reached`. To finish the login flow, you
This makes sense and is more concise.

2022-09-27 15:09 UTC, rozenmd commented on content/workers/wrangler/get-started.md
> +### Using `wrangler login` in a remote machine
You'll typically find `on a server/computer` to be the more common usage, `in a server/computer/remote machine` implies being physically inside it with the RAM/CPU

2022-09-27 15:20 UTC, cameron-robey commented on content/workers/wrangler/get-started.md
> +### Using `wrangler login` in a remote machine
https://github.com/cloudflare/cloudflare-docs/pull/5981/commits/76cacc2478f9d91726aa2579d6b5aef32fd9d6a8

2022-09-27 15:21 UTC, cameron-robey commented on content/workers/wrangler/get-started.md
> +If you are using wrangler from a remote machine but run the login flow from your local browser, you will get an error after logging in that `This site can't be reached`. To finish the login flow, you
https://github.com/cloudflare/cloudflare-docs/pull/5981/commits/76cacc2478f9d91726aa2579d6b5aef32fd9d6a8

2022-09-27 15:21 UTC, cameron-robey commented on content/workers/wrangler/get-started.md
> +```
https://github.com/cloudflare/cloudflare-docs/pull/5981/commits/76cacc2478f9d91726aa2579d6b5aef32fd9d6a8

2022-09-27 15:21 UTC, cameron-robey commented on content/workers/wrangler/get-started.md
> +In a second terminal session:
https://github.com/cloudflare/cloudflare-docs/pull/5981/commits/76cacc2478f9d91726aa2579d6b5aef32fd9d6a8

2022-09-27 15:26 UTC, deadlypants1973 requested changes

2022-09-27 15:26 UTC, deadlypants1973 commented on content/workers/wrangler/get-started.md
> +### Using `wrangler login` on a remote machine
```suggestion
### Use `wrangler login` on a remote machine
```

2022-09-27 15:26 UTC, deadlypants1973 commented on content/workers/wrangler/get-started.md
> +If you are using wrangler from a remote machine, but run the login flow from your local browser, after logging in you will see the following error message: `This site can't be reached`.
```suggestion
If you are using Wrangler from a remote machine, but run the login flow from your local browser, you will receive the following error message after logging in:`This site can't be reached`.
```

2022-09-27 15:26 UTC, deadlypants1973 commented on content/workers/wrangler/get-started.md
> +To finish the login flow, you can use `curl` or an equivalent request library on the remote machine to fetch this `localhost` url.
```suggestion
To finish the login flow, you can use `curl` or an equivalent request library on the remote machine to fetch this `localhost` URL.
```

2022-09-28 09:11 UTC, deadlypants1973 commented on content/workers/wrangler/get-started.md
> +To finish the login flow, you can use `curl` or an equivalent request library on the remote machine to fetch this `localhost` URL.
```suggestion
To finish the login flow, run `wrangler login` and go through the login flow in the browser:
```

2022-09-28 09:11 UTC, deadlypants1973 commented on content/workers/wrangler/get-started.md
> +In a second terminal session, run:
```suggestion
Leave the login flow active. Open a second terminal session. In that second terminal session, use `curl` or an equivalent request library on the remote machine to fetch this `localhost` URL:
```

2022-09-28 09:11 UTC, deadlypants1973 approved these changes
PCX review

2022-09-28 09:54 UTC, deadlypants1973 approved these changes

2022-09-28 09:54 UTC, deadlypants1973 commented on content/workers/wrangler/get-started.md
> +Leave the login flow active. Open a second terminal session. In that second terminal session, use `curl` or an equivalent request library on the remote machine to fetch this `localhost` URL:
```suggestion
The browser login flow will redirect you to a `localhost` URL on your machine.

Leave the login flow active. Open a second terminal session. In that second terminal session, use `curl` or an equivalent request library on the remote machine to fetch this `localhost` URL. Copy and paste the `localhost` URL that was generated during the `wrangler login` flow and run:
```

2022-09-28 09:54 UTC, deadlypants1973 commented on content/workers/wrangler/get-started.md
> +$ curl http://localhost:8976/oauth/callback?code=xyz...
```suggestion
$ curl <LOCALHOST_URL>
```

2022-09-28 10:00 UTC, rozenmd approved these changes
🚢

2022-09-28 10:01 UTC, merged