Add Pages Early Hints docs
cloudflare/cloudflare-docs pull request #5989
Opened 2022-09-26 16:46 UTC by GregBrimble

https://early-hints.cloudflare-docs-7ou.pages.dev/pages/platform/early-hints/

2022-09-27 10:23 UTC, deadlypants1973 requested changes

2022-09-27 10:23 UTC, deadlypants1973 commented on content/pages/platform/early-hints.md
> +[Early Hints](https://developers.cloudflare.com/cache/about/early-hints/) is enabled automatically on all `pages.dev` domains. [It can be enabled for your any custom domains](https://developers.cloud
```suggestion
[Early Hints](https://developers.cloudflare.com/cache/about/early-hints/) help the browser to load webpages faster. Early Hints is enabled automatically on all `pages.dev` domains. It can be [enabled](https://developers.cloudflare.com/cache/about/early-hints/#enabling-early-hints) for your custom domains by logging into the [Cloudflare dashboard](https://dash.cloudflare.com) > selecting your account and domain > **Speed** > **Optimization** and turning on the **Early Hints** toggle.
```

2022-09-27 10:23 UTC, deadlypants1973 commented on content/pages/platform/early-hints.md
> +Early Hints automatically caches any [`preload`](https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types/preload) and [`preconnect`](https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types/
```suggestion
Early Hints automatically caches any [`preload`](https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types/preload) and [`preconnect`](https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types/preconnect) type [`Link` headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Link) to send as Early Hints to the browser. The hints are sent to the browser before the full response is prepared, and the browser can figure out how to load the webpage faster for the end user. There are two ways to create these `Link` headers in Pages:
```

2022-09-27 10:23 UTC, deadlypants1973 commented on content/pages/platform/early-hints.md
> +
There needs to be a sentence here that addresses what the user is about to go. "This guide will teach you _____" "By following this guide, you will _____" before the steps.

2022-09-27 10:23 UTC, deadlypants1973 commented on content/pages/platform/early-hints.md
> +## 1. Using a `_headers` file
```suggestion
## 1. Configure your `_headers` file
```

2022-09-27 10:23 UTC, deadlypants1973 commented on content/pages/platform/early-hints.md
> +Custom headers can be created by using the [`_headers` file](/pages/platform/headers/). For example, if you include a particular stylesheet on your `/blog/` section of your website, you can create th
```suggestion
Create custom headers using the [`_headers` file](/pages/platform/headers/). For example, if you include a particular stylesheet on your `/blog/` section of your website, you can create the following rule:
```

2022-09-27 10:23 UTC, deadlypants1973 commented on content/pages/platform/early-hints.md
> +In order to make the authoring experience easier, Pages also automatically generates `Link` headers from any `<link>` HTML elements with any of the following attributes:
Is the user doing anything in this step?

2022-09-27 10:23 UTC, deadlypants1973 commented on content/pages/platform/early-hints.md
> +### Disabling automatic `Link` header generation Automatic `Link` header
```suggestion
### Disable automatic `Link` header generation Automatic `Link` header
```

2022-09-27 10:23 UTC, deadlypants1973 commented on content/pages/platform/early-hints.md
> +you find yourself needing to disable this feature, please get in touch with us!
```suggestion
Automatic `Link` header generation should not have any negative performance impact on your website. If you find yourself needing to disable this feature, ____
```
How are they contacting us? Cloudflare account team? Support? Discord?

2022-09-27 10:23 UTC, deadlypants1973 commented on content/pages/platform/early-hints.md
> +You can remove any automatically generated `Link` headers by adding the following to your `_headers` file:
```suggestion
Remove any automatically generated `Link` headers by adding the following to your `_headers` file:
```

2022-10-03 19:02 UTC, GregBrimble commented on content/pages/platform/early-hints.md
> +
This isn't a guide (the user doesn't follow step 1 and then step 2), rather, this presents two options. They can choose to do either step 1, or step 2, or both.

```suggestion

Early Hints can be created with either of the two methods detailed below.

```

2022-10-03 19:03 UTC, GregBrimble commented on content/pages/platform/early-hints.md
> +## 1. Using a `_headers` file
Does this still make sense if this isn't a mandatory step in a guide?

2022-10-03 19:03 UTC, GregBrimble commented on content/pages/platform/early-hints.md
> +Custom headers can be created by using the [`_headers` file](/pages/platform/headers/). For example, if you include a particular stylesheet on your `/blog/` section of your website, you can create th
Same here.

2022-10-03 19:04 UTC, GregBrimble commented on content/pages/platform/early-hints.md
> +In order to make the authoring experience easier, Pages also automatically generates `Link` headers from any `<link>` HTML elements with any of the following attributes:
No. This is one of the mechanisms that generates Early Hints. The only action a user can take here is below under the "Disabling automatic `Link` header generation Automatic `Link` header" header, where they can essentially turn off this automatic behavior if they choose.

2022-10-03 19:04 UTC, GregBrimble commented on content/pages/platform/early-hints.md
> +### Disabling automatic `Link` header generation Automatic `Link` header
Same here.

2022-10-03 19:04 UTC, GregBrimble commented on content/pages/platform/early-hints.md
> +You can remove any automatically generated `Link` headers by adding the following to your `_headers` file:
Same here.

2022-10-07 08:43 UTC, deadlypants1973 approved these changes

2022-10-07 08:43 UTC, deadlypants1973 commented on content/pages/platform/early-hints.md
> +[Early Hints](/cache/about/early-hints/) help the browser to load webpages faster. Early Hints is enabled automatically on all `pages.dev` domains. It can be [enabled](/cache/about/early-hints/#enabl
```suggestion
[Early Hints](/cache/about/early-hints/) help the browser to load webpages faster. Early Hints is enabled automatically on all `pages.dev` domains. [To enable](/cache/about/early-hints/#enabling-early-hints) Early Hints for your custom domains:

1. Log in to [Cloudflare dashboard](https://dash.cloudflare.com) and select your account and domain.
2. Go to **Speed** > **Optimization**.
3. Turn on the **Early Hints** toggle.
```

2022-10-07 08:43 UTC, deadlypants1973 commented on content/pages/platform/early-hints.md
> +
I'd resolve my comment but it doesn't give me that option. This is good as is, doesn't need changes :)

2022-10-07 08:48 UTC, deadlypants1973 approved these changes

2022-10-07 08:48 UTC, deadlypants1973 commented on content/pages/platform/early-hints.md
> +Note: `<link>` elements which contain any other additional attributes (e.g. `fetchpriority`, `crossorigin` or `data-do-not-generate-a-link-header`) will not be used to generate `Link` headers in orde
```suggestion
`<link>` elements which contain any other additional attributes (for example, `fetchpriority`, `crossorigin` or `data-do-not-generate-a-link-header`) will not be used to generate `Link` headers in order to prevent accidentally losing any custom prioritization logic that would otherwise be dropped as an Early Hint.
```

2022-10-07 08:48 UTC, deadlypants1973 commented on content/pages/platform/early-hints.md
> +This allows you to directly create Early Hints as you're authoring your document, without needing to flick between your HTML and `_headers` file.
```suggestion
This allows you to directly create Early Hints as you are writing your document, without needing to alternate between your HTML and `_headers` file.
```

2022-10-07 08:48 UTC, deadlypants1973 commented on content/pages/platform/early-hints.md
> +Automatic `Link` header generation should not have any negative performance impact on your website. If you find yourself needing to disable this feature, please reach let us know about your circumsta
```suggestion
Automatic `Link` header generation should not have any negative performance impact on your website. If you need to disable this feature, contact us by letting us know about your circumstance in our [Discord server](https://discord.com/invite/cloudflaredev).
```

2022-10-07 08:48 UTC, deadlypants1973 commented on content/pages/platform/early-hints.md
> +Note: `<link>` elements which contain any other additional attributes (e.g. `fetchpriority`, `crossorigin` or `data-do-not-generate-a-link-header`) will not be used to generate `Link` headers in orde
If it needs to be a note, then we can make this an aside. Otherwise, taking out the "note".

2022-10-07 08:48 UTC, deadlypants1973 commented on content/pages/platform/early-hints.md
> +Pages will then attach this `Link: </styles.css>; rel=preload; as=stylesheet` header, which Early Hints will then emit as an Early Hint once cached.
```suggestion
Pages will then attach this `Link: </styles.css>; rel=preload; as=stylesheet` header. Early Hints will then emit this header as an Early Hint once cached.
```

2022-10-07 12:04 UTC, merged