[Wrangler]: Document Global Variables
cloudflare/cloudflare-docs pull request #5990
Opened 2022-09-26 16:52 UTC by lauragift21

2022-09-26 21:15 UTC, GregBrimble commented on content/workers/wrangler/global-variables.md
> +- "CLOUDFLARE_API_BASE_URL": The default value is "https://api.cloudflare.com/client/v4".
Wouldn't bother documenting this here since there's no good reason for anyone other than Cloudflare employees needing this. Maybe in the `CONTRIBUTING.md` of the wrangler repo instead?

2022-09-26 21:20 UTC, GregBrimble commented on content/workers/wrangler/global-variables.md
> +title: Global Variables
Not a big fan of the name "Global Variables". In my head, this is kinda slipping over to `globalThis.VARIABLE`. Is there another phrase that we could use?

- "Wrangler Variables"
- "Wrangler CLI Variables"
- "CLI Variables"
- "System Variables"
- "OS Variables"
- "Non-Runtime Variables"

Possibly with "Environment" in the middle of each of those (e.g. "Wrangler CLI Environment Variables")?

2022-09-26 21:20 UTC, GregBrimble commented on content/workers/wrangler/global-variables.md
> +title: Global Variables
"System Environment Variables" is probably my personal favorite.

2022-09-27 09:06 UTC, lauragift21 commented on content/workers/wrangler/global-variables.md
> +title: Global Variables
Thanks @GregBrimble! I like these, We actually had a conversation to determine the best possible naming for this without confusing people since we've  Environment Variables and Environment already documented.

System Environment Variables sounds good wdyt @JacobMGEvans?

2022-09-27 15:13 UTC, JacobMGEvans commented on content/workers/wrangler/global-variables.md
> +- "CLOUDFLARE_API_BASE_URL": The default value is "https://api.cloudflare.com/client/v4".
Strongly disagree. If we are going to document the Global Variables we shouldn't exclude any assuming users won't need it.

2022-09-27 15:14 UTC, JacobMGEvans commented on content/workers/wrangler/global-variables.md
> +title: Global Variables
Definitely sounds good, we were juggling the "Systems Variable" naming for awhile. Thanks @GregBrimble

2022-09-27 19:03 UTC, GregBrimble commented on content/workers/wrangler/global-variables.md
> +- "CLOUDFLARE_API_BASE_URL": The default value is "https://api.cloudflare.com/client/v4".
But as a member of the public, I can't use the staging API anyway?

2022-09-27 22:34 UTC, JacobMGEvans commented on content/workers/wrangler/global-variables.md
> +- "CLOUDFLARE_API_BASE_URL": The default value is "https://api.cloudflare.com/client/v4".
We don't know what other uses "a member of the public" could want or need it for, it doesn't make sense to me to keep the information somewhere else due to the possibility it may or may not be useful.

2022-09-28 00:30 UTC, penalosa commented on content/workers/wrangler/global-variables.md
> +- "CLOUDFLARE_API_BASE_URL": The default value is "https://api.cloudflare.com/client/v4".
We do actually have a use for this for external users-environments that need to use a CORs proxy

2022-09-28 00:37 UTC, GregBrimble commented on content/workers/wrangler/global-variables.md
> +- "CLOUDFLARE_API_BASE_URL": The default value is "https://api.cloudflare.com/client/v4".
Good point!! Okay, disregard 😊

2022-09-28 15:35 UTC, lauragift21 commented on content/workers/wrangler/system-environment-variables.md
> +1. Setting them `.env` file in the project directory this is the recommended & persistent way to set these variables.
```suggestion
1. Setting an`.env` file in your project directory this is the recommended & persistent way to set these variables.
```

2022-09-28 15:35 UTC, lauragift21 commented on content/workers/wrangler/system-environment-variables.md
> +2. Inlining them in your Wrangler command for one-off use cases, for example `WRANGLER_LOG="debug" wrangler publish`.
```suggestion
2. Inlining the values in your Wrangler command for one-off use cases, for example `WRANGLER_LOG="debug" wrangler publish`.
```

2022-09-28 15:35 UTC, lauragift21 commented on content/workers/wrangler/system-environment-variables.md
> +3. Setting them in your shell environment persists depending on the shell settings, for example `export CF_API_TOKEN=...`.
```suggestion
3. Setting the values in your shell environment persists depending on the shell settings, for example `export CF_API_TOKEN=...`.
```

2022-10-01 19:25 UTC, Jutanium reviewed
🥳❤️

2022-10-01 19:25 UTC, Jutanium commented on content/workers/wrangler/system-environment-variables.md
> +System Environment Variables are process environment variables that are available to Wrangler commands. These variables are used to configure Wrangler's behavior. They can be set in a variety of ways
I'm not sure about the word "System" here - what does it mean/add? Similar question about "process".

Is it meant to differentiate from environment variables set on the hosting side? Maybe _local_ is better. If there isn't any other kind of environment variables, you don't need the modifier.

"They can be set in a variety of ways, including" - this implies that the list is incomplete (what ways weren't included?) 

Something like:
```suggestion
System Environment Variables are local environment variables that can change Wrangler's behavior. You can set them by:
```

2022-10-01 19:25 UTC, Jutanium commented on content/workers/wrangler/system-environment-variables.md
> +1. Setting an`.env` file in your project directory this is the recommended & persistent way to set these variables.
The "an" vs "a" depending on how `.env` is pronounced ("dot env" vs "env") is something we argue about all the time - it's up to your team!

Why is it recommended?

It's worth explaining what you mean by "persistent"

Something like:

```suggestion
1. Setting the values in a `.env` file in your project directory. This is the recommended way to set these variables, as it persists the values between Wrangler sessions.
```

2022-10-01 19:25 UTC, Jutanium commented on content/workers/wrangler/system-environment-variables.md
> +1. Setting an`.env` file in your project directory this is the recommended & persistent way to set these variables.
Also you can link to the section where you show `.env` examples

2022-10-01 19:25 UTC, Jutanium commented on content/workers/wrangler/system-environment-variables.md
> +2. Inlining the values in your Wrangler command for one-off use cases, for example `WRANGLER_LOG="debug" wrangler publish`.
```suggestion
2. Inlining the values in your Wrangler command. For example, `WRANGLER_LOG="debug" wrangler publish` will set the value of `WRANGLER_LOG` to "debug" for this execution of the command.
```

2022-10-01 19:25 UTC, Jutanium commented on content/workers/wrangler/system-environment-variables.md
> +3. Setting the values in your shell environment persists depending on the shell settings, for example `export CF_API_TOKEN=...`.
The example is incomplete without explicitly saying _where_ this line goes. Something like:
```suggestion
3. Setting the values in your shell environment. For example, if you're using Z shell, adding `export CF_API_TOKEN=...` to your `~/.zshrc`  file will set this token as part of your shell configuration.
```
(This assumes that by "depending on" you mean "applied with". If you meant that there's some configuration flag that will determine when the variable is applied, we can clarify that instead)

2022-10-01 19:25 UTC, Jutanium commented on content/workers/wrangler/system-environment-variables.md
> +**Currently, Wrangler supports the following System Environment Variables:**
```suggestion
**Currently, Wrangler supports the following environment variables:**
```

2022-10-01 19:25 UTC, Jutanium commented on content/workers/wrangler/system-environment-variables.md
> +- `"CLOUDFLARE_ACCOUNT_ID"`: The account ID for the Workers related account, can be found in the Cloudflare dashboard, can usually be inferred by Wrangler.
Clarify what you mean by "usually" - when can't it be inferred / when you would you want to set it?

2022-10-01 19:25 UTC, Jutanium commented on content/workers/wrangler/system-environment-variables.md
> +- `"CLOUDFLARE_ACCOUNT_ID"`: The account ID for the Workers related account, can be found in the Cloudflare dashboard, can usually be inferred by Wrangler.
What service is the "Workers related account"? Is that always a Cloudflare account, or could it be other kinds of services?

2022-10-01 19:25 UTC, Jutanium commented on content/workers/wrangler/system-environment-variables.md
> +- `"CLOUDFLARE_API_TOKEN"`: The API token for your Cloudflare account, can be used for authentication for situations like CI/CD, and other automation.
```suggestion
- `"CLOUDFLARE_API_TOKEN"`: The API token for your Cloudflare account. This is used for authenticating CI/CD and other automation.
```

2022-10-01 19:25 UTC, Jutanium commented on content/workers/wrangler/system-environment-variables.md
> +- `"CLOUDFLARE_API_KEY"`: The API key for your Cloudflare account, usually used for older authentication method with `CLOUDFLARE_EMAIL=`.
Same problem with "usually"

Since it's particularly confusing that there are two kinds of API key variables, extra care should be put into highlighting the difference and when you'd use one or the other

2022-10-01 19:25 UTC, Jutanium commented on content/workers/wrangler/system-environment-variables.md
> +- `"CLOUDFLARE_EMAIL"`: The email address associated with your Cloudflare account, usually used for older authentication method with `CLOUDFLARE_API_KEY=`.
Since this is the equivalent of the ID in the new system, I would put this before CLOUDFLARE_API_KEY. I would actually probably move these "old system" variables into their own section after this main list and give them their own title

2022-10-01 19:25 UTC, Jutanium commented on content/workers/wrangler/system-environment-variables.md
> +- `"WRANGLER_SEND_METRICS"`: Options for this are `true` and `false`, the default behavior is `false`.
Describe what happens when you set it to `true`

2022-10-01 19:25 UTC, Jutanium commented on content/workers/wrangler/system-environment-variables.md
> +- `"WRANGLER_LOG"`: Options for Logging levels are "none", "error", "warn", "info", "log" and "debug".
This might deserve its own section that you could link to, explaining what the different logging levels do

2022-10-01 19:25 UTC, Jutanium commented on content/workers/wrangler/system-environment-variables.md
> +**examples in `.env` file:**
**Example `.env` file: **

2022-10-01 19:25 UTC, Jutanium commented on content/workers/wrangler/system-environment-variables.md
> +CLOUDFLARE_EMAIL=...
I'd put some dummy values here rather than the `...`

2022-10-01 19:25 UTC, Jutanium commented on content/workers/wrangler/system-environment-variables.md
> +```
After the example, I'd add a line that explains how this changes the Wrangler behavior

2022-10-01 19:25 UTC, Jutanium commented on content/workers/wrangler/system-environment-variables.md
> +**Deprecated global variables are:**
I noticed that y'all use `**` rather than `###` for subsections here, just flagging in case that wasn't intended

2022-10-03 13:00 UTC, JacobMGEvans commented on content/workers/wrangler/system-environment-variables.md
> +3. Setting the values in your shell environment persists depending on the shell settings, for example `export CF_API_TOKEN=...`.
I think this is more accurate. Thank you.

2022-10-03 13:03 UTC, JacobMGEvans commented on content/workers/wrangler/system-environment-variables.md
> +**Deprecated global variables are:**
I will switch, I was on the fence which one to use but I know that the Headers have anchors you can reference in URLs

2022-10-03 13:05 UTC, JacobMGEvans commented on content/workers/wrangler/system-environment-variables.md
> +- `"WRANGLER_LOG"`: Options for Logging levels are "none", "error", "warn", "info", "log" and "debug".
I think I am going to redo this section based on the Configuration section rewrite.  @KianNH Thanks for the inspiration.

2022-10-03 22:28 UTC, JacobMGEvans commented on content/workers/wrangler/system-environment-variables.md
> +- `"WRANGLER_LOG"`: Options for Logging levels are "none", "error", "warn", "info", "log" and "debug".
Done.

2022-10-03 22:31 UTC, JacobMGEvans commented on content/workers/wrangler/system-environment-variables.md
> +**examples in `.env` file:**
Done.

2022-10-03 22:32 UTC, JacobMGEvans commented on content/workers/wrangler/system-environment-variables.md
> +CLOUDFLARE_EMAIL=...
Done.

2022-10-03 22:32 UTC, JacobMGEvans commented on content/workers/wrangler/system-environment-variables.md
> +**Deprecated global variables are:**
Done.

2022-10-03 22:50 UTC, JacobMGEvans commented
Oh no... Why rebase...

2022-10-03 23:01 UTC, JacobMGEvans commented
> Oh no... Why rebase...

Well that was awful, but I fixed it.

2022-10-04 03:43 UTC, WalshyDev requested changes

2022-10-04 03:43 UTC, WalshyDev commented on content/workers/wrangler/system-environment-variables.md
> +CLOUDFLARE_API_BASE_URL=https://api.cloudflare.com/client/v3
This is really only useful for us so I'd opt to remove it. Or at least change it to /v4 so those who copy this don't have issues.

```suggestion
```

2022-10-04 03:43 UTC, WalshyDev commented on content/workers/wrangler/system-environment-variables.md
> +1. Setting the values in a [`.env`](http://localhost:1313/workers/wrangler/system-environment-variables/#examples-in-env-file) file in your project directory. This is the recommended way to set these
```suggestion
1. Setting the values in a [`.env`](/workers/wrangler/system-environment-variables/#example-env-file) file in your project directory. This is the recommended way to set these variables, as it persists the values between Wrangler sessions.
```

2022-10-04 03:43 UTC, WalshyDev commented on content/workers/wrangler/system-environment-variables.md
> +3. Setting the values in your shell environment. For example, if you're using Z shell, adding `export CF_API_TOKEN=...` to your `~/.zshrc` file will set this token as part of your shell configuration
```suggestion
3. Setting the values in your shell environment. For example, if you're using Z shell, adding `export CLOUDFLARE_API_TOKEN=...` to your `~/.zshrc` file will set this token as part of your shell configuration.
```

2022-10-04 04:07 UTC, JacobMGEvans commented on content/workers/wrangler/system-environment-variables.md
> +CLOUDFLARE_API_BASE_URL=https://api.cloudflare.com/client/v3
Going to keep it. I will change it to V4 for peace of mind though
https://github.com/cloudflare/cloudflare-docs/pull/5990#discussion_r981834803

2022-10-04 04:08 UTC, JacobMGEvans commented on content/workers/wrangler/system-environment-variables.md
> +3. Setting the values in your shell environment. For example, if you're using Z shell, adding `export CF_API_TOKEN=...` to your `~/.zshrc` file will set this token as part of your shell configuration
Nice catch!

2022-10-04 04:13 UTC, WalshyDev approved these changes
LGTM

2022-10-04 04:14 UTC, JacobMGEvans commented
> LGTM

I am gonna wait for @deadlypants1973 to check it out, but thanks for the stamp @WalshyDev!

2022-10-07 11:28 UTC, deadlypants1973 commented on content/workers/wrangler/system-environment-variables.md
> +### Deprecated global variables are:
```suggestion
### Deprecated global variables
```

2022-10-07 11:28 UTC, deadlypants1973 commented on content/workers/wrangler/system-environment-variables.md
> +These variables are deprecated. Please use the new variables listed above, to prevent any issues or unwanted messaging.
```suggestion
The following variables are deprecated. Use the new variables listed above to prevent any issues or unwanted messaging.
```

2022-10-07 11:28 UTC, deadlypants1973 commented on content/workers/wrangler/system-environment-variables.md
> +- CF_API_BASE_URL
```suggestion
- `CF_ACCOUNT_ID`
- `CF_API_TOKEN`
- `CF_API_KEY`
- `CF_EMAIL`
- `CF_API_BASE_URL`
```

2022-10-07 11:28 UTC, deadlypants1973 commented on content/workers/wrangler/system-environment-variables.md
> +### Example `.env` file:
```suggestion
### Example `.env` file
```

2022-10-07 11:28 UTC, deadlypants1973 commented on content/workers/wrangler/system-environment-variables.md
> +
```suggestion

The following is an example `.env` file:

```

2022-10-07 11:28 UTC, deadlypants1973 commented on content/workers/wrangler/system-environment-variables.md
> +  - The account ID for the Workers related account, can be found in the Cloudflare dashboard, can usually be inferred by Wrangler.
```suggestion
  - The account ID for the Workers related account, can be [found in the Cloudflare dashboard](/fundamentals/get-started/basic-tasks/find-account-and-zone-ids/), can usually be inferred by Wrangler.
```

2022-10-07 11:28 UTC, deadlypants1973 commented on content/workers/wrangler/system-environment-variables.md
> +  - Options for Logging levels are "none", "error", "warn", "info", "log" and "debug".
```suggestion
  - Options for Logging levels are `"none"`, `"error"`, `"warn"`, `"info"`, `"log"` and `"debug"`.
```

2022-10-07 11:28 UTC, deadlypants1973 commented on content/workers/wrangler/system-environment-variables.md
> +  - Options for Logging levels are "none", "error", "warn", "info", "log" and "debug".
Are these possible values? if so, added backticks

2022-10-07 11:28 UTC, deadlypants1973 commented on content/workers/wrangler/system-environment-variables.md
> +  - The [API token](https://developers.cloudflare.com/api/get-started/create-token/) for your Cloudflare account, can be used for authentication for situations like CI/CD, and other automation.
```suggestion
  - The [API token](/api/get-started/create-token/) for your Cloudflare account, can be used for authentication for situations like CI/CD, and other automation.
```

2022-10-07 11:28 UTC, deadlypants1973 commented on content/workers/wrangler/system-environment-variables.md
> +### Wrangler supports the following environment variables:
```suggestion
### Supported environment variables
```

2022-10-07 11:28 UTC, deadlypants1973 commented on content/workers/wrangler/system-environment-variables.md
> +
```suggestion

Wrangler supports the following environment variables:

```

2022-10-07 11:28 UTC, deadlypants1973 commented on content/workers/wrangler/system-environment-variables.md
> +3. Setting the values in your shell environment. For example, if you're using Z shell, adding `export CLOUDFLARE_API_TOKEN=...` to your `~/.zshrc` file will set this token as part of your shell confi
```suggestion
1. Create an `.env` file in your project directory. Set the values of your environment variables in your [`.env`](/workers/wrangler/system-environment-variables/#example-env-file) file. This is the recommended way to set these variables, as it persists the values between Wrangler sessions.

2. Inline the values in your Wrangler command. For example, `WRANGLER_LOG="debug" wrangler publish` will set the value of `WRANGLER_LOG` to `"debug"` for this execution of the command.

3. Set the values in your shell environment. For example, if you are using Z shell, adding `export CLOUDFLARE_API_TOKEN=...` to your `~/.zshrc` file will set this token as part of your shell configuration.
```

2022-10-07 11:28 UTC, deadlypants1973 commented on content/workers/wrangler/system-environment-variables.md
> +System Environment Variables are local environment variables that can change Wrangler's behavior. You can set them by:
```suggestion
System Environment Variables are local environment variables that can change Wrangler's behavior. To set System Environment Variables:
```

2022-10-09 07:06 UTC, merged