Analytics Engine function additions
cloudflare/cloudflare-docs pull request #6094
Opened 2022-10-03 12:02 UTC by 46bit

In `analytics-engine-api` PR #90 I'm adding some new SQL functions (`min` and `max`) and adding support for the `DISTINCT` keyword to `count`, `avg` and `sum`. This PR updates the documentation with information on those new features.

This PR also quick-fixes a page that still listed us as being in private beta.

2022-10-03 13:20 UTC, angelampcosta approved these changes

2022-10-03 13:20 UTC, angelampcosta commented on content/analytics/analytics-engine/sql-reference.md
> +Sum is an aggregation function that returns the sum of column values across all rows in each group or results set. Sum also supports `DISTINCT`, and then it will only sum the unique values in the col
```suggestion
Sum is an aggregation function that returns the sum of column values across all rows in each group or results set. Sum also supports `DISTINCT`, but in this case it will only sum the unique values in the column.
```

2022-10-03 13:20 UTC, angelampcosta commented on content/analytics/analytics-engine/sql-reference.md
> +Avg is an aggregation function that returns the mean of column values across all rows in each group or results set. Avg also supports `DISTINCT`, and then it will only average the unique values in th
```suggestion
Avg is an aggregation function that returns the mean of column values across all rows in each group or results set. Avg also supports `DISTINCT`, but in this case it will only average the unique values in the column.
```

2022-10-03 15:16 UTC, jimhawkridge requested changes
I've requested one change (to the `COUNT()`).
I've also suggested a change to the example to make it more "real world". I'm stuggling to think of good examples for AVG and SUM with DISTINCT though. I'll think on that, but either way the current examples are fine really - I'm just being picky.

2022-10-03 15:16 UTC, jimhawkridge commented on content/analytics/analytics-engine/sql-reference.md
> +COUNT(item_cost)
The usage suggest the options are empty brackets, or DISTINCT?
```suggestion
COUNT()
```

2022-10-03 15:16 UTC, jimhawkridge commented on content/analytics/analytics-engine/sql-reference.md
> +-- return the number of unique item costs
How about `COUNT(DISTINCT product_variety` (counts the number of distinct product types). Or something.
I think counting distinct costs could be a confusing/unlikely thing to want to do.

2022-10-04 14:18 UTC, 46bit commented on content/analytics/analytics-engine/sql-reference.md
> +-- return the number of unique item costs
I've run queries like that before but yeah it's hard to describe a usecase briefly. I'll go with your idea 👍🏻

2022-10-04 14:34 UTC, 46bit commented on content/analytics/analytics-engine/sql-reference.md
> +-- return the number of unique item costs
Pushed up a commit that should help a bit

2022-10-04 14:34 UTC, jimhawkridge approved these changes

2022-10-05 10:28 UTC, 46bit commented
@angelampcosta @jimhawkridge The changes this PR documents are live now. I don't have merge permissions for this PR, could either of you merge? Thanks :)

2022-10-05 10:32 UTC, merged