[Workers] Added a section about using workers to purge
cloudflare/cloudflare-docs pull request #6155
Opened 2022-10-06 10:31 UTC by angelampcosta

2022-10-06 10:45 UTC, marciocloudflare approved these changes

2022-10-06 10:45 UTC, marciocloudflare commented on content/cache/how-to/purge-cache.md
> +For information on how to use single-file purge to purge assets cached by a workers fetch, please refer to [​​Using Workers to purge](/workers/learning/how-the-cache-works/#using-workers-to-purge).
```suggestion
For information on how to use single-file purge to purge assets cached by a Workers fetch, please refer to [​​Using Workers to purge](/workers/learning/how-the-cache-works/#using-workers-to-purge).
```

2022-10-06 10:45 UTC, marciocloudflare commented on content/workers/learning/how-the-cache-works.md
> +When using single-file purge to purge assets cached by a workers fetch, be aware not to purge the end user url instead of the url that is in the fetch. For example, if you have a worker that runs on
```suggestion
When using single-file purge to purge assets cached by a Workers fetch, be aware not to purge the end user URL instead of the URL that is in the fetch. For example, if you have a Worker that runs on `https://example.com/hello` and this Worker makes a `fetch` request to `https://notexample.com/hello`.
```

2022-10-06 10:45 UTC, marciocloudflare commented on content/workers/learning/how-the-cache-works.md
> +When using single-file purge to purge assets cached by a workers fetch, be aware not to purge the end user url instead of the url that is in the fetch. For example, if you have a worker that runs on
I'm didn't understand this. It almost looks like there's something missing in the end of the sentence.

2022-10-06 10:45 UTC, marciocloudflare commented on content/workers/learning/how-the-cache-works.md
> +As far as cache is concerned, the asset in the fetch is the asset that is cached which is `https://notexample.com/hello`, so if you would like to purge it, you need to purge `https://notexample.com/h
```suggestion
As far as cache is concerned, the asset in the fetch is the asset that is cached which is `https://notexample.com/hello`. So, if you would like to purge it, you need to purge `https://notexample.com/hello`. 
```

2022-10-06 10:45 UTC, marciocloudflare commented on content/workers/learning/how-the-cache-works.md
> +As far as cache is concerned, the asset in the fetch is the asset that is cached which is `https://notexample.com/hello`, so if you would like to purge it, you need to purge `https://notexample.com/h
Breaking up long sentence

2022-10-06 10:45 UTC, marciocloudflare commented on content/workers/learning/how-the-cache-works.md
> +Purging the end user url, `https://example.com/hello`, will not work since that is not the url that cache sees. You need to confirm in your worker, which url you are actually fetching, so you can pur
```suggestion
Purging the end user URL, `https://example.com/hello`, will not work since that is not the URL that cache sees. You need to confirm in your worker which URL you are actually fetching, so you can purge the correct asset.
```

2022-10-06 11:05 UTC, ZahoorNoor commented
angela/document-single-file-purge-of-assets-fetched-by-workers

2022-10-06 14:29 UTC, deadlypants1973 approved these changes

2022-10-06 14:29 UTC, deadlypants1973 commented on content/cache/how-to/purge-cache.md
> +For information on how to use single-file purge to purge assets cached by a Workers fetch, please refer to [​​Using Workers to purge](/workers/learning/how-the-cache-works/#using-workers-to-purge).
```suggestion
For information on how to use single-file purge to purge assets cached by a Workers fetch, refer to [​​Using Workers to purge](/workers/learning/how-the-cache-works/#using-workers-to-purge).
```

2022-10-06 14:29 UTC, deadlypants1973 commented on content/workers/learning/how-the-cache-works.md
> +When using single-file purge to purge assets cached by a Workers fetch, be aware not to purge the end user URL instead of the URL that is in the fetch. For example, if you have a Worker that runs on
```suggestion
When using single-file purge to purge assets cached by a Worker, make sure not to purge the end user URL. Instead, purge the URL that is in the `fetch` request. For example, you have a Worker that runs on `https://example.com/hello` and this Worker makes a `fetch` request to `https://notexample.com/hello`.
```

2022-10-06 14:29 UTC, deadlypants1973 commented on content/workers/learning/how-the-cache-works.md
> +As far as cache is concerned, the asset in the fetch is the asset that is cached which is `https://notexample.com/hello`. So, if you would like to purge it, you need to purge `https://notexample.com/
```suggestion
As far as cache is concerned, the asset in the `fetch` request (`https://notexample.com/hello`) is the asset that is cached (`https://notexample.com/hello`). To purge it, you need to purge `https://notexample.com/hello`. 
```

2022-10-06 14:29 UTC, deadlypants1973 commented on content/workers/learning/how-the-cache-works.md
> +Purging the end user URL, `https://example.com/hello`, will not work since that is not the URL that cache sees. You need to confirm in your worker which URL you are actually fetching, so you can purg
```suggestion
Purging the end user URL, `https://example.com/hello`, will not work because that is not the URL that cache sees. You need to confirm in your Worker which URL you are actually fetching, so you can purge the correct asset.
```

2022-10-06 23:37 UTC, iveelsm requested changes
We will need some additional content here. There is some nuance that is missing. Some scenarios that could cause issues...

Worker runs at `example.com/hello`

* If `notexample.com/hello` is Orange Clouded on Cloudflare, these docs stand as is with two caveats
  * If `notexample.com/hello` is not owned by the account, then you cannot purge the asset
  * If `notexample.com/hello` is not a cacheable asset for `notexample.com`, then you cannot purge the asset
  
 * If `notexample.com/hello` is not orange clouded by cloudflare, then this doc stands.

2022-10-07 09:52 UTC, deadlypants1973 commented on content/workers/learning/how-the-cache-works.md
> +- If `notexample.com/hello` is not a cacheable asset for `notexample.com`, then you cannot purge the asset.
```suggestion
In the previous example, `https://notexample.com/hello` is not proxied through Cloudflare. If `https://notexample.com/hello` was proxied (orange-clouded) through Cloudflare, there would be two caveats:
 
- If `notexample.com/hello` is not owned by the account, then you cannot purge the asset.
- If `notexample.com/hello` is not a cacheable asset for `notexample.com`, then you cannot purge the asset.
```

2022-10-07 16:02 UTC, iveelsm approved these changes

2022-10-07 16:13 UTC, merged