[Wrangler] Explain bundling & rules
cloudflare/cloudflare-docs pull request #6164
Opened 2022-10-06 16:08 UTC by penalosa

Explain how Wrangler bundles, and when it _doesn't_ bundle

2022-10-06 16:11 UTC, GregBrimble commented on content/workers/wrangler/bundling.md
> +the variable `data` will be a string containing the contents of `test.html`.
```suggestion
import data from "./example.html"; // Where `example.html` is a file in your local directory
\```

the variable `data` will be a string containing the contents of `example.html`.
```

2022-10-06 16:11 UTC, GregBrimble commented on content/workers/wrangler/bundling.md
> +This is also the basis of WASM support with Wrangler. To use a WASM module in a Worker developed with Wrangler, add the following to your Worker:
```suggestion
This is also the basis of Wasm support with Wrangler. To use a Wasm module in a Worker developed with Wrangler, add the following to your Worker:
```

2022-10-06 16:12 UTC, GregBrimble commented on content/workers/wrangler/bundling.md
> +import wasm from "example.wasm"; // Where `example.wasm` is a file in your local directory
```suggestion
import wasm from "./example.wasm"; // Where `example.wasm` is a file in your local directory
```

2022-10-06 16:12 UTC, GregBrimble requested changes
The relative referencing is just a suggestion, but the others should be fixed.

2022-10-06 16:14 UTC, GregBrimble commented on content/workers/wrangler/bundling.md
> +We recommend using Wrangler's inbuilt bundling, but we understand there are cases where you'll need a bit more flexibility. We've built an escape hatch in the form of [Custom Builds](/workers/wrangle
```suggestion
We recommend using Wrangler's inbuilt bundling, but we understand there are cases where you'll need a bit more flexibility. We've built an escape hatch in the form of [Custom Builds](/workers/wrangler/custom-builds/), which let you replace Wrangler's built-in build step with your own.
```

2022-10-07 13:25 UTC, deadlypants1973 requested changes
PCX review

2022-10-07 13:25 UTC, deadlypants1973 commented on content/workers/wrangler/bundling.md
> +# Wrangler's bundling
```suggestion
# Bundling
```

2022-10-07 13:25 UTC, deadlypants1973 commented on content/workers/wrangler/bundling.md
> +We recommend using Wrangler's inbuilt bundling, but we understand there are cases where you'll need a bit more flexibility. We've built an escape hatch in the form of [Custom Builds](/workers/wrangle
```suggestion
We recommend using Wrangler's inbuilt bundling, but we understand there are cases where you will need more flexibility. We have built an escape hatch in the form of [Custom Builds](/workers/wrangler/custom-builds/), which let you replace Wrangler's built-in build step with your own.
```
Two things here: Custom Builds page is very much blank, so don't know if you want to do a link out. Is 'escape hatch' a programmatic term? If not, more straightforward, less colloquial lingual replacement is preferred for readers.

2022-10-07 13:25 UTC, deadlypants1973 commented on content/workers/wrangler/bundling.md
> +By default, Wrangler bundles your Worker code using [`esbuild`](https://esbuild.github.io/). This means that Wrangler has built in support for importing modules from [npm](https://www.npmjs.com/) def
```suggestion
By default, Wrangler bundles your Worker code using [`esbuild`](https://esbuild.github.io/). This means that Wrangler has built-in support for importing modules from [npm](https://www.npmjs.com/) defined in your `package.json`. To review the exact code that Wrangler will upload to Cloudflare, run `wrangler publish --dry-run --outdir dist`, which will show your Worker code after Wrangler's bundling.
```

2022-10-07 13:25 UTC, deadlypants1973 commented on content/workers/wrangler/bundling.md
> +## Files which won't be bundled
```suggestion
## Files which will not be bundled
```

2022-10-07 13:25 UTC, deadlypants1973 commented on content/workers/wrangler/bundling.md
> +See the [rules configuration](/workers/wrangler/configuration/#bundling) to customise these file types.
```suggestion
Refer to [Bundling configuration](/workers/wrangler/configuration/#bundling) to customize these file types.
```

2022-10-07 13:25 UTC, deadlypants1973 commented on content/workers/wrangler/bundling.md
> +The effect of bundling your Worker code is to take multiple modules and bundle them into one. Sometimes, however, that isn't the behaviour you want. There might be modules that _shouldn't_ be inlined
```suggestion
Bundling your Worker code is taking multiple modules and bundling them into one. Sometimes, that is not the desired behavior. There might be modules that should not be inlined directly into the bundle. For example, instead of bundling a WASM file into your Javascript Worker, you would want to upload the WASM file as a separate module that can be imported at runtime. Wrangler supports this for the following file types:
```

2022-10-07 13:25 UTC, deadlypants1973 commented on content/workers/wrangler/bundling.md
> +This means that for an import like the following:
```suggestion
Review the following import:
```

2022-10-07 13:25 UTC, deadlypants1973 commented on content/workers/wrangler/bundling.md
> +the variable `data` will be a string containing the contents of `example.html`.
```suggestion
In the above import, the variable `data` will be a string containing the contents of `example.html`.
```

2022-10-07 13:25 UTC, deadlypants1973 commented on content/workers/wrangler/bundling.md
> +Cloudflare Workers doesn't support `WebAssembly.instantiateStreaming()`
```suggestion
Cloudflare Workers does not support `WebAssembly.instantiateStreaming()`
```

2022-10-07 13:25 UTC, deadlypants1973 commented on content/workers/wrangler/bundling.md
> +This is also the basis of Wasm support with Wrangler. To use a Wasm module in a Worker developed with Wrangler, add the following to your Worker:
```suggestion
This is also the basis of Wasm support with Wrangler. To use a Wasm module in a Worker developed with Wrangler, add the following to your Worker:
```

2022-10-07 15:23 UTC, KianNH commented
I *believe* dynamic imports (i.e `await import`) are now supported in Workers, as teased in https://twitter.com/jasnell/status/1546498745054814209

I don't recall seeing it in changelogs but a few people reported it now works for them. If that's the case, might be worth mentioning?

2022-10-12 15:05 UTC, rozenmd commented on content/workers/wrangler/bundling.md
> +We recommend using Wrangler's inbuilt bundling, but we understand there are cases where you'll need a bit more flexibility. We've built an escape hatch in the form of [Custom Builds](/workers/wrangle
It's a programming thing: https://wiki.c2.com/?EscapeHatch

2022-10-14 06:45 UTC, penalosa commented
@deadlypants1973 I've addressed your comments, but I've also added an additional section that's probably worth reviewing. In terms of the link to the custom builds page, I think it's worth keeping for right now (I've added a quick link to the custom builds configuration to that page) as we'll hopefully be expanding that page soon.
@rozenmd I've added an extra section mentioning the downsides of `--no-bundle`; no D1 support and that the dashboard might blow up with errors (more diplomatically worded :joy:)—was there anything else you wanted added here?

2022-10-14 08:12 UTC, rozenmd approved these changes
This looks great to me, I'll let @deadlypants1973 have a final review though

2022-10-14 12:34 UTC, deadlypants1973 requested changes

2022-10-14 12:34 UTC, deadlypants1973 commented on content/workers/wrangler/bundling.md
> +
```suggestion

By default, Wrangler bundles your Worker code using [`esbuild`](https://esbuild.github.io/). This means that Wrangler has built-in support for importing modules from [npm](https://www.npmjs.com/) defined in your `package.json`. To review the exact code that Wrangler will upload to Cloudflare, run `wrangler publish --dry-run --outdir dist`, which will show your Worker code after Wrangler's bundling.

{{<Aside type="note">}}
We recommend using Wrangler's inbuilt bundling, but we understand there are cases where you will need more flexibility. We have built an escape hatch in the form of [Custom Builds](/workers/wrangler/custom-builds/), which let you run your own build before Wrangler's built-in one.
{{</Aside>}}

```

2022-10-14 12:34 UTC, deadlypants1973 commented on content/workers/wrangler/migration/eject-webpack.md
> +As of Wrangler 2, Wrangler has built-in support for this use case. Refer to the [Bundling](/workers/wrangler/bundling/) page for more details.
```suggestion
As of Wrangler 2, Wrangler has built-in support for this use case. Refer to [Bundling](/workers/wrangler/bundling/) for more details.
```

2022-10-14 12:34 UTC, deadlypants1973 commented on content/workers/wrangler/bundling.md
> +There are sometimes cases where it's necessary to edit your Worker from the Cloudflare dashboard. When you use the `--no-bundle` flag, this isn't possible, as the Cloudflare dashboard doesn't support
```suggestion
It is not possible to edit your Worker in the Cloudflare dashboard when you use the `--no-bundle` flag. The Cloudflare dashboard does not support Workers with multiple modules. If you use a Custom Build script, which bundles your Worker into a single module, this limitation can be bypassed.
```

2022-10-14 12:34 UTC, deadlypants1973 commented on content/workers/wrangler/bundling.md
> +By default, Wrangler bundles your Worker code using [`esbuild`](https://esbuild.github.io/). This means that Wrangler has built-in support for importing modules from [npm](https://www.npmjs.com/) def
```suggestion
By default, Wrangler bundles your Worker code using [`esbuild`](https://esbuild.github.io/). This means that Wrangler has built-in support for importing modules from [npm](https://www.npmjs.com/) defined in your `package.json`. To review the exact code that Wrangler will upload to Cloudflare, run `wrangler publish --dry-run --outdir dist`, which will show your Worker code after Wrangler's bundling.

{{<Aside type="note">}}
We recommend using Wrangler's inbuilt bundling but for cases where you need more flexibility, we recommend using [Custom Builds](/workers/wrangler/custom-builds/). Custom builds allow you to run your own build before Wrangler's built-in one.
{{</Aside>}}
```

2022-10-14 12:34 UTC, deadlypants1973 commented on content/workers/wrangler/bundling.md
> +Cloudflare Workers does not support `WebAssembly.instantiateStreaming()`
```suggestion
Cloudflare Workers does not support `WebAssembly.instantiateStreaming()`.
```

2022-10-14 12:34 UTC, deadlypants1973 commented on content/workers/wrangler/bundling.md
> +Disabling bundling is not recommended, and has a number of major tradeoffs that are detailed below. Most users should be able to ignore this section.
```suggestion
Disabling bundling is not recommended and has a number of major tradeoffs that are detailed below. Most users should be able to ignore this section.
```

2022-10-14 12:34 UTC, deadlypants1973 commented on content/workers/wrangler/bundling.md
> +As well as using [Custom Builds](/workers/wrangler/custom-builds/) to customise what Wrangler will bundle and upload to the Cloudflare Edge when you use `wrangler dev` and `wrangler publish`, you can
```suggestion
Opt out of bundling by using the `--no-bundle` command line flag: `wrangler publish --no-bundle`. If you opt out of bundling, Wrangler will not process your code and a number of features will not be available. You can use [Custom Builds](/workers/wrangler/custom-builds/) to customize what Wrangler will bundle and upload to the Cloudflare edge network when you use `wrangler dev` and `wrangler publish`.
```

2022-10-14 12:34 UTC, deadlypants1973 commented on content/workers/wrangler/bundling.md
> +During the beta period for D1, D1 bindings will not be available to a Worker published with `--no-bundle`.
```suggestion
During the [beta period for D1](/workers/platform/betas/), D1 bindings will not be available to a Worker published with `--no-bundle`.
```

2022-10-14 12:34 UTC, deadlypants1973 commented on content/workers/wrangler/bundling.md
> +Bundling your Worker code takes multiple modules and bundles them into one. Sometimes, that is not the desired behavior and there might be modules that should not be inlined directly into the bundle.
```suggestion
Bundling your Worker code takes multiple modules and bundles them into one. Sometimes, you might have modules that should not be inlined directly into the bundle. For example, instead of bundling a WASM file into your JavaScript Worker, you would want to upload the WASM file as a separate module that can be imported at runtime. Wrangler supports this for the following file types:
```

2022-10-14 12:34 UTC, deadlypants1973 commented on content/workers/wrangler/bundling.md
> +pcx_content_type: how-to
```suggestion
pcx_content_type: concept
```

2022-10-14 12:49 UTC, deadlypants1973 reviewed
PCX review

2022-10-14 12:52 UTC, deadlypants1973 commented on content/workers/wrangler/custom-builds.md
> +This page is in progress. Refer to the [configuration](/workers/wrangler/configuration/#custom-builds) for a brief overview.
```suggestion
This page is in progress. Refer to [Configuration](/workers/wrangler/configuration/#custom-builds) for a brief overview.
```

2022-10-14 12:56 UTC, GregBrimble approved these changes

2022-10-14 13:02 UTC, GregBrimble commented on content/workers/wrangler/bundling.md
> +We recommend using Wrangler's inbuilt bundling, but we understand there are cases where you will need more flexibility. We have built an escape hatch in the form of [Custom Builds](/workers/wrangler/
```suggestion
We recommend using Wrangler's inbuilt bundling, but we understand there are cases where you will need more flexibility. We have built an escape hatch in the form of [Custom Builds](/workers/wrangler/custom-builds/), which lets you run your own build before Wrangler's built-in one.
```

2022-10-14 13:02 UTC, GregBrimble commented on content/workers/wrangler/bundling.md
> +Bundling your Worker code takes multiple modules and bundles them into one. Sometimes, you might have modules that should not be inlined directly into the bundle. For example, instead of bundling a W
```suggestion
Bundling your Worker code takes multiple modules and bundles them into one. Sometimes, you might have modules that should not be inlined directly into the bundle. For example, instead of bundling a Wasm file into your JavaScript Worker, you would want to upload the Wasm file as a separate module that can be imported at runtime. Wrangler supports this for the following file types:
```

2022-10-14 13:02 UTC, deadlypants1973 approved these changes
PCX review

2022-10-14 13:04 UTC, GregBrimble commented on content/workers/wrangler/bundling.md
> +We recommend using Wrangler's inbuilt bundling, but we understand there are cases where you will need more flexibility. We have built an escape hatch in the form of [Custom Builds](/workers/wrangler/
idk, maybe not.

2022-10-14 13:13 UTC, merged