workers: remove deprecated experimental-enable-local-persistence flag in commands.md
cloudflare/cloudflare-docs pull request #6185
Opened 2022-10-07 18:09 UTC by justinnoel

The flag `--experimental-enable-local-persistence` is deprecated and no longer available.

When attempting to use this flag, wrangler says:

```
🚧 'wrangler pages <command>' is a beta command. Please report any issues to https://github.com/cloudflare/wrangler2/issues/new/choose
▲ [WARNING] --experimental-enable-local-persistence is deprecated.

  Move any existing data to .wrangler/state and use --persist, or
  use --persist-to=./wrangler-local-state to keep using the old path.
```

2022-10-11 16:07 UTC, rozenmd requested changes

2022-10-11 16:07 UTC, rozenmd commented on content/workers/wrangler/commands.md
> -This runs an ephemeral local version of your Worker, and will not be able to access data stored on Cloudflare's Edge (for instance, this includes your data stored on KV). If you'd like to persist dat
Rather than deleting, probably better to include the message from the deprecation warning:
```
This runs an ephemeral local version of your Worker, and will not be able to access data stored on Cloudflare's Edge (for instance, this includes your data stored on KV). If you'd like to persist data locally, use --persist to use a default path (`.wrangler/state`), or use --persist-to=<YOUR_PATH_HERE> to set a custom persistence path.
```

2022-10-11 20:18 UTC, justinnoel commented on content/workers/wrangler/commands.md
> -This runs an ephemeral local version of your Worker, and will not be able to access data stored on Cloudflare's Edge (for instance, this includes your data stored on KV). If you'd like to persist dat
The message you suggested adding is the one I'm suggesting deleting. There's no need to add something that's already there.

My point is that the **docs** don't need to document the effects of a command that is not only deprecated but **also** doesn't exist in the current code base anymore.

2022-10-11 21:44 UTC, rozenmd commented on content/workers/wrangler/commands.md
> -This runs an ephemeral local version of your Worker, and will not be able to access data stored on Cloudflare's Edge (for instance, this includes your data stored on KV). If you'd like to persist dat
No, it isn't. We deprecated `--experimental-enable-local-persistence` in favour of `--persist` and `--persist-to`.

2022-10-13 11:44 UTC, justinnoel commented
Okay.

2022-10-13 11:44 UTC, closed without merging