Explain how to paginate with the Analytics Engine SQL API
cloudflare/cloudflare-docs pull request #6206
Opened 2022-10-10 14:09 UTC by 46bit

This commit's diff is quite self-explanatory. This is a common request and it's best to have it in the documentation.

2022-10-11 11:16 UTC, jimhawkridge commented on content/analytics/analytics-engine/sql-api.md
> +> SELECT * FROM your_dataset WHERE timestamp < toDateTime("2022-10-10 13:56:48") ORDER BY timestamp DESC LIMIT 1000
```suggestion
> SELECT * FROM your_dataset WHERE timestamp < toDateTime("2022-10-10 13:56:48") ORDER BY timestamp DESC LIMIT 10000
```

2022-10-11 11:16 UTC, jimhawkridge commented on content/analytics/analytics-engine/sql-api.md
> +First run your desired query, adding `ORDER BY timestamp DESC` and a sensible `LIMIT`:
Can we offer any guidance on what a sensible value might be?
What factors affect this?

2022-10-11 11:16 UTC, jimhawkridge commented on content/analytics/analytics-engine/sql-api.md
> +> SELECT * FROM your_dataset ORDER BY timestamp DESC LIMIT 10000
I think it might be worth breaking each of these examples into two code blocks with appropriate syntax highlighting on each.

2022-10-18 16:38 UTC, 46bit commented on content/analytics/analytics-engine/sql-api.md
> +First run your desired query, adding `ORDER BY timestamp DESC` and a sensible `LIMIT`:
I think I'm going to suggest `1000` items as a sensible limit. Queries are expensive to run and if we suggest something like `100` it'll add up a lot more.

2022-10-18 21:42 UTC, victor-perov commented
Thanks for providing a pagination example!

Described concept of paginating by N rows ordered by timestamp is good enough only if you are 100% sure that you have no more than one event per second. For example, you paginate over aggregates by timestamp (`... GROUP BY timestamp...`). 

It would make more sense if the concept pointed out the importance of understanding the data before running into a pagination SQL query. It will save time for our fellow users to understand their results.

Also, the pagination is primarily used inside a script that runs data extraction in the loop. Therefore, examples with a so-called "preparation step" (like getting an initial "offset") are hard to use as-is.

I want to suggest structuring this information in blocks as follows:

1. describe the points users should be aware of, as this will help to write the needed query:
    
    * LIMIT N OFFSET is not supported;
    * describe hard limits of the API (like 1000 rows of the result set);
    * datasets might have more than one event per second, so users should be aware of inconsistent sorting if they re-run the same query with sorting by a timestamp only;
    * adding more high cardinality fields to `ORDER BY` clause is very helpful;
    * having `timestamp > datetimeA AND timestamp <= datetimeB` is vital as you won't read twice the exact second;
    * including more fields to the filter criteria and using narrow time ranges improves chances of not hitting hard limits;
    * using GROUP BY should be considered when the hard limit is reached, and the user runs out of filter options.

2. Prepare user to understand the given query by describing the nature of data and the rate of events per granule (like one event per second per index);

3. Provide a SQL query that has appropriate WHERE criteria to the rate of events;

4. Finally, show a complete snippet where the given SQL query is injected into a loop that gets a timestamp and iterates by incrementing it by hour/day/etc.

2022-10-18 21:45 UTC, victor-perov requested changes
Please, see my comment above.

2022-10-19 00:40 UTC, 46bit commented
If you have strong opinions I’d suggest writing an alternate PR. This is a small PR intended as a brief how-to and not a detailed article.

2022-10-19 11:52 UTC, jimhawkridge approved these changes
I think this is fine to cover off the basics of pagination. We can always add a more detailed page with some of Viktor's suggestions later on.
I especially agree it would be nice to have a story around how to cope with duplicate timestamps. I don't think there is actually a good answer to that at the moment. 
How granular are timestamps? This will have a big effect on how much of an issue this is.

2022-10-19 11:52 UTC, jimhawkridge commented on content/analytics/analytics-engine/sql-api.md
> +An example is where you want to retrieve all of your data from a dataset: `SELECT * FROM your_dataset`. If you only have a few thousand rows then that query should execute fine, but if you have milli
Few thousand seems at odds with the recommendation of 1000.

2022-10-27 12:06 UTC, 46bit commented on content/analytics/analytics-engine/sql-api.md
> +An example is where you want to retrieve all of your data from a dataset: `SELECT * FROM your_dataset`. If you only have a few thousand rows then that query should execute fine, but if you have milli
I think I might leave this for now, as we don't have a fixed limit. 1000 is intended as a sensible suggestion but you can get back a lot more than that if you try -- it's just, at some point it will error.

I've added DS-12845 to think about how we handle large responses.

2022-10-27 12:07 UTC, 46bit commented
Looks like this can't be merged with @victor-perov's outstanding requested changes

2022-10-27 12:59 UTC, angelampcosta approved these changes

2022-10-27 12:59 UTC, angelampcosta commented on content/analytics/analytics-engine/sql-api.md
> +An example is where you want to retrieve all of your data from a dataset: `SELECT * FROM your_dataset`. If you only have a few thousand rows then that query should execute fine, but if you have milli
```suggestion
An example might be when you want to retrieve all of your data from a dataset: `SELECT * FROM your_dataset`. If you only have a few thousand rows then that query should execute fine, but if you have millions of rows then it is likely to fail. Instead you can break down the query into multiple sequential queries.
```

2022-10-27 12:59 UTC, angelampcosta commented on content/analytics/analytics-engine/sql-api.md
> +First run your desired query, adding `ORDER BY timestamp DESC` and our recommended `LIMIT` of 1000:
```suggestion
First, run your desired query, adding `ORDER BY timestamp DESC` and our recommended `LIMIT` of 1000:
```

2022-10-27 12:59 UTC, angelampcosta commented on content/analytics/analytics-engine/sql-api.md
> +Next run a second query, using the timestamp of the final row in the `WHERE` clause of the next query:
```suggestion
Next, run a second query, using the timestamp of the final row in the `WHERE` clause of the next query:
```

2022-10-27 12:59 UTC, angelampcosta commented on content/analytics/analytics-engine/sql-api.md
> +You'll get the next 1000 older rows:
```suggestion
You will get the next 1000 older rows:
```

2022-10-27 12:59 UTC, angelampcosta commented on content/analytics/analytics-engine/sql-api.md
> +Traditionally the SQL `OFFSET` feature has been used for pagination, but we do not support it because it is inefficient with big datasets. Instead you can use the timestamp of each row as a cursor.
```suggestion
Traditionally, the SQL `OFFSET` feature has been used for pagination, but we do not support it because it is inefficient with big datasets. Instead you can use the timestamp of each row as a cursor.
```

2022-10-27 18:18 UTC, victor-perov commented
> If you have a strong vision I’d suggest writing an alternate PR. This is a small PR intended as a brief how-to and not a detailed article.

I see, thanks for clarification. In that case, is it possible to re-phrase the bit about "millions of rows"? In my understanding it doesn't match with further solution and might cause confusion.

Would be nice to get all parts of the guide aligned together.

2023-05-10 17:51 UTC, tlozoot approved these changes

2023-05-10 17:51 UTC, tlozoot approved these changes

2023-05-11 09:15 UTC, angelampcosta commented
Hi @victor-perov! Could you please review again to make sure your comments have been addressed. Thanks!

2023-05-15 16:25 UTC, victor-perov commented on content/analytics/analytics-engine/sql-api.md
> +You will get the next 1000 older rows:
What if the next batch will get 1000 rows with the same timestamp?

I think we should highlight here an assumption that it works for a scenario when we have at most 1 request per second.

Would also be nice to notice that we SQL API does not support `LIMIT n OFFSET m`.

2023-09-11 15:27 UTC, angelampcosta commented
Hi @victor-perov! @jimhawkridge addressed your last comment. Do you think we can merge this PR?

2023-09-26 14:35 UTC, KimJ15 commented
@victor-perov @jimhawkridge See Angela's comment above. We would like to merge this PR and close out the request. Thanks!

2023-10-26 15:02 UTC, haleycode commented
Hi all, this PR has been open for quite some time without resolution, so I'm going to close it out for now. We can always reopen or revisit the issue in future if needed!

2023-10-26 15:02 UTC, closed without merging