Create a new Reference Architecture tile
cloudflare/cloudflare-docs pull request #6309
Opened 2022-10-17 21:49 UTC by haleycode

2022-10-17 22:08 UTC, kodster28 requested changes

2022-10-17 22:08 UTC, kodster28 commented on content/reference-architecture/cdn-reference-architecture.md
> +### The impact this has:
Headings with colons leading into bulleted lists sorta makes me barf a bit in my mouth...

2022-10-17 22:08 UTC, kodster28 commented on content/reference-architecture/cdn-reference-architecture.md
> +|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------------------------
You don't need all these extra lines. Could shorten pretty easily. Let me know if you need help.

2022-10-17 22:08 UTC, kodster28 commented on content/reference-architecture/magic-transit-reference-architecture.md
> +![Figure 1: Magic transit overview](/reference-architecture/static/magic-transit-ref-arch-diagrams/magic-transit-ref-arch-1.png)
These should always be absolute links, btw, which is what I updated them to.

2022-10-17 22:08 UTC, kodster28 commented on data/reference-architecture.yml
> +logo: <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48"><path d="M4 14h22v-4H4v4Zm0 8h22v-4H4v4Zm36 16H26v-4h14v4Zm-14-8h14v-4H26v4Zm34 24H26v-4h34v4Zm-34-8h34v-4H26v4Z"/></svg>
Need to update this to a new SVG (that isn't Zaraz :)  ).

2022-10-17 22:16 UTC, kodster28 commented on content/reference-architecture/magic-transit-reference-architecture.md
> +In many cases, [traffic is faster when routed over Cloudflare](https://www.cloudflare.com/static/360e550c8890054d5e5835efb9fb8dd1/Magic_Transit_protects_networks_while_also_improving_performance__1_.
I'd really prefer not to link to a static asset on the Marketing site and instead just link to the associated marketing page.

This hash will change if the file is updated and -- in all likelihood -- no one will update this link.

2022-10-17 22:37 UTC, haleycode commented on content/reference-architecture/magic-transit-reference-architecture.md
> +In many cases, [traffic is faster when routed over Cloudflare](https://www.cloudflare.com/static/360e550c8890054d5e5835efb9fb8dd1/Magic_Transit_protects_networks_while_also_improving_performance__1_.
Totally hear you, but I'll need to check in with the author before making the change.

2022-10-17 22:38 UTC, haleycode commented on content/reference-architecture/magic-transit-reference-architecture.md
> +![Figure 1: Magic transit overview](/reference-architecture/static/magic-transit-ref-arch-diagrams/magic-transit-ref-arch-1.png)
THANK YOU!

2022-10-17 22:38 UTC, haleycode commented on data/reference-architecture.yml
> +logo: <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48"><path d="M4 14h22v-4H4v4Zm0 8h22v-4H4v4Zm36 16H26v-4h14v4Zm-14-8h14v-4H26v4Zm34 24H26v-4h34v4Zm-34-8h34v-4H26v4Z"/></svg>
Done!

2022-10-18 15:24 UTC, kodster28 approved these changes

2022-10-18 16:05 UTC, merged