[Cache] Update purge by prefix normalization section
cloudflare/cloudflare-docs pull request #6408
Opened 2022-10-25 13:47 UTC by angelampcosta

2022-10-25 19:23 UTC, drcaramelsyrup requested changes

2022-10-25 19:23 UTC, drcaramelsyrup commented on content/cache/how-to/purge-cache.md
> +Using purge by prefix normalization, when a purge by prefix request comes into Cloudflare for a normalized URL path, the purge services respects the [URL normalization](/rules/normalization/) and pur
`services` -> `service`

2022-10-25 19:23 UTC, drcaramelsyrup commented on content/cache/how-to/purge-cache.md
> +#### Purge by prefix
I'm not sure this section is still necessary given the above table outlines the behavior difference between the settings.

If we want to add clarification, I do think we could replace it with a sentence like:

> As shown above, with URL normalization **on**, visitors to the two URLs, `https://cloudflare.com/%D8%A7%D9%86%D8%B4%D8%A7%D8%A1-%D9%85%D9%88%D9%82%D8%B9-%D8%A7%D9%84%D9%83%D8%AA%D8%B1%D9%88%D9%86%D9%8A/img_1.jpg` and `https://cloudflare.com/انشاء-موقع-الكتروني/img_1.jpg`, will be served the same cached asset. Purging `https://cloudflare.com/%D8%A7%D9%86%D8%B4%D8%A7%D8%A1-%D9%85%D9%88%D9%82%D8%B9-%D8%A7%D9%84%D9%83%D8%AA%D8%B1%D9%88%D9%86%D9%8A/img_1.jpg` will purge that asset for both visitors.

2022-10-26 09:38 UTC, pedrosousa approved these changes

2022-10-26 20:20 UTC, drcaramelsyrup approved these changes

2022-10-27 08:49 UTC, merged