[wrangler] deployment command
cloudflare/cloudflare-docs pull request #6461
Opened 2022-10-27 20:32 UTC by JacobMGEvans

Add documentation reference in command section of Wrangler for new  command feature.

2022-10-28 13:15 UTC, lrapoport-cf commented on content/workers/wrangler/commands.md
> +- [`deployments`](#deployments) - Logs the 10 most recent deployments with 'Version ID', 'Version number','Author name', and 'Latest deploy'.
to be consistent with the tense used in defining the other commands, suggest using the imperative mood. and to be consistent with how `whoami` is defined, suggest changing from "log" to "retrieve". also suggest we leave the info about what is returned in the detail section for the command

```suggestion
- [`deployments`](#deployments) - Retrieve details for the 10 most recent deployments.
```

2022-10-28 13:15 UTC, lrapoport-cf commented on content/workers/wrangler/commands.md
> +- `--name` {{<type>}}string{{</type>}} {{<prop-meta>}}optional{{</prop-meta>}}
what does this flag do? we should define

2022-10-28 13:15 UTC, lrapoport-cf commented on content/workers/wrangler/commands.md
> +Logs the 10 most recent deployments with 'Version ID', 'Version number','Author name', and 'Latest deploy'
```suggestion
Retrieve details for the 10 most recent deployments. Details include `Version ID`, `Version number`, `Author name`, and `Latest deploy`.
```

2022-10-28 14:08 UTC, JacobMGEvans commented on content/workers/wrangler/commands.md
> +- `--name` {{<type>}}string{{</type>}} {{<prop-meta>}}optional{{</prop-meta>}}
Done. Its allows you to specify a script name rather than Wrangler inferring it.

2022-10-28 19:48 UTC, lrapoport-cf approved these changes
approved but should not be merged until https://github.com/cloudflare/wrangler2/pull/2091 is merged

2022-10-31 19:26 UTC, lrapoport-cf requested changes

2022-10-31 19:26 UTC, lrapoport-cf commented on content/workers/wrangler/commands.md
> +Retrieve details for the 10 most recent deployments. Details include `Version ID`, `Version number`, `Author name`, and `Latest deploy`.
per https://github.com/cloudflare/wrangler2/pull/2091#discussion_r1009533087 and https://github.com/cloudflare/wrangler2/pull/2091#discussion_r1009557379: 

```suggestion
Retrieve details for the 10 most recent deployments. Details include `Version ID`, `Version number`, `Author email`, `Created on`, and `Latest deploy`.
```

2022-10-31 19:32 UTC, JacobMGEvans commented on content/workers/wrangler/commands.md
> +Retrieve details for the 10 most recent deployments. Details include `Version ID`, `Version number`, `Author name`, and `Latest deploy`.
Fixes on https://github.com/cloudflare/wrangler2/pull/2108

2022-10-31 19:33 UTC, JacobMGEvans commented on content/workers/wrangler/commands.md
> +Retrieve details for the 10 most recent deployments. Details include `Version ID`, `Version number`, `Author name`, and `Latest deploy`.
I thought this was a different PR lol

2022-10-31 19:36 UTC, lrapoport-cf approved these changes

2022-10-31 19:37 UTC, merged