[Radar] Add Radar api docs
cloudflare/cloudflare-docs pull request #6577
Opened 2022-11-07 17:14 UTC by meddulla

Add initial developers documentation for the Radar API (radar.cloudflare.com).

Right now, it's missing the icon and the license attribution will also be reviewed but wanted to start the process.

Tagging @marciocloudflare since he helped with the API docs.

2022-11-08 14:28 UTC, G4brym approved these changes

2022-11-11 16:01 UTC, marciocloudflare requested changes

2022-11-11 16:01 UTC, marciocloudflare commented on content/radar/_index.md
> +{{</button-group>}}
```suggestion
{{<beta>}}Cloudflare Radar{{</beta>}}

{{<description>}}
Get access to Cloudflare's data on global Internet traffic.
{{</description>}}

{{<plan type="all">}}

[Cloudflare Radar](https://radar.cloudflare.com) is a hub that showcases global Internet traffic, attacks, and technology trends and insights. It is powered by data from Cloudflare’s global network, as well as aggregated and anonymized data from Cloudflare’s [1.1.1.1 public DNS resolver](/1.1.1.1/).

Using Radar's API you can access Cloudflare's data on global Internet traffic.

Radar's API is free, allowing academics, data sleuths and other web enthusiasts to investigate Internet usage across the globe.

Usage of the API and its data is made available under the [CC BY-NC 4.0 license](https://creativecommons.org/licenses/by-nc/4.0/).

---

## Features

{{<feature header="Make your first API request" href="/radar/get-started/first-request/">}}
Start learning how to use Radar's API by making your first request.
{{</feature>}}

{{<feature header="Compare data" href="/radar/get-started/making-comparisons/">}}
What to know before making comparisons between locations, [autonomous systems](https://www.cloudflare.com/en-gb/learning/network-layer/what-is-an-autonomous-system/) and more.
{{</feature>}}
```

2022-11-11 16:01 UTC, marciocloudflare commented on content/radar/_index.md
> +{{</button-group>}}
Changing overview page to conform to style guide.

2022-11-11 16:01 UTC, marciocloudflare commented on content/radar/api-reference.md
> +weight: 7
```suggestion
weight: 5
```

2022-11-11 16:01 UTC, marciocloudflare commented on content/radar/concepts/_index.md
> +weight: 3
```suggestion
weight: 2
```

2022-11-11 16:01 UTC, marciocloudflare commented on content/radar/concepts/aggregation-intervals.md
> +weight: 2
```suggestion
title: Aggregation intervals
weight: 1
```

2022-11-11 16:01 UTC, marciocloudflare commented on content/radar/concepts/aggregation-intervals.md
> +# Aggregation Intervals
```suggestion
# Aggregation intervals
```

2022-11-11 16:01 UTC, marciocloudflare commented on content/radar/concepts/aggregation-intervals.md
> +
```suggestion
Aggregation intervals allow you to return data in a specified interval (or frequency). If no interval is defined, data will be returned in the default aggregation interval (or frequency). As a general principle, the longer the date range, the bigger the aggregation interval.

For example, when requesting one day of data, the default aggregation interval is 15 minutes. When requesting more than one month of data, the default is one day.
```

2022-11-11 16:01 UTC, marciocloudflare commented on content/radar/concepts/aggregation-intervals.md
> +| **1d** | 1 day frequency. |
```suggestion
| Aggregation Interval | Description |
| ---- | ---- |
| `15m` | 15 minutes frequency. |
| `1h` | One hour frequency. |
| `1d` | One day frequency. |
```

2022-11-11 16:01 UTC, marciocloudflare commented on content/radar/concepts/bot-classes.md
> +Bot traffic is comprised of requests with bot scores from 1 to 29, and non-bot/human traffic of bot scores above or equal to 30.
```suggestion
Scores between 1 to 29 are classified as bot traffic. Scores equal or above 30 are classified as non-bot/human traffic.
```

2022-11-11 16:01 UTC, marciocloudflare commented on content/radar/concepts/confidence-levels.md
> +The `result.meta.confidenceInfo.level` in the response will provide an indication of how much confidence we have in the data, either due to internal issues affecting data quality or due to simply not
```suggestion
The `result.meta.confidenceInfo.level` in the response provides an indication of how much confidence Cloudflare has in the data. Confidence levels can be affected either by internal issues affecting data quality or by not having a lot of data for a given location (like Antarctica) or Autonomous System (AS).
```

2022-11-11 16:01 UTC, marciocloudflare commented on content/radar/concepts/bot-classes.md
> +| **Likely Human** | Bot scores of 30 through 99. |
```suggestion
| **Likely automated** | Bot scores of 1 through 29. |
| **Likely human** | Bot scores of 30 through 99. |
```

2022-11-11 16:01 UTC, marciocloudflare commented on content/radar/concepts/confidence-levels.md
> +| **5** | No known data quality issues. |
```suggestion
| **1** | There is not enough data in this time range and/or for this location or Autonomous System. Data also exhibits an erratic pattern, possibly due to the reasons previously mentioned.  |
| **2** | There is not enough data in this timerange and/or in this location or Autonomous System. |
| **3** | Data exhibits an erratic pattern but is not affected by known data issues (like pipeline issues). |
| **4** | Unassigned. |
| **5** | No known data quality issues. |
```

2022-11-11 16:01 UTC, marciocloudflare commented on content/radar/concepts/confidence-levels.md
> +weight: 2
```suggestion
weight: 3
```

2022-11-11 16:01 UTC, marciocloudflare commented on content/radar/concepts/normalization.md
> +weight: 2
```suggestion
weight: 4
```

2022-11-11 16:01 UTC, marciocloudflare commented on content/radar/concepts/normalization.md
> +Cloudflare Radar does not normally return raw values, values are instead returned as percentages or normalized using min max.
```suggestion
Cloudflare Radar does not normally return raw values. Instead, values are returned as percentages or normalized using min-max.
```

2022-11-11 16:01 UTC, marciocloudflare commented on content/radar/concepts/normalization.md
> +
```suggestion
Refer to the `result.meta.normalization` property in the response to check which post-processing method was applied to the raw values, if any.
```

2022-11-11 16:01 UTC, marciocloudflare commented on content/radar/concepts/normalization.md
> +| **RAW_VALUES** | Values are raw and have not been changed. |
```suggestion
| `PERCENTAGE` | Values represent percentages. |
| `PERCENTAGE_CHANGE` | Values represent a [percentage change](https://en.wikipedia.org/wiki/Relative_change_and_difference#Percentage_change) from a baseline period. |
| `MIN_MAX` | Values have been normalized using [min-max](https://en.wikipedia.org/wiki/Feature_scaling#Rescaling_(min-max_normalization)).|
| `MIN0_MAX` | Values have been normalized using min-max, but setting the minimum value to `0`. Equivalent to a proportion of the maximum value in the entire response, scaled between 0 and 1.|
| `RAW_VALUES` | Values are raw and have not been changed. |
```

2022-11-11 16:01 UTC, marciocloudflare commented on content/radar/concepts/normalization.md
> +
```suggestion
If you want to compare values across locations/time ranges/etc., in endpoints that normalize values using min-max, you must do so in the same request. This is done by asking for multiple series. All values will then be normalized using the same minimum and maximum value and can safely be compared against each other. Refer to [Making comparisons](/radar/get-started/making-comparisons) for more information.
```

2022-11-11 16:01 UTC, marciocloudflare commented on content/radar/get-started/_index.md
> +title: Get Started
```suggestion
title: Get started
```

2022-11-11 16:01 UTC, marciocloudflare commented on content/radar/get-started/_index.md
> +# Get Started
```suggestion
# Get started
```

2022-11-11 16:01 UTC, marciocloudflare commented on content/radar/get-started/first-request.md
> +weight: 3
```suggestion
weight: 1
```

2022-11-11 16:01 UTC, marciocloudflare commented on content/radar/get-started/first-request.md
> +title: Make your first API request
```suggestion
title: Make your first API request
meta:
    title: Make your first Radar API request
```

2022-11-11 16:01 UTC, marciocloudflare commented on content/radar/get-started/first-request.md
> +Once you have the token, you are ready to make your first request to Radar's API hosted at `https://api.cloudflare.com/client/v4/radar/`.
```suggestion
To make your first request to Cloudflare's Radar API, you must obtain your [API token](/fundamentals/api/get-started/create-token/) first. Create a Custom Token, with _User_ > _User Details_ in the **Permissions** group, and select _Edit_ as the access level.

Once you have the token, you are ready to make your first request to Radar's API at `https://api.cloudflare.com/client/v4/radar/`.
```

2022-11-11 16:01 UTC, marciocloudflare commented on content/radar/get-started/first-request.md
> +## Using curl
```suggestion
## Example using cURL
```

2022-11-11 16:01 UTC, marciocloudflare commented on content/radar/get-started/first-request.md
> +In the following example, let's look at the global percentage distribution of device types, e.g. mobile and desktop traffic, for the last 7 days (for more information refer to this [endpoint's refere
```suggestion
In the following example, we will access the global percentage distribution of device types (like mobile and desktop traffic) for the last seven days. For more information, refer to [Get a summary of device types](https://api.cloudflare.com/#radar-http-get-a-summary-of-device-types) endpoint:
```

2022-11-11 16:01 UTC, marciocloudflare commented on content/radar/get-started/first-request.md
> +You should get something like this:
```suggestion
A successful response will look similar to the following:
```

2022-11-11 16:01 UTC, marciocloudflare commented on content/radar/get-started/first-request.md
> +Out of all requests, 41% are classified as coming from mobile devices.
```suggestion
This response means that 41% of the requests are classified as coming from mobile devices, while 58% are desktop traffic.
```

2022-11-11 16:01 UTC, marciocloudflare commented on content/radar/get-started/first-request.md
> +{{<Aside type="note" >}} Cloudflare Radar attempts to provide trends and insights into general Internet usage, using the traffic that Cloudflare sees. As such, it only provides data on _eyeball_ traf
```suggestion
{{<Aside type="note" >}} Cloudflare Radar attempts to provide trends and insights into general Internet usage, using the traffic that goes through Cloudflare infrastructure. As such, Cloudflare Radar only provides data on traffic coming from end-users, unless otherwise specified (for example, origin fetches are excluded).
```

2022-11-11 16:01 UTC, marciocloudflare commented on content/radar/get-started/first-request.md
> +Above, you are looking at _all_ traffic but you can also look at just traffic classified as coming from humans (the default in [Cloudflare Radar](https://radar.cloudflare.com)) by adding `botClass=LI
```suggestion
The previous example returns all traffic from bots and humans. However, you can access just the traffic classified as coming from humans (the default in [Cloudflare Radar](https://radar.cloudflare.com)) by adding `botClass=LIKELY_HUMAN`. You can also access traffic coming only from bots with `botClass=LIKELY_AUTOMATED` (refer to [bot classes](/radar/concepts/bot-classes) for more information). For example:
```

2022-11-11 16:01 UTC, marciocloudflare commented on content/radar/get-started/first-request.md
> +
```suggestion
```

2022-11-11 16:01 UTC, marciocloudflare commented on content/radar/get-started/first-request.md
> +
We don't really have this kind of language on dev docs :)

2022-11-11 16:01 UTC, marciocloudflare commented on content/radar/get-started/first-request.md
> +{{</Aside>}}
```suggestion
{{<Aside type="note" header="The <code>result.meta</code> property">}}
The `result.meta` property in the response includes metadata about the current request. In the example above, `meta.dateRange` returns the date range specified in the query, while `meta.normalization` returns the type of normalization applied to the data (refer to [Normalization methods](/radar/concepts/normalization) for more information).

When querying for timeseries, `result.meta` will also include the returned [aggregation interval](/radar/concepts/aggregation-intervals) in `meta.aggInterval`.

When present, `meta.confidenceInfo.level` will also provide an indication of how much confidence Cloudflare has in the data. Confidence levels are affected either by internal issues affecting data quality or by Cloudflare not having sufficient data for a given location or Autonomous System (AS). In these cases, confidence level will be below `5` (refer to [Confidence levels](/radar/concepts/confidence-levels) for more information).
{{</Aside>}}
```

2022-11-11 16:01 UTC, marciocloudflare commented on content/radar/get-started/first-request.md
> +[Python](https://www.python.org/) has become one of the standard languages in data analysis so here's quick example on how to chart the same data using [Requests](https://pypi.org/project/requests/)
```suggestion
[Python](https://www.python.org/) has become one of the standard languages in data analysis. Here is a quick example on how to chart the same data using [Requests](https://pypi.org/project/requests/) and [Pandas](https://pandas.pydata.org/) libraries. Here, we are using `format=csv` in the parameters to make it easier for Pandas to import.
```

2022-11-11 16:01 UTC, marciocloudflare commented on content/radar/get-started/first-request.md
> +{{</button-group>}}
```suggestion
Refer to [Making comparisons](/radar/get-started/making-comparisons) to learn how to compare data.
```

2022-11-11 16:01 UTC, marciocloudflare commented on content/radar/get-started/making-comparisons.md
> +weight: 3
```suggestion
weight: 2
```

2022-11-11 16:01 UTC, marciocloudflare commented on content/radar/get-started/making-comparisons.md
> +When comparing time series, across locations/time ranges/etc, in endpoints that normalize values using [MinMax](/radar/concepts/normalization), we __must__ do so in the __same__ request, by asking fo
```suggestion
When comparing time series, across locations/time ranges/etc., in endpoints that normalize values using [min-max](/radar/concepts/normalization), you must do so in the same request. This is done by asking for multiple series. All values will then be normalized using the same minimum and maximum value and can safely be compared against each other.
```

2022-11-11 16:01 UTC, marciocloudflare commented on content/radar/get-started/making-comparisons.md
> +[Netflows](/radar/investigate/netflows.md) values are normalized using [Min0Max](/radar/concepts/normalization), so we'll use it as an example ([API reference](https://api.cloudflare.com/#radar-netfl
```suggestion
[Netflows](/radar/investigate/netflows) values are normalized using [min0-max](/radar/concepts/normalization), so we will use it as an example. Refer to [Get NetFlow time series](https://api.cloudflare.com/#radar-netflows-get-netflow-time-series) for more information.
```

2022-11-11 16:01 UTC, marciocloudflare commented on content/radar/get-started/making-comparisons.md
> +Let's compare the traffic change across different locations, United States and Portugal (using [alpha-2 codes](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements)), fo
```suggestion
In the following example, we will compare the traffic change across two different locations — United States and Portugal. The example will use [alpha-2 codes](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements), for the last seven days:
```

2022-11-11 16:01 UTC, marciocloudflare commented on content/radar/get-started/making-comparisons.md
> +Here, we're asking for 2 timeseries. The 1st series has these parameters:
```suggestion
In the example above we are asking for two timeseries. The first series has the following parameters:
```

2022-11-11 16:01 UTC, marciocloudflare commented on content/radar/get-started/making-comparisons.md
> +`
```suggestion
`name=us_data&dateRange=7d&location=US`
```

2022-11-11 16:01 UTC, marciocloudflare commented on content/radar/get-started/making-comparisons.md
> +`
```suggestion
The second series has the following parameters:

`name=pt_data&dateRange=7d&location=PT`
```

2022-11-11 16:01 UTC, marciocloudflare commented on content/radar/get-started/making-comparisons.md
> +All of these parameters are arrays and it's the position in the array that defines the series the filter belongs to. For more information on the available parameters refer to the [endpoint's referenc
```suggestion
All of these parameters are arrays and it is the position in the array that defines the series the filter belongs to. Refer to [NetFlow's endpoint](https://api.cloudflare.com/#radar-netflows-get-netflow-time-series) for more information on the available parameters.
```

2022-11-11 16:01 UTC, marciocloudflare commented on content/radar/get-started/making-comparisons.md
> +The response (shortened below for brevity) uses the provided `name` property to wrap the timestamps and corresponding values. Charting these, it would be obvious that Cloudflare received much less tr
```suggestion
The response (shortened below for brevity) uses the provided `name` property to wrap the timestamps and corresponding values. If we chart this data, it becomes obvious that Cloudflare received much less traffic from Portugal than from the United States.
```

2022-11-11 16:01 UTC, marciocloudflare commented on content/radar/get-started/making-comparisons.md
> +Take into account that comparisons can be made in most endpoints, not just endpoints that use `MinMax`.
```suggestion
Comparisons can be made in most endpoints, not just endpoints that use `min-max`.
```

2022-11-11 16:01 UTC, marciocloudflare commented on content/radar/get-started/making-comparisons.md
> +Let's compare the same location, United States, across different date ranges, using the shortcuts `7d` and `7dControl`, which respectively mean, the last 7 days, and the last 7 days before those, so
```suggestion
In the next example, we will compare the United States across different date ranges using the shortcuts `7d` and `7dControl`. These mean the last seven days and the last seven days before those, respectively — or, in other words, this week versus the previous week.
```

2022-11-11 16:01 UTC, marciocloudflare commented on content/radar/get-started/making-comparisons.md
> +`
```suggestion
The first series has these parameters:

`name=this_week&dateRange=7d&location=US`

The second series has the following parameters:

`name=previous_week&dateRange=7dControl&location=US`
```

2022-11-11 16:01 UTC, marciocloudflare commented on content/radar/get-started/making-comparisons.md
> +And now, inside the `result` property, you should see something like this:
```suggestion
Now, in the `result` property, you should get something like this:
```

2022-11-11 16:01 UTC, marciocloudflare commented on content/radar/get-started/making-comparisons.md
> +Looking at this, we see that the maximum value was reached at `2022-10-27T14:00:00Z` (all Radar timestamps are in  `UTC`). We also see what the date range shortcuts `7d` and `7dControl` were resolved
```suggestion
Examining this information, we can conclude that the maximum value was reached at `2022-10-27T14:00:00Z` (all Radar timestamps are in Coordinated Universal Time (UTC)). We can also check what the date range shortcuts `7d` and `7dControl` were resolved to at the time this was run.
```

2022-11-11 16:01 UTC, marciocloudflare commented on content/radar/get-started/making-comparisons.md
> +title: Making comparisons
```suggestion
title: Make comparisons
```

2022-11-11 16:01 UTC, marciocloudflare commented on content/radar/get-started/making-comparisons.md
> +# Making comparisons
```suggestion
# Make comparisons
```

2022-11-11 16:01 UTC, marciocloudflare commented on content/radar/get-started/making-comparisons.md
> +## Comparing locations
```suggestion
## Compare locations
```

2022-11-11 16:01 UTC, marciocloudflare commented on content/radar/get-started/making-comparisons.md
> +## Comparing date ranges
```suggestion
## Compare date ranges
```

2022-11-11 16:01 UTC, marciocloudflare commented on content/radar/get-started/first-request.md
> +## Using Python
```suggestion
## Use Python
```

2022-11-11 16:01 UTC, marciocloudflare commented on content/radar/get-started/making-comparisons.md
> +### Using specific timestamps
```suggestion
### Use specific timestamps
```

2022-11-11 16:01 UTC, marciocloudflare commented on content/radar/get-started/making-comparisons.md
> +
```suggestion
You can also request for specific timestamps. In the following example, we will ask for data relative to [Tonga](https://blog.cloudflare.com/tonga-internet-outage/) in October versus January 2022, when there was an outage.
```

2022-11-11 16:01 UTC, marciocloudflare commented on content/radar/get-started/making-comparisons.md
> +`
```suggestion
The first series has these parameters (URL encoded):

`name=tonga&dateStart=2022-10-15T02%3A00%3A00Z&dateEnd=2022-10-15T05%3A00%3A00Z%&location=TO`

The second series has these parameters:

`name=tonga_outage&dateStart=2022-01-15T02%3A00%3A00Z&&dateEnd=2022-01-15T05%3A00%3A00Z&location=TO`
```

2022-11-11 16:01 UTC, marciocloudflare commented on content/radar/get-started/making-comparisons.md
> +Inside the `result` property, you should see something like this:
```suggestion
The `result` property should return a response like this:
```

2022-11-11 16:01 UTC, marciocloudflare commented on content/radar/get-started/making-comparisons.md
> +Traffic dropped to almost 0 during the outage. Charting it (but setting the end date to January 18 to make it clearer):
```suggestion
This shows how traffic dropped to almost zero during the outage. If we chart it and set the end date to January 18 to make it clearer, we get the following:
```

2022-11-11 16:01 UTC, marciocloudflare commented on content/radar/get-started/making-comparisons.md
> +{{</button-group>}}
```suggestion
Refer to the Investigate section to drill down on the data Radar returns, such as [NetFlows](/radar/investigate/netflows).
```

2022-11-11 16:01 UTC, marciocloudflare commented on content/radar/get-started/making-comparisons.md
> +We also asked for an [aggregation interval](/radar/concepts/aggregation-intervals) of 1 hour (`aggInterval=1h`), so that all results could be placed here (both `format` and `aggInterval` are not arra
```suggestion
In the above example, we requested for an [aggregation interval](/radar/concepts/aggregation-intervals) of one hour (`aggInterval=1h`), so that the results could be shown in this page. `format` and `aggInterval` are not arrays, as specified in the [API reference](https://api.cloudflare.com/#radar-netflows-get-netflow-time-series), and apply globally to all series in the request.
```

2022-11-14 12:53 UTC, marciocloudflare requested changes

2022-11-14 12:53 UTC, marciocloudflare commented on content/radar/investigate/_index.md
> +weight: 3
```suggestion
weight: 4
```

2022-11-14 12:53 UTC, marciocloudflare commented on content/radar/investigate/_index.md
> +
I think we could add a small intro here to explain what this section is all about. Wdyt?

2022-11-14 12:53 UTC, marciocloudflare commented on content/radar/investigate/dns.md
> +weight: 3
```suggestion
weight: 2
```

2022-11-14 12:53 UTC, marciocloudflare commented on content/radar/investigate/http-requests.md
> +weight: 3
```suggestion
weight: 2
```

2022-11-14 12:53 UTC, marciocloudflare commented on content/radar/investigate/netflows.md
> +weight: 3
```suggestion
weight: 1
```

2022-11-14 12:53 UTC, marciocloudflare commented on content/radar/investigate/network-layer-attacks.md
> +weight: 3
```suggestion
weight: 6
```

2022-11-14 12:53 UTC, marciocloudflare commented on content/radar/investigate/outages.md
> +weight: 3
```suggestion
weight: 7
```

2022-11-14 12:53 UTC, marciocloudflare commented on content/radar/investigate/application-layer-attacks.md
> +While in [HTTP requests](/radar/investigate/http-requests) we were looking at all kinds of web requests, here we're looking at only _mitigated_ HTTP requests. These requests can be mitigated by one o
```suggestion
While in [HTTP requests](/radar/investigate/http-requests) you can examine all kinds of web requests, in application layer attacks you have access only to mitigated HTTP requests. These requests can be mitigated by one of several Cloudflare products, like [WAF](/waf/), [Cloudflare DDoS Protection](/ddos-protection/), [Cloudflare bot solutions](/bots/) and others.
```

2022-11-14 12:53 UTC, marciocloudflare commented on content/radar/investigate/application-layer-attacks.md
> + {{</Aside>}}
```suggestion
{{<Aside type="note" header="Mitigated traffic">}}
Mitigated traffic is any HTTP request from an end-user that has a terminating action applied by the Cloudflare platform. These include actions like `BLOCK` or `CHALLENGE` in captchas or JavaScript based challenges.
{{</Aside>}}
```

2022-11-14 12:53 UTC, marciocloudflare commented on content/radar/investigate/application-layer-attacks.md
> +Since we're looking at attacks, we can look at both sides of an attack, the source location of the attack and the target location of the attack. For the source of the attack, the location associated
```suggestion
Since we are examining attacks, we can inspect both sides of an attack — both the source location and the target location of the attack. For the source of the attack Cloudflare uses the location the attack is coming from associated with the IP (take into account that the human orchestrator of the attack may be in a different location than the computer the attack is originating from). For the target location of the attacks, Cloudflare uses the billing location associated with the zone under attack.
```

2022-11-14 12:53 UTC, marciocloudflare commented on content/radar/investigate/application-layer-attacks.md
> +This ability to filter by both sides of the attack is only available in the `top locations` endpoints. Others, unless otherwise specified, are filtering by _source_ location, i.e. the origin location
```suggestion
This ability to filter by both sides of the attack is only available in the `top locations` endpoints. Unless otherwise specified, other endpoints are filtered by source location, like the origin location of the attack.
```

2022-11-14 12:53 UTC, marciocloudflare commented on content/radar/investigate/application-layer-attacks.md
> +With regards to attacks magnitude, it's defined by the total number of mitigated requests unless otherwise specified.
```suggestion
The magnitute of the attack  is defined by the total number of mitigated requests, unless otherwise specified.
```

2022-11-14 12:53 UTC, marciocloudflare commented on content/radar/investigate/application-layer-attacks.md
> +## Timeseries
```suggestion
## List of endpoints

### Timeseries
```

2022-11-14 12:53 UTC, marciocloudflare commented on content/radar/investigate/application-layer-attacks.md
> +Let's look at the global distribution of mitigated requests by product:
```suggestion
#### Example: houly mitigation requests by product

Let us examine the global distribution of mitigated requests by product.
```

2022-11-14 12:53 UTC, marciocloudflare commented on content/radar/investigate/application-layer-attacks.md
> +## Summary
```suggestion
### Summary
```

2022-11-14 12:53 UTC, marciocloudflare commented on content/radar/investigate/application-layer-attacks.md
> +## Top
```suggestion
### Top
```

2022-11-14 12:53 UTC, marciocloudflare commented on content/radar/investigate/application-layer-attacks.md
> +Looking at the abbreviated response below, we see that DDoS makes up the majority of the requests (which makes sense since by the very nature of this attack type it will perform more requests), follo
```suggestion
From the abbreviated response below, we can conclude that distributed denial-of-service (DDoS) attacks make up the majority of the requests — which makes sense since DDoS attacks, by their very nature, will perform more requests. This is followed by WAF and then I reputation requests.
```

2022-11-14 12:53 UTC, marciocloudflare commented on content/radar/investigate/application-layer-attacks.md
> +For more information refer to the [API reference](https://api.cloudflare.com/#radar-attacks-get-layer-7-attacks-by-mitigation-technique-over-time) for this endpoint.
```suggestion
For more information refer to [Get layer 7 attacks by mitigation technique, over time](https://api.cloudflare.com/#radar-attacks-get-attacks-layer-7-time-series).
```

2022-11-14 12:53 UTC, marciocloudflare commented on content/radar/investigate/application-layer-attacks.md
> +For more information refer to the [API reference](https://api.cloudflare.com/#radar-attacks-get-layer-7-attacks-by-mitigation-technique-over-time) for this endpoint.
The link didn't work, so I changed it to the overall section

2022-11-14 12:53 UTC, marciocloudflare commented on content/radar/investigate/application-layer-attacks.md
> +### Example: Great Britain - overall percentage breakdown by attack mitigation product
```suggestion
#### Example: Mitigation requests by product
```

2022-11-14 12:53 UTC, marciocloudflare commented on content/radar/investigate/application-layer-attacks.md
> +We can also filter by _source_ location and look at attacks coming _from_ Great Britain:
```suggestion
We can also filter by source location and examine attacks coming from a specific place - in the following example, we examine attacks coming from Great Britain:
```

2022-11-14 12:53 UTC, marciocloudflare commented on content/radar/investigate/application-layer-attacks.md
> +This can read as, 75% of all mitigated requests coming from Great Britain were mitigated by the [WAF](/waf) product.
```suggestion
This response means that 75% of all mitigated requests coming from Great Britain were mitigated by the [WAF](/waf/) product.
```

2022-11-14 12:53 UTC, marciocloudflare commented on content/radar/investigate/application-layer-attacks.md
> +For more information refer to the [API reference](https://api.cloudflare.com/#radar-attacks-get-a-summary-of-layer-7-attacks) for this endpoint.
```suggestion
For more information refer to [Get a summary of layer 7 attacks](https://api.cloudflare.com/#radar-attacks-get-a-summary-of-layer-7-attacks).
```

2022-11-14 12:53 UTC, marciocloudflare commented on content/radar/investigate/application-layer-attacks.md
> +### Example: Top target locations
```suggestion
#### Example: Top target locations
```

2022-11-14 12:53 UTC, marciocloudflare commented on content/radar/investigate/application-layer-attacks.md
> +Let's look at the top locations being targeted in application layer attacks, in the last 24 hours:
```suggestion
In the following example, we will examine the top locations being targeted in application layer attacks, in the last 24 hours:
```

2022-11-14 12:53 UTC, marciocloudflare commented on content/radar/investigate/application-layer-attacks.md
> +Mitigated requests to zones with a billing address located in Belgium make up about 18% of all mitigated requests, during the specified date range.
```suggestion
During the specified date range, mitigation requests to zones with a billing address located in Belgium represent 18%.
```

2022-11-14 12:53 UTC, marciocloudflare commented on content/radar/investigate/application-layer-attacks.md
> +For more information refer to the [API reference](https://api.cloudflare.com/#radar-attacks-get-layer-7-top-target-locations) for this endpoint.
```suggestion
For more information refer to [Get layer 7 top target locations](https://api.cloudflare.com/#radar-attacks-get-layer-7-top-target-locations).
```

2022-11-14 12:53 UTC, marciocloudflare commented on content/radar/investigate/application-layer-attacks.md
> +### Example: Top attacks
```suggestion
#### Example: Top attacks
```

2022-11-14 12:53 UTC, marciocloudflare commented on content/radar/investigate/application-layer-attacks.md
> +
```suggestion

A typical response will be similar to the following:

```

2022-11-14 12:53 UTC, marciocloudflare commented on content/radar/investigate/application-layer-attacks.md
> +This can be read as, 3.79% of all mitigated requests are from and to the US, 3.6% of all mitigated requests are from the US to Belgium, etc. This is using attack magnitude as the sum of mitigated req
```suggestion
This means that 3.79% of all mitigated requests are from and to the US, 3.6% of all mitigated requests are from the US to Belgium, etc.. 

This response came from a query that is using attack `magnitude` as the sum of mitigated requests. To use the number of unique zones attacked as the metric, for example, use `attack_magnitude=AFFECTED_ZONES`.
```

2022-11-14 12:53 UTC, marciocloudflare commented on content/radar/investigate/application-layer-attacks.md
> +For more information refer to the [API reference](https://api.cloudflare.com/#radar-attacks-get-layer-7-top-attack-pairs-origin-and-target-locations) for this endpoint.
```suggestion
For more information refer to [Get layer 7 top attack pairs](https://api.cloudflare.com/#radar-attacks-get-layer-7-top-attack-pairs-origin-and-target-locations-).
```

2022-11-14 12:53 UTC, marciocloudflare commented on content/radar/investigate/application-layer-attacks.md
> +{{</button-group>}}
```suggestion
Refer to [Network layer attacks](/radar/investigate/network-layer-attacks/) for more information on data on layer 3 of the Open Systems Interconnection (OSI) model.
```

2022-11-14 12:53 UTC, marciocloudflare commented on content/radar/investigate/application-layer-attacks.md
> +{{</button-group>}}
We don't have buttons or button groups for Next steps. Feel free to edit my suggestion, though

2022-11-14 14:28 UTC, carlosefr requested changes

2022-11-14 14:28 UTC, carlosefr commented on content/radar/_index.md
> +[Cloudflare Radar](https://radar.cloudflare.com) is a hub that showcases global Internet traffic, attacks, and technology trends and insights. It is powered by data from Cloudflare’s global network,
"anonymized" could probably be a link to 1.1.1.1's privacy policy.

2022-11-14 14:28 UTC, carlosefr commented on content/radar/_index.md
> +Using Radar's API you can now access Cloudflare's data on global Internet traffic as well.
Perhaps drop the "now" as it anchors the text in time.

2022-11-14 14:28 UTC, carlosefr commented on content/radar/_index.md
> +[Making comparisons](/radar/get-started/making-comparisons/) - What to know before making comparisons between locations, [ASes](https://www.cloudflare.com/en-gb/learning/network-layer/what-is-an-auto
It's the first time "AS" is used here, so it should be "autonomous systems (AS)".

2022-11-14 14:28 UTC, carlosefr commented on content/radar/_index.md
> +[Application level attacks](/radar/investigate/application-layer-attacks/) - Investigate Layer 7 cyber attacks trends and patterns.
"Layer 7" could be a link to https://www.cloudflare.com/en-gb/learning/ddos/what-is-layer-7/

2022-11-14 14:28 UTC, carlosefr commented on content/radar/_index.md
> +[Network level attacks](/radar/investigate/network-layer-attacks/) - Investigate Layer 3/4 cyber attacks trends and patterns.
"Layer 3"  could be a link to https://www.cloudflare.com/en-gb/learning/ddos/layer-3-ddos-attacks/

2022-11-14 14:28 UTC, carlosefr commented on content/radar/concepts/aggregation-intervals.md
> +When requesting time series, data may be returned in one of a series of aggregation intervals, or frequencies, if none is specified, according to the date range. As a general principle, the longer th
```suggestion
When requesting time series, data may be returned in one of several aggregation intervals, or frequencies, if none is specified, according to the date range. As a general principle, the longer the date range, the bigger the aggregation interval.
```

2022-11-14 14:28 UTC, carlosefr commented on content/radar/concepts/aggregation-intervals.md
> +For example, when requesting 1 day of data, the default aggregation interval is 15 minutes, when requesting more than 1 month of data, the default is 1 day.
```suggestion
For example, when requesting 1 day of data, the default aggregation interval is 15 minutes. When requesting more than 1 month of data, the default is 1 day.
```

2022-11-14 14:28 UTC, carlosefr commented on content/radar/concepts/normalization.md
> +Cloudflare Radar does not normally return raw values, values are instead returned as percentages or normalized using min max.
"normalized using min max" over all returned timeseries.

2022-11-14 14:28 UTC, carlosefr commented on content/radar/get-started/first-request.md
> +  headers={ "Authorization": f"Bearer {my_token}"})
```suggestion
                 headers={"Authorization": f"Bearer {my_token}"})
```

2022-11-14 14:28 UTC, carlosefr commented on content/radar/investigate/dns.md
> +  -H "Authorization: Bearer <API_TOKEN>"
```suggestion
     -H "Authorization: Bearer <API_TOKEN>"
```

2022-11-14 14:28 UTC, carlosefr commented on content/radar/investigate/dns.md
> +  -H "Content-Type: application/json"
```suggestion
     -H "Authorization: Bearer <API_TOKEN>" \
     -H "Content-Type: application/json"
```

2022-11-14 14:28 UTC, carlosefr commented on content/radar/investigate/domain-ranking-datasets.md
> +  -H "Authorization: Bearer <API_TOKEN>"
```suggestion
     -H "Authorization: Bearer <API_TOKEN>"
```

2022-11-14 14:28 UTC, carlosefr commented on content/radar/investigate/domain-ranking-datasets.md
> +  -H "Authorization: Bearer <API_TOKEN>"
```suggestion
     -H "Authorization: Bearer <API_TOKEN>"
```

2022-11-14 14:28 UTC, carlosefr commented on content/radar/investigate/outages.md
> +  -H "Authorization: Bearer <API_TOKEN>"
```suggestion
     -H "Authorization: Bearer <API_TOKEN>"
```

2022-11-14 14:28 UTC, carlosefr commented on content/radar/investigate/application-layer-attacks.md
> +}
```suggestion
{
  "success": true,
  "errors": [],
  "result": {
    "attacks": {
      "timestamps": ["2022-11-05T11:00:00Z", ".."],
      "ddos": ["53.824302", "54.305823",  ".."],
      "waf": ["39.760956", "39.31228",  ".."],
      "ip_reputation": ["5.623487", "5.485468",  ".."],
      "access_rules": ["0.648368", "0.676456",  ".."],
      "bot_management": ["0.139733", "0.217155",  ".."],
      "api_shield": ["0.003154", "0.002819",  ".."],
      "data_loss_prevention": ["0.0", "0.0",  ".."]
    },
    "meta": {
      "dateRange": {
        "startTime": "2022-11-05T11:00:00Z",
        "endTime": "2022-11-06T11:00:00Z"
      },
    }
  }
}
```

2022-11-14 14:28 UTC, carlosefr commented on content/radar/investigate/application-layer-attacks.md
> +}
```suggestion
{
  "success": true,
  "errors": [],
  "result": {
    "attacks_target": [{
      "targetCountryName": "Belgium",
      "targetCountryAlpha2": "BE",
      "value": "18.536740",
      "rank": 1
    }, {
      "targetCountryName": "United States",
      "targetCountryAlpha2": "US",
      "value": "16.116210",
      "rank": 2
    }, {
      "targetCountryName": "China",
      "targetCountryAlpha2": "CN",
      "value": "13.864696",
      "rank": 3
    }, {
      "targetCountryName": "India",
      "targetCountryAlpha2": "IN",
      "value": "4.344139",
      "rank": 4
    }, {
      "targetCountryName": "Germany",
      "targetCountryAlpha2": "DE",
      "value": "4.182777",
      "rank": 5
    }],
    "meta": {
      "dateRange": {
        "startTime": "2022-11-05T12:00:00Z",
        "endTime": "2022-11-06T12:00:00Z"
      },
    }
  }
}
```

2022-11-14 14:28 UTC, carlosefr commented on content/radar/investigate/http-requests.md
> +}
```suggestion
"human": {
  "mobile": "54.967243",
  "desktop": "44.974006",
  "other": "0.058751"
},
"bot": {
  "desktop": "83.275452",
  "mobile": "16.707455",
  "other": "0.017093"
}
```

2022-11-14 14:28 UTC, carlosefr commented on content/radar/investigate/netflows.md
> +},
```suggestion
"AS3243_all": {
  "timestamps": ["2022-11-08T14:00:00Z", "2022-11-08T15:00:00Z", "..."],
  "values": ["0.565885", "0.586434", "..."]
},
"AS3243_http": {
  "timestamps": ["2022-11-08T14:00:00Z", "2022-11-08T15:00:00Z", "..."],
  "values": ["0.548564", "0.568329", "..."]
},
```

2022-11-14 14:28 UTC, carlosefr commented on content/radar/investigate/netflows.md
> +}
```suggestion
"AS174_all": {
  "timestamps": ["2022-11-08T14:00:00Z", "2022-11-08T15:00:00Z", "..."],
  "values": ["0.917348", "1.0", "..."]
},
"AS174_http": {
  "timestamps": ["2022-11-08T14:00:00Z", "2022-11-08T15:00:00Z", "..."],
  "values": ["0.381777", "0.408091", "..."]
}
```

2022-11-14 14:28 UTC, carlosefr commented on content/radar/investigate/network-layer-attacks.md
> +}
```suggestion
{
  "success": true,
  "errors": [],
  "result": {
    "global": {
      "timestamps": ["2022-11-06T13:00:00Z", "2022-11-06T14:00:00Z", "..."],
      "udp": ["50.784034", "51.055221", "..."],
      "tcp": ["49.213944", "48.943769", "..."],
      "icmp": ["0.002023", "0.001009", "..."],
      "gre": ["0.0", "0.0", "0.0", "..."]
    },
    "singapore": {
      "timestamps": ["2022-11-06T13:00:00Z", "2022-11-06T14:00:00Z", "..."],
      "tcp": ["79.605287", "83.943885", "..."],
      "udp": ["20.394594", "16.056115", "..."],
      "icmp": ["0.000119", "0.0", "..."],
      "gre": ["0.0", "0.0", "..."]
    },
    "meta": {
      "dateRange": {
        "startTime": "2022-11-06T13:00:00Z",
        "endTime": "2022-11-07T13:00:00Z"
      },
      "normalization": "PERCENTAGE",
    }
  }
}
```

2022-11-14 14:28 UTC, carlosefr commented on content/radar/investigate/network-layer-attacks.md
> +}
```suggestion
{
  "success": true,
  "errors": [],
  "result": {
    "attacks_ru": {
      "udp": "86.682356",
      "tcp": "11.928664",
      "gre": "1.381015",
      "icmp": "0.007965"
    },
    "meta": {
      "dateRange": {
        "startTime": "2022-11-06T15:00:00Z",
        "endTime": "2022-11-07T15:00:00Z"
      },
      "normalization": "PERCENTAGE"
    }
  }
}
```

2022-11-14 17:36 UTC, marciocloudflare requested changes

2022-11-14 17:36 UTC, marciocloudflare commented on content/radar/investigate/dns.md
> +Access aggregated and anonymized DNS queries to our [1.1.1.1](https://1.1.1.1/dns/) public resolver service.
```suggestion
Access aggregated and anonymized DNS queries to Cloudflare's [1.1.1.1](/1.1.1.1//) public resolver service.
```

2022-11-14 17:36 UTC, marciocloudflare commented on content/radar/investigate/dns.md
> +## Top locations
```suggestion
## List of endpoints

### Top locations
```

2022-11-14 17:36 UTC, marciocloudflare commented on content/radar/investigate/dns.md
> +### Example: Geographical distribution of google.com vs yandex.ru
```suggestion
#### Example: Geographical distribution of `google.com` versus `yandex.ru`
```

2022-11-14 17:36 UTC, marciocloudflare commented on content/radar/investigate/dns.md
> +Let's look at the top locations from where DNS queries to `google.com` are coming:
```suggestion
In the next example, we will request the top originating locations for `google.com` DNS queries:
```

2022-11-14 17:36 UTC, marciocloudflare commented on content/radar/investigate/dns.md
> +Most queries come from the United States and Brazil:
```suggestion
The response shows that most queries come from the United States and Brazil:
```

2022-11-14 17:36 UTC, marciocloudflare commented on content/radar/investigate/dns.md
> +And looking at `yandex.ru`, a russian search engine:
```suggestion
Making the same search request for `yandex.ru`, a Russian search engine:
```

2022-11-14 17:36 UTC, marciocloudflare commented on content/radar/investigate/dns.md
> +
```suggestion

Returns the following response:

```

2022-11-14 17:36 UTC, marciocloudflare commented on content/radar/investigate/dns.md
> +Take into account that this looks at the total number of DNS queries from that location and to that hostname, _out_ of the total DNS queries to the given hostname. In this sense, it's expected that l
```suggestion
Note that these examples return the total number of DNS queries from a location to a hostname, _out_ of the total DNS queries to a given hostname. In this sense, it is expected that locations with higher population numbers — like the United States — frequently appear in the top spots, even if the actual percentage is low.
```

2022-11-14 17:36 UTC, marciocloudflare commented on content/radar/investigate/dns.md
> +Multiple hostnames can also be provided - take a look at the [API reference](https://api.cloudflare.com/#radar-dns-get-top-locations-by-dns-queries) for this endpoint. This is useful when the applica
```suggestion
You can also provide multiple hostnames. Refer to [Get top locations by DNS queries](https://api.cloudflare.com/#radar-dns-get-top-locations-by-dns-queries) for more information. This is useful when the application you want to explore uses several hostnames to serve its content (like a hostname for the main website, another hostname dedicated to its API, etc.).
```

2022-11-14 17:36 UTC, marciocloudflare commented on content/radar/investigate/dns.md
> +{{</button-group>}}
```suggestion
Refer to [Domain ranking](/radar/investigate/domain-ranking-datasets/) for more information on rankings generated by Cloudflare based on DNS queries to [1.1.1.1 public resolver](/1.1.1.1/).
```

2022-11-14 17:36 UTC, marciocloudflare commented on content/radar/investigate/domain-ranking-datasets.md
> +weight: 3
```suggestion
weight: 5
```

2022-11-14 17:36 UTC, marciocloudflare commented on content/radar/investigate/domain-ranking-datasets.md
> +
```suggestion
```

2022-11-14 17:36 UTC, marciocloudflare commented on content/radar/investigate/domain-ranking-datasets.md
> +title: Domains Ranking
```suggestion
title: Domains ranking
```

2022-11-14 17:36 UTC, marciocloudflare commented on content/radar/investigate/domain-ranking-datasets.md
> +Cloudflare regularly generates a Domain Ranking based on DNS queries to [1.1.1.1](https://1.1.1.1/dns/), our public DNS resolver.  Check the [blog post](https://blog.cloudflare.com/radar-domain-ranki
```suggestion
Cloudflare regularly generates a domain ranking based on DNS queries to [1.1.1.1](/1.1.1.1/),  Cloudflare's public DNS resolver.  Refer to the [blog post](https://blog.cloudflare.com/radar-domain-rankings/) for a deep dive. In short, Cloudflare generates two types of listings:
```

2022-11-14 17:36 UTC, marciocloudflare commented on content/radar/investigate/domain-ranking-datasets.md
> +- Unordered global most popular domains datasets divided into buckets of the following sizes: 200, 500, 1,000, 2,000, 5,000, 10,000, 20,000, 50,000, 100,000, 200,000, 500,000, 1,000,000. Last 7 days,
```suggestion
- An ordered list of the top 100 most popular domains globally and per country. This includes the last 24 hours and is updated daily.
- An unordered global most popular domains dataset, divided into buckets of the following number of domains: 200, 500, 1,000, 2,000, 5,000, 10,000, 20,000, 50,000, 100,000, 200,000, 500,000, 1,000,000. It includes the last seven days and is updated weekly.
```

2022-11-14 17:36 UTC, marciocloudflare commented on content/radar/investigate/domain-ranking-datasets.md
> +### Example: Get the current ordered top domains in the Cloudflare ranking
```suggestion
## Example: Get the current ordered top domains in the Cloudflare ranking
```

2022-11-14 17:36 UTC, marciocloudflare commented on content/radar/investigate/domain-ranking-datasets.md
> +For more information refer to the [API reference](https://api.cloudflare.com/#radar-ranking-get-domains-rank-top) for this endpoint.
```suggestion
For more information refer to [Get Domains Rank top](https://api.cloudflare.com/#radar-ranking-get-domains-rank-top).
```

2022-11-14 17:36 UTC, marciocloudflare commented on content/radar/investigate/domain-ranking-datasets.md
> +### Example: Get the last top X ranking bucket
```suggestion
## Example: Get the last top `x` ranking bucket
```

2022-11-14 17:36 UTC, marciocloudflare commented on content/radar/investigate/domain-ranking-datasets.md
> +As mentioned in the [blog post](https://blog.cloudflare.com/radar-domain-rankings/), Cloudflare provides an ordered rank for the top 100 domains, but for the remainder it only provides ranking bucket
```suggestion
As mentioned in the [blog post](https://blog.cloudflare.com/radar-domain-rankings/), Cloudflare provides an ordered rank for the top 100 domains, but for the remainder it only provides ranking buckets — like top 200 thousand, top one million, etc.. These are available through Cloudflare's [datasets endpoints](https://api.cloudflare.com/#radar-datasets-get-datasets).
```

2022-11-14 17:36 UTC, marciocloudflare commented on content/radar/investigate/domain-ranking-datasets.md
> +So, let's get the last available domain ranking buckets:
```suggestion
In the following example we will request the last available domain ranking buckets:
```

2022-11-14 17:36 UTC, marciocloudflare commented on content/radar/investigate/domain-ranking-datasets.md
> +
```suggestion
If you are interested in a specific top (like the top one million), go through the `meta.top` property. After finding the top you are looking for, get its `id` to fetch the dataset using the [`GET dataset`](https://api.cloudflare.com/#radar-datasets-get-dataset-download-url) endpoint.
```

2022-11-14 17:36 UTC, marciocloudflare commented on content/radar/investigate/domain-ranking-datasets.md
> +{{</button-group>}}
```suggestion
Refer to [Investigate outages](/radar/investigate/outages/) to get data from outages occurring around the world.
```

2022-11-14 17:36 UTC, marciocloudflare commented on content/radar/investigate/http-requests.md
> +While in [Netflows](/radar/investigate/netflows) we were looking at bytes and packets reaching our edge routers, here we're a layer above, looking at complete eyeball HTTP requests that reach website
```suggestion
While in [Netflows](/radar/investigate/netflows/) we were examining bytes and packets reaching Cloudflare's edge routers, in HTTP requests we are a layer above in the [OSI model](https://en.wikipedia.org/wiki/OSI_model). In HTTP requests we examine complete HTTP requests from end users that reach websites served by Cloudflare's [CDN](https://www.cloudflare.com/en-gb/learning/cdn/what-is-a-cdn/).
```

2022-11-14 17:36 UTC, marciocloudflare commented on content/radar/investigate/http-requests.md
> + {{</Aside>}}
```suggestion
{{<Aside type="note">}}
HTTP traffic includes both HTTP and HTTPS traffic coming from end users.
{{</Aside>}}
```

2022-11-14 17:36 UTC, marciocloudflare commented on content/radar/investigate/http-requests.md
> +Most of the charts, in the [Adoption and Usage](https://radar.cloudflare.com/adoption-and-usage) section on Radar, come from this data source.
```suggestion
Most of the charts in the [Adoption and Usage](https://radar.cloudflare.com/adoption-and-usage) section on Radar come from this data source.
```

2022-11-14 17:36 UTC, marciocloudflare commented on content/radar/investigate/http-requests.md
> +- top: a list of the top locations or [ASes](https://www.cloudflare.com/en-gb/learning/network-layer/what-is-an-autonomous-system/) ranked by adoption of a specific metric, for example, top locations
```suggestion
- `timeseries`: A time series of a group of metrics. For example, when looking at IP version, displays an IPv4 time series and an IPv6 time series.
- `summary`: Displays a summary of a group of metrics over the specified time range. For example, IPv4 traffic percentage out of the total HTTP traffic during that time period.
- `top`: A list of the top locations or [Autonomous Systems](https://www.cloudflare.com/en-gb/learning/network-layer/what-is-an-autonomous-system/) (ASes) ranked by adoption of a specific metric. For example, top locations by mobile device traffic (like which locations have a higher percentage of mobile traffic out of the total traffic for that location).
```

2022-11-14 17:36 UTC, marciocloudflare commented on content/radar/investigate/http-requests.md
> +Let's look at traffic by device type globally with and without [bot traffic](/radar/concepts/bot-classes) (parameters for the `human` series: `name=human&botClass=LIKELY_HUMAN&dateRange=1d` and for t
```suggestion
In this example, we will request traffic by device type globally, with and without [bot traffic](/radar/concepts/bot-classes/). Parameters for the `human` series are `name=human&botClass=LIKELY_HUMAN&dateRange=1d`. For the `bot` series, the parameters are `name=bot&botClass=LIKELY_AUTOMATED&dateRange=1d`:
```

2022-11-14 17:36 UTC, marciocloudflare commented on content/radar/investigate/http-requests.md
> +And here's the abbreviated response:
```suggestion
Here is the abbreviated response:
```

2022-11-14 17:36 UTC, marciocloudflare commented on content/radar/investigate/http-requests.md
> +Mobile devices tend to be considerably more present when looking at human generated traffic vs bot generated traffic.
```suggestion
Mobile devices tend to be considerably more present when examining human generated traffic versus bot generated traffic.
```

2022-11-14 17:36 UTC, marciocloudflare commented on content/radar/investigate/http-requests.md
> +Take into account that device classification comes from the [User-agent](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent), so ultimately this depends on the user agent(s) that bo
```suggestion
Note that device classification comes from the [User-agent](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent) header. Ultimately, this classification depends on the user agent(s) that bots use.
```

2022-11-14 17:36 UTC, marciocloudflare commented on content/radar/investigate/http-requests.md
> +For more information refer to the [API reference](https://api.cloudflare.com/#radar-http-get-time-series-of-device-types) for this endpoint.
```suggestion
For more information refer to [Get time series of device types](https://api.cloudflare.com/#radar-http-get-time-series-of-device-types).
```

2022-11-14 17:36 UTC, marciocloudflare commented on content/radar/investigate/http-requests.md
> +We could also look at the same information but now asking for a summary of the device type breakdown over the _entire_ period, instead of per hour like we did above.
```suggestion
We can also look at the same information asking for a summary of the device type breakdown over the entire period, instead of a per hour breakdown like in the example before.
```

2022-11-14 17:36 UTC, marciocloudflare commented on content/radar/investigate/http-requests.md
> +The abbreviated response:
```suggestion
Here is the abbreviated response:
```

2022-11-14 17:36 UTC, marciocloudflare commented on content/radar/investigate/http-requests.md
> +Let's look at another example, global breakdown of traffic by IP version, with and without bots:
```suggestion
In the following example, we will examine global breakdown of traffic by IP version, with and without bots:
```

2022-11-14 17:36 UTC, marciocloudflare commented on content/radar/investigate/http-requests.md
> +And we get:
```suggestion
This returns the following:
```

2022-11-14 17:36 UTC, marciocloudflare commented on content/radar/investigate/http-requests.md
> +
```suggestion
```

2022-11-14 17:36 UTC, marciocloudflare commented on content/radar/investigate/http-requests.md
> +Bots tend to use more IPv4.
```suggestion
Bots tend to use more IPv4 addresses.
```

2022-11-14 17:36 UTC, marciocloudflare commented on content/radar/investigate/http-requests.md
> +
```suggestion
It is also interesting to know how your ISP fares in IPv6 adoption. If you know your ISP’s autonomous system number (ASN), you can use the `asn` parameter to query for this information. Refer to the [API reference](https://api.cloudflare.com/#radar-http-get-a-summary-of-ip-versions) for other parameters.

If you do not know your ISP’s ASN, you use [Radar](https://radar.cloudflare.com/ip) to find what it is.
```

2022-11-14 17:36 UTC, marciocloudflare commented on content/radar/investigate/http-requests.md
> +Which locations have a higher adoption of [IPv6](https://en.wikipedia.org/wiki/IPv6) in the last 28 days?
```suggestion
In the following example, we will find which locations had a higher adoption of [IPv6](https://en.wikipedia.org/wiki/IPv6) in the last 28 days.
```

2022-11-14 17:36 UTC, marciocloudflare commented on content/radar/investigate/http-requests.md
> +Seems like India is leading the charge.
```suggestion
According to the returned data, India is leading in IPv6 adoption.
```

2022-11-14 17:36 UTC, marciocloudflare commented on content/radar/investigate/http-requests.md
> +{{</button-group>}}
```suggestion
Refer to [Application layer attacks](/radar/investigate/application-layer-attacks/) to learn more about mitigfated HTTP requests.
```

2022-11-14 17:36 UTC, marciocloudflare commented on content/radar/investigate/netflows.md
> +[Netflows](https://en.wikipedia.org/wiki/NetFlow) shows eyeball network traffic data collected from Cloudflare's edge routers, aka Radar's `Internet Traffic Change`.
```suggestion
[Netflows](https://en.wikipedia.org/wiki/NetFlow) shows network traffic data from end users collected from Cloudflare's edge routers. Netflows' data also feeds the [Internet traffic change](https://radar.cloudflare.com/) chart.
```

2022-11-14 17:36 UTC, marciocloudflare commented on content/radar/investigate/netflows.md
> +Netflows includes _all_ kinds of traffic our routers get, not just traffic to websites served by the Cloudflare [CDN](https://www.cloudflare.com/en-gb/learning/cdn/what-is-a-cdn/) product.
```suggestion
Netflows includes all types of traffic from Cloudflare's routers, not just traffic to websites served by Cloudflare's [CDN](https://www.cloudflare.com/en-gb/learning/cdn/what-is-a-cdn/).
```

2022-11-14 17:36 UTC, marciocloudflare commented on content/radar/investigate/netflows.md
> +Besides comparing timeseries across locations or date ranges, already looked at in [Making comparisons](/radar/get-started/making-comparisons), we can also look at `ALL` traffic versus only `HTTP` tr
```suggestion
Besides comparing time series across locations or date ranges (discussed in [Making comparisons](/radar/get-started/making-comparisons/)), we can also examine `ALL` traffic versus only `HTTP` traffic using the `product` filter. For more information, refer to the [API reference](https://api.cloudflare.com/#radar-netflows-get-netflow-time-series) for this endpoint. 
```

2022-11-14 17:36 UTC, marciocloudflare commented on content/radar/investigate/netflows.md
> +
```suggestion
{{<Aside type="note" header="NetFlow products">}}
`HTTP` traffic only includes web traffic to Cloudflare's zones, while `ALL` also includes traffic to all other services, like [Spectrum](/spectrum/), [Magic Transit](/magic-transit/), [1.1.1.1](/1.1.1.1/), and others.
{{</Aside>}}
```

2022-11-14 17:36 UTC, marciocloudflare commented on content/radar/investigate/netflows.md
> +First, we'll look at [AS3243](https://radar.cloudflare.com/as3243), a portuguese local Internet Service Provider or ISP (parameters for all traffic: `name=AS3243_all&product=ALL&dateRange=1d&asn=3243
```suggestion
In the following example, we will examine both `ALL` and `HTTP` traffic in two [autonomous systems](https://www.cloudflare.com/en-gb/learning/network-layer/what-is-an-autonomous-system/). First, we will examine [AS3243](https://radar.cloudflare.com/as3243), a Portuguese local Internet Service Provider (ISP). The parameters for all traffic are `name=AS3243_all&product=ALL&dateRange=1d&asn=3243`, and for just the HTTP traffic are `name=AS3243_http&product=HTTP&dateRange=1d&asn=3243`):
```

2022-11-14 17:36 UTC, marciocloudflare commented on content/radar/investigate/netflows.md
> +And here's the abbreviated response:
```suggestion
This is the abbreviated response:
```

2022-11-14 17:36 UTC, marciocloudflare commented on content/radar/investigate/netflows.md
> +We see that `HTTP` traffic values are similar to `ALL` traffic values - this means that most traffic Cloudflare sees as coming from this AS, is traffic to websites served by Cloudflare's [CDN](https:
```suggestion
`HTTP` traffic values are similar to `ALL` traffic values. This means that most traffic Cloudflare receives from this AS is traffic to websites served by Cloudflare's [CDN](https://www.cloudflare.com/en-gb/learning/cdn/what-is-a-cdn/) product.
```

2022-11-14 17:36 UTC, marciocloudflare commented on content/radar/investigate/netflows.md
> +And now, let's look at [AS174](https://radar.cloudflare.com/as174), another autonomous system that is not an ISP:
```suggestion
In this other example, we will examine [AS174](https://radar.cloudflare.com/as174), another autonomous system that is not an ISP:
```

2022-11-14 17:36 UTC, marciocloudflare commented on content/radar/investigate/netflows.md
> +The abbreviated response:
```suggestion
The abbreviated response is:
```

2022-11-14 17:36 UTC, marciocloudflare commented on content/radar/investigate/netflows.md
> +
```suggestion
Here, there is less `HTTP` traffic compared to other types of traffic — which makes sense, since this is not an ISP serving end-users.

Note that here we made two separate requests since we are only interested in whether `HTTP` comprises the majority of the traffic in each AS or not. If we wanted to actually [compare](/radar/get-started/making-comparisons/) the traffic values between them to, for example, examine who has more traffic, we would have to make a single request including all series. Here is how we could do that:
```

2022-11-14 17:36 UTC, marciocloudflare commented on content/radar/investigate/netflows.md
> +Cloudflare sees more traffic from AS174 than it sees from AS3243.
```suggestion
This response shows how Cloudflare receives more traffic from AS174 than from AS3243.
```

2022-11-14 17:36 UTC, marciocloudflare commented on content/radar/investigate/netflows.md
> +Cloudflare sees more traffic from AS174 than it sees from AS3243.
Trying to be inclusive and not use the word "see". But I'm not sure if "receive" is the correct word here.

2022-11-14 17:36 UTC, marciocloudflare commented on content/radar/investigate/netflows.md
> +{{</button-group>}}
```suggestion
Refer to [HTTP requests](/radar/investigate/http-requests/) for more information about requests from end users.
```

2022-11-14 17:36 UTC, marciocloudflare commented on content/radar/investigate/network-layer-attacks.md
> +Here we're looking at [DDoS](https://www.cloudflare.com/en-gb/learning/ddos/layer-3-ddos-attacks/) attack trends at the network layer. These attacks can be split by the network protocol they use: [IC
```suggestion
Network layer attacks show [DDoS](https://www.cloudflare.com/en-gb/learning/ddos/layer-3-ddos-attacks/) attack trends at the network layer. These attacks can be split by the network protocol they use: [ICMP](https://www.cloudflare.com/en-gb/learning/ddos/glossary/internet-control-message-protocol-icmp/), [TCP](https://www.cloudflare.com/learning/ddos/glossary/tcp-ip/), [UDP](https://www.cloudflare.com/en-gb/learning/ddos/glossary/user-datagram-protocol-udp/) and others.
```

2022-11-14 17:36 UTC, marciocloudflare commented on content/radar/investigate/network-layer-attacks.md
> +Unlike in [Application Layer Attacks](/radar/investigate/application-layer-attacks), in network layer attacks, due to [IP spoofing](https://www.cloudflare.com/en-gb/learning/ddos/glossary/ip-spoofing
```suggestion
Unlike what happens in [Application Layer Attacks](/radar/investigate/application-layer-attacks/), in network layer attacks location attribution does not use the location associated with the client's IP address. Instead, it uses the location of the data center itself. This is due to [IP spoofing](https://www.cloudflare.com/en-gb/learning/ddos/glossary/ip-spoofing/).
```

2022-11-14 17:36 UTC, marciocloudflare commented on content/radar/investigate/network-layer-attacks.md
> +When filtering by location or AS, we're filtering by the _source_ location/AS of the attack (which can be very different to the location of the human orchestrator of the attack, see [botnets](https:/
```suggestion
When filtering by location or autonomous system (AS), we are filtering by the source location/AS of the attack 
 — which can be very different to the location of the human orchestrator of the attack. Refer to [botnets](https://www.cloudflare.com/learning/ddos/what-is-a-ddos-botnet/) for more information.
```

2022-11-14 17:36 UTC, marciocloudflare commented on content/radar/investigate/network-layer-attacks.md
> +Let's look at the worldwide vs Singapore distribution of mitigated attacks by network protocol:
```suggestion
In the following example, we will examine the worldwide versus Singapore distribution of mitigated attacks by network protocol:
```

2022-11-14 17:36 UTC, marciocloudflare commented on content/radar/investigate/network-layer-attacks.md
> +Looking at the abbreviated response below, we see that globally, at those timestamps, `UDP` and `TCP` attacks were pretty evenly split.
```suggestion
If we inspect the abbreviated response below, we can conclude that globally, at those timestamps, `UDP` and `TCP` attacks were mostly evenly split.
```

2022-11-14 17:36 UTC, marciocloudflare commented on content/radar/investigate/network-layer-attacks.md
> +We can also see that the distribution of network layer attacks coming _from_ Singapore or, more accurately, reaching our data center located in Singapore, differs quite a bit from the worldwide distr
```suggestion
We can also conclude that the distribution of network layer attacks coming from Singapore  — or, more accurately, reaching Cloudflare's data center located in Singapore — differs quite a bit from the worldwide distribution. At those times, the distribution of network layer attacks clearly favors [TCP](https://www.cloudflare.com/learning/ddos/glossary/tcp-ip/).
```

2022-11-14 17:36 UTC, marciocloudflare commented on content/radar/investigate/network-layer-attacks.md
> +We can also filter by _source_ location and look at attacks coming _from_ Russia:
```suggestion
We can also filter by source location and examine attacks coming from Russia:
```

2022-11-14 17:36 UTC, marciocloudflare commented on content/radar/investigate/network-layer-attacks.md
> +We see that attacks coming from Russia to other locations, at the time above, tend to use the [UDP](https://www.cloudflare.com/en-gb/learning/ddos/glossary/user-datagram-protocol-udp/) network protoc
```suggestion
The response shows that the attacks coming from Russia to other locations tended to use the [UDP](https://www.cloudflare.com/en-gb/learning/ddos/glossary/user-datagram-protocol-udp/) network protocol at those timestamps.
```

2022-11-14 17:36 UTC, marciocloudflare commented on content/radar/investigate/network-layer-attacks.md
> +{{</button-group>}}
```suggestion
Refer to [DNS](/radar/investigate/dns/) to learn more about the aggregated and anonymized DNS queries to Cloudflare's [1.1.1.1](/1.1.1.1/) public resolver service.
```

2022-11-14 17:36 UTC, marciocloudflare commented on content/radar/investigate/outages.md
> +
```suggestion
```

2022-11-14 17:36 UTC, marciocloudflare commented on content/radar/investigate/outages.md
> +See the [blog post](https://blog.cloudflare.com/announcing-cloudflare-radar-outage-center/) for more information but, in short, we provide the following information:
```suggestion
Refer the [blog post](https://blog.cloudflare.com/announcing-cloudflare-radar-outage-center/) for more information but, in short, Radar provides the following information:
```

2022-11-14 17:36 UTC, marciocloudflare commented on content/radar/investigate/outages.md
> +- Scope: If it was a sub-national/regional outage, what state or city was impacted? If it was a network-level outage, which one?
```suggestion
- Scope: If it was a sub-national/regional outage, what state or city was impacted? If it was a network-level outage, which one was it?
```

2022-11-14 17:36 UTC, marciocloudflare commented on content/radar/investigate/outages.md
> +- Cause: Insight into the likely cause of the outage, based on publicly available information. Historically, some have been government directed shutdowns, while others are caused by severe weather or
```suggestion
- Cause: Insight into the likely cause of the outage, based on publicly available information. Historically, some outages have been government directed shutdowns, while others are caused by severe weather or natural disasters, or by infrastructure issues such as cable cuts, power outages, or filtering/blocking.
```

2022-11-14 17:36 UTC, marciocloudflare commented on content/radar/investigate/outages.md
> +### Example: Get outages in the last 7 days
```suggestion
## Example: Get outages in the last 7 days
```

2022-11-14 17:36 UTC, marciocloudflare commented on content/radar/investigate/outages.md
> +Refer to the [API reference](https://api.cloudflare.com/#radar-annotations-get-outages-annotations) for this endpoint.
```suggestion
Refer to the [API reference](https://api.cloudflare.com/#radar-annotations-get-outages-annotations) for more information regarding this endpoint.
```

2022-11-14 17:36 UTC, marciocloudflare commented on content/radar/investigate/outages.md
> +
```suggestion
Having data on a given outage allows you to examine its impact through both [Netflows](/radar/investigate/netflows) (like in the [Tonga outage](/radar/get-started/making-comparisons/#using-specific-timestamps) and [others](https://blog.cloudflare.com/q3-2022-internet-disruption-summary/)) and [HTTP](/radar/investigate/http-requests) data (for example, did the outage affect more mobile than desktop traffic?).
```

2022-11-14 17:36 UTC, marciocloudflare commented on content/radar/investigate/outages.md
> +{{</button-group>}}
```suggestion
```

2022-11-14 17:36 UTC, marciocloudflare commented on content/radar/investigate/outages.md
> +{{</button-group>}}
This assumes customers read docs from start to end, but they might also just come here for the Outages section. Hence, it doesn't make sense to "end" with this. I've also deleted the API reference as that's on the side menu.

2022-11-14 17:36 UTC, marciocloudflare commented on content/radar/get-started/first-request.md
> +
```suggestion
### Notebooks

A [notebook](https://jupyter.org/) is a web-based interactive computing application, where text, code, and code outputs, like charts, can be combined into a single document. Refer to Radar's companion [colaboratory notebook](https://colab.research.google.com/drive/1MP8_YDPx44RRevG1ImHS1ycnF1bFW9ve?usp=sharing) for more examples on how you can use them for your own projects.

```

2022-11-15 14:23 UTC, meddulla commented on content/radar/get-started/first-request.md
> +Above, you are looking at _all_ traffic but you can also look at just traffic classified as coming from humans (the default in [Cloudflare Radar](https://radar.cloudflare.com)) by adding `botClass=LI
Would prefer "The previous example returns all traffic, from bots and humans alike." instead of "The previous example returns all traffic available to Cloudflare Radar".

2022-11-15 14:24 UTC, meddulla commented on content/radar/get-started/first-request.md
> +
Shame. Wanted to drop hints for possible explorations they could do on their own.

2022-11-15 14:27 UTC, meddulla commented on content/radar/get-started/first-request.md
> +
The url needs to be updated since the notebook will come from a github repository instead (waiting on the repo). Will add this once we have the final url.

2022-11-15 14:29 UTC, meddulla commented on content/radar/get-started/first-request.md
> +{{</button-group>}}
Should be 'Make comparisons'.

2022-11-15 14:30 UTC, meddulla commented on content/radar/get-started/making-comparisons.md
> +When comparing time series, across locations/time ranges/etc, in endpoints that normalize values using [MinMax](/radar/concepts/normalization), we __must__ do so in the __same__ request, by asking fo
Any reason why we shouldn't use bold for emphasis on the 'must'?

2022-11-15 14:38 UTC, meddulla commented on content/radar/investigate/_index.md
> +
How about this? "Explore the different kinds of data available, from Netflows (what feeds the "Internet Traffic Change" chart in Radar) to HTTP requests and DNS queries."

2022-11-15 14:40 UTC, meddulla commented on content/radar/investigate/application-layer-attacks.md
> +Like in [HTTP requests](/radar/investigate/http-requests), these endpoints can be split into the ability to fetch a timeseries, a single value summarizing the entire date range, and a list of top loc
There 3 kinds of endpoints: timeseries, summary and top. This would make summary part of the timeseries endpoint which is incorrect.

2022-11-15 16:31 UTC, marciocloudflare requested changes

2022-11-15 16:31 UTC, marciocloudflare commented on content/radar/_index.md
> +[Cloudflare Radar](https://radar.cloudflare.com) is a hub that showcases global Internet traffic, attacks, and technology trends and insights. It is powered by data from Cloudflare’s global network,
```suggestion
[Cloudflare Radar](https://radar.cloudflare.com) is a hub that showcases global Internet traffic, attacks, and technology trends and insights. It is powered by data from Cloudflare’s global network, as well as aggregated and anonymized data from Cloudflare’s [1.1.1.1](/1.1.1.1/privacy/) public DNS Resolver.
```

2022-11-15 16:31 UTC, marciocloudflare commented on content/radar/_index.md
> +[Cloudflare Radar](https://radar.cloudflare.com) is a hub that showcases global Internet traffic, attacks, and technology trends and insights. It is powered by data from Cloudflare’s global network,
Good call. Left a suggestion to change

2022-11-15 16:31 UTC, marciocloudflare commented on content/radar/_index.md
> +Using Radar's API you can now access Cloudflare's data on global Internet traffic as well.
```suggestion
Using Radar's API you can access Cloudflare's data on global Internet traffic as well.
```

2022-11-15 16:31 UTC, marciocloudflare commented on content/radar/_index.md
> +[Making comparisons](/radar/get-started/making-comparisons/) - What to know before making comparisons between locations, [ASes](https://www.cloudflare.com/en-gb/learning/network-layer/what-is-an-auto
This was deleted from this page

2022-11-15 16:31 UTC, marciocloudflare commented on content/radar/_index.md
> +[Network level attacks](/radar/investigate/network-layer-attacks/) - Investigate Layer 3/4 cyber attacks trends and patterns.
This was deleted from this page

2022-11-15 16:31 UTC, marciocloudflare commented on content/radar/_index.md
> +[Application level attacks](/radar/investigate/application-layer-attacks/) - Investigate Layer 7 cyber attacks trends and patterns.
This was deleted from this page

2022-11-15 16:31 UTC, marciocloudflare commented on content/radar/get-started/first-request.md
> +Above, you are looking at _all_ traffic but you can also look at just traffic classified as coming from humans (the default in [Cloudflare Radar](https://radar.cloudflare.com)) by adding `botClass=LI
Updated

2022-11-15 16:31 UTC, marciocloudflare commented on content/radar/investigate/_index.md
> +
```suggestion

Explore the different types of data available in Cloudflare Radar, from Netflows (what feeds the [Internet Traffic Change](https://radar.cloudflare.com/) chart in Radar) to HTTP requests and DNS queries.

```

2022-11-15 16:31 UTC, marciocloudflare commented on content/radar/investigate/_index.md
> +
Sounds good. Added

2022-11-15 16:31 UTC, marciocloudflare commented on content/radar/investigate/application-layer-attacks.md
> +Like in [HTTP requests](/radar/investigate/http-requests), these endpoints can be split into the ability to fetch a timeseries, a single value summarizing the entire date range, and a list of top loc
Oh. Noted. Deleting

2022-11-16 09:58 UTC, marciocloudflare approved these changes

2022-11-16 09:58 UTC, marciocloudflare commented on content/radar/_index.md
> +[Cloudflare Radar](https://radar.cloudflare.com) is a hub that showcases global Internet traffic, attacks, and technology trends and insights. It is powered by data from Cloudflare’s global network,
```suggestion
[Cloudflare Radar](https://radar.cloudflare.com) is a hub that showcases global Internet traffic, attacks, and technology trends and insights. It is powered by data from Cloudflare’s global network, as well as aggregated and [anonymized](/1.1.1.1/privacy/public-dns-resolver/) data from Cloudflare’s [1.1.1.1 public DNS resolver](/1.1.1.1/).
```

2022-11-16 09:58 UTC, marciocloudflare commented on content/radar/get-started/first-request.md
> +{{<Aside type="note" >}} Cloudflare Radar attempts to provide trends and insights into general Internet usage, using the traffic that goes through Cloudflare infrastructure. As such, Cloudflare Radar
```suggestion
{{<Aside type="note">}}Cloudflare Radar attempts to provide trends and insights into general Internet usage, using the traffic that goes through Cloudflare infrastructure. As such, Cloudflare Radar only provides data on traffic coming from end-users, unless otherwise specified (for example, origin fetches are excluded).
```

2022-11-16 09:58 UTC, marciocloudflare commented on content/radar/get-started/first-request.md
> +Running the above, do you see any differences between both in the distribution of mobile vs desktop traffic?
```suggestion
Running the above, can you find any differences between both in the distribution of mobile versus desktop traffic?
```

2022-11-16 09:58 UTC, marciocloudflare commented on content/radar/get-started/first-request.md
> +When querying for timeseries, `result.meta` will also include the returned [aggregation interval](/radar/concepts/aggregation-intervals) in `meta.aggInterval`.
```suggestion
When querying for time series, `result.meta` will also include the returned [aggregation interval](/radar/concepts/aggregation-intervals) in `meta.aggInterval`.
```

2022-11-16 09:58 UTC, marciocloudflare commented on content/radar/get-started/first-request.md
> +## Use Python
```suggestion
## Use Python
```

2022-11-16 09:58 UTC, marciocloudflare commented on content/radar/get-started/making-comparisons.md
> +In the following example, we will compare the traffic change across two different locations — United States and Portugal. The example will use [alpha-2 codes](https://en.wikipedia.org/wiki/ISO_3166-1
```suggestion
In the following example, we will compare the traffic change across two different locations — United States and Portugal. The example will use [alpha-2 codes](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements) for the last seven days:
```

2022-11-16 09:58 UTC, marciocloudflare commented on content/radar/get-started/making-comparisons.md
> +## Compare date ranges
```suggestion
## Compare date ranges
```

2022-11-16 09:58 UTC, marciocloudflare commented on content/radar/get-started/making-comparisons.md
> +## Next steps
```suggestion
## Next steps
```

2022-11-16 09:58 UTC, marciocloudflare commented on content/radar/investigate/application-layer-attacks.md
> +Since we are examining attacks, we can inspect both sides of an attack — both the source location and the target location of the attack. For the source of the attack Cloudflare uses the location the
```suggestion
Since we are examining attacks, we can inspect both sides of an attack — both the source location and the target location of the attack. For the source of the attack Cloudflare uses the location the attack is coming from associated with the IP (note that the human orchestrator of the attack may be in a different location than the computer the attack is originating from). For the target location of the attacks, Cloudflare uses the billing location associated with the zone under attack.
```

2022-11-16 09:58 UTC, marciocloudflare commented on content/radar/investigate/http-requests.md
> + {{</Aside>}}
```suggestion
{{</Aside>}}
```

2022-11-16 09:58 UTC, marciocloudflare commented on content/radar/investigate/http-requests.md
> +If you do not know your ISP’s ASN, you use [Radar](https://radar.cloudflare.com/ip) to find what it is.
```suggestion
If you do not know your ISP’s ASN, you can use [Radar](https://radar.cloudflare.com/ip) to find what it is.
```

2022-11-16 10:04 UTC, merged