wrangler 2: route changes, zone id needed for subdomain zones
cloudflare/cloudflare-docs pull request #6609
Opened 2022-11-08 17:48 UTC by e271828-

These behavior changes are both critical and difficult to catch prior to deployment.

2023-01-11 15:35 UTC, deadlypants1973 approved these changes

2023-01-11 15:35 UTC, deadlypants1973 commented on content/workers/wrangler/migration/deprecations.md
>  - To manage routes via the Cloudflare dashboard only, update your `wrangler.toml` file as follows: remove any `route` and `routes` keys and add `workers_dev = false`.
```suggestion
- To manage routes via the Cloudflare dashboard only, update your `wrangler.toml` file by removing any `route` and `routes` keys and add `workers_dev = false`.
```

2023-01-11 15:35 UTC, deadlypants1973 commented on content/workers/wrangler/migration/deprecations.md
> +Please note a breaking change has been introduced to routes: all Cloudflare dashboard-defined routes for your worker will be **deleted upon deployment** if you have any Wrangler-defined routes for th
```suggestion
{{<Aside type="warning" header="Breaking change for routes">}}

All Cloudflare dashboard-defined routes for your Worker will be deleted upon deployment if you have any Wrangler-defined (`wrangler.toml`) routes for that Worker.

{{</Aside>}}
```

2023-01-11 15:52 UTC, Mehrdadmehrdadian commented on content/workers/wrangler/migration/deprecations.md
> +Please note a breaking change has been introduced to routes: all Cloudflare dashboard-defined routes for your worker will be **deleted upon deployment** if you have any Wrangler-defined routes for th
🙏هنگام بازدید از blockchain.com

کد خطا: 1020

2023-01-20 17:19 UTC, JacobMGEvans requested changes
We were not able to reproduce this, given a subdomain we used. Could you please provide a minimal reproduction of a Worker that is doing this.

2023-01-20 17:30 UTC, e271828- commented
@JacobMGEvans should be easy to repro. Create a root domain zone and two enterprise subdomain zones. Create some manual routes to workers. Switch to w2 with some routes defined using the subdomain zone hostnames without the ID, and watch everything manual get blown away with nothing added from config on the subdomain zones.

Also, we reported this behavior months ago. Perhaps they've fixed it since then. Have you checked your changelogs for related changes?

2023-01-20 17:43 UTC, JacobMGEvans commented
> @JacobMGEvans should be easy to repro. Create a root domain zone and two enterprise subdomain zones. Create some manual routes to workers. Switch to w2 with some routes defined using the subdomain zone hostnames without the ID, and watch everything manual get blown away with nothing added from config on the subdomain zones.
> 
> Also, we reported this behavior months ago. Perhaps they've fixed it since then. Have you checked your changelogs for related changes?

I understand, we still would like to see perhaps a GitHub repo that specifically does this `It can be deduced from the routes directly **unless** you are using subdomain zones, in which case you must specify it explicitly.` We would also likely treat this as a bug, not something to document. 

Which is a separate issue from from the routes in Wrangler configuration blowing away the ones upstream, as for the source of truth issues with publishing routes, we do have the issue in backlog (https://github.com/cloudflare/wrangler2/issues/2082) and @admah is planning out the future work, it is on our radar 😃 .

2023-02-13 17:23 UTC, JacobMGEvans commented
Thank you for the PR, we would appreciate  a minimal reproduction of a Worker that is doing this in `workers-sdk` for Wrangler https://github.com/cloudflare/workers-sdk/issues/new?assignees=&labels=bug&template=bug-template.yaml&title=%F0%9F%90%9B+BUG%3A

2023-02-13 19:09 UTC, closed without merging