[Bots] JS Detections update
cloudflare/cloudflare-docs pull request #6610
Opened 2022-11-08 17:58 UTC by patriciasantaana

pcx-1500

2022-11-08 18:55 UTC, worenga requested changes

2022-11-08 18:55 UTC, worenga commented on content/bots/reference/javascript-detections.md
> +The injected script has been augmented with window property checks which are validated by the Challenge Platform (CP).
remove this sentence please

2022-11-08 18:55 UTC, worenga commented on content/bots/reference/javascript-detections.md
> +The snippets of JavaScript will now contain a source pointing to the challenge platform `/cdn-cgi/challenge-platform/h/d/scripts/invisible.js`.
remove "now", change path into "paths that start with /cdn-cgi/challenge-platform/..."

2022-11-08 18:55 UTC, worenga commented on content/bots/reference/javascript-detections.md
> +The script will then execute, collecting window properties and fingerprints, which will be sent to a new endpoint `/cdn-cgi/challenge-platform/h/d/cv/results/abcdef`.
Remove this sentence

2022-11-08 19:34 UTC, dcpena approved these changes

2022-11-10 12:40 UTC, worenga approved these changes

2022-11-10 12:40 UTC, merged