add information on deployments
cloudflare/cloudflare-docs pull request #6631
Opened 2022-11-09 16:45 UTC by kabirsikand

2022-11-09 21:08 UTC, danielrs commented on content/workers/platform/deployments.md
> +* `deployment_number`: An auto-incrementing integer indicating the deployment number
Should be just `number`.

2022-11-09 21:08 UTC, danielrs commented on content/workers/platform/deployments.md
> +		author_name: string,
No `author_name` in the metadata binding, let's start without it and see if users ask for it... Prefer to be careful when exposing this information.

2022-11-09 21:11 UTC, danielrs commented on content/workers/platform/deployments.md
> +timestamp: datetime
Fix indentation of these two lines above.

2022-11-09 21:31 UTC, admah commented on content/workers/platform/deployments.md
> +* `created_on` - A timestamp indicating deployment date and time
```suggestion
### Deployments consist of : 

|   |   |   |   |   |
|---|---|---|---|---|
| `id` | A unique Cloudflare-generated identifier |
| `deployment_number` | An auto-incrementing integer indicating the deployment number |
| `metadata` | An object containing information about the deployment |
| `author_id`  | A Cloudflare-generated unique identifier |
| `author_name`  | A string representing the user or token information of the author of the deployment |
| `source`  | A string representing the interface that was used to author the deployment. One of: `"api", "dash", "wrangler", "terraform", "other"`. |
| `created_on`  | A timestamp indicating deployment date and time |
```

2022-11-09 21:33 UTC, admah commented on content/workers/platform/deployments.md
> +* Changes to a Worker’s bindings, code, or configuration in the CLI via [wrangler publish](/workers/wrangler/commands#publish)
I would suggest adding a line break between headings and content.

```suggestion
### Deployments are triggered by:

* Changes to a Worker’s bindings, code, or configuration in the Cloudflare dashboard
* Changes to a Worker’s bindings, code, or configuration in the API
* Changes to a Worker’s bindings, code, or configuration in the CLI via [wrangler publish](/workers/wrangler/commands#publish)
```

2022-11-09 21:33 UTC, admah commented on content/workers/platform/deployments.md
> +### wrangler
I would suggest adding a line break between headings.

2022-11-09 21:34 UTC, JacobMGEvans commented on content/workers/wrangler/commands.md
we should show an example of the output here as well.

2022-11-09 21:41 UTC, admah reviewed
Haven't had a chance for a full review, but here are some initial comments.

2022-11-09 21:41 UTC, admah commented on content/workers/platform/deployments.md
> +Deployments are a set of static historical ‘snapshots’ of your Worker. They include the code, configuration, and bindings associated with your Worker. A change to any of these will trigger a new depl
```suggestion
Deployments are a set of static historical ‘snapshots’ of your Worker. They include the code, configuration, and bindings associated with your Worker. A change to any of these will trigger a new deployment on Cloudflare’s network.
```

2022-11-09 21:41 UTC, admah commented on content/workers/platform/deployments.md
> +Only **one** deployment is active at any time – always the latest deployment. That deployment is accessible via any of your configured custom domains, routes, service bindings, schedules, and your op
Does workers.dev need to be `workers.dev`?

2022-11-09 21:41 UTC, admah commented on content/workers/platform/deployments.md
> +Only **one** deployment is active at any time – always the latest deployment. That deployment is accessible via any of your configured custom domains, routes, service bindings, schedules, and your op
```suggestion
Only **one** deployment is active at any time. Currently this is the latest deployment. The active deployment is accessible via any of your configured custom domains, routes, service bindings, schedules, and your optional workers.dev preview.
```

2022-11-10 18:23 UTC, JacobMGEvans approved these changes
Tentatively approving.

2022-11-11 16:06 UTC, JacobMGEvans approved these changes
Love the examples

2022-11-11 16:42 UTC, admah commented
@kabirsikand one thing I noticed is that that the `metadata` keys in the table are breaking. It would be a better experience for those to stay on the same line. You should be able to achieve that by wrapping them in `<span style="white-space: nowrap;">metadata.key</span>`.

![Screen Shot 2022-11-11 at 10 38 41 AM](https://user-images.githubusercontent.com/2184114/201387875-2f6ad92f-04e3-421b-a26a-81d2e989d25b.png)

2022-11-11 17:26 UTC, IgorMinar commented on content/workers/platform/deployments.md
> +* Changes to a Worker’s bindings, code, or configuration in the API
```suggestion
* Changes to a Worker’s bindings, code, or configuration in the REST API
```

2022-11-11 17:26 UTC, IgorMinar commented on content/workers/platform/deployments.md
> +The author of a deployment is available in the Cloudflare dashboard, displayed after a wrangler publish, visible via [wrangler documentation](/workers/wrangler/commands#deployments) command, accessib
is the last "optionally" part correct? I don't see author field in the runtime binding API.

2022-11-11 17:26 UTC, IgorMinar commented on content/workers/platform/deployments.md
> +### Metadata binding
I assume that we are temporarily removing / commenting out this part until we settle the binding discussion.

2022-11-11 17:26 UTC, IgorMinar commented on content/workers/platform/deployments.md
> +### Deployments consist of :
Hmm... this section, especially this early on, is a bit confusing to me.

Are you describing our internal data structure, or is this the shape of the data that as a developer I can consume?

It is not the the runtime binding API, because that's described later. Could you please clarify what this is. Also consider moving this section to later in the doc unless it's really critical part of the intro.

2022-11-11 17:26 UTC, IgorMinar commented on content/workers/wrangler/commands.md
> +🟩Active
nit: have we considered adding a space between the green square and Active?

2022-11-11 17:26 UTC, IgorMinar commented on content/workers/platform/deployments.md
> +## Triggering a new Deployment
```suggestion
## Creating a new Deployment
```

2022-11-11 17:26 UTC, IgorMinar commented on content/workers/platform/deployments.md
> +New Deployments will be issued whenever you change code, configuration, or bindings.
```suggestion
New Deployments will be created whenever you change code, configuration, or bindings.
```

2022-11-11 17:51 UTC, kabirsikand commented on content/workers/platform/deployments.md
> +### Metadata binding
yup!

2022-11-11 17:52 UTC, kabirsikand commented on content/workers/platform/deployments.md
> +The author of a deployment is available in the Cloudflare dashboard, displayed after a wrangler publish, visible via [wrangler documentation](/workers/wrangler/commands#deployments) command, accessib
Not anymore, was pulled.

2022-11-11 18:02 UTC, lrapoport-cf commented
@kabirsikand did we want to indicate anywhere on the docs that the feature is in beta?

2022-11-11 21:54 UTC, jspspike commented on content/workers/platform/deployments.md
> +
Maybe explicitly state that changing triggers such as routes/cron will not result in a deployment. Might help clarify it for users who expect that to be the case

2022-11-11 21:54 UTC, jspspike commented on content/workers/platform/deployments.md
> +Updates to code can be as small as a simple whitespace change. Any changes to code will trigger a new deployment.
Maybe say `wrangler publish` will create a new deployment even if there are no changes made to code or bindings

2022-11-11 22:09 UTC, JacobMGEvans commented on content/workers/platform/deployments.md
> +Updates to code can be as small as a simple whitespace change. Any changes to code will trigger a new deployment.
That feels like documenting a something that isn't intentional behavior. We should consider making it something that doesn't happen rather than documenting it.

2022-11-16 15:39 UTC, deadlypants1973 commented on content/workers/platform/deployments.md
> +Deployments are a set of static historical ‘snapshots’ of your Worker. They include the code, configuration, and bindings associated with your Worker. A change to any of these will trigger a new depl
```suggestion
Deployments are a set of static historical snapshots of your Worker. They include the code, configuration, and bindings associated with your Worker. A change to any of these will trigger a new deployment on Cloudflare’s network.
```
Can we write something more technically straightforward than 'snapshots'? Like "Deployments are your Worker running in production." This reads more like a blog than technical documentation. @kabirsikand

2022-11-16 15:39 UTC, deadlypants1973 commented on content/workers/platform/deployments.md
> +Only **one** deployment is active at any time. Currently this is the latest deployment. The active deployment is accessible via any of your configured custom domains, routes, service bindings, schedu
```suggestion
Only one deployment is active at any time. The active deployment is your latest deployment. The active deployment is accessible via any of your configured custom domains, routes, service bindings, schedules, and your `*.workers.dev` subdomain.
```

2022-11-16 15:39 UTC, deadlypants1973 commented on content/workers/platform/deployments.md
> +You can view a list of your deployments in the Cloudflare dashboard under the **‘Deployments’** tab within any Worker’s detail view. You can also use the `wrangler deployments` command to list out th
```suggestion
You can view a list of your deployments in the Cloudflare dashboard > **Workers** > **your Worker project** > **Deployments**. You can also use the `wrangler deployments` command to list out the most recent deployments.
```

2022-11-16 15:39 UTC, deadlypants1973 commented on content/workers/platform/deployments.md
> +* Changes to a Worker’s bindings, code, or configuration in the CLI via [wrangler publish](/workers/wrangler/commands#publish)
```suggestion
Deployments are triggered by:

* Changes to a Worker’s bindings, code, or configuration in the Cloudflare dashboard.
* Changes to a Worker’s bindings, code, or configuration in the REST API.
* Changes to a Worker’s bindings, code, or configuration in the CLI via [wrangler publish](/workers/wrangler/commands#publish).
```

2022-11-16 15:39 UTC, deadlypants1973 commented on content/workers/platform/deployments.md
> +The [`wrangler deployments`](/workers/wrangler/commands#deployments) command will output information about the most recent deployments.
This and `publish` description are extremely similar? Is this intentional? I know the images are different but still.

2022-11-16 15:39 UTC, deadlypants1973 commented on content/workers/platform/deployments.md
> +* Changing a Worker’s secret or environment variable names and values
```suggestion
* Changing a Worker’s usage model.
* Changing a Worker’s secret or environment variable names and values.
```

2022-11-16 15:39 UTC, deadlypants1973 commented on content/workers/platform/deployments.md
> +## Author and Source
```suggestion
## Author and source
```

2022-11-16 15:39 UTC, deadlypants1973 commented on content/workers/platform/deployments.md
> +Updates to bindings include a change to the value or variable name of a binding, or any CRUD operation on an individual binding. Notably, this does not include changes to the target resource itself –
```suggestion
Updates to bindings include a change to the value or variable name of a binding, or any CRUD operation on an individual binding. Notably, this does not include changes to the target resource itself. For example, changing the code of a Worker B that is connected via a service binding from Worker A will not trigger a new deployment on Worker A. Only changes to the service binding between Worker A and Worker B will trigger a new deployment.
```

2022-11-16 15:39 UTC, deadlypants1973 commented on content/workers/platform/deployments.md
> +The author of a deployment is available in the Cloudflare dashboard, visible via [wrangler documentation](/workers/wrangler/commands#deployments) command, and accessible in [Cloudflare’s REST API](ht
`wrangler documentation` command? or `wrangler deployment` command? is `wrangler documentation` a new command that hasn't been documented yet?

2022-11-16 15:39 UTC, deadlypants1973 commented on content/workers/platform/deployments.md
> +The author of a deployment is available in the Cloudflare dashboard, visible via [wrangler documentation](/workers/wrangler/commands#deployments) command, and accessible in [Cloudflare’s REST API](ht
```suggestion
The author of a deployment is available in the Cloudflare dashboard, visible via [`wrangler deployments`](/workers/wrangler/commands#deployments) command, and accessible in [Cloudflare’s REST API](https://api.cloudflare.com/).
```

2022-11-16 16:52 UTC, deadlypants1973 commented on content/workers/platform/deployments.md
> +The [`wrangler deployments`](/workers/wrangler/commands#deployments) command will output information about the most recent deployments.
My advice is to get rid of the screenshots because the terminal will look different as the wrangler team updates the command. Instead, I would publish very clear verbal descriptions here on these commands and why you put them in the article.

2022-11-16 16:54 UTC, deadlypants1973 commented on content/workers/platform/deployments.md
> +The Deployments tab of your Cloudflare dashboard will include information about historical deployments, and your Worker’s detail page will now indicate information about the most recently deployed an
```suggestion
In the Cloudflare dashboard, **Deployments** will show information about historical deployments. Your Worker’s detail page will now indicate information about the most recently deployed and currently active deployment.
```

What is the 'detail page'?

2022-11-16 16:56 UTC, deadlypants1973 requested changes
Wrangler publish description differs too much from what is on the commands page for Wrangler. This should be unified so we don't have 2 pages with separate info

2022-11-17 13:35 UTC, deadlypants1973 approved these changes

2022-11-17 13:41 UTC, merged