queues: more documentation
cloudflare/cloudflare-docs pull request #6677
Opened 2022-11-14 13:09 UTC by elithrar

cc/ @deadlypants1973 @rts-rob 

- [x] Initial "How Queues Works" page
- [x] Delivery Guarantees page
- [x] Batching and Retries (also covers Dead Letter Queues)
- [x] Updated pricing with better examples + finer details on edge cases
- [x] Clarified limits and how a KB is defined

2022-11-14 21:03 UTC, w-kuhn commented on content/queues/pricing.md
> +| Standard operations | 2 * 100 \* 99,000,000        | 1,000,000  | 199,000,000  | $79.60     |
are these usage numbers correct?

2022-11-14 21:23 UTC, elithrar commented on content/queues/pricing.md
> +| Standard operations | 2 * 100 \* 99,000,000        | 1,000,000  | 199,000,000  | $79.60     |
Good catch, fixing...

2022-11-15 17:52 UTC, a-robinson commented on content/queues/pricing.md
> +* Messages larger than 64KB are charged as if they were multiple messages: for exampele, a 65KB message and a 127KB message would both incur two read, write and delete operations.
```suggestion
* Messages larger than 64 KB are charged as if they were multiple messages: for example, a 65 KB message and a 127 KB message would both incur two operation charges when written, read, or deleted.
```

2022-11-15 17:52 UTC, a-robinson commented on content/queues/pricing.md
> +* Messages that reach the maximum retries and that are written to a [Dead Letter Queue](https://developers.cloudflare.com/queues/batching-retries) incur a write operation for each 64KB chunk. A messa
```suggestion
* Messages that reach the maximum retries and that are written to a [Dead Letter Queue](https://developers.cloudflare.com/queues/batching-retries) incur a write operation for each 64 KB chunk. A message that was retried 3 times (the default), fails delivery on the fourth time and is written to a Dead Letter Queue would incur five (5) read operations.
```

2022-11-15 17:52 UTC, a-robinson commented on content/queues/pricing.md
> +* Messages that are written to a queue, but that reach the maximum persistency duration (or "expire") before they are read, incur only a write and delete operation per 64KB chunk.
```suggestion
* Messages that are written to a queue, but that reach the maximum persistence duration (or "expire") before they are read, incur only a write and delete operation per 64 KB chunk.
```

2022-11-15 17:52 UTC, a-robinson commented on content/queues/pricing.md
> +An application that sends 100 million ~127KB messages (each message counts as two 64KB chunks) per month would have an estimated bill resembling the following:
I can see why you did it this way and don't know that there's anything to be done about it, but FWIW it does look kind of strange to see 127 KB used in the examples here rather than 128 KB.

2022-11-15 17:52 UTC, a-robinson commented on content/queues/pricing.md
> +An application that sends 100 million ~127KB messages (each message counts as two 64KB chunks) per month would have an estimated bill resembling the following:
```suggestion
An application that sends 100 million ~127 KB messages (each message counts as two 64 KB chunks) per month would have an estimated bill resembling the following:
```

2022-11-15 17:52 UTC, a-robinson commented on content/queues/pricing.md
> +If an application writes one million messages a day (in a 30 day month), and each message is less than 64 KB in size, the estimated bill for the month would be:
Why does the example only include writes and not reads or deletes? Is this scenario even possible given that deletes would be incurred after the message retention window expires?

2022-11-15 18:10 UTC, a-robinson commented on content/queues/learning/batching-retries.md
> +For example, a `max_batch_size = 30` and a `max_batch_timeout = 10` means that if 30 messages are written to the queue, we'll deliver a batch of 30 messages. However, if it takes longer than 10 secon
```suggestion
For example, a `max_batch_size = 30` and a `max_batch_timeout = 10` means that if 30 messages are written to the queue, we'll deliver a batch of 30 messages. However, if it takes longer than 10 seconds for those 30 messages to be written to the queue, then the consumer will get a batch of messages that contains however many messages were on the queue at the time (somewhere between 1 and 29, in this case).
```

2022-11-15 18:10 UTC, a-robinson commented on content/queues/learning/batching-retries.md
> +**Importantly, in order to process messages placed on our DLQ, you need to set up a consumer associated with that queue as well**. Messages otherwise delivered to a DLQ without an active consumer wil
Is 5 days what we decided on for this? I thought it was 4?

Although on this topic, it'd be nice to mention this somewhere else, e.g. perhaps on the Limits page.

2022-11-15 18:10 UTC, a-robinson commented on content/queues/learning/how-queues-works.md
> +**For most applications, a single producer per queue with multiple queues** is easier to reason with, and allows you to
Incomplete sentence

2022-11-15 18:10 UTC, a-robinson commented on content/queues/learning/how-queues-works.md
> + },
```suggestion
```

2022-11-15 18:10 UTC, a-robinson commented on content/queues/learning/how-queues-works.md
> +Notably, you can use associate the same consumer with multiple queues: the `queue` handler that defines your consumer will be invoked the same. The `MessageBatch` that is passed to your `queue` handl
```suggestion
Notably, you can use associate the same consumer with multiple queues: the `queue` handler that defines your consumer will be invoked the same. The `MessageBatch` that is passed to your `queue` handler includes a `queue` property with the name the batch was consumed from. This can reduce the amount of code you need to write, and allow you to process messages based on the name of your queues.
```

2022-11-15 18:10 UTC, a-robinson commented on content/queues/learning/how-queues-works.md
> +Notably, you can use associate the same consumer with multiple queues: the `queue` handler that defines your consumer will be invoked the same. The `MessageBatch` that is passed to your `queue` handl
This reads awkwardly now -- "... `queue` handler includes a `queue` property" -- but that is indeed the name of the property on the `MessageBatch`, not `name`. Maybe the sentence just needs restructuring to be clearer.

2022-11-15 18:10 UTC, a-robinson commented on content/queues/learning/how-queues-works.md
> +A message is the object you are producing to, and consuming from, a queue. Any serializable object can be published to a queue: for most developers, this means either simple strings or JSON objects.
```suggestion
A message is the object you are producing to and consuming from a queue. Any serializable object can be published to a queue: for most developers, this means either simple strings or JSON objects.
```

2022-11-15 18:10 UTC, a-robinson commented on content/queues/learning/how-queues-works.md
> +A message is the object you are producing to, and consuming from, a queue. Any serializable object can be published to a queue: for most developers, this means either simple strings or JSON objects.
Sorry for the minor tweak here, but as written my brain interpreted this as saying that you are producing to the message (rather than producing the message to a queue)

2022-11-15 18:31 UTC, elithrar commented on content/queues/learning/batching-retries.md
> +**Importantly, in order to process messages placed on our DLQ, you need to set up a consumer associated with that queue as well**. Messages otherwise delivered to a DLQ without an active consumer wil
Good catch. Should be 4. And agree. Will update `/limits` as well.

2022-11-15 19:24 UTC, elithrar commented on content/queues/pricing.md
> +An application that sends 100 million ~127KB messages (each message counts as two 64KB chunks) per month would have an estimated bill resembling the following:
I wanted to avoid the (slight) complexity of a 128KB message + metadata likely incurring 3x ops. We can tweak if folks find confusing in the other direction?

2022-11-15 19:24 UTC, elithrar commented on content/queues/pricing.md
> +If an application writes one million messages a day (in a 30 day month), and each message is less than 64 KB in size, the estimated bill for the month would be:
Just omitted from the copy I carried over. Will fix.

2022-11-15 19:39 UTC, a-robinson commented on content/queues/pricing.md
> +| Standard operations | 2 \* 3 \* 100 \* 1,000,000   | 1,000,000  | 299,000,000  | $119.60     |
Looks like your math is off here by a factor of 2. Should be 599,000,000 billed operations, right? Plus a correspondingly higher price?

2022-11-15 20:04 UTC, elithrar commented on content/queues/learning/how-queues-works.md
> +Notably, you can use associate the same consumer with multiple queues: the `queue` handler that defines your consumer will be invoked the same. The `MessageBatch` that is passed to your `queue` handl
Added an example + rephrased.

2022-11-15 20:07 UTC, a-robinson approved these changes

2022-11-15 20:08 UTC, elithrar commented on content/queues/pricing.md
> +| Standard operations | 2 \* 3 \* 100 \* 1,000,000   | 1,000,000  | 299,000,000  | $119.60     |
😢 

(Fixed)

2022-11-16 10:53 UTC, deadlypants1973 requested changes

2022-11-16 10:53 UTC, deadlypants1973 commented on content/queues/learning/batching-retries.md
> +When configuring a [consumer](https://developers.cloudflare.com/queues/learning/how-queues-works#consumers) for a queue, you can also define how messages are batched as they are delivered.
```suggestion
When configuring a [consumer Worker](https://developers.cloudflare.com/queues/learning/how-queues-works#consumers) for a queue, you can also define how messages are batched as they are delivered.
```

2022-11-16 10:53 UTC, deadlypants1973 commented on content/queues/learning/batching-retries.md
> +3. "Smooth" out load over time, especially if your producers are associated with user-facing activity
```suggestion
1. Reduce the total number of times your consumer Worker needs to be invoked (which can reduce costs).
2. Allow you to batch messages when writing to an external API or service (reducing writes).
3. Disperse load over time, especially if your producer Workers are associated with user-facing activity.
```

We always avoid "" and colloquial language in docs, so I tried to replace 'smooth' with the verb that most accurately captures what is happening, but please change it to something else if this isn't technically correct.

2022-11-16 10:53 UTC, deadlypants1973 commented on content/queues/learning/batching-retries.md
> +There are two ways to configure how messages are batched, and these can be configured when associating your consumer with a queue.
```suggestion
There are two ways to configure how messages are batched. You configure batching when connecting your consumer Worker to a queue.
```

2022-11-16 10:53 UTC, deadlypants1973 commented on content/queues/learning/batching-retries.md
> +* `max_batch_size` - the _maximum_ size of a batch delivered to a consumer (defaults to 10 messages)
```suggestion
* `max_batch_size` - The maximum size of a batch delivered to a consumer (defaults to 10 messages).
```

2022-11-16 10:53 UTC, deadlypants1973 commented on content/queues/learning/batching-retries.md
> +* `max_batch_timeout` - the _maximum_ amount of time the queue will wait before delivering a batch to a consumer (defaults to 5 seconds)
```suggestion
* `max_batch_timeout` - The maximum amount of time the queue will wait before delivering a batch to a consumer (defaults to 5 seconds).
```

2022-11-16 10:53 UTC, deadlypants1973 commented on content/queues/learning/batching-retries.md
> +Both `max_batch_size` and `max_batch_timeout` work together: whichever limit is reached first will trigger the delivery of a batch.
```suggestion
Both `max_batch_size` and `max_batch_timeout` work together. Whichever limit is reached first will trigger the delivery of a batch.
```

2022-11-16 10:53 UTC, deadlypants1973 commented on content/queues/learning/batching-retries.md
> +For example, a `max_batch_size = 30` and a `max_batch_timeout = 10` means that if 30 messages are written to the queue, we'll deliver a batch of 30 messages. However, if it takes longer than 10 secon
```suggestion
For example, a `max_batch_size = 30` and a `max_batch_timeout = 10` means that if 30 messages are written to the queue, the consumer Worker is called to deliver a batch of 30 messages. However, if it takes longer than 10 seconds for those 30 messages to be written to the queue, then the consumer Worker will get a batch of messages that contains however many messages were written to the queue within those 10 seconds (somewhere between 0 and 29, in this case).
```

2022-11-16 10:53 UTC, deadlypants1973 commented on content/queues/learning/batching-retries.md
> +For example, a `max_batch_size = 30` and a `max_batch_timeout = 10` means that if 30 messages are written to the queue, we'll deliver a batch of 30 messages. However, if it takes longer than 10 secon
```suggestion
For example, a `max_batch_size = 30` and a `max_batch_timeout = 10` means that if 30 messages are written to the queue, the consumer Worker will deliver a batch of 30 messages. However, if it takes longer than 10 seconds for those 30 messages to be written to the queue, then the consumer Worker will get a batch of messages that contains however many messages were on the queue at the time (somewhere between 1 and 29, in this case).
```

2022-11-16 10:53 UTC, deadlypants1973 commented on content/queues/learning/batching-retries.md
> +When a message is failed to be delivered, the default behaviour is to retry delivery three times before marking the delivery is failed (see [Dead Letter Queues](#dead-letter-queues)). You can set `ma
```suggestion
When a message is failed to be delivered, the default behaviour is to retry delivery three times before marking the delivery as failed (refer to [Dead Letter Queues](#dead-letter-queues)). You can set `max_retries` (defaults to 3) when configuring your consumer Worker, but in most cases we recommend leaving this as the default.
```

2022-11-16 10:53 UTC, deadlypants1973 commented on content/queues/learning/batching-retries.md
> +Each retry counts as an additional "read" operation per [Queues pricing](https://developers.cloudflare.com/queues/pricing).
```suggestion
Each retry counts as an additional read operation per [Queues pricing](https://developers.cloudflare.com/queues/pricing).
```

2022-11-16 10:53 UTC, deadlypants1973 commented on content/queues/learning/batching-retries.md
> +**Note**: When a single message within a batch fails to be delivered, the entire batch is retried. For example, if a batch of 10 messages is delivered, but the 8th message fails to be delivered, all
```suggestion
When a single message within a batch fails to be delivered, the entire batch is retried. For example, if a batch of 10 messages is delivered, but the 8th message fails to be delivered, all 10 messages will be retried and thus re-delivered to your consumer in full.
```

2022-11-16 10:53 UTC, deadlypants1973 commented on content/queues/learning/batching-retries.md
> +A Dead Letter Queue, or "DLQ", is a common concept in a messaging system, and represents where messages are sent when a delivery failure occurs with a consumer after `max_retries` is reached. A Dead
```suggestion
A Dead Letter Queue (DLQ) is a common concept in a messaging system, and represents where messages are sent when a delivery failure occurs with a consumer after `max_retries` is reached. A Dead Letter Queue is just like any other queue, and can be produced to and consumed from independently. 
```

2022-11-16 10:53 UTC, deadlypants1973 commented on content/queues/learning/batching-retries.md
> +With Cloudflare Queues, a Dead Letter Queue is configured as part of your consumer. For example, the following consumer configuration would send messages to our DLQ named "my-other-queue" after retry
```suggestion
With Cloudflare Queues, a Dead Letter Queue is configured as part of your consumer. For example, the following consumer configuration would send messages to our DLQ named `"my-other-queue"` after retrying delivery (by default, 3 times):
```

2022-11-16 10:53 UTC, deadlypants1973 commented on content/queues/learning/batching-retries.md
> +**Note**: When a single message within a batch fails to be delivered, the entire batch is retried. For example, if a batch of 10 messages is delivered, but the 8th message fails to be delivered, all
Either we make this also an aside or take out **Note**.

2022-11-16 10:53 UTC, deadlypants1973 commented on content/queues/learning/batching-retries.md
> +[[queues.consumers]]
```suggestion
```toml
---
filename: wrangler.toml
---
[[queues.consumers]]
```

2022-11-16 10:53 UTC, deadlypants1973 commented on content/queues/learning/batching-retries.md
> +**Importantly, in order to process messages placed on our DLQ, you need to set up a consumer associated with that queue as well**. Messages otherwise delivered to a DLQ without an active consumer wil
```suggestion
To process messages placed on your DLQ, you need to set up a consumer associated with that queue. Messages delivered to a DLQ without an active consumer will persist for four (4) days before being deleted from the queue.
```

2022-11-16 10:53 UTC, deadlypants1973 commented on content/queues/learning/delivery-guarantees.md
> +Delivery guarantees define how strongly a messaging system enforces the delivery of messages it processes
```suggestion
Delivery guarantees define how strongly a messaging system enforces the delivery of messages it processes.
```

2022-11-16 10:53 UTC, deadlypants1973 commented on content/queues/learning/delivery-guarantees.md
> +Each mode comes with a number of trade-offs. As you make stronger guarantees about message delivery, the system needs to perform more checks and acknowledgments to ensure that messages are delivered,
What is a 'mode' in this context? I don't see the connection to the sentence above.

2022-11-16 10:53 UTC, deadlypants1973 commented on content/queues/learning/delivery-guarantees.md
> +* This means that messages are guaranteed to be delivered "at least once", and in rare occassions, may be delivered more than once.
```suggestion
* This means that messages are guaranteed to be delivered at least once, and in rare occassions, may be delivered more than once.
```

2022-11-16 10:53 UTC, deadlypants1973 commented on content/queues/learning/delivery-guarantees.md
> +* For the vast majority of applications, this is the right balance between "don't lose any messages" and "minimize end-to-end latency", as "exactly once" delivery incurs additional overheads in any m
```suggestion
* For the majority of applications, this is the right balance between not losing any messages and minimizing end-to-end latency, as exactly once delivery incurs additional overheads in any messaging system.
```

2022-11-16 10:53 UTC, deadlypants1973 commented on content/queues/learning/delivery-guarantees.md
> +Each mode comes with a number of trade-offs. As you make stronger guarantees about message delivery, the system needs to perform more checks and acknowledgments to ensure that messages are delivered,
Is a mode something the user sets? Is a delivery guarantee something user sets?

2022-11-16 10:53 UTC, deadlypants1973 commented on content/queues/pricing.md
> +Cloudflare Queues requires the [Workers paid plan](https://developers.cloudflare.com/workers/platform/pricing/) to use, but does not increase your monthly subscription cost.
```suggestion
Cloudflare Queues requires the [Workers Paid plan](https://developers.cloudflare.com/workers/platform/pricing/) to use, but does not increase your monthly subscription cost.
```

2022-11-16 10:53 UTC, deadlypants1973 commented on content/queues/pricing.md
> +* There are no data transfer ("egress") or throughput (bandwidth) charges.
```suggestion
* There are no data transfer (egress) or throughput (bandwidth) charges.
```

2022-11-16 10:53 UTC, deadlypants1973 commented on content/queues/pricing.md
> +estimated bill for the month would be:
```suggestion
If an application writes, reads and deletes (consumes) one million messages a day (in a 30 day month), and each message is less than 64 KB in size, the estimated bill for the month would be:
```

2022-11-16 10:53 UTC, deadlypants1973 commented on content/queues/pricing.md
> +estimated bill resembling the following:
```suggestion
An application that writes, reads and deletes (consumes) 100 million ~127 KB messages (each message counts as two 64 KB chunks) per month would have an estimated bill resembling the following:
```

2022-11-16 10:53 UTC, deadlypants1973 commented on content/queues/learning/how-queues-works.md
> +Messages themselves can be batched when delivered to the consumer, and messages within a batch are treated as "all or nothing" when determining retries. If the "last" message in a batch fails to be p
```suggestion
Messages themselves can be batched when delivered to the consumer, and messages within a batch are treated as all or nothing when determining retries. If the last message in a batch fails to be processed, the entire batch will be retried.
```

2022-11-16 10:53 UTC, deadlypants1973 commented on content/queues/learning/how-queues-works.md
> +Importantly, each queue can only have one active consumer: this allows Cloudflare Queues to achieve "at least once" delivery and minimize the risk of duplicate messages beyond that.
```suggestion
Importantly, each queue can only have one active consumer. This allows Cloudflare Queues to achieve at least once delivery and minimize the risk of duplicate messages beyond that.
```

2022-11-16 10:53 UTC, deadlypants1973 commented on content/queues/learning/how-queues-works.md
> +For example, a consumer configured to consume messages from multiple queues would resemble the following:
```suggestion
For example, a consumer Worker configured to consume messages from multiple queues would resemble the following:
```

2022-11-16 10:53 UTC, deadlypants1973 commented on content/queues/learning/how-queues-works.md
> +Notably, you can use associate the same consumer with multiple queues: the `queue` handler that defines your consumer will be invoked the same.
```suggestion
Notably, you can use the same consumer with multiple queues: the `queue` handler that defines your consumer Worker will be invoked the same <?>
```

2022-11-16 10:53 UTC, deadlypants1973 commented on content/queues/learning/how-queues-works.md
> +Notably, you can use associate the same consumer with multiple queues: the `queue` handler that defines your consumer will be invoked the same.
There's something missing here

2022-11-16 10:53 UTC, deadlypants1973 commented on content/queues/learning/how-queues-works.md
> +[[queues.consumers]]
```suggestion
```toml
---
filename: wrangler.toml
---
[[queues.consumers]]
```

2022-11-16 10:53 UTC, deadlypants1973 commented on content/queues/learning/how-queues-works.md
> +You then connect that consumer to a queue with `wrangler queues consumer <queue-name> <worker-script-name>` or by defining a `[[queues.consumers]]` configuration in your `wrangler.toml` manually:
```suggestion
You then connect that consumer Worker to a queue with `wrangler queues consumer <queue-name> <worker-script-name>` or by defining a `[[queues.consumers]]` configuration in your `wrangler.toml` manually:
```

2022-11-16 10:53 UTC, deadlypants1973 commented on content/queues/learning/how-queues-works.md
> +A queue can have multiple producers: for example, you may have multiple Workers writing events or logs to a shared queue based on incoming HTTP requests from users. There is no limit to the total num
```suggestion
A queue can have multiple producer Workers. For example, you may have multiple Workers writing events or logs to a shared queue based on incoming HTTP requests from users. There is no limit to the total number of producer Workers that can write to a single queue. Additionally, multiple queues can be bound to a single Worker. That single Worker can decide which queue to write to (or write to multiple) based on any logic you define in your code.
```

2022-11-16 10:53 UTC, deadlypants1973 commented on content/queues/learning/how-queues-works.md
> +A producer is the term for a client that is publishing or _producing_ messages on to a queue. A producer is configured by [binding](https://developers.cloudflare.com/workers/platform/bindings/) a que
```suggestion
A producer is the term for a client that is publishing or producing messages on to a queue. A producer Worker is configured by [binding](https://developers.cloudflare.com/workers/platform/bindings/) a queue to a Worker and writing messages to the queue by calling that binding.
```

2022-11-16 10:53 UTC, deadlypants1973 commented on content/queues/learning/how-queues-works.md
> +Cloudflare Queues is great at decoupling components of applications, like the checkout and order fulfillment services for an ecommerce site. Decoupled services are easier to reason about, deploy, and
```suggestion
Cloudflare Queues is a flexible messaging queue that allows you to queue messages for asynchronous processing. Message queues are great at decoupling components of applications, like the checkout and order fulfillment services for an e-commerce site. Decoupled services are easier to reason about, deploy, and implement, allowing you to ship features that delight your customers without worrying about synchronizing complex deployments. Queues also allow you to batch and buffer calls to downstream services and APIs.
```

2022-11-16 10:53 UTC, deadlypants1973 commented on content/queues/learning/how-queues-works.md
> +## What is a Queue
```suggestion
## What is a queue
```

2022-11-16 10:53 UTC, deadlypants1973 commented on content/queues/learning/how-queues-works.md
> +A queue is the core concept underpinning Cloudflare Queues: a queue can be thought of as a buffer or list that automatically scales as messages are written to it, and allows a consumer to pull messag
```suggestion
A queue is a buffer or list that automatically scales as messages are written to it, and allows a consumer Worker to pull messages from that same queue.
```

2022-11-16 10:53 UTC, deadlypants1973 commented on content/queues/learning/how-queues-works.md
> +Queues are designed to be reliable, and messages written to a queue should never be lost once the write succeeds. Similarly, messages are not deleted from a queue until the [consumer](#consumer) has
```suggestion
Queues are designed to be reliable, and messages written to a queue should never be lost once the write succeeds. Similarly, messages are not deleted from a queue until the [consumer](#consumer) Worker has successfully consumed the message.
```

2022-11-16 10:53 UTC, deadlypants1973 commented on content/queues/learning/how-queues-works.md
> +Developers can create multiple queues, and creating multiple queues can be useful to:
```suggestion
Developers can create multiple queues. Creating multiple queues can be useful to:
```

2022-11-16 10:53 UTC, deadlypants1973 commented on content/queues/learning/how-queues-works.md
> +* Configure different batching strategies for each consumer connected to a queue.
```suggestion
* Separate different use-cases and processing requirements: for example, a logging queue vs. a password reset queue.
* Horizontally scale your overall throughput (messages per second) by using multiple queues to scale out.
* Configure different batching strategies for each consumer connected to a queue.
```

2022-11-16 10:53 UTC, deadlypants1973 commented on content/queues/learning/how-queues-works.md
> +**For most applications, a single producer per queue with multiple queues** is easier to reason with, and allows you to logically separate the processing for each of your queues.
```suggestion
For most applications, a single producer Worker per queue with multiple queues is easier to manage, and allows you to logically separate the processing for each of your queues.
```

2022-11-16 10:53 UTC, deadlypants1973 commented on content/queues/learning/how-queues-works.md
> +**For most applications, a single producer per queue with multiple queues** is easier to reason with, and allows you to logically separate the processing for each of your queues.
This sentence reads weird `a single producer Worker per queue with multiple queues`

2022-11-16 14:21 UTC, elithrar commented on content/queues/learning/batching-retries.md
> +There are two ways to configure how messages are batched, and these can be configured when associating your consumer with a queue.
Since this is not the Getting Started guide, `wrangler.toml` isn't the only way to configure this: the API and the UI are also able to configure consumers.

2022-11-16 14:22 UTC, elithrar commented on content/queues/learning/batching-retries.md
> +* `max_batch_timeout` - the _maximum_ amount of time the queue will wait before delivering a batch to a consumer (defaults to 5 seconds)
I don't think we need to say "consumer Worker" every time — today, a consumer needs to be a Worker, but it may not be forever. The concept of a "consumer" is unrelated to a Worker.

2022-11-16 14:22 UTC, elithrar commented on content/queues/learning/how-queues-works.md
> +Queues are designed to be reliable, and messages written to a queue should never be lost once the write succeeds. Similarly, messages are not deleted from a queue until the [consumer](#consumer) has
Same as above — "consumer Worker" is unnecessary here.

2022-11-16 14:26 UTC, deadlypants1973 commented on content/queues/learning/batching-retries.md
> +There are two ways to configure how messages are batched, and these can be configured when associating your consumer with a queue.
Updated

2022-11-16 14:38 UTC, deadlypants1973 commented on content/queues/learning/how-queues-works.md
> +A queue can have multiple producers: for example, you may have multiple Workers writing events or logs to a shared queue based on incoming HTTP requests from users. There is no limit to the total num
leaving Worker in here before producer because we are talking about Workers

2022-11-16 14:43 UTC, deadlypants1973 commented on content/queues/learning/how-queues-works.md
> +Notably, you can use associate the same consumer with multiple queues: the `queue` handler that defines your consumer will be invoked the same.
Updated

2022-11-16 14:44 UTC, elithrar commented on content/queues/learning/delivery-guarantees.md
> +Each mode comes with a number of trade-offs. As you make stronger guarantees about message delivery, the system needs to perform more checks and acknowledgments to ensure that messages are delivered,
Rewriting

2022-11-16 14:50 UTC, deadlypants1973 approved these changes

2022-11-16 16:37 UTC, merged