Update index.md
cloudflare/cloudflare-docs pull request #6682
Opened 2022-11-14 15:16 UTC by sarah-adam

Added a example bucket path: cloudflare-logs/http_requests/example.com

2022-11-16 16:21 UTC, victor-perov requested changes
I think we can move an example to the same line and wrap it in a single "`".

2022-11-16 16:21 UTC, victor-perov commented on content/logs/get-started/enable-destinations/r2/index.md
> +    - Bucket path - For example,
```suggestion
    - Bucket path, for example, `cloudflare-logs/http_requests/example.com`
```

2022-11-16 18:30 UTC, cmackenzie1 approved these changes
Other than the comment from Victor, it looks good to me!

2022-11-16 22:43 UTC, victor-perov requested changes
Just a tiny cleanup needed.

2022-11-16 22:43 UTC, victor-perov commented on content/logs/get-started/enable-destinations/r2/index.md
> +```cloudflare-logs/http_requests/example.com```
```suggestion
```

2022-11-16 22:43 UTC, victor-perov commented on content/logs/get-started/enable-destinations/r2/index.md
> +
```suggestion
```

2022-11-17 10:32 UTC, angelampcosta approved these changes

2022-11-17 11:13 UTC, victor-perov approved these changes

2022-11-17 11:22 UTC, angelampcosta commented
@sarah-adam thank you so much for your feedback!

2022-11-17 11:22 UTC, merged