[1.1.1.1] Update DNS over Discord
cloudflare/cloudflare-docs pull request #674
Opened 2021-01-23 00:19 UTC by MattIPv4

- Add docs for the new whois command
- Fix linebreaks/back-slashes (#602, https://github.com/cloudflare/cloudflare-docs-engine/issues/309)
- Add development note on Workers and source code

2021-01-25 12:40 UTC, abracchi-tw approved these changes

2021-01-28 13:15 UTC, abracchi-tw requested changes

2021-01-28 13:15 UTC, abracchi-tw commented on products/1.1.1.1/src/content/fun-stuff/dns-over-discord.md
> +Curious about who's behind a domain name, an IP address or even an ASN?
I would delete this sentence and dive right into the description of the command

2021-01-29 11:18 UTC, abracchi-tw approved these changes

2021-01-29 11:19 UTC, merged

2021-01-29 11:27 UTC, MattIPv4 commented
Ty once again 🧡