[Radar] add glossary for route leak detection
cloudflare/cloudflare-docs pull request #6806
Opened 2022-11-22 18:50 UTC by digizeph

2022-11-22 22:57 UTC, celso approved these changes

2022-11-23 08:39 UTC, G4brym approved these changes

2022-11-23 09:41 UTC, marciocloudflare requested changes

2022-11-23 09:41 UTC, marciocloudflare commented on content/radar/glossary.md
> +In Cloudflare Radar, you can view the detected route leak events on the corresponding ASN pages. The columns in the table are defined as follows:
```suggestion
In Cloudflare Radar, you can inspect the detected route leak events on the corresponding autonomous system number (ASN) pages. The columns in the table are defined as follows:
```

2022-11-23 09:41 UTC, marciocloudflare commented on content/radar/glossary.md
> +In Cloudflare Radar, you can view the detected route leak events on the corresponding ASN pages. The columns in the table are defined as follows:
Where are these pages? Any link we can add to this?

2022-11-23 09:41 UTC, marciocloudflare commented on content/radar/glossary.md
> +In Cloudflare Radar, you can view the detected route leak events on the corresponding ASN pages. The columns in the table are defined as follows:
Also, replaced `view` with `inspect` as we try to use inclusive language whenever possible.

2022-11-23 09:41 UTC, marciocloudflare commented on content/radar/glossary.md
> +* `Vatange Points`: the number of route collectors that observed a route leak event
```suggestion
* `From`: The autonomous system (AS) from which the routes are learned from.
* `By`: The AS that leaked the routes, or the leaker.
* `To`: The AS that received and propagated the leaked routes.
* `Start` and `End`: The starting and ending time of a route leak event.
* `BGP Msgs.`: The number of BGP announcements that contain leaked routes.
* `Prefixes`: The number of IP prefixes a route leak event affects.
* `Origins`: The number of origin ASes a route leak event affects.
* `Vatange Points`: The number of route collectors that observed a route leak event.
```

2022-11-23 09:41 UTC, marciocloudflare commented on content/radar/glossary.md
> +Learn more about our route leak detection system design and usages [here](https://blog.cloudflare.com/route-leak-detetion).
```suggestion
Learn more about our route leak detection system design and usages  in [Protecting Cloudflare Customers from BGP Insecurity with Route Leak Detection](https://blog.cloudflare.com/route-leak-detection/) blog post.
```

2022-11-23 11:03 UTC, celso commented on content/radar/glossary.md
> +Learn more about our route leak detection system design and usages  in [Protecting Cloudflare Customers from BGP Insecurity with Route Leak Detection](https://blog.cloudflare.com/route-leak-detection
@marciocloudflare can you change this link to https://blog.cloudflare.com/route-leak-detection-with-cloudflare-radar/ ?

2022-11-23 11:03 UTC, celso commented on content/radar/glossary.md
> +In Cloudflare Radar, you can view the detected route leak events on the corresponding ASN pages. The columns in the table are defined as follows:
@marciocloudflare  There are no links right now because an AS page can have route leaks or not, so I suggest we leave it as in. In the future we will have an aggregation page on Radar, we can add the links then.

2022-11-23 12:49 UTC, marciocloudflare approved these changes

2022-11-23 12:49 UTC, marciocloudflare commented on content/radar/glossary.md
> +Learn more about our route leak detection system design and usages  in [Protecting Cloudflare Customers from BGP Insecurity with Route Leak Detection](https://blog.cloudflare.com/route-leak-detection
```suggestion
Learn more about our route leak detection system design and usages  in [How we detect route leaks and our new Cloudflare Radar route leak service](https://blog.cloudflare.com/route-leak-detection-with-cloudflare-radar/) blog post.
```

2022-11-23 12:51 UTC, merged