[d1] add tutorials section and first tutorial
cloudflare/cloudflare-docs pull request #6864
Opened 2022-11-28 20:49 UTC by codewithkristian

2022-11-28 22:22 UTC, WalshyDev requested changes

2022-11-28 22:22 UTC, WalshyDev commented on content/d1/tutorials/build-a-comments-api/index.md
> +Note that this directive, the `[[d1_databases]]` field, currently requires a beta version of wrangler. You can install this for your project using the command `npm install -D wrangler/beta`.
D1 has been in mainline Wrangler for quite a while, I don't see anything not in a release here (we should also just do a release rather than pushing people to beta imo)

2022-11-28 22:22 UTC, WalshyDev commented on content/d1/tutorials/build-a-comments-api/index.md
> +import { cors } from 'hono/cors'
this isn't used till later
```suggestion
```

Sidenote: I question using Hono & TS here, this brings the barrier of entry up quite a bit. We had a lot of people very confused about us using TS in Functions examples and assuming TS knowledge.

2022-11-28 22:22 UTC, WalshyDev commented on content/d1/tutorials/build-a-comments-api/index.md
> +You can also pass a SQL file - perfect for initial data seeding in a single command. Create `src/schema.sql`, which will create a new `comments` table for your project:
nit: it's weird to make this in src, this should really just be in like a `schemas` dir.

2022-11-28 22:22 UTC, WalshyDev commented on content/d1/tutorials/build-a-comments-api/index.md
> +create table comments (
you could use `create table if not exists`

also another nit: i'd make any SQL full caps - `CREATE TABLE IF NOT EXISTS comments`. It's the general practice and just a bit easier to distinguish over names.

2022-11-28 22:22 UTC, WalshyDev commented on content/d1/tutorials/build-a-comments-api/index.md
> +create index idx_comments_post_id on comments (post_slug);
```suggestion
create index idx_comments_post_slug on comments (post_slug);
```

2022-11-28 22:22 UTC, WalshyDev commented on content/d1/tutorials/build-a-comments-api/index.md
> +Begin by running `wrangler whoami` to confirm that you are logged in to yuor Cloudflare account. If you are not logged in, Wrangler will prompt you to login, creating an API key that you can use to m
```suggestion
Begin by running `wrangler whoami` to confirm that you are logged in to your Cloudflare account. If you are not logged in, Wrangler will prompt you to login, creating an API key that you can use to make authenticated requests automatically from your local machine.
```

2022-11-28 22:22 UTC, WalshyDev commented on content/d1/tutorials/build-a-comments-api/index.md
> +$ curl https://d1-example.signalnerve.workers.dev/api/posts/hello-world/comments | jq
I'd probably remove `jq` here, most of people reading this won't have it

2022-11-28 22:22 UTC, WalshyDev commented on content/d1/tutorials/build-a-comments-api/index.md
> +This application is just an API backend, best served for use with a frontend UI for actually creating and viewing comments. If you'd like to test this backend with a prebuild frontend UI, visit the e
Can we get this in the CF org? Templates repo maybe?

2022-11-30 16:05 UTC, codewithkristian commented on content/d1/tutorials/build-a-comments-api/index.md
> +import { cors } from 'hono/cors'
ty - questions/concerns about hono or just the TS part? I removed TS config

2022-11-30 17:40 UTC, deadlypants1973 commented on content/d1/tutorials/build-a-comments-api/index.md
> +In this tutorial, you'll learn how to use D1 to add comments to a static blog site. To do this, you will construct a new D1 database, and build a JSON API that allows the creation and retrieval of co
```suggestion
In this tutorial, you wil learn how to use D1 to add comments to a static blog site. To do this, you will construct a new D1 database, and build a JSON API that allows the creation and retrieval of comments.
```

2022-11-30 17:40 UTC, deadlypants1973 commented on content/d1/tutorials/build-a-comments-api/index.md
> +## Project setup
```suggestion
## Set up your project
```

2022-11-30 17:40 UTC, deadlypants1973 commented on content/d1/tutorials/build-a-comments-api/index.md
> +First, create a new directory and initialize a new project using [Wrangler](https://github.com/cloudflare/wrangler2), the command-line tool for Cloudflare's developer products:
```suggestion
First, use [Wrangler](https://github.com/cloudflare/wrangler2), the command-line tool for Cloudflare's developer products, to create a new directory and initialize a new Worker project:
```

2022-11-30 17:40 UTC, deadlypants1973 commented on content/d1/tutorials/build-a-comments-api/index.md
> +In this example, we’ll use [Hono](https://github.com/honojs/hono), an Express.js-style framework, to rapidly build your API. To use Hono in this project, install it using NPM:
```suggestion
In this example, you will use [Hono](https://github.com/honojs/hono), an Express.js-style framework, to build your API. To use Hono in this project, install it using npm:
```

2022-11-30 17:40 UTC, deadlypants1973 commented on content/d1/tutorials/build-a-comments-api/index.md
> +Now you'll create a D1 database. In Wrangler 2, there is support for the `wrangler d1` subcommand, which allows you to create and query your D1 databases directly from the command line. Create a new
```suggestion
You will now create a D1 database. In Wrangler 2, there is support for the `wrangler d1` subcommand, which allows you to create and query your D1 databases directly from the command line. Create a new database with `wrangler d1 create`:
```

2022-11-30 17:40 UTC, deadlypants1973 commented on content/d1/tutorials/build-a-comments-api/index.md
> +Then, in `src/index.js`, we’ll initialize a new Hono app, and define a few endpoints - `GET /API/posts/:slug/comments`, and `POST /get/api/:slug/comments`. Using Hono, it's easy to create a few reque
```suggestion
Next, in `src/index.js`, initialize a new Hono app, and define the following endpoints: `GET /API/posts/:slug/comments`, and `POST /get/api/:slug/comments`. Using Hono, it's easy to create a few request handlers, including the ability to pattern match on a `slug` key:
```

Can we change this sentence into an instruction? "Using Hono, it's easy to create a few request handlers, including the ability to pattern match on a `slug` key:" It sounds like marketing right now.

2022-11-30 17:40 UTC, deadlypants1973 commented on content/d1/tutorials/build-a-comments-api/index.md
> +With a created database, you can reference the database in your code using a binding inside of `wrangler.toml`, Wrangler's configuration file. Bindings allow us to access Cloudflare resources, like D
```suggestion
Reference your created database in your Worker code by creating a [binding](/workers/platform/bindings/) inside of your `wrangler.toml` file, Wrangler's configuration file. Bindings allow us to access Cloudflare resources, like D1 databases, KV namespaces, and R2 buckets, using a simple variable name in code. In `wrangler.toml`, set up the binding `DB` and connect it to the `database_name` and `database_id`:
```

2022-11-30 17:40 UTC, deadlypants1973 commented on content/d1/tutorials/build-a-comments-api/index.md
> +binding = "DB" # i.e. available in your Worker on env.DB
```suggestion
binding = "DB" # available in your Worker on `env.DB`
```

2022-11-30 17:40 UTC, deadlypants1973 commented on content/d1/tutorials/build-a-comments-api/index.md
> +With the database configured in `wrangler.toml`, you can interact with it from the command line, and inside your Workers function.
```suggestion
With your binding configured in your `wrangler.toml`file, you can interact with your database from the command line, and inside your Workers function.
```

2022-11-30 17:40 UTC, deadlypants1973 commented on content/d1/tutorials/build-a-comments-api/index.md
> +First, you can issue direct SQL commands using `wrangler d1 execute`:
```suggestion
Interact with D1 by issuing direct SQL commands using `wrangler d1 execute`:
```

2022-11-30 17:40 UTC, deadlypants1973 commented on content/d1/tutorials/build-a-comments-api/index.md
> +## Executing SQL
```suggestion
## Execute SQL
```

2022-11-30 17:40 UTC, deadlypants1973 commented on content/d1/tutorials/build-a-comments-api/index.md
> +## Executing SQL
This may be awkward like this but as long as the header doesn't start with a gerund (-ing), it would be good.

2022-11-30 17:40 UTC, deadlypants1973 commented on content/d1/tutorials/build-a-comments-api/index.md
> +So far, you've created a SQL database with just a few commands and seeded it with initial data. Now you can add a route to your Workers function to retrieve data from that database. Based on your wra
```suggestion
In earlier steps, you created an SQL database and populated it with initial data. Now, you will add a route to your Workers function to retrieve data from that database. Based on your `wrangler.toml` configuration in previous steps, your D1 database is now accessible via the `DB` binding. In your code, use the binding to prepare SQL statements and execute them, for example, to retrieve comments:
```

2022-11-30 17:40 UTC, deadlypants1973 commented on content/d1/tutorials/build-a-comments-api/index.md
> +The above code makes use of the `prepare`, `bind`, and `all` functions on a D1 binding to prepare and execute a SQL statement. The full documentation for all methods available in D1's client API can
```suggestion
The above code makes use of the `prepare`, `bind`, and `all` functions on a D1 binding to prepare and execute a SQL statement. Refer to [Client API](/d1/platform/client-api) for a list of all methods available in D1's client API.
```

2022-11-30 17:40 UTC, deadlypants1973 commented on content/d1/tutorials/build-a-comments-api/index.md
> +In this function, you accept a `slug` URL query parameter and set up a new SQL statement where you select all comments with a matching `post_slug` value to your query parameter. you can then return i
```suggestion
In this function, you accept a `slug` URL query parameter and set up a new SQL statement where you select all comments with a matching `post_slug` value to your query parameter. You can then return it as a simple JSON response.
```

2022-11-30 17:40 UTC, deadlypants1973 commented on content/d1/tutorials/build-a-comments-api/index.md
> +So far, you've built read-only access to your data. Next, you can define another endpoint function that allows creating new comments, by inserting data into the database:
```suggestion
By completing the previous step, you have built read-only access to your data. Next, you will define another endpoint function that allows creating new comments, by inserting data into the database:
```

2022-11-30 17:40 UTC, deadlypants1973 commented on content/d1/tutorials/build-a-comments-api/index.md
> +So far, you've built read-only access to your data. Next, you can define another endpoint function that allows creating new comments, by inserting data into the database:
Where are they putting this code block? And how?

2022-11-30 17:40 UTC, deadlypants1973 commented on content/d1/tutorials/build-a-comments-api/index.md
> +With your application ready for deployment, you can use Wrangler to quickly build and publish your project to your Cloudflare account.
```suggestion
With your application ready for deployment, use Wrangler to build and publish your project to the Cloudflare network.
```

2022-11-30 17:40 UTC, deadlypants1973 commented on content/d1/tutorials/build-a-comments-api/index.md
> +Once you've logged in, confirm that your `wrangler.toml` file is configured similarly to what is seen below. You can change the `name` field to a project name of your choice:
```suggestion
After you have logged in, confirm that your `wrangler.toml` file is configured similarly to what is seen below. You can change the `name` field to a project name of your choice:
```

2022-11-30 17:40 UTC, deadlypants1973 commented on content/d1/tutorials/build-a-comments-api/index.md
> +binding = "DB" # i.e. available in your Worker on env.DB
```suggestion
binding = "DB" # available in your Worker on env.DB
```

2022-11-30 17:40 UTC, deadlypants1973 commented on content/d1/tutorials/build-a-comments-api/index.md
> +Now, run `wrangler publish` to publish your project to Cloudflare Workers. When it has successfully published, you can test the API by making a `GET` request to retrieve comments for an associated po
```suggestion
Now, run `wrangler publish` to publish your project to Cloudflare. When it has successfully published, test the API by making a `GET` request to retrieve comments for an associated post. Since you have no posts yet, this response will be empty, but it will still make a request to the D1 database regardless, which you can use to confirm that the application has deployed correctly:
```

2022-11-30 17:40 UTC, deadlypants1973 commented on content/d1/tutorials/build-a-comments-api/index.md
> +## Testing with an optional frontend
```suggestion
## Test with an optional frontend
```

2022-11-30 17:40 UTC, deadlypants1973 commented on content/d1/tutorials/build-a-comments-api/index.md
> +This application is just an API backend, best served for use with a frontend UI for actually creating and viewing comments. If you'd like to test this backend with a prebuild frontend UI, visit the e
```suggestion
This application is just an API back end, best served for use with a front-end UI for creating and viewing comments. To test this back-end with a prebuild front-end UI, refer to the example UI at [codewithkristian/d1-frontend-app](https://github.com/codewithkristian/d1-frontend-app). Notably, the [`loadComments` and `submitComment` functions](https://github.com/codewithkristian/d1-frontend-app/blob/master/src/views/PostView.vue#L57-L82) make requests to a deployed version of this site, meaning you can take the frontend and replace the URL with your deployed version of the codebase in this tutorial to use your own data.
```

2022-11-30 17:40 UTC, deadlypants1973 commented on content/d1/tutorials/build-a-comments-api/index.md
> +Note that interacting with this API from a frontend will require enabling specific Cross-Origin Resource Sharing (or *CORS*) headers in your backend API. Luckily, Hono has a quick way to enable this
```suggestion
Note that interacting with this API from a front end will require enabling specific Cross-Origin Resource Sharing (or *CORS*) headers in your back-end API. Luckily, Hono has a quick way to enable this for your application. Import the `cors` module and add it as middleware to your API in `src/index.js`:
```

2022-11-30 17:40 UTC, deadlypants1973 commented on content/d1/tutorials/build-a-comments-api/index.md
> +Now, when you make requests to `/api/*`, Hono will automatically generate and add CORS headers to responses from your API, allowing frontend UIs to interact with it without erroring.
```suggestion
Now, when you make requests to `/api/*`, Hono will automatically generate and add CORS headers to responses from your API, allowing front-end UIs to interact with it without erroring.
```

2022-12-01 17:22 UTC, merged