[R2] document the R2 multipart worker API
cloudflare/cloudflare-docs pull request #6878
Opened 2022-11-29 21:42 UTC by Frederik-Baetens

2022-12-05 12:49 UTC, deadlypants1973 requested changes

2022-12-05 12:49 UTC, deadlypants1973 commented on content/r2/data-access/workers-api/workers-api-reference.md
> +  - Returns Promise which resolves to a {{<code>}}R2MultipartUpload{{</code>}} object representing the newly created multipart upload. Once the multipart upload has been created, the multipart upload
```suggestion
  - Returns Promise which resolves to an `R2MultipartUpload` object representing the newly created multipart upload. Once the multipart upload has been created, the multipart upload can be immediately interacted with globally, either through the Workers API, or through the S3 API.
```

2022-12-05 12:49 UTC, deadlypants1973 commented on content/r2/data-access/workers-api/workers-api-reference.md
> +  - The resumeMultipartUpload does not perform any checks to ensure the validity of the uploadId, nor does it verify the existence of a corresponding active multipart upload. This is done to minimize
```suggestion
  - The `resumeMultipartUpload` does not perform any checks to ensure the validity of the `uploadId`, nor does it verify the existence of a corresponding active multipart upload. This is done to minimize latency before being able to call subsequent operations on the multipart object.
```
is `resumeMultipartUpload` an object? can we write what it is or remove the 'the'?

2022-12-05 12:49 UTC, deadlypants1973 commented on content/r2/data-access/workers-api/workers-api-reference.md
> +  - Returns an object representing a multipart upload with the given key and uploadId.
```suggestion
  - Returns an object representing a multipart upload with the given key and `uploadId`.
```

putting `uploadId` in monospaces because it seems like it's an object

2022-12-05 12:49 UTC, deadlypants1973 commented on content/r2/data-access/workers-api/workers-api-reference.md
> +`R2MultipartUpload` is a representation of an ongoing multipart upload.
```suggestion
An `R2MultipartUpload` object is created when you call `createMultipartUpload` or `resumeMultipartUpload`. `R2MultipartUpload` is a representation of an ongoing multipart upload.
```

Changing to 'an' because the grammatical rule will depend on pronunciation and R2 sounds like it starts with a vowel.

2022-12-05 12:49 UTC, deadlypants1973 commented on content/r2/data-access/workers-api/workers-api-reference.md
> +A `R2MultipartUpload` object does not guarantee that there is an active underlying multipart upload corresponding to that object.
```suggestion
An `R2MultipartUpload` object does not guarantee that there is an active underlying multipart upload corresponding to that object.
```

2022-12-05 12:49 UTC, deadlypants1973 commented on content/r2/data-access/workers-api/workers-api-reference.md
> +A multipart upload can be completed or aborted at any time, either through the S3 API, or by a parralel invocation of your worker. Therefore it is important to add the necessary error handling code a
```suggestion
A multipart upload can be completed or aborted at any time, either through the S3 API, or by a parallel invocation of your Worker. Therefore it is important to add the necessary error handling code around each operation on a `R2MultipartUpload` object in case the underlying multipart upload no longer exists.
```

2022-12-05 12:49 UTC, deadlypants1973 commented on content/r2/data-access/workers-api/workers-api-reference.md
> +  - The uploadId for the multipart upload.
```suggestion
  - The `uploadId` for the multipart upload.
```

2022-12-05 12:49 UTC, deadlypants1973 commented on content/r2/data-access/workers-api/workers-api-reference.md
> +  - Returns an `R2UploadedPart` object containing the etag and partNumber. These `R2UploadedPart` objects are required when completing the multipart upload.
```suggestion
  - Returns an `R2UploadedPart` object containing the `etag` and `partNumber`. These `R2UploadedPart` objects are required when completing the multipart upload.
```

2022-12-05 12:49 UTC, deadlypants1973 commented on content/r2/data-access/workers-api/workers-api-reference.md
> +  - Aborts the multipart upload. Returns a promise that resolves when the upload has been successfully aborted.
```suggestion
  - Aborts the multipart upload. Returns a Promise that resolves when the upload has been successfully aborted.
```

2022-12-05 12:49 UTC, deadlypants1973 commented on content/r2/data-access/workers-api/workers-api-reference.md
> +  - Returns a promise that resolves when the complete operation has finished. Once this happens, the object is immediately accessible globally by any subsequent read operation.
```suggestion
  - Returns a Promise that resolves when the complete operation has finished. Once this happens, the object is immediately accessible globally by any subsequent read operation.
```

2022-12-05 12:49 UTC, deadlypants1973 commented on content/r2/data-access/workers-api/workers-api-reference.md
> +### R2UploadedPart
```suggestion
### `R2UploadedPart`
```

2022-12-05 12:49 UTC, deadlypants1973 commented on content/r2/data-access/workers-api/workers-api-reference.md
> +`R2UploadedPart` objects are returned from uploadPart operations and must be passed to completeMultipartUpload operations.
```suggestion
An `R2UploadedPart` object represents a part that has been uploaded. `R2UploadedPart` objects are returned from `uploadPart` operations and must be passed to `completeMultipartUpload` operations.
```

2022-12-05 12:49 UTC, deadlypants1973 commented on content/r2/data-access/workers-api/workers-multipart-usage.md
> +This could serve as a basis for your use case where you could add extra validation and authentication.
```suggestion
# Use the R2 multipart API from Workers

By following this guide, you will create a Worker through which your applications can perform multipart uploads and add extra validation and authentication for your application.

This guide assumes you have set up the [R2 binding](/workers/platform/bindings/) for your Worker. Refer to [Use R2 from Workers](/r2/data-access/workers-api/workers-api-usage) for instructions on setting up an R2 binding.
```

2022-12-05 12:49 UTC, deadlypants1973 commented on content/r2/data-access/workers-api/workers-multipart-usage.md
> +## An example worker using the multipart API
```suggestion
## An example Worker using the multipart API
```

2022-12-05 12:49 UTC, deadlypants1973 commented on content/r2/data-access/workers-api/workers-multipart-usage.md
> +This could serve as a basis for your use case where you could add extra validation and authentication.
Where are we adding "extra validation and authentication"? To the application? This sentence needs a bit more technical detail

2022-12-05 12:49 UTC, deadlypants1973 commented on content/r2/data-access/workers-api/workers-multipart-usage.md
> +In turn, the client keeps track of this state, and includes the uploadId in subsequent requests, and the etag and part number of each part when completing a multipart upload.
```suggestion
The following example Worker exposes an HTTP API which enables applications to use the multipart API through the Worker.

In this example, each request is routed based on the HTTP method and the action request parameter. As your Worker becomes more complicated, consider utilizing a serverless web framework such as [Hono](https://honojs.dev/) to handle the routing for you.

The following example Worker includes any new information about the state of the multipart upload in the response to each request. For the request which creates the multipart upload, the `uploadId` is returned. For requests uploading a part, the part number and etag are returned. In turn, the client keeps track of this state, and includes the `uploadId` in subsequent requests, and the etag and part number of each part when completing a multipart upload.
```

2022-12-05 12:49 UTC, deadlypants1973 commented on content/r2/data-access/workers-api/workers-multipart-usage.md
> +## Using the worker to perform a multipart upload
```suggestion
## Perform a multipart upload using a Worker
```

2022-12-05 12:49 UTC, deadlypants1973 commented on content/r2/data-access/workers-api/workers-multipart-usage.md
> +# Use the R2 multipart API from workers
```suggestion
# Use the R2 multipart API from Workers
```

2022-12-05 12:49 UTC, deadlypants1973 commented on content/r2/data-access/workers-api/workers-multipart-usage.md
> +That will upload the file `myfile` from your machine to your bucket through the worker.
```suggestion
This example application uploads a file to the Worker in multiple parts. It uses Python's built-in `ThreadPoolExecutor` to parallelize the uploading of parts to the Worker, which increases upload speeds. HTTP requests to the Worker are made with the [requests](https://pypi.org/project/requests/) library.

Utilizing the multipart API in this way also allows you to use the Worker to upload files larger than the [Workers request body size limit](/workers/platform/limits#request-limits). The uploading of individual parts is still subject to this limit.

Pass the file you want to upload as an argument when running this script: `python3 mpuscript.py myfile`. That will upload the file `myfile` from your machine to your bucket through the Worker.
```

2022-12-05 12:49 UTC, deadlypants1973 commented on content/r2/data-access/workers-api/workers-multipart-usage.md
> +## A note on state management
```suggestion
## State management
```

2022-12-05 12:49 UTC, deadlypants1973 commented on content/r2/data-access/workers-api/workers-multipart-usage.md
> +When keeping track of this state in the client is impossible, alternative designs can be considered. For example, you could track the uploadId and which parts have been uploaded in a durable object,
```suggestion
The stateful nature of multipart uploads does not easily map to the usage model of Workers, which are inherently stateless. In a normal multipart upload, the multipart upload is usually performed in one continuous execution of the client application. This is different from multipart uploads in a Worker, which will often be completed over multiple invocations of that Worker. This makes state management more challenging. 

To overcome this, the state associated with a multipart upload, namely the `uploadId` and which parts have been uploaded, needs to be kept track of somewhere outside of the Worker.

In this example, the state of the multipart upload is tracked in the client application which sends requests to the Worker, with the necessary state contained in each request. Keeping track of the multipart state in the client application enables maximal flexibility and allows for parallel and unordered uploads of each part.

When keeping track of this state in the client is impossible, alternative designs can be considered. For example, you could track the `uploadId` and which parts have been uploaded in a Durable Object or other database.
```

2022-12-05 12:49 UTC, deadlypants1973 commented on content/r2/data-access/workers-api/workers-multipart-usage.md
> +When keeping track of this state in the client is impossible, alternative designs can be considered. For example, you could track the uploadId and which parts have been uploaded in a durable object,
"In this example, the state of the multipart ..." 

Which example?

2022-12-05 13:03 UTC, Frederik-Baetens commented on content/r2/data-access/workers-api/workers-api-reference.md
> +  - Returns an object representing a multipart upload with the given key and uploadId.
Hmm, It's just a string, so it's as much of an object as the key. I'd either leave it as is, or put both in monospace, what's your preference there?

2022-12-05 13:03 UTC, Frederik-Baetens commented on content/r2/data-access/workers-api/workers-api-reference.md
> +  - The resumeMultipartUpload does not perform any checks to ensure the validity of the uploadId, nor does it verify the existence of a corresponding active multipart upload. This is done to minimize
resumemultipartUpload is an operation, I'll clarify that.

2022-12-05 13:07 UTC, Frederik-Baetens commented on content/r2/data-access/workers-api/workers-api-reference.md
> +  - Returns an `R2UploadedPart` object containing the etag and partNumber. These `R2UploadedPart` objects are required when completing the multipart upload.
Same here, why put the partNumber in monospace, but not the etag?

2022-12-05 13:17 UTC, Frederik-Baetens commented on content/r2/data-access/workers-api/workers-multipart-usage.md
> +## Using the worker to perform a multipart upload
Changed this to `Perform a multipart upload using the Worker` to indicate that this only works with the very specific worker described in the earlier example.

2022-12-05 13:18 UTC, Frederik-Baetens commented on content/r2/data-access/workers-api/workers-multipart-usage.md
> +That will upload the file `myfile` from your machine to your bucket through the worker.
:+1: applied this

2022-12-05 13:21 UTC, Frederik-Baetens commented on content/r2/data-access/workers-api/workers-multipart-usage.md
> +When keeping track of this state in the client is impossible, alternative designs can be considered. For example, you could track the uploadId and which parts have been uploaded in a durable object,
Clarified that I meant the example worker & application in the guide.

2022-12-05 13:25 UTC, Frederik-Baetens commented on content/r2/data-access/workers-api/workers-multipart-usage.md
> +This could serve as a basis for your use case where you could add extra validation and authentication.
Well, I don't really intend to go into how to add extra validation and authentication in this guide. I'll add that the validation ought to be added in the worker.

2022-12-05 13:33 UTC, Frederik-Baetens commented on content/r2/data-access/workers-api/workers-multipart-usage.md
> +This could serve as a basis for your use case where you could add extra validation and authentication.
I've applied part of these suggestions, but kept the "as a base" wording, since this is a template on which users can build, rather than a guide where I intend to cover authentication or other stuff in this guide.

2022-12-05 14:43 UTC, Frederik-Baetens commented on content/r2/data-access/workers-api/workers-multipart-usage.md
> +In turn, the client keeps track of this state, and includes the uploadId in subsequent requests, and the etag and part number of each part when completing a multipart upload.
Applied this

2022-12-12 14:53 UTC, deadlypants1973 commented on content/r2/data-access/workers-api/workers-multipart-usage.md
> +For example, you could track the uploadId and which parts have been uploaded in a Durable Object or other database.
```suggestion
The stateful nature of multipart uploads does not easily map to the usage model of Workers, which are inherently stateless. In a normal multipart upload, the multipart upload is usually performed in one continuous execution of the client application. This is different from multipart uploads in a Worker, which will often be completed over multiple invocations of that Worker. This makes state management more challenging. 

To overcome this, the state associated with a multipart upload, namely the `uploadId` and which parts have been uploaded, needs to be kept track of somewhere outside of the Worker.

In the example Worker and Python application described in this guide, the state of the multipart upload is tracked in the client application which sends requests to the Worker, with the necessary state contained in each request. Keeping track of the multipart state in the client application enables maximal flexibility and allows for parallel and unordered uploads of each part.

When keeping track of this state in the client is impossible, alternative designs can be considered. For example, you could track the `uploadId` and which parts have been uploaded in a Durable Object or other database.
```

2022-12-12 14:53 UTC, deadlypants1973 commented on content/r2/data-access/workers-api/workers-multipart-usage.md
> +That will upload the file `myfile` from your machine to your bucket through the Worker.
```suggestion
This example application uploads a file to the Worker in multiple parts. It uses Python's built-in `ThreadPoolExecutor` to parallelize the uploading of parts to the Worker, which increases upload speeds. HTTP requests to the Worker are made with the [requests](https://pypi.org/project/requests/) library.

Utilizing the multipart API in this way also allows you to use the Worker to upload files larger than the [Workers request body size limit](/workers/platform/limits#request-limits). The uploading of individual parts is still subject to this limit.

Pass the file you want to upload as an argument when running this script: `python3 mpuscript.py myfile`. That will upload the file `myfile` from your machine to your bucket through the Worker.
```

2022-12-12 14:53 UTC, deadlypants1973 commented on content/r2/data-access/workers-api/workers-multipart-usage.md
> +The following example Worker includes any new information about the state of the multipart upload in the response to each request. For the request which creates the multipart upload, the `uploadId` i
```suggestion
The following example Worker exposes an HTTP API which enables applications to use the multipart API through the Worker.

In this example, each request is routed based on the HTTP method and the action request parameter. As your Worker becomes more complicated, consider utilizing a serverless web framework such as [Hono](https://honojs.dev/) to handle the routing for you.

The following example Worker includes any new information about the state of the multipart upload in the response to each request. For the request which creates the multipart upload, the `uploadId` is returned. For requests uploading a part, the part number and `etag` are returned. In turn, the client keeps track of this state, and includes the uploadId in subsequent requests, and the `etag` and part number of each part when completing a multipart upload.
```

2022-12-12 14:53 UTC, deadlypants1973 commented on content/r2/data-access/workers-api/workers-multipart-usage.md
> +This guide assumes you have set up the [R2 binding](/workers/platform/bindings/) for your Worker. Refer to [Use R2 from Workers](/r2/data-access/workers-api/workers-api-usage) for instructions on set
```suggestion
By following this guide, you will create a Worker through which your applications can perform multipart uploads. This guide also contains an example Python application that uploads files to this Worker.

This guide assumes you have [created a Worker](/workers/get-started/guide/) and set up the [R2 binding](/workers/platform/bindings/) for your Worker. Refer to [Use R2 from Workers](/r2/data-access/workers-api/workers-api-usage) for instructions on setting up an R2 binding.
```

2022-12-12 14:53 UTC, deadlypants1973 commented on content/r2/data-access/workers-api/workers-api-reference.md
> +  - The key for the multipart upload.
```suggestion
  - The `key` for the multipart upload.
```

2022-12-12 14:53 UTC, deadlypants1973 commented on content/r2/data-access/workers-api/workers-api-reference.md
> +  - The etag of the part.
```suggestion
  - The `etag` of the part.
```

2022-12-12 14:53 UTC, deadlypants1973 commented on content/r2/data-access/workers-api/workers-multipart-usage.md
> +As your Worker becomes more complicated, consider utilizing a serverless web framework such as [Hono](https://honojs.dev/) to handle the routing for you.
```suggestion
In this example, each request is routed based on the HTTP method and the action request parameter. As your Worker becomes more complicated, consider utilizing a serverless web framework such as [Hono](https://honojs.dev/) to handle the routing for you.
```

2022-12-12 14:53 UTC, deadlypants1973 commented on content/r2/data-access/workers-api/workers-multipart-usage.md
> +The next section shows an example of a Python script which uploads a chosen file on your machine to this worker.
```suggestion
After you have updated your Worker with the above code, run `wrangler publish` . 

You can now use this Worker to perform multipart uploads. You can either send requests from your existing application to this Worker to perform uploads or use a script to upload files through this Worker.

The next section is optional and shows an example of a Python script which uploads a chosen file on your machine to your Worker.
```

2022-12-12 14:53 UTC, deadlypants1973 commented on content/r2/data-access/workers-api/workers-multipart-usage.md
> +## Perform a multipart upload using the Worker
```suggestion
## Perform a multipart upload with your Worker (optional)
```

2022-12-12 14:53 UTC, deadlypants1973 commented on content/r2/data-access/workers-api/workers-multipart-usage.md
> +HTTP requests to the Worker are made with the [requests](https://pypi.org/project/requests/) library.
```suggestion
This example application uploads a local file to the Worker in multiple parts. It uses Python's built-in `ThreadPoolExecutor` to parallelize the uploading of parts to the Worker, which increases upload speeds. HTTP requests to the Worker are made with the [requests](https://pypi.org/project/requests/) library.
```

2022-12-12 14:53 UTC, deadlypants1973 commented on content/r2/data-access/workers-api/workers-multipart-usage.md
> +The uploading of individual parts is still subject to this limit.
```suggestion
Utilizing the multipart API in this way also allows you to use your Worker to upload files larger than the [Workers request body size limit](/workers/platform/limits#request-limits). The uploading of individual parts is still subject to this limit.
```

2022-12-12 14:53 UTC, deadlypants1973 commented on content/r2/data-access/workers-api/workers-multipart-usage.md
> +```python
```suggestion
```python
---
filename: myfile
---
```

2022-12-12 14:53 UTC, deadlypants1973 commented on content/r2/data-access/workers-api/workers-multipart-usage.md
> +That will upload the file `myfile` from your machine to your bucket through the Worker.
```suggestion
Save the following code on a file named `myfile` on your local machine. Pass the file as an argument when running this script: `python3 mpuscript.py myfile`. This will upload the file `myfile` from your machine to your bucket through the Worker.
```

2022-12-12 14:53 UTC, deadlypants1973 commented on content/r2/data-access/workers-api/workers-multipart-usage.md
> +
```suggestion

Add the following code to your project's `index.js` file and replace `MY_BUCKET` with your bucket's name:

```

2022-12-12 14:57 UTC, deadlypants1973 approved these changes

2022-12-12 20:32 UTC, merged