Add CF Pages Function Fauna Tutorial
cloudflare/cloudflare-docs pull request #6890
Opened 2022-11-30 17:36 UTC by Shadid12

2022-11-30 17:43 UTC, Teerasak71 commented
***@***.***
***@***.***
***@***.***

ในวันที่ พฤ. 1 ธ.ค. 2022 00:38 cloudflare-pages[bot] <
***@***.***> เขียนว่า:

> Deploying with  [image: Cloudflare Pages] <https://pages.dev>  Cloudflare
> Pages
> *Latest commit:* 65edd0d
> *Status:*  ✅  Deploy successful!
> *Preview URL:* https://a9238dab.cloudflare-docs-7ou.pages.dev
> *Branch Preview URL:*
> https://feat-pages-functions-nextjs-.cloudflare-docs-7ou.pages.dev
>
> View logs
> <https://dash.cloudflare.com/?to=/:account/pages/view/cloudflare-docs/a9238dab-38cd-45a0-b303-ea93d0d7ee84>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/cloudflare/cloudflare-docs/pull/6890#issuecomment-1332517195>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZW7QV4RJT7ZBK5QBQ7I4ETWK6GLFANCNFSM6AAAAAASP4LJS4>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2022-12-06 13:20 UTC, lauragift21 approved these changes

2022-12-07 01:09 UTC, WalshyDev requested changes

2022-12-07 01:09 UTC, WalshyDev commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function/index.md
> +In this tutorial, you will build a globally distributed full stack application using Cloudflare Pages (for the front end), Pages Functions (the backend), and Fauna as the database. You will use the N
```suggestion
In this tutorial, you will build a globally distributed full-stack application using Cloudflare Pages (for the front end), Pages Functions (the backend), and Fauna as the database. You will use the Next.js framework to tie all these services together in a cohesive and scalable codebase.
```

2022-12-07 01:09 UTC, WalshyDev commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function/index.md
> +- A [Cloudflare](https://www.cloudflare.com/) account
```suggestion
- A [Cloudflare](https://www.cloudflare.com/) account
- A [Fauna](https://fauna.com/) account
```

2022-12-07 01:09 UTC, WalshyDev commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function/index.md
> +Cloudflare [Pages](https://developers.cloudflare.com/pages/) and Pages Functions run your code closest to the end user’s geographical location without you maintaining a server. While Fauna being a gl
```suggestion
Cloudflare [Pages](https://developers.cloudflare.com/pages/) and Pages Functions will run closest to the end user without you maintaining a server. Fauna is a globally distributed database system, that ensures data reads and writes always happen on the closest replicas of your database. This combination of Pages Functions and Fauna allows you to build highly performant apps with very low latency.
```

2022-12-07 01:09 UTC, WalshyDev commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function/index.md
> +> 💡 Info: When you create API routes in your Next.js application (i.e. under `/pages/api` folder) and deploy them to Cloudflare each of these functions become individual Cloudflare Workers function o
```suggestion
{{<Aside>}}
When you create API routes in your Next.js application (i.e. under `/pages/api` folder) these will be turned into a Pages Function which will run globally on Cloudflare's network.
{{</Aside>}}
```

2022-12-07 01:09 UTC, WalshyDev commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function/index.md
> +Next, enable edge-runtime for your API routes. Open the `pages/api/hello.js` file. This is an API route. When deployed this API route will become an edge function, however for this to work you have t
```suggestion
Next, enable edge-runtime for your API routes. Open the `pages/api/hello.js` file. This is an API route. When deployed this API route will become a Pages Function, however for this to work you have the add the following code. 
```

2022-12-07 01:09 UTC, WalshyDev commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function/index.md
> +// pages/api/hello.js
```suggestion
```js
---
filename: pages/api/hello.js
---
```

2022-12-07 01:09 UTC, WalshyDev commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function/index.md
> +To learn more about how Edge Runtime works refer to Next.js' [Edge API Routes documentation](https://nextjs.org/docs/api-routes/edge-api-routes).
```suggestion
To learn more about how the Next.js Edge Runtime works refer to [Edge API Routes documentation](https://nextjs.org/docs/api-routes/edge-api-routes). 
```

2022-12-07 01:09 UTC, WalshyDev commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function/index.md
> +![Build output](/pages/tutorials/build-a-fullstack-app-with-pages-function/build-output.png)
Can we get a non-transparent image here?

2022-12-07 01:09 UTC, WalshyDev commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function/index.md
> +Notice that a folder named `.vercel/output` is generated. Inside you can find the generated Clourflare Workers and Pages functions.
```suggestion
Notice that a folder named `.vercel/output` is generated. Inside you can find the generated Cloudflare Pages Function.
```

2022-12-07 01:09 UTC, WalshyDev commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function/index.md
> +
```suggestion
```

2022-12-07 01:09 UTC, WalshyDev commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function/index.md
> +```
```suggestion
```sh
```

2022-12-07 01:09 UTC, WalshyDev commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function/index.md
> +
```suggestion
$ git branch -M main
$ git add .
$ git commit -m "Initial commit"
$ git push -u origin main
```
```

2022-12-07 01:09 UTC, WalshyDev commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function/index.md
> +If you haven’t already signed up for a free Cloudflare Pages account, [create an account now](https://dash.cloudflare.com/pages).
```suggestion
If you haven't already signed up for a free Cloudflare Pages account, [create an account now](https://dash.cloudflare.com/sign-up/pages).
```

2022-12-07 01:09 UTC, WalshyDev commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function/index.md
> +1. In the build settings select `Next.js` you can leave everything else as default.
```suggestion
1. In the build settings select `Next.js`, you can leave everything else as default.
```

2022-12-07 01:09 UTC, WalshyDev commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function/index.md
> +
```suggestion
```

2022-12-07 01:09 UTC, WalshyDev commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function/index.md
> +![Configure deployment](/pages/tutorials/build-a-fullstack-app-with-pages-function/configure-build.png)
```suggestion
![Configure build settings](/pages/tutorials/build-a-fullstack-app-with-pages-function/configure-build.png)
```

2022-12-07 01:09 UTC, WalshyDev commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function/index.md
> +4. In the environment variable section add a new variable called `NODE_VERSION` and add the node version of your project. **You require a node version 14 or greater.**
```suggestion
4. In the environment variable section add a new variable called `NODE_VERSION` and add the node version of your project. **You must have a Node.js version of 14 or greater.**
```

2022-12-07 01:09 UTC, WalshyDev commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function/index.md
> +![Define Node Version in cloud flare configuration](/pages/tutorials/build-a-fullstack-app-with-pages-function/node_version.png)
```suggestion
![Define Node.js version](/pages/tutorials/build-a-fullstack-app-with-pages-function/node_version.png)
```

2022-12-07 01:09 UTC, WalshyDev commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function/index.md
> +5. Next, go to **Settings > Functions** and under compatibility flags add the following flags.
```suggestion
5. Next, go to **Settings > Functions** and under compatibility flags add the following flags:
```

2022-12-07 01:09 UTC, WalshyDev commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function/index.md
> +`streams_enable_constructors`, `transformstream_enable_standard_constructor`.
```suggestion
- `streams_enable_constructors`
- `transformstream_enable_standard_constructor`
```

2022-12-07 01:09 UTC, WalshyDev commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function/index.md
> +*These flags are scheduled to graduate on the 2022-11-30 compatibility date and should no longer be necessary to manually add after November 30, 2022.*
```suggestion
*These flags are scheduled to become stable when using a compatibility date of 2022-11-30 or greater, this means you will no longer need to specify them*
```

2022-12-07 01:09 UTC, WalshyDev commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function/index.md
> +Next, visit [`https://<your-domain-name>/api/hello`](https://with-cloudflare-nextjs.pages.dev/api/hello) to make sure that the Pages function is working as expected.
We will not embed third-party projects into the docs.

```suggestion
Next, visit `https://<your-domain-name>/api/hello` to make sure that the Pages Function is working as expected. 
```

2022-12-07 01:09 UTC, WalshyDev commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function/index.md
> +Info:  *By default, Fauna allows you to save your data globally closer to your user. However, you can also limit your data's distribution to a specific geographic region group to comply with GDPR and
```suggestion
{{<Aside>}}
*By default, Fauna allows you to save your data globally closer to your user. However, you can also limit your data's distribution to a specific geographic region group to comply with GDPR and data residency. Learn more about region groups [here](https://docs.fauna.com/fauna/current/learn/understanding/region_groups).
{{</Aside>}}
```

2022-12-07 01:09 UTC, WalshyDev commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function/index.md
> +*You also have the option to save data into privately distributed nodes with [Virtual Private Fauna.](https://www.globenewswire.com/news-release/2022/11/17/2558259/0/en/Fauna-Launches-Virtual-Private
This doesn't really feel relevant and I'm not a fan of linking to a press-release here.
```suggestion
```

2022-12-07 01:09 UTC, WalshyDev commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function/index.md
> +![Fauna Secret](/pages/tutorials/build-a-fullstack-app-with-pages-function/fauna_secret.png)
This is where secrets should be used, let's update the image for that too, please.
I hate my wording here - cc: @deadlypants1973
I'm not sure we've discussed about how we describe secrets yet.

```suggestion
8. Finally, head back to Cloudflare Pages settings and add a new environment variable called FAUNA_SECRET. Then select **Encrypt**, this will make sure your secret is encrypted and is not viewable by anyone else in the future.

![Fauna Secret](/pages/tutorials/build-a-fullstack-app-with-pages-function/fauna_secret.png)
```

2022-12-07 01:09 UTC, WalshyDev commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function/index.md
> +Create a new front-end page to add data to your database. Create a new file `pages/add-products.js` in your project and add the following code to it.
```suggestion
Create a new front-end page that will add data to your database. Create a new file `pages/add-products.js` in your project and add the following code to it.
```

2022-12-07 01:09 UTC, WalshyDev commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function/index.md
> +    setState({ ...state, [name]: value });
I try to avoid object destructuring as much as possible in tutorials. 
```suggestion
    setState({ ...state, [e.target.name]: e.target.value });
```

2022-12-07 01:09 UTC, WalshyDev commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function/index.md
> +    await fetch('/api/products', {
```suggestion

    // Make an API call to create a product    
    await fetch('/api/products', {
```

2022-12-07 01:09 UTC, WalshyDev commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function/index.md
> +        <label htmlFor="description" >Description</label>
```suggestion
        <label htmlFor="description">Description</label>
```

2022-12-07 01:09 UTC, WalshyDev commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function/index.md
> +
```suggestion
```

2022-12-07 01:09 UTC, WalshyDev commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function/index.md
> +In the previous code block you have a simple form component to add products. On form submit it calls the `/api/products` api routes.
```suggestion
In the previous code block you have a simple form component to add products. On form submit it calls the `/api/products` api route.
```

2022-12-07 01:09 UTC, WalshyDev commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function/index.md
> +$ npm run dev
We never told the user to setup this script, this will run standard Next dev no? we'd want Functions dev.

2022-12-07 01:09 UTC, WalshyDev commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function/index.md
> +// pages/api/products.js
```suggestion
```jss
---
filename: pages/api/products.js
---
```

2022-12-07 01:09 UTC, WalshyDev commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function/index.md
> +  if(req.method === 'POST') {
```suggestion
  if (req.method === 'POST') {
```

2022-12-07 01:09 UTC, WalshyDev commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function/index.md
> +  if(req.method === 'POST') {
```suggestion
  if (req.method === 'POST') {
```

2022-12-07 01:09 UTC, WalshyDev commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function/index.md
> +```jsx
```suggestion
```js
---
filename: pages/api/products.js
---
```

2022-12-07 01:09 UTC, WalshyDev commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function/index.md
> +    const { title, price, description } = req.body;
Again not a fan of this object destructuring. It's wonderful for people who know JS but those who are new, it's just confusing.

2022-12-07 01:09 UTC, WalshyDev commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function/index.md
> +    const body = await readRequestBodyStream(req.body);
Can we not just request.json() here?

2022-12-07 01:09 UTC, WalshyDev commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function/index.md
> +However, this is not saving the data in our database yet. Next, let’s add the code for database operation.
```suggestion
However, this is not saving the data in our database yet. Next, let's add the code for database operation.
```

2022-12-07 01:09 UTC, WalshyDev commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function/index.md
> +$ npm i faunadb --save
```suggestion
$ npm install faunadb --save
```

2022-12-07 01:09 UTC, WalshyDev commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function/index.md
> +// db.js
```suggestion
```js
---
filename: db.js
---
```

2022-12-07 01:09 UTC, WalshyDev commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function/index.md
> +// partials of pages/api/products.js
```suggestion
```js
---
filename: pages/api/products.js
---
```

2022-12-07 01:09 UTC, WalshyDev commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function/index.md
> +// db.js
```suggestion
```js
---
filename: db.js
---
```

2022-12-07 01:09 UTC, WalshyDev commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function/index.md
> +```jsx
```suggestion
```jsx
---
filename: pages/index.js
---
```

2022-12-07 01:09 UTC, WalshyDev commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function/index.md
> +  const fauna_secret = process.env.FAUNA_SECRET;
```suggestion
  const faunaSecret = process.env.FAUNA_SECRET;
```

2022-12-07 01:09 UTC, WalshyDev commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function/index.md
> +      fauna_secret
```suggestion
      faunaSecret
```

2022-12-07 01:09 UTC, WalshyDev commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function/index.md
> +export default function Home({ products, fauna_secret }) {
```suggestion
export default function Home({ products, faunaSecret }) {
```

2022-12-07 01:09 UTC, WalshyDev commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function/index.md
> +  const fauna_secret = process.env.FAUNA_SECRET;
I'm not seeing where this is actually used, is this required?

2022-12-07 01:09 UTC, WalshyDev commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function/index.md
> +The compute and database operations are almost the same across the globe. The powerful combination of Cloudflare CDN, workers and Fauna database allow your code and data to run closer to your end use
Not sure how I feel about this. We don't do this in any other doc, time will vary depending on many factors and complexity. 
I'll leave it for @deadlypants1973 to decide what to do here.

2022-12-07 01:09 UTC, WalshyDev commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function/index.md
> +If you are looking to build something more practical and hands on we have created a self paced workshop on “How to build a global application with Cloudflare and Fauna”. You can check this out [here]
Was this done in partnership with us?  

```suggestion
## Where to go from here

If you are looking to build something more practical and hands on we have created a self paced workshop on "How to build a global application with Cloudflare and Fauna". You can check this out [here](https://github.com/fauna-labs/fauna-workers). 
```

2022-12-07 01:09 UTC, WalshyDev commented
I will mark this PR as a draft for now.

2022-12-07 01:18 UTC, WalshyDev commented
Oh and can we rename this dir too `build-a-fullstack-app-with-pages-function` to include Fauna and probably Next.js too?

2022-12-07 13:37 UTC, deadlypants1973 requested changes
Tech writer review after @WalshyDev 's comments have been reviewed

2022-12-07 13:37 UTC, deadlypants1973 commented
> Tech writer review after @WalshyDev 's comments have been reviewed

Thank you for putting this up @Shadid12 :)

2022-12-09 18:40 UTC, Shadid12 commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function/index.md
> +In this tutorial, you will build a globally distributed full stack application using Cloudflare Pages (for the front end), Pages Functions (the backend), and Fauna as the database. You will use the N
updated in new commit.

2022-12-09 18:42 UTC, Shadid12 commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function/index.md
> +- A [Cloudflare](https://www.cloudflare.com/) account
updated

2022-12-09 18:43 UTC, Shadid12 commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function/index.md
> +Cloudflare [Pages](https://developers.cloudflare.com/pages/) and Pages Functions run your code closest to the end user’s geographical location without you maintaining a server. While Fauna being a gl
updated

2022-12-09 18:44 UTC, Shadid12 commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function/index.md
> +Next, enable edge-runtime for your API routes. Open the `pages/api/hello.js` file. This is an API route. When deployed this API route will become an edge function, however for this to work you have t
updated

2022-12-09 18:45 UTC, Shadid12 commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function/index.md
> +export default function Home({ products, fauna_secret }) {
fixed

2022-12-09 18:47 UTC, Shadid12 commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function/index.md
> +  const fauna_secret = process.env.FAUNA_SECRET;
yes it is used right here. I updated the variable to snaked case as per guide
https://github.com/cloudflare/cloudflare-docs/blob/65edd0d004f0f499a1eeda1aa1485b0856766e33/content/pages/tutorials/build-a-fullstack-app-with-pages-function/index.md#L415

2022-12-09 18:48 UTC, Shadid12 commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function/index.md
> +If you are looking to build something more practical and hands on we have created a self paced workshop on “How to build a global application with Cloudflare and Fauna”. You can check this out [here]
yes it was a partnership

2022-12-10 00:13 UTC, WalshyDev commented
Looks like there are still a few outstanding comments :)

2022-12-11 21:38 UTC, Shadid12 commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function/index.md
> +> 💡 Info: When you create API routes in your Next.js application (i.e. under `/pages/api` folder) and deploy them to Cloudflare each of these functions become individual Cloudflare Workers function o
updated

2022-12-11 21:38 UTC, Shadid12 commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function/index.md
> +      fauna_secret
updated

2022-12-11 21:39 UTC, Shadid12 commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function/index.md
> +The compute and database operations are almost the same across the globe. The powerful combination of Cloudflare CDN, workers and Fauna database allow your code and data to run closer to your end use
Please advise, I can remove it if you would like?

2022-12-11 21:41 UTC, Shadid12 commented
@WalshyDev Hey updated all the comments. Please advise on the CDN comment. I can remove it.

2022-12-21 17:57 UTC, deadlypants1973 requested changes

2022-12-21 17:57 UTC, deadlypants1973 commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function-with-fauna-nextjs/index.md
> +In this tutorial, you will build a globally distributed full-stack application using Cloudflare Pages (for the front end), Pages Functions (the backend), and Fauna as the database. You will use the N
```suggestion
# Build a globally distributed full-stack application using Cloudflare Pages, Next.js and Fauna

In this tutorial, you will build a globally distributed full-stack application using Cloudflare Pages (the front end), Pages Functions (the back-end logic), and Fauna as the database. You will use the Next.js framework to tie all these services together in a cohesive and scalable codebase.  
```

2022-12-21 17:57 UTC, deadlypants1973 commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function-with-fauna-nextjs/index.md
> +- A [Fauna](https://fauna.com/?utm_source=[graphql/aws/cloudflare]&utm_medium=fauna_workshop&utm_campaign=fauna_workshop) account
```suggestion
You must have the following to continue:

- A recent version of [Node and NPM](https://docs.npmjs.com/getting-started) on your computer.
- A [Cloudflare](https://www.cloudflare.com/) account.
- A [Fauna](https://fauna.com/?utm_source=[graphql/aws/cloudflare]&utm_medium=fauna_workshop&utm_campaign=fauna_workshop) account.
```

2022-12-21 17:57 UTC, deadlypants1973 commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function-with-fauna-nextjs/index.md
> +## What is a globally distributed app?
```suggestion
## An introduction to globally distributed applications
```

2022-12-21 17:57 UTC, deadlypants1973 commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function-with-fauna-nextjs/index.md
> +Cloudflare [Pages](https://developers.cloudflare.com/pages/) and Pages Functions will run closest to the end user without you maintaining a server. Fauna is a globally distributed database system, th
```suggestion
A globally distributed application always runs closest to the end user, making the application response time fast.

Cloudflare [Pages](https://developers.cloudflare.com/pages/) and Pages Functions run closest to the end user without the need for you to maintain a server. Fauna is a globally distributed database system. It ensures data reads and writes always happen on the closest replicas of your database. The combination of Pages Functions and Fauna allows you to build highly performant applications with low latency.
```

2022-12-21 17:57 UTC, deadlypants1973 commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function-with-fauna-nextjs/index.md
> +$ npx create-next-app <your-app-name>
```suggestion
$ npx create-next-app <YOUR_APP_NAME>
```

2022-12-21 17:57 UTC, deadlypants1973 commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function-with-fauna-nextjs/index.md
> +{{</Aside>}}
```suggestion
{{<Aside type="note">}}
When you create API routes in your Next.js application (under the `/pages/api` folder) these will be turned into a Pages Function which will run globally on Cloudflare's network.
{{</Aside>}}
```

2022-12-21 17:57 UTC, deadlypants1973 commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function-with-fauna-nextjs/index.md
> +Next, enable edge-runtime for your API routes. Open the `pages/api/hello.js` file. This is an API route. When deployed this API route will become a Pages Function, however for this to work you have t
```suggestion
Next, enable edge-runtime for your API routes. Open the `pages/api/hello.js` file. This is an API route. When deployed this API route will become a Pages Function. For this to work, add the following code.
```

2022-12-21 17:57 UTC, deadlypants1973 commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function-with-fauna-nextjs/index.md
> +Next, enable edge-runtime for your API routes. Open the `pages/api/hello.js` file. This is an API route. When deployed this API route will become a Pages Function, however for this to work you have t
Where are they adding the code? What location?

2022-12-21 17:57 UTC, deadlypants1973 commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function-with-fauna-nextjs/index.md
> +```jsx
was jsx on purpose here?

2022-12-21 17:57 UTC, deadlypants1973 commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function-with-fauna-nextjs/index.md
> +Notice that a folder named `.vercel/output` is generated. Inside you can find the generated Clourflare Workers and Pages functions.
```suggestion
A folder named `.vercel/output` will be created. Find the generated Clourflare Workers and Pages Functions inside this folder.
```

2022-12-21 17:57 UTC, deadlypants1973 commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function-with-fauna-nextjs/index.md
> +
```suggestion
```

2022-12-21 17:57 UTC, deadlypants1973 commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function-with-fauna-nextjs/index.md
> +Next, create a new GitHub repository by visiting [repo.new](https://repo.new/). When you are done creating a new repository, prepare and push your local application to GitHub by running the following
```suggestion
Create a new GitHub repository by visiting [repo.new](https://repo.new/). When you are done creating a new repository, prepare and push your local application to GitHub by running the following commands in your terminal:
```

2022-12-21 17:57 UTC, deadlypants1973 commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function-with-fauna-nextjs/index.md
> +
```suggestion
```

2022-12-21 17:57 UTC, deadlypants1973 commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function-with-fauna-nextjs/index.md
> +
```suggestion
To deploy your project:

1. Log in to the [Cloudflare dashboard](https://dash.cloudflare.com/).
2. In Account Home, select **Pages** > **Create a project**.
3. In **Build settings**, select **Next.js** as your **Framework preset**.
```

2022-12-21 17:57 UTC, deadlypants1973 commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function-with-fauna-nextjs/index.md
> +4. In the environment variable section add a new variable called `NODE_VERSION` and add the node version of your project. **You require a node version 14 or greater.**
```suggestion
4. In **Environment variables (advanced), add a new variable called `NODE_VERSION` and add the Node version of your project. You need a Node version `14` or higher.
```

2022-12-21 17:57 UTC, deadlypants1973 commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function-with-fauna-nextjs/index.md
> +5. Next, go to **Settings > Functions** and under compatibility flags add the following flags.
```suggestion
5. Select **Save and Deploy**.
6. After you have created and deployed your project, go to your project > **Settings**  > **Functions** > **Compatibility flags** > **Add Production compatibility flags** and add the following flags: `streams_enable_constructors` and `transformstream_enable_standard_constructor`.
```

2022-12-21 17:57 UTC, deadlypants1973 commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function-with-fauna-nextjs/index.md
> +*These flags are scheduled to graduate on the 2022-11-30 compatibility date and should no longer be necessary to manually add after November 30, 2022.*
If that's the case, let's remove step 5 entirely?

2022-12-21 17:57 UTC, deadlypants1973 commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function-with-fauna-nextjs/index.md
> +Visit the deployed site url to make sure everything is working as expected.
This can be deleted. The user has to save and deploy before they can access Functions.
```suggestion
```

2022-12-21 17:57 UTC, deadlypants1973 commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function-with-fauna-nextjs/index.md
> +![Define Node Version in cloud flare configuration](/pages/tutorials/build-a-fullstack-app-with-pages-function-with-fauna-nextjs/node_version.png)
```suggestion
![Define Node Version in Cloudflare configuration](/pages/tutorials/build-a-fullstack-app-with-pages-function-with-fauna-nextjs/node_version.png)
```

2022-12-21 17:57 UTC, deadlypants1973 commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function-with-fauna-nextjs/index.md
> +Next, visit [`https://<your-domain-name>/api/hello`](https://with-cloudflare-nextjs.pages.dev/api/hello) to make sure that the Pages function is working as expected.
```suggestion
Next, go to [`https://<YOUR_DOMAIN_NAME>/api/hello`](https://with-cloudflare-nextjs.pages.dev/api/hello) to make sure that the Pages Function is working as expected. 
```

2022-12-21 17:57 UTC, deadlypants1973 commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function-with-fauna-nextjs/index.md
> +Next, visit [`https://<your-domain-name>/api/hello`](https://with-cloudflare-nextjs.pages.dev/api/hello) to make sure that the Pages function is working as expected.
What Function is this? What you set up in the compat flag step?

2022-12-21 17:57 UTC, deadlypants1973 commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function-with-fauna-nextjs/index.md
> +*You also have the option to save data into privately distributed nodes with [Virtual Private Fauna.](https://www.globenewswire.com/news-release/2022/11/17/2558259/0/en/Fauna-Launches-Virtual-Private
```suggestion
To configure your Fauna database:

1. Log in to your [Fauna dashboard](https://dashboard.fauna.com/) or create an account and log in.
2. Create a new database give your database a name. 
3. Select **Classic** as your **Region Group** and select **Create**.

{{<Aside type="note">}}

By default, Fauna allows you to save your data globally closer to your user. You can limit your data's distribution to a specific geographic region group to comply with GDPR and data residency. Learn more about [region groups](https://docs.fauna.com/fauna/current/learn/understanding/region_groups).

You also have the option to save data into privately distributed nodes with [Virtual Private Fauna](https://www.globenewswire.com/news-release/2022/11/17/2558259/0/en/Fauna-Launches-Virtual-Private-Offering-of-its-Serverless-Database-for-the-Most-Demanding-Enterprise-Applications.html).

{{</Aside>}}
```

2022-12-21 17:57 UTC, deadlypants1973 commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function-with-fauna-nextjs/index.md
> +3. Next, select *create new collection*.
```suggestion
4. Next, select **NEW COLLECTION*. 
```

2022-12-21 17:57 UTC, deadlypants1973 commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function-with-fauna-nextjs/index.md
> +4. Create a new Collection called `Products`.
```suggestion
5. Create a new Collection called `Products`.
```

2022-12-21 17:57 UTC, deadlypants1973 commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function-with-fauna-nextjs/index.md
> +5. You would require a secret to query your database from your application. Navigate to *Security > Keys* and select *New Key*.
```suggestion
6. You need a secret to query your database from your application. Go to **Security** > **Keys** and select **New Key**.
```

2022-12-21 17:57 UTC, deadlypants1973 commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function-with-fauna-nextjs/index.md
> +6. Select `Server` Role from the dropdown. Give your key a name and select *Save*. When the key is generated save it into a secure file.
```suggestion
7. Select *Server* as your **Role**. 
8. Give your key a name and select **Save**. When the key is generated, save it into a secure file.
```

2022-12-21 17:57 UTC, deadlypants1973 commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function-with-fauna-nextjs/index.md
> +7. For local development create a new file called `.env` in the root of your project and add the following code. Make sure you add `.env` to your git ignore file so it doesn’t get committed.
```suggestion
9. For local development, create a new file called `.env` in the root of your project and add the following code. Make sure you add `.env` to your `.gitignore` file so it does not get committed.
```

2022-12-21 17:57 UTC, deadlypants1973 commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function-with-fauna-nextjs/index.md
> +8. Finally, head back to Cloudflare Pages settings and add a new environment variable called FAUNA_SECRET.
```suggestion
10. Lastly, go to **Pages** in the Cloudflare dashboard > **Settings** > **Environment Variables** and add a new environment variable called `FAUNA_SECRET` with a value of ____. 
```
What is the value for the variable?

2022-12-21 17:57 UTC, deadlypants1973 commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function-with-fauna-nextjs/index.md
> +![Fauna Secret](/pages/tutorials/build-a-fullstack-app-with-pages-function-with-fauna-nextjs/fauna_secret.png)
```suggestion
![Instructions for adding a `FAUNA_SECRET` variable are above.](/pages/tutorials/build-a-fullstack-app-with-pages-function-with-fauna-nextjs/fauna_secret.png)
```

2022-12-21 17:57 UTC, deadlypants1973 commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function-with-fauna-nextjs/index.md
> +### Create the add product page (Frontend)
```suggestion
### Create the add product page
```

2022-12-21 17:57 UTC, deadlypants1973 commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function-with-fauna-nextjs/index.md
> +Create a new front-end page to add data to your database. Create a new file `pages/add-products.js` in your project and add the following code to it.
```suggestion
Create a new front-end page to add data to your database. Create a new file `pages/add-products.js` in your project and add the following code:
```

2022-12-21 17:57 UTC, deadlypants1973 commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function-with-fauna-nextjs/index.md
> +```jsx
```suggestion
```jsx
---
filename: pages/add-products.js
---
```

2022-12-21 17:57 UTC, deadlypants1973 commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function-with-fauna-nextjs/index.md
> +Run the application locally with the following command.
```suggestion
Run the application locally with the following command:
```

2022-12-21 17:57 UTC, deadlypants1973 commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function-with-fauna-nextjs/index.md
> +In the previous code block you have a simple form component to add products. On form submit it calls the `/api/products` api routes.
```suggestion
In the above code block, you have a simple form component to add products. On form submit, it calls the `/api/products` API route. 
```
1. "On form submit..." What is 'form submit'?

2022-12-21 17:57 UTC, deadlypants1973 commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function-with-fauna-nextjs/index.md
> +Visit [`http://localhost:3000/add-products`](http://localhost:3000/add-products) and try to create a new product.
```suggestion
Go to [`http://localhost:3000/add-products`](http://localhost:3000/add-products) and try to create a new product.
```

2022-12-21 17:57 UTC, deadlypants1973 commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function-with-fauna-nextjs/index.md
> +Notice, when you submit the form it gives you a *404 not found error.* This is because the api route for `api/products` doesn’t exist yet. Let’s go ahead and create the API route next.
```suggestion
When you submit the form, it returns a `404 Not found` error. This is because the API route for `api/products` does not exist yet. You will now create the API route. 
```

2022-12-21 17:57 UTC, deadlypants1973 commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function-with-fauna-nextjs/index.md
> +### Create the api route to add product (Backend)
```suggestion
### Create the API route to add product
```

2022-12-21 17:57 UTC, deadlypants1973 commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function-with-fauna-nextjs/index.md
> +Create a new file `pages/api/products.js` and add the following code to the file.
Where are they creating this file?

2022-12-21 17:57 UTC, deadlypants1973 commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function-with-fauna-nextjs/index.md
> +```jsx
```suggestion
```jsx
---
filename: pages/api/products.js
---
```

2022-12-21 17:57 UTC, deadlypants1973 commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function-with-fauna-nextjs/index.md
> +Try creating a new product from the `add-products` page again. Open the network tab in your browser and notice that on form submit you will not get a 404 error anymore.
```suggestion
Create a new product from the `add-products` page. Open the network tab in your browser and notice that on form submit you will not get a `404` error anymore. 
```
"network tab in your browser" is this talking about Chrome devtools? Need to be specific on this navigation.

2022-12-21 17:57 UTC, deadlypants1973 commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function-with-fauna-nextjs/index.md
> +### Reading data from request body in Edge Runtime
```suggestion
### Read data from the request body in Edge Runtime
```

2022-12-21 17:57 UTC, deadlypants1973 commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function-with-fauna-nextjs/index.md
> +The Next.js Edge Runtime is based on standard Web APIs. This is slightly different than the default Node.js-powered API route. The request body for Edge Runtime gives you a [ReadableStream](https://d
```suggestion
The Next.js Edge Runtime is based on standard Web APIs. This is different than the default Node.js-powered API route. The request body for Edge Runtime gives you a [ReadableStream](https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream/ReadableStream). You must decode this to read the request body. 
```

2022-12-21 17:57 UTC, deadlypants1973 commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function-with-fauna-nextjs/index.md
> +```jsx
```suggestion
```jsx
---
filename: pages/api/products.js
---
```

2022-12-21 17:57 UTC, deadlypants1973 commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function-with-fauna-nextjs/index.md
> +However, this is not saving the data in our database yet. Next, let’s add the code for database operation.
```suggestion
You will not be able to save the data in your database yet. Next, you will add the code for database operation.
```

2022-12-21 17:57 UTC, deadlypants1973 commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function-with-fauna-nextjs/index.md
> +### Adding database operations
```suggestion
### Add database operations
```

2022-12-21 17:57 UTC, deadlypants1973 commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function-with-fauna-nextjs/index.md
> +install the fauna package in your project by running the following command.
```suggestion
Install the Fauna package in your project by running the following command:
```

2022-12-21 17:57 UTC, deadlypants1973 commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function-with-fauna-nextjs/index.md
> +Next, create a new file called `db.js` and add the following code.
Create a new file where?

2022-12-21 17:57 UTC, deadlypants1973 commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function-with-fauna-nextjs/index.md
> +You can import the `createProduct` function into your Edge runtime and execute it to create a new database record.
```suggestion
You can import the `createProduct` function into your Edge Runtime and execute it to create a new database record.
```

2022-12-21 17:57 UTC, deadlypants1973 commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function-with-fauna-nextjs/index.md
> +```jsx
What file is this?

2022-12-21 17:57 UTC, deadlypants1973 commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function-with-fauna-nextjs/index.md
> +Next, go ahead and create new database function to retrieve all the products. Add the following function to your `db.js` file.
```suggestion
You will now create a new database function to retrieve all the products. Add the following function to your `db.js` file.
```

2022-12-21 17:57 UTC, deadlypants1973 commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function-with-fauna-nextjs/index.md
> +```jsx
```suggestion
```jsx
---
filename: db.js
---
```

2022-12-21 17:57 UTC, deadlypants1973 commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function-with-fauna-nextjs/index.md
> +```jsx
```suggestion
```jsx
---
filename: pages/index.js
---
```

2022-12-21 17:57 UTC, deadlypants1973 commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function-with-fauna-nextjs/index.md
> +Go to [https://www.webpagetest.org/](https://www.webpagetest.org/) and paste in your website url to check the performance of your global application. You can pick up various global location and netwo
```suggestion
Go to [https://www.webpagetest.org/](https://www.webpagetest.org/) and paste in your website URL to check the performance of your global application.
```

2022-12-21 17:57 UTC, deadlypants1973 commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function-with-fauna-nextjs/index.md
> +For this simple application, the page resolves in less 15ms on average from different servers across the globe.
```suggestion
For this simple application, the page should resolve in less 15 ms on average from different servers across the globe. 
```

2022-12-21 17:57 UTC, deadlypants1973 commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function-with-fauna-nextjs/index.md
> +The compute and database operations are almost the same across the globe. The powerful combination of Cloudflare CDN, workers and Fauna database allow your code and data to run closer to your end use
```suggestion
The compute and database operations are almost the same across the globe. The combination of Cloudflare CDN, Workers and Fauna database allows your code and data to run closer to your end user reducing application latency globally. 
```

2022-12-21 17:57 UTC, deadlypants1973 commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function-with-fauna-nextjs/index.md
> +## Where to go from here
```suggestion
## Related resources
```

2022-12-21 17:57 UTC, deadlypants1973 commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function-with-fauna-nextjs/index.md
> +If you are looking to build something more practical and hands on we have created a self paced workshop on "How to build a global application with Cloudflare and Fauna". You can check this out [here]
```suggestion
* [How to build a global application with Cloudflare and Fauna](https://github.com/fauna-labs/fauna-workers)
```

2022-12-21 17:57 UTC, deadlypants1973 commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function-with-fauna-nextjs/index.md
> +## Global Application Benchmark
```suggestion
## Test your application's speed
```

2022-12-21 17:58 UTC, deadlypants1973 commented
@Shadid12 hello! Tech writer review has been submitted. Please accept suggestions and answer questions when time allows :)

2023-01-11 09:42 UTC, deadlypants1973 commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function-with-fauna-nextjs/index.md
> +// db.js
```suggestion
```jsx
---
filename: db.js
---
```

2023-01-11 10:12 UTC, deadlypants1973 commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function-with-fauna-nextjs/index.md
> +## Create a new Project
```suggestion
## Create a new project
```

2023-01-11 10:14 UTC, deadlypants1973 commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function-with-fauna-nextjs/index.md
> +// pages/api/hello.js
```suggestion
---
filename: pages/api/hello.js
---
```

2023-01-11 10:26 UTC, deadlypants1973 commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function-with-fauna-nextjs/index.md
> +![adding compatibility flags](/pages/tutorials/build-a-fullstack-app-with-pages-function-with-fauna-nextjs/compatibility.png)
```suggestion
![Add compatibility flags by following the instructions above](/pages/tutorials/build-a-fullstack-app-with-pages-function-with-fauna-nextjs/compatibility.png)
```

2023-01-19 20:22 UTC, Shadid12 commented
@deadlypants1973 Updated the content as per review. Thank you

2023-02-09 04:17 UTC, Shadid12 commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function/index.md
> +![Build output](/pages/tutorials/build-a-fullstack-app-with-pages-function/build-output.png)
done

2023-02-09 04:25 UTC, Shadid12 commented on content/pages/tutorials/build-a-fullstack-app-with-pages-function/index.md
> +*You also have the option to save data into privately distributed nodes with [Virtual Private Fauna.](https://www.globenewswire.com/news-release/2022/11/17/2558259/0/en/Fauna-Launches-Virtual-Private
removed

2023-03-31 13:34 UTC, Teerasak71 commented
***@***.***

Pau Teerasak

2023-06-23 12:25 UTC, KimJ15 commented
@deadlypants1973 @WalshyDev Seems like we got close with this tutorial/PR and I just wanted to bump to see if we're close to publication!

2023-06-23 15:27 UTC, closed without merging