Add feature enablement information
cloudflare/cloudflare-docs pull request #6895
Opened 2022-12-01 15:28 UTC by markdembo

Added information on how to get WFP enabled

2022-12-01 15:40 UTC, tanushreesharma-cf commented on content/cloudflare-for-platforms/workers-for-platforms/get-started/configuration.md
> +This guide will instruct you on setting up Workers for Platforms. This guide assumes that you already have a Cloudflare account. If you do not have a Cloudflare account, sign up before continuing. Mo
```suggestion
This guide will instruct you on setting up Workers for Platforms. This guide assumes that you already have a Cloudflare account. If you do not have a Cloudflare account, sign up before continuing. Moreover, this feature is not enabled by default. Please contact your account manager, or reach out on the [Cloudflare Developer Discord](https://discord.com/invite/cloudflaredev) on more information about how to get Workers for Platforms enabled for your account.
```

2022-12-01 15:59 UTC, tanushreesharma-cf commented
@deadlypants1973 can you take a look at this?

2022-12-05 13:36 UTC, deadlypants1973 requested changes

2022-12-05 13:36 UTC, deadlypants1973 commented on content/cloudflare-for-platforms/workers-for-platforms/get-started/configuration.md
> +This guide will instruct you on setting up Workers for Platforms. This guide assumes that you already have a Cloudflare account. If you do not have a Cloudflare account, sign up before continuing. Mo
talking with tanushree about updating this with exact instructions, do not merge

2022-12-06 14:36 UTC, deadlypants1973 commented
Closing this to open another PR with different formatting

2022-12-06 14:36 UTC, closed without merging

2022-12-06 16:49 UTC, deadlypants1973 commented
https://github.com/cloudflare/cloudflare-docs/pull/6947