Document new time-related Analytics Engine SQL features
cloudflare/cloudflare-docs pull request #6903
Opened 2022-12-02 12:34 UTC by 46bit

This PR adds documentation for a variety of new time-related SQL features in Analytics Engine. They're already live but mostly unannounced until this PR is merged.

New show statements:
  - `SHOW TIMEZONE`
  - `SHOW TIMEZONES`

New comparison operators:
  - `BETWEEN`

New functions:
  - `formatDateTime`
  - `toUnixTimestamp`
  - `toStartOfInterval`
  - `extract`

2022-12-05 08:24 UTC, jimhawkridge requested changes

2022-12-05 08:24 UTC, jimhawkridge commented on content/analytics/analytics-engine/sql-reference.md
> +## `SHOW TABLES` statement
If this is going to be backticked then SELECT statement should be too, below, for consistency.
ISTR that backticks in these titles don't render too well though (they are also rendered in the sidebar) so maybe better without?

2022-12-05 08:24 UTC, jimhawkridge commented on content/analytics/analytics-engine/sql-reference.md
> +### toDateTime
Merge this with the one below?

2022-12-05 08:24 UTC, jimhawkridge commented on content/analytics/analytics-engine/sql-reference.md
> +`formatDateTime` prints a datetime as a string according to a provided format string. The format
Something got lost from the end of this?

2022-12-05 08:24 UTC, jimhawkridge commented on content/analytics/analytics-engine/sql-reference.md
> +extract(SECOND from toDateTime('2022-06-06 11:15:15'))
For clarity, maybe??:
```suggestion
extract(SECOND from toDateTime('2022-06-06 11:15:30'))
```

2022-12-05 14:04 UTC, 46bit commented on content/analytics/analytics-engine/sql-reference.md
> +## `SHOW TABLES` statement
Thanks, you're right, I'll fix

2022-12-05 14:07 UTC, jimhawkridge commented on content/analytics/analytics-engine/sql-reference.md
> +extract(SECOND from toDateTime('2022-06-06 11:15:15'))
Just noticed - I changed the wrong field in the above suggestion. Have edited it.

2022-12-05 14:14 UTC, 46bit commented on content/analytics/analytics-engine/sql-reference.md
> +extract(SECOND from toDateTime('2022-06-06 11:15:15'))
Thanks :)

2022-12-06 09:24 UTC, jimhawkridge approved these changes
Nice :-)

2022-12-06 10:08 UTC, angelampcosta approved these changes

2022-12-06 12:29 UTC, victor-perov approved these changes

2022-12-13 16:35 UTC, merged