[Logs] Updated Max Upload Parameters and created a page for Log Output Options
cloudflare/cloudflare-docs pull request #6920
Opened 2022-12-05 15:40 UTC by angelampcosta

2022-12-05 18:15 UTC, soheiokamoto commented on content/logs/get-started/api-configuration.md
> +- There are no maximum value limits for these parameters, however, setting them too high may result in data loss.
Each of them actually has maximum value limits.
I.e., current allowed ranges are:
 - max_upload_bytes: 5MB to 1GB
 - max_upload_records: 1K to 1M
 - max_upload_interval_seconds: 30 seconds to 5 minute (as describe above)

2022-12-05 18:23 UTC, soheiokamoto commented on content/logs/get-started/log-output-options.md
> +- **sample_rate**: floating number to specify sampling rate (default 1.0: no sampling). Sampling is applied on top of andregardless of the current sample_interval of the data.
I think this should be:
```suggestion
- **sample_rate**: floating number to specify sampling rate (default 1.0: no sampling). Sampling is applied on top of filtering, and regardless of the current sample_interval of the data.
```

2022-12-05 19:18 UTC, soheiokamoto commented on content/logs/get-started/log-output-options.md
> +---
Shouldn't this page go under `Reference`, just like `Filter` and `Custom fields`?

2022-12-06 00:47 UTC, tlozoot requested changes
This is great -- just a few minor comments before merge

2022-12-06 00:47 UTC, tlozoot commented on content/logs/get-started/api-configuration.md
> +- There are no maximum value limits for these parameters, however, setting them too high may result in data loss.
Can we address this before merge?

2022-12-06 00:47 UTC, tlozoot commented on content/logs/get-started/log-output-options.md
> +---
I agree with this

2022-12-06 00:47 UTC, tlozoot commented on content/logs/get-started/log-output-options.md
> +## Why replace logpull_options
"Why" is a bit odd in section header here -- we don't really explain "why" and not sure we need to put that in dev docs (maybe a blog post?)

Maybe just "Replacing logpull_options"?

2022-12-06 00:47 UTC, tlozoot commented on content/logs/get-started/api-configuration.md
> -The options that you can customize are:
Can we keep this somewhere in the docs? I'm sure there are people who are still using logpull_options and will need time to migrate, and they'll want to see what the old options were.

2022-12-06 10:10 UTC, angelampcosta commented on content/logs/get-started/log-output-options.md
> +---
Makes sense. I'll move it.

2022-12-06 10:12 UTC, angelampcosta commented on content/logs/get-started/api-configuration.md
> +- There are no maximum value limits for these parameters, however, setting them too high may result in data loss.
I'll add the limits.

2022-12-06 10:45 UTC, angelampcosta commented on content/logs/get-started/api-configuration.md
> -The options that you can customize are:
I think we can keep the options were they are, after saying that logpull_options is substituted by output_options. When we think it's no longer needed, we can remove them from the docs.

2022-12-06 12:40 UTC, victor-perov requested changes
Thanks for working on it! I think we should fix json/csv in some example headers to make the syntax clearer.

2022-12-06 12:40 UTC, victor-perov commented on content/logs/reference/log-output-options.md
> +- **field_names**: array of strings.
nit: if we group options here by separating them with empty space then `field_names` should be accompanied with `field_delimeter` and separated from `output_type` (which in its turn should be grouped with `CVE-2021-44228`).

2022-12-06 12:40 UTC, victor-perov commented on content/logs/reference/log-output-options.md
> +```json
looks like a CSV to me

2022-12-06 12:40 UTC, victor-perov commented on content/logs/reference/log-output-options.md
> +```json
```suggestion
```csv
```

2022-12-06 12:40 UTC, victor-perov commented on content/logs/reference/log-output-options.md
> +```json
```suggestion
```csv
```

2022-12-06 12:40 UTC, victor-perov commented on content/logs/reference/log-output-options.md
> +```json
```suggestion
```csv
```

2022-12-06 12:40 UTC, victor-perov commented on content/logs/reference/log-output-options.md
> +- ndjson with different field names:
nit: move this example to the `ndjson` section above

2022-12-06 13:08 UTC, angelampcosta commented on content/logs/reference/log-output-options.md
> +- **field_names**: array of strings.
I removed the extra lines because they weren't displaying.

2022-12-06 17:07 UTC, jsells1 commented
👍

2022-12-06 17:27 UTC, victor-perov approved these changes

2022-12-06 18:22 UTC, soheiokamoto commented on content/logs/reference/log-output-options.md
> +```JSON
I don't know if it matters, but shouldn't this be lowercase usually?
```suggestion
```json
```

2022-12-06 22:20 UTC, tlozoot approved these changes

2022-12-07 10:01 UTC, merged