[BYOIP] Proxy IPs
cloudflare/cloudflare-docs pull request #6967
Opened 2022-12-07 19:09 UTC by patriciasantaana

PCX-5308

2022-12-07 19:31 UTC, kodster28 requested changes

2022-12-07 19:31 UTC, kodster28 commented on content/byoip/proxy-ips.md
> +The zone must also be proxied or orange-clouded. When a zone is proxied, Cloudflare authoritative DNS will respond with the address on the Address Map. The IP addresses under Records on the zone-leve
I'd cross link to managing DNS records.

2022-12-07 19:31 UTC, kodster28 commented on content/byoip/proxy-ips.md
> +The zone must also be proxied or orange-clouded. When a zone is proxied, Cloudflare authoritative DNS will respond with the address on the Address Map. The IP addresses under Records on the zone-leve
Zones aren't proxied (unless I'm mistaken). The records within a zone are proxied. Should also probably link this to https://developers.cloudflare.com/dns/manage-dns-records/reference/

2022-12-07 19:31 UTC, kodster28 commented on content/byoip/proxy-ips.md
> +Some customers may only use BYOIP and are prohibited from using Cloudflare IP addresses. In this case, Cloudflare will create an immutable, account-wide Address Map to ensure all zones in your accoun
I might sync with whoever your tech lead is to clarify the wording here.

Technically, records that are proxied _respond_ with CF IP addresses, but a DNS record should never be _directly using_ a CF IP address. That'll actually give you an error if you enter it in the dashboard.

2022-12-07 19:31 UTC, kodster28 commented on content/byoip/proxy-ips.md
> +To specify different addresses for certain zones, [create a new Address Map](/byoip/proxy-ips/#create-address-maps).
```suggestion
To specify different addresses for certain zones, [create a new Address Map](#create-address-maps).
```

2022-12-07 19:31 UTC, kodster28 commented on content/byoip/proxy-ips.md
> +To specify different addresses for certain zones, [create a new Address Map](/byoip/proxy-ips/#create-address-maps).
If it's w/in the same page, you only need the anchor link.

2022-12-15 21:00 UTC, kodster28 reviewed
Still some questions, but don't want PTO to block this going live.

2022-12-15 21:00 UTC, kodster28 approved these changes

2022-12-19 22:48 UTC, tarnfeld reviewed
I left a few comments to clarify things.

2022-12-19 22:48 UTC, tarnfeld commented on content/byoip/proxy-ips.md
> +The Address Map is a data structure which enables customers with BYOIP prefixes or account-level Static IPs to specify which IP addresses should be mapped to a zone when they are proxied on Cloudflar
```suggestion
The Address Map is a data structure enabling customers with BYOIP prefixes or account-level Static IPs to specify which IP addresses should be mapped to a zone's DNS records, when they are proxied through Cloudflare.
```

2022-12-19 22:48 UTC, tarnfeld commented on content/byoip/proxy-ips.md
> +Some customers may only use BYOIP and are prohibited from using Cloudflare IP addresses. In this case, Cloudflare will create an immutable, account-wide Address Map to ensure all zones in your accoun
I agree, I left a suggestion at the top to this effect as well.

2022-12-19 22:48 UTC, tarnfeld commented on content/byoip/proxy-ips.md
> +The zone must also be proxied or orange-clouded. When a zone is proxied, [Cloudflare authoritative DNS](/dns/manage-dns-records/how-to/create-dns-records/) will respond with the address on the Addres
```suggestion
For an Address Map to take effect, DNS records within the mapped zone must be set to proxied or orange-clouded. When a zone is proxied, [Cloudflare authoritative DNS](/dns/manage-dns-records/how-to/create-dns-records/) will respond with the address(es) on the Address Map. Address Maps do not change how Cloudflare reaches the configured origin, the IP addresses under Records on the zone-level DNS tab continue to instruct Cloudflare how to reach the origin.
```

2022-12-19 22:48 UTC, tarnfeld commented on content/byoip/proxy-ips.md
> +Creating an Address Map does not automatically change DNS configuration. DNS Responses only begin to change when a zone or account is added to a map.
```suggestion
Creating an Address Map does not automatically change DNS configuration. DNS Responses only begin to change when a zone or account is added to a map. Additionally, Address Maps that are not yet **Enabled** will not take effect in DNS responses.
```

2022-12-19 22:48 UTC, tarnfeld commented on content/byoip/proxy-ips.md
> +Creating an Address Map does not automatically change DNS configuration. DNS Responses only begin to change when a zone or account is added to a map.
I am unsure if we are using the Enabled or Deployed wording in the UI. Might need to adjust this as needed.

2022-12-19 22:48 UTC, tarnfeld commented on content/byoip/proxy-ips.md
> +Some customers may only use BYOIP and are prohibited from using Cloudflare IP addresses. In this case, Cloudflare will create an immutable, account-wide Address Map to ensure all zones in your accoun
```suggestion
Some customers may only proxy zones through BYOIP addresses, and are prohibited from using Cloudflare IP addresses for proxied DNS names. In this case, Cloudflare will create an immutable, account-wide Address Map to ensure all zones in your account receive BYOIP addresses as a fallback. These Address Maps cannot be deleted. It is still possible to create more specific zone-level Address Maps with specific BYOIPs, but without one DNS will fall back to the account-wide Address Map.
```

2022-12-20 17:13 UTC, merged