Add Queue Event Listener
cloudflare/cloudflare-docs pull request #7135
Opened 2023-01-02 23:31 UTC by omarkhairy21

2023-01-11 14:29 UTC, deadlypants1973 commented on content/workers/runtime-apis/add-event-listener.md
> +```js
```suggestion
### Queue Listener

```js
```

2023-01-12 13:49 UTC, rts-rob requested changes
Thanks for these fixes!

We should replace `waitUntil` with a sync call as shown elsewhere in the docs so that errors are not silently lost. Otherwise g2g.

2023-01-12 13:49 UTC, rts-rob commented on content/workers/runtime-apis/add-event-listener.md
> +  event.waitUntil(handleMessages(event));
I would not recommend using `waitUntil` for placing messages onto the queue. If `handleMessages(event)` throws an error, the client will not know about it, as the producer worker will have already returned (presumably) a 200.

2023-01-31 16:36 UTC, elithrar commented on content/workers/runtime-apis/add-event-listener.md
> +  event.waitUntil(handleMessages(event));
I would amend this to:

```js
addEventListener("queue", (event) => {
  await handleMessages(event);
});
```

2023-01-31 16:37 UTC, elithrar commented on content/workers/runtime-apis/add-event-listener.md
> +### Queue Listener
Under this header, we should add more context on what a "Queue Listener" is - e.g.

> A Queue listener acts as [a consumer for one or more queues](https://developers.cloudflare.com/queues/javascript-apis/#consumer).

2023-01-31 16:47 UTC, deadlypants1973 commented on content/workers/runtime-apis/add-event-listener.md
> +  event.waitUntil(handleMessages(event));
```suggestion
addEventListener("queue", (event) => {
  await handleMessages(event);
});
```

2023-01-31 16:48 UTC, deadlypants1973 commented on content/workers/runtime-apis/add-event-listener.md
> +});
```suggestion
```

2023-01-31 16:48 UTC, deadlypants1973 approved these changes

2023-01-31 17:03 UTC, a-robinson requested changes

2023-01-31 17:03 UTC, a-robinson commented on content/workers/runtime-apis/add-event-listener.md
> +  await handleMessages(event);
This is not valid code. The function defined here is not async, and so calling `await` inside it won't do what you want.

And you can't just make it async, because `addEventListener` doesn't handle async functions. The code was correct as originally written.

2023-02-02 15:17 UTC, deadlypants1973 commented on content/workers/runtime-apis/add-event-listener.md
> +  await handleMessages(event);
```suggestion
addEventListener("queue", (event) => {
  event.waitUntil(handleMessages(event));
```

2023-02-02 15:24 UTC, a-robinson approved these changes

2023-02-02 15:28 UTC, merged