[Teams] auth domain > team domain
cloudflare/cloudflare-docs pull request #717
Opened 2021-02-01 20:22 UTC by abracchi-tw

2021-02-01 20:23 UTC, TownLake approved these changes

2021-02-01 21:46 UTC, kennyj42 commented on products/cloudflare-one/src/content/connections/connect-devices/warp/deployment/Windows-Teams.md
> +1. Enter your [team name](/glossary#team-name).
Are we doing these changes in the docs before the UI changes or just queuing up?

2021-02-01 21:47 UTC, kennyj42 commented on products/cloudflare-one/src/content/identity/idp-integration/azuread.md
> +![Azure AD groups](../../static/documentation/identity/azure/azure-ad-groups.png)
this image is broken

2021-02-01 21:48 UTC, kennyj42 commented on products/cloudflare-one/src/content/identity/idp-integration/facebook-login.md
> +    ![OAuth ID and OAuth Secret](../../static/documentation/identity/facebook/fb10.png)
This image looks broken

2021-02-01 21:51 UTC, kennyj42 commented on products/cloudflare-one/src/content/identity/idp-integration/keycloak.md
> +    ![Access Config](../../static/documentation/identity/keycloak/access-config-keycloak.png)
broken image

2021-02-01 21:51 UTC, kennyj42 commented on products/cloudflare-one/src/content/identity/idp-integration/keycloak.md
> +    ![Access Config](../../static/documentation/identity/keycloak/access-config-keycloak.png)
\it's the old dash I think

2021-02-01 21:52 UTC, kennyj42 commented on products/cloudflare-one/src/content/identity/idp-integration/okta.md
>  1. In your Okta dashboard, click **Admin**.
The numbering is broken on this one. It's all "1." 's

2021-02-01 21:55 UTC, kennyj42 commented on products/cloudflare-one/src/content/identity/idp-integration/saml-okta.md
> +1. In the **Single sign on URL** and the **Audience URI** **(SP Entity ID)** fields, enter your [team domain](/glossary#team-domain) followed by this callback at the end of the path: `/cdn-cgi/access
I think this should have an e.g.:

e.g. [your-team-name].cloudflareaccess.com/cdn-cgi/access/callback

2021-02-01 21:56 UTC, kennyj42 commented on products/cloudflare-one/src/content/identity/idp-integration/yandex.md
> +1. In the **Callback URL #1** field, enter [team domain](/glossary#team-domain) followed by this callback at the end of the path: `/cdn-cgi/access/callback`.
Same comment as signed_authn

2021-02-01 21:56 UTC, kennyj42 commented on products/cloudflare-one/src/content/identity/idp-integration/yandex.md
> +1. In the **Callback URL #1** field, enter [team domain](/glossary#team-domain) followed by this callback at the end of the path: `/cdn-cgi/access/callback`.
should give the e.g.

2021-02-01 21:57 UTC, kennyj42 commented on products/cloudflare-one/src/content/identity/idp-integration/yandex.md
> +     ![Cloudflare Access Add a Yandex identity provider dialog Platforms](../../static/documentation/identity/yandex/yandex-9.png)
this image may be broken

2021-02-01 21:59 UTC, kennyj42 requested changes
See individual comments. A couple image issues and a few spots where additional examples may help

2021-02-03 20:10 UTC, abracchi-tw commented on products/cloudflare-one/src/content/connections/connect-devices/warp/deployment/Windows-Teams.md
> +1. Enter your [team name](/glossary#team-name).
yeah these changes will go live before the UI gets updated, but it's just a matter of days

2021-02-03 20:10 UTC, abracchi-tw commented on products/cloudflare-one/src/content/identity/idp-integration/okta.md
>  1. In your Okta dashboard, click **Admin**.
yeah that's intended, they'll be rendered correctly

2021-02-03 20:10 UTC, abracchi-tw commented on products/cloudflare-one/src/content/identity/idp-integration/saml-okta.md
> +1. In the **Single sign on URL** and the **Audience URI** **(SP Entity ID)** fields, enter your [team domain](/glossary#team-domain) followed by this callback at the end of the path: `/cdn-cgi/access
fixed

2021-02-03 20:10 UTC, abracchi-tw commented on products/cloudflare-one/src/content/identity/idp-integration/yandex.md
> +1. In the **Callback URL #1** field, enter [team domain](/glossary#team-domain) followed by this callback at the end of the path: `/cdn-cgi/access/callback`.
fixed

2021-02-03 21:52 UTC, kennyj42 approved these changes

2021-02-04 10:16 UTC, merged