Clarify how functions are uploaded with wrangler pages
cloudflare/cloudflare-docs pull request #7176
Opened 2023-01-06 19:31 UTC by IanVS

I was recently confused how to upload functions using wrangler.  Hopefully these changes can help make it clear to others.

2023-01-06 20:46 UTC, jasikpark reviewed
lgtm

2023-01-07 00:39 UTC, WalshyDev requested changes

2023-01-07 00:39 UTC, WalshyDev commented on content/pages/platform/direct-upload.md
> +Drag-and-drop deployments made from the Cloudflare dashboard do not currently support compiling a `functions` folder of Pages Functions. In order to deploy a `functions` folder, you must use Wrangler
```suggestion
Drag-and-drop deployments made from the Cloudflare dashboard do not currently support compiling a `functions` folder of Pages Functions.
In order to deploy a functions folder, you must use Wrangler. When deploying a project using Wrangler, if a `functions` folder exists where the command is run, that will be uploaded with the project.
```

2023-01-07 00:39 UTC, WalshyDev commented on content/workers/wrangler/commands.md
> +{{</Aside>}}
I'm not sure this brings any benefit.  I'd rather we describe this more clearly elsewhere than add _another_ aside.
```suggestion
```

2023-01-07 02:58 UTC, IanVS commented on content/workers/wrangler/commands.md
> +{{</Aside>}}
Ok that's fine. I think the other spot is probably enough.

2023-01-09 14:39 UTC, WalshyDev commented on content/workers/wrangler/commands.md
> +
```suggestion
```

2023-01-09 23:56 UTC, jasikpark reviewed
lgtm

2023-01-10 17:43 UTC, deadlypants1973 approved these changes

2023-01-10 17:43 UTC, deadlypants1973 commented on content/pages/platform/direct-upload.md
> +In order to deploy a functions folder, you must use Wrangler. When deploying a project using Wrangler, if a `functions` folder exists where the command is run, that will be uploaded with the project.
```suggestion
Drag and drop deployments made from the Cloudflare dashboard do not currently support compiling a `functions` folder of Pages Functions.
In order to deploy a `functions` folder, you must use Wrangler. When deploying a project using Wrangler, if a `functions` folder exists where the command is run, that will be uploaded with the project.
```

2023-01-10 17:44 UTC, deadlypants1973 requested changes
Added wording for proper noun clarity

2023-01-10 17:48 UTC, deadlypants1973 approved these changes

2023-01-10 17:49 UTC, WalshyDev approved these changes

2023-01-11 13:59 UTC, merged