Clarify "Source of Truth" wording
cloudflare/cloudflare-docs pull request #7278
Opened 2023-01-17 13:23 UTC by penalosa

Follow on from https://github.com/cloudflare/cloudflare-docs/issues/6786

2023-01-17 13:28 UTC, rozenmd commented on content/workers/wrangler/configuration.md
> +We recommend treating your wrangler.toml file as the source of truth for your Worker configuration, and to avoid making changes to your Worker via the Cloudflare dashboard if you're using Wrangler. I
```suggestion
We recommend treating your `wrangler.toml` file as the source of truth for your Worker configuration, and to avoid making changes to your Worker via the Cloudflare dashboard if you are using Wrangler. 

If you need to make changes to your Worker from the Cloudflare dashboard, the dashboard will generate a TOML snippet for you to copy into your `wrangler.toml` file, which will help ensure your `wrangler.toml` file is always up to date.
```

2023-01-17 15:13 UTC, JacobMGEvans requested changes
I suggest we start using `Wrangler configuration` verbage then reference `i.e. wrangler.toml` due to the JSON support that will be available in the near future.

2023-01-17 16:19 UTC, admah commented
@JacobMGEvans I think we'll need to think through that verbiage more and do that work as a part of a larger docs effort for JSON support.

2023-01-17 19:44 UTC, JacobMGEvans approved these changes
Based on the conversation internally with @admah about my concerns considering a more umbrella terminology around `Wrangler configuration` this PR is not blocked by that. 

Tentative to resolution with @rozenmd comments.

2023-01-19 14:25 UTC, deadlypants1973 approved these changes

2023-01-20 11:32 UTC, merged

2026-09-25 17:35 UTC, kinwcal357-prog commented
QR—vpn