Add documentation for mTLS certificates in workers
cloudflare/cloudflare-docs pull request #7371
Opened 2023-01-23 19:54 UTC by matthewdavidrodgers

Adds a new page for documenting the runtime API: `/workers/runtime-apis/mtls`
And then references that new page in the `/workers/learning/integrations` pages

Updates the commands and configuration pages for wrangler to document the new mTLS APIs

2023-01-24 06:37 UTC, KianNH commented on content/workers/runtime-apis/mTLS.md
> +        return await environment.MY_CERT.fetch("https://a-secured-origin.com")
It'd be awesome to use the Tab Switcher shortcode to have both a JavaScript and TypeScript example - demonstrating that `MY_CERT` has the `Fetcher` type.

Example usage: https://github.com/cloudflare/cloudflare-docs/blob/production/content/workers/examples/103-early-hints.md?plain=1#L24-L105

2023-01-24 22:31 UTC, matthewdavidrodgers commented on content/workers/runtime-apis/mTLS.md
> +        return await environment.MY_CERT.fetch("https://a-secured-origin.com")
great idea - added

2023-01-26 15:11 UTC, deadlypants1973 requested changes

2023-01-26 15:11 UTC, deadlypants1973 commented on content/workers/learning/integrations/apis.md
> +For services that require mTLS authentication, you can use [mTLS certificates](/workers/runtime-apis/mtls) to present a client certificate.
```suggestion
For services that require mTLS authentication, use [mTLS certificates](/workers/runtime-apis/mtls) to present a client certificate.
```

2023-01-26 15:11 UTC, deadlypants1973 commented on content/workers/learning/integrations/databases.md
> +For services that require mTLS authentication, you can use [mTLS certificates](/workers/runtime-apis/mtls) to present a client certificate.
```suggestion
For services that require mTLS authentication, use [mTLS certificates](/workers/runtime-apis/mtls) to present a client certificate.
```

2023-01-26 15:11 UTC, deadlypants1973 commented on content/workers/learning/integrations/external-services.md
> +For services that require mTLS authentication, you can use [mTLS certificates](/workers/runtime-apis/mtls) to present a client certificate.
```suggestion
For services that require mTLS authentication, use [mTLS certificates](/workers/runtime-apis/mtls) to present a client certificate.
```

2023-01-26 15:11 UTC, deadlypants1973 commented on content/workers/runtime-apis/mTLS.md
> +Add the certificate to your wrangler.toml to bind to the certificate:
```suggestion
Add the certificate to your `wrangler.toml` to bind your Worker project to the certificate:
```

2023-01-26 15:11 UTC, deadlypants1973 commented on content/workers/runtime-apis/mTLS.md
> +Certificate IDs are displayed after uploading, and can also be viewed with the command `wrangler mtls-certificate list`
```suggestion
Certificate IDs are displayed after uploading, and can also be viewed with the command `wrangler mtls-certificate list`.
```

2023-01-26 15:11 UTC, deadlypants1973 commented on content/workers/wrangler/commands.md
> +You can then add this cert as a binding in your wrangler.toml:
```suggestion
You can then add this certificate as a binding in your Worker project's `wrangler.toml`:
```

2023-01-26 15:11 UTC, deadlypants1973 commented on content/workers/wrangler/configuration.md
> +To communicate with origins that require client authentication, a worker can present a certificate for mTLS in subrequests. Wrangler provides the `mtls-certificate` [command](/workers/wrangler/comman
```suggestion
To communicate with origins that require client authentication, a Worker can present a certificate for mTLS in subrequests. Wrangler provides the `mtls-certificate` [command](/workers/wrangler/commands#mtls-certificate) to upload and manage these certificates.
```

2023-01-26 15:11 UTC, deadlypants1973 commented on content/workers/wrangler/commands.md
> +You can then add this cert as a binding in your wrangler.toml:
This section is missing a sentence describing what the binding will achieve for the user. Why are they creating this binding?

2023-01-26 15:11 UTC, deadlypants1973 commented on content/workers/wrangler/configuration.md
> +To bind an mTLS certificate to your worker, assign an array of objects with the following shape to the `mtls_certificates` key.
```suggestion
To bind an mTLS certificate to your Worker, assign an array of objects with the following shape to the `mtls_certificates` key.
```

2023-01-26 15:11 UTC, deadlypants1973 commented on content/workers/wrangler/configuration.md
> +  - The id of the certificate. Wrangler displays this via the `mtls-certificate upload` and `mtls-certificate list` commands.
```suggestion
  - The ID of the certificate. Wrangler displays this via the `mtls-certificate upload` and `mtls-certificate list` commands.
```

2023-01-31 16:51 UTC, matthewdavidrodgers commented
@deadlypants1973 thanks for the catches there - cleaned up!

2023-01-31 17:00 UTC, deadlypants1973 commented on content/workers/wrangler/commands.md
> +You can then add this certificate as a binding in your wrangler.toml:
```suggestion
You can then add this certificate as a binding in your `wrangler.toml`:

```

2023-01-31 17:00 UTC, deadlypants1973 commented on content/workers/runtime-apis/mTLS.md
> +To present a client certificate when communicating with a service, upload and bind a certificate and its private key using the [`wrangler mtls-certificate`](/workers/wrangler/commands/#mtls-certifica
Is 'service' here meaning Worker? because if so, it should be written as either:

"Service (Worker)"
or
"Worker"

2023-01-31 17:00 UTC, deadlypants1973 commented on content/workers/runtime-apis/mTLS.md
> +Add the certificate to your wrangler.toml to bind to the certificate:
```suggestion
Add the certificate to your `wrangler.toml` to bind your Worker project to the certificate:
```

Not sure why this wasn't added in, monospace and explanation of why create a binding seems necessary?

2023-01-31 17:42 UTC, matthewdavidrodgers commented on content/workers/runtime-apis/mTLS.md
> +To present a client certificate when communicating with a service, upload and bind a certificate and its private key using the [`wrangler mtls-certificate`](/workers/wrangler/commands/#mtls-certifica
'service' here does not refer to a Worker - it refers to any traditional (probably external) service that a Worker would like to communicate with

2023-01-31 17:45 UTC, matthewdavidrodgers commented on content/workers/runtime-apis/mTLS.md
> +Add the certificate to your wrangler.toml to bind to the certificate:
will update the monospace and add "your Worker project", but:

not sure what you mean by "why create a binding seems necessary"? the previous paragraph does that in my opinion, particularly this line: "To present a client certificate when communicating with a service, upload and bind a certificate..."

2023-02-02 22:48 UTC, matthewdavidrodgers commented on content/workers/runtime-apis/mTLS.md
> +Add the certificate to your wrangler.toml to bind to the certificate:
@deadlypants1973 just a bump for clarification on what you mean here

2023-02-03 14:57 UTC, deadlypants1973 commented on content/workers/runtime-apis/mTLS.md
> +To present a client certificate when communicating with a service, upload and bind a certificate and its private key using the [`wrangler mtls-certificate`](/workers/wrangler/commands/#mtls-certifica
oh I see, in that case, disregard my comment! thanks :)

2023-02-06 19:27 UTC, matthewdavidrodgers commented
bump for any others watching this - looking for approvals/feedback here

2023-02-07 04:22 UTC, tanushreesharma-cf commented on content/workers/runtime-apis/mTLS.md
> +Add the certificate to your wrangler.toml to bind to the certificate:
Hey @deadlypants1973 what do we need to get this PR through?

2023-02-07 04:28 UTC, KianNH commented on content/workers/runtime-apis/mTLS.md
> +wrangler mtls-certificate upload --cert cert.pem --key key.pem
```suggestion
$ wrangler mtls-certificate upload --cert cert.pem --key key.pem
```

2023-02-07 04:28 UTC, KianNH commented on content/workers/wrangler/commands.md
> +- `--name`{{<type>}}string{{</type>}} {{<prop-meta>}}optional{{</prop-meta>}}
```suggestion
- `--name` {{<type>}}string{{</type>}} {{<prop-meta>}}optional{{</prop-meta>}}
```

2023-02-08 16:26 UTC, deadlypants1973 commented on content/workers/wrangler/configuration.md
> +To bind an mTLS certificate to your Worker, assign an array of objects with the following shape to the `mtls_certificates` key.
Is this also talking about creating a binding?

2023-02-08 16:27 UTC, deadlypants1973 commented on content/workers/wrangler/configuration.md
> +Example:
This needs full sentences explaining what this is an example of.

2023-02-10 16:38 UTC, matthewdavidrodgers commented on content/workers/wrangler/configuration.md
> +To bind an mTLS certificate to your Worker, assign an array of objects with the following shape to the `mtls_certificates` key.
updated to be more explicit about creating a binding

2023-02-10 16:39 UTC, matthewdavidrodgers commented on content/workers/wrangler/configuration.md
> +Example:
updated example description

2023-02-10 18:27 UTC, deadlypants1973 approved these changes

2023-02-10 18:27 UTC, deadlypants1973 commented on content/workers/platform/bindings/_index.md
> +* Configure mTLS certificate bindings via your [`wrangler.toml` file](/workers/wrangler/configuration/#mtls-certificates)
```suggestion
mTLS certificate bindings enable Worker subrequests to present a client certificate when communicating with a service that requires client authentication.

* Learn more about [mTLS certificate bindings](/workers/runtime-apis/mtls/).
* Configure mTLS certificate bindings via your [`wrangler.toml` file](/workers/wrangler/configuration/#mtls-certificates).
```

2023-02-10 18:27 UTC, deadlypants1973 commented on content/workers/runtime-apis/mTLS.md
> +```toml
```suggestion
```toml
---
header: wrangler.toml
---
```

2023-02-10 18:27 UTC, deadlypants1973 commented on content/workers/runtime-apis/mTLS.md
> +Update your `wrangler.toml` to create a binding to the certificate:
```suggestion
Then, update your  Worker project's `wrangler.toml` file to create a binding to the certificate:
```

2023-02-10 18:27 UTC, deadlypants1973 commented on content/workers/wrangler/configuration.md
> +Example of a wrangler.toml configuration that includes an mTLS certificate binding:
```suggestion
Example of a `wrangler.toml` configuration that includes an mTLS certificate binding:
```

2023-02-10 18:28 UTC, deadlypants1973 commented on content/workers/learning/using-services/index.md
> +6. [mTLS certificate bindings](/workers/runtime-apis/mtls) for using an uploaded certificate when communicating with an origin secured by mTLS
```suggestion
6. [mTLS certificate bindings](/workers/runtime-apis/mtls) for using an uploaded certificate when communicating with an origin secured by mTLS.
```

@matthewdavidrodgers see comment left in Google chat for full phrasing on this. Added a period at the end of the sentence as well.

2023-02-13 17:12 UTC, merged