Update firewall use cases pcx 1275
cloudflare/cloudflare-docs pull request #738
Opened 2021-02-04 14:50 UTC by kodster28

Addresses [PCX-1275](https://jira.cfops.it/browse/PCX-1275).

@bensol1998, here's a screenshot of the output so you don't have to download and run yourself.

![image](https://user-images.githubusercontent.com/26727299/106909526-fe8a5080-66c5-11eb-999a-96cade5436e0.png)

2021-02-04 19:00 UTC, bensol1998 commented
Two things I think we should change before publishing:

1. Bot Management banner should say Enterprise plan _with Bot Management_
2. Can you remove the first "potential example" at the top of the page? Not sure internal systems should be protected this way

2021-02-04 19:01 UTC, bensol1998 requested changes
Two things I think we should change before publishing:

Bot Management banner should say Enterprise plan with Bot Management
Can you remove the first "potential example" at the top of the page? Not sure internal systems should be protected this way

2021-02-04 20:55 UTC, stumblefiend approved these changes

2021-02-05 18:19 UTC, bensol1998 approved these changes

2021-02-05 18:20 UTC, merged