Fix and improve pages Hono guide
cloudflare/cloudflare-docs pull request #7410
Opened 2023-01-26 11:46 UTC by dario-piotrowicz

Improve the Hono guide by fixing present wrong statements, clarifying others, providing the option to use typescript as well as javascript and also renaming Honojs to Hono (since afaict that's the correct name)

2023-01-26 11:48 UTC, dario-piotrowicz commented
@yusukebe please give this PR a review if you want 🙂

2023-01-26 12:09 UTC, yusukebe commented
Thanks for looking out for Hono! I am glad.

I am just now thinking about the use of Hono on Pages. There is much more that is not covered in this document. In addition to transpiling to `_workers.js` as described here, it can be used as an API for SPAs in `/functions`. Also, we can use JSX middleware with Hono.

But, it is difficult to create new content that includes them right now. We will create another PR when the time comes. Looks good for this PR. Thanks!

2023-01-26 12:39 UTC, dario-piotrowicz commented
Thanks for the approval @yusukebe 😃 

regarding other stuff yeah I understand but if you look at the pages framework guides https://developers.cloudflare.com/pages/framework-guides/ you can see that they are all very minimalistic and just tell you basically how to get started with the various frameworks, so I don't think we should anyways include too much content there.

Maybe there is some other place in which we could provide more information? (and potentially linking to that place in the guide?) (I think that even a glob post in the Cloudflare blog would be pretty cool, I'd definitely like try to help out with that 🙂)

2023-01-26 12:53 UTC, yusukebe commented
Thanks for the advice. It's sure better not to write a lot of stuff.

> If you want to have a more descriptive document showcasing various cool things that Hono can do maybe there is some other place in which we could provide that?

Yes, we are planning to renew the website of Hono ( https://honojs.dev ) when releasing the next major version. It's appropriate there.

> I think that even a blog post in the Cloudflare blog would be pretty cool, I'd definitely like try to help out with that

Wow, that's super cool! No, ultra cool!

2023-01-26 14:52 UTC, deadlypants1973 requested changes

2023-01-26 14:52 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-hono-site.md
> +If you want your application to use typescript we need to generate a `tsconfig.json` file, to do so run:
```suggestion
If you want your application to use TypeScript, you need to generate a `tsconfig.json` file. To generate a `tsconfig.json` file:
```

2023-01-26 14:52 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-hono-site.md
> +Open your project and create a `src/server.js` file (or `src/server.ts` if you're using typescript). Add the following content to your file:
```suggestion
Open your project and create a `src/server.js` file (or `src/server.ts` if you are using TypeScript). Add the following content to your file:
```

2023-01-26 14:52 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-hono-site.md
> +If you want to serve static files like CSS, image or JavaScript files, you will need to add the following to your `src/server.js/ts` file:
```suggestion
To serve static files like CSS, image or JavaScript files, add the following to your `src/server.js/ts` file:
```

2023-01-26 14:52 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-hono-site.md
> +```javascript
```suggestion
```javascript
---
filename: src/server.js/ts
---
```

2023-01-26 14:52 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-hono-site.md
> +The `dist` directory is created and used during the bundling process, you'll need to create a `public` directory there. Having `public` inside `dist` is not generally wanted as `dist` isn't a directo
```suggestion
The `dist` directory is created and used during the bundling process. You will need to create a `public` directory in the `dist` directory. Having `public` inside `dist` is not generally wanted as `dist` is not a directory to commit to your repository whilst `public` is.
```

2023-01-26 14:52 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-hono-site.md
> +There are different alternatives to fix such issue, for example you can configure your `.gitignore` file to include the `dist` directory, but ignore all its context except the `public` directory. Alt
```suggestion
There are different alternatives to fix this issue. For example, you can configure your `.gitignore` file to include the `dist` directory, but ignore all its context except the `public` directory. Alternatively, you can create a `public` directory somewhere else and copy it inside `dist` as part of the bundling process.
```

2023-01-26 14:52 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-hono-site.md
> +Here `npm-run-all` enables you to use a single command `npm run dev` to run `npm run dev:wrangler` and `npm run dev:esbuild` together simultaneously in watch mode.
```suggestion
Here `npm-run-all` enables you to use a single command `npm run dev` to run `npm run dev:wrangler` and `npm run dev:esbuild` simultaneously in watch mode.
```

2023-01-26 18:09 UTC, dario-piotrowicz commented on content/pages/framework-guides/deploy-a-hono-site.md
> +```javascript
mh.... would be an overkill to add tabs for js and ts here? .js/ts doesn't sit well with me 😖

2023-01-26 18:16 UTC, dario-piotrowicz commented
@deadlypants1973 Thanks so very much for the awesome reviewing 🙂 (and sorry about the silly mistakes 😅)

I've accepted all your suggestions 🙂👍

2023-01-27 04:02 UTC, yudai-nkt commented
Hi, I'd like to add my thoughts on @yusukebe's proposal here. Regarding the JSX middlware, it sounds to me a non-fundamental topic to be covered in Cloudflare's domain. On the other hand, what is referred to "as an API for SPAs in `/functions`" could be covered IMHO.

Adapters, which were proposed in honojs/hono#802 and implemented in honojs/hono#807, make it way easier to integrate Hono into Pages like this:

```js
import { Hono } from "hono";
import { handle } from "hono/cloudflare-pages";

const app = new Hono();

// implement requests handling here

export const onRequest = handle(app);
```

Since this feature is not in stable releases now (only in v3 RC), we need to consider when to ship a document describing adapters but it would definitely be a nice-to-have!

2023-01-27 22:26 UTC, dario-piotrowicz commented on content/pages/framework-guides/deploy-a-hono-site.md
> +$ git push -u origin main
```suggestion
$ git init
$ git remote add origin https://github.com/<username>/my-hono-app
$ git add .
$ git commit -m "Initial commit"
$ git branch -M main
$ git push -u origin main
```

2023-02-08 16:11 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-hono-site.md
> +If you want your application to use TypeScript, you need to generate a `tsconfig.json` file. To generate a `tsconfig.json` file:
```suggestion
If you want your application to use TypeScript, you need to generate a `tsconfig.json` file. To generate a `tsconfig.json` file, run:
```

2023-02-08 16:11 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-hono-site.md
> +Here `npm-run-all` enables you to use a single command `npm run dev` to run `npm run dev:wrangler` and `npm run dev:esbuild` simultaneously in watch mode.
```suggestion
In the above example, `npm-run-all` enables you to use a single command (`npm run dev`) to run `npm run dev:wrangler` and `npm run dev:esbuild` simultaneously in watch mode.
```

2023-02-10 12:07 UTC, deadlypants1973 approved these changes

2023-02-10 17:37 UTC, merged