improve svelte pages guide
cloudflare/cloudflare-docs pull request #7437
Opened 2023-01-27 17:55 UTC by dario-piotrowicz

by:
 - correctly outdated infomation
 - clarify ambibuous workings
 - shortening the document but not going into details regarding the other adaptors but keeping focus only on the cloudflare one

2023-01-27 22:04 UTC, dario-piotrowicz commented on content/pages/framework-guides/deploy-a-svelte-site.md
> +In order to use SvelteKit with Cloudflare pages you'll need to add the [Cloudflare adapter](https://kit.svelte.dev/docs/adapter-cloudflare) to your application, to do so:
```suggestion
In order to use SvelteKit with Cloudflare Pages you'll need to add the [Cloudflare adapter](https://kit.svelte.dev/docs/adapter-cloudflare) to your application, to do so:
```

2023-01-27 22:05 UTC, dario-piotrowicz commented on content/pages/framework-guides/deploy-a-svelte-site.md
> +### SvelteKit Cloudflare Configuration
```suggestion
## SvelteKit Cloudflare Configuration
```

2023-02-07 17:46 UTC, deadlypants1973 requested changes

2023-02-07 17:46 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-svelte-site.md
> +For more information about SvelteKit API Routes, see the [SvelteKit docs](https://kit.svelte.dev/docs/routing#server).
```suggestion
For more information about SvelteKit API Routes, refer to the [SvelteKit documentation](https://kit.svelte.dev/docs/routing#server).
```

2023-02-07 17:46 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-svelte-site.md
> +During `init`, SvelteKit will prompt you for customization choices. For the template option choose one of the application/project ones, the remaining answers will not affect the rest of this tutorial
```suggestion
During `init`, SvelteKit will prompt you for customization choices. For the template option, choose one of the application/project options. The remaining answers will not affect the rest of this tutorial. Choose the options that better suit your project.
```

2023-02-07 17:46 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-svelte-site.md
> +Next move to the directory of the project and install its dependencies:
```suggestion
After creating your project, go to your project directory and install its dependencies:
```

2023-02-07 17:46 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-svelte-site.md
> +You can now start your application with:
```suggestion
After you have installed your project dependencies, start your application:
```

2023-02-07 17:46 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-svelte-site.md
> +## SvelteKit Cloudflare Configuration
```suggestion
## SvelteKit Cloudflare configuration
```

2023-02-07 17:46 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-svelte-site.md
> +In order to use SvelteKit with Cloudflare Pages you'll need to add the [Cloudflare adapter](https://kit.svelte.dev/docs/adapter-cloudflare) to your application, to do so:
```suggestion
To use SvelteKit with Cloudflare Pages, you need to add the [Cloudflare adapter](https://kit.svelte.dev/docs/adapter-cloudflare) to your application:
```

2023-02-07 17:46 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-svelte-site.md
> +3. (Needed if you're using Typescript) Include support for environment variables. The `env` object, containing KV namespaces and other storage objects, is passed to SvelteKit via the platform propert
```suggestion
3. (Needed if you are using Typescript) Include support for environment variables. The `env` object, containing KV namespaces and other storage objects, is passed to SvelteKit via the platform property along with context and caches, meaning you can access it in hooks and endpoints. For example:
```
Are property, context and caches code elements? If so, they need to be in ``

2023-02-07 17:46 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-svelte-site.md
> +Besides the Cloudflare adapter there are other adapters that you can use in your project:
```suggestion
In addition to the Cloudflare adapter, review other adapters you can use in your project:
```

2023-02-07 17:46 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-svelte-site.md
> +## Deploying with Cloudflare Pages
```suggestion
## Deploy with Cloudflare Pages
```

2023-02-07 17:46 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-svelte-site.md
> +  platform the application is going to be deployed to. To solve such issue in you need to provide a `CF_PAGES` variable to SvelteKit so that the adapter can detect the Pages platform, for example whe
The first sentence here seems incomplete? Can you please recheck? :)

2023-02-07 17:46 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-svelte-site.md
> +You will be asked to authorize access to your GitHub account if you have not already done so. Cloudflare needs this so that it can monitor and deploy your projects from the source. You may narrow acc
```suggestion
You will be asked to authorize access to your GitHub account if you have not already done so. Cloudflare needs this  authorization to deploy your projects from your GitHub account. You may narrow Cloudflare's access to specific repositories. However, you will have to manually update this list [within your GitHub settings](https://github.com/settings/installations) when you want to add more repositories to Cloudflare Pages.
```

2023-02-07 17:46 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-svelte-site.md
> +Select the new GitHub repository that you created and, in the **Set up builds and deployments** section, provide the following information:
```suggestion
Select the new GitHub repository that you created and, in **Set up builds and deployments**, provide the following information:
```

2023-02-07 17:46 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-svelte-site.md
> +So in order to have the functionality equivalent to [Pages Functions onRequests](https://developers.cloudflare.com/pages/platform/functions/api-reference/#onrequests), you just need to write standard
```suggestion
To have the functionality equivalent to Pages Functions [`onRequests`](https://developers.cloudflare.com/pages/platform/functions/api-reference/#onrequests), you need to write standard request handlers in SvelteKit. For example, the following TypeScript file behaves like an `onRequestGet`:
```

2023-02-07 17:46 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-svelte-site.md
> +So in order to have the functionality equivalent to [Pages Functions onRequests](https://developers.cloudflare.com/pages/platform/functions/api-reference/#onrequests), you just need to write standard
What is the thing that they are making equivalent to `onRequests` in the beginning of the sentence?

2023-02-07 17:59 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-svelte-site.md
> +  platform the application is going to be deployed to. To solve such issue in you need to provide a `CF_PAGES` variable to SvelteKit so that the adapter can detect the Pages platform, for example whe
Also, is it for sure "adapter"? You GitHub PR description made me do a double take.

2023-02-07 22:53 UTC, dario-piotrowicz commented on content/pages/framework-guides/deploy-a-svelte-site.md
> +So in order to have the functionality equivalent to [Pages Functions onRequests](https://developers.cloudflare.com/pages/platform/functions/api-reference/#onrequests), you just need to write standard
Basically in SvelteKit you can't use Pages Functions so you instead write request handlers that basically implement the same functionality as Functions

2023-02-07 22:53 UTC, dario-piotrowicz commented on content/pages/framework-guides/deploy-a-svelte-site.md
> +  platform the application is going to be deployed to. To solve such issue in you need to provide a `CF_PAGES` variable to SvelteKit so that the adapter can detect the Pages platform, for example whe
> The first sentence here seems incomplete? Can you please recheck? :)
sorry it's a single sentence I added a newline by mistake 😅

2023-02-07 22:56 UTC, dario-piotrowicz commented on content/pages/framework-guides/deploy-a-svelte-site.md
> +  platform the application is going to be deployed to. To solve such issue in you need to provide a `CF_PAGES` variable to SvelteKit so that the adapter can detect the Pages platform, for example whe
> Also, is it for sure "adapter"? You GitHub PR description made me do a double take.

Yes it's adapter as you can see here: https://kit.svelte.dev/docs/adapters
sorry I get confused because some framework call them adapters and others adaptors (like [Qwik](https://qwik.builder.io/integrations/deployments/cloudflare-pages/#cloudflare-pages-adaptor) for example 🙈) 😅

Let me update the description and the commit message 🙂👍

2023-02-10 13:59 UTC, deadlypants1973 approved these changes
Approved with comment

2023-02-10 13:59 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-svelte-site.md
> +  SvelteKit's default adapter, which automatically chooses the adapter for your current environment (if you use this adapter [no configuration is needed](https://kit.svelte.dev/docs/adapter-auto)), i
```suggestion
  SvelteKit's default adapter  automatically chooses the adapter for your current environment. If you use this adapter, [no configuration is needed](https://kit.svelte.dev/docs/adapter-auto). However, the default adapter introduces a few disadvantages for local development because it has no way of knowing what platform the application is going to be deployed to. 

To solve this issue, provide a `CF_PAGES` variable to SvelteKit so that the adapter can detect the Pages platform. For example, when locally building the application: `CF_PAGES=1 vite build`.
```

2023-02-10 13:59 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-svelte-site.md
> +  SvelteKit's default adapter, which automatically chooses the adapter for your current environment (if you use this adapter [no configuration is needed](https://kit.svelte.dev/docs/adapter-auto)), i
The first sentence seemed a bit incomplete so I restructured the paragraph. If I misunderstood or wrote incorrectly, feel free to change!

2023-02-10 13:59 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-svelte-site.md
> +  You can see how to set it up in the [official SvelteKit documentation](https://kit.svelte.dev/docs/adapter-static). Keep in mind that if you decide to use this adapter the build directory, instead
```suggestion
  Review the [official SvelteKit documentation](https://kit.svelte.dev/docs/adapter-static) for instructions on how to set up the adapter. Keep in mind that if you decide to use this adapter, the build directory, instead of `.svelte-kit/cloudflare`, becomes `.build`. You must also configure your Cloudflare Pages application's build directory accordingly.
```

2023-02-10 13:59 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-svelte-site.md
> +  You can see how to set it up in the [official SvelteKit documentation](https://kit.svelte.dev/docs/adapter-static). Keep in mind that if you decide to use this adapter the build directory, instead
How are they configuring this? Is it by declaring the build directory during set up?

2023-02-10 13:59 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-svelte-site.md
> +**Important:** If you're using any adapter different from auto, remember to commit and push your adapter setting changes to your GitHub repository before attempting the deployment.
```suggestion
{{<Aside type="warning">}}

If you are using any adapter different from the default SvelteKit adapter, remember to commit and push your adapter setting changes to your GitHub repository before attempting the deployment.

{{</Aside>}}
```

2023-02-10 13:59 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-svelte-site.md
> +**Important:** If you're using any adapter different from auto, remember to commit and push your adapter setting changes to your GitHub repository before attempting the deployment.
Is "auto" the default adapter?

2023-02-10 17:32 UTC, merged