add solidStart pages framework guide
cloudflare/cloudflare-docs pull request #7442
Opened 2023-01-27 23:31 UTC by dario-piotrowicz

2023-02-07 18:06 UTC, deadlypants1973 requested changes

2023-02-07 18:06 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-solid.md
> +[Solid](https://www.solidjs.com/) is an open-source web application framework focused on generating very performant applications with a modern developer experience based on JSX.
```suggestion
[Solid](https://www.solidjs.com/) is an open-source web application framework focused on generating performant applications with a modern developer experience based on JSX.
```

2023-02-07 18:06 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-solid.md
> +At the time of writing SolidStart is in beta, this may cause things to change and make the following guide inaccurate. Please keep this in mind.
```suggestion
At the time of writing SolidStart is in beta, this may cause things to change and make the following guide inaccurate.
```

2023-02-07 18:06 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-solid.md
> +## Creating a new project
```suggestion
## Create a new project
```

2023-02-07 18:06 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-solid.md
> +You will be prompted to select a starter, you can choose any of the available options. Then you will be asked if you want to enable Server Side Rendering, reply yes. Finally you'll be asked if you wa
```suggestion
You will be prompted to select a starter. Choose any of the available options. You will then be asked if you want to enable Server Side Rendering. Reply `yes`. Finally, you will be asked if you want to use TypeScript, choose either `yes` or `no`.
```

2023-02-07 18:06 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-solid.md
> +You can then install the application's dependencies:
```suggestion
Then, install the application's dependencies:
```

2023-02-07 18:06 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-solid.md
> +And finally run the application:
```suggestion
After installing dependencies, run your application:
```

2023-02-07 18:06 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-solid.md
> +## SolidStart Cloudflare Configuration
```suggestion
## SolidStart Cloudflare configuration
```

2023-02-07 18:06 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-solid.md
> +In order to use SolidStart with Cloudflare Pages you'll add the [SolidStart Cloudflare Pages adapter](https://github.com/solidjs/solid-start/tree/main/packages/start-cloudflare-pages) to your applica
```suggestion
In order to use SolidStart with Cloudflare Pages, add the [SolidStart Cloudflare Pages adapter](https://github.com/solidjs/solid-start/tree/main/packages/start-cloudflare-pages) to your application:
```

2023-02-07 18:06 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-solid.md
> +Next you need to use the adapter in your the vite.config.(ts/js) file:
```suggestion
Next, use the adapter in your the `vite.config.(ts/js)` file:
```

2023-02-07 18:06 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-solid.md
> +## Creating a GitHub repository
```suggestion
## Create a GitHub repository
```

2023-02-07 18:06 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-solid.md
> +Deploy your site to Pages by logging in to the [Cloudflare dashboard](https://dash.cloudflare.com/) > **Account Home** > **Pages** and selecting **Create a project**. Select the new GitHub repository
```suggestion
Deploy your site to Pages by logging in to the [Cloudflare dashboard](https://dash.cloudflare.com/) > **Account Home** > **Pages** and selecting **Create a project**. Select the new GitHub repository that you created and, in **Set up builds and deployments**, provide the following information:
```

2023-02-07 18:06 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-solid.md
> +## Using bindings in your Solid application
```suggestion
## Use bindings in your Solid application
```

2023-02-07 18:06 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-solid.md
> +To add a binding in your SolidStart, let's start by adding them to the Cloudflare adapter, this allows you to conveniently access those during development, allowing you to test your application befor
```suggestion
To add a binding in your SolidStart, add the binding to the Cloudflare adapter. This allows you to access your bindings during development, and test your application before deploying it.
```

2023-02-07 18:06 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-solid.md
> +To add a binding in your SolidStart, let's start by adding them to the Cloudflare adapter, this allows you to conveniently access those during development, allowing you to test your application befor
Are they added to the CF adapter by updating the `vite.config` file?

2023-02-07 18:06 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-solid.md
> +Let's supposed that you want to create a new binding for a KV named "MY_KV", update the adapter's use in your the vite.config.(ts/js) file, for example in the following way:
```suggestion
The following example configuration supposes you are using a KV namespace binding named `"MY_KV"`. You will need to update the adapter's use in your `vite.config.(ts/js)` file in the following way:
```

2023-02-07 18:06 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-solid.md
> +In your code you can then access the binding in the environment variable provided to you by SolidStart, for example in a [createServerData$](https://start.solidjs.com/api/createServerData) loader:
```suggestion
You can then access the binding in the environment variable provided to you by SolidStart. For example, in a [`createServerData$`](https://start.solidjs.com/api/createServerData) loader:
```

2023-02-07 18:06 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-solid.md
> +In your code you can then access the binding in the environment variable provided to you by SolidStart, for example in a [createServerData$](https://start.solidjs.com/api/createServerData) loader:
Is the $ intentional?

2023-02-07 18:06 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-solid.md
> +The Cloudflare adapter accepts the same options [Miniflare](https://miniflare.dev/) does, you can see a reference of the various available options in this [Miniflare API Reference](https://miniflare.
```suggestion
The Cloudflare adapter accepts the same options as [Miniflare](https://miniflare.dev/). Review the available options in this [Miniflare API Reference](https://miniflare.dev/get-started/api#reference).
```

2023-02-08 08:56 UTC, dario-piotrowicz commented on content/pages/framework-guides/deploy-a-solid.md
> +To add a binding in your SolidStart, let's start by adding them to the Cloudflare adapter, this allows you to conveniently access those during development, allowing you to test your application befor
yes, as you can see below with the MY_KV one 🙂

2023-02-08 08:58 UTC, dario-piotrowicz commented on content/pages/framework-guides/deploy-a-solid.md
> +In your code you can then access the binding in the environment variable provided to you by SolidStart, for example in a [createServerData$](https://start.solidjs.com/api/createServerData) loader:
yes, it's intentional, as you can see if you follow the link 🙂 

[
![Screenshot 2023-02-08 at 08 57 26](https://user-images.githubusercontent.com/61631103/217482443-556adf75-1901-4197-a9e3-4e8befed358b.png)
](https://start.solidjs.com/api/createServerData)

2023-02-10 13:50 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-solid.md
> +At the time of writing SolidStart is in beta, this may cause things to change and make the following guide inaccurate.
```suggestion
At the time of writing SolidStart is in beta, this may make the following guide inaccurate in the event of a breaking change.
```

2023-02-10 13:51 UTC, deadlypants1973 approved these changes

2023-02-10 13:51 UTC, deadlypants1973 commented on content/pages/framework-guides/deploy-a-solid.md
> +Create a new project by running the following command in your terminal:
```suggestion
Create a new project (`my-solid-app`) by running the following command in your terminal:
```

2023-02-10 17:32 UTC, merged