[Wrangler] Rollbacks & Views
cloudflare/cloudflare-docs pull request #7492
Opened 2023-01-31 18:36 UTC by JacobMGEvans

Adding general documentation for rollbacks & view on deployments. Including Rollbacks to deployments platform page.

_DEVX-285 & DEVX-284_
related https://github.com/cloudflare/wrangler2/pull/2607

2023-01-31 20:24 UTC, lrapoport-cf commented on content/workers/wrangler/commands.md
> +wrangler deployments view y565f193-a6b9-4c7f-91ae-4b4e6d98ftbf
```suggestion
$ wrangler deployments view <DEPLOYMENT_ID>
```

2023-01-31 20:26 UTC, lrapoport-cf commented on content/workers/wrangler/commands.md
> +### view <deployment-id>
this anchor appears to resolve to `/#view-deployment-id` -- is that intentional?

2023-01-31 20:29 UTC, lrapoport-cf commented on content/workers/wrangler/commands.md
> +### rollback <deployment-id>
similar to above, this anchor resolves to `/#rollback-deployment-id`. to be consistent with other anchors, we probably want as just `/#rollback`

2023-01-31 20:30 UTC, lrapoport-cf commented on content/workers/wrangler/commands.md
> +Retrieve details for the 10 most recent deployments. Details include Deployment ID, Author, Source, Created on, and indicates which deployment is Active.
i think this may be a copy/paste issue -- i believe the view command only shows details for the specified deployment

2023-02-14 16:16 UTC, JacobMGEvans commented on content/workers/wrangler/commands.md
> +wrangler deployments view y565f193-a6b9-4c7f-91ae-4b4e6d98ftbf
I am fine with this, however I have also previously been told to use more realistic examples.

2023-02-14 16:17 UTC, JacobMGEvans commented on content/workers/wrangler/commands.md
> +### view <deployment-id>
I dont understand?

2023-02-14 16:17 UTC, JacobMGEvans commented on content/workers/wrangler/commands.md
> +### rollback <deployment-id>
Not sure what you mean, as above.

2023-02-14 16:17 UTC, JacobMGEvans commented on content/workers/wrangler/commands.md
> +### rollback <deployment-id>
Not sure what you mean, as above.

2023-02-14 16:23 UTC, lrapoport-cf commented on content/workers/wrangler/commands.md
> +### view <deployment-id>
i just meant the url will resolve to https://developers.cloudflare.com/workers/wrangler/commands/#view-deployment-id instead of e.g. https://developers.cloudflare.com/workers/wrangler/commands/#view and didn't know if that was intentional

2023-02-14 16:26 UTC, lrapoport-cf commented on content/workers/wrangler/commands.md
> +Retrieve details for the 10 most recent deployments. Details include Deployment ID, Author, Source, Created on, and indicates which deployment is Active.
doesn't the view command only show detail for one deployment? that is, the description you added says it retrieves details for 10 deployments, but i believe this command only shows the details for a single one, as in the example you provided:

![image](https://user-images.githubusercontent.com/107272160/218797547-8c618a96-88fe-498b-b9fc-88a96636aaed.png)

2023-02-14 16:35 UTC, JacobMGEvans commented on content/workers/wrangler/commands.md
> +### view <deployment-id>
Yes, the <deployment-id> is part of the sub header.

2023-02-14 16:37 UTC, JacobMGEvans commented on content/workers/wrangler/commands.md
> +Retrieve details for the 10 most recent deployments. Details include Deployment ID, Author, Source, Created on, and indicates which deployment is Active.
Yes, that is incorrect. It should just be "for the most recent deployment"

2023-02-14 17:24 UTC, JacobMGEvans commented on content/workers/platform/deployments.md
> +being rolled back onto, in which the deployed code would handle the resource data erroneously.
Pending.

2023-02-16 23:52 UTC, jspspike commented on content/workers/platform/deployments.md
> +being rolled back onto, in which the deployed code would handle the resource data erroneously.
* A durable object migration has occurred between latest deployment and target deployment
* If the target deployment has a binding to an R2 bucket, KV namespace, or Queue that no longer exists
* Currently if the target deployment has a binding to a D1 database, this will be removed in the future

2023-03-01 20:11 UTC, admah requested changes
Thanks for writing these up. I had some suggestions to review.

2023-03-01 20:11 UTC, admah commented on content/workers/platform/deployments.md
> +Associated resources for a worker such as KV, R2, Durable Objects etc. will not be tracked with deployments.
```suggestion
Associated resources for a worker such as KV, R2, and Durable Objects are not tracked with deployments.
```

2023-03-01 20:11 UTC, admah commented on content/workers/platform/deployments.md
> +The latest deployment for a Worker is considered the "active deployment". [You can view your latest 10 deployments via the cloudflare dashboard or the `wrangler deployments` command.](#Interacting-wi
```suggestion
The latest deployment for a Worker is considered the "active deployment". You can view your latest 10 deployments [via the Cloudflare dashboard](#via-the-cloudflare-dashboard) or the [`wrangler deployments` command](#via-wrangler).
```

2023-03-01 20:11 UTC, admah commented on content/workers/platform/deployments.md
> +New Deployments will be created whenever an upload, binding change (including environment variables and secrets), usage model change, or [rollback](#rollbacks) is made. These can be done via the Clou
```suggestion
New Deployments are created whenever an upload, binding change (including environment variables and secrets), usage model change, or [rollback](#rollbacks) is made. These can be done via the Cloudflare Dashboard, [Workers API](/api), or [`wrangler publish` command](/workers/wrangler/commands#publish).
```

2023-03-01 20:11 UTC, admah commented on content/workers/platform/deployments.md
> +Notably, this does not include changes to bound resources. For example if two workers (Worker A and Worker B) are bound via a service binding, changing the code of a Worker B will not trigger a new d
```suggestion
Notably, this does not include changes to bound resources. For example, if two workers (Worker A and Worker B) are bound via a service binding, changing the code of a Worker B will not trigger a new deployment on Worker A. Changes to the service binding on Worker A will also not trigger a new deployment for Worker B.
```

2023-03-01 20:11 UTC, admah commented on content/workers/platform/deployments.md
> +
```suggestion

There are currently two ways to perform a rollback: via Wrangler or via the Cloudflare Dashboard.
```

2023-03-01 20:11 UTC, admah commented on content/workers/platform/deployments.md
> +You can rollback in wrangler using the `wrangler deployments rollback` command, you can learn about it [here](/workers/wrangler/commands#rollback).
```suggestion
You can rollback in Wrangler using the `wrangler deployments rollback` command detailed [here](/workers/wrangler/commands#rollback).
```

2023-03-01 20:11 UTC, admah commented on content/workers/platform/deployments.md
> +In the deployements tab under your Worker you can select the menu dropdown on the right of the deployment and select **`Rollback to this deployment`**.
```suggestion
In the Dashboard, find the deployments tab under your Worker. From there, you can select the menu dropdown on the right of the deployment and select **`Rollback to this deployment`**.
```

2023-03-01 20:11 UTC, admah commented on content/workers/platform/deployments.md
> +Rollbacks are only valid to the latest 10 deployments. Further rollbacks will be invalid if external resources have been deleted or modified between the target deployment and the active deployment. S
```suggestion
## Limitations

Rollbacks are only valid to the latest 10 deployments. 

Rollbacks will not be allowed if external resources have been deleted or modified between the target deployment and the active deployment. Specifically if:
```

2023-03-04 09:49 UTC, deadlypants1973 approved these changes
Approved with style guide suggestions and 1 question for @admah :)

2023-03-04 09:49 UTC, deadlypants1973 commented on content/workers/platform/deployments.md
> +Deployments are currently in Public Beta and subcommands are currently in Beta. Please report Deployments bugs to the [Wrangler team](https://github.com/cloudflare/wrangler2/issues/new/choose).
```suggestion
Deployments are currently in Public Beta and subcommands are currently in Beta. Report Deployments bugs to the [Wrangler team](https://github.com/cloudflare/wrangler2/issues/new/choose).
```

2023-03-04 09:49 UTC, deadlypants1973 commented on content/workers/platform/deployments.md
> +The latest deployment for a Worker is considered the "active deployment". You can view your latest 10 deployments [via the Cloudflare dashboard](#via-the-cloudflare-dashboard) or the [`wrangler deplo
@admah Are we leaving deployments in lower case or upper case? We seem to be using both. I think from our last conversation we said lower case but please confirm :)

2023-03-04 09:49 UTC, deadlypants1973 commented on content/workers/platform/deployments.md
> +New Deployments are created whenever an upload, binding change (including environment variables and secrets), usage model change, or [rollback](#rollbacks) is made. These can be done via the Cloudfla
```suggestion
New deployments are created whenever an upload, binding change (including environment variables and secrets), usage model change, or [rollback](#rollbacks) is made. These can be done via the Cloudflare dashboard, [Workers API](/api), or [`wrangler publish` command](/workers/wrangler/commands#publish).
```

2023-03-04 09:49 UTC, deadlypants1973 commented on content/workers/platform/deployments.md
>  ## Creating a new Deployment
```suggestion
## Creating a new deployment
```

2023-03-04 09:49 UTC, deadlypants1973 commented on content/workers/platform/deployments.md
> +Notably, this does not include changes to bound resources. For example, if two workers (Worker A and Worker B) are bound via a service binding, changing the code of a Worker B will not trigger a new
```suggestion
Notably, this does not include changes to bound resources. For example, if two Workers (Worker A and Worker B) are bound via a service binding, changing the code of a Worker B will not trigger a new deployment on Worker A. Changes to the service binding on Worker A will also not trigger a new deployment for Worker B.
```

2023-03-04 09:49 UTC, deadlypants1973 commented on content/workers/platform/deployments.md
>  Rollbacks are a way to quickly deploy an older deployment to the edge. This could be useful if a breaking change or unintended publish is made to a production Worker.
```suggestion

Rollbacks are a way to quickly deploy an older deployment to the Cloudflare global network. This could be useful if a breaking change or unintended publish is made to a production Worker.
```

2023-03-04 09:49 UTC, deadlypants1973 commented on content/workers/platform/deployments.md
>  Rollbacks are a way to quickly deploy an older deployment to the edge. This could be useful if a breaking change or unintended publish is made to a production Worker.
`Edge` should now be replaced by `global network` in docs.

2023-03-04 09:49 UTC, deadlypants1973 commented on content/workers/platform/deployments.md
> +There are currently two ways to perform a rollback: via Wrangler or via the Cloudflare Dashboard.
```suggestion
Perform a rollback via:

1. [Wrangler](/workers/platform/deployments/#via-wrangler-1).
2. The [Cloudflare dashboard](/workers/platform/deployments/#via-the-cloudflare-dashboard-1).
```

2023-03-04 09:49 UTC, deadlypants1973 commented on content/workers/platform/deployments.md
> +You can rollback in Wrangler using the `wrangler deployments rollback` command detailed [here](/workers/wrangler/commands#rollback).
```suggestion
To perform a rollback via Wrangler, use the `wrangler deployments rollback` command. Refer to [Wrangler `rollback` command documentation](/workers/wrangler/commands#rollback) for more information.
```

2023-03-04 09:49 UTC, deadlypants1973 commented on content/workers/platform/deployments.md
> +In the Dashboard, find the deployments tab under your Worker. From there, you can select the menu dropdown on the right of the deployment and select **`Rollback to this deployment`**.
```suggestion
To perform a rollback via the Cloudflare dashboard:

1. Log in to the [Cloudflare dashboard](https://dash.cloudflare.com) and select your account.
2. Go to **Workers** > select your Worker > **Deployments**. 
3. Find the deployment you would like to rollback to.
4. Select the three dot icon on the right of the deployment and select **Rollback to this deployment**.
```

2023-03-04 09:49 UTC, deadlypants1973 commented on content/workers/platform/deployments.md
> +Rollbacks are only valid to the latest 10 deployments.
```suggestion
## Limitations

Rollbacks are only valid to the latest 10 deployments. 
```

2023-03-04 09:49 UTC, deadlypants1973 commented on content/workers/wrangler/commands.md
> +Rollback to a specific deployment by ID. If an ID is not speicified, wrangler will rollback to the previous deployment. There are limitations on what deployments you can rollback to which you can rea
```suggestion
Rollback to a specific deployment by ID. If an ID is not speicified, wrangler will rollback to the previous deployment. There are limitations on what deployments you can rollback to. Refer to [Rollbacks in the Deployments documentation](/workers/platform/deployments#rollbacks) for more information.
```

2023-03-04 09:49 UTC, deadlypants1973 commented on content/workers/platform/deployments.md
> +Rollbacks will not be allowed if external resources have been deleted or modified between the target deployment and the active deployment. Specifically if:
```suggestion
Rollbacks will not be allowed if external resources have been deleted or modified between the target deployment and the active deployment. Specifically, rollbacks will not be allowed if:
```

2023-03-04 09:49 UTC, deadlypants1973 commented on content/workers/platform/deployments.md
>  - If the target deployment has a binding to an R2 bucket, KV namespace, or Queue that no longer exists.
```suggestion
- If the target deployment has a binding to an R2 bucket, KV namespace, or queue that no longer exists.
```

2023-03-08 17:21 UTC, deadlypants1973 approved these changes

2023-03-13 19:21 UTC, admah commented on content/workers/platform/deployments.md
> +The latest deployment for a Worker is considered the "active deployment". You can view your latest 10 deployments [via the Cloudflare dashboard](#via-the-cloudflare-dashboard) or the [`wrangler deplo
@deadlypants1973 let's keep it lower-case since it's not a product name.

2023-03-15 10:39 UTC, deadlypants1973 approved these changes

2023-03-15 10:39 UTC, deadlypants1973 commented on content/workers/platform/deployments.md
> +The latest deployment for a Worker is considered the "active deployment". You can view your latest 10 deployments [via the Cloudflare dashboard](#via-the-cloudflare-dashboard) or the [`wrangler deplo
```suggestion
The latest deployment for a Worker is considered the active deployment. You can view your latest 10 deployments [via the Cloudflare dashboard](#via-the-cloudflare-dashboard) or the [`wrangler deployments` command](#via-wrangler).
```
https://wiki.cfdata.org/display/Prod/Quotation+Marks

2023-03-15 10:39 UTC, deadlypants1973 commented on content/workers/platform/deployments.md
> +Associated resources for a worker such as KV, R2, and Durable Objects are not tracked with deployments.
```suggestion
Associated resources for a Worker such as [KV](/workers/wrangler/workers-kv/), [R2](/r2/), and [Durable Objects](/workers/learning/using-durable-objects/) are not tracked with deployments.
```

2023-03-15 10:39 UTC, deadlypants1973 commented on content/workers/platform/deployments.md
> +## Interacting with Deployments
```suggestion
## Interacting with deployments
```

2023-03-15 10:39 UTC, deadlypants1973 commented on content/workers/platform/deployments.md
> +More details about the `wrangler deployments` and `wrangler deployments view` command can be found [here](/workers/wrangler/commands#deployments).
```suggestion
For more information on the `wrangler deployments` and `wrangler deployments view` commands, refer to the [commands documentation](/workers/wrangler/commands#deployments).
```

2023-03-15 10:39 UTC, deadlypants1973 commented on content/workers/platform/deployments.md
> +- If the target deployment has a binding to a D1 database (this limitation will be removed in the future)
```suggestion
- If the target deployment has a binding to a D1 database (this limitation will be removed in the future).
```

2023-03-15 10:39 UTC, deadlypants1973 commented on content/workers/wrangler/commands.md
> +Deployments are currently in Public Beta and subcommands are currently in Beta. Please report Deployments bugs to the [Wrangler team](https://github.com/cloudflare/wrangler2/issues/new/choose).
```suggestion
Deployments are currently in Public Beta and subcommands are currently in Beta. Report deployments bugs to the [Wrangler team](https://github.com/cloudflare/wrangler2/issues/new/choose).
```

2023-03-15 10:39 UTC, deadlypants1973 commented on content/workers/wrangler/commands.md
> +You can read more about deployments and how they work [here](/workers/platform/deployments).
```suggestion
For more information about deployments and how they work, refer to [Deployments](/workers/platform/deployments).
```

2023-03-15 10:39 UTC, deadlypants1973 commented on content/workers/wrangler/commands.md
> +Retrieve details for the specified deployment. Details include Deployment ID, Author, Source, Created on, and bindings.
```suggestion
Retrieve details for the specified deployment. Details include `Deployment ID`, `Author`, `Source`, `Created on`, and bindings.
```

2023-03-15 10:39 UTC, deadlypants1973 commented on content/workers/wrangler/commands.md
> +Rollback to a specific deployment by ID. If an ID is not speicified, wrangler will rollback to the previous deployment. There are limitations on what deployments you can rollback to. Refer to [Rollba
```suggestion
Rollback to a specific deployment by ID. If an ID is not speicified, Wrangler will rollback to the previous deployment. There are limitations on what deployments you can rollback to. Refer to [Rollbacks in the Deployments documentation](/workers/platform/deployments#rollbacks) for more information.
```

2023-03-16 03:09 UTC, lrapoport-cf commented on content/workers/platform/deployments.md
> +The latest deployment for a Worker is considered the "active deployment". You can view your latest 10 deployments [via the Cloudflare dashboard](#via-the-cloudflare-dashboard) or the [`wrangler deplo
fixed :)

2023-03-16 03:14 UTC, lrapoport-cf commented on content/workers/platform/deployments.md
> +More details about the `wrangler deployments` and `wrangler deployments view` command can be found [here](/workers/wrangler/commands#deployments).
👍

2023-03-22 00:25 UTC, lrapoport-cf approved these changes

2023-03-22 00:31 UTC, merged