[SUPPORT] Adding new Support tile
cloudflare/cloudflare-docs pull request #7497
Opened 2023-02-01 00:11 UTC by jedecf

New Support Tile with owner

2023-02-01 17:59 UTC, kodster28 requested changes

2023-02-01 17:59 UTC, kodster28 commented on content/support/_index.md
> +After migration, we will be moving product-specific Knowledge Base content yo live within the Troubleshooting section of its relevant product area. Any content that spans multiple products, is relate
```suggestion
After migration, we will be moving product-specific Knowledge Base content to live within the Troubleshooting section of its relevant product area. Any content that spans multiple products, is related to Account and Billing, or is related to working with Support will remain in this section.
```

2023-02-01 17:59 UTC, kodster28 commented on content/support/_index.md
> +After migration, we will be moving product-specific Knowledge Base content yo live within the Troubleshooting section of its relevant product area. Any content that spans multiple products, is relate
I also don't know how true that statement is... I'd imagine we'd move Account/Billing stuff into https://developers.cloudflare.com/fundamentals/account-and-billing/ and similar thoughts with the content spanning multiple products.

2023-02-01 17:59 UTC, kodster28 commented on data/support.yml
> +  community: https://community.cloudflare.com/tags/c/reliability/7/none
```suggestion
```

2023-02-01 17:59 UTC, kodster28 commented on data/support.yml
> +  learning_center: https://www.cloudflare.com/learning/dns/what-is-dns/
```suggestion
```

2023-02-01 17:59 UTC, kodster28 commented on data/support.yml
> +  dashboard_link: https://dash.cloudflare.com/?to=/:account/:zone/dns
```suggestion
  dashboard_link: https://dash.cloudflare.com/?to=/:account/support
```

2023-02-01 23:45 UTC, jedecf commented on content/support/_index.md
> +After migration, we will be moving product-specific Knowledge Base content yo live within the Troubleshooting section of its relevant product area. Any content that spans multiple products, is relate
we could, for this tile placeholder deploy, noy have that whole paragraph at all.

2023-02-02 19:45 UTC, kodster28 approved these changes

2023-02-02 19:58 UTC, merged