NC-232: Document langauge parameter for Turnstile
cloudflare/cloudflare-docs pull request #7509
Opened 2023-02-01 13:48 UTC by worenga

2023-02-01 15:01 UTC, migueldemoura requested changes

2023-02-01 15:01 UTC, migueldemoura commented on content/turnstile/changelog.md
> +- Added the [`[data-]langauge`](/turnstile/get-started/client-side-rendering/#configurations) parameter.
```suggestion
- Added the [`[data-]language`](/turnstile/get-started/client-side-rendering/#configurations) parameter.
```

2023-02-01 15:01 UTC, migueldemoura commented on content/turnstile/get-started/client-side-rendering.md
> +| `langauge` | `data-langauge` | Language to display, must be either: `auto` (default) to use the language that the visitor has chosen, or an ISO 639-1 two-letter language code (e.g. `en`) or languag
```suggestion
| `language` | `data-language` | Language to display, must be either: `auto` (default) to use the language that the visitor has chosen, or an ISO 639-1 two-letter language code (e.g. `en`) or language and country code (e.g. `en-US`). The following languages are currently supported: `ar-eg`,`de`,`en`,`es`,`fa`,`fr`,`id`,`it`,`ja`,`ko`,`nl`,`pl`,`pt-br`,`ru`,`tr`,`zh-cn` and `zh-tw`.|
```

2023-02-02 09:18 UTC, patriciasantaana approved these changes

2023-02-02 11:16 UTC, migueldemoura approved these changes

2023-02-02 11:19 UTC, merged