Wrangler v1 deprecation
cloudflare/cloudflare-docs pull request #7556
Opened 2023-02-06 12:39 UTC by penalosa

For internal context, see https://jira.cfdata.org/browse/DEVX-80 and https://jira.cfdata.org/browse/DEVX-78.

This supersedes https://github.com/cloudflare/cloudflare-docs/pull/6934 and prepares the way for deprecating Wrangler v1 in favour of v2. Specifically:

- Restructures docs to add a new top level section in the workers docs under  which all v1/migration stuff goes (called "Wrangler (legacy)")
- Rename all references to Wrangler 1 or Wrangler 2 to Wrangler v1/Wrangler v2
- Change GitHub repository links from wrangler -> wrangler-legacy and wrangler2 -> workers-sdk (this rename will take place this week before merging this PR)
- Unify the deprecation messaging across Wrangler v1 docs pages

2023-02-06 14:22 UTC, rozenmd commented on content/d1/_index.md
> +If you are having issues with Wrangler, report issues in the [Wrangler GitHub repository](https://github.com/cloudflare/workers-sdk/issues/new/choose).
What's workers-sdk?

2023-02-06 14:41 UTC, penalosa commented on content/pages/migrations/migrating-from-workers/index.md
> +As a prerequisite, you should have a Cloudflare Workers Sites project, created with [Wrangler](https://github.com/cloudflare/wrangler-legacy).
Actually this should probably just be a link to v2

2023-02-06 15:31 UTC, penalosa commented
@mrbbot I've left the links from the tutorials the same, since I think they have wider issues that need addressing before updating to v2, but everything else should be good to go

2023-02-06 15:32 UTC, penalosa commented on content/d1/_index.md
> +If you are having issues with Wrangler, report issues in the [Wrangler GitHub repository](https://github.com/cloudflare/workers-sdk/issues/new/choose).
The new name for the Wrangler repo

2023-02-06 17:45 UTC, deadlypants1973 requested changes
When we published the Wrangler 2 docs, we agreed to go for a unified "Wrangler 2" wording on all things related to Wrangler 2 in the docs because that's what we called the product. We removed all "Wrangler v2/Wrangler V2/Wrangler Version 2/ Wrangler 2.0" from the docs. We did the same thing for "Wrangler 1". With this PR, I see that 'v1' and 'v2' wording has been added back. 

Other developer docs use "Wrangler 2" when talking about installation needs. Can we remove all inconsistencies and update wording to "Wrangler 2"? Or are we proceeding with "Wrangler v2" from this point forward?

2023-02-06 17:58 UTC, petebacondarwin commented
> When we published the Wrangler 2 docs, we agreed to go for a unified "Wrangler 2" wording on all things related to Wrangler 2 in the docs because that's what we called the product. We removed all "Wrangler v2/Wrangler V2/Wrangler Version 2/ Wrangler 2.0" from the docs. We did the same thing for "Wrangler 1". With this PR, I see that 'v1' and 'v2' wording has been added back.
> 
> Other developer docs use "Wrangler 2" when talking about installation needs. Can we remove all inconsistencies and update wording to "Wrangler 2"? Or are we proceeding with "Wrangler v2" from this point forward?

In the not too distant future we expect to release Wrangler 3.0.0 and then 4.0.0, etc.
The aim here is to avoid rebranding each version at each major version bump.
Therefore we should try to use just "Wrangler" wherever possible and then refer to vN when we need to call out something specific to a version.

2023-02-06 18:21 UTC, penalosa commented
I didn't want to add to the complexity of this PR by removing version qualifiers, but that's definitely something we want to do in the future. With the v1/v2 language we just wanted to make it clear that Wrangler 1 and 2 are both Wrangler, not too distinct things

2023-02-07 16:55 UTC, penalosa commented
@deadlypants1973 With that additional context, are there any further concerns with this PR?

2023-02-07 17:42 UTC, deadlypants1973 approved these changes

2023-02-07 17:42 UTC, deadlypants1973 commented
> > When we published the Wrangler 2 docs, we agreed to go for a unified "Wrangler 2" wording on all things related to Wrangler 2 in the docs because that's what we called the product. We removed all "Wrangler v2/Wrangler V2/Wrangler Version 2/ Wrangler 2.0" from the docs. We did the same thing for "Wrangler 1". With this PR, I see that 'v1' and 'v2' wording has been added back.
> > Other developer docs use "Wrangler 2" when talking about installation needs. Can we remove all inconsistencies and update wording to "Wrangler 2"? Or are we proceeding with "Wrangler v2" from this point forward?
> 
> In the not too distant future we expect to release Wrangler 3.0.0 and then 4.0.0, etc. The aim here is to avoid rebranding each version at each major version bump. Therefore we should try to use just "Wrangler" wherever possible and then refer to vN when we need to call out something specific to a version.

thank you! this makes sense. "we should try to use just "Wrangler" wherever possible and then refer to vN when we need to call out something specific to a version." I am going to stick to this logic in future docs.

2023-02-09 15:22 UTC, merged