revenue = total - shipping - tax - discounts
cloudflare/cloudflare-docs pull request #7611
Opened 2023-02-10 21:56 UTC by tomfuertes

Haven't double checked the component code as stated in this answer from Aug 2022 but would like for this to be updated/merged if correct since it's come up 3x in our recent implementation questions

https://community.cloudflare.com/t/clarification-between-subtotal-and-revenue/401443/4

2023-04-19 07:26 UTC, bjesus approved these changes

2023-04-20 14:12 UTC, haleycode approved these changes

2023-04-20 16:10 UTC, haleycode requested changes
Leaving a comment to see if it'll re-trigger checks.

2023-04-24 12:38 UTC, bjesus approved these changes

2023-04-24 13:30 UTC, pedrosousa approved these changes

2023-04-24 13:31 UTC, haleycode approved these changes

2023-04-24 13:32 UTC, merged