Revert "Update template urls (#7638)"
cloudflare/cloudflare-docs pull request #7728
Opened 2023-02-21 15:53 UTC by penalosa

This reverts #7638, which broke links for the Workers Quickstarts page, and in some tutorials.

Fixes https://github.com/cloudflare/workers-sdk/issues/2770

2023-02-21 15:59 UTC, lrapoport-cf commented
@penalosa i don't think all the links are broken? it may be just that some of the commands need to be fixed -- instead of reverting the whole thing, can we just fix the broken ones?

2023-02-21 20:24 UTC, penalosa commented
@lrapoport-cf I've reverted the revert (😂) for non-git/wrangler links—how does that look now?

2023-02-23 18:26 UTC, bretthoerner commented
FWIW I just got this (same issue reported in original bug)

```
npx wrangler generate my-app cloudflare/workers-sdk/tree/main/templates/worker-typescript
Need to install the following packages:
  wrangler
Ok to proceed? (y) 
npm WARN deprecated rollup-plugin-inject@3.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-inject.
npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
 ⛅️ wrangler 2.11.0 
--------------------
Creating a worker in my-app from cloudflare/workers-sdk/tree/main/templates/worker-typescript

✘ [ERROR] Failed to find "tree/main/templates/worker-typescript" in https://github.com/cloudflare/workers-sdk.git


If you think this is a bug then please create an issue at https://github.com/cloudflare/workers-sdk/issues/new/choose
```

2023-02-23 22:19 UTC, lrapoport-cf requested changes

2023-02-23 22:19 UTC, lrapoport-cf commented on content/workers/get-started/quickstarts.md
> +{{<worker-starter title="JavaScript Starter" repo="worker" description="A bare-bones Workers starter project, in JavaScript.">}}
```suggestion
{{<worker-starter title="JavaScript Starter" repo="cloudflare/workers-sdk/tree/main/templates/worker" description="A bare-bones Workers starter project, in JavaScript.">}}
```

2023-02-23 22:19 UTC, lrapoport-cf commented on content/workers/get-started/quickstarts.md
> +{{<worker-starter title="TypeScript Starter" repo="worker-typescript" description="A bare-bones Workers starter project, in TypeScript.">}}
```suggestion
{{<worker-starter title="TypeScript Starter" repo="cloudflare/workers-sdk/tree/main/templates/worker-typescript" description="A bare-bones Workers starter project, in TypeScript.">}}
```

2023-02-23 22:19 UTC, lrapoport-cf commented on content/workers/get-started/quickstarts.md
> +{{<worker-starter title="Workers Sites" repo="worker-sites" description="Easily deploy a static site or static assets to Cloudflare’s edge network.">}}
```suggestion
{{<worker-starter title="Workers Sites" repo="cloudflare/workers-sdk/tree/main/templates/worker-sites" description="Easily deploy a static site or static assets to Cloudflare’s edge network.">}}
```

2023-02-23 22:19 UTC, lrapoport-cf commented on content/workers/get-started/quickstarts.md
> +{{<worker-starter title="Router" repo="worker-router" description="Run different logic based on the URL and request method. Use this starter to Build REST APIs or apps that require routing logic.">}}
```suggestion
{{<worker-starter title="Router" repo="cloudflare/workers-sdk/tree/main/templates/worker-router" description="Run different logic based on the URL and request method. Use this starter to Build REST APIs or apps that require routing logic.">}}
```

2023-02-23 22:19 UTC, lrapoport-cf commented on content/workers/get-started/quickstarts.md
> +{{<worker-starter title="Speedtest" repo="worker-speedtest"
```suggestion
{{<worker-starter title="Speedtest" repo="cloudflare/workers-sdk/tree/main/templates/worker-speedtest"
```

2023-02-23 22:19 UTC, lrapoport-cf commented on content/workers/get-started/quickstarts.md
> +{{<worker-starter title="AWS DynamoDB SQS" repo="worker-aws" description="Use AWS services such as DynamoDB and SQS from a Cloudflare Worker">}}
```suggestion
{{<worker-starter title="AWS DynamoDB SQS" repo="cloudflare/workers-sdk/tree/main/templates/worker-aws" description="Use AWS services such as DynamoDB and SQS from a Cloudflare Worker">}}
```

2023-02-23 22:19 UTC, lrapoport-cf commented on content/workers/get-started/quickstarts.md
> +{{<worker-starter title="Analytics Engine Forwarder" repo="worker-analytics-engine-forwarder" description="Use a Worker to capture analytics data with Analytics Engine.">}}
```suggestion
{{<worker-starter title="Analytics Engine Forwarder" repo="cloudflare/workers-sdk/tree/main/templates/worker-analytics-engine-forwarder" description="Use a Worker to capture analytics data with Analytics Engine.">}}
```

2023-02-23 22:19 UTC, lrapoport-cf commented on content/workers/get-started/quickstarts.md
> +{{<worker-starter title="Hello World (Rust)" repo="cloudflare/worker-rust" description="A bare-bones starter in Rust.">}}
```suggestion
{{<worker-starter title="Hello World (Rust)" repo="cloudflare/workers-sdk/tree/main/templates/worker-rust" description="A bare-bones starter in Rust.">}}
```

2023-02-23 22:19 UTC, lrapoport-cf commented on content/workers/get-started/quickstarts.md
> +{{<worker-starter title="Hello World (COBOL)" repo="cloudflare/worker-cobol" description="A bare-bones starter in COBOL.">}}
```suggestion
{{<worker-starter title="Hello World (COBOL)" repo="cloudflare/workers-sdk/tree/main/templates/worker-cobol" description="A bare-bones starter in COBOL.">}}
```

2023-02-23 22:19 UTC, lrapoport-cf commented on content/workers/get-started/quickstarts.md
> +{{<worker-starter title="Emscripten + Wasm Image Resizer" repo="cloudflare/worker-emscripten-template" description="An image resizer in C compiled to Wasm with Emscripten.">}}
```suggestion
{{<worker-starter title="Emscripten + Wasm Image Resizer" repo="cloudflare/workers-sdk/tree/main/templates/worker-emscripten" description="An image resizer in C compiled to Wasm with Emscripten.">}}
```

2023-02-23 22:19 UTC, lrapoport-cf commented on content/workers/wrangler-legacy/commands.md
> +  - When defined, the default `$TEMPLATE` value is changed to [`cloudflare/worker-sites-template`](https://github.com/cloudflare/worker-sites-template). This scaffolds a [Workers Site](/workers/platf
```suggestion
  - When defined, the default `$TEMPLATE` value is changed to [`cloudflare/workers-sdk/templates/worker-sites`](https://github.com/cloudflare/workers-sdk/tree/main/templates/worker-sites). This scaffolds a [Workers Site](/workers/platform/sites/) project.
```

i think we want to keep the change i had because it points to the version of the worker-sites template that is now in the workers-sdk repo. my understanding is the top-level one is a duplicate and should be deprecated.

2023-02-23 22:19 UTC, lrapoport-cf commented on content/workers/wrangler-legacy/commands.md
> +  - When defined, the default `$TEMPLATE` value is changed to [`cloudflare/worker-sites-template`](https://github.com/cloudflare/worker-sites-template). This scaffolds a [Workers Site](/workers/platf
```suggestion
  - When defined, the default `$TEMPLATE` value is changed to [`cloudflare/workers-sdk/templates/worker-sites`](https://github.com/cloudflare/workers-sdk/tree/main/templates/worker-sites). This scaffolds a [Workers Site](/workers/platform/sites/) project.
```

as above, i think we want to keep the change i had because it points to the version of the worker-sites template that is now in the workers-sdk repo. my understanding is the top-level one is a duplicate and should be deprecated.

2023-02-23 22:20 UTC, lrapoport-cf commented
> @lrapoport-cf I've reverted the revert (😂) for non-git/wrangler links—how does that look now?

😂 i think there are still some which should be un-reverted, which i've noted :)

2023-02-24 14:14 UTC, penalosa commented on content/workers/get-started/quickstarts.md
> +{{<worker-starter title="JavaScript Starter" repo="worker" description="A bare-bones Workers starter project, in JavaScript.">}}
The `<worker-starter/>` fragment generates a command of the form `npx wrangler generate my-app $repo`. The value in `repo` is interpreted as either the (bare) name of a Cloudflare template, or a path on the default branch of a repo. Using `tree/main` in the repo path leads to the following command being generated:

```sh
npx wrangler generate my-app cloudflare/workers-sdk/tree/main/templates/worker
```

which results in the following error:

> ✘ [ERROR] Failed to find "tree/main/templates/worker" in https://github.com/cloudflare/workers-sdk.git

If you omit the repo and path, and just use `repo=worker`, Wrangler will look it up in the `workers-sdk` templates folder by default:

```sh
npx wrangler generate my-app worker
```

Alternatively, using `repo=cloudflare/workers-sdk/templates/worker` would also work.

(Fixing these generated commands in the quickstarts was the main purpose of this PR)

2023-02-24 14:15 UTC, penalosa commented on content/workers/get-started/quickstarts.md
> +{{<worker-starter title="Workers Sites" repo="worker-sites" description="Easily deploy a static site or static assets to Cloudflare’s edge network.">}}
As above

2023-02-24 14:15 UTC, penalosa commented on content/workers/get-started/quickstarts.md
> +{{<worker-starter title="Router" repo="worker-router" description="Run different logic based on the URL and request method. Use this starter to Build REST APIs or apps that require routing logic.">}}
As above

2023-02-24 14:15 UTC, penalosa commented on content/workers/get-started/quickstarts.md
> +{{<worker-starter title="Speedtest" repo="worker-speedtest"
As above

2023-02-24 14:16 UTC, penalosa commented on content/workers/get-started/quickstarts.md
> +{{<worker-starter title="AWS DynamoDB SQS" repo="worker-aws" description="Use AWS services such as DynamoDB and SQS from a Cloudflare Worker">}}
As above

2023-02-24 14:19 UTC, penalosa commented on content/workers/get-started/quickstarts.md
> +{{<worker-starter title="JavaScript Starter" repo="worker" description="A bare-bones Workers starter project, in JavaScript.">}}
Oh I _see_, that breaks the links... I think the partial needs to updated for the templates repo move

2023-02-27 16:09 UTC, JacobMGEvans approved these changes

2023-02-28 02:43 UTC, lrapoport-cf commented on content/workers/wrangler-legacy/commands.md
> +  - When defined, the default `$TEMPLATE` value is changed to [`cloudflare/worker-sites-template`](https://github.com/cloudflare/worker-sites-template). This scaffolds a [Workers Site](/workers/platf
@penalosa is there a reason we don't want to reference the worker-sites template in the workers-sdk templates folder?

2023-02-28 02:43 UTC, lrapoport-cf commented on content/workers/wrangler-legacy/commands.md
> +  - When defined, the default `$TEMPLATE` value is changed to [`cloudflare/worker-sites-template`](https://github.com/cloudflare/worker-sites-template). This scaffolds a [Workers Site](/workers/platf
@penalosa is there a reason we don't want to reference the worker-sites template in the workers-sdk templates folder?

2023-02-28 02:49 UTC, lrapoport-cf commented
@penalosa links all seem to be working now :) just one more followup question -- how was it decided which examples to remove from the quickstarts page? i thought it would track with those in the `templates/experimental` folder, but looks like more than just those were removed from the page. should more of our templates be moved into `templates/experimental`?

2023-02-28 17:42 UTC, penalosa commented
- I removed the TypeScript & Javascript Starter since they’re covered by  `wrangler init`
- I removed the Workers Sites starter & Miniflare Example Project since we don’t recommend them for new users (covered by Pages and Wrangler respectively)
- I moved Sundar & Hono to the Frameworks section

2023-03-01 18:17 UTC, lrapoport-cf commented on content/workers/get-started/quickstarts.md
> +{{<worker-starter title="Hono Starter" repo="honojs/hono-minimal" description="Hono is an ultrafast web framework built for Cloudflare Workers. This is a minimal project using Hono, TypeScript, esbui
suggestion to remove "starter" to be consistent with the format of the rest of the titles in this section
```suggestion
{{<worker-starter title="Hono" repo="honojs/hono-minimal" description="Hono is an ultrafast web framework built for Cloudflare Workers. This is a minimal project using Hono, TypeScript, esbuild, Miniflare, and Jest.">}}
```

2023-03-01 18:18 UTC, lrapoport-cf commented on content/workers/get-started/quickstarts.md
>  {{<worker-starter title="Edge-side rendering - Vitedge" repo="frandiox/vitessedge-template" description="Use Vite to render pages at the edge with great DX. Includes i18n, markdown support and more."
let's capitalize for consistency
```suggestion
{{<worker-starter title="Edge-Side Rendering - Vitedge" repo="frandiox/vitessedge-template" description="Use Vite to render pages at the edge with great DX. Includes i18n, markdown support and more.">}}
```

2023-03-01 18:20 UTC, lrapoport-cf commented
> * I removed the TypeScript & Javascript Starter since they’re covered by  `wrangler init`
> * I removed the Workers Sites starter & Miniflare Example Project since we don’t recommend them for new users (covered by Pages and Wrangler respectively)
> * I moved Sundar & Hono to the Frameworks section

@penalosa  👍  

as a followup PR to workers-sdk, does it make sense to move `worker-rust`, `worker-cobol`, and `worker-emscripten` to the `templates/experimental` folder?

2023-03-01 18:25 UTC, lrapoport-cf commented
@penalosa i added two more small nit suggestions. just have an outstanding question re: worker-sites (https://github.com/cloudflare/cloudflare-docs/pull/7728#discussion_r1116308466 and https://github.com/cloudflare/cloudflare-docs/pull/7728#discussion_r1116308466

2023-03-02 15:18 UTC, deadlypants1973 approved these changes
PCX reviewed with comment. We are not using the word 'edge' to describe the CF network anymore and are now using 'Cloudflare global network'. Also added in some periods at the end of descriptions.

2023-03-02 15:18 UTC, deadlypants1973 commented on content/workers/get-started/quickstarts.md
> +{{<worker-starter title="Router" repo="cloudflare/workers-sdk/templates/worker-router" description="Run different logic based on the URL and request method. Use this starter to Build REST APIs or app
```suggestion
{{<worker-starter title="Router" repo="cloudflare/workers-sdk/templates/worker-router" description="Run different logic based on the URL and request method. Use this starter to Build REST APIs or applications that require routing logic.">}}
```

2023-03-02 15:18 UTC, deadlypants1973 commented on content/workers/get-started/quickstarts.md
> +{{<worker-starter title="AWS DynamoDB SQS" repo="cloudflare/workers-sdk/templates/worker-aws" description="Use AWS services such as DynamoDB and SQS from a Cloudflare Worker">}}
```suggestion
{{<worker-starter title="AWS DynamoDB SQS" repo="cloudflare/workers-sdk/templates/worker-aws" description="Use AWS services such as DynamoDB and SQS from a Cloudflare Worker.">}}
```

2023-03-02 15:18 UTC, deadlypants1973 commented on content/workers/get-started/quickstarts.md
>  {{<worker-starter title="Edge-side rendering - Vitedge" repo="frandiox/vitessedge-template" description="Use Vite to render pages at the edge with great DX. Includes i18n, markdown support and more."
```suggestion
{{<worker-starter title="Edge-Side Rendering - Vitedge" repo="frandiox/vitessedge-template" description="Use Vite to render pages at the edge with great developer experience (DX). Includes i18n, markdown support and more.">}}
```

2023-03-02 15:18 UTC, deadlypants1973 commented on content/workers/get-started/quickstarts.md
> +{{<worker-starter title="Router" repo="cloudflare/workers-sdk/templates/worker-router" description="Run different logic based on the URL and request method. Use this starter to Build REST APIs or app
```suggestion
{{<worker-starter title="Router" repo="cloudflare/workers-sdk/templates/worker-router" description="Run different logic based on the URL and request method. Use this starter to Build REST APIs or applications that require routing logic.">}}
```

2023-03-02 15:18 UTC, deadlypants1973 commented on content/workers/get-started/quickstarts.md
>  {{<worker-starter title="Sentry" repo="bustle/cf-sentry" description="Log exceptions and errors in your Workers application to Sentry.io - an error tracking tool">}}
```suggestion
{{<worker-starter title="Sentry" repo="bustle/cf-sentry" description="Log exceptions and errors in your Workers application to Sentry.io - an error tracking tool.">}}
```

2023-03-02 15:18 UTC, deadlypants1973 commented on content/workers/get-started/quickstarts.md
>  description="Measure download / upload connection speed from the client side, using the Performance Timing API.">}}
```suggestion
description="Measure download/upload connection speed from the client side, using the Performance Timing API.">}}
```

2023-03-02 15:18 UTC, deadlypants1973 commented on content/workers/get-started/quickstarts.md
> +{{<worker-starter title="AWS DynamoDB SQS" repo="cloudflare/workers-sdk/templates/worker-aws" description="Use AWS services such as DynamoDB and SQS from a Cloudflare Worker">}}
```suggestion
{{<worker-starter title="AWS DynamoDB SQS" repo="cloudflare/workers-sdk/templates/worker-aws" description="Use AWS services such as DynamoDB and SQS from a Cloudflare Worker.">}}
```

2023-03-02 15:18 UTC, deadlypants1973 commented on content/workers/get-started/quickstarts.md
> +{{<worker-starter title="Apollo GraphQL Server" repo="signalnerve/workers-graphql-server" description="Lightning-fast, globally distributed Apollo GraphQL server, deployed at the edge using Cloudflar
```suggestion
{{<worker-starter title="Apollo GraphQL Server" repo="signalnerve/workers-graphql-server" description="Lightning-fast, globally distributed Apollo GraphQL server, deployed on the Cloudflare global network using Cloudflare Workers.">}}
```

2023-03-02 16:18 UTC, penalosa commented
@lrapoport-cf & @deadlypants1973 those should all be addressed now.

> as a followup PR to workers-sdk, does it make sense to move worker-rust, worker-cobol, and worker-emscripten to the templates/experimental folder?

Yes, we should definitely do that

2023-03-02 16:58 UTC, lrapoport-cf commented on content/workers/get-started/quickstarts.md
> +{{<worker-starter title="Sentry" repo="bustle/cf-sentry" description="Log exceptions and errors in your Workers application to Sentry.io - an error tracking tool.">}}
```suggestion
{{<worker-starter title="Sentry" repo="mhart/cf-sentry" description="Log exceptions and errors in your Workers application to Sentry.io - an error tracking tool.">}}
```

`bustle/cf-sentry` redirects to `mhart/cfsentry`

2023-03-02 16:59 UTC, lrapoport-cf commented on content/workers/get-started/quickstarts.md
> +{{<worker-starter title="Apollo GraphQL Server" repo="signalnerve/workers-graphql-server" description="Lightning-fast, globally distributed Apollo GraphQL server, deployed on the Cloudflare global ne
this redirects to https://github.com/cloudflare/workers-graphql-server -- can we update the `repo=` param so that the command displayed reflects this?

2023-03-02 17:01 UTC, lrapoport-cf approved these changes

2023-03-02 17:01 UTC, lrapoport-cf commented
@penalosa i found two other small things that would be great to fix but otherwise lgtm :) thank you!

2023-03-03 00:02 UTC, penalosa commented
@lrapoport-cf That should (🤞) be everything now

2023-03-03 04:48 UTC, lrapoport-cf commented
> @lrapoport-cf & @deadlypants1973 those should all be addressed now.
> 
> > as a followup PR to workers-sdk, does it make sense to move worker-rust, worker-cobol, and worker-emscripten to the templates/experimental folder?
> 
> Yes, we should definitely do that

created https://github.com/cloudflare/workers-sdk/issues/2846

2023-03-03 05:01 UTC, lrapoport-cf commented
> @lrapoport-cf That should (🤞) be everything now

looks good!

2023-03-03 14:15 UTC, merged