Add notes about incompatibility between Pages and ACM
cloudflare/cloudflare-docs pull request #7807
Opened 2023-02-28 17:54 UTC by Erisa

PCX suggestions welcome on wording/etc

2023-02-28 20:19 UTC, WalshyDev commented on content/pages/platform/known-issues.md
> +    - a Worker already routed on that domain.
Don't think this is working as intended
![image](https://user-images.githubusercontent.com/8492901/221968613-2cb2e31f-855b-45c5-a012-8a6a6ff7ba20.png)

2023-02-28 20:19 UTC, WalshyDev commented on content/pages/platform/known-issues.md
> +- [Advanced Certificates](/ssl/edge-certificates/advanced-certificate-manager/) are not able to be used with Cloudflare Pages due to [certificate prioritization](/ssl/reference/certificate-and-hostna
```suggestion
- [Advanced Certificates](/ssl/edge-certificates/advanced-certificate-manager/) are not able to be used with Cloudflare Pages due to SSL for SaaS's [certificate prioritization](/ssl/reference/certificate-and-hostname-priority).
```

2023-02-28 20:20 UTC, Erisa commented on content/pages/platform/known-issues.md
> +    - a Worker already routed on that domain.
Oops, will have to check how that's done properly

2023-03-01 15:03 UTC, kodster28 requested changes

2023-03-01 15:03 UTC, kodster28 commented on content/ssl/edge-certificates/advanced-certificate-manager/_index.md
> +{{<Aside type="note">}}
I'd rather we add a new H2 at the bottom called `Limitations` and put it under there.

2023-03-01 15:03 UTC, kodster28 commented on content/pages/platform/known-issues.md
> +- [Advanced Certificates](/ssl/edge-certificates/advanced-certificate-manager/) are not able to be used with Cloudflare Pages due to SSL for SaaS's [certificate prioritization](/ssl/reference/certifi
```suggestion
- [Advanced Certificates](/ssl/edge-certificates/advanced-certificate-manager/) cannot be used with Cloudflare Pages due to SSL for SaaS's [certificate prioritization](/ssl/reference/certificate-and-hostname-priority).
```

2023-03-01 15:03 UTC, kodster28 commented on content/ssl/edge-certificates/advanced-certificate-manager/_index.md
> +Advanced Certificate Manager is unable to be used with Cloudflare Pages due to [certificate prioritization](/ssl/reference/certificate-and-hostname-priority). This is because Pages uses Cloudflare fo
```suggestion
Advanced Certificate Manager cannot be used with Cloudflare Pages due to [certificate prioritization](/ssl/reference/certificate-and-hostname-priority). This is because Pages uses Cloudflare for SaaS for Custom Domains.
```

2023-03-01 15:13 UTC, Erisa commented on content/ssl/edge-certificates/advanced-certificate-manager/_index.md
> +{{<Aside type="note">}}
Good idea, lets do that

2023-03-02 21:16 UTC, kodster28 commented on content/ssl/edge-certificates/advanced-certificate-manager/_index.md
> +Advanced Certificate Manager cannot be used with [Cloudflare Pages](/pages/) due to [certificate prioritization](/ssl/reference/certificate-and-hostname-priority). This is because Pages uses Cloudfla
```suggestion
Advanced Certificate Manager cannot be used with [Cloudflare Pages](/pages/) due to [certificate prioritization](/ssl/reference/certificate-and-hostname-priority/). This is because Pages uses Cloudflare for SaaS for Custom Domains.
```

2023-03-02 21:16 UTC, kodster28 commented on content/pages/platform/known-issues.md
> +- [Advanced Certificates](/ssl/edge-certificates/advanced-certificate-manager/) cannot be used with Cloudflare Pages due to SSL for SaaS's [certificate prioritization](/ssl/reference/certificate-and-
```suggestion
- [Advanced Certificates](/ssl/edge-certificates/advanced-certificate-manager/) cannot be used with Cloudflare Pages due to SSL for SaaS's [certificate prioritization](/ssl/reference/certificate-and-hostname-priority/).
```

2023-03-02 21:17 UTC, kodster28 approved these changes

2023-03-02 21:20 UTC, merged