[R2] Reorganizing the nav
cloudflare/cloudflare-docs pull request #7917
Opened 2023-03-07 23:11 UTC by dcpena

Updates to the current R2 nav to align with PCX content strategy and improve user experience. Addresses PCX-5956.

2023-03-08 11:10 UTC, KianNH commented on content/r2/buckets/presigned-urls.md
> +```ts
This looks like the old presigned URLs page rather than the current one (https://github.com/cloudflare/cloudflare-docs/blob/production/content/r2/data-access/s3-api/presigned-urls.md?plain=1#L70) which seems to be renamed in this PR to be under `content/r2/data-migration/s3-api/presigned-urls.md`

2023-03-08 20:19 UTC, elithrar commented
@dcpena — we should also be adding all of these changes to `content/_redirects` so that existing links don't break.

2023-03-08 20:20 UTC, elithrar requested changes
- [x] Update `content/_redirects` so that existing links don't break.

2023-03-08 20:22 UTC, dcpena commented
> * [x]  Update `content/_redirects` so that existing links don't break.

Thanks for that handy little checkbox! Redirects are definitely part of my plan, but I was going to wait until I got the nav finalized so that I was certain on the new paths for the redirects.

2023-03-13 22:15 UTC, kodster28 requested changes
Content looks good, let me push up a change to help with the link checks.

2023-03-13 22:15 UTC, kodster28 commented on content/r2/reference/_index.md
> +# Reference
```suggestion
# Reference

{{<directory-listing>}}
```

2023-03-13 22:23 UTC, kodster28 approved these changes

2023-03-14 15:42 UTC, elithrar commented on content/r2/buckets/create-buckets.md
> +title: Create new buckets
This should probably be ordered first in the list

<img width="328" alt="image" src="https://user-images.githubusercontent.com/18544/225055113-04f2eef3-f34d-4b4e-98af-93c7be96b026.png">

2023-03-14 15:42 UTC, elithrar commented on content/r2/buckets/create-buckets.md
> +title: Create new buckets
```suggestion
title: Create new buckets
weight: 1
```

2023-03-14 15:42 UTC, elithrar commented on content/r2/buckets/public-buckets.md
>  title: Public buckets
```suggestion
title: Public buckets
weight: 2
```

2023-03-14 15:42 UTC, elithrar commented on content/r2/objects/cache-api.md
> +title: Store objects in Cloudflare's cache
Should this just be "Use the Cache API" - ?

The guide here is actually NOT as useful as using a custom domain, since the Cache API is more work for a user. I don't think this deserves a top-level guide as it's currently named. cc @jonesphillip

2023-03-14 15:42 UTC, elithrar commented on content/r2/reference/pricing.md
Is this buried too deep under Reference? Is Pricing "reference" material?

2023-03-14 15:45 UTC, KianNH commented on content/r2/buckets/presigned-urls.md
> +	async fetch(request) {
Bump on this - the proposed changes actually revert this page back to an incorrect example which doesn’t work.

2023-03-14 16:09 UTC, dcpena commented on content/r2/reference/pricing.md
Pulled out o fReference and made it a top level nav item. Fixed redirect as well

2023-03-14 16:37 UTC, dcpena commented on content/r2/buckets/presigned-urls.md
> +	async fetch(request) {
Thank you so much for this, @KianNH! Will you give this another pass? Should be fixed now

2023-03-14 16:38 UTC, dcpena commented on content/r2/objects/cache-api.md
> +title: Store objects in Cloudflare's cache
Good catch. Chatted about this with Phillip too and made the updates called out in this comment

2023-03-15 14:40 UTC, elithrar approved these changes
Looks great — thanks for making the changes! Let's ship it 🚢

2023-03-15 14:41 UTC, merged

2023-04-29 17:51 UTC, Dezzj reviewed
Approved