[Workers] Added how to filter 504s
cloudflare/cloudflare-docs pull request #8013
Opened 2023-03-14 15:05 UTC by angelampcosta

2023-03-14 16:09 UTC, deadlypants1973 approved these changes

2023-03-14 16:09 UTC, deadlypants1973 commented on content/workers/runtime-apis/cache.md
> +You may see an influx of `504` responses with the `RequestSource` of `earlyHintsCache` in Cloudflare Logs when Early Hints is enabled, which is expected and benign. Requests from `earlyHintsCache` ar
```suggestion
You may see an influx of `504` responses with the `RequestSource` of `earlyHintsCache` in Cloudflare Logs when [Early Hints](/cache/about/early-hints/) is enabled. This behavior is expected and benign. Requests from `earlyHintsCache` are internal subrequests for cached Early Hints. These requests are not end user requests, nor do they go to your origin server. Their response status only indicates whether there are cached Early Hints for the request URI (`200` on cache hit, `504` on cache miss). These requests are already filtered out in other views, such as Cache Analytics. To filter out these requests or to filter requests by end users of your website only, refer to [Filter end users](/analytics/graphql-api/features/filtering/#filter-end-users).
```

2023-03-14 17:22 UTC, drcaramelsyrup requested changes

2023-03-14 17:22 UTC, drcaramelsyrup commented on content/workers/runtime-apis/cache.md
> +You may see an influx of `504` responses with the `RequestSource` of `earlyHintsCache` in Cloudflare Logs when [Early Hints](/cache/about/early-hints/) is enabled. This behavior is expected and benig
I think we actually want to reference [edgeWorkerCacheAPI](https://developers.cloudflare.com/logs/reference/clientrequestsource/) as the request source here, since this page is talking about the Cache API product, not Early Hints which already has its own disclaimer on its own page.

2023-03-14 17:31 UTC, angelampcosta commented on content/workers/runtime-apis/cache.md
> +You may see an influx of `504` responses with the `RequestSource` of `earlyHintsCache` in Cloudflare Logs when [Early Hints](/cache/about/early-hints/) is enabled. This behavior is expected and benig
Thanks @drcaramelsyrup Could you help rephrasing the paragraph?

2023-03-14 19:36 UTC, drcaramelsyrup commented on content/workers/runtime-apis/cache.md
> +You may see an influx of `504` responses with the `RequestSource` of `earlyHintsCache` in Cloudflare Logs when [Early Hints](/cache/about/early-hints/) is enabled. This behavior is expected and benig
I would like a Workers team opinion as well, but perhaps:

> `cache.match` returns a `504` error when the content is stale or not found in cache.

> If you use Cloudflare Logs, you may see these `504` responses with the `RequestSource` of `edgeWorkerCacheAPI`. Again, these are expected if the cached asset was evicted or stale. Note that `edgeWorkerCacheAPI` requests are already filtered out in other views, such as Cache Analytics. To filter out these requests or to filter requests by end users of your website only, refer to [Filter end users](/analytics/graphql-api/features/filtering/#filter-end-users).

2023-03-14 19:59 UTC, angelampcosta commented on content/workers/runtime-apis/cache.md
> +You may see an influx of `504` responses with the `RequestSource` of `earlyHintsCache` in Cloudflare Logs when [Early Hints](/cache/about/early-hints/) is enabled. This behavior is expected and benig
Thanks @drcaramelsyrup 
@deadlypants1973 can we add someone from the Workers team to review?

2023-03-15 14:11 UTC, harrishancock commented on content/workers/runtime-apis/cache.md
> +`cache.match` returns a `504` error when the content is stale.
```suggestion
`cache.match` generates a `504` error response when the requested content is missing or expired. The Cache API does not expose this `504` directly to the Worker script, instead returning `undefined`. Nevertheless, the underlying `504` is still visible in Cloudflare Logs.
```

2023-03-15 14:11 UTC, harrishancock commented on content/workers/runtime-apis/cache.md
> +You may see an influx of `504` responses with the `RequestSource` of `earlyHintsCache` in Cloudflare Logs when [Early Hints](/cache/about/early-hints/) is enabled. This behavior is expected and benig
I agree that mentioning Early Hints doesn't make sense here.

I offer a suggestion above on how I would word the first paragraph.

For the second paragraph, I think @drcaramelsyrup's suggestion is good. I think I'd suggest the phrase "missing or expired" instead of "evicted or stale", though. "Evicted" and "stale" both imply that the response was cached in the first place, which may not be the case. And I think "expired" is a bit clearer than "stale" -- we use the latter term in documentation elsewhere to refer to expired responses which we knowingly expose to the eyeball, which isn't happening here.

2023-03-15 15:47 UTC, harrishancock approved these changes

2023-03-16 09:28 UTC, merged