[Queues] Clarify waitUntil interaction
cloudflare/cloudflare-docs pull request #8091
Opened 2023-03-17 15:09 UTC by elithrar

2023-03-17 16:39 UTC, a-robinson requested changes

2023-03-17 16:39 UTC, a-robinson commented on content/queues/platform/javascript-apis.md
> +Using [`ctx.waitUntil()`](/workers/runtime-apis/fetch-event/#waituntil) extends the lifetime of the "queue" event handler. It accepts a Promise-based task which the Workers runtime will execute befor
> but without blocking the response.

This isn't true as currently implemented -- promises passed to `waitUntil` *do* currently block the response in `queue()` event handlers. This differs from `fetch()` handlers but matches the behavior of `scheduled()` handlers.

As discussed before I'd like to change it to behave more like `fetch`, but that'll require a compatibility flag and until then we should document how it actually works :)

2023-03-23 11:22 UTC, deadlypants1973 commented on content/queues/platform/javascript-apis.md
> +We do not generally recommend using `ctx.waitUntil()` to process message batches directly, as any failure within the context of `waitUntil` can't be caught by your own code.
```suggestion
We do not generally recommend using `ctx.waitUntil()` to process message batches directly, as any failure within the context of `waitUntil` cannot be caught by your own code.
```

2023-03-23 11:23 UTC, deadlypants1973 commented on content/queues/platform/javascript-apis.md
> +Using [`ctx.waitUntil()`](/workers/runtime-apis/fetch-event/#waituntil) extends the lifetime of the "queue" event handler. It accepts a Promise-based task which the Workers runtime will execute befor
```suggestion
Using [`ctx.waitUntil()`](/workers/runtime-apis/fetch-event/#waituntil) extends the lifetime of the queue event handler. It accepts a Promise-based task which the Workers runtime will execute before the handler terminates but without blocking the response.
```

queue should either be in `monospaces` or left without "". We avoid "" in docs unless we are `"quoting to point to a string in code"`.

2023-03-23 15:36 UTC, elithrar commented on content/queues/platform/javascript-apis.md
> +Using [`ctx.waitUntil()`](/workers/runtime-apis/fetch-event/#waituntil) extends the lifetime of the "queue" event handler. It accepts a Promise-based task which the Workers runtime will execute befor
(Fixed this — it should have said blocking. Bad copy + paste)

2023-03-23 15:37 UTC, elithrar commented on content/queues/platform/javascript-apis.md
> +Using [`ctx.waitUntil()`](/workers/runtime-apis/fetch-event/#waituntil) extends the lifetime of the "queue" event handler. It accepts a Promise-based task which the Workers runtime will execute befor
Copied from https://developers.cloudflare.com/workers/runtime-apis/fetch-event/#waituntil so should fix there 😄

2023-03-23 15:45 UTC, a-robinson approved these changes

2023-09-14 19:19 UTC, closed without merging