Change CLOUDFLARE_TOKEN to CLOUDFLARE_API_TOKEN
cloudflare/cloudflare-docs pull request #816
Opened 2021-02-20 21:43 UTC by nemeth

https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/website/docs/index.html.markdown#argument-reference

2021-03-25 17:38 UTC, KimJ15 commented
@garrettgalow Do you approve this PR?

2021-04-08 20:45 UTC, KimJ15 commented
@crwaters16 can you look at this other Terraform PR as well? Thanks!

2021-04-08 22:06 UTC, jacobbednarz requested changes
I'm afraid API keys and API tokens are not interchangeable. If you choose to use an API key, email is required however API tokens do not use an email address. API tokens are preferred however not all services offer support yet so I'd recommend sticking with API keys for this particular documentation.

2021-04-08 22:21 UTC, jacobbednarz commented on products/terraform/src/content/tutorial/source-control.md
> +  token = "your-api-token"
`token` is no longer a valid provider attribute. it was removed to prevent ambiguity and is now `api_key` or `api_token`

```suggestion
  api_token = "your-api-token"
```

2021-04-08 22:21 UTC, jacobbednarz commented on products/terraform/src/content/tutorial/source-control.md
> +$ sed -ie 's/^.*token =.*$/  # token pulled from $CLOUDFLARE_API_TOKEN/' cloudflare.tf
```suggestion
$ sed -ie 's/^.*api_token =.*$/  # token pulled from $CLOUDFLARE_API_TOKEN/' cloudflare.tf
```

2021-04-23 20:16 UTC, crwaters16 approved these changes

2021-04-23 20:16 UTC, merged