[Privacy Gateway] New docs section
cloudflare/cloudflare-docs pull request #8257
Opened 2023-03-29 23:45 UTC by kodster28

2023-03-31 15:26 UTC, kodster28 commented on content/privacy-gateway/_index.md
> +## Features
Forgot to update this section, actually.... will update after these meetings.

2023-03-31 16:04 UTC, mgalicer reviewed
this is looking great! added some comments/suggestions :)

2023-03-31 16:04 UTC, mgalicer commented on content/privacy-gateway/_index.md
> +{{<plan type="all">}}
only available on ENT

2023-03-31 16:04 UTC, mgalicer commented on content/privacy-gateway/_index.md
> +{{<feature header="Make your first API request" href="/radar/get-started/first-request/" cta="Make your first API request">}}
needs to be updated :)

2023-03-31 16:04 UTC, mgalicer commented on content/privacy-gateway/_index.md
> +## Limitations
think this should go in the reference section instead

2023-03-31 16:04 UTC, mgalicer commented on content/privacy-gateway/about.md
> +Privacy Gateway improves the privacy of end-users reaching an application by [proxying HTTP requests](https://www.cloudflare.com/learning/cdn/glossary/reverse-proxy/) through our network. We take thi
this sentence should be in "Legal"

2023-03-31 16:04 UTC, mgalicer commented on content/privacy-gateway/get-started.md
> +Privacy Gateway is compatible with most - but not all - Cloudflare products.
I would strike this content. Instead:

## before you begin
Privacy Gateway is currently in closed beta – if you're interested, please [request access](https://www.cloudflare.com/lp/privacy-edge/).

2023-03-31 16:04 UTC, mgalicer commented on content/privacy-gateway/get-started.md
> +## Step 4 - Configure relay requests
## Step 4 – Relay requests through Cloudflare

2023-04-12 17:28 UTC, chris-wood requested changes

2023-04-12 17:28 UTC, chris-wood commented on content/privacy-gateway/_index.md
> +[Privacy Gateway](https://blog.cloudflare.com/building-privacy-into-internet-standards-and-how-to-make-your-app-more-private-today/) is a managed gateway service deployed on Cloudflare’s edge network
```suggestion
[Privacy Gateway](https://blog.cloudflare.com/building-privacy-into-internet-standards-and-how-to-make-your-app-more-private-today/) is a managed service deployed on Cloudflare’s edge network that implements part of the [Oblivious HTTP (OHTTP) IETF](https://www.ietf.org/archive/id/draft-thomson-http-oblivious-01.html) standard. The goal of Privacy Gateway and Oblivious HTTP is to hide the client's IP address when interacting with an application backend.
```

2023-04-12 17:28 UTC, chris-wood commented on content/privacy-gateway/_index.md
> +OHTTP introduces a trusted third party between client and server, called a relay, whose purpose is to forward requests from client to server, and likewise to forward responses from server to client.
```suggestion
OHTTP introduces a trusted third party between client and server, called a relay, whose purpose is to forward encrypted requests and responses between client and server. These messages are encrypted between client and server such that the relay learns nothing of the application data, beyond the length of the encrypted message and the server the client is interacting with.
```

2023-04-12 17:28 UTC, chris-wood commented on content/privacy-gateway/about.md
> +- **Cloudflare**: Operators of the Privacy Gateway Proxy service.
```suggestion
- **Cloudflare**: Operators of the Privacy Gateway relay service.
```

2023-04-12 17:28 UTC, chris-wood commented on content/privacy-gateway/about.md
> +- **Customers**: Companies and organizations that pay Cloudflare to proxy traffic to their application services through Privacy Gateway.
```suggestion
- **Customers**: Companies and organizations that pay Cloudflare to relay encrypted HTTP messages between clients and their application backends through Privacy Gateway.
```

2023-04-12 17:28 UTC, chris-wood commented on content/privacy-gateway/about.md
> +- Your device or computer’s IP address.
```suggestion
- The IP address associated with client devices connecting to Privacy Gateway.
```

2023-04-12 17:28 UTC, chris-wood commented on content/privacy-gateway/about.md
> +- The application service you are using, including its DNS name and IP address.
```suggestion
- The application service to which HTTP messages are relayed, including its DNS name and IP address.
```

2023-04-12 17:28 UTC, chris-wood commented on content/privacy-gateway/about.md
> +When requests go through Cloudflare's Privacy Gateway, Cloudflare relays the following information to the customer:
```suggestion
As part of using Cloudflare's Privacy Gateway, Cloudflare will collect and report the following information to the customer:
```

2023-04-12 17:28 UTC, chris-wood commented on content/privacy-gateway/get-started.md
> +3. Connection to a Privacy Gateway Relay Server (operated by Cloudflare).
```suggestion
1. Application Gateway Server/backend configuration (operated by you).
2. Client configuration (operated by you).
3. Connection to a Privacy Gateway Relay Server (operated by Cloudflare).
```

2023-04-12 17:28 UTC, chris-wood commented on content/privacy-gateway/get-started.md
> +3. Connection to a Privacy Gateway Relay Server (operated by Cloudflare).
The client depends on the application gateway, so I think these two should be swapped (here and in the subsections below).

2023-04-12 17:28 UTC, chris-wood commented on content/privacy-gateway/get-started.md
> +After you have configured your client and server, review your application to make sure you are only sending intended data to Cloudflare:
```suggestion
After you have configured your client and server, review your application to make sure you are only sending intended data to Cloudflare and the application backend. In particular, application data should not contain anything unique to an end-user, as this would invalidate the benefits that OHTTP provides.
```

2023-04-17 14:46 UTC, kodster28 commented
Howdy @chris-wood or @mgalicer, any additional feedback?

Or is this ready for final review from my team?

2023-04-18 23:11 UTC, ranbel commented on content/privacy-gateway/_index.md
> +[Privacy Gateway](https://blog.cloudflare.com/building-privacy-into-internet-standards-and-how-to-make-your-app-more-private-today/) is a managed service deployed on Cloudflare’s edge network that im
```suggestion
[Privacy Gateway](https://blog.cloudflare.com/building-privacy-into-internet-standards-and-how-to-make-your-app-more-private-today/) is a managed service deployed on Cloudflare’s global network that implements part of the [Oblivious HTTP (OHTTP) IETF](https://www.ietf.org/archive/id/draft-thomson-http-oblivious-01.html) standard. The goal of Privacy Gateway and Oblivious HTTP is to hide the client's IP address when interacting with an application backend.
```

2023-04-18 23:11 UTC, ranbel commented on content/privacy-gateway/_index.md
> +Privacy Gateway is currently in closed beta – available to select privacy-oriented companies and partners. If you’re interested, [contact us](https://www.cloudflare.com/lp/privacy-edge/).
```suggestion
Privacy Gateway is currently in closed beta – available to select privacy-oriented companies and partners. If you are interested, [contact us](https://www.cloudflare.com/lp/privacy-edge/).
```

2023-04-18 23:13 UTC, ranbel commented on content/privacy-gateway/reference/legal.md
> +Privacy Gateway is a managed gateway service deployed on Cloudflare’s edge network that implements the Oblivious HTTP IETF standard to improve client privacy when connecting to an application backend
```suggestion
Privacy Gateway is a managed gateway service deployed on Cloudflare’s global network that implements the Oblivious HTTP IETF standard to improve client privacy when connecting to an application backend. 
```

2023-04-18 23:14 UTC, ranbel commented on content/privacy-gateway/reference/legal.md
> +While Cloudflare will never see the contents of the encrypted application HTTP request proxied through the Privacy Gateway service – because the client will first connect to the OHTTP relay server op
```suggestion
While Cloudflare will never see the contents of the encrypted application HTTP request proxied through the Privacy Gateway service – because the client will first connect to the OHTTP relay server operated in Cloudflare’s global network– Cloudflare will see the following information: the connecting device’s IP address, the application service they are using, including its DNS name and IP address, and metadata associated with the request, including the type of browser, device operating system, hardware configuration, and timestamp of the request ("Privacy Gateway Logs").
```

2023-04-18 23:15 UTC, ranbel commented on content/privacy-gateway/reference/legal.md
> +While Cloudflare will never see the contents of the encrypted application HTTP request proxied through the Privacy Gateway service – because the client will first connect to the OHTTP relay server op
Could put this info in a bulleted list?

2023-04-18 23:16 UTC, ranbel commented on content/privacy-gateway/reference/limitations.md
> +End users should be aware that Cloudflare cannot ensure that websites and services will not send identifying user data from requests forwarded through the Privacy Gateway. This includes - for example
```suggestion
End users should be aware that Cloudflare cannot ensure that websites and services will not send identifying user data from requests forwarded through the Privacy Gateway. This includes information such as names, email addresses, and phone numbers. 
```

2023-04-18 23:17 UTC, ranbel approved these changes

2023-04-18 23:37 UTC, kodster28 commented on content/privacy-gateway/reference/legal.md
> +While Cloudflare will never see the contents of the encrypted application HTTP request proxied through the Privacy Gateway service – because the client will first connect to the OHTTP relay server op
It's a legal thing, so I'll just leave it there.

2023-04-18 23:43 UTC, merged