Add Node.js compatibility page to /platform section
cloudflare/cloudflare-docs pull request #8320
Opened 2023-04-03 16:57 UTC by irvinebroque

2023-04-05 13:13 UTC, elithrar requested changes

2023-04-05 13:13 UTC, elithrar commented on content/workers/platform/nodejs-compatibility.md
> +The following APIs from the [Node.js runtime](https://nodejs.org/en/about) are available directly as [Runtime APIs](/workers/runtime-apis/nodejs), with no need to add polyfills to your own code:
Perhaps an introduction as to why this might be valuable to a layperson?

We jump into "no polyfills" (great!) but for many devs that's hard to grok.

Something like: Allows you to import and use packages across the JavaScript ecosystem, including making it even easier to bring your existing applications to Cloudflare Workers with minimal, if any, changes.

(Etc etc)

2023-04-05 13:13 UTC, elithrar commented on content/workers/platform/nodejs-compatibility.md
> +Node.js APIs are available under the `node:` prefix, and this prefix must be used when importing modules, both in your code and the NPM packages you depend on.
Is there an easy way to have dependencies reference these native built-ins?

2023-04-05 15:40 UTC, deadlypants1973 reviewed
PCX review

2023-04-05 15:40 UTC, deadlypants1973 commented on content/workers/platform/nodejs-compatibility.md
> +title: Node.js Compatibility
```suggestion
title: Node.js compatibility
```

2023-04-05 15:40 UTC, deadlypants1973 commented on content/workers/runtime-apis/nodejs/_index.md
> +# Node.js Compatibility
```suggestion
# Node.js compatibility
```

2023-04-05 15:40 UTC, deadlypants1973 commented on content/workers/platform/nodejs-compatibility.md
> +title: Node.js Compatibility
This is a style guide format. You'll see this format in other titles and subtitles in dev platform docs.

2023-04-05 15:40 UTC, deadlypants1973 commented on content/workers/platform/nodejs-compatibility.md
> +# Node.js Compatibility
```suggestion
# Node.js compatibility
```

2023-04-05 15:40 UTC, deadlypants1973 commented on content/workers/platform/nodejs-compatibility.md
> +## How to enable with Workers
```suggestion
## Enable Node.js with Workers
```

2023-04-05 15:40 UTC, deadlypants1973 commented on content/workers/platform/nodejs-compatibility.md
> +// Not this:
```suggestion
//  Do not do this:
```

2023-04-05 15:40 UTC, deadlypants1973 commented on content/workers/platform/nodejs-compatibility.md
> +## How to enable with Pages Functions
```suggestion
## Enable Node.js with Pages Functions
```

2023-04-05 15:40 UTC, deadlypants1973 commented on content/workers/platform/nodejs-compatibility.md
> +### Using Wrangler
```suggestion
### Enable with Wrangler
```

2023-04-05 15:40 UTC, deadlypants1973 commented on content/workers/platform/nodejs-compatibility.md
> +4. Add the `nodejs_compat` compatibility flag to your Preview and Production deployments
```suggestion
4. Add the `nodejs_compat` compatibility flag to your Preview and Production deployments.
```

2023-04-05 15:40 UTC, deadlypants1973 commented on content/workers/platform/nodejs-compatibility.md
> +### Using the Cloudflare dashboard
```suggestion
### Enable Node.js from the Cloudflare dashboard
```

2023-04-05 15:40 UTC, deadlypants1973 commented on content/workers/platform/nodejs-compatibility.md
> +
```suggestion

To enable Node.js for your Pages Function from the Cloudflare dashboard:

```

2023-04-05 15:40 UTC, deadlypants1973 commented on content/workers/platform/nodejs-compatibility.md
> +1. Log into the [Cloudflare dashboard](https://dash.cloudflare.com) and select your account.
```suggestion
1. Log in to the [Cloudflare dashboard](https://dash.cloudflare.com) and select your account.
```

2023-04-05 15:40 UTC, deadlypants1973 commented on content/workers/runtime-apis/nodejs/_index.md
> +## How to enable with Workers
```suggestion
## Enable Node.js with Workers
```

2023-04-05 15:40 UTC, deadlypants1973 commented on content/workers/runtime-apis/nodejs/_index.md
> +// Not this:
```suggestion
// Do not do this:
```

2023-04-05 15:40 UTC, deadlypants1973 commented on content/workers/runtime-apis/nodejs/_index.md
> +## How to enable with Pages Functions
```suggestion
## Enable Node.js with Pages Functions
```

2023-04-05 15:40 UTC, deadlypants1973 commented on content/workers/runtime-apis/nodejs/_index.md
> +### Using Wrangler
```suggestion
### Enable Node.js with Wrangler
```

2023-04-05 15:40 UTC, deadlypants1973 commented on content/workers/runtime-apis/nodejs/_index.md
> +### Using the Cloudflare dashboard
```suggestion
### Enable Node.js from the Cloudflare dashboard
```

2023-04-05 15:40 UTC, deadlypants1973 commented on content/workers/runtime-apis/nodejs/_index.md
> +4. Add the `nodejs_compat` compatibility flag to your Preview and Production deployments
```suggestion
4. Add the `nodejs_compat` compatibility flag to your Preview and Production deployments.
```

2023-04-05 15:40 UTC, deadlypants1973 commented on content/workers/runtime-apis/nodejs/_index.md
```suggestion

To enable Node.js for your Pages Function from the Cloudflare dashboard:

```

2023-04-06 22:30 UTC, irvinebroque commented on content/workers/platform/nodejs-compatibility.md
> +Node.js APIs are available under the `node:` prefix, and this prefix must be used when importing modules, both in your code and the NPM packages you depend on.
Not yet, but I know @jasnell has ideas

2023-04-06 22:58 UTC, irvinebroque commented on content/workers/platform/nodejs-compatibility.md
> +The following APIs from the [Node.js runtime](https://nodejs.org/en/about) are available directly as [Runtime APIs](/workers/runtime-apis/nodejs), with no need to add polyfills to your own code:
https://github.com/cloudflare/cloudflare-docs/pull/8320/commits/8aef609dcbaf405e59b3044982466e40b7266be9

2023-04-18 06:13 UTC, irvinebroque commented on content/workers/platform/nodejs-compatibility.md
> +The following APIs from the [Node.js runtime](https://nodejs.org/en/about) are available directly as [Runtime APIs](/workers/runtime-apis/nodejs), with no need to add polyfills to your own code:
@deadlypants1973 or @elithrar for 👀 on https://github.com/cloudflare/cloudflare-docs/commit/8aef609dcbaf405e59b3044982466e40b7266be9

2023-04-18 10:09 UTC, elithrar approved these changes

2023-04-18 19:56 UTC, merged