workers: storage objects -> storage OPTIONS
cloudflare/cloudflare-docs pull request #8537
Opened 2023-04-18 16:52 UTC by elithrar

The URL was a typo. Added a redirect from existing pages/redirects as well.

2023-04-18 16:54 UTC, a-robinson requested changes

2023-04-18 16:54 UTC, a-robinson commented on content/_redirects
> +/workers/storage-options/ /workers/storage-options/ 301
```suggestion
/workers/platform/storage-objects/ /workers/platform/storage-options/ 301
```

2023-04-18 17:57 UTC, a-robinson approved these changes

2023-04-19 09:44 UTC, deadlypants1973 approved these changes

2023-04-19 13:21 UTC, merged