[Radar] Add BGP anomaly detection examples
cloudflare/cloudflare-docs pull request #8659
Opened 2023-04-28 00:23 UTC by digizeph

## Overview

This PR adds BGP anomaly detection examples and fixes a couple small issues under Radar.

## Changes

1. add `BGP anomalies` page under `radar/investigate` section
2. remove Radar index page beta tag
3. remove one duplicate line in DNS examples page

2023-04-28 07:57 UTC, G4brym approved these changes

2023-04-28 09:55 UTC, celso approved these changes

2023-04-28 11:02 UTC, marciocloudflare requested changes

2023-04-28 11:02 UTC, marciocloudflare commented on content/radar/investigate/bgp-anomalies.md
> +title: BGP anomalies
```suggestion
title: BGP anomalies (beta)
```

2023-04-28 11:02 UTC, marciocloudflare commented on content/radar/investigate/bgp-anomalies.md
> +should work with a free-tier Cloudflare account.
```suggestion
To access Cloudflare Radar BGP Anomaly Detection results, you will first need to create an API token that includes a `User:User Details` permission. All the following examples should work with a free-tier Cloudflare account.
```

2023-04-28 11:02 UTC, marciocloudflare commented on content/radar/investigate/bgp-anomalies.md
> +should work with a free-tier Cloudflare account.
Active voice is always preferred to passive :)

2023-04-28 11:02 UTC, marciocloudflare commented on content/radar/investigate/bgp-anomalies.md
> +## Search BGP Hijack Events
Unless this is a feature name, it should be lowecase

2023-04-28 11:02 UTC, marciocloudflare commented on content/radar/investigate/bgp-anomalies.md
> +  - a negative score indicates that the event is *less likely* to be a hijack
```suggestion
In the response we can learn about the following information about each event:
- `hijack_msg_count`: the number of potential BGP hijack messages observed from all peers.
- `peer_asns`: the AS numbers of the route collector peers who observed the hijack messages.
- `prefixes`: the affected prefixes.
- `hijacker_asn` and `victim_asns`: the potential hijacker ASN and victim ASNs.
- `confidence_score`: a quantitative score describing how confident the system is for this event being a hijack:
  - 1-3: low confidence.
  - 4-7: medium confidence.
  - 8-above: high confidence.
- `tags`: the evidence collected for the events. Each `tag` is also associated with a score that affects the overall confidence score:
  - a positive score indicates that the event is *more likely* to be a hijack.
  - a negative score indicates that the event is *less likely* to be a hijack.
```

2023-04-28 11:02 UTC, marciocloudflare commented on content/radar/investigate/bgp-anomalies.md
> +```
```suggestion
Users can further filter out low-confidence events by attaching a `minConfidence=8` parameter, which will return only events with a `confidence_score` of `8` or higher.

```bash
curl -X GET "https://api.cloudflare.com/client/v4/radar/bgp/hijacks/events?invlovedAsn=64512&format=json&per_page=10&minConfidence=8" \
     -H "Authorization: Bearer <API_TOKEN>"
```
```

2023-04-28 11:02 UTC, marciocloudflare commented on content/radar/investigate/bgp-anomalies.md
> +the `provider-customer-provider` type of route leak. You can learn more about our design and methodology in [our blog post][route-leak-blog-post].
```suggestion
BGP route leak is another type of BGP anomaly that Cloudflare Radar detects. Currently, we focus on detecting specifcally the `provider-customer-provider` type of route leak. You can learn more about our design and methodology in [our blog post][route-leak-blog-post].
```

2023-04-28 11:02 UTC, marciocloudflare commented on content/radar/investigate/bgp-anomalies.md
> +- `prefix_count` and `origin_count`: the number of prefixes and origin ASes affected by the leak
```suggestion
In the response we can learn about the following information about each event:
- `leak_asn`: the AS who potentially caused the leak.
- `leak_seg`: the AS path segment observed and believed to be a leak.
- `min_ts` and `max_ts`: the earliest and latest timestamps of the leak announcements.
- `leak_count`: the total number of BGP route leak announcements observed.
- `peer_count`: the number of route collector peers observed the leak.
- `prefix_count` and `origin_count`: the number of prefixes and origin ASes affected by the leak.
```

2023-04-28 11:02 UTC, marciocloudflare commented on content/radar/investigate/bgp-anomalies.md
> +relevant to a given ASN using webhook (works for Google Hangouts, Discord, Telegram, etc) or Emails.
```suggestion
In this example, we will show you how you can build a simple Cloudflare Workers app that sends out alerts for BGP hijacks relevant to a given ASN using webhooks (works for Google Hangouts, Discord, Telegram, etc) or email.
```

2023-04-28 11:02 UTC, marciocloudflare commented on content/radar/investigate/bgp-anomalies.md
> +3. construct messages for new hijacks and send out alerts via webhook triggers
```suggestion
- Fetch from Cloudflare API with a given API token.
- Check against Cloudflare KV to know what events are new.
- Construct messages for new hijacks and send out alerts via webhook triggers.
```

2023-04-28 11:02 UTC, marciocloudflare commented on content/radar/investigate/bgp-anomalies.md
> +Let's first create a new workers app in a local directory
```suggestion
First, create a new Workers app in a local directory:

```

2023-04-28 11:02 UTC, marciocloudflare commented on content/radar/investigate/bgp-anomalies.md
> +When prompt to select a type of worker, choose ` Scheduled handler`.
```suggestion

When prompted to select a type of Worker, choose ` Scheduled handler`.
```

2023-04-28 11:02 UTC, marciocloudflare commented on content/radar/investigate/bgp-anomalies.md
> +of configuring the workers to run the script five minutes.
```suggestion
of configuring the workers to run the script five minutes.

```

2023-04-28 11:02 UTC, marciocloudflare commented on content/radar/investigate/bgp-anomalies.md
> +Once you have created a KV (it's free!), you can head back to the `wranglers.toml` file and add the following sections in.
```suggestion
In this example, we will also need to use Cloudflare KV to save the latest checked event IDs which allows us to know what events are new. Once you have created a KV, you can head back to the `wranglers.toml` file and add the following sections:

```

2023-04-28 11:02 UTC, marciocloudflare commented on content/radar/investigate/bgp-anomalies.md
> +Let's start with the API fetching function.
```suggestion
Start with the API fetching function.
```

2023-04-28 11:02 UTC, marciocloudflare commented on content/radar/investigate/bgp-anomalies.md
> +fetch from the Cloudflare API BGP hijacks endpoint.
```suggestion
fetch from the Cloudflare API BGP hijacks endpoint.

```

2023-04-28 11:02 UTC, marciocloudflare commented on content/radar/investigate/bgp-anomalies.md
> +string variable that holds the query parameters in a query URL.
```suggestion

The `env` parameter is passed in from the caller and we do not need to worry about construct it. The `paramsStr` is a string variable that holds the query parameters in a query URL.
```

2023-04-28 11:02 UTC, marciocloudflare commented on content/radar/investigate/bgp-anomalies.md
> +The default cron trigger worker script is defined as the follows:
```suggestion
The default cron trigger worker script is defined as the follows:

```

2023-04-28 11:02 UTC, marciocloudflare commented on content/radar/investigate/bgp-anomalies.md
> +In our example, we use the `env` variables to get the runtime variables like the TOKEN and ASN of interest, and Cloudflare
```suggestion

In our example, we use the `env` variables to get the runtime variables like the TOKEN and ASN of interest, and Cloudflare
```

2023-04-28 11:02 UTC, marciocloudflare commented on content/radar/investigate/bgp-anomalies.md
> +processed event ID.
```suggestion
processed event ID.

```

2023-04-28 11:02 UTC, marciocloudflare commented on content/radar/investigate/bgp-anomalies.md
> +The main loop that checks for the most recent events looks like this. (Some of the validation code is skipped.)
```suggestion
The main loop that checks for the most recent events looks like this (some of the validation code is skipped):

```

2023-04-28 11:02 UTC, marciocloudflare commented on content/radar/investigate/bgp-anomalies.md
> +Now that we have all the newly detected events saved in `new_events` variable, we can then send out alerts:
```suggestion
Now that we have all the newly detected events saved in `new_events` variable, we can then send out alerts:

```

2023-04-28 11:02 UTC, marciocloudflare commented on content/radar/investigate/bgp-anomalies.md
> +Note that the webhook is considered secret and should be set to the environment via `wrangler secret put WEBHOOK_URL` command.
```suggestion

Note that the webhook is considered secret and should be set to the environment via `wrangler secret put WEBHOOK_URL` command.
```

2023-04-28 11:02 UTC, marciocloudflare commented on content/radar/investigate/bgp-anomalies.md
> +account, and will be triggered to execute every 5 minutes.
```suggestion
account, and will be triggered to execute every five minutes.
```

2023-04-28 11:02 UTC, marciocloudflare commented on content/radar/investigate/bgp-anomalies.md
> +Please check out our [developer portal][api-portal] for detailed API documentation.
```suggestion
Refer to our [API documentationl][api-portal] for more information on these topics.
```

2023-04-28 11:02 UTC, marciocloudflare commented on content/radar/investigate/bgp-anomalies.md
> +[api-portal]: https://developers.cloudflare.com/api
This should link directly to Radar's API

2023-04-28 11:03 UTC, marciocloudflare requested changes

2023-04-28 11:03 UTC, marciocloudflare commented on content/radar/investigate/bgp-anomalies.md
> +[api-portal]: https://developers.cloudflare.com/api
```suggestion
[api-portal]: https://developers.cloudflare.com/api/
```

2023-05-03 21:28 UTC, digizeph commented on content/radar/investigate/bgp-anomalies.md
> +[api-portal]: https://developers.cloudflare.com/api
Updated to radar api doc in the new commit

2023-05-03 21:28 UTC, digizeph commented on content/radar/investigate/bgp-anomalies.md
> +## Search BGP Hijack Events
Changed all section titles to have upper case only for first letter

2023-05-04 08:51 UTC, marciocloudflare requested changes

2023-05-04 08:51 UTC, marciocloudflare commented on content/radar/investigate/bgp-anomalies.md
> +For this alerter app, you will need to add the `Emails binding` to the [`wrangler.toml`][wrangler-send-email] file.
```suggestion
If you have [Email Routing][email-routing] enabled for your domain, you can also send email alerts directly from Workers. Refer to [Send emails from Workers][email-workers-tutorial] to learn more.

For this alert to work, you will need to configure the proper email bindings in the [`wrangler.toml`][wrangler-send-email] file.
```

2023-05-04 08:51 UTC, marciocloudflare commented on content/radar/investigate/bgp-anomalies.md
> +Then you can create an email sending function like the follows to send alert emails to your configured destination address.
```suggestion
Then, you can create an email-sending function to send alert emails to your configured destination address:

```

2023-05-04 16:14 UTC, marciocloudflare approved these changes

2023-05-04 16:21 UTC, merged