need-logpush-job-update-for-new-field
cloudflare/cloudflare-docs pull request #8660
Opened 2023-04-28 03:01 UTC by kyouheicf

In order to apply the following new security field settings to the existing Logpush jobs, you will have to edit Logpush option of jobs and make sure the new field is checked at **Select data fields**, then **Save changes**.

2023-04-28 22:19 UTC, tlozoot requested changes
A couple suggestions to make this more clear:
1) I think this should be lower on the page - it's confusing to have this at the top with no other context as to what this is about
2) This gives only instructions as to what to do _in the UI_ -- but many customers update their logpush jobs via API or Terraform. We should explain what needs to be done there.
3) The wording is a bit confusing. I might suggesting breaking up the description of what to do in the UI into a few sentences or a numbered list.

2023-05-02 17:05 UTC, soheiokamoto approved these changes

2023-05-02 17:30 UTC, tlozoot approved these changes
Would like @jsells1 to review this as well

2023-05-02 20:42 UTC, angelampcosta approved these changes

2023-05-04 10:43 UTC, pedrosousa commented
@jsells1 Can you please review the proposed documentation changes?

2023-05-04 20:44 UTC, jsells1 approved these changes

2023-05-05 08:29 UTC, merged