Clarify the DLS eligibility
cloudflare/cloudflare-docs pull request #8826
Opened 2023-05-10 15:10 UTC by cicku

2023-05-10 15:44 UTC, tlozoot requested changes
Thanks for adding this -- good info to include in dev docs.

Can we move the "aside" after the first paragraph? We should start with what DLS "is"

2023-05-10 15:44 UTC, tlozoot commented on content/data-localization/_index.md
> +This feature is only available as a paid add-on for customers on the Enterprise plan. Reach out to your Customer Success Manager for more information.
```suggestion
This feature is available as a paid add-on for customers on the Enterprise plan. Reach out to your Customer Success Manager for more information.
```
"only" seems gratuitous...

2023-05-10 15:44 UTC, tlozoot commented on content/data-localization/_index.md
> +The Data Localization Suite (DLS) is a set of products that helps customers who want to maintain local control over their traffic while retaining the security benefits of a global network.
```suggestion
The Data Localization Suite (DLS) is a set of products that enables customers to control where Cloudflare processes their data, while still benefiting from the security of our global network.
```

Since we're editing this I think the "lede" here can be improved.

2023-05-10 17:26 UTC, tlozoot commented on content/data-localization/_index.md
> +The Data Localization Suite (DLS) is a set of products that helps customers who want to maintain local control over their traffic while retaining the security benefits of a global network.
I made another update to this suggestion per chat with Emily Hancock.

2023-05-10 19:23 UTC, cicku commented
Perhaps we need to use `{{<plan type="ent-add-on">}}`, @angelampcosta any idea for a unified display?

2023-05-11 09:20 UTC, angelampcosta commented
We can. But do need to keep "Reach out to your Customer Success Manager for more information about purchasing DLS."?

2023-05-15 08:59 UTC, angelampcosta commented on content/data-localization/_index.md
> +The Data Localization Suite (DLS) is a collection of tools that enable customers to choose the location where Cloudflare inspects and stores data, while maintaining the security and performance benef
@cicku It's better to move this paragraph to the top, before the note.

2023-07-14 08:23 UTC, closed without merging