Constellation Dev Docs (blog-1803)
cloudflare/cloudflare-docs pull request #8855
Opened 2023-05-11 15:38 UTC by celso

Do not merge yet

2023-05-11 15:49 UTC, edevil commented on content/constellation/platform/wrangler.md
> +    {binding = 'AI', project = '9d478427-dea6-4988-9b16-f6f8888d974c'},
I was asked to change this to `project_id`.

2023-05-12 10:20 UTC, deadlypants1973 requested changes
PCX review

2023-05-12 10:20 UTC, deadlypants1973 commented on content/constellation/_index.md
> +Constellation allows you to run fast, low-latency inference tasks on pre-trained machine learning models natively on Cloudflare Workers scripts. It supports some of the most popular ML/AI runtimes an
```suggestion
Constellation allows you to run fast, low-latency inference tasks on pre-trained machine learning models natively on Cloudflare Workers. It supports some of the most popular machine learning (ML) and AI runtimes and multiple classes of models.
```

2023-05-12 10:20 UTC, deadlypants1973 commented on content/constellation/_index.md
> +Use Constellation from a Cloudflare Worker
```suggestion
Use Constellation from a Cloudflare Worker.
```

2023-05-12 10:20 UTC, deadlypants1973 commented on content/constellation/_index.md
> +{{<feature header="Make your first ML app" href="/radar/get-started/first-request/" cta="Make your first ML app">}}
```suggestion
{{<feature header="Make your first ML application" href="/radar/get-started/first-request/" cta="Make your first ML application">}}
```

2023-05-12 10:20 UTC, deadlypants1973 commented on content/constellation/_index.md
> +Some examples of applications you can deploy leveraging Constellation are:
```suggestion
Functionality you can deploy to your application with Constellation includes:
```

2023-05-12 10:20 UTC, deadlypants1973 commented on content/constellation/_index.md
> +Some examples of applications you can deploy leveraging Constellation are:
The below list is tailored more of a feature list than a use case list, so wording here has been changed to reflect this.

2023-05-12 10:20 UTC, deadlypants1973 commented on content/constellation/_index.md
> +* Question answering
```suggestion
* Image or audio classification
* Object detection
* Anomaly detection
* Text translation, summarization, or similarity analysis
* Natural language processing (NLP)
* Sentiment analysis
* Speech recognition (or text to speech)
* Question answering
```

2023-05-12 10:20 UTC, deadlypants1973 commented on content/constellation/get-started/first-constellation-worker.md
> +    title: First Constellation Worker
```suggestion
    title: Make your first Constellation Worker
```

2023-05-12 10:20 UTC, deadlypants1973 commented on content/constellation/get-started/first-constellation-worker.md
> +In this example, we will build an Image Classification app powered by a Constellation inference engine and the [SqueezeNet 1.1](https://github.com/onnx/models/blob/main/vision/classification/squeezen
```suggestion
In this guide, you will build an [image classification](https://developers.google.com/machine-learning/practica/image-classification#how_image_classification_works) application powered by a Constellation inference engine and the [SqueezeNet 1.1](https://github.com/onnx/models/blob/main/vision/classification/squeezenet/README.md) ONNX model. SqueezeNet is a small Convolutional Neural Network (CNN) which achieves AlexNet-level accuracy on ImageNet with 50 times fewer parameters.
```

2023-05-12 10:20 UTC, deadlypants1973 commented on content/constellation/get-started/first-constellation-worker.md
> +name = "image-classifier-worker"
```suggestion
name = "image-classifier"
```
The name and create command listed above only says "image-classifier".

Does the `create` command add an extra "-worker" at the end of the name in wrangler.toml? I can't test this myself yet.

2023-05-12 10:20 UTC, deadlypants1973 commented on content/constellation/get-started/first-constellation-worker.md
> +Now let's create the wrangler.toml configuration file with the project [binding](/constellation/platform/wrangler/#bindings):
```suggestion
In your project's directory, find the newly generated `wrangler.toml` configuration file and add a Constellation [binding](/constellation/platform/wrangler/#bindings). Bindings allow your Worker to communicate with other Cloudflare Developer Platform products, like Constellation:
```

2023-05-12 10:20 UTC, deadlypants1973 commented on content/constellation/get-started/first-constellation-worker.md
> +Install the client API library:
```suggestion
In your `image-classifier` directory, install the client API library:
```

2023-05-12 10:20 UTC, deadlypants1973 commented on content/constellation/get-started/first-constellation-worker.md
> +Take note of the model id.
```suggestion
Copy the model ID for future reference.
```

2023-05-12 10:20 UTC, deadlypants1973 commented on content/constellation/get-started/first-constellation-worker.md
> +Upload the pre-trained [SqueezeNet 1.1](https://github.com/onnx/models/blob/main/vision/classification/squeezenet/README.md) ONNX model to your project.
```suggestion
Upload the pre-trained [SqueezeNet 1.1](https://github.com/onnx/models/blob/main/vision/classification/squeezenet/README.md) ONNX model to your project:
```

2023-05-12 10:20 UTC, deadlypants1973 commented on content/constellation/get-started/first-constellation-worker.md
> +## Download Imagenet Classes
```suggestion
## Download Imagenet classes
```

2023-05-12 10:20 UTC, deadlypants1973 commented on content/constellation/get-started/first-constellation-worker.md
> +The SqueezeNet model was trained on top of the [Imagenet](https://www.image-net.org/) dataset. Let's download the the list of 1000 image classes that it was trained for.
```suggestion
The SqueezeNet model was trained on top of the [Imagenet](https://www.image-net.org/) dataset. Make a new `src` folder in your `image-classifier` directory. Then download the the list of 1,000 image classes that SqueezeNet was trained for:
```

2023-05-12 10:20 UTC, deadlypants1973 commented on content/constellation/get-started/first-constellation-worker.md
> +Finally let's deploy our Worker.
```suggestion
After you have created your Worker, uploaded your model and downloaded the ImageNet classes for your model, you are ready to deploy your Worker. To deploy your Worker, run:
```

2023-05-12 10:20 UTC, deadlypants1973 commented on content/constellation/get-started/first-constellation-worker.md
> +You can see this demo online [here]().
```suggestion
Refer to [the online demo]().
```
Link needed.

2023-05-12 10:20 UTC, deadlypants1973 commented on content/constellation/platform/client-api.md
> +pcx_content_type: concept
```suggestion
pcx_content_type: configuration
```

2023-05-12 10:20 UTC, deadlypants1973 commented on content/constellation/platform/client-api.md
> +The client API allows developers to interact with the inference engine using the models configured for each project. Inference is the process of running data inputs on a machine-learning model and ge
```suggestion
The Constellation client API allows developers to interact with the inference engine using the models configured for each project. Inference is the process of running data inputs on a machine-learning model and generating an output, or otherwise known as a prediction.
```

2023-05-12 10:20 UTC, deadlypants1973 commented on content/constellation/platform/client-api.md
> +* Have a Cloudflare account with Constellation enabled.
```suggestion
* Sign up for a [Cloudflare account](https://dash.cloudflare.com/sign-up).
* Enable Constellation by logging into the Cloudflare dashboard > **Workers & Pages** > **Constellation**.
```

2023-05-12 10:20 UTC, deadlypants1973 commented on content/constellation/platform/client-api.md
> +* Create a Constellation project and configure the binding.
```suggestion
* Create a [Constellation project](/constellation/get-started/firstconstellation-worker/) and [configure the binding](/constellation/platform/wrangler/#bindings).
```

2023-05-12 10:20 UTC, deadlypants1973 commented on content/constellation/platform/client-api.md
> +* Import the <code>@cloudflare/constellation</code> library in your code.
```suggestion
* Import the <code>@cloudflare/constellation</code> library in your code:
```

2023-05-12 10:20 UTC, deadlypants1973 commented on content/constellation/platform/client-api.md
> +Tensors are essentially multidimensional numerical arrays used to represent any kind of data, like a piece of text, an image, or a time series. TensorFlow popularized the use of [Tensors](https://www
```suggestion
Tensors are essentially multidimensional numerical arrays used to represent any kind of data, like a piece of text, an image, or a time series. TensorFlow popularized the use of [Tensors](https://www.tensorflow.org/guide/tensor) in machine learning (hence the name). Other frameworks and runtimes have since followed the same concept.
```

2023-05-12 10:20 UTC, deadlypants1973 commented on content/constellation/platform/client-api.md
> +Not surprisingly, Constellation also uses Tensors for model input.
```suggestion
Constellation also uses Tensors for model input.
```

2023-05-12 10:20 UTC, deadlypants1973 commented on content/constellation/platform/client-api.md
> +Defines the type of data represented in the Tensor. Options are: <code>float32</code>, <code>float64</code>, <code>int32</code>, <code>int64</code>, <code>string</code> or <code>bool</code>
```suggestion
Defines the type of data represented in the Tensor. Options are: `float32`, `float64`, `int32`, `int64`, `string` or `bool`.
```

2023-05-12 10:20 UTC, deadlypants1973 commented on content/constellation/platform/client-api.md
> +Defines the type of data represented in the Tensor. Options are: <code>float32</code>, <code>float64</code>, <code>int32</code>, <code>int64</code>, <code>string</code> or <code>bool</code>
for readability

2023-05-12 10:20 UTC, deadlypants1973 commented on content/constellation/get-started/first-constellation-worker.md
> +## Setup project
```suggestion
## Configure your project
```

2023-05-12 10:20 UTC, deadlypants1973 commented on content/constellation/get-started/first-constellation-worker.md
> +First, let's [create](/constellation/platform/wrangler/#manage-projects) the new project:
```suggestion
Generate your new project by running [`create`](/constellation/platform/wrangler/#manage-projects). Then run `list` to review th details of your newly created `image-classifier` project:
```

2023-05-12 10:20 UTC, deadlypants1973 commented on content/constellation/platform/client-api.md
> +Click [here](https://www.tensorflow.org/guide/tensor) to know more about shapes.
```suggestion
Refer to the [TensorFlow documentation](https://www.tensorflow.org/guide/tensor) for more information about shapes.
```

2023-05-12 10:20 UTC, deadlypants1973 commented on content/constellation/platform/client-api.md
> +This is tensor's data. See examples:
```suggestion
This is tensor's data. Example tensor values could include:
```

2023-05-12 10:20 UTC, deadlypants1973 commented on content/constellation/platform/client-api.md
> +### Tensor examples:
```suggestion
### Tensor examples
```

2023-05-12 10:20 UTC, deadlypants1973 commented on content/constellation/platform/client-api.md
> +**A single string of text**
```suggestion
#### A single string of text
```

2023-05-12 10:20 UTC, deadlypants1973 commented on content/constellation/platform/client-api.md
> +**A two-element vector**
```suggestion
#### A two-element vector
```

2023-05-12 10:20 UTC, deadlypants1973 commented on content/constellation/platform/client-api.md
> +**A 3x2 float64 matrix***
```suggestio
#### A 3x2 float64 matrix
```

2023-05-12 10:20 UTC, deadlypants1973 commented on content/constellation/platform/client-api.md
> +### await project.run( model, input )
```suggestion
### `await project.run(model, input)`
```

2023-05-12 10:20 UTC, deadlypants1973 commented on content/constellation/platform/client-api.md
> +* **modelId** is the model Id inside the project, you can use [wrangler](constellation/platform/wrangler/#manage-models) to list them.
```suggestion
* **modelId** is the model ID inside the project. Use [wrangler](constellation/platform/wrangler/#manage-models) to list the model ID associated with your project.
```

2023-05-12 10:20 UTC, deadlypants1973 commented on content/constellation/platform/data-model.md
> +# Data Model
```suggestion
# Data model
```

2023-05-12 10:20 UTC, deadlypants1973 commented on content/constellation/platform/data-model.md
> +title: Data Model
```suggestion
title: Data model
```

2023-05-12 10:20 UTC, deadlypants1973 commented on content/constellation/platform/data-model.md
> +The three fundamental concepts of our model are Projects, Models, and the Catalog.
```suggestion
The three fundamental concepts of our model are projects, models, and the catalog.
```

2023-05-12 10:20 UTC, deadlypants1973 commented on content/constellation/platform/data-model.md
> +The Project has a name, a machine-learning runtime, and an Id.
```suggestion
The project has a name, a machine-learning runtime, and an ID.
```

2023-05-12 10:20 UTC, deadlypants1973 commented on content/constellation/platform/data-model.md
> +The runtime has to be one of our supported engines; [click here](/constellation/platform/runtimes/) for the complete list. The Id is what binds the project to the Worker Script.
```suggestion
The runtime has to be one of our supported engines. Refer to [Constellation Runtimes](/constellation/platform/runtimes/) for the complete list. The ID is what binds the project to the Worker.
```

2023-05-12 10:20 UTC, deadlypants1973 commented on content/constellation/platform/data-model.md
> +The name can only have alphanumeric, minus (-) and underscore (_) characters (```/^[a-zA-Z0-9-_]+$/```) and it helps organize things and is used for certain operations in [Wrangler](/constellation/co
```suggestion
The name can only have alphanumeric, minus (`-`) and underscore (`_`) characters (`/^[a-zA-Z0-9-_]+$/`). The name helps with organization and is used for certain operations in [Wrangler](/constellation/concepts/wrangler-support/) and the APIs.
```

2023-05-12 10:20 UTC, deadlypants1973 commented on content/constellation/platform/data-model.md
> +The name can only have alphanumeric, minus (-) and underscore (_) characters (```/^[a-zA-Z0-9-_]+$/```) and it helps organize things and is used for certain operations in [Wrangler](/constellation/co
A triple ` is not needed here unless you want to create a code block I believe?

2023-05-12 10:20 UTC, deadlypants1973 commented on content/constellation/platform/data-model.md
> +The models are user-uploaded files that are attached to a specific project. The model has a name, a description, and an Id. It needs to be compatible with the machine-learning [runtime](/constellatio
```suggestion
The models are user-uploaded files that are attached to a specific project. The model has a name, a description, and an ID. A model needs to be compatible with the [machine-learning runtime](/constellation/platform/runtimes/) defined in the project it belongs to. For example, you should only upload the `model.onnx` file to a project configured for ONNX runtime.
```

2023-05-12 10:20 UTC, deadlypants1973 commented on content/constellation/platform/data-model.md
> +The name can only have alphanumeric, minus (-) and underscore (_) characters (```/^[a-zA-Z0-9-_]+$/```).
```suggestion
The name can only have alphanumeric, minus (`-`) and underscore (`_`) characters (`/^[a-zA-Z0-9-_]+$/`).
```

2023-05-12 10:20 UTC, deadlypants1973 commented on content/constellation/platform/data-model.md
> +Currently, during the private beta, we only support models that are smaller than 10MiB.
```suggestion
Currently, during the private beta, we only support models that are smaller than 10 MiB.
```

2023-05-12 10:20 UTC, deadlypants1973 commented on content/constellation/platform/data-model.md
> +Not everyone will want to train models or browse the Internet for models they didn't test yet and upload them. Cloudflare will maintain a list of verified models that are known to work with the Const
```suggestion
You may not want to train models or upload models you have not tested. Cloudflare will maintain a list of verified models that are known to work with the Constellation APIs without extra configuration.
```

2023-05-12 10:20 UTC, deadlypants1973 commented on content/constellation/platform/data-model.md
> +Like user-uploaded models, the models in the catalog have a name, an Id, and a description and are associated with a parent catalog project that defines the runtime.
```suggestion
Like user-uploaded models, the models in the catalog have a name, an ID, and a description and are associated with a parent catalog project that defines the runtime.
```

2023-05-12 10:20 UTC, deadlypants1973 commented on content/constellation/platform/runtimes.md
> +# Constellation Runtimes
```suggestion
# Constellation runtimes
```

2023-05-12 10:20 UTC, deadlypants1973 commented on content/constellation/platform/runtimes.md
> +There are various machine learning and AI tools and frameworks being improved or emerging, with lots of innovation happening in the space. Constellation was designed to support multiple Machine Learn
```suggestion
Due to innovation in the AI space, there are various machine learning, AI tools and frameworks being improved or emerging. Constellation was designed to support multiple machine learning (ML) runtimes at its core.
```

2023-05-12 10:20 UTC, deadlypants1973 commented on content/constellation/platform/runtimes.md
> +Our vision is to support multiple runtimes over time. Currently we only support the ONNX Runtime, but we are exploring and researching others. [XGBoost](https://xgboost.ai/) is in the final stages of
```suggestion
Our vision is to support multiple runtimes over time. Currently, we only support the ONNX Runtime, but we are exploring and researching others. [XGBoost](https://xgboost.ai/) is in the final stages of testing.
```

2023-05-12 10:20 UTC, deadlypants1973 commented on content/constellation/platform/runtimes.md
> +You can also use Wrangler to list the supported models:
```suggestion
Use Wrangler to list the models Cloudflare supports:
```

2023-05-12 10:20 UTC, deadlypants1973 commented on content/constellation/platform/runtimes.md
> +Currently, Constellation supports the [ONNX Runtime](https://onnxruntime.ai/).
```suggestion
### ONNX
```
This is already stated above. Removing this to downsize docs update work later.

2023-05-12 10:20 UTC, deadlypants1973 commented on content/constellation/platform/runtimes.md
> +The Open Neural Network Exchange (ONNX) is an ecosystem supported by multiple technology companies and research organizations, defines open standards for machine learning, and makes open-source softw
```suggestion
Constellation supports the [ONNX Runtime](https://onnxruntime.ai/). The Open Neural Network Exchange (ONNX) is an ecosystem supported by multiple technology companies and research organizations, defines open standards for machine learning, and makes open-source software for AI.
```

2023-05-12 10:20 UTC, deadlypants1973 commented on content/constellation/platform/runtimes.md
> +The Open Neural Network Exchange (ONNX) is an ecosystem supported by multiple technology companies and research organizations, defines open standards for machine learning, and makes open-source softw
```suggestion
The Open Neural Network Exchange (ONNX) is an ecosystem supported by multiple technology companies and research organizations. ONNX defines open standards for machine learning, and makes open-source software for AI.
```

2023-05-12 10:20 UTC, deadlypants1973 commented on content/constellation/platform/runtimes.md
> +The Open Neural Network Exchange (ONNX) is an ecosystem supported by multiple technology companies and research organizations, defines open standards for machine learning, and makes open-source softw
```suggestion
```
Repeat of above.

2023-05-12 10:20 UTC, deadlypants1973 commented on content/constellation/platform/wrangler.md
> +[Wrangler](https://developers.cloudflare.com/workers/wrangler/) our command-line tool for configuring, building and deploying applications with Cloudflare developer products. You can use Wrangler to
```suggestion
[Wrangler](https://developers.cloudflare.com/workers/wrangler/) is our command-line tool for configuring, building and deploying applications with Cloudflare developer products. Use Wrangler to manipulate your Constellation projects and machine-learning models or search for verified models in our [catalog](/constellation/platform/data-model/#catalog).
```

2023-05-12 10:20 UTC, deadlypants1973 commented on content/constellation/platform/wrangler.md
> +Test it with [npx](https://github.com/npm/npx):
```suggestion
Test Wrangler with [npx](https://github.com/npm/npx):
```

2023-05-12 10:20 UTC, deadlypants1973 commented on content/constellation/platform/wrangler.md
> +Wrangler for Constellation is still in Beta. To install it, do:
```suggestion
Wrangler for Constellation is still in Beta. To install Wrangler, run:
```

2023-05-12 10:20 UTC, deadlypants1973 commented on content/constellation/platform/wrangler.md
> +You can use Wrangler to list, create or delete your [projects](/constellation/platform/data-model/#projects).
```suggestion
Use Wrangler to [list, create or delete your projects](/constellation/platform/data-model/#projects).
```

2023-05-12 10:20 UTC, deadlypants1973 commented on content/constellation/platform/wrangler.md
> +You can use Wrangler to list, create or delete your [models](/constellation/platform/data-model/#models).
```suggestion
You can use Wrangler to [list, create or delete your models](/constellation/platform/data-model/#models).
```

2023-05-12 10:20 UTC, deadlypants1973 commented on content/constellation/platform/wrangler.md
> +The [catalog](/constellation/platform/data-model/#catalog) has ready-to-use pre-verified models for our supported runtimes that you can start using in any script without additional configurations. He
```suggestion
The [catalog](/constellation/platform/data-model/#catalog) has ready-to-use pre-verified models for our supported runtimes that you can start using in any script without additional configurations. Review the following commands on how you interact with the catalog from Wrangler.
```

2023-05-12 10:20 UTC, deadlypants1973 commented on content/constellation/platform/data-model.md
> +For each machine-learning runtime we support, developers can search for ready-to-use permanent models in our catalog and use them for some of the most popular tasks without additional configurations
```suggestion
For each machine-learning runtime we support, developers can search for ready-to-use permanent models in our [catalog](/constellation/platform/data-model/#catalog) and use them for some of the most popular tasks without additional configurations or file uploads.
```

2023-05-12 10:20 UTC, deadlypants1973 commented on content/constellation/platform/data-model.md
> +The runtime has to be one of our supported engines; [click here](/constellation/platform/runtimes/) for the complete list. The Id is what binds the project to the Worker Script.
```suggestion
The runtime has to be one of our supported engines. Refer to [Constellation Runtimes](/constellation/platform/runtimes/) for the complete list. The ID is what binds the project to the Worker.
```

2023-05-15 08:54 UTC, deadlypants1973 commented on content/constellation/get-started/first-constellation-worker.md
> +We're going to need [pngjs](https://github.com/pngjs/pngjs), our PNG decoder, and [string-to-stream](https://github.com/feross/string-to-stream).
```suggestion
## Install modules

Install [pngjs](https://github.com/pngjs/pngjs), a PNG decoder, and [string-to-stream](https://github.com/feross/string-to-stream) before you begin coding your project:
```

2023-05-15 08:58 UTC, deadlypants1973 commented on content/constellation/get-started/first-constellation-worker.md
> +Make sure to replace <code>297f3cda-5e55-33c0-8ffe-224876a76a39</code> with your actual model id.
```suggestion
With your project configured, begin coding. The following script gets a PNG file upload from the request, decodes the image to RGB raw bitmaps, constructs a 3D tensor with the input data, runs the SqueezeNet model, maps the top predictions to the ImagetNet human-readable classes and returns the strongest one in a JSON object.

Replace <code>297f3cda-5e55-33c0-8ffe-224876a76a39</code> with your actual model ID.
```

2023-05-15 08:58 UTC, deadlypants1973 commented on content/constellation/get-started/first-constellation-worker.md
> +## Test it
```suggestion
## Test your project
```

2023-05-15 08:59 UTC, deadlypants1973 commented on content/constellation/get-started/first-constellation-worker.md
> +Here are some test 224x244 PNG images you can use for tests:
```suggestion
Below are some test 224x244 PNG images you can use for tests:
```

2023-05-15 09:01 UTC, deadlypants1973 commented on content/constellation/get-started/first-constellation-worker.md
> +Now the moment of truth, lets upload the test images to our image classifier.
```suggestion
### Run `wrangler dev`

Start a local server to test your `image-classifier` Worker by running [`wrangler dev`](/workers/wrangler/commands/#dev):

```bash
$ npx wrangler dev
⬣ Listening at http://0.0.0.0:8787
```

### Run the test images

Upload the test images to your image classifier:
```

2023-05-15 09:02 UTC, deadlypants1973 commented on content/constellation/get-started/first-constellation-worker.md
> +You can see this demo online at https://ai.cloudflare.com/demos/image-classifier
```suggestion
## Publish your projct

When you are ready, deploy your Worker:

```bash
$ npx wrangler publish
```

[Review this demo online](https://ai.cloudflare.com/demos/image-classifier).
```

2023-05-15 09:45 UTC, samirbani commented on content/constellation/platform/data-model.md
> +The name can only have alphanumeric, minus (-) and underscore (_) characters (```/^[a-zA-Z0-9-_]+$/```).
SAMEER ABBALRAHMAN AHMAD ABJEISA

2023-05-15 09:45 UTC, samirbani commented on content/constellation/platform/data-model.md
> +The name can only have alphanumeric, minus (-) and underscore (_) characters (```/^[a-zA-Z0-9-_]+$/```).
https://ebayst.net/index/user/register/invite_code/GR4WVZ.html

2023-05-15 09:55 UTC, celso reviewed
approved

2023-05-15 09:59 UTC, deadlypants1973 approved these changes
PCX review

2023-05-15 10:10 UTC, deadlypants1973 approved these changes
Fixing broken links

2023-05-15 10:10 UTC, deadlypants1973 commented on content/constellation/platform/client-api.md
> +* Create a [Constellation project](/constellation/get-started/firstconstellation-worker/) and [configure the binding](/constellation/platform/wrangler/#bindings).
```suggestion
* Create a Constellation project and [configure the binding](/constellation/platform/wrangler/#bindings).
```

2023-05-15 10:10 UTC, deadlypants1973 commented on content/constellation/platform/client-api.md
> +* **modelId** is the model ID inside the project. Use [wrangler](constellation/platform/wrangler/#manage-models) to list the model ID associated with your project.
```suggestion
* **modelId** is the model ID inside the project. Use Wrangler to list the model ID associated with your project.
```

2023-05-15 10:10 UTC, deadlypants1973 commented on content/constellation/platform/data-model.md
> +The name can only have alphanumeric, minus (`-`) and underscore (`_`) characters (`/^[a-zA-Z0-9-_]+$/`). The name helps with organization and is used for certain operations in [Wrangler](/constellati
```suggestion
The name can only have alphanumeric, minus (`-`) and underscore (`_`) characters (`/^[a-zA-Z0-9-_]+$/`). The name helps with organization and is used for certain operations in Wrangler and the APIs.
```

2023-05-15 10:27 UTC, merged

2023-05-23 15:11 UTC, samirbani commented
ادمج

2023-05-23 15:53 UTC, samirbani commented
> لا تندمج بعد
ادمج قانوني