[Workers] Wrangler Migrations section
cloudflare/cloudflare-docs pull request #8857
Opened 2023-05-11 16:19 UTC by deadlypants1973

PCX-6913

2023-05-11 22:11 UTC, admah requested changes
The content looks fine, but the new Migration pages are not resolving. I'm not seeing why at first glance.

2023-05-11 22:13 UTC, admah commented on content/workers/wrangler/migration/v1-to-v2/eject-webpack.md
> +title: 1. Migrate webpack projects
Is there a reason why the title is numbered?

2023-05-11 22:13 UTC, admah commented on content/workers/wrangler/migration/v1-to-v2/update-v1-to-v2.md
> +title: 2. Update to Wrangler v2
Is there a reason why the title is numbered?

2023-05-12 09:09 UTC, deadlypants1973 commented on content/workers/wrangler/migration/v1-to-v2/eject-webpack.md
> +title: 1. Migrate webpack projects
Talked with Samuel, and he said that webpack projects need to be addressed before the version is updated. So this is telling the user: in this migration path, change your code first and then update your version. This was unclear before and seems like a crucial thing to point out. I put instructions about this on both pages as well.

2023-05-15 13:03 UTC, marciocloudflare commented on content/workers/wrangler/deprecations.md
> +<div style="position: relative; padding-top: 56.25%;"><iframe src="https://iframe.videodelivery.net/6ce3c7bd51288e1e8439f50ad63eda1d?poster=https%3A%2F%2Fcloudflarestream.com%2F6ce3c7bd51288e1e8439f5
Are you sure about this video? We don't normally have them because it's too hard to maintain. Also, awful from an SEO perspective

2023-05-15 13:05 UTC, marciocloudflare commented on content/workers/wrangler/deprecations.md
> +| `config`    | ✅   | ❔  |
The ? is really light and almost illegible in the page. Isn't there another one we can use?

2023-05-15 13:05 UTC, marciocloudflare commented on content/workers/wrangler/deprecations.md
> +| `subdomain` | ✅   | ❔  |
The `?` is really light and almost unreadable in the page. Isn't there another one we can use?

2023-05-15 13:08 UTC, marciocloudflare approved these changes

2023-05-15 13:14 UTC, deadlypants1973 commented on content/workers/wrangler/deprecations.md
> +| `config`    | ✅   | ❔  |
```suggestion
| `config`    | ✅   | ❓  |
```

2023-05-15 13:14 UTC, deadlypants1973 commented on content/workers/wrangler/deprecations.md
> +| `subdomain` | ✅   | ❔  |
```suggestion
| `subdomain` | ✅   | ❓  |
```

2023-05-15 13:15 UTC, deadlypants1973 reviewed
PCX review

2023-05-15 13:15 UTC, deadlypants1973 reviewed
PCX review

2023-05-15 13:58 UTC, admah commented on content/workers/wrangler/deprecations.md
> +<div style="position: relative; padding-top: 56.25%;"><iframe src="https://iframe.videodelivery.net/6ce3c7bd51288e1e8439f50ad63eda1d?poster=https%3A%2F%2Fcloudflarestream.com%2F6ce3c7bd51288e1e8439f5
@marciocloudflare I believe this has been in the docs for awhile. This just moves it to a different section. Based on that, is it still an issue?

2023-05-15 13:59 UTC, admah approved these changes
LGTM!

2023-05-15 17:59 UTC, merged