Update _index.md
cloudflare/cloudflare-docs pull request #8929
Opened 2023-05-16 14:11 UTC by zeinjaber

Related to SPM-1659 Jira

2023-05-16 15:50 UTC, angelampcosta approved these changes

2023-05-16 23:19 UTC, tlozoot requested changes
I suggested a few changes to make the question/answer a bit more neutral

2023-05-16 23:19 UTC, tlozoot commented on content/analytics/faq/other-faqs/index.md
> +## Does CLOUDFLARENET ASN 13335 traffic spike in Analytics (for example, Security Events or Security Analytics) indicate a DDoS attack?
```suggestion
## Why do I see a large amount of traffic from CLOUDFLARENET ASN 13335 in Analytics? Does this indicate a DDoS attack?
```

2023-05-16 23:19 UTC, tlozoot commented on content/analytics/faq/other-faqs/index.md
> +When you notice a significant volume of traffic originating from **CLOUDFLARENET ASN 13335**, you may assume that Cloudflare is flooding your network with a DDoS attack or generating an excessive tra
```suggestion
There is a number of different types of traffic which may originate from **CLOUDFLARENET ASN 13335**; just because there is a lot of traffic from this AS, it likely does not indicate a DDoS attack.

Some sources of traffic from ASN13335 include:
* [Workers subrequests](https://developers.cloudflare.com/workers/runtime-apis/fetch/)
* [WARP](https://developers.cloudflare.com/warp-client/known-issues-and-faq/#does-warp-reveal-my-ip-address-to-websites-i-visit)
* [iCloud Private Relay](https://blog.cloudflare.com/icloud-private-relay/) (For reference, iCloud Private Relay’s egress IP addresses are available in this [CSV form](https://mask-api.icloud.com/egress-ip-ranges.csv))
* [Cloudflare Privacy Proxy](https://blog.cloudflare.com/building-privacy-into-internet-standards-and-how-to-make-your-app-more-private-today/)
* Other Cloudflare features like [Health Checks](https://developers.cloudflare.com/health-checks/
)


```

2023-05-16 23:19 UTC, tlozoot commented on content/analytics/faq/other-faqs/index.md
> +For reference, iCloud Private Relay’s egress IP addresses are available in this [CSV form](https://mask-api.icloud.com/egress-ip-ranges.csv).
```suggestion
```

2023-05-17 08:10 UTC, angelampcosta commented on content/analytics/faq/other-faqs/index.md
> +For reference, iCloud Private Relay’s egress IP addresses are available in this [CSV form](https://mask-api.icloud.com/egress-ip-ranges.csv).
@zeinjaber can we commit this last suggestion as well?

2023-05-18 06:54 UTC, tlozoot approved these changes

2023-05-18 08:41 UTC, merged