docs(d1): :memo: remove the persist flag from run command
cloudflare/cloudflare-docs pull request #8965
Opened 2023-05-18 09:17 UTC by mcnaveen

Remove `--persist` flag from the dev local run command. Since it's a default behavior now.

Here is the response I got from the Discord server.

> Wrangler will now persist local KV, R2, D1, Cache and Durable Object data
in the .wrangler folder, by default, between reloads. This persistence
directory can be customised with the --persist-to flag. The --persist flag
has been removed, as this is now the default behaviour.

2023-05-18 09:27 UTC, elithrar requested changes
See comment

2023-05-18 09:27 UTC, elithrar commented on content/d1/get-started.md
> -$ wrangler dev --local --persist
This is only the case for wrangler 3, which not everyone is using yet.

2023-05-18 09:44 UTC, mcnaveen commented on content/d1/get-started.md
> -$ wrangler dev --local --persist
I have added a new blockquote explaining it's only from Wrangler 3.

2023-06-29 16:08 UTC, deadlypants1973 approved these changes
PCX

2023-06-29 16:08 UTC, deadlypants1973 commented on content/d1/get-started.md
> +> Starting from Wrangler 3 you don't need to pass the `--persist` flag. By default it'll be cached in the `.wrangler` folder and used upon reloads.
```suggestion
> If using Wrangler 3, you do not need to pass the `--persist` flag. By default, it will be cached in the `.wrangler` folder and used on reloads.
```

2023-06-29 16:54 UTC, elithrar commented
This is out of date - https://developers.cloudflare.com/d1/learning/local-development/#start-a-local-development-session

2023-06-29 16:54 UTC, closed without merging