Add idempotency key documentation for Turnstile
cloudflare/cloudflare-docs pull request #8968
Opened 2023-05-18 13:23 UTC by AleksandarHr

We have recently introduced a support for idempotent POST requests for Turnstile's Siteverify. This PR adds documentation which would inform customers how to make use of this functionality.

2023-05-18 13:26 UTC, lbarthon commented on content/turnstile/get-started/server-side-validation.md
> +// This is a demo idempotency key. In production, we recomment
```suggestion
// This is a demo idempotency key. In production, we recommend
```

2023-05-18 13:26 UTC, lbarthon commented on content/workers/examples/turnstile-html-rewriter.md
> +	formData.append('idempotency_key', idempotency_key);
nit: indentation mismatch with the rest of the file

2023-05-18 14:11 UTC, AleksandarHr commented on content/workers/examples/turnstile-html-rewriter.md
> +	formData.append('idempotency_key', idempotency_key);
hmm something odd is happening, indentation looks fine locally git diff shows different

2023-05-18 14:39 UTC, punkeel commented on content/turnstile/get-started/server-side-validation.md
> +const IDEMPOTENCY_KEY = '4f6fabfd-c55f-46e5-8f4b-6fb44e91e52d';
I'd prefer we keep the demo simple and omit this entirely. Right now, this has the *opposite* effect of what we want: this *disables* replay prevention.

2023-05-18 14:40 UTC, punkeel commented on package.json
> +    "mermaid": "^9.4.3",
unrelated to your PR, please remove.

2023-05-18 14:40 UTC, punkeel commented on content/workers/examples/turnstile-html-rewriter.md
> +	formData.append('idempotency_key', idempotency_key);
use spaces, not tabs.

2023-05-18 14:41 UTC, punkeel commented on content/turnstile/get-started/server-side-validation.md
> +* `idempotency_key` is the UUID associated with the specific token. It was either already provided by the customer with the POST request or was generated internally upon initial successful token vali
What do we expect customers will do with this information? Do they *have* to use it?

> This UUID can be used by the customer for subsequent POST requests with the same token.

is unclear

2023-05-18 14:43 UTC, punkeel commented on content/turnstile/get-started/server-side-validation.md
> +A response (i.e. token) may only be validated once. A previously validated token can be presented again along with an `idempotency key` - a UUID associated with the specific response. If the provided
I'd keep the sentence the same, and add a subsequent one "If you wish to retry failed requests, etc". This should be an advanced feature, the default must remain simple (without it)

2023-05-19 11:19 UTC, AleksandarHr commented on content/turnstile/get-started/server-side-validation.md
> +* `idempotency_key` is the UUID associated with the specific token. It was either already provided by the customer with the POST request or was generated internally upon initial successful token vali
I removed this from here (and the returned `idempotency_key` in the response) altogether -- only left the clarification in the text snipped further up the page.

2023-05-19 11:21 UTC, worenga requested changes

2023-05-19 11:21 UTC, worenga commented on content/turnstile/get-started/server-side-validation.md
> +  "cdata": "sessionid-123456789",
ending comma? did you wanted to add the indempotency return here?

2023-05-19 11:21 UTC, worenga commented on content/turnstile/get-started/server-side-validation.md
> +A response may only be validated once. If the same response is presented twice, the second and each subsequent request will generate an error stating that the response has already been consumed. If y
Don't say `if you wish`, try to keep the wording more generic, e.g. if an application wants to retry, it must...

2023-05-19 11:22 UTC, worenga reviewed
can we add a separate, retry specific example/code recipe?

2023-05-19 11:22 UTC, worenga reviewed
can we add a separate, retry specific example/code recipe?

2023-05-19 11:22 UTC, worenga reviewed
can we add a separate, retry specific example/code recipe?

2023-05-19 11:35 UTC, AleksandarHr commented on content/turnstile/get-started/server-side-validation.md
> +  "cdata": "sessionid-123456789",
I did have it, but removed it subsequently (keeping things simple, by default re discussion with Maxime).
Removing the comma.

2023-05-23 20:23 UTC, patriciasantaana commented on content/turnstile/get-started/server-side-validation.md
> +A response may only be validated once. If the same response is presented twice, the second and each subsequent request will generate an error stating that the response has already been consumed. If a
```suggestion
A response may only be validated once. If the same response is presented twice, the second and each subsequent request will generate an error stating that the response has already been consumed. If an application requires to retry failed requests, it must utilize the idempotency functionality. You can do so by providing a UUID as the `idempotency_key` parameter of your `POST` request when initially validating the response and the same UUID with any subsequent request for that response.
```

2023-05-23 20:25 UTC, patriciasantaana approved these changes

2023-05-24 00:26 UTC, worenga commented
would you mind also adding a note to the turnstile changelog?

2023-05-25 11:36 UTC, worenga approved these changes

2023-05-25 11:36 UTC, merged