[Workers] fix tail worker doc issues
cloudflare/cloudflare-docs pull request #9040
Opened 2023-05-22 18:58 UTC by ndisidore

Hello from the Workers team :wave: 

This was part of a new feature rollout that went live last week as part of Dev Week. There were a few issues with the docs we're getting a chance to circle back around on.

These have all been tested both in a local docs preview and with the actual Workers in production.
CC @tanushreesharma-cf

2023-05-25 13:53 UTC, tanushreesharma-cf approved these changes

2023-05-25 13:53 UTC, tanushreesharma-cf commented
Thanks Nathan! @deadlypants1973 can we get your eyes on this too

2023-06-07 16:41 UTC, deadlypants1973 requested changes

2023-06-07 16:41 UTC, deadlypants1973 commented on content/workers/runtime-apis/tail-event.md
> +  - An array of [`TailItems`](/workers/runtime-apis/tail-event/#tailitems). One `TailItem` is collected for each event that triggers a Worker. For Workers for Platforms customers with a Tail Worker i
Annoying block but I'd like us to standardize what things are called before this PR is merged to avoid further customer confusion. There is currently "dynamic dispatch Worker", "dispatcher Worker", and "dispatch Worker". Can we have unity (naming and capitalization) around this in the W4P and Workers docs before we publish this PR? https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/

2023-06-07 16:41 UTC, deadlypants1973 commented on content/workers/runtime-apis/tail-event.md
> +  - An array of [`TailItems`](/workers/runtime-apis/tail-event/#tailitems). One `TailItem` is collected for each event that triggers a Worker. For Workers for Platforms customers with a Tail Worker i
Same comment as above.

2023-06-07 16:41 UTC, deadlypants1973 commented on content/workers/runtime-apis/tail-event.md
> +    - `scriptNotFound`: An internal error from difficulty retrieving the script.
```suggestion
    - `scriptNotFound`: An internal error from difficulty retrieving the Worker script.
```

2023-06-07 16:42 UTC, deadlypants1973 commented on content/workers/runtime-apis/tail-event.md
> +  - An array of [`TailItems`](/workers/runtime-apis/tail-event/#tailitems). One `TailItem` is collected for each event that triggers a Worker. For Workers for Platforms customers with a Tail Worker i
@Maddy-Cloudflare @tanushreesharma-cf

2023-06-07 16:54 UTC, deadlypants1973 approved these changes

2023-06-07 16:54 UTC, deadlypants1973 commented on content/workers/runtime-apis/tail-event.md
> +  - An array of [`TailItems`](/workers/runtime-apis/tail-event/#tailitems). One `TailItem` is collected for each event that triggers a Worker. For Workers for Platforms customers with a Tail Worker i
```suggestion
  - An array of [`TailItems`](/workers/runtime-apis/tail-event/#tailitems). One `TailItem` is collected for each event that triggers a Worker. For Workers for Platforms customers with a Tail Worker installed on the dynamic dispatch Worker, `events` will contain two elements: one for the dynamic dispatch Worker and one for the user Worker.
```

2023-06-07 16:54 UTC, deadlypants1973 commented on content/workers/runtime-apis/tail-event.md
> +  - An array of [`TailItems`](/workers/runtime-apis/tail-event/#tailitems). One `TailItem` is collected for each event that triggers a Worker. For Workers for Platforms customers with a Tail Worker i
```suggestion
  - An array of [`TailItems`](/workers/runtime-apis/tail-event/#tailitems). One `TailItem` is collected for each event that triggers a Worker. For Workers for Platforms customers with a Tail Worker installed on the dynamic dispatch Worker, `events` will contain two elements: one for the dynamic dispatch Worker and one for the user Worker.
```

2023-07-14 16:19 UTC, deadlypants1973 commented on content/workers/runtime-apis/tail-event.md
> +  - An array of [`TailItems`](/workers/runtime-apis/tail-event/#tailitems). One `TailItem` is collected for each event that triggers a Worker. For Workers for Platforms customers with a Tail Worker i
```suggestion
  - An array of [`TailItems`](/workers/runtime-apis/tail-event/#tailitems). One `TailItem` is collected for each event that triggers a Worker. For Workers for Platforms customers with a Tail Worker installed on the dynamic dispatch Worker, `events` will contain two elements: one for the dynamic dispatch Worker and one for the User Worker.
```

2023-07-14 16:36 UTC, merged