Update common-policies.md
cloudflare/cloudflare-docs pull request #9073
Opened 2023-05-24 13:06 UTC by maesoser

Added an end of line regex symbol `$` to the TLD example in order to block:

```
domain.fail
```

but avoid unintended blocks like:

```
domain.fail.com
```

2023-07-18 15:28 UTC, maxvp approved these changes

2023-07-18 15:34 UTC, maxvp commented
The regex for catching unintended blocks was implemented [here](https://developers.cloudflare.com/cloudflare-one/policies/filtering/dns-policies/common-policies/#block-top-level-domains).

2023-07-18 16:05 UTC, maxvp requested changes
This PR is no longer necessary.

2023-07-18 16:05 UTC, closed without merging

2023-07-19 12:28 UTC, samirbani commented
في الثلاثاء، ١٨ يوليو ٢٠٢٣ ٧:٠٥ م Max Phillips ***@***.***>
كتب:

> Closed #9073 <https://github.com/cloudflare/cloudflare-docs/pull/9073>.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/cloudflare/cloudflare-docs/pull/9073#event-9852440115>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AWV6NCQXPQTIKZIAXZ5P4ZTXQ2X5VANCNFSM6AAAAAAYNLNMF4>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***
> com>
>