[ZT] UDP regional services warning
cloudflare/cloudflare-docs pull request #9192
Opened 2023-06-01 21:39 UTC by maxvp

2023-06-01 23:10 UTC, tlozoot requested changes

2023-06-01 23:10 UTC, tlozoot commented on content/data-localization/_index.md
> +DLS does not support UDP traffic with Cloudlfare Secure Web Gateway.  prevent traffic bypass, disable UDP in your account and [disable QUIC](/cloudflare-one/policies/filtering/http-policies/http3/#pr
I'm confused by what the second sentence is saying here (and it's missing capitalization I think?)

Can you take another pass at that?

2023-06-02 20:41 UTC, kodster28 approved these changes

2023-06-02 21:38 UTC, tlozoot approved these changes

2023-06-02 21:41 UTC, merged