[Logs] Adding information about Logpush updates
cloudflare/cloudflare-docs pull request #920
Opened 2021-03-10 16:16 UTC by crwaters16

PR currently open for the [HTTP field updates](https://github.com/cloudflare/cloudflare-docs/pull/355) - waiting for resolution on that before updating those docs.

2021-03-10 23:09 UTC, tlozoot approved these changes
Thanks, this looks good! We can follow up with docs on specific fields.

Definitely would like @soheiokamoto and @jherre to review as well before we merge.

2021-03-11 00:36 UTC, soheiokamoto requested changes

2021-03-11 00:36 UTC, soheiokamoto commented on products/logs/src/content/log-fields/_partials/spectrum_events.md
> +| ClientTlsCipher | The cipher negotiated between the client and Spectrum. In v1, an unknown cipher returned as “Unknown.” In v2, it’s returned as “UNK.” | string |
Any changes under `products/logs/src/content/log-fields/_partials/` must be done on the internal `logshare-api` repo, otherwise any change here will be lost (as the contents of these files are based on the templates there).

2021-03-11 14:31 UTC, crwaters16 commented on products/logs/src/content/log-fields/_partials/spectrum_events.md
> +| ClientTlsCipher | The cipher negotiated between the client and Spectrum. In v1, an unknown cipher returned as “Unknown.” In v2, it’s returned as “UNK.” | string |
Thanks Sohei, didn't know that - I'll revert the changes here and add to logshare-api!

2021-03-12 21:51 UTC, soheiokamoto commented on products/logs/src/content/log-fields/_partials/spectrum_events.md
> +| ClientTlsCipher | The cipher negotiated between the client and Spectrum. In v1, an unknown cipher returned as “Unknown.” In v2, it’s returned as “UNK.” | string |
Let me know how I can help or we can facilitate.
CC: @tlozoot

2021-03-12 21:53 UTC, soheiokamoto approved these changes

2021-03-15 14:19 UTC, abracchi-tw approved these changes

2021-03-15 14:23 UTC, merged