Add new section on Rules
cloudflare/cloudflare-docs pull request #923
Opened 2021-03-11 19:25 UTC by pedrosousa

Note: Using an alternate method for defining the tile icon while waiting for a PR merge on `cloudflare-brand-assets`.

2021-03-11 23:18 UTC, dcpena approved these changes
Looks good! Left a few comments that you can address or disregard. :)

2021-03-11 23:18 UTC, dcpena commented on products/rules/src/content/transform/index.md
> +You can configure transform rules in the Cloudflare UI (the dashboard) to perform rewrites at the edge, without reaching your web server.
Should we refer to it simply as the dashboard instead of saying Cloudflare UI?

2021-03-11 23:18 UTC, dcpena commented on products/rules/src/content/transform/manage.md
> +**Transform Rules** is a feature of **Rules** in the Cloudflare UI (dashboard).
Same question here about whether we should call it the dashboard instead of Cloudflare UI.

2021-03-11 23:18 UTC, dcpena commented on products/rules/src/content/transform/index.md
> +To configure Transform Rules from the Cloudflare dashboard, use the **Transform Rules** tab in Rules. For more, see [Manage Transform Rules](/transform/manage).
I'd probably add "information" after "more."

2021-03-11 23:18 UTC, dcpena commented on products/firewall/src/content/cf-firewall-language/functions.md
> +  - Returns `true` when a string (first argument) ends with a given substring (second argument). Returns `false` otherwise.
This might be easier to understand after the first read for a developer, but I was a bit confused after reading the sentence. Would the meaning change or be less helpful if the sentence used either string or first argument and either substring or second argument instead of both? Feel free to disregard if choosing one term doesn't make sense.

2021-03-12 09:46 UTC, pedrosousa commented on products/firewall/src/content/cf-firewall-language/functions.md
> +  - Returns `true` when a string (first argument) ends with a given substring (second argument). Returns `false` otherwise.
It does make sense. I added parameter names to the first name (here and in the other two new functions) to make it clearer.

2021-03-12 10:23 UTC, pedrosousa commented on products/rules/src/content/transform/index.md
> +You can configure transform rules in the Cloudflare UI (the dashboard) to perform rewrites at the edge, without reaching your web server.
Changed it to just "dashboard", except on the first occurrence where I used "Cloudflare dashboard".

2021-03-12 11:08 UTC, helloandre requested changes
I'm checking with the team to make sure this is the structure we want. Please do not merge this yet.

2021-03-29 08:26 UTC, helloandre approved these changes

2021-03-29 08:26 UTC, merged