[Style guide] Grammar and Formatting
cloudflare/cloudflare-docs pull request #9263
Opened 2023-06-06 15:59 UTC by EmTeGo

Created new folder for the style guide and moved over all pages in "grammar and formatting" 

@patriciasantaana

2023-06-06 17:31 UTC, patriciasantaana commented on content/style-guide/_index.md
> +
perhaps a short description that provides an overview might be helpful?

2023-06-06 17:32 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/URLs-and-domain-names.md
> +When referring to a URL in text, do not use the *http://* or *www* with Cloudflare web address. Use the *www* only when referring to URLs outside of Cloudflare. When referring to [Cloudflare.com](clo
```suggestion
When referring to a URL in text, do not use the *http://* or *www* with Cloudflare web address. Use the *www* only when referring to URLs outside of Cloudflare. When referring to [Cloudflare.com](cloudflare.com), use [cloudflare.com](cloudflare.com).
```

2023-06-06 17:33 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/URLs-and-domain-names.md
> +When referring to a URL in text, do not use the *http://* or *www* with Cloudflare web address. Use the *www* only when referring to URLs outside of Cloudflare. When referring to [Cloudflare.com](clo
```suggestion
When referring to a URL in text, do not use the *http://* or *www* with Cloudflare web address. Use the *www* only when referring to URLs outside of Cloudflare. When referring to [Cloudflare.com](https://www.cloudflare.com/), use at [cloudflare.com](https://www.cloudflare.com/).
```

2023-06-06 17:36 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/code-block-guidelines.md
> +To define the syntax highlighting language used for the code block, enter a language name after the first fence. Refer to the List of languages being used in Dev Docs at the end of this page for a li
perhaps you can add a link to the section below for "List of languages..."

2023-06-06 17:37 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/code-block-guidelines.md
> +To define the syntax highlighting language used for the code block, enter a language name after the first fence. Refer to the List of languages being used in Dev Docs at the end of this page for a li
```suggestion
To define the syntax highlighting language used for the code block, enter a language name after the first fence. Refer to the List of languages used in Cloudflare documentation for a list of supported languages.
```

2023-06-06 17:37 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/code-block-guidelines.md
> +Use the `txt` language when there's no appropriate syntax hightlighting (for example, a fragment of an Apache configuration file).
```suggestion
Use the `txt` language when there is no appropriate syntax highlighting (for example, a fragment of an Apache configuration file).
```

2023-06-06 17:38 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/code-block-guidelines.md
> +Use the `txt` language when there's no appropriate syntax hightlighting (for example, a fragment of an Apache configuration file).
avoid contractions

2023-06-06 17:39 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/code-block-guidelines.md
> +JSON example:
it might look nicer to add a header instead of just a body text for "JSON example:"
You can do so by adding after the first ```
---
header: [title]
---

2023-06-06 17:41 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/code-block-guidelines.md
> +Note that the "Copy to clipboard" button (top-right corner of the code block) will copy the entire content, not just what the reader can select.
Notes should be added as an <aside>

2023-06-06 17:42 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/code-block-guidelines.md
> +
```suggestion
```

2023-06-06 17:42 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/code-block-guidelines.md
> +
```suggestion
```

2023-06-06 17:45 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/code-block-guidelines.md
> +~/my-folder $ command-to-run     (where `~` means the home folder of the current user).
this format isn't translating too well on the docs site preview. mind fixing it up?
```suggestion
$ command-to-run
~/my-folder $ command-to-run (where `~` means the home folder of the current user).
```

2023-06-06 17:52 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/code-block-guidelines.md
> +#### For "bash" blocks
the whole section for bash blocks is not rendering well on the docs site

2023-06-06 17:53 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/code-block-guidelines.md
> ++ bash (alias: curl)
would be helpful to add backticks to all these languages 
ex: `bash` (alias: `curl`)

2023-06-06 17:54 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/code-block-guidelines.md
> +## List of languages being used in Dev Docs
```suggestion
## List of languages used in Cloudflare developer documentation
```

2023-06-06 17:55 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/code-block-guidelines.md
> +
```suggestion
```

2023-06-06 17:57 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/code-block-guidelines.md
> +Note: JSON fragments may appear with a red background in GitHub because they're not valid JSON. Make it clear in the documentation that it's a fragment and not an entire piece of valid JSON content.
same comment as above, use an aside for notes

2023-06-06 18:01 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/code-block-guidelines.md
> +These are usually POST requests, and we should provide syntax highlighting for the essential part of the request, which is usually the body.
```suggestion
These are usually `POST` requests, and we should provide syntax highlighting for the essential part of the request, which is usually the body.
```

2023-06-06 18:01 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/code-conventions-and-format.md
> +Use the conventions described in this topic throughout Cloudflare product content.
```suggestion
Use the conventions described below throughout Cloudflare product content.
```

2023-06-06 18:02 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/code-conventions-and-format.md
> +
```suggestion
```

2023-06-06 18:21 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/code-conventions-and-format.md
> +
```suggestion
```

2023-06-06 18:31 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/dates-and-times.md
> +Remember that our readership is international, so keep date formats international.
```suggestion
Since our readership is international, keep date formats international.
```

2023-06-06 18:32 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/dates-and-times.md
> +On February 11th, 2010, the company went public.
perhaps you can make these bullet point examples?

2023-06-06 18:32 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/dates-and-times.md
> +For graphs, charts, and other visual assets use the ISO-8601 (YYYY-MM-DD HH:mm:ss) standard like we do for product content.
```suggestion

For graphs, charts, and other visual assets use the ISO-8601 (YYYY-MM-DD HH:mm:ss) standard.
```

2023-06-06 18:39 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/example-values.md
> ++ 203.0.113.0/24.
add backticks to monospace IPs

2023-06-06 18:39 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/external-references.md
> +When referencing external resources, make sure you're linking to a trustworthy source that is recognized as an authority.
```suggestion
When referencing external resources, ensure that you are linking to a trustworthy source that is recognized as an authority. 
```

2023-06-06 18:43 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/external-references.md
> +Note: When linking to a Cloudflare blog post, sometimes we use only "blog post" for the link text.
another note

2023-06-06 18:43 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/external-references.md
> +- Use the page name if you're linking to a specific page.
remove contractions

2023-06-06 18:47 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/external-references.md
> +CAA is a new DNS resource record type defined in RFC 6844.
```suggestion
For example: CAA is a new DNS resource record type defined in RFC 6844.
```

2023-06-06 18:47 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/external-references.md
> +RFC <number>    (RFC, space, number up to four digits)
```suggestion
Use the following formatting when referencing an RFC: 
RFC <number>    (RFC, space, number up to four digits)
```

2023-06-06 19:00 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/external-references.md
> +To get the link:
I'm debating whether we should make this line into an H3, wdyt?
```suggestion
To get the link:
```

2023-06-06 19:01 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/external-references.md
> +1. Open the following URL and search for the RFC number: https://www.rfc-editor.org/rfc-index.html
```suggestion
1. Go to [RFC Editor](https://www.rfc-editor.org/rfc-index.html) and search for the RFC number. 
```

2023-06-06 19:03 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/file-types-and-extensions.md
> +Referring to file extensions: Upload the `.txt` file to the dashboard.
```suggestion
- Referring to file types: Accepted file formats are JSON and YAML. 
- Referring to file extensions: Upload the `.txt` file to the dashboard.
```

2023-06-06 19:03 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/file-types-and-extensions.md
> +    + ❌Download the `.txt`.
```suggestion
    + ✅ Download the `.txt` file.
    + ❌ Download the `.txt`.
```

2023-06-06 19:03 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/file-types-and-extensions.md
> ++ always specify a noun after mentioning a file extension, e.g. "file" or "file extension". Don't leave the extension hanging
```suggestion
+ always specify a noun after mentioning a file extension, e.g. "file" or "file extension". Do not leave the extension hanging
```

2023-06-06 19:04 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/file-types-and-extensions.md
> +Concatenate the string to a text-based `.pem` file.
```suggestion
- The accepted file formats are YAML (files with a `.yml` or `.yaml` file extension) and JSON (files with a `.json` file extension).
- Additionally, this plist can be wrapped in a `.mobileconfig` file.
- If you'd like to test how this feature works, here is a sample `.csv` file.
- Concatenate the string to a text-based `.pem` file.
```

2023-06-06 19:09 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/footnotes.md
> +We use https://littlefoot.js.org/, which helps us render fancy footnotes in context of what you're talking about (and also are much better for mobile).
this may not be necessary to include

2023-06-06 19:10 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/footnotes.md
> +To implement footnotes, use standard [markdown footnote formatting](https://github.blog/changelog/2021-09-30-footnotes-now-supported-in-markdown-fields/). You can also see an example at https://githu
```suggestion
To implement footnotes, use standard [markdown footnote formatting](https://github.blog/changelog/2021-09-30-footnotes-now-supported-in-markdown-fields/). You can also see an example in the [Load Balancing documentation](https://github.com/cloudflare/cloudflare-docs/blob/production/content/load-balancing/understand-basics/health-details.md?plain=1#L17)
```

2023-06-06 19:13 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/notes-and-other-notation-types.md
> +You can call out product requirements, limitations, and specifications so that users see them loud and clearly.
indent this line so it lines up with the bulleted description

2023-06-06 19:13 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/notes-and-other-notation-types.md
> +Refer to Notes/tips/warnings for details on the Markdown syntax.
where does this lead to? perhaps link?

2023-06-06 19:14 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/numbers-and-units-of-measurement.md
> +    + Like, We've added three more servers.
```suggestion
    + For example: We've added three more servers.
```

2023-06-06 19:14 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/numbers-and-units-of-measurement.md
> +    + Like, if for example the message is 32 bytes long, [...]
```suggestion
    + For example: The message is 32 bytes long, [...]
```

2023-06-06 19:15 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/numbers-and-units-of-measurement.md
> ++ For numbers >= 10, use digits.
perhaps write it out rather than >=
```suggestion
+ For numbers greater than or equal to 10, use digits.
```

2023-06-06 19:19 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/numbers-and-units-of-measurement.md
> ++ See UI Content Guidelines for additional information.
add this line to the end of this section instead and link to the page it's referring to (not the wiki link since we don't wanna put that out here)

2023-06-06 19:21 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/numbers-and-units-of-measurement.md
> ++ Add a noun to indicate what the number measures, and to make clear that you're not using k as an abbreviation for *kilobytes*.
contractions

2023-06-06 19:21 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/numbers-and-units-of-measurement.md
> +Example: On this plan, you are limited to 55k download operations and 20k upload operations per day.
```suggestion
For example: On this plan, you are limited to 55k download operations and 20k upload operations per day.
```

2023-06-06 19:22 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/numbers-and-units-of-measurement.md
> +As nouns:
might be worth making these H3?

2023-06-06 19:22 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/numbers-and-units-of-measurement.md
> +As nouns:
Might be worth making this h3? Same with other sections like "As modifiers of numbers:", etc.
```suggestion
### As nouns: 
```

2023-06-06 19:23 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/numbers-and-units-of-measurement.md
> +Many CPU architectures either don't allow execution of the machine code, which is unaligned in memory (**4 KB** for x86 systems)
```suggestion
Many CPU architectures either do not allow execution of the machine code, which is unaligned in memory (**4 KB** for x86 systems).
```

2023-06-06 19:23 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/numbers-and-units-of-measurement.md
> +In general, it's best to only abbreviate units of measurements when they modify specific quantities/numbers. When you need to abbreviate them:
```suggestion
In general, only abbreviate units of measurements when they modify specific quantities/numbers. When you need to abbreviate them:
```

2023-06-06 19:24 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/numbers-and-units-of-measurement.md
> +    + ❌10 cms
```suggestion
    + ✅ 10 m
    + ❌ 10 m
+ Unit symbols should unaltered in the plural.
    + ✅ 10 cm
    + ❌ 10 cms
```

2023-06-06 19:28 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/numbers-and-units-of-measurement.md
> +    + ❌10 cms
I'm not too keen on using bullet points on these lines but that may just be my preference. Up to you how you format this!

2023-06-06 19:40 UTC, EmTeGo commented on content/style-guide/grammar-and-formatting/external-references.md
> +To get the link:
I think it's too soon after the "Link" heading to make it an H3. If a reader wanted to find how to get the link, they'd still find it easily

2023-06-06 19:46 UTC, EmTeGo commented on content/style-guide/grammar-and-formatting/footnotes.md
> +We use https://littlefoot.js.org/, which helps us render fancy footnotes in context of what you're talking about (and also are much better for mobile).
Yeah I'm not sure either. Kody said it's fine to keep but I can check with others if it's essential. Maybe we'll keep it internal

2023-06-06 19:49 UTC, EmTeGo commented on content/style-guide/grammar-and-formatting/notes-and-other-notation-types.md
> +Refer to Notes/tips/warnings for details on the Markdown syntax.
This will lead to a page in Content Strategy, which would make it a broken link. Should I include a link, hold off on it, or remove the sentence until it leads somewhere?

2023-06-06 19:57 UTC, EmTeGo commented on content/style-guide/grammar-and-formatting/numbers-and-units-of-measurement.md
> ++ See UI Content Guidelines for additional information.
I think we should leave that line out. I checked the wiki page and it's not going to be published. I can't find any other pages to reference in this folder.

2023-06-06 20:09 UTC, EmTeGo commented on content/style-guide/grammar-and-formatting/numbers-and-units-of-measurement.md
> +    + ❌10 cms
Agreed, it takes up too much space as it is. How else would you format it? I was thinking we could have fewer examples instead.

Always include a space between the number and the unit
Unit symbols should unaltered in the plural.

✅10 cm
❌10cms

2023-06-06 20:23 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/parts-of-speech/abbreviations.md
> +Abbreviations include acronyms, initialisms, shortened words, and contractions (in most contexts, the technical distinction between acronyms and initialisms isn’t relevant; it’s fine to use the word
contractions

2023-06-06 20:24 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/parts-of-speech/abbreviations.md
> +**Long and short versions of a word**
might be better to have these bolded lines as headers

2023-06-06 20:24 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/parts-of-speech/abbreviations.md
> +The short versions of the words are not abbreviations, and if you use them, you don't need to put a period after them.
contraction

2023-06-06 20:24 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/parts-of-speech/abbreviations.md
> +If you're not sure whether a word is an abbreviation or just a short version of a longer word, here is a list of [common abbreviations](https://abbreviations.yourdictionary.com/articles/list-of-commo
contraction

2023-06-06 20:26 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/parts-of-speech/abbreviations.md
> +If a standard term in the Cloudflare UI is the long version of a word, use that over the shorter version to maintain consistency and distinctions. For example, customer *applications* on Cloudflare f
```suggestion
If a standard term in the Cloudflare dashboard is the long version of a word, use that over the shorter version to maintain consistency and distinctions. For example, customer *applications* on Cloudflare for Teams are not shortened to *apps*. Depending on the use case, application might be the preferred term, especially due to translation.
```

2023-06-06 20:26 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/parts-of-speech/abbreviations.md
> +**In general, when an abbreviation is likely to be unfamiliar to the audience, spell out the first mention of the term and immediately follow with the abbreviation, in parentheses. For all subsequent
```suggestion
In general, when an abbreviation is likely to be unfamiliar to the audience, spell out the first mention of the term and immediately follow with the abbreviation, in parentheses. For all subsequent mentions of the abbreviation, use the abbreviation by itself.
```

2023-06-06 20:27 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/parts-of-speech/abbreviations.md
> +When deciding to spell out a term, consider your audience. If the majority of your audience is likely to recognize and understand the term, then you don't need to spell it out. For example, if you're
contraction

2023-06-06 20:28 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/parts-of-speech/abbreviations.md
> +Prefer English terms over Latin abbreviations. Don't use i.e. or e.g.; instead, use that is or for example, respectively.
```suggestion
Prefer English terms over Latin abbreviations. Don't use i.e. or e.g.; instead, use **that is** or **for example**, respectively.
```

2023-06-06 20:31 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/parts-of-speech/abbreviations.md
> +One exception: avoid both etc. and and so on wherever possible, but if you really need to use one, use etc. Always include the period, even if a comma follows immediately after.
```suggestion
One exception: avoid both *etc.* and *and so on* wherever possible, but if you really need to use one, use *etc.* Always include the period, even if a comma follows immediately after.
```

2023-06-06 20:31 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/parts-of-speech/abbreviations.md
> +Don't use internet slang abbreviations such as tl;dr, IMO, FYI, or others. Write out what you mean in a non-figurative way.
```suggestion
Do not use internet slang abbreviations such as tl;dr, IMO, FYI, or others.
```

2023-06-06 20:32 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/parts-of-speech/abbreviations.md
> ++ Don't use periods with acronyms or initialisms.
```suggestion
+ Do not use periods with acronyms or initialisms.
```

2023-06-06 20:46 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/parts-of-speech/abbreviations.md
> ++ Don't use a period with an abbreviation for the name of a country, US state, or the District of Columbia (DC).
contractions

2023-06-06 20:48 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/parts-of-speech/abbreviations.md
> +    Use this when introducing examples for something you've just mentioned. It's like saying "for example", or "like".
```suggestion
    Use this when introducing examples for something you have just mentioned. This is similar to "for example", or "like".
```

2023-06-06 20:52 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/parts-of-speech/abbreviations.md
> +    Yes, it still works! ✅
```suggestion
    
    Yes, it still works! ✅
```

2023-06-06 20:52 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/parts-of-speech/abbreviations.md
> +    Yes, it still works! ✅
add a line break to make sure it's not right next to the sentence. otherwise, it ends up being on just one line and looks weird on dev docs site

2023-06-06 20:58 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/parts-of-speech/anthropomorphisms.md
> +Avoid Anthropomorphisms in product content. Anthropomorphism is attributing human characteristics to inanimate objects. Computers don't think, want, worry, or do other things that are uniquely human.
```suggestion
Avoid Anthropomorphisms in product content. Anthropomorphism is attributing human characteristics to inanimate objects. Computers do not think, want, worry, or do other things that are uniquely human.
```

2023-06-06 21:00 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/parts-of-speech/capitalization.md
> +|Correct|Incorrect|Rationale|
might be better to match the format of this table to the one above

2023-06-06 21:01 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/parts-of-speech/compound-words.md
> +Change your nameservers to Cloudflare's.
make it apparent that these lines are examples

2023-06-06 21:01 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/parts-of-speech/compound-words.md
> +
```suggestion
```

2023-06-06 21:01 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/parts-of-speech/compound-words.md
> +
```suggestion
```

2023-06-06 21:02 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/parts-of-speech/compound-words.md
> +See these examples:
i think we can make this into a header so its apparent that the sections below contain examples

2023-06-06 21:07 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/parts-of-speech/compound-words.md
> +See these examples:
same comment as above

2023-06-06 21:09 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/parts-of-speech/nouns-and-pronouns.md
> +**First Person**
make these H3s instead?

2023-06-06 21:14 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/parts-of-speech/possessives.md
> +In general, avoid the 's construction to show possession by an inanimate object as doing so personifies the object. For example, *the device's address*.
```suggestion
In general, avoid the 's construction to show possession by an inanimate object as doing so personifies the object. 

For example, *the device's address*.
```

2023-06-06 21:15 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/parts-of-speech/prepositions.md
> +You can put a preposition at the end of a sentence, but don't do it a lot. Your sentences can sound stilted if you try to avoid putting the preposition at the end.
```suggestion
You can put a preposition at the end of a sentence, but do not do it often. Your sentences can sound stilted if you try to avoid putting the preposition at the end.
```

2023-06-06 21:17 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/punctuation-marks-and-symbols/commas.md
> ++ Use the Oxford comma in lists of 3 or more items in a sentence.
```suggestion
+ Use the Oxford comma in lists of three or more items in a sentence.
```

2023-06-06 21:32 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/punctuation-marks-and-symbols/commas.md
> +    + *After you open the file, save it to your desktop with a different name.*
```suggestion
+ Dependent clauses that start a sentence, end with a comma [(learn more)](https://www.dailywritingtips.com/subordinate-clauses-and-commas/).
    + For example: After you open the file, save it to your desktop with a different name.
```

2023-06-06 21:32 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/punctuation-marks-and-symbols/commas.md
> +Incorrect: Stream for Free, Pro and Business plans
make this consistent w/ the other examples

2023-06-06 22:10 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/punctuation-marks-and-symbols/dashes.md
> +Note: never include whitespaces around a hyphen.
note

2023-06-06 22:11 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/punctuation-marks-and-symbols/dashes.md
> +Note: Following AP style guides, and to improve readability, we include whitespaces before and after the em dash.
note

2023-06-06 22:11 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/punctuation-marks-and-symbols/dashes.md
> +
```suggestion
```

2023-06-06 22:13 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/punctuation-marks-and-symbols/quotation-marks.md
> +In general, avoid the 's construction to show possession by an inanimate object as doing so personifies the object. For example, *the device's address*.
```suggestion
In general, avoid the 's construction to show possession by an inanimate object as doing so personifies the object. For example: the device's address.
```

2023-06-06 22:14 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/structure/lists.md
> ++ Bulleted lists for unordered items
keep these bulleted lists consistent with each other

2023-06-06 22:14 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/structure/lists.md
> +However, as with any other aspect of writing, they should be used mindfully. Here's a list of when you should and shouldn't resort to bullet points.
```suggestion
However, as with any other aspect of writing, they should be used mindfully. Below is a list of when you should and shouldn't resort to bullet points.
```

2023-06-06 22:15 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/structure/lists.md
> ++ To list **options**
```suggestion
❌ Don't use bullet points:

+ To outline **processes** (prefer numbered lists)
+ To **explain** your reasoning (it's a blog post, not a list of system requirements)

✅ Use bullet points:

+ To list **facts**
+ To list **data**
+ To list **options**
```

2023-06-06 22:15 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/structure/lists.md
> ++ Instructions should be numbered steps and not bullet points. See How to Write Procedures for additional information.
link to this

2023-06-06 22:17 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/structure/lists.md
> ++ If bullet point items are followed by a description, use a colon after the heading and capitalize the description. For example,
```suggestion
Do not punctuate bullet points unless each item is a full sentence.

If bullet point items are followed by a description, use a colon after the heading and capitalize the description. For example:
```

2023-06-06 22:18 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/structure/lists.md
> ++ See [The best way to use bullet points](https://thewritinghabit.blog/2016/08/22/best-way-to-use-bullet-points/) for additional guidance.
```suggestion
For bullet points, try to stick to the "six-pack" rule: no more than six bullets, each made up of six words or less.

Refer to [The best way to use bullet points](https://thewritinghabit.blog/2016/08/22/best-way-to-use-bullet-points/) for additional guidance.
```

2023-06-06 22:18 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/structure/lists.md
> +Use this checklist
make this a section so this should be a header perhaps?

2023-06-06 22:18 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/structure/lists.md
> +When you find yourself creating a list of bullet points, go through this checklist:
```suggestion

When you find yourself creating a list of bullet points, go through this checklist:
```

2023-06-06 22:19 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/structure/lists.md
> +    + ⚠️Check that all the elements in the list are logically connected.
```suggestion
    + Check that all the elements in the list are logically connected.
```

2023-06-06 22:19 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/structure/lists.md
> +    + ⚠️Check that all the elements in the list are logically connected.
do this for the other points in this section

2023-06-06 22:21 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/structure/lists.md
> +    + ⚠️Readers get lost when reading long lists; at the same time, if you have less than three elements to list, do you really need to use bullet points?
```suggestion
    + ⚠️Readers get lost when reading long lists; at the same time, if you have less than three elements to list, is it necessary to use bullet points?
```

2023-06-06 22:23 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/structure/lists.md
> +    + ⚠️End all elements of a bulleted list with a period if each element is a full sentence; do not add any punctuation if you're just listing nouns or parameters.
```suggestion
    + ⚠️End all elements of a bulleted list with a period if each element is a full sentence; do not add any punctuation if you are listing nouns or parameters.
```

2023-06-06 22:24 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/structure/paragraphs-and-line-breaks.md
> +```
is this supposed to be a markdown table?

2023-06-06 22:24 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/structure/paragraphs-and-line-breaks.md
> +Warning:
aside

2023-06-06 22:26 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/structure/paragraphs-and-line-breaks.md
> +Do not use two spaces at the end of a sentence to create a forced line break. Even though this Markdown syntax is supported, is it not immediately visible and we can easily miss these line breaks dur
```suggestion
Do not use two spaces at the end of a sentence to create a forced line break. Although this Markdown syntax is supported, it is not immediately visible and can easily miss these line breaks during peer reviews.
```

2023-06-06 22:28 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/structure/sentence-structure.md
> +In the UI, keep only what is necessary to convey the message. For example, complete sentences and certain words ("the," for example) are not always necessary.
```suggestion
In the Cloudflare dashboard, keep only what is necessary to convey the message. For example, complete sentences and certain words ("the," for example) are not always necessary.
```

2023-06-06 22:32 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/symbols-in-UI-element-names.md
> +When writing these names or labels in procedural instructions, do not include these symbols. They're usually redundant and can be safely removed.
```suggestion
When writing these names or labels in procedural instructions, do not include these symbols. They are usually redundant and can be safely removed.
```

2023-06-06 22:33 UTC, patriciasantaana commented
some broken links are causing the compiles check to fail

2023-06-06 22:36 UTC, patriciasantaana requested changes
revise based on comments and i can take a look at it once its more put together to review again :)

2023-06-07 14:19 UTC, EmTeGo commented on content/style-guide/grammar-and-formatting/structure/paragraphs-and-line-breaks.md
> +```
Yes, is there a problem with the output? I just tested it and the <br/> tag works with Md

2023-06-07 14:21 UTC, EmTeGo commented on content/style-guide/grammar-and-formatting/structure/lists.md
> +Use this checklist
I'm considering removing "Use this checklist" and just make "Bulleted List Checklist" the H3. Is this a good solution?

2023-06-07 14:23 UTC, EmTeGo commented on content/style-guide/grammar-and-formatting/structure/lists.md
> ++ Instructions should be numbered steps and not bullet points. See How to Write Procedures for additional information.
That page is in Content Strategy, I'll remove the sentence for now until I can have a working link

2023-06-07 14:41 UTC, EmTeGo commented on content/style-guide/grammar-and-formatting/structure/lists.md
> ++ Bulleted lists for unordered items
I'm unsure what you mean on this, could you tell me which list is inconsistent?

2023-06-07 15:43 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/notes-and-other-notation-types.md
> +Refer to Notes/tips/warnings for details on the Markdown syntax.
you can probably hold off on it until you've got a working link. After all, I don't imagine you'd be merging it in its current form yet haha

2023-06-07 15:48 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/numbers-and-units-of-measurement.md
> +    + ❌10 cms
maybe you could format it like the tables that have the correct/incorrect forms? would take up more horizontal space than vertical imo -- and yes to the fewer examples :D

2023-06-07 15:57 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/structure/lists.md
> ++ Bulleted lists for unordered items
i think the main difference i noticed was that this list capitalizes the first word of each line vs other lists don't (ex: the one in File Type and Extensions). I think we can format it to remain consistent with each other

2023-06-07 15:57 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/structure/lists.md
> +Use this checklist
that sounds like a good idea

2023-06-07 15:58 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/structure/paragraphs-and-line-breaks.md
> +```
never mind, it looks good! not sure why the preview was bugging out on me before

2023-06-07 18:20 UTC, EmTeGo commented on content/style-guide/grammar-and-formatting/numbers-and-units-of-measurement.md
> +    + ❌10 cms
I ended up formatting it like the other tables in the page, though I needed to keep the extra row of examples or else the table would be too short

2023-06-16 15:31 UTC, patriciasantaana commented on content/style-guide/_index.md
> +Use this guide when writing any content for product, including the dashboard and elsewhere.
good start on the description but "elsewhere" is a little vague

2023-06-16 15:38 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/URLs-and-domain-names.md
> +When referring to a URL in text, do not use the *http://* or *www* with Cloudflare web address. Use the *www* only when referring to URLs outside of Cloudflare. When referring to [Cloudflare.com](clo
```suggestion
When referring to a URL in text, do not use the `http://` or `www` with Cloudflare web address. Use the `www` only when referring to URLs outside of Cloudflare. When referring to [Cloudflare.com](cloudflare.com), use [cloudflare.com](cloudflare.com).
```

2023-06-16 15:39 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/URLs-and-domain-names.md
> +When referring to a URL in text, do not use the *http://* or *www* with Cloudflare web address. Use the *www* only when referring to URLs outside of Cloudflare. When referring to [Cloudflare.com](clo
backticks _OR_ bold might be better to use to set the "http://" and "www" apart from the rest of the text. It blends in when looking at it from the docs site.

2023-06-16 15:40 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/URLs-and-domain-names.md
> +When referring to a URL in text, do not use the *http://* or *www* with Cloudflare web address. Use the *www* only when referring to URLs outside of Cloudflare. When referring to [Cloudflare.com](clo
Also please fix the broken links! Use https://www.cloudflare.com/ and not just cloudflare.com

2023-06-16 15:44 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/code-block-guidelines.md
> +## Code Block Guidelines (language, command prompts)
page title needs to be H1 and the rest of the headers should follow. So, "Fenced code blocks" should be H2 and so on. FYI: We don't skip headers so what follows H2 needs to be H3 then H4.... 
*Apply to the rest of the pages

2023-06-16 15:47 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/code-block-guidelines.md
> ++ (Recommended) Using triple-acute characters as a "fence" around the code block.
Might just be me but I usually put (recommended) or (optional) at the end of the sentence. Up to your judgment though!

2023-06-16 15:48 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/code-block-guidelines.md
> +To define the syntax highlighting language used for the code block, enter a language name after the first fence. Refer to the [List of languages used in Cloudflare developer documentation](/style-gui
```suggestion
To define the syntax highlighting language used for the code block, enter a language name after the first fence. Refer to the [List of languages used in Cloudflare developer documentation](/style-guide/grammar-and-formatting/code-block-guidelines/#list-of-languages-being-used-in-dev-docs) for a list of supported languages.
```

2023-06-16 15:55 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/code-block-guidelines.md
> +### JSON example:
```suggestion
### JSON example
```

2023-06-16 15:57 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/code-block-guidelines.md
> +{{<Aside type="note">}} The "Copy to clipboard" button (top-right corner of the code block) will copy the entire content, not just what the reader can select.{{</Aside>}}
```suggestion
{{<Aside type="note">}} The **Copy to clipboard** button (top-right corner of the code block) will copy the entire content, not just what the reader can select.{{</Aside>}}
```

2023-06-16 16:03 UTC, EmTeGo commented on content/style-guide/grammar-and-formatting/code-block-guidelines.md
> +## Code Block Guidelines (language, command prompts)
Gotcha, thank you! Will make that change on all the pages.

2023-06-16 16:04 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/code-block-guidelines.md
> +  $ command-to-run
are these two separate examples? there might be a better way to make that stand out

2023-06-16 16:04 UTC, EmTeGo commented on content/style-guide/_index.md
> +Use this guide when writing any content for product, including the dashboard and elsewhere.
Agreed. Should I change it to "dashboard and documentation"? or should I just remove the "elsewhere"

2023-06-16 16:06 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/code-block-guidelines.md
> +#### For "bash" blocks
can you format this section to follow how it looks like on the wiki site? some words are bolded on there but not here.

2023-06-16 16:07 UTC, EmTeGo commented on content/style-guide/grammar-and-formatting/code-block-guidelines.md
> +  $ command-to-run
That's true, they do blend together on the site. Are bullet points a better format? I think a table would be too short.

2023-06-16 16:07 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/code-block-guidelines.md
> +### Notes about JSON code blocks
might be better to move this section above to join the other "code blocks" examples and rename the title to match the 'sh' and 'bash' ones

2023-06-16 16:13 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/code-conventions-and-format.md
> +The > symbol leads you through nested menu items and dialog box options to a final action. The sequence **Options > Settings > General** directs you to pull down the **Options** menu, select the **Se
```suggestion
The > symbol leads you through nested menu items and dialog box options to a final action. The sequence **Options > Settings > General** directs you to pull down the **Options** menu, select the **Settings** item, and select **General** from the last dialog box. Do not use bold formatting for the > symbol.
```

2023-06-16 16:14 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/code-conventions-and-format.md
> +This icon denotes a caution, which advise you to take precautions to avoid injury.
```suggestion
This icon denotes a caution, which advises you to take precautions to avoid injury.
```

2023-06-16 16:18 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/code-conventions-and-format.md
> +Use **bold** when referring to a clickable action or to highlight a title/name/etc in the UI. Bold text denotes items that you must select or click in the software, such as menu items, toggles, and d
```suggestion
Use **bold** when referring to a clickable action or to highlight a title or name in the UI. Bold text denotes items that you must select or click in the software, such as menu items, toggles, and dialog box options. Bold text denotes titles or names that are identifiers in the UI. Bold text also denotes a parameter name. 
```

2023-06-16 16:18 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/code-conventions-and-format.md
> +Use **bold** when referring to a clickable action or to highlight a title/name/etc in the UI. Bold text denotes items that you must select or click in the software, such as menu items, toggles, and d
I feel like this paragraph is a bit repetitive, can you condense it/combine it together?

2023-06-16 16:19 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/code-conventions-and-format.md
> +Do not use for programs.
```suggestion
Do not use **bold** for programs.
```

2023-06-16 16:19 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/code-conventions-and-format.md
> +In nested menus, use bold for the word not the symbol. Example: **Dashboard** > **This** > **That**
```suggestion
In nested menus, use bold for the word not the symbol. 

Example: **Dashboard** > **This** > **That**
```

2023-06-16 16:20 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/code-conventions-and-format.md
> +In nested menus, use bold for the word not the symbol. Example: **Dashboard** > **This** > **That**
We should remain consistent with example lines.
I noticed some pages use "Example:" while others use "For example,"
Wdyt?

2023-06-16 16:21 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/code-conventions-and-format.md
> +Text in this font denotes text or characters that you should enter from the keyboard, sections of code, programming examples, and syntax examples. This font is also used for the proper names of drive
```suggestion
Text in this font denotes text or characters that you should enter from the keyboard, sections of code, programming examples, and syntax examples. This font is also used for the proper names of drives, paths, directories, programs, subprograms, devices, functions, operations, variables, files, API commands, and extensions. 

Examples of elements we monospace:
```

2023-06-16 16:21 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/code-conventions-and-format.md
> +Text in this font denotes text or characters that you should enter from the keyboard, sections of code, programming examples, and syntax examples. This font is also used for the proper names of drive
Perhaps we can make this an H3

2023-06-16 16:26 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/dates-and-times.md
> +### Blogs
```suggestion
### Product Content (including UI)

To account for internationalization and inclusivity of all locales, use the ISO-8601 (YYYY-MM-DD hh:mm:ss) standard when writing dates and times as much as possible.

### Blogs

```

2023-06-16 16:27 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/dates-and-times.md
> +### Blogs
Can we have "(including UI)" integrated into the description sentence below? maybe something like... this includes content in the UI/dashboard

2023-06-16 16:45 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/external-references.md
> +    (RFC, space, number up to four digits)
```suggestion
RFC <number>   
(RFC, space, number up to four digits)
```

2023-06-16 17:03 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/external-references.md
> +4. Use the current URL as the link target in Dev Docs.
```suggestion
4. Use the current URL as the link target in Developer Documentation.
```

2023-06-16 17:08 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/file-types-and-extensions.md
> ++ Referring to file extensions: Upload the `.txt` file to the dashboard.
```suggestion
+ File types: Accepted file formats are JSON and YAML. 
+ File extensions: Upload the `.txt` file to the dashboard.
```

2023-06-16 17:09 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/file-types-and-extensions.md
> +
it might be better if we just make this into one sentence rather than bullet points. Same goes for the other sections below this.

2023-06-16 17:12 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/file-types-and-extensions.md
> ++ Concatenate the string to a text-based `.pem` file.
not sure if this should be labeled examples per se... more like additional notes or misc info

2023-06-16 17:17 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/notes-and-other-notation-types.md
> +    You can provide context for a topic that would be a digression if added directly to the discussion at hand.
```suggestion
Use a **warning** to alert a reader to behavior that could impact the security of a users network or break functionality. You can call out product requirements, limitations, and specifications so that users see them loud and clearly.

Use a **note** to alert a reader to additional useful information that you cannot integrate into the text. You can provide context for a topic that would be a digression if added directly to the discussion at hand.
```

2023-06-16 17:22 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/numbers-and-units-of-measurement.md
> +    + 7,465
I'm thinking there might be a better way to format this. Can you play around with it (with/without bullets, spacing, etc) and see what works best?

2023-06-16 17:24 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/numbers-and-units-of-measurement.md
> +For example: On this plan, you are limited to 55k download operations and 20k upload operations per day.
should be consistent with previous section. this one is not bulleted, while other is. See comment about playing with formatting

2023-06-16 17:32 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/numbers-and-units-of-measurement.md
> +
```suggestion
### As nouns

Fast forward to 2020 and the storage provider landscape has become highly competitive with many providers capable of providing **petabyte** (and **exabyte**) scale content storage at extremely low cost-per-**gigabyte**. 	

### As modifiers of numbers 

```

2023-06-16 17:40 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/parts-of-speech/abbreviations.md
> ++ synchronize and sync
this might work better as just a sentence tbh. like...
Some words have a long version and a short version, such as "application" and "app", "demonstration" and "demo", "synchronize" and "sync".

2023-06-16 17:47 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/parts-of-speech/abbreviations.md
> +When you are not sure which one to use, remember this:
this entire section is a little difficult to read. can you reformat it?

2023-06-16 17:51 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/parts-of-speech/capitalization.md
> +Each product, service, and feature should be properly spelled and capitalized when used in any content, both to ensure consistency across all channels and to differentiate common performance and secu
can you replace the e.g. on here? lol

2023-06-16 17:54 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/parts-of-speech/compound-words.md
> +Some are fairly frequent in our blog posts and product content. For the sake of consistency, we need to follow these conventions when using them:
```suggestion
Whitespace is used in our blog posts and product content. For the sake of consistency, follow these conventions when using them:
```

2023-06-16 17:58 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/parts-of-speech/compound-words.md
> +This allows us to implement **state-of-the-art** security for our customers.
i feel like it might be better to make this into a table like on the wiki page.

2023-06-16 18:00 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/parts-of-speech/nouns-and-pronouns.md
> +Substitute we or I with Cloudflare if you need to represent Cloudflare.
```suggestion
Substitute "we" or "I" with "Cloudflare" if you need to represent Cloudflare.
```

2023-06-16 18:00 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/parts-of-speech/nouns-and-pronouns.md
> +When you give instructions, use the polite command form with the second person you or in special cases they or it.
```suggestion
When you give instructions, use the polite command form with the second person "you" or in special cases "they" or "it".
```

2023-06-16 18:01 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/parts-of-speech/nouns-and-pronouns.md
> +Use you instead of the user when the audience is the user of a Cloudflare product.
```suggestion
Use "you" instead of "the user" when the audience is the user of a Cloudflare product. 
```

2023-06-16 18:02 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/parts-of-speech/possessives.md
> +For example, *the device's address*.
same point I made above. Perhaps we can find a consistent format for examples. Colon or comma?

2023-06-16 18:04 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/punctuation-marks-and-symbols/commas.md
> +    + For example: After you open the file, save it to your desktop with a different name.
dont think these need to be bulleted

2023-06-16 18:06 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/punctuation-marks-and-symbols/dashes.md
> +To express ranges: It takes 24-48 hours for the data to upload.
```suggestion
In compound words: The most up-to-date software can be found here.

To express ranges: It takes 24-48 hours for the data to upload.
```

2023-06-16 18:06 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/punctuation-marks-and-symbols/dashes.md
> ++ Shortcut for PC users: Hold down the Alt key and type 0151
```suggestion
Shortcut for Mac users: Hold down Shift and Option keys, then press the Minus key

Shortcut for PC users: Hold down the Alt key and type 0151
```

2023-06-16 18:07 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/punctuation-marks-and-symbols/dashes.md
> +Cookies provide saved information about a user’s session to establish a “state” — in most cases, identity — as your browser makes a request.
```suggestion
In pairs, in place of parentheses: Cookies provide saved information about a user’s session to establish a “state” — in most cases, identity — as your browser makes a request.
```

2023-06-16 18:07 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/punctuation-marks-and-symbols/dashes.md
> +Embed yourself in the team — the best results will come when trust is built.
```suggestion
Alone, in place of a semicolon or colon: Embed yourself in the team — the best results will come when trust is built.

```

2023-06-16 18:08 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/punctuation-marks-and-symbols/dashes.md
> +Additional examples:
maybe move "Additional examples:" out of the note block to join the table below

2023-06-16 18:10 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/punctuation-marks-and-symbols/quotation-marks.md
> +In general, avoid the 's construction to show possession by an inanimate object. Doing so personifies the object. For example: the device's address.
```suggestion
In general, avoid the 's construction to show possession by an inanimate object. Doing so personifies the object. 

For example: the device's address.
```

2023-06-16 18:18 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/structure/lists.md
> ++ To list **options**
maybe we can make this into a table like the others similar to it? wdyt

2023-06-16 18:21 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/structure/tables.md
> +Using tables to simplify content and data provides a comprehensive way to arrange design, structure, outlines, pattern, or order. It is a great tool for comparisons, breakdowns, lists, functions, and
```suggestion
Using tables to simplify content and data provides a comprehensive way to arrange design, structure, outlines, pattern, or order. It is a great tool for comparisons, breakdowns, lists, functions, and descriptions. 

Here are some tips when creating tables:
```

2023-06-16 18:21 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/structure/tables.md
> ++ Label column headers
```suggestion
+ Label column headers.
```

2023-06-16 18:21 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/structure/tables.md
> +Tables display pieces of information that have some sort of relationship. For example:
```suggestion
Tables display pieces of information that have some sort of relationship. 

For example:
```

2023-06-16 18:23 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/symbols-in-UI-element-names.md
> +    + Keep the symbol in the instructions.
```suggestion
**The button has no text other than the symbol (For example, just "+")**. 

    + Keep the symbol in the instructions.

**The button has no text other than the symbol and the instructions are for the UI of a third-party product**.

    + Keep the symbol in the instructions.
```

2023-06-19 14:33 UTC, EmTeGo commented on content/style-guide/grammar-and-formatting/structure/lists.md
> ++ To list **options**
Agreed, will look better as a table

2023-06-19 14:46 UTC, EmTeGo commented on content/style-guide/grammar-and-formatting/parts-of-speech/possessives.md
> +For example, *the device's address*.
You're right, there's some inconsistency with that. I think we stick to colon. It makes sense especially when it's not a complete sentence.

2023-06-19 14:50 UTC, EmTeGo commented on content/style-guide/grammar-and-formatting/parts-of-speech/compound-words.md
> +This allows us to implement **state-of-the-art** security for our customers.
Agreed. I'll remove the headings here and just make it a table comparing the two.

2023-06-19 15:25 UTC, EmTeGo commented on content/style-guide/grammar-and-formatting/parts-of-speech/abbreviations.md
> +When you are not sure which one to use, remember this:
Yeah I'm looking at it now and it needs work. I think that entire section can be cut and the section prior can be amended to reflect these ideas. i.e. vs e.g. starts with "here are the rules" and the next section is "don't forget these rules:"

2023-06-19 18:58 UTC, EmTeGo commented on content/style-guide/grammar-and-formatting/code-conventions-and-format.md
> +In nested menus, use bold for the word not the symbol. Example: **Dashboard** > **This** > **That**
I think "Example:" makes more sense. The comma makes sense in a complete sentence, but we're just listing things most of the time we start off with "Example".

2023-06-23 16:01 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/URLs-and-domain-names.md
> +When referring to a URL in text, do not use the `http://` or `www` with Cloudflare web address. Use the `www` only when referring to URLs outside of Cloudflare. When referring to [Cloudflare.com](htt
I'm thinking it might be better to put the latter mention of cloudflare.com in quotes or something just to make the distinction apparent from the first clause. Wdyt?

2023-06-23 16:20 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/code-conventions-and-format.md
> +In placeholders inside a URL: ``` https://api.cloudflare.com/client/v4/organizations/{organization_identifier}/invites ```
```suggestion
When they are part of a code sample or other string literal, such as in placeholders inside a URL.

Example:

``` https://api.cloudflare.com/client/v4/organizations/{organization_identifier}/invites ```
```

2023-06-23 16:21 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/code-conventions-and-format.md
> +Specify a subsearch that starts with this search command: ``` tag=dns query [search tag=malware]. ```
I don't think you'd need more than one pair of backticks when monospacing one-line phrases.
```suggestion
Specify a subsearch that starts with this search command: `tag=dns query [search tag=malware].`
```

2023-06-23 16:22 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/code-conventions-and-format.md
> +Do not bold use for programs.
```suggestion
Do not use bold for programs.
```

2023-06-23 16:28 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/code-conventions-and-format.md
> +## Examples of elements we monospace:
```suggestion
### Examples of elements we monospace
```

2023-06-23 16:28 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/dates-and-times.md
> +Since our readership is international, keep date formats international.
```suggestion
## Blogs

Since our readership is international, keep date formats international.
```

2023-06-23 16:30 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/file-types-and-extensions.md
> +When referring to a specific file type: always use regular text formatting, write the file type in uppercase, and avoid the initial dot (you are referring to the file type, not the file extension).
```suggestion

When referring to a specific file type, always use regular text formatting, write the file type in uppercase, and avoid the initial dot (you are referring to the file type, not the file extension).
```

2023-06-23 16:30 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/file-types-and-extensions.md
> +When referring to a specific extension: always monospace the file, include a dot, write the extension in lowercase, and always specify a noun after mentioning a file extension (for example: "file" or
```suggestion
When referring to a specific extension, always monospace the file, include a dot, write the extension in lowercase, and always specify a noun after mentioning a file extension (for example: "file" or "file extension"). Do not leave the extension hanging. 
```

2023-06-23 16:35 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/notes-and-other-notation-types.md
> ++ Use a **note** to alert a reader to additional useful information that you cannot integrate into the text. You can provide context for a topic that would be a digression if added directly to the di
```suggestion
Use a **warning** to alert a reader to behavior that could impact the security of a users network or break functionality. You can call out product requirements, limitations, and specifications so that users see them loud and clearly.

Use a **note** to alert a reader to additional useful information that you cannot integrate into the text. You can provide context for a topic that would be a digression if added directly to the discussion at hand.
```

2023-06-23 16:39 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/product-name-and-pluralization.md
> +Cloudflare Workers executes/propagates.
```suggestion
- Cloudflare Pages enables/allows...
- Cloudflare Workers executes/propagates...
```

2023-06-23 16:50 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/parts-of-speech/abbreviations.md
> +    + The median compression ratio achieved by Railgun was 0.65% (**i.e.**, the page was reduced to 0.65% of its size).
```suggestion
**i.e.** stands for **id est**. Quite literally, it means "that is" (that = id, est = is). It can be replaced with "that is" or "in other words".
    + The median compression ratio achieved by Railgun was 0.65% (**i.e.**, the page was reduced to 0.65% of its size).
```

2023-06-23 16:51 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/parts-of-speech/abbreviations.md
> +    + Cloudflare products (**e.g.**, Zero Trust, Magic Transit, etc.) offer network security and reliability.
```suggestion
+ **e.g.** stands for **exempli gratia**. Use this when introducing examples for something you have just mentioned. It can be replaced with "for example", or "like".
+ Cloudflare products (**e.g.**, Zero Trust, Magic Transit, etc.) offer network security and reliability.
```

2023-06-23 16:58 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/punctuation-marks-and-symbols/dashes.md
> +In compound words: The most up-to-date software can be found here.
there might be a better way to differentiate the phrases as examples, wdyt?

2023-06-23 16:59 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/punctuation-marks-and-symbols/dashes.md
> +Alone, in place of a semicolon or colon: Embed yourself in the team — the best results will come when trust is built.
same comment as above for examples

2023-06-23 17:01 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/structure/lists.md
> ++ Refer to [The best way to use bullet points](https://thewritinghabit.blog/2016/08/22/best-way-to-use-bullet-points/) for additional guidance.
```suggestion
Do not punctuate bullet points unless each item is a full sentence.

If bullet point items are followed by a description, use a colon after the heading and capitalize the description. For example,
+ **Item 1**: Description 1
+ **Item 2**: Description 2

For bullet points, try to stick to the "six-pack" rule: no more than six bullets, each made up of six words or less.

Refer to [The best way to use bullet points](https://thewritinghabit.blog/2016/08/22/best-way-to-use-bullet-points/) for additional guidance.
```

2023-06-23 17:09 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/footnotes.md
> +We use https://littlefoot.js.org/, which helps us render fancy footnotes in context of what you're talking about (and also are much better for mobile).
```suggestion
We use https://littlefoot.js.org/, which helps us render fancy footnotes in context of what you are talking about (and also are much better for mobile).
```

2023-06-23 17:31 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/structure/lists.md
> +<table>
The sentences in this table are bolded (if you check it out on the preview link), any way we can only have the table headers be bold?

2023-06-23 17:36 UTC, patriciasantaana commented on content/style-guide/_index.md
> +Use this guide when writing any content for product, including the dashboard and elsewhere.
documentation would be good addition

2023-06-23 17:45 UTC, EmTeGo commented on content/style-guide/grammar-and-formatting/structure/lists.md
> +<table>
Oh yeah I'm not sure why it's like that. I'll see what I can do about it, another one of the HTML tables I did looks just fine

2023-06-26 14:53 UTC, EmTeGo commented on content/style-guide/grammar-and-formatting/URLs-and-domain-names.md
> +When referring to a URL in text, do not use the `http://` or `www` with Cloudflare web address. Use the `www` only when referring to URLs outside of Cloudflare. When referring to [Cloudflare.com](htt
Agreed

2023-06-26 15:02 UTC, EmTeGo commented on content/style-guide/grammar-and-formatting/structure/lists.md
> +<table>
Fixed, wrong tags

2023-06-26 15:10 UTC, EmTeGo commented on content/style-guide/grammar-and-formatting/punctuation-marks-and-symbols/dashes.md
> +Alone, in place of a semicolon or colon: Embed yourself in the team — the best results will come when trust is built.
I rewrote it is: 
Dashes are used in pairs (in place of parenthesis) or alone (in place of a semicolon or colon).
 And put examples afterwards

What do you think? I also considered: Dashes are used in pairs — in place of parenthesis —  or alone — in place of a semicolon or colon. It serves as a good example of it being used, but I think too many dashes makes the sentence confusing.

2023-06-26 15:12 UTC, EmTeGo commented on content/style-guide/grammar-and-formatting/punctuation-marks-and-symbols/dashes.md
> +In compound words: The most up-to-date software can be found here.
Agreed. Putting sentences after "Example" and making the explanations into a sentence

2023-06-26 15:21 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/punctuation-marks-and-symbols/dashes.md
> +In compound words: The most up-to-date software can be found here.
sounds good, i think that's a better way to show these examples

2023-06-26 15:22 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/punctuation-marks-and-symbols/dashes.md
> +Alone, in place of a semicolon or colon: Embed yourself in the team — the best results will come when trust is built.
i think the first one is a good idea since we don't wanna confuse readers on the use of dashes in the page about dashes haha

2023-06-26 16:42 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/parts-of-speech/abbreviations.md
> ++ **i.e.** stands for **id est**. Quite literally, it means "that is" (that = id, est = is). It can be replaced with "that is" or "in other words".
can you indent the examples beneath the i.e./e.g. definitions?

2023-06-26 16:45 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/punctuation-marks-and-symbols/dashes.md
> +{{<Aside type="note">}}
one thing I noticed in comparison to other pages is that some of them list the examples using bullet points, while these ones do not. Perhaps we can keep consistent with it and add them here too?

2023-06-26 16:45 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/punctuation-marks-and-symbols/commas.md
> +Dependent clauses that start a sentence, end with a comma [(learn more)](https://www.dailywritingtips.com/subordinate-clauses-and-commas/)
```suggestion
Dependent clauses that start a sentence, end with a comma. [(Learn more)](https://www.dailywritingtips.com/subordinate-clauses-and-commas/)
```

2023-06-26 16:47 UTC, patriciasantaana commented on content/style-guide/grammar-and-formatting/example-values.md
> ++ `203.0.113.0/24`.
these are example IPs right? So maybe we can add the 
"Example:" line to it too.

2023-06-26 16:52 UTC, EmTeGo commented on content/style-guide/grammar-and-formatting/punctuation-marks-and-symbols/dashes.md
> +{{<Aside type="note">}}
yeah I agree, a few example sentences need bullets

2023-06-26 17:50 UTC, patriciasantaana approved these changes

2023-06-26 17:55 UTC, merged