Remove redundant await in return statement.
cloudflare/cloudflare-docs pull request #930
Opened 2021-03-14 16:23 UTC by mahmoudsultan

Hi all 👋,

I was trying out the Cloudfare service workers and noticed there are some redundant `await` in a couple of return statements so I wanted to open a small PR for those.

2021-03-14 16:30 UTC, a-robinson commented on developers.cloudflare.com/workers-site/index.js
> -    return await getAssetFromKV(event, options)
While some of the `await`s in this PR are redundant, they aren't all. In particular, any time the `return await ...` is wrapped in a try-catch, the `await` is important because it allows rejected promises to be caught. If `getAssetFromKV`'s promise is rejected in the prior version of the code, the `catch` block below will catch the exception. In your new version of the code, it won't.

2021-03-14 16:51 UTC, mahmoudsultan commented on developers.cloudflare.com/workers-site/index.js
> -    return await getAssetFromKV(event, options)
You're right, I completely missed that, thank you.

I've updated the PR undoing some of the changes.

2021-03-16 16:49 UTC, signalnerve commented
hey @a-robinson, do you mind re-reviewing this real quick to check @mahmoudsultan's new changes?

2021-03-17 03:46 UTC, a-robinson commented
@signalnerve I'd rather leave that to you. I don't have much of an opinion on whether the rest of the PR is an improvement or not, I just wanted to call out the changes that definitely made things worse.

2021-07-13 19:43 UTC, lukeed requested changes
A lot of the now-removed `await`s meant that their parent functions are `async function`s for no reason. Left a few notes where this is happening, but may have missed some.

Thanks~!

2021-07-13 19:43 UTC, lukeed commented on products/stream/src/content/uploading-videos/direct-creator-uploads.md
>  async function gatherResponse(response) {
```suggestion
function gatherResponse(response) {
```

2021-07-13 19:43 UTC, lukeed commented on products/workers/src/content/examples/bulk-origin-proxy.md
> -    return await fetch(url.toString(), request)
This parent `handleRequest` function should not be an `async function` anymore.

2021-07-13 19:43 UTC, lukeed commented on products/workers/src/content/examples/cors-header-proxy.md
>      }
```js
reqs.noproxy = () => {
  return fetch("${API_URL}").then(r => r.json())
}
```

2021-07-13 19:43 UTC, lukeed commented on products/workers/src/content/examples/cors-header-proxy.md
>      }
```js
reqs.proxy = () => {
  let href = window.location.origin + "${PROXY_ENDPOINT}?apiurl=${API_URL}"
  return fetch(href).then(r => r.json())
}
```

2021-07-13 19:43 UTC, lukeed commented on products/workers/src/content/examples/country-code-redirect.md
> +    return fetch(request)
This means the parent `redirect` function does not need to be an `async` function

2021-07-13 19:43 UTC, lukeed commented on products/workers/src/content/examples/data-loss-prevention.md
> +  return fetch(SOME_HOOK_SERVER, init)
Parent `postDataBreach` function does not need `async`

2021-07-13 19:43 UTC, lukeed commented on products/workers/src/content/examples/fetch-json.md
> +    return response.text()
Parent `gatherResponse` function does not need `async`

2021-07-13 19:43 UTC, lukeed commented on products/workers/src/content/learning/using-durable-objects.md
>      async fetch(request, env) {
```suggestion
    fetch(request, env) {
```

2021-07-13 19:43 UTC, lukeed commented on products/workers/src/content/tutorials/build-a-qr-code-generator/index.md
>  async function handleRequest(request) {
```suggestion
function handleRequest(request) {
```

2021-07-13 19:43 UTC, lukeed commented on products/workers/src/content/tutorials/build-a-qr-code-generator/index.md
>  async function handleRequest(request) {
Actually this entire file still has extra `async`/`await` keywords throughout. GitHub interface not letting leave comments throughout.

2021-07-15 20:13 UTC, lukeed approved these changes
Sent thru a bad merge conflict by mistake. Otherwise, caught this PR up and addressed my own review comments.

//cc @signalnerve to possibly go over my code changes

2021-07-15 20:24 UTC, signalnerve approved these changes

2021-07-15 21:39 UTC, deadlypants1973 approved these changes

2021-07-15 21:54 UTC, merged