[Workers]: Update Form Submission Tutorial
cloudflare/cloudflare-docs pull request #9335
Opened 2023-06-13 10:37 UTC by lauragift21

This PR updates the tutorial to use latest version of wrangler and module syntax format. 

Part of Quick-wins and #7610

2023-06-13 17:43 UTC, kristianfreeman approved these changes

2023-06-15 13:44 UTC, deadlypants1973 requested changes

2023-06-15 13:44 UTC, deadlypants1973 commented on content/workers/tutorials/handle-form-submissions-with-airtable/index.md
> +## Step 1: Create a form
```suggestion
## 1. Create a form
```
Let's mirror the Get started 1., 2., 3.... format.

2023-06-15 13:44 UTC, deadlypants1973 commented on content/workers/tutorials/handle-form-submissions-with-airtable/index.md
> +## Step 2: Create a serverless function
```suggestion
## 2. Create a Worker
```

2023-06-15 13:44 UTC, deadlypants1973 commented on content/workers/tutorials/handle-form-submissions-with-airtable/index.md
>  To handle the form submission, you will create and deploy a Workers serverless function that parses the incoming form data and prepares it for submission to Airtable.
```suggestion
To handle the form submission, you will create and deploy a Worker that parses the incoming form data and prepares it for submission to Airtable.
```

2023-06-15 13:44 UTC, deadlypants1973 commented on content/workers/tutorials/handle-form-submissions-with-airtable/index.md
`wrangler init` is deprecated and these instructions should be replaced with the C3 instructions in the Get started: developers.cloudflare.com/workers/](https://developers.cloudflare.com/workers/get-started/guide/

2023-06-15 13:44 UTC, deadlypants1973 commented on content/workers/tutorials/handle-form-submissions-with-airtable/index.md
> +## Step 3: Configure an Airtable base
```suggestion
## 3. Configure an Airtable base
```

2023-06-15 13:44 UTC, deadlypants1973 commented on content/workers/tutorials/handle-form-submissions-with-airtable/index.md
> +## Step 4: Submit data to Airtable
```suggestion
## 4. Submit data to Airtable
```

2023-06-15 13:44 UTC, deadlypants1973 commented on content/workers/tutorials/handle-form-submissions-with-airtable/index.md
> +In `index.js`, begin by setting up a Workers handler that can respond to requests. When the URL requested has a pathname of `/submit`, you will handle a new form submission, otherwise, you will redir
Per C3, 'index.js' would've been replaced by 'worker.js'.

2023-06-28 15:15 UTC, deadlypants1973 approved these changes
PCX

2023-07-10 09:52 UTC, merged