[Queues] Update types and Wrangler commands in get-started.md and send-errors-to-r2.md
cloudflare/cloudflare-docs pull request #9363
Opened 2023-06-14 16:31 UTC by kewbish

This PR:
- Updates the `Queue` type to the generic `Queue<T>` in `send-errors-to-r2.md` and `get-started.md`.
- Updates 'Paid Workers' → 'Workers Paid' - I believe this is the updated plan name, and I couldn't find any other instances of 'Paid Workers' in the docs.
- Updates the 'Create a Worker project' section to use the new recommended C3 command as it's what's recommended when running `wrangler init` anyways. Also updates the template code in the code snippets to match the [template code used by C3](https://github.com/cloudflare/workers-sdk/blob/84149640fa032a56d927c167af65c9c5570fccbf/packages/create-cloudflare/templates/simple/ts/src/worker.ts#L28).
- Adds a snippet to add the Queue binding to the `interface Env` in the ['​​Set up your producer Worker'](https://developers.cloudflare.com/queues/get-started/#set-up-your-producer-worker).
- Fixes the `MessageBatch` type from `Error` to `any` in the ['Create your consumer Worker'](https://developers.cloudflare.com/queues/get-started/#5-create-your-consumer-worker) section.
- Updates `wrangler publish` → `wrangler deploy`, which is the new recommended command.

2023-06-14 17:12 UTC, elithrar requested changes
These are great, thanks @kewbish - !

I have a minor comment: we need to make sure the onboarding flow with `create cloudflare` is consistent across all products.

https://github.com/cloudflare/cloudflare-docs/pull/9260 is Kate’s WIP PR for Workers and https://github.com/cloudflare/cloudflare-docs/pull/9346 is my WIP PR for D1.

@deadlypants1973 - we should probably have some of the boilerplate in steps 1 + 2 as partials so they are consistent.

cc @admah @IgorMinar

2023-06-14 17:12 UTC, elithrar commented on content/queues/get-started.md
> +$ npm create cloudflare@2 # or 'yarn create cloudflare'
```suggestion
$ npm create cloudflare@latest # or 'yarn create cloudflare'
```

2023-06-14 17:12 UTC, elithrar commented on content/queues/get-started.md
> +In your terminal, you will be asked a series of questions related to your project. For the question `What type of application do you want to create?`, indicate `"Hello World" script`. For the questio
Need to align with https://github.com/cloudflare/cloudflare-docs/pull/9260

2023-06-14 18:19 UTC, kewbish commented on content/queues/get-started.md
> +In your terminal, you will be asked a series of questions related to your project. For the question `What type of application do you want to create?`, indicate `"Hello World" script`. For the questio
Pushed another commit to reorder some steps and adjust the onboarding steps - let me know if you have any ideas on how to make it more consistent!

2023-06-15 09:28 UTC, deadlypants1973 commented on content/queues/get-started.md
> +This will create a new directory, which will include both a `src/index.ts` Worker script, and a [`wrangler.toml`](/workers/wrangler/configuration/) configuration file. After you create your Worker, y
@kewbish could you check this again? It should be `worker.ts`.

2023-06-15 14:17 UTC, kewbish commented on content/queues/get-started.md
> +This will create a new directory, which will include both a `src/index.ts` Worker script, and a [`wrangler.toml`](/workers/wrangler/configuration/) configuration file. After you create your Worker, y
Good catch, I've renamed all the references to `index.ts`!

2023-07-05 18:07 UTC, elithrar approved these changes

2023-07-05 18:24 UTC, merged