Document commonly used Rust crates and link to examples
cloudflare/cloudflare-docs pull request #9400
Opened 2023-06-15 22:13 UTC by kflansburg

Depends on merge of https://github.com/cloudflare/workers-rs/pull/340 for links to work

2023-06-15 22:14 UTC, kflansburg commented on content/workers/platform/webassembly/javascript.md
> +pcx_content_type: tutorial
I don't really understand what the different layouts do, but previously the Rust and JavaScript layouts were different.

2023-06-15 22:14 UTC, kflansburg commented on content/workers/platform/webassembly/rust/_index.md
>  pcx_content_type: tutorial
Moving this to be a `_index` file seems to remove the right sidebar. Not sure how to keep that?

2023-06-19 23:20 UTC, irvinebroque commented on content/workers/platform/webassembly/rust/crates.md
> +The `reqwest` library can be compiled to Wasm, and hooks into the JavaScript `fetch` API automatically using `wasm-bindgen`.
```suggestion
The [`reqwest` library](https://docs.rs/reqwest/latest/reqwest/) can be compiled to Wasm, and hooks into the JavaScript `fetch` API automatically using `wasm-bindgen`. 
```

I think worthwhile to link to these

2023-06-19 23:20 UTC, irvinebroque commented on content/workers/platform/webassembly/rust/crates.md
> +This document outlines popular Rust crates which have been confirmed to work on Workers when using `workers-rs` (or in some cases just `wasm-bindgen`),
```suggestion
This document outlines popular Rust crates which have been confirmed to work on Workers when using [`workers-rs`](https://github.com/cloudflare/workers-rs) (or in some cases just `wasm-bindgen`), to write Workers in WebAssembly.
```

2023-06-19 23:20 UTC, irvinebroque commented on content/workers/platform/webassembly/rust/crates.md
> +and any custom configuration that was required.
```suggestion
Each example includes any custom configuration that is required.
```

2023-06-19 23:20 UTC, irvinebroque commented on content/workers/platform/webassembly/rust/crates.md
> +This is not an exhaustive list, many Rust crates can be compiled to the `wasm32-unknown-unknown` target that is supported by Workers.
Where should `wasm32-unknown-unknown` link to for people to understand more about this target?

2023-06-19 23:20 UTC, irvinebroque commented on content/workers/platform/webassembly/rust/crates.md
> +consider the addition of new dependencies, as this can significantly increase bundle size.
```suggestion
consider the addition of new dependencies, as this can significantly increase the [size](/workers/platform/limits/#worker-size) of your Worker.
```

2023-06-19 23:20 UTC, irvinebroque commented on content/workers/platform/webassembly/rust/crates.md
> +Many crates which have been made Wasm-friendly, will use the `time` crate instead of `std::time`. For the `time` crate to work in Wasm, the `wasm-bindgen` feature must be enabled to obtain timing inf
```suggestion
Many crates use the `time` crate instead of `std::time`, in order to work more easily in WebAssembly runtimes. For the `time` crate to work in Wasm, the `wasm-bindgen` feature must be enabled to obtain timing information from JavaScript.
```

2023-06-19 23:20 UTC, irvinebroque commented on content/workers/platform/webassembly/rust/crates.md
> +Due to timing limitations on Workers, spans will have identical start and end times unless they encompass I/O.
Link to https://developers.cloudflare.com/workers/learning/security-model/#step-1-disallow-timers-and-multi-threading?

2023-06-20 13:40 UTC, kflansburg commented on content/workers/platform/webassembly/rust/crates.md
> +This is not an exhaustive list, many Rust crates can be compiled to the `wasm32-unknown-unknown` target that is supported by Workers.
Potentially here but I'm not sure how useful it is https://doc.rust-lang.org/rustc/platform-support/wasm64-unknown-unknown.html

2023-06-20 13:43 UTC, kflansburg commented on content/workers/platform/webassembly/rust/crates.md
> +Many crates which have been made Wasm-friendly, will use the `time` crate instead of `std::time`. For the `time` crate to work in Wasm, the `wasm-bindgen` feature must be enabled to obtain timing inf
I'm not sure this is the same meaning:
1. `std::time` does not work at all in Wasm.
2. Its good to call out that not all crates are Wasm-compatible, and will usually have some documented effort of being made compatible.

2023-06-20 13:44 UTC, kflansburg commented on content/workers/platform/webassembly/rust/crates.md
> +Due to timing limitations on Workers, spans will have identical start and end times unless they encompass I/O.
```suggestion
Due to [timing limitations](/workers/learning/security-model/#step-1-disallow-timers-and-multi-threading) on Workers, spans will have identical start and end times unless they encompass I/O.
```

2023-06-20 13:45 UTC, kflansburg commented on content/workers/platform/webassembly/rust/crates.md
> +This is not an exhaustive list, many Rust crates can be compiled to the `wasm32-unknown-unknown` target that is supported by Workers.
```suggestion
This is not an exhaustive list, many Rust crates can be compiled to the [`wasm32-unknown-unknown`](https://doc.rust-lang.org/rustc/platform-support/wasm64-unknown-unknown.html) target that is supported by Workers.
```

2023-06-20 14:57 UTC, irvinebroque approved these changes
🚀

2023-06-20 15:12 UTC, kflansburg commented
@deadlypants1973 do you want to review here?

2023-06-21 16:28 UTC, deadlypants1973 requested changes
PCX

2023-06-21 16:28 UTC, deadlypants1973 commented on content/workers/platform/webassembly/rust/crates.md
> +title: Supported Crates
```suggestion
title: Supported crates
```

2023-06-21 16:28 UTC, deadlypants1973 commented on content/workers/platform/webassembly/rust/crates.md
> +# `workers-rs` Supported Rust Crates
```suggestion
# `workers-rs` supported Rust crates
```

2023-06-21 16:28 UTC, deadlypants1973 commented on content/workers/platform/webassembly/rust/crates.md
> +  title: Supported Crates
```suggestion
  title: Supported crates
```

2023-06-21 16:28 UTC, deadlypants1973 commented on content/workers/platform/webassembly/rust/crates.md
> +[See Example](https://github.com/kflansburg/workers-rs/tree/main/examples/hyper).
This link is broken?

2023-06-21 16:28 UTC, deadlypants1973 commented on content/workers/platform/webassembly/rust/crates.md
> +This document outlines popular Rust crates which have been confirmed to work on Workers when using [`workers-rs`](https://github.com/cloudflare/workers-rs) (or in some cases just `wasm-bindgen`), to
```suggestion

## Background

Learn about popular Rust crates which have been confirmed to work on Workers when using [`workers-rs`](https://github.com/cloudflare/workers-rs) (or in some cases just `wasm-bindgen`), to write Workers in WebAssembly.
```

2023-06-21 16:28 UTC, deadlypants1973 commented on content/workers/platform/webassembly/rust/crates.md
> +Each example includes any custom configuration that is required.
```suggestion
Each Rust crate example includes any custom configuration that is required.
```

2023-06-21 16:28 UTC, deadlypants1973 commented on content/workers/platform/webassembly/rust/crates.md
> +This is not an exhaustive list, many Rust crates can be compiled to the [`wasm32-unknown-unknown`](https://doc.rust-lang.org/rustc/platform-support/wasm64-unknown-unknown.html) target that is support
```suggestion

This is not an exhaustive list, many Rust crates can be compiled to the [`wasm32-unknown-unknown`](https://doc.rust-lang.org/rustc/platform-support/wasm64-unknown-unknown.html) target that is supported by Workers.
```

I am looking at the rendered site when I edit this and we need a paragraph break here imo. It's blocky.

2023-06-21 16:28 UTC, deadlypants1973 commented on content/workers/platform/webassembly/rust/crates.md
> +consider the addition of new dependencies, as this can significantly increase the [size](/workers/platform/limits/#worker-size) of your Worker.
```suggestion
In some cases, this may require disabling default features or enabling a Wasm-specific feature. It is important to consider the addition of new dependencies, as this can significantly increase the [size](/workers/platform/limits/#worker-size) of your Worker.
```

2023-06-21 16:28 UTC, deadlypants1973 commented on content/workers/platform/webassembly/rust/crates.md
> +[See Example](https://github.com/kflansburg/workers-rs/tree/main/examples/tokio-postgres).
Broken link?

2023-06-21 16:28 UTC, deadlypants1973 commented on content/workers/platform/webassembly/rust/crates.md
> +[See Example](https://github.com/kflansburg/workers-rs/tree/main/examples/tokio-postgres).
```suggestion
[Refer to the `tokio-postgres` example](https://github.com/kflansburg/workers-rs/tree/main/examples/tokio-postgres) for more information.
```

2023-06-21 16:28 UTC, deadlypants1973 commented on content/workers/platform/webassembly/rust/crates.md
> +[See Example](https://github.com/kflansburg/workers-rs/tree/main/examples/hyper).
```suggestion
[Refer to the `hyper` example](https://github.com/kflansburg/workers-rs/tree/main/examples/hyper).
```

2023-06-21 16:29 UTC, deadlypants1973 reviewed
PCX

2023-06-21 16:37 UTC, deadlypants1973 commented on content/workers/platform/webassembly/rust/crates.md
> +[See Example](https://github.com/kflansburg/workers-rs/tree/main/examples/tracing).
```suggestion
[Refer to the `tracing` example](https://github.com/kflansburg/workers-rs/tree/main/examples/tracing) for more information.
```

2023-06-21 16:37 UTC, deadlypants1973 commented on content/workers/platform/webassembly/rust/crates.md
> +Many crates which have been made Wasm-friendly, will use the `time` crate instead of `std::time`. For the `time` crate to work in Wasm, the `wasm-bindgen` feature must be enabled to obtain timing inf
Is a GH example link needed here?

2023-06-21 18:32 UTC, kflansburg commented on content/workers/platform/webassembly/rust/crates.md
> +Many crates which have been made Wasm-friendly, will use the `time` crate instead of `std::time`. For the `time` crate to work in Wasm, the `wasm-bindgen` feature must be enabled to obtain timing inf
No, we do not have an example for this crate.

2023-06-21 18:33 UTC, kflansburg commented on content/workers/platform/webassembly/rust/crates.md
> +[See Example](https://github.com/kflansburg/workers-rs/tree/main/examples/tokio-postgres).
Another PR needed to be merged, I will update

2023-06-21 18:33 UTC, kflansburg commented on content/workers/platform/webassembly/rust/crates.md
> +[See Example](https://github.com/kflansburg/workers-rs/tree/main/examples/tracing).
```suggestion
[Refer to the `tracing` example](https://github.com/cloudflare/workers-rs/tree/main/examples/tracing) for more information.
```

2023-06-21 18:34 UTC, kflansburg commented on content/workers/platform/webassembly/rust/crates.md
> +[See Example](https://github.com/kflansburg/workers-rs/tree/main/examples/tokio-postgres).
```suggestion
[Refer to the `tokio-postgres` example](https://github.com/cloudflare/workers-rs/tree/main/examples/tokio-postgres) for more information.
```

2023-06-21 18:35 UTC, kflansburg commented on content/workers/platform/webassembly/rust/crates.md
> +[See Example](https://github.com/kflansburg/workers-rs/tree/main/examples/hyper).
```suggestion
[Refer to the `hyper` example](https://github.com/cloudflare/workers-rs/tree/main/examples/hyper) for more information.
```

2023-06-22 15:35 UTC, deadlypants1973 approved these changes

2023-06-22 15:43 UTC, merged