[Workers]: Update QR Code Generator Tutorial
cloudflare/cloudflare-docs pull request #9414
Opened 2023-06-16 12:24 UTC by lauragift21

This PR updates the tutorial to use latest version of wrangler and module syntax format.

Part of Quick-wins and https://github.com/cloudflare/cloudflare-docs/issues/7610

2023-06-16 12:55 UTC, codewithkristian requested changes

2023-06-16 12:55 UTC, codewithkristian commented on content/workers/tutorials/build-a-qr-code-generator/index.md
> +The `qr-image` package we installed depends on Node.js APIs, for this to work, you need to set the `node_compat` flag in your wrangler configuration file:
Is this true? I don't think we needed this in the past, so I'm not sure we need to add it unless qr-image has changed

2023-06-16 12:55 UTC, codewithkristian commented on content/workers/tutorials/build-a-qr-code-generator/index.md
> +		'<img id="qr" src="#" />',
Confused on this - we should just be returning the qr_png right? And then the client-side HTML loads it and replaces the #qr container with it. As this is currently set up, it will add the entire HTML page into #qr when a new QR code is returned from the Workers fn

2023-06-16 12:55 UTC, codewithkristian commented on content/workers/tutorials/build-a-qr-code-generator/index.md
> +In this tutorial, you built and deployed a Worker application for generating QR codes. If you would like to see the full source code for this application, you can find it [on GitHub](https://github.c
Not sure if we really need to keep the source link, but if we do we should update it to this new example and probably move it into https://github.com/cloudflare/workers-sdk/tree/main/templates

2023-06-16 12:58 UTC, lauragift21 commented on content/workers/tutorials/build-a-qr-code-generator/index.md
> +The `qr-image` package we installed depends on Node.js APIs, for this to work, you need to set the `node_compat` flag in your wrangler configuration file:
I got this error when I tried to use it without the `node_compat` flag. 

```
✘ [ERROR] Could not resolve "zlib"

    node_modules/qr-image/lib/png.js:3:19:
      3 │ var zlib = require('zlib');
        ╵                    ~~~~~~

  The package "zlib" wasn't found on the file system but is built into node.
  Add "node_compat = true" to your wrangler.toml file to enable Node.js compatibility.
```

2023-06-16 12:59 UTC, lauragift21 commented on content/workers/tutorials/build-a-qr-code-generator/index.md
> +The `qr-image` package we installed depends on Node.js APIs, for this to work, you need to set the `node_compat` flag in your wrangler configuration file:
So my guess `qr-image` has some dependencies that relies on Node.js API.

2023-06-16 13:00 UTC, lauragift21 commented on content/workers/tutorials/build-a-qr-code-generator/index.md
> +In this tutorial, you built and deployed a Worker application for generating QR codes. If you would like to see the full source code for this application, you can find it [on GitHub](https://github.c
Yes I added a comment to move it over. I will move over the example and update the link.

2023-06-16 13:20 UTC, lauragift21 commented on content/workers/tutorials/build-a-qr-code-generator/index.md
> +		'<img id="qr" src="#" />',
Right this shouldn't be here.

2023-06-16 14:23 UTC, codewithkristian commented on content/workers/tutorials/build-a-qr-code-generator/index.md
> +The `qr-image` package we installed depends on Node.js APIs, for this to work, you need to set the `node_compat` flag in your wrangler configuration file:
ok cool! thanks

2023-06-16 14:24 UTC, kristianfreeman approved these changes

2023-06-28 15:28 UTC, deadlypants1973 approved these changes
PCX

2023-06-29 11:46 UTC, merged