[Durable Objects] New hibernatable WebSocket auto-response methods
cloudflare/cloudflare-docs pull request #9459
Opened 2023-06-19 18:58 UTC by jqmmes

This commits adds documentation for the new methods introduced to Durable Objects for setting and managing hibernatable WebSockets auto-response.

2023-06-21 10:16 UTC, Maddy-Cloudflare approved these changes

2023-06-21 10:16 UTC, Maddy-Cloudflare commented on content/workers/runtime-apis/durable-objects.md
> +  - Sets and application level auto-response that doesn't unhibernate hibernated WebSockets. `state.setWebSocketAutoResponse` receives a `WebSocketRequestResponsePair(request{{<param-type>}}string{{<
```suggestion
  - Sets and application level auto-response that doesn't unhibernate hibernated WebSockets. `state.setWebSocketAutoResponse` receives a `WebSocketRequestResponsePair(request{{<param-type>}}string{{</param-type>}}, response{{<param-type>}}string{{</param-type>}})` as parameter, making all WebSockets attached to this object reply with response when they received the specified request. The difference between using `setWebSocketAutoResponse()` and setting up a server for ping/pong messages is that `setWebSocketAutoResponse()` enables the ping/pong behavior out-of-the-box and works with hibernated WebSockets without unhibernating them.
```

2023-06-21 17:15 UTC, cacheburner commented on content/workers/runtime-apis/durable-objects.md
> +  - Sets and application level auto-response that doesn't unhibernate hibernated WebSockets. `state.setWebSocketAutoResponse` receives a `WebSocketRequestResponsePair(request{{<param-type>}}string{{<
Sets and -> _Sets an_

2023-06-21 17:15 UTC, cacheburner commented on content/workers/runtime-apis/durable-objects.md
> +  - Sets and application level auto-response that doesn't unhibernate hibernated WebSockets. `state.setWebSocketAutoResponse` receives a `WebSocketRequestResponsePair(request{{<param-type>}}string{{<
doesn't unhibernate hibernated -> _doesn't wake hibernated_

2023-06-21 17:15 UTC, cacheburner commented on content/workers/runtime-apis/durable-objects.md
> +  - Sets and application level auto-response that doesn't unhibernate hibernated WebSockets. `state.setWebSocketAutoResponse` receives a `WebSocketRequestResponsePair(request{{<param-type>}}string{{<
"as parameter" -> "_as an argument_". (argument over parameter because we say "receives a" before).

2023-06-21 17:15 UTC, cacheburner commented on content/workers/runtime-apis/durable-objects.md
> +  - Sets and application level auto-response that doesn't unhibernate hibernated WebSockets. `state.setWebSocketAutoResponse` receives a `WebSocketRequestResponsePair(request{{<param-type>}}string{{<
In "...object reply with response when they received the specified request", I would make `response` and `request` in code blocks.

2023-06-21 17:15 UTC, cacheburner commented on content/workers/runtime-apis/durable-objects.md
> +  - Sets and application level auto-response that doesn't unhibernate hibernated WebSockets. `state.setWebSocketAutoResponse` receives a `WebSocketRequestResponsePair(request{{<param-type>}}string{{<
> "_making all WebSockets attached to this object reply with response when they received the specified request_"

Almost makes it sound like if one websocket receives it, it sends the reply to all connected websockets. IMO it would be better to say _"enabling any WebSocket attached to this object to automatically reply with `response` when it receives the specified `request`"_.

2023-06-21 17:15 UTC, MellowYarker commented on content/workers/runtime-apis/durable-objects.md
> +  - Sets and application level auto-response that doesn't unhibernate hibernated WebSockets. `state.setWebSocketAutoResponse` receives a `WebSocketRequestResponsePair(request{{<param-type>}}string{{<
> The difference between using `setWebSocketAutoResponse()` and setting up a server for ping/pong messages is that `setWebSocketAutoResponse()` enables the ping/pong behavior out-of-the-box and works with hibernated WebSockets without unhibernating them.

How about: 
> `setWebSocketAutoResponse()` is preferable to setting up a server for static ping/pong messages because `setWebSocketAutoResponse()` handles application level ping/pongs without waking the websocket from hibernation, thereby preventing unnecessary duration charges.

2023-06-21 17:15 UTC, MellowYarker commented on content/workers/runtime-apis/durable-objects.md
> +  - Both request and response are limited to 2048 characters each.
Code blocks for `request` and `response`.

2023-06-21 17:15 UTC, cacheburner commented on content/workers/runtime-apis/durable-objects.md
> +  - Gets the most recent `Date` when the WebSocket received an auto-response request, or `null` if the selected WebSocket never received an auto-response request.
nit: selected -> _given_

2023-06-21 17:15 UTC, MellowYarker commented on content/workers/runtime-apis/durable-objects.md
> +- {{<code>}}state.setWebSocketAutoResponse(webSocketRequestResponsePair{{<param-type>}}Object{{</param-type>}}{{<prop-meta>}}optional{{</prop-meta>}}){{</code>}} : {{<type>}}void{{</type>}}
Should clarify that if no value is given, it unsets the current `WebSocketRequestResponsePair` (if one exists).

Also, I think we'd want to change the param type from `Object` to `WebSocketRequestResponsePair`.

2023-06-22 08:39 UTC, Maddy-Cloudflare requested changes
Will need to re-review this PR

2023-06-22 14:33 UTC, jqmmes commented
Thanks @Maddy-Cloudflare and @MellowYarker for the reviews. 
I've updated the docs based on your suggestions and I think they're ready to a second review.
The main changes are grammar corrections, adding code blocks where needed and additional clarification for `state.setWebSocketAutoResponse` when there's not argument passed.

2023-06-22 15:05 UTC, Maddy-Cloudflare approved these changes

2023-06-22 15:05 UTC, Maddy-Cloudflare commented on content/workers/runtime-apis/durable-objects.md
> +  - Sets an application level auto-response that doesn't wake hibernated WebSockets. `state.setWebSocketAutoResponse` receives a `WebSocketRequestResponsePair(request{{<param-type>}}string{{</param-t
```suggestion
  - Sets an application level auto-response that doesn't wake hibernated WebSockets. `state.setWebSocketAutoResponse` receives `WebSocketRequestResponsePair(request{{<param-type>}}string{{</param-type>}}, response{{<param-type>}}string{{</param-type>}})` as an argument, enabling any WebSocket attached to this object to automatically reply with `response` when it receives the specified `request`. `setWebSocketAutoResponse()` is preferable to setting up a server for static ping/pong messages because `setWebSocketAutoResponse()` handles application level ping/pongs without waking the websocket from hibernation, thereby preventing unnecessary duration charges.
```

2023-06-22 16:46 UTC, MellowYarker commented
I'd like to hold off on merging this until we've done some testing in production, you okay to wait on merging until I approve the PR @Maddy-Cloudflare?

2023-06-22 16:50 UTC, Maddy-Cloudflare commented
> I'd like to hold off on merging this until we've done some testing in production, you okay to wait on merging until I approve the PR @Maddy-Cloudflare?

Yep, you can go ahead with testing!

2023-07-05 16:55 UTC, Maddy-Cloudflare commented
> > I'd like to hold off on merging this until we've done some testing in production, you okay to wait on merging until I approve the PR @Maddy-Cloudflare?
> 
> Yep, you can go ahead with testing!

@MellowYarker and @jqmmes has this PR been tested in the end?

2023-07-05 17:00 UTC, MellowYarker commented
@Maddy-Cloudflare The limited deployment window ended today, meaning we will be releasing the latest version of the runtime over the next few days (this code is _not currently in production_). There is still a risk of rollback as this release has more changes than usual, so we need to wait a little longer for things to stabilize before updating docs with a new API.

2023-07-06 09:11 UTC, Maddy-Cloudflare commented
> @Maddy-Cloudflare The limited deployment window ended today, meaning we will be releasing the latest version of the runtime over the next few days (this code is _not currently in production_). There is still a risk of rollback as this release has more changes than usual, so we need to wait a little longer for things to stabilize before updating docs with a new API.

Okay, thanks for letting me know! 😄

2023-07-07 11:28 UTC, jqmmes commented
Updated docs with pricing details regarding messages handled by `state.setWebSocketAutoResponse()`.

2023-07-07 14:17 UTC, jqmmes commented
@MellowYarker, @Maddy-Cloudflare This new api has rolled RoW. Guess we can do a last text review and merge it afterwards.

2023-07-07 16:39 UTC, MellowYarker commented on content/workers/platform/pricing.md
> +4. If an Object is not active while using [`state.acceptWebSocket()`](/workers/runtime-apis/durable-objects/#websockets-hibernation-api), auto-response messages handled by `state.setWebSocketAutoResp
I think this is true if they're active as well, no? We send straight through the kj websocket; no need to touch JS.

Better to say:
> Application level auto-response messages handled by `state.setWebSocketAutoResponse()` will not incur additional wall-clock time, and so they will not be charged.

2023-07-07 16:41 UTC, jqmmes commented on content/workers/platform/pricing.md
> +4. If an Object is not active while using [`state.acceptWebSocket()`](/workers/runtime-apis/durable-objects/#websockets-hibernation-api), auto-response messages handled by `state.setWebSocketAutoResp
Yeah, it's also true if they are active. Updating description.

2023-07-07 16:41 UTC, MellowYarker commented on content/workers/runtime-apis/durable-objects.md
> +  - Sets an application level auto-response that doesn't wake hibernated WebSockets. `state.setWebSocketAutoResponse` receives `WebSocketRequestResponsePair(request{{<param-type>}}string{{</param-typ
> enabling any WebSocket attached to this...

more precise to say:

> enabling any WebSocket that was accepted via `state.acceptWebSocket()` belonging to this...

2023-07-07 16:43 UTC, MellowYarker commented on content/workers/platform/pricing.md
> +4. If an Object is not active while using [`state.acceptWebSocket()`](/workers/runtime-apis/durable-objects/#websockets-hibernation-api), auto-response messages handled by `state.setWebSocketAutoResp
I wonder if the method should also include a variable name like `value` i.e. `state.setWebSocketAutoResponse(value)`, it's kind of a nit but technically if you don't give a value it unsets so it might lead to confusion?

2023-07-07 16:50 UTC, MellowYarker approved these changes

2023-07-07 16:51 UTC, MellowYarker commented
Thanks Joaquim! @Maddy-Cloudflare you can merge if you're happy with this

2023-07-10 10:00 UTC, merged