[Durable Objects - DO NOT MERGE] Make Durable Objects a tile
cloudflare/cloudflare-docs pull request #9477
Opened 2023-06-20 16:35 UTC by Maddy-Cloudflare

PCX-6424

2023-06-20 18:31 UTC, cacheburner commented on content/durable-objects/_index.md
> +Durable Objects are Cloudflare's storage and coordination solution. Durable Objects provide you with scalable compute and permanent, consistent storage. With Durable Objects, you can coordinate reque
> With Durable Objects, you can coordinate requests without accessing the storage.

I would just say "without accessing storage", so drop the "the" (obligatory https://www.youtube.com/watch?v=PEgk2v6KntY :stuck_out_tongue: )

2023-06-20 18:31 UTC, cacheburner commented on content/durable-objects/_index.md
> +Durable Objects come with global uniqueness and transactional storage API that simplifies data access and grants low-latency coordination. You can use Durable Objects to facilitate real-time chat, co
conferecing -> _conferencing_

2023-06-20 18:31 UTC, cacheburner commented on content/durable-objects/api/websockets-api.md
> +title: WebSockets API
@elithrar My sense is we should continue to call this the Hibernatable WebSockets API, if only because we don't support outbound connections with this API and someone who sees this page might think:
1. Regular websockets don't work for DOs
2. There's no way to have an outbound websocket connection from a DO

2023-06-20 18:31 UTC, cacheburner commented on content/durable-objects/api/websockets-api.md
> +#### `webSocketMessage()` handler method
One suggestion I made to Cody was moving the method arguments (in this case `(ws: WebSocket, message: String | ArrayBuffer)`) and moving them into the named handler so it looked like the examples above (ex. `state.getWebSockets()`).  It's not necessary but I always found it a bit weird that we treat handlers differently.

2023-06-20 18:31 UTC, cacheburner commented on content/durable-objects/get-started.md
> +The first parameter passed to the class constructor contains state specific to the Durable Object, including methods for accessing storage. The second parameter, `env`, contains any bindings you have
Since we mention the second param (`env`) by its name, we should do the same for the first param (`state`).

2023-06-20 18:31 UTC, MellowYarker commented on content/durable-objects/get-started.md
> +The fetch handler in the example below implements the Worker that talks to the Durable Object. Note that the fetch handler is written using a new kind of Workers syntax based on ES Modules. This synt
Do we still want to mention this? I feel like it'd be better to just say you need to use ES Modules syntax for scripts that implement DOs, and then as an "Aside" we can mention that calling workers (in other scripts) can be written in Service Worker syntax.

Point being it doesn't seem as important to make this clarification as it might have been earlier during DO open beta (or whenever we started using ES Module syntax). CC @elithrar

2023-06-20 18:31 UTC, MellowYarker commented on content/durable-objects/get-started.md
> +ES Modules differ from regular JavaScript files in that they have imports and exports. When [writing the class that defines a Durable Object](/durable-objects/get-started/#2-write-a-class-that-define
It feels a bit awkward to have this be so directed to the reader (in particular, saying _"you wrote"_ and _"your class"_). I've looked at the "learning DOs" page a number of times without actually writing anything so reading that would slightly interrupt me imo. Can we change it to say _"we wrote"_ and _"our class"_?

2023-06-20 20:18 UTC, elithrar commented on content/durable-objects/platform/limits.md
> +Durable Objects scale well across Objects, but each object is inherently single-threaded. A baseline of 100 req/sec is a good floor estimate of the request rate an individual Object can handle, thoug
```suggestion
Durable Objects is designed to scale horizontally across many objects, but note that each individual object is inherently single-threaded.

An individual object has a soft limit of 1000 requests per second. A simple get on a small value that directly returns the response may realize a higher request throughput.

Correspondingly, an object that (for example) serializes and/or deserializes large JSON values or performs larger `list()` operations may be more limited in terms of request throughput. An object that receives too many requests will, after attempting to queue them, return an [overloaded](/durable-objects/platform/troubleshooting/#error-durable-object-is-overloaded) error to the caller.
```

2023-06-20 22:02 UTC, elithrar commented on content/durable-objects/platform/limits.md
> +|  Storage per account                       | 50 GB (can be raised by contacting Cloudflare)    |
```suggestion
|  Storage per account                       | 50 GB (can be raised by contacting Cloudflare) <sup>1</sup>   |
```

2023-06-20 22:02 UTC, elithrar commented on content/durable-objects/platform/limits.md
> +
```suggestion
* <sup>1</sup> Durable Objects both bills and measures storage based on a gigabyte (1 GB = 1,000,000,000 bytes) and not a gibibyte (GiB).
```

2023-06-21 16:02 UTC, Maddy-Cloudflare commented on content/durable-objects/_index.md
> +Durable Objects are Cloudflare's storage and coordination solution. Durable Objects provide you with scalable compute and permanent, consistent storage. With Durable Objects, you can coordinate reque
```suggestion
Durable Objects are Cloudflare's storage and coordination solution. Durable Objects provide you with scalable compute and permanent, consistent storage. With Durable Objects, you can coordinate requests without accessing storage. 
```

2023-06-21 16:02 UTC, Maddy-Cloudflare commented on content/durable-objects/_index.md
> +Durable Objects come with global uniqueness and transactional storage API that simplifies data access and grants low-latency coordination. You can use Durable Objects to facilitate real-time chat, co
```suggestion
Durable Objects come with global uniqueness and transactional storage API that simplifies data access and grants low-latency coordination. You can use Durable Objects to facilitate real-time chat, collaborative editing, video conferencing, game sessions and more.
```

2023-06-21 16:02 UTC, Maddy-Cloudflare commented on content/durable-objects/get-started.md
> +The first parameter passed to the class constructor contains state specific to the Durable Object, including methods for accessing storage. The second parameter, `env`, contains any bindings you have
```suggestion
The first parameter, `state`, passed to the class constructor contains state specific to the Durable Object, including methods for accessing storage. The second parameter, `env`, contains any bindings you have associated with the Worker when you uploaded it.
```

2023-06-21 16:02 UTC, Maddy-Cloudflare commented on content/durable-objects/get-started.md
> +The fetch handler in the example below implements the Worker that talks to the Durable Object. Note that the fetch handler is written using a new kind of Workers syntax based on ES Modules. This synt
Indeed I would happily remove this bit since we want to migrate to the newer module.

2023-06-21 16:02 UTC, Maddy-Cloudflare commented on content/durable-objects/get-started.md
> +ES Modules differ from regular JavaScript files in that they have imports and exports. When [writing the class that defines a Durable Object](/durable-objects/get-started/#2-write-a-class-that-define
I think the original creator of this doc assumed that the reader would have created the Durable Object class once reached this point of the documentation. 

In the docs we prefer to address the reader to make features relatable to the user.

I would still rewrite this as:

For example, to [write a class that defines a Durable Object](/durable-objects/get-started/#2-write-a-class-that-defines-a-durable-object), you use `export class DurableObjectExample`.

2023-06-21 17:18 UTC, MellowYarker commented on content/durable-objects/get-started.md
> +ES Modules differ from regular JavaScript files in that they have imports and exports. When [writing the class that defines a Durable Object](/durable-objects/get-started/#2-write-a-class-that-define
SGTM!

2023-06-22 13:02 UTC, elithrar commented on content/durable-objects/get-started.md
We should align this with the recently updated D1 tutorial at https://developers.cloudflare.com/d1/get-started/ - e.g.

1. using `create cloudflare` to set up a project.
2. moving any account / subscription requirements into a "Prerequisites" section
3. breaking into it more steps

2023-06-29 15:59 UTC, kodster28 commented on data/durable-objects.yml
> +
Make sure to include the Algolia config here as well (refer to other product tiles for examples)

2023-06-29 16:04 UTC, Maddy-Cloudflare commented on data/durable-objects.yml
> +
Will do. Thanks Kody 😄

2023-06-30 13:57 UTC, elithrar commented on content/durable-objects/api/websockets-api.md
> +title: WebSockets API
Agree ^

2023-06-30 14:01 UTC, elithrar requested changes

2023-06-30 14:01 UTC, elithrar commented on content/durable-objects/api/websockets-api.md
> +{{<beta>}}WebSockets API{{</beta>}}
```suggestion
{{<beta>}}Hibernatable WebSockets API{{</beta>}}
```

2023-06-30 14:01 UTC, elithrar commented on content/durable-objects/api/websockets-api.md
> +Durable Objects WebSockets support includes Cloudflare-specific extensions to the standard WebSocket interface, related methods on the `state` object, and handler methods that a Durable Object can im
```suggestion
Durable Objects WebSockets support includes Cloudflare-specific extensions to the standard WebSocket interface, related methods on the `state` object, and handler methods that a Durable Object can implement for processing WebSocket events.

The Hibernatable WebSocket APIs enable you to terminate (not proxy) WebSocket connections within a Durable Object, and push messages to all connected clients based on state stored within the [Transactional Storage API](/durable-objects/learning/transactional-storage-api/), HTTP fetches to external services, and/or data stored in [R2](/r2/) and [Workers KV](/workers/runtime-apis/kv/).

For WebSocket proxy use-cases, [refer to the standard WebSocket API documentation](/workers/learning/using-websockets/#writing-a-websocket-client).
```

2023-07-11 14:49 UTC, elithrar approved these changes

2023-07-13 15:27 UTC, deadlypants1973 requested changes
PCX 1

2023-07-13 15:27 UTC, deadlypants1973 commented on content/durable-objects/_index.md
> +You can use Durable Objects to facilitate real-time chat, collaborative editing, video conferencing, game sessions and more.
```suggestion
Use Durable Objects to facilitate real-time chat, collaborative editing, video conferencing, game sessions and more.
```

2023-07-13 15:27 UTC, deadlypants1973 commented on content/durable-objects/_index.md
> +A serverless approach to storage and state.
This should change to a sentence that starts with a verb. "Build/create.." etc. Review the Workers, Pages and other landing pages for inspo.

2023-07-13 15:27 UTC, deadlypants1973 commented on content/durable-objects/_index.md
> +Durable Objects come with Hibernatable WebSockets API to help you keep a long-term connection, and Transactional Storage API to simplify data access.
This sentence seems like it is missing some grammar and it needs linkouts to the documentation that talks about these two APIs. 

But also this information is also repeated in features below. I would delete this and add Transactional Storage API to features as well for length.

2023-07-13 15:27 UTC, deadlypants1973 commented on content/durable-objects/_partials/_durable-objects-pricing.md
> +Durable Objects are only available on the Workers Paid plan.
```suggestion
Durable Objects are only available on the [Workers Paid plan](/workers/platform/pricing/#workers).
```

2023-07-13 15:27 UTC, deadlypants1973 commented on content/durable-objects/api/alarms-in-durable-objects.md
> +Alarms are more fine grained than Cron Triggers. A Workers service can have up to three Cron Triggers configured at once, but it can have an unlimited amount of Durable Objects each of which can have
```suggestion
Alarms are more fine grained than [Cron Triggers](/workers/platform/triggers/cron-triggers/). A Worker can have up to three Cron Triggers configured at once, but it can have an unlimited amount of Durable Objects each of which can have an alarm set.
```

2023-07-13 15:27 UTC, deadlypants1973 commented on content/durable-objects/api/alarms-in-durable-objects.md
> +Alarms have guaranteed at-least-once execution and are retried automatically when the `alarm()` handler throws. Retries are performed using exponential backoff starting at a 2 second delay from the f
```suggestion
Alarms have guaranteed at-least-once execution and are retried automatically when the `alarm()` handler throws. Retries are performed using exponential backoff starting at a two (2) second delay from the first failure with up to six (6) retries allowed.
```

2023-07-13 15:27 UTC, deadlypants1973 commented on content/durable-objects/api/alarms-in-durable-objects.md
> +Alarms are directly scheduled from within your Durable Object. Cron Triggers, on the other hand, are not programmatic. Cron Triggers execute based on their schedules, which have to be configured thro
```suggestion
Alarms are directly scheduled from within your Durable Object. Cron Triggers, on the other hand, are not programmatic. [Cron Triggers](/workers/platform/triggers/cron-triggers/) execute based on their schedules, which have to be configured through the Cloudflare dashboard or API.
```

2023-07-13 15:27 UTC, deadlypants1973 commented on content/durable-objects/api/alarms-in-durable-objects.md
> +Alarms can be used to build distributed primitives, like queues or batching of work atop Durable Objects. Alarms also provide a method for guaranteeing work within a Durable Object will complete with
Second sentence ("Alarms also provide a method...") needs rewrite.

2023-07-13 15:27 UTC, deadlypants1973 commented on content/durable-objects/_index.md
> +Durable Objects come with Hibernatable WebSockets API to help you keep a long-term connection, and Transactional Storage API to simplify data access.
```suggestion
```

2023-07-13 15:27 UTC, deadlypants1973 commented on content/durable-objects/_index.md
> +
Add Transactional Storage API here.

2023-07-13 15:27 UTC, deadlypants1973 commented on content/durable-objects/_index.md
> +{{<resource header="Limits" href="/durable-objects/platform/limits/" icon="documentation-clipboard">}}Learn about what limits Durable Objects have and how to work within them.{{</resource>}}
```suggestion
{{<resource header="Limits" href="/durable-objects/platform/limits/" icon="documentation-clipboard">}}Learn about Durable Objects limits.{{</resource>}}
```

2023-07-13 15:27 UTC, deadlypants1973 commented on content/durable-objects/_index.md
> +{{<resource header="Storage options" href="/workers/platform/storage-options/" icon="documentation-clipboard">}}Learn more about the storage and database options you can build on with Workers.{{</res
```suggestion
{{<resource header="Storage options" href="/workers/platform/storage-options/" icon="documentation-clipboard">}}Learn more about storage and database options you can build with Workers.{{</resource>}}
```

2023-07-13 15:27 UTC, deadlypants1973 commented on content/durable-objects/_index.md
> +{{<resource header="@CloudflareDev" href="https://twitter.com/cloudflaredev" icon="twitter">}}Follow @CloudflareDev on Twitter to learn about product announcements, and what is new in Cloudflare Work
```suggestion
{{<resource header="@CloudflareDev" href="https://twitter.com/cloudflaredev" icon="twitter">}}Follow @CloudflareDev on Twitter to learn about product announcements, and what is new in Cloudflare Developer Platform.{{</resource>}}
```

2023-07-13 15:27 UTC, deadlypants1973 commented on content/durable-objects/_partials/_durable-objects-pricing.md
> +1.  Duration is billed in wall-clock time as long as the Object is active, but is shared across all requests active on an Object at once. Once your Object finishes responding to all requests, it will
```suggestion
1.  Duration is billed in wall-clock time as long as the Object is active. Duration is shared across all requests active on an Object at once. Once your Object finishes responding to all requests, it will stop incurring duration charges. Calling `.accept()` on a WebSocket in an Object will incur duration charges for the entire time the WebSocket is connected. If you prefer, use [`state.acceptWebSocket()`](/workers/runtime-apis/durable-objects/#websockets-hibernation-api) instead, which will stop incurring duration charges once all event handlers finish running.
```
"Prefer using..." did not read correctly? Please check that the correction is accurate.

2023-07-13 15:27 UTC, deadlypants1973 commented on content/durable-objects/_partials/_durable-objects-pricing.md
> +3.  Requests including all incoming HTTP requests, WebSocket messages, and alarm invocations. There is no charge for outgoing WebSocket messages, nor for incoming [WebSocket protocol pings](https://w
```suggestion
3.  Requests include all incoming HTTP requests, WebSocket messages, and alarm invocations. There is no charge for outgoing WebSocket messages, nor for incoming [WebSocket protocol pings](https://www.rfc-editor.org/rfc/rfc6455#section-5.5.2).
```
Requests include? This seems like an incomplete sentence.

2023-07-13 15:27 UTC, deadlypants1973 commented on content/durable-objects/_partials/_durable-objects-pricing.md
> +1.  A request unit is defined as 4 KB of data read or written. A request that writes or reads more than 4 KB will consume multiple units, for example, a 9 KB write will consume 3 write request units.
```suggestion
1.  A request unit is defined as 4 KB of data read or written. A request that writes or reads more than 4 KB will consume multiple units. For example, a 9 KB write will consume 3 write request units.
```

2023-07-13 15:27 UTC, deadlypants1973 commented on content/durable-objects/_partials/_durable-objects-pricing.md
> +2.  List operations are billed by read request units, based on the amount of data examined, for example, a list request that returns a combined 80 KB of keys and values will be billed 20 read request
```suggestion
2.  List operations are billed by read request units, based on the amount of data examined. For example, a list request that returns a combined 80 KB of keys and values will be billed 20 read request units. A list request that does not return anything is billed for 1 read request unit.
```

2023-07-13 15:27 UTC, deadlypants1973 commented on content/durable-objects/_partials/_durable-objects-pricing.md
> +3.  Delete requests are unmetered, for example, deleting a 100 KB value will be charged one delete request.
```suggestion
3.  Delete requests are unmetered. For example, deleting a 100 KB value will be charged one delete request.
```

2023-07-13 15:27 UTC, deadlypants1973 commented on content/durable-objects/api/alarms-in-durable-objects.md
> +The `alarm()` handler has guaranteed at-least-once execution and will be retried upon failure using exponential backoff, starting at 2 seconds delay for up to 6 retries. Retries will be performed if
```suggestion
The `alarm()` handler has guaranteed at-least-once execution and will be retried upon failure using exponential backoff, starting at two (2) second delays for up to six (6) retries. Retries will be performed if the method fails with an uncaught exception. Calling `deleteAlarm()` inside the `alarm()` handler may prevent retries on a best-effort basis, but is not guaranteed. 
```

2023-07-13 15:27 UTC, deadlypants1973 commented on content/durable-objects/api/alarms-in-durable-objects.md
> +The method takes no parameters, does not return a result, and can be `async`.
What method? Proper noun here.

2023-07-13 15:27 UTC, deadlypants1973 commented on content/durable-objects/api/alarms-in-durable-objects.md
> +## How to use the `alarm()` handler method
```suggestion
## Use the `alarm()` handler method
```

2023-07-13 15:27 UTC, deadlypants1973 commented on content/durable-objects/api/alarms-in-durable-objects.md
> +This example implements an `alarm()` handler that wakes the Durable Object up once every 10 seconds to batch requests to a single Durable Object. The `alarm()` handler will delay processing until the
```suggestion
This example implements an `alarm()` handler that wakes the Durable Object up once every 10 seconds to batch requests to a single Durable Object. The `alarm()` handler will delay processing until there is enough work in the queue.
```

2023-07-13 15:27 UTC, deadlypants1973 commented on content/durable-objects/api/hibernatable-websockets-api.md
> +Durable Objects WebSockets support includes Cloudflare-specific extensions to the standard WebSocket interface, related methods on the `state` object, and handler methods that a Durable Object can im
```suggestion
Durable Objects WebSockets support includes:

* Cloudflare-specific extensions to the standard WebSocket interface.
* Related methods on the `state` object. 
* Handler methods that a Durable Object can implement for processing WebSocket events.
```

2023-07-13 15:27 UTC, deadlypants1973 commented on content/durable-objects/api/hibernatable-websockets-api.md
> +For WebSocket proxy use-cases, [refer to the standard WebSocket API documentation](/workers/learning/using-websockets/#writing-a-websocket-client).
```suggestion
For WebSocket proxy use-cases, refer to the [standard WebSocket API documentation](/workers/learning/using-websockets/#writing-a-websocket-client).
```

2023-07-13 15:27 UTC, deadlypants1973 commented on content/durable-objects/api/hibernatable-websockets-api.md
> +  - Adds a WebSocket to the set attached to this object. `ws.accept()` must not have been called separately. Once called, any incoming messages will be delivered by calling the Durable Object's `webS
"Adds a WebSocket to the set attached to this object." Is this a Durable Object? Then it should be capitalized. All info being merged should make really clear when it's stating an Object and an object. CTRL + F the word object to be sure about this.

2023-07-13 15:27 UTC, deadlypants1973 commented on content/durable-objects/api/hibernatable-websockets-api.md
> +  - After calling `ws.accept()`, the WebSocket is accepted. Therefore, you can use its `send()` and `close()` methods to send messages. Its `addEventListener()` method won't ever receive any events a
```suggestion
  - After calling `ws.accept()`, the WebSocket is accepted. Therefore, you can use its `send()` and `close()` methods to send messages. Its `addEventListener()` method will not ever receive any events as they will be delivered to the Durable Object. 
```
What is 'its' here? The WebSocket? The method? Proper noun needed.

2023-07-13 15:27 UTC, deadlypants1973 commented on content/durable-objects/api/hibernatable-websockets-api.md
> +  - Sets an application level auto-response that doesn't wake hibernated WebSockets.
```suggestion
  - Sets an application level auto response that does not wake hibernated WebSockets. 
```

2023-07-13 15:27 UTC, deadlypants1973 commented on content/durable-objects/api/hibernatable-websockets-api.md
> +  - `state.setWebSocketAutoResponse` receives `WebSocketRequestResponsePair(request{{<param-type>}}string{{</param-type>}}, response{{<param-type>}}string{{</param-type>}})` as an argument, enabling
object or Object?

2023-07-13 15:27 UTC, deadlypants1973 commented on content/durable-objects/api/hibernatable-websockets-api.md
> +  - If `state.setWebSocketAutoResponse()` is set without any argument, it will remove any previously set auto-response configuration. Doing so, will stop an actor from replying with `response` for a
```suggestion
  - If `state.setWebSocketAutoResponse()` is set without any argument, it will remove any previously set auto-response configuration. Setting `state.setWebSocketAutoResponse()` without any argument will stop an actor from replying with `response` for a `request`. It will also stop updating the last timestamp of a `request`, but if there was any auto-response timestamp set, it will remain accessible with `state.getWebSocketAutoResponseTimestamp()`.
```
Name the action that produces the consequence in the second sentence.

2023-07-13 15:27 UTC, deadlypants1973 commented on content/durable-objects/api/hibernatable-websockets-api.md
> +  - Gets the `WebSocketRequestResponsePair(request{{<param-type>}}string{{</param-type>}}, response{{<param-type>}}string{{</param-type>}})` currently set, or `null` if there's none.
```suggestion
  - Gets the `WebSocketRequestResponsePair(request{{<param-type>}}string{{</param-type>}}, response{{<param-type>}}string{{</param-type>}})` currently set, or `null` if there is none. 
```

2023-07-13 15:27 UTC, deadlypants1973 commented on content/durable-objects/api/hibernatable-websockets-api.md
> +
```suggestion
```

2023-07-13 15:27 UTC, deadlypants1973 commented on content/durable-objects/api/transactional-storage-api.md
> +```js
Need a description of what this code block is.

2023-07-13 15:27 UTC, deadlypants1973 commented on content/durable-objects/api/transactional-storage-api.md
> +    - If true, then the key/value will not be inserted into the in-memory cache. If the key is already in the cache, the cached value will be returned, but its last-used time will not be updated. Use
```suggestion
    - If true, then the key/value will not be inserted into the in-memory cache. If the key is already in the cache, the cached value will be returned, but its last-used time will not be updated. Use this when you expect this key will not be used again in the near future. This flag is only a hint. This flag will never change the semantics of your code, but it may affect performance.
```

2023-07-13 15:27 UTC, deadlypants1973 commented on content/durable-objects/api/transactional-storage-api.md
> +  - Note that enabling this does not change the meaning of `start`, `startKey`, or `endKey`. `start` still defines the smallest key in lexicographic order that can be returned (inclusive), effectivel
```suggestion
  - Note that enabling this does not change the meaning of `start`, `startKey`, or `endKey`. `start` still defines the smallest key in lexicographic order that can be returned (inclusive), effectively serving as the endpoint for a reverse-order list. `end` still defines the largest key in lexicographic order that the list should consider (exclusive), effectively serving as the starting point for a reverse-order list.
```
"enabling this" -> what is 'this'?

2023-07-13 15:27 UTC, deadlypants1973 commented on content/durable-objects/api/transactional-storage-api.md
> +      </aside>
Maybe a formatting thing I am not aware of but can this not be written as a standard aside?

2023-07-13 15:27 UTC, deadlypants1973 commented on content/durable-objects/api/transactional-storage-api.md
> +  - Sets the current alarm time, accepting either a JS Date, or integer milliseconds since epoch.
Is this talking abouta JavaScript `Date`? https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date 

Needs proper formatting.

2023-07-13 15:27 UTC, deadlypants1973 commented on content/durable-objects/api/transactional-storage-api.md
> +- [Durable Objects: Easy, Fast, Correct – Choose Three](https://blog.cloudflare.com/durable-objects-easy-fast-correct-choose-three/).
Probably the Hibernatable WebSockets API should be linked here?

2023-07-13 15:27 UTC, deadlypants1973 commented on content/durable-objects/get-started.md
> +This guide assumes you already have a Cloudflare account. If you do not have a Cloudflare account, [sign up](/fundamentals/account-and-billing/account-setup/create-account/) before continuining.
```suggestion
```

2023-07-13 15:27 UTC, deadlypants1973 commented on content/durable-objects/get-started.md
> +## Prerequisites
See the prerequisites partial in the Workers docs.

2023-07-13 15:27 UTC, deadlypants1973 commented on content/durable-objects/get-started.md
> +You can enable Durable Objects for your account by purchasing Workers paid plan.
```suggestion
Enable Durable Objects for your account by purchasing the Workers Paid plan:
```

2023-07-13 15:27 UTC, deadlypants1973 commented on content/durable-objects/get-started.md
> +If you don't use JavaScript, you will need a [shim](https://developer.mozilla.org/en-US/docs/Glossary/Shim) to translate your class definition to a JavaScript class.
```suggestion
If you do not use JavaScript, you will need a [shim](https://developer.mozilla.org/en-US/docs/Glossary/Shim) to translate your class definition to a JavaScript class.
```

2023-07-13 15:27 UTC, deadlypants1973 commented on content/durable-objects/get-started.md
> +HTTP requests received by a Durable Object do not come directly from the Internet. They come from other Worker code – possibly other Durable Objects, or just plain Workers. Durable Objects use HTTP f
```suggestion
HTTP requests received by a Durable Object do not come directly from the Internet. They come from other Worker code – possibly other Durable Objects, or Workers. Durable Objects use HTTP for familiarity, but plan to introduce other protocols in the future.
```

2023-07-13 15:27 UTC, deadlypants1973 commented on content/durable-objects/get-started.md
> + ## 1. Write a class to define a Durable Object
Is the user creating a Worker in this step? Where do they "export an ordinary JavaScript class"? What files are being written and what commands are being run?

2023-07-13 15:27 UTC, deadlypants1973 commented on content/durable-objects/get-started.md
> +You can configure Durable Object bindings in the `wrangler.toml` by providing the class name and script name whose objects you wish to access using the binding. The script name can be omitted when cr
```suggestion
Configure Durable Object [bindings](/workers/platform/bindings/) in the `wrangler.toml` by providing the class name and script name whose objects you wish to access using the binding. The script name can be omitted when creating a binding for a class that is defined in the same Worker as the binding.
```
Where did the `wrangler.toml` come from? What is the `wrangler.toml`? When was a Worker created? This is all unclear.

2023-07-13 15:27 UTC, deadlypants1973 commented on content/durable-objects/get-started.md
> +  { name = "EXAMPLE_CLASS", class_name = "DurableObjectExample" } # Binding to our DurableObjectExample class
Step 1 did not make it clear that a DurableObjectExample needs to be created to be used in step 2.

2023-07-13 15:27 UTC, deadlypants1973 commented on content/durable-objects/get-started.md
> +```js
Filename needed.

2023-07-13 15:27 UTC, deadlypants1973 commented on content/durable-objects/get-started.md
> +```js
Filename needed.

2023-07-13 15:27 UTC, deadlypants1973 commented on content/durable-objects/get-started.md
> +If you are using Wrangler [environments](/workers/wrangler/environments/), you must specify any Durable Object bindings you wish to use on a per-environment basis.
Useful info but is this get started guide material?

2023-07-13 15:27 UTC, deadlypants1973 commented on content/durable-objects/get-started.md
> +{{</Aside>}}
```suggestion
Refer to [Bindings](/workers/platform/bindings/) for more information about bindings.
```
Standardize source of truth on information.

2023-07-13 15:27 UTC, deadlypants1973 commented on content/durable-objects/get-started.md
> +This is achieved by configuring a binding in the calling Worker for each Durable Object class that you would like it to be able to talk to. These bindings work similarly to KV bindings and must be co
```suggestion
This is achieved by configuring a binding in the calling Worker for each Durable Object class that you would like it to be able to talk to. These bindings must be configured at upload time. Methods exposed by the binding can be used to communicate with particular Durable Object instances.
```
KV bindings are irrelevant to new users who have never worked with KV.

2023-07-13 15:27 UTC, deadlypants1973 commented on content/durable-objects/get-started.md
> +{{</Aside>}}
```suggestion
```
Since we are encouraging modules, let's get rid of this.

2023-07-13 15:27 UTC, deadlypants1973 commented on content/durable-objects/get-started.md
> +ES Modules differ from regular JavaScript files in that they have imports and exports. For example, [to write a class that defines a Durable Object](/durable-objects/get-started/#1-write-a-class-to-d
```suggestion
Durable Objects must be written in ES Modules syntax. ES Modules differ from regular JavaScript files in that they have imports and exports. For example, [to write a class that defines a Durable Object](/durable-objects/get-started/#1-write-a-class-to-define-a-durable-object), you use `export class DurableObjectExample`. To implement a fetch handler, export a method named `fetch()` in an `export default {}` block.
```

2023-07-13 15:27 UTC, deadlypants1973 commented on content/durable-objects/get-started.md
> +// In modules-syntax workers, you use `export default` to export your script's
```suggestion
// In ES Modules format, you use `export default` to export your Worker's
```

2023-07-13 15:27 UTC, deadlypants1973 commented on content/durable-objects/get-started.md
> +// requests. In Service workers, the fetch handler was registered using
```suggestion
// requests. In Service Worker format, the fetch handler was registered using
```

2023-07-13 15:27 UTC, deadlypants1973 commented on content/durable-objects/get-started.md
> +// requests. In Service workers, the fetch handler was registered using
I think any mention of Service Worker format in this code block is unnecessary?

2023-07-13 15:27 UTC, deadlypants1973 commented on content/durable-objects/get-started.md
> +  // in which bindings show up as global variables.
```suggestion
  // In ES modules format, bindings are delivered as a property of the
  // environment object passed as the second parameter when an event handler or
  // class constructor is invoked. This is new compared to Service Module workers,
  // in which bindings show up as global variables.
```
"This is new compared to Service Module workers,"  This seems like it mixed up 2 concepts together? Is it saying ES modules or is it saying Service Worker?

2023-07-13 15:27 UTC, deadlypants1973 commented on content/durable-objects/get-started.md
> +To upload Workers that implement or bind to Durable Objects, use [Wrangler](/workers/wrangler/), the Workers CLI. Start with one of our templates, the simplest of which can be used by running:
Why are we creating a new Worker here? Why are we `wrangler dev`ing it?

2023-07-13 15:27 UTC, deadlypants1973 commented on content/durable-objects/get-started.md
> +Refer to the [modules section of the custom builds documentation](/workers/wrangler/custom-builds/) for more details.
```suggestion
Refer to [Custom builds documentation](/workers/wrangler/custom-builds/) for more details.
```

2023-07-13 15:27 UTC, deadlypants1973 commented on content/durable-objects/get-started.md
> +{{</Aside>}}
```suggestion
```

This seems like old info?

2023-07-13 15:27 UTC, deadlypants1973 commented on content/durable-objects/get-started.md
> +### Related resources
Did not understand what I have built in the end?

2023-07-13 15:27 UTC, deadlypants1973 commented on content/durable-objects/learning/access-durable-object-from-a-worker.md
> +Namespace bindings allow you to generate Object IDs and connect to Objects.
```suggestion
To access a Durable Object from a Worker, you must first create a Durable Object namespace binding in your Worker. The namespace is, in turn, configured to use a particular class and controls access to instances of that class.

Namespace bindings allow you to generate Object IDs and connect to Objects.
```
Are we calling it a DO namespace binding? A namespace binding? A DO namespace binding? Need to have uniformity here.

2023-07-13 15:27 UTC, deadlypants1973 commented on content/durable-objects/learning/access-durable-object-from-a-worker.md
> +- Derive IDs from names.
What names?

2023-07-13 15:27 UTC, deadlypants1973 commented on content/durable-objects/learning/access-durable-object-from-a-worker.md
> +There are three methods to create Durable Object IDs. You can choose to:
What is a DO ID?

2023-07-13 15:27 UTC, deadlypants1973 commented on content/durable-objects/learning/access-durable-object-from-a-worker.md
> +```js
What is this codeblock doing?

2023-07-13 15:27 UTC, deadlypants1973 commented on content/durable-objects/learning/access-durable-object-from-a-worker.md
> +```js
No description on this page of what these codeblocks are doing?

2023-07-13 15:27 UTC, deadlypants1973 commented on content/durable-objects/learning/durable-objects-migrations.md
> +You must initiate a migration process when you create a new Durable Object class, rename, delete, or transfer an existing Durable Objects class. This process informs the Workers runtime of the change
```suggestion
You must initiate a migration process when you create a new Durable Object class, or rename, delete, or transfer an existing Durable Objects class. This process informs the Workers runtime of the changes and provides it with instructions on how to deal with those changes.
```

2023-07-13 15:27 UTC, deadlypants1973 commented on content/durable-objects/learning/durable-objects-migrations.md
> +After a migration, any existing bindings to the original Durable Object class (for example, from other Workers) will automatically forward to the updated destination class. However, any Worker script
```suggestion
After a migration, any existing bindings to the original Durable Object class (for example, from other Workers) will automatically forward to the updated destination class. However, any Workers bound to the updated Durable Object class must update their `[durable_objects]` configuration in the `wrangler.toml` file for their next deployment.
```

2023-07-13 15:27 UTC, deadlypants1973 commented on content/durable-objects/learning/durable-objects-migrations.md
> +Migrations are performed through the `[[migrations]]` configurations key in your `wrangler.toml` file.
This seems like it is dupe info of another section of this PR? Can we make one source of truth and link out to it in other sections?

2023-07-13 15:27 UTC, deadlypants1973 commented on content/durable-objects/learning/in-memory-state.md
> +
```suggestion
```

2023-07-13 15:27 UTC, deadlypants1973 commented on content/durable-objects/learning/limitations.md
> +# Limitations
There's a limits page and a limitation page? Limitations page should not exist.

2023-07-13 15:27 UTC, deadlypants1973 commented on content/durable-objects/learning/websockets.md
> +
```suggestion
```

2023-07-13 15:27 UTC, deadlypants1973 commented on content/durable-objects/learning/limitations.md
> +Global uniqueness guarantess there is only a single instance of a Durable Object class with a given ID running at once, across the world.
```suggestion
Global uniqueness guarantees there is only a single instance of a Durable Object class with a given ID running at once, across the world.
```

2023-07-13 15:27 UTC, deadlypants1973 commented on content/durable-objects/learning/limitations.md
> +[Wrangler tail](/workers/wrangler/commands/#tail) logs from requests that are upgraded to WebSockets are delayed until the WebSocket is closed. Wrangler tail should not be connected to a script that
```suggestion
[`wrangler tail`](/workers/wrangler/commands/#tail) logs from requests that are upgraded to WebSockets are delayed until the WebSocket is closed. `wrangler tail` should not be connected to a Worker that you expect will receive heavy volumes of traffic.
```

2023-07-13 15:27 UTC, deadlypants1973 commented on content/durable-objects/learning/limitations.md
> +[`wrangler dev`](/workers/wrangler/commands/#dev) has read access to Durable Object storage, but writes will be kept in memory and will not affect persistent data. However, if you specify the `script
```suggestion
[`wrangler dev`](/workers/wrangler/commands/#dev) has read access to Durable Object storage, but writes will be kept in memory and will not affect persistent data. However, if you specify the `script_name` explicitly in the Durable Object binding, then writes will affect persistent data. Wrangler will emit a warning in that case. 
```

2023-07-13 15:27 UTC, deadlypants1973 commented on content/durable-objects/learning/websockets.md
> +As part of Durable Objects, Workers can act as WebSocket endpoints – including as a client or as a server. Previously, Workers could proxy WebSocket connections on to a back-end server, but could not
Is the second sentence necessary now?

2023-07-13 15:27 UTC, deadlypants1973 commented on content/durable-objects/platform/data-location.md
> +To use a jurisdiction, first create a jursidictional subnamespace:
Where?

2023-07-13 15:27 UTC, deadlypants1973 commented on content/durable-objects/platform/data-location.md
> +A jurisdictional subnamespace works like a normal Durable Object namespace (`OBJECT_NAMESPACE` above), except that IDs created within them permanently encode the jurisdiction that was used to create
```suggestion
A jurisdictional subnamespace works like a normal Durable Object namespace (`OBJECT_NAMESPACE` above), except that IDs created within them permanently encode the jurisdiction that was used to create the subnamespace. Additionally, the `idFromString()` and `get()` methods will throw an exception if the IDs passed into them are not within the subnamespace's jurisdiction. Once you have a subnamespace, you can use all of the namespace methods documented above.
```

2023-07-13 15:27 UTC, deadlypants1973 commented on content/durable-objects/platform/data-location.md
> +```js
Where?

2023-07-13 15:27 UTC, deadlypants1973 commented on content/durable-objects/platform/data-location.md
> +```js
Where?

2023-07-13 15:27 UTC, deadlypants1973 commented on content/durable-objects/platform/data-location.md
> +# Data location
This page uses object, Object and Durable Object seemingly interchangeably. Need to pick one option and standardize it throughout.

2023-07-13 15:27 UTC, deadlypants1973 commented on content/durable-objects/platform/data-location.md
> +Your Workers may still access Objects constrained to a jurisdiction from anywhere in the world. The jurisdiction constraint only controls where the Durable Object itself runs and persists data. Consi
```suggestion
Your Workers may still access Objects constrained to a jurisdiction from anywhere in the world. The jurisdiction constraint only controls where the Durable Object itself runs and persists data. Consider using [Regional Services](/data-localization/regional-services/) to control the regions from which Cloudflare responds to requests.
```

2023-07-13 15:27 UTC, deadlypants1973 commented on content/durable-objects/platform/graphql-analytics.md
> +# GraphQL Analytics
```suggestion
# GraphQL analytics
```

2023-07-13 15:39 UTC, deadlypants1973 requested changes
PCX 2

2023-07-13 15:39 UTC, deadlypants1973 commented on content/durable-objects/platform/graphql-analytics.md
> +title: GraphQL Analytics
```suggestion
title: GraphQL analytics
```

2023-07-13 15:39 UTC, deadlypants1973 commented on content/durable-objects/platform/graphql-analytics.md
> +Refer to [Querying Workers Metrics](/analytics/graphql-api/tutorials/querying-workers-metrics/) tutorial for authentication and to learn more about querying Workers data sets.
```suggestion
Refer to the [Querying Workers Metrics tutorial](/analytics/graphql-api/tutorials/querying-workers-metrics/) for authentication and to learn more about querying Workers data sets.
```

2023-07-13 15:39 UTC, deadlypants1973 commented on content/durable-objects/platform/limits.md
> +Durable Objects are only available on the Workers Paid plan.
```suggestion
Durable Objects are only available on the [Workers Paid plan](/workers/platform/pricing/#workers).
```

2023-07-13 15:39 UTC, deadlypants1973 commented on content/durable-objects/platform/limits.md
> +|  Number of objects                         | unlimited (within an account or of a given class) |
```suggestion
|  Number of objects                         | Unlimited (within an account or of a given class) |
```

2023-07-13 15:39 UTC, deadlypants1973 commented on content/durable-objects/platform/limits.md
> +<sup>1</sup> Durable Objects both bills and measures storage based on a gigabyte (1 GB = 1,000,000,000 bytes) and not a gibibyte (GiB).
I think this is missing the limit request form? Look at the aside in this section
/workers/platform/limits/#account-plan-limits

2023-07-13 15:39 UTC, deadlypants1973 commented on content/durable-objects/platform/pricing.md
> +Durable Objects are only available on the Workers Paid plan.
```suggestion
Durable Objects are only available on the [Workers Paid plan](/workers/platform/pricing/#workers).
```

2023-07-13 15:39 UTC, deadlypants1973 commented on content/durable-objects/platform/troubleshooting.md
> +### Error: `No event handlers were registered. This script does nothing.`
Do we need to put Error in front of all of these? It seems like the message itself will suffice. Also one is in backticks but the rest are not.

2023-07-13 15:48 UTC, Maddy-Cloudflare commented on content/durable-objects/_index.md
> +
> Add Transactional Storage API here.

I thought I added it?

2023-07-17 15:01 UTC, MellowYarker commented on content/durable-objects/api/hibernatable-websockets-api.md
> +  - `state.setWebSocketAutoResponse` receives `WebSocketRequestResponsePair(request{{<param-type>}}string{{</param-type>}}, response{{<param-type>}}string{{</param-type>}})` as an argument, enabling
The generated doc looks a bit weird here https://maddy-durable-objects-tile.cloudflare-docs-7ou.pages.dev/durable-objects/api/hibernatable-websockets-api/#state-methods-for-websockets

> `state.setWebSocketAutoResponse` receives `WebSocketRequestResponsePair(request<span class="InlineCode--type">string</span>, response<span class="InlineCode--type">string</span>)` as an argument

I think it's because it's wrapped in `code` backticks, rather than {{<code>}}? This happens below as well

2023-07-17 15:02 UTC, MellowYarker commented on content/durable-objects/api/hibernatable-websockets-api.md
> +  - Gets the `WebSocketRequestResponsePair(request{{<param-type>}}string{{</param-type>}}, response{{<param-type>}}string{{</param-type>}})` currently set, or `null` if there is none.
Here

2023-07-17 15:02 UTC, cacheburner commented on content/durable-objects/api/hibernatable-websockets-api.md
> +  - Each `WebSocketRequestResponsePair(request{{<param-type>}}string{{</param-type>}}, response{{<param-type>}}string{{</param-type>}})` Object provides methods for `getRequest()` and  `getResponse()
Here too

2023-07-17 16:39 UTC, MellowYarker commented on content/durable-objects/api/hibernatable-websockets-api.md
> +### `state` methods for WebSockets
# Short Term
I think this (as well as the webSocketEvent handlers below) should be 2 ##, not 3, as it's not part of **WebSocket extensions** above -- that specifically references extensions to the _WebSocket object_.

# Longer Term
IMO this page should look more like the [alarms page](https://maddy-durable-objects-tile.cloudflare-docs-7ou.pages.dev/durable-objects/api/alarms-in-durable-objects/). The alarms page clearly tells me what alarms are for, identifies the important method, and provides an easy to follow example.

Here we have 5 methods on `state` with a bunch of code mixed with text underneath each. It's hard to distinguish what does what, or what I need to get started.

With that in mind, I'm proposing we do something closer to:

### Accepting a Hibernatable WebSocket
#### Using `state.acceptWebSocket()`
- Reiterate how this differs from `ws.accept()`
- Introduce the method signature
- Introduce the new `webSocketEvent()` handlers
- Make it clear this means old `addEventListeners` will not receive events
- Make it clear that we do not _currently_ support _outbound_ connections, meaning DO <-> Origin Server and Proxy use-cases are not supported. 
#### Using `state.getWebSockets()`
- Explain what this is useful for (ex. broadcast)
- Introduce the method signature
### Hibernatable WebSocket "echo" server example
- Very simple echo server, upon receiving a message, we reply with the same message.
- If the message is/starts with `"broadcast"`, we use `getWebSockets()` to broadcast to everyone.

### Using auto-response to reduce billing for static messages
- When is auto-response useful (static application-level pings)?
- What are the implications of using it (WS will not wake up to reply to message)
- Introduce the relevant methods
- Repeat our echo example above, but extend it with an auto-response use-case

---
I think this would help clarify what the API is for, make it easier for folks to get started, and provide a simpler map of the Hibernation API. @elithrar @jqmmes thoughts?

2023-07-17 17:30 UTC, jqmmes commented on content/durable-objects/api/hibernatable-websockets-api.md
> +### `state` methods for WebSockets
I agree on the handler section, it should be its own section "Hibernatable WebSocket Handlers".

And I also agree on the longer term proposal.

2023-07-27 15:16 UTC, deadlypants1973 requested changes
PCX

2023-07-27 15:16 UTC, deadlypants1973 commented on content/durable-objects/_index.md
> +Built on SQLite, D1 is Cloudflare’s first queryable relational database. Create an entire database by importing data or defining your tables and writing your queries within a Worker or through the AP
```suggestion
D1 is Cloudflare’s native serverless database. Create a database by importing data or defining your tables and writing your queries within a Worker or through the API.
```

2023-07-27 15:16 UTC, deadlypants1973 commented on content/durable-objects/api/alarms-in-durable-objects.md
> +Durable Objects alarms allow you to schedule the Durable Object to be waken up at a time in the future.
```suggestion
Durable Objects alarms allow you to schedule the Durable Object to be woken up at a time in the future.
```

2023-07-27 15:16 UTC, deadlypants1973 commented on content/durable-objects/api/hibernatable-websockets-api.md
> +For WebSocket proxy use-cases, refer to the [standard WebSocket API](/workers/runtime-apis/websockets/use-websockets/#write-a-websocket-client) documentation.
```suggestion
For WebSocket proxy use-cases, refer to the [standard WebSocket API documentation](/workers/runtime-apis/websockets/use-websockets/#write-a-websocket-client).
```

2023-07-27 15:16 UTC, deadlypants1973 commented on content/durable-objects/api/hibernatable-websockets-api.md
> +  - `state.setWebSocketAutoResponse` receives `WebSocketRequestResponsePair(request{{<param-type>}}string{{</param-type>}}, response{{<param-type>}}string{{</param-type>}})` as an argument, enabling
```suggestion
  - `state.setWebSocketAutoResponse` receives {{<code>}}WebSocketRequestResponsePair(request{{<param-type>}}string{{</param-type>}}, response{{<param-type>}}string{{</param-type>}}){{</code>}} as an argument, enabling any WebSocket that was accepted via `state.acceptWebSocket()` belonging to this Object to automatically reply with `response` when it receives the specified `request`. 
```

2023-07-27 15:16 UTC, deadlypants1973 commented on content/durable-objects/api/hibernatable-websockets-api.md
> +- {{<code>}}state.setWebSocketAutoResponse(webSocketRequestResponsePair{{<param-type>}}WebSocketRequestResponsePair{{</param-type>}}{{<prop-meta>}}<br/>optional{{</prop-meta>}}){{</code>}}: {{<type>}
I think this `<br/>` is messing with your formatting and creating a big gray block.

2023-07-27 15:16 UTC, deadlypants1973 commented on content/durable-objects/api/hibernatable-websockets-api.md
> +- {{<code>}}state.setWebSocketAutoResponse(webSocketRequestResponsePair{{<param-type>}}WebSocketRequestResponsePair{{</param-type>}}{{<prop-meta>}}<br/>optional{{</prop-meta>}}){{</code>}}: {{<type>}
```suggestion
- {{<code>}}state.setWebSocketAutoResponse(webSocketRequestResponsePair{{<param-type>}}WebSocketRequestResponsePair{{</param-type>}}{{<prop-meta>}}optional{{</prop-meta>}}){{</code>}}: {{<type>}}void{{</type>}}
```

2023-07-27 15:16 UTC, deadlypants1973 commented on content/durable-objects/api/hibernatable-websockets-api.md
> +  - `setWebSocketAutoResponse()` is preferable to setting up a server for static ping/pong messages because `setWebSocketAutoResponse()` handles application level ping/pongs without waking the websoc
```suggestion
  - `setWebSocketAutoResponse()` is preferable to setting up a server for static ping/pong messages because `setWebSocketAutoResponse()` handles application level ping/pongs without waking the WebSocket from hibernation, preventing unnecessary duration charges.
```

2023-07-27 15:16 UTC, deadlypants1973 commented on content/durable-objects/examples/durable-objects-rollup-es-modules.md
> +# Durable Objects Rollup ES Modules template
```suggestion
# Durable Objects Rollup ES modules template
```

2023-07-27 15:16 UTC, deadlypants1973 commented on content/durable-objects/examples/durable-objects-typescript-rollup-es-modules.md
> +# Durable Objects TypeScript Rollup ES Modules template
```suggestion
# Durable Objects TypeScript Rollup ES modules template
```

2023-07-27 15:16 UTC, deadlypants1973 commented on content/durable-objects/examples/durable-objects-webpack-commonjs.md
> +Use this template to bundle external dependencies with your code using Rollup or Webpack.
```suggestion
Use this template to bundle external dependencies with your code using Rollup or webpack. 
```

2023-07-27 15:16 UTC, deadlypants1973 commented on content/durable-objects/examples/durable-objects-webpack-commonjs.md
> +Use this template to bundle external dependencies with your code using Rollup or Webpack.
Rollup seems to be capitalized normally, but webpack is not. https://rollupjs.org/introduction/

2023-07-27 15:16 UTC, deadlypants1973 commented on content/durable-objects/get-started.md
> +## Prerequisites
This should be a partial, not a copy paste.

```suggestion
{{<render file="_prereqs.md" productFolder="workers">}}
```

2023-07-27 15:16 UTC, deadlypants1973 commented on content/durable-objects/get-started.md
> +To enable Durable Objects, you will need to purchase Workers Paid plan:
```suggestion
To enable Durable Objects, you will need to purchase the Workers Paid plan:
```

2023-07-27 15:16 UTC, deadlypants1973 commented on content/durable-objects/get-started.md
> +```sh
Use the tab switcher code on Workers get started.

2023-07-27 15:16 UTC, deadlypants1973 commented on content/durable-objects/get-started.md
> +To create a producer Worker, run:
```suggestion
You will access your Durable Object from a [Worker](/workers/).

To create a Worker project, run:
```

2023-07-27 15:16 UTC, deadlypants1973 commented on content/durable-objects/get-started.md
> +This will create a new directory, which will include both a `src/worker.js` Worker script, and a [`wrangler.toml`](/workers/wrangler/configuration/) configuration file. After you create your Worker,
```suggestion
This will create a new directory, which will include both a `src/worker.js` file to write your code, and a [`wrangler.toml`](/workers/wrangler/configuration/) configuration file. After you create your Worker, create a class to define a Durable Object.
```

2023-07-27 15:16 UTC, deadlypants1973 commented on content/durable-objects/get-started.md
> +HTTP requests received by a Durable Object do not come directly from the Internet. They come from other Worker code – possibly other Durable Objects, or Workers. Durable Objects use HTTP for familiar
```suggestion
HTTP requests received by a Durable Object do not come directly from the Internet. HTTP requests come from other Workers and other Durable Objects. Durable Objects use HTTP for familiarity, but plan to introduce other protocols in the future.
```

2023-07-27 15:16 UTC, deadlypants1973 commented on content/durable-objects/get-started.md
> +Configure Durable Object bindings in the `wrangler.toml` by providing the class name and script name whose objects you wish to access using the binding. The script name can be omitted when creating a
```suggestion
Durable Object bindings for communication between a Worker and a Durable Object. Configure Durable Object bindings in your Worker project's `wrangler.toml` by providing a binding name (for this guide, use `EXAMPLE_CLASS`) and the class name (`DurableObjectExample`).
```

2023-07-27 15:16 UTC, deadlypants1973 commented on content/durable-objects/get-started.md
> +If you are using Wrangler [environments](/workers/wrangler/environments/), you must specify any Durable Object bindings you wish to use on a per-environment basis.
This needs to be another page in the docs. Environments information is not necessary for a get started. Everything from here to `## 5.` could and should be moved.

2023-07-27 15:16 UTC, deadlypants1973 commented on content/durable-objects/get-started.md
> +`"EXAMPLE_CLASS"` in the staging environment is bound to a different script name compared to the top-level `"EXAMPLE_CLASS"` binding, and will therefore access different objects with different persis
This is also refering to Workers as 'scripts'  which we do not do anymore. This will need a refresh.

2023-07-27 15:16 UTC, deadlypants1973 commented on content/durable-objects/get-started.md
> +Migrations are performed through the `[[migrations]]` configurations key in your `wrangler.toml` file.
What are migrations?

2023-07-27 15:16 UTC, deadlypants1973 commented on content/durable-objects/get-started.md
> +Migration tags are treated like unique names and are used to determine which migrations have already been applied. Once a given script has a migration tag set on it, all future script uploads must in
What is a script and an upload? Is a script a Worker? Is an upload a deploy? These words don't coincide with commands or concepts used today.

2023-07-27 15:16 UTC, deadlypants1973 commented on content/durable-objects/get-started.md
> +## 7. Upload a Durable Object Worker
This section does not describe uploading, it describes testing (`wrangler dev`).

2023-07-27 15:16 UTC, deadlypants1973 commented on content/durable-objects/get-started.md
> +## 6. Instantiate and communicate with a Durable Object
This section feels out of order. It's talking about creating a binding (which we already did) and then introduces a new code block for the Worker file. Do we want the user to copy and paste this code into their `worker.js`? What's the action that needs to be done here?

2023-07-27 15:16 UTC, deadlypants1973 commented on content/durable-objects/get-started.md
> +Refer to [Access a Durable Object from a Worker](/durable-objects/how-to/access-durable-object-from-a-worker/) to  learn more about communicating to a Durable Object.
```suggestion
Refer to [Access a Durable Object from a Worker](/durable-objects/how-to/access-durable-object-from-a-worker/) to learn more about communicating to a Durable Object.
```

2023-07-27 15:16 UTC, deadlypants1973 commented on content/durable-objects/get-started.md
> +{{</Aside>}}
```suggestion
```
The user has already installed Wrangler in step 1. If we want to put version requirements, let's put them at the top of the guide.

2023-07-27 15:16 UTC, deadlypants1973 commented on content/durable-objects/get-started.md
> +To upload Workers that implement or bind to Durable Objects, use [Wrangler](/workers/wrangler/), the Workers CLI.
Are we uploading as in running locally? Or uploading as in deploying? This part is unclear.

2023-07-27 15:16 UTC, deadlypants1973 commented on content/durable-objects/get-started.md
> +### Specify the main module
This seems like instructions that need to be at the top with the rest of the wrangler.toml file modification.

2023-07-27 15:16 UTC, deadlypants1973 commented on content/durable-objects/get-started.md
> +## 8. Test your Durable Objects project
Where does `wrangler deploy` fit into this flow?

2023-07-27 15:34 UTC, deadlypants1973 reviewed
PCX

2023-07-28 11:14 UTC, deadlypants1973 approved these changes
Main issues:

1. Get started guide needs to be written with a basic get started flow. Create Worker > update toml > update Worker code > test > deploy > summarize what was built. Right now, the guide is lacking this structure.
2. 'Script' and 'upload' are being used throughout the tile and do not reference anything Workers architecture specific. What is a script? (The Worker code? The Worker project?) And what is an upload? (Deployment?)
3. What is a DO namespace? This is never defined.
4. Durable Object namespace binding is not used in the dash or docs yet referenced here multiple times.
5. The two topics in the how to section seem essential to the get started in terms of actually using DOs. The relationship between what is happening in how to's and what is happening in Get started needs to be made clear. For example, by  updating the related resources of the get started guide.

2023-07-28 11:14 UTC, deadlypants1973 commented on content/durable-objects/how-to/access-durable-object-from-a-worker.md
> +To access a Durable Object from a Worker, you must first create a Durable Object namespace binding in your Worker. The namespace is, in turn, configured to use a particular class and controls access
```suggestion
To access a Durable Object from a Worker, you must first create a Durable Object binding in your Worker project's `wrangler.toml` file. The binding is configured to use a particular class and controls access to instances of that class.
```
I think the second section should say binding? The docs and dash call it "Durable Object binding" not "Durable Object namespace binding".

2023-07-28 11:14 UTC, deadlypants1973 commented on content/durable-objects/how-to/access-durable-object-from-a-worker.md
> +Durable Objects namespace bindings allow you to generate Durable Object IDs and connect to Durable Objects.
```suggestion
Durable Object bindings for communication between a Worker and a Durable Object.
```
Definition: https://developers.cloudflare.com/workers/configuration/bindings/#durable-object-bindings

2023-07-28 11:14 UTC, deadlypants1973 commented on content/durable-objects/how-to/access-durable-object-from-a-worker.md
> +If you are using [Wrangler environments](/workers/wrangler/environments/), you must specify any Durable Object namespace bindings you wish to use on a per-environment basis.
```suggestion
If you are using [Wrangler environments](/workers/wrangler/environments/), you must specify any Durable Object bindings you wish to use on a per-environment basis.
```

2023-07-28 11:14 UTC, deadlypants1973 commented on content/durable-objects/how-to/access-durable-object-from-a-worker.md
> +The system calls the `fetch()` method of a Durable Object namespace when an HTTP request is sent to the Durable Object. These requests are not sent from the public Internet, but from other [Workers u
```suggestion
The system calls the `fetch()` method of a Durable Object namespace when an HTTP request is sent to the Durable Object. These requests are not sent from the public Internet, but from other Workers using a Durable Object binding.
```
This section was linking to its own page.

2023-07-28 11:14 UTC, deadlypants1973 commented on content/durable-objects/how-to/access-durable-object-from-a-worker.md
> +The method takes a [`Request`](/workers/runtime-apis/request/) as the parameter and returns a [`Response`](/workers/runtime-apis/response/) (or a `Promise` for a `Response`).
```suggestion
The `fetch()` method takes a [`Request`](/workers/runtime-apis/request/) as the parameter and returns a [`Response`](/workers/runtime-apis/response/) (or a `Promise` for a `Response`).
```

2023-07-28 11:14 UTC, deadlypants1973 commented on content/durable-objects/get-started.md
> +- Instantiating and communicationg with a Durable Object from another Worker via the Fetch API.
```suggestion
- Instantiating and communicationg with a Durable Object from another Worker via the `Fetch` API.
```

2023-07-28 11:14 UTC, deadlypants1973 commented on content/durable-objects/how-to/create-durable-object-stubs.md
> +The Cloudflare REST API supports retrieving a [list of Durable Objects](/api/operations/durable-objects-namespace-list-objects/) within a namespace and a [list of namespaces](/api/operations/durable-
What is a DO namespace? This is not defined anywhere.

2023-07-28 11:14 UTC, deadlypants1973 commented on content/durable-objects/learning/durable-objects-migrations.md
> +The destination class (the class that stored Durable Objects are being transferred to) for a rename or transfer migration must be exported by the deployed script.
```suggestion
The destination class (the class that stored Durable Objects are being transferred to) for a rename or transfer migration must be exported by the deployed Worker.
```

2023-07-28 11:14 UTC, deadlypants1973 commented on content/durable-objects/learning/durable-objects-migrations.md
> +The most common migration performed is a new class migration, which informs the system that a new Durable Object class is being uploaded.
```suggestion
The most common migration performed is a new class migration, which informs the runtime that a new Durable Object class is being uploaded.
```

What is uploaded? Deployed?

2023-07-28 11:14 UTC, deadlypants1973 commented on content/durable-objects/learning/durable-objects-migrations.md
> +It is possible to define a migration through extra arguments to the `wrangler deploy` command. When taking this route, any migrations listed in the `wrangler.toml` configuration file are ignored.
```suggestion
It is possible to define a migration through extra arguments to the [`wrangler deploy`](/workers/wrangler/commands/#deploy) command. When taking this route, any migrations listed in the `wrangler.toml` configuration file are ignored.
```

2023-07-28 11:14 UTC, deadlypants1973 commented on content/durable-objects/learning/in-memory-state.md
> +A given instance of a Durable Object may share global memory with other instances defined in the same script.
Script  = Worker code, Worker project?

2023-07-28 11:14 UTC, deadlypants1973 commented on content/durable-objects/platform/limits.md
> +An individual Object has a soft limit of 1000 requests per second. A simple get on a small value that directly returns the response may realize a higher request throughput.
```suggestion
An individual Object has a soft limit of 1,000 requests per second. A simple get on a small value that directly returns the response may realize a higher request throughput.
```

2023-07-28 11:14 UTC, deadlypants1973 commented on content/durable-objects/platform/troubleshooting.md
> +### Your account is doing too many concurrent storage operations. Please back off and try again later
```suggestion
### Your account is doing too many concurrent storage operations. Please back off and try again later.
```

2023-07-28 11:14 UTC, deadlypants1973 commented on content/durable-objects/platform/troubleshooting.md
> +"Reset" in error messages refers to in-memory state. Any durable state that has already been successfully persisted via `state.storage` is not affected.
```suggestion
Reset in error messages refers to in-memory state. Any durable state that has already been successfully persisted via `state.storage` is not affected.
```

2023-07-28 11:14 UTC, deadlypants1973 commented on content/durable-objects/platform/troubleshooting.md
> +### Your account is generating too much load on Durable Objects. Please back off and try again later
```suggestion
### Your account is generating too much load on Durable Objects. Please back off and try again later.
```

2023-07-28 11:14 UTC, deadlypants1973 commented on content/durable-objects/platform/troubleshooting.md
> +In your `wrangler.toml` file, make sure the `dir` and `main` entries point to the correct file containing your Worker script, and that the file extension is `.mjs` instead of `.js` if using ES Module
```suggestion
In your `wrangler.toml` file, make sure the `dir` and `main` entries point to the correct file containing your Worker code, and that the file extension is `.mjs` instead of `.js` if using ES modules syntax.
```

2023-07-28 11:14 UTC, deadlypants1973 commented on content/durable-objects/platform/troubleshooting.md
> +## Common errors
Why do some of these have periods at the end of the sentence and some don't?

2023-07-28 11:14 UTC, deadlypants1973 commented on content/durable-objects/platform/troubleshooting.md
> +### No event handlers were registered. This script does nothing
```suggestion
### No event handlers were registered. This script does nothing.
```

2023-07-28 11:14 UTC, deadlypants1973 commented on content/durable-objects/platform/troubleshooting.md
> +### When deleting migration
```suggestion
### Cannot apply `--delete-class` migration to class
```
This seems like the actual error

2023-07-28 11:14 UTC, deadlypants1973 commented on content/durable-objects/platform/troubleshooting.md
> +### Durable Object is overloaded
```suggestion
### Durable Object is overloaded.
```

2023-07-28 11:14 UTC, deadlypants1973 commented on content/durable-objects/platform/troubleshooting.md
> +### Durable Object storage operation exceeded timeout which caused object to be reset
```suggestion
### Durable Object storage operation exceeded timeout which caused object to be reset.
```

2023-07-28 15:26 UTC, deadlypants1973 approved these changes
PCX

2023-07-28 15:26 UTC, deadlypants1973 commented on content/durable-objects/get-started.md
> +{{</Aside>}}
The partial does this work. Can delete this.

```suggestion
```

2023-07-28 15:26 UTC, deadlypants1973 commented on content/durable-objects/get-started.md
> + 1. Log in to the [Cloudflare dashboard](https://dash.cloudflare.com/).
```suggestion
 1. Log in to the [Cloudflare dashboard](https://dash.cloudflare.com/) and select your account.
```

2023-07-28 15:26 UTC, deadlypants1973 commented on content/durable-objects/get-started.md
> +
```suggestion
```

2023-07-28 15:26 UTC, deadlypants1973 commented on content/durable-objects/get-started.md
> +You will access your Durable Object from a [Worker](/workers/).
```suggestion
You will access your Durable Object from a [Worker](/workers/). Your Worker application is an interface to interact with your Durable Object.
```

2023-07-28 15:26 UTC, deadlypants1973 commented on content/durable-objects/get-started.md
> +
```suggestion
```

2023-07-28 15:26 UTC, deadlypants1973 commented on content/durable-objects/get-started.md
> +## 7. Upload a Durable Object Worker
```suggestion
## 7. Develop a Durable Object Worker locally
```

2023-07-28 15:26 UTC, deadlypants1973 commented on content/durable-objects/get-started.md
> +Open your terminal and run the following command to upload a Durable Object Worker:
```suggestion
To test your Durable Object locally, run [`wrangler dev`](/workers/wrangler/commands/#dev):
```

2023-07-28 15:26 UTC, deadlypants1973 commented on content/durable-objects/get-started.md
> +In your terminal, you will be asked a series of questions related to your project:
```suggestion
Running `create cloudlfare` will install [Wrangler](/workers/wrangler/install-and-update/), the Workers CLI. You will use Wrangler to test and deploy your project.

In your terminal, you will be asked a series of questions related to your project: 
```

2023-07-28 15:26 UTC, deadlypants1973 commented on content/durable-objects/get-started.md
> +Configure Durable Object bindings in your Worker project's `wrangler.toml` by providing a binding name (for this guide, use `EXAMPLE_CLASS`) and the class name (`DurableObjectExample`).
```suggestion
[Bindings](/workers/configuration/bindings/) allow your Workers to interact with resources on the Cloudflare developer platform. Configure Durable Object bindings in your Worker project's `wrangler.toml` by providing a binding name (for this guide, use `EXAMPLE_CLASS`) and the class name (`DurableObjectExample`).
```

2023-07-28 15:26 UTC, deadlypants1973 commented on content/durable-objects/get-started.md
> +To configure a Durable Object migration in `wrangler.toml` file:
```suggestion
To configure a Durable Object migration in your Worker's `wrangler.toml` file:
```

2023-07-28 15:26 UTC, deadlypants1973 commented on content/durable-objects/get-started.md
> +Your class `DurableObjectExample` will have a constructor with two parameters. The first parameter, `state`, passed to the class constructor contains state specific to the Durable Object, including m
```suggestion
Your `DurableObjectExample` class will have a constructor with two parameters. The first parameter, `state`, passed to the class constructor contains state specific to the Durable Object, including methods for accessing storage. The second parameter, `env`, contains any bindings you have associated with the Worker when you uploaded it. 
```

2023-07-28 15:26 UTC, deadlypants1973 commented on content/durable-objects/get-started.md
> +Note that this means bindings are no longer global variables. For example, if you had a secret binding `MY_SECRET`, you must access it as `env.MY_SECRET`.
```suggestion
Note that this means bindings are no longer global variables. For example, if you had a secret binding with a `binding` name of `MY_SECRET`, you must access it as `env.MY_SECRET`.
```

2023-07-28 15:26 UTC, deadlypants1973 commented on content/durable-objects/get-started.md
> +
```suggestion
```

2023-07-28 15:26 UTC, deadlypants1973 commented on content/durable-objects/get-started.md
> + ## 5. Write a class to define a Durable Object
This should be step 3.

2023-07-28 15:26 UTC, deadlypants1973 commented on content/durable-objects/get-started.md
> +## 6. Instantiate and communicate with a Durable Object
This should be step 4.

2023-07-28 15:26 UTC, deadlypants1973 commented on content/durable-objects/get-started.md
> +## 3. Configure Durable Object bindings
This should be step 5.

2023-07-28 15:26 UTC, deadlypants1973 commented on content/durable-objects/get-started.md
> +## 4. Configure Durable Object classes with migrations
This should be step 6.

2023-07-28 15:26 UTC, deadlypants1973 commented on content/durable-objects/get-started.md
> +To implement a `fetch()` handler, export a method named `fetch()` in an `export default {}` block:
```suggestion
To implement a `fetch()` handler, export a method named `fetch()` in an `export default {}` block. Add the following to your `worker.js` file's existing class and fetch handler:
```

2023-07-28 15:26 UTC, deadlypants1973 commented on content/durable-objects/get-started.md
> +
```suggestion

Your `worker.js` file should now look like:

```

2023-07-28 15:26 UTC, deadlypants1973 commented on content/durable-objects/get-started.md
> +Open your terminal and run the following command to deploy a Durable Object Worker:
```suggestion
To deploy your Durable Object Worker:
```

2023-07-28 15:26 UTC, deadlypants1973 commented on content/durable-objects/get-started.md
> +
```suggestion
```

2023-07-28 15:26 UTC, deadlypants1973 commented on content/durable-objects/get-started.md
> +Once deployed, you should be able to see your newly created Durable Object on the [Cloudflare dashboard](https://dash.cloudflare.com/), **Workers & Pages** > **Overview**.
```suggestion
Once deployed, you should be able to see your newly created Durable Object Worker on the [Cloudflare dashboard](https://dash.cloudflare.com/), **Workers & Pages** > **Overview**.

Preview your Durable Object Worker at `<YOUR_WORKER>.<YOUR_SUBDOMAIN>.workers.dev`.
```

2023-07-28 15:26 UTC, deadlypants1973 commented on content/durable-objects/get-started.md
> +  { name = "EXAMPLE_CLASS", class_name = "DurableObjectExample" } # Binding to our DurableObjectExample class
```suggestion
[[durable_objects.bindings]]
name = "EXAMPLE_CLASS"
class_name = "DurableObjectExample"
```

2023-07-28 15:26 UTC, deadlypants1973 commented on content/durable-objects/get-started.md
> +Each table contains the following fields:
```suggestion
The `[[durable_objects.bindings]]` section contains the following fields:
```

2023-07-28 15:26 UTC, deadlypants1973 commented on content/durable-objects/get-started.md
> +
```suggestion
```

2023-07-31 09:26 UTC, Maddy-Cloudflare commented on content/durable-objects/learning/limitations.md
> +# Limitations
Limitations in this case refer to Durable Objects shortcomings.

2023-08-03 13:50 UTC, deadlypants1973 approved these changes
PCX

Final things to consider:

1. DO architecture is not clear. How do a class, stub, ID, namespace relate to each other? Get started guide defines a class. How should the user think about architecture from there?

2. The tutorials have no numbered steps or instructions and should be moved to examples. If there were to be numbered steps, a start goal and end product that the user is guided through, then this would be a tutorial.

3. DO requires a Worker project with numerous files. It's important for the user to know what information should go into the entry point file (index.js) and what info can go in other files. Refer to Peter's comment in dev plat chat.

4. Mentions of "Worker script" needs to be removed from the tile completely and changed to something correct in relation to point 3.

2023-08-03 13:50 UTC, deadlypants1973 commented on content/durable-objects/get-started.md
> +class_name = "DurableObjectExample"
```suggestion
[[durable_objects.bindings]]
name = "EXAMPLE_CLASS"
class_name = "DurableObjectExample"

# or

[durable_objects]
bindings = [
  { name = "EXAMPLE_CLASS", class_name = "DurableObjectExample" }
]
```

2023-08-03 13:50 UTC, deadlypants1973 commented on content/durable-objects/examples/durable-objects-webpack-commonjs.md
> +You can find the full code [on GitHub](https://github.com/cloudflare/durable-objects-webpack-commonjs).
```suggestion
Find the [full code for this example on GitHub](https://github.com/cloudflare/durable-objects-webpack-commonjs).
```

2023-08-03 13:50 UTC, deadlypants1973 commented on content/durable-objects/how-to/access-durable-object-from-a-worker.md
> +To access a Durable Object from a Worker, you must first create a Durable Object binding in your Worker project's `wrangler.toml` file. The binding is configured to use a particular class and control
```suggestion
To access a Durable Object from a Worker, you must first create a [Durable Object binding](/workers/configuration/bindings/#durable-object-bindings) in your Worker project's [`wrangler.toml`](/workers/wrangler/configuration/#durable-objects) file. The binding is configured to use a particular class and controls access to instances of that class.
```

2023-08-03 13:50 UTC, deadlypants1973 commented on content/durable-objects/how-to/access-durable-object-from-a-worker.md
> +Durable Object bindings for communication between a Worker and a Durable Object.
```suggestion
Durable Object bindings allow for communication between a Worker and a Durable Object.
```

2023-08-03 13:50 UTC, deadlypants1973 commented on content/durable-objects/_partials/_durable-objects-pricing.md
> +<sup>2</sup> Application level auto-response messages handled by [`state.setWebSocketAutoResponse()`](/durable-objects/api/hibernatable-websockets-api/) will not incur additional wall-clock time, and
```suggestion
<sup>2</sup> Application-level auto-response messages handled by [`state.setWebSocketAutoResponse()`](/durable-objects/api/hibernatable-websockets-api/) will not incur additional wall-clock time, and will not be charged.
```

2023-08-03 13:50 UTC, deadlypants1973 commented on content/durable-objects/_partials/_durable-objects-pricing.md
> +<sup>3</sup> Duration is billed in wall-clock time as long as the Object is active, but is shared across all requests active on an Object at once. Once your Object finishes responding to all requests
"Prefer using [`state.acceptWebSocket()`](/durable-objects/api/hibernatable-websockets-api/#state-methods-for-websockets), which will stop incurring duration charges once all event handlers finish running." 

-> What is this trying to say? It is not a full sentence.

2023-08-03 13:50 UTC, deadlypants1973 commented on content/durable-objects/_partials/_durable-objects-pricing.md
> +
```suggestion
```

2023-08-03 13:50 UTC, deadlypants1973 commented on content/durable-objects/_partials/_durable-objects-pricing.md
> +The [Transactional Storage API](/durable-objects/api/transactional-storage-api/) is only accessible from within Durable Objects. Durable Objects do not have to use the storage API, but if your code d
```suggestion
The [Transactional Storage API](/durable-objects/api/transactional-storage-api/) is only accessible from within Durable Objects. Durable Objects do not have to use the Transactional Storage API, but if your code does call methods on `state.storage`, it will incur the following additional charges:
```

2023-08-03 13:50 UTC, deadlypants1973 commented on content/durable-objects/_partials/_durable-objects-pricing.md
> +5.  Each alarm write is billed as a single write request unit.
```suggestion
1.  A request unit is defined as 4 KB of data read or written. A request that writes or reads more than 4 KB will consume multiple units. For example, a 9 KB write will consume three write request units.
2.  List operations are billed by read request units, based on the amount of data examined. For example, a list request that returns a combined 80 KB of keys and values will be billed 20 read request units. A list request that does not return anything is billed for one read request unit.
3.  Delete requests are unmetered. For example, deleting a 100 KB value will be charged one delete request.
4.  Objects will be billed for stored data until the data is removed. Once the data is removed, the object will be cleaned up automatically by the system.
5.  Each alarm write is billed as a single write request unit.
```

2023-08-03 13:50 UTC, deadlypants1973 commented on content/durable-objects/api/alarms-in-durable-objects.md
> +When the alarm's schedlued time comes, the `alarm()` handler will be called.
```suggestion
When the alarm's scheduled time comes, the `alarm()` handler will be called.
```

2023-08-03 13:50 UTC, deadlypants1973 commented on content/durable-objects/api/alarms-in-durable-objects.md
> +Alarms have guaranteed at-least-once execution and are retried automatically when the `alarm()` handler throws. Retries are performed using exponential backoff starting at a two (2) second delay from
```suggestion
Alarms have guaranteed at-least-once execution and are retried automatically when the `alarm()` handler throws. Retries are performed using exponential backoff starting at a two second delay from the first failure with up to six retries allowed.
```

2023-08-03 13:50 UTC, deadlypants1973 commented on content/durable-objects/api/alarms-in-durable-objects.md
> +Alarms have guaranteed at-least-once execution and are retried automatically when the `alarm()` handler throws. Retries are performed using exponential backoff starting at a two (2) second delay from
I know this was my suggestion originally but just reviewed style guide on this https://developers.cloudflare.com/style-guide/formatting/numbers-and-units-of-measurement/

2023-08-03 13:50 UTC, deadlypants1973 commented on content/durable-objects/api/alarms-in-durable-objects.md
> +Alarms are more fine grained than [Cron Triggers](/workers/configuration/cron-triggers/#cron-triggers). A Worker can have up to three Cron Triggers configured at once, but it can have an unlimited am
```suggestion
Alarms are more fine grained than [Cron Triggers](/workers/configuration/cron-triggers/#cron-triggers). A Worker can have up to three Cron Triggers configured at once, but it can have an unlimited amount of Durable Objects, each of which can have an alarm set.
```

2023-08-03 13:50 UTC, deadlypants1973 commented on content/durable-objects/api/alarms-in-durable-objects.md
> +Alarms can be used to build distributed primitives, like queues or batching of work atop Durable Objects. Alarms also provide a mechanism to guarantee that operations within a Durable Object will com
```suggestion
Alarms can be used to build distributed primitives, like queues or batching of work atop Durable Objects. Alarms also provide a mechanism to guarantee that operations within a Durable Object will complete without relying on incoming requests to keep the Durable Object alive. Refer to the [Durable Objects alarms announcement blog post](https://blog.cloudflare.com/durable-objects-alarms/) to learn more about alarms.
```

2023-08-03 13:50 UTC, deadlypants1973 commented on content/durable-objects/api/alarms-in-durable-objects.md
> +The `alarm()` handler has guaranteed at-least-once execution and will be retried upon failure using exponential backoff, starting at two (2) second delays for up to six (6) retries. Retries will be p
```suggestion
The `alarm()` handler has guaranteed at-least-once execution and will be retried upon failure using exponential backoff, starting at two second delays for up to six retries. Retries will be performed if the method fails with an uncaught exception. Calling `deleteAlarm()` inside the `alarm()` handler may prevent retries on a best-effort basis, but is not guaranteed. 
```

2023-08-03 13:50 UTC, deadlypants1973 commented on content/durable-objects/api/alarms-in-durable-objects.md
> +### Example of `alarm()` handler method
```suggestion
### Example `alarm()` handler method
```

2023-08-03 13:50 UTC, deadlypants1973 commented on content/durable-objects/api/alarms-in-durable-objects.md
> +This example implements an `alarm()` handler that wakes the Durable Object up once every 10 seconds to batch requests to a single Durable Object. The `alarm()` handler will delay processing until the
```suggestion
This example implements an `alarm()` handler that wakes the Durable Object once every 10 seconds to batch requests to a single Durable Object. The `alarm()` handler will delay processing until there is enough work in the queue.
```

2023-08-03 13:50 UTC, deadlypants1973 commented on content/durable-objects/api/hibernatable-websockets-api.md
> +The Hibernatable WebSockets API allows a Durable Object that is not currently running an event handler, such as handling a WebSocket message, HTTP request, or [alarm](/durable-objects/api/alarms-in-d
```suggestion
The Hibernatable WebSockets API allows a Durable Object that is not currently running an event handler (such as handling a WebSocket message, HTTP request, or [alarms](/durable-objects/api/alarms-in-durable-objects/)) to be removed from memory while keeping its WebSockets connected ("hibernation").
```

2023-08-03 13:50 UTC, deadlypants1973 commented on content/durable-objects/api/hibernatable-websockets-api.md
> +If an event occurs for a hibernated Durable Object's corresponding handler method, it will return to memory. This will call the Durable Object's constructor, so it is best to minimize work in the con
"minimize work" is a bit vague. What does that actually mean in terms of action steps for the user (if any)?

2023-08-03 13:50 UTC, deadlypants1973 commented on content/durable-objects/api/hibernatable-websockets-api.md
> +  - If you modify `value` after calling this method, those changes will not be retained unless you call this method again. The serialized size of `value` is limited to 2048 bytes, otherwise this meth
```suggestion
  - If you modify `value` after calling this method, those changes will not be retained unless you call this method again. The serialized size of `value` is limited to 2,048 bytes, otherwise this method will throw an error. If you need larger values to survive hibernation, use the [Transactional Storage API](/durable-objects/api/transactional-storage-api/) and pass the corresponding key to this method so it can be retrieved later.
```

2023-08-03 13:50 UTC, deadlypants1973 commented on content/durable-objects/_index.md
> +
Delete extra lines.

2023-08-03 13:50 UTC, deadlypants1973 commented on content/durable-objects/_index.md
> +
```suggestion
```

2023-08-03 13:50 UTC, deadlypants1973 commented on content/durable-objects/_index.md
> +
```suggestion
```

2023-08-03 13:50 UTC, deadlypants1973 commented on content/durable-objects/api/hibernatable-websockets-api.md
> +  - Retrieves the most recent value passed to `serializeAttachment`, or null if none exists.
```suggestion
  - Retrieves the most recent value passed to `serializeAttachment`, or `null` if none exists.
```

2023-08-03 13:50 UTC, deadlypants1973 commented on content/durable-objects/_partials/_durable-objects-pricing.md
> +Requests that hit the Durable Objects in-memory cache or that use the [multi-key versions of get/put/delete methods](/durable-objects/api/transactional-storage-api/) are billed the same as if they we
```suggestion
Requests that hit the Durable Objects in-memory cache or that use the [multi-key versions of `get()`/`put()`/`delete()` methods](/durable-objects/api/transactional-storage-api/) are billed the same as if they were a normal, individual request for each key.
```

2023-08-03 13:50 UTC, deadlypants1973 commented on content/durable-objects/platform/pricing.md
> +Requests that hit the [Durable Objects in-memory cache](/durable-objects/learning/in-memory-state/) or that use the [multi-key versions of get/put/delete methods](/durable-objects/api/transactional-s
```suggestion
Requests that hit the [Durable Objects in-memory cache](/durable-objects/learning/in-memory-state/) or that use the [multi-key versions of `get()`/`put()`/`delete()` methods](/durable-objects/api/transactional-storage-api/) are billed the same as if they were a normal, individual request for each key.
```

2023-08-03 13:50 UTC, deadlypants1973 commented on content/durable-objects/api/hibernatable-websockets-api.md
> +  - Both `request` and `response` are limited to 2048 characters each.
```suggestion
  - Both `request` and `response` are limited to 2,048 characters each.
```

2023-08-03 13:50 UTC, deadlypants1973 commented on content/durable-objects/api/alarms-in-durable-objects.md
> +title: Alarms in Durable Objects
```suggestion
title: Alarms
```

2023-08-03 13:50 UTC, deadlypants1973 commented on content/durable-objects/api/transactional-storage-api.md
> +    Same as `get(key, options)`, above.
```suggestion
  <br/>**Supported options:** Same as `get(key, options)`, above.
```

2023-08-03 13:50 UTC, deadlypants1973 commented on content/durable-objects/examples/durable-objects-rollup-es-modules.md
> +You can find the full code [on GitHub](https://github.com/cloudflare/durable-objects-rollup-esm).
```suggestion
Find the [full code for this example on GitHub](https://github.com/cloudflare/durable-objects-rollup-esm). 
```

2023-08-03 13:50 UTC, deadlypants1973 commented on content/durable-objects/examples/durable-objects-typescript-rollup-es-modules.md
> +You can find the full code [on GitHub](https://github.com/cloudflare/durable-objects-typescript-rollup-esm).
```suggestion
Find the [full code for this example on GitHub](https://github.com/cloudflare/durable-objects-typescript-rollup-esm). 
```

2023-08-03 13:50 UTC, deadlypants1973 commented on content/durable-objects/get-started.md
> +$ wrangler deploy
```suggestion
$ npx wrangler deploy
```

2023-08-03 13:50 UTC, deadlypants1973 commented on content/durable-objects/how-to/create-durable-object-stubs.md
> +To make new requests to the Durable Object, you must call `OBJECT_NAMESPACE.get(id)` again to get a new Durable Object stub, keeping in mind that there are no ordering guarantees between requests to
```suggestion
To make new requests to the Durable Object, you must call `OBJECT_NAMESPACE.get(id)` again to get a new Durable Object stub. There are no ordering guarantees between requests to the new stub compared to the old one. If ordering is not a concern, you can create a new Durable Object for every request.
```

2023-08-03 13:50 UTC, deadlypants1973 commented on content/durable-objects/learning/durable-objects-migrations.md
> +You must initiate a migration process when you create a new Durable Object class, or rename, delete, or transfer an existing Durable Objects class. This process informs the Workers runtime of the cha
```suggestion
You must initiate a migration process when you:

* Create a new Durable Object class.
* Rename a Durable Object class.
* Delete a Durable Object class.
* Transfer an existing Durable Objects class.

This process informs the Workers runtime of the changes and provides it with instructions on how to deal with those changes.
```

2023-08-03 13:50 UTC, deadlypants1973 commented on content/durable-objects/learning/durable-objects-migrations.md
> +You must initiate a migration process when you create a new Durable Object class, or rename, delete, or transfer an existing Durable Objects class. This process informs the Workers runtime of the cha
The sentence formatting was hard to read.

2023-08-03 13:50 UTC, deadlypants1973 commented on content/durable-objects/learning/durable-objects-migrations.md
> +Migrations can also be used for transferring stored data between two Durable Object classes. Rename migrations are used to transfer stored Durable Objects between two Durable Object classes in the sa
```suggestion
Migrations can also be used for transferring stored data between two Durable Object classes:

* Rename migrations are used to transfer stored Durable Objects between two Durable Object classes in the same Worker code file. 
* Transfer migrations are used to transfer stored Durable Objects between two Durable Object classes in different Worker code files.
```

2023-08-03 13:50 UTC, deadlypants1973 commented on content/durable-objects/learning/durable-objects-migrations.md
> +After a migration, any existing bindings to the original Durable Object class (for example, from other Workers) will automatically forward to the updated destination class. However, any Workers bound
```suggestion
After a migration, any existing bindings to the original Durable Object class (for example, from other Workers) will automatically forward to the updated destination class. However, any Workers bound to the updated Durable Object class must update their Durable Object binding configuration in the `wrangler.toml` file for their next deployment.
```
`[durable_objects]` depends on user's preference for toml syntax. They might write it differently. So to say bindings config is the more correct explanation.

2023-08-03 13:50 UTC, deadlypants1973 commented on content/durable-objects/platform/data-location.md
> +To use a jurisdiction, first create a jurisidictional subnamespace in your `worker.js` file:
```suggestion
To use a jurisdiction, first create a jurisidictional subnamespace in your Worker's entry point:
```

2023-08-03 13:50 UTC, deadlypants1973 commented on content/durable-objects/platform/data-location.md
> +---
```suggestion
```

2023-08-03 13:50 UTC, deadlypants1973 commented on content/durable-objects/platform/data-location.md
> +---
```suggestion
```

2023-08-03 13:50 UTC, deadlypants1973 commented on content/durable-objects/platform/data-location.md
> +---
```suggestion
```

2023-08-03 13:50 UTC, deadlypants1973 commented on content/durable-objects/platform/data-location.md
> +---
```suggestion
```

2023-08-03 13:50 UTC, deadlypants1973 commented on content/durable-objects/platform/data-location.md
> +---
```suggestion
```

2023-08-03 13:50 UTC, deadlypants1973 commented on content/durable-objects/platform/known-issues.md
> +A Durable Object is instantiated close to where the initial `get()`is made. This may not be in the data center the user is connected to, but in most cases, it will be in close proximity.
```suggestion
A Durable Object is instantiated close to where the initial `get()` is made. This may not be in the data center the user is connected to, but in most cases, it will be in close proximity.
```

2023-08-03 13:50 UTC, deadlypants1973 commented on content/durable-objects/api/transactional-storage-api.md
> +    - By default, the system will pause delivery of I/O events to the object while a storage operation is in progress, in order to avoid unexpected race conditions. Pass `allowConcurrency: true` to o
object? or Object?

2023-08-03 13:50 UTC, deadlypants1973 commented on content/durable-objects/api/transactional-storage-api.md
> +  - Retrieves the values associated with each of the provided keys. The type of each returned value in the [Map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map)
```suggestion
  - Retrieves the values associated with each of the provided keys. The type of each returned value in the [`Map`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map) will be whatever was previously written for the corresponding key. Results in the `Map` will be sorted in increasing order of their UTF-8 encodings, with any requested keys that do not exist being omitted. Supports up to 128 keys at a time.
```

2023-08-03 13:50 UTC, deadlypants1973 commented on content/durable-objects/api/transactional-storage-api.md
> +  - Stores the value and associates it with the given key. The value can be any type supported by the [structured clone algorithm](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Str
```suggestion
  - Stores the value and associates it with the given key. The value can be any type supported by the [structured clone algorithm](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm), which is true of most types. Keys are limited to a max size of 2,048 bytes and values are limited to 128 KiB (131,072 bytes).<br><br>
```

2023-08-03 13:50 UTC, deadlypants1973 commented on content/durable-objects/api/transactional-storage-api.md
> +The `put()` method returns a `Promise`, but most applications can discard this promise without using `await`. The `Promise` usually completes immediately, because `put()` writes to an in-memory write
```suggestion
The `put()` method returns a `Promise`, but most applications can discard this promise without using `await`. The `Promise` usually completes immediately, because `put()` writes to an in-memory write buffer that is flushed to disk asynchronously. However, if an application performs a large number of `put()` without waiting for any I/O, the write buffer could theoretically grow large enough to cause the isolate to exceed its 128 MB memory limit. To avoid this scenario, such applications should use `await` on the `Promise` returned by `put()`. The system will then apply backpressure onto the application, slowing it down so that the write buffer has time to flush. Using `await` will disable automatic write coalescing.
```

2023-08-03 13:50 UTC, deadlypants1973 commented on content/durable-objects/api/transactional-storage-api.md
> +  - Supports up to 128 key-value pairs at a time. Each key is limited to a maximum size of 2048 bytes and each value is limited to 128 KiB (131072 bytes).
```suggestion
  - Supports up to 128 key-value pairs at a time. Each key is limited to a maximum size of 2,048 bytes and each value is limited to 128 KiB (131,072 bytes).
```

2023-08-03 13:50 UTC, deadlypants1973 commented on content/durable-objects/api/transactional-storage-api.md
> +  - The type of each returned value in the [Map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map) will be whatever was previously written for the corresponding ke
```suggestion
  - The type of each returned value in the [`Map`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map) will be whatever was previously written for the corresponding key. 
```

2023-08-03 13:50 UTC, deadlypants1973 commented on content/durable-objects/api/transactional-storage-api.md
> +  - Provides access to the `put()`, `get()`, `delete()` and `list()` methods documented above to run in the current transaction context. In order to get transactional behavior within a transaction cl
Is the \<br>\<br> here necessary?

2023-08-03 13:50 UTC, deadlypants1973 commented on content/durable-objects/api/transactional-storage-api.md
> +  - Retrieves the current alarm time (if set) as integer milliseconds since epoch. The alarm is considered to be set if it has not started, or if it has failed and any retry has not begun. If no alar
```suggestion
  - Retrieves the current alarm time (if set) as integer milliseconds since epoch. The alarm is considered to be set if it has not started, or if it has failed and any retry has not begun. If no alarm is set, `getAlarm()` returns `null`.
```

2023-08-03 13:50 UTC, deadlypants1973 commented on content/durable-objects/api/transactional-storage-api.md
> +    <br/> If `setAlarm()` is called with a time equal to or before `Date.now()`,  the alarm will be scheduled for asynchronous execution in the immediate future. If the alarm handler is currently exe
```suggestion
    <br/> If `setAlarm()` is called with a time equal to or before `Date.now()`, the alarm will be scheduled for asynchronous execution in the immediate future. If the alarm handler is currently executing in this case, it will not be canceled. Alarms can be set to millisecond granularity and will usually execute within a few milliseconds after the set time, but can be delayed by up to a minute due to maintenance or failures while failover takes place.
```

2023-08-03 13:50 UTC, deadlypants1973 commented on content/durable-objects/get-started.md
> + 1. Log in to the [Cloudflare dashboard](https://dash.cloudflare.com/) and select your account.
```suggestion
 1. Log in to the [Cloudflare dashboard](https://dash.cloudflare.com/), and select your account.
```

2023-08-03 13:50 UTC, deadlypants1973 commented on content/durable-objects/how-to/access-durable-object-from-a-worker.md
> +The following code gives you a new Durable Object ID. You can add this code in your `index.js` file.
```suggestion
The following code gives you a new Durable Object ID. Add the following to your Worker code.
```

2023-08-03 13:50 UTC, deadlypants1973 commented on content/durable-objects/how-to/access-durable-object-from-a-worker.md
> +---
```suggestion
```

2023-08-03 13:50 UTC, deadlypants1973 commented on content/durable-objects/how-to/access-durable-object-from-a-worker.md
> +---
```suggestion
```

2023-08-03 13:50 UTC, deadlypants1973 commented on content/durable-objects/how-to/access-durable-object-from-a-worker.md
> +---
```suggestion
```

2023-08-03 13:50 UTC, deadlypants1973 commented on content/durable-objects/how-to/access-durable-object-from-a-worker.md
> +---
```suggestion
```

2023-08-03 13:50 UTC, deadlypants1973 commented on content/durable-objects/how-to/access-durable-object-from-a-worker.md
> +---
```suggestion
```

2023-08-03 13:50 UTC, deadlypants1973 commented on content/durable-objects/how-to/access-durable-object-from-a-worker.md
> +title: Access a Durable Object from a Worker
Reading this page, the connection between a DO namespace and a class is unclear. The get started only mentioned creating a class. This page seems to introduce the architecture of DO namespace having classes within it. This architecture could be explained better from a beginner perspective for users who have just finished the get started and have transitioned to this page.

2023-08-03 13:50 UTC, deadlypants1973 commented on content/durable-objects/how-to/create-durable-object-stubs.md
> +
Same for this page. What is the connection between a class, an ID, a stub, a namespace, and a DO? Architecture is unclear. After I have created my first class in the get started, what is this page telling me to do?

2023-08-03 13:50 UTC, deadlypants1973 commented on content/durable-objects/how-to/create-durable-object-stubs.md
> +
Do the follow 1,2,3 steps relate to creating a DO stub? There's a lot of conceptual information up top but no guidance into why the user is going into the 1,2,3.

2023-08-03 13:50 UTC, deadlypants1973 commented on content/durable-objects/learning/durable-objects-migrations.md
> +{{<Aside type="warning" header="Important">}}
```suggestion
{{<Aside type="warning" header="Delete migrations">}}
```

2023-08-03 13:50 UTC, deadlypants1973 commented on content/durable-objects/learning/durable-objects-migrations.md
> +Migrations are performed through the `[[migrations]]` configurations key in your `wrangler.toml` file.
```suggestion
A migration is a mapping process from a class name to a runtime state. You perform a migration when:

* Creating a new Durable Object class.
* Renaming an existing Durable Object class.
* Deleting an existing Durable Object class.
* Transferring an existing Durable Object class.

Migrations are performed through the `[[migrations]]` configurations key in your `wrangler.toml` file. 
```

2023-08-03 13:50 UTC, deadlypants1973 commented on content/durable-objects/learning/durable-objects-migrations.md
> +It is possible to define a migration through extra arguments to the [`wrangler deploy`](/workers/wrangler/commands/#deploy) command. When taking this route, any migrations listed in the `wrangler.tom
```suggestion
It is possible to define a migration through extra arguments to the [`wrangler deploy`](/workers/wrangler/commands/#deploy) command. When taking this route, any migrations listed in the [`wrangler.toml`](/workers/wrangler/configuration/#migrations) configuration file are ignored.
```

2023-08-03 13:50 UTC, deadlypants1973 commented on content/durable-objects/learning/websockets.md
> +Durable Objects are a coordinated state tool for [Cloudflare Workers](/workers/), which are often used in parallel with WebSockets to persist state over multiple clients and connections.
```suggestion
Durable Objects are a coordinated state tool for [Cloudflare Workers](/workers/), which are often used in parallel with [WebSockets](/workers/runtime-apis/websockets/) to persist state over multiple clients and connections. 
```

2023-08-03 13:50 UTC, deadlypants1973 commented on content/durable-objects/learning/websockets.md
> +If your application needs to coordinate among multiple WebSocket connections, such as a chat room or game match, you will need to [create a Durable Object](/durable-objects/how-to/create-durable-obje
```suggestion
If your application needs to coordinate among multiple WebSocket connections, such as a chat room or game match, you will need to [create a Durable Object](/durable-objects/how-to/create-durable-object-stubs/) so clients send messages to a single-point-of-coordination. 
```

2023-08-03 13:50 UTC, deadlypants1973 commented on content/durable-objects/learning/websockets.md
> +WebSockets are most useful when combined with Durable Objects. When a client connects to your application using a WebSocket, you need a way for server-generated events to be sent back to the existing
```suggestion
WebSockets are most useful when combined with Durable Objects. When a client connects to your application using a WebSocket, you need a way for server-generated events to be sent back to the existing socket connection.
```

2023-08-03 13:50 UTC, deadlypants1973 commented on content/durable-objects/learning/websockets.md
> +As part of Durable Objects, Workers can act as WebSocket endpoints – including as a client or as a server.
```suggestion
As part of Durable Objects, Workers can act as WebSocket endpoints – including as a client or as a server.
```

2023-08-03 13:50 UTC, deadlypants1973 commented on content/durable-objects/learning/websockets.md
> +Durable Objects can use the web standard APIs described in [Use WebSockets](/workers/runtime-apis/websockets/use-websockets/). When using a Durable Object to terminate a WebSocket (as opposed to usin
```suggestion
Durable Objects can use the web standard APIs described in [WebSockets](/workers/runtime-apis/websockets/use-websockets/). When using a Durable Object to terminate a WebSocket (as opposed to using it as a WebSocket client) the [Hibernatable WebSockets API](/durable-objects/api/hibernatable-websockets-api/) has significant advantages and should be preferred over the web standard APIs. 
```
Going to rename this page soon.

2023-08-03 13:50 UTC, deadlypants1973 commented on content/durable-objects/platform/data-location.md
> +---
```suggestion
```

2023-08-03 13:50 UTC, deadlypants1973 commented on content/durable-objects/platform/data-location.md
> +---
```suggestion
```

2023-08-03 13:50 UTC, deadlypants1973 commented on content/durable-objects/platform/graphql-analytics.md
> +You can use [GraphQL Introspection](/analytics/graphql-api/features/discovery/introspection/) to get information on the fields exposed by each data sets.
```suggestion
Use [GraphQL Introspection](/analytics/graphql-api/features/discovery/introspection/) to get information on the fields exposed by each data sets.
```

2023-08-03 13:50 UTC, deadlypants1973 commented on content/durable-objects/platform/graphql-analytics.md
> +## Example of GraphQL query for Durable Objects
```suggestion
## Example GraphQL query for Durable Objects
```

2023-08-03 13:50 UTC, deadlypants1973 commented on content/durable-objects/platform/limits.md
> +Durable Objects have been built such that the number of Objects in the system do not need to be limited. You can create and run as many separate Durable Objects as you want. The main limit to your us
```suggestion
Durable Objects have been built such that the number of Objects in the system do not need to be limited. You can create and run as many separate Durable Objects as you want. The main limit to your usage of Durable Objects is the total storage limit per account. If you need more storage, contact your account team or complete the [Limit Increase Request Form](https://forms.gle/ukpeZVLWLnKeixDu7) and we will contact you with next steps.
```

2023-08-03 13:50 UTC, deadlypants1973 commented on content/durable-objects/platform/troubleshooting.md
> +### Cannot apply `--delete-class` migration to class
```suggestion
### Cannot apply `--delete-class` migration to class.
```

2023-08-03 13:50 UTC, deadlypants1973 commented on content/durable-objects/platform/troubleshooting.md
> +### Durable Object reset because its code was updated
```suggestion
### Durable Object reset because its code was updated.
```

2023-08-03 13:50 UTC, deadlypants1973 commented on content/durable-objects/tutorials/build-a-counter/index.md
> +## Build a counter
This is not a tutorial as there are no steps. This would be an example. https://developers.cloudflare.com/style-guide/documentation-content-strategy/content-types/tutorial/#structure

2023-08-03 13:50 UTC, deadlypants1973 commented on content/durable-objects/tutorials/durable-object-example/index.md
> +## Durable Object example
Same comment. This is not a tutorial and should be moved to examples. https://developers.cloudflare.com/style-guide/documentation-content-strategy/content-types/tutorial/#structure

2023-08-03 13:50 UTC, deadlypants1973 commented on content/durable-objects/get-started.md
> +  - `script_name` - Optional. Defaults to the current [environment's](/workers/wrangler/environments/) Worker script.
This should link to /durable-objects/platform/environments/.
```suggestion
  - `script_name` - Optional. Defaults to the current [environment's](/durable-objects/platform/environments/) Worker script.
```

2023-08-03 13:50 UTC, deadlypants1973 commented on content/durable-objects/learning/durable-objects-migrations.md
> +All migrations are applied at deployment. Each migration can only be applied once per [environment](/workers/wrangler/environments/).
```suggestion
All migrations are applied at deployment. Each migration can only be applied once per [environment](/durable-objects/platform/environments/).
```

2023-08-03 13:50 UTC, deadlypants1973 commented on content/durable-objects/platform/environments.md
> +If you are using Wrangler [environments](/workers/wrangler/environments/), you must specify any Durable Object bindings you wish to use on a per-environment basis.
This link stays the same because the user will need to reference the Workers environments page for the original concept. All other environments links on DO tile should point to this page though.

2023-08-03 13:50 UTC, deadlypants1973 commented on content/durable-objects/platform/environments.md
> +If you are using Wrangler [environments](/workers/wrangler/environments/), you must specify any Durable Object bindings you wish to use on a per-environment basis.
```suggestion
[Wrangler](/workers/wrangler/install-and-update/) allows you to deploy the same Worker application with different configuration for each [environment](/workers/wrangler/environments/).

If you are using Wrangler environments, you must specify any [Durable Object bindings](/workers/configuration/bindings/#durable-object-bindings) you wish to use on a per-environment basis. 
```

2023-08-03 13:50 UTC, deadlypants1973 commented on content/durable-objects/platform/known-issues.md
> +[`wrangler dev`](/workers/wrangler/commands/#dev) has read access to Durable Object storage, but writes will be kept in memory and will not affect persistent data. However, if you specify the `script
```suggestion
[`wrangler dev`](/workers/wrangler/commands/#dev) has read access to Durable Object storage, but writes will be kept in memory and will not affect persistent data. However, if you specify the `script_name` explicitly in the [Durable Object binding](/workers/configuration/bindings/#durable-object-bindings), then writes will affect persistent data. Wrangler will emit a warning in that case.
```

2023-08-03 13:50 UTC, deadlypants1973 approved these changes
PCX

Final things to consider:

1. DO architecture is not clear. How do a class, stub, ID, namespace relate to each other? Get started guide defines a class. How should the user think about architecture from there?

2. The tutorials have no numbered steps or instructions and should be moved to examples. If there were to be numbered steps, a start goal and end product that the user is guided through, then this would be a tutorial.

3. DO requires a Worker project with numerous files. It's important for the user to know what information should go into the entry point file (index.js) and what info can go in other files. Refer to Peter's comment in dev plat chat.

4. Mentions of "Worker script" needs to be removed from the tile completely and changed to something correct in relation to point 3.

2023-08-03 17:24 UTC, pedrosousa approved these changes

2023-08-03 17:24 UTC, pedrosousa commented on content/_redirects
> +/workers/learning/using-durable-objects/ /durable-objects/get-started/ 301
There's already a redirect for this source URL (on line 949). You should update that line (setting the target URL to `/durable-objects/get-started/`) instead of adding this new redirect.

2023-08-03 17:24 UTC, pedrosousa commented on content/_redirects
You should delete these files in the same PR, since you're creating redirects for these pages and they will no longer be accessible:
https://github.com/cloudflare/cloudflare-docs/blob/production/content/workers/runtime-apis/durable-objects.md
https://github.com/cloudflare/cloudflare-docs/blob/production/content/workers/configuration/durable-objects.md

2023-08-04 10:00 UTC, Maddy-Cloudflare commented on content/_redirects
Deleting the files would remove the content referencing Durable Objects from the Worker's docs. Instead, I want to keep the files and simply redirect. 

I'm following the same example of R2 in the Worker's docs: https://developers.cloudflare.com/workers/runtime-apis/

If you select R2 under the Runtime APIs page, it redirects to the R2's docs. That's what I'm trying to achieve with Durable Objects. 😄

2023-08-04 10:05 UTC, merged

2023-08-04 10:56 UTC, pedrosousa commented on content/_redirects
You can use external links, which is the usual way of addressing this requirement.
For example, these links in the Terraform tile redirect to a different place and they don't have associated pages (their files have just a front-matter):
![image](https://github.com/cloudflare/cloudflare-docs/assets/680496/8f5070a3-e759-49bb-a73d-942c474e02a6)

For example, here's the corresponding file that creates the "Single Redirects" link as seen above:
https://github.com/cloudflare/cloudflare-docs/blob/production/content/terraform/additional-configurations/link-dynamic-redirects.md?plain=1

2023-08-04 12:58 UTC, deadlypants1973 commented on content/_redirects
@pedrosousa agreed and I have made a ticket to address this in Workers docs