[API Shield] Volumetric Abuse Detection revision
cloudflare/cloudflare-docs pull request #9602
Opened 2023-06-26 20:27 UTC by patriciasantaana

2023-06-27 11:04 UTC, deadlypants1973 requested changes

2023-06-27 11:04 UTC, deadlypants1973 commented on content/api-shield/security/volumetric-abuse-detection.md
> +Because these rate limits are generated on a per-session basis, they are not as susceptible to false positives as traditional rate limits based on IP addresses are when traffic to your API increases.
```suggestion
Volumetric Abuse Detection rate limits are generated on a per-session basis. Unlike traditional rate limits, which are based on IP addresses, Volumetric Abuse Detection rate limits are not as susceptible to false positives when traffic to your API increases.
```

2023-06-27 11:04 UTC, deadlypants1973 commented on content/api-shield/security/volumetric-abuse-detection.md
> +These rate limits are a way to prevent blatant volumetric abuse while minimizing false positives. If you are trying to prevent abusive bot traffic altogether, refer to Cloudflare’s [Bot solutions](/b
```suggestion
Volumetric Abuse Detection rate limits are a way to prevent blatant volumetric abuse while minimizing false positives. If you are trying to prevent abusive bot traffic altogether, refer to Cloudflare’s [Bot solutions](/bots/).
```
When not using proper nouns (like "Volumetric Abuse Detection rate limits" instead of 'they') to describe concepts, it's hard for me to understand what you are describing or comparing.

2023-06-27 11:04 UTC, deadlypants1973 commented on content/api-shield/security/volumetric-abuse-detection.md
> +After adding a session identifier, allow 24 hours for rate limit recommendations to appear on endpoints in Endpoint Management. Recommendations will continue to update if your traffic pattern changes
Where is Endpoint Management? It's also bolded below and not here.

2023-06-27 11:04 UTC, deadlypants1973 commented on content/api-shield/security/volumetric-abuse-detection.md
> +## Limitations
```suggestion
## Limits
```

2023-06-27 11:04 UTC, deadlypants1973 commented on content/api-shield/security/volumetric-abuse-detection.md
> +{{<Aside type="Note">}}
```suggestion
{{<Aside type="note" header="p-values">}}
```

2023-06-27 11:04 UTC, deadlypants1973 commented on content/api-shield/security/volumetric-abuse-detection.md
> +The p-values describe what percentile of your traffic fits below the value. For example, if your p90 value is 83, then 90% of your sessions had maximum request rates less than 83 requests per 10 minu
```suggestion
p-values describe what percentile of your traffic fits below the value. For example, if your p90 value is `83`, then 90% of your sessions had maximum request rates less than 83 requests per 10 minutes.
```

2023-06-27 11:04 UTC, deadlypants1973 commented on content/api-shield/security/volumetric-abuse-detection.md
> +You can also see our confidence in the recommendation and how many unique sessions we have seen over the last 7 days. In general, endpoints with fewer unique sessions and high variability of user beh
```suggestion
In **Endpoint Management**, you can review our confidence in the recommendation and how many unique sessions we have seen over the last seven (7) days. In general, endpoints with fewer unique sessions and high variability of user behavior will have lower confidence scores.
```

2023-06-27 11:04 UTC, deadlypants1973 commented on content/api-shield/security/volumetric-abuse-detection.md
> +In the endpoint row, select **Create rule** to be automatically redirected to the [Advanced Rate Limiting](/waf/rate-limiting-rules/create-zone-dashboard/) rules dashboard with your endpoint informat
This section should change to

To <accomplish task>:

1. Log in to the [Cloudflare dashboard](https://dash.cloudflare.com), and select your account.
2. Step 
3. Step
4. Step
5. Select **Deploy** to activate your rule.

2023-06-27 11:04 UTC, deadlypants1973 commented on content/api-shield/security/volumetric-abuse-detection.md
> +Rate limit recommendations [are available via the API](/api/operations/api-shield-endpoint-management-retrieve-information-about-an-operation) if you would like to dynamically update rate limits over
```suggestion
[Rate limit recommendations are available via the API](/api/operations/api-shield-endpoint-management-retrieve-information-about-an-operation) if you would like to dynamically update rate limits over time.
```
PCX > Style Guide > UX > Content accessibility > UI content accessibility best practices

2023-06-27 11:04 UTC, deadlypants1973 commented on content/api-shield/security/volumetric-abuse-detection.md
> +While API Shield will always calculate recommendations when session identifiers are configured, enabling session-based rate limits requires a subscription to Advanced Rate Limiting.
```suggestion
API Shield will always calculate recommendations when session identifiers are configured. To enable session-based rate limits, subscribe to Advanced Rate Limiting.
```
Instructions on how to subscribe to Advanced Rate Limiting needed.

2023-06-27 17:03 UTC, patriciasantaana commented on content/api-shield/security/volumetric-abuse-detection.md
> +## Limitations
Other pages in the product docs call it Limitations! will keep as is for consistency

2023-06-28 09:40 UTC, deadlypants1973 approved these changes
PCX

2023-06-28 09:40 UTC, deadlypants1973 commented on content/api-shield/security/volumetric-abuse-detection.md
> +This feature currently requires a [session identifier](/api-shield/get-started/#set-up-session-identifiers), like an authorization token available as a request header or cookie.
```suggestion
Volumetric Abuse Detection currently requires a [session identifier](/api-shield/get-started/#set-up-session-identifiers), like an authorization token available as a request header or cookie.
```

2023-06-28 09:40 UTC, deadlypants1973 commented on content/api-shield/security/volumetric-abuse-detection.md
> +1. Log in to the [Cloudflare dashboard](https://dash.cloudflare.com/), and select your account and domain.
```suggestion
### Create rate limits

To create rate limits:

1. Log in to the [Cloudflare dashboard](https://dash.cloudflare.com/), and select your account and domain.
```

2023-06-28 09:40 UTC, deadlypants1973 commented on content/api-shield/security/volumetric-abuse-detection.md
> +After adding a session identifier, allow 24 hours for rate limit recommendations to appear on endpoints in **Endpoint Management** in the Cloudflare dashboard. Recommendations will continue to update
```suggestion
After adding a session identifier, allow 24 hours for rate limit recommendations to appear on endpoints in **Security** > **API Shield** > **Endpoint Management** on the Cloudflare dashboard. Recommendations will continue to update if your traffic pattern changes
```

2023-06-28 09:40 UTC, deadlypants1973 commented on content/api-shield/security/volumetric-abuse-detection.md
> +After adding a session identifier, allow 24 hours for rate limit recommendations to appear on endpoints in **Endpoint Management** in the Cloudflare dashboard. Recommendations will continue to update
felt weird to say 'in' twice so changed one to on.

2023-06-28 15:31 UTC, merged