Adds troubleshooting information to TCP Sockets docs
cloudflare/cloudflare-docs pull request #9640
Opened 2023-06-28 11:06 UTC by dom96

2023-06-28 14:09 UTC, deadlypants1973 requested changes
PCX

2023-06-28 14:09 UTC, deadlypants1973 commented on content/workers/runtime-apis/tcp-sockets.md
> +Below is a description of common error messages you may see when working with TCP Sockets, what they mean and how to solve them.
```suggestion
Review descriptions of common error messages you may see when working with TCP Sockets, what the error messages mean, and how to solve them.
```

2023-06-28 14:09 UTC, deadlypants1973 commented on content/workers/runtime-apis/tcp-sockets.md
> +If you need to connect to addresses on port 80 or 443 to make HTTP requests, consider instead using `fetch`.
```suggestion
If you need to connect to addresses on port `80` or `443` to make HTTP requests, use [`fetch`](/workers/runtime-apis/fetch/).
```

2023-06-28 14:09 UTC, deadlypants1973 commented on content/workers/runtime-apis/tcp-sockets.md
> +Your socket is connecting to an address that was disallowed. Examples include Cloudflare IPs, localhost, and private network IPs.
```suggestion
Your socket is connecting to an address that was disallowed. Examples of a disallowed address include Cloudflare IPs, `localhost`, and private network IPs.
```

2023-06-28 14:09 UTC, deadlypants1973 commented on content/workers/runtime-apis/tcp-sockets.md
> +Your socket is connecting back to the Worker that initiated the outbound connection. In other words, it is connecting back to itself. This is currently not supported. Get in touch with us if this is
```suggestion
Your socket is connecting back to the Worker that initiated the outbound connection. In other words, the Worker is connecting back to itself. This is currently not supported.
```
Describe how the customer contacts. Discord? Support? Email?

2023-06-28 14:09 UTC, deadlypants1973 commented on content/workers/runtime-apis/tcp-sockets.md
> +Your socket is connecting to an address on port 25. This is usually the port used for SMTP mail servers. Workers cannot create outbound connections on port `25`. Consider using [Cloudflare Email Work
```suggestion
Your socket is connecting to an address on port `25`. This is usually the port used for SMTP mail servers. Workers cannot create outbound connections on port `25`. Consider using [Cloudflare Email Workers](/email-routing/email-workers/) instead.
```

2023-06-28 18:20 UTC, irvinebroque approved these changes
Huge thank you, this is excellent

2023-06-28 18:20 UTC, irvinebroque commented on content/workers/runtime-apis/tcp-sockets.md
> +Your socket is connecting back to the Worker that initiated the outbound connection. In other words, it is connecting back to itself. This is currently not supported. Get in touch with us if this is
Leave blank

2023-06-29 15:09 UTC, deadlypants1973 approved these changes

2023-06-29 15:20 UTC, merged