Update geo-steering.md
cloudflare/cloudflare-docs pull request #9692
Opened 2023-07-01 08:20 UTC by CFSeiya

it is related to ticket 2841372. Customer's request

2023-07-01 19:38 UTC, cicku requested changes
Should be _in the same region_

2023-07-05 16:43 UTC, patriciasantaana commented on content/load-balancing/understand-basics/traffic-steering/steering-policies/geo-steering.md
> +When there is one pool in the region and it is unavailable, if there is a fallback pool, it would be used.
```suggestion
A fallback pool will be used if there is only one pool in the region and it is unavailable.
```

2023-07-05 16:44 UTC, patriciasantaana commented on content/load-balancing/understand-basics/traffic-steering/steering-policies/geo-steering.md
> +If there are some pools in the region, the order of the pool will be respected. For example, when the 1st pool is down, 2nd pool will be used.
```suggestion
If there are multiple pools in the same region, the order of the pools will be respected. For example, if the first pool is unavailable, the second pool will be used.
```

2023-07-05 16:46 UTC, patriciasantaana approved these changes

2023-07-05 16:49 UTC, patriciasantaana commented on content/load-balancing/understand-basics/traffic-steering/steering-policies/geo-steering.md
> +A fallback pool will be used if there is only one pool in the region and it is unavailable.
```suggestion
A fallback pool will be used if there is only one pool in the same region and it is unavailable.
```

2023-07-05 18:56 UTC, cicku approved these changes

2023-07-05 19:41 UTC, merged