[Radar] Add URL Scanner docs
cloudflare/cloudflare-docs pull request #9718
Opened 2023-07-04 16:34 UTC by meddulla

2023-07-05 08:40 UTC, carlosefr approved these changes

2023-07-05 15:10 UTC, carlosefr approved these changes

2023-07-06 20:07 UTC, haleycode requested changes
Added mostly small grammar and link structure tweaks.

2023-07-06 20:07 UTC, haleycode commented on content/radar/investigate/url-scanner.md
> +In order to better understand Internet usage around the world, Radar also showcases a URL Scanner at [https://radar.cloudflare.com/scan](https://radar.cloudflare.com/scan).
```suggestion
In order to better understand Internet usage around the world, Radar provides a URL Scanner at [https://radar.cloudflare.com/scan](https://radar.cloudflare.com/scan).
```

2023-07-06 20:07 UTC, haleycode commented on content/radar/investigate/url-scanner.md
> +To make your first URL scan using the API, you must obtain a URL Scanner specific [API token](/fundamentals/api/get-started/create-token/) first. Create a Custom Token, with _Account_ > _URL Scanner_
```suggestion
To make your first URL scan using the API, you must obtain a URL Scanner specific [API token](/fundamentals/api/get-started/create-token/). Create a Custom Token with _Account_ > _URL Scanner_ in the **Permissions** group, and select _Edit_ as the access level.
```

2023-07-06 20:07 UTC, haleycode commented on content/radar/investigate/url-scanner.md
> +By default, the report will have a `Public` visibility level, which means it will appear in the [recent scan's](https://radar.cloudflare.com/scan#recent-scans) list and in search results. It will als
```suggestion
By default, the report will have a `Public` visibility level, which means it will appear in the [recent scans](https://radar.cloudflare.com/scan#recent-scans) list and in search results. It will also include a single screenshot with desktop resolution.
```

2023-07-06 20:07 UTC, haleycode commented on content/radar/investigate/url-scanner.md
> +Above, the visibility level is set as `Unlisted`, which means that the scan report won't be included in the [recent scan's](https://radar.cloudflare.com/scan#recent-scans) list nor in search results.
```suggestion
Above, the visibility level is set as `Unlisted`, which means that the scan report won't be included in the [recent scans](https://radar.cloudflare.com/scan#recent-scans) list nor in search results. In  effect, only users with knowledge of the scan ID will be able to access it.
```

2023-07-06 20:07 UTC, haleycode commented on content/radar/investigate/url-scanner.md
> +There will also be 3 screenshots taken of the webpage, one per target device type and the [`User-Agent`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent) HTTP Header will be set
```suggestion
There will also be three screenshots taken of the webpage, one per target device type. The [`User-Agent`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent) HTTP Header will be set as "My-custom-user-agent". Note that you can set any custom HTTP header, including [Authorization](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Authorization).
```

2023-07-06 20:07 UTC, haleycode commented on content/radar/investigate/url-scanner.md
> +Once the URL Scan submission is made, the current progress can be checked by calling `https://api.cloudflare.com/client/v4/accounts/<accountId>/urlscanner/scan/<scanId>` (the `scanId` will be the `re
```suggestion
Once the URL Scan submission is made, the current progress can be checked by calling `https://api.cloudflare.com/client/v4/accounts/<accountId>/urlscanner/scan/<scanId>`. The `scanId` will be the `result.uuid` value returned in the previous response.
```

2023-07-06 20:07 UTC, haleycode commented on content/radar/investigate/url-scanner.md
> +Of those above, here are some highlights:
```suggestion
Some examples of more specific properties include:
```

2023-07-06 20:07 UTC, haleycode commented on content/radar/investigate/url-scanner.md
> +While the scan is in progress, the HTTP status code will be `202`, once it's finished it will be `200`. Clients are advised to poll every 10-30 seconds.
"Clients are advised to poll" is a bit confusing. Should this be something like, "You should check scan progress every 10-30 seconds while the scan is running." ?

2023-07-06 20:07 UTC, haleycode commented on content/radar/investigate/url-scanner.md
> +- `verdicts.overall.malicious` - Whether the website was considered, _at the time of the scan_, malicious. Please check the remaining properties for each subsystem(s) specific threats detected.
```suggestion
- `verdicts.overall.malicious` - Whether the website was considered malicious _at the time of the scan_. Please check the remaining properties for each subsystem(s) for specific threats detected.
```

2023-07-06 20:07 UTC, haleycode commented on content/radar/investigate/url-scanner.md
> +Visit `https://developers.cloudflare.com/api/operations/urlscanner-get-scan` for the full response schema.
```suggestion
The [Get URL Scan](/api/operations/urlscanner-get-scan) API endpoint documentation contains the full response schema.
```

2023-07-06 20:07 UTC, haleycode commented on content/radar/investigate/url-scanner.md
> +In order to fetch the scan's [screenshots](https://developers.cloudflare.com/api/operations/urlscanner-get-scan-screenshot), [DOM](https://developers.cloudflare.com/api/operations/urlscanner-get-scan
```suggestion
In order to fetch the scan's [screenshots](/api/operations/urlscanner-get-scan-screenshot), [DOM](/api/operations/urlscanner-get-scan-dom) and full [network log](/api/operations/urlscanner-get-scan-har), please visit the corresponding endpoints' documentation.
```

2023-07-07 15:33 UTC, meddulla commented on content/radar/investigate/url-scanner.md
> +- `verdicts.overall.malicious` - Whether the website was considered, _at the time of the scan_, malicious. Please check the remaining properties for each subsystem(s) specific threats detected.
Would prefer to leave the "at the time" highlighted as I suspect this will become an issue (a site is considered malicious erroneously or they changed the site since then, so it should no longer be considered so.

2023-07-07 15:36 UTC, meddulla commented on content/radar/investigate/url-scanner.md
> +Of those above, here are some highlights:
These aren't really responses but fields or properties in the response. Would be fine with "Some examples of more specific properties include"

2023-07-07 15:41 UTC, meddulla commented on content/radar/investigate/url-scanner.md
> +While the scan is in progress, the HTTP status code will be `202`, once it's finished it will be `200`. Clients are advised to poll every 10-30 seconds.
"polling" is a loaded tech word which basically means "the process of repeatedly sampling the status of external devices by a client program.". Actually prefer the original line because of this but ok with your suggestion.

2023-07-13 13:50 UTC, haleycode approved these changes

2023-07-13 13:57 UTC, merged