Update links of cipher suites restriction
cloudflare/cloudflare-docs pull request #9734
Opened 2023-07-05 17:15 UTC by cicku

2023-07-05 17:25 UTC, ngayerie requested changes

2023-07-05 17:25 UTC, ngayerie commented on content/support/SSL TLS/Edge Certificates SSL TLS configuration/Disabling Weak Cipher Suites.md
> +Cipher suites has to be disabled when you have [Advanced Certificate Manager](/ssl/edge-certificates/advanced-certificate-manager) purchased. After you subscribed to Advance Certificate Manager for y
I assume you meant "Cipher suites can only be disabled" here?

2023-07-05 17:25 UTC, ngayerie commented on content/support/SSL TLS/Edge Certificates SSL TLS configuration/Disabling Weak Cipher Suites.md
> +1.  [Get/view Global API Key _(or create Token)_](/fundamentals/api/get-started/keys/)
The link to the Dashboard is correct, I think it makes sense to keep it?

2023-07-05 17:25 UTC, ngayerie commented on content/support/SSL TLS/Edge Certificates SSL TLS configuration/Disabling Weak Cipher Suites.md
> +Cipher suites has to be disabled when you have [Advanced Certificate Manager](/ssl/edge-certificates/advanced-certificate-manager) purchased. After you subscribed to Advance Certificate Manager for y
Advance Certificate Manager
-> 
Advanced Certificate Manager

2023-07-05 17:27 UTC, cicku commented on content/support/SSL TLS/Edge Certificates SSL TLS configuration/Disabling Weak Cipher Suites.md
> +1.  [Get/view Global API Key _(or create Token)_](/fundamentals/api/get-started/keys/)
Doc refs always have higher priority than actual URLs.

2023-07-05 17:32 UTC, cicku commented on content/support/SSL TLS/Edge Certificates SSL TLS configuration/Disabling Weak Cipher Suites.md
> +Cipher suites has to be disabled when you have [Advanced Certificate Manager](/ssl/edge-certificates/advanced-certificate-manager) purchased. After you subscribed to Advance Certificate Manager for y
Fixed

2023-07-06 09:51 UTC, ngayerie requested changes

2023-07-06 09:51 UTC, ngayerie commented on content/support/SSL TLS/Edge Certificates SSL TLS configuration/Disabling Weak Cipher Suites.md
> +Cipher suites has to be disabled when you have [Advanced Certificate Manager](/ssl/edge-certificates/advanced-certificate-manager) purchased. After you have subscribed to Advanced Certificate Manager
"Cipher suites has to be disabled when you" 
This needs to be updated

2023-07-31 16:52 UTC, closed without merging