fix: add a note about de-pagination with prefix
cloudflare/cloudflare-docs pull request #9782
Opened 2023-07-08 06:57 UTC by barabo

For context: https://community.cloudflare.com/t/kv-list-with-prefix-includes-mismatches-when-paginating/516969/4

2023-07-14 16:23 UTC, Maddy-Cloudflare approved these changes

2023-07-14 16:23 UTC, Maddy-Cloudflare commented on content/workers/runtime-apis/kv.md
> +Also note than when de-paginating a large result set while also providing a `prefix` argument, the `prefix` argument must be provided in all subsequent calls along with the initial arguments.
```suggestion
The `prefix` argument must be provided in all subsequent calls along with the initial arguments when de-paginating a large result set while also providing a `prefix` argument.
```

2023-07-28 05:52 UTC, barabo commented
Friendly ping.  The `Compiles` check has been stuck in 'Waiting' for 2 weeks.  :-)

2023-07-28 16:27 UTC, vlovich approved these changes

2023-07-28 17:09 UTC, CharlieBurnett requested changes

2023-07-28 17:09 UTC, CharlieBurnett commented on content/workers/runtime-apis/kv.md
> +The `prefix` argument must be provided in all subsequent calls along with the initial arguments when de-paginating a large result set while also providing a `prefix` argument.
Lets break it up so its easier to read. Right now this is a run-on sentence that's hard to parse out.

"When de-paginating a large result set while also providing a `prefix` argument, The `prefix` argument must be provided in all subsequent calls along with the initial arguments"

2023-07-28 17:15 UTC, CharlieBurnett approved these changes

2023-07-31 14:53 UTC, merged