Update radar glossary ddos entries
cloudflare/cloudflare-docs pull request #9811
Opened 2023-07-11 17:34 UTC by vasturiano

2023-07-11 17:45 UTC, meddulla approved these changes

2023-07-13 13:54 UTC, haleycode requested changes

2023-07-13 13:54 UTC, haleycode commented on content/radar/glossary.md
> +Layer 7 attack information based on mitigated requests. Including the most frequent mitigation techniques as well as trending of mitigated request volume over time. Selected location or ASN is the so
```suggestion
Layer 7 attack information based on mitigated requests, including the most frequent mitigation techniques as well as the trend of mitigated request volume over time. Selected location or ASN is the source of the mitigated requests.
```

2023-07-13 21:37 UTC, haleycode approved these changes

2023-07-13 21:37 UTC, merged