d1: add Time Travel documentation
cloudflare/cloudflare-docs pull request #9833
Opened 2023-07-12 16:25 UTC by elithrar

DRAFT

This PR:

- [ ] Adds new documentation for Time Travel
- [ ] Updates the wrangler docs to detail the `wrangler d1 time-travel` commands: https://developers.cloudflare.com/workers/wrangler/commands/#d1
- [x] Adds a /d1/changelog entry for Time Travel
- [ ] Updates the existing Backups documentation to reference Time Travel for new databases

2023-07-14 09:46 UTC, Maddy-Cloudflare requested changes
Will need to review this again once it's finished.

2023-07-14 09:46 UTC, Maddy-Cloudflare commented on content/d1/changelog.md
> +[Time Travel](/d1/learning/time-travel/) is now available. Time Travel allows you to restore a D1 database back to any minute within the last 30 days (Workers paid plans) or 7 days (Workers free plan
```suggestion
[Time Travel](/d1/learning/time-travel/) is now available. Time Travel allows you to restore a D1 database back to any minute within the last 30 days (Workers Paid plan) or 7 days (Workers Free plan), at no additional cost for storage or restore operations.
```

2023-07-14 09:46 UTC, Maddy-Cloudflare commented on content/d1/learning/time-travel.md
> +* You do not need to enable Time Travel: it is always on.
```suggestion
* You do not need to enable Time Travel. It is always on.
```

2023-07-14 09:46 UTC, Maddy-Cloudflare commented on content/d1/learning/time-travel.md
> +* Time Travel automatically creates [bookmarks](#terminology) on your behalf: you do not need to manually trigger or remember to initiate a backup.
```suggestion
* Time Travel automatically creates [bookmarks](#terminology) on your behalf. You do not need to manually trigger or remember to initiate a backup.
```

2023-07-14 09:46 UTC, Maddy-Cloudflare commented on content/d1/learning/time-travel.md
> +Time Travel introduces the concept of a "bookmark" to D1: a bookmark represents the state of a database at a specific point in time, and is effectively an append-only log.
```suggestion
Time Travel introduces the concept of a "bookmark" to D1. A bookmark represents the state of a database at a specific point in time, and is effectively an append-only log.
```

2023-07-14 09:46 UTC, Maddy-Cloudflare commented on content/d1/learning/time-travel.md
> +title: Time Travel & Backups
```suggestion
title: Time Travel and backups
```

2023-07-14 09:46 UTC, Maddy-Cloudflare commented on content/d1/learning/time-travel.md
> +* Queries in flight will be cancelled, and an error returned to the client
```suggestion
* Queries in flight will be cancelled, and an error returned to the client.
```

2023-07-14 09:46 UTC, Maddy-Cloudflare commented on content/d1/learning/time-travel.md
> +* Taking note of the previous bookmark returned as part of a `wrangler d1 restore` operation
```suggestion
* Taking note of the previous bookmark returned as part of a `wrangler d1 restore` operation.
```

2023-07-14 09:46 UTC, Maddy-Cloudflare commented on content/d1/learning/time-travel.md
> +* You can quickly get the Unix timestamp from the command-line in macOS and Windows via `date %+s`
```suggestion
* You can quickly get the Unix timestamp from the command-line in macOS and Windows via `date %+s`.
```

2023-07-14 09:46 UTC, Maddy-Cloudflare commented on content/d1/learning/time-travel.md
> +To restore a database a specific point-in-time:
```suggestion
To restore a database to a specific point-in-time:
```

2023-07-14 09:46 UTC, Maddy-Cloudflare commented on content/d1/learning/time-travel.md
> +* Restore directly to a bookmark in the past, prior to your last restore.
```suggestion
* Restoring directly to a bookmark in the past, prior to your last restore.
```

2023-07-14 09:46 UTC, Maddy-Cloudflare commented on content/d1/changelog.md
> +Refer to the [Time Travel documentation](/d1/learning/time-travel/) to learn how to travel backwards in time.
```suggestion
Refer to the [Time Travel](/d1/learning/time-travel/) documentation to learn how to travel backwards in time.
```

2023-07-14 09:46 UTC, Maddy-Cloudflare commented on content/d1/learning/time-travel.md
> +* Bookmarks are lexicographically sortable: sorting a list of bookmarks will order them from oldest-to-newest
```suggestion
* Bookmarks are lexicographically sortable. Sorting orders a list of bookmarks from oldest-to-newest.
```

2023-07-27 15:26 UTC, elithrar commented
@Maddy-Cloudflare - ready for final review!

2023-07-27 15:42 UTC, rozenmd commented on content/workers/wrangler/commands.md
> +  - ...
these `...` should probably have more info, but can iterate on it

2023-07-27 15:43 UTC, rozenmd approved these changes
LGTM apart from the `...`s in `workers/wrangler/commands.md`, but can fix 'em later

2023-07-27 16:28 UTC, Maddy-Cloudflare approved these changes

2023-07-27 16:30 UTC, Maddy-Cloudflare requested changes

2023-07-27 16:30 UTC, Maddy-Cloudflare commented on content/workers/wrangler/commands.md
> +  - ...
@elithrar are you planning on adding more information here?

2023-07-27 16:31 UTC, elithrar commented on content/workers/wrangler/commands.md
> +  - ...
Fixed both.

2023-07-27 17:37 UTC, Maddy-Cloudflare approved these changes

2023-07-27 17:37 UTC, Maddy-Cloudflare commented on content/workers/wrangler/commands.md
> +  - A Unix timestamp or JavaScript date-time string within the last 30 days.
```suggestion
  - A Unix timestamp or JavaScript date-time `string` within the last 30 days.
```

2023-07-27 17:37 UTC, Maddy-Cloudflare commented on content/workers/wrangler/commands.md
> +  - A Unix timestamp or JavaScript date-time string within the last 30 days.
```suggestion
  - A Unix timestamp or JavaScript date-time `string` within the last 30 days.
```

2023-07-27 17:37 UTC, Maddy-Cloudflare commented on content/d1/learning/time-travel.md
> +* You can restore a database back to a point in time up to 30 days in the past (Workers Paid plans) or 7 days (Workers free plans). See the [Limits](/d1/platform/limits/) page for details on Time Tra
```suggestion
* You can restore a database back to a point in time up to 30 days in the past (Workers Paid plan) or 7 days (Workers Free plan). See the [Limits](/d1/platform/limits/) page for details on Time Travel's limits.
```

2023-07-27 17:37 UTC, Maddy-Cloudflare commented on content/d1/learning/time-travel.md
> +To fetch a bookmark from an earlier state
```suggestion
To fetch a bookmark from an earlier state:
```

2023-07-27 17:54 UTC, merged