Radar: added sharing/embed instructions
cloudflare/cloudflare-docs pull request #9843
Opened 2023-07-13 12:21 UTC by tiagoad

2023-07-13 14:07 UTC, haleycode commented
@tiagoad Please remove the screenshot. We try to make sure never to include screenshots unless it's critical for user understanding, due to how difficult it is to maintain screenshots over time.

2023-07-13 14:16 UTC, tiagoad commented
> @tiagoad Please remove the screenshot. We try to make sure never to include screenshots unless it's critical for user understanding, due to how difficult it is to maintain screenshots over time.

Understood. It's removed now

2023-07-19 22:09 UTC, haleycode requested changes

2023-07-19 22:09 UTC, haleycode commented on content/radar/get-started/embed.md
> +Radar allows you to download an image of a chart, as well as to embed interactive cards of most charts into your own webpages.
```suggestion
Radar allows you to download an image of a chart, as well as embed interactive cards of most charts into your own web pages.
```

2023-07-19 22:09 UTC, haleycode commented on content/radar/get-started/embed.md
> +3. Done! Your browser will download the .png file containing the requested chart
```suggestion
1. Select the Share icon next to the description of the chart you wish to share.
2. Select `Download Image.`
3. A .png file containing the requested chart will be downloaded.
```

2023-07-19 22:09 UTC, haleycode commented on content/radar/get-started/embed.md
> +3. Copy the HTML to your page
```suggestion
1. Select the Share icon next to the description of the chart you wish to share.
2. Select between Fixed Time and Real Time.
   - Real Time uses a “sliding window” based on the selected date range, and will display data points looking back over that duration from the current date/time.
   - Fixed Time will always display a chart with only the currently visible data points.
3. Select Copy Code and paste the code into your web page.
```

2023-07-24 15:59 UTC, haleycode approved these changes

2023-08-01 14:18 UTC, merged