[Workers KV] Create advanced-kv-guide.md
cloudflare/cloudflare-docs pull request #9874
Opened 2023-07-14 17:57 UTC by vlovich

Write up tips and tricks that might be relevant to advanced users.

2023-07-14 19:14 UTC, elithrar requested changes

2023-07-14 19:14 UTC, elithrar commented on content/workers/learning/advanced-kv-guide.md
> +To optimize the long-tail performance of infrequently accessed keys, specify a longer cacheTtl value (e.g. 1 day).
Since this is the first mention of `cacheTtl` in this document, you should have a brief explainer - 1-2 sentences tops - that also cross-links to https://developers.cloudflare.com/workers/runtime-apis/kv/#cache-ttl

e.g.

```
KV allows you to set a `cacheTtl` when reading a value, which <...>. Setting a sensible `cacheTtl` value can dramatically improve overall performance.
```

2023-07-14 19:14 UTC, elithrar commented on content/workers/learning/advanced-kv-guide.md
> +# Background
```suggestion
# Best practices for Workers KV
```

2023-07-14 19:14 UTC, elithrar commented on content/workers/learning/advanced-kv-guide.md
> +To get the best possible performance out of your usage of Workers KV, this document contains some tips.
Be more precise - this intro should effectively summarize the rest of the doc.

```suggestion
[Workers KV](https://developers.cloudflare.com/workers/learning/how-kv-works/) is a low-latency key-value store optimized for extremely high read throughput.

This guide provides additional advice and best practices for using KV, including:

* Improving cache hit performance through the [`cacheTtl`](/workers/runtime-apis/kv/#cache-ttl) API
* Avoiding use of additional, redundant caching layers, which can make it harder to maintain key-value freshness
* Using Workers KV's [bindings API](/workers/platform/bindings/#kv-namespace-bindings) instead of its administrative REST APIs for user-facing workloads.
```

2023-07-14 19:14 UTC, elithrar commented on content/workers/learning/advanced-kv-guide.md
> +coalescing them.
Explain what this is to a reader in a (brief) sentence. e.g. - "Coalescing refers to <...>"

2023-07-14 19:44 UTC, mhart commented on content/workers/learning/advanced-kv-guide.md
> +## Batch reading multiple keys
Neat trick! But it only applies to keys stored adjacently in lexicographic order right?

2023-07-14 19:44 UTC, mhart commented on content/workers/learning/advanced-kv-guide.md
> +## Batch reading multiple keys
Like `Batch reading multiple keys with the same prefix` or something

2023-07-14 20:03 UTC, vlovich commented on content/workers/learning/advanced-kv-guide.md
> +## Batch reading multiple keys
Yes, did I not mention it?

2023-07-14 22:47 UTC, vlovich commented on content/workers/learning/how-kv-works.md
>  ![Your data is written to central data stores when you write to KV.](/images/workers/kv-write.svg)
@CharlieBurnett / @elithrar the assets on this page need to be updated to align with https://blog.cloudflare.com/faster-workers-kv-architecture/. I'd update them to what's on the blog, but the blog post has PNGs and these are SVGs.

2023-07-14 23:09 UTC, KianNH commented on content/workers/learning/advanced-kv-guide.md
> +As background, it's best to review [how KV works](/workers/learning/how-kv-works.md) before reading this document.
```suggestion
As background, it's best to review [how KV works](/workers/learning/how-kv-works/) before reading this document.
```

2023-07-17 16:09 UTC, Maddy-Cloudflare requested changes
Needs a better structure.

2023-07-17 23:51 UTC, CharlieBurnett commented
@vlovich reading through this, _great_ content, it reads as if it was a document we should've always had. I'm glad we're finally writing this.

@Maddy-Cloudflare wants to break into sections to make it a bit more readable. I agree, but feel that the current proposed sections dont present topically different information. Please work with her to improve the information design to make it a bit more digestable

Only critique is we should probably discuss "How to get early access to get sub 1 minute consistency latency." as a team and with our leadership before bringing to our customers. Lets split that out into a separate commit once we align there

2023-07-17 23:54 UTC, CharlieBurnett commented on content/workers/learning/how-kv-works.md
>  ![Your data is written to central data stores when you write to KV.](/images/workers/kv-write.svg)
@vlovich do we feel we can pull the assets directly from the blog post or want me to work with Lyla to get some new assets for the docs?

2023-07-17 23:57 UTC, CharlieBurnett requested changes
Lets remove this until we have a robust conversation around how this feature will work for customers

2023-07-17 23:57 UTC, CharlieBurnett commented on content/workers/learning/advanced-kv-guide.md
> +* How to get early access to get sub 1 minute consistency latency.
```suggestion
```

2023-07-20 17:08 UTC, Maddy-Cloudflare commented on content/workers/learning/advanced-kv-guide.md
> +When KV encounters a key beyond it's `cacheTTL`, this is treated as a miss and requires traversal to the central data center containing the most
```suggestion
When KV encounters a key beyond it's `cacheTTL`, this is treated as a miss and requires traversal to the central data center containing the most
```

2023-07-28 16:24 UTC, vlovich commented on content/workers/learning/how-kv-works.md
>  ![Your data is written to central data stores when you write to KV.](/images/workers/kv-write.svg)
I think that's a stylistic choice someone else needs to make. We probably do want whatever we choose to be consistent with "how kv works" diagrams as well (if we want to use the one from the blog post, then updating assets we should use there).

2023-07-28 16:25 UTC, vlovich commented
@Maddy-Cloudflare please feel free to make whatever structural changes are needed & update this PR.

2024-04-30 15:44 UTC, kodster28 commented
Closing this PR out externally... but moving to an internal ticket for tracking and prioritization.

PCX-10697 for reference.

2024-04-30 15:44 UTC, closed without merging