Clarify the fields that is available only for Bot Mgmt Ent customer (Botxxx, JA3)
cloudflare/cloudflare-docs pull request #9911
Opened 2023-07-18 02:59 UTC by kyouheicf

2023-07-18 09:33 UTC, angelampcosta commented
Hi @kyouheicf The log field files are Code generated by logshare-api. They cannot be edited directly in Github. Just to confirm, did you do that update first?

2023-07-24 05:35 UTC, kyouheicf commented
@pedrosousa Can you help move this forward as we did the previous one?
https://github.com/cloudflare/cloudflare-docs/pull/8504

2023-07-28 18:45 UTC, soheiokamoto approved these changes

2023-07-28 18:50 UTC, soheiokamoto requested changes
The descriptions are slightly different than the changes made at the source repo.
Please update this PR to match them.

2023-07-28 21:38 UTC, angelampcosta commented on content/logs/reference/log-fields/zone/http_requests.md
> +| BotDetectionIDs | List of IDs that correlate to the Bot Management Heuristic detections made on a request. Available in Logpush v2 only. Available only for Bot Management customers (please contact
```suggestion
| BotDetectionIDs | List of IDs that correlate to the Bot Management Heuristic detections made on a request. Available in Logpush v2 only. Available only for Bot Management customers. To enable this feature, contact your account team. | array[int] |
```

2023-07-28 21:38 UTC, angelampcosta commented on content/logs/reference/log-fields/zone/http_requests.md
> +| BotScoreSrc | Detection engine responsible for generating the Bot Score. <br />Possible values are <em>Not Computed</em> \| <em>Heuristics</em> \| <em>Machine Learning</em> \| <em>Behavioral Analys
```suggestion
| BotScoreSrc | Detection engine responsible for generating the Bot Score. <br />Possible values are <em>Not Computed</em> \| <em>Heuristics</em> \| <em>Machine Learning</em> \| <em>Behavioral Analysis</em> \| <em>Verified Bot</em> \| <em>JS Fingerprinting</em> \| <em>Cloudflare Service</em>. Available only for Bot Management customers. To enable this feature, contact your account team. | string |
```

2023-07-28 21:38 UTC, angelampcosta commented on content/logs/reference/log-fields/zone/http_requests.md
> +| BotTags | Type of bot traffic (if available). Refer to [Bot Tags](/bots/concepts/cloudflare-bot-tags/) for the list of potential values. Available in Logpush v2 only. Available only for Bot Managem
```suggestion
| BotTags | Type of bot traffic (if available). Refer to [Bot Tags](/bots/concepts/cloudflare-bot-tags/) for the list of potential values. Available in Logpush v2 only. Available only for Bot Management customers. To enable this feature, contact your account team. | array[string] |
```

2023-07-28 21:38 UTC, angelampcosta commented on content/logs/reference/log-fields/zone/http_requests.md
> +| BotScore | Cloudflare Bot Score. Scores below 30 are commonly associated with automated traffic. Available only for Bot Management customers (please contact your account team to enable). | int |
```suggestion
| BotScore | Cloudflare Bot Score. Scores below 30 are commonly associated with automated traffic. Available only for Bot Management customers. To enable this feature, contact your account team. | int |
```

2023-07-28 21:38 UTC, angelampcosta commented on content/logs/reference/log-fields/zone/http_requests.md
> +| JA3Hash | The MD5 hash of the JA3 fingerprint used to profile SSL/TLS clients. Available in Logpush v2 only. Available only for Bot Management customers (please contact your account team to enable)
```suggestion
| JA3Hash | The MD5 hash of the JA3 fingerprint used to profile SSL/TLS clients. Available in Logpush v2 only. Available only for Bot Management customers. To enable this feature, contact your account team. | string |
```

2023-07-28 23:26 UTC, soheiokamoto approved these changes

2023-07-31 08:35 UTC, merged