Add info in required permissions for mTLS cert upload
cloudflare/cloudflare-docs pull request #9918
Opened 2023-07-18 15:09 UTC by markdembo

Add warning for required permissions

2023-07-18 15:12 UTC, deadlypants1973 requested changes
PCX

2023-07-18 15:12 UTC, deadlypants1973 commented on content/workers/runtime-apis/mTLS.md
> +This command requires "Account: SSL and Certificates" write permissions.
```suggestion
The `wrangler mtls-certificate upload` command requires Account: SSL and Certificates write permissions.
```
Are there instructions for how to establish this "Account: SSL and Certificates write permissions"? If something is necessary, there should be followup guidance on how to accomplish it.

2023-07-19 07:07 UTC, markdembo commented on content/workers/runtime-apis/mTLS.md
> +This command requires "Account: SSL and Certificates" write permissions.
Added further instructions.

2023-07-19 12:26 UTC, samirbani commented
في الأربعاء، ١٩ يوليو ٢٠٢٣ ١٠:٠٨ ص Mark Dembo ***@***.***>
كتب:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In content/workers/runtime-apis/mTLS.md
> <https://github.com/cloudflare/cloudflare-docs/pull/9918#discussion_r1267629817>
> :
>
> > @@ -19,6 +19,12 @@ Currently, mTLS for Workers is not supported for domains [proxied](/dns/manage-d
>
>  First, upload a certificate and its private key to your account using the [`wrangler mtls-certificate`](/workers/wrangler/commands/#mtls-certificate) command:
>
> +{{<Aside type="warning">}}
> +
> +This command requires "Account: SSL and Certificates" write permissions.
>
> Added further instructions.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/cloudflare/cloudflare-docs/pull/9918#discussion_r1267629817>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AWV6NCQPDUH4JJWY6SBXVUTXQ6BVJANCNFSM6AAAAAA2ORSOCQ>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2023-07-19 15:48 UTC, deadlypants1973 approved these changes
PCX approved with suggestion

2023-07-19 15:48 UTC, deadlypants1973 commented on content/workers/runtime-apis/mTLS.md
> +The `wrangler mtls-certificate upload` command requires ["SSL and Certificates Edit"](https://developers.cloudflare.com/fundamentals/api/reference/permissions/) API token scope. If your are using the
```suggestion
The `wrangler mtls-certificate upload` command requires the [SSL and Certificates Edit API token scope](/fundamentals/api/reference/permissions/). If you are using the OAuth flow triggered by  `wrangler login`, the correct scope is set automatically. If you are using API tokens, refer to [Create an API token](https://developers.cloudflare.com/fundamentals/api/get-started/create-token/) to set the right scope for your API token.
```

2023-09-11 15:26 UTC, merged