Add explanation of industry and verticals to Radar glossary
cloudflare/cloudflare-docs pull request #9952
Opened 2023-07-19 15:06 UTC by vasturiano

2023-07-20 17:05 UTC, haleycode requested changes

2023-07-20 17:05 UTC, haleycode commented on content/radar/glossary.md
> +Industry categories include businesses connected through their primary activities, such as Information Technology and Services, Retail, or Telecommunications, while vertical categories are high-level
```suggestion
Industry categories include business types grouped by their primary activities, such as information technology and services, retail, or telecommunications. Vertical categories are high-level groupings that incorporate related industries, such as the "Internet and Telecom" vertical, which includes industries such as "Internet" and "Telecommunications".
```

2023-07-20 17:05 UTC, haleycode commented on content/radar/glossary.md
> +Industry categories include businesses connected through their primary activities, such as Information Technology and Services, Retail, or Telecommunications, while vertical categories are high-level
This might benefit from a bit more detail. I'm not sure I understand how we're defining "primary activities" and how that differs from industry verticals.

2023-07-21 20:20 UTC, meddulla approved these changes

2023-07-24 16:00 UTC, haleycode approved these changes

2023-08-01 14:19 UTC, merged