Update enable.md
cloudflare/cloudflare-docs pull request #9970
Opened 2023-07-20 12:48 UTC by AlphaK5

PCX-6387

2023-07-20 14:56 UTC, garrettgalow approved these changes

2023-07-20 16:14 UTC, garrettgalow commented
based on internal discussion we should add a warning to this that disabling zone versioning will revert your zone configuration to what is configured in version 0 immediately. Ensuring version 0 has the correct settings first is necessary

2023-07-20 16:14 UTC, garrettgalow requested changes
see previous comment

2023-07-26 14:00 UTC, kodster28 commented
Addressed in another PR.

2023-07-26 14:00 UTC, closed without merging