Update Gathering information for troubleshooting sites.md
cloudflare/cloudflare-docs pull request #9981
Opened 2023-07-20 18:32 UTC by lindsey-em

Fixing the page formatting that was broken in migration

I've included an empty header `###` inside each `<details>` section because it was was the only way I was able to get a space between the `<summary> and the content.

2023-07-20 19:22 UTC, kodster28 commented on content/support/Troubleshooting/General Troubleshooting/Gathering information for troubleshooting sites.md
> +  ![HAR network tab screenshot from Chrome developer tools](/assets/images/support/gathering_har_file_network.png)
Should just be `/images/support/` and then they'll resolve correctly.

Also, fwiw, direct headers are usually better than dropdowns for search crawlers (google / algolia, etc).

2023-07-20 19:24 UTC, kodster28 requested changes
Should just be `/images/support/` and then they'll resolve correctly.

Also, not sure I love shoving empty header tags on our pages. Maybe go with `<br/>` instead? All headers gets picked up by search crawlers (google / algolia) and might lead to not so ideal results.

Finally, you should remove the `/` from the numbers so the lists render correctly.

2023-07-21 08:53 UTC, pedrosousa commented
> I've included an empty header `###` inside each `<details>` section because it was was the only way I was able to get a space between the `<summary>` and the content.

No need to use a hack — actually, you're missing an internal `div`. The full syntax is the following (without the `+` signs):

```diff
  <details>
  <summary>Summary here</summary>
+ <div>

  ( content here )

+ </div>
  </details>
```

If you have questions, please ask someone or check how it's being handled elsewhere.

2023-08-22 11:15 UTC, lindsey-em commented
Quick question on this: 

`Should just be /images/support/ and then they'll resolve correctly.`

I added the /assets/ part of the uri because for me the images weren't loading in the preview. Is that expected behavior then?

2023-08-28 14:23 UTC, kodster28 commented
I just tested and I'm confused what behavior you're seeing.

All the images rendered correctly without `/assets` in the url path.

2023-09-05 14:52 UTC, zeinjaber commented
@lindsey-em, have you addressed @pedrosousa's comment?

2023-09-06 10:57 UTC, lindsey-em commented
I am prioritizing it right now!

2023-09-06 14:00 UTC, lindsey-em commented
Spell check fail is a false inclusive language failure, but I don't know about the GitGuardian one. I just removed backslashes after numbered lists on those files

2023-09-06 14:29 UTC, pedrosousa commented
No need to worry about Git Guardian. It's an old false positive that got triggered when you merged production to this PR's branch.

2023-09-06 15:07 UTC, kodster28 commented
Closing this b/c the git history is pulling in a lot more changes. Think it got messed up when you merged in production.

2023-09-06 15:07 UTC, closed without merging

2023-09-06 15:12 UTC, lindsey-em commented
It was intentional, but I can make a new PR with a newly defined scope - I fixed all instances of numbering like

1\.
2\.
3\.

in the docs, after seeing the correction made here