[D1]: Add Foreign Key documentation
cloudflare/cloudflare-docs pull request #9984
Opened 2023-07-20 20:28 UTC by elithrar

Work in progress.

This PR adds:

- [ ] New Foreign Key documentation covering how FKs are enforced and how to defer enforcement
- [ ] How to use FK actions to cascade (or not) deletes/updates
- [ ] A new changelog entry

2023-07-21 09:51 UTC, Maddy-Cloudflare requested changes
Will need to review this again once complete.

2023-07-21 09:51 UTC, Maddy-Cloudflare commented on content/d1/changelog.md
> +Databases using D1's new experimental backend now have [foreign key constraints](/d1/learning/foreign-keys/) enforced by default. Foreign key constraints allow you to enforce relationships across tab
```suggestion
Databases using D1's new experimental backend now have [foreign key constraints](/d1/learning/foreign-keys/) enforced by default. Foreign key constraints allow you to enforce relationships across tables. For example, creating a strict binding between a `user_id` in a `users` table and the `user_id` in an `orders` table, so that no order can be created against a user that does not exist.
```

2023-07-21 09:51 UTC, Maddy-Cloudflare commented on content/d1/learning/foreign-keys.md
> +D1 has a new experimental storage back-end that dramatically improves query throughput, latency and reliability. The experimental back-end will become the default back-end for all new D1 databases in
```suggestion
D1 has a new experimental storage back-end that improves query throughput, latency and reliability. The experimental back-end will become the default back-end for all new D1 databases in the near future.
```

2023-07-21 09:51 UTC, Maddy-Cloudflare commented on content/d1/learning/foreign-keys.md
> +* A `users` table that defines common properties about a user account, including a unique `user_id` identifier
```suggestion
* A `users` table that defines common properties about a user account, including a unique `user_id` identifier.
```

2023-07-21 09:51 UTC, Maddy-Cloudflare commented on content/d1/learning/foreign-keys.md
> +## Updating or deleting rows
```suggestion
## Update or delete rows
```

2023-07-21 09:51 UTC, Maddy-Cloudflare commented on content/d1/platform/migrations.md
> +## Applying migrations
```suggestion
## Apply migrations
```

2023-08-18 13:20 UTC, Maddy-Cloudflare requested changes
Will check this again once completed

2023-08-18 13:20 UTC, Maddy-Cloudflare commented on content/d1/learning/foreign-keys.md
> +## Relax foreign key constraints
```suggestion
## Disable foreign key constraints
```

2024-03-31 21:46 UTC, elithrar commented
Closure because this is blocked on @Maddy-Cloudflare who is OOO

2024-03-31 21:46 UTC, closed without merging