Issue 9995: adding known issue description for WARP + Docker on Linux…
cloudflare/cloudflare-docs pull request #9998
Opened 2023-07-21 14:01 UTC by cdrubin

Issue 9995: adding known issue description for WARP + Docker on Linux relating to mtu size

[Issue 9995](https://github.com/cloudflare/cloudflare-docs/issues/9995)

Updates to WARP known issues and link from WARP Client to the same list of limitations

2023-08-07 20:47 UTC, ranbel commented on content/warp-client/known-issues-and-faq.md
> +- See [Known Limitations](/cloudflare-one/connections/connect-devices/warp/troubleshooting/known-limitations/)
```suggestion
- Refer to [Known Limitations](/cloudflare-one/connections/connect-devices/warp/troubleshooting/known-limitations/)
```

2023-08-07 20:53 UTC, ranbel commented
Hi @cdrubin, thanks for opening this PR! Let me know if the copy-edits look ok to you and I will merge it in.

2023-08-08 10:58 UTC, thibault-ml requested changes

2023-08-08 10:58 UTC, thibault-ml commented on content/cloudflare-one/connections/connect-devices/warp/troubleshooting/known-limitations.md
> +
We should add a comment saying that while we have used 1420 as the MTU value in those examples, the actual value people should use will depend on the MTU on the host's main interface. Most MTUs are 1500, and therefore 1420 should work for most people.

But we should explain that the value to use for Docker is basically the host's main interface MTU minus 80 bytes for the WARP protocol overhead.

2023-08-09 23:01 UTC, thibault-ml approved these changes

2023-08-10 14:12 UTC, ranbel approved these changes

2023-08-10 14:12 UTC, merged